### ISSUE TITLE
Find out how the motors are working

### ISSUE THREAD

**Issue by EliasKotlyar** [EliasKotlyar/Xiaomi-Dafang-Hacks#1]
For using the Pan/Tilt Functionality , we need to find out how the motors can be used.

I suppose that they are wired really similar to the reference implementation of the "Bull Board":
https://github.com/dim08/Ingenic-T10_20/blob/master/hardware/RD_T20_BULL_V10_20160912B.pdf

There is a "motor"-Driver(sample_motor.ko), but nobody knows how to use it. It has the following parameters:
hmaxstep = 2600
hmotor2vmotor = 1
vmaxstep = 700

Unfrotunately, i dont know how to use it. There is no documentation about using it.

**Comment by BugSyst3m** [comment]
My guess is that the two motors are namec h and v, and the commands should look like something like this: 
hsetTargetAbs(pos + 100)
hsetTargetRel(100)
move(h, True, 0x100)
hstop()
etc...

**Comment by EliasKotlyar** [comment]
Yeah, i suppose that everything is similar to the reference design. I would love to use that driver instead of writing the code. Any ideas on that? Anyone?

**Comment by BugSyst3m** [comment]
Have you tried random commands like
h.settarget(100)
move(h,true,100)
h.stop()
Etc...

**Comment by EliasKotlyar** [comment]
I dont think that is possible - you cannot send "any commands". You need proper headers for doing that.

I have extracted all the strings of the sample_motor.ko:
`}E!@
$!0@
$! @
$! @
<! @
<! @
<! @
 br0
$! @
<! @
$! @
<! @
<! @
<!  
<! @
<! @
$!0@
c$* 
$!(@
'!(@
>r! `
'!(@
'!(@
$! @
4!  
r&! 
r&! 
motor_ioctl
motor_ops_reset
	hmotor2vmotor
Motor driver busy now!
kzalloc motor device memery error
Failed to get mfd cell for jz_adc_aux!
&mdev->dev_mutex
&x->wait
motor_min_gpio
request motor_min_gpio error
motor_max_gpio
request motor_max_gpio error
motor_st1_gpio
motor_st2_gpio
motor_st3_gpio
motor_st4_gpio
Failed to get platform irq: %d
jz_timer_interrupt
Failed to run request_irq() !
motor
misc_register failed
create dev_attr_isp_info failed!
motor_info
the reset of counter is not finished now
Please Open /dev/motor Firstly
[%s][%d] copy from user error
include/linux/kernel.h
ERROR: the parameters of %s is wrong!!
ERROR:wait motor timeout %s%d
[%s][%d] copy to user error
speed(%d) set error
opened
closed
running
stop
The version of Motor driver is %s
H20170908a
Motor driver is %s
The max speed is %d and the min speed is %d
The status of motor is %s
The pos of motor is (%d, %d)
The speed of motor is %d
## motor is %s ##
max steps %d
motor direction %d
motor state %d(normal; cruise; reset)
the irq's counter of max pos is %d
the irq's counter of min pos is %d
tcu_chn2
license=GPL
parm=hmotor2vmotor:The value is hmotor's speed / vmotor's
parmtype=hmotor2vmotor:int
depends=
vermagic=3.10.14 preempt mod_unload MIPS32_R1 32BIT 
Horizontal motor
Vertical motor
sample_motor
GCC: (Ingenic r2.3.3 2016.12) 4.7.2
GCC: (Ingenic r2.3.3 2016.12) 4.7.2
.symtab
.strtab
.shstrtab
.note.gnu.build-id
.rel.text
.rel.init.text
.rel.exit.text
.reginfo
.rel.rodata
.rodata.str1.4
.modinfo
.rel__param
.rel.data
.rel.gnu.linkonce.this_module
.sbss
.bss
.comment
.rel.pdr
.gnu.attributes
.mdebug.abi32
motor.c
motor_remove
motor_open
motor_info_open
motor_info_show
motor_ops_move
skip_move_mode
motor_ops_goback
motor_set_default
motor_probe
__key.23055
__key.5765
motor_min_gpio_interrupt
motor_max_gpio_interrupt
gpio_keys_min_timer
gpio_keys_max_timer
jz_timer_interrupt
motor_fops
motor_info_fops
motor_move_step
step_8
hmotor2vmotor
motor_ops_stop.part.2
motor_ioctl
__func__.22967
__func__.22895
motor_release
motor_init
motor_driver
motor_exit
__UNIQUE_ID_license2
__UNIQUE_ID_hmotor2vmotor1
__UNIQUE_ID_hmotor2vmotortype0
__param_hmotor2vmotor
__param_str_hmotor2vmotor
$LC0
$LC1
$LC2
$LC5
$LC3
$LC4
$LC6
$LC7
$LC8
$LC9
$LC10
$LC11
$LC12
$LC13
$LC14
$LC15
$LC16
$LC17
$LC18
$LC19
$LC20
$LC21
$LC22
$LC23
$LC24
$LC25
$LC26
$LC27
$LC32
$LC33
$LC28
$LC29
$LC34
$LC35
$LC30
$LC31
$LC36
$LC37
$LC38
$LC39
$LC40
$LC41
$LC42
$LC43
$LC44
sample_motor.mod.c
__module_depends
__UNIQUE_ID_vermagic0
free_irq
misc_deregister
dev_get_drvdata
platform_driver_unregister
__this_module
platform_get_irq
complete
__gpio_get_value
cleanup_module
seq_lseek
proc_create_data
gpio_free
single_open_size
init_module
wait_for_completion_interruptible_timeout
msecs_to_jiffies
__gpio_to_irq
preempt_schedule
platform_driver_register
request_threaded_irq
mod_timer
mutex_lock
gpio_direction_output
printk
__mutex_init
dev_err
misc_register
PDE_DATA
__init_waitqueue_head
__copy_user
jzgpio_ctrl_pull
proc_remove
motors_pdata
__might_sleep
jiffies
arch_local_irq_restore
seq_read
mutex_unlock
jz_proc_mkdir
init_timer_key
seq_printf
gpio_request
single_release
jz_tcu_config_chn
devm_kzalloc
dev_set_drvdata
arch_local_irq_save
del_timer
param_ops_int
msleep

**Comment by EliasKotlyar** [comment]
I have several news:
1. The Xiaomi Driver is a modified version of the original kernel driver
2. I was not able to drive the motors with the xiaomi driver
3. However i was able to compile the original and drive the horizontal axis with it. 
4. Unfortunately i dont know the pins for the vertical axis. Maybe someone can find them out, then i can compile a new version of the driver

**Comment by deennoo** [comment]
Which pin did you use for horizon axis ? Looks to be "only" 8 pins needed, you found 4 of them

**Comment by EliasKotlyar** [comment]
I have used following Pins:
```
#define MOTOR0_ST1_GPIO		GPIO_PB(19)	/**< Phase A */
#define MOTOR0_ST2_GPIO		GPIO_PB(20)	/**< Phase B */
#define MOTOR0_ST3_GPIO		GPIO_PB(21)	/**< Phase C */
#define MOTOR0_ST4_GPIO		GPIO_PB(22)	/**< Phase D */
```
This were the pins which were defined in the original driver. There are 6 Pins left: 4 for the motor and 2 Stop-Pins. I am thinking about dissassembling the original sample_motor.ko, and have a look if i can find this mapping there.

**Comment by EliasKotlyar** [comment]
Okey, i found out the other pins. You can see them if you disassemble the original driver. I have modded it into the cfw.
