### ISSUE TITLE
Can I still use Xiaomi Home ?

### ISSUE THREAD

**Issue by sharkoz** [EliasKotlyar/Xiaomi-Dafang-Hacks#10]
Hi,

Is it possible to also setup the cam to connect to xiaomi, while I am not playing with the software ? By removing the SD card or clicking 'setup' once again ?

The hack is making great progress, but I wondered if I could fall back to Xiaomi while some stuff still aren't available.

Thanks!

**Comment by dbuxo** [comment]
just remove the SD and reboot the camera, you can also delete the run.sh file from the SD.

**Comment by sharkoz** [comment]
Thanks works great.
