### ISSUE TITLE
mqtt configuration

### ISSUE THREAD

**Issue by wojtulab** [EliasKotlyar/Xiaomi-Dafang-Hacks#100]
Hello, how to properly configure mqtt conf file?
`[root@dafang:~]# cat /system/sdcard/config/mqtt
############################################################
# edit this file and move it to /system/sdcard/config/mqtt #
############################################################

# Options for mosquitto_sub & mosquitto_pub

USER=myusr
PASS=mypass
HOST=192.168.1.2
PORT=1883

TOPIC=cam/dafang/
# the topic used. send a message to topic/dafang/set with the payload help for help.
# Results will be placed in topic/dafang/${command} or topic/dafang/error - so please subscribe topic/dafang/# for testing purposes

MOSQUITTOOPTS=""
# add Options for Mosquitto here. For example --cafile /system/sdcard/config/DST_Root_CA_X3.pem --tls-version tlsv1
# or using a special id to connect to brokers like azure

CURLOPTS=""
# add options for curl here e.g --user user:password

FIFO=/var/run/mqtt-sub
# the FIFO used. Change it if you like to
`

After that I create in node-red mqtt sub with topic: cam/dafang/#
![image](https://user-images.githubusercontent.com/14801148/36339483-6ceafaac-13c7-11e8-86ff-d3b9fdcad7cb.png)
![image](https://user-images.githubusercontent.com/14801148/36339487-795cffba-13c7-11e8-8b32-fa5e3f3d512f.png)

There is no msg from Dafang....

**Comment by shinebar1001** [comment]
@wojtulab the "mqtt-control" only reacts ton Inputs on $topic/set, in your case cam/dafang/set (try to publish help or status)
I just added a new script which sends periodic status-messages. please update to the newest version and  add

```
STATUSFORMAT="json"
STATUSINTERVAL=30

```
STATUSINTERVAL controls the interval in seconds, 

to /system/sdcard/config/mqtt

after that enable the mqtt-status in the "Manage" Tab. You'll receive a Json-object which easyly can be used in Node Red.

Please report back if your problem is fixed and close the topic

**Comment by wojtulab** [comment]
Great, i'll gry it today. Is there possibilty to control it via mqtt? For example MOTOR LEFT?

**Comment by shinebar1001** [comment]
Yeah, of course. Just enable mqtt-control. After that you can send "help" to $topic/set and you see all possible commands.
For example send motor_up to $topic/set and the cam goes up 

Other commands are:
`status reboot blue_led_on blue_led_off yellow_led_on yellow_led_off ir_led_on ir_led_off ir_cut_on ir_cut_off motor_left motor_right motor_up motor_down motor_vcalibrate motor_hcalibrate audio_test h264_noseg_start h264_nosegmentation_start xiaomi_start rtsp_stop auto_night_mode_start auto_night_mode_stop toggle-rtsp-nightvision-on toggle-rtsp-nightvision-off flip-on flip-off`

**Comment by wojtulab** [comment]
Wow! That's amazing. Thank you.

**Comment by shinebar1001** [comment]
You're welcome. If there are any other options that should be included just open a feature request (currently I think about OSD, but I doubt anybody will use such a feature :)

**Comment by jmtatsch** [comment]
@shinebar1001 scripts/mqtt_control.sh, scripts/mqtt_status.sh and scripts/mqtt_status_control.sh seem to have dos line endings, can you please check?

**Comment by shinebar1001** [comment]
@jmtatsch Thank you for reporting, you're right - fixed. And finally I identifed the culprit - winscp.

**Comment by shinebar1001** [comment]
Added the possibility to configure OSD via mqtt

**Comment by utya1988** [comment]
Hello. after editing mqtt.dist, i have

> You have to configure mqtt first. Please see /system/sdcard/config/mqtt.dist for further instructions

**Comment by shinebar1001** [comment]
You have to move mqtt.dist to mqtt - so the configuration will survive an update. If the file isn't renamed, the process won't start

**Comment by freddujour** [comment]
Hi all,

i can't get the flip-on flip-off command working. I am now trying with topic "myhome/dafang/flip" value "on" but no effect on the picture. Did someone succeed?
