### ISSUE TITLE
Sannce i41HD

### ISSUE THREAD

**Issue by alexps70** [EliasKotlyar/Xiaomi-Dafang-Hacks#1000]
Want get RTSP/ONVIF from Sannce i41HD
Connect from UART and see

_U-Boot SPL 2013.07 (Jun 12 2018 - 03:06:59)
pll_init:358

l2cache_clk = 375000000

pll_cfg.pdiv = 8, pll_cfg.h2div = 4, pll_cfg.h0div = 4, pll_cfg.cdiv = 1, pll_cfg.l2div = 3

nf=35 nr = 1 od0 = 1 od1 = 1

cppcr is 02304900

CPM_CPAPCR 0450890d

nf=42 nr = 1 od0 = 1 od1 = 1

cppcr is 02a04900

CPM_CPMPCR 07d0c90d

nf=50 nr = 1 od0 = 1 od1 = 1

cppcr is 03204900

CPM_CPVPCR 0320490d

cppcr 0x9a794410

apll_freq 828000000 

mpll_freq 1000000000 

vpll_freq = 1200000000

ddr sel mpll, cpu sel apll

ddrfreq 500000000

cclk  828000000

l2clk 276000000

h0clk 250000000

h2clk 250000000

pclk  125000000

sdram init start

T20L 

get_ddr_type 

DDRC_DLP:0000f003

sdram init finished

U-Boot 2013.07 (Jun 12 2018 - 03:06:59)

Board: ISVP (Ingenic XBurst T20 SoC)
DRAM:  256 MiB
Top of RAM usable for U-Boot at: 84000000
Reserving 456k for U-Boot at: 83f8c000
Reserving 32800k for malloc() at: 81f84000
Reserving 32 Bytes for Board Info at: 81f83fe0
Reserving 124 Bytes for Global Data at: 81f83f64
Reserving 128k for boot params() at: 81f63f64
Stack Pointer at: 81f63f48
Now running in RAM - U-Boot at: 83f8c000
MMC:   msc: 0
idcode:ef4017 
the manufacturer ef

idcode:ef4017 
the manufacturer ef

In:    serial
Out:   serial
Err:   serial
Net:   Jz4775-9161
idcode:ef4017 
the manufacturer ef

  Sensor is [JXF22] 
  Bootargs Sensor is JXF22
Interface:  MMC
  Device 0: Vendor: Man 000003 Snr c63ec900 Rev: 3.5 Prod: SL32GЂ
            Type: Removable Hard Disk
            Capacity: 29476.5 MB = 28.7 GB (60367872 x 512)
Filesystem: FAT32 "NO NAME    "
Hit any key to stop autoboot:  1

T20# printenv
baudrate=115200
bootargs=console=ttyS1,115200n8 mem=37712K@0x0 ispmem=8100K@0x24D4000 rmem=19724K@0x2CBD000 init=/linuxrc rootfstype=squashfs root=/dev/mtdblock3 flash=SF sensor=JXF22 maxheight=1080 eeprom=NONE device_id=30400023346 ethaddr=00:11:22:33:44:72 devinfo=jcoxa19700101o016d5a7f7174c431e18c7f6101d686c15e8z10j7jn cpu=T20 ddr=64M mtdparts=jz_sfc:256K@0K(sf-bootloader),32K@256K(sf-bootenv),1472K@288K(sf-kernel),1152K@1760K(sf-rootfs),4576K@2912K(sf-ipcfs),704K@7488K(sf-miscfs) feature=4 lang=2
bootcmd=sf probe;sf read 0x80600000 0x48000 0x280000; bootm 0x80600000
bootdelay=1
device_id=30400023346
devinfo=jcoxa19700101o016d5a7f7174c431e18c7f6101d686c15e8z10j7jn
ethact=Jz4775-9161
ethaddr=00:11:22:33:44:72
gatewayip=192.168.2.1
ipaddr=192.168.2.84
loads_echo=1
netmask=255.255.255.0
serverip=192.168.2.81
stderr=serial
stdin=serial
stdout=serial

Environment size: 894/32764 bytes

root@jabsco:~# cat /proc/mtd
dev:    size   erasesize  name
mtd0: 00040000 00008000 "sf-bootloader"
mtd1: 00008000 00008000 "sf-bootenv"
mtd2: 00170000 00008000 "sf-kernel"
mtd3: 00120000 00008000 "sf-rootfs"
mtd4: 00478000 00008000 "sf-ipcfs"
mtd5: 000b0000 00008000 "sf-miscfs"_

**Comment by EliasKotlyar** [comment]
Hello Alexps70,

Many thanks for the bootlog. Can you try to flash the normal rootfs on the camera? It should be possible..

**Comment by alexps70** [comment]
(translation of Google from Russian)
I am very sorry, but I do not understand with Linux
all I managed to do was get the port and password from the telnet
When loading the camera opens the telnet port
if! ps | grep '[t] elnetd'; then
     telnetd -p9527
     (sleep 300; ps | awk '/ [p] 9527 / {print $ 1}' | xargs kill -9) &
and then it closes it

At this time I managed to perform telnetd and now I can view the contents of the files.

It would be enough for me to replace the cloud storage of videos on my webdav disk
I would not want to kill the camera - write in detail what needs to be done - I will try to collect information

**Comment by ThatUsernameAlreadyExist** [comment]
alexps70, 
you can try my hack rework for this type of camera here:  https://github.com/ThatUsernameAlreadyExist/JCO-PM203-Fisheye-Ingenic-T20-P2P-camera-hacks
