### ISSUE TITLE
Laggy stream

### ISSUE THREAD

**Issue by MeisterQ** [EliasKotlyar/Xiaomi-Dafang-Hacks#1002]
### Description

Using Xiaofang 1s. Firmware downloaded (10.04.2019).

After i finally got my Camera connected to my WiFi, its very laggy. Even with the smallest resolution

I tried many diffrenz resolutions and bitrates. I dont get a nice and clear stream, its just laggy like 1 frame per 5 seconds.

My WiFi-Router is about 1meter away from cam.

### What did you do to debug the issue

Tried many resolutions.

Is there any chance to get a nice stream without any latency or stucking?

**Comment by aqueiroz** [comment]
same here, just updated and its really bad. any way to rollback?

**Comment by voloszad** [comment]
Same for me, but I didn't updated any firmware, well except the bootloader. Tried many configuration, maybe disabling audio helps a bit, but VLC stream is still behind.  In TinyCam I get everything as expected.

(disabling audio was required for Synology's Surveillance Station, with it I got only 1 sec unplayable files)
