### ISSUE TITLE
'Unable to load image' error, servers won't stay enabled

### ISSUE THREAD

**Issue by unbwogable** [EliasKotlyar/Xiaomi-Dafang-Hacks#1006]
I just purchased a pair of Wyze v2 cameras, I believe they both have the jfx32 sensors, and I cannot get anything besides 'Unable to load image', nor can I get any of the servers to stay enabled (I enable with the toggle, and when I reopen the menu the toggle is animating back to the off position). I followed the instructions here multiple times
https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/hacks/install_cfw.md
which I found from another thread for a similar issue (https://github.com/openipcamera/openipc-firmware/issues/117#issuecomment-454884147), however the steps outlined do not work for me. I have also tried downgrading using the file from
https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/firmware_original/demo_5.5.1.177.bin. I'm using commit 994, and the light starts orange when I hold the button and plug in, then goes blue, then when it finishes up and I power up without the card, it does switch to blue for a few moments. I can switch the IR leds on and off, so it's obviously receiving commands. I also purchased a new 16GB card and partitioned it to 500MB, FAT32, and I confirmed it had no other files on the card besides the required files from this project. Any assistance would be greatly appreciated.

**Comment by pastroboy** [comment]
I have the exact same issue and I tried quite everything I found on github...

**Comment by unbwogable** [comment]
I did just find out they have a beta firmware that provides native rtsp support, should work in the mean time until we figure out why this isn't working for some of us.

**Comment by pastroboy** [comment]
can you share which firmware you installed?

**Comment by unbwogable** [comment]
Certainly. It's https://wyze.com/firmware/demos_V2_rtsp_4.19.4.48.bin.zip,
found at
https://support.wyzecam.com/hc/en-us/articles/360026245231-Wyze-Cam-RTSP,
which also has instructions and other info

**Comment by pastroboy** [comment]
Mine doesn' seem to be a Wyze cam, so I'm not able to connect the cam to my network and the wyze app :(
