### ISSUE TITLE
unsupported model or incorrect flashing?

### ISSUE THREAD

**Issue by prankousky** [EliasKotlyar/Xiaomi-Dafang-Hacks#1007]
Hi everybody,

I am currently running `Xiaomi-Dafang-Hacks` on a `Xiamo Dafang` Camera. Once I had flashed it and successfully booted from sd card, I ordered another camera.

This camera's model number is `DF3-00487358`. I attempted to first flash the bootloader, then boot from sd card as well, but no success. It had been a while since I had flashed the other camera, so I am not sure if it was similar back then, but upon inserting the sd card to flash and holding the `setup` button on the bottom of the camera, it only takes a few seconds, then the base will start rotating (should take about three minutes according to tutorial). Also, after rebooting, the blue led is not shining for five seconds.

I  tried to eliminate errors; this is what I have done so far

* check if download messed with the file => downloaded again and checked SHAsum => correct SHAsum
* SD card too large => tried another, smaller SD card; while this was still too big, it was smaller than the one I first attempted this with; **note** I used a 16GB card for the *previous* (working!) camera and just created a 512MB partition on it for flashing. It worked *back then*, so even though I could not get my hands on a regular 512MB sd card, this should work with this camera as well
* tried a third sd card; only 2GB, tried *both* just using the initial partition as well as creating one with 512MB; no success
* made triple sure I had renamed the file to `demo.bin`, which I forgot the first time I attempted flashing, so I made a note not to forget it again

I am using, and had been using before, sandisk sd cards, the original USB cable that came with each camera, and my active usb hub as a power source (this hub will fast-charge my smartphone even when the computer is turned off or not connected because it has it's own dedicated power supply; the camera should be able to draw enough power from it!)

The **only** thing that is different between first successfully flashing that other Dafang and now not successfully trying to flash this one is the operating system. While I was still running `Mac OSX Mojave` at the first attempt, I am now on `Archlinux`; OSX gave me a gui to format, copy files, etc., but I am pretty sure I did everything correctly on arch as well. I used `fdisk -l` to find the correct device, `fdisk <dev>` to edit it's partition (FAT32, 512MB size), and `umount` to mount it to my system and write files unto it. This all worked, and I could verify the output (for example, un- and remounting the sd card presented me with the expected file(s) to be there, so they actually are on that card; `fdisk -l` tells me the filesystem.

I am left with these possible error sources:

* camera model not supported
* camera broken (which I doubt; it will move its base, it will speak in what I assume is Chinese, ...)
* I messed something up **other than** using a small enough partition for my sd card and following all the steps; but if so, what did I do wrong?

I would appreciate any help on how to fix this. After multiple failed attempts, I stopped working on this and am now trying to once again. Thanks in advance for your help

**Comment by prankousky** [comment]
No ideas on what I can do to fix this? I still couldn't get it to work. My other device still works fine to this day.

**Comment by NorthernMan54** [comment]
Not sure if this helps, but I found that the SD cards formatted by WYZE Firmware had these settings in linux FDISK

```
Disklabel type: dos
Disk identifier: 0x00000000

Device     Boot Start     End Sectors  Size Id Type
/dev/sda1          63 3855599 3855537  1.9G  c W95 FAT32 (LBA)
```

I haven't tried loading a firmware with this card, but thought I would mention

**Comment by TimSoethout** [comment]
FYI Under OSX I had to make sure MBR was on the SD card (instead of EFI):

`diskutil eraseDisk FAT32 NAME MBRFormat disk2`

resulting in `diskutil list`:

```/dev/disk2 (external, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:     FDisk_partition_scheme                        *63.9 GB    disk2
   1:                 DOS_FAT_32 DATA                    63.9 GB    disk2s1
```
