### ISSUE TITLE
Live view

### ISSUE THREAD

**Issue by gysmo38** [EliasKotlyar/Xiaomi-Dafang-Hacks#101]
Hello,
I don't knwon if it interest other, I create a little page to have live view. 

I share it with you.

You have to change extension from txt to html and put in /system/sdcard/www

[livestream.txt](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/files/1734593/livestream.txt)

**Comment by shinebar1001** [comment]
That one is really nice. I would suggest to change the image-size to 640x360 to keep the aspect ratio.

Why don't you add this to the repo (including a link on status.cgi?)

**Comment by gysmo38** [comment]
Yes it is better with 640x360 :)
I don't know how add it to repo.

**Comment by jmtatsch** [comment]
I took the liberty to open a PR for you #102. Love the responsive UI.

**Comment by shinebar1001** [comment]
mergend #102

**Comment by wojtulab** [comment]
hello, is it possible to build similar page with cgi not a html?
I've created it in cgi but the picture can't refresh...

**Comment by gysmo38** [comment]
I do not knonw why you need that ut I think it not work because in html code there is reference to cgi-bin/*.api

You probably need to remobe the cgi-bin

**Comment by wojtulab** [comment]
What do you mean exactly?
