### ISSUE TITLE
No Picture Available

### ISSUE THREAD

**Issue by LordNex** [EliasKotlyar/Xiaomi-Dafang-Hacks#1011]
This is an issue tracking system only.
If you have general questions or are a newbie, please ask for help in our [chat channel](https://gitter.im/Xiaomi-Dafang-Hacks).

To make sure your issue can be resolved as quickly as possible please state your

* exact camera hardware: PTZ Version
* the Xiaomi-Dafang-Hacks commitid (from `git log`) you are experiencing the issue with: Ive downloaded and installed the latest version but when i connect to the HTTP of the camera I cannot see the video stream. I can connect and control the PTZ functions but do not see any video. I have folled the proper procedures and can access the camera with HTTP. Everything works but i cannot see any video

**Comment by Skettalee** [comment]
Im currently having the same issue. I went through the process really carefully a huge number of times and I see the cameras ip on my network and everything, just never getting an image of the video feed at all. Anyone?
