### ISSUE TITLE
Dafang rtsp stream only works properly when streaming to device/host on local network.

### ISSUE THREAD

**Issue by roberttseu** [EliasKotlyar/Xiaomi-Dafang-Hacks#1012]
Hi I am having an issue similar to the one described in this thread which has since been closed:-
https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/81

I am using a xiaomi dafang on the latest firmware as of today and I have performed the bootloader memory hack. 

I can stream to a pc using  rtsp://x.x.x.x:8554/unicast on vlc with the Dafang set to 1920x1080 FixedQp at 6000 kbps bitrate with no problems at all but no matter how I modify the configs, when I stream over my internet connection via a forwarded port on  rtsp://mypublicIP:8554/unicast with vlc the stream loads slowly and then freezes less than half a minute in or disconnects completely.

My internet connection is a 800 mbps down / 200 mbps up fiber connection on a mikrotik RB750Gr3 router. i have made sure that there are no other users on the network utilizing the internet at the time. I have also tried using the router my ISP provided just to make sure the issue was not because of my router but I am getting the same results.

To make sure there were no problems with my internet, on a linux pc on my local network i tunneled to the DAFANG using "ssh -L 0.0.0.0:9554:localhost:8554 -l root DAFANGIP and then forwarded tcp port 9554 to my linux PC and I was able to stream over the internet from a PC using rtsp://mypublicIP:9554/unicast with no problems at all. 

So it seems that for some reason, the DAFANG seems to freeze when streaming directly to a host/ip on the internet but when I tunnel the stream through a pc on the local network to the internet, the stream does not freeze or disconnect.

Anyone else having a similar issue?

**Comment by Meesah** [comment]
I'm having the _exact_ same issue. Same set up, V2 cams with latest Dafang Hacks firmware, @ 1080, and I have to lower settings to 720p, at 150kbps to make the stream somewhat stable. There are still 3-4 drops/hour, even with this setting. However, streamed to my PC it runs at 1080, 6000kbps stream, with 0 hiccups. This problem has also been documented over on the Wyze subreddit.

**Comment by dyburke** [comment]
I am also experiencing this issue.  ssh tunnel did do the trick, but it's not ideal.

**Comment by maslyankov** [comment]
Same here

**Comment by crackers8199** [comment]
> I am also experiencing this issue. ssh tunnel did do the trick, but it's not ideal.

how did you fix this? i've not been able to get it working even via openvpn...
