### ISSUE TITLE
Xiaofang 1S - RTSP Serv disables itself after a very few seconds

### ISSUE THREAD

**Issue by Tele3000** [EliasKotlyar/Xiaomi-Dafang-Hacks#1017]
Hello everyone,

Camera: Xiaofang 1S
Commitid: 1904a3e  

What I want:
Get the camera to work non stop without crashing and get a flux for Synology Surveillance Station.

My problem:
I successfully installed the CFW, was able to connect to the camera using its IP address normally but the RTSP H264 Serv option was disabled, I enabled it everything was working for a few seconds on VLC, then when I get back to the web interface, I saw the RTSP option disabling itself.
It does this all the time, sometimes randomly the RTSP will not be disabled and instead VLC image will completly freeze with no error, the web interface will not respond anymore,  some other times whenever I try to access the web interface (same with Putty or anything), it will say connection refused, and I just experienced the camera to completly crash after a few seconds and reboot.
In plus, whenever the camera reboot, it reboots like three times in a row and seems to crash between each of them.

What I tried:
I tried rebooting the camera tons of times.
I tried using different qualities because some people posted using lower video settings and no audio recording was more stable.
I tried accessing it in SSH to see a log or something before it crash or stop working, but the camera doesn't stay stable enough time for me to input login and see what is happening.
I tried to check the SD card to see if there was a windows file, if it was in read only or anything I could see broken.
I tried disabling all options in the web interface of the camera.
I checked to see if the camera was overheating (checked with my bare hands), it's a little warm but not hot at all and the camera is not in a specifically harmful environnement.

Logs:
Last startup.log:
```
==================================================
Starting the Dafang Hacks Custom Application Layer
==================================================
Loaded common functions
Created etc directory on sdcard
Bind mounted /system/sdcard/bin/busybox to /bin/busybox
Bind mounted /system/sdcard/root to /root
Bind mounted /system/sdcard/etc to /etc
wpa_supplicant: wpa_supplicant v2.5.nova.1.02
random: Trying to read entropy from /dev/random
Successfully initialized wpa_supplicant
Initializing interface 'wlan0' conf '/system/sdcard/config/wpa_supplicant.conf' driver 'default' ctrl_interface 'N/A' bridge 'N/A'
Configuration file '/system/sdcard/config/wpa_supplicant.conf' -> '/system/sdcard/config/wpa_supplicant.conf'
Reading configuration file '/system/sdcard/config/wpa_supplicant.conf'
ctrl_interface='/var/run/wpa_supplicant'
ctrl_interface_group='0'
ap_scan=1
Priority group 2
   id=0 ssid='telenet-DD753'
nl80211: Could not add multicast membership for vendor events: -2 (No such file or directory)
rfkill: Cannot open RFKILL control device
nl80211: RFKILL status not available
nl80211: Supported cipher 00-0f-ac:1
nl80211: Supported cipher 00-0f-ac:5
nl80211: Supported cipher 00-0f-ac:2
nl80211: Supported cipher 00-0f-ac:4
nl80211: Disable use_monitor with device_ap_sme since no monitor mode support detected
nl80211: interface wlan0 in phy phy0
nl80211: Set mode ifindex 2 iftype 2 (STATION)
nl80211: Subscribe to mgmt frames with non-AP handle 0x88f1f8
nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x88f1f8 match=06
nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x88f1f8 match=0a07
nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x88f1f8 match=0a11
nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x88f1f8 match=1101
nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x88f1f8 match=1102
nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x88f1f8 match=0505
netlink: Operstate: ifindex=2 linkmode=1 (userspace-control), operstate=5 (IF_OPER_DORMANT)
nl80211: Could not re-add multicast membership for vendor events: -2 (No such file or directory)
nl80211: driver param='(null)'
Add interface wlan0 to a new radio phy0
nl80211: Regulatory information - country=00
nl80211: 2402-2472 @ 40 MHz 20 mBm
nl80211: 2457-2482 @ 40 MHz 20 mBm (no IR)
nl80211: 2474-2494 @ 20 MHz 20 mBm (no OFDM) (no IR)
nl80211: 5170-5250 @ 80 MHz 20 mBm (no IR)
nl80211: 5735-5835 @ 80 MHz 20 mBm (no IR)
nl80211: 57240-63720 @ 2160 MHz 0 mBm
nl80211: Added 802.11b mode based on 802.11g information
wlan0: Own MAC address: 34:ce:00:b3:cf:c2
wpa_driver_nl80211_set_key: ifindex=2 (wlan0) alg=0 addr=(nil) key_idx=0 set_tx=0 seq_len=0 key_len=0
wpa_driver_nl80211_set_key: ifindex=2 (wlan0) alg=0 addr=(nil) key_idx=1 set_tx=0 seq_len=0 key_len=0
wpa_driver_nl80211_set_key: ifindex=2 (wlan0) alg=0 addr=(nil) key_idx=2 set_tx=0 seq_len=0 key_len=0
wpa_driver_nl80211_set_key: ifindex=2 (wlan0) alg=0 addr=(nil) key_idx=3 set_tx=0 seq_len=0 key_len=0
wlan0: RSN: flushing PMKID list in the driver
nl80211: Flush PMKIDs
wlan0: Setting scan request: 0.100000 sec
ENGINE: Loading dynamic engine
ENGINE: Loading dynamic engine
EAPOL: SUPP_PAE entering state DISCONNECTED
EAPOL: Supplicant port status: Unauthorized
nl80211: Skip set_supp_port(unauthorized) while not associated
EAPOL: KEY_RX entering state NO_KEY_RECEIVE
EAPOL: SUPP_BE entering state INITIALIZE
EAP: EAP entering state DISABLED
ctrl_interface_group=0
wlan0: Added interface wlan0
wlan0: State: DISCONNECTED -> DISCONNECTED
nl80211: Set wlan0 operstate 0->0 (DORMANT)
netlink: Operstate: ifindex=2 linkmode=-1 (no change), operstate=5 (IF_OPER_DORMANT)
Writing wpa stat file /tmp/wpastat
Daemonize..
udhcpc: deleting routers
adding dns 195.130.130.1
adding dns 195.130.131.1
Initialized gpios
Determined image sensor model as 
dropbear: 
lighttpd: 
Startup finished!
```

Startup log the last time the camera crashed during startup:
```
==================================================
Starting the Dafang Hacks Custom Application Layer
==================================================
Loaded common functions
Created etc directory on sdcard
Bind mounted /system/sdcard/bin/busybox to /bin/busybox
Bind mounted /system/sdcard/root to /root
Bind mounted /system/sdcard/etc to /etc
wpa_supplicant: wpa_supplicant v2.5.nova.1.02
random: Trying to read entropy from /dev/random
Successfully initialized wpa_supplicant
Initializing interface 'wlan0' conf '/system/sdcard/config/wpa_supplicant.conf' driver 'default' ctrl_interface 'N/A' bridge 'N/A'
Configuration file '/system/sdcard/config/wpa_supplicant.conf' -> '/system/sdcard/config/wpa_supplicant.conf'
Reading configuration file '/system/sdcard/config/wpa_supplicant.conf'
ctrl_interface='/var/run/wpa_supplicant'
ctrl_interface_group='0'
ap_scan=1
Priority group 2
   id=0 ssid='telenet-DD753'
nl80211: Could not add multicast membership for vendor events: -2 (No such file or directory)
rfkill: Cannot open RFKILL control device
nl80211: RFKILL status not available
nl80211: Supported cipher 00-0f-ac:1
nl80211: Supported cipher 00-0f-ac:5
nl80211: Supported cipher 00-0f-ac:2
nl80211: Supported cipher 00-0f-ac:4
nl80211: Disable use_monitor with device_ap_sme since no monitor mode support detected
nl80211: interface wlan0 in phy phy0
nl80211: Set mode ifindex 2 iftype 2 (STATION)
nl80211: Subscribe to mgmt frames with non-AP handle 0xc731f8
nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0xc731f8 match=06
nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0xc731f8 match=0a07
nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0xc731f8 match=0a11
nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0xc731f8 match=1101
nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0xc731f8 match=1102
nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0xc731f8 match=0505
netlink: Operstate: ifindex=2 linkmode=1 (userspace-control), operstate=5 (IF_OPER_DORMANT)
nl80211: Could not re-add multicast membership for vendor events: -2 (No such file or directory)
nl80211: driver param='(null)'
Add interface wlan0 to a new radio phy0
nl80211: Regulatory information - country=00
nl80211: 2402-2472 @ 40 MHz 20 mBm
nl80211: 2457-2482 @ 40 MHz 20 mBm (no IR)
nl80211: 2474-2494 @ 20 MHz 20 mBm (no OFDM) (no IR)
nl80211: 5170-5250 @ 80 MHz 20 mBm (no IR)
nl80211: 5735-5835 @ 80 MHz 20 mBm (no IR)
nl80211: 57240-63720 @ 2160 MHz 0 mBm
nl80211: Added 802.11b mode based on 802.11g information
wlan0: Own MAC address: 34:ce:00:b3:cf:c2
wpa_driver_nl80211_set_key: ifindex=2 (wlan0) alg=0 addr=(nil) key_idx=0 set_tx=0 seq_len=0 key_len=0
wpa_driver_nl80211_set_key: ifindex=2 (wlan0) alg=0 addr=(nil) key_idx=1 set_tx=0 seq_len=0 key_len=0
wpa_driver_nl80211_set_key: ifindex=2 (wlan0) alg=0 addr=(nil) key_idx=2 set_tx=0 seq_len=0 key_len=0
wpa_driver_nl80211_set_key: ifindex=2 (wlan0) alg=0 addr=(nil) key_idx=3 set_tx=0 seq_len=0 key_len=0
wlan0: RSN: flushing PMKID list in the driver
nl80211: Flush PMKIDs
wlan0: Setting scan request: 0.100000 sec
ENGINE: Loading dynamic engine
ENGINE: Loading dynamic engine
EAPOL: SUPP_PAE entering state DISCONNECTED
EAPOL: Supplicant port status: Unauthorized
nl80211: Skip set_supp_port(unauthorized) while not associated
EAPOL: KEY_RX entering state NO_KEY_RECEIVE
EAPOL: SUPP_BE entering state INITIALIZE
EAP: EAP entering state DISABLED
ctrl_interface_group=0
wlan0: Added interface wlan0
wlan0: State: DISCONNECTED -> DISCONNECTED
nl80211: Set wlan0 operstate 0->0 (DORMANT)
netlink: Operstate: ifindex=2 linkmode=-1 (no change), operstate=5 (IF_OPER_DORMANT)
Writing wpa stat file /tmp/wpastat
Daemonize..
```

Thanks in advance for any help you could provide, anyway if I get no solution I will simply ask the seller for a refund, if he doesn't want well, 15€ in my ass (because there's no way I will accept my video surveillance be send to China).
**Could you also please tell me if the Dafang camera is safier to use (because I saw many people struggling with almost all models except the Dafang one which seems to work fine except for a very few feature as PTZ I don't care personnally)?**

Best regards.

**Comment by Nisbo** [comment]
Do you already have a solution for the RTSP problem ? I have the same / similar problem. 
RTSP stop in VLC player after some seconds and I have to restart it. Sometimes I get no connection to the CAM during the restart then I have to try it again some seconds later

**Comment by Nisbo** [comment]
OK I solved my problem by reducing the video settings. Default is 25 FPS and 5000 kbps.
I changed it to 10 FPS and 750 kbps and now it is running without crashes.

**Comment by Seg22** [comment]
Same Cam same issue, try this:
go into your run.sh and search for "swap" change false into true

Worked for me :)

**Comment by Tele3000** [comment]
I thought it was good with the solution provided by Seg22, but nope, just tried, the RTSP Server doesn't disable itself anymore, but now the camera shutdown after between 20 seconds and 1 minutes then either sometimes restart sometimes not.

It will never work, I lost all hope! T_T
Thanks anyway to everyone who took some time to answer to this.

**Comment by Seg22** [comment]
Dont give up that quick, which version do you have? Look at your mac-address, does it begin with 78 or with c8?
Did u try to reload the files? Maybe something is corruped.Yould you see at the loogfiles after the crash or after it closes RTSP? That would help me a lot to help you :)
    Am Dienstag, 16. Juli 2019, 19:44:12 MESZ hat Tele3000 <notifications@github.com> Folgendes geschrieben:  
 
 
I thought it was good with the solution provided by Seg22, but nope, just tried, the RTSP Server doesn't disable itself anymore, but now the camera shutdown after between 20 seconds and 1 minutes then either sometimes restart sometimes not.

It will never work, I lost all hope! T_T
Thanks anyway to everyone who took some time to answer to this.

**Comment by Tele3000** [comment]
Hello Seg22, sorry for the late answer, the MAC address of my cam is neither 78 nor C8, it begins by 34 but in BOOTEX.log there's a volume serial code which begin by C8.
Will try to reload the file again to see if it can solve the problem.

For providing a log after the crash (the RTSP server work as intended now because of your solution) of the whole camera, I have no such log, or I don't see any, in the camera SD card, I have three logs file : BOOTEX.log (which doesn't seem useful except for the volume serial code maybe and is in French), crond.log (have no idea what it is, can provide it if you want, it's 8K of the same 3 or 4 lines) and startup.log (which seems to only provide logs of the camera bootstrap step which doesn't seem to be what you want).
So I'm not sure for providing one of these except if you tell me which one would be useful.

**Comment by Seg22** [comment]
Hmm ok, could you provide the hole mac-address?
i want to see the vendor

and please provide the logs at your webpage/Status/logs dmessg and video server

**Comment by PietroMB** [comment]
Exact same issue, someone have some fixs to try?
