### ISSUE TITLE
How do I stream MJPEG HTTP not RTSP?

### ISSUE THREAD

**Issue by peteboz** [EliasKotlyar/Xiaomi-Dafang-Hacks#1020]
I have an application that does not support rtsp and needs to be in the format: http://x.x.x.x:8554 NOT rtsp://x.x.x.x:8554.

Any ideas on how to access this?  I did see some threads on this topic in the past, but didn't come across a solution.  I have a Wyze cam v2 with latest Dafang Hacks firmware.

Thank you in advance.

**Comment by Nathan116** [comment]
What are the chances this can be reopened?
