### ISSUE TITLE
Reset Password after accidentally pressed set http password

### ISSUE THREAD

**Issue by tof92130** [EliasKotlyar/Xiaomi-Dafang-Hacks#1022]
I accidentally pressed Set HTTP Password on the panel without entering anything.
Now, I don't know the password now

root/ismart12

is not working anymore.

Can I reset the pass with command lines ?

**Comment by Dopeyr** [comment]
Do you still have SSH access? If so, SSH in then run:

http_password yournewpassord

**Comment by tof92130** [comment]
I can mount the sd card containing the files on my PC

**Comment by Dopeyr** [comment]
The alternative if you mount it is you can replace `lighthttpd.user` in `/system/sdcard/config/lighttpd.user` with the original file https://raw.githubusercontent.com/EliasKotlyar/Xiaomi-Dafang-Hacks/master/firmware_mod/config/lighttpd.user

That will reset it to `ismart12`

**Comment by tof92130** [comment]
it worked (second method) and I didn't test the first method.

Thank you !

**Comment by DifferentComputers** [comment]
I had the very same problem. Could you please look at the interface here in terms of usability to prevent this happening accidentally?

Also, in the current 2019-05-21T19:52:43Z firmware, I no longer see any way to create other users besides root. DIdn't there used to be a way to do this?
