### ISSUE TITLE
 mqtt-control wont work . Camera stream into hass wont work

### ISSUE THREAD

**Issue by marrobHD** [EliasKotlyar/Xiaomi-Dafang-Hacks#1023]
Homeassistant Mqtt discovery work- But mqtt-control wont start
- platform: ffmpeg
  name: DaFang3
  input: -rtsp_transport tcp -i rtsp://dafang:8554/unicast
I cant get a picture whci Homeasssiatnt

**Comment by marrobHD** [comment]
After restart the mqtt works. But i cant see a picture in a hass. In vlc is the stream working

**Comment by marrobHD** [comment]
Mqtt is very slow. The state update takes 15secs. It wont find the device tracker and the state

**Comment by jokerigno** [comment]
I can't make mqtt control work (no ok) while no issue with mqtt status or video streaming.

**Comment by marrobHD** [comment]
Jep

**Comment by shauder** [comment]
I have issues where the MQTT control service stops and wont start again without a unplug and replug of the camera. The Service shows 'Nok'.

**Comment by jokerigno** [comment]
I noticed that if you manually turn on service mqtt status, wait, and then turn on mqtt control it results as ok.

**Comment by jokerigno** [comment]
Please don't close this issue because fix is around the corner.

Just add some delay in autostart for mqtt control and it's fixed!

**Comment by jmtatsch** [comment]
@jokerigno those two should really be independent of each other. Can you explain why adding a delay helps?

**Comment by jokerigno** [comment]
Because it simply works. If I start those 2 service at boot mqtt control doesn't work.

If I start mqtt status, wait until it's on and the tick on mqtt control box it works.

That's it.
