### ISSUE TITLE
Can we improve RTSP by learning from official Wyze RTSP firmware?

### ISSUE THREAD

**Issue by austhomp** [EliasKotlyar/Xiaomi-Dafang-Hacks#1025]
### Background
Wyze has now released firmware that [enables RTSP support here](https://support.wyzecam.com/hc/en-us/articles/360026245231-Wyze-Cam-RTSP).

I tried it on one of my WyzeCam V2's and it's interesting because it keeps all of the existing functionality as well as adding RTSP support.

Their RTSP stream has:
- video stream with full 1080p resolution
- includes audio
- video is delayed by at least 3 seconds 
- audio is out of sync with the video

I have a feeling it would work pretty well if the resolution could be lowered but the settings in the Wyze app do not affect the RTSP stream.

### Question

I'm wondering if we can discover some clues to improve the RTSP stream in this project by looking at the files in the demo.bin they provide [here](https://wyze.com/firmware/demos_V2_rtsp_4.19.4.48.bin.zip).

I looked at the files but i didn't see anything obvious. If this isn't feasible please just close the issue. Thanks.

**Comment by marrobHD** [comment]
I think EliasKotlyar wont update that. I have the wyze cam pan and the motion tracking function wont work correct. Mqtt work wigh huge delay
