### ISSUE TITLE
#DaFang Use only in mainland China fix needed

### ISSUE THREAD

**Issue by daxyco** [EliasKotlyar/Xiaomi-Dafang-Hacks#1026]
Hi guys, noob alert :(

I've purchased a Xiaomi DaFang camera, CMIT ID **2017DP3894**, than it says DF3--00522010 on the back. The only thing I want to achieve is to use the Mi Home app (or another) to look at what's going on in the house. When I paired the camera to the app for the first time, I chose my location (there was no mainland China choice). I get the message: Use only in mainland China. This product is only used in mainland China. I then upgraded the FW, to the newest, I only know i had to do it a few times to get to the newest. Changed a few Xioami accounts also.

I then downgraded the app on my phone, changed region to mainland China, and still getting the same message. Current FW in the cam is 5.5.1.243, Mi Home app 5.4.38 (i read in a forum that this version would work).

What I noticed is that, when the sd card was inserted, the camera made videos and stored them on the card.

Can you tell me if there is a fix? If you need any more info, I'll be more than glad to provide it.

**Comment by Pololilo** [comment]
Hi there,

Unfortunately I just experience the same issue on my DF3.
I had an other issue with it so I upgrade it to the latest firmware (5.5.1.421), I was on 5.5.1.419, and bam got this message.
So went to this thread and install from the CWF 1.3, which install firmware 5.5.1.243, but still the same error.
I could see that some Xiaomi camera have this issue with a specific MAC address.
But I have two DF3  ID 2017DP3894 with a close MAC address (78:11:DC) and are DF3-00418336 and DF3-00481392. the second one is working fine...

Any tips are welcome...
Cheers,
Paul

**Comment by pr882** [comment]
I have the same issue and would also appreciate some help.

**Comment by telenut** [comment]
Samen here... Guess I can only use him with the hack now

**Comment by damienbelliard** [comment]
The same :'(

**Comment by pr882** [comment]
So if the camera is blocked...with hack/CFW there is no way to use it with MiHome app? 

Which android app do you recommend instead?

**Comment by daxyco** [comment]
It's possible to view the camera from another app? Wow, that's great! I'd be so grateful if anyone can tell me how to get it working...

**Comment by telenut** [comment]
It is not possible...

**Comment by daxyco** [comment]
I've got this hack working, but I'm connecting to the camera via 192.... So I can only access it when I'm in the local network. I could probably set up a VPN to get into my local network and view the camera? I'm a noob, so pardon me asking, please...

**Comment by XaviM85** [comment]
If you got the hack working, then you can access camera's stream with e.g. VLC. To make the stream available outside LAN, make camera's IP static in your router settings, then set up IP forwarding. Let's say your camera IP is 192.168.1.100, stream shall be available by default at "rstp://192.168.1.100:8554/unicast". You need to know your WAN IP and make forwarding it to LAN camera's IP. It is very probable that WAN IP is dynamic - in that case google for DDNS service and set up your custom host name which you will use outside LAN to access camera's stream. In the end you should have something like this: "rtsp://yourcustomhostname.ddns.net:8554/unicast". DDNS.net is the one I got from noip.com

**Comment by pr882** [comment]
Hi I have hack working.

How can I do this:
I have a "Phone A" with Mobile hotspot enabled and I have Dafang camera connected to it. It works. Also Im allowed to use mobile hotspot/tether with my mobile operator.

Then I want to connect from "Phone B" via internet from another location to Phone A (camera) and see the video. I use app tinyCam. I tried various settings in tinyCam (IP, port) but it doesnt connect to Phone A?

If I connect with Phone B to Mobile hotspot on Phone A an put local IP of camera in tinyCam the video works fine. So I assume either my mobile operator or Mobile hotspot is blocking incoming connections? Also I think my mobile operator is using CGNAT so I dont know my "real" IP for Phone A?

Any help would be appreciated.

**Comment by pr882** [comment]
I have a "Phone A" with Mobile hotspot enabled and I have Dafang (with hack) connected to it. It works. Also Im allowed to use mobile hotspot/tether with my mobile operator.
Then I want to connect from "Phone B" via internet from another location to Phone A (camera) and see the video. I use app tinyCam. I tried various settings in tinyCam (IP, port) but it doesnt connect to Phone A?
If I connect with Phone B to Mobile hotspot on Phone A an put local IP of camera in tinyCam the video works fine. So I assume either my mobile operator or Mobile hotspot is blocking incoming connections? Also I think my mobile operator is using CGNAT so I dont know my "real" IP for Phone A?
Can I connect Dafang in that way?

**Comment by XaviM85** [comment]
You can't connect from outside your LAN to local IP address. To be able to do that, you need port forwarding. Check this tutorial for details: https://videos.cctvcamerapros.com/surveillance-systems/port-forwarding-remote-access-setup-for-ip-security-cameras.html

**Comment by pr882** [comment]
OK, with my home router I forwarded ports and I can watch video outside my LAN.   

My question is can I do the same when modem/router is Android phone with enabled Mobile hotspot and Dafang connected to it?

**Comment by XaviM85** [comment]
That's a good question, though. As far as I know, there is no port forwarding in Android hotspot settings, unfortunately. There might be some third party app, but I have no knowledge here.

**Comment by pr882** [comment]
I found an app which claims that can port forward. Also I guess bigger issue is that because of CGNAT I dont have my phones public IP.

**Comment by daxyco** [comment]
What android app do you recommend to access the camera stream?

**Comment by vikasrajbhagat** [comment]
Not sure if this helps. 
https://www.computersolutions.cn/blog/2016/09/xiaomi-camera-bs-region-locking-fix/

**Comment by daxyco** [comment]
I forwarded the port as instructed, and now i can access the camera stream from outside the LAN, via VLC or an app on my smartphone. But can I access the main page, with all the settings and configurations? How do I formulate the URL?

I have a static IP, but going to xxx.xxx.xxx.xxx:8554 just gives me an HLS stream that never loads.

**Comment by jairowagner** [comment]
Same problem here

**Comment by mansaf1** [comment]
I've been facing the same issue with a couple of XiaoFang cameras and a Dafang for a couple of months. I sent the email request to unlock it on the 1st of May 2019 as per the instructions given. I didn't hear from them so after going through the threads again yesterday looking for a fix i decided to send another reminder to them. The next morning i got an reply that my camera is unlocked. So keep trying them, they will eventually unlock it for you.

**Comment by pr882** [comment]
Hi, did you send exactly as the instructions given (with invoice,  etc)? I have send numerous emails to feedback@hualaikeji.com in the last two months and still no answer.

**Comment by telenut** [comment]
same here, no answer...

Op do 4 jul. 2019 om 09:18 schreef pr882 <notifications@github.com>:

**Comment by mansaf1** [comment]
> Hi, did you send exactly as the instructions given (with invoice, etc)? I have send numerous emails to [feedback@hualaikeji.com](mailto:feedback@hualaikeji.com) in the last two months and still no answer.

Ya that's what i did. It took them 2 months and a few followups, but to my surprise, i got a reply today. I did give up hope on them for a while to be honest.

**Comment by pr882** [comment]
Where did you buy your camera? Was from one of the sites as in instructions or...?

**Comment by mansaf1** [comment]
> Where did you buy your camera? Was from one of the sites as in instructions or...?

No some random site (lightinthebox.com), it was not one of the mentioned sites.

**Comment by daxyco** [comment]
> > Hi, did you send exactly as the instructions given (with invoice, etc)? I have send numerous emails to [feedback@hualaikeji.com](mailto:feedback@hualaikeji.com) in the last two months and still no answer.
> 
> Ya that's what i did. It took them 2 months and a few followups, but to my surprise, i got a reply today. I did give up hope on them for a while to be honest.

Hey, I repeated the email request, and oddly enough they responded within a few hours, and my camera was unlocked!

Thanks for the input!

As for trying another solution (the one in this link https://www.computersolutions.cn/blog/2016/09/xiaomi-camera-bs-region-locking-fix/), I haven't been able to telnet into the camera...

**Comment by telenut** [comment]
wow, I also mailed again, got reply after 3 minutes!


Op di 9 jul. 2019 om 10:23 schreef daxyco <notifications@github.com>:

**Comment by JminyChv** [comment]
Hey, I send several mail but still no answer...
You explained your problem or just sent MAC address, invoice and photo of your camera ?
Thanks

**Comment by daxyco** [comment]
I explained rhe problem, and attached all the necessary files...

**Comment by telenut** [comment]
Just mentioned county, Mac address, screenshot of purchase and picture of
back of cam
And it was an Ali purchase...
Just testing it now, and it works again, even after installing the update

But no support for streaming to Chromecast on this model so far...

**Comment by JminyChv** [comment]
I send an email yesterday and they answer me!!! My 2 Dafangs work!

**Comment by telenut** [comment]
Would it work with the xiaofang too? :-)

**Comment by Pololilo** [comment]
Hey all,

I also sent a message to AliExpress's seller to whom I bought this camera. They take time to reply, first unlock was unsuccessful the second successful.
You should do the same. Apparently they usually know someone to unlock devices directly in Xiaomi system

They also recommend to not upgrade any device specially camera.

Best,
Paul

**Comment by fakotibor** [comment]
For me the problem is solved. After I write a request (few minutes after) the camera MAC address was unlocked. It is very important to begin the letter with mac address. I think that the unlock is made by a bot.
I writed this:
mailing address: feedback@hualaikeji.com
subject: request of international user
content:
78:11:XX:XX:XX:XX
I cannot use my DaFang camera, it is blocked. Please unlock it.

The reply was:

Dear customers,
Congratulations! Your device unlock request has been approved.
Your Spot is now unlocked for use outside of Mainland China. Please restart
Again, we remind you that we may not able to provide technical support and after-sale service when the Spot is used outside of Mainland China.

Thank you for choosing our products.

**Comment by fr1sk** [comment]
I also sent an email about unblocking my camera. They responded and told me that is unlocked. I tried after that (reset the camera and connect it again) and the issue was the same. I was still restricted to Mainland China even if they told me that is unblocked. What should I do? Did someone experience the same issue?
Thanks

**Comment by pr882** [comment]
Even if the camera is unlocked you will be restricted to Mainland China. Unlocked means it will work but only in Maniland China.

**Comment by spattinson** [comment]
> Not sure if this helps.
> https://www.computersolutions.cn/blog/2016/09/xiaomi-camera-bs-region-locking-fix/

If you want to try this method because email is unanswered on my cams the api server was **apicn.hualaikeji.com** I found this by capturing boot on an unmodified cam, though in my case my cam was not blocked for some reason - note this is the same domain as where you email. You can block that domain at DNS level if you cannot get telnetd working, pihole, hosts file etc

**Comment by majfriend** [comment]
> 
> 
> > Not sure if this helps.
> > https://www.computersolutions.cn/blog/2016/09/xiaomi-camera-bs-region-locking-fix/
> 
> If you want to try this method because email is unanswered on my cams the api server was **apicn.hualaikeji.com** I found this by capturing boot on an unmodified cam, though in my case my cam was not blocked for some reason - note this is the same domain as where you email. You can block that domain at DNS level if you cannot get telnetd working, pihole, hosts file etc

is that method i compatible with Firmware 5.5.1_0426?

**Comment by lukinalutuna** [comment]
> > Not sure if this helps.
> > https://www.computersolutions.cn/blog/2016/09/xiaomi-camera-bs-region-locking-fix/
> 
> If you want to try this method because email is unanswered on my cams the api server was **apicn.hualaikeji.com** I found this by capturing boot on an unmodified cam, though in my case my cam was not blocked for some reason - note this is the same domain as where you email. You can block that domain at DNS level if you cannot get telnetd working, pihole, hosts file etc

It didn't work for my camera.

**Comment by george-kar** [comment]
It looks like that they are not unlocking cameras anymore. I have sent dozen of emails and they didnt replied. Also, the seller I purchased cameras also tried and told me try in 2 days but nothing.

Xiaomi wants to stop international sales on cameras.

**Comment by pr882** [comment]
Anybody with unlocked Dafang tried to update offical firmware via MiHome app? Will camera work if I update offical firmware?

**Comment by bromptonista** [comment]
Camera won’t work with Mi app unless hualaikeji.com unlock it for you.
I’m wondering if there is a way to simply change the MAC address to something they accept?
