### ISSUE TITLE
Cannot Flash Dafang

### ISSUE THREAD

**Issue by ac13332** [EliasKotlyar/Xiaomi-Dafang-Hacks#1029]
I am unable to install the custom firmware. I've read all the threads where people had issues and tried all of their solutions (such as pairing it with the app first etc).

I have tried 3x MicroSD cards, 64gb, 32gb, and 16gb. I have tried all of those with various partition sizes. Partition has always been primary and FAT or FAT32. There has been no other data whatsoever on the SD card.

When I hold the Setup button and turn on the camera the light eventually turns blue, but that only lasts 5-10 seconds, not long enough for the firmware. After which is spins, flashes a bit and, eventually starts recording - presumably on the original firmware.

I am out of ideas and have tried pretty much every combination of ideas, as I said, pairing with the app first, not pairing, different SD formats, and so on.

**Comment by damienbelliard** [comment]
The same problem here, with last official update.

**Comment by jozhix** [comment]
> When I hold the Setup button and turn on the camera the light eventually turns blue, but that only lasts 5-10 seconds, not long enough for the firmware. After which is spins, flashes a bit and, eventually starts recording - presumably on the original firmware.

What steps did you take to verify what firmware you are on?
Mine did the same (5..10sec blue light) and camera was up and running. No need to wait 3 minutes. Just dont forget to modify config file for wifi.
