### ISSUE TITLE
Unable to load image when accessing via ip - Xiaomi Dafang

### ISSUE THREAD

**Issue by mcmcc1** [EliasKotlyar/Xiaomi-Dafang-Hacks#1030]
I have the Xiaomi Dafang and when I log into the camera via ip, I get an "Unable to load the image" on the main page. I'm able to rotate, update and control the camera. Just unable to view the image. 

I've tried in Chrome and IE and the same issue. The page has a certificate invalid, not sure if that's normal.

**Comment by snowsmoked** [comment]
I have exactly the same problem. First it worked but not anymore.

**Comment by jokerigno** [comment]
Same issue. Any update?

**Comment by MkLHX** [comment]
so no body can explain what is the cause of trouble and every issues about that still closed automatically? 
juste start from scratch everythings is good, run update through web gui and go back to unable to load image....
what is this shitty trouble?

**Comment by jokerigno** [comment]
In my case was an HW issue. I reconnected the cable to the mainboard and now image is staple when the camera moves.
