### ISSUE TITLE
Dafang .lastCommitDate : No such file or directory

### ISSUE THREAD

**Issue by DavidB81** [EliasKotlyar/Xiaomi-Dafang-Hacks#1034]
On Dafang camera the date is wrong like 01.01.1970 since last update.
in log: cat: can't open '/system/sdcard/.lastCommitDate': No such file or directory
The file is missing, it's a new update.
The problem is the same on my 2 Dafang camera.

**Comment by jmtatsch** [comment]
Format sd and start from scratch.

**Comment by DavidB81** [comment]
I already formatted the 2 sd cards and copied all the files from folder firmware_mod.
Then I reconfigured everything from scratch.
I tested several times.
Always this file missing.

**Comment by jmtatsch** [comment]
You copy with windows? Is the file there after git checkout? Show hidden files...

**Comment by DavidB81** [comment]
I copy with ubuntu and the show hidden files command is activate. The file is not present after the decompression of the Github ZIP.

**Comment by jmtatsch** [comment]
Hm actually that file may be created once you run the update function, can you try?

**Comment by DavidB81** [comment]
this morning's new ZIP Github copied to SD card.
Update function, restart and nothing more. Always the same and no file.

**Comment by DavidB81** [comment]
I found my problem. I use the static ip configuration and forgot to configure ip gateway in the defaultgw.conf file.
Thanks

You can close the subject.
