### ISSUE TITLE
Trigger MQTT autodiscovery on reconnection or manually

### ISSUE THREAD

**Issue by mikeage** [EliasKotlyar/Xiaomi-Dafang-Hacks#1042]
### Description

Currently, if the camera boots before the mqtt server is running (e.g., power failure), the autodiscovery message is lost (it fails to send, but that doesn't report any errors, and it doesn't retry).

There are two ways that I can think of to fix this:

1. Always send autodiscovery when we reconnect
2. Add a command to manually send the autodiscovery message; this can be a bit of a chicken and egg problem, but it could also list to (for example) `myhome/` rather than `myhome/foo`

I'll try to work on this, but before I do (I probably won't have any time for the next few days), any thoughts on which option is preferable?

**Comment by jmtatsch** [comment]
1. Which reconnection do you mean? The MQTT client is frequently connecting/disconnecting every loop run. This is already a problem, and can break the video stream if to much MQTT control commands are coming in.

2. Better than nothing, but still annoying to do it manually :)

**Comment by mikeage** [comment]
Good point about #1. Forgot about that. So it'd probably have to be option 2... I have my homeassistant automatically send out announce requests anyway, so it's not really manually. 

Another option would be to set a flag if the autodiscovery send fails, and to keep trying until it succeeds. I think we send it with `retain` set, right? If not, it probably should be, to avoid a problem if the camera comes up after MQTT but before HA does (or if HA is restarted).

**Comment by mikeage** [comment]
Took me a while, but I just opened a PR. Works for me ;-)
