### ISSUE TITLE
Dafang Camera wont connect to WIFI

### ISSUE THREAD

**Issue by JuhaHeikki** [EliasKotlyar/Xiaomi-Dafang-Hacks#1048]
Hello,

I have had some troubles connecting my Dafang to the network. Looking at the log file it seems like its a driver issue. As the logs are quite long, I will paste only the parts of the logs I think matter (if needed I can paste full logs):

==================================================
Starting the Dafang Hacks Custom Application Layer
==================================================

Failed to add interface wlan0
wlan0: Request to deauthenticate - bssid=00:00:00:00:00:00 pending_bssid=00:00:00:00:00:00 reason=3 state=DISCONNECTED
wlan0: State: DISCONNECTED -> DISCONNECTED
nl80211: Set wlan0 operstate 0->0 (DORMANT)

_I then hooked up the serial and tried to check that too:_

Ingenic-uc1_1 login: [    4.472098] RTL871X: module init start
[    4.475994] RTL871X: rtl8189es v4.3.18.3_20185.20161116_pmpinclu_mac_monitor_minMem_EDCA542B_pbyr
[    4.487500] RTL871X: build time: Oct 19 2017 11:54:52
[    4.492828] wlan power on
[    4.512537] RTL871X: module init ret=0
[    4.570256] mmc1: new SDIO card at address 0001
[    4.592263] bFWReady == _FALSE call reset 8051...
[    4.632301] RTL871X: rtw_ndev_init(wlan0) if1 mac_addr=78:11:dc:76:83:0d
[    6.392103] ==> rtl8188e_iol_efuse_patch 
[    6.703299] RTL871X: rtw_cmd_thread: DriverStopped(True) SurpriseRemoved(False) break at line 564
[    6.723819] RTL871X: rtw_dev_unload: driver not in IPS
[    7.042085] ==> rtl8188e_iol_efuse_patch 
udhcpc: started, v1.29.0.git
udhcpc: sending discover
udhcpc: sending discover
udhcpc: sending discover
udhcpc: no lease, forking to background
Terminated

Looking at both I think I have a different wifi chip in my camera. Linux is loading  RTL871X: and on the pcb I have an RTL8189ETV chip.

Camera hardware: Dafang DF3, pcb DF3-IFM01 V1.4
Wifi Chip, RTL8189ETV
![WifiChip](https://user-images.githubusercontent.com/50568647/57600002-297f5900-7561-11e9-98dc-8f5d3f44eb2b.JPG)

Could someone please say if I am on the right track or not? If it is a different driver, how would I proceed on loading a different one during boot up?

**Comment by jmtatsch** [comment]
Hmm, really may be a new board revision.
Try loading the drivers of xiaofang or wyzecam here https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/6a11d6354db4937df71acc7203f1d9d8ef481be8/firmware_mod/run.sh#L117
