### ISSUE TITLE
Can camera be used as USB camera?

### ISSUE THREAD

**Issue by raptor59** [EliasKotlyar/Xiaomi-Dafang-Hacks#1049]
Hello, wondering whether i can use this camera directly connecting it to computer through USB. No network, just pure usb camera with night vision capabilities. Want to use it to monitor my 3d printer and connect it to raspberry pi with repetier server installed. But for this reason - it has to be USB camera, not some wifi thing. Thanks

**Comment by jgwinner** [comment]
The Pi is only USB2, so you might get higher bandwidth out of WiFi. After having said that, my understanding is No. I believe the USB is only for powering it.

        == John ==

**Comment by Combie81** [comment]
No it cant output through USB - it is only indeed for power..

**Comment by raptor59** [comment]
Thank you for the answers :)

**Comment by gadget78** [comment]
not sure i can comment on closed issues...
but this is wrong info, you CAN use these camera variants as a simple USB camera .. 
wyze have officially released  
['demo.bin' firmware..](https://support.wyzecam.com/hc/en-us/articles/360041605111-Webcam-Firmware-Instructions)
but is DOES work well :) (on Neos) and can be flashed back again easily the same way... with demo.bin

no configurable options ref. nightvision etc.. but HD USB yes ..

**Comment by ragde22** [comment]
> not sure i can comment on closed issues...
> but this is wrong info, you CAN use these camera variants as a simple USB camera ..
> wyze have officially released
> ['demo.bin' V2Webcam.zip firmware..](https://support.wyzecam.com/hc/en-us/articles/360041605111-Webcam-Firmware-Instructions)
> but is DOES work well :) (on Neos) and can be flashed back again easily the same way... with demo.bin
> 
> no configurable options ref. nightvision etc.. but HD USB yes ..

It will be nice if they can add this feature to this firmware, USB from the (Usb A port) and with auto-night.
I had to move to the one you mentioned, but as you know, it doesn't have the night vision and I am also looking for that just like @raptor59 for my 3D Printer monitor!! :(
