### ISSUE TITLE
Update notifications / autoupdate

### ISSUE THREAD

**Issue by wojtulab** [EliasKotlyar/Xiaomi-Dafang-Hacks#105]
Could you enable notification in www/status.cgi with info about new features is available?

fo example: 
`Xiaomi-Dafang-Hacks is up to date / download new files.`

**Comment by EliasKotlyar** [comment]
I think thats a good idea. Can someone try to compile git? If it would be there, it would be easy to implement a check and also a complete "update" functionality

**Comment by jmtatsch** [comment]
New update functionality is there.
