### ISSUE TITLE
AutoUpdate no longer functional; SSL out of date

### ISSUE THREAD

**Issue by mikeage** [EliasKotlyar/Xiaomi-Dafang-Hacks#1052]
### Description

The version of curl used by the autoupdate can no longer reliably connect to github (it seems like they may have a few servers that work, but generally it fails rather quickly

### Evidence
Version:
```
[root@dafang2:sdcard]# cat /system/sdcard/.lastCommitDate
2019-02-23T15:12:19Z
```

Auto Update:
```
[root@dafang2:sdcard]# ./autoupdate.sh -u FOO:BAR -v -s
Starting AutoUpdate
Getting list of remote files.
Number of file to update 192
Can not get remote file https://raw.githubusercontent.com/EliasKotlyar/Xiaomi-Dafang-Hacks/master/firmware_mod/autoupdate.sh, exiting.
```

Direct curl:
```
[root@dafang2:sdcard]# curl https://raw.githubusercontent.com/EliasKotlyar/Xiaomi-Dafang-Hacks/master/firmware_mod/autoupdate.sh
curl: (35) error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number
```

**Comment by JustinHoeky** [comment]
Try the following command:
curl --insecure https://raw.githubusercontent.com/EliasKotlyar/Xiaomi-Dafang-Hacks/master/firmware_mod/autoupdate.sh

Might work, but i'm not sure

**Comment by mikeage** [comment]
It will not. `--insecure` tells curl to ignore invalid certificates, but not to ignore the SSL handshake required. 

It seems like we need a new version of curl/openssl

**Comment by mikeage** [comment]
never mind; I forgot that I'd firewalled my devices from connecting to the internet. Duh.
