### ISSUE TITLE
Restoring Xiaofang 1s Original Firmware

### ISSUE THREAD

**Issue by jshplayer** [EliasKotlyar/Xiaomi-Dafang-Hacks#1056]
First download: https://www102.zippyshare.com/v/OhOnBJg6/file.html

Trust me i already tried this firmware and initially had issues still but it's the only one that finally worked.

Save it as demo.bin on the root as normal AFTER a fresh wipe of the SD card using SD Card Formatter.

Hold the setup button as normal and power it up with the SD card inserted, let go after the light turns blue. Now at this point the usual status disappears and you have to go by sound and time. Wait for it to go orange for a sec and it may make a brief clicking noise again - 1 second after this point hold the setup button again for a couple of seconds (even if the status light is blank) it should make the little chinese voice sound, if not let go and hold it down again for a couple of seconds, at this point start again if you don't hear it.

After the chinese voice, point it at the Mi app QR code as normal and although the lights may not show any status, it may flash blue or go solid blue but let the app setup continue and it should link up. This took me a few attempts but now i can get it every time, after it's linked you can re-enable the status light and update the official firmware. Things go back to normal from there.

I used an 8GB and 32GB sd card formatted in fat32 without issues, but formatting it after each attempt helped as the process stuffed up sometimes after just deleting the files. Remember even if the light is out it's still technically working just keep trying.

**Comment by farrokh19** [comment]
MAC starting with 32 or 78?

**Comment by alinelena** [comment]
see #988

**Comment by xandeinfohouse** [comment]
for the camera xiaofang worked well thank you already for dafang did not work I'm trying for months thank you

**Comment by GreypaX** [comment]
its work! i have **xiaofang S1 T20L**
