### ISSUE TITLE
No version after update

### ISSUE THREAD

**Issue by S474N** [EliasKotlyar/Xiaomi-Dafang-Hacks#1057]
After update there is no version info in footer. If I tried cat via SSH, there is also no info in file. Also in System is no info.

Model | Xiaomi Dafang
Kernel Version | #21 PREEMPT Thu Oct 19 11:38:16 CST 2017
Bootloader version U-Boot 2013.07-gc78f10c-dirty (Jul 21 2018 - 20:20:37)

CMDline:
console=ttyS1,115200n8 mem=87M@0x0 ispmem=9M@0x5700000 rmem=32M@0x6000000 init=/linuxrc rootfstype=squashfs root=/dev/mtdblock2 rw mtdparts=jz_sfc:256k(boot),2048k(kernel),3392k(root),640k(driver),4736k(appfs),2048k(backupk),640k(backupd),2048k(backupa),256k(config),256k(para),-(flag)

**Comment by S1ou** [comment]
Same issue here!

**Comment by martinschm** [comment]
Same here. Also no video shown.

**Comment by martinschm** [comment]
I reloaded the page, Its working now. Video is shown, menu items are clickable and on the top left it now shows my custom name instead of "Dafang Hacks" as a name. Version number is also shown "2019-05-21T19:52:43Z"

**Comment by S474N** [comment]
Updated to new version and everything is OK.

Dafang Hacks Version: 2019-06-09T17:19:16
