### ISSUE TITLE
ability to upload to an s3 bucket

### ISSUE THREAD

**Issue by RichardHerold** [EliasKotlyar/Xiaomi-Dafang-Hacks#1058]
### Description

The ability to upload video files as objects to a generic s3 bucket would be useful for secure long term cloud storage.

**Comment by saipsa** [comment]
PRs are welcome :)

**Comment by hamid-elaosta** [comment]
This sounds like something that would be better handled by offloading to a more powerful machine on your network and then going from there. I would think uploading straight to S3 per-camera is probably going to push its little hardware a little too hard.
