### ISSUE TITLE
Using CFW without SD card - rootfs does not fit to NAND

### ISSUE THREAD

**Issue by danergo** [EliasKotlyar/Xiaomi-Dafang-Hacks#1059]
Hello, I'm using a Dafang camera with 128MB RAM with this hack.

I wanted to use it without any SD card.

So far I've succeed:
-modifing & building uboot to boot from nand (uEnv*.txt is not needed on SDCard)
-flashed uboot to /dev/mtd0
-compiled my own version of kernel (which is not changed, just made sure that it could be compiled)
-flashed this kernel to /dev/mtd1 and changed uboot according to this. Now kernel_* files are not needed to be on SDCard.
-created squashfs from the rootfs which would normally goes onto SDCard. It is about 13MB.

However I'm not succeed in flashing the rootfs onto NAND.
Flashing it onto /dev/mtd2 stops and reports out-of-space error around 3.3 MB:
```
dd: writing '/dev/mtd2': No space left on device
6785+0 records in
6784+0 records out
3473408 bytes (3.3MB) copied, 12.851148 seconds, 263.9KB/s
```

mtd4 has a bit more space but I'm really curious of how the original idea was designed.
Shall I take apart the rootfs and split it between mtd2, mtd3 and mtd4?
As all other mtds are made for backups and configs.

**Update1:**
"jz_sfc" contains only 16MB space. I'm wondering how the original firmware fit on such a small flash.
Any ideas?

What would you recommend to flash the rootfs to NAND?

**Comment by EliasKotlyar** [comment]
Hello @danergo 

Basically: You will need to "optimize" the CFW and remove all the unnecessary features out of the firmware. Its a big pain, and thats why the original firmware is working only trough cloud. There are some firmwares which fit the NAND like the Sannce Devices. However they have stripped a lot of functionality.

I would suggest buying a cheap 3$ MicroSD instead of trying to make it fit. Its not worth the effort, as long as you are not a vendor of this devices.

**Comment by aenertia** [comment]
Question - why not strip out everything but Wifi and boot from NFS/Network ? This should be trivial and allow for centralized control/storage upgrade of multiple cameras.

**Comment by danergo** [comment]
Uboot is not able to handle the wifi. So to boot from NFS, first you would
boot into your small Linux which would need to initiate the wlan chip and
connect to your ap. Then the Linux can mount the nfs to somewhere, but this
I would not 'booting'.

Still might be interesting, but it is not that easy to shrink Linux below
16m either.

Dafang does not have ethernet port by default.

If once uboot will handle wlan, this might worth the effort.

**Comment by aenertia** [comment]
Not suggesting to boot from tftp via uboot. Just minimal kernel/initramfs with hook for wifi and nfs root pivot

**Comment by danergo** [comment]
Hm, interesting suggestion. So the whole rootfs would come from NFS, still
the challenging part would be to shrink the Linux initramfs + uboot +
kernel to fit into 16M.

Would you mind helping me to achieve this? I need to investigate on how to
create an initramfs which can handle the connection.

I already created an uboot which boots from nand, but if you insert an SD
card it would be preferred, just to not brick anything.

**Comment by aenertia** [comment]
I have a couple of unoppened S1's and I don't want to sacrifice the good SD cards I have ; but I also have a severe lack of time right now. 

What would be helpful is a familiar build system like openwrt or just some ansible playbooks
