### ISSUE TITLE
How to integrate stream in a webplayer?

### ISSUE THREAD

**Issue by haexhub** [EliasKotlyar/Xiaomi-Dafang-Hacks#1060]
### Description

I would like to integrate the stream in my webapplication, but not sure how to achieve this. Natively its not possible to stream rtsp in browsers. But there are providers out there, which provide a webservice, where they convert the rtsp stream to a video format, browsers can work with. But I would like to do this on my own. Any Ideas how to do this?

**Comment by danergo** [comment]
https://janus.conf.meetecho.com

**Comment by beankylla** [comment]
Motioneyeos does this. I think its mostly open source.

**Comment by jmtatsch** [comment]
Can't the HLS stream be used? See also the example hls.js web player.  Watch out, this requires the rtspserver to be started with the -S flag.
