### ISSUE TITLE
Home Assistant - still getting breaking changes notification

### ISSUE THREAD

**Issue by ivanovd** [EliasKotlyar/Xiaomi-Dafang-Hacks#1061]
I am still getting breaking changes notifications in Home Assistant 0.93 although I have the latest firmware on the camera and I have removed the icon attribute from mqtt-autodiscovery.sh

```
Your configuration contains extra keys that the platform does not support.
Please remove [device]. 
Configuration source: MQTT (topic: 'homeassistant/camera/dafang/motion_snapshot/config'). 
Offending data: {"name": "dafang motion snapshot", "unique_id": "<redacted>", "device": {"identifiers": "34ce00aff79d", "connections": [["mac", "34:ce:00:af:f7:9d"]], "manufacturer": "Xiaomi", "model": "Dafang", "name": "Xiaomi Dafang", "sw_version": "Dafang Hacks"}, "topic": "<redacted>", "platform": "mqtt"}
```

```
Your configuration contains extra keys that the platform does not support.
Please remove [icon]. 
Configuration source: MQTT (topic: 'homeassistant/binary_sensor/dafang/motion/config'). 
Offending data: {"name": "dafang motion sensor", "unique_id": "<redacted>", "device": "<redacted>", "icon": "mdi:run", "state_topic": "myhome/dafang/motion", "device_class": "<redacted>", "platform": "mqtt"}
```

Are these attributes present somewhere else as well?

**Comment by ivanovd** [comment]
Was anybody able to solve this?

**Comment by kpcz** [comment]
HIi, had similar issue.  Install https://mqtt-explorer.com/ connect to your mqtt and delete retained messages from cameras. I had a lot of them there.

**Comment by ivanovd** [comment]
@kpcz , thanks mate, you were right, there were few retained messages. I deleted them and I no longer have the warning.

Thanks again

**Comment by spattinson** [comment]
> HIi, had similar issue. Install https://mqtt-explorer.com/ connect to your mqtt and delete retained messages from cameras. I had a lot of them there.

thanks, i struggle with retained msgs polluting my env and causing _2 _3 suffixes etc when i change config. i am moving away from mqtt and use native api with esphome instead.
