### ISSUE TITLE
Night mode issue

### ISSUE THREAD

**Issue by zlayabelka20** [EliasKotlyar/Xiaomi-Dafang-Hacks#1062]
Xiaomi Xiaofang 1s camera.

Camera switches form day mode to night without any problems. But it doesn't switch to day mode until I turn off and on "Auto Night Detection".

please help

**Comment by Howaner** [comment]
Same problem with Xiami Dafang

**Comment by Howaner** [comment]
Now it's working. Disabling "IR LED" fixed it.
