### ISSUE TITLE
The telegram feature doesn't seems to work.

### ISSUE THREAD

**Issue by bchiu2000** [EliasKotlyar/Xiaomi-Dafang-Hacks#1063]
I created the Telegram bot and got the chatuserid and token.  I then typed that into the conf file in the SD card.  But the telegram bot isn't responding.  Is there anything else needed to be done?

**Comment by boomyville** [comment]
Make sure the telegram service is on (check by logging into camera via web browser)

**Comment by root75** [comment]
You can test the telegram message with this command

[root@DAFANG:~]# /system/sdcard/bin/telegram m test

**Comment by rafalefighter** [comment]
for me also telegram doesn't work at first ( for image mode ). I was able to manually send a message using the command "/system/sdcard/bin/telegram m message" but when it executes from detectionOn.sh script it didn't work. but after I enabled the swap on run.sh telegram working perfectly now and already flooded my group with photos taken after motion  :-) extremely nice feature

**Comment by muster021** [comment]
I have the same problem. The command "/system/sdcard/bin/telegram m message" works great, but detection does not send any messages. I've enabled swap in run.sh but that did not fix it. Any other ideas?

**Comment by rafalefighter** [comment]
Try to change the message format to text in a motion configuration file and check whether it works. I think the issue only occurs while you try to send an image or video. For me, text and image always work but video fails every time. This seems like a memory issue with the 64mb model. Additionally, you can check the /var/log files for telegram and rstp server log files.

**Comment by jmtatsch** [comment]
Vídeo doesnt work. Haven’t been able to encode it in a way that telegram can display it.

**Comment by rafalefighter** [comment]
oh, that's the case. I thought it because of memory issue while converting.  However, image is more useful than video as I guess. Even though it flooding my group with images for every motion detected. Really useful feature

**Comment by bchiu2000** [comment]
Argh.. I got this

login as: root
root@192.168.1.29's password:
[root@DAFANG:~]# system/sdcard/bin/telegram m test
-sh: system/sdcard/bin/telegram: not found

I am sure I have telegram service running. what should I do?

**Comment by rafalefighter** [comment]
/system/sdcard/bin/telegram m test

**Comment by bchiu2000** [comment]
Ah.. thanks for pointing that out.

but still didn't work.

[root@DAFANG:~]# /system/sdcard/bin/telegram m test
: not foundard/bin/telegram: /system/sdcard/config/telegram.conf: line 4:
Sending message: test

this is my telegram.conf

############################################################

# edit this file and move it to /system/sdcard/config/telegram.conf #

############################################################



# Add your Telegram credentials here (these are just examples)

apiToken="723496616:AAXXXXXXXXXXXXZjfvJv7pm0mchUxc"

userChatId="8XXXXXX164"

(I masked my chatid and token)

**Comment by bchiu2000** [comment]
is there something wrong with my telegram.conf?

**Comment by bchiu2000** [comment]
Ah.. okay. I got it.  I need to delete the # comment out lines.  

Now my telegram gets the message "test" when I enter /system/sdcard/bin/telegram m test.

But if I try to message the Bot from my app like /start or /mem, he won't reply.

**Comment by bchiu2000** [comment]
Anyone can help me out?  I get "test" when I enter /system/sdcard/bin/telegram m test.

But if I try to message the Bot from my app like /start or /mem, he won't reply.  and no notification from him.

**Comment by maddoglee** [comment]
just wanted to add another thing which a noobie would need to know. 

Rename  /system/sdcard/config/swap.conf.dist to swap.conf
...and also change the value in the swap.conf from false to true. 

Images started working for me after setting the swap file up properly. 

if you are getting 0 for swap when you message /mem then the swapfile isn't working. As soon as I got the swapfile working, it said it was using 288. 

Hope this helps someone.
