### ISSUE TITLE
Issue while falshing hack, Xiaofang

### ISSUE THREAD

**Issue by RosetteOnFire** [EliasKotlyar/Xiaomi-Dafang-Hacks#1064]
No flashing possible!

Setting:

Xiaofang Cam with MAC: 34... @ Firmware 3.0.3.56

Mi App up to date

SD Card with FAT32 @ 100 Mb Partition

[used Hack](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/raw/master/hacks/cfw/xiaofang/cfw-1.0.bin)

### Description

I cant flash the "demo.bin". I used the TuT for flashing the hack but when the SD-Card insert booting will cause only a normal boot with the connection to th Mi App. While pressing the " Setup" Knob only a normal boot will start, the leds act normal.

### What did you do to debug the issue

I tried to use fang hack (https://github.com/samtap/fang-hacks). it runs perfectly. i formated the SD-Card serveral times with different settings but same result.

**Comment by jmtatsch** [comment]
You seem to be using an old Xiao fang. Thi repo is for the new architecture generation only.
