### ISSUE TITLE
New model (Sannce I141CB clone)

### ISSUE THREAD

**Issue by naong** [EliasKotlyar/Xiaomi-Dafang-Hacks#1066]
I bought an IP CAM based on an Ingenic T20 processor. I think this is a clone of the Sannce I141CB model. I cannot boot from an SD card. I think it needs a custom boot loader.

I connected to the cam using a serial connection and collected the following information.

Aliexpress Link: https://www.aliexpress.com/item/720P-HD-IR-Night-Vision-wireless-IP-Security-Camera-camaras-de-seguridad-cctv-system-easycap-Free/32315322074.html

Sensor Resolution: 1080p
Processor: Ingenic T20
Memory: 64M
Sensor: sc2135 [sensor_sc2135.zip](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/files/3264126/sensor_sc2135.zip)
Device Firmware Version: t2.9.1.17.4E
Device Embeded Web UI Version: 12.9.10.4-12-en
Working login: root/hslwificam

[cat mtd.txt](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/files/3261214/cat.mtd.txt)
> '# cat mtd
>dev:    size   erasesize  name
>mtd0: 00040000 00010000 "boot"
>mtd1: 00220000 00010000 "kernel"
>mtd2: 00340000 00010000 "root"
>mtd3: 00240000 00010000 "root"
>mtd4: 00010000 00010000 "factory"
>mtd5: 00010000 00010000 "param"

dump files: [sannce_clone_dump.zip](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/files/3261218/sannce_clone_dump.zip)

[cat proc cmdline.txt](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/files/3261210/cat.proc.cmdline.txt)
>'# cat cmdline
>console=ttyS1,115200n8 mem=32M@0x0 ispmem=8M@0x2000000 rmem=24M@0x2800000 init=/linuxrc rootfstype=squashfs root=/dev/mtdblock2 rw mtdparts=jz_sfc:256k(boot),2176k(kernel),3328k(root),2304k(root),64k(factory),64k(param) quiet

[bootlog.log](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/files/3261216/bootlog.log)
[kmsg.log](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/files/3268428/kmsg.log)

**Comment by ejalal** [comment]
Hi, did you manage to use the firmware on this model ?

Just curious because I bought another model https://www.aliexpress.com/item/32895308558.html but not sure if I can flash it.
