### ISSUE TITLE
Telegram - More than one chatid

### ISSUE THREAD

**Issue by DerMilchShake** [EliasKotlyar/Xiaomi-Dafang-Hacks#1069]
Hi,

is it possible to configure more than one chat id as receiver for the telegram function?
What should i change to setup more receivers without creating a telegram group.

Regards

**Comment by rafalefighter** [comment]
you can write a small script with multiple chat IDs on it and run it from detectionOn.sh. but this may increase the execution time of detectionOn.sh script. correct me if I'm wrong.

**Comment by ex725** [comment]
installed in me and my wife
we created a common group.
but only I can control it.
How do I add multiple chat-id?
