### ISSUE TITLE
Any planned support for new XiaoVV cameras ?

### ISSUE THREAD

**Issue by Lefuneste83** [EliasKotlyar/Xiaomi-Dafang-Hacks#1081]
Hi there

Has anyone had the chance to get a look at these new cameras. They seem quite promising but I am afraid they are quite different from the Dafang/Xiaofang.

https://www.aliexpress.com/item/HOT-Xiaomi-XiaoVV-Smart-Panoramic-IP-Camera-HD-1080P-360-Panoramic-AI-Humanoid-Detection-Night-version/33028892108.html

https://www.aliexpress.com/store/product/HOT-Xiaomi-Xiaovv-Outdoor-Panoramic-Camera-Surveillance-camera-Wireless-WIFI-High-definition-Night-vision-With-Mijia/2953070_33038150822.html

**Comment by djansen1987** [comment]
Hi Lefuneste83,

Any luck with your XiaoVV ? I got one for some time now and really mis the rtsp functionality to hook it up to my home assistant or iSPY
