### ISSUE TITLE
Error: A network protocol error occurred when communicating with the broker.

### ISSUE THREAD

**Issue by marrobHD** [EliasKotlyar/Xiaomi-Dafang-Hacks#1082]
Today I was trying to get my wyzecampan in HomeAssistant working but I get some errors:

mqtt-control wont start: https://mycloudstorage.tk/s/NMPLpByXb2XKCG6/preview

My mqtt.conf
```
############################################################
# edit this file and move it to /system/sdcard/config/mqtt.conf #
############################################################

export LD_LIBRARY_PATH='/thirdlib:/system/lib:/system/sdcard/lib'

# Options for mosquitto_sub & mosquitto_pub
USER="Marlon"
PASS="Mar32456gvlon"
HOST="192.168.178.56"
PORT="1884"

# Define a location
LOCATION="camera"

# Define device name
DEVICE_NAME="wyzepan"

# Define the base topic used by the camera
# send a message to myhome/dafang/set with the payload help for help.
# Results will be placed in myhome/dafang/${command} or topic/dafang/error - so please subscribe topic/dafang/# for testing purposes
TOPIC="$LOCATION/$DEVICE_NAME"

# Define an autodiscovery prefix, if autodiscovery is desired:
AUTODISCOVERY_PREFIX="homeassistant"

# Define additional options for Mosquitto here.
# For example --cafile /system/sdcard/config/DST_Root_CA_X3.pem --tls-version tlsv1
# or use a special id to connect to brokers like azure
MOSQUITTOOPTS="-V mqttv311"

# Add options for mosquitto_pub like -r for retaining messages
MOSQUITTOPUBOPTS="-r"

# Send a mqtt statusupdate every n seconds
STATUSINTERVAL="10"

# Publish and update the light dependant resistor (LDR) status or not. The
# default value if the variable is not set is to send it. This might be useful
# for owners of devices that lack the hardware sensor to avoid publishing
# rubbish.
SENDLDR="true"
```

If I try to run the mqtt-autodiscovery.sh manualy i get this error:
[root@DAFANG:scripts]# ./mqtt-autodiscovery.sh
Error: A network protocol error occurred when communicating with the broker.
Error: A network protocol error occurred when communicating with the broker.
Error: A network protocol error occurred when communicating with the broker.
Error: A network protocol error occurred when communicating with the broker.
Error: A network protocol error occurred when communicating with the broker.
Error: A network protocol error occurred when communicating with the broker.
Error: A network protocol error occurred when communicating with the broker.
Error: A network protocol error occurred when communicating with the broker.
Error: A network protocol error occurred when communicating with the broker.
Error: A network protocol error occurred when communicating with the broker.
Error: A network protocol error occurred when communicating with the broker.
Error: A network protocol error occurred when communicating with the broker.
Error: A network protocol error occurred when communicating with the broker.
Error: A network protocol error occurred when communicating with the broker.
Error: A network protocol error occurred when communicating with the broker.
Error: A network protocol error occurred when communicating with the broker.
Error: A network protocol error occurred when communicating with the broker.

Thanks for help
~Marlon

**Comment by marrobHD** [comment]
Now I have removed -V mqttv311 it gives me another errors. It shows Success but nothing is happened in homeassistant and mqttextplorer:
```
[root@DAFANG:scripts]# ./mqtt-autodiscovery.sh
Error: Success
Error: Success
Error: Success
Error: Success
Error: Success
Error: Success
Error: Success
Error: Success
Error: Success
Error: Success
Error: Success
Error: Success
Error: Success
Error: Success
Error: Success
Error: Success
Error: Success
```

**Comment by marrobHD** [comment]
Autodiscovery wont work

**Comment by jokerigno** [comment]
I have the same issue (mqtt control doesn't work). Did you managed it?

**Comment by marrobHD** [comment]
Nope
