### ISSUE TITLE
Flashing custom firmware on XiaoFang camera (3.0.3.56)

### ISSUE THREAD

**Issue by JBS5** [EliasKotlyar/Xiaomi-Dafang-Hacks#1084]
I realise this is not the first issue about this problem, but I have tried several solutions found in other issues, but still no luck flashing my XiaoFang (I guess 1S).

- (Full) Format a 512MB partition on a SD card to FAT32 and copied the to demo.bin renamed file to it
- Press the setup button (I hear it clicks) and connect power, holding setup buton for 10+ seconds.
- LED blinks blue/orange for a few seconds and after that it blinks blue.
- Wait for at least 3 minutes. LED keeps blinking blue.

After waiting 10+ minutes, I see on the SD card the folders 'record', 'time_lapse' and a file .record_auto_list (and demo.bin) so I guess the flashing process did not start or even complete?

- Firmware 3.0.3.56 is on the camera now: Tried downgrading to firmware demo_5.5.1.194 from the firmware_original/dafang folder as I read in another issue, flash did not work either
- Tried another SD card, an older 8GB and a 32GB Samsung 32GB Evo Plus.
- Tried the flash procedure for at least 5 times.

Any further tips to flash the firmware on this XiaoFang camera?

SD card afther trying to flash demo.bin:
![image](https://user-images.githubusercontent.com/25594213/60189735-b5a7c000-9831-11e9-910e-01ce75f57698.png)

Partition on the SD card:
![image](https://user-images.githubusercontent.com/25594213/60189761-c0faeb80-9831-11e9-97e8-682a35101483.png)

XiaoFang camera information:
![image](https://user-images.githubusercontent.com/25594213/60195626-af1e4600-983b-11e9-973c-7ea44ab329c8.png)

**Comment by DarioB92** [comment]
I flashed the custom firmware on similar camera. On the fat32 partion copy the custom firmware (cfw 1.0) and rename it demo.bin . It has to be the only file. Insert sd, hold the button and turn it on. When the blue led turns on, you can stop push, if I'm right, if the firmware is found and correctly checked, both leds are solid on, until reboot. Turn off the camera and remove the sd. Power on without sd. If during the boot the blue led is on for 5 seconds, the cfw is correctly flashed.
If you have problems, there are telnet terminals exposed, so you could know what is going on.

**Comment by JBS5** [comment]
@DarioB92 After pressing the Setup button, connect power and hold Setup button, the LED is and keeps solid yellow. Never turns blue. After 20+ seconds the XiaoFang starts speaking Chinese (repeatedly the same text).

**Comment by JBS5** [comment]
Maybe it is not 1S version, I succesfully installed the old hack https://github.com/samtap/fang-hacks and looking to a status page right now:

![image](https://user-images.githubusercontent.com/25594213/60299815-e4a35c00-992d-11e9-8194-9feb5285e537.png)
![image](https://user-images.githubusercontent.com/25594213/60299878-0997cf00-992e-11e9-94a4-089aa0bf289f.png)

The red error is there because I extended the data partition I guess (using the provided option to do that).

Not sure if there is any way to update to the newest firmware at this point?

**Comment by DarioB92** [comment]
Yesterday I checked, during flash both LEDs (red and yellow) are solid.
On mine it's specified 1s on the sticker.

**Comment by 4rianton** [comment]
Hi @JBS5, did you stick with the old hack, or were you able to find some success with this one?

**Comment by JBS5** [comment]
@4rianton That's a few years ago, not sure which version is on that Xiaofang at this point of thime, but the Information pages shows me:

![image](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/assets/25594213/da34a56e-a92e-4266-ba5a-4ee2bd0751e7)

![image](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/assets/25594213/27c97df9-d4d5-4d19-94c6-26feccc2bd08)

Seems to be a EliasKotlyar version:

![image](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/assets/25594213/f7fcd496-e0da-4cb1-a413-289abe46f9ab)

**Comment by 4rianton** [comment]
Super, I suppose you don't remember how you got around to resolving the issues you were having? 

I opened my camera and it seems like it's the ARM version.. not sure if there's any possibility of installing this one on it. 

I have a dafang camera that has this one and it works flawlessly with Homesssistant.

**Comment by JBS5** [comment]
To be honest, I now doubt it was one of my cameras for which I had created
this issue.

Op wo 5 jun 2024 22:42 schreef 4rianton ***@***.***>:
