### ISSUE TITLE
Trouble flashing Neos Smartcam

### ISSUE THREAD

**Issue by stephenjsweeney** [EliasKotlyar/Xiaomi-Dafang-Hacks#1085]
I just got my camera today, and am attempting to flash the firmware.

I've taken a 16GB micro SD card, formatted it to fat32, created a 512MB partition, and then loaded the firmware onto it:

https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/raw/master/hacks/cfw/wyzecam_v2/cfw-1.1.bin

I've renamed this to demo.bin.

I've then inserted the SD card (it doesn't seem to go in all the way?), held the setup button, and inserted the USB cable.

The light is yellow to begin with, then begins flashing yellow. I then hear "Ready to connect".

The light never turns blue for me. Is the SD card (16GB partitioned to 512MB) too large? Anything else I might be doing wrong?

**Comment by matbrewer396** [comment]
have a look at https://ryanfitton.co.uk/blog/install-dafang-custom-firmware-to-neos-smartcam/

**Comment by stephenjsweeney** [comment]
Unfortunately, that's the guide that I was following (and the one that prompted me to buy the camera).

I'm sort of worried that the cameras have now started shipping with firmware that is patched against the hack. But perhaps I'm not flashing the demo.bin file right. Maybe a 16GB SD card is too big.

**Comment by 6a61636b** [comment]
Hi @stephenjsweeney 
Any luck? I have a SmartCam on order and will attempt tomorrow, report back.

Neo's lead developer commented [here](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/pull/964#issuecomment-494263398) that he thinks this project is cool, so blocking it seems unlikely but you never know!

**Comment by stephenjsweeney** [comment]
None at all. I've tried for a few hours now. Either I'm doing it wrong (I've followed the instructions to the letter, including blog, and videos) and can't get the firmware to flash.

Chances are I'm going to return the camera.

**Comment by daaaaan** [comment]
Hey, I flashed 2 last night with the same 512 partition. I formatted it FAT16 from linux. I never got the ready to connect voice prompt. Might be your card isn't inserted. I had to mash it in with a fingernail..! 

I used a 32gb card so it's not that :)

**Comment by stephenjsweeney** [comment]
How far in did you need to push it? 

When I've tried, the card is still protruding a little bit at the bottom. Was it almost flush against the bottom or the unit, or were there a few millimetres left? 

Could you take a photo to show me, so I can tell if mine just isn't going in all the way?

**Comment by 6a61636b** [comment]
@stephenjsweeney my camera arrived today, I managed to flash the firmware successfully. 

The SD card should "click" when you insert it all the way, I had to use a paperclip. Photos [here.](https://imgur.com/a/n4lUZiC)

**Comment by stephenjsweeney** [comment]
Ugh. Yes, it was just the sd card not inserting properly. It took quite an effort to get it in and even more to get it out. Maybe bad design or a dodgy assembly (or probably just me being crap!).

At any rate, the flashing worked and the camera is all up and working.

Many thanks, all. Closing this now.
