### ISSUE TITLE
Da fang fail to update firmware

### ISSUE THREAD

**Issue by ranrinc** [EliasKotlyar/Xiaomi-Dafang-Hacks#1088]
Da-fang 1080 camera,
FW: 5.5.1.285
CFW bin 1.2 

My procedure:
1. put demo.bin into blank MicroSD (formated exFat)
2. put the microSD into the camera (no power)
3. push the reset + plug in the power
4. keep push until blue + orange and release
5. Blue led blink and become solid
6. led blue keep on solid after 5 minute nothing.

Need help on this issue..

**Comment by rcpao** [comment]
You must format with FAT32 (which turns out to be FAT16 for my 2GB card) if you are trying to flash demo.bin.  See https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/hacks/install_cfw.md step 2.

**Comment by leosegovia** [comment]
Same issue here.
Wyzecam v2

1. Download the CFW-Binary for your Camera from https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/raw/master/hacks/cfw/wyzecam_v2/cfw-1.1.bin 

2. Format your microSD to FAT32. (16GB SD card with single 512MB partition | _also tried with 16GB partition_)
3. Copy the CFW-Binary from step 1 to the formatted microSD card and rename it to "demo.bin" __(no files on SD)__
```
$ ls -l <sd_card> 
total 0
```
4. Remove the power cable from the camera and plug the microSD card into the camera
5. Hold down the setup button on the camera while
6. Plugging in the USB power cable
7. Keep the setup button pressed for another 10 seconds __(light goes blue)__
8. Wait until the firmware has finished flashing __(like 3 minutes | light goes solid orange)__
9. Remove the microSD card and power up the camera __(light remains solid orange)__

Any help is appreciated if you´ve run into the same issue

**Comment by ersaguns** [comment]
hello, i have dafang df3 with first mac number 78 and have encounter this same issue.
i cannot install updates firmware or dowgrade it.
now it stuck at steady yellow whatever i do, please if you have any solution

**Comment by jmtatsch** [comment]
Build a newer custom firmware based on a newer official firmware.

**Comment by ersaguns** [comment]
> You might want to build a newer custom firmware based on a newer official firmware.

is it because my dafang cannot accept the firmware? but i do flash my other dafang and it works.
only this one stuck at yellow light not blinking, and no matter what i do, it keeps yellow no sound, no blink

**Comment by ManuIB** [comment]
> > You might want to build a newer custom firmware based on a newer official firmware.
> 
> is it because my dafang cannot accept the firmware? but i do flash my other dafang and it works. only this one stuck at yellow light not blinking, and no matter what i do, it keeps yellow no sound, no blink

I have the same problem than you, do you have any solution or someone?
