### ISSUE TITLE
Script to reconnect wifi

### ISSUE THREAD

**Issue by amagnolo** [EliasKotlyar/Xiaomi-Dafang-Hacks#1089]
### Description

I had the problem described in #77 , so I wrote a script to restart the wifi connection when it was down. The interesting thing is that after having scheduled the script to run hourly, the wifi did not disconnect anymore; probably the router "ping" at the start is enough to keep the connection alive.

### What did you do to debug the issue

This is the script I used. Copy and paste using
vi /system/sdcard/config/cron/periodic/hourly/network_reboot
change the pinged ip with the one from your router or gateway.

```
#!/bin/sh
if ping -q -c 1 -W 1 192.168.1.1 >/dev/null; then
  echo "`date` network is up" >> /system/sdcard/log/network_reboot.log
else
  echo "`date` network is down - trying to bring it up..." >> /system/sdcard/log/network_reboot.log
  ifconfig wlan0 down
  sleep 20
  ifconfig wlan0 up
  sleep 60
  if ping -q -c 1 -W 1 192.168.1.1 >/dev/null; then
    echo "`date` network is back up" >> /system/sdcard/log/network_reboot.log
  else
    echo "`date` network is still down - REBOOT!" >> /system/sdcard/log/network_reboot.log
    reboot
  fi
fi
```

### Contribute Back

This could be useful for other people affected by #77 or #158, or it could be integrated as an enhancement.

**Comment by msmarks** [comment]
> #!/bin/sh
> if ping -q -c 1 -W 1 192.168.1.1 >/dev/null; then
>   echo "`date` network is up" >> /system/sdcard/log/network_reboot.log
> else
>   echo "`date` network is down - trying to bring it up..." >> /system/sdcard/log/network_reboot.log
>   ifconfig wlan0 down
>   sleep 20
>   ifconfig wlan0 up
>   sleep 60
>   if ping -q -c 1 -W 1 192.168.1.1 >/dev/null; then
>     echo "`date` network is back up" >> /system/sdcard/log/network_reboot.log
>   else
>     echo "`date` network is still down - REBOOT!" >> /system/sdcard/log/network_reboot.log
>     reboot
>   fi
> fi

It works perfectly. I don't have to climb to the roof to restart my camera.
