### ISSUE TITLE
some troubles - UI - unable to load image - logs etc

### ISSUE THREAD

**Issue by MkLHX** [EliasKotlyar/Xiaomi-Dafang-Hacks#1090]
i search on issues historic if i can help me with troubles after update CFW on my Xiaomi Dafang camera. But with no success...
on start i just update the firmware as describe here [ici](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/hacks/install_cfw.md#installation-of-the-new-firmware)
Having some troules like no image on home page, cannot access to logs or network informations through the UI.
So i decide to start from fresh install. I run the demo.bin process and then past all core from firmware_mod folder.
everything sounds good until i browse the camera ip address on my browser, cannot access to logs, network etc... and i still have this error on currentpic.cgi
>https://IPCAM/cgi-bin/currentpic.cgi "unable to load image"

I have acces to the camera through ssh

![image](https://user-images.githubusercontent.com/17542841/60682931-85959800-9e95-11e9-9727-0843e97e0a2e.png)

![image](https://user-images.githubusercontent.com/17542841/60682962-a5c55700-9e95-11e9-8faa-a91b976e2ab5.png)

**Comment by bwhite80** [comment]
any solution????

**Comment by jmtatsch** [comment]
Restart your rstp service in the service panel.

**Comment by MkLHX** [comment]
Nothing change after rstp restart

**Comment by jmtatsch** [comment]
The format sd and start from scratch

**Comment by MkLHX** [comment]
hello!
so i start from scratch and everything sounds ok now! thx

**Comment by MkLHX** [comment]
same problem today again...

cannot use this hack actually, nothing works...

Get the last update change nothing...
snapshot/MJPEG/RTSP etc nothing display any images...

**Comment by jmtatsch** [comment]
Update can corrupt your files if you have connection issues.
But in your case I would guess your rtspserver is out of memory killed. Did you enable some swap?
