### ISSUE TITLE
Firmware XiaoYuan HL5

### ISSUE THREAD

**Issue by rah66** [EliasKotlyar/Xiaomi-Dafang-Hacks#1092]
Camera [XiaoYuan HL5](https://www.joybuy.com/600494905.html)
On board Ingenic T20L
Firmware [demo_5.8.0.82.zip](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/files/3356210/demo_5.8.0.82.zip)

**Comment by jjss520** [comment]
HL5，没人破解呀，每次打开个米家太操蛋了，哎
