### ISSUE TITLE
Hardware purchasing discussion

### ISSUE THREAD

**Issue by TRSx80** [EliasKotlyar/Xiaomi-Dafang-Hacks#1094]
First off, great work you have shared here! I have put off getting into IP cameras because of all the proprietary "cloud" nonsense and phoning home, etc. but now that I have found this I am excited to jump into playing with IP cameras!

Perhaps if this generates discussion, I could harvest the useful bits and add to the Wiki?

After stumbling upon your project today, I excitedly went to Aliexpress to purchase some hardware, only to come away scratching my head a bit. This is what I have come up with so far:

**1. 128MB Devices**

I noticed when reading about flashing the open source bootloader some talk about 128MB devices, but could find absolutely no information about this in seller listings. Is it just luck of the draw? Am I looking for certain model numbers? New? Old? I could not find anywhere how to insure I would be getting a 128MB version.

**2. Naming / Marketing**

A lot of sellers (on Aliexpress, anyway) seem to include Dafang in the listing title, even if the listing is for a Xiaofang. Similarly Many listings also state "Mijia" which I thought was another model entirely? It was all very confusing, but perhaps I am overthinking it?

**3.a. Compatibility: "New" T20_L_ chip**

I read in at least one listing about "new T20 >L< chip" which according to the listing claimed it was supposed to be faster hardware (CPU?) apparently. I am also pretty sure I read at least one forum post here stating they picked up one of those and it worked. So, nothing to worry about here?

**3.b. Compatibiilty: Newest hardware / firmware revisions**

Similar to 3.a., above, I can't help but wonder at what point will these start coming from the factory with newer firmware already included on them that might break/disable this bootloader and spoil all of our fun?

I guess, if I get no replies/discussion, I might just pull the trigger on one each Dafang (approx. $30) and Xiaofang (approx. $20) and see what happens... However I would feel much more comfortable sharing experiences/thoughts with other recent purchasers before shelling out $50+ and waiting a few-several weeks...

**Comment by znanev** [comment]
Hi @TRSx80, recently I went through most of your points myself, so last month I bough a Dafang from AliExpress  from this seller:

https://www.aliexpress.com/item/32882221060.html?spm=a2g0s.9042311.0.0.43b74c4ddW1xSI

The camera is exactly what I expected - it has 128MB RAM and old enough firmware, so running this hack from the SD card was a piece of cake and is now happily integrated in my Home Assistant instance.

**Comment by TRSx80** [comment]
Yeah, those listings are all so similar. I don't see anything in there about 128MB RAM either.

So, is it just a crap shoot what you are going to get? Sounds like it...

And if so, maybe I should just pull the trigger?

**Comment by FHFS** [comment]
Dont get this [I21](https://www.aliexpress.com/item/32709260309.html) new firmware version with everything except p2p closed, still phones home, new board revision with uart headers removed (uart on hard to reach testpoints)

**Comment by TRSx80** [comment]
Well, I pulled the trigger on 2x Xiaofang and 1x Dafang from the cheapest sellers I could find on AliExpress (because I could tell no other way to differentiate them). They should arrive in a few weeks, I'll try and remember to post back my findings.

**Comment by TRSx80** [comment]
Subsequent to my creation of this thread, it has become known that there are apparently some problems with the new L variant. By now a solution has been found, however we are still (I think) trying to develop a way for the software to automatically decide which version of the firmware to load (right now the solution is still a manual workaround). More info here: [
Xiaomi Xiaofang 1S T20L support](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/1128).

**Comment by TRSx80** [comment]
Answering one of my own questions, I think that the 128 MB devices are typically the Dafangs, where the 64 MB are typically Xiaofangs (/speculation)?

However, looking at [the list of compiled open source bootloaders](https://github.com/Dafang-Hacks/uboot/tree/master/compiled_bootloader) it seems there are options for both 64 and 128 MB for both Xiaofangs _and_ Dafangs. So, I dunno... I guess it's just a crap shoot? No way to know what you are getting, until you get it?

Another issue, related to hardware purchasing...

I did not realize that these devices are all strictly Wi-Fi. Something so obvious now, I somehow completely overlooked when doing my initial research and purchasing.

I actually also already purchased a 24 port PoE gigabit switch (half powered, half not), a 1000' box of Cat5e cable, crimpers, ends, and the PoE adapters for the camera end that splits the power back out, only to just now realize that these are only Wi-Fi devices. /smh

I now understand that with the custom firmware we can use USB to Ethernet adapters, which will be my next research. I will be looking for some that are well supported in Linux, stable/reliable, and inexpensive (I am ok, even prefer, ordering from places like AliExpress). So if anyone is already aware of such adapter meeting those criteria, I would appreciate a recommendation, as it would save me a little time doing research.

**Comment by TRSx80** [comment]
OK here is a dumb question. Sorry but I am a total noob with video stuff.

I am not sure if I should get gigabit or 10/100 adapters. I suppose it depends on the bitrate and resolution you set. I pulled the following out of `/system/sdcard/config/rtspserver.conf` (I only have ssh access to the device right now):
```
# Video
BITRATE=5000
# Framerate
FRAMERATE_DEN=1
FRAMERATE_NUM=25
# Video format: (0 = FixedQp, 1 = CBR, 2 = VBR, 3 = SMART, default = 2)
VIDEOFORMAT=2
```

So, that BITRATE is what?  Bits/Kb/Mb per second (I vaguely recall something in the UI about this)?
