### ISSUE TITLE
Cronjob to enable/disable telegram notifications

### ISSUE THREAD

**Issue by DarioB92** [EliasKotlyar/Xiaomi-Dafang-Hacks#1096]
Hello, on my xiaofang 1s I'm trying to turn on/off motion detection telegram notifications.
To achieve it I know I can use motion_send_telegram in common_functions.sh, however I was unable to use this function in crontab (I modified root file in /system/sdcard...  .
Can you help me? Thanks

**Comment by jmtatsch** [comment]
Run a script like this via crontab. 

```
#!/bin/sh
. /system/sdcard/scripts/common_functions.sh
motion_send_telegram on
```
