### ISSUE TITLE
Telegram issue

### ISSUE THREAD

**Issue by bchiu2000** [EliasKotlyar/Xiaomi-Dafang-Hacks#1101]
My telegram gets the message "test" when I enter /system/sdcard/bin/telegram m test.

But if I try to message the Bot from my app like /start or /mem, he won't reply.

Any thoughts?  

Thanks!

**Comment by DarioB92** [comment]
Did you turned on the bot? (You could receive pics or messages without bot on)
If it works should reply to /help

**Comment by bchiu2000** [comment]
Ah no sure why but it's working now! Woohoo
