### ISSUE TITLE
1 Camera of Many not Working Stable. Restarting, NOK RTSP & random MAC ID

### ISSUE THREAD

**Issue by almostserious** [EliasKotlyar/Xiaomi-Dafang-Hacks#1102]
Hi, i am using several XiaoFang 1S with 78 MacID.
All of the but one work fine. 

This one gets a random MAC address every reboot and stops the rtsp server every 10 or so seconds.
It also often restarts on its own.

They all seem to be the same Hardware Revision.
Any Tipps where i can check this?

**Comment by sepodele** [comment]
I also have one Xiaofang 1S with RTSP NOK all the time and another without issues. They have same production month and almost same MAC address so I don't think they have different hardware revisions. I'm guessing poor quality control from Xiaomi.

**Comment by FHFS** [comment]
same here

**Comment by BaQs** [comment]
Same here also, MAC stays the same, but RTSP service crashes after few seconds.
Tried all the configurations tweaks I could find here... still no way to get a stable RTSP flux.

**Comment by jmtatsch** [comment]
Is it running out of memory when running some detection tasks?
Is it a T20L chip?

**Comment by FHFS** [comment]
@jmtatsch that was my first guess too, but looking at 'top' it still had like 1MB of ram. I even killed some other tasks to create some extra ram. but it still crashes.

**Comment by sepodele** [comment]
@jmtatsch Not running detection tasks and turned off basically everything. Lowest possible resolution too. How to know if it's T20 or T20L? Was bought in October 2018. Bought two and one of them behaves nicely while the other is crap.

**Comment by FHFS** [comment]
@sepodele T20 is marked on the chip. You would have to open it up.

**Comment by sepodele** [comment]
It's a T20. Had a white check mark on top of the chip for some reason.

**Comment by jmtatsch** [comment]
Do all your cameras have the jxf23 sensor?

**Comment by sepodele** [comment]
How to check that?

**Comment by jmtatsch** [comment]
search in your startup log for jxf

**Comment by sepodele** [comment]
Yep. 

[   22.266540] probe ok ------->jxf23
[   22.417427] -----jxf23_detect: 529 ret = 0, v = 0x0f
[   22.417851] -----jxf23_detect: 537 ret = 0, v = 0x23
[   22.417868] jxf23 0-0040: jxf23 chip found @ 0x40 (i2c0)
[   22.423368] tx_isp: Registered sensor subdevice jxf23 0-0040

**Comment by aminhusni** [comment]
RTSP server is not stable at all. Image is how it is cutting out aggressively making recorded footage unusable. 

![2019-10-11 17_42_13-Shinobi](https://user-images.githubusercontent.com/8511047/66642130-a87ed780-ec4e-11e9-85f0-5267962ef9aa.jpg)

This is the expected result, stable RTSP recorded stream: 

![2019-10-11 17_42_24-Shinobi](https://user-images.githubusercontent.com/8511047/66642193-cb10f080-ec4e-11e9-9b13-0f80e3e45606.jpg)
