### ISSUE TITLE
Noise level sensor

### ISSUE THREAD

**Issue by vlaraort** [EliasKotlyar/Xiaomi-Dafang-Hacks#1107]
Hi!

First of all, awesome project!

I have configured a Xiaofang1S to work with homeassistant, and everything is working fine :)

But I have found a small thing, I would like to have a sound sensor, like the light sensor, but I think it's not done yet

I have seen in this image:

![image](https://user-images.githubusercontent.com/2410951/61732117-34cedc00-ad7d-11e9-9ad3-1d452dbdd7b6.png)

That a sensor (sensor.dafang3 in the [configuration guide](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/integration/homeassistant/homeassistant.md) ) should be exposed to homeassistant by mqtt, and this have an attribute called "noise_level". Maybe I can use that attribute as a sound level sensor?

If yes, why I don't have it? I have all the others but this one, should I configure or enable something to get it?

Thank you!

**Comment by jmtatsch** [comment]
This is about wifi signal noise.

**Comment by vlaraort** [comment]
Oh, sorry to hear that, thank you for your response.

Do you think that make sense to open a Feature request for that? I would try to make it by myself, 
and open a PR, but I am just a JS developer and I have zero experience with this type of projects.

**Comment by jmtatsch** [comment]
Sure you can do it - if you really want it. Watch out, the current rtsp server is known to be broken, you will need to go some commits back. There is some issues about this, find someone that has recently compiled it an ask for help. You could look how motion detection is implemented and do something architecturally similar for sound level detection.

**Comment by mauckc** [comment]
Is the only way to interact with the microphone solely through the rtsp server? @jmtatsch

**Comment by jmtatsch** [comment]
Dont know. Maybe you can run rtsp without audio and the Audio recording in parallel.

**Comment by matbrewer396** [comment]
did anyone make progress on this? Noise level would be really handy

**Comment by patrik996** [comment]
Im currently testing out the ffmpeg_noise component in Hass. You feed it the rtsp stream and it gives you a binary sensor in hass. It probably uses more resources than if we could get the sensor value from the camera itself but it seems to work ok.

**Comment by olup** [comment]
Complete dafang noob here -  so do net take me too seriously - but wouldn't it possible to run a noise detection script in the firmware itself ? Something to trigger the `detectionOn.sh` script so that we get the same perks (auto video recording and moreover MQTT / Telegram messaging) ? Baby monitoring is the goal... Wyze, Xiaomi and Neos have it in their app, but I don't know if it's camera based or cloud based. `ffmpeg_noise` does not feel very scalable for me (I mean, what if you take you camera away on the week end with the baby ?)

**Comment by thepuncake** [comment]
Are there any news on this? Baby monitoring is what I'm also going for. Ffmpeg noise sensor seems to be misbehaving on hassio.
