### ISSUE TITLE
Is there any way that can watch Dafang camera streaming online when using my phone on LTE 4G?

### ISSUE THREAD

**Issue by vstevenphan** [EliasKotlyar/Xiaomi-Dafang-Hacks#1108]
Is there any way that can watch Dafang camera streaming online when using my phone on LTE 4G?

**Comment by wylde780** [comment]
Yes .. You would forward the port you defined for rtsp ( 8554 ) to your camera. Then use vlc to connect

**Comment by vstevenphan** [comment]
I thought that way only allows me to watch if I use same WAN?

**Comment by wylde780** [comment]
Well, the networks you allow to connect to your camera via the port forwarding is completely up to you, but this certainly not a Xiaomi issue.

**Comment by vstevenphan** [comment]
I'm not so technical. How can I set up that? In tiny cam, I edited the IP which is the internal IP that the router provided the camera 192.168.1.x

**Comment by PhilippZ** [comment]
Your phone's app has to connect to your router's IP address, not your internal network IP. You can find it at whatsmyip.com .  You can view remotely by typing your IP and the port (default is 8554). Here's an example: 204.5.25.24.1:8554

**Comment by broros** [comment]
Do I need to do port forwarding on my router?  
In my DaFang dashboard, I am showing the only Path to feed: rtsp://192.168.1.112:8554/unicast

**Comment by jmtatsch** [comment]
Yes you need to forward that port on your router.
