### ISSUE TITLE
Recording Service NOK

### ISSUE THREAD

**Issue by clclgithub** [EliasKotlyar/Xiaomi-Dafang-Hacks#1109]
Model: Xiaomi Dafang
Kernel Version: #21 PREEMPT Thu Oct 19 11:38:16 CST 2017
Bootloader Version: U-Boot 2013.07 (Jul 05 2018 - 13:33:27)

After i start the Recording service via web admin page, I can see the system show the PID and generate folder and file on /system/sdcard/DCIM folder.

However, after run for a while, the service show NOK icon and "Stop" cannot click.

and the MOV generated only have zero byte in size.

Any hints how to debug or fix it?

Many thanks in advance.

**Comment by xgusto** [comment]
Do you tried change resolutionon on 640x360?

**Comment by clclgithub** [comment]
It can now create MOV file, but it only have about 400K in size after record for whole day.
After I stop the service and download it to PC, it cannot play by VLC player.

**Comment by darrencope** [comment]
I am also getting a "NOK" message for recording on a new fresh install. What needs to happen in order for me to have video record? @clclgithub did you have any further luck? Anyone else able to lend a hand here?

**Comment by jmtatsch** [comment]
Just updated the recording script, can you try again?

**Comment by darrencope** [comment]
Thanks @jmtatsch ! I'll give it a try when I have a minute. Do I have to reflash the firmware, or can I just copy over the single script and reboot?

**Comment by jmtatsch** [comment]
autoupdate should work fine

**Comment by darrencope** [comment]
@jmtatsch - I updated via the GUI, and was able to enable recording. It ran for about an hour, then I check the card for files -- it had created subfolderfolders in the DCIM folder, but they were empty. Rebooting the cam then gave me a NOK message again for recording service.

What settings do I need to change for it to write files, and how do I get it to keep working once it's working?

**Comment by jmtatsch** [comment]
Not sure if you’ll be able to record for hours, it may run out of memory. Try some minutes first. If it says not okay there is usually  something wrong with a leftover pid file in /tmp. Restarting the camera should clean tmp or delete the file via ssh or ftp.

**Comment by clclgithub** [comment]
@jmtatsch Confirm the updated script working properly now. Thanks!

@darrencope  I got the same empty folder issue after update. Try run following command on SSH console to repair the SD card:

# dosfsck -a /dev/mmcblk0p1
# mount -o remount,rw /system/sdcard

**Comment by clclgithub** [comment]
@jmtatsch Any reason why the recording video using .h264 as filename extension instead of .mp4?

**Comment by jmtatsch** [comment]
I guess h264 is the native output format. Tried briefly to embed into mp4 container but failed. Would also be my preferred format because telegram should be able to preview it. Maybe you can have a try to play with the parameters?

**Comment by clclgithub** [comment]
@jmtatsch Then why motion video is different codec? i.e. JPEG Video. Should it better to use the same codec format?

**Comment by jmtatsch** [comment]
What exactly do you mean by motion video? The RTSP stream can be h264 or mjpeg. What you see in the web interface is just jpeg snaps updated regularly.

**Comment by clclgithub** [comment]
@jmtatsch 

Why I mean motion video mean is  "Motion - Snapshots" feature, which define the setting on following config file: 

/system/sdcard/config/motion.conf

**Comment by clclgithub** [comment]
@jmtatsch The service can start recording manually, but if I set service to Autorun, reboot the camera, it will show NOK.

**Comment by jmtatsch** [comment]
I guess the recording service may start before the rtsp server is running.

Can you replace the one in your recording service with this:

```
start()
{
  if [ -f $PIDFILE ]; then
    echo "Recording already running.";
  else
    echo "Started recording."
    SUB_DIR="$(date +%m%dFANG)"
    if [ ! -d "$DCIM_PATH/$SUB_DIR" ]; then
      mkdir -p "$DCIM_PATH/$SUB_DIR"
    fi
    FILE_NAME="MOV_$(date +%H%M.h264)"
    RECORDING_PATH="$DCIM_PATH/$SUB_DIR/$FILE_NAME"
    until pids=$(pidof v4l2rtspserver-master)
    do
      sleep 1
    done
    /system/sdcard/bin/busybox nohup /system/sdcard/bin/avconv -flags low_delay -fflags nobuffer -probesize 32 -i rtsp://0.0.0.0:8554/unicast -strict experimental -y -vcodec copy -an $RECORDING_PATH &>/dev/null &
    echo "$!" > "$PIDFILE"
  fi
}
```

**Comment by chaoranxie** [comment]
@jmtatsch @clclgithub i was having the exact same issue, adding that 4 lines to wait for v4l2rtspserver fixed it

**Comment by clclgithub** [comment]
@jmtatsch 

Update the firmware to 2019-08-26T17:45:48Z, reboot, recording service set to AutoRun, reboot:

recording service does not running
No PID show.
Start button enabled
No video file created.

SSH console pidof v4l2rtspserver-master can return value

**Comment by jmtatsch** [comment]
Then make sure your rtspserver is running

**Comment by clclgithub** [comment]
@jmtatsch rtsp-h264 already set to AutoRun and can return PID

# pidof v4l2rtspserver-master 
can return the same ID number on web console

**Comment by jmtatsch** [comment]
Interesting, imho the services are started in a single threaded manner one after the other. 
With that until loop blocking, not allowing the rtsp service to start.
Can you try this in your run.sh:

```
## Autostart all enabled services:
for i in /system/sdcard/config/autostart/*; do
  $i&
done
```

**Comment by clclgithub** [comment]
@jmtatsch update the run.sh now the services running properly.

@chaoranxie 

I do not using mqtt server, so I don't help you to test right now.

But after I enable Recording service, the system create following script 

/system/sdcard/config/autostart/recording

which is different from your :

/system/sdcard/config/autostart/rtsp-h264_recording

Which firmware are you using now?

**Comment by jmtatsch** [comment]
@chaoranxie with my solution my mqtt seems to start/work fine for me
why should an unsuccessful mqtt-control block everything?
