### ISSUE TITLE
H264 Start button not working - Missing controlscript

### ISSUE THREAD

**Issue by msj33** [EliasKotlyar/Xiaomi-Dafang-Hacks#111]
Just downloaded latest Master.

**Issue:**
The H264 button in the status.cgi does not work.

**Cause:**
Action.cgi refers to control script file rtsp-h264-with-segmentation start - But no such file exists in Master branch:
```
  h264_start)  
    /system/sdcard/controlscripts/rtsp-h264-with-segmentation start
```

**Solution**
Find the person holding the Al mghty "rtsp-h264-with-segmentation"-file :-)

P.S Could be good to know what segmentation actually is and what pros/cons are(Unless picture quality states quite clearly)

**Comment by shinebar1001** [comment]
Segmentation is not enabled in the current v4l2rtspserver. So  the script was deleted - the button is just a remain, and has no Impact.

The segmenting is described here:
http://www.streamingmedia.com/Articles/Editorial/What-Is-.../What-is-HLS-(HTTP-Live-Streaming)-78221.aspx
