### ISSUE TITLE
recordig of motion

### ISSUE THREAD

**Issue by xgusto** [EliasKotlyar/Xiaomi-Dafang-Hacks#1110]
Hi all
I'm newbie :)
I have a Xiaomi Mijia Dafang camera. Im installed https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks all works it.
When I start recording via the web interface, everything works.
How to set it to trigger recording automatically when motion is detected?

**Comment by Sungtroll** [comment]
There seems to be no motion recording in dafang hacks, only snapshots. Even the manual recording does only work in low resolution. I use 1920x1080 and it works ok with snapshot saved to SD card. I am still waiting for the development to proceed but i am also very impressed of the development already achived from the beginning of this project.

**Comment by xgusto** [comment]
So video recording can only be started via web interface or CLI command
`avconv -rtsp_transport tcp -y -i rtsp://name:password@192.168.1.15:8554/unicast -vcodec copy -c:a copy -t 30 /system/sdcard/DCIM/`date +%Y-%m-%d_%H-%M-%S`.mp4`

**Comment by xgusto** [comment]
I just need.
If motion is detected, run the script

`avconv -rtsp_transport tcp -y -i rtsp://name:password@192.168.1.15:8554/unicast -vcodec copy -c:a copy -t 10 /system/sdcard/DCIM/date +%Y-%m-%d_%H-%M-%S.mp4`

How could I do that?

**Comment by joeelia** [comment]
I believe what you’re trying to do is in the documentation: https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/integration/custom/motiondetection.md

**Comment by xgusto** [comment]
I did it this way https://tech.thierry.me/posts/2018-07-04_xiami_camera/

**Comment by jmtatsch** [comment]
Did you try enabling it in your motion.conf https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/6adc8844ef266ef630ee1ec4d669c41fe8bdc715/firmware_mod/config/motion.conf.dist#L34
