### ISSUE TITLE
Not work rtsp after update 2019/07/06

### ISSUE THREAD

**Issue by dmolner** [EliasKotlyar/Xiaomi-Dafang-Hacks#1117]
I update today with menu, and after these rtsp-h264 and mpeg not work

> `Content of dmesg
> 
> [    0.000000] Initializing cgroup subsys cpu
> [    0.000000] Initializing cgroup subsys cpuacct
> [    0.000000] Linux version 3.10.14 (taozhang@zhangtao-ThinkPad-X220) (gcc version 4.7.2 (Ingenic r2.3.3 2016.12) ) #32 PREEMPT Wed Jan 24 02:40:56 CST 2018
> [    0.000000] bootconsole [early0] enabled
> [    0.000000] CPU0 RESET ERROR PC:801CB664
> [    0.000000] [<801cb664>] __delay+0x4/0x10
> [    0.000000] CPU0 revision is: 00d00101 (Ingenic Xburst)
> [    0.000000] FPU revision is: 00b70000
> [    0.000000] cgu_get_rate, parent = 712704000, rate = 0, m = 0, n = 0, reg val = 0x000020ff
> [    0.000000] CCLK:712MHz L2CLK:356Mhz H0CLK:200MHz H2CLK:200Mhz PCLK:100Mhz
> [    0.000000] Determined physical RAM map:
> [    0.000000]  memory: 0051b000 @ 00010000 (usable)
> [    0.000000]  memory: 00035000 @ 0052b000 (usable after init)
> [    0.000000] User-defined physical RAM map:
> [    0.000000]  memory: 028b9000 @ 00000000 (usable)
> [    0.000000] Zone ranges:
> [    0.000000]   Normal   [mem 0x00000000-0x028b8fff]
> [    0.000000] Movable zone start for each node
> [    0.000000] Early memory node ranges
> [    0.000000]   node   0: [mem 0x00000000-0x028b8fff]
> [    0.000000] On node 0 totalpages: 10425
> [    0.000000] free_area_init_node: node 0, pgdat 805285f0, node_mem_map 81000000
> [    0.000000]   Normal zone: 82 pages used for memmap
> [    0.000000]   Normal zone: 0 pages reserved
> [    0.000000]   Normal zone: 10425 pages, LIFO batch:1
> [    0.000000] Primary instruction cache 32kB, 8-way, VIPT, linesize 32 bytes.
> [    0.000000] Primary data cache 32kB, 8-way, VIPT, no aliases, linesize 32 bytes
> [    0.000000] pls check processor_id[0x00d00101],sc_jz not support!
> [    0.000000] MIPS secondary cache 128kB, 8-way, linesize 32 bytes.
> [    0.000000] pcpu-alloc: s0 r0 d32768 u32768 alloc=1*32768
> [    0.000000] pcpu-alloc: [0] 0 
> [    0.000000] Built 1 zonelists in Zone order, mobility grouping off.  Total pages: 10343
> [    0.000000] Kernel command line: console=ttyS1,115200n8 mem=41700K@0x0 ispmem=8M@0x28B9000 rmem=15644K@0x30B9000 init=/linuxrc rootfstype=squashfs root=/dev/mtdblock2 rw mtdparts=jz_sfc:256k(boot),2048k(kernel),3392k(root),640k(driver),4736k(appfs),2048k(backupk),640k(backupd),2048k(backupa),256k(config),256k(para),-(flag)
> [    0.000000] PID hash table entries: 256 (order: -2, 1024 bytes)
> [    0.000000] Dentry cache hash table entries: 8192 (order: 3, 32768 bytes)
> [    0.000000] Inode-cache hash table entries: 4096 (order: 2, 16384 bytes)
> [    0.000000] Memory: 35192k/41700k available (3951k kernel code, 6508k reserved, 1275k data, 212k init, 0k highmem)
> [    0.000000] SLUB: HWalign=32, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
> [    0.000000] Preemptible hierarchical RCU implementation.
> [    0.000000] NR_IRQS:418
> [    0.000000] clockevents_config_and_register success.
> [    0.000028] Calibrating delay loop... 709.42 BogoMIPS (lpj=3547136)
> [    0.057700] pid_max: default: 32768 minimum: 301
> [    0.062746] Mount-cache hash table entries: 512
> [    0.067961] Initializing cgroup subsys debug
> [    0.072227] Initializing cgroup subsys freezer
> [    0.079775] regulator-dummy: no parameters
> [    0.084052] NET: Registered protocol family 16
> [    0.109152] bio: create slab  at 0
> [    0.116026] jz-dma jz-dma: JZ SoC DMA initialized
> [    0.121291] SCSI subsystem initialized
> [    0.125373] usbcore: registered new interface driver usbfs
> [    0.130916] usbcore: registered new interface driver hub
> [    0.136418] usbcore: registered new device driver usb
> [    0.141721] i2c-gpio i2c-gpio.1: using pins 57 (SDA) and 58 (SCL)
> [    0.148013]  (null): set:249  hold:250 dev=100000000 h=500 l=500
> [    0.154142] media: Linux media interface: v0.10
> [    0.158745] Linux video capture interface: v2.00
> [    0.165937] Switching to clocksource jz_clocksource
> [    0.171606] jz-dwc2 jz-dwc2: cgu clk gate get error
> [    0.176611] cfg80211: Calling CRDA to update world regulatory domain
> [    0.183073] jz-dwc2 jz-dwc2: regulator vbus get error
> [    0.188132] DWC IN OTG MODE
> [    0.341044] sft id =========================off
> [    0.345666] dwc2 dwc2: Keep PHY ON
> [    0.349039] dwc2 dwc2: Using Buffer DMA mode
> [    0.552739] dwc2 dwc2: Core Release: 3.00a
> [    0.556855] dwc2 dwc2: DesignWare USB2.0 High-Speed Host Controller
> [    0.563214] dwc2 dwc2: new USB bus registered, assigned bus number 1
> [    0.570756] hub 1-0:1.0: USB hub found
> [    0.574576] hub 1-0:1.0: 1 port detected
> [    0.578642] dwc2 dwc2: DWC2 Host Initialized
> [    0.583216] NET: Registered protocol family 2
> [    0.588274] TCP established hash table entries: 512 (order: 0, 4096 bytes)
> [    0.595262] TCP bind hash table entries: 512 (order: -1, 2048 bytes)
> [    0.601663] TCP: Hash tables configured (established 512 bind 512)
> [    0.607970] TCP: reno registered
> [    0.611206] UDP hash table entries: 256 (order: 0, 4096 bytes)
> [    0.617106] UDP-Lite hash table entries: 256 (order: 0, 4096 bytes)
> [    0.623804] NET: Registered protocol family 1
> [    0.628536] RPC: Registered named UNIX socket transport module.
> [    0.634559] RPC: Registered udp transport module.
> [    0.639252] RPC: Registered tcp transport module.
> [    0.644038] RPC: Registered tcp NFSv4.1 backchannel transport module.
> [    0.651165] freq_udelay_jiffys[0].max_num = 10
> [    0.655596] cpufreq 	udelay 	loops_per_jiffy	
> [    0.660028] dwc2 dwc2: ID PIN CHANGED!
> [    0.663886] init DWC as A_HOST
> [    0.666934] 12000	 59724	 59724	
> [    0.670171] 24000	 119448	 119448	
> [    0.673748] 60000	 298620	 298620	
> [    0.677119] 120000	 597241	 597241	
> [    0.680650] 200000	 995402	 995402	
> [    0.684304] 300000	 1493103	 1493103	
> [    0.687939] 600000	 2986206	 2986206	
> [    0.691675] 792000	 3941793	 3941793	
> [    0.695355] 1008000	 5016827	 5016827	
> [    0.699151] 1200000	 5972413	 5972413	
> [    0.709598] squashfs: version 4.0 (2009/01/31) Phillip Lougher
> [    0.716712] jffs2: version 2.2. (NAND) © 2001-2006 Red Hat, Inc.
> [    0.723412] msgmni has been set to 68
> [    0.728731] io scheduler noop registered
> [    0.732801] io scheduler cfq registered (default)
> [    0.739582] jz-uart.1: ttyS1 at MMIO 0x10031000 (irq = 58) is a uart1
> [    0.748240] console [ttyS1] enabled, bootconsole disabled
> [    0.764428] brd: module loaded
> [    0.770087] loop: module loaded
> [    0.774419] zram: Created 2 device(s) ...
> [    0.778646] logger: created 256K log 'log_main'
> [    0.784145] jz SADC driver registeres over!
> [    0.789615] jz TCU driver register completed
> [    0.794793] the id code = c84018, the flash name is GD25Q127C
> [    0.800719] JZ SFC Controller for SFC channel 0 driver register
> [    0.806931] 11 cmdlinepart partitions found on MTD device jz_sfc
> [    0.813139] Creating 11 MTD partitions on "jz_sfc":
> [    0.818167] 0x000000000000-0x000000040000 : "boot"
> [    0.823791] 0x000000040000-0x000000240000 : "kernel"
> [    0.829528] 0x000000240000-0x000000590000 : "root"
> [    0.835163] 0x000000590000-0x000000630000 : "driver"
> [    0.840981] 0x000000630000-0x000000ad0000 : "appfs"
> [    0.846675] 0x000000ad0000-0x000000cd0000 : "backupk"
> [    0.852588] 0x000000cd0000-0x000000d70000 : "backupd"
> [    0.858438] 0x000000d70000-0x000000f70000 : "backupa"
> [    0.864365] 0x000000f70000-0x000000fb0000 : "config"
> [    0.870177] 0x000000fb0000-0x000000ff0000 : "para"
> [    0.875863] 0x000000ff0000-0x000001000000 : "flag"
> [    0.881507] SPI NOR MTD LOAD OK
> [    0.884822] tun: Universal TUN/TAP device driver, 1.6
> [    0.890023] tun: (C) 1999-2004 Max Krasnyansky 
> [    0.896590] usbcore: registered new interface driver zd1201
> [    0.902425] usbcore: registered new interface driver r8152
> [    0.908173] usbcore: registered new interface driver usb-storage
> [    0.914545] usbcore: registered new interface driver usbserial
> [    0.920594] usbcore: registered new interface driver usbserial_generic
> [    0.927395] usbserial: USB Serial support registered for generic
> [    0.933645] usbcore: registered new interface driver ch341
> [    0.939329] usbserial: USB Serial support registered for ch341-uart
> [    0.945843] usbcore: registered new interface driver cp210x
> [    0.951645] usbserial: USB Serial support registered for cp210x
> [    0.957794] usbcore: registered new interface driver pl2303
> [    0.963592] usbserial: USB Serial support registered for pl2303
> [    1.469595] i8042: i8042 controller selftest timeout
> [    1.475324] jzmmc_v1.2 jzmmc_v1.2.0: vmmc regulator missing
> [    1.490872] jzmmc_v1.2 jzmmc_v1.2.0: card inserted, state=0
> [    1.520877] jzmmc_v1.2 jzmmc_v1.2.0: register success!
> [    1.526247] jzmmc_v1.2 jzmmc_v1.2.1: vmmc regulator missing
> [    1.570985] jzmmc_v1.2 jzmmc_v1.2.1: register success!
> [    1.576454] hidraw: raw HID events driver (C) Jiri Kosina
> [    1.583447] usbcore: registered new interface driver usbhid
> [    1.589186] usbhid: USB HID core driver
> [    1.593492] TCP: cubic registered
> [    1.596912] NET: Registered protocol family 17
> [    1.602742] input: gpio-keys as /devices/platform/gpio-keys/input/input0
> [    1.609881] drivers/rtc/hctosys.c: unable to open rtc device (rtc0)
> [    1.623086] VFS: Mounted root (squashfs filesystem) readonly on device 31:2.
> [    1.630791] Freeing unused kernel memory: 212K (8052b000 - 80560000)
> [    1.773554] dwc2 dwc2:  ++OTG Interrupt: A-Device Timeout Change++
> [    2.674037] mmc0: new high speed SDHC card at address aaaa
> [    2.683589] mmcblk0: mmc0:aaaa SL08G 7.40 GiB 
> [    2.699953]  mmcblk0: p1
> [    3.057268] FAT-fs (mmcblk0p1): Volume was not properly unmounted. Some data may be corrupt. Please run fsck.
> [    4.871166] RTL871X: module init start
> [    4.875041] RTL871X: rtl8189ftv v4.3.24.7_21113.20170208.nova.1.01
> [    4.884317] RTL871X: build time: Nov 22 2017 16:25:23
> [    4.889535] wlan power on
> [    4.911349] RTL871X: module init ret=0
> [    4.956691] mmc1: card claims to support voltages below the defined range. These will be ignored.
> [    4.977494] mmc1: new SDIO card at address 0001
> [    4.986816] RTL871X: ++++++++rtw_drv_init: vendor=0x024c device=0xf179 class=0x07
> [    5.064097] RTL871X: HW EFUSE
> [    5.070980] RTL871X: hal_com_config_channel_plan chplan:0x20
> [    5.299565] RTL871X: rtw_regsty_chk_target_tx_power_valid return _FALSE for band:0, path:0, rs:0, t:-1
> [    5.322780] RTL871X: rtw_ndev_init(wlan0) if1 mac_addr=34:ce:00:b1:c2:57
> [    8.762054] RTL871X: rtw_set_802_11_connect(wlan0)  fw_state=0x00000008
> [    8.769044] connect:ADAMO-2BCB(10)
> [    8.858910] RTL871X: start auth
> [    8.865292] RTL871X: auth success, start assoc
> [    8.875417] bssid:80:3f:5d:8d:fa:75
> [    8.879023] is bss
> [    8.881139] RTL871X: assoc success
> [    8.884743] conn:  (null) channel:0
> [    8.888338] bssid:80:3f:5d:8d:fa:75, ssid:ADAMO-2BCB(10)
> [    8.894003] RTL871X: recv eapol packet
> [    8.898381] bssid:80:3f:5d:8d:fa:75
> [    8.902033] is bss
> [    8.914734] RTL871X: send eapol packet
> [    8.923755] RTL871X: recv eapol packet
> [    8.936601] RTL871X: send eapol packet
> [    8.944056] RTL871X: set pairwise key camid:4, addr:80:3f:5d:8d:fa:75, kid:0, type:AES
> [    8.957293] RTL871X: set group key camid:5, addr:80:3f:5d:8d:fa:75, kid:1, type:AES
> [   37.939247] request spk en gpio 63 ok!
> [   37.939267] jz_codec_register: probe() successful!
> [   37.946980] cgu_set_rate, parent = 712704000, rate = 2048000, n = 348, reg val = 0x0000215c
> [   37.947003] cgu_enable,cgu_i2s reg val = 0x2000215c
> [   38.291351] dma dma0chan24: Channel 24 have been requested.(phy id 7,type 0x06 desc a1418000)
> [   38.300642] dma dma0chan25: Channel 25 have been requested.(phy id 6,type 0x06 desc a141e000)
> [   39.364714] motor_probe731
> [   39.385397] name : i2c-gpio1 nr : 1
> [   39.389001] name : i2c0 nr : 0
> [   39.455098] i2c i2c-0: i2c_jz_irq 441, I2C transfer error, ABORT interrupt
> [   39.462211] i2c i2c-0: --I2C txabrt:
> [   39.465897] i2c i2c-0: --I2C TXABRT[0]=I2C_TXABRT_ABRT_7B_ADDR_NOACK
> [   39.472471] error: sensor_read,172 ret = -5
> [   39.476776]  sensor_read: addr=0xa value = 0x0
> [   39.481463] err sensor read addr = 0xa, value = 0x0
> [   39.546627] i2c i2c-0: i2c_jz_irq 441, I2C transfer error, ABORT interrupt
> [   39.553732] i2c i2c-0: --I2C txabrt:
> [   39.557418] i2c i2c-0: --I2C TXABRT[0]=I2C_TXABRT_ABRT_7B_ADDR_NOACK
> [   39.563991] error: sensor_read,172 ret = -5
> [   39.568296]  sensor_read: addr=0x300a value = 0x0
> [   39.573152] err sensor read addr = 0x300a, value = 0x0
> [   39.638593] i2c i2c-0: i2c_jz_irq 441, I2C transfer error, ABORT interrupt
> [   39.645698] i2c i2c-0: --I2C txabrt:
> [   39.649384] i2c i2c-0: --I2C TXABRT[0]=I2C_TXABRT_ABRT_7B_ADDR_NOACK
> [   39.656023] error: sensor_read,172 ret = -5
> [   39.660332]  sensor_read: addr=0x300b value = 0x0
> [   39.665197] err sensor read addr = 0x300b, value = 0x0
> [   39.730664] i2c i2c-0: i2c_jz_irq 441, I2C transfer error, ABORT interrupt
> [   39.737772] i2c i2c-0: --I2C txabrt:
> [   39.741472] i2c i2c-0: --I2C TXABRT[0]=I2C_TXABRT_ABRT_7B_ADDR_NOACK
> [   39.748028] error: sensor_read,172 ret = -5
> [   39.752348]  sensor_read: addr=0xa value = 0x0
> [   39.756924] err sensor read addr = 0xa, value = 0x0
> [   39.822128] i2c i2c-0: i2c_jz_irq 441, I2C transfer error, ABORT interrupt
> [   39.829214] i2c i2c-0: --I2C txabrt:
> [   39.832920] i2c i2c-0: --I2C TXABRT[0]=I2C_TXABRT_ABRT_7B_ADDR_NOACK
> [   39.839476] error: sensor_read,172 ret = -5
> [   39.843797]  sensor_read: addr=0x580b value = 0x0
> [   39.848641] err sensor read addr = 0x580b, value = 0x0
> [   39.914100] i2c i2c-0: i2c_jz_irq 441, I2C transfer error, ABORT interrupt
> [   39.921206] i2c i2c-0: --I2C txabrt:
> [   39.924894] i2c i2c-0: --I2C TXABRT[0]=I2C_TXABRT_ABRT_7B_ADDR_NOACK
> [   39.931465] error: sensor_read,172 ret = -5
> [   39.935770]  sensor_read: addr=0x580b value = 0x0
> [   39.940612] err sensor read addr = 0x580b, value = 0x0
> [   40.006273] i2c i2c-0: i2c_jz_irq 441, I2C transfer error, ABORT interrupt
> [   40.013387] i2c i2c-0: --I2C txabrt:
> [   40.017073] i2c i2c-0: --I2C TXABRT[0]=I2C_TXABRT_ABRT_7B_ADDR_NOACK
> [   40.023646] error: sensor_read,172 ret = -5
> [   40.027952]  sensor_read: addr=0x3107 value = 0x0
> [   40.032810] err sensor read addr = 0x3107, value = 0x0
> [   40.098288] i2c i2c-0: i2c_jz_irq 441, I2C transfer error, ABORT interrupt
> [   40.105403] i2c i2c-0: --I2C txabrt:
> [   40.109090] i2c i2c-0: --I2C TXABRT[0]=I2C_TXABRT_ABRT_7B_ADDR_NOACK
> [   40.115994] error: sensor_read,172 ret = -5
> [   40.120309]  sensor_read: addr=0x3107 value = 0x0
> [   40.125190] err sensor read addr = 0x3107, value = 0x0
> [   40.191228] i2c i2c-0: i2c_jz_irq 441, I2C transfer error, ABORT interrupt
> [   40.198422] i2c i2c-0: --I2C txabrt:
> [   40.202252] i2c i2c-0: --I2C TXABRT[0]=I2C_TXABRT_ABRT_7B_ADDR_NOACK
> [   40.208812] error: sensor_read,172 ret = -5
> [   40.213149]  sensor_read: addr=0x3000 value = 0x0
> [   40.217994] err sensor read addr = 0x3000, value = 0x0
> [   40.283301] i2c i2c-0: i2c_jz_irq 441, I2C transfer error, ABORT interrupt
> [   40.290389] i2c i2c-0: --I2C txabrt:
> [   40.294091] i2c i2c-0: --I2C TXABRT[0]=I2C_TXABRT_ABRT_7B_ADDR_NOACK
> [   40.300719] error: sensor_read,172 ret = -5
> [   40.305135]  sensor_read: addr=0xa value = 0x0
> [   40.309712] err sensor read addr = 0xa, value = 0x0
> [   40.374937] i2c i2c-0: i2c_jz_irq 441, I2C transfer error, ABORT interrupt
> [   40.382044] i2c i2c-0: --I2C txabrt:
> [   40.385729] i2c i2c-0: --I2C TXABRT[0]=I2C_TXABRT_ABRT_7B_ADDR_NOACK
> [   40.392300] error: sensor_read,172 ret = -5
> [   40.396607]  sensor_read: addr=0xf0 value = 0x0
> [   40.401357] err sensor read addr = 0xf0, value = 0x0
> [   40.466751] i2c i2c-0: i2c_jz_irq 441, I2C transfer error, ABORT interrupt
> [   40.473857] i2c i2c-0: --I2C txabrt:
> [   40.477542] i2c i2c-0: --I2C TXABRT[0]=I2C_TXABRT_ABRT_7B_ADDR_NOACK
> [   40.484112] error: sensor_read,172 ret = -5
> [   40.488420]  sensor_read: addr=0xf0 value = 0x0
> [   40.493099] err sensor read addr = 0xf0, value = 0x0
> [   40.558381] i2c i2c-0: i2c_jz_irq 441, I2C transfer error, ABORT interrupt
> [   40.565489] i2c i2c-0: --I2C txabrt:
> [   40.569175] i2c i2c-0: --I2C TXABRT[0]=I2C_TXABRT_ABRT_7B_ADDR_NOACK
> [   40.575746] error: sensor_read,172 ret = -5
> [   40.580054]  sensor_read: addr=0xf0 value = 0x0
> [   40.584731] err sensor read addr = 0xf0, value = 0x0
> [   40.650012] i2c i2c-0: i2c_jz_irq 441, I2C transfer error, ABORT interrupt
> [   40.657183] i2c i2c-0: --I2C txabrt:
> [   40.660895] i2c i2c-0: --I2C TXABRT[0]=I2C_TXABRT_ABRT_7B_ADDR_NOACK
> [   40.667453] error: sensor_read,172 ret = -5
> [   40.671775]  sensor_read: addr=0xfc value = 0x0
> [   40.676441] err sensor read addr = 0xfc, value = 0x0
> [   40.741745] i2c i2c-0: i2c_jz_irq 441, I2C transfer error, ABORT interrupt
> [   40.748833] i2c i2c-0: --I2C txabrt:
> [   40.752537] i2c i2c-0: --I2C TXABRT[0]=I2C_TXABRT_ABRT_7B_ADDR_NOACK
> [   40.759096] error: sensor_read,172 ret = -5
> [   40.763418]  sensor_read: addr=0x3004 value = 0x0
> [   40.768262] err sensor read addr = 0x3004, value = 0x0
> [   40.833728] i2c i2c-0: i2c_jz_irq 441, I2C transfer error, ABORT interrupt
> [   40.840833] i2c i2c-0: --I2C txabrt:
> [   40.844522] i2c i2c-0: --I2C TXABRT[0]=I2C_TXABRT_ABRT_7B_ADDR_NOACK
> [   40.851093] error: sensor_read,172 ret = -5
> [   40.855401]  sensor_read: addr=0x300a value = 0x0
> [   40.860242] err sensor read addr = 0x300a, value = 0x0
> [   40.925740] i2c i2c-0: i2c_jz_irq 441, I2C transfer error, ABORT interrupt
> [   40.932848] i2c i2c-0: --I2C txabrt:
> [   40.936535] i2c i2c-0: --I2C TXABRT[0]=I2C_TXABRT_ABRT_7B_ADDR_NOACK
> [   40.943109] error: sensor_read,172 ret = -5
> [   40.947414]  sensor_read: addr=0x31f3 value = 0x0
> [   40.952273] err sensor read addr = 0x31f3, value = 0x0
> [   41.017731] i2c i2c-0: i2c_jz_irq 441, I2C transfer error, ABORT interrupt
> [   41.024847] i2c i2c-0: --I2C txabrt:
> [   41.028534] i2c i2c-0: --I2C TXABRT[0]=I2C_TXABRT_ABRT_7B_ADDR_NOACK
> [   41.035108] error: sensor_read,172 ret = -5
> [   41.039416]  sensor_read: addr=0x3107 value = 0x0
> [   41.044272] err sensor read addr = 0x3107, value = 0x0
> [   41.110799] i2c i2c-0: i2c_jz_irq 441, I2C transfer error, ABORT interrupt
> [   41.117985] i2c i2c-0: --I2C txabrt:
> [   41.121788] i2c i2c-0: --I2C TXABRT[0]=I2C_TXABRT_ABRT_7B_ADDR_NOACK
> [   41.128350] error: sensor_read,172 ret = -5
> [   41.132683]  sensor_read: addr=0x4 value = 0x0
> [   41.137260] err sensor read addr = 0x4, value = 0x0
> [   41.202296] i2c i2c-0: i2c_jz_irq 441, I2C transfer error, ABORT interrupt
> [   41.209384] i2c i2c-0: --I2C txabrt:
> [   41.213088] i2c i2c-0: --I2C TXABRT[0]=I2C_TXABRT_ABRT_7B_ADDR_NOACK
> [   41.219644] error: sensor_read,172 ret = -5
> [   41.224037]  sensor_read: addr=0xa value = 0x0
> [   41.228700] err sensor read addr = 0xa, value = 0x0
> [   41.293742] i2c i2c-0: i2c_jz_irq 441, I2C transfer error, ABORT interrupt
> [   41.300846] i2c i2c-0: --I2C txabrt:
> [   41.304532] i2c i2c-0: --I2C TXABRT[0]=I2C_TXABRT_ABRT_7B_ADDR_NOACK
> [   41.311105] error: sensor_read,172 ret = -5
> [   41.315410]  sensor_read: addr=0x0 value = 0x0
> [   41.319985] err sensor read addr = 0x0, value = 0x0
> [   41.385233] i2c i2c-0: i2c_jz_irq 441, I2C transfer error, ABORT interrupt
> [   41.392342] i2c i2c-0: --I2C txabrt:
> [   41.396030] i2c i2c-0: --I2C TXABRT[0]=I2C_TXABRT_ABRT_7B_ADDR_NOACK
> [   41.402604] error: sensor_read,172 ret = -5
> [   41.406911]  sensor_read: addr=0x300a value = 0x0
> [   41.411770] err sensor read addr = 0x300a, value = 0x0
> [   41.477673]  sensor_read: addr=0xa value = 0xf
> [   41.482686]  sensor_read: addr=0xb value = 0x23
> [   41.547546] i2c i2c-0: i2c_jz_irq 441, I2C transfer error, ABORT interrupt
> [   41.554656] i2c i2c-0: --I2C txabrt:
> [   41.558344] i2c i2c-0: --I2C TXABRT[0]=I2C_TXABRT_ABRT_7B_ADDR_NOACK
> [   41.564915] error: sensor_read,172 ret = -5
> [   41.569222]  sensor_read: addr=0x31f3 value = 0x0
> [   41.574078] err sensor read addr = 0x31f3, value = 0x0
> [   41.639536] i2c i2c-0: i2c_jz_irq 441, I2C transfer error, ABORT interrupt
> [   41.646642] i2c i2c-0: --I2C txabrt:
> [   41.650328] i2c i2c-0: --I2C TXABRT[0]=I2C_TXABRT_ABRT_7B_ADDR_NOACK
> [   41.656967] error: sensor_read,172 ret = -5
> [   41.661298]  sensor_read: addr=0x3008 value = 0x0
> [   41.666141] err sensor read addr = 0x3008, value = 0x0
> [   41.671454] info: failed sensor find
> [   41.833331] register all isp device successfully!
> [   41.841491] @@@@ tx-isp-probe ok @@@@@`

> `==> /var/log/v4l2rtspserver-master.log <==
> /system/sdcard/bin/v4l2rtspserver-master: '/system/sdcard/lib//libliveMedia.so' is not an ELF file
> /system/sdcard/bin/v4l2rtspserver-master: can't load library 'libliveMedia.so'
> ================== START ===============
> /system/sdcard/bin/v4l2rtspserver-master -W1280 -H720 -A -r 2  -P 8554
> /system/sdcard/bin/v4l2rtspserver-master: '/system/sdcard/lib//libliveMedia.so' is not an ELF file
> /system/sdcard/bin/v4l2rtspserver-master: can't load library 'libliveMedia.so'
> ================== START ===============
> /system/sdcard/bin/v4l2rtspserver-master -fMJPG -W1280 -H720  -A -r 2  -P 8554
> /system/sdcard/bin/v4l2rtspserver-master: '/system/sdcard/lib/libliveMedia.so' is not an ELF file
> /system/sdcard/bin/v4l2rtspserver-master: can't load library 'libliveMedia.so'

**Comment by jmtatsch** [comment]
I don't think anything related has changed for a while.
Maybe something is messed up due to a botched update.
Can you please start with a fresh checkout?

**Comment by dmolner** [comment]
I solved the problem.
I write old firmware version on SD and update, now work fine.
