### ISSUE TITLE
How can I change the WiFi SSID?

### ISSUE THREAD

**Issue by ChienTing** [EliasKotlyar/Xiaomi-Dafang-Hacks#1119]
How can I change the WiFi SSID?

Thank you ～

**Comment by Dopeyr** [comment]
Hi, see https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/hacks/install_cfw.md#installation-of-the-new-firmware, specifically:

>4. Modify the file config/wpa_supplicant.conf on the microSD card to match your wifi-settings. Make sure wpa_supplicant.conf does not have windows line endings.

**Comment by ChienTing** [comment]
> 嗨，請參閱https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/hacks/install_cfw.md#installation-of-the-new-firmware，具體如下：
> 
> > 1. 修改microSD卡上的文件config / wpa_supplicant.conf以匹配您的wifi設置。確保wpa_supplicant.conf沒有Windows行結尾。

Thank you, solve my troubles
