### ISSUE TITLE
cloud connection

### ISSUE THREAD

**Issue by tabishz** [EliasKotlyar/Xiaomi-Dafang-Hacks#112]
Am I missing something here. I went through FAQs but didn't find a way to connect to camera outside of my network, i.e. from outside. for other Fang cameras i've seen a cloud script for them.

**Comment by shinebar1001** [comment]
when you want to connect to the camera from the Internet you have to configure your router accordingly. (But, first of all you should configure an authentification) - can you provide a link to the "Cloud script" the other cams are using? I could only imagine things like UPNP, but that is only one part - DDNS and so on is needed.

**Comment by hubmon** [comment]
@shinebar1001 Have Internet connection to the camera using port 80(default). How can I change the port?

**Comment by tabishz** [comment]
@shinebar1001 i just some screenshots of another xiaomi fang camera hack software, looks very much like this one and it had cloud as one of the enabled script.

**Comment by tabishz** [comment]
I am able to use some android app to view the camera stream however can't control the camera movement. I used tinycam and Onvifer.

**Comment by hubmon** [comment]
Did you install the API ?
https://github.com/kszere/Custom-Software-For-Xiaomi-Dafang

**Comment by tabishz** [comment]
No i haven't.. I'll give that a try.

**Comment by tabishz** [comment]
it is a different script but here https://github.com/samtap/fang-hacks/issues/122 you can see it has cloud option in one of the screenshots there.

**Comment by shinebar1001** [comment]
Thanks to @kszere  the api is now part of this repository!

**Comment by jmtatsch** [comment]
As answered in post no 2 you need to configure your router to expose your cameras http and rtsp ports to the internet. As there has not been a lot of activity in this issue i will close it.
