### ISSUE TITLE
Light sensor - 1S - Values from 20 to 40? (With no relation to real brightness in the room)

### ISSUE THREAD

**Issue by exetico** [EliasKotlyar/Xiaomi-Dafang-Hacks#1120]
### Details
```
Hostname | DAFANG
-- | --
Model | Xiaomi Xiaofang 1S
Firmware Version | 2019-08-05T14:45:25Z
Kernel Version | #32 PREEMPT Wed Jan 24 02:40:56 CST 2018
Bootloader Version | U-Boot 2013.07 (Jul 05 2018 - 17:59:02)

Local Time | Tue Aug 13 17:13:35 CEST 2019
Uptime | 1d, 1m
Load Average | 3.73, 3.39, 3.31
```

### Description
My 1S is connected to Home Assistant by MQTT, and it's working OK. 

I've added a few other sensors, to control the light in our hallway. And they are working OK, too.

However, the reported light_level from my Dafang-cam is jumping "up and down" from 20 to 40, and back again - with only a small amount of changes in between. Sometime it's values in between, but not relevant to the lightlevel in the room, at all...

I would love to use the light_sensor level, to get a better idea of how bright it is in the room, but currently i can't use it to anything, due to the changes in the value.

Question: 
**Would i be able to use the light_sensor as a trusted source for light level, or have i misunderstood something? Is there something broken with the sensor, or am i missing a specific config, or?**

### Evidence

Sensor from HA:
![image](https://user-images.githubusercontent.com/3549445/62954017-ee562580-bdee-11e9-8d67-604463642740.png)
_As you can see, it's jumping from 20 to 40 many many times, and my light is not turned on in the hall (see picture below)_

![image](https://user-images.githubusercontent.com/3549445/62954085-10e83e80-bdef-11e9-8f1b-d2b34debaf64.png)
_Light has been turn off the whole night, but the values of the light_sensor_

I've seen #79, but i can't find anything related to my problem.

**Comment by jmtatsch** [comment]
Only the old generation cameras have physical light sensors. Probably yours doesn’t.

**Comment by exetico** [comment]
One hour later...

![image](https://user-images.githubusercontent.com/3549445/62959028-26159b00-bdf8-11e9-8b21-237d48ded9bd.png)


Oh, that's sad. Is it the one missing right here? Or?

![image](https://user-images.githubusercontent.com/3549445/62959075-3fb6e280-bdf8-11e9-9d6e-01b73060d14a.png)

If that's the case, i guess my problem is like #1098 :-( Or?

Compared to the other PCB i could find only, it's definitely that one..
![image](https://user-images.githubusercontent.com/3549445/62959194-81e02400-bdf8-11e9-91b7-5c7e84fb299a.png)

Did you manage to add a sensor @Lefuneste83 ?

**Comment by exetico** [comment]
I don't have any of the parts laying around, so i guess it would be better to just grap an alternative.

What should i pick up, instead?
