### ISSUE TITLE
Motion tracking with Sannce I21AG, MixSight HX-I2110T2, WanScam HW0036 or Digoo BB-M2

### ISSUE THREAD

**Issue by rradar** [EliasKotlyar/Xiaomi-Dafang-Hacks#1121]
### Description

**Motion tracking with Sannce I21AG, MixSight HX-I2110T2, WanScam HW0036 or Digoo BB-M2**

I wonder if motion tracking is also available with this cameras and the custom firmware from this repo?

Sannce I21AG, MixSight HX-I2110T2, WanScam HW0036, Digoo BB-M2 or another Device with Ingenic T10/T20	

![image](https://user-images.githubusercontent.com/34582688/63057860-20e14a80-bee3-11e9-930d-b53eee1187d6.png)

**Comment by rradar** [comment]
No? Yes? Maybe?

**Comment by permmobi** [comment]
Купил видеокамеру MIXsight I2110T2 за криптовалюту PRIZM Пользуюсь уже 4 года. Интересно, есть ли обновлённая прошивка, может есть приложение в смартфон более функциональное. С удовольствием приобрету за монету PZM в разумном ценнике. Обращайтесь в Телеграмм @permmobi
