### ISSUE TITLE
Update device list on main page

### ISSUE THREAD

**Issue by rradar** [EliasKotlyar/Xiaomi-Dafang-Hacks#1122]
### Description

I look for a good and cheap camera to have it flashed with this custom firmware and therefor full (offline) control of it

### What did you do to debug the issue

Checked the README.md on this github and (luckily) found out (before I went shopping) that the list is not quite update to date (contains wrong entries or missing information)

### Evidence

The Xiaofang Dafang S1 ships with a T20L SoC nowadays which looks like is not (proper) supported for now #1050

Escam G02 listed as supported is not supported at all #795 

Their are some more T10/T20 devices which are not in the list yet #980 

### Contribute Back

Please update the main page accordingly because I don't have the rights to do it. Thanks :yum: 

### What to buy now

Good question - isn't it? :thinking:

**Comment by yanniboi** [comment]
You can make the changes here: https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/edit/master/README.md

Then all someone has to do is approve the changes. That is easier than asking someone to do the work.

**Comment by rradar** [comment]
My first pull request :fireworks: https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/pull/1123

@yanniboi got any idea for a good & cheap cam btw?

**Comment by gtors** [comment]
Qihoo 360 D603 (720p) also works on T20 chip
![photo_2019-10-21_23-17-35](https://user-images.githubusercontent.com/9943520/67240016-3a5dc000-f459-11e9-9936-47dcdcebce2b.jpg)
