### ISSUE TITLE
MQTT-values: exposure

### ISSUE THREAD

**Issue by exetico** [EliasKotlyar/Xiaomi-Dafang-Hacks#1126]
Hi,

Would it be possible to sent the exposure value by the MQTT-service? (For us without lightsensor build in, anymore). I guess it could be useful :-)

**Comment by jmtatsch** [comment]
Should be possible, will gladly accept a pull request.

**Comment by exetico** [comment]
Thanks for the fast merge-accepts :-)

https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/pull/1166
https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/pull/1167
