### ISSUE TITLE
Wyze Pan Cam 

### ISSUE THREAD

**Issue by MyCodeRocks** [EliasKotlyar/Xiaomi-Dafang-Hacks#1127]
Question/Issue

Wyze Pan Cam with Firmware cfw-1.0 from this repo.

Description:

I am trying to ssh into the camera, whilst I do get a terminal prompt for username and password the default root, ismart12 does not work. There seems to be different credentials for the Wyze Pan Cam. 

I have read through the documentation and searched for any additional documentation but cannot find this documented anywhere. I would really appreciate if someone could send me or post the default wyze pan cam ssh root user and password.

**Comment by HclX** [comment]
I ran into the same problem. i think they are using a different password. Here is the hash I grabbed from the camera. Can someone help cracking it?
root:$1$h.WNWVcj$I16bljj/Jcbxh/oQGCmVg.:0:0:99999:7:::

**Comment by MyCodeRocks** [comment]
I think I saw @EliasKotlyar  mentioning its a different user and password. If I read correctly he did say he had it. @EliasKotlyar  if you do have it would you mind posting or PM the user and password please,

**Comment by MyCodeRocks** [comment]
So figured it out - for anyone that is trying to get this working.

1. Turn on FTP on the camera through the web interface
2. Connect via FTP to the camera (root, ismart12)
3. Navigate to : /system/sdcard/config
4. In that folder there is a file called: lighttpd.pem
6. Open and copy from (and including) -----BEGIN PRIVATE KEY----- <everything in between> to (including) -----END PRIVATE KEY-----
7. Create a new txt document (Call it whatever you want) and paste the copied info from above - Save.
8. Using a SSH client or a terminal that you know, before connecting to the IP address on port 22 (default SSH port) - specify in  your connection config that it should use a private key.
9. Connect to the camera via SSH
10. It will prompt you for user and password - normal default Uname and Pwd - root / ismart12. It will prompt you to accept the certificate (which you created in step 6) - Select Yes and you are in via SSH :)

Hope this helps someone.
