### ISSUE TITLE
Recording n days

### ISSUE THREAD

**Issue by clclgithub** [EliasKotlyar/Xiaomi-Dafang-Hacks#1129]
Model: Xiaomi Dafang
Firmware Version: 2019-08-21T13:00:42Z
Bootloader Version: U-Boot 2013.07 (Jul 05 2018 - 13:33:27)

Is it possible 

1. Generate new video file for each day instead of single large file

2. Keep only n days of recording video (e.g. 3 days), like motion video
   max_videos=3

**Comment by jmtatsch** [comment]
Not sure you will be ever able to record full days. Rather record short snippets when motion is detected.

**Comment by clclgithub** [comment]
@jmtatsch 

If the resolution is not too high i think the 32GB SD card can keep it more than one day.

Can I run schedule task to start / stop recording service @ 00:00 each day, so the system can create new video file daily?

**Comment by jmtatsch** [comment]
Sure you could do that. Just use cron jobs to  run a script like this:

```
#!/bin/sh
. /system/sdcard/scripts/common_functions.sh
recording stop
recording start
```

**Comment by clclgithub** [comment]
I create script and run on SSH console, seems it does not work.

**Comment by jmtatsch** [comment]
should be recording on/off or /system/sdcard/controlscripts/recording start

**Comment by jmtatsch** [comment]
make sure the script is executable and put it in /system/sdcard/config/cron/periodic/daily

**Comment by clclgithub** [comment]
The script can run properly manually, Will further test on cron job.

Besides, it is possible to clean up the recording video like "Motion - Snapshot" video (for example, max_videos=3). 

Also, any reason for system to create subfolder like 0821FANG, 0822FANG? Why just put all under \DCIM\RECORDING\ folder?

**Comment by jmtatsch** [comment]
Sure, just develop a cleanup script and run it with a cron job.

Regarding DCIM look up "Design Rules for Camera File System". By sticking to the standard you might be able to view your footage in digital cameras, picture frames etc.

**Comment by clclgithub** [comment]
@jmtatsch I put the .sh script on /system/sdcard/config/cron/periodic/daily, seems it does not run.
I also try to put it /system/sdcard/config/cron/periodic/hourly for testing, the result is the same, nothing happen.

Do I need to enable something to start the cron job?

**Comment by jmtatsch** [comment]
Are you sure your script has the execution bit set?

**Comment by clclgithub** [comment]
already run the following cmd:

chmod +x record-rotate.sh 

-rwxr-xr-x root root record-rotate.sh

I can run the script on console without error.

**Comment by jmtatsch** [comment]
Can you have a look at crond's log:
`cat /system/sdcard/log/crond.log`

**Comment by jmtatsch** [comment]
Actually because of an old bug, the script may not have a .sh ending. Remove it and it should work.

**Comment by chaoranxie** [comment]
tested that without .sh ending works. Thanks @jmtatsch 
```
cd /system/sdcard/config/cron/periodic/15min
```
```
vi record-rotate
```
```
#!/bin/sh
. /system/sdcard/scripts/common_functions.sh
/system/sdcard/controlscripts/recording stop
/system/sdcard/controlscripts/recording start
```

```
chmod +x record-rotate
```

**Comment by chaoranxie** [comment]
I did find one potential issue, if the recording process is ever kill by any other process, this cronjob will just fail. because the stop process tried to run `kill "$pid" &&  rm "$PIDFILE"` https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/firmware_mod/controlscripts/recording#L43 

if the process is already dead, kill command will fail and not remove the pidfile, which will prevent `start` from working, any idea what a fix or workaround might be?

**Comment by clclgithub** [comment]
@jmtatsch confirm remove .sh extension working properly now. Thanks!

**Comment by clclgithub** [comment]
@jmtatsch I cannot reopen following issue:

Recording Service NOK #1109

Please take a look as well. Thanks!

**Comment by clclgithub** [comment]
@jmtatsch If I have 64G SD card, is it possible to create two 32G partition. one for mod firmware, another for recording video storage?

**Comment by jmtatsch** [comment]
Theoretically possible but you will be on your own there.

**Comment by clclgithub** [comment]
I updated the script, so it can delete the old videos and remove the empty folder.

#!/bin/sh
. /system/sdcard/scripts/common_functions.sh
/system/sdcard/controlscripts/recording stop
/system/sdcard/controlscripts/recording start
find /system/sdcard/DCIM/ -type f -name '*.h264' -mmin +720 -exec rm {} \;
find /system/sdcard/DCIM/ -type d -name '*FANG' -exec rmdir {} \;

**Comment by clclgithub** [comment]
Seems it better -mmin paramter to delete empty folder after a period of time. 

#!/bin/sh
. /system/sdcard/scripts/common_functions.sh
/system/sdcard/controlscripts/recording stop
/system/sdcard/controlscripts/recording start
find /system/sdcard/DCIM/ -type f -name '*.h264' -mmin +720 -exec rm {} ;
find /system/sdcard/DCIM/ -type d -name '*FANG' -mmin +720 -exec rmdir {} ;

**Comment by clclgithub** [comment]
> Theoretically possible but you will be on your own there.

Seems it not necessary now.

I boot the camera with 64GB SD card, formatted as single FAT32 partition without error.

I update the above script to keep videos for 5 days for further testing:

#!/bin/sh
. /system/sdcard/scripts/common_functions.sh
/system/sdcard/controlscripts/recording stop
/system/sdcard/controlscripts/recording start
find /system/sdcard/DCIM/ -type f -name '*.h264' -mtime +5 -exec rm {} ;
find /system/sdcard/DCIM/ -type d -name '*FANG' -mtime +5 -exec rmdir {} ;

**Comment by tibo888** [comment]
Hello, this my script for delete all directories after 3 days
You just put this script to /system/sdcard/config/cron/periodic/daily
That it that all
[rmdir.txt](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/files/4804522/rmdir.txt)
