### ISSUE TITLE
Keep Motion Video 

### ISSUE THREAD

**Issue by clclgithub** [EliasKotlyar/Xiaomi-Dafang-Hacks#1130]
Model: Xiaomi Dafang
Firmware Version: 2019-08-21T13:00:42Z
Bootloader Version: U-Boot 2013.07 (Jul 05 2018 - 13:33:27)

The Motion Video and still Images are removed after system reboot.

It is possible to keep it after reboot?

**Comment by jmtatsch** [comment]
Weird, they are stored on the sdcard and shouldn’t be removed. Which paths are affected?

**Comment by clclgithub** [comment]
@jmtatsch Default config location:

# Snapshots
save_snapshot=ture
save_dir=/media/motion/stills
save_snapshot_attr="0666"
save_file_date_pattern="+%d-%m-%Y_%H.%M.%S"
max_snapshots=20

# Videos
save_video=true
save_video_dir=/media/motion/videos
save_video_attr="0666"
video_duration=1

After restart

only /media folder are keep, other subfolder under it are removed
i.e. 
/media <- Keep
/media/motion <- Removed
/media/motion/stills <- Removed
/media/motion/videos <- Removed

**Comment by jmtatsch** [comment]
Umm, if you look at the mounts media on /media type tmpfs (rw,relatime) is temporary file system, so it will be cleaned with a reboot.
Maybe the default path should be /system/sdcard/DCIM/

**Comment by clclgithub** [comment]
Noted with Thanks!
So it will update on next firmware update?

**Comment by jmtatsch** [comment]
We only update *.conf.dist as a recommendation for users. You will have to make these changes yourself on your motion.conf file or start with a fresh checkout.

**Comment by clclgithub** [comment]
Noted. Case closed. Thanks a lot!

**Comment by clclgithub** [comment]
Sorry, I just find the setting does not work, after I change the save folder as following:

# Snapshots
save_snapshot=true
save_dir=/system/sdcard/DCIM/motion/stills

# Videos
save_video=true
save_video_dir=/system/sdcard/DCIM/motion/videos

motion subfolders and video/images does not create after motion detected.
