### ISSUE TITLE
1S with jxf23 - capture stops after a few seconds

### ISSUE THREAD

**Issue by orlyandico** [EliasKotlyar/Xiaomi-Dafang-Hacks#1134]
Dafang-1S

seems to have a jxf23 sensor based on kernel module load. The chip is a T20 and the main board is dated 2018-11-11, but I cannot determine if the sensor is a jxf22 or 23, there are no markings on the sensor board.

Using the cfw1.1 binary.

Not sure of version, I downloaded the entire zip repository today (27-Aug-2019)

Capture stops after some seconds. Error below (relevant is "jxf23 stream off"). Once the stream is off, even the still capture does not work (always returns the last image captured). Only a reboot restores it.

I tried lower resolutions, lower bitrates, and enabling swap in run.sh

None of these made the captures last longer. Also the captures seem to be 1 fps only (not streaming video).

[   43.704492]  sensor_read: addr=0x3008 value = 0x0
[   43.709337] err sensor read addr = 0x3008, value = 0x0
[   43.715012] info: failed sensor find
[   43.719176] misc sinfo_release
[   43.739480] set sensor gpio as PA-low-10bit
[   43.746327] probe ok ------->jxf23
[   43.897228] -----jxf23_detect: 529 ret = 0, v = 0x0f
[   43.897660] -----jxf23_detect: 537 ret = 0, v = 0x23
[   43.897677] jxf23 0-0040: jxf23 chip found @ 0x40 (i2c0)
[   43.925298] tx_isp: Registered sensor subdevice jxf23 0-0040
[   43.931216] do not support ctrl->cmd ====1
[   43.931238] do not support ctrl->cmd ====0
[   44.013707] do not support ctrl->cmd ====1
[   44.523901] do not support ctrl->cmd ====1
[   44.525149] jxf23 stream on
[   44.573598] ###### image_tuning_v4l2_open 4219 #######
[   44.597135] &&& chan1  scaler.max_width = 1920 max_height = 1080  min_width = 128 min_height = 128 &&&
[   56.324640] do_page_fault() #2: sending SIGSEGV to v4l2rtspserver- for invalid read access from
[   56.324640] 00000008 (epc == 00000008, ra == 00000008)
[   56.345474] jxf23 stream off
[   56.351612] do not support ctrl->cmd ====0

**Comment by orlyandico** [comment]
Another run.. this time the capture lasted about a minute. No SIGSEGV this time..

[   50.138183] jxf23 stream on
[   50.185053] ###### image_tuning_v4l2_open 4219 #######
[   50.216039] &&& chan1  scaler.max_width = 1920 max_height = 1080  min_width = 128 min_height = 128 &&&
[   50.761768] cgu_set_rate, parent = 712704000, rate = 4096000, n = 174, reg val = 0x200020ae
[   50.761790] codec_codec_ctl: set sample rate...
[   50.762802] codec_codec_ctl: set device...
[   51.161489] codec_set_device: set device: MIC...
[  213.626957] jxf23 stream off
[  213.627342] do not support ctrl->cmd ====0
[  213.628186] codec_codec_ctl: set CODEC_TURN_OFF...

**Comment by jmtatsch** [comment]
Try to build your own cfw based on a newer original fw.

**Comment by orlyandico** [comment]
I see https://github.com/mbevand/Xiaomi-Dafang-Hacks/commit/957b7ccfda5471e6770863fb071c7c3043e91e63

4.9.4.28 is dated Feb 2019 (https://support.wyzecam.com/hc/en-us/articles/360010068231-Wyze-Cam-v2-Firmware)

Since my cameras are from Dec 2018,  would using the newest firmware (dated July 2019) provide any benefit over the Feb 2019 firmware? presumably the CFW in mbevand's link is already in the mainline?

I've never even seen one of these cameras till a few hours ago, where can I get a guide to building a new CFW from the vendor-supplied binary?

**Comment by jmtatsch** [comment]
We try not to check in binaries because they could contain god knows what. 
Thus mbevands cfw has been removed in
https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/commit/ff61ac33565d7a627f0643878a9d1156cfa3a2ac
You may want to give it a try though.

**Comment by jmtatsch** [comment]
Also try the new drivers in #1128
