### ISSUE TITLE
Pan / Tilt - Return to Center

### ISSUE THREAD

**Issue by clclgithub** [EliasKotlyar/Xiaomi-Dafang-Hacks#1136]
Did the system have "Return to Center" function, after the camera Pan and Tilt?

Model: Xiaomi Dafang
Firmware version: 2019-08-26T17:45:48Z

**Comment by clclgithub** [comment]
Also, it is possible to run motor "Calibrate" when startup?

**Comment by znanev** [comment]
I've done this using the startup userscripts feature.

Create a new file with name for example `calibrate_motors.sh` and place it in `/system/sdcard/config/userscripts/startup` directory. The contents of the file is as follows:

```shell
#!/bin/sh
/system/sdcard/bin/motor -d v -s 100
```

Reboot the camera and upon start, when the `calibrate_motors.sh` script executes, the pan/tilt motors will be calibrated and camera will be set to center position.

**Comment by clclgithub** [comment]
@znanev  Thanks!

The command return:
x: 1300
y: 350
speed: 900

What is the meaning for above values?

**Comment by znanev** [comment]
@clclgithub These values are steps of the pan/tilt motors.

For x - 0 is leftmost position, 2600 is the rightmost.
For y - 0 is lowest position, 700 is highest.

So (1300, 350) is the central position of the camera.
