### ISSUE TITLE
How to get into config files

### ISSUE THREAD

**Issue by Dylantje** [EliasKotlyar/Xiaomi-Dafang-Hacks#1137]
Did flash the xiaomi cam with the latest version of dafang.
works fine.
Only i will try to get into the config files with FTP.
I am in the cam, with putty.

Only where can i find the most config files?
I found the files in the old dafnag image.. only here can i not find the conf. [ for wifi en mqtt etc ]
Also the  i cannot find the snapshot map.....

Thanks!!!

**Comment by jmtatsch** [comment]
/system/sdcard/config

**Comment by Dylantje** [comment]
That part I know
Only when the camera online is...
I log in white putty
And I hope I can set there som settings

And then a reboot ....

**Comment by jmtatsch** [comment]
I don't understand. Just ftp in and change your files. Or ssh in and use vi to edit directly on the camera.

**Comment by Dylantje** [comment]
Only there is no config file in the map config


And the picture map for the snapsnots

**Comment by jmtatsch** [comment]
```
ls /system/sdcard/config
autostart                 matrix.conf               rtspserver.conf.dist
bftpd.conf                matrix.conf.dist          sendmail.conf.dist
cron                      motion.conf               ssl
defaultgw.conf.dist       motion.conf.dist          staticip.conf.dist
dropbear_ecdsa_host_key   mqtt.conf                 telegram.conf
hostname.conf             mqtt.conf.dist            telegram.conf.dist
hostname.conf.dist        ntp_srv.conf              timelapse.conf
ldr-average.conf          ntp_srv.conf.dist         timezone.conf
lighttpd.conf             openssl.cnf               usb_eth_driver.conf.dist
lighttpd.conf.dist        osd.conf                  userscripts
lighttpd.pem              resolv.conf.dist          wpa_supplicant.conf
lighttpd.user             rtspserver.conf           wpa_supplicant.conf.dist
```
