### ISSUE TITLE
rtsp server dead after update

### ISSUE THREAD

**Issue by halastjarna** [EliasKotlyar/Xiaomi-Dafang-Hacks#1139]
Xiaomi Xiaofang 1S. 
2019-08-26T17:45:48Z

If I turn on RTSP H264 Server in Camera Controls, it dies after a few seconds. 
I can see the feed in Motioneye, but then it is gone. 
I'm a novice regarding this so that any help would be appreciated. 

[video server log.txt](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/files/3553135/video.server.log.txt)

**Comment by MrAlester** [comment]
Same thing happens to me. I can see the stream on VLC no problem, but on Motioneye dies after a few seconds.
I'm currently using another cam from an old cellphone with the same setup and it works great.
