### ISSUE TITLE
LED configuration

### ISSUE THREAD

**Issue by clclgithub** [EliasKotlyar/Xiaomi-Dafang-Hacks#1140]
1. On System/ LED configuration page

Suggest using "Toggle Switch" control instead on On / Off button, as it difficult to to tell the current LED/IR status

2.  Camera Controls - Last setting now save
- Switch OFF 'Blue LED' manually
- Reboot camera
- Blue LED return Switched On

**Comment by jmtatsch** [comment]
I will gladly accept pull requests for these suggestions.
