### ISSUE TITLE
Telegram

### ISSUE THREAD

**Issue by netRunner0** [EliasKotlyar/Xiaomi-Dafang-Hacks#1141]
Does sending animation, video to telegrams work? If so, what should be done?

**Comment by jmtatsch** [comment]
Video format is still not quite right to play back via telegram, maybe you can experiment a bit with it to figure it out.
Look at https://stackoverflow.com/a/38703079 for hints.

**Comment by netRunner0** [comment]
But what about the animation? Does it work (gif)?

**Comment by jmtatsch** [comment]
I think it expects x264 snippets in a mp4 container as well

**Comment by jmtatsch** [comment]
But by all means please try it. Copy a known working gif and send it as animation.
Maybe we can do gifs instead of mp4.

**Comment by netRunner0** [comment]
I think that sending GIFs with a length of 5-10 seconds would be a better option than these inoperative videos)

**Comment by jmtatsch** [comment]
Just tested, with this video http://techslides.com/demos/sample-videos/small.mp4 sending works
All gifs will be recoded to mp4 anyways according to this: https://telegram.org/blog/gif-revolution
As long as its works ...

**Comment by jmtatsch** [comment]
Sending gifs as animation also works for me. Now we would just need to produce gifs.

**Comment by jmtatsch** [comment]
Can you try https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/6adc8844ef266ef630ee1ec4d669c41fe8bdc715/firmware_mod/scripts/detectionOn.sh#L33 with something like that https://www.unix-ag.uni-kl.de/~guenther/avconv.html to produce gifs?

**Comment by netRunner0** [comment]
Nothing but an image works for me. How to set it up?

**Comment by jmtatsch** [comment]
Close in favour of #957
