### ISSUE TITLE
Chuangmi smart IP Camera 1080p PTZ,is it hackable yet ?

### ISSUE THREAD

**Issue by ovisopa** [EliasKotlyar/Xiaomi-Dafang-Hacks#1142]
Hello everyone,

really appreciate the hard work everyone did so far!

I haven't seen any talk regarding this model, or maybe I haven't searched hard enough, this is why I'm asking you guys, is this camera hackable yet ?

I want to have access to the RTSP stream, and will be great to be able to grab a screenshot by accessing an url, like every other IP cameras. 

![image](https://user-images.githubusercontent.com/5344791/64045179-56d42f00-cb71-11e9-864b-1d0acab9ef84.png)

https://www.banggood.com/International-Version-Chuangmi-Xiaobai-H_265-1080P-Smart-Home-IP-Camera-EU-Plug-360-PTZ-AI-Detection-WIFI-Security-Monitor-from-Xiaomi-Eco-system-p-1450083.html?rmmds=myorder&cur_warehouse=CN

Thank you

**Comment by TRSx80** [comment]
Is that a T10/T20 based device? That would be the first thing I would determine.

After that (or at the same time), it would be up to you to do some exploring and find out. You can get started on that [here](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/hacks/newdevices.md).
