### ISSUE TITLE
Log Files

### ISSUE THREAD

**Issue by clclgithub** [EliasKotlyar/Xiaomi-Dafang-Hacks#1146]
Model: Xiaomi Dafang
Firmware Ver: 2019-08-26T17:48:48Z

When view the log file by Status | Logs, I find 2 binary files on /var/log folder:

/var/log/isp_tuning_func
/var/log/wtmp

Also i did not show log files on /system/sdcard/log

/system/sdcard/log/crond.log
/system/sdcard/log/startup.log
/system/sdcard/log/update.log

Besides, any logrotate function to keep logs for 3 days only?

**Comment by dakush** [comment]
I have the same doubt about the 2 binaries in /var/log.

About the logrotate, I just made this script and placed it in /system/sdcard/cron/periodic/weekly (to be executed every Sunday at 3:00 AM):

```
#!/bin/sh
for f in "/system/sdcard/log"/*; do
  echo "" > $f
done
for f in "/var/log"/*.log; do
  echo "" > $f
done
```

Hope it helps.
