### ISSUE TITLE
Scan and Fix SD Card 

### ISSUE THREAD

**Issue by clclgithub** [EliasKotlyar/Xiaomi-Dafang-Hacks#1147]
Model: Xiaomi Dafang
Firmware Ver: 2019-08-26T17:48:48Z

Every time I insert SD Card from Xiaomi Dafang, Windows 10 prompt following error:

There's a problem with this drive. Scan and the drive now and fix it.

The card read normally after Repaired. Is it normal?

**Comment by bchristian68** [comment]
I'm getting the same issue 
Model: Xiaomi Dafang
Firmware: 2019-10

**Comment by coax** [comment]
It's normal. Camera is caching (writing to SD card non-stop) and when you turn off the camera, it distrupts the writing, hence the error.
