### ISSUE TITLE
Implement h264 variable bitrate encoding

### ISSUE THREAD

**Issue by tamamma** [EliasKotlyar/Xiaomi-Dafang-Hacks#115]
Hi in tinycam i see that Dafang has 500KB/s flow @H264 20fps while Xiaofang has a 15KB/s flow at same resolution and encoding. I think is too high Dafang rate, how can it be reduced?

**Comment by dpanijan** [comment]
I am also interested in reducing the bitrate if possible. Tnx.

**Comment by EliasKotlyar** [comment]
I think that the xiaofang is using a variable bitrate. If there is much motion in the picture, the bitrate goes up, if not is stays very low. There is a way of implementing it, but i havent tried yet.

**Comment by jmtatsch** [comment]
Seems as if nik0 has implemented variable bitrate encoding already. Closing this for now.
