### ISSUE TITLE
motion detection stops record videos and snapshots

### ISSUE THREAD

**Issue by matulekpl** [EliasKotlyar/Xiaomi-Dafang-Hacks#1150]
Hey, 
I have weird problem.
I have set to make snapshot and record short video after motion detection.
I have set to send this videos and pictures to ftp serwer.
Everything works only for few times. After maybe 20 pictures and 16 videos everything stops working.

Second thing is that videos have very low fps. Can It be increased?

**Comment by jmtatsch** [comment]
You can set a max amount of photos and videos. If you have more the script will try to delete the old ones. The FPS can also be changed if you look into the recordingOn.sh script.

**Comment by matulekpl** [comment]
> You can set a max amount of photos and videos. If you have more the script will try to delete the old ones. The FPS can also be changed if you look into the recordingOn.sh script.

When I change the FPS in that place it only makes video faster...not smoother...

**Comment by saipsa** [comment]
It will never be smooth as it is not true video recording.
