### ISSUE TITLE
Half screen is green on recorded videos

### ISSUE THREAD

**Issue by matulekpl** [EliasKotlyar/Xiaomi-Dafang-Hacks#1152]
Hey,
I'm running recording video after motion detect

`/system/sdcard/bin/avconv -flags low_delay -fflags nobuffer -probesize 32 -i rtsp://0.0.0.0:8554/unicast -strict experimental -t 10 -y -vcodec copy -an /system/sdcard/DCIM/`date +%Y-%m-%d_%H.%M.%S`.h264`

But the recorded videos are half green. What can be the couse of this?

**Comment by saipsa** [comment]
Lower the resolution.

**Comment by znanev** [comment]
@matulekpl Just resolved this issue for myself.. Long story short - I flashed the modified bootloader, changed the memory parameters and when selecting 1920x1080 resolution, I had always had flashing green frames..

Now, when I was doing the same procedure to another Dafang camera, I spotted my mistake: I had changed the memory sizes, but not the addresses! Following the instruction from this guide:

https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/hacks/flashinguboot.md

Be sure to change the addresses too!


from:

mem=104M@0x0 ispmem=8M@**0x6800000** rmem=16M@**0x7000000**

to:

mem=87M@0x0 ispmem=9M@**0x5700000** rmem=32M@**0x6000000**

After reboot, the camera is streaming in 1920 x 1080 without the flashing green frames...

**Comment by saipsa** [comment]
@znanev Thank you so much. I did the same mistake, and I thought lowering resolution was the only way.

**Comment by matulekpl** [comment]
hmm I have everything changed already, and streaming is ok. only recorded video is with green frames.

**Comment by znanev** [comment]
What is the output of the following command, executed from your camera:

```
cat /proc/cmdline
```

**Comment by matulekpl** [comment]
Hey, sory for delay. I was away from home.

that is what I see from cat /proc/cmdline

`console=ttyS1,115200n8 mem=87M@0x0 ispmem=9M@0x5700000 rmem=32M@0x6000000 init=/linuxrc rootfstype=squashfs root=/dev/mtdblock2 rw mtdparts=jz_sfc:256k(boot),2048k(kernel),3392k(root),640k(driver),4736k(appfs),2048k(backupk),640k(backupd),2048k(backupa),256k(config),256k(para),-(flag)
`
