### ISSUE TITLE
uboot.bin missing in  firmware_original/wyzecam_pan/4.10.0.222/

### ISSUE THREAD

**Issue by robertmuth** [EliasKotlyar/Xiaomi-Dafang-Hacks#1154]
This useful for reverting a custom bootloader

**Comment by ineedit91** [comment]
apparently it can be found directly on Wyze cams website along with flashing instructions, and a video on youtube by wyze. https://forums.wyzecam.com/t/flashing-your-wyzecam-pan-firmware/5313

**Comment by robertmuth** [comment]
are you sure this refers to the boot loader as opposed to "just" the regular firmware.

**Comment by ineedit91** [comment]
@robertmuth  so sorry you are correct that is just the firmware. Would you be able to use the uboot from the dafang section?

**Comment by robertmuth** [comment]
would you risk bricking your device?

**Comment by jmtatsch** [comment]
You should back up your bootloader before flashing uboot.

**Comment by robertmuth** [comment]
This is excellent advice but too late for me. I was hoping that someone else with an unadulterated bootloader could provide this missing piece.
Also, it seems that the dafang section contains bootloaders - so there is an asymmetry.
