### ISSUE TITLE
Send image to MQTT every 30 seconds 

### ISSUE THREAD

**Issue by Snotmann** [EliasKotlyar/Xiaomi-Dafang-Hacks#1157]
Hey guys,

i got 10 cams Xiaofang witch working fine. Now i want a NodeRed Dashboard where all cams send their images via MQTT in a interval of 30 secs.

How is this possible ? Any ideas ? The mosqitto server is runnign already and the cams sends its status all 30 secs to it.

Snot

**Comment by NorthernMan54** [comment]
I’m doing something similar with node red, but it pulls the video stream using ffmpeg

https://github.com/NorthernMan54/node-red-contrib-homebridge-automation/wiki/Ring-Doorbell-replacement

**Comment by Snotmann** [comment]
... but you dont use MQTT there ?!

**Comment by NorthernMan54** [comment]
Correct, not for this flow in particular 

I’m working on V2 which constantly caches 2 minutes of video, and allows creation of videos from before motion is detected.

This may not be what you are looking for, but it is something similar

**Comment by jmtatsch** [comment]
Just write a script that runs every 30s via cronjob. You can get inspiration how to send an image via MQTT from detectionOn.sh.
