### ISSUE TITLE
Is it possible for online viewing from MI_Home App after installed?

### ISSUE THREAD

**Issue by dieptang** [EliasKotlyar/Xiaomi-Dafang-Hacks#1158]
Hello there,

I am installed successfully camera and it's have been recording on synology, so eveything fine now!
But I am interesting on viewing online on Mi-Home or something like that, I am already know the way for share the camera post 8554 outside from my router but seem it's a little bit uncomfortable.

Any recommended ?

Thanks

**Comment by NorthernMan54** [comment]
I’m using HomeKit to view mine outside the house

https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/integration/homekit/homekit.md

**Comment by dieptang** [comment]
@NorthernMan54  Very Nice ;) I will give it a try. 

Thank you.
