### ISSUE TITLE
Missile Control

### ISSUE THREAD

**Issue by kszere** [EliasKotlyar/Xiaomi-Dafang-Hacks#116]
What it is?

**Comment by EliasKotlyar** [comment]
I have a USB-Rocket Launcher, which i have connected via the USB-port.

Same like this:
https://www.amazon.de/Fremdhersteller-USB-Raketenwerfer-Rocket-Launcher/dp/B000NOUCF6

 I was able to compile the drivers for make it work. Also i developed a small web-gui for using that :)

**Comment by Shaktohh** [comment]
Ahah, do you want to use it in case of intrusion ? :dagger:

**Comment by jmtatsch** [comment]
Question answered.
