### ISSUE TITLE
Live video has green bits all over it (example included)

### ISSUE THREAD

**Issue by curacat** [EliasKotlyar/Xiaomi-Dafang-Hacks#1161]
Hi! 

Really love my Dafang camera, it's a 128 mb with Elias' mod, and I've also put on the open source bootloader (128 mb v2).

I've had this issue where the screen shows bits of green all over the place.
animated gif demonstrating the problem is here:
**https://imgur.com/a/ViGmVCO**

I'd also like to add that I've modified the boot-line memory has been modified to support FullHD as per output below.
![chrome_2019-09-09_14-52-51](https://user-images.githubusercontent.com/55074692/64504140-86253180-d311-11e9-987c-24acd35fb9ae.jpg)
![DafangProblem](https://user-images.githubusercontent.com/55074692/64504232-f338c700-d311-11e9-96fc-863258838229.gif)

[root@DAFANG:~]# cat /proc/cmdline
console=ttyS1,115200n8 mem=87M@0x0 ispmem=9M@0x5700000 rmem=32M@0x6000000 init=/linuxrc rootfstype=squashfs root=/dev/mtdblock2 rw mtdparts=jz_sfc:256k(boot),2048k(kernel),3392k(root),640k(driver),4736k(appfs),2048k(backupk),640k(backupd),2048k(backupa),256k(config),256k(para),-(flag)

I'm not sure whether this is a problem specifically with my camera (hardware issue?), but it certainly doesn't seem to be a software issue. 

Things I've tried: 
Going back and forth from Official to the modded firmware doesn't seem to change anything.
Changing resolution of the output video doesn't change anything either.
Updated bootloader to open-source
Updated /system/sdcard/uEnv.txt boot line to mem=87M@0x0 ispmem=9M@0x5700000 rmem=32M@0x6000000 

I'm hoping someone has an idea what is wrong with my camera (or software!)

**Comment by znanev** [comment]
@curacat All colours look quite washed, might be something from the sensor itself...

Have you tried how it looks with the original firmware through Xiaomi Home App?

**Comment by curacat** [comment]
@znanev Maybe the white balance is too aggressive ? I left it at default.
I've tried the original firmware and same thing.

**Comment by znanev** [comment]
@curacat So it is a defective device then - maybe you could try contacting the seller for a refund.

**Comment by curacat** [comment]
Thanks for the help @znanev
