### ISSUE TITLE
Xiaomi Dafang wont connect to WiFi

### ISSUE THREAD

**Issue by adslisdn** [EliasKotlyar/Xiaomi-Dafang-Hacks#1168]
Hello,

I recently purchased an Xiaomi Dafang from ebay unknown of the Geoblocking issue. Since i live outside china. I can,t connect the camera using Mi app. So therefore want to use Dafang hack to be able to use it with custom firmware. I followed instructions of the guide and i think i have managed to flash with custom firmware. But the issue is after i insert til micro-SD card with the mod-firmware and config file. The camera goes from a yellow light to a still blue light. But i can,t find the ip adress of the camera. I have checked all devices connencted to my router.

Below you may find the startup log:
Starting the Dafang Hacks Custom Application Layer
==================================================
Loaded common functions
Created etc directory on sdcard
Bind mounted /system/sdcard/bin/busybox to /bin/busybox
Bind mounted /system/sdcard/root to /root
Bind mounted /system/sdcard/etc to /etc
Created cron directories and standard interval jobs
wpa_supplicant: wpa_supplicant v2.5
random: Trying to read entropy from /dev/random
Successfully initialized wpa_supplicant
Initializing interface 'wlan0' conf '/system/sdcard/config/wpa_supplicant.conf' driver 'default' ctrl_interface 'N/A' bridge 'N/A'
Configuration file '/system/sdcard/config/wpa_supplicant.conf' -> '/system/sdcard/config/wpa_supplicant.conf'
Reading configuration file '/system/sdcard/config/wpa_supplicant.conf'
ctrl_interface='/var/run/wpa_supplicant'
ctrl_interface_group='0'
ap_scan=1
Line 15: Invalid passphrase length 64 (expected: 8..63)
 'MYPASSWORD"'.
Line 15: failed to parse psk 
'"MYPASSWORD"'.
Line 17: failed to parse network block.
Failed to read or parse configuration '/system/sdcard/config/wpa_supplicant.conf'.
Failed to add interface wlan0
: Cancelling scan request
: Cancelling authentication timeout
udhcpc: 
Initialized gpios
Determined image sensor model as jxf22
dropbear: 
Created new certificate for webserver
lighttpd: 
Startup finished!
==================================================
Starting the Dafang Hacks Custom Application Layer
==================================================
Loaded common functions
Created etc directory on sdcard
Bind mounted /system/sdcard/bin/busybox to /bin/busybox
Bind mounted /system/sdcard/root to /root
Bind mounted /system/sdcard/etc to /etc
wpa_supplicant: wpa_supplicant v2.5
random: Trying to read entropy from /dev/random
Successfully initialized wpa_supplicant
Initializing interface 'wlan0' conf '/system/sdcard/config/wpa_supplicant.conf' driver 'default' ctrl_interface 'N/A' bridge 'N/A'
Configuration file '/system/sdcard/config/wpa_supplicant.conf' -> '/system/sdcard/config/wpa_supplicant.conf'
Reading configuration file '/system/sdcard/config/wpa_supplicant.conf'
ctrl_interface='/var/run/wpa_supplicant'
ctrl_interface_group='0'
ap_scan=1
Line 9: failed to parse ssid 'Myssid'.
Line 9: failed to parse ssid 'Myssid'.
Line 17: failed to parse network block.
Failed to read or parse configuration '/system/sdcard/config/wpa_supplicant.conf'.
Failed to add interface wlan0
: Cancelling scan request
: Cancelling authentication timeout
udhcpc: 
Initialized gpios
Determined image sensor model as jxf22
dropbear: 
lighttpd: 
Startup finished!

Since i am not a programmer i would like some help in sorting this issue out, and by the way when you type your SSID and password are you supposed to delete the "" signs on both sides. Although i have tried both using it and removing it without luck.

# For more configuration option please see:
# https://w1.fi/cgit/hostap/plain/wpa_supplicant/wpa_supplicant.conf

ctrl_interface=/var/run/wpa_supplicant
ctrl_interface_group=0
ap_scan=1

network={
        ssid=" "
        # Uncomment to connect to Hidden SSIDs
        #scan_ssid=1 
        key_mgmt=WPA-PSK
        pairwise=CCMP TKIP
        group=CCMP TKIP WEP104 WEP40
        psk=" "
        priority=2
}

**Comment by jmtatsch** [comment]
Custom Firmware is loading but your WiFi config is messed up. Just simple double quotes around your password and ssid. I hope you didn’t use a space as your ssid or pw nor single quotes
