### ISSUE TITLE
How edit /etc/profile?

### ISSUE THREAD

**Issue by kszere** [EliasKotlyar/Xiaomi-Dafang-Hacks#117]
How edit /etc/profile for custom settings?
File in read only.

**Comment by wojtulab** [comment]
"Thats not easy possible. The /etc/ Folder is locked because of the original firmware. You will have to modifiy the firmware to "unlock" it:
https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/hacks/howto_modfirmware.md" #62

**Comment by kszere** [comment]
@EliasKotlyar From I can get unpacker.py and packer.py?

**Comment by rhass** [comment]
I think what is needed is a way to bind mount an `/etc` directory stored on the sdcard over the /etc/ on the root filesystem. The main issue with this though is it is very insecure... so alternative ideas are welcome.

**Comment by shinebar1001** [comment]
Bind mounting is easily possible, but as the sdcard is fat links are not supported, so you need to copy every file onto the sdcard, as eg resolv.conf is a symlink to /tmp which is writeable. 

One could copy /etc to /tmp on startup which takes some time and change the files with another copy-job from the SD-Card. But in my opinion the best way would be a jffs image which gets mounted to /etc on startup.

https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/141

**Comment by Dopeyr** [comment]
For `/etc/profile` specifically, it is possible to bind one file and not a whole dir. So:

```
cp /etc/profile  /system/sdcard/config/profile
mount --bind /system/sdcard/config/profile   /etc/profile
```

You can then edit `/etc/profile`. Logout then in to see the change. Obviously for this to persist, you'll have to mount `/etc/profile` on boot.

I didn't get this working with #141 though, but I'm not sure which files need mounting. Tried `/etc/passwd` and `/etc/shadow` I was still seeing the 'applet not found' message.

**Comment by tssva** [comment]
```bash
mkdir /system/sdcard/root
mkdir /system/sdcard/etc
cp /etc/passwd /etc/shadow /etc/group /system/sdcard/etc 
sed -i s#/:#/system/sdcard/root:# /system/sdcard/passwd
mount -o bind /system/sdcard/etc/passwd /etc/passwd
mount -o bind /system/sdcard/etc/shadow /etc/shadow
mount -o bind /system/sdcard/etc/group /etc/group
```
Add the mount commands to run.sh. Logout and back in.

Now `/system/sdcard/root` will be the home directory for the root user. You can change the password, install ssh keys for login and a `.profile` file in the directory for customization. 

To change the password use `/system/sdcard/bin/busybox passwd`. You will get an error message about not being able to create backups of the passwd and shadow files but the password change will occur.

**Comment by jmtatsch** [comment]
Setting a password works like a charm
even ssh-copy-id root@dafang 😄 
Can we somehow overlay the busybox commands per default? 
Maybe also mount -o bind /system/sdcard/bin /bin and create symlinks?

**Comment by tssva** [comment]
The limitations of the FAT32 filesystem means creating symlinks is not possible.

**Comment by jmtatsch** [comment]
aliases in .profile work but are ugly and much work
`alias passwd="busybox passwd"`

**Comment by tssva** [comment]
Run the following command to create a file with aliases for all the commands supported by the /system/sdcard/bin/busybox.

`/system/sdcard/bin/busybox --list | sed "s/^\(.*\)$/alias \1='busybox \1'/" > ~/.busybox_aliases`

Then run `source ~/.busybox_aliases` to activate the aliases. Add `source ~/.busybox_aliases` to your .profile to have them available whenever you login.
