### ISSUE TITLE
Disable logging of v4l2rtspserver-master

### ISSUE THREAD

**Issue by Snotmann** [EliasKotlyar/Xiaomi-Dafang-Hacks#1171]
Hey guys,

i want to save memory, disk space and cpu by disabling most of the logs. But until now i cant disable logging of the v4l2rtspserver-master.log. If I uncomment the lines the server wont start again ...

Someone got a good idea how to do that ?

Snot

**Comment by znanev** [comment]
@Snotmann You can patch the control script to log to the _null_ device. At least it's what I did in mine (/system/sdcard/controlscripts/rtsp-h264). Just change the values in both variables (**LOGDIR** and **LOGPATH**):

LOGDIR="/dev/null"
LOGPATH="/dev/null"

I think about submitting a pull request at some point to make disabling the log globally configurable.

**Comment by Snotmann** [comment]
That would be nice ... for debbuging its very useful ... but if all works it gives load to cpu and other components for nothing ;)

**Comment by znanev** [comment]
For now, just comment out the last line in /system/sdcard/config/lighttpd.conf

```
## accesslog module
#accesslog.filename          = "/tmp/lighttpd-access.log"
```

I think that this should be the default in lighttpd.conf.dist (the same way that debug logging is disabled by default). Most people do not expose the camera directly outside LAN, so webserver's access log shouldn't be that interesting to look at. Will have it in mind when I'm ready to propose said pull request.

**Comment by jmtatsch** [comment]
In normal use there is very few log entries from lighttppd not really worth doing anything.
However v4l2rtspserver-master.log size is definitely a problem. We should add a switch to disable it.
