### ISSUE TITLE
USB to Ethernet adapter - how to setup

### ISSUE THREAD

**Issue by ktsi** [EliasKotlyar/Xiaomi-Dafang-Hacks#1176]
Hi,

I am trying to setup the dafang so that I can connect via Ethernet. I have purchased a USB to Ethernet adapter with Asix AX8872B chipset.

I have seen closed issue no #236 but I cannot even start working on this, because I cannot locate the kernel directory and find makefile. Some people are saying it should be in ‘temp/Xiaomi-Dafang-Software-master/kernel but I have no such folder.

Is there a guide for a newbie to make this work?

Thanks a lot in advance and I hope I am not asking too much.

**Comment by ktsi** [comment]
Bump. I would really appreciate some help on this one. Thanks!

**Comment by jmtatsch** [comment]
@ktsi I would really appreciate you reading the wiki. Thanks!

**Comment by jmtatsch** [comment]
This is in the FAQ

```
Yes, just create a usb_eth_driver.conf file in /system/sdcard/config.

cp /system/sdcard/config/usb_eth_driver.conf.dist /system/sdcard/config/usb_eth_driver.conf
reboot
If this file exists the run.sh won't start the WIFI driver but instead load the usb ethernet driver. Currently only the asix.ko driver is supported but others can be built.
```

**Comment by ktsi** [comment]
And that’s it? Do I not need to compile anything? 

:)

**Comment by jmtatsch** [comment]
Yup

**Comment by ktsi** [comment]
Thank you so much!!! I still cannot find this on the wiki, btw.

**Comment by ktsi** [comment]
One last thing: If the WiFi connection is killed and smith goes wrong with Ethernet, how do I connect via ssh to the camera?

**Comment by jmtatsch** [comment]
Just alter that config file on the sdcard with a sdcard Reader.

**Comment by ktsi** [comment]
Thank you so much. Will try it out later on today. If all goes according to plan I will close the issue.

**Comment by ktsi** [comment]
I can confirm that the solution works. Thanks a lot @jmtatsch !!!

Closing issue.
