### ISSUE TITLE
There is no tutorial to upload videos from camera to FTP

### ISSUE THREAD

**Issue by vstevenphan** [EliasKotlyar/Xiaomi-Dafang-Hacks#1178]
There is no tutorial how to config file in the firmware_mode folder to upload videos from camera to my FTP server properly. @@ I don't know how to

**Comment by 0n3-70uch** [comment]
Hi thats similar to the normal motion detection. Just edit the motion.conf.dist and rename it to motion.conf. You need to edit these lines:

```
# Configure FTP snapshots and videos
ftp_snapshot=false
ftp_video=false
ftp_host="ftp.myserver.net"
ftp_port=21
ftp_username="user1"
ftp_password="password2"
ftp_stills_dir="motion/stills"
ftp_videos_dir="motion/videos"
```

# Configure FTP snapshots and videos
ftp_snapshot=false
ftp_video=false
ftp_host="ftp.myserver.net"
ftp_port=21
ftp_username="user1"
ftp_password="password2"
ftp_stills_dir="motion/stills"
ftp_videos_dir="motion/videos"

Please do not forget to close this issue. Greetings
