### ISSUE TITLE
Envoi du mouvement à Jeedom avec Xiaofang

### ISSUE THREAD

**Issue by Heracles44** [EliasKotlyar/Xiaomi-Dafang-Hacks#1179]
Bonjour,

Je ne parle pas anglais. Je préfère donc parler en français pour ne pas faire d’erreurs.

J’ai utiliser le tuto pour hack 2 Dafang et 6 Xiaofang. Le hack marche très bien.

Par contre, je rencontre un problème.
C’est pour cette raison que j’écris ici aujourd’hui.
J’ai configuré les 2 Dafang pour qu’elles envoient a jeedom l’information de mouvement. Ça marche bien!
J’ai fait exactement la même chose pour les Xiaofang mais ça n’envoie pas l’information mouvement à Jeedom.
On ne peut pas envoyer cette information avec les Xiaofang?
Si oui, que faut il faire sur les Xiaofang pour que l’information mouvement soit bien envoyé à ma box Domotique?

Merci

**Comment by Heracles44** [comment]
Nobody can help me?

Translate:

Hello,

I do not speak English. I prefer to speak French so as not to make mistakes.

I use the tutorial for hack 2 Dafang and 6 Xiaofang. The hack works very well.

By cons, I encounter a problem.
That's why I'm writing here today.
I configured the 2 Dafangs to send a motion information to jeedom. It works well!
I did exactly the same thing for the Xiaofang but it does not send the movement information to Jeedom.
We can not send this information with the Xiaofang?
If so, what should I do on the Xiaofang so that the information movement is sent to my home automation box?

Thank you

This is the code:

#!/bin/sh

source /system/sdcard/config/motion.conf
source /system/sdcard/scripts/common_functions.sh
/system/sdcard/bin/curl -X GET "http://192.168.0.XX:80/core/api/jeeApi.php?apikey=XXXXXXX&type=camera&id=XXX&value=$1"

Works with Dafang!
Not Works with Xiaofang!

Why?

**Comment by jmtatsch** [comment]
Probably not enough memory on the xiaofang. 
Try to enable swap in the swap config file and reboot.

**Comment by Heracles44** [comment]
> Probably not enough memory on the xiaofang.
> Try to enable swap in the swap config file and reboot.

Where please? I d'ont find the swap file! Thanks

**Comment by jmtatsch** [comment]
Search the repo, this is not a service hotline.

**Comment by Heracles44** [comment]
I have do that: https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/commit/d52ee4e7631e1af0b04db438ec7cd9612c1b6bff

i do true to the swap and nothing change. the motion isn't send to my box jeedom

the repo? sorry, i'm a stater to github

**Comment by Heracles44** [comment]
i do:

# If you need to run many services in parallel you may want to enable swap on your camera to avoid running out of memory
# in particular on the xiaofang & clones with only 64 mb 

SWAP=true
SWAPPATH="/system/sdcard/swapfile"
SWAPSIZE=256

it's correct?

**Comment by jmtatsch** [comment]
Looks good, don’t forget to reboot.

**Comment by Heracles44** [comment]
reboot and nothing change...

**Comment by Heracles44** [comment]
So i rename swap.conf.dist to rename swap.conf and it's work!

**Comment by Heracles44** [comment]
now i have "Unable load image" when i go to IP Cam! maybe 256 Mo Swap is too much?

**Comment by Heracles44** [comment]
i think there's a problem with the spaw true. the cam bug...
