### ISSUE TITLE
rtsp-h264 process not autorunning

### ISSUE THREAD

**Issue by robertjuric** [EliasKotlyar/Xiaomi-Dafang-Hacks#1180]
### Description

After every reboot/power cycle the rtsp-h264 service is not starting even though 'Auto-run' is enabled. I have to go in and manually start the service each time. The process will continue running until power is interrupted but will not autostart.

Wyzecam V2
Firmware Version | 2019-07-06T04:01:10Z
Kernel Version | #21 PREEMPT Thu Oct 19 11:38:16 CST 2017
Bootloader Version | U-Boot 2013.07 (Jul 05 2018 - 13:33:27)

### What did you do to debug the issue

Manually start process.

**Comment by ivanovd** [comment]
I have a similar issue: the rtsp-h264 process starts for few seconds then it stops. Nothing is written in the log, so I don't know what's happening. It was working fine until the last update.

**Comment by kubikub** [comment]
Similar issue for me until I uncheck autorun buton (on web interface) for configureMotion and recording. I think one or both was stopping the rtsp server.
