### ISSUE TITLE
Home Assistant MQTT integration

### ISSUE THREAD

**Issue by clclgithub** [EliasKotlyar/Xiaomi-Dafang-Hacks#1184]
MQTT Newbie Questions:

I following the guide below for Home Assistant MQTT integration

https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/integration/homeassistant/homeassistant.md

I install Mosquitto broker addon

Mosquitto broker version 5.1

Config:

{
  "logins": [
    {
      "username": "fake-mqttusername",
      "password": "fake-mqttpassword"
    }
  ],
  "anonymous": false,
  "customize": {
    "active": true,
    "folder": "mosquitto"
  },
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem",
  "require_certificate": false,
  "discovery_prefix": "homeassistant"
}

Seems the Camera can connect to MQTT server by proper setup the ACL
https://www.home-assistant.io/addons/mosquitto/

MQTT Log :

1570673665: New connection from 192.168.0.119 on port 1883.
1570673665: New client connected from 192.168.0.119 as mosqpub|26435-DAFANG (p2, c1, k60, u'fake-mqttusernamer').
1570673665: Client mosqpub|26435-DAFANG disconnected.

However I got following warning message on System log:

19-10-10 01:37:26 WARNING (MainThread) [hassio.addons.validate] Unknown options discovery_prefix

> "To enable MQTT discovery in Home Assistant please add/adjust in your configuration.yaml:"

Does the setup Doc based on build in? MQTT broker which work different with Mosquitto broker? Please kindly advise.

Run HASS.IO under Docker
System :  Raspbian GNU/Linux 10 (buster)
Hass.io supervisor: 189

**Comment by 0n3-70uch** [comment]
Hi, this is a hassio questions. Please use the stock config for your addon:
```
{
  "logins": [],
  "anonymous": false,
  "customize": {
    "active": false,
    "folder": "mosquitto"
  },
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem",
  "require_certificate": false
}
```

You need to add a new user in "Hassio>Settings>User". I added one with username "MQTT". 
Please close this issue if everything works fine now.

**Comment by DragonredEsp** [comment]
Manual Home Assistant installation and having issues loading the sensors and switchs as entities. Is it possible to use MQTT discovery in non Hassio installation? Thanks
No errors, they just don't appear on entities section

**Comment by jmtatsch** [comment]
@DragonredEsp no hassio required, just need to run your now mqtt broker.

**Comment by DragonredEsp** [comment]
Nvm i forgot to change the passwords in all the files and the most important one, in the Dafang, had the wrong info. Works like charm now, Thanks!
