### ISSUE TITLE
Problems Flashing Xiaomi and Neos Smartcam

### ISSUE THREAD

**Issue by ichilton** [EliasKotlyar/Xiaomi-Dafang-Hacks#1189]
Trying to flash bot a Xiaomi 1S and a Neos Smartcam with this firmware.

Have a Sandisk 4GB card - have created a 512MB partition, formatted it FAT32 and put demo.bin in place.

With the Xiaomi, I get the blue led, release the button and it ends up staying on permanent orange and doesn't seem to do anything more. Now even if I remove the sd card and boot it, it just sits sat on orange and I don't get the chinese voice prompts I got before I started.

With the Neos Smartcam, I tried the same with the cfw-1.1.bin file from wyzecam_v2.

I get exactly the same as the Youtube video showing someone doing this, except the very last part - it keeps flashing blue and never goes solid blue. i.e. I got the alternate orange/blue, then flashing blue - then it keeps flashing blue forever. Now when I remove the sd card and boot it, I get the same - it keeps flashing blue forever and I can no longer connect from the Neos app either.

Anyone able to help?

What does permanent flashing blue and solid orange signify? - are they recoverable?

Thanks!

Ian

**Comment by ichilton** [comment]
I forgot to mention - with the Neos one, when I put the card back in a linux box, it's created "record" and "timelapse" directories on the card. I remove them, but after another attempt they are back again.

**Comment by s58DB** [comment]
OK Ian. But, when you flash with BIN file, you copy others files on SD card?

Look this:
![FW](https://user-images.githubusercontent.com/23266214/66750150-fd5b6180-ee8b-11e9-99c6-5fab5ff37fdd.JPG)

**Comment by ichilton** [comment]
Not yet - I thought you were supposed to get a solid blue light on the demo.bin part before removing the card and putting the other files on?

**Comment by s58DB** [comment]
I'm flash my Xiaomi 1S one week ago. I have connected on TTL connectorc in camera for reason to monitor whole process. When flash procedure was done one my Xiaomi 1s cam light up yellow light and in terminal I see the problem because don't fined some files on SD card. I remove SD card and put on files from "firmware_mode". When do this I get blue light always on and camera work good all week.

**Comment by smithjw** [comment]
I've just received a couple of the Xiaofang cams but can't seem to flash them at all. Has anyone else had a camera which refuses to show the blue light as mine will only ever be solid orange or flashing orange?

Steps I've taken:
- Place demo.bin file on SD card (brand new)
- Hold down reset button
- Plug in power (tried multiple times and with different lengths of time)
- When I release the button, I simply get the chime and Chinese announcement that the camera is ready

**Comment by TRSx80** [comment]
> Not yet - I thought you were supposed to get a solid blue light on the demo.bin part before removing the card and putting the other files on?

Yes, but only for 5 seconds. That confirms you have successfully flashed the boot loader. After that, you need to put the firmware_mod files onto (preferably a different) SD card, and (re-)boot from that.

But all this is in the instructions already.

If you are not getting blue light for 5 seconds (and for everyone else): first step, make sure you are trying all advice given [here](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/hacks/install_cfw.md#community-tips). Try different SD cards, etc...

**Comment by disleyland** [comment]
on flashing, the blue light never came, just yellow.  but that's ok.  just move on to stage where you move the repository over (deleting the bin file) and setting up the conf file.  was able to login and everything.  my problem is that the rtsp feed only seem to be 1 image per second, regardless of the setting.  also I could not get any video unless size is below 1080p setting.  connecting to a Synology cam system doesn't work, always losing connection and reactivating for each image
