### ISSUE TITLE
not able to set retain falg for MQTT

### ISSUE THREAD

**Issue by lolouk44** [EliasKotlyar/Xiaomi-Dafang-Hacks#119]
Hi @shinebar1001,

It seems that by default the status messages are not set to be retained.
I tried to add `-r` in the MOSQUITTOOPTS e.g. `MOSQUITTOOPTS=" -r"`
The result is that mqtt-control shows up as NOK and I can enable it, message are still not retained.
How do I set the status messages to be retained?

**Comment by shinebar1001** [comment]
That's definitely a bug - the MOSQUITTOOPTS are passed to mosuqitto_sub, which fails to start, as there is no retention for subscriptions. I'll submit an update with options for mosquitto in general (like certificates), and another configuration option only for mosquitto_pub like -r

**Comment by shinebar1001** [comment]
An updated version is available - it introduces MOSQUITTOPUBOPTS - options that are only passed to the regular mqtt-Status, please see the mqtt.dist
