### ISSUE TITLE
Firmware 5.5.1_0426

### ISSUE THREAD

**Issue by Kartens** [EliasKotlyar/Xiaomi-Dafang-Hacks#1197]
have issues with latest firmware on Defang DF3 2017DP3894
Firmware 5.5.1_0426. Can't reset the camera with sdcard. does anyone have the same problem?

**Comment by Dirtylife** [comment]
Same here. Firmware 5.5.1_0426 doesn´t accept the "demo.bin"-Method

**Comment by vulcan4d** [comment]
Same, this new version kills the hack.  Looks like figuring out how to downgrade is a challenge too.

**Comment by TRSx80** [comment]
Pretty sure we are going to need some serial output to see what is going on. A dump of the boot log at least.

**Comment by sifus** [comment]
This update is avaible for my cam, i'm on 5.5.1.243 but the hack doesn't work to.

**Comment by cabani495** [comment]
I have the same problem. Had the camera in a drawer for ages and now that I've acquired a Synology NAS I realized it doesn't work without this hack and everything after having updated the damn firmware.

I've tried it with a known working SD but I don't manage to hack it...

Hope someone with much more knowledge will manage to figure it out.

**Comment by george-kar** [comment]
Anyone managed to downgrade 5.5.1_0426 ?

**Comment by drmaex** [comment]
I did! Althought I have serial connection attached i did not use it to downgrade to "demo_5.5.1.177.bin" from the original firmware folder. Just inserted the card with firmware on it (renamed to demo.bin) and booted with reset button pressed. Then I successfully installed CFW with same method. Maybe it would even work with CFW directly on 0426 but I had problems mounting my first SD card so I prepared another card with firmware binary and tried it directly. The serial connection was very handy to find out that not the update process failed but simply my first sd card could not be mounted

**Comment by piit79** [comment]
@sifus I was just able to downgrade from 5.5.1.243 to 5.5.1.194 and then to 5.5.1.177. Then I flashed the hack successfully and booted from SD card. I used a 32 GB SD card with a 512 MB partition just to be sure.

**Comment by wnleo** [comment]
> @sifus I baru saja bisa menurunkan versi dari 5.5.1.243 ke 5.5.1.194 dan kemudian ke 5.5.1.177. Kemudian saya berhasil mem-flash hack dan mem-boot dari kartu SD. Saya menggunakan kartu SD 32 GB dengan partisi 512 MB hanya untuk memastikan.

Dimanakah saya bisa mendapatkan fw 5.5.1.177 dan bisakah anda membantu saya langkah - langkahnya
