### ISSUE TITLE
Stale Bot for old issues

### ISSUE THREAD

**Issue by 0n3-70uch** [EliasKotlyar/Xiaomi-Dafang-Hacks#1201]
Hi, just an idea for better management of issues here:
https://github.com/apps/stale

**Comment by jmtatsch** [comment]
We have a stale bot here https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/commit/0aeaa7b9b726beb3478d42e8bab759a079dc50f1 . Not sure how the proposed one is different/better?

**Comment by 0n3-70uch** [comment]
Oh ok... I saw so many open issues.... ;-)
