### ISSUE TITLE
Xiofang 1s keep restarting.

### ISSUE THREAD

**Issue by m4sterpiece** [EliasKotlyar/Xiaomi-Dafang-Hacks#1202]
Thw Xiaofang1s keep restarting before pairing. After yellow light blink, I pressed setup button, there is chinese sound (wating for connection) but before I can connect it via Mi Home App, the Xiaofang restart. It keep happend.

This is an issue tracking system only.
If you have general questions or are a newbie, please ask for help in our [chat channel](https://gitter.im/Xiaomi-Dafang-Hacks).

To make sure your issue can be resolved as quickly as possible please state your

* exact camera hardware:
* the Xiaomi-Dafang-Hacks commitid (from `git log`) you are experiencing the issue with:

### Description

Describe what you were trying to achieve.
Tell us what happened and what you expected to happen.

### What did you do to debug the issue

Tell us what you did to remedy/debug the issue yourself and what you think causes the issue.

### Evidence

Please add snippets from the logfiles in:
* /system/sdcard/log/startup.log
* /var/log/*
* dmesg
* logcat
and/or screenshots you deem relevant.

### Contribute Back

If your issue was resolved, please consider contributing back to the project by creating a pull request to improve the code or documentation in order to avoid that this issue arises again for other people.

**Comment by tERB00** [comment]
Thats why we have custom firmware for Chinese cameras right here. Stock firmware just does not work.

**Comment by spattinson** [comment]
Can confirm, I attached to the serial debug port watching all the error scroll past, and the occasional run out of memory then reboot. much better after custom firmware installed.

**Comment by tERB00** [comment]
> I already used the custom firmware like you said, but the problem like I said occurred.

When you install custom firmware you must use text config file to configure your wifi and then use web browser to configure the rest of the camera's settings. Mi Home app wont work anymore with flashed camera.
