### ISSUE TITLE
Extra keys not allowed

### ISSUE THREAD

**Issue by torbenan** [EliasKotlyar/Xiaomi-Dafang-Hacks#1203]
I'm trying to make Dafang snap shot available i Home assistant, but I don't see any sensor in HA for that

Sun Oct 20 2019 22:46:13 GMT+0200 (Central European Summer Time)

Exception in async_discover when dispatching 'mqtt_discovery_new_camera_mqtt': ({'name': 'LilleDafang motion snapshot', 'unique_id': '7811dc76ea1e-motion-snapshot', 'device': {'identifiers': '7811dc76ea1e', 'connections': [['mac', '78:11:dc:76:ea:1e']], 'manufacturer': 'Xiaomi', 'model': 'Dafang', 'name': 'Xiaomi Dafang', 'sw_version': 'Dafang Hacks'}, 'topic': 'Kaelder/LilleDafang/motion/snapshot', 'platform': 'mqtt'},)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/mqtt/camera.py", line 47, in async_discover
    config = PLATFORM_SCHEMA(discovery_payload)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: extra keys not allowed @ data['device']

This happens on bott my cameras. (a Xiaomi Xiaofang 1S and a Xiaomi Dafang)

**Comment by jmtatsch** [comment]
Are you using the latest version of Homeassistant?

**Comment by torbenan** [comment]
No, I'm running 98.1

**Comment by jmtatsch** [comment]
Well update then. Device info support for mqtt camera was only very recently added.

**Comment by torbenan** [comment]
I upgraded to 0.100.3. That solved the problem with the extra keys, and I now see all sensor in HA. 
Thanks jmtatsch
