### ISSUE TITLE
Camera not used for six month, shows only purple noise

### ISSUE THREAD

**Issue by invisible999** [EliasKotlyar/Xiaomi-Dafang-Hacks#1205]
Hello everyone,

I have probably a hardware issue and want to understand what to do. I got WyZeCam V2 a year ago, setup with Hacks and it was working fine for about three month. I put it on storage afterwards till my next project.

I pulled the camera yesterday and when I logged in, I see only a purple noise in the screen, see the attached screenshot.

But I was able to log on to GUI and do software update - nothing changed. I've attached logs as well for reference

Anyone had the similar issue? What did happen here?

[dmseg.txt](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/files/3753538/dmseg.txt)
[Logcat.txt](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/files/3753539/Logcat.txt)
[mounts.txt](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/files/3753540/mounts.txt)
![screenshot](https://user-images.githubusercontent.com/45667495/67254490-e4683700-f4af-11e9-800b-10b32ba6c093.jpeg)
[Summary.log](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/files/3753541/Summary.log)

**Comment by jmtatsch** [comment]
Maybe an overheating issue in the summer? Does it go away after a reboot?

**Comment by invisible999** [comment]
I turned it off for a a night, the same situation in the morning.

I live in Singapore. The camera was sitting inside a cardboard box for 6 month, never exposed to direct sunlight. The day/night temp all this time was in the range of 25-32C, I do not think that it is the problem.

So... is the sensor dead? Anyone else have seen this? 

I need to decide if I want to order another camera or stay away from it.

**Comment by matt-mich** [comment]
Is it possible that the image sensor was exposed to signifigant humidity over time? If there's water in the image sensor, maybe a dehumidifiying/vacuum chamber could help.

Also, the noisy purple reminds me of a CMOS sensor with no light reaching it, but brightened signifigantly. Not sure if that helps, just a thought.

**Comment by invisible999** [comment]
That's interesting point. Here 60-80% of humidity even in indoors is norm, unless someone runs aircon 24/7 and I don't.

Let me do closer inspection. How difficult is to disassemble the camera without breaking?

**Comment by jmtatsch** [comment]
Rather simple. Open all screws under the sticker.

**Comment by TRSx80** [comment]
There is a great disassembly video [here](https://www.youtube.com/watch?v=OOghPawyIms) but it has terrible music (just turn it off, there is no talking in video, only text).

**Comment by Hypfer** [comment]
This looks very similar to #1105
