### ISSUE TITLE
Stragne bug: Files don't update

### ISSUE THREAD

**Issue by saipsa** [EliasKotlyar/Xiaomi-Dafang-Hacks#1206]
Files don't update. the log says files upto date, although they are not.

It seems the SHA calculation is wrong

SHA of scripts/detectionOn.sh is  

> 250a5526396aac9bb2d431684ff7c156dab3e9ff22ace457a59b04889cbffdbc ** remote is  250a5526396aac9bb2d431684ff7c156dab3e9ff22ace457a59b04889cbffdbc
> scripts/detectionOn.sh is up to date.
> 

I know my detectionOn.sh is different from the repo. But both show same SHA.

**Comment by bentolor** [comment]
Hi @saipsa – you could try to manually update `autoupdate.sh` on the sdcard and then try again?

Reading `autoupdate.sh` you could SSH into your webcam and verify whats going on:

```
[root@dafang:sdcard]# /system/sdcard/bin/openssl dgst -sha256 /system/sdcard/scripts/detectionOn.sh 
WARNING: can't open config file: /home/osboxes/SRC/Xiaomi-Dafang-Software/libressl/_install/etc/ssl/openssl.cnf
SHA256(/system/sdcard/scripts/detectionOn.sh)= 250a5526396aac9bb2d431684ff7c156dab3e9ff22ace457a59b04889cbffdbc
```
