### ISSUE TITLE
FTP upload .MP4 instead of .AVI

### ISSUE THREAD

**Issue by KptnKMan** [EliasKotlyar/Xiaomi-Dafang-Hacks#1207]
I am using 2x Dafang and 2x Xiaofang cameras.
All 4 are flashed with custom, and working.

I am having an issue where I want MP4 FTP uploads, instead of AVI FTP uploads.

### Description

I am unable to upload MP4 copies of recordings, instead of AVI.
I know there are MP4 copies on the camera, as I can see them in `/media/motion/videos/` so why are they not uploaded, but an AVI version instead.

I cannot find a documented or otherwise way to enable this.

I have tried to check scripts on the devices and cannot find where this would be relevant.

Is there somewhere I can add an upload for the latest MP4 or replace the AVI upload?

**Comment by jmtatsch** [comment]
The avi video is live streamed to the ftp server. Probably you can change that line https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/b935053c58cac47637846ea6cc2cbc43717f6506/firmware_mod/scripts/detectionOn.sh#L150 to produce mp4 files.

**Comment by oribl** [comment]
> The avi video is live streamed to the ftp server. Probably you can change that line
> 
> https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/b935053c58cac47637846ea6cc2cbc43717f6506/firmware_mod/scripts/detectionOn.sh#L150
> 
> to produce mp4 files.

didn't work for me. the files saved as mp4 but they are empty.
