### ISSUE TITLE
Xiaomi Xiaofang dual lens (360°/VR) camera support

### ISSUE THREAD

**Issue by kbesson** [EliasKotlyar/Xiaomi-Dafang-Hacks#1209]
Hi,

I just got a Xiaomi Xiaofang dual lens camera, the one that can do 360 view with VR headset compatibility.

I'm trying to know if this alternative firmware is compatible with this camera ?

If it can help, maybe I can open it and try to find the serial connection for bootlog ?

Thanks for your help !

**Comment by jmtatsch** [comment]
Open up and hook up a serial connection.
