### ISSUE TITLE
Sanance I41CB Support

### ISSUE THREAD

**Issue by derelict** [EliasKotlyar/Xiaomi-Dafang-Hacks#1213]
I have bought a Sanance I41CB (https://www.aliexpress.com/item/32814824292.html?spm=a2g0s.9042311.0.0.27424c4dvS92WN) ... i guess this Cam is not Yet supported or there is no booloader/firmware available (please be kind with me .. i'm a total newbie here ;-) ) ... the only Bootloader i could find was for a I141CB (so thats "141" instead of "41" ?? ... was there ever a "141" Version ? i can't find much about that on the web ???)... i don't think that the 141 bootloader will work on by "41" ? or will it ? .. how should i proceed in order to get it "supported" ? ... do i need a serial connection ? What information should i get ? (I CAN NOT connect to the cam using Digma !)

**Comment by cirolaferrara** [comment]
Tried with [this](https://github.com/Dafang-Hacks/uboot/blob/master/compiled_bootloader/sannce_i141cb_v2.bin) bootloader?

**Comment by derelict** [comment]
no not yet ... because i'm "afraid" of bricking my cam ... that bootloader is stated to be for 141 .. mine is 41 ??

**Comment by cirolaferrara** [comment]
I am not sure but https://support.sannce.com/hc/en-us/sections/360004651731-Instruction-For-Home-automation-Camera i see only I41CB.

So I141CB should be non existent

**Comment by derelict** [comment]
That's my point ... 141 is referenced "everywhere" in here ... so that's why i got confused ... i think i may just give it a try and see what happens then ... :-)

**Comment by cirolaferrara** [comment]
> That's my point ... 141 is referenced "everywhere" in here ... so that's why i got confused ... i think i may just give it a try and see what happens then ... :-)

Done?

**Comment by cirolaferrara** [comment]
Hello. I have bought this camera. I am not able to access it via telnet with APP "Digma" (always wrong ID error).

But [here](https://github.com/Dafang-Hacks/uboot/tree/master/compiled_bootloader) there is the bootloader, so someone hacked it.

How to access it? I need to disassemble it?

**Comment by dtalens** [comment]
Hello, new sannce cam i41cb is made by another manufacturer. I have a anterior versión and it show diferent information. This is the last one I bought: https://www.aliexpress.com/snapshot/0.html?spm=a2g0s.9042647.6.2.3c7363c0iuXv10&orderId=3002646746528337&productId=32814824292
The new version of the camera does not have LAN but the old one did. 
New version not compatible with Sannce app or Digma, only can use with ycc665 plus app or JoyLite app.

I could not access via web but via telnet. I would like to at least be able to close port 23 for security and to be able to control the camera using web browser.
I
