### ISSUE TITLE
Can I use USB network card

### ISSUE THREAD

**Issue by weue** [EliasKotlyar/Xiaomi-Dafang-Hacks#1214]
![image](https://user-images.githubusercontent.com/28719349/67942254-6d027800-fc12-11e9-9b7b-147aa8dd05d3.png)
There is no network in the usage environment. I don't need to watch the video. I want to upload images using 4G. I only found USB using an Ethernet adapter, #1176 what should I do?

**Comment by tERB00** [comment]
You can:
1. Compile drivers for your 4G stick and put it in your camera
2. Find 4G USB stick which have built-in wifi AP and connect your camera via WiFi.

**Comment by weue** [comment]
> You can:
> 
> 1. Compile drivers for your 4G stick and put it in your camera
> 2. Find 4G USB stick which have built-in wifi AP and connect your camera via WiFi.

Now I am using Option 2, I would like to use Option 1, I don't know if there are examples. Because I am not good at porting drivers.

**Comment by tERB00** [comment]
Nice opportunity to learn coding.

**Comment by weue** [comment]
> Nice opportunity to learn coding.

Thank you for your answer, I am trying.
