### ISSUE TITLE
Telegram bot not responding to commands

### ISSUE THREAD

**Issue by saipsa** [EliasKotlyar/Xiaomi-Dafang-Hacks#1219]
This has been after https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/commit/87ab7953315a1d541ddd38e67703d47bd744193f

this commit.

I think, removal of local inclusion, and instead global inclusion of commonfunction.sh is the cause.

Is it working for other people?

**Comment by b9389** [comment]
i had the same issue.

i had created static defaultgw.conf and staticip.conf files for my use case. Once I deleted the manually created files, my cameras were able to connect to the Telegram bot.
