### ISSUE TITLE
rtsp-h264 always NOK why?

### ISSUE THREAD

**Issue by JeedHome44** [EliasKotlyar/Xiaomi-Dafang-Hacks#1221]
Hello,

One of my Xiaofang work but now, when i turn ON, rtsp-h264 turn NOK.
I don't know why...
I try to replace files in the SD Card with new configuration and i can't go to setting camera...

My others 7 Xiaomi camera (Dafang and Xiaofang) work normaly with hack and motion with swap.

The Xiaofang is dead?

Sorry for my bad english, i'm french.

Thanks

**Comment by ghiagio** [comment]
I am having the same issue as well, the rtsp h264 turns off randomly

**Comment by hankanman** [comment]
I have the same issue with one of my cams but not the other, using neos smartcams

**Comment by Heracles44** [comment]
I know why! Your SD card is dead! I tried to change it and start with a new configuration and it’s work!
When the RTSP not work, it’s the SD card...

**Comment by hankanman** [comment]
I shall give that a go and let you know if it sorts it for me ta :)

**Comment by hank** [comment]
I've been having this issue for a while now and I finally dug through the camera over ssh. Here's my solution:

* Go to the 15 minute cron directory
```
cd /system/sdcard/config/cron/periodic/15min
```
* Create a new script that checks the status of rtsp, and if it's off, starts it
```
cat > unscrew-rtsp
#!/bin/sh
/system/sdcard/controlscripts/rtsp-h264 status || /system/sdcard/controlscripts/rtsp-h264 start
```
Hit CTRL-D to stop input.

* Make sure it works
```
[root@DAFANG02:15min]# busybox run-parts /system/sdcard/config/cron/periodic/15min
PID: 9051
[root@DAFANG02:15min]# /system/sdcard/controlscripts/rtsp-h264 stop
[root@DAFANG02:15min]# busybox run-parts /system/sdcard/config/cron/periodic/15min
Starting v4l2rtspserver-master
```

I added a little change to my status function in rtsp-h264:

```
status()
{
  pid="$(cat "$PIDFILE" 2>/dev/null)"
  if [ "$pid" ]; then
    # Prints PID: $pid if exists and returns 0(no error) else returns 1(error condition)
    kill -0 "$pid" >/dev/null && echo "PID: $pid" || return 1
  else
    return 2
  fi
}
```
This makes it so if there's no pidfile it returns 2. This seems to work as intended.
