### ISSUE TITLE
Telegram notifications not working

### ISSUE THREAD

**Issue by redelsoft** [EliasKotlyar/Xiaomi-Dafang-Hacks#1222]
camera hardware: Xiaomi Xiaofang (fabrication date 2019-09)
commitid: 143aba1 (??)

### Description

I got the firmware with sd-card working on the device. The webinterface and ssh work just fine. Streaming (RTSP) with VLC works as well. The motion detection seems to work, because I see a red dot in the video when motion occurs. The notification via Telegram doesn't work.
I Have the telegram settings enabled and can request the memory usage through telegram. When I do a /on I get a reply the motion capture is enabled. So the communications work.
/shot gives me also a image from the webcam.

Only thing that doesn't work (in regards to telegram) is receiving messages from the camera when motion occurs.

running the telegram command from the cli (e.g. sh telegram m hello) gives a text message in the telegram group chat. Doing the same for picture of video doesn't work.

There are telegram.log entries. The first one is a /shot command. The second is a sh telegram command:

[root@cam-1:bin]# cat /tmp/telegram.log 
Sending Photo: /tmp/telegram_image.jpg cam-1-17112019_111112
Sending Photo:  cam-1-17112019_112538

[root@cam-1:bin]# cat /system/sdcard/config/motion.conf
###################################################################
# edit this file and move it to /system/sdcard/config/motion.conf #
###################################################################

# Enable verbose debug messages to stderr
debug_msg_enable=false

# Configure the motion core parameters:

region_of_interest=0,0,1280,720
motion_sensitivity=3
motion_indicator_color=2
motion_timeout=5
motion_detection=on
motion_tracking=off

# Configure how to deal with motion events:

motion_trigger_led=false
publish_mqtt_message=false
publish_mqtt_snapshot=false
send_email=false
send_telegram=true
#telegram_alert_type=text
telegram_alert_type=image
 send_matrix=false

# General
group_date_pattern="+%d-%m-%Y"
file_date_pattern="+%d-%m-%Y_%H.%M.%S"
video_duration=10

# Record from RTSP (RTSP H264 must be enabled)
# RTSP is alternative for `record_video` function in `detectionOn.sh` - instead of 1s-getimage gets real video.
video_use_rtsp=true
video_rtsp_w=1280
video_rtsp_h=720
video_rtsp_f=15

# Snapshots
save_snapshot=false
save_snapshot_dir=/system/sdcard/DCIM/motion/stills
save_snapshot_attr="0666"
max_snapshot_days=20

# Videos
save_video=true
save_video_dir=/system/sdcard/DCIM/motion/videos
save_video_attr="0666"
max_video_days=10

Another thing I noticed is that the DCIM/motion/stills & video remain empty.

Things that do work: integration in Domoticz, MQTT connectivity, etc. FTP, mail and shares haven't been tried yet, because I have no use-case for it.
So the camera and all its basic functions seem to work with the hack, but the notification part (sending content upon motion) from the device not.

Any help would be highly appreciated.

**Comment by jmtatsch** [comment]
Did you enable some swap?

**Comment by redelsoft** [comment]
I did enable swap, but I ran into issue that's probably causing this problem (or attributing to it). A corrupt sd-card. Edits of files result in a zero byte file. Can remove them, but not recreate them.

Will try another card tomorrow.

**Comment by redelsoft** [comment]
After swapping the sdcard (from a cheap generic to a lexar pro) everything looks stable. Telegram works and the integration in the Synology Surveillance is also working. So no PEBCAK, or bug, but old-fashioned hardware failure.

**Comment by ex725** [comment]
I have that same problem.
Are there any results?

**Comment by tekgamerpt** [comment]
Same problem here on a XIaofang. Telegram notifications not working. No errors, alreay swapped sdcard and problem remains
