### ISSUE TITLE
Compatability with Wyze Sense Bridge

### ISSUE THREAD

**Issue by TomGrozev** [EliasKotlyar/Xiaomi-Dafang-Hacks#1223]
Is it possible with this modified firmware to hook into the Wyze Sense bridge adapter? My understanding is that the bridge connects to the motion sensors and door sensors using a 'proprietary' wireless protocol. Is there a way to use the adapter to connect to these other devices? If someone knows where the original Wyze firmware deals with this I could have a look.

**Comment by joyshukla** [comment]
why was this closed? any chance we can use wyze sense with homekit?
