### ISSUE TITLE
Unable to flash bootloader 1S, wrong version?

### ISSUE THREAD

**Issue by Fromble** [EliasKotlyar/Xiaomi-Dafang-Hacks#1226]
I've just reveiced my xiaofang camera. It's a 1S with a mac adress starting with 44.23.
In other issues i've read that there are different versions with different mac-adresses.
I am not sure which version it is.

It came with firmware 5.6.2.77 (latest now = 5.6.2.138).
I've tried to install the micro-sd bootloader, format sdcard as fat32, copy .bin file, renamed to demo.bin. Restart with setup button pressed.
Flashing doesn't work. No blue led's . I have tried both 1.0 and 1.3 version's

Could it be that the supplied firmware prevents the flashing?
The camera does work with the mi home app, so the camera itself seems ok.
what version bootloader can i install?

**Comment by tERB00** [comment]
Did you partitioned your SD card with 512MB?

**Comment by Fromble** [comment]
Yes, i have tried 256, 512MB, 2Gb. Fat32 and FAT.
Version 1.0 and version 1.3. 
Never worked.

**Comment by velijv** [comment]
+1, if you find a solution I would be grateful

**Comment by Fromble** [comment]
> +1, if you find a solution I would be grateful

Yes, i found a solution. I ordered a cam that supports RTSP out of the box...

**Comment by edgeball** [comment]
I think I've been having the same issue. I'm trying 1.1 and 1.3. LED never turns blue or blinks

**Comment by edgeball** [comment]
never mind. It worked! :)

**Comment by ferbar** [comment]
This is what I had, maybe it will help soneone else..
* toshiba 16GB sdcard. Used for a raspberry pi before. Tried several times. no way
* no-name 8GB sdcard. I wiped the complete sdcard before with dd_rescue /dev/zero /dev/sdXYZ, created the 512MB fat32 partition with fdisk + mkfs.vfat -F 32 /dev/sdXYZ1, copied demo.bin. got orange + blue led. worked.
