### ISSUE TITLE
Update via web interface downloads an outdated version?

### ISSUE THREAD

**Issue by mrdc** [EliasKotlyar/Xiaomi-Dafang-Hacks#1227]
Hello,

I'm running Dafang Hacks firmware on Xiaofang 1S (MAC 78:xx) since March 2019. 
Yesterday I've decided to update it via Web interface - the same version 31/03/2019 was downloaded and installed. A lot of commits were made after March 2019, so is it correct behaviour? Or should update request up-to-date files?

**Comment by bentolor** [comment]
You could try to login & start via terminal and see what's happening, @mrdc 

```
$ ssh root@dafang
[root@dafang:~]# cd /system/sdcard/
[root@dafang:sdcard]# ./autoupdate.sh -v
Starting AutoUpdate
Getting list of remote files.
autoupdate.sh is up to date.
run.sh is up to date.
uEnv.bootfromnand.txt is up to date.
uEnv.bootfromsdcard.txt is up to date.
bin/README.md is up to date.
bin/audioplay is up to date.
…
```

**Comment by bentolor** [comment]
#1206 could be related

**Comment by mrdc** [comment]
`./autoupdate.sh -v` works fine - the camera is updated to `Version: 2020-02-04T10:04:20Z`
