### ISSUE TITLE
Open source loader – I21AG

### ISSUE THREAD

**Issue by forospocoyo** [EliasKotlyar/Xiaomi-Dafang-Hacks#1228]
Hi. I have a Sannce I21AG 64MB camera with closed ports. I have connected tx, rx and gnd to get console access.
I’ve installed open source bootloader with this commands.

`isvp# fatload mmc 0:1 0x80600000 sannce_i21ag_v2.bin
reading sannce_i21ag_v2.bin
235884`

`isvp# sf update 0x80600000 0x0 0x40000
262144 bytes written, 0 bytes skipped in 1.102s, speed 242928 B/s
--->update spend 1108 ms`

Then, I reformatted the sd card to ext3 and copy https://github.com/Dafang-Hacks/rootfs and https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/tree/master/firmware_mod

Edit /etc/wpa_supplicant.conf with my wifi data and modifiy etc/init.d/rcS to adapt to Sannce camera.

Update env and save it.

`isvp# env default -f -a`
`isvp# setenv bootargs console=ttyS1,115200n8 mem=39M@0x0 ispmem=5M@0x2700000 rmem=20M@0x2C00000 init/linuxrc rootfstype=squashfs init=/linuxrc rootfstype=squashfs root=/dev/mtdblock2 rw mtdparts=jz_sfc:256k(boot),2176k(kernel),3584k(rootfs),2176k(system) quiet`
`isvp# saveenv
CPM_SSICDR(74) = e000000b
the manufacturer ef
SF: Detected W25Q128
Erasing SPI flash...Writing to SPI flash...done
isvp#`

Camera boot in new bootloader but can’t execute /linuxrc

`U-Boot 2013.07-gcb17d7d-dirty (Jan 01 2019 - 21:36:43)
Bootloader-Version: Dafanghacks v2
Board: Sannce I21AG (Ingenic XBurst T10 SoC)
DRAM:  64 MiB
`

`[    2.099565] EXT4-fs (mmcblk0p1): mounting ext3 file system using the ext4 subsystem`
`[    2.122233] EXT4-fs (mmcblk0p1): mounted filesystem with ordered data mode. Opts: (null)`
`[    2.130778] VFS: Mounted root (ext3 filesystem) on device 179:1.`
`[    2.137419] Freeing unused kernel memory: 196K (804cf000 - 80500000)`
`[    2.148884] Failed to execute /linuxrc.  Attempting defaults...`
`[    2.184846] Kernel panic - not syncing: No init found.  Try passing init= option to kernel. See Linux Documentation/init.txt for guidance.`
`[    2.197749] Rebooting in 3 seconds..Restarting after 4 ms`

 
What am I doing wrong?
Regards
[log03_12_2019.txt](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/files/3922955/log03_12_2019.txt)
[printenv_ext4ls.txt](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/files/3922962/printenv_ext4ls.txt)

**Comment by levurusov** [comment]
Maybe there is no permission to run busybox, check ownership and privileges for files on your sd card. If you copied them under non-privileged user it is better to chown to root.
