### ISSUE TITLE
Can not move DAFANG through hack CFW and motion detection disabled on region

### ISSUE THREAD

**Issue by ShuhengLi** [EliasKotlyar/Xiaomi-Dafang-Hacks#1229]
I got DAFANG setup and able to see it on rtsp. 

However after I login https://dafang and I clicked the four dirction arrows button, nothing happend! 
Another problem I met if I go to Service -> Motion Detection, it shows Region disabled. 

How can I fix above issues? Thanks!

**Comment by tERB00** [comment]
Did you try using different browser?

**Comment by shuheng-li-nielsen** [comment]
Yeah, both chrome and safari, none of them works.

**Comment by HotdogWithMustard** [comment]
I can confirm both of these issues on my Xiaomi Xiaofang 1S  as well, additionally I checked the logs and noticed this line:

 tcu_chn2 tcu_chn2.2: Motor driver busy now!

Any ideas on how to fix this?

**Comment by jmtatsch** [comment]
Xiaofang does not have motors. Motors on Dafang can be physically stuck, you can try to move them with a bit of force.

**Comment by HotdogWithMustard** [comment]
Ah ok, good to know lol.

**Comment by drmaex** [comment]
On my dafang I experience the same behaviour after boot and after login. The arrows have no effect. I need to go to pan/ tilt and press calibrate. Then the buttons begin to work

**Comment by SeTeM** [comment]
The same issue for me.
I'm using Dafang 128mb with CFW. The motor works when SD card is unmounted, but with mounted SD card control arrows do nothing and logs full of "Motor driver busy now!" errors. The manual move didn't help as well.

**Comment by jmtatsch** [comment]
Do you have onvif activated? That blocks the motor for itself.

**Comment by SeTeM** [comment]
@jmtatsch, thank you! Thant's the reason, now it works.
