### ISSUE TITLE
Night mode is very bad

### ISSUE THREAD

**Issue by george-kar** [EliasKotlyar/Xiaomi-Dafang-Hacks#1230]
I have Xiaomi DaFang and it has very good night vision via Xiaomi app. But when I see over RTSP with firmware is just a big black noise. I tried everything (IR-LED IR-CUT on/off etc) but I cant get good night quality. What am I doing wrong?

**Comment by saipsa** [comment]
Your night mode is not turning on. turn it on directly from  terminal and see. also, ir cut should be set to off and ir led to on.

**Comment by Adrellias** [comment]
Frame rate also makes a difference, if you want to light up more of a area you can lower the frame rate which would allow more exposure time. As mentioned make sure that IR cut is off, and IR led is on. I usually just toggle auto night vision on.
