### ISSUE TITLE
View record file via http

### ISSUE THREAD

**Issue by Carmad** [EliasKotlyar/Xiaomi-Dafang-Hacks#1231]
I've installed the hack in my dafang and all is working well.
I can't view the recorded file in the sd via http or ftp.
The only mode to view the file was by the removed sd in my pc.

Was present a semplification mode in the hack to view the file via remote?

**Comment by Ayuei** [comment]
Not sure about http. But I wasn't able to connect to ftp either, but all you needed to do was start the service via `bftpd -d` via the ssh terminal.

**Comment by grigio** [comment]
Hi, you can expose your `DCIM` via lighttpd

```
# override this in /system/sdcard/config/motion.conf
save_video_dir=/system/sdcard/www/DCIM/motion/videos
```
and

```
# put this in /system/sdcard/config/lighttpd.conf
$HTTP["url"] =~ "^/DCIM($|/)" { server.dir-listing = "enable" } 
```

Then you find the directories in `https://yourcameraip/DCIM/`

**Comment by jmtatsch** [comment]
@grigio great idea, can we somehow expose DCIM as virtual server like 
```
$HTTP["host"] == "media.dafang.local" {
        server.document-root = "/system/sdcard/DCIM/"
        $HTTP["url"] =~ "^/media($|/)" { server.dir-listing = "enable" }
}
```
unfortunately i am not getting this to work, any ideas why?

**Comment by grigio** [comment]
No idea, try to look at the lighttpd logs or permissions or try:

```
$HTTP["url"] =~ "^/media($|/)" { server.dir-listing = "enable" }

$HTTP["host"] == "media.dafang.local" {
        server.document-root = "/system/sdcard/DCIM/"
}
```

**Comment by wnleo** [comment]
Apakah ini sudah bisa digunakan

**Comment by 1116420469** [comment]
> Not sure about http. But I wasn't able to connect to ftp either, but all you needed to do was start the service via `bftpd -d` via the ssh terminal.

did the "bftpd -d" But now i cant access the camera in internet browser.
