### ISSUE TITLE
Settings for motioneye OS

### ISSUE THREAD

**Issue by recom273** [EliasKotlyar/Xiaomi-Dafang-Hacks#1235]
I have tried installing a dafang hack-ed xiaofang camera in motioneye OS and all I get is a grey box, 

Has anyone else had any success, is there some setting in services that I should enable. 

I have had success in Homebridge / ffmpegx but never been able to see the feed in VLC.

I saw an issue before, but using the fix was never successful .. is this still an issue?

**Comment by fotiDim** [comment]
I did have success with Dafang and motionEye. The grey box means it never connected to the camera. Try the URL in that form: rtsp://192.168.X.X:8554/unicast and try setting it up as rtsp/udp if rtsp/tcp fails

**Comment by digiltd** [comment]
Mine works ok

On the Defang, turn off motion detection and audio and fiddle with the video settings.

I use a low res, bitrate, framerate, though it was also working 1080 and 720.

I used UDP when setting the cams up in motioneye, though it was working on TCP as well.

![motioneyeos 2019-12-31 15-59-42](https://user-images.githubusercontent.com/5680968/71626757-b8231200-2be6-11ea-88a6-d1e1931a2d95.png)
![DAFANG2 2019-12-31 15-58-08](https://user-images.githubusercontent.com/5680968/71626758-b8231200-2be6-11ea-9f70-89b34ded4d74.png)

**Comment by recom273** [comment]
> Mine works ok
> 
> On the Defang, turn off motion detection and audio and fiddle with the video settings.
> 
> I use a low res, bitrate, framerate, though it was also working 1080 and 720.
> 
> I used UDP when setting the cams up in motioneye, though it was working on TCP as well.
> 
> ![motioneyeos 2019-12-31 15-59-42](https://user-images.githubusercontent.com/5680968/71626757-b8231200-2be6-11ea-88a6-d1e1931a2d95.png)
> ![DAFANG2 2019-12-31 15-58-08](https://user-images.githubusercontent.com/5680968/71626758-b8231200-2be6-11ea-9f70-89b34ded4d74.png)

That’s a great New Years present - thank you very much for the detailed reply, perfect!

**Comment by recom273** [comment]
This is super, I cant actually set the frame rate, not too sure why .. however, its working perfectly.

I will close - Thanks all.

**Comment by Wycombegav** [comment]
I've tried to use the above settings and my picture on motioneye is grainy and blurry. Any ideas as to why?
