### ISSUE TITLE
Several seconds lag Wyze V2

### ISSUE THREAD

**Issue by yvessa** [EliasKotlyar/Xiaomi-Dafang-Hacks#1236]
Hello,

Just finished installing the hack on a Wyze V2.

I can access the web gui. And video is working.

But video is lagging badly like 4-5 seconds.

I played with video size, video format, framerate and bitrate. Nothing seems to give enough to reduce lagging.

Any tips?

Regards,

Yves

**Comment by cwiggs** [comment]
I've noticed the video in the webui is laggy and there isn't anything I've been able to do to fix it.  However using tinyCam on Android via RTSP and it isn't very lagging, especially when you compare it with the official Wyze app.

Have you tried using some software to stream via RTSP?  I tested with tinyCam and VLC, both were much less lagging then the webui.

**Comment by jmtatsch** [comment]
Webui is basically jscript loading some jpegs.
Would be better to do it with HLS but our version of https://github.com/mpromonet/v4l2rtspserver is too old to be stable doing this. Someone would need to port our customisations to a newer version of it.

**Comment by yvessa** [comment]
hmm interesting, I have just checked the CAM in zoneminder and lag is not as bad, between 1 or 2 s.  And tinyCam also. Then looked at webgui, was still not bad.

I have changed CAM position since first issue. Might only be a simple wifi issue... I'll continue testing. I also played with 1080P stream while installing it. Now streaming at 720p...

**Comment by meidyjordan** [comment]
Hi, I Have Question about v4l2rtspserver-master.log

![image](https://user-images.githubusercontent.com/58964494/72689938-99f76480-3b49-11ea-9965-654f65c74827.png)

in this case that /var/log/lighttpd-cgi-stderr.log say : can't open '/tmp/v4l2rtspserver-master.log': No such file or directory.
Can someone tell me what's wrong ?

**Comment by meidyjordan** [comment]
Hi,
Can someone create script for do this :  
If 
          found "RTCPInstance::RTCPInstance error: totSessionBW parameter should not be zero!"
Then
         Set Video Setting / Reset Video Setting (the last setting)
Endif
So the Stream Won't Freeze to long because there is an Auto Set Video / Reset Video Setting while using NVR Etc.
Thanks
