### ISSUE TITLE
Model number database?

### ISSUE THREAD

**Issue by snailium** [EliasKotlyar/Xiaomi-Dafang-Hacks#1240]
I just received 2x Xiaofang 1S, turns out T20L. I tried to scan the QR codes on the box and at bottom of the camera. Both of them have MAC address and model number.

For example, in my hands,
- Xiaofang 1S T20L, MAC starts with 44:23:7C, model number D01C0017
- Original Xiaofang, MAC starts with 34:CE:00, model number C01C0003

And I tried the QR codes from the other T20L thread, https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/1128#issuecomment-554783629
- Xiaofang 1S T20L, MAC starts with 34:CE:00, model number Y01C0017
- Xiaofang 1S T20L, MAC starts with 78:11:DC, model number D01C0017

Should we build a model number database, so people can use the model number to choose which firmware to flash?

**Comment by jasonrmh** [comment]
This is a good idea.
How do you determine the correct model number?

**Comment by adamhun94** [comment]
Hey @snailium! 
How are your T20L cameras work with custom firmware? I'm about to purchase one, and I think I'll get a T20L as well. For me RTSP is mandatory, and I can't decide if it's working fine or not.
Thanks!

**Comment by snailium** [comment]
> Hey @snailium! 
> How are your T20L cameras work with custom firmware? I'm about to purchase one, and I think I'll get a T20L as well. For me RTSP is mandatory, and I can't decide if it's working fine or not.
> Thanks!

It works with the following configuration and swap enabled. But have some problem.

`
uEnv.txt

console=ttyS1,115200n8 mem=39M@0x0 ispmem=5M@0x2700000 rmem=20M@0x2C00000 init=/linuxrc rootfstype=squashfs root=/dev/mtdblock2 rw mtdparts=jz_sfc:256k(boot),2048k(kernel),3392k(root),640k(driver),4736k(appfs),2048k(backupk),640k(backupd),2048k(backupa),256k(config),256k(para),-(flag)

Video: > Size: 1920x1080 > Bitrate: 2000 > Format: SMART > Frame rate: 15 Audio: > Format: MP3 > In sample rate: 8000 > Out sample rate: 44100
`

Problem is it only last for a day, and then RTSP daemon crashes. So I also setup a cron to make it self-reboot every day.

Another problem is the automatic night mode is not reliable. I found very often it won't switch to night (IR) mode after I turn off the light.

If you are planning to use the camera to monitor a critical or important area, it is better get another brand.
