### ISSUE TITLE
Feature: trigger record service via MQTT

### ISSUE THREAD

**Issue by apat183** [EliasKotlyar/Xiaomi-Dafang-Hacks#1241]
### Description
Feature request, just like you can turn on motion detection and bunch of other services via MQTT, would be awesome to expose the record service and have that as a MQTT switch. Happy to try and contribute but looking at the mqtt-control.sh I couldn't see and understand how it calls other services to turn on etc.

**Comment by jmtatsch** [comment]
Good idea, you can use https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/143aba1159a5aae2acb35235cb48049fd95043b4/firmware_mod/scripts/mqtt-control.sh#L329 as a blueprint. Call "recording on" or "recording off" from common functions.

**Comment by apat183** [comment]
Submitted pull request, can close for now :) https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/pull/1246
