### ISSUE TITLE
PTZ not working (/system/sdcard/bin/motor: not found)

### ISSUE THREAD

**Issue by Buliwyf-Stonehand** [EliasKotlyar/Xiaomi-Dafang-Hacks#1243]
Camera: **Xiaomi Dafang**
Commit: 143aba1159a5aae2acb35235cb48049fd95043b4 

### Description

The camera does not move when the arrow buttons in _'System -> Pan / Tilt'_ are clicked or the calibration is started.

### Evidence

Log (Summary)

```
==> /var/log/lighttpd-cgi-stderr.log <==
/system/sdcard/www/cgi-bin/action.cgi: line 145: /system/sdcard/bin/motor: not found
/system/sdcard/www/cgi-bin/action.cgi: line 137: /system/sdcard/bin/motor: not found
/system/sdcard/www/cgi-bin/action.cgi: line 141: /system/sdcard/bin/motor: not found
/system/sdcard/www/cgi-bin/action.cgi: line 149: /system/sdcard/bin/motor: not found
```

**Comment by jmtatsch** [comment]
Maybe the motor binary got lost in an update. You can replace it manually or start with a fresh sd card.

**Comment by Buliwyf-Stonehand** [comment]
I already started with a fresh installation. The binary is in the _bin_ folder. I also tried another SD card.

**Comment by jmtatsch** [comment]
Can you call it manually?

**Comment by Buliwyf-Stonehand** [comment]
Nope.

```
[root@cam:~]# /system/sdcard/bin/motor left 100
-sh: /system/sdcard/bin/motor: not found
```

```
[root@cam:~]# /bin/sh /system/sdcard/bin/motor left 100
: not foundard/bin/motor: line 2:
/system/sdcard/bin/motor: line 6: syntax error: unexpected word (expecting "in")
```

**Comment by Buliwyf-Stonehand** [comment]
The problem was caused by the wrong kind of line ending in _motor_. I'm using Git on Windows and have `core.autocrlf` set to `auto`. Because there is no line ending specified for _motor_ in _.gitattributes_ and `text` is set to `auto`, the line endings were converted to _CRLF_.

To resolve this issue, I set `core.eol` to `lf` (default is `native` == _CRLF_ on Windows). Maybe you want to add `firmware_mod/bin/motor text eol=lf` to _.gitattributes_.
