### ISSUE TITLE
Video pixelizes or blurred 

### ISSUE THREAD

**Issue by justinbayliss** [EliasKotlyar/Xiaomi-Dafang-Hacks#1250]
I had been getting a lot of random pixeling and distortion on my videos. I am using a Wyzecam V2 with recent git pull. I appear to have found the solution. Basically the v412rtspserver-master process is competing for resources. Increasing the priority by adding **renice -n -15 -p $(cat "$PIDFILE")** between lines 93 and 94 in /controlscripts/rtsp-h264 seems to have resolved my issue. I hope you consider updating your code with this suggestion.

**Comment by aeckard87** [comment]
I’ve also noticed this - I’ll update on one of my Wyze v2 cams and see how it does. Thanks for sharing!

**Comment by jmtatsch** [comment]
Would be a great find, will also test on one of my dafangs. 
Why not nice starting the process directly instead of renicing?

**Comment by aeckard87** [comment]
@justinbayliss - what are your settings for video's? Also is it happening when you manually start recording or on motion detection triggered videos?

**Comment by justinbayliss** [comment]
@aeckard87 - I was seeing the issue accessing the RTSP feed directly(using VLC or a recorder like motionEyeOS) . I was doing continuous recording, no motion. I have really messed with my recording settings, so it would not be a good comparison. I am actually going to redo with a fresh OS with the latest updates, and start with only the changes that worked best. Due to all my other changes my recording was good, and then I changed something that made it go wacky.  But increasing the priority made the RTSP service work as expected.

**Comment by PixelDJ** [comment]
I have noticed this issue as well. I am using Wyzecam v2 and notice significant pixelation/blurring of the stream when using RTSP via VLC.

Making the change to my rtsp-h264 file hasn't done much for me yet, but I'm using default video settings. I will tweak some settings and post here if I come up with anything.

**Comment by mszefler** [comment]
I've had similar issues on a Wyze v2 running h264 at 640x480. I get pixelation and missing key frames. Problem seems to be more severe in night mode and  originally appeared to be  related to the location of the camera. Camera affected was one of 6, and was the one furthest from access point (40 feet). When I switched  the cameras at the various locations, the new most distant camera began exhibiting the symptoms.  Recently, another camera (one approximately 12 feet from access point) began exhibiting similar symptoms, so I am scratching my head.
