### ISSUE TITLE
Change WIFI via SSH?

### ISSUE THREAD

**Issue by fuzzewuzze** [EliasKotlyar/Xiaomi-Dafang-Hacks#1254]
I was hoping to modify my WPA supplicant file via Putty/SSH, but found it does not exist. 

Is there no way to modify your WIFI settings without taking the SD card out and modifying it via Windows?

I want to experiment with different WIFI extenders i have at my actual camera's mounting location outside without having to take it down and the SD card out repeatedly.

**Comment by meidyjordan** [comment]
> I was hoping to modify my WPA supplicant file via Putty/SSH, but found it does not exist.
> 
> Is there no way to modify your WIFI settings without taking the SD card out and modifying it via Windows?
> 
> I want to experiment with different WIFI extenders i have at my actual camera's mounting location outside without having to take it down and the SD card out repeatedly.

Hi @fuzzewuzze , have you tried it via FTP? You can copy the wpa_supplicant.conf file from the "system/sdcard/config/" on Cam folder to your computer and edit it and then restore it. The reboot the Cam. Hope this Help U.

**Comment by jmtatsch** [comment]
Your wifi wouldn't be working if that file wasn't there.
SSH to your device and `vi /system/sdcard/config/wpa_supplicant.conf`
