### ISSUE TITLE
I need solution for an idea. Connect the online Web server Internet camera (not local network)

### ISSUE THREAD

**Issue by pkadmin** [EliasKotlyar/Xiaomi-Dafang-Hacks#1256]
I would like to be able to modify the code so that the camera sent the information to a webServices developed by me.

For this I need to understand where I should modify I understand that there are customization scripts that could work for someone who has already tried this?

Any comments or ideas will be received. The issue is to go from the camera directly to the internet.

**Comment by drott** [comment]
I was able to get a gateway to work based on gstreamer's webrtc support, converting the rtsp h264 stream from the dafang camera to a webrtc stream that gets sent to browsers.
