### ISSUE TITLE
Easyway to turn of IR LED for nightmode?

### ISSUE THREAD

**Issue by Vinestou** [EliasKotlyar/Xiaomi-Dafang-Hacks#1259]
* exact camera hardware: Xiaomi Xiaofang 1S

### Description

My camera is behind a window and i have extra IR light outside shining on the path the camera is pointed at. I do need to use the nightmode but because of the window the IR LED from the camera itself make the image not usable 

So a permanent off for the IR light would be great.

### What did you do to debug the issue

Issue #847 has some sort of a solution but i really don't know how to do that without some extra explanation.

**Comment by jmtatsch** [comment]
Had the same issue with one of our cams. You can now set ir_led_off=true in autonight.conf to use night mode without IR leds. Please check out and report back.

**Comment by Vinestou** [comment]
@jmtatsch aa perfect. So just to be sure: i copy autonight.conf.dist to autonight.conf

and edit: 

```
autonight_mode=sw
hw_parameters=
sw_parameters='-S -j 3 -w 3 -1 1200000 -2 930000,14,10 -3 3000,17,8'
# set ir_led_off to true in front of IR reflecting windows
ir_led_off=true
```

**Comment by jmtatsch** [comment]
Yes, if autonight.conf didn't exist before it should be populated upon reboot from  autonight.conf.dist. Then you would need to set ir_led_off=true. Or populate autonight.conf manually from autonight.conf.dist.

**Comment by Vinestou** [comment]
autonight.conf was empty so i copied the info above and made it :true. Is that correctway?

**Comment by jmtatsch** [comment]
yes

**Comment by Vinestou** [comment]
Perfect. Ill test tonight.

**Comment by Vinestou** [comment]
@jmtatsch ok that worked! Thanks alot
