### ISSUE TITLE
Cant play audio on camera speaker along with v4l2rtspserver

### ISSUE THREAD

**Issue by iashwinprasada** [EliasKotlyar/Xiaomi-Dafang-Hacks#126]
I was trying to implement some sort of two-way communication to the camera along with streaming. Now the problem is when the camera is streaming and I play a test wav file on the camera, the audio stream on the v4l2rtspserver is getting corrupt and the audio doesn't recover. But I noticed that just restarting the v4l2rtspserver will fix the audio stream, indicating this is more of an application bug than the driver.

**Comment by jmtatsch** [comment]
Please continue discussing/helping in #323
