### ISSUE TITLE
Nvr board

### ISSUE THREAD

**Issue by wnleo** [EliasKotlyar/Xiaomi-Dafang-Hacks#1260]
dvr board specifications such as what can be used for rtsp xiofang hack

**Comment by meidyjordan** [comment]
> dvr board specifications such as what can be used for rtsp xiofang hack

Most dvr / nvr supports Onviv and RTSP. I use Hikvision brand NVR and can be used for Xiaofang RTSP.

**Comment by meidyjordan** [comment]
The most important thing is setting the video on Xiaofang that has been hacked, so that it can run stably during the stream. Because the issue of hang stream is very possible and we have to reset the video settings manually

**Comment by meidyjordan** [comment]
![image](https://user-images.githubusercontent.com/58964494/73534919-f36a6800-4454-11ea-94db-a90e656e3c87.png)
![image](https://user-images.githubusercontent.com/58964494/73534943-041ade00-4455-11ea-917f-00766a2e1ab7.png)
![image](https://user-images.githubusercontent.com/58964494/73534957-0b41ec00-4455-11ea-8797-068f177a3f00.png)
![image](https://user-images.githubusercontent.com/58964494/73534973-185edb00-4455-11ea-8dea-82d06bf09fad.png)
![image](https://user-images.githubusercontent.com/58964494/73534985-20b71600-4455-11ea-982d-3d32989e7b6b.png)

**Comment by wnleo** [comment]
really xiaofang I also experienced freeze, and it is very annoying when using it, can you help with the settings ... thanks for helping me

**Comment by meidyjordan** [comment]
> really xiaofang I also experienced freeze, and it is very annoying when using it, can you help with the settings ... thanks for helping me

Youre Welcome. I hope this can be useful for all.

**Comment by meidyjordan** [comment]
![image](https://user-images.githubusercontent.com/58964494/73592618-dace8080-452e-11ea-9bb3-0b668df1a7a5.png)
This is my Video Setting of Xiaofang 1S

**Comment by wnleo** [comment]
this setting reduces video clarity, but is good for streaming

**Comment by meidyjordan** [comment]
> this setting reduces video clarity, but is good for streaming

Yup. I have tested several settings to get optimal results. Until now Freeze Stream events are very rare. But the results of these settings can vary in others. 
I hope that someone can make RTSP run stable with high video quality when streaming

**Comment by wnleo** [comment]
whether wizcam has the same results as xiaofang

**Comment by wnleo** [comment]
whether wyzecam has the same results as xiaofang

**Comment by meidyjordan** [comment]
> whether wyzecam has the same results as xiaofang

I don't know for sure because I don't have a Wyze Cam. They look the same but don't know the engine. In my country it's expensive so I can't test it.
