### ISSUE TITLE
Wyze v2 Homeassistant Motion not detected

### ISSUE THREAD

**Issue by radinsky** [EliasKotlyar/Xiaomi-Dafang-Hacks#1266]
This is an issue tracking system only.
If you have general questions or are a newbie, please ask for help in our [chat channel](https://gitter.im/Xiaomi-Dafang-Hacks).

To make sure your issue can be resolved as quickly as possible please state your

* exact camera hardware: **Wyze Cam v2**
* the Xiaomi-Dafang-Hacks commitid (from `git log`) you are experiencing the issue with: latest

### Description

Motion detection (mqtt) binary sensor is always Clear.

### What did you do to debug the issue
Checked configuration, compared to other 2 dafang cameras where it is working, reboots of both homeassistant and camera, disabling enabling motion detection. Motion detection in dafang web seems to be working (the red dot in the corner appears on motion). Other MQTT control/status worked correct.

### Evidence

![image](https://user-images.githubusercontent.com/4540268/73691188-8c5de500-46da-11ea-9fa8-7cdd83ebc14d.png)
![image](https://user-images.githubusercontent.com/4540268/73691307-c3cc9180-46da-11ea-9f9a-96b4477a6ded.png)

**Comment by radinsky** [comment]
Actually motion over mqtt not working at all on Wyze v2, no mqtt snapshot sent, the config set correctly in /system/sdcard/config/motion.conf

```

# Configure the motion core parameters:

region_of_interest=0,0,1280,720
motion_sensitivity=2
motion_indicator_color=2
motion_timeout=-1
motion_detection=on
motion_tracking=off

# Configure how to deal with motion events:

motion_trigger_led=true
publish_mqtt_message=true
publish_mqtt_snapshot=true
send_email=false
send_telegram=false
telegram_alert_type=image
send_matrix=false


```

**Comment by jmtatsch** [comment]
Enable swap, camera might go out of memory when processing motion

**Comment by radinsky** [comment]
https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/1dde71af83b0798471e4880a77d583efb9cd26af/hacks/faq.md#what-if-my-scripts-in-configuserscriptsmotiondetection-are-not-executed-or-mqtttelegram-messagesemails-are-not-sent-on-motion
