### ISSUE TITLE
Duplicate mqtt entities "dafang_light_sensor"

### ISSUE THREAD

**Issue by radinsky** [EliasKotlyar/Xiaomi-Dafang-Hacks#1267]
* exact camera hardware: 2x Dafang  + Wyzecam v2
* the Xiaomi-Dafang-Hacks commitid (from `git log`) you are experiencing the issue with: latest

### Description

Getting the following fail in logs:
`homeassistant.exceptions.HomeAssistantError: Entity id already exists: sensor.dafang_light_sensor. Platform mqtt does not generate unique IDs`

Having 2 Dafangs (Xiaomi and Wyze) and Xiofang (Wyze cam v2)
On all light sensor set as "virtual" (couldn't get the hw work), but with false and hw value the behavior was the same.

### What did you do to debug the issue
Tried removing the entry from .storage entity/device registry..
### Evidence

`2020-02-04 00:44:48 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 410, in _async_add_entity
    raise HomeAssistantError(msg)
homeassistant.exceptions.HomeAssistantError: Entity id already exists: sensor.dafang_light_sensor. Platform mqtt does not generate unique IDs`

**Comment by jmtatsch** [comment]
Can you check if the issue persists with the newest version? Please reset the relevant topics in your mqtt broker...

**Comment by jonwaland** [comment]
seems fixed to me. 
(also had the issue - with only 1 dafang originally, now two)

**Comment by eekdood** [comment]
This was solved for me by manually removing the ldr topic from the broker.
