### ISSUE TITLE
Can't listening fifo with ossplay

### ISSUE THREAD

**Issue by kszere** [EliasKotlyar/Xiaomi-Dafang-Hacks#127]
I try make "Push To Talk" function for we camera. :)

I create fifo file and start playing:
`/system/sdcard/bin/ossplay -g 500 /run/listen-to-play.fifo`

Send *.wav file to fifo file.
`cat /system/sdcard/sounds/startup.wav >  /run/listen-to-play.fifo`

ossplay exit and return:
```
listen-to-play.fifo: File size is smaller than the form size!
listen-to-play.fifo: Couldn't find format chunk!
```

ossplay with `-f wav` param also not work, return: `Unsupported format name 'wav'!`

Do you have idea or solution?

**Comment by iashwinprasada** [comment]
#126

**Comment by kszere** [comment]
@iashwinprasada  I not understand. When runing v4l2rtspserver I can play sound from camera. This is other issue.

**Comment by iashwinprasada** [comment]
have you tried playing a wav file and live streaming? You can try this and let me know what's happening 

1. Start v4l2rtspserver with h264 and audio
2. Play with VLC
3. Now open dafang hacks page and press test audio playback

The audio on VLC will get corrupted

"Push to talk" along with live streaming will be the end goal, that's why I linked it.

**Comment by kszere** [comment]
I tested and sound from VLC works.
I listen echo from camera when play sounds,

**Comment by kszere** [comment]
Could you see this video?
[![Test sound from Xiaomi Dafang | Test #1](https://img.youtube.com/vi/VQ5hU71hM7E/0.jpg)](https://youtu.be/VQ5hU71hM7E)

**Comment by iashwinprasada** [comment]
That seems to be fine! hmmm, what am i missing. see my video here
[dafangaudioGlitch.zip](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/files/1768919/dafangaudioGlitch.zip)

**Comment by kszere** [comment]
I not have this problem.

**Comment by jmtatsch** [comment]
Probably outdated. Please reopen if still an issue.
