### ISSUE TITLE
wpa supplicant vulnerability - PSK encryption

### ISSUE THREAD

**Issue by morpheouso** [EliasKotlyar/Xiaomi-Dafang-Hacks#1270]
Has any thought been put into the potential vulnerability in having a network passkey unencrypted on the SD? I know these cameras are not designed for outdoor (insecure) mounting areas but housings exist and I'd like to use them in such a location. I'm currently looking to set up a separate SSID and vlan for these due to this security flaw but I was wondering in the feasibility in encrypting the PSK in the supplicant file?

**Comment by jmtatsch** [comment]
You can just enter the hashed pw into the config file. That doesn’t solve the issue though because with the hashed wpa key anyone can access your network as well.

**Comment by Morphy99** [comment]
Thanks I'll look into that as it's another barrier I guess. I'm going to put MAC authentication on the cameras SSID and hope I get a notification if it's stolen so I can remove it from the whitelist.

**Comment by morpheouso** [comment]
Thanks I'll look into that, it's another barrier I guess. I'm going to put MAC authentication on that network so at least if it's stolen I'll get a notification and be able to remove it from the whitelist.

**Comment by WarmChocolateCake** [comment]
Just FYI - I used wpa_passphrase on a Linux laptop to generate the config to copy into the microSD card's config file and it has been running fine.

**Comment by morpheouso** [comment]
Ah great I'll give this a go, I wasn't aware this was possible.

**Comment by jmtatsch** [comment]
Good. I will close this, as this is not really an issue that can be fixed while there is physical access.
