### ISSUE TITLE
Xiaofang hack in Octoprint

### ISSUE THREAD

**Issue by JeedHome44** [EliasKotlyar/Xiaomi-Dafang-Hacks#1273]
Hi,

I need to use my Xiaofang in Octoprint.

Someone can help me?

Thank you

**Comment by madiedinro** [comment]
Octoprint expect mjpeg stream therefore you should choose corresponding stream type at video stream options and type given url in octoprint preferences

**Comment by G1K** [comment]
mjpeg not working, see #1302
