### ISSUE TITLE
Streaks on image

### ISSUE THREAD

**Issue by sifus** [EliasKotlyar/Xiaomi-Dafang-Hacks#1274]
Hi,

i always had streaks on image when it refreshing :

<img width="1680" alt="Capture d’écran 2020-02-13 à 20 23 39" src="https://user-images.githubusercontent.com/2979258/74477400-87075400-4eab-11ea-9cb4-fc19f386b621.png">

**Comment by tERB00** [comment]
You are using third party software to view the camera. Maybe that's the problem.

**Comment by jmtatsch** [comment]
reduce the resolution until it streams the the complete image or enable or increase the swap space

**Comment by christ** [comment]
I've seen this problem with using ffmpeg and connecting to the RTSP stream with UDP instead of TCP. jeedom, which uses avconv, has the same flag you can set.
