### ISSUE TITLE
Flash OS then remove SD?

### ISSUE THREAD

**Issue by SamPhoenix91** [EliasKotlyar/Xiaomi-Dafang-Hacks#1275]
Is there a way to flash the camera so that Dafang stays on there permanently, so I can use the same SD card to flash multiple cameras?

**Comment by tERB00** [comment]
Internal storage is too small for CFW

**Comment by SamPhoenix91** [comment]
Whats the minimum size for the hack to work? I don't want to be buying a bunch of 16GB cards to only use a fraction of them

**Comment by jmtatsch** [comment]
Will you need to activate swap? Will you want to save any pictures, videos locally? Then go at least 16 G. Otherwise only the size of firmware_mod directory has to fit on it.
