### ISSUE TITLE
how to make MAC address static?

### ISSUE THREAD

**Issue by CleverJay** [EliasKotlyar/Xiaomi-Dafang-Hacks#1276]
Every time the camera reboots it has a new MAC address. I need it to have a static MAC address so that I can give it a DHCP reservation on router, so that I can use wget to grab the image from the camera and FTP it to a server. Is there a setting to "lock" the MAC Address?

**Comment by pr882** [comment]
Are you sure MAC address changes? I have mine MAC written on the camera and I thought that it cant be changed?

**Comment by CleverJay** [comment]
I am absolutely sure that the mac address is changing here is a log sample:
Dafang Cam Mac Address:

20200220 0830MST
00:e0:4c:d8:7b:ff

20200220 0847MST
00:e0:4c:4b:38:e6
after reboot.

The value is being generated by the OS at start-up. The question is, where is the start-up process getting the value and can I set it to be static?

**Comment by Dopeyr** [comment]
Not sure if it answers your question, but this is where the MAC is obtained: https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/firmware_mod/run.sh#L119, so it comes from `/params/config/.product_config`

**Comment by jmtatsch** [comment]
Yeah, just alter your run.sh to not read from .product_config but hardcode something.

**Comment by CleverJay** [comment]
Thanks jmtatsch, I will try that.

**Comment by CleverJay** [comment]
I commented out the Grep MAC line 119 and
hard coded the device MAC address in the Wyzecam V2 MAC line 128 and that solved the issue.
Thank you jmtatsch!

**Comment by milty456** [comment]
> Thanks jmtatsch, I will try that.

Hi, can you share exactly what you changed so i can mimic that please?  Having trouble getting it to work here.

**Comment by milty456** [comment]
How do i change the password and have it stick?  I go into the web interface; change it; it says changing to.....then if i reboot it; it uses the old pw.
