### ISSUE TITLE
wpa_supplicant.conf is deleted after startup

### ISSUE THREAD

**Issue by komadori1** [EliasKotlyar/Xiaomi-Dafang-Hacks#1277]
### Description

My Xiaomi Dafang used to work for months before without issue. I've added MQTT 4 weeks ago and telegram motion snapshots 2 weeks ago - both worked without issues.

Now when I go to the dafang webpage - it tells me unable to load image, so I tried powercycling and realized it won't connect to my router anymore.

Thus I checked the SD card and saw that my wpa_supplicant.conf was empty, which is why I guess it would not connect to my wifi

The startup log looked fine at the beginning, comparing it to other startup.log found on here, apart from not printing the "Startup finished!" line

### What did you do to debug the issue
I've tried to use a different SD-card and the latest firmware_mod from GitHub, but then the cam LED does not turn blue, but keeps flashing yellow. Checking the SD-card does not give me a log folder to check the startup-log.

I've used the same SD-card with the latest firmware_mod, but same yellow flashing LED without a log or wifi-connection.

If I revert the files from firmware_mod back to the one before, it connects with a blue LED, but the issues persist.

update:
I've used the newest firmware_mod again but this time enabled swap with the swap.conf - now the LED turns blue, still no connections

### Evidence

Please add snippets from the logfiles in:
* /system/sdcard/log/startup.log
==================================================
Starting the Dafang Hacks Custom Application Layer
==================================================
Loaded common functions
Created etc directory on sdcard
Bind mounted /system/sdcard/bin/busybox to /bin/busybox
Bind mounted /system/sdcard/root to /root
Bind mounted /system/sdcard/etc to /etc
Configuring swap file
Swap set on file /system/sdcard/swapfile
wpa_supplicant: wpa_supplicant v2.5
random: Trying to read entropy from /dev/random
Successfully initialized wpa_supplicant
Initializing interface 'wlan0' conf '/system/sdcard/config/wpa_supplicant.conf' driver 'default' ctrl_interface 'N/A' bridge 'N/A'
Configuration file '/system/sdcard/config/wpa_supplicant.conf' -> '/system/sdcard/config/wpa_supplicant.conf'
Reading configuration file '/system/sdcard/config/wpa_supplicant.conf'
ctrl_interface='/var/run/wpa_supplicant'
ctrl_interface_group='0'
ap_scan=1
Priority group 0
   id=0 ssid='UnifiAPLR_IoT'
nl80211: Could not add multicast membership for vendor events: -2 (No such file or directory)
rfkill: Cannot open RFKILL control device
nl80211: RFKILL status not available
nl80211: Supported cipher 00-0f-ac:1
nl80211: Supported cipher 00-0f-ac:5
nl80211: Supported cipher 00-0f-ac:2
nl80211: Supported cipher 00-0f-ac:4
nl80211: Using driver-based off-channel TX
nl80211: Disable use_monitor with device_ap_sme since no monitor mode support detected
nl80211: interface wlan0 in phy phy0
nl80211: Set mode ifindex 2 iftype 2 (STATION)
nl80211: Subscribe to mgmt frames with non-AP handle 0xb94268
nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0xb94268 match=06
nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0xb94268 match=0a07
nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0xb94268 match=0a11
nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0xb94268 match=1101
nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0xb94268 match=1102
nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0xb94268 match=0505
netlink: Operstate: ifindex=2 linkmode=1 (userspace-control), operstate=5 (IF_OPER_DORMANT)
nl80211: Could not re-add multicast membership for vendor events: -2 (No such file or directory)
nl80211: driver param='(null)'
Add interface wlan0 to a new radio phy0
nl80211: Regulatory information - country=00
nl80211: 2402-2472 @ 40 MHz 20 mBm
nl80211: 2457-2482 @ 40 MHz 20 mBm (no IR)
nl80211: 2474-2494 @ 20 MHz 20 mBm (no OFDM) (no IR)
nl80211: 5170-5250 @ 80 MHz 20 mBm (no IR)
nl80211: 5735-5835 @ 80 MHz 20 mBm (no IR)
nl80211: 57240-63720 @ 2160 MHz 0 mBm
nl80211: Added 802.11b mode based on 802.11g information
wlan0: Own MAC address: 78:11:dc:77:6a:50
wpa_driver_nl80211_set_key: ifindex=2 (wlan0) alg=0 addr=(nil) key_idx=0 set_tx=0 seq_len=0 key_len=0
wpa_driver_nl80211_set_key: ifindex=2 (wlan0) alg=0 addr=(nil) key_idx=1 set_tx=0 seq_len=0 key_len=0
wpa_driver_nl80211_set_key: ifindex=2 (wlan0) alg=0 addr=(nil) key_idx=2 set_tx=0 seq_len=0 key_len=0
wpa_driver_nl80211_set_key: ifindex=2 (wlan0) alg=0 addr=(nil) key_idx=3 set_tx=0 seq_len=0 key_len=0
wlan0: RSN: flushing PMKID list in the driver
nl80211: Flush PMKIDs
wlan0: Setting scan request: 0.100000 sec
ENGINE: Loading dynamic engine
ENGINE: Loading dynamic engine
EAPOL: SUPP_PAE entering state DISCONNECTED
EAPOL: Supplicant port status: Unauthorized
nl80211: Skip set_supp_port(unauthorized) while not associated
EAPOL: KEY_RX entering state NO_KEY_RECEIVE
EAPOL: SUPP_BE entering state INITIALIZE
EAP: EAP entering state DISABLED
ctrl_interface_group=0
wlan0: Added interface wlan0
wlan0: State: DISCONNECTED -> DISCONNECTED
nl80211: Set wlan0 operstate 0->0 (DORMANT)
netlink: Operstate: ifindex=2 linkmode=-1 (no change), operstate=5 (IF_OPER_DORMANT)
Daemonize..
udhcpc: deleting routers
adding dns 192.168.0.7
adding dns 212.33.36.155
adding dns 212.33.55.5
Initialized gpios
Determined image sensor model as jxf22
dropbear: 
lighttpd: 

* /var/log/*
3 files, lighthttpd-acces.log and lighthttpd-cgi-stderr.log are empty
lighthttpd-error.log:
2020-02-15 09:49:40: (server.c.1423) server started (lighttpd/1.4.50-devel-lighttpd-1.4.49-7-g26fb8d3e) 

Please tell me if there is something else I can provide

**Comment by komadori1** [comment]
Update:

I've reverted back to the working config and did:
https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/880#issuecomment-458704522

which made it update, changed wpa_supplicant back and I am online, the rtsp server does not start tough, so here are my logs:

Summary of all log files:

==> /var/log/lighttpd-access.log <==
192.168.0.7 192.168.0.18 root [15/Feb/2020:12:17:04 +0000] "GET /cgi-bin/action.cgi?cmd=motor_up&val=100 HTTP/1.1" 200 125 "https://192.168.0.18/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) snap Chromium/80.0.3987.100 Chrome/80.0.3987.100 Safari/537.36"
192.168.0.7 192.168.0.18 root [15/Feb/2020:12:17:05 +0000] "GET /cgi-bin/action.cgi?cmd=motor_up&val=100 HTTP/1.1" 200 125 "https://192.168.0.18/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) snap Chromium/80.0.3987.100 Chrome/80.0.3987.100 Safari/537.36"
192.168.0.7 192.168.0.18 root [15/Feb/2020:12:17:05 +0000] "GET /cgi-bin/action.cgi?cmd=motor_up&val=100 HTTP/1.1" 200 125 "https://192.168.0.18/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) snap Chromium/80.0.3987.100 Chrome/80.0.3987.100 Safari/537.36"
192.168.0.7 192.168.0.18 root [15/Feb/2020:12:17:06 +0000] "GET /cgi-bin/system_osd.cgi?_=1581769026381 HTTP/1.1" 200 14629 "https://192.168.0.18/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) snap Chromium/80.0.3987.100 Chrome/80.0.3987.100 Safari/537.36"
192.168.0.7 192.168.0.18 root [15/Feb/2020:12:17:06 +0000] "GET /cgi-bin/action.cgi?cmd=motor_up&val=100 HTTP/1.1" 200 125 "https://192.168.0.18/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) snap Chromium/80.0.3987.100 Chrome/80.0.3987.100 Safari/537.36"
192.168.0.7 192.168.0.18 root [15/Feb/2020:12:17:11 +0000] "GET /cgi-bin/system_audio.cgi?_=1581769031437 HTTP/1.1" 200 15516 "https://192.168.0.18/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) snap Chromium/80.0.3987.100 Chrome/80.0.3987.100 Safari/537.36"
192.168.0.7 192.168.0.18 root [15/Feb/2020:12:17:15 +0000] "GET /cgi-bin/system_admin.cgi?_=1581769034993 HTTP/1.1" 200 8199 "https://192.168.0.18/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) snap Chromium/80.0.3987.100 Chrome/80.0.3987.100 Safari/537.36"
192.168.0.7 192.168.0.18 root [15/Feb/2020:12:17:16 +0000] "GET /cgi-bin/system_video.cgi?_=1581769036473 HTTP/1.1" 200 20414 "https://192.168.0.18/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) snap Chromium/80.0.3987.100 Chrome/80.0.3987.100 Safari/537.36"
192.168.0.7 192.168.0.18 root [15/Feb/2020:12:17:18 +0000] "GET /cgi-bin/system_system.cgi?_=1581769038629 HTTP/1.1" 200 32997 "https://192.168.0.18/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) snap Chromium/80.0.3987.100 Chrome/80.0.3987.100 Safari/537.36"
192.168.0.7 192.168.0.18 root [15/Feb/2020:12:17:20 +0000] "GET /logs.html?_=1581769041491 HTTP/1.1" 200 6186 "https://192.168.0.18/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) snap Chromium/80.0.3987.100 Chrome/80.0.3987.100 Safari/537.36"

==> /var/log/lighttpd-cgi-stderr.log <==
cat: can't open '/tmp/v4l2rtspserver-master.log': No such file or directory
cat: can't open '/system/sdcard/log/update.log': No such file or directory
cat: can't open '/run/timelapse.pid': No such file or directory
cat: can't open '/run/timelapse.pid': No such file or directory
cat: can't open '/run/timelapse.pid': No such file or directory
cat: can't open '/run/timelapse.pid': No such file or directory

==> /var/log/lighttpd-error.log <==
2020-02-15 12:06:40: (server.c.1423) server started (lighttpd/1.4.50-devel-lighttpd-1.4.49-7-g26fb8d3e)

**Comment by komadori1** [comment]
When trying to manually start now the server with
v4l2rtspserver-master -W1280 -H720 -A -r 2 -P 8554

I just get
v4l2rtspserver-master: can't load library 'libliveMedia.so'

The file seems to be in the lib folder though

**Comment by jmtatsch** [comment]
Wow that is wild with wpa_supplicant.conf missing.
Have seen a bunch of cameras not being able to connect to wifi anymore, that would certainly explain it. Maybe your sdcard is written through or you had a power outage/weak power supply. 
Reformat/change you sdcard and start from scratch.

**Comment by komadori1** [comment]
Hey,

thank you for shooting me a reply!
Just to clarify: starting from scratch means to reload a stock firmware and then start anew with a bootloader, or simply copying the firmware_mod stuff onto a new SD-card, since the bootloader is already flashed?
If it is the latter, I have tried that already to no avail

**Comment by jmtatsch** [comment]
By starting from scratch I mean formatting the sdcard properly and copying the firmware_mod stuff.
