### ISSUE TITLE
Not getting anywhere setting up a Neos Cam

### ISSUE THREAD

**Issue by typhoon2099** [EliasKotlyar/Xiaomi-Dafang-Hacks#1279]
I've followed the guide [here](https://ryanfitton.co.uk/blog/install-dafang-custom-firmware-to-neos-smartcam/) and made it as far as flashing the CFW (step 5), but never get to the point where it installs successfully. Based on [the example video](https://www.youtube.com/watch?v=F-MnpGf6Iss) in that blog post I'm reaching the solid amber at 1:19 to 1:35, but I never see the blue and amber occulting led.

I've tried switching SD Cards (the first 2 cards wouldn't even get to the first blue light), and ensured that I have used a FAT32 partition no larger than 512MB, but I seem to be getting nowhere.

**Comment by digiltd** [comment]
@typhoon2099 it seems that things change, the the timing and sequence of the leds is one of them. It was a while back now, but this is how I managed to get it working https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/pull/964#issuecomment-555448876

**Comment by typhoon2099** [comment]
Yup, it turns out the flash was successful, but I didn't realise until I decided to turn on the camera normally and saw the solid blue light. I added the mod files to the SD card and I was up and running.
