### ISSUE TITLE
Video stream password not saved

### ISSUE THREAD

**Issue by JBS5** [EliasKotlyar/Xiaomi-Dafang-Hacks#1285]
Using version 2020-02-18T23:06:22Z on a Dafang camera but I am not able to set a video stream password. The username is saved, but the password keeps getting blank after refreshing the page, despite I click 'Set'

**Comment by jmtatsch** [comment]
Sorry, i cannot reproduce your issue. Can you start with a fresh rtspserver.conf?

**Comment by JBS5** [comment]
Solved. I was using special characters in the stream password. 
It was present in rtspserver.conf but not shown on the video settings page in the GUI.
After removing the characters from the password, the password is also shown on the video settings page in the GUI.
