### ISSUE TITLE
Auto night detection issue on Neos SmartCam

### ISSUE THREAD

**Issue by iceatcs** [EliasKotlyar/Xiaomi-Dafang-Hacks#1286]
Description of issue:
I couldn't get the auto night detection work on the Neos SmartCam. It will work if I'm on the SW night configuration page. 
Save the SW auto night setting won't do anything or switched HW and SW in the Video setting.

My 2 Xiaomi Dafang cameras are working well on auto night detection. I cloned this Dafang SD for Neos SmartCam, and still the same problem. It could be a device problem-related.

I have tried in many ways to debug the issue, no lucks so far. Even I've edited the autonight.conf file.

Only notice that the version on the bottom for Neo SmartCam is missing, whereas others have "Version: 2020-02-13T09:45:05Z" showed.

**Comment by jmtatsch** [comment]
Probably your neos doesn’t have a hardware light sensor. There is already an issue about software night mode not working. Please join and contribute there.
