### ISSUE TITLE
annoying click sound : please add hysteresis for light detection

### ISSUE THREAD

**Issue by ptempier** [EliasKotlyar/Xiaomi-Dafang-Hacks#1289]
Model | Xiaomi Xiaofang 1S
Firmware Version | Update for version string
Kernel Version | #32 PREEMPT Wed Jan 24 02:40:56 CST 2018
Bootloader Version | U-Boot 2013.07 (Jul 05 2018 - 17:59:02)
i dont have the commit id anymore

### Description

in low light condition, like when you watch a movie, the camera keeps making a click sound.
Apparently this happens when the camera switch to night mode.
Typically this happens when a trigger is at single value and the sensor keeps receiving data around that same value thus it keeps firing.
Usually the solution is to use two values, ie enter night mode when light is below 45, stop night mode when light is above 55.
Instead of using one value : 50, and sometime the sensor gets 49 and sometime 51 and the trigger keeps firing

### What did you do to debug the issue

Watch the camera feed when out of the room and the room is in low light condition.
In a closed room with nobody inside and curtain closed, the feed keeps switching between day mode and night mode and the camera keeps clicking.

### Evidence

Didn't found a log that contain that data

### Contribute Back

If your issue was resolved, please consider contributing back to the project by creating a pull request to improve the code or documentation in order to avoid that this issue arises again for other people.

**Comment by jmtatsch** [comment]
Look at the parameters of autonight with autonight -h for logging and tuning options

**Comment by ptempier** [comment]
Ok, apparently there's already some kind of hysteresis detection.
stupid me didn't saw there were a gui for it too.
i increased the time from 3 to 15 sec and the clicking seems to be gone, will confirm in 2-3 days.(typically happens at sunset)

**Comment by ptempier** [comment]
ok , no clicking today, i ll re-open if needed
