### ISSUE TITLE
MQTT - Status different than command = can't integrate in Home-Assistant

### ISSUE THREAD

**Issue by lolouk44** [EliasKotlyar/Xiaomi-Dafang-Hacks#129]
There is an issue with Home-Assistant in that defining an MQTT device requires the payload to be the same for status and command.
Currently we have (for example) status "on" for Blue LED, but on command is blue_led_on so Home-Assistant always returns an off status.
The way I made it work was to change the status to be the same as the command, so for blue led:
```
# Blue Led
blue=$(getgpio 39)
if [ "$blue" == "0" ]; then blue="blue_led_on"; fi
if [ "$blue" == "1" ]; then blue="blue_led_off"; fi
```

and in HA this the code I use:
```
- platform: mqtt
  name: "Dafang Kitchen Blue LED"
  state_topic: "Kitchen/DaFang/status"
  value_template: '{{ value_json.LEDs.Blue }}'
  command_topic: "Kitchen/DaFang/set"
  payload_on: "blue_led_on"
  payload_off: "blue_led_off"
  optimistic: false
```

Also can you update the script so that when a command is received, it publishes the status straight away? (at least for the items that return a status, i.e no point for the motor) This way I don't have to wait for up to 30 sec for the actual status to reflect in Home-Assistant...

Thanks :)

**Comment by lolouk44** [comment]
Actually ignore the status bit, here is the solution for it:
```
- platform: mqtt
  name: "Dafang Kitchen Blue LED"
  state_topic: "Kitchen/DaFang/status"
  value_template: "{% if value_json.LEDs.Blue == 'on' %}blue_led_on{% else %}blue_led_off{% endif %}"
  command_topic: "Kitchen/DaFang/set"
  payload_on: "blue_led_on"
  payload_off: "blue_led_off"
  optimistic: false
```

It would still be good to publish as soon as a command is received though

**Comment by shinebar1001** [comment]
That's no Problem - I have only Little time at the moment an will see, when I can do this.

**Comment by lolouk44** [comment]
Thanks, all we really need is to call the pub command when a message is received on the sub command...
Thanks

**Comment by shinebar1001** [comment]
so, if you publish dafang/set/blue_led_on it would be okay to answer with /dafang/blue_led_on - is the payload important? so, should it be like /dafang/blue_led with payload "on" or would /dafang/blue_led_on with any payload work?

**Comment by lolouk44** [comment]
At the moment when I send a command (e.g. blue light on), the light switch automatically goes back to off until the next time it reads the status.
All other MQTT driven lights normally reply to a command with the new status.
So yes 2nd option would make more sense:
Kitchen/DaFang/Blue_LED for status
Kitchen/DaFang/Blue_LED/set for commands, with the payload being ON or OFF

Thanks

**Comment by lolouk44** [comment]
check this post:
https://community.home-assistant.io/t/hacking-the-xiaomifang-wifi-camera/18579/76

**Comment by shinebar1001** [comment]
@lolouk44 
`Kitchen/DaFang/Blue_LED for status
Kitchen/DaFang/Blue_LED/set for commands, with the payload being ON or OFF`

please see the new version:
You can set the state of the leds with Kitchen/DaFang/Blue_LED/set Payload (on|off) and will get an immediate reply in Kitchen/DaFang/Blue_LED

I hope this implementation will help you.

**Comment by lolouk44** [comment]
I'm back on Monday, will try then. Thanks a lot

**Comment by lolouk44** [comment]
Thanks @shinebar1001 that works great.
If you could do the same with setting RTSP on and off it would be great :)
Then I won't bother you anymore :)

**Comment by lolouk44** [comment]
Ah sorry just a tiny request left: can you get the "new" statuses to also publish every [30] sec?

**Comment by shinebar1001** [comment]
No problem. Do you need the json status as well? I'm thinking of making this configurable: Staus as JSON / TEXT / NOTHING and Singlestats or something like this.

**Comment by lolouk44** [comment]
I personally would not need the JSON status as long as I have other entries available as their own topic like you did for the LEDs. But it might be a good idea to leave it there as an option for others who might need this format?
In case it helps, this is how HA defines an MQTT [switch](https://home-assistant.io/components/switch.mqtt/#configuration-variables), [light](https://home-assistant.io/components/light.mqtt/#configuration-variables), and [sensor](https://home-assistant.io/components/sensor.mqtt/#configuration-variables)

Thanks

**Comment by jmtatsch** [comment]
I think it would be great to keep the full json status updates.
I am currently preparing a tiny pull request for HA so it can be used like this:

```
  - platform: mqtt
    state_topic: "drachenhorst/dafang2/status"
    name: "DaFang2"
    json_attributes:
      - RTSP-Server
      - Uptime
      - IR-Cut
      - Wifi.SSID
      - LEDs
```

Otherwise we could also try to make mqtt autoconfiguration work.

**Comment by lolouk44** [comment]
Oooh I like that :) Thanks @jmtatsch

**Comment by jmtatsch** [comment]
@lolouk44 check out  https://github.com/home-assistant/home-assistant/pull/13177 and let me know if it works for you.

**Comment by msj33** [comment]
@jmtatsch - Very cool:-). Can you add HASS setup instructions to the documentation.

Could be cool to have both camera view, dafang status and control as full setup in HASS.

**Comment by lolouk44** [comment]
Hi @jmtatsch,

This is how I've done it. Bear in mind the mqtt settings are now it is date since the last changes in status 
https://community.home-assistant.io/t/hacking-the-xiaomifang-wifi-camera/18579/76

**Comment by shiznat** [comment]
The mqtt implementation was working for me up until an update to the mod firmware a few weeks ago. It appears the status portion of mqtt is still working but the payload/command does not.

**Comment by jmtatsch** [comment]
There are two pull requests fixing this

**Comment by jmtatsch** [comment]
Much has happened since then. There is HA support via autodiscovery for most things So lets close this and discuss improvements in new issues.
