### ISSUE TITLE
Inconsistent Power Consumption When Toggling RTSP h264 Server Status 

### ISSUE THREAD

**Issue by mauckc** [EliasKotlyar/Xiaomi-Dafang-Hacks#1291]
### Hardware
camera hardware: Wyze Can Pan

with custom bootloader for 1080p

### Description

I was trying to turn on and off the RTSP server to reduce power consumption.  I see that when the h264 RTSP server is on, the current draw is about **0.29 Amps**.

When I turn off the RTSP server, the current draw can drop either to **0.17 Amps** or **0.23 Amps**. I don't understand why it isn't always dropping down to 0.17 Amps **every time**. 

### Debug

I checked for hanging processes using ```top```, but I couldn't find anything related to the RTSP server.

### Evidence

Here is the plot from my measuring device:
![image](https://user-images.githubusercontent.com/8161032/75280992-4bca2680-57c3-11ea-9acf-e252ef5f9a5b.png)

Here is a closer look at just the current values:
<img width="741" alt="Toggling RTSP server ON and OFF" src="https://user-images.githubusercontent.com/8161032/75281826-d0697480-57c4-11ea-8309-ae988a15bb7f.PNG">

I am turning the rtsp_h264_server on then turning it off a few seconds later. Sometimes the current drops to ~0.17 A and sometimes it drops tp ~0.23 A. This also happens when I let the RTSP server be on for a longer time (not dependent on the duration of the RTSP status being "ON")

**Comment by saipsa** [comment]
what happens when you reboot the device after turning the server off? are the results consistent?

**Comment by mauckc** [comment]
> what happens when you reboot the device after turning the server off? are the results consistent?

After reboot, the wyze cam pan sits at ~0.183 Amps without running RTSP the server. Strange how that is higher than the lowest low I see in the graph above
