### ISSUE TITLE
person detection

### ISSUE THREAD

**Issue by qwertangel** [EliasKotlyar/Xiaomi-Dafang-Hacks#1295]
* exact camera hardware: wyze v2

wyze had person detection AI code running on camera hardware itself in old firmware ( https://support.wyzecam.com/hc/en-us/articles/360031188971-Person-Detection ) . any possibility to port it to dafang hacks and trigger MQTT ? that will be lot more useful than motion detection.

**Comment by yangqi** [comment]
It's not possible, wyze was using a third party service from Xnor.ai, which is not bought by Apple. So wyze cannot use their service and has removed person detection now.

**Comment by jmtatsch** [comment]
this looks interesting https://github.com/blakeblackshear/frigate

**Comment by nik0** [comment]
> this looks interesting https://github.com/blakeblackshear/frigate
This is a Python based project that need to be compiled first (or use Entware)
I doubt that the camera is powerfull enough for that. 
What can be done is to upload images to Amazon or Google cloud: they have API for that. Unforrtunatly you have to pay to have enough transaction.

Almost 2 years I found this https://github.com/Dafang-Hacks/Main/issues/28
Unfortunatly again the source disapear from Github. But it seems that T20 have some OpenCV capacity. It needed a crypto key to run the API. 
If someone have the dev kit ...
