### ISSUE TITLE
Auto Night/Day not switching on neos

### ISSUE THREAD

**Issue by OptimusGREEN** [EliasKotlyar/Xiaomi-Dafang-Hacks#1297]
This is an issue tracking system only.
If you have general questions or are a newbie, please ask for help in our [chat channel](https://gitter.im/Xiaomi-Dafang-Hacks).

To make sure your issue can be resolved as quickly as possible please state your

Neos Smart Cam
Version: 2020-02-23T01:51:51Z

### Description

Auto day or night not switching on its own unless the SW auto night setting web page is open.

### What did you do to debug the issue

tried turning auto night mode on and off, tried firmware upgrade

### Evidence

I dont see anything obvious in the log.

==================================================
Starting the Dafang Hacks Custom Application Layer
==================================================
Loaded common functions
Created etc directory on sdcard
Bind mounted /system/sdcard/bin/busybox to /bin/busybox
Bind mounted /system/sdcard/root to /root
Bind mounted /system/sdcard/etc to /etc
wpa_supplicant: wpa_supplicant v2.5.nova.1.02
random: Trying to read entropy from /dev/random
Successfully initialized wpa_supplicant
Initializing interface 'wlan0' conf '/system/sdcard/config/wpa_supplicant.conf' driver 'default' ctrl_interface 'N/A' bridge 'N/A'
Configuration file '/system/sdcard/config/wpa_supplicant.conf' -> '/system/sdcard/config/wpa_supplicant.conf'
Reading configuration file '/system/sdcard/config/wpa_supplicant.conf'
ctrl_interface='/var/run/wpa_supplicant'
ctrl_interface_group='0'
ap_scan=1
Priority group 2
   id=0 ssid='m******d'
nl80211: Could not add multicast membership for vendor events: -2 (No such file or directory)
rfkill: Cannot open RFKILL control device
nl80211: RFKILL status not available
nl80211: Supported cipher 00-0f-ac:1
nl80211: Supported cipher 00-0f-ac:5
nl80211: Supported cipher 00-0f-ac:2
nl80211: Supported cipher 00-0f-ac:4
nl80211: Disable use_monitor with device_ap_sme since no monitor mode support detected
nl80211: interface wlan0 in phy phy0
nl80211: Set mode ifindex 2 iftype 2 (STATION)
nl80211: Subscribe to mgmt frames with non-AP handle 0x712218
nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x712218 match=06
nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x712218 match=0a07
nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x712218 match=0a11
nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x712218 match=1101
nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x712218 match=1102
nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x712218 match=0505
netlink: Operstate: ifindex=2 linkmode=1 (userspace-control), operstate=5 (IF_OPER_DORMANT)
nl80211: Could not re-add multicast membership for vendor events: -2 (No such file or directory)
nl80211: driver param='(null)'
Add interface wlan0 to a new radio phy0
nl80211: Regulatory information - country=00
nl80211: 2402-2472 @ 40 MHz 20 mBm
nl80211: 2457-2482 @ 40 MHz 20 mBm (no IR)
nl80211: 2474-2494 @ 20 MHz 20 mBm (no OFDM) (no IR)
nl80211: 5170-5250 @ 80 MHz 20 mBm (no IR)
nl80211: 5735-5835 @ 80 MHz 20 mBm (no IR)
nl80211: 57240-63720 @ 2160 MHz 0 mBm
nl80211: Added 802.11b mode based on 802.11g information
wlan0: Own MAC address: a8:******:a0
wpa_driver_nl80211_set_key: ifindex=2 (wlan0) alg=0 addr=(nil) key_idx=0 set_tx=0 seq_len=0 key_len=0
wpa_driver_nl80211_set_key: ifindex=2 (wlan0) alg=0 addr=(nil) key_idx=1 set_tx=0 seq_len=0 key_len=0
wpa_driver_nl80211_set_key: ifindex=2 (wlan0) alg=0 addr=(nil) key_idx=2 set_tx=0 seq_len=0 key_len=0
wpa_driver_nl80211_set_key: ifindex=2 (wlan0) alg=0 addr=(nil) key_idx=3 set_tx=0 seq_len=0 key_len=0
wlan0: RSN: flushing PMKID list in the driver
nl80211: Flush PMKIDs
wlan0: Setting scan request: 0.100000 sec
ENGINE: Loading dynamic engine
ENGINE: Loading dynamic engine
EAPOL: SUPP_PAE entering state DISCONNECTED
EAPOL: Supplicant port status: Unauthorized
nl80211: Skip set_supp_port(unauthorized) while not associated
EAPOL: KEY_RX entering state NO_KEY_RECEIVE
EAPOL: SUPP_BE entering state INITIALIZE
EAP: EAP entering state DISABLED
ctrl_interface_group=0
wlan0: Added interface wlan0
wlan0: State: DISCONNECTED -> DISCONNECTED
nl80211: Set wlan0 operstate 0->0 (DORMANT)
netlink: Operstate: ifindex=2 linkmode=-1 (no change), operstate=5 (IF_OPER_DORMANT)
Writing wpa stat file /tmp/wpastat
Daemonize..
udhcpc: deleting routers
adding dns 192.168.1.1
Initialized gpios
Determined image sensor model as 
dropbear: 
lighttpd: 
Startup finished!

**Comment by jmtatsch** [comment]
Pls determine with what parameters your autonight executable is running with the tool ps.

**Comment by OptimusGREEN** [comment]
Is this the info you require?

-S -j 3 -w 3 -1 1200000 -2 930000,14,10 -3 3000,17,8

**Comment by jmtatsch** [comment]
Yes, so the autonight executable is running with these parameters?
And with these parameters it is switching when the page is open?

**Comment by OptimusGREEN** [comment]
Hi,

Yes that is right, it won't switch unless the page is open.

**Comment by jmtatsch** [comment]
Please try with a fresh firmware_mod checkout and fresh config files.

**Comment by 0n3-70uch** [comment]
I can confirm this for the Xiaomi Dafang. Clean install will not help. See here:
https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/1301

**Comment by 0n3-70uch** [comment]
Hotfix: https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/1301#issuecomment-594749251

**Comment by OptimusGREEN** [comment]
> Hotfix: [#1301 (comment)](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/1301#issuecomment-594749251)

Superb thanks
