### ISSUE TITLE
Camera Not Connecting and Cannot Read Log

### ISSUE THREAD

**Issue by SamPhoenix91** [EliasKotlyar/Xiaomi-Dafang-Hacks#1299]
The camera used to work, but has stopped. I have re-flashed default (neos) firmware (made sure I heard "ready to connect") and re-flashed custom bootloader successfully (Assuming by the fact it will not say "ready to connect"). 

I have changed wpa file and powered it on.
The camera just occasionally clicks of the night mode switching (caused by what I assume is the camera rebooting) and upon removing the SD card the logs are gibberish. (log atttached)

Have ordered a new SD in case that is the issue.

[log_44237CE69719_20190225124321_s.txt](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/files/4272928/log_44237CE69719_20190225124321_s.txt)

**Comment by jmtatsch** [comment]
Never seen anything like it.
You may want to hook up a serial console to see whats going on.

**Comment by SamPhoenix91** [comment]
Used the new SD card and the logs are now readable so guess it was the SD card. ~~still can't seem to connect but at least can have some insight~~ EDIT: Where I took the camera apart I hadn't plugged in the wifi antenna
