### ISSUE TITLE
cannot load bootloader

### ISSUE THREAD

**Issue by otakon87** [EliasKotlyar/Xiaomi-Dafang-Hacks#130]
Hello, I've bought a Xiaomi Dafang a few days ago, I'm following the installation instructions but  I cannot manage to write the bootloader. 

I'm using a 16Gb micro sd card, FAT file system, I copy the cfw 1.3 (tried 1.2 too) into it and rename it in demo.bin as instructed (so there's just thisfile on the memory card). Insert, then, in the camera and power it up while pressing the setup button (first question for how long? I've tried, one seconds, 10 seconds) but the camera just boot normally and connects to the wifi (i can control it via Mi Home app). What am I doing wrong? Thank you.

**Comment by nicolas-lang** [comment]
Same problem here (8GB Transcend SD, FAT32, CFW 1.3, pushed "Set-Up" like forever) . Except that mine has never been Set-Up properly as i wanted to avoid an Update of the Stock FW, in order to reduce Rooting-Troubles... 
is there a safe way to check the installed FW revision without doing OTA Update stuff?

**Comment by leonidas2522** [comment]
Try keep continue press the setup button until the base moving.

**Comment by nicolas-lang** [comment]
I kept the Button pushed down, until the Asian girl started talking to me, removed the power cable, and inserted the SD-card containing the firmware_mod files 
it would be really cool if the 'hack' could "touch" a  file on the SD indicating success 
With the mod_fw the device neither joined my WiFi nor did a "touch /system/sdcard/executed" which I added to run.sh generate a file on the SD

**Comment by otakon87** [comment]
@leonidas2522 The base moves after 20 seconds I think.. the instructions say "Wait until the firmware has finished flashing (like 5 minutes). Disconnect the power as soon as the base starts moving." So is my understanding that if the operation is successful the base will move after 5 minutes? If I have to remove the power when the base starts its movement, that's after a few seconds, not 5 minutes... Am I misunderstanding something here? Thank you

**Comment by leonidas2522** [comment]
Don't concern about time. Mine about 20 seconds too.
Just keep pressing and disconnect power when the base moving.

**Comment by cb416** [comment]
Hi, I had this issue a week ago and was able to resolve it.

You don't have to hold the setup button for very long, you can release it a few seconds after powering on.  The light turns blue while it's flashing if I remember correctly.  If you don't see blue, it's not working.
I was able to use FAT32 and didn't have to partition my microSD card.  The two main things I needed to resolve where:  
1) Make sure you have the real firmware renamed to demo.bin.  It should be >10MB.  (I right clicked and saved as, instead of using GitHub's download button)
2) There can only be demo.bin on the card.  Windows creates a hidden system directory that can't be there but I never found a way to delete or prevent within the Windows GUI.  I had to use a Linux PC to remove it.  You can try a USB bootable OS if you don't have another option.

**Comment by Dopeyr** [comment]
Hi,

I also found that if you don't hold down the setup button, or release too early and the original firmware starts, then that firmware creates directories on the sdcard (I think for recordings). That means demo.bin is no longer the only thing on the card.

It's worth taking the card out and double checking that demo.bin really is the only thing on the card.

**Comment by otakon87** [comment]
I did it! thank you guys... I had to use linux on virtual machine! there is no motion detection on this firmware right? just the direct view

**Comment by kevincaradant** [comment]
Hi guys

I have the same issue as you.

I downloaded the file of 11.1MB, rename it in demo.bin

It's the 5th times that I tried but everytime even when I push the button before to connect it with usb cable power, few seconds later, the spot turns, the lady speaks and that's all, she speaks very loud every 15 seconds and after that my sdcard have some folders that I have to remove on the computer. I use Linux ( in the aim  to remove the folders of Windows).

I use a TRANSEND 4GB Class 4. Is it a problem ? 

Someone can tell me if I do something wrong ? 

Thank you in advance

**Comment by nicolas-lang** [comment]
I had to use a Linux Boot-CD/USB in order to avoid having windows create a hidden "System Volume Information" folder, which makes the installation fail.
USB Stick for initial installation must never see windows after it has been prepared on linux.

**Comment by kevincaradant** [comment]
@nicolas-lang, is it an answer for me? I mean, I use only Linux to put demo.bin inside the SD card but nothing happen. Orange led blinking and that's all. Once the camera seems to was off after 1min. I don't know how to say if it works or not... After to reboot I didn't see any blue led blinking :/

**Comment by nicolas-lang** [comment]
yeah, it was meant as a summary, to encourage you, that most steps seem ok, and also to ensure you didnt use it in a windows pc in between.

My steps in summary:
- 2 SD cards for testing, one with the new firmware and one to install the bootloader
- linux FAT32-formatted SD card only with demo.bin ( **check with ls -a** )
- plug SDCard into camera
- press button with something harder than a fingertip to ensure it is "really" pressed
- plug power into camera while button is pressed and keep button pressed
- camera has led blue and orange, but "slightly longer that previously" in blue ( total time like 30-45 seconds for sure not 5m )  ( not sure when i released the button )
- camera starts moving/talking "asian"
- unplug power
- edit WiFi Settings on new firmware SD
- swap cards
- power up camera and check my wifi-base for new clients

**Comment by kevincaradant** [comment]
OK thank you I retry as you said, for the moment I pushed only twenty / thirty seconds, maybe should I stay more time pushed. But during this time, she speaks the first seconds then the stuff turns on 180 degrees, then the led stays in orange, the stuff do again 180 degrees, and now it's blinking orange but nothing happend so I think it doesn't work :(. I go to retry!

**Comment by kevincaradant** [comment]
Furthemore I have a bad hash, isn't it ?:

echo cfw-1.3.bin | sha256sum
48d3cd9af08f61c6ad1e4d8cf9f33fd216e4ffdf2c1c38651b4a432e7f7110ed
![image](https://user-images.githubusercontent.com/6093175/37879884-fa52dd9a-307f-11e8-9f2a-a360280d6bbd.png)


In the official doc:
![image](https://user-images.githubusercontent.com/6093175/37879881-e4461652-307f-11e8-8186-af9778f393ce.png)


I also tried with the old file in case:
![image](https://user-images.githubusercontent.com/6093175/37879876-c9620206-307f-11e8-89f9-65b0179b6aca.png)

**Comment by kevincaradant** [comment]
Ohhhhhh I think after the 10 tries, it's working, I pushed the button 30 seconds, after  30+5 seconds, the led blue shut down, and start in orange, two seconds after that, the stuff turns on 180 degrees but the lady didn't speak... I SWITCH OFF the camera and at the next reboot I get a blue led during 5 seconds! Is it good? :)

**Comment by T3rm1** [comment]
It doesn't work for me. I checked with Linux that I have only one file and that the checksum is correct. I tried holding the button for 3, 10 and 30 seconds. It never works. The camera always boots normally (2 clicks, then base starts moving).

**Comment by jmtatsch** [comment]
@T3rm1 first you must install the custom firmware, only from there you can install the new bootloader.

**Comment by T3rm1** [comment]
@jmtatsch oh sorry, I think I mixed things up. The first step where I put the demo.bin on the sd card and try to boot from it does not work. I think this is the custom firmware and not the bootloader.
I did more testing but it doesn't work. FS is FAT32 and I even booted into Linux to make sure there are no hidden files. The result is the same. The camera boots as usual.

**Comment by christhehoff** [comment]
@T3rm1 that's what I did too - Fat32 512MB partition (I changed the Allocation Size to) and finally had success
