### ISSUE TITLE
Question about wireguard vpn

### ISSUE THREAD

**Issue by davibe** [EliasKotlyar/Xiaomi-Dafang-Hacks#1304]
Does it make sense to integrate a VPN service as for example WireGuard (which is very lightweight i think) ? What is the common choice for installations that are behind NAT/Firewalls ?

**Comment by josephdouce** [comment]
I don't think we would have the headroom to put a vpn onbaord, run a vpn somewhere else on your network, I'm using a rpi running pivpn to vpn into my home network.
