### ISSUE TITLE
Can't get any static image with https://IP/cgi-bin/currentpic.cgi

### ISSUE THREAD

**Issue by sergueibucka** [EliasKotlyar/Xiaomi-Dafang-Hacks#1305]
Hi.
I had this working in the past...
https://192.168.0.4/cgi-bin/currentpic.cgi

I don't get any response back but I can see the live stream using:
rtsp://root: ismart12@192.168.0.4:8554/unicast

What I am missing?

thanks

**Comment by jmtatsch** [comment]
Seems like there is a stray whitespace in your url

**Comment by sergueibucka** [comment]
@jmtatsch thanks. There was typo in the IP but no stray whitespace.

**Comment by sergueibucka** [comment]
@jmtatsch I haven't resolved it

**Comment by jmtatsch** [comment]
You miss the basic auth parameters

**Comment by sergueibucka** [comment]
https://root:ismart12@192.168.0.4/cgi-bin/currentpic.cgi

Still nothing
