### ISSUE TITLE
Lighttpd: user/password sent in clear (HTTP) before redirect to HTTPS

### ISSUE THREAD

**Issue by Knurlnheim** [EliasKotlyar/Xiaomi-Dafang-Hacks#1309]
Hello,

I noticed that my browser is asking for username/password two times when connecting to the camera from browser coldstart.
In lighttpd.conf, we ask for authentification even if protocol is http, resulting in cleartext transmission... and only then we redirect to https.

I think the fix is simple, I will try to push a PR today.

**Comment by jmtatsch** [comment]
Might have to do with the forced connection upgrade to https. Would very much appreciate a PR.
