### ISSUE TITLE
rtsp stream sharing to internet

### ISSUE THREAD

**Issue by S1NNxs** [EliasKotlyar/Xiaomi-Dafang-Hacks#1314]
Hi! Have problem with rtsp steam sharing to internet. In local network is working as well, but i cant connect from outside. Port forwarding and DMZ were tried, is there some another configuration that i need turn on?

Thanks for helping!

**Comment by coax** [comment]
If it works okay on local network - it must be invalid configuration on your router.
You'll need to set up DDNS and port forwarding (protocol TCP, in/out port 8554).
