### ISSUE TITLE
Telegram Bot Settings

### ISSUE THREAD

**Issue by btutal** [EliasKotlyar/Xiaomi-Dafang-Hacks#1315]
Hi,

I've configured Telegram bot successfully and can interact with it but it keeps sending photos for every motion even though I sent /off command and got the response back. What are the right settings under System/Services to have a proper Telegram bot ? Is there any place where I can read about it?

**Comment by jmtatsch** [comment]
You got response "Motion detection stopped" and still get sent new pictures?

**Comment by btutal** [comment]
Yes but apparently it was old photos just delivered after "Motion detection stopped" message. This issue can be closed
