### ISSUE TITLE
Blank page

### ISSUE THREAD

**Issue by adrianmihalko** [EliasKotlyar/Xiaomi-Dafang-Hacks#1321]
This is an issue tracking system only.
If you have general questions or are a newbie, please ask for help in our [chat channel](https://gitter.im/Xiaomi-Dafang-Hacks).

To make sure your issue can be resolved as quickly as possible please state your

* exact camera hardware:
* the Xiaomi-Dafang-Hacks commitid (from `git log`) you are experiencing the issue with:

Xiaofang cube 1st generation

### Description

I followed the installation guide, but when I am trying to access admin page I get only blank page.

### What did you do to debug the issue

This is not a cache issue.

I can ping the device after half minute:

```
$ ping 192.168.1.154
PING 192.168.1.154 (192.168.1.154): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
Request timeout for icmp_seq 3
Request timeout for icmp_seq 4
Request timeout for icmp_seq 5
Request timeout for icmp_seq 6
ping: sendto: No route to host
Request timeout for icmp_seq 7
ping: sendto: Host is down
Request timeout for icmp_seq 8
ping: sendto: Host is down
Request timeout for icmp_seq 9
ping: sendto: Host is down
Request timeout for icmp_seq 10
ping: sendto: Host is down
Request timeout for icmp_seq 11
ping: sendto: Host is down
Request timeout for icmp_seq 12
ping: sendto: Host is down
Request timeout for icmp_seq 13
ping: sendto: Host is down
Request timeout for icmp_seq 14
ping: sendto: Host is down
Request timeout for icmp_seq 15
ping: sendto: Host is down
Request timeout for icmp_seq 16
ping: sendto: Host is down
Request timeout for icmp_seq 17
ping: sendto: Host is down
Request timeout for icmp_seq 18
ping: sendto: Host is down
Request timeout for icmp_seq 19
Request timeout for icmp_seq 20
64 bytes from 192.168.1.154: icmp_seq=21 ttl=64 time=69.441 ms
```

Trying to access admin page, response is 200 and empty body:

```
$ curl 192.168.1.154 -v -L
*   Trying 192.168.1.154...
* TCP_NODELAY set
* Connected to 192.168.1.154 (192.168.1.154) port 80 (#0)
> GET / HTTP/1.1
> Host: 192.168.1.154
> User-Agent: curl/7.64.1
> Accept: */*
>
* HTTP 1.0, assume close after body
< HTTP/1.0 200 OK
< Date: Thu, 26 Mar 2020 19:49:16 GMT
< Server: Boa/0.94.13
< Connection: close
< Last-Modified: Thu, 26 Mar 2020 19:49:16 GMT
< Content-Type: text/html
<
* Closing connection 0
```

Cannot connect trough SSH as well:

```
$ ssh root@192.168.1.154 -v
OpenSSH_7.9p1, LibreSSL 2.7.3
debug1: Reading configuration data /Users/adrianmihalko/.ssh/config
debug1: /Users/adrianmihalko/.ssh/config line 1: Applying options for *
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 48: Applying options for *
debug1: Connecting to 192.168.1.154 [192.168.1.154] port 22.
debug1: connect to address 192.168.1.154 port 22: Connection refused
ssh: connect to host 192.168.1.154 port 22: Connection refused
```

I tried with 2 memory card: 128MB and 32GB. Same results.

### Evidence

Please add snippets from the logfiles in:
* /system/sdcard/log/startup.log
* /var/log/*
* dmesg
* logcat
and/or screenshots you deem relevant.

I don't see any log files on sdcard.

Maybe I have wrong device version?

![IMG_3902](https://user-images.githubusercontent.com/733361/77693287-5e917000-6fa8-11ea-8bf5-433809b6cdfb.jpg)

### Contribute Back

If your issue was resolved, please consider contributing back to the project by creating a pull request to improve the code or documentation in order to avoid that this issue arises again for other people.

**Comment by jmtatsch** [comment]
Lock at the logfiles in the log directory of your sdcard.

**Comment by adrianmihalko** [comment]
> Lock at the logfiles in the log directory of your sdcard.

There is no log folder on the sd card. 

On other hand Fang Hacks is working without any problem for first try. Is this a compatibility issue then?

**Comment by jmtatsch** [comment]
Fang hacks and dafang hack are for different platforms.
If there is no log folder the custom firmware did not start at all.

**Comment by pascaltsc** [comment]
Same problem here.
Freshly prepared a SD-Card, from latest Zip File
Edit wpa_supplicant... Boot...
Ping reacts after some seconds
But blank page, no ssh.
Mac 34:CE...

**Comment by scotie** [comment]
Had the same issue with dafang and didn't have any logs on the camera.
Formated the card and started fresh. Resolved the issue.
Both times were with the latest files
