### ISSUE TITLE
No video after today update

### ISSUE THREAD

**Issue by serejks** [EliasKotlyar/Xiaomi-Dafang-Hacks#1327]
No video after today update
2 devices - xiaofang mac 78 and dafang mac 78

**Comment by jmtatsch** [comment]
Cannot reproduce on my dafang. Maybe a botched autoupdate. Can you start fresh?

**Comment by serejks** [comment]
Updated agayn - same issue (

**Comment by serejks** [comment]
RTSP h246 server does not starts automatically, when i start it manually he is stopping

**Comment by serejks** [comment]
SSL certificate is expired at 30.10.2019.
This is can be a reason of no image?

**Comment by jmtatsch** [comment]
Unlikely. Just start fresh, it will generate a new cert.

**Comment by serejks** [comment]
Start fresh? Install hack from zero?

**Comment by jmtatsch** [comment]
Just format your sd and pull a fresh firmware_mod copy on it.

**Comment by serejks** [comment]
ok, i'll try to configure from zero (

**Comment by serejks** [comment]
yeah, fresh install fixed an issue.
but which reason to appear it?
