### ISSUE TITLE
getting web access to /system/sdcard/DCIM/motion

### ISSUE THREAD

**Issue by fanaticsurf** [EliasKotlyar/Xiaomi-Dafang-Hacks#1328]
Xiaomi Dafang
newest firmware : Version: 2020-03-28T20:47:55Z

### Description

I would like to add web access to the pics and videos in /system/sdcard/DCIM/motion

### What did you do to debug the issue

I can't create a symlink in document root

or
add the module mod_alias in lighttpd.conf (webserver not accesible afterwards):
server.modules = ("mod_alias",
"mod_auth",
...

nor
enable the mod_alias with lighty-enable-mod, because it is not available in the firmware.

### Evidence

[root@DAFANG:www]# ln -s /system/sdcard/DCIM/motion .
ln: ./motion: Operation not permitted

**Comment by Combie81** [comment]
I did ask a month or so ago about updateing lightttp to the laterst release so adding this into the build of it at that time would be handy - along with SMB support(I really want/need this!)

**Comment by fanaticsurf** [comment]
SMB Support could also be a solution for me to get access to the files.

**Comment by nik0** [comment]
> I did ask a month or so ago about updateing lightttp to the laterst release so adding this into the build of it at that time would be handy - along with SMB support(I really want/need this!)

What version of lightttp do you need ? I made a PR with the latest 1.4 version

**Comment by Combie81** [comment]
> > I did ask a month or so ago about updateing lightttp to the laterst release so adding this into the build of it at that time would be handy - along with SMB support(I really want/need this!)
> 
> What version of lightttp do you need ? I made a PR with the latest 1.4 version

I just thought upgrading to the latest version (1.4.55) would be beneficial to get the latest patches.  

Can SMB support/binaries also be included?  I'm very tech savvy but this is beyond my capabiliteis to add in(really would like to learn how to!) but having this would be perfect for saving files to my network shares where they are backed up.

Thanks for the other updates too nik0 :)

**Comment by jmtatsch** [comment]
smb support hasm been there for quite a while, see motion.conf to enable it.

**Comment by Combie81** [comment]
I've changed settings as below but had no luck in getting it working.  Tried variations of domain and local user with both / and \ slashes and sub paths are created within the CCTV share:

smb_snapshot=true
smb_video=true
smb_share="//my-server/CCTV"
smb_username="domain\user"
smb_password="userpass"
smb_stills_path="door_camera/stills"
smb_videos_path="door_camera/videos"

**Comment by Masch67** [comment]
Same problem on my Dafang Camera. SMB isn't present or activated.

**Comment by fanaticsurf** [comment]
@nik0 please include mod_alias in the new lighttpd version

**Comment by jmtatsch** [comment]
@Combie81 smb support is realized via /system/bin/smbclient
you can try to debug from there

**Comment by jmtatsch** [comment]
I absolutely agree that it would be very nice to have some kind of interface to view/manage the recorded videos.

@fanaticsurf liked your symlink idea, unfortunately /system/sdcard/DCIM/motion is on a FAT formatted partition which doesn't support symlinks.

**Comment by nik0** [comment]
> @nik0 please include mod_alias in the new lighttpd version

On it's way, please chec:  https://github.com/nik0/Xiaomi-Dafang-Hacks/commit/eaae5fa3d0df0bf78dba0509e4bf66972b0d60b5

**Comment by fanaticsurf** [comment]
@nik0 :+1:

**Comment by Masch67** [comment]
> @Combie81 smb support is realized via /system/bin/smbclient
> you can try to debug from there

I have set up a smb save in motion.conf and tried to run detectionOn.sh in a ssh session.
Found those errors 

> params.c:OpenConfFile() - Unable to open configuration file "/usr/samba/config/s                                                                                                                     mb.conf":
>         No such file or directory
> Can't load /usr/samba/config/smb.conf - run testparm to debug it
> load_client_codepage: filename /usr/samba/lib/codepages/codepage.850 does not ex                                                                                                                     ist.
> load_unicode_map: filename /usr/samba/lib/codepages/unicode_map.850 does not exi                                                                                                                     st.
> load_unicode_map: filename /usr/samba/lib/codepages/unicode_map.ISO8859-1 does n                                                                                                                     ot exist.
> 

Sorry, I'm only a new user trying to use the hack ...

**Comment by jmtatsch** [comment]
For web access to DCIM check out commit https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/commit/ec57bb3af71b82a326acb0661637b3e08c27b9ad on the beta branch.
You will need to delete/adjust your lighttpd.conf though. If someone knows how to keep the link to the viewer in the responsive bulma framework with the links to the directories resolving correctly please let me know.

**Comment by fanaticsurf** [comment]
Thanks for updating lighttpd + conf in beta branch. Access to pics and videos works fine, but in beta branch I recognized that videos are recorded with the size of 0.
Updating back to master branch the videos are recorded successfully again.
Switching back to beta branch I get the issue back.
#1382

**Comment by GSVNoFixedabode** [comment]
Looking at list of timelapse files, the download link appears incorrect: .../viewer/timelapse/2020-05-29/10/2020-05-29_10-52-35_001.jpg but viewer is not currently defined in lighttpd.conf I'm on Version: commit 652365d from branch master. I recently updated to master via the 'update' command.

**Comment by GSVNoFixedabode** [comment]
Any suggestions?

**Comment by carefulcomputer** [comment]
ping.
