### ISSUE TITLE
Not working after official test

### ISSUE THREAD

**Issue by nbourre** [EliasKotlyar/Xiaomi-Dafang-Hacks#133]
Hey guys,

I've tested the hack when it was the CFW-1.2.bin and the hack was working. After I tested the Mi Home app to see if it was working it did and also seem to have done some updates.

After doing so, I've tried to reinstall the hack without success. The new firmware CFW-1.3 seems to have installed, but the camera does execute the "run.sh" file. I've add a "touch" command to write to the sdcard, but it did work.

Did something major changed between 1.2 and 1.3? Can a new version write a simple text file on the sd card when the firmware installed correctly?

Thanks

**Comment by kszere** [comment]
@EliasKotlyar Can you describe changes between CWF v1.2 and  CWF v1.3?

**Comment by jmtatsch** [comment]
Since 522508869f219868095cfed4f1d967e2e2f70dff the camera writes a startup.log in the log directory of your sd card. This can possibly help you with figuring out your issues. closing this for now.
