### ISSUE TITLE
Help! Xiaomi DAFANG: lighttpd webserver is not working after update. Illeagal instruction

### ISSUE THREAD

**Issue by int2018** [EliasKotlyar/Xiaomi-Dafang-Hacks#1332]
Hallo,

I have a Xiaomi DAFANG and I was running the firmware version from 07. March without big issues (besides rtsp stream breaks)
I wanted to check out the ONVIF feature so I started the frmware update via the web interface.
The update was working and the camera did reboot but the webpage does not load. 
I can access the camrea via ssh and I noticed that the lighttpd is not running.
I tried to start that from the terminal (same command as in the run.sh) but it fails with the messge: Illeagal instruction

Help....

I dont know the exact hardware of th cam, sorry. The label says DF3 CMIIT2017DP3894
uname -a:
Linux DAFANG 3.10.14 #21 PREEMPT Thu Oct 19 11:38:16 CST 2017 mips GNU/Linux
free
              total        used        free      shared  buff/cache   available
Mem:          99640       21404       42904           0       35332           0
-/+ buffers/cache:        21404       78236

startup.log:

==================================================
Starting the Dafang Hacks Custom Application Layer
==================================================
Loaded common functions
Created etc directory on sdcard
Bind mounted /system/sdcard/bin/busybox to /bin/busybox
Bind mounted /system/sdcard/root to /root
Bind mounted /system/sdcard/etc to /etc
wpa_supplicant: wpa_supplicant v2.5
random: Trying to read entropy from /dev/random
Successfully initialized wpa_supplicant
Initializing interface 'wlan0' conf '/system/sdcard/config/wpa_supplicant.conf' driver 'default' ctrl_interface 'N/A' bridge 'N/A'
Configuration file '/system/sdcard/config/wpa_supplicant.conf' -> '/system/sdcard/config/wpa_supplicant.conf'
Reading configuration file '/system/sdcard/config/wpa_supplicant.conf'
ctrl_interface='/var/run/wpa_supplicant'
ctrl_interface_group='0'
ap_scan=1
Priority group 3
   id=2 ssid='---'
Priority group 2
   id=1 ssid='---'
Priority group 1
   id=0 ssid='---'
nl80211: Could not add multicast membership for vendor events: -2 (No such file or directory)
rfkill: Cannot open RFKILL control device
nl80211: RFKILL status not available
nl80211: Supported cipher 00-0f-ac:1
nl80211: Supported cipher 00-0f-ac:5
nl80211: Supported cipher 00-0f-ac:2
nl80211: Supported cipher 00-0f-ac:4
nl80211: Using driver-based off-channel TX
nl80211: Disable use_monitor with device_ap_sme since no monitor mode support detected
nl80211: interface wlan0 in phy phy0
nl80211: Set mode ifindex 2 iftype 2 (STATION)
nl80211: Subscribe to mgmt frames with non-AP handle 0x4cd268
nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x4cd268 match=06
nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x4cd268 match=0a07
nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x4cd268 match=0a11
nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x4cd268 match=1101
nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x4cd268 match=1102
nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x4cd268 match=0505
netlink: Operstate: ifindex=2 linkmode=1 (userspace-control), operstate=5 (IF_OPER_DORMANT)
nl80211: Could not re-add multicast membership for vendor events: -2 (No such file or directory)
nl80211: driver param='(null)'
Add interface wlan0 to a new radio phy0
nl80211: Regulatory information - country=00
nl80211: 2402-2472 @ 40 MHz 20 mBm
nl80211: 2457-2482 @ 40 MHz 20 mBm (no IR)
nl80211: 2474-2494 @ 20 MHz 20 mBm (no OFDM) (no IR)
nl80211: 5170-5250 @ 80 MHz 20 mBm (no IR)
nl80211: 5735-5835 @ 80 MHz 20 mBm (no IR)
nl80211: 57240-63720 @ 2160 MHz 0 mBm
nl80211: Added 802.11b mode based on 802.11g information
wlan0: Own MAC address: 78:11:dc:45:4d:a6
wpa_driver_nl80211_set_key: ifindex=2 (wlan0) alg=0 addr=(nil) key_idx=0 set_tx=0 seq_len=0 key_len=0
wpa_driver_nl80211_set_key: ifindex=2 (wlan0) alg=0 addr=(nil) key_idx=1 set_tx=0 seq_len=0 key_len=0
wpa_driver_nl80211_set_key: ifindex=2 (wlan0) alg=0 addr=(nil) key_idx=2 set_tx=0 seq_len=0 key_len=0
wpa_driver_nl80211_set_key: ifindex=2 (wlan0) alg=0 addr=(nil) key_idx=3 set_tx=0 seq_len=0 key_len=0
wlan0: RSN: flushing PMKID list in the driver
nl80211: Flush PMKIDs
wlan0: Setting scan request: 0.100000 sec
ENGINE: Loading dynamic engine
ENGINE: Loading dynamic engine
EAPOL: SUPP_PAE entering state DISCONNECTED
EAPOL: Supplicant port status: Unauthorized
nl80211: Skip set_supp_port(unauthorized) while not associated
EAPOL: KEY_RX entering state NO_KEY_RECEIVE
EAPOL: SUPP_BE entering state INITIALIZE
EAP: EAP entering state DISABLED
ctrl_interface_group=0
wlan0: Added interface wlan0
wlan0: State: DISCONNECTED -> DISCONNECTED
nl80211: Set wlan0 operstate 0->0 (DORMANT)
netlink: Operstate: ifindex=2 linkmode=-1 (no change), operstate=5 (IF_OPER_DORMANT)
Daemonize..
udhcpc: deleting routers
adding dns 192.168.---
Initialized gpios
Determined image sensor model as jxf22
dropbear:
lighttpd:
Startup finished!
[root@DAFANG:log]#

**Comment by int2018** [comment]
Hm... even worse, I run the autoupdate,sh and confirmed the update ob binaries. After reboot the cam is not availabe in my WLAN. 
:-(

**Comment by jmtatsch** [comment]
Just start with a fresh firmware mod. There was a non functional commit some hours ago, you might have caught that.

**Comment by int2018** [comment]
Thanks I will try tomorrow, I don't have an SD card adapter here ....
Stay healthy :-)

**Comment by int2018** [comment]
Ok, during update via the web gui somehow the wlan config file was wiped to 0 bytes and of course no access to the camera. I found an entry in the lighttpd-cgi-stderror.lo about an invalid  "-S" parameter but I dont remember.
Anyway, I updated the files on the SD card with latest firmware, updated the wlan config and everything works. Thanks.
