### ISSUE TITLE
mqtt_autodiscovery.sh script error.

### ISSUE THREAD

**Issue by Masch67** [EliasKotlyar/Xiaomi-Dafang-Hacks#1335]
Hello,
The mqtt_autodiscovery.sh script doesn't work.
I tried it out in a ssh session and had following errors :

![image](https://user-images.githubusercontent.com/28890762/78678096-ccaf2e80-78e8-11ea-9818-31251031da18.png)

I had an old version of this script (2019-05) and t's working fine...

**Comment by Masch67** [comment]
Well I think the problem is my MQTT password. I've set a password starting with the $ character and in the string $COMMAND the password doesn't appear… 
I changed the password to a string not starting with the $ character and now everything works well 👍 

So the problem isn't in the script :)

**Comment by Masch67** [comment]
Ok, the issue is closed, but the mqtt_autodiscover.sh script doens't work when MQTT Password begins with the $ character. As far I know, those password are not prohibited in MQTT. I use then elsewhere (by example in Home Assistant) and it works fine....

**Comment by jmtatsch** [comment]
$something causes trouble in shell scripting. Maybe you can make a pull request escaping things properly.
