### ISSUE TITLE
[Feature Request] More OSD Colors

### ISSUE THREAD

**Issue by BiatuAutMiahn** [EliasKotlyar/Xiaomi-Dafang-Hacks#1336]
Can you add more OSD colors? Or color inversion? Thank you

**Comment by nik0** [comment]
Check https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/pull/1411
Now with new setconf you can set colors in RGBA like this:
`
setconf -k c -v 0xR,0XG,0XB,0xA
or
setconf -k c -v 0xRGBA
`
With R as red value, G as green, B as blue, and A as alpha (transparency)
I din't update the GUI to add a RGB selector, feel free to do it
Anyway this is backward compatible, tou can edit file config/osd.conf to set color like this 0xRGBA
