### ISSUE TITLE
low quality with freezes 

### ISSUE THREAD

**Issue by elect0nik** [EliasKotlyar/Xiaomi-Dafang-Hacks#134]
Elias, thank you for this tremendous work you doing! I been reading some topics here and it seems that video quality is good for most people, for me it's awful for some reason, low quality, 1 frame in 10 seconds. what can i check? FTP upload speed from camera is 1.2-2 mbytes/s. i'm using 5.5.1.200

**Comment by shinebar1001** [comment]
Can you probably try to lower the bitrate?

> setconf -k b -v 1000

**Comment by elect0nik** [comment]
where, in run.sh?
for some reason my camera has very unstable connection with router, despite it's being 1m from it now. 
all other wifi devices has a good, stable connection
Reply from 192.168.10.40: bytes=32 time=1ms TTL=64
Reply from 192.168.10.40: bytes=32 time=5ms TTL=64
Reply from 192.168.10.40: bytes=32 time=298ms TTL=64
Reply from 192.168.10.40: bytes=32 time=681ms TTL=64
Reply from 192.168.10.40: bytes=32 time=11ms TTL=64
Reply from 192.168.10.40: bytes=32 time=1ms TTL=64
Reply from 192.168.10.40: bytes=32 time=2ms TTL=64
Reply from 192.168.10.40: bytes=32 time=1ms TTL=64
Reply from 192.168.10.40: bytes=32 time=1ms TTL=64
Reply from 192.168.10.40: bytes=32 time=18ms TTL=64
Reply from 192.168.10.40: bytes=32 time=1ms TTL=64
Reply from 192.168.10.40: bytes=32 time=60ms TTL=64
Reply from 192.168.10.40: bytes=32 time=22ms TTL=64
Reply from 192.168.10.40: bytes=32 time=855ms TTL=64
Reply from 192.168.10.40: bytes=32 time=279ms TTL=64
Reply from 192.168.10.40: bytes=32 time=1ms TTL=64
Reply from 192.168.10.40: bytes=32 time=261ms TTL=64
Reply from 192.168.10.40: bytes=32 time=1113ms TTL=64
Reply from 192.168.10.40: bytes=32 time=25ms TTL=64
Reply from 192.168.10.40: bytes=32 time=1372ms TTL=64
Request timed out.
Reply from 192.168.10.40: bytes=32 time=378ms TTL=64
Reply from 192.168.10.40: bytes=32 time=65ms TTL=64
Reply from 192.168.10.40: bytes=32 time=63ms TTL=64
Reply from 192.168.10.40: bytes=32 time=15ms TTL=64
Reply from 192.168.10.40: bytes=32 time=30ms TTL=64

**Comment by shinebar1001** [comment]
just try it once on command line.

My Dafang has severe problems when the wifi-channel ist crowded (definitely more than other devices) - so, if possible, check if there are intereferences on the wifi channel you are using.

**Comment by jmtatsch** [comment]
Please install the latest custom firmware and software. Also select a wifi channel with minimal inferences (other networks, microwave, radar, etc). Please reopen if still an issue then.

**Comment by saipsa** [comment]
@shinebar1001 how to write on command line? I mean how to access the camera via command line? Thanks.

**Comment by jmtatsch** [comment]
`ssh root@your_dafangs_ip` with password ismart12
