### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by gysmo38** [EliasKotlyar/Xiaomi-Dafang-Hacks#1343]
Not really an issue but a proposal.
I think, it could be great to have release and create a relase file.
With relealse, we can have update when you release is done and update from github for beta version.
If I can help with this part, it will be a pleasure.

**Comment by jmtatsch** [comment]
So you would pack a bunch of commits together and tag as version and release? Sounds nice but the updater would need to be able to select from a list of releases. Would you implement that?

**Comment by gysmo38** [comment]
@jmtatsch yes the idea could be to pack a bunch of commits and tag as a version. At each version we can make a snapshot of firmware_mod rep into to a compresses file. 
We can update tu updater to check the release file for stable update and use the same script like now for beta. I will try to implement release on my fork.

**Comment by gysmo38** [comment]
@jmtatsch I made test with release, I think the first step, is to create a new rep with only firmware_mode directory.
After we can use tags to create release and generate a zip file of the firmware.
I create a new rep to show you gysmo38/Xiaomi-Dafang-Hack-firmware_mod
Do you think this is something possible to move all the work on firmware_mod directory to a new rep?
After we could update the update script to check release file for stable release and use github for beta upgrade.

**Comment by jmtatsch** [comment]
I created a repo at https://github.com/Dafang-Hacks/firmware_mod
Could you attempt to make a pull request to it with just the firmware_mod contents and the git history intact?

**Comment by gysmo38** [comment]
Ok I will do it. Before I made an improvement of autoupdate script. I would like to finish and make a PR for it and after make the PR to move the directory

**Comment by gysmo38** [comment]
@jmtatsch I PR is ready :) I also prepare a repo for https://github.com/Dafang-Hacks/firmware_mod.
I would like to fork it before but it is not possible because there is no file on it. Can you put one file? Maybe you can put a README file.

**Comment by gysmo38** [comment]
No news. I think it is not the right time... I close this issue.

**Comment by jmtatsch** [comment]
Dont worry, your idea is appreciated. I just dont know how we get a part of the repo to the new firmware repo with all the git history. I simply need to read up on it.

**Comment by jmtatsch** [comment]
I think i found a way https://medium.com/@ayushya/move-directory-from-one-repository-to-another-preserving-git-history-d210fa049d4b

**Comment by OptimusGREEN** [comment]
I like this idea of having release tags.
