### ISSUE TITLE
v4l2rstpserver ini-file issues

### ISSUE THREAD

**Issue by Yannik** [EliasKotlyar/Xiaomi-Dafang-Hacks#1355]
The current v4l2rtpserver attempts to read a v4l2rstpserver ini-file like [this](https://github.com/Dafang-Hacks/Main/blob/master/v4l2rtspserver-master/v4l2rtspserver-master.ini) from `/system/sdcard/bin/v4l2rtspserver-master.ini`.

I found 4 issues with this:
 * there's no such ini-file included in firmware_mod
 * placing this file in `/system/sdcard/bin` seems like the wrong place to me (this dir should contain binaries)
 * also, while the file that is being opened should supposedly be named `v4l2rtspserver-master.ini`, the [error-message](https://github.com/Dafang-Hacks/Main/commit/39020a625d7c7da45ce6095c67af1931f97c615c#diff-10f3604ef1273a9a310b50099b0bdc35R710) if no such file exists is `Can't load 'v4l2rstpserver.ini': set default values`
 * finally, if such a file exists, the message `Parsing 'v4l2rstpserver.ini'!!!` is [logged](https://github.com/Dafang-Hacks/Main/commit/39020a625d7c7da45ce6095c67af1931f97c615c#diff-10f3604ef1273a9a310b50099b0bdc35R721), which is again using the incorrect filename

Pinging @nik0 because you included this feature.

**Comment by nik0** [comment]
Thanks for the feedback 
It was placed in bin folder because it was for test purposes at the beginning (that’s why it was not delivered)
Anyway I think I pushed it on beta branch

**Comment by Yannik** [comment]
bump

**Comment by goermezer** [comment]
nik posted an ini file in another thread when testing another binary. This is the content of the  v4l2rtspserver-master.ini:

`[Configuration]
FontFixedWidth=/system/sdcard/fonts/NotoMono-Regular.ttf
FontRegular=/system/sdcard/fonts/NotoSans-Regular.ttf
DetectionScriptOn=/system/sdcard/scripts/detectionOn.sh
DetectionScriptOff=/system/sdcard/scripts/detectionOff.sh
DetectionTracking=/system/sdcard/scripts/detectionTracking.sh

[Video]
# IMP_Encoder_STYPE_N1X                   = 0
# IMP_Encoder_STYPE_N2X                   = 1
# IMP_Encoder_STYPE_N4X                   = 2
SkipType=1
# 0 is best, 7 is worst
Quality=2
`
I think, there were some changes in v4l2rtspserver-master. So I`m not sure if the ini file will make a better stream...
