### ISSUE TITLE
Wifi disconnects

### ISSUE THREAD

**Issue by Yannik** [EliasKotlyar/Xiaomi-Dafang-Hacks#1356]
Hi,
I'm experiencing regular wifi disconnects on my xiaofang. This also happens when the camera is close to the AP.

The disconnects manifest in the kernel log with entries such as this:
```
[ 2284.824732] RTL871X: recv eapol packet
[ 2284.847202] RTL871X: send eapol packet
[ 2284.851246] RTL871X: set group key camid:5, addr:44:4e:6d:25:xx:xx, kid:1, type:AES
```

According to my research, this seems to be a regular problem with the RTL871X driver.

Anyone else experiencing this?

**Comment by Yannik** [comment]
Has anyone compiled their own driver from source (https://linux-sunxi.org/Wifi#RTL8189FTV seems promising) for this model? Or are you all using the stock driver?

**Comment by nik0** [comment]
I guess we are using the stock F/W
Try compile it. It was a long time I didn't compile a module ... good luck :-)
