### ISSUE TITLE
WIFI not connecting

### ISSUE THREAD

**Issue by nobet78** [EliasKotlyar/Xiaomi-Dafang-Hacks#136]
I do everything according to the tutorial. At the last stage, the wifi connection does not work. What am I doing wrong?

**Comment by EliasKotlyar** [comment]
Please check your Wifi Credentials. Also ensure the Encoding of the wpa_supplificant file.

**Comment by nobet78** [comment]
Now it is working. My AP was hidden;) I added the scan_ssid = 1 option in the wpa_supplicant.conf file.
