### ISSUE TITLE
Cannot connect to cams over the network

### ISSUE THREAD

**Issue by monogoat** [EliasKotlyar/Xiaomi-Dafang-Hacks#1361]
I have both a Wyze Cam V2 and a Wyze Cam Pan, that cannot be accessed over the network when connected at my home. They are working fine at my office running a rather standard TP Link router, but not at my home running an Opnsense computer as a router and Unifi AP nano HD access points. They connected to the access points where I can see a few packets reach them and a few come out, then nothing else reaches them. I can see in Opn sense logs where they request and accept IP address, and in the startup logs they show DNS servers are pulled.  The startup logs look the same whether at home or the office so I can't figure out what is different. These are the only devices I'm having trouble with, so I don't think it is a problem with my network but perhaps an incompatibility? What is stranger is when first setting up the mod firmware they worked fine but after a couple reboots they are gone.

**Comment by monogoat** [comment]
Was able to play with this more today and created a test network with a simpler SSID and password, and the cameras are working fine now. It appears the custom firmware doesn't like either my SSID having spaces in it, or my password being 30ish characters long (also with spaces).

**Comment by jmtatsch** [comment]
Great to hear?
Can you pin it down further?
Was it just the spaces in ssid or password? Or both?
you can always set them manually in the wpa_supplicant conf file, if you dont want to rename your ssid :)

**Comment by monogoat** [comment]
I've been using the wpa supplicant conf file the whole time. I'll be setting up another camera tonight, I'll throw up another test network and try with spaces in the ssid and password separately and see how it behaves, then I'll try a long password and figure out what specifically threw it for a loop.

I know the hardware isn't the problem because they work fine on the Wyze firmware.

**Comment by gareth-ellis** [comment]
To chime in here, I just upgraded to unifi (nanohd AP), and despite using the same SSID and password as before, I now cannot get into the webui or ssh to the camera. It is however able to talk out - I can see traffic going to my mqtt broker.

The only difference from before is i used to have a seperate SSID for 5G - Unifi supports having the same (ie both 2.4 and 5 broadcast with the same SSID). 

My camera is a Neos, i have one stock and one with Dafang - stock connected up fine and i can access video feed etc.
