### ISSUE TITLE
motion detection and send email

### ISSUE THREAD

**Issue by Riewekooche** [EliasKotlyar/Xiaomi-Dafang-Hacks#1362]
The Dafang hacks work fine. RTSP on VCL and Android apps - perfect.

But the config of the motion detection and send email seems to be a problem for me.

in motion.conf
motion_detection=on
send_email=true

in sendmail.conf
FROM="test@boennrep.de"
FROMNAME="`hostname`"
AUTH="info@boennrep.de"
PASS="xxxxxx"
TO="info@boennrep.de"
SERVER=smtp.ionos.com
PORT=587

Nothing happens.
No received alarm, neither a attached picture...

Any ideas?

**Comment by jmtatsch** [comment]
Can you manually trigger the detectionOn.sh script? Does it work then?

**Comment by Riewekooche** [comment]
i'n not so familiar with these scripts.
How can i start it?
Watching the GUI in Firefox..

Btw another problem. The RTSP h264 server has to be started manually in the browser each time i start the camera. How can i automate this?

**Comment by jmtatsch** [comment]
Ssh in and execute.
For h264 make sure autostart is enabled in the services webui.

**Comment by Riewekooche** [comment]
Now i've entered the SSH of the camera. But what is the command string?
tried "exec detection.sh" - not working

**Comment by jmtatsch** [comment]
You need to cd to /system/sdcard/scripts and there type ./onDetection.h

**Comment by Riewekooche** [comment]
I think, the command is ./detectionOn.sh
After starting this, the command prompt doesnt return.
(not like the "./detectionOff.sh")
??

**Comment by jmtatsch** [comment]
Well that means it hangs somewhere in that script. Do you get any output? Maybe add some debug echo statements to see where you are hanging.

**Comment by jmtatsch** [comment]
You can also turn debugging on in motion.conf with debug_msg_enable=true.

**Comment by sksumit1** [comment]
I too had this same problem.
You will have to enable swapon
Checkout https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/1208 & 
https://www.digitalocean.com/community/tutorials/how-to-add-swap-space-on-ubuntu-16-04

**Comment by Riewekooche** [comment]
Now i turned on the debugging:
![grafik](https://user-images.githubusercontent.com/63638471/79825115-6c17fb00-8398-11ea-9268-9d34314716e5.png)

The email seems to be send without an error - but i doesnt reach my smtp server...

I there anyone, who can send me a packet of cfg.files (except without the auth-pwd) which is really working with the motion detection nad sendemails ?

**Comment by jmtatsch** [comment]
Looks good to me, maybe your smtp server filters as spam? Add additional debug statements in the email sending routine.

**Comment by Riewekooche** [comment]
My SMPT server works fine with other apps and devices.

But i'm not sure about the syntax of the sendmail.conf.

FROM="test@boennrep.de"
FROMNAME="hostname"
AUTH="info@boennrep.de"
PASS="xxxxxx"
TO="info@boennrep.de"
SERVER=smtp.ionos.com
PORT=587

Is it right to write the SERVER adress and the PORT without quotation marks?
In Gmail, you wrote, it isn't necessary to add the "@gmail.com" to AUTH.
But in my case, dropping "@boennrep.de" would destroy the AUTH ... (??)

Anyone there who had success in sendmail other than to gmail.com?

**Comment by Dopeyr** [comment]
Hi, yes I use 1and1.co.uk, which have been taken over by ionos recently.

Only thing that looks different is my username (AUTH) is not my email address; it's an account number. e.g. `m1234567-bob`, but that might be just a difference in ionos vs 1and1 user formats.

Also, in my config FROMNAME contains backticks i.e.

```
FROMNAME="`hostname`"
```
Otherwise I can't see anything really different.

**Comment by Dopeyr** [comment]
To debug the email sending:

* change `NUMBEROFPICTURES=0` (optional, but stops a lot of stuff being logged) in `sendmail.conf`
* edit `scripts/sendPictureMail.sh`
  * Add a `-v` on the `sendmail` line i.e. `} |  /system/sdcard/bin/busybox sendmail -v \`
  * Remove `2>/dev/null` after the `$TO`
* Run `sendPictureMail.sh` 
  * `cd scripts`
  * `./sendPictureMail.sh`

Look for any errors.

**Comment by Riewekooche** [comment]
Using your advices, i've got this:
[root@DAFANG:scripts]# ./sendPictureMail.sh
sendmail: send:'NOOP'
depth=2 C = DE, O = T-Systems Enterprise Services GmbH, OU = T-Systems Trust Center, CN = T-TeleSec GlobalRoot Class 2
verify return:1
depth=1 C = DE, O = T-Systems International GmbH, OU = T-Systems Trust Center, ST = Nordrhein Westfalen, postalCode = 57250, L = Netphen, street = Untere Industriestr. 20, CN = TeleSec ServerPass Class 2 CA
verify return:1
depth=0 C = DE, O = 1&1 Internet SE, ST = Rheinland-Pfalz, L = Montabaur, CN = smtp.ionos.de
verify return:1
250 STARTTLS
sendmail: recv:'250 OK'
sendmail: send:'EHLO DAFANG'
sendmail: recv:'250-kundenserver.de Hello DAFANG [5.10.xxx.xxx]'
sendmail: recv:'250-8BITMIME'
sendmail: recv:'250-AUTH LOGIN PLAIN'
sendmail: recv:'250 SIZE 69920427'
sendmail: send:'AUTH LOGIN'
sendmail: recv:'334 yxyxyxxxx'                         changed
sendmail: send:''
sendmail: recv:'334 yxyxxxyxyx'                        changed
sendmail: send:''
sendmail: recv:'235 Authentication succeeded'
sendmail: send:'MAIL FROM:<info@boennrep.de>'
sendmail: recv:'250 Requested mail action okay, completed'
sendmail: send:'RCPT TO:<info@boennrep.de>'
sendmail: recv:'250 OK'
sendmail: send:'DATA'
sendmail: recv:'354 Start mail input; end with <CRLF>.<CRLF>'
sendmail: send:'From: DAFANG'
sendmail: send:'To: info@boennrep.de'
sendmail: send:'Subject: Alarm IPCam !!'
sendmail: send:'Date: Fri, 24 Apr 2020 18:33:09 +0200'
sendmail: send:'Mime-Version: 1.0'
sendmail: send:'Content-Type: multipart/mixed; boundary="ZZ_/afg6432dfgkl.94531q"'
sendmail: send:''
sendmail: send:'--ZZ_/afg6432dfgkl.94531q'
sendmail: send:'Content-Type: text/plain; charset="US-ASCII"'
sendmail: send:'Content-Transfer-Encoding: 7bit'
sendmail: send:'Content-Disposition: inline'
sendmail: send:''
sendmail: send:'This is an alert from DAFANG'
sendmail: send:''
sendmail: send:'--ZZ_/afg6432dfgkl.94531q--'
sendmail: send:'-- End --'
sendmail: send:'.'
sendmail: recv:'554-Transaction failed'
sendmail: recv:'554-Reject due to policy restrictions.'
sendmail: recv:'554 For explanation visit https://www.ionos.com/help/index.php?id=2425&ip=5.10.189.206&c=hd'
sendmail: . failed

The Error 554: Invalid DNS PTR resource record 
(somthing with the DNS registration...)

Is it a problem of the provider or me?

BTW sending mails per smtp by by internetrouter works at the same address.

**Comment by Dopeyr** [comment]
Hi, `sendmail: recv:'554-Reject due to policy restrictions.'` looks like this one:

> 
> 554 Reject due to policy restrictions:
> 
> The email was rejected because it violates our policies. The sending server mainly transmits spam messages. If the error occurs over a longer period of time, please contact your administrator so that they can contact us.


Might be worth contacting ionos to see what they say? Could be that these messages are being treated as spam for some reason, and they're blacklisting your IP for a time.

**Comment by Riewekooche** [comment]
Now after changing the smtp-server the sendPictureMail.sh and detectionOn.sh are working fine.
The smtp.ionos.de seems to be the problem in receiving mails from the camera. 

So one (hopefully) one  last question: :-) 
How th enable the motion detection on my (modified) XIAOFANG iSC5?

By enabling in motion.conf 
# Configure the motion core parameters:

region_of_interest=0,0,1280,720
motion_sensitivity=2
motion_indicator_color=2
motion_timeout=-1
motion_detection=on
motion_tracking=off

# Configure how to deal with motion events:
motion_trigger_led=true
publish_mqtt_message=false
publish_mqtt_snapshot=false
publish_mqtt_video=false
send_email=true
send_telegram=false
telegram_alert_type=image
send_matrix=false

the camera doesnt detect a motion and doesnt send a picturemail...

Excuse my boring questions. Of course it would be easier to have a manual for dummies...

**Comment by jmtatsch** [comment]
Search faqs for swap

**Comment by Riewekooche** [comment]
Yeah!
Now, with the last update (SWAP_ZRAM=true), MotionDetecion and sending the email works!!
Problems seems to be solved 👍

**Comment by jerkxyz** [comment]
Got this all working with GMail, thanks. 
I'm just wondering how to make it send notifications to multiple emails.
