### ISSUE TITLE
Telegram

### ISSUE THREAD

**Issue by ex725** [EliasKotlyar/Xiaomi-Dafang-Hacks#1364]
installed in me and my wife ( Telegram )
we created a common group.
but only I can control it.
How do I add multiple chat-id?

**Comment by ex725** [comment]
https://www.youtube.com/watch?v=kU36mfIEabo&feature=youtu.be

**Comment by jmtatsch** [comment]
🤷‍♂️, look at the telegram bot script perhaps?
