### ISSUE TITLE
script not executed, error message: " applet not found"

### ISSUE THREAD

**Issue by pkovacs85** [EliasKotlyar/Xiaomi-Dafang-Hacks#1365]
Hi, I enabled the timelapse.sh function and it works well. It takes a picture every 5 seconds. I also modified the motion detection script to create a timestamp, when motion is detected. Now I would be able to sort out the pictures based on the timestamps, to have only those pictures, which is taken at a motion (or around a motion). I created the script, but I cannot run it, it always says: "[root@DAFANG:userscripts]# /system/sdcard/bin/busybox /system/sdcard/config/userscripts/collect_motion_pictures
collect_motion_pictures: applet not found". 
The script is the following:
```
[root@DAFANG:userscripts]# cat collect_motion_pictures
#!/bin/sh
yesterday=`date -d @$( echo $(( $(date +%s)-$((60*60*24)) )) ) +%Y-%m-%d`
TSTAMP_DIR='/system/sdcard/motion_timestamp/'$yesterday
TIMELAPS_DIR='/system/sdcard/DCIM/timelapse/'$yesterday
cd $TSTAMP_DIR
for i in *
do
    minutes=`echo $i|awk -F "_" '{print $2$3}'`
    minutes_bef1=$((minutes - 1))
    minutes_bef2=$((minutes - 2))
    minutes_aft1=$((minutes + 1))
    minutes_aft2=$((minutes + 2))
    mkdir $TIMLAPS_DIR/$yesterday/saved
    mv $TIMLAPS_DIR/$yesterday/*$minutes_bef2* $TIMLAPS_DIR/$yesterday/saved
    mv $TIMLAPS_DIR/$yesterday/*$minutes_bef1* $TIMLAPS_DIR/$yesterday/saved
    mv $TIMLAPS_DIR/$yesterday/*$minutes* $TIMLAPS_DIR/$yesterday/saved
    mv $TIMLAPS_DIR/$yesterday/*$minutes_aft1* $TIMLAPS_DIR/$yesterday/saved
    mv $TIMLAPS_DIR/$yesterday/*$minutes_aft2* $TIMLAPS_DIR/$yesterday/saved
done

```
Why is it not working? The firmware_mod I have is from 30.07.2019.

**Comment by jmtatsch** [comment]
1. Why not simply using the motion detection function to save the picture?
2. `chmod +x /system/sdcard/config/userscripts/collect_motion_pictures` then just run `/system/sdcard/config/userscripts/collect_motion_pictures`

**Comment by pkovacs85** [comment]
Hi,

1, thanks, I did not think about doing this by that script :)
(I thought I would make a daily cronjob to do the job...)
2, permissions are already set
```
[root@DAFANG:~]# ls -l /system/sdcard/config/userscripts/collect_motion_pictures
-rwxr-xr-x    1 root     root           853 Jan 26 16:44 /system/sdcard/config/userscripts/collect_motion_pictures
```
so the script execution is still a question.

**Comment by jmtatsch** [comment]
Why do you want to execute the scipt with the busybox shell? why not use the default shell?

**Comment by jmtatsch** [comment]
If you want to execute a script with busybox you have to use its sh applet like this.
`/system/sdcard/bin/busybox sh /system/sdcard/config/userscripts/collect_motion_pictures`

**Comment by pkovacs85** [comment]
> 
> 
> Why do you want to execute the scipt with the busybox shell? why not use the default shell?

I did not know, that there is default shell. I saw only using the busybox. Thanks for the help.
