### ISSUE TITLE
Feature Request : Add option to snooze mqtt notifications for X minutes

### ISSUE THREAD

**Issue by sksumit1** [EliasKotlyar/Xiaomi-Dafang-Hacks#1367]
Usecase:
If the kid is playing on the driveway, you end up getting too much notifications on the mqtt channel. I have configured a Dafang 1S, and so far its holding up good.

On a side note, i have see that one needs to enable swapon to get motion detection working.
I discovered that other people have resolved this issue by enabling swapon.
Please add this as a note to your documentation.

**Comment by jmtatsch** [comment]
Why not implement some kind of presence detection with a smart home software like homeassistant and disable motion detection while some is at home?

This is straight from the FAQ

What if my scripts in config/userscripts/motiondetection are not executed or mqtt/telegram messages/emails are not sent on motion?


Your camera probably runs out of memory when processing the motion event. This is likely in cameras with 64MB e.g. the Xiaofang 1s. Try to enable some swap memory by copying swap.conf.dist to swap.conf and setting SWAP=true

**Comment by sksumit1** [comment]
Makes sense. This can be done in HA's automation.yaml to ignore the alert by setting a conditional
