### ISSUE TITLE
Telegram Help PLS

### ISSUE THREAD

**Issue by ex725** [EliasKotlyar/Xiaomi-Dafang-Hacks#1368]
Hello there
telegram detects commands that I send manually.
But I want a bot to detect the commands it sends.

I made a short video for this
https://youtu.be/kU36mfIEabo

**Comment by olvier** [comment]
Maybe try "/shot@botname"

I remember i wasn't able to manually shot via second-telegram-bot, too (node-red).
But i can't remember whether i tried "/shot" or "/shot@botname".

**Comment by ex725** [comment]
can you explain a little more
I do not understand
![image](https://user-images.githubusercontent.com/56446241/79645148-24d21480-81b6-11ea-8ef2-d08d1c525219.png)

**Comment by ex725** [comment]
> Maybe try "/shot@botname"
> 
> I remember i wasn't able to manually shot via second-telegram-bot, too (node-red).
> But i can't remember whether i tried "/shot" or "/shot@botname".

**Comment by olvier** [comment]
If this didnt work I can't help you. Checked on wife's phone "/on" and "/off" and both work without botname. So I have no idea what's wrong with your setup.

**Comment by ex725** [comment]
?????

**Comment by ex725** [comment]
:(

**Comment by fergio** [comment]
So you have a camera, tablet and phone. That's 3 people in the conversation ? You need group chat and a group chat id on the telegram.conf.
