### ISSUE TITLE
RTSP for this camera is not reliable at all.

### ISSUE THREAD

**Issue by mercuryin** [EliasKotlyar/Xiaomi-Dafang-Hacks#1369]
Hello,

I have 6 neos smartcam from almost 1.5 years ago. During all this time, I have tried with the original firmware from Neos, later on with Dafang, again with Neos and now I wanted to try again with Dafang.

I have spent several months trying to get reliable and durable rtsp streams from each camera and I thinkI have just give up with this.

These cameras are so cheap but totally unreliable. Just worth it if you have 2/3 cameras maximum at same time, same network.

1. With Neos original firmware and original app no problem because just 1 stream at a time is available so no problem, you can get the stream, but if you want more options you can´t or just pay more money for their cloud recordings.

2. With Neos original firmware + Tinycam Pro, you can add all the cameras you want but if you try to see the 6 cameras at same time with the app, I mean the layout with multiples cameras available within the app the local network crash because the latency added to the network and packet loss. Please don´t tell me anything about do this or this with my network. I´m IT engineer Cisco CCIE certified so I think I know something about network connections and is not a problem with my network. I have many different routers, switches, etc to try with and I have tried with all of them and different topologies and same results. With other camera makers I can stream simultaneously without any problems or latency added to the lan. I have tried with 5g and 2.4.
If you just see one or two cameras same time you are good, but no more. Sometimes even two cameras same time is too much. Again let me say I have tried all what one person can try, let´s say turning off the rest of devices same network. Different wifi channels, different routers, etc. etc. etc. etc.

I have read every single post around the web here and there, almost every day during months of testing. Change VBR, change FPS, disable audio, change bitrate,  try adding more swap, change the bootloader, etc. etc. etc. etc. etc.

With Dafang firmware, rtsp streams drops every few seconds, then reconnect again. etc. etc.

I don´t know what people is doing with these cameras and this firmware and are able to be happy with it. Perhaps is people with just 2 or 3 cameras and they don´t have same problem than I have or simply I am unlucky or I´m the more silly guy of the web.

I´m giving up with this cameras, I would like to hear your experiences and perhaps I can learn or hear anything that may give me a last try with these cameras.

I think these cameras are cheap for a reason, the encoder used for this cameras may not be reliable because the cameras run out of memory continuously " MultiFramedRTPSink::afterGettingFrame1(): The input frame data was too
large for our buffer size (60753).  34086 bytes of trailing data was
dropped!  Correct this by increasing "OutPacketBuffer::maxSize" to at
least 94839, *before* creating this 'RTPSink'.  (Current value is
60000.) "

The message above is continuous every day, here and there and doesn´t matter how to configure the camera, stream, fps, resolution, bitrate, etc. etc. 

But before to trash these cameras I would like to try anything else you may think I´m not doing well. Any ideas ?

Please don´t get me wrong. I love this firmware and the way of the developers are doing this for free is just I would like to be happy with it and to have the same good experiences than you have but looks like me and some other people and there are having the same problems with rtsp streams.

Thanks for reading this.

**Comment by mercuryin** [comment]
Close this thread. Thanks for all.

**Comment by Combie81** [comment]
> before to trash these cameras
Before you trash them let me know - I'll perhaps take a few if we come to an arrangement :P
I've had no major issue with my 2 unless the storage fills and it doesn't clear the recorded footage/images.

**Comment by timpur** [comment]
@mercuryin 
I was looking ever where to try find a solution to my problem. https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/1796 might fix yours.
