### ISSUE TITLE
Entware MIPS32(r1)

### ISSUE THREAD

**Issue by daniel-dona** [EliasKotlyar/Xiaomi-Dafang-Hacks#1372]
In this tutorial (https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/information/sannce.md)  the use of Entware as a software source is proposed, but Ingenic T10/20 is MIPS32r1 and Entware is currently compiling packages with MIPS32r2 as target, in consequence packages doesn't work and the result are simply segfaults.

So I opened this issue begging for a bit of help... https://github.com/Entware/Entware/issues/454

The problem can be fixed by compiling the packages with a modified config, and It seems to work just fine...

I can write a small guide for self compiling, at least seams easier than compiling software on your own. I'm also figuring out how to enable an opkg feed to the T10/20 SoC so anyone can use my already compiled packages.

Just one question, ¿are the current kernels hardfloat or softfloat? Can be a good optimization on compile time.

**Comment by nik0** [comment]
How can we know about the hard/soft float? 
You can find the tool chain here https://github.com/Dafang-Hacks/Main
But I am sure you already look at it ?

**Comment by daniel-dona** [comment]
Up to my understanding, this means it'll be a hardfloat kernel, but I'm not sure...

https://github.com/Dafang-Hacks/kernel/blob/beddfe6ece99a455cefe5401006d47528fdaf28b/.config#L127
