### ISSUE TITLE
S1: rtsp-h264 unable to start after update to: 2020-04-18T18:43:03Z

### ISSUE THREAD

**Issue by hb9eue** [EliasKotlyar/Xiaomi-Dafang-Hacks#1373]
Hi

After updating two s1 cams to the latest stable firmware. The rtsp-h264 server is not being started anymore and cannot be started via the Web-GUI. That constantly shows the 'NOK' flag. 'STOP' 'START' is greyed out. 'STOP' does nothing, as there is no process.

No /var/log/v4l2rtspserver-master.log is being created.

Nothing obvious in dmesg or any other logs.

Strangely, if I log in and do:
/system/sdcard/controlscripts/rtsp-h264 start

The server is started and runs normally. The PID is shown in the Web-Gui and the server can be stopped, but then it shows 'NOK' again and is stuck at the same place.

Changing Video Settings like resolution works, when the server is manually started.

Any hints to the source of the issue?

-Benoît-

**Comment by hb9eue** [comment]
Ok, just figured out a work-around to get it back working.
From the Configuration => Video page. Stop and Start the RTSP Server there. Then reboot. Now it is being auto-started again.

**Comment by elchanly** [comment]
It works. If activated from services, NOK appears and rtsp cant be enabled, but from config/video it runs! Maybe something related to services button.

Thanks!!!!

**Comment by lech4tnoir** [comment]
Don't work for me :'(
Every time I restart my xiaofang, RTSP server is uncheck...

**Comment by Morphy99** [comment]
I have an issue which may be related to this. The RTSP Stream doesn't start at boot. 
On services page rtsp-h264 is displayed as NOK and Start is greyed out. Autorun is enabled.
Once service is started in camera controls this is showing PID and is running ok.
I tried the above with stopping then starting in video page but this returned to NOK after a reboot.
I'm running 2020-05-09 and have a Neos Smartcam. This issue started happening on 2020-04-21 and have another identical camera which works on 2020-04-21.
