### ISSUE TITLE
No issue | Just Question about Version

### ISSUE THREAD

**Issue by olvier** [EliasKotlyar/Xiaomi-Dafang-Hacks#1377]
Hi, are these Cams the supported T20 or unsupported T20L?

Kind regards
![Screenshot_20200421-175139~2](https://user-images.githubusercontent.com/13106409/79886549-656da000-83f9-11ea-9051-ad2a4db8c922.png)

**Comment by gadget78** [comment]
not sure why you posted twice, and how we are supposed to figure out what these cams are from the info given !! 
but they square, whie, with similair sticker to Wyze2 or the neocams so i would guess they do...
get the original demo.bin, and then the custom firmware and give it a go !
