### ISSUE TITLE
license of this project

### ISSUE THREAD

**Issue by woswos** [EliasKotlyar/Xiaomi-Dafang-Hacks#1379]
### Description

I really liked this project, and I already installed it in my Wyze Cam V2. That being said, I realized this project doesn't have any license! Having a license is very important for potential contributors to understand what they can do with your code. Am I allowed to fork your project and start my own thing? Should I cite your names if I embed this into my website? Are you OK with me contributing to this project at all? Can I take your code and commercialize it? Having a license help people answer these questions and many others.

For example, [OpenIPCamera](https://github.com/openipcamera/openipc-firmware) project literally copied this project and released under a different name.

I just saw issue #974 and it is closed. Are there any updates on it?

**Comment by jmtatsch** [comment]
We can't really give a license for the work of Ingenic which this repo uses and is built on. For the work that has happened inside this repo, you can assume a very free license i.e. do whatever you like with it but we take no responsibility in any way.

**Comment by woswos** [comment]
I understand the issue, thank you anyway!
