### ISSUE TITLE
Neos Smartcam firmware reverts when power cycled

### ISSUE THREAD

**Issue by TwoToneEddy** [EliasKotlyar/Xiaomi-Dafang-Hacks#1380]
Hi,
The firmware is working well on my neos smartcam but when I power cycle the camera it reverts back the the factory firmware for some reason. Is this expected behaviour?

**Comment by Combie81** [comment]
Are you leaving the SD card in as this is needed for the firmware to work as it runs off the SD card?

**Comment by TwoToneEddy** [comment]
Hi, yes I am leaving the card in.

**Comment by sean1516** [comment]
Hi, can you give us more info.
im also running 3 of the flashes Neos Smartcams and they can be powercyled no problem, as said above the SD card should be left in and are you able to run the flashed firmware up until the power cycle?

**Comment by GreenBear33** [comment]
Hi All, 

I am having trouble with this. I am using a NEOS smart Cam and followed instructions up to stage 10. I have removed the SD card and now the camera doesn't work at all. 

What am I doing wrong? 

Also during stage 8, as I switched on the camera with the SD card in it, the light was blue initially and then went to orange and stayed that way. After about 20 minutes I unplugged it and tried to remove the SD card to try the camera and now I cannot connect. Now the light is orange on startup, blue after 5 seconds and then orange again after 20 seconds.

**Comment by GreenBear33** [comment]
> Hi, can you give us more info.
> im also running 3 of the flashes Neos Smartcams and they can be powercyled no problem, as said above the SD card should be left in and are you able to run the flashed firmware up until the power cycle?

Hi Sean, Any chance you could help me with a bit of troubleshooting? I can't get it to work on my NEOS smartcam and since you got it working on 3 of yours, maybe you could help me out. 

Thanks

**Comment by sean1516** [comment]
> > Hi, can you give us more info.
> > im also running 3 of the flashes Neos Smartcams and they can be powercyled no problem, as said above the SD card should be left in and are you able to run the flashed firmware up until the power cycle?
> 
> Hi Sean, Any chance you could help me with a bit of troubleshooting? I can't get it to work on my NEOS smartcam and since you got it working on 3 of yours, maybe you could help me out.
> 
> Thanks

Hi, I’ll try my best. I had issues also, in the end I followed the steps on this website (I am in no way involved in this website but it’s the one I used”

https://ryanfitton.co.uk/blog/install-dafang-custom-firmware-to-neos-smartcam/

I followed those steps and it worked for me. Let me know what the outcome is

**Comment by GreenBear33** [comment]
Hi, Thanks for the tip. I was already reading that. The problem I have is that when I first tried to flash the demo.bin file onto my cam it never started flashing. It just went from steady blue to steady orange. Now the camera doesn't work at all and just stays on steady orange all the time. 

I have tried to complete the process but nothing happens and I have tried to go through the steps again but still no response other than a steady orange light. Any ideas?

**Comment by sean1516** [comment]
> Hi, Thanks for the tip. I was already reading that. The problem I have is that when I first tried to flash the demo.bin file onto my cam it never started flashing. It just went from steady blue to steady orange. Now the camera doesn't work at all and just stays on steady orange all the time.
> 
> I have tried to complete the process but nothing happens and I have tried to go through the steps again but still no response other than a steady orange light. Any ideas?

From me experience if the camera doesn’t make the regular neos noises when it boots up it sounds like it could be flashed. Did you fill in your WiFi details correctly? And how do you know it isn’t working anymore?

**Comment by GreenBear33** [comment]
I know (think) it isn't working because I had it set up in the Neos app before and it was displaying just fine but now when I remove the SD card and try to start it I still get the orange steady light and I cannot connect to it via the app anymore. 

I think I did the correct thing with the wifi details, but I am never sure with these things as I am a complete noob. 

Here is what I put: (the only changes I made are in Bold)

```
# For more configuration option please see:
# https://w1.fi/cgit/hostap/plain/wpa_supplicant/wpa_supplicant.conf

ctrl_interface=/var/run/wpa_supplicant
ctrl_interface_group=0
ap_scan=1

network={
        ssid="**I INSERTED MY SSID HERE**"
        # Uncomment to connect to Hidden SSIDs
        #scan_ssid=1 
        key_mgmt=** I INSERTED MY WPA-PSK HERE**
        pairwise=CCMP TKIP
        group=CCMP TKIP WEP104 WEP40
        psk="PW"
        priority=2
}
```

**Comment by sean1516** [comment]
> I know (think) it isn't working because I had it set up in the Neos app before and it was displaying just fine but now when I remove the SD card and try to start it I still get the orange steady light and I cannot connect to it via the app anymore.
> 
> I think I did the correct thing with the wifi details, but I am never sure with these things as I am a complete noob.
> 
> Here is what I put: (the only changes I made are in between ** **)
> 
> ```
> # For more configuration option please see:
> # https://w1.fi/cgit/hostap/plain/wpa_supplicant/wpa_supplicant.conf
> 
> ctrl_interface=/var/run/wpa_supplicant
> ctrl_interface_group=0
> ap_scan=1
> 
> network={
>         ssid="**I INSERTED MY SSID HERE**"
>         # Uncomment to connect to Hidden SSIDs
>         #scan_ssid=1 
>         key_mgmt=** I INSERTED MY WPA-PSK HERE**
>         pairwise=CCMP TKIP
>         group=CCMP TKIP WEP104 WEP40
>         psk="PW"
>         priority=2
> }
> ```

I think I know the problem!

> network={
>         ssid="SSID HERE”
>         # Uncomment to connect to Hidden SSIDs
>         #scan_ssid=1 
>         key_mgmt=WPA-PSK
>         pairwise=CCMP TKIP
>         group=CCMP TKIP WEP104 WEP40
>         psk=“WIFI PASS HERE”
>         priority=2
> }

Give that a try remember your

**Comment by GreenBear33** [comment]
Great thanks for the pointer, I will try that now. 

I am still nervous though as the camera only ever starts up in this sequence. Steady Orange, Steady Blue, Steady Orange. I didn't get any flashing lights.

**Comment by sean1516** [comment]
> Great thanks for the pointer, I will try that now.
> 
> I am still nervous though as the camera only ever starts up in this sequence. Steady Orange, Steady Blue, Steady Orange. I didn't get any flashing lights.

It sounds like you done it correctly just a small error with the WiFi details. Let me know how It goes

**Comment by GreenBear33** [comment]
Ok, so I made the adjustments and have put the SD card in. 

1. I am still getting an orange steady light.
2. I am unable to access https://dafang
3. I cannot use the cam through the app after removing the SD card. 

Not going well for me. I thought this was going to be easy. Do you have any ideas?

**Comment by sean1516** [comment]
> Ok, so I made the adjustments and have put the SD card in.
> 
> 1. I am still getting an orange steady light.
> 2. I am unable to access https://dafang
> 3. I cannot use the cam through the app after removing the SD card.
> 
> Not going well for me. I thought this was going to be easy. Do you have any ideas?

Are you able to log into your router and check if it’s on the network, if your on Android WiFi analyser or iOS iNet are good tools. Typing in the IP directly might work. I log in via https://192.168.0.60 but yours will be different. 
I’m going to sleep now. Hopefully you get this fixed. If not I’ll help how I can in the morning

**Comment by GreenBear33** [comment]
Just tried to find my IP using the iPad app you recommended. After switching on the cam, no new IP hosts are found. It seems it isn't working. 

Have a good rest. Hopefully we can come up with a solution in the morning.

**Comment by Ozzyminted** [comment]
Try refreshing a neos firmware and then reflash. I use the latest wyzecam
v2 on my neos and both worked well.
Maybe post an updated log see what is happening in run.sh

**Comment by GreenBear33** [comment]
Hi, To reflash do i jsut download the original firmware on the github repository and do the same as the steps to flash the other firmware?

**Comment by GreenBear33** [comment]
Because that isn't working for me. I have tried several times. I am only getting the orange steady light with nothing else. I'm not sure what to do. I would be thankful for any help

**Comment by gadget78** [comment]
hey, if your having problems... 
by all means start again ... use this demo.bin from here ...
[aqueiroz on #964  ](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/pull/964#issuecomment-515421690)
you can reset up neos cam... (dont update firmware if it ask's, just in case)
then restart installing procedure like this one .. 
[by RyanFitton...](https://ryanfitton.co.uk/blog/install-dafang-custom-firmware-to-neos-smartcam/)

but the rtsp stream is a bit flaky :(  shame we couldnt just modify the original firmware !
