### ISSUE TITLE
beta branch - motion videos recorded with size 0

### ISSUE THREAD

**Issue by fanaticsurf** [EliasKotlyar/Xiaomi-Dafang-Hacks#1382]
beta branch from 2020/04/21 (latest)

### Description

videos in /system/sdcard/DCIM/motion/videos
are recorded with size of 0

### What did you do to debug the issue

I switched back to master branch and got rid of the problem.
Switching back to beta branch I get the issue back.

The reason to switch to beta is the new lighttpd version with web access to pics and videos.

### Evidence

-rwxr-xr-x    1 root     root             0 Apr 26 13:06 26-04-2020_13.06.57.mp4
-rwxr-xr-x    1 root     root             0 Apr 26 13:09 26-04-2020_13.09.41.mp4
-rwxr-xr-x    1 root     root       6389778 Apr 26 13:48 26-04-2020_13.48.15.mp4
...
-rwxr-xr-x    1 root     root        603614 Apr 26 13:58 26-04-2020_13.58.16.mp4
-rwxr-xr-x    1 root     root             0 Apr 26 13:58 26-04-2020_13.58.58.mp4
-rwxr-xr-x    1 root     root             0 Apr 26 13:59 26-04-2020_13.59.13.mp4

**Comment by jmtatsch** [comment]
I had the same issue with the new rtspserver. @nik0 did you know why this happens?

**Comment by nik0** [comment]
Try new openRTSP here
https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/pull/1383
If it not working I don't see why ...

**Comment by jmtatsch** [comment]
recording filesize seems fixed, process dies after a couple of hours and logs are not written

**Comment by nik0** [comment]
Logs are written for not activated ? I had to activate them through a configuration flag.
My Dafang is working fine since several days

**Comment by jmtatsch** [comment]
how can we enable logging?

**Comment by nik0** [comment]
Set true to log flag in rtspserver.conf

**Comment by fanaticsurf** [comment]
Thanks @nik0 recording is working here too with new version, no crashes so far, but I only use it for motion recording.

**Comment by jmtatsch** [comment]
Ah ok, logging works for me when enabled in rtspserver.conf
