### ISSUE TITLE
No 1080p on Dafang

### ISSUE THREAD

**Issue by throttlenerd** [EliasKotlyar/Xiaomi-Dafang-Hacks#1384]
Hey guys (Elias?), thank you so much for such a great software!! Just one issue: my Xiaomi Dafang can't go higher than 1600x900 no matter which framerate or bitrate. As for now I'm stuck with 900p 15fps but the cam is supposed to handle 1080p 15fps, afaik.

Thanks and God bless you ))

**Comment by jmtatsch** [comment]
Search faq for zram or you have to repartition your memory.

**Comment by throttlenerd** [comment]
And, rather a feature request than an issue:

1. .mp4 files which my Synology NAS creates from this hacked Dafang are "black" on macOS Catalina if I play them with QuickTime (Final Cut doesn't play them back correctly too), however, they play ok via VLC. So I guess there may be some H.264 options that can be made "more standard". And I don't have this issue with Amcrest camera connected to the same NAS, files play ok. By the way, PCMU Audio is ok with my Synology while MP3 is not, but I'm ok with that )

2. Is there a possibility to add "Contrast" and "Saturation" parameter adjustments? Contrast is the most important one so we could see more details in shadows/highlights.

**Comment by throttlenerd** [comment]
> Search faq for zram or you have to repartition your memory.

Oh thank you!!

**Comment by christ** [comment]
1080 seems to be working on Wyze Cam v2 and the beta firmware.

**Comment by throttlenerd** [comment]
Whew, changed the bootloader as per FAQ and 1080p works! Thanks a lot guys!!
