### ISSUE TITLE
Audio stream/recording on Neos SmartCam issues

### ISSUE THREAD

**Issue by timdonovanuk** [EliasKotlyar/Xiaomi-Dafang-Hacks#1390]
Camera hardware: NeosCam

### Description

Booted latest release. Most settings unchanged.

Audio stream in RTSP is either:

- very laggy and behind the video 
- stops working entirely
- stops working after a loud noise

VLC thinks an audio stream and bytes are being sent.

![image](https://user-images.githubusercontent.com/8156439/80704880-5663ad80-8add-11ea-889c-071915e0c45d.png)

![image](https://user-images.githubusercontent.com/8156439/80704900-5e235200-8add-11ea-9faa-9578d1e0ee06.png)

Trying to record via SSH throws an error:

```
root@DAFANG:~]# /system/sdcard/bin/ossrecord /system/sdcard/test.wav 
Unexpected EOF on audio device
```

I tried switching the audio format and sample rates and this seems to have killed audio entirely. Even reverting back to MP3 and restarting the cam, audio no longer works at all in the RTSP stream.

For what it's worth, outputting audio on the camera is also broken - it cuts out after the first 2 seconds when using the audio test feature in the UI. 

### What did you do to debug the issue

I also tried recording manually over SSH

### Evidence

logcat shows this when trying to record, that I think is relevant:

```
[ 4963.431240] xb_snd_dsp_ioctl[line:1467]SOUDND ERROR:ioctl command -2143266558 is not supported
[ 4963.440810] xb_snd_dsp_ioctl[line:1467]SOUDND ERROR:ioctl command -2147201001 is not supported
[ 4963.453574] xb_snd_dsp_ioctl[line:1467]SOUDND ERROR:ioctl command 536891425 is not supported
[ 5503.963510] xb_snd_dsp_ioctl[line:1467]SOUDND ERROR:ioctl command -2143266558 is not supported
[ 5504.003291] xb_snd_dsp_ioctl[line:1467]SOUDND ERROR:ioctl command -2147201001 is not supported
[ 5504.019150] xb_snd_dsp_ioctl[line:1467]SOUDND ERROR:ioctl command 536891425 is not supported
```

### Contribute Back

If your issue was resolved, please consider contributing back to the project by creating a pull request to improve the code or documentation in order to avoid that this issue arises again for other people.

**Comment by timdonovanuk** [comment]
Noticed that the H264 RTSP stream has video and no audio and the MJPEG RTSP stream has audio and no video!

**Comment by nik0** [comment]
Did you try starting v4l2rtspserver-master with -a option ? Or without it ?

**Comment by timdonovanuk** [comment]
hey thanks @nik0 - only just installed this so still finding my way around it. I've not changed any of the settings other than whats immediately obvious through the webUI.

I can try with the -a option, looks like to do that I modify the rtsp-h264 script?

`/system/sdcard/bin/v4l2rtspserver-master $RTSPH264OPTS $AUDIOPARAM $VIDEOFORMAT $CREDENTIAL $PORT $MULTICASTDEST 2>> "$LOGPATH" >> "$LOGPATH" `

**Comment by nik0** [comment]
Yes I guess 😜

**Comment by timdonovanuk** [comment]
I see in the logs its running this command by default:

`/system/sdcard/bin/v4l2rtspserver-master -fMJPG -W1280 -H720  -E MP3:16000:16000 -r 2 -F 24  -P 8554 `

Not sure what `-E MP3:16000:16000` is? There is no -E documented here https://github.com/Dafang-Hacks/v4l2rtspserver-master by @EliasKotlyar

**Comment by nik0** [comment]
The code is here now
https://github.com/Dafang-Hacks/Main/tree/master/v4l2rtspserver-master

**Comment by timdonovanuk** [comment]
Still no -E option documented there though :D 

I added -a but v4l2rtspserver-master didn't even start on a reboot. I've tried running it from the command line now with default options and get:

```
[root@DAFANG:~]# /system/sdcard/bin/v4l2rtspserver-master -W1280 -H720 -E MP3:16000:16000 -r 2 -F 24 -P 8554
/system/sdcard/bin/v4l2rtspserver-master: can't load library 'libliveMedia.so
```
Will keep trying.

**Comment by timdonovanuk** [comment]
Getting really down the rabbit hole here! 

According to this https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/691 and your helpful comment there @nik0 it seems like $LD_LIBRARY_PATH is set incorrectly by default (is that a bug?). I've fixed that and can start it now. 

I see -E is documented when you run the app but -a is documented on https://github.com/Dafang-Hacks/Main/tree/master/v4l2rtspserver-master but not documented when you run the app.

I've tried -a and -aS16_BE but neither seem to be recognised as a command.

**Comment by nik0** [comment]
Only -a should be necessary 
This is changing the way the audio stream is get from the system
To my point of view this is not a matter of output audio but input
Do you have any audio logs in dmesg or logcat ?

**Comment by timdonovanuk** [comment]
This actually seems to work fine in the beta branch! Many thanks anyway. Audio output on the device is still clipped off after 1 second but I'm not using this functionality, just tried it through the web UI.

**Comment by gz7-design** [comment]
Greetings, I am running into the same exact issue, i.e. no audio and I have tried PCM 8000+8000, no audio filters, and still same result. v4l2rtspserver-master log says "bitrate=2980.0kbits/s video:1454kB audio:0kB", and "ffmpeg" says there are no audio streams at all in the video file.

Based on the comment above, it looks like what I am missing is the new beta version of the v4l2rtspserver-master binary. My question is: where I can I get this binary build?  
The one under https://github.com/Dafang-Hacks/Main/tree/master/c looks very old:
1296827 May 30  2018 v4l2rtspserver-master
