### ISSUE TITLE
No version information - force update? Already latest version?

### ISSUE THREAD

**Issue by NoTrace-Kai** [EliasKotlyar/Xiaomi-Dafang-Hacks#1400]
Hi there ...

today i did the update for my 3 Xiaofang S1 Cams ...
but when i now look at the botton of the webinterface there is no information about the version,
i can only see this:
-  Dafang Hacks Version: commit null from branch master Issues? -

And when i take a look into the "Information - Overview" i can read this:
Model | Xiaomi Xiaofang 1S
-- | --
Firmware date | null
Firmware branch | master
Firmware commit |  
Kernel Version | #32 PREEMPT Wed Jan 24 02:40:56 CST 2018
Bootloader Version | U-Boot 2013.07 (Jul 05 2018 - 17:59:02)

When i try to get the update again, the will be this messege:
Update - You have already the lastest version.

Is it possible to "force-update" the cams? Over telnet i did also the information,
that the can has the latest version ...

Is it possible, that the video quality is a little bit worser like bevor ?

CU und THX for help ... Kai

**Comment by jmtatsch** [comment]
@gysmo38 can you help

**Comment by gysmo38** [comment]
@NoTrace-Kai It is strange,  Firmware commit stay blank. You can check /system/sdcard/VERSION file to see in the commit version you have. If you would like to force upgrade, you just have to delete VERSION file but maybe there is no new version...

**Comment by NoTrace-Kai** [comment]
Hi ...
The VERSION File told me this:
"date":"null","branch":"master","commit":"null"
When i delete the VERSION file i can not update with ./autoupdate.sh
I get the information: 
Version file missing. Upgrade to last commit null
Github limit exceeded, try with an account (-u option)
No files to update.
CU Kai

**Comment by gysmo38** [comment]
@NoTrace-Kai Ok maybe a bug. Update should work but you have reach the github api limit. If you have a github account you can try ./autoupdate.sh -u logingithub:passwordgithub .

**Comment by NoTrace-Kai** [comment]
Not really ...

Need to upgrade from null to ec9f5b9
jq: error (at <stdin>:4): Cannot iterate over null (null)
No files to update.

But now the information page shows this:

Model | Xiaomi Xiaofang 1S
-- | --
Firmware date | 2020-04-30T18:44:10Z
Firmware branch | master
Firmware commit |  
Kernel Version | #32 PREEMPT Wed Jan 24 02:40:56 CST 2018
Bootloader Version | U-Boot 2013.07 (Jul 05 2018 - 17:59:02)

But on the bottom of the page this:
 Dafang Hacks Version: commit ec9f5b9 from branch master Issues? 

Perhaps i try to write the files direcly onto the sd card ... but not today ;)

Thanks a lot ...

But on 1 of the 3 cams there i can find this on the information page:

Model | Xiaomi Xiaofang 1S
-- | --
Firmware Version | 2020-04-30T18:44:10Z ## master branch
Kernel Version | #32 PREEMPT Wed Jan 24 02:40:56 CST 2018
Bootloader Version | U-Boot 2013.07 (Jul 05 2018 - 17:59:02)

And this on the bottom:
 Dafang Hacks Version: 2020-04-30T18:44:10Z ## master branch Issues? 

?!

**Comment by nik0** [comment]
@gysmo38 ,
Another issue I didn't notice first:
When up-to-date  how to switch between branches? Beta/master ?

**Comment by gysmo38** [comment]
@nik0 Yes I notice too. I will make a new PR to correct this. I am not sure having two branches is a good idea. It could be easier to have master branch for beta and use tag to create stable version. I notice that on github beta branche autoupgrade.sh have branch variable set to master.

**Comment by nik0** [comment]
@gysmo38 
For the branch management you maybe right. 
For me it was more convenient to test binaries

**Comment by gysmo38** [comment]
@nik0 Ok i understand. I suggest to @jmtatsch creating a new repo with only firmware_mod directory in it and point cameras to this repo for upgrade. I think it could be a good idea to sperate binaries and firmware_code directory.

**Comment by gysmo38** [comment]
@NoTrace-Kai I have update the update.html page. Now you have a new button to be able to force update when needed. I hope it will work better for you now.

**Comment by NoTrace-Kai** [comment]
Hi,
thanks a lot, i will try it ...
Yesterday i updatet the software with my pc direkt on the sd card ... they show all of them
" Dafang Hacks Version: commit ec9f5b9 from branch master Issues? "
Have i to take your "forked" Version of Dafang-Hacks or can i also use the "original" from EliasKotlyar?
CU and thanks a lot.

**Comment by NoTrace-Kai** [comment]
Now I can push the Update Button ... final or beta ... but after 50% i got this:
- Error starting update process -

CU Kai

**Comment by radinsky** [comment]
@NoTrace-Kai have you find a solution? Updated today, Im getting now the same :\

**Comment by Cats869** [comment]
I also get this error when I try using the update functionality when accessing the web management page of the camera. Happened several times and I'm not sure why.

**Comment by Rocketboy235** [comment]
I also get this error when I try using the update functionality when accessing the web management page of the camera. Happened several times and I'm not sure why.
