### ISSUE TITLE
Device will not connect to wifi after router change

### ISSUE THREAD

**Issue by mattboston** [EliasKotlyar/Xiaomi-Dafang-Hacks#1408]
I previously had this working on a number of Wyze cams.  I needed to replace my Netgear R7000 with a new router Gryphon Router.  I used the same SSID and password.  All of my devices in my house reconnected with the exception of the Wyze cams (running this firmware).  I have double-checked the sd card and the SSID and password are correct.  How can I get them to reconnect?

**Comment by helio58** [comment]
Hi mattboston, I have exactly the same problem.

**Comment by Dopeyr** [comment]
Hi @mattboston, @helio58 

After rebooting your cams, please can you post your dmesg logs?

IIRC they only connect to 2.4ghz wifi, but not sure on that.

**Comment by helio58** [comment]
Hi @Dopeyr, I get it working. I was using a old wpa.conf file. change to the new one works great.Thanks

**Comment by mattboston** [comment]
@Dopeyr I've mounted the sdcard on my computer.  Where would I find the dmesg log?  it's not in the /log folder. Also, here's the /config/wpa_supplicant.conf file

```update_config=1
ignore_old_scan_res=1
ctrl_interface=/var/run/wpa_supplicant
ctrl_interface_group=0
ap_scan=1

network={
        ssid="That's What She SSID2"
        psk="Password Removed"
        scan_ssid=1 
        key_mgmt=WPA-PSK
        pairwise=CCMP TKIP
        group=CCMP TKIP WEP104 WEP40
        priority=2
}

**Comment by Dopeyr** [comment]
@mattboston Apologies, it's in `log/startup.log` - if you post that hopefully that will give some clues.

**Comment by mattboston** [comment]
Attached
[startup.log](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/files/4606789/startup.log)

**Comment by mattboston** [comment]
I realize the startup.log previously posted had logs from a long time ago when I did have a different SSID.  I cleared out the log, and tried to re-connect.  Keep in mine that what has changed recently is just the router, the SSID and Password are the same as the old router from about a week ago.
[startup.log](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/files/4610933/startup.log)

**Comment by Dopeyr** [comment]
Well, I'm confused :) I see in your log re: the DISCONNECTED status... but I also see that in my startup log, and it's very much connected...

```
wlan0: RSN: flushing PMKID list in the driver
nl80211: Flush PMKIDs
wlan0: Setting scan request: 0.100000 sec
ENGINE: Loading dynamic engine
ENGINE: Loading dynamic engine
EAPOL: SUPP_PAE entering state DISCONNECTED
EAPOL: Supplicant port status: Unauthorized
nl80211: Skip set_supp_port(unauthorized) while not associated
EAPOL: KEY_RX entering state NO_KEY_RECEIVE
EAPOL: SUPP_BE entering state INITIALIZE
EAP: EAP entering state DISABLED
ctrl_interface_group=0
wlan0: Added interface wlan0
wlan0: State: DISCONNECTED -> DISCONNECTED
nl80211: Set wlan0 operstate 0->0 (DORMANT)
netlink: Operstate: ifindex=2 linkmode=-1 (no change), operstate=5 (IF_OPER_DORMANT)
```

So not really sure... I run my cameras on a 2ghz-only AP (there was some evidence a while ago that they didn't work on 5ghz e.g. #689), so I'd try that if possible. If it's already 2ghz or you were using mixed 2ghz/5ghz prior to that, I'm really don't know sorry.

**Comment by mattboston** [comment]
"That's What She SSID2" is my 2.4Ghz network.  "That's What She SSID" is my 5Ghz network.  I'm not sure why it would work with one router but not the other, but I came across some documentation about using a single quote in the SSID with wpa_supplicant and properly escaping it.

**Comment by Dopeyr** [comment]
Just for ref, other people have seen the same "DISCONNECTED" issue in the log #704 #644, but are still connected. So I don't think that means much...

I see there's some output in dmesg re: wifi from `RTL871X` which isn't logged in startup.log. I've added a PR to add the output of dmesg to startup.log. It might help people who have boot issues to debug, but can't access dmesg due to no wifi.

@mattboston If you want to add `dmesg >> $LOGPATH` to the very bottom of `run.sh` it will add extra info in `startup.log` that might be of use.

**Comment by mattboston** [comment]
Here's the latest log.  I also added an output of "iwlist scan" and "ifconfig", hopefully that's helpful.  I've also tried using wpa_passphrase to generate the network config.  Then I found some website that recommended to add proto=RSN into the network config.  The current config is below

[startup.log](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/files/4624540/startup.log)

```update_config=1
ignore_old_scan_res=1

ctrl_interface=/var/run/wpa_supplicant
ctrl_interface_group=0
ap_scan=1
country=US

network={
        ssid="That's What She SSID2"
        psk=REMOVED
        proto=RSN
        key_mgmt=WPA-PSK
}

**Comment by aartrost** [comment]
What helped for me was assigning static DHCP leases to the dafang devices. It looks like the camera doesn't request a new lease after reconnecting to wifi.

**Comment by NoTrace-Kai** [comment]
Hi ...
Where can I edit the "static DHCP leases" on the Camera?
CU Kai

**Comment by Combie81** [comment]
defaultgw.conf -> gateway for camera (your routers IP)
config/resolve.conf -> nameservers
config/staticip.conf -> IP adress you want on camera

**Comment by mattboston** [comment]
I was not able to get it to work.  But I have done quite a bit of troubleshooting. As mentioned I'm using the same SSID as my old router, which everything worked.  In my old wpa_supplicant files I used "That's What She SSID2" and it worked, but doing an iwlist on the Raspberry Pi with the new router tells me the SSID is "That\xE2\x80\x99s What She SSID2" .  I tried using that, as well as found numerous websites about encoding the apostrophe and even tried using wpa_passphrase to encode it.  Nothing worked.  What ended up working was using my old router with a new SSID (Without only alphanumeric characters) for only the devices like my WyzeCams, ESP32's, and a couple Raspberry Pi's which all seemed to have a problem with the way the Gryphon Router's handles special characters.

```
wlx14cc201da71b  Scan completed :
          Cell 01 - Address: 80:02:9C:35:1C:43
                    ESSID:"That\xE2\x80\x99s What She SSID2"
                    Protocol:IEEE 802.11bgn
                    Mode:Master
                    Frequency:2.462 GHz (Channel 11)
                    Encryption key:on
                    Bit Rates:144 Mb/s
                    Extra:rsn_ie=30140100000fac040100000fac040100000fac020000
                    IE: IEEE 802.11i/WPA2 Version 1
                        Group Cipher : CCMP
                        Pairwise Ciphers (1) : CCMP
                        Authentication Suites (1) : PSK
                    Quality=100/100  Signal level=100/100  
          Cell 02 - Address: FA:8F:CA:72:C8:08
                    ESSID:"Living Room TV.v"
                    Protocol:IEEE 802.11bgn
                    Mode:Master
                    Frequency:2.437 GHz (Channel 6)
                    Encryption key:off
                    Bit Rates:108 Mb/s
                    Quality=0/100  Signal level=56/100  
          Cell 03 - Address: CC:40:D0:F5:29:CD
                    ESSID:"Dad"
                    Protocol:IEEE 802.11bgn
                    Mode:Master
                    Frequency:2.437 GHz (Channel 6)
                    Encryption key:on
                    Bit Rates:144 Mb/s
                    Extra:rsn_ie=30140100000fac040100000fac040100000fac020c00
                    IE: IEEE 802.11i/WPA2 Version 1
                        Group Cipher : CCMP
                        Pairwise Ciphers (1) : CCMP
                        Authentication Suites (1) : PSK
                    IE: Unknown: DD310050F204104A000110104400010210470010B8216101B6044CC21473951C244388F9103C0001031049000600372A000120
                    Quality=0/100  Signal level=23/100  `

**Comment by NoTrace-Kai** [comment]
> 
> 
> defaultgw.conf -> gateway for camera (your routers IP)
> config/resolve.conf -> nameservers
> config/staticip.conf -> IP adress you want on camera

Thanks a lot ... no I can see the Camera in my Router, but the WebInterface is not available.
I tried a reflash with the latest Master Files and edited also the configs ... but that won't work.
Also a ping is not possible ... 
I got 3 of that cams, but only on one it is not working ?!

CU Kai
