### ISSUE TITLE
Day mode switch causing motion trigger

### ISSUE THREAD

**Issue by Morphy99** [EliasKotlyar/Xiaomi-Dafang-Hacks#1409]
Neos Smartcam
2020-04-17T07:38:51Z ## master branch

Motion is triggered at sunrise when camera reaches threshold to switch from sw night mode to day mode as this switches on / off a few times before going into day mode.

A [workaround](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/332#issuecomment-422190463) would be to switch off night mode manually with HA but I'm not sure if this would still trigger motion or not.

**Comment by xoniq** [comment]
> Neos Smartcam
> 2020-04-17T07:38:51Z ## master branch
> 
> Motion is triggered at sunrise when camera reaches threshold to switch from sw night mode to day mode as this switches on / off a few times before going into day mode.
> 
> A [workaround](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/332#issuecomment-422190463) would be to switch off night mode manually with HA but I'm not sure if this would still trigger motion or not.

I assume it detects motion because the transition it takes on the screen, if you live view the RTSP stream, you see it does multiple steps to switch. I guess the motion detect keeps monitoring there. Perhaps it would be useful to add a 4 second gap in the motion check when a mode is switching.

**Comment by fergio** [comment]
Not an elegant solution, but I modified the /system/sdcard/scripts/common_functions.sh night_mode function. If motion detection is on, it turns it off before changing mode. Its not perfect, and still triggers the odd false alarm, particularly at dawn,

```/system/sdcard/scripts/common_functions.sh
# Control the night mode
night_mode(){
  bMotion=false
  if [ "$(motion_detection status)" = "ON" ] ; then
      bMotion=true
      bMotionDelay=1
      motion_detection off
      echo "Motion detection is off"
      sleep $bMotionDelay
  fi
  case "$1" in
  on)

    bMotionDelay=4
    /system/sdcard/bin/setconf -k n -v 1
    . /system/sdcard/config/autonight.conf
    if [ -z "$ir_led_off" ] || [ $ir_led_off = false ]; then
        ir_led on
    else
        ir_led off
    fi
    ir_cut off
    ;;
  off)

    bMotionDelay=6
    ir_led off
    ir_cut on
    /system/sdcard/bin/setconf -k n -v 0
    ;;
  status)
    status=$(/system/sdcard/bin/setconf -g n)
    case $status in
      0)
        echo "OFF"
        ;;
      1)
        echo "ON"
        ;;
    esac
  esac
  if [ "$bMotion" = "true" ]; then
        bMotion=false
        echo "Turning on motion after $bMotionDelay second delay"
        sleep $bMotionDelay
        motion_detection on
        echo "Motion detection is on"
  fi
}

**Comment by fergio** [comment]
Tested this and it does not really work.
