### ISSUE TITLE
Remove OSD "Too high value won't display anything" from beta branch

### ISSUE THREAD

**Issue by timdonovanuk** [EliasKotlyar/Xiaomi-Dafang-Hacks#1410]
I think the user is capable of deciding if the text is too big or not 😉 

I thought OSD had broken when I updated to beta, as it used my previous setting of 50 but showed nothing. 

I use Dafang as a baby monitor and it's important to see that the stream has not frozen from a distance - the best way to do this is a large second OSD that can be seen across the room.

**Comment by nik0** [comment]
@timdonovanuk 
Will look at it later ... Reproduced the issue
It was working before ?

**Comment by nik0** [comment]
What you can do:
1/ Edit  firmware_mod/bin/v4l2rtspserver-master.ini and set POOLSIZE to OFF
2/ Test this PR:
Please check https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/pull/1411

Add edit the field POOLSIZEBUFFER to set to 0x320000 (if still have "ipu_osd error ret" error, continue augmenting the value)

**Comment by timdonovanuk** [comment]
It was working in the stable branch, I had it set to 60 successfully. In beta any values over 30 nothing shows. Cheers.
