### ISSUE TITLE
Dafang base starts moving at camera start

### ISSUE THREAD

**Issue by SAOPP** [EliasKotlyar/Xiaomi-Dafang-Hacks#1414]
Hi guys!

I have one question, I have 2 hacks dafang over 1 year ago (I'm not update the firmware from day one), today I hack my 3th dafang - and this camera start moving at the starts... Any options to disable this? Or now this is normal behaviour at current firmware? 'Coz my two cameras is not moving at the starts. Thanks!

**Comment by saipsa** [comment]
yes, with the recent update, my cam also started moving.

**Comment by SAOPP** [comment]
Okay, thanks for comfirm.

**Comment by dewi-ny-je** [comment]
Personally I'd like to set the camera to calibrate only vertically at boot and not horizontally.

I haven't yet checked whether it's possible, but you can in theory disable movement at boot by renaming /system/sdcard/config/userscripts/calibratePTZ.sh so that the extension is .dist in addition to .sh.

If it still moves, let me know.

**Comment by SAOPP** [comment]
Okay thanks u! I will check it during next two hours and back with some feedback. 

PS I asked 'bout it, 'coz one of my Dafang hangs on the bracket, and it hangs at the diagonal. :) And I wouldn't want it to lose the exposed angle after every boot.

**Comment by SAOPP** [comment]
@dewi-ny-je hey buddy, I don't see this file at this path:

![image](https://user-images.githubusercontent.com/5647009/81715493-f677ea00-9480-11ea-90fe-208c0b52ec16.png)

I have a latest master branch at this device.

**Comment by SAOPP** [comment]
maybe it's PTZpresets.sh now?

**Comment by SAOPP** [comment]
Hey I tried to rename this script, and it didn't help. :) So I moved it back.

**Comment by jmtatsch** [comment]
Calibration at boot should be disabled by default because it can destroy cameras without endstop sensors.

**Comment by jmtatsch** [comment]
Recently this https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/74247138e7a0a899ca0e13d0afd94b79682b33aa/firmware_mod/config/userscripts/startup/calibratePTZ.sh.dist was introduced, but is not enabled by default. Yet 2 of my 4 cameras are calibrating and I have no idea why.

**Comment by jmtatsch** [comment]
Seems like *.dist files in startup are executed no matter what because the excluding condition fails.
