### ISSUE TITLE
RTSP H264 SERVER uncheck after xiaofang camera reboot

### ISSUE THREAD

**Issue by Zeroo92** [EliasKotlyar/Xiaomi-Dafang-Hacks#1420]
Hello,

I have a xiaofang and the RSTP H264 server is uncheck every time I reboot the camera.

I try to change the state of the button on main page, on configuration/video, on system page and with safari, chrome, explorer and nothing to do, this don't work.

Any idea to try ?

**Comment by Morphy99** [comment]
Does this work if you toggle switch in camera controls?
