### ISSUE TITLE
Record few seconds before motion is detected

### ISSUE THREAD

**Issue by dewi-ny-je** [EliasKotlyar/Xiaomi-Dafang-Hacks#1422]
It can be useful, especially since motion is detected with a short lag, to have the last seconds also included in the recording. More advanced solutions offer this feature because it is quite useful.

I don't know how to implement it, except for brute force: continuously recording to temp files and discarding if not needed, but also such a solution may result in discrete videos, not "the last seconds before motion detection".

Any idea?

**Comment by nik0** [comment]
I tried to add such functionnality. Unfortunatly I didn't succeed because I am not a video format expert and I didn't manage to get iframe at beggining. So a lot of blank video was recorded.
What I wanted to do instead is to record pictures instead of video, it is something that can be acceptable for you ?

**Comment by NorthernMan54** [comment]
I went down this path a few months ago and have something that works pretty well with my rtsp enabled wyzecams and raspberry pi 4 - 4gb.

I created a ram drive on my rpi, and used the ffmpeg option to create video clips, and loop thru the files to create a 60 second video buffer that I use to grab snapshots and video clips.

Scripts are https://github.com/NorthernMan54/homebridge-camera-ffmpeg/tree/Google-Photos/scripts

To manage this, I’m using node-red and for display I’m using homebridge, and google-photos for storage.

**Comment by saipsa** [comment]
> I created a ram drive on my rpi, and used the ffmpeg option to create video clips, and loop thru the files to create a 60 second video buffer that I use to grab snapshots and video clips.

How does it work? Won't the sd card get destroyed because all read/write will take place at same location range?

**Comment by NorthernMan54** [comment]
I’m not using the sd card but the tmpfs file system for storage mounted to /var/tmp.   This doesn’t use the sd card, but does go away on reboot.
