### ISSUE TITLE
Password encoding

### ISSUE THREAD

**Issue by MarkSanders54** [EliasKotlyar/Xiaomi-Dafang-Hacks#1424]
I did something silly, and set the password as:
root:all:a6564**8**02a687c445cbd80bab194c42d5

instead of:
root:all:a6564**9**02a687c445cbd80bab194c42d5

I no longer have physical access to the device because it is setup as a nest cam. 

I assumed that I can just put in the encoded password but putting in "a6564802a687c445cbd80bab194c42d5" as the password I had no luck. How is "ismart12" encoded as "a6564902a687c445cbd80bab194c42d5"? Is there anyway to decode the password I have set? I don't see this documented anywhere.

**Comment by marked23** [comment]
This hash is the MD5 of the string: 
root:all:ismart12  
A6564902A687C445CBD80BAB194C42D5

Any tiny change in the password causes a completely different hash.
root:all:ismbrt12   (changed a to b)
B8772A442B3B76EBC526E6BAB4EBFC79

Determining what password would encode to your hash with the "8" is hopeless.

**Comment by MarkSanders54** [comment]
I see, makes sense. I had tried the MD5 hash of just ismart12, but that didn't match. I now see why. 

I was able to remotely fix the password by connecting via telnet since the system password remained as ismart12.

**Comment by jmtatsch** [comment]
Ah so you still had web access to enable the telnet daemon?

**Comment by jmtatsch** [comment]
Would you mind sharing some photos of the nest for usecase examples?

**Comment by MarkSanders54** [comment]
Telnet must have been enabled previously, but it was still on after the upgrade, luckily. The camera is a real pain to reach. 

Here are some photos:
![203539](https://user-images.githubusercontent.com/38710090/81965847-7dd27400-95cd-11ea-8895-e7600cb02857.jpg)
![130704](https://user-images.githubusercontent.com/38710090/81965852-7f03a100-95cd-11ea-9027-13cab65bf740.jpg)
![135516](https://user-images.githubusercontent.com/38710090/81965855-7f9c3780-95cd-11ea-8ec0-14031c04ff44.jpg)
