### ISSUE TITLE
X264 RTSP taking all available CPU on Wyzecam PAN

### ISSUE THREAD

**Issue by gleepwurp** [EliasKotlyar/Xiaomi-Dafang-Hacks#1427]
exact camera hardware: Wyze Cam Pan - Wyze CP1
Version: commit 99f67ef

### Description

Connect to the x264 Video Stream through RTSP,  720p resolution.

VLC won't connect to it remotely, and when I logged in locally to the Wyzecam, CPU Utilization was at 100%, Load AVG was at 5.

Issue started yesterday after running an update. I see that the v4l2
[wyzecam_v4l2issue.zip](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/files/4618495/wyzecam_v4l2issue.zip)
 video streaming app was updated 4 days ago.

### What did you do to debug the issue

Turned off x264 Streaming, CPU load went down to near 95% idle, LoadAvg 0.16.

### Evidence

See Attached.

### Contribute Back

If your issue was resolved, please consider contributing back to the project by creating a pull request to improve the code or documentation in order to avoid that this issue arises again for other people.

**Comment by gleepwurp** [comment]
Tried running the v4l2rtspserver-master manually:

`[root@DAFANG:]# /system/sdcard/bin/v4l2rtspserver-master -W1280 -H720 -E MP3:16000:44100 -r 1 -F 25 -U XXXX:YYYY -P 8554
/system/sdcard/bin/v4l2rtspserver-master: can't load library 'libliveMedia.so'
[root@DAFANG:]# 
`

**Comment by Dopeyr** [comment]
> Tried running the v4l2rtspserver-master manually:
> 
> `[root@DAFANG:]# /system/sdcard/bin/v4l2rtspserver-master -W1280 -H720 -E MP3:16000:44100 -r 1 -F 25 -U XXXX:YYYY -P 8554 /system/sdcard/bin/v4l2rtspserver-master: can't load library 'libliveMedia.so' [root@DAFANG:]# `

See https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/691

**Comment by gleepwurp** [comment]
> See #691

Thanks, stopped the service and exported the library and am now able to run the v4l2 server on the command line:
`stop the running server: /system/sdcard/controlscripts/rtsp-h264 stop`
`export LD_LIBRARY_PATH=/system/sdcard/lib:$LD_LIBRARY_PATH`
`/system/sdcard/bin/v4l2rtspserver-master -W1280 -H720 -E MP3:16000:44100 -r 1 -F 25 -U monitor:hassio -P 8554 -vv`
 
At least now I'm seeing some logs, as the v4l2 logs in the web console were always empty. Video is always pretty corrupted though...
Running with verbose logging, I see a lot to drop frame messages:
`2020-05-13 07:40:10.228 (  14.250s) [DeviceSource    ]       DeviceSource.cpp:254      9| Queue full size drop frame size:10`
`2020-05-13 07:40:10.233 (  14.255s) [DeviceSource    ]       DeviceSource.cpp:244      9| queueFrame	timestamp:1589370010.113552	size:21	diff:80ms`
`2020-05-13 07:40:10.243 (  14.265s) [DeviceSource    ]       DeviceSource.cpp:254      9| Queue full size drop frame size:10`
`2020-05-13 07:40:10.246 (  14.268s) [DeviceSource    ]       DeviceSource.cpp:244      9| queueFrame	timestamp:1589370010.113552	size:4	diff:80ms`
`2020-05-13 07:40:10.248 (  14.270s) [DeviceSource    ]       DeviceSource.cpp:254      9| Queue full size drop frame size:10`
`2020-05-13 07:40:10.252 (  14.274s) [DeviceSource    ]       DeviceSource.cpp:244      9| queueFrame	timestamp:1589370010.113552	size:21	diff:80ms`
`2020-05-13 07:40:10.254 (  14.275s) [DeviceSource    ]       DeviceSource.cpp:254      9| Queue full size drop frame size:10`


G.

**Comment by gleepwurp** [comment]
I've copied over the SDCard files with an older Wyzecam PAN deployment dafang on a CAM that works well, and using the older V4L2rtspserver-master I don't get streaming issues and camera glitches anymore. Usage is still high but as it is running OK with this old version I'm guessing that is the normal operating range for this camera.

This is the md5sum of the server that works:
5fb03fd4e782a004c4b29f5801eb363d  /system/sdcard/bin/v4l2rtspserver-master

And matches the "JpegOpim (lot smaller)" from July 30th 2018.

**Comment by so3n** [comment]
I began experiencing similar issue since updating a few days ago. 

Viewing stream on tinycam works fine for a bit, then eventually drops out. 

What's interesting is the fps is around 40-50 while it is streaming even though in video settings it should only be 25 fps. Wondering if this additional load from frame rate is causing the issue.

I ended up downgrading to an older commit (from around end of march 2020) and streaming issue goes away. Streaming on tinycam shows max 25fps.

**Comment by nik0** [comment]
Can you try setting parameter POOLSIZE to off in /system/sdcard/bin/v4l2rtspserver-master.ini ?

**Comment by so3n** [comment]
I will test this on one of my Dafang's.

What does poolsize do?

**Comment by nik0** [comment]
This parameter which is undocumented in the SDK allow to save some memory

**Comment by so3n** [comment]
Just been testing for a few minutes now, and it seems to help although it did drop out once after I was panning the camera around left and right. But doesn't seem to be as frequent as before. Will monitor over the day to see how it goes.

**Comment by Dopeyr** [comment]
> I began experiencing similar issue on a Xiaomi Dafang since updating the firmware a few days ago.
> 
> Viewing stream on tinycam works fine for a bit, then eventually drops out.
> 
> What's interesting is the fps is around 40-50 while it is streaming even though in video settings it should only be 25 fps. 

Interestingly, I've seen this on Tiny Cam too - the frame rate is reported double what's in the video settings. I've only noticed this on the new version. However, streaming at the same time with VLC reports the correct framerate.

**Comment by jmtatsch** [comment]
@nik0 Maybe that’s why every second frame the OSD is not displayed properly?

**Comment by nik0** [comment]
@jmtatsch  You mean the number of FPS? It's a good idea to look around this ...
@Dopeyr how do you measure framerate if VLC is  ok?

**Comment by Dopeyr** [comment]
@nik0 TinyCam has an option to display bitrate and framerate whilst viewing the stream. I'll try and get some logs to see if there's anyting interesting in there. As I said, the same stream at the same time in VLC reports the correct framerate. It's odd.

**Comment by nik0** [comment]
Yes strange.
What are your video settings ?
What happen if you change the FPS in the video settings ?

**Comment by so3n** [comment]
> Can you try setting parameter POOLSIZE to off in /system/sdcard/bin/v4l2rtspserver-master.ini ?

So after trying for a day seems a bit better but still not as stable as older version. 

Also tinycam is still showing 50fps which I think is causing the stability issue. 

Going to go back to older version.

**Comment by Dopeyr** [comment]
> Yes strange.
> What are your video settings ?
> What happen if you change the FPS in the video settings ?

Hi, my settings are:

<img width="429" alt="image" src="https://user-images.githubusercontent.com/5502915/82119781-c8d8bc80-9770-11ea-80ad-bef39331de88.png">

This works pretty stable in TinyCam for me. It's just that the the FPS TinyCam is reporting doesn't match. If I increase the FPS to say 25, then TinyCam reports 45fps. This does vary - e.g. between 43 - 47fps, so I'm thinking perhaps TinyCam calculates the FPS, whereas VLC might just read it from the stream "metadata" (if there is such a thing?)

Interestingly, if I set the set the "per" value to 2 e.g. 25 frames per 2 seconds, the frame rate is correct in both TinyCam and VLC. It still varies with tinycam.

I also noticed if I set the frame rate really low e..g 1 per 1 second, it's really unstable in VLC (which normally performs great) I get a frame every second, then there's big gaps, etc. I don't know if this is indicative of anything...

**Comment by nik0** [comment]
@Dopeyr 
The good news is that I can reproduce the issue with your video settings
It seems to be correlated to the bitrate. Try a much higher value like 9000
The bad news is that I don't know why :-(

**Comment by gleepwurp** [comment]
Question I have: Where do the binaries comes from? I don't recall seeing the source file for v4l2rtspserver anywhere...?

I'm curious to know if its something we can take a look at, or if it's coming from an external, non-open source? Or another Github repo?

Thx.

Y.

**Comment by jmtatsch** [comment]
https://github.com/Dafang-Hacks/Main

**Comment by gleepwurp** [comment]
Thx!

**Comment by nik0** [comment]
> @Dopeyr
> The good news is that I can reproduce the issue with your video settings
> I think I can not reproduce because I am using 1920x1080 and the camera can not meet my 25FPS settings
> The bad news is that I don't know why :-(

I pushed a new version that doesn't use the SDK API for the FPS ...

**Comment by inode-** [comment]
> I've copied over the SDCard files with an older Wyzecam PAN deployment dafang installation from another Wyzacam PAN that works well, and using the older V4L2rtspserver-master I don't get streaming issues and camera glitches anymore. Usage is still high but as it is running OK with this old version I'm guessing that is the normal operating range for this camera.
> 
> This is the md5sum of the server that works:
> 5fb03fd4e782a004c4b29f5801eb363d /system/sdcard/bin/v4l2rtspserver-master
> 
> And matches the "JpegOpim (lot smaller)" Commit tag from July 30th 2018.

You saved my life... The v4l2rtspserver has definitely some problems.

Working on the new version it cause (on Xiaomi S1) the camera to go offline after some minutes of RTSP streaming, using the old binary everything work properly.

inode

**Comment by klausmcm** [comment]
@inode- @gleepwurp Which files do you have installed on your camera? I installed the files from `a6832b204efc9be12ce16cb34808951af4d0f2bc` and copied `/system/sdcard/bin/v4l2rtspserver-master` from `5fb03fd4e782a004c4b29f5801eb363d` (sha `56431bc796f06618599f0c6c9555c49941618fc3`). But that combination just crashes the rtsp server whenever I try to connect with vlc. Thanks,

**Comment by gleepwurp** [comment]
Hi @klausmcm ,

here is my current directory's checksum (/system/sdcard/bin):

0850c891db0dcefe20953876d099c152  README.md
9d61979e2d34427412165577d38184c7  audioplay
d8033edb5a3bae99048342af015f099b  autonight
c779546402defbff7698d32d45d97cfe  avconv
e2ebdcabcf36fc3c1d379d22a2fae468  bftpd
0d273f0cfb39f37660602a1e21b380a0  busybox
8a9a77d53e8f9042c566e61208cb8a85  curl
a99443e2294068d03c43737d83de1ec4  curl.bin
583208d758219df361e4ba900831f134  dosfsck
35ce242d87f2fa0567fdf3d05cd05485  dosfslabel
dd0fed3b2dbdf1cb9f5ea9194531d58e  dropbearmulti
35ce242d87f2fa0567fdf3d05cd05485  fatlabel
583208d758219df361e4ba900831f134  fsck.fat
583208d758219df361e4ba900831f134  fsck.msdos
583208d758219df361e4ba900831f134  fsck.vfat
ebed1d71a2c1db04e590744517f2e825  gdbserver
513fc8329d5d82fce10d2cd12ae33037  getimage
74e3950c1302278efa93d01b156de716  h264Snap
b5e901a652a2489d46f22fd61f4b9f57  jpegoptim
c956c91520c841967fc0783591260b18  jpegtran
4bfd98a65f658d1de7ce20c2bf257c67  jq
7e5f89a13aaf4fe1fe4f954158c9ac2d  lighttpd
7abb3b92cc4b5cd00632f65eead4f0b5  lighttpd.bin
8cbe76d8f0b77a1e6951efe69f994b27  mJpegStreamer
7514d9f2c63fbfd4c16c80a0c14ad877  matrix
d6868bf8e9cbe852b3ceb969b546b567  mkdosfs
d6868bf8e9cbe852b3ceb969b546b567  mkfs.fat
d6868bf8e9cbe852b3ceb969b546b567  mkfs.msdos
d6868bf8e9cbe852b3ceb969b546b567  mkfs.vfat
2bf05aaea1456d532f1a2a835d81eb11  mosquitto_pub
2d81f04b06d27a060b8d43b109a098dd  mosquitto_pub.bin
8282c80440ed71738ab5893859fa6210  mosquitto_sub
dfda783300c4bf04103f341039a27272  mosquitto_sub.bin
257343cac74fde1b6a670f20f5e87e85  motor
1bf0c4eb03938bd9237bb2541a46a207  motor.bin
5708873447e30a732b582a7c03da244c  onvif_srvd
08e570edc408adfcf25d32b6756b0a27  openRTSP
0ce11848cb730f5f08943a3d7b150712  openRTSP.bin
2cef61dda12d4f823adacedd16a23615  openssl
3a45d20fd24aa72f99c6550a565ea4ca  ossplay
3a45d20fd24aa72f99c6550a565ea4ca  ossrecord
b5ffd96d09eaacf745e55cd9ba793ee3  sample-Audio
2f65912c1e3461dc90491bacbc1180b9  sample-Encoder-h264-IVS-move
8bfb60e51df8f972bc56bfee591481b7  sample_sinfo
6b85f1be1ea3e92b46022a06d80d86b8  setconf
4d93036f3327e29aa19ed3a1562c9958  telegram
5fb03fd4e782a004c4b29f5801eb363d  v4l2rtspserver-master
153f611f54ff8808f77dba5c7cc72feb  v4l2rtspserver-master.ini
9131a8c7176739e52ebcd150863f8f87  v4l2rtspserver-master.old

I can send you a copy of my files zipped up if you want.

**Comment by klausmcm** [comment]
Thanks @gleepwurp . I'll try to match these hashes with a repo commit.

**Comment by klausmcm** [comment]
@gleepwurp Could you also please post the hashes for the files in your `/lib` folder? I'm having trouble matching the `/bin` hashes to a commit even when considering the changed ` v4l2rtspserver-master` file.

**Comment by gleepwurp** [comment]
@klausmcm , sure, here it is:

d95c036964f82493f4e5c0ad2df50e40  libBasicUsageEnvironment.so
6c336007b37df59e199032bbd569f549  libUsageEnvironment.so
90a3c90d81bc2f8e2a952a01cdd6e672  libalog.so
4a524aada02cc41fa5a9006aa967473f  libcrypto.so
51e665af044214e0624609d7f21dd748  libcrypto.so.42
194a95fe0b309b43a826dc40b4b673b4  libcrypto.so.43
4a524aada02cc41fa5a9006aa967473f  libcrypto.so.46
4a524aada02cc41fa5a9006aa967473f  libcrypto.so.46.0.1
44025ecaa61d0dc23a466ab37ce41f3e  libgroupsock.so
da38e940020f876183a1ed19520f2526  libimp.so
b831a14ce901fd8c0c07f0b7fa904cdf  libliveMedia.so
cef99715f4c1a13cf556aba2a1b2f15a  libmosquitto.so.1
34d4096815bbf5eb3c066d6956cb7fb4  libmosquittopp.so.1
341cbbb1a05ae73ccb79982d1ec2f438  libmp3lame.so
992c93411942f36879b14ba3b48e1e55  libopus.so
ba851a0e508f696680b9180af57cc3a9  libssl.so
2649ee9d2b76c2d788e34d2be3a21979  libssl.so.44
4066d057c71a6e03d35f6248a71b96a4  libssl.so.45
ba851a0e508f696680b9180af57cc3a9  libssl.so.48
ba851a0e508f696680b9180af57cc3a9  libssl.so.48.0.1

**Comment by klausmcm** [comment]
Thanks again @gleepwurp . Could you share a copy of your `/` (minus any confidential files like wpasupplicant.conf)?

I managed to piece together `/bin` and `/lib` folder that matches your hashes. For `/bin`, I had to get files from `a6832b20`, `1727757f`, `75eee984`, `d31d1968`, `03041f48`, `e08a5e5f` and `56431bc7`. For `/lib`, I grabbed files from `7059874e`, `62851318` and `a6832b20`. And now my camera doesn't boot ... Putting back files from `a6832b20` (current master), gets the camera going again.

**Comment by gleepwurp** [comment]
@klausmcm, having fun trying to get the backup off of the cam... Will let you know as soon as I have the backup, and I've uploaded to a transfer location (tempsend.com)

**Comment by gleepwurp** [comment]
@klausmcm I've put the tar here: https://tempsend.com/rfbbj
Will expire in 24h.

**Comment by klausmcm** [comment]
@gleepwurp Perfect, thank you! So I also decided to try out opening the rtsp stream on vlc on my android device and the stream is loading fine! It's vlc in Debian 11 (Bullseye) that's the issue ... I will still hold onto the files in case I experience the same issue described in this thread.
