### ISSUE TITLE
No video streaming

### ISSUE THREAD

**Issue by TakTeek** [EliasKotlyar/Xiaomi-Dafang-Hacks#143]
What i do wrong. Sound, motor and indicators work, but no video
![img_20180305_230327_hdr](https://user-images.githubusercontent.com/37100528/37022037-5cadb650-212a-11e8-8e7d-3874b58524c4.jpg)
![img_20180305_230445_hdr](https://user-images.githubusercontent.com/37100528/37022038-5cdf38b0-212a-11e8-860c-d4fed56ec512.jpg)
![img_20180305_230346_hdr](https://user-images.githubusercontent.com/37100528/37022039-5d0e2b02-212a-11e8-8aab-2abddde790e0.jpg)
![img_20180305_230815_hdr](https://user-images.githubusercontent.com/37100528/37022102-97d3c396-212a-11e8-8460-7a1b7120dfed.jpg)
![img_20180305_230706_hdr](https://user-images.githubusercontent.com/37100528/37022106-98a9fbdc-212a-11e8-8476-4f1bc334acb1.jpg)

**Comment by shinebar1001** [comment]
Can you please
- reboot the camera
- try to stop / start the rtsp-server
- provide a  screenshot of the process list?

Thanks!

**Comment by vicm96** [comment]
I have exactly same issues. I have try reboot stop and start rtsp and no luck.

Here is my Process list


Process list: | PID USER       VSZ STAT COMMAND     1 root      1600 S    {linuxrc} init     2 root         0 SW   [kthreadd]     3 root         0 SW   [ksoftirqd/0]     5 root         0 SW<  [kworker/0:0H]     6 root         0 SW   [kworker/u2:0]     7 root         0 SW   [rcu_preempt]     8 root         0 SW   [rcu_bh]     9 root         0 SW   [rcu_sched]    10 root         0 SW   [watchdog/0]    11 root         0 SW<  [khelper]    12 root         0 SW<  [writeback]    13 root         0 SW<  [bioset]    14 root         0 SW<  [kblockd]    15 root         0 SW   [khubd]    16 root         0 SW   [kworker/0:1]    17 root         0 SW<  [cfg80211]    18 root         0 SW<  [rpciod]    20 root         0 SW   [kswapd0]    21 root         0 SW   [fsnotify_mark]    22 root         0 SW<  [nfsiod]    23 root         0 SW<  [crypto]    37 root         0 SW   [kworker/u2:1]    38 root         0 SW<  [deferwq]    39 root         0 SW<  [kworker/0:1H]    52 root      1588 S    telnetd    56 root         0 SW   [mmcqd/0]    60 root         0 SWN  [jffs2_gcd_mtd4]    62 root         0 SWN  [jffs2_gcd_mtd7]    64 root         0 SWN  [jffs2_gcd_mtd8]    66 root         0 SWN  [jffs2_gcd_mtd9]    73 root      1600 S    /sbin/getty -L console 115200 vt100    93 root         0 SW   [ksdioirqd/mmc1]    96 root         0 SW   [RTW_XMIT_THREAD]    97 root         0 SW   [RTW_CMD_THREAD]    98 root         0 SW   [RTWHALXT]   107 root      4700 S    wpa_supplicant -B -i wlan0 -c /system/sdcard/config/   144 root      1604 S    udhcpc -i wlan0 -p /var/run/udhcpc.pid -b -x hostnam   147 root         0 SW<  [i2s_work_1]   148 root         0 SW<  [i2s_codec_irq_w]   160 root         0 DW   [motor_thread]   166 root         0 SW   [irq/37-isp]   179 root      1448 S    /system/sdcard/bin/dropbearmulti dropbear -R   183 root      1236 S    /system/sdcard/bin/bftpd -d   184 root      1368 S    /system/sdcard/bin/boa -c /system/sdcard/config/   196 root      1604 S    {ldr.sh} /bin/sh /system/sdcard/scripts/ldr.sh  6894 root      1516 S    /system/sdcard/bin/dropbearmulti dropbear -R  7000 root      1608 S    -sh 11848 root      1604 S    udhcpc -i wlan0 -p /var/run/udhcpc.pid -b -x hostnam 15278 root         0 SW   [kworker/0:0] 16212 root      163m S    /system/sdcard/bin/v4l2rtspserver-master 16216 root         0 DW   [apical_isp_fw_p] 21502 root      1584 S    sleep 10 21676 root      1596 S    {currentpic.cgi} /bin/sh ./currentpic.cgi 1523636685 21690 root      3536 S    /system/sdcard/bin/getimage 21695 root      1632 S    {status.cgi} /bin/sh ./status.cgi 21749 root      1632 S    {status.cgi} /bin/sh ./status.cgi 21750 root      1584 S    cat 21805 root      1592 R    ps
-- | --
rootfs on / type rootfs (rw) /dev/root on / type squashfs (ro,relatime) tmpfs on /dev type tmpfs (rw,relatime) proc on /proc type proc (rw,relatime) devpts on /dev/pts type devpts (rw,relatime,gid=5,mode=620,ptmxmode=000) tmpfs on /tmp type tmpfs (rw,relatime) tmpfs on /run type tmpfs (rw,nosuid,nodev,relatime,mode=755) sysfs on /sys type sysfs (rw,relatime) media on /media type tmpfs (rw,relatime) /dev/mtdblock3 on /driver type squashfs (ro,relatime) /dev/mtdblock4 on /system type jffs2 (rw,relatime) /dev/mtdblock7 on /backupa type jffs2 (rw,relatime) /dev/mtdblock8 on /configs type jffs2 (rw,relatime) /dev/mtdblock9 on /params type jffs2 (rw,relatime) /dev/mmcblk0p1 on /system/sdcard type vfat (rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro)

**Comment by vicm96** [comment]
Sorry here is screenshot. Is it a busted camera
![process_list](https://user-images.githubusercontent.com/38358670/38746636-1eabdad0-3f16-11e8-8226-39a90471f0e7.JPG)

**Comment by pjsg** [comment]
Can you login over ssh and run 'dmesg' and see what is there.... Is there talk of a segmentation fault?

**Comment by pjsg** [comment]
This is the same as mine (and some other people). It is unclear what is happening -- it could be that there are multiple hardware versions out in the wild and the streaming code simply doesn't work on our hardware version....

**Comment by elchilango22** [comment]
I had a similar issue with a brand new camera I set up today. After a little digging, I found that there is some kind of path issue in the current web UI. Specifically, there are references to cgi scripts like this:
https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/6521d6e4b7c07c6419499314a6360888e2b07589/firmware_mod/www/cgi-bin/scripts.cgi#L99 These links must have worked at one time with a relative path (perhaps being referenced from another page directly accessed from the cgi-bin directory), but now with `live.html` loading those pages asynchronously via `/live.html`, the paths are broken.

I was able to fix it by replacing references to things like `scripts.cgi` with `/cgi-bin/scripts.cgi`.

**Comment by vicm96** [comment]
After many times loading different hacks cfw-12.bin and 13 and using firmware mod, my camera stop working. It is orange light, no blinking, just orange.

**Comment by jmtatsch** [comment]
@vicm96 Your link is for a different camera model on a different platform. I hope you at least loaded one of the original firmwares from Elias repo.

**Comment by jmtatsch** [comment]
Closing this in favour of #223. Please continue the discussion there.
