### ISSUE TITLE
[feature request] gui "motion" add video recording / timelapse photos

### ISSUE THREAD

**Issue by herrxyz** [EliasKotlyar/Xiaomi-Dafang-Hacks#1430]
Hey there,
I would like to have the convenient possibility to enable video-recording in the motion-part in GUI when motion is detected.
would also like to have a checkmark to enable/disable timelapse photos (ideally with other timing then "normal" timelapse). both types of recording should end several seconds after no motion detected.

**Comment by gysmo38** [comment]
On my new ui there I add motion files :) It wait in PR :)

**Comment by herrxyz** [comment]
great :-) looking forward to seeing it
I'll close this issue then
