### ISSUE TITLE
h264 rtsp server stops sending video (xiaofang 1S)

### ISSUE THREAD

**Issue by ivanfor** [EliasKotlyar/Xiaomi-Dafang-Hacks#1435]
Hi

> Model | Xiaomi Xiaofang 1S
Firmware date | 2020-05-13T17:08:36Z
Firmware branch | master
Firmware commit | c65614a ( No update available)
Kernel Version | #32 PREEMPT Wed Jan 24 02:40:56 CST 2018
Bootloader Version | U-Boot 2013.07 (Mar 13 2018 - 15:07:07)
Local Time | Wed May 20 17:38:56 CEST 2020

### Description
RTSP Server stops sending video from time to time and a restart is needed in order for it to work again.

### What did you do to debug the issue
I used the following command trying to see what's happening:
`/system/sdcard/bin/avconv` -probesize 32 -i rtsp://127.0.0.1:8554/unicast

#### Normal output (after a rtsp server restart):
>avconv version v13_dev0-1541-ge368b0cbf, Copyright (c) 2000-2018 the Libav developers
  built on May 17 2018 20:39:55 with gcc 4.7.2 (Ingenic r2.3.3 2016.12)
Trailing options were found on the commandline.
[rtsp @ 0x163e6e0] Estimating duration from bitrate, this may be inaccurate
Input #0, rtsp, from 'rtsp://127.0.0.1:8554/unicast':
  Metadata:
    title           : LIVE555 Streaming Media v2020.03.06
    comment         : LIVE555 Streaming Media v2020.03.06
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: h264 (Main)
      **yuv420p, 640x360**
      90k tbn
    Stream #0:1: Audio: mp3
      0 channels, s16p
At least one output file must be specified

#### Wrong output (no video, after some time working)
>avconv version v13_dev0-1541-ge368b0cbf, Copyright (c) 2000-2018 the Libav developers
  built on May 17 2018 20:39:55 with gcc 4.7.2 (Ingenic r2.3.3 2016.12)
Trailing options were found on the commandline.
[rtsp @ 0x1a066e0] Estimating duration from bitrate, this may be inaccurate
Guessed Channel Layout for Input Stream #0.1 : mono
Input #0, rtsp, from 'rtsp://127.0.0.1:8554/unicast':
  Metadata:
    title           : LIVE555 Streaming Media v2020.03.06
    comment         : LIVE555 Streaming Media v2020.03.06
  Duration: N/A, start: 0.000000, bitrate: 64 kb/s
    Stream #0:0: Video: h264
      **none**
      90k tbn
    Stream #0:1: Audio: mp3
      44100 Hz, 1 channels, s16p, 64 kb/s
At least one output file must be specified

I can't find anything relevant in v4l2rtspserver-master.log 
It seems to happen more frecuently with higher video resolution.
I have SWAP enabled:
>total        used        free      shared  buff/cache   available
Mem:          35404       22984        2452           0        9968           0
-/+ buffers/cache:        22984       12420
Swap:        278520        4076      274444

Is there anything I can do to debug further?

**Comment by MatheusAmbrozio** [comment]
I have the same problem here =(

**Comment by OneOfTheInfiniteMonkeys** [comment]
I have a similar issue following the upgrade:

Following approximatly 8 hours of operation the service seems to stop. When reviewing the System  | Services options rtsp-h264 shows as stopped (no PID shown). rtsp-h264 can be restarted using the System | Services menu option and selecting Start. A PID is shown to the right of rtsp-h264 following pressing start and the video is displayed when returning to the home screen.

I was unable to locate the log file v4l2rtspserver-master.log mentioned in the above responses. 

**Device**
NEOS Smartcam V2.0

**Recording**
Recording should be enabled using the Motion Detection Specified Zone, however this does not appear to function at this time.

**Video configuration**
Video Settings
Video username {none}
Video password {none}
Video port
Default is 8554
Video Size 1280 x 72
Video format VBR
FrameRate:15 number of image(s) per 1 second(s)

**Configuration summary**
System
Hostname 	SMCAM01
Model 	Wyzecam V2
Firmware date 	2020-05-25T01:27:18Z
Firmware branch 	master
Firmware commit 	4a64c49 ( No update available)
Kernel Version 	#21 PREEMPT Thu Oct 19 11:38:16 CST 2017
Bootloader Version 	U-Boot 2013.07 (Jul 05 2018 - 13:33:27)
Local Time 	Mon May 25 21:09:17 BST 2020
Uptime 	1d, 12h, 44m
Load Average 	2.15, 1.48, 1.09

Network (WLAN0)
SSID 	XXXX
Link Quality 	100
IP Address 	10.0.0.209
MAC Address 	xx:xx:xx:xx:xx:x
Netmask 	255.255.255.0
Gateway 	10.0.0.1
DNS 	

search home # wlan0
nameserver 10.0.0.55 # wlan0 

Bootloader
Bootloader MD5:

b1f6f38dbb48d4e9d8911833aff0bc99

Bootloader Version:

U-Boot 2013.07 (Jul 05 2018 - 13:33:27)

Your CMDline is:

console=ttyS1,115200n8 mem=104M@0x0 ispmem=8M@0x6800000 rmem=16M@0x7000000 init=/linuxrc rootfstype=squashfs root=/dev/mtdblock2 rw mtdparts=jz_sfc:256k(boot),2048k(kernel),3392k(root),640k(driver),4736k(appfs),2048k(backupk),640k(backupd),2048k(backupa),256k(config),256k(para),-(flag)

**SD Card**
SanDisk High Endurance 32 GB MicroSDHC Card, Up to 100 MB/s Read and 40 MB/s Write

**Note**
The device is on reliability testing and is not currently employed for monitoring.

**Comment by ex725** [comment]
I have the same problem.
the camera cannot be reached for a certain amount of time after starting the recording.
It is necessary to pull the plug and plug it in.

**Comment by rudders** [comment]
Similar issues on two WYZE CAM V2 running latest beta - works fine for a few hours and then the stream stops. haven't done much triage - will try and poke around next time it happens - reboot fixes each time.

**Comment by pascal1n** [comment]
Hello,
same problem here on xiaofang 1S.... 
Stop/Start H264 RTSP   and the video restart...

any idea ?

**Comment by maichai** [comment]
Same here. I need to restart the RTSP server every few hours. 
It is definitely not a problem with a particular client, all my clients experience the same problem: VLC, HASS.io, Shinobi Pro.
Is a solution already in the pipeline?

Model | Xiaomi Xiaofang 1S
-- | --
Firmware date | 2020-06-21T08:01:00Z
Firmware branch | beta
Firmware commit | cbace4f ( No update available)
Kernel Version | #32 PREEMPT Wed Jan 24 02:40:56 CST 2018
Bootloader Version | U-Boot 2013.07 (Jul 05 2018 - 17:59:02)

**Comment by jmtatsch** [comment]
Yeah, this is annoying.
Anything in your logs?
After how many hours does it happen?
Can you watch if memory overflows?

**Comment by maglub** [comment]
On my Xaifang 1S, I cannot even get it to start serving rtsp over h264.

I am on the BETA, hash 535065ff4d85668c1661fe2acaf9900c02ab5c0f

My 1S seems to have 64MB RAM, MAC address 44.23.7C.E8.18.08

I suspect we are running out of RAM, and the rtsp server just dies, and the kernel is just killing off processes.

When this happens, I see no particular log entries about it. The processes are just gone.

**Comment by kiwi-cam** [comment]
@maglub I've got the same model. I've had some success after [enabling swap](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/fd5219100fdccdc3a854dc9bb01c590b3a40c206/firmware_mod/config/swap.conf.dist). I set both to true.

**Comment by MrAndersonMD** [comment]
h264 rtsp server  stops sending video. I enabled swap at swap.conf, but that didn't solved it. It seems that process crashes but it's not restarted even it's configured to autorun.

**Comment by machineglow** [comment]
I have a few wyzecam pans that seem to be exhibiting this behaviour after running fine for over a year.  A reboot helps but eventually, I'll notice rtsp h264 service is stopped on the camera.  

I'm on the 2c2990b build and I'd say this behaviour started for me maybe only 2-3 weeks ago.  

Any advice?

**Comment by MrAndersonMD** [comment]
Same build 2c2990b here. Never used this hack before. Rebooting solves the problem just for some minutes.

Looking on Information - Logs - Process List, it seems rtsp server process gets killed for some reason.

In my case this is the process running after reboot.

`282 root      0:30 /system/sdcard/bin/v4l2rtspserver-master -W1280 -H720 -A -r 2 -F 25 -P 8554`

After some minutes, process is gone.

Can it be 'croned' to be restarted when killed?

**Comment by MrAndersonMD** [comment]
Checking Homebridge logs, I got something that may bring a clue...

`[8/16/2020, 8:36:14 PM] [Camera FFmpeg] [Cámara Comedor] [error] rtsp://192.168.1.100:8554/unicast: Connection refused
[8/16/2020, 8:36:14 PM] [Camera FFmpeg] [Cámara Comedor] 
[8/16/2020, 8:36:14 PM] [Camera FFmpeg] [Cámara Comedor] ffmpeg exited with code: 1 and signal: null (Error)
[8/16/2020, 8:36:14 PM] [Camera FFmpeg] [Cámara Comedor] Stopped video stream.`

Maybe is something related to FFmpeg plugin instead of this plugin?

**Comment by MrAndersonMD** [comment]
Checking every time rtsp stops working, at System menu, then Services, rtsp service stops, don't know why, and even it's set to autorun, doesn't get restarted automatically.

There's a script for that should restart rtsp service, but is not working

`#!/bin/sh
PIDFILE="/run/v4l2rtspserver-master-h264.pid"
export LD_LIBRARY_PATH='/system/sdcard/lib/:/thirdlib:/system/lib'

if [ ! -f /system/sdcard/config/rtspserver.conf ]; then
  cp /system/sdcard/config/rtspserver.conf.dist /system/sdcard/config/rtspserver.conf
fi

if [ -f /system/sdcard/config/rtspserver.conf ]; then
  . /system/sdcard/config/rtspserver.conf
fi

if [ "$LOG" != true ] ; then
  LOGPATH="/dev/null"
fi

if [ -f /system/sdcard/config/osd.conf ]; then
  . /system/sdcard/config/osd.conf 2>/dev/null
fi

status()
{
  pid="$(cat "$PIDFILE" 2>/dev/null)"
  if [ "$pid" ]; then
    # return current pid if pidfile exists and contained pid is alive
    # return 1 if pidfile existed but the contained pid is dead
    kill -0 "$pid" >/dev/null && echo "PID: $pid" || return 1
  else
    # return 2 if pidfile did not exist
    return 2
  fi
}

start()
{
  if [ "$(status)" != "" ]; then
    echo "A v4l2rtspserver is already running, please stop it or reboot"
  else
    echo "Starting v4l2rtspserver-master"
    /system/sdcard/controlscripts/rtsp-mjpeg stop

    ## Configure OSD
    if [ -f /system/sdcard/controlscripts/configureOsd ]; then
      . /system/sdcard/controlscripts/configureOsd  2>/dev/null
    fi

    ## Configure Motion
    if [ -f /system/sdcard/controlscripts/configureMotion ]; then
      . /system/sdcard/controlscripts/configureMotion  2>/dev/null
    fi
    ## Bitrate
    /system/sdcard/bin/setconf -k b -v ${BITRATE} 2>/dev/null

    ## Framerate
    if [ "$FRAMERATE_DEN" != "" ] && [ "$FRAMERATE_NUM" != "" ]; then
        /system/sdcard/bin/setconf -k d -v "$FRAMERATE_NUM,$FRAMERATE_DEN" 2>/dev/null
    fi

    ## Audio
    if [ "$AUDIOFORMAT" != "OFF" ] ; then
        AUDIOPARAM="-E $AUDIOFORMAT:$AUDIOINBR:$AUDIOOUTBR"
        /system/sdcard/bin/setconf -k h -v "$HWVOLUME" 2>/dev/null
        /system/sdcard/bin/setconf -k i -v "$SWVOLUME" 2>/dev/null
        /system/sdcard/bin/setconf -k q -v "$FILTER" 2>/dev/null
        /system/sdcard/bin/setconf -k l -v "$HIGHPASSFILTER" 2>/dev/null
        /system/sdcard/bin/setconf -k a -v "$AECFILTER" 2>/dev/null
    else
        AUDIOPARAM="-A"
    fi

    ## Video format
    if [ "$VIDEOFORMAT" != "" ]; then
	    VIDEOFORMAT="-r $VIDEOFORMAT -F $FRAMERATE_NUM"
    fi

    ## UserName and password
    if [ "$USERNAME" != "" ]; then
        CREDENTIAL="-U $USERNAME:$USERPASSWORD"
    fi

    ## Port
    if [ "$PORT" != "" ]; then
        PORT="-P $PORT"
    fi

    ## Multicast
    if [ "$MULTICASTDEST" != "" ]; then
        MULTICASTDEST="-M $MULTICASTDEST"
    fi

    ## FLIP
    if [ "$FLIP" == "ON" ]; then
        /system/sdcard/bin/setconf -k f -v 1
    elif [ "$FLIP" == "OFF" ]; then
        /system/sdcard/bin/setconf -k f -v 0
    fi

    echo "================== START ===============" >> "$LOGPATH"
    echo "/system/sdcard/bin/v4l2rtspserver-master $RTSPH264OPTS $AUDIOPARAM $VIDEOFORMAT $CREDENTIAL $PORT $MULTICASTDEST" >> "$LOGPATH"
    cd /system/sdcard/hls
    /system/sdcard/bin/v4l2rtspserver-master $RTSPH264OPTS $AUDIOPARAM $VIDEOFORMAT $CREDENTIAL $PORT $MULTICASTDEST 2>> "$LOGPATH" >> "$LOGPATH" &
    echo "$!" > "$PIDFILE"
  fi
}

stop()
{
  pid="$(cat "$PIDFILE" 2>/dev/null)"
  if [ "$pid" ]; then
    kill "$pid"
    rm "$PIDFILE" 1> /dev/null 2>&1
  fi
}

if [ $# -eq 0 ]; then
  start
else
  case $1 in start|stop|status)
    $1
    ;;
  esac
fi`

Please, someone can fix it?

**Comment by mjrider** [comment]
autorun is afaik only if it is started when the device is started, not that it restarts when the rtsp server crashes

**Comment by machineglow** [comment]
I've resorted to rebooting my cameras every 3 hours.  that seems to be working.   Hopefully the stealth rtsp death can be resolved.
