### ISSUE TITLE
Add 'update available' sensor via mqtt?

### ISSUE THREAD

**Issue by SAOPP** [EliasKotlyar/Xiaomi-Dafang-Hacks#1436]
Hi!

Guys, it's possible to add sensor for current updates for hack? I mean sensor via mqtt to Home Assistant.

**Comment by gadget78** [comment]
what sensor did you want to add ?? .. 

ive been adding the option of audio play buttons :) (so HA can play alarms, doorbel chimes etc)
you would need to edit.update/change the mqtt-autodiscovery.sh file in controlscripts... 

oddly this has gone wrong.. not sure it was me or latest beta update ??.. 
ive even reverted all file i altered back, but still seems faulty ? i must of missed something :( 
as i know get 
```
Error: Unknown option 'homeassistant/binary_sensor/camera/motion/config'.

Use 'mosquitto_pub --help' to see usage.
Error: Unknown option 'homeassistant/switch/camera/motion_detection/config'.
```
when its ran... and mqtt_control wont run ...
