### ISSUE TITLE
lighttpd HTTP error 500 after update (Xiaofang 1S)

### ISSUE THREAD

**Issue by adamast0r** [EliasKotlyar/Xiaomi-Dafang-Hacks#1444]
I have updated today to the last version of GIT and now it seems that the webinterface will not start:
"500 Internal Server Error"

From the update.log:
```
Starting AutoUpdate on branch master
Forcing update.
Need to upgrade from c65614a to 4a64c49
Getting list of remote files.
Number of file to update 5
autoupdate.sh updated.
config/motion.conf.dist updated.
www/cgi-bin/status_overview.cgi updated.
www/index.html updated.
www/scripts/index.html.js updated.
```

Nothing relevant from the lighttpd logs, however I can confirm that lighttpd is running:
` 204     1 root     S     5060 14.3   0  0.0 /system/sdcard/bin/lighttpd.bin -f /system/sdcard/config/lighttpd.conf`

I have some errors on Dmesg but not sure if they are relevant for this problem:

```
[ 1020.865141] mmcblk0p1: rw=1, want=2786576, limit=2097152
[ 1020.880147] attempt to access beyond end of device
[ 1020.893169] mmcblk0p1: rw=1, want=2786704, limit=2097152
[ 1020.898811] attempt to access beyond end of device
[ 1020.919623] mmcblk0p1: rw=1, want=2786832, limit=2097152
[ 1020.946429] attempt to access beyond end of device
[ 1020.956151] mmcblk0p1: rw=1, want=2786960, limit=2097152
[ 1020.984457] attempt to access beyond end of device
[ 1021.014711] mmcblk0p1: rw=1, want=2787088, limit=2097152
[ 1021.051740] attempt to access beyond end of device
[ 1021.087567] mmcblk0p1: rw=1, want=2787216, limit=2097152
[ 1021.096500] attempt to access beyond end of device
[ 1021.109962] mmcblk0p1: rw=1, want=2787344, limit=2097152
[ 1021.120115] attempt to access beyond end of device
[ 1021.129928] mmcblk0p1: rw=1, want=2787472, limit=2097152
```

**Comment by jmtatsch** [comment]
Looks like you filesystem might be corrupted. Better start fresh.

**Comment by adamast0r** [comment]
just noticed that when I run it directly I get:

[root@Dafang_Xiaomi:log]# /system/sdcard/bin/lighttpd.bin -f /system/sdcard/config/lighttpd.conf
/system/sdcard/bin/lighttpd.bin: can't load library 'libssl.so.48'

Is this normal?

**Comment by jmtatsch** [comment]
Need to have that lib on the path. look at /system/sdcard/bin/lighttpd

**Comment by adamast0r** [comment]
it seems that the problem might be related with the card!
