### ISSUE TITLE
Adapting RTSP server to a noname camera with Ingenic T10

### ISSUE THREAD

**Issue by didkivskyy** [EliasKotlyar/Xiaomi-Dafang-Hacks#1448]
Hello,

Thanks for a great project and repo you maintain!

I'm trying to adapt the code and experience from your project for my case.

### My camera:
**SOC:** Ingenic T10
**Sensor:** jxh42
**RAM:** 64M
**Flash:** 8M
**Network:** ethernet
**NO MMC slot !**
**UART pins on the board**
**Linux:** 3.10.14
**gcc:** 4.7.2 (Ingenic r2.3.3 2016.12)
**Board name:** Mango

Photo (sorry for bad quality):
![image](https://user-images.githubusercontent.com/12132936/82918110-eda50f00-9f7c-11ea-8461-4fbd7aa78c58.png)
![image](https://user-images.githubusercontent.com/12132936/82918170-0281a280-9f7d-11ea-801f-bf20de893704.png)
Similar board from the net (better photo):
![image](https://user-images.githubusercontent.com/12132936/82918456-6dcb7480-9f7d-11ea-9be3-93cce032f4c3.png)

Stock software is working well in terms of image/video-streaming and even some basic ONVIF communication. I am not happy that it is always trying to connect to Chinese clouds and stream video over there. I was able to check it when connecting to the cloud from an Android app.
So far I fight cloud connections with router firewall that forbids every outbound traffic from the camera.

I am able to telnet to the camera with root access. So the very first I did - dumped flash images to backup files.

I have several problems with adapting CFW and other software for such cameras:
- Firmwares are made to be loaded from SD card while my camera has no slot
- Size. Even if I want to write images to NOR flash I still can't fit them

### What I have tried so far

1. Unpacking CFW rootfs image with scripts from this repo, shrink it a bit to fit into flash and pack back.
I tried to flash repacked image from running camera with no success. Had to connect via UART to stop boot process. Used TFTD to get new images and write them to the flash.
Result: Kernel panic.
2. So I decided to write new kernel as well.
Result: kernel could not find partitions and boot.
3. Compiled v4l2rtspserver, carrier-rtsp-server and other sample applications to test working with the sensor. Used toolchain from Ingenic-T10-T20-SDK-3.9.0.
I've uploaded binaries via FTP and tried running them along with stock software and/or after killing stock apps.
Result: all of apps are failing with different errors (either ISP specific errors or Segmentation fault). No video streams or snapshots taken.
4. Tweaking original rootfs and appfs.
Binwalked images and removed some stock apps at startup while including compiled binaries described in 3.
Result: similar to 3.
5. Compiling sensor drivers from SDK and using them with compiled binaries.
Result: similar to 3.

I've spent most of the time trying to launch v4l2rtspserver with some useful results. My idea was to change sensor and stream parameters in the code to those used by stock app.
It is named **sctrl**. It looks like an awful compilation of everything authors wanted to be in the camera: sensor settings, RTSP streaming, ONVIF communication, communication with DVRs, proprietary management protocol, streaming to cloud, serving some webinterface requests and more. This is a single file which makes it impossible to disable unwanted functionality. No visible configuration to achieve this either.  
Some of the code for sure was taken from this repo (or its variants):
[https://github.com/linuxmap/wstv](https://github.com/linuxmap/wstv)
At least they share many similarities but still **sctrl** has many different parts which is bad for my efforts.
I had to reverse engineer a lot to understand how **ISVP** (Ingenic Smart Video Platform) is used originally. Looking at logs and disassembling the app gave me sensor/encoder parameters which I am pretty confident in:

`IMP_FrameSource_SetChnAttr for channel 0`
`1280x720, crop (0,0,1280,720), no scaler, pixFmt = PIX_FMT_NV12, frame rate = 25/1, nrVBs = 3` 
`IMPEncoderCHNAttr for channel 0`
`enType = PT_H264, CBR, bitrate=1680, maxQp = 38, minQp = 15, gop=50`

sctrl also starts a second channel which is downscaled to 640x480 but I never get that far because my code stops with error at 1st chan.
Framesource channel is created but calling **IMP_Encoder_CreateChn** raises different errors.
For now I've switched OSD, motion and audio off.
I've started with the code for ISVP SDK 3.12 but when analyzing sctrl disassembly I've figured that structures are different because **sctrl** used SDK 3.7 (couldn't find this SDK online). I've compared 
**imp_encoder.h** (which refers to libimp.so) and found that SDK 3.9 is identical for these structures. So I've tried code and libraries from different SDK versions. With no success :(
The most often result I get (logcat from ISP log):

> D/Sample-Common(22801): sample_system_init start
> D/IMP-ISP (22801): ~~~~~~ IMP_ISP_Open[120] ~~~~~~~
> D/System  (22801): IMP_System_Init SDK Version:3.9.0 built: Dec  9 2016 17:09:39
> D/System  (22801): system_init()
> D/System  (22801): Calling DSystem
> D/System  (22801): Calling FrameSource
> D/System  (22801): [ignored]read /proc/cpuinfo ret is NULL
> D/System  (22801): Calling IVS
> D/System  (22801): Calling OSD
> I/Alloc Manager(22801): MEM Alloc Method is kmalloc
> D/KMEM Method(22801): CMD Line Rmem Size:16777216, Addr:0x03000000
> D/KMEM Method(22801): alloc->mem_alloc.method = kmalloc
> D/KMEM Method(22801):  			alloc->mem_alloc.vaddr = 0x75dc1000
> D/KMEM Method(22801):  			alloc->mem_alloc.paddr = 0x03000000
> D/KMEM Method(22801):  			alloc->mem_alloc.length = 16777216
> I/Alloc Manager(22801): MEM Manager Method is continuous
> D/System  (22801): Calling Encoder
> D/System  (22801): Calling Decoder
> D/Sample-Common(22801): ImpSystemInit success
> E/Encoder (22801): Channel buffer alloc failed
> E/Encoder (22801): Channel0 stream buffer init failed
> E/Sample-Common(22801): IMP_Encoder_CreateChn(0) error !
> E/Sample-Encoder-h264(22801): Encoder init failed

Depending on code/libimp.so version used it may differ a little with similar error on stdout (sometimes followed by Segmentation fault).

**Could you please point what I am possibly doing wrong and what could I try to successfully launch RTSP server on my camera?**

This is already a lot of info so please tell me if anything is still worth posting here.

Thanks a lot!

### Basic logs/config files
* /proc/cmdline
`console=ttyS1,115200n8 mem=43M@0x0 ispmem=5M@0x2B00000 rmem=16M@0x3000000 init=/                                                                             linuxrc rootfstype=squashfs root=/dev/mtdblock3 rw mtdparts=jz_sfc:256k(boot),
	3584k(appfs),2048k(kernel),1728k(root),64k(hwconfig),512k(config)
`

* /proc/mtd

> dev:    size   erasesize  name
> mtd0: 00040000 00008000 "boot"
> mtd1: 00380000 00008000 "appfs"
> mtd2: 00200000 00008000 "kernel"
> mtd3: 001b0000 00008000 "root"
> mtd4: 00010000 00008000 "hwconfig"
> mtd5: 00080000 00008000 "config"

* mount

> rootfs on / type rootfs (rw)
> /dev/root on / type squashfs (ro,relatime)
> proc on /proc type proc (rw,relatime)
> sysfs on /sys type sysfs (rw,relatime)
> tmpfs on /dev type tmpfs (rw,relatime)
> tmpfs on /tmp type tmpfs (rw,relatime)
> tmpfs on /var type tmpfs (rw,relatime)
> devpts on /dev/pts type devpts (rw,relatime,mode=600,ptmxmode=000)
> /dev/mtdblock1 on /tmp/appfs type squashfs (ro,relatime)
> /dev/mtdblock1 on /progs type squashfs (ro,relatime)
> /dev/mtdblock1 on /home type squashfs (ro,relatime)
> tmpfs on /etc type tmpfs (rw,relatime)
> tmpfs on /progs/rec type tmpfs (rw,relatime)
> /dev/mtdblock5 on /etc/conf.d type jffs2 (rw,relatime)
> tmpfs on /progs/html/cgi-bin/snapshot type tmpfs (rw,relatime)

### Specific logs/config files
* /etc/jovision.cfg
> product=JVS-INGT10
> firmup-url=http://updatewt.afdvr.com/ipcsw/ingt10
> firmup-url=http://updatedx.afdvr.com/ipcsw/ingt10
> firmup-url=http://updatehw.afdvr.com/ipcsw/ingt10
> firmup-binName=jvsingT10.bin
> firmup-verName=jvsingT10-ver.bin

_Links above are dead._

* /etc/conf.d/fixed/hwconfig.cfg
> #hwconfig 1.0
> product=INGT10
> cut-check=2_18
> cut-day=0_25
> cut-night=0_26
> redlight=2_17

* dmesg
> [    0.000000] Initializing cgroup subsys cpu
> [    0.000000] Initializing cgroup subsys cpuacct
> [    0.000000] Linux version 3.10.14 (devil@ubuntu) (gcc version 4.7.2 (Ingenic r2.3.3 2016.12) ) #1 PREEMPT Thu Jan 5 10:52:33 CST 2017
> [    0.000000] bootconsole [early0] enabled
> [    0.000000] CPU0 RESET ERROR PC:801B5E00
> [    0.000000] [<801b5e00>] 0x801b5e00
> [    0.000000] CPU0 revision is: 00d00100 (Ingenic Xburst)
> [    0.000000] FPU revision is: 00b70000
> [    0.000000] cgu_get_rate, parent = 712704000, rate = 0, m = 0, n = 0, reg val = 0x000020ff
> [    0.000000] CCLK:712MHz L2CLK:356Mhz H0CLK:200MHz H2CLK:200Mhz PCLK:100Mhz
> [    0.000000] Determined physical RAM map:
> [    0.000000]  memory: 00439000 @ 00010000 (usable)
> [    0.000000]  memory: 00037000 @ 00449000 (usable after init)
> [    0.000000] User-defined physical RAM map:
> [    0.000000]  memory: 02b00000 @ 00000000 (usable)
> [    0.000000] Zone ranges:
> [    0.000000]   Normal   [mem 0x00000000-0x02afffff]
> [    0.000000] Movable zone start for each node
> [    0.000000] Early memory node ranges
> [    0.000000]   node   0: [mem 0x00000000-0x02afffff]
> [    0.000000] On node 0 totalpages: 11008
> [    0.000000] free_area_init_node: node 0, pgdat 804467c0, node_mem_map 81000000
> [    0.000000]   Normal zone: 86 pages used for memmap
> [    0.000000]   Normal zone: 0 pages reserved
> [    0.000000]   Normal zone: 11008 pages, LIFO batch:1
> [    0.000000] Primary instruction cache 32kB, 8-way, VIPT, linesize 32 bytes.
> [    0.000000] Primary data cache 32kB, 8-way, VIPT, no aliases, linesize 32 bytes
> [    0.000000] pls check processor_id[0x00d00100],sc_jz not support!
> [    0.000000] MIPS secondary cache 128kB, 8-way, linesize 32 bytes.
> [    0.000000] pcpu-alloc: s0 r0 d32768 u32768 alloc=1*32768
> [    0.000000] pcpu-alloc: [0] 0
> [    0.000000] Built 1 zonelists in Zone order, mobility grouping off.  Total pages: 10922
> [    0.000000] Kernel command line: console=ttyS1,115200n8 mem=43M@0x0 ispmem=5M@0x2B00000 rmem=16M@0x3000000 init=/linuxrc rootfstype=squashfs root=/dev/mtdblock3 rw mtdparts=jz_sfc:256k(boot),3584k(appfs),2048k(kernel),1728k(root),64k(hwconfig),512k(config)
> [    0.000000] PID hash table entries: 256 (order: -2, 1024 bytes)
> [    0.000000] Dentry cache hash table entries: 8192 (order: 3, 32768 bytes)
> [    0.000000] Inode-cache hash table entries: 4096 (order: 2, 16384 bytes)
> [    0.000000] Memory: 38424k/44032k available (3658k kernel code, 5608k reserved, 665k data, 220k init, 0k highmem)
> [    0.000000] SLUB: HWalign=32, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
> [    0.000000] Preemptible hierarchical RCU implementation.
> [    0.000000] NR_IRQS:418
> [    0.000000] clockevents_config_and_register success.
> [    0.000028] Calibrating delay loop... 709.42 BogoMIPS (lpj=3547136)
> [    0.057700] pid_max: default: 32768 minimum: 301
> [    0.062753] Mount-cache hash table entries: 512
> [    0.067984] Initializing cgroup subsys debug
> [    0.072252] Initializing cgroup subsys freezer
> [    0.079779] regulator-dummy: no parameters
> [    0.084062] NET: Registered protocol family 16
> [    0.094292] bio: create slab <bio-0> at 0
> [    0.101221] jz-dma jz-dma: JZ SoC DMA initialized
> [    0.106460] usbcore: registered new interface driver usbfs
> [    0.112004] usbcore: registered new interface driver hub
> [    0.117524] usbcore: registered new device driver usb
> [    0.122809] i2c-gpio i2c-gpio.0: using pins 12 (SDA) and 13 (SCL)
> [    0.129091] i2c-gpio i2c-gpio.1: using pins 57 (SDA) and 58 (SCL)
> [    0.135259] media: Linux media interface: v0.10
> [    0.139835] Linux video capture interface: v2.00
> [    0.147062] Switching to clocksource jz_clocksource
> [    0.152754] jz-dwc2 jz-dwc2: cgu clk gate get error
> [    0.157746] cfg80211: Calling CRDA to update world regulatory domain
> [    0.164180] jz-dwc2 jz-dwc2: regulator vbus get error
> [    0.169317] DWC IN OTG MODE
> [    0.323504] sft id =========================off
> [    0.328137] dwc2 dwc2: Keep PHY ON
> [    0.331511] dwc2 dwc2: Using Buffer DMA mode
> [    0.535124] dwc2 dwc2: Core Release: 3.00a
> [    0.539240] dwc2 dwc2: DesignWare USB2.0 High-Speed Host Controller
> [    0.545594] dwc2 dwc2: new USB bus registered, assigned bus number 1
> [    0.553160] hub 1-0:1.0: USB hub found
> [    0.556961] hub 1-0:1.0: 1 port detected
> [    0.561055] dwc2 dwc2: DWC2 Host Initialized
> [    0.565636] NET: Registered protocol family 2
> [    0.570713] TCP established hash table entries: 512 (order: 0, 4096 bytes)
> [    0.577689] TCP bind hash table entries: 512 (order: -1, 2048 bytes)
> [    0.584078] TCP: Hash tables configured (established 512 bind 512)
> [    0.590414] TCP: reno registered
> [    0.593616] UDP hash table entries: 256 (order: 0, 4096 bytes)
> [    0.599568] UDP-Lite hash table entries: 256 (order: 0, 4096 bytes)
> [    0.606246] NET: Registered protocol family 1
> [    0.610998] RPC: Registered named UNIX socket transport module.
> [    0.617006] RPC: Registered udp transport module.
> [    0.621702] RPC: Registered tcp transport module.
> [    0.626482] RPC: Registered tcp NFSv4.1 backchannel transport module.
> [    0.633526] freq_udelay_jiffys[0].max_num = 10
> [    0.637997] cpufreq  udelay  loops_per_jiffy
> [    0.642386] dwc2 dwc2: ID PIN CHANGED!
> [    0.646217] init DWC as A_HOST
> [    0.649291] 12000     59724   59724
> [    0.652526] 24000     119448  119448
> [    0.656104] 60000     298620  298620
> [    0.659476] 120000    597241  597241
> [    0.663006] 200000    995402  995402
> [    0.666656] 300000    1493103         1493103
> [    0.670291] 600000    2986206         2986206
> [    0.673998] 792000    3941793         3941793
> [    0.677730] 1008000   5016827         5016827
> [    0.681503] 1200000   5972413         5972413
> [    0.691881] squashfs: version 4.0 (2009/01/31) Phillip Lougher
> [    0.699004] jffs2: version 2.2. © 2001-2006 Red Hat, Inc.
> [    0.704971] msgmni has been set to 75
> [    0.710413] io scheduler noop registered
> [    0.714361] io scheduler cfq registered (default)
> [    0.721309] jz-uart.1: ttyS1 at MMIO 0x10031000 (irq = 58) is a uart1
> [    0.729967] console [ttyS1] enabled, bootconsole disabled
> [    0.746249] brd: module loaded
> [    0.751895] loop: module loaded
> [    0.755509] logger: created 256K log 'log_main'
> [    0.760935] jz SADC driver registeres over!
> [    0.766582] jz TCU driver register completed
> [    0.771561] the id code = 1c7017, the flash name is EN25QH64
> [    0.777455] JZ SFC Controller for SFC channel 0 driver register
> [    0.783577] 6 cmdlinepart partitions found on MTD device jz_sfc
> [    0.789713] Creating 6 MTD partitions on "jz_sfc":
> [    0.794654] 0x000000000000-0x000000040000 : "boot"
> [    0.800301] 0x000000040000-0x0000003c0000 : "appfs"
> [    0.806021] 0x0000003c0000-0x0000005c0000 : "kernel"
> [    0.811751] 0x0000005c0000-0x000000770000 : "root"
> [    0.817401] 0x000000770000-0x000000780000 : "hwconfig"
> [    0.823355] 0x000000780000-0x000000800000 : "config"
> [    0.829169] SPI NOR MTD LOAD OK
> [    0.832495] tun: Universal TUN/TAP device driver, 1.6
> [    0.837735] tun: (C) 1999-2004 Max Krasnyansky <maxk@qualcomm.com>
> [    0.844232] Bus Mode Reg after reset: 0x00020101, cnt=0
> [    0.853433] libphy: jz_mii_bus: probed
> [    0.857480] =======>gmacdev = 0x821f1980<================
> [    0.863041] =========>gmacdev->MacBase = 0xb34b0000 DmaBase = 0xb34b1000
> [    0.869993] Bus Mode Reg after reset: 0x00020101, cnt=0
> [    0.877099] jz_mac jz_mac.0: JZ on-chip Ethernet MAC driver, Version 1.0
> [    0.884155] usbcore: registered new interface driver zd1201
> [    0.890391] jzmmc_v1.2 jzmmc_v1.2.0: vmmc regulator missing
> [    0.905089] jzmmc_v1.2 jzmmc_v1.2.0: card inserted, state=0
> [    0.935073] jzmmc_v1.2 jzmmc_v1.2.0: register success!
> [    0.940465] ------------ init codec driver start!
> [    0.945407] jz_codec_probe: probe() start
> [    0.949543] jz_codec_probe, codec iomem is :0xb0021000
> [    0.954830] jz_codec_probe: probe() done
> [    0.958979] i2s global init
> [    0.961871] current codec is :82203380
> [    0.966037] cgu_set_rate, parent = 712704000, rate = 2048000, n = 348, reg val = 0x0000215c
> [    0.966056] i2s_global_init, i2s clk rate is 2048000
> [    0.966070] cgu_enable,cgu_i2s reg val = 0x2000215c
> [    0.966087] i2s init success.
> [    1.395836] TCP: cubic registered
> [    1.399267] NET: Registered protocol family 17
> [    1.405122] input: gpio-keys as /devices/platform/gpio-keys/input/input0
> [    1.412290] drivers/rtc/hctosys.c: unable to open rtc device (rtc0)
> [    1.424851] VFS: Mounted root (squashfs filesystem) readonly on device 31:3.
> [    1.432748] Freeing unused kernel memory: 220K (80449000 - 80480000)
> [    1.755357] dwc2 dwc2:  ++OTG Interrupt: A-Device Timeout Change++
> [    3.257811] register all isp device successfully!
> [    3.269062] @@@@ tx-isp-probe ok @@@@@
> [    3.342669] at24 1-0050: 2048 byte 24c02 EEPROM, writable, 16 bytes/write
> [    3.371184] Bus Mode Reg after reset: 0x00020101, cnt=0
> [    5.423669] name : i2c-gpio0 nr : 0
> [    5.487957]  sensor_read: addr=0xa value = 0xa0
> [    5.553338] error: sensor_read,144 ret = -6
> [    5.557688]  sensor_read: addr=0x300a value = 0x0
> [    5.562533] err sensor read addr = 0x300a, value = 0x0
> [    5.628537] error: sensor_read,144 ret = -6
> [    5.632845]  sensor_read: addr=0x300b value = 0x0
> [    5.637704] err sensor read addr = 0x300b, value = 0x0
> [    5.703558]  sensor_read: addr=0xa value = 0xa0
> [    5.708944]  sensor_read: addr=0xb value = 0x42
> [    5.714314]  sensor_read: addr=0x9 value = 0x81
> [    5.718995] info: success sensor find : jxh42
> [    5.723484] name : i2c-gpio1 nr : 1
> [    5.727173] misc sinfo_release
> [    5.794590] set sensor gpio as PA-low-10bit
> [    5.824241] jxh42 0-0030: jxh42 chip found @ 0x30 (i2c-gpio0)
> [    5.830206] tx_isp: Registered sensor subdevice jxh42 0-0030
> [    5.875242] libphy: 0:00 - Link is Up - 100/Full
> [    5.941520] jxh42 stream on
> [    5.944481] ###### image_tuning_v4l2_open 3770 #######
> [    6.995594] dma dma0chan24: Channel 24 have been requested.(phy id 7,type 0x06 desc a158a000)
> [    7.009256] ------ come to i2s_enable
> [    7.013128] cgu_set_rate, parent = 712704000, rate = 11289600, n = 63, reg val = 0x2000203f
> [    7.013142] i2s_set_rate, i2s clk rate is 11289600
> [    7.013154] codec_codec_ctl: set sample rate...
> [    7.013166] dp->filter convert_16bits_stereo2mono
> [    7.018504] codec_codec_ctl: set device...
> [    7.018523] codec_set_device 13
> [    7.021846] codec_set_device: set device: MIC...
> [    7.425797] cgu_set_rate, parent = 712704000, rate = 2048000, n = 348, reg val = 0x2000215c
> [    7.425820] i2s_set_rate, i2s clk rate is 2048000
> [    7.425833] codec_codec_ctl: set sample rate...
> [    7.445888] dma dma0chan25: Channel 25 have been requested.(phy id 6,type 0x06 desc a15ae000)
> [    7.456658] codec_codec_ctl: set repaly channel...
> [    7.456685] cgu_set_rate, parent = 712704000, rate = 11289600, n = 63, reg val = 0x2000203f
> [    7.456698] i2s_set_rate, i2s clk rate is 11289600
> [    7.456710] codec_codec_ctl: set sample rate...
> [    7.459328] codec_codec_ctl: set device...
> [    7.459346] codec_set_device 4
> [    7.697177] codec_set_device: set device: speaker...
> [    7.703111] cgu_set_rate, parent = 712704000, rate = 2048000, n = 348, reg val = 0x2000215c
> [    7.703127] i2s_set_rate, i2s clk rate is 2048000
> [    7.703141] codec_codec_ctl: set sample rate...
> [    7.703570] codec_codec_ctl: set repaly channel...
> [    7.704389] codec_set_play_volume 294: codec set play volume = 0x1c
> [    7.959081] &&& chan0  scaler.max_width = 0 max_height = 0  min_width = 0 min_height = 0 &&&
> [    8.133009] &&& chan1  scaler.max_width = 640 max_height = 480  min_width = 128 min_height = 128 &&&
> [    8.380015] device eth0 entered promiscuous mode
> [    8.440456] eth0: Enter promisc mode!
> [    8.444617] eth0: Enter promisc mode!
> [    8.480091] eth0: Enter promisc mode!
> [   15.568551] eth0: Enter promisc mode!
> [   15.572982] eth0: Enter promisc mode!

* /etc/init.d/rcS
> #!/bin/sh
> 
> runlevel=S
> prevlevel=N
> umask 022
> export runlevel prevlevel
> 
> /bin/hostname
> /bin/mount -a
> 
> #_ create necessary devices
> /bin/mknod /dev/null c 1 3
> /bin/mkdir /dev/pts
> /bin/mount -t devpts devpts /dev/pts
> /bin/mknod /dev/rtc c 10 135
> 
> #_ comment next when you use alsa
> #/bin/mknod /dev/audio c 14 4
> 
> echo /sbin/mdev > /proc/sys/kernel/hotplug
> /sbin/mdev -s && echo "mdev is ok......"
> 
> #get /dev/mtdblockN with mtd name
> getmtd()
> {
>         MTDNAME=$1
>         temp=`grep $MTDNAME /proc/mtd`
>         temp=${temp%%:*}
>         echo ${temp/mtd/\/dev\/mtdblock}
> }
> 
> #mtd1: 00480000 00010000 "appfs"
> APPFS_MTD=`getmtd \"appfs\"`
> echo $APPFS_MTD
> 
> mkdir /tmp/appfs
> mount -t squashfs $APPFS_MTD /tmp/appfs
> mount /tmp/appfs/progs /progs/
> mount /tmp/appfs/home /home
> 
> /home/bashrc.sh

* bashrc.sh
> #! /bin/sh
> 
> mount_as_tmpfs	/etc/
> mount_as_tmpfs	/progs/rec
> 
> rm -rf /etc/sensor
> ln -s /tmp/appfs/sensor /etc/sensor
> 
> export LD_LIBRARY_PATH='/home/libs'
> 
> #get /dev/mtdblockN with mtd name
> getmtd() 
> {
> 	MTDNAME=$1
> 	temp=`grep $MTDNAME /proc/mtd`
> 	temp=${temp%%:*}
> 	echo ${temp/mtd/\/dev\/mtdblock}
> }
> 
> #mtd3: 00080000 00010000 "config"
> CONFIG_MTD=`getmtd \"config\"`
> echo $CONFIG_MTD
> 
> [ -d /etc/conf.d ] || mkdir /etc/conf.d
> mount -t jffs2 $CONFIG_MTD /etc/conf.d/
> [ -d /etc/conf.d/jovision ] || mkdir /etc/conf.d/jovision
> [ -d /etc/conf.d/fixed ] || mkdir /etc/conf.d/fixed
> 
> echo "256000" > /proc/sys/net/core/wmem_default	#500KBÄ¬ÈÏ»º´æ
> echo "512000" > /proc/sys/net/core/wmem_max	#1000KB×î´ó»º´æ
> #echo "512000" > /proc/sys/net/core/rmem_default	#500KBÄ¬ÈÏ»º´æ
> #echo "1024000" > /proc/sys/net/core/rmem_max	#1000KB×î´ó»º´æ
> 
> #ÉèÖÃ±£ÁôÄÚ´æ´óÐ¡
> echo 512 > /proc/sys/vm/min_free_kbytes
> 
> #ÉèÖÃÕ»´óÐ¡
> ulimit -s 4096
> 
> cd /home/ipc_drv
> 
> #default value of SENSOR
> SENSOR=h42
> 
> #set the value of SENSOR
> if [ -f /etc/conf.d/jovision/sensor.sh ] ; then
>     . /etc/conf.d/jovision/sensor.sh
> else
>     echo SENSOR=$SENSOR > /etc/conf.d/jovision/sensor.sh
> fi
> 
> ./loaddrv --${SENSOR}
> 
> #wifi
> [ ! -f /home/wifi/vt9271.ko ] || insmod /home/wifi/vt9271.ko
> [ ! -f /home/wifi/8188eu.ko ] || insmod /home/wifi/8188eu.ko
> if [ -f /home/wifi/mt7601Usta.ko ] ; then
>     insmod /home/wifi/mt7601Usta.ko
> fi
> 
> #setMAC
> if [ -f /etc/conf.d/jovision/network/mac.cfg ] ; then
> 	. /etc/conf.d/jovision/network/mac.cfg
> fi
> 
> #ÅäÖÃÍøÂç²ÎÊý
> /progs/networkcfg.sh
> 
> telnetd&
> hwclock -s -u
> 
> cd /progs
> cp /progs/bin/mySystem /tmp/
> /tmp/mySystem &
> 
> if [ -f /etc/conf.d/startup.sh ] ; then
>     /etc/conf.d/startup.sh
>     exit
> fi
> 
> ./startup.sh &

* sctrl output:
> ./sctrl cmd=[0/1] to enable debug
> ./sctrl log=[LOGLEVEL] to set syslog level
> building date: Apr  7 2017: 18:53:13
> y=2017,m=11,d=6
> ====>>. sensor: 19
> IspInit start
> InitIsp success
> __framesource_init ok
> __encoder_group_init ok
> __osd_group_init ok
> __device_bind ok
> enter night mode...
> enter day mode...
> IMP_ISP_Tuning_SetTemperDnsAttr ret 0
> main start AI and AO
> IMP_AI_SetVol 60 ret with 0
> IMP_AI_SetGain 18 ret with 0
> jv_ai_start success
> IMP_AO_SetVol 60 ret with 0
> IMP_AO_SetGain 28 ret with 0
> jv_ao_start success
> __bSupport_WIFI_check=0
> check inet: static
> mptzosd_init:  af not support!
> No Disk
> zrtsp start......
> dooralarm not support
> Read config file /etc/conf.d/jovision//default/system.cfg failed.
> schedule1  0
> schedule2  0
> sch1TimeStart  6:0
> sch1TimeEnd  18:0
> sch2TimeStart  18:0
> sch2TimeEnd  6:0
> Read config file /etc/conf.d/jovision/glnk.cfg failed.
> IMP_FrameSource_SetChnAttr chn=0, w=1280, h=720, crop(0, 0), ret=0
> i264e[info]: profile Main, level 3.1
> jv_stream_start ok venc=0, w=1280, h=720, fps=25/1, gop=50, bitrate=1680, Qp=[20,38]
> jv_osddrv_create chn=0, handle=0, rgnHandle=0, (812, 4), w=464, h=56
> mprivacy_flush chn=0, enable=0
> IMP_FrameSource_SetChnAttr chn=1, w=640, h=360, ret=0
> i264e[info]: profile Main, level 3.0
> [chn1] scaler->outwidth = 640 scaler->outheight = 360, sscaler.outwidth = 640 sscaler.outheight = 368
> jv_stream_start ok venc=1, w=640, h=480, fps=25/1, gop=50, bitrate=819, Qp=[20,38]
> jv_osddrv_create chn=1, handle=1, rgnHandle=1, (324, 4), w=312, h=40
> mprivacy_flush chn=0, enable=0
> jv_mdetect_stop ok
> jv_osddrv_destroy handle=0, rgnHandle=0
> jv_osddrv_create chn=0, handle=0, rgnHandle=2, (812, 4), w=464, h=56
> jv_osddrv_destroy handle=1, rgnHandle=1
> jv_osddrv_create chn=1, handle=1, rgnHandle=3, (324, 4), w=312, h=40
> IP auto adapt open!
> utl_net_lan_init(266) dev_id :e7b0f3
> Start create MLAN
> IMP_Encoder_SetChnRcAttr(chn 0): fps=25/1, gop=50, bitrate=1680, qp=[20,38], ret with 0
> IMP_Encoder_SetChnRcAttr(chn 1): fps=25/1, gop=50, bitrate=819, qp=[20,38], ret with 0
> mprivacy_flush chn=0, enable=0
> jv_mdetect_stop ok
> move->param.sense[0]=3
> jv_mdetect_start ok
> Failed open /etc/conf.d/jovision/presetpos.cfg, because: No such file or directory
> NO support Af!
> NOt support pu&c!
> jv_sensor_brightness 128
> jv_sensor_contrast 128
> jv_sensor_sharpness 128
> jv_sensor_saturation 128
> new CSWorker = 0
> 
> jvserver************v2.0.80.8[private:v2.0.79.14 20160706.1]  (build 2017-4-5 3:52:49)
> ================ Init YST first ok(SQ412748458).
> ###_ tinyonvif built: Oct 14 2016: 19:16:03
> ovdistar
> ipc sdk dll loading error.
> ======NET_DVR_PICCFG_V40: 12d54,37c,1e48
> RAW_PROTOCOL
> ===ov pid:787
> restart here:  connection: 0
> my 192.168.1.140,255.255.255.0,192.168.1.1
> [DBG]_________[exxm_init: 166]
> exsdk ok!
> gp.bRunning=1
> watchdog enabled, timeout=30
> client IP is 127.0.0.1, port is 36712
> content is : 'websnapshot' '1' 'snapshot'
> jv_snapshot_get_ex: vencChn=3, width=720, height=576
> **************set net to eth0**************
> set net card eth0
> JVN_SetLocalNetCard eth0
> _ipcinfo_ntp_thread(681) : start ntp time ntp.fudan.edu.cn
> Trun to DayMode...
> enter day mode...
> set isp fps 25/1, ret 0
> Уʱ▒ɹ▒
> 15 s has gone
> ovdistop
> join ok.
> ovdistar
> I am master run!
> mdetect delay start timer
> client IP is 127.0.0.1, port is 58016
> content is : 'websnapshot' '1' 'snapshot'
> jv_snapshot_get_ex: vencChn=3, width=720, height=576
> client IP is 127.0.0.1, port is 39131
> content is : 'websnapshot' '1' 'snapshot'
> jv_snapshot_get_ex: vencChn=3, width=720, height=576

**Comment by nik0** [comment]
Hi,
Nice analysis.
What I could suggest:
- What does lsmod says on the stock firmware ?
- Try to compile the RSTP server with the stock firmware of: libalog.so, libimp.so, libsysutils.so
- What is the result of logcat after you tried to start the server ?

Nik0

**Comment by brainstorm** [comment]
@didkivskyy Try again with OpenIPC, I've got very good results (working and de-clouded camera) with it right now. My camera's board has a very similar layout and has the Ingenic T10 too.
