### ISSUE TITLE
Duration of video clips

### ISSUE THREAD

**Issue by avdelco** [EliasKotlyar/Xiaomi-Dafang-Hacks#145]
Hello,
Sorry if this is already answered, but is there a way to increase the default 1 minute duration of the clips, when using the Xiaomi-Dafang camera?

Thanks in sdvance

**Comment by shinebar1001** [comment]
This question addresses the original firmware, doesn't it?

**Comment by avdelco** [comment]
Hi
Yes, currently I am using the latest stock firmware 
Does this issue occur in the hacked firmware?

Thanks a lot in advance 

Konstantinos

**Comment by jmtatsch** [comment]
Recording with the hacked firmware is still very tricky but no hard limits are set.
To get support for the stock firmware please contact xiaomi support.
