### ISSUE TITLE
autoupdate: libcrypto.so.46 missing

### ISSUE THREAD

**Issue by hb9eue** [EliasKotlyar/Xiaomi-Dafang-Hacks#1450]
Hi

I see the fix for the RTSP-Server button has been comited. So time for an update.

Via WebGUI, update fails on both of my cams. So trying to figure out if there is a way to update from CLI. I suppose it's:

/system/sdcard/autoupdate.sh

It fails at:

lib/libUsageEnvironment.so updated.
lib/libalog.so is up to date.
lib/libcrypto.so created.
lib/libcrypto.so.42 updated.
lib/libcrypto.so.43 updated.
Can not get remote file https://raw.githubusercontent.com/EliasKotlyar/Xiaomi-Dafang-Hacks/master/firmware_mod/lib/libcrypto.so.46, exiting.

Retried a couple of times, it always stopps at that file or at:
https://raw.githubusercontent.com/EliasKotlyar/Xiaomi-Dafang-Hacks/master/firmware_mod/lib/libcrypto.so.46.0.1

Strangely that URI is correct and I seem to get the proper file if downloaded manually:

$ file libcrypto.so.46 
libcrypto.so.46: ELF 32-bit LSB shared object, MIPS, MIPS32 rel2 version 1 (SYSV), dynamically linked, not stripped

Any idea about the cause of this problem?

**Comment by Dopeyr** [comment]
Hi, how much free space do you have in /tmp? Just wondering if it's running out of space there.

**Comment by nik0** [comment]
It can also be a github limitation. You are limited for downloading in anonymous session
try later

**Comment by hb9eue** [comment]
dmesg showed curl crashing out of memory. killed all non relevant running daemons, tried agian, ran into github connection rate limit. Attempted again later, success :-)

**Comment by hb9eue** [comment]
Ok some more information as I could not update one cam this way... curl keeps crashing out of memory.
So let's try to add swap:

# dd if=/dev/zero of=/system/sdcard/swap bs=100M count=1
dd: out of memory

bummer!

# dd if=/dev/zero of=/system/sdcard/swap bs=1M count=100
100+0 records in
100+0 records out
104857600 bytes (100.0MB) copied, 10.716433 seconds, 9.3MB/s

Better!

# mkswap /system/sdcard/swap
Setting up swapspace version 1, size = 104853504 bytes
UUID=7fac6232-a29e-47c2-9304-c167047d5d73

# swapon /system/sdcard/swap

# free
             total       used       free     shared    buffers     cached
Mem:         35404      34348       1056          0       1080      15964
-/+ buffers/cache:      17304      18100
Swap:       102396          0     102396

So, let's try again...

# /system/sdcard/autoupdate.sh
[...]
lib/libcrypto.so.46 created.
lib/libcrypto.so.46.0.1 created.
Yes, that's further than ever...
Received zero byte file https://raw.githubusercontent.com/EliasKotlyar/Xiaomi-Dafang-Hacks/master/firmware_mod/lib/libgroupsock.so, exiting.

Oh, I suppose that's github rate limiting again.
