### ISSUE TITLE
Rootfs still maintained? Can't get it running

### ISSUE THREAD

**Issue by SaturnusDJ** [EliasKotlyar/Xiaomi-Dafang-Hacks#1451]
Currently I am running firmware_mod with https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/hacks/flashinguboot.md for FullHD. It is on a bad old SD card. Replacing it with a new 32GB one and hoping to move to ext3/4.

1. Is https://github.com/Dafang-Hacks/rootfs still up to date? Last commit is a long time ago, but maybe when running it, the packages can be updated live? (https://github.com/Dafang-Hacks/rootfs/issues/12)

2. I cannot get it to run actually. In a linux VM with Parted, the SD card was given a msdos partition table with ext3 partition. Then mkfs.ext3 onto the partition. Cloned https://github.com/Dafang-Hacks/rootfs right onto the card. WiFi password file adjusted. I tried with the rootfs folder in the root of the card and with the contents of rootfs in the root of the card.

**Comment by jmtatsch** [comment]
No. Please have a look at openfang.

**Comment by SaturnusDJ** [comment]
For question 2: https://github.com/Dafang-Hacks/rootfs/issues/9
The hack is really nice but without proper documentation it takes so much time.

@jmtatsch 
Thanks. 2 follow up questions: 1) Does it require to flash the bootloader mentioned there or can the one from this repo be used? 2) Will it have a webinterface similar to the one from this repo? (I do have linux CLI experience, but am not waiting to spend lots of time on getting it to work via CLI.)

**Comment by jmtatsch** [comment]
1) If you have our bootloader that runs the rootfs, you shouldnt need a special opfenfang bootloader.
2) yes, it has a webinterface, albeit with fewer functions
3)To my knowledge the update function does not work properly yet. Ask the author kindly, its almost ready.

**Comment by Ozzyminted** [comment]
It has its own bootloader but i think the rootfs bootloader works as well.
Or compile it yourself from docker from openfang.
Yes it has a nice updated version.

**Comment by SaturnusDJ** [comment]
Willing to try, even that bootloader but I don't find the right hash: https://github.com/anmaped/openfang/issues/60
