### ISSUE TITLE
flash_eraseall: applet not found

### ISSUE THREAD

**Issue by mplinuxgeek** [EliasKotlyar/Xiaomi-Dafang-Hacks#1454]
This is an issue tracking system only.
If you have general questions or are a newbie, please ask for help in our [chat channel](https://gitter.im/Xiaomi-Dafang-Hacks).

To make sure your issue can be resolved as quickly as possible please state your

* exact camera hardware: Wyzecam V2
* the Xiaomi-Dafang-Hacks commitid (from `git log`) you are experiencing the issue with: 4a64c49

### Description

flash_eraseall fails:
[root@Camera1:sdcard]# flash_eraseall /dev/mtd0
flash_eraseall: applet not found

### What did you do to debug the issue

Attempted to use flash_erase but I don't know the correct start block nor block count:

[root@Camera1:sdcard]# flash_erase /dev/mtd0
flash_erase: error!: no start erase block specified
flash_erase: error!: no erase block count specified
flash_erase: error!: Try `--help' for more information

### Evidence

[root@Camera1:sdcard]# md5sum dafang_128mb_v2.bin 
aab52eefe246dc1e15e56b253df3d64f  dafang_128mb_v2.bin
[root@Camera1:sdcard]# flash_eraseall /dev/mtd0
flash_eraseall: applet not found
[root@Camera1:sdcard]# flash_erase /dev/mtd0
flash_erase: error!: no start erase block specified
flash_erase: error!: no erase block count specified

### Contribute Back

If your issue was resolved, please consider contributing back to the project by creating a pull request to improve the code or documentation in order to avoid that this issue arises again for other people.

**Comment by jmtatsch** [comment]
We have a newer busybody version. Can you list the commands whether this applet still exists?

**Comment by mplinuxgeek** [comment]
This is what I get:

`[root@Camera1:~]# busybox
BusyBox v1.32.0.git (2020-04-05 20:30:22 UTC) multi-call binary.
BusyBox is copyrighted by many authors between 1998-2015.
Licensed under GPLv2. See source distribution for detailed
copyright notices.

Usage: busybox [function [arguments]...]
   or: busybox --list[-full]
   or: busybox --show SCRIPT
   or: busybox --install [-s] [DIR]
   or: function [arguments]...

	BusyBox is a multi-call binary that combines many common Unix
	utilities into a single executable.  Most people will create a
	link to busybox for each function they wish to use and BusyBox
	will act like whatever it was invoked as.

Currently defined functions:
	[, [[, acpid, add-shell, addgroup, adduser, adjtimex, arch, arp, arping, ash, awk, base64, basename, bc, beep, blkdiscard, blkid, blockdev, bootchartd, brctl,
	bunzip2, bzcat, bzip2, cal, cat, chat, chattr, chgrp, chmod, chown, chpasswd, chpst, chroot, chrt, chvt, cksum, clear, cmp, comm, conspy, cp, cpio, crond, crontab,
	cryptpw, cttyhack, cut, date, dc, dd, deallocvt, delgroup, deluser, depmod, devmem, df, dhcprelay, diff, dirname, dmesg, dnsd, dnsdomainname, dos2unix, dpkg,
	dpkg-deb, du, dumpkmap, dumpleases, echo, ed, egrep, eject, env, envdir, envuidgid, ether-wake, expand, expr, factor, fakeidentd, false, fatattr, fbset, fbsplash,
	fdflush, fdformat, fdisk, fgconsole, fgrep, find, findfs, flock, fold, free, freeramdisk, fsck, fsck.minix, fsfreeze, fstrim, ftpd, ftpget, ftpput, fuser, getopt,
	getty, grep, groups, gunzip, gzip, halt, hd, hdparm, head, hexdump, hexedit, hostid, hostname, httpd, hush, hwclock, i2cdetect, i2cdump, i2cget, i2cset,
	i2ctransfer, id, ifconfig, ifdown, ifenslave, ifplugd, ifup, inetd, init, insmod, install, ionice, iostat, ip, ipaddr, ipcalc, ipcrm, ipcs, iplink, ipneigh,
	iproute, iprule, iptunnel, kbd_mode, kill, killall, killall5, klogd, last, less, link, linux32, linux64, linuxrc, ln, loadfont, loadkmap, logger, login, logname,
	logread, losetup, lpd, lpq, lpr, ls, lsattr, lsmod, lsof, lspci, lsscsi, lsusb, lzcat, lzma, lzop, makedevs, makemime, man, md5sum, mdev, mesg, microcom, mkdir,
	mkdosfs, mke2fs, mkfifo, mkfs.ext2, mkfs.minix, mkfs.vfat, mknod, mkpasswd, mkswap, mktemp, modinfo, modprobe, more, mount, mountpoint, mpstat, mt, mv, nameif,
	nanddump, nandwrite, nbd-client, nc, netstat, nice, nl, nmeter, nohup, nologin, nproc, nslookup, ntpd, nuke, od, openvt, partprobe, passwd, paste, patch, pgrep,
	pidof, ping, ping6, pipe_progress, pivot_root, pkill, pmap, popmaildir, poweroff, powertop, printenv, printf, ps, pscan, pstree, pwd, pwdx, raidautorun, rdate,
	rdev, readahead, readlink, readprofile, realpath, reboot, reformime, remove-shell, renice, reset, resize, resume, rev, rm, rmdir, rmmod, route, rpm, rpm2cpio,
	rtcwake, run-init, run-parts, runlevel, runsv, runsvdir, rx, script, scriptreplay, sed, sendmail, seq, setarch, setconsole, setfattr, setfont, setkeycodes,
	setlogcons, setpriv, setserial, setsid, setuidgid, sh, sha1sum, sha256sum, sha3sum, sha512sum, showkey, shred, shuf, slattach, sleep, smemcap, softlimit, sort,
	split, ssl_client, start-stop-daemon, stat, strings, stty, su, sulogin, sum, sv, svc, svlogd, svok, swapoff, swapon, switch_root, sysctl, syslogd, tac, tail, tar,
	taskset, tc, tcpsvd, tee, telnet, telnetd, test, tftp, tftpd, time, timeout, top, touch, tr, traceroute, traceroute6, true, truncate, ts, tty, ttysize, tunctl,
	ubiattach, ubidetach, ubimkvol, ubirename, ubirmvol, ubirsvol, ubiupdatevol, udhcpc, udhcpc6, udhcpd, udpsvd, uevent, umount, uname, unexpand, uniq, unix2dos,
	unlink, unlzma, unshare, unxz, unzip, uptime, users, usleep, uudecode, uuencode, vconfig, vi, vlock, volname, w, wall, watch, watchdog, wc, wget, which, who,
	whoami, whois, xargs, xxd, xz, xzcat, yes, zcat, zcip
`

**Comment by jmtatsch** [comment]
Looks like that applet isn’t there. Maybe the look at the busybox of the Original fw in /bin?

**Comment by nik0** [comment]
Will check tonight why this module is not here

**Comment by nik0** [comment]
@mplinuxgeek 
Good catch ... Please see latest version of beta branch

**Comment by manutenfruits** [comment]
I'm also affected by this, where `flash_eraseall` is not present. I checked on `/bin/busybox` and it's also missing.

```
[root@DAFANG:sdcard]# which busybox
/system/sdcard/bin/busybox
[root@DAFANG:sdcard]# busybox
BusyBox v1.32.0.git (2020-04-05 20:30:22 UTC) multi-call binary.
BusyBox is copyrighted by many authors between 1998-2015.
Licensed under GPLv2. See source distribution for detailed
copyright notices.

Usage: busybox [function [arguments]...]
   or: busybox --list[-full]
   or: busybox --show SCRIPT
   or: busybox --install [-s] [DIR]
   or: function [arguments]...

	BusyBox is a multi-call binary that combines many common Unix
	utilities into a single executable.  Most people will create a
	link to busybox for each function they wish to use and BusyBox
	will act like whatever it was invoked as.

Currently defined functions:
	[, [[, acpid, add-shell, addgroup, adduser, adjtimex, arch, arp,
	arping, ash, awk, base64, basename, bc, beep, blkdiscard, blkid,
	blockdev, bootchartd, brctl, bunzip2, bzcat, bzip2, cal, cat, chat,
	chattr, chgrp, chmod, chown, chpasswd, chpst, chroot, chrt, chvt,
	cksum, clear, cmp, comm, conspy, cp, cpio, crond, crontab, cryptpw,
	cttyhack, cut, date, dc, dd, deallocvt, delgroup, deluser, depmod,
	devmem, df, dhcprelay, diff, dirname, dmesg, dnsd, dnsdomainname,
	dos2unix, dpkg, dpkg-deb, du, dumpkmap, dumpleases, echo, ed, egrep,
	eject, env, envdir, envuidgid, ether-wake, expand, expr, factor,
	fakeidentd, false, fatattr, fbset, fbsplash, fdflush, fdformat, fdisk,
	fgconsole, fgrep, find, findfs, flock, fold, free, freeramdisk, fsck,
	fsck.minix, fsfreeze, fstrim, ftpd, ftpget, ftpput, fuser, getopt,
	getty, grep, groups, gunzip, gzip, halt, hd, hdparm, head, hexdump,
	hexedit, hostid, hostname, httpd, hush, hwclock, i2cdetect, i2cdump,
	i2cget, i2cset, i2ctransfer, id, ifconfig, ifdown, ifenslave, ifplugd,
	ifup, inetd, init, insmod, install, ionice, iostat, ip, ipaddr, ipcalc,
	ipcrm, ipcs, iplink, ipneigh, iproute, iprule, iptunnel, kbd_mode,
	kill, killall, killall5, klogd, last, less, link, linux32, linux64,
	linuxrc, ln, loadfont, loadkmap, logger, login, logname, logread,
	losetup, lpd, lpq, lpr, ls, lsattr, lsmod, lsof, lspci, lsscsi, lsusb,
	lzcat, lzma, lzop, makedevs, makemime, man, md5sum, mdev, mesg,
	microcom, mkdir, mkdosfs, mke2fs, mkfifo, mkfs.ext2, mkfs.minix,
	mkfs.vfat, mknod, mkpasswd, mkswap, mktemp, modinfo, modprobe, more,
	mount, mountpoint, mpstat, mt, mv, nameif, nanddump, nandwrite,
	nbd-client, nc, netstat, nice, nl, nmeter, nohup, nologin, nproc,
	nslookup, ntpd, nuke, od, openvt, partprobe, passwd, paste, patch,
	pgrep, pidof, ping, ping6, pipe_progress, pivot_root, pkill, pmap,
	popmaildir, poweroff, powertop, printenv, printf, ps, pscan, pstree,
	pwd, pwdx, raidautorun, rdate, rdev, readahead, readlink, readprofile,
	realpath, reboot, reformime, remove-shell, renice, reset, resize,
	resume, rev, rm, rmdir, rmmod, route, rpm, rpm2cpio, rtcwake, run-init,
	run-parts, runlevel, runsv, runsvdir, rx, script, scriptreplay, sed,
	sendmail, seq, setarch, setconsole, setfattr, setfont, setkeycodes,
	setlogcons, setpriv, setserial, setsid, setuidgid, sh, sha1sum,
	sha256sum, sha3sum, sha512sum, showkey, shred, shuf, slattach, sleep,
	smemcap, softlimit, sort, split, ssl_client, start-stop-daemon, stat,
	strings, stty, su, sulogin, sum, sv, svc, svlogd, svok, swapoff,
	swapon, switch_root, sysctl, syslogd, tac, tail, tar, taskset, tc,
	tcpsvd, tee, telnet, telnetd, test, tftp, tftpd, time, timeout, top,
	touch, tr, traceroute, traceroute6, true, truncate, ts, tty, ttysize,
	tunctl, ubiattach, ubidetach, ubimkvol, ubirename, ubirmvol, ubirsvol,
	ubiupdatevol, udhcpc, udhcpc6, udhcpd, udpsvd, uevent, umount, uname,
	unexpand, uniq, unix2dos, unlink, unlzma, unshare, unxz, unzip, uptime,
	users, usleep, uudecode, uuencode, vconfig, vi, vlock, volname, w,
	wall, watch, watchdog, wc, wget, which, who, whoami, whois, xargs, xxd,
	xz, xzcat, yes, zcat, zcip
[root@DAFANG:sdcard]# /bin/busybox
BusyBox v1.32.0.git (2020-04-05 20:30:22 UTC) multi-call binary.
BusyBox is copyrighted by many authors between 1998-2015.
Licensed under GPLv2. See source distribution for detailed
copyright notices.

Usage: busybox [function [arguments]...]
   or: busybox --list[-full]
   or: busybox --show SCRIPT
   or: busybox --install [-s] [DIR]
   or: function [arguments]...

	BusyBox is a multi-call binary that combines many common Unix
	utilities into a single executable.  Most people will create a
	link to busybox for each function they wish to use and BusyBox
	will act like whatever it was invoked as.

Currently defined functions:
	[, [[, acpid, add-shell, addgroup, adduser, adjtimex, arch, arp,
	arping, ash, awk, base64, basename, bc, beep, blkdiscard, blkid,
	blockdev, bootchartd, brctl, bunzip2, bzcat, bzip2, cal, cat, chat,
	chattr, chgrp, chmod, chown, chpasswd, chpst, chroot, chrt, chvt,
	cksum, clear, cmp, comm, conspy, cp, cpio, crond, crontab, cryptpw,
	cttyhack, cut, date, dc, dd, deallocvt, delgroup, deluser, depmod,
	devmem, df, dhcprelay, diff, dirname, dmesg, dnsd, dnsdomainname,
	dos2unix, dpkg, dpkg-deb, du, dumpkmap, dumpleases, echo, ed, egrep,
	eject, env, envdir, envuidgid, ether-wake, expand, expr, factor,
	fakeidentd, false, fatattr, fbset, fbsplash, fdflush, fdformat, fdisk,
	fgconsole, fgrep, find, findfs, flock, fold, free, freeramdisk, fsck,
	fsck.minix, fsfreeze, fstrim, ftpd, ftpget, ftpput, fuser, getopt,
	getty, grep, groups, gunzip, gzip, halt, hd, hdparm, head, hexdump,
	hexedit, hostid, hostname, httpd, hush, hwclock, i2cdetect, i2cdump,
	i2cget, i2cset, i2ctransfer, id, ifconfig, ifdown, ifenslave, ifplugd,
	ifup, inetd, init, insmod, install, ionice, iostat, ip, ipaddr, ipcalc,
	ipcrm, ipcs, iplink, ipneigh, iproute, iprule, iptunnel, kbd_mode,
	kill, killall, killall5, klogd, last, less, link, linux32, linux64,
	linuxrc, ln, loadfont, loadkmap, logger, login, logname, logread,
	losetup, lpd, lpq, lpr, ls, lsattr, lsmod, lsof, lspci, lsscsi, lsusb,
	lzcat, lzma, lzop, makedevs, makemime, man, md5sum, mdev, mesg,
	microcom, mkdir, mkdosfs, mke2fs, mkfifo, mkfs.ext2, mkfs.minix,
	mkfs.vfat, mknod, mkpasswd, mkswap, mktemp, modinfo, modprobe, more,
	mount, mountpoint, mpstat, mt, mv, nameif, nanddump, nandwrite,
	nbd-client, nc, netstat, nice, nl, nmeter, nohup, nologin, nproc,
	nslookup, ntpd, nuke, od, openvt, partprobe, passwd, paste, patch,
	pgrep, pidof, ping, ping6, pipe_progress, pivot_root, pkill, pmap,
	popmaildir, poweroff, powertop, printenv, printf, ps, pscan, pstree,
	pwd, pwdx, raidautorun, rdate, rdev, readahead, readlink, readprofile,
	realpath, reboot, reformime, remove-shell, renice, reset, resize,
	resume, rev, rm, rmdir, rmmod, route, rpm, rpm2cpio, rtcwake, run-init,
	run-parts, runlevel, runsv, runsvdir, rx, script, scriptreplay, sed,
	sendmail, seq, setarch, setconsole, setfattr, setfont, setkeycodes,
	setlogcons, setpriv, setserial, setsid, setuidgid, sh, sha1sum,
	sha256sum, sha3sum, sha512sum, showkey, shred, shuf, slattach, sleep,
	smemcap, softlimit, sort, split, ssl_client, start-stop-daemon, stat,
	strings, stty, su, sulogin, sum, sv, svc, svlogd, svok, swapoff,
	swapon, switch_root, sysctl, syslogd, tac, tail, tar, taskset, tc,
	tcpsvd, tee, telnet, telnetd, test, tftp, tftpd, time, timeout, top,
	touch, tr, traceroute, traceroute6, true, truncate, ts, tty, ttysize,
	tunctl, ubiattach, ubidetach, ubimkvol, ubirename, ubirmvol, ubirsvol,
	ubiupdatevol, udhcpc, udhcpc6, udhcpd, udpsvd, uevent, umount, uname,
	unexpand, uniq, unix2dos, unlink, unlzma, unshare, unxz, unzip, uptime,
	users, usleep, uudecode, uuencode, vconfig, vi, vlock, volname, w,
	wall, watch, watchdog, wc, wget, which, who, whoami, whois, xargs, xxd,
	xz, xzcat, yes, zcat, zcip
[root@DAFANG:sdcard]# 
```

@nik0 your last comment sounds like you found a solution? is that correct?

**Comment by mplinuxgeek** [comment]
@manutenfruits as per @nik0 comment update to beta, I meant to respond to nik0 earlier.
Use the update to beta option in the GUI, once updated you will have flash_eraseall available, after you've used flash_eraseall you can downgrade back to stable.

**Comment by pwfff** [comment]
Y'all should probably get this out ASAP. Followed https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/hacks/flashinguboot.md and didn't notice the applet error, and now I have a bricked device.

**Comment by pwfff** [comment]
Also, the reflash guide linked from the flashing documentation is out of date, wrong (says you can't use a clip), and links to a pdf that 403s. Luckily it looks like someone posted their own process in the issues: https://github.com/Dafang-Hacks/spiflasher/issues/1#issuecomment-613026294

**Comment by jmtatsch** [comment]
@pwfff What changes would you deem fit? Can you open a pull request please?

**Comment by pwfff** [comment]
It sounds like the applet is already in the beta branch, so my PR would just be a release. I don't see contribution instructions for making a new release. Is it just a merge to master from beta?

**Comment by pwfff** [comment]
Oh, and I'll make a PR to spiflasher for the documentation. The .bin there also confuses me - it doesn't match the hash of the .bin I was originally trying to flash, so I'm not even sure if it's for my hardware...

**Comment by jmtatsch** [comment]
Yes I meant improve the documentation 😉

**Comment by mail929** [comment]
Switching to the beta branch worked on my Wyzecam Pan but not my Wyzecam v2. But, I was able to do the same thing with `flash_erase /dev/mtd0 0 0`

**Comment by wolcen** [comment]
> @pwfff What changes would you deem fit? Can you open a pull request please?

Not sure what @pwfff would suggest (I don't know what applies from the referenced issue)...but just wanted to point out that the `flash_erase /dev/mtd0 0 0` from @mail929 is precisely what made the process work for me when getting an `applet not found` error with a Wyzecam v2 as well.

I'd open a PR, but I barely know the project, just having started experimenting today with a first device, sorry.

**Comment by LeonCame** [comment]
For me too, (Dafang 128 / putty)

- flash_eraseall /dev/mtd0 = applet not found
- flash_erase /dev/mtd0 0 0 = worked

followed (in my case) by
- dd if=/system/sdcard/dafang_128mb_v2.bin of=/dev/mtd0
as described here: https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/hacks/flashinguboot.md

successfully flashed.

**Comment by LeonCame** [comment]
For me too, (Dafang 128 / putty)

- flash_eraseall /dev/mtd0 = applet not found
- flash_erase /dev/mtd0 0 0 = worked

followed (in my case) by
- dd if=/system/sdcard/dafang_128mb_v2.bin of=/dev/mtd0
as described here: https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/hacks/flashinguboot.md

successfully flashed.

**Comment by LeonCame** [comment]
For me too, (Dafang 128 / putty)

- flash_eraseall /dev/mtd0 = applet not found
- flash_erase /dev/mtd0 0 0 = worked

followed (in my case) by
- dd if=/system/sdcard/dafang_128mb_v2.bin of=/dev/mtd0
as described here: https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/hacks/flashinguboot.md

successfully flashed.

**Comment by LeonCame** [comment]
For me too, (Dafang 128 / putty)

- flash_eraseall /dev/mtd0 = applet not found
- flash_erase /dev/mtd0 0 0 = worked

followed (in my case) by
- dd if=/system/sdcard/dafang_128mb_v2.bin of=/dev/mtd0
as described here: https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/hacks/flashinguboot.md

successfully flashed.
