### ISSUE TITLE
Hack dafang info

### ISSUE THREAD

**Issue by crm1801** [EliasKotlyar/Xiaomi-Dafang-Hacks#146]
Very good, first of all forgive me for my English, I am using a translator. Can you tell me if with the hack, you could thus record the alerts on a private server? Thank you.

**Comment by shinebar1001** [comment]
As the Xiaomi-Dafang-Hack isn't able to detect motion, you are not able to record *alerts* on a private server without additional software running on an another server like motioneye.
But you can record videos (with some manual actions to a ftp-server or a nfs-enabled NAS.
I'm closing this issue, please feel free to reopen it when you have further questions.

**Comment by Adriien-M** [comment]
Just for my information, the original firmware of the Dafang camera  is able to detect motion, right?
It's not possible to use the original function to get an alert when motion is detected?

**Comment by nik0** [comment]
I added the v4l2server motion detection that is not yet merged https://github.com/EliasKotlyar/Xiaomi-Dafang-Software/pull/8
For now the "region selection" of the motion is not working but it seems to be promising. I didn't suceeded saving the stream using avconv ...
Nik0

**Comment by Adriien-M** [comment]
Wow nice work indeed! This is an important feature...
Currently, I detect motion and record video stream via Synology Surveillance Station, it works perfectly. However, it would be interesting to handle the detection directly via the camera and send a notification via MQTT. In this way, the management can be centralized in our favorite home automation platform...
