### ISSUE TITLE
Cron tab

### ISSUE THREAD

**Issue by gysmo38** [EliasKotlyar/Xiaomi-Dafang-Hacks#1462]
How cron tab work?

I try to put a script in /system/sdcard/controlscripts/periodic/hourly but nothing happen.

There is something to restart?

I would like to use it to check update periodicaly and write it in a file. It could be use for the web ui and for mqtt to send update status.

**Comment by saipsa** [comment]
did you make the scripts executable?

**Comment by tachang** [comment]
Is there a cron daemon running?

**Comment by s58DB** [comment]
I have same problems. I want run cronjob after rebot. 
I want automatic mount USB storage. 
In crontab I write @reboot mount /dev/sda1 /system/sdcard/media/usb_drive but this cronjob don't run after reboot. 
What can I do.

**Comment by gysmo38** [comment]
I check /system/sdcard/log/cron.log it look like the cron work but when you execute busybox run-parts /system/sdcard/config/cron/periodicaly/15min for example nothing happen.
I only create a small script that write date in a file.

**Comment by jmtatsch** [comment]
I think you need to give it the full path of our busybox executable.

**Comment by gysmo38** [comment]
I try like this /system/sdcard/bin/busybox run-parts /system/sdcard/config/cron/periodic/15min
It look like run-parts not working. If I add a line in the crontab file, it work well.

**Comment by jmtatsch** [comment]
Is run parts a busybox applet? Maybe it confuses the argument order then. Try a symlink to the busybox applet in that case.

**Comment by gysmo38** [comment]
how I do that?
