### ISSUE TITLE
Can the hack be used for Xiaomi Mijia Outdoor AI Smart IP Camera IP65 Waterproof Dustproof 1080p FHD 170° 2.4GG Wi-Fi IR Night Vision?

### ISSUE THREAD

**Issue by saipsa** [EliasKotlyar/Xiaomi-Dafang-Hacks#1469]
Can the hack be used for this camera?

https://www.aliexpress.com/item/4000767986646.html?spm=a2g0s.8937460.0.0.643c2e0edb1nwU

**Comment by gysmo38** [comment]
I don't knwon but it could be great it this is the case. Outdoor cam really missing in this hack.

**Comment by Phslion** [comment]
Id like to know also.  I just bought two of these.  They seem to be good cameras with questionable security through the xiaomi app.

**Comment by kakemanx** [comment]
I also would like to know :)

**Comment by asCii88** [comment]
Open one up if you can and upload some pictures of the chips inside.

**Comment by john9393** [comment]
Saipsa : I had bought this camera once week ago and sorry I didn't find any hack working.
NO rtsp , worked only with M-HOME and Chinese server .

**Comment by john9393** [comment]
Saipsa : I had bought this camera once week ago and sorry I didn't find any hack working.
NO rtsp , worked only with M-HOME and Chinese server .

**Comment by john9393** [comment]
Saipsa : I had bought this camera once week ago and sorry I didn't find any hack working.
NO rtsp , worked only with M-HOME and Chinese server .

**Comment by ahmadnazirafiq** [comment]
mine broken after using it for 4 months. won't power on and no status light at all.
