### ISSUE TITLE
Frame rate question

### ISSUE THREAD

**Issue by DomoJe** [EliasKotlyar/Xiaomi-Dafang-Hacks#147]
Hi,

I successfully managed to use your (great) hack, but I still have a question regarding the frame rate.
Up to now, the dafang only sends jpg pictures every 4 seconds. According to Xioami specs, this camera is able to send 15 fps.

Did I something wrong ? Or should I configure something else to have a "real" video stream ?

Thx in advance

**Comment by shinebar1001** [comment]
I suppose you're using the live view Webpage? Please try VLC with the rtsp-streams linked on the front page to get 25fps

**Comment by DomoJe** [comment]
You are right. It works great

Thanks
