### ISSUE TITLE
Telegram and mount USB storage

### ISSUE THREAD

**Issue by s58DB** [EliasKotlyar/Xiaomi-Dafang-Hacks#1470]
Hello,

yesterday I upgraded FW on SD-card on new version 34a96ba. On previous version I don't have problems with telegram and mount USB storage.

On this version Telegram-bot don't respond on commands when I send them via phone but send image when detect motion. 

With USB storage I don't know what I do wrong. I wrote simple script in /config/userscripts/startup. This Script I make executable but don't run when I reboot system. If i run script manually I get good result.

Does anyone have the same problems?

Best regards, D

**Comment by pfefferle** [comment]
The change only adds an alternate message source, that supports channel posts, it should not break previous implementations.

**Comment by pfefferle** [comment]
Do you send via channel or directly to the bot?

**Comment by jmtatsch** [comment]
Does your userscript have the .sh ending?

**Comment by s58DB** [comment]
> Do you send via channel or directly to the bot?

I send commands directly to the bot. 

> Does your userscript have the .sh ending?

yes

![my_script_mount](https://user-images.githubusercontent.com/23266214/83421982-2cc5db00-a429-11ea-9dfc-cf4f1994d326.PNG)

**Comment by dvybornov** [comment]
I’ve got the same troubles with Telegram-bot after last update. I send messages via shared group with bot.

**Comment by YogaSakti** [comment]
I also have the same problem. when i see the logs page, , last_update_id changes but there is no reply message 
![image](https://user-images.githubusercontent.com/24309806/83999805-aa3f9d00-a98d-11ea-91a1-c9f897aa9b32.png) 
![image](https://user-images.githubusercontent.com/24309806/83999821-b9bee600-a98d-11ea-9981-4279a304cf8e.png)
![image](https://user-images.githubusercontent.com/24309806/83999840-c6433e80-a98d-11ea-8fc9-98a5f278157d.png)

**Comment by RaymondSchnyder** [comment]
Ive spent 2 hours searching for the bug, but it was actually right there all the time.
Its a simple assignement bug, my merge request is right here:
https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/compare/master...RaymondSchnyder:patch-1

Already tested on my local dafang, works fine.

**Comment by dvybornov** [comment]
I've make the changes in telegram-bot-daemon.sh but it doesn't help.
Bot sends me alerts but don't respond on commands.

**Comment by RaymondSchnyder** [comment]
> 
> 
> I've make the changes in telegram-bot-daemon.sh but it doesn't help.
> Bot sends me alerts but don't respond on commands.

Did you make the changes i suggested?
Did you restart the telegram daemon after that?

**Comment by dvybornov** [comment]
Yes. I replaced one line with two new and rebooted the camera several times.
Now I use telegram-bot-daemon.sh from the previous firmware ec9f5b9 and everything works fine.
