### ISSUE TITLE
CFW to Flash, Eliminating SD Card

### ISSUE THREAD

**Issue by jttri777** [EliasKotlyar/Xiaomi-Dafang-Hacks#1475]
Good Afternoon,

Hardware: Neos SmartCam

Firstly, I'd like to thank you all for the fantastic CFW and amount of work you have put in to creating such a great system.

I have spent some time over the last few days attempting to create an image that can directly be flashed to the internal flash chip, eliminating the need for an SD Card. For the time being, I only require the camera to essentially run the v4l2rtspserver software, getting the feed from the camera and pushing it out over RTSP (ideally with an ethernet and not Wi-Fi connection to the network). I'm not concerned with any other features at the moment.

I took the original Neos firmware, changed the /init/app-init.sh file around a bit in the appfs partition to prevent any of the original Neos/Dafang software from running (/bin/iCamera etc.) and have added functionality to load in the usbnet.ko and asix.ko drivers (which I added into the separate drivers partition) to enable a USB ethernet device to be used, as well as starting DHCP, setting the hostname and starting telnet etc. I have then tested this by flashing it back to a camera's flash chip (using the demo.bin method) and all seems to work well.

This is the contents of my /system/bin folder:
 
![image](https://user-images.githubusercontent.com/12187650/83647822-3f691d00-a5ad-11ea-9cc7-0469d9a7400c.png)

This is the contents of my /system/lib folder:

![image](https://user-images.githubusercontent.com/12187650/83647865-4d1ea280-a5ad-11ea-8af0-587bfb190964.png)
 
The final piece in the puzzle was to get the v4l2rtspserver software running. I copied this into the bin directory within the appfs partition, along with it's .ini file and copied in what I thought were the relevant libraries into the lib folder within the appfs partition, directly from the firmware_mod folder. However, when either my startup script goes to execute the v4l2rtspserver, or I do directly over serial/telnet the following error appears:
![image](https://user-images.githubusercontent.com/12187650/83647974-6aec0780-a5ad-11ea-9ffd-920dce622bba.png)
 
This prevents me from starting the application, no matter what options/switches I provide. I assume this is some kind of library not being picked up whilst attempting to start things up, however (as shown above), I thought I'd included everything that was necessary (is there a definitive list of v4l2rtspserver dependeicies?).
As a side note, a lot of the following errors seem to appear when the firmware loads, but everything seems to run fine afterwards:

![image](https://user-images.githubusercontent.com/12187650/83648081-8b1bc680-a5ad-11ea-9256-d3d0f5278c63.png)

The appfs partition seem to be completely full as well:

![image](https://user-images.githubusercontent.com/12187650/83648104-92db6b00-a5ad-11ea-83b5-1fa2951876aa.png)
 
Under normal circumstances, i'd include every library in the image from the original firmware, as well as the dafang-hacks CFW and hope that something was picked up, however with the size limitations of the firmware, I have had to remove things that I thought were unnecessary/unused to try and fit in things that are required. 

As an additional point, the flash chip on my camera is a "25Q127CSIG", which according to this web page [https://www.tme.eu/en/details/gd25q127csig/serial-flash-memories-integrated-circ/gigadevice/](https://www.tme.eu/en/details/gd25q127csig/serial-flash-memories-integrated-circ/gigadevice/), is an 128MB chip.

Then came the second quest, attempting to increase the size of the partition table allocations, to allow me to add more functionality into the firmware later on. I have worked out that the partitions are specified using the "mtdparts" command within the "bootargs" parameter within uboot. Linux then seems to pick this up and allocate the partitions accordingly. However when I attempted to change the partition table allocations using the "setenv" command in uboot, upon booting the system a message appears saying something along the lines of "partition exceeds flash capacity". If the chip is 128MB, why is the system not recognizing it with the full capacity? (and is there a way to check the capacity either in uboot or linux?). One of the "bootcmd" parameters defined in uboot identifies the chip as "GD25Q128" upon startup, which (whilst being a different model) is still 128MB according to various datasheets (so I assume they're compatible with each other). Could this be a driver issue?, I believe that the driver is called "jz_sfc".

![image](https://user-images.githubusercontent.com/12187650/83648355-dc2bba80-a5ad-11ea-8081-b6a3a54d7e9b.png)
 
Sorry for the long post, I believe that if the full potential of the flash chip could be utilised, a lot more functionality could be included in an image designed to be flashed to the internal flash chip, and therefore potentially alleviate the need for the permanent usage of an SD card, for those using some kind of external device to record the RTSP feed (zoneminder, shinobi, blueiris etc.)

Any help would be greatly appreciated.

Many thanks for your time,

James.

**Comment by nik0** [comment]
before starting the server what is the result of env command ? 
Maybe you need to set LD_LIBRARY_PATH to point to the /system/lib

**Comment by jttri777** [comment]
Hi nik0,

Thanks for your response, really appreciate your help.

The result of the env command is:
![image](https://user-images.githubusercontent.com/12187650/83654910-a985c000-a5b5-11ea-8088-7d4d993d6395.png)

With the LD_LIBRARY_PATH set to just /system/lib, the error message still appears, just without the /thirdlib/ line.

![image](https://user-images.githubusercontent.com/12187650/83655160-f8335a00-a5b5-11ea-99d7-245b23104fbd.png)


Many Thanks,
James.

**Comment by nik0** [comment]
Try to invert thirdlib and systemlib,
something like this:
`
export LD_LIBRARY_PATH=/system/lib:/thridlib
`

**Comment by nik0** [comment]
Strange, are you sure of your libs ?
What is the output of 
`
ls -la /system/lib
`
?

**Comment by jttri777** [comment]
Swapping the LD_LIBRARY_PATH results in the same error.

I've copied the libs straight out of the latest stable firmware_mod version.

ls -la /system/lib:
![image](https://user-images.githubusercontent.com/12187650/83655926-d8506600-a5b6-11ea-8064-2eab28d288c2.png)

Many Thanks,
James

**Comment by nik0** [comment]
Very strange
try getting all the libs of firmware_mod/lib path
Need also to check where is the libc

**Comment by jttri777** [comment]
Hi,

libc is in the main /lib directory

ls /lib:
![image](https://user-images.githubusercontent.com/12187650/83658203-cde39b80-a5b9-11ea-947a-430f44f97270.png)

Adding the /lib directory to the LD_LIBRARY_PATH still presents the same error message (although I believe that is was checking it anyway?).

Currently, I am unable to put any more of the libs from the firmware_mod file in the image due to the size restraints. This was one of the main reasons why I started to look into expanding the file system to use the whole capacity of the 128MB flash chip, with enough space my plan was to throw in every library and hope that something worked!

Thanks again,
James.

**Comment by nik0** [comment]
This is a very strange error, it seems to be system related ...
And what does the command `cat /proc/cpuinfo` gives?

**Comment by jttri777** [comment]
cat /proc/cpuinfo:
![image](https://user-images.githubusercontent.com/12187650/83659540-95dd5800-a5bb-11ea-9a87-e4d472058296.png)

Many Thanks,
James.

**Comment by nik0** [comment]
I have the same info... Strange, strange
Any chance with with another binary like bftpd which have no dependancy ?

**Comment by jttri777** [comment]
OK,
I've flashed a new image onto the camera with bftpd present.

Upon running it i'm getting the following error:
![image](https://user-images.githubusercontent.com/12187650/83661147-a2fb4680-a5bd-11ea-963a-4fbab5cc075e.png)


Just looking into where I have to put the config file now.

Many Thanks,
James.

**Comment by nik0** [comment]
it seems to work anyway ...
I don't understand your problem ...

**Comment by jttri777** [comment]
No problem. Thanks a lot for your help, would you know anything about expanding the filesystem to use the full 128MB of the chip?

**Comment by nik0** [comment]
Keep me posted
You need to check old post about bootloader I guess

**Comment by jttri777** [comment]
Ok, Thank you for your time.

**Comment by jttri777** [comment]
Been over to the Dafang-Hacks/uboot repository. According to this issue https://github.com/Dafang-Hacks/uboot/issues/8, the flash driver is something that is maintained within the Dafang-Hacks/uboot repository.

I will log an issue on that repository in relation to the size of the chip being identified incorrectly (if it is?) and see what happens over there. If I'm right and the flash chip is being wrongly identified, then I'll have a go at recompiling the driver myself (don't know how well that'll go!).

Once I've got a bit more room to add libs etc. I suppose I can come back and experiment adding libraries without the space restrictions.

Many Thanks.
James.

**Comment by fundef1** [comment]
I think you are mixing up bits and bytes.

**Comment by fundef1** [comment]
Did you check whether the libs you copied over aren't corrupted somehow?
Check the header with a hex-editor/hexdump just to make sure.

**Comment by jakass202** [comment]
@jttri777 any light instructions on how you flashed the chip please?

**Comment by jttri777** [comment]
I've checked all the files with a hex editor and they all contain the ".ELF" at the beginning, I'll have a proper look tomorrow and attempt to redownload the repo and see if that makes a difference. Thanks for your help @fundef1.

@jakass202, the way I'm doing it is by using the packet.py script to package up the file system into a single bin file, renaming it to "demo.bin", putting it on an sd card, which I then put into the camera. When powering the camera, holding down the setup button should start a procedure that wipes and flashes the chip, with the "demo.bin" file. Make sure the "demo.bin" file is the only one on the card.

This is essentially the same method used in the first part of the installing the original dafang hack, which enables booting from the sd card.

Thanks,
James

**Comment by Combie81** [comment]
This video may be of use: https://youtu.be/hV8W4o-Mu2o

**Comment by meduar** [comment]
Could you share your code?

**Comment by jttri777** [comment]
@meduar, yes I'll share the code, just need to get over this v4l2rtspserver issue. Might have a proper look at it if I have some time today. Once I've got it working, it'll just be an image that loads in with ethernet drivers and plays the rtsp stream over that connection, there's no Web interface or real way to change the configuration without rebuilding the image.

**Comment by nik0** [comment]
Did you check with MD5sum ?

**Comment by jttri777** [comment]
Hi Nik0,

I was able to check the MD5 sums directly on the camera, and then compared them with the libraries in the mod_firmware folder. The versions of libimp.so, libalog.so and libsysutils.so were showing up as having different hashes. Upon replacing them and flashing the images back to the camera, v4l2rtspserver executed successfully and I have just connected to the video stream using VLC over the network. Obviously something was updated at some point.

At this moment, the audio doesn't seem to be working but i'll have a play with that (i think that may be due to the lack of an MP3 library), and the video is breaking up in some parts. I've just ran top and the v4l2rtspserver is consuming about 90% CPU utilisation. I think there have been some issues raised about this, so I'll do some reading.

Thanks a lot for all your (and others) help and suggestions. I'll close the issue for now, and add the image to the bottom of this issue for those interested over the next few days, hopefully once the audio is working and maybe the v4l2rtspserver's CPU usage has been reduced somewhat.

Many Thanks,
James.

**Comment by nik0** [comment]
Good news !!! 
Maybe it was because of LF/CR difference between windows / unix.
Indeed you need MP3 or Opus. There is also a RAW PCM format thay may not need any lib

I guess you need to lower the resolution to have less CPU usage ...

**Comment by jttri777** [comment]
Yes, adding the libmp3lame.so and libaudioProcess.so gets the audio working. Thanks for that.

Frame rate is currently set to 25fps with a resolution of 1280x720. CPU usage is quite low until a connection is made and then jumps up to 100%, lost of breaking up on the video stream as well. There seem to be lots of issues regarding this so i'll have to read through them and see if anyone has found a solution.

Many Thanks,
James.

**Comment by meduar** [comment]
jttri777 Could I have the steps you did to flash directly to the camera, I need to do it. please

**Comment by jttri777** [comment]
Hello,

This was quite a while ago, so I'm having trouble even remembering how I did it to be honest!

The project started because I made a mistake when looking into the internal memory capacity of the camera. I ended up thinking that the internal flash memory within the camera was significantly bigger than it ended up being.

I did still manage to build an image that did the job, however due to the lack of flash space available, the drawbacks outweighed the benefits.

The image stream quality was just as good as using the full firmware installed on an SD card, and you end up losing the ability to change settings through the web interface. To change any settings on the camera (RTSP usernames and passwords, IP config settings etc.), I ended up making the required changes and recreating a whole new image each time, which was a complete nightmare. You can't change these settings over SSH because they are not written back to the camera's flash storage, therefore when the camera restarts it pulls in the settings originally implemented into the image again.

As I said, in the end, it really wasn't worth the bother aside from the learning experience. The overall performance of the camera was no better than using the full "Hacks" image on an SD card, and configuration was a complete nightmare.

**Comment by meduar** [comment]
I have a project that requires only one functionality so it has to be flashed into the camera, but I agree with you that is better to dont do this only in special case, at this moment is for a special case.

Do you mind if I ask you how did you build the image? did you created a squashfs? that basically what I need build the image.


thanks.

**Comment by jttri777** [comment]
Hello,

- I don't believe that I did get hold of the original Neos firmware, I don't know if the firmware requires it anymore, but the old installation process used to involve installing a smaller image onto the camera (which you'd put onto the SD card named something specific, and then hold down the button on the bottom whilst the camera booted, the image would then be flashed onto the internal flash memory of the camera). Once the firmware booted it would then instantly boot into the image on the SD Card. This image used to be available within the "Hacks" repository.
- I used this (booting image) as my starting point and basically took the image apart and began swapping elements until it was below 8mb but had all the required functionality. This primarily involved editing the squashfs using multiple commands to that effect.

**Comment by meduar** [comment]
Hi,

I really appreciate your time, last question sorry to bother you again

- How did you make it to flash it on the nand directly using the demo.bin method?
- 
Thank you

**Comment by jttri777** [comment]
As far as I can remember I used the method documented within the "Hacks" repository.

https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/hacks/install_cfw.md

It seems as though if the firmware of the camera is fairly modern, then they have prevented the firmware from being modified using this method (it says this in the main README file within the "Hacks" repository). At the time I was doing this, this wasn't a problem.
