### ISSUE TITLE
Lighttpd setenv module

### ISSUE THREAD

**Issue by gysmo38** [EliasKotlyar/Xiaomi-Dafang-Hacks#1477]
I would like to add multicams page in the UI.
I already try but I need the module setenv in lighttpd.
Someone knwon or can add this module?
I need to have it to accept Access-Control-Allow-Origin. It will use to get informations and images from another camera.

The idea is to have something like this
![image](https://user-images.githubusercontent.com/988934/83952922-c7b12180-a83c-11ea-8246-28074bc2ff44.png)

and view, basic controle, update multi cams page.

**Comment by jmtatsch** [comment]
@nik0 can you add this module?

**Comment by nik0** [comment]
Yep will do it...

**Comment by gysmo38** [comment]
Thanks a lot :)

**Comment by nik0** [comment]
@gysmo38 check latest beta

**Comment by gysmo38** [comment]
@nik0 thank you. It work bit i have another issue with cross orign and authentication. I do not manage to get pictire cam from one cam to another...
