### ISSUE TITLE
Nightview not working for new binaries 

### ISSUE THREAD

**Issue by visualus** [EliasKotlyar/Xiaomi-Dafang-Hacks#148]
Hello
I've pulled new version and updated all SD card content but unfortunately  night vision stopped working.
It looks like IR leds are not turning on or turn on just for 1-2 sec and then go off.
All I see is blackness.

I had to revert to commit cb410c55d71c0c4886da0e03416badf283aa0a35 and works fine

**Comment by wojtulab** [comment]
Its working :)

**Comment by visualus** [comment]
Thanks for the extensive comment ...
Anyway it's not working in my case. What shall I provide to narrow down the root-cause?
I have 1.3 on-board if it changes anything...

**Comment by dobseh** [comment]
Also not working for me, same versions as @visualus

**Comment by Byebyesky** [comment]
I went to fix the issue:
on line 33 in ldr.sh
`	[[ ! $SUM -eq 0 -o ! $CONFIG_LDR_AVG -eq 0 ]] && AVGMEASUREMENT=$(( $SUM / $CONFIG_LDR_AVG )) || AVGMEASUREMENT=0 # calculate the average
`
change the $CONFIG_LDR_AVG to $AVG.
After that it should work, if I know how I will send a pull request (first time commiting)

**Comment by dobseh** [comment]
Above fixed it for me, thanks!

**Comment by shinebar1001** [comment]
Thanks for the fix! cd58bd09a0cfdde0122f504f6adef8fbe4839326
