### ISSUE TITLE
Firmware buggy

### ISSUE THREAD

**Issue by Snotmann** [EliasKotlyar/Xiaomi-Dafang-Hacks#1480]
With the new firmeware versions my cams wont staring anymore ... anyone got the latest working versions here ? Autoupdate even wont work anymore:
Can not get remote file https://raw.githubusercontent.com/EliasKotlyar/Xiaomi-Dafang-Hacks/master/firmware_mod/lib/libcrypto.so.43, exiting.

**Comment by jmtatsch** [comment]
Likely the github rate limit. Try tomorrow or enter your github credentials.
