### ISSUE TITLE
Very dark and green-tinted picture since updating to a new master

### ISSUE THREAD

**Issue by jromero2k** [EliasKotlyar/Xiaomi-Dafang-Hacks#1485]
This is an issue tracking system only.
If you have general questions or are a newbie, please ask for help in our [chat channel](https://gitter.im/Xiaomi-Dafang-Hacks).

To make sure your issue can be resolved as quickly as possible please state your

Camera: Xiaomi Dafang DF3
commitid: f73542f6 I updated in May (it's an offline camera, so I don't update often)

### Description

Instead of having the usual image, everything is coming out green-tinted.

### What did you do to debug the issue

I tried different binaries, the previous fix about 22 and 23 sensors, no results.

### Evidence

![currentpic cgi~green-tinted](https://user-images.githubusercontent.com/18057757/84084079-cef93c00-a9b0-11ea-99b8-1c049e6e7e96.jpg)

### Contribute Back

If your issue was resolved, please consider contributing back to the project by creating a pull request to improve the code or documentation in order to avoid that this issue arises again for other people.

**Comment by gysmo38** [comment]
I have already same issue when swapping sd card from Dafang 1s and Dafang 1080.

You can try this 
 rm -rf /system/sdcard/etc/sensor/
reboot

**Comment by jromero2k** [comment]
It worked :)

**Comment by jromero2k** [comment]
Even though there was nothing inside /system/sdcard/etc/sensor/ it was messing up the camera

**Comment by gysmo38** [comment]
:)
