### ISSUE TITLE
[Suggestion] Zoneminder Configuration Wyzecam V2

### ISSUE THREAD

**Issue by BiatuAutMiahn** [EliasKotlyar/Xiaomi-Dafang-Hacks#1488]
under /system/sdcard/sbin/v4l2rtspserver-master.ini
```
SkipType=5
Quality=0
maxSameSceneCnt=128
```
Video Settings:
```
Resolution=960x540 (is most stable)
Format=VBR (CBR causes issues at high resolution/bitrate, smart quality isn't very good imo)
Bitrate=125-2000 (Higher than 1000 can cause corruption)
FPS=15
```
With these settings, I have nearly real-time feed <=2secs, and almost no dropouts.

**Comment by nik0** [comment]
Are you on beta branch ?
In the latest version I added MaxGop parameter, you can play this it also
Thanks for testing that ...

**Comment by BiatuAutMiahn** [comment]
np, and the biggest issue was the SkipType for me, 5 seems to have the best balance between quality/no dropout

**Comment by BiatuAutMiahn** [comment]
`Are you on beta branch ?` I usually stay with master

**Comment by Dopeyr** [comment]
I'm seeing good performance on beta branch with these settings too. TinyCam always used to drop the connection after a min or two, but now it's solid, and the stream starts quicker too.

I'm just trying work out the best settings for my camera, and which setting has helped with the drops in tinycam.

@nik0 I have a question re: `maxSameSceneCnt`, looking at https://github.com/Dafang-Hacks/Main/blob/d26974cd2cf90ecb34abdf73381242c5665d792c/v4l2rtspserver-master/inc/imp/imp_encoder.h#L183 this translates to:

>The maximum number of gop occupied in the same scene is only valid for the H1M Skip type. If it is not greater than 0, the m value will not work

So I think that means it's only effective when SkipType=IMP_Encoder_STYPE_H1M_TRUE (6)

The line below for `bEnableSceneCut` translates to:

>Whether to enable scene switching, only valid for H1M Skip type

And https://github.com/Dafang-Hacks/Main/blob/4079a7501b636fb0268d3adae6c506ad9017952e/v4l2rtspserver-master/src/ImpEncoder.cpp#L1585 says it's set to 0.

So just wondering if that means for `maxSameSceneCnt` to work, `bEnableSceneCut` must also be set to 1 and SkipType=6?

Another thing I noticed: the double frame rate issue seems to be resolved, but no matter what I set I can't get more than 20 fps. 

I've noticed that the FPS command line option `-F` no longer seems to work, but the `setconf` does (`setconf -k d -v 20,1`), but even setting it by setconf, I can only get 20 fps, despite setting it higher.

**Comment by BiatuAutMiahn** [comment]
Sensor limitations?

**Comment by nik0** [comment]
@Dopeyr ,
Yeah you are right the flag have to be set to 1. I will make a correction

And yes I deactivated -F flag is useless now.
It is the same for me, on my Dafang on full resolution: 1920*1080 I can reach only 20fps. My guess is that normal. Can you get higher framerate with the stock firmware ?

**Comment by nik0** [comment]
@Dopeyr new version pushed (you can also check the sources)
