### ISSUE TITLE
Nothing is OK :(

### ISSUE THREAD

**Issue by zajaaczki** [EliasKotlyar/Xiaomi-Dafang-Hacks#1492]
Hello 
I have Xiaofang camera with latest hack and nothing works OK.
Lags, artifacts, frozens, services can't start correct, recordings are partly poor or no recordings on sd.
Same troubles for rtsp stream. 
When I disasembled cam it looks like T20 no any signs with T20L ???
Factory firmware it works OK.

**Comment by zajaaczki** [comment]
Now cam streaming rtsp to Synology surveillance and I have a lot of logs "Lost connectivity with cam" and back again. I tested Tplink, Unifi and Mikrotik same issue. Seams to be something wrong with my Xiaofang or hack killing device performance.

**Comment by mdbrewer** [comment]
The feed takes up a lot of resources in the camera in the beta. Disable the camera in Synology surveillance station and your cameras will be responsive to ssh and web.

**Comment by zajaaczki** [comment]
Thanks. I am using camera for home security and I have to store somwhere recordings. I can't use sd recordings because usually service is broken or movies are 20% noise. How to find stable hack releases?

**Comment by mdbrewer** [comment]
It seems to be one or the other. Enable the cameras in Surveillance Station, and SSH and Web will be spotty.  Vice versa, too. 
It works on my side with with VBR video, 540 res, and 1024 bitrate. For audio try PCM.

**Comment by zajaaczki** [comment]
Damn xiao doesn't work as well as people say. I have 2 HD cameras mades from brokens Galaxy S5 and both works great in full resolution. Thanks Michael.

**Comment by zajaaczki** [comment]
I found a lot of information that rtsp is unstable also with shinobi. That means my expirience with xiaofang will over :(

**Comment by gysmo38** [comment]
@zajaaczki have you try with audio disable. On my side, it reduce the cpu load.

**Comment by zajaaczki** [comment]
Now I have 1280/720 CBR 2048 15fps with broken audio and works acceptable.
There is one strange thing: TinyCam displays variable fps up to 30fps.
