### ISSUE TITLE
Dafang kaputt?

### ISSUE THREAD

**Issue by int2018** [EliasKotlyar/Xiaomi-Dafang-Hacks#1493]
Hallo,

I use motion on a raspberry to read images from the DAFANG pan and since 20:43 no contact to the camera anymore. Today I tried to reboot, repower and reset the camera but no success. The camera does nothing when I connect the power (tried several sources).
I assume the camrea ist dead but it is straneg because it worked without problems over about 2 years.

So the question is: 
Has anybody any idea what can cause the fail? Could be some capacitor or something?
Does it make sense to try and repair it?

If I buy a new one, is the hack running on the latest firmware?

I have a EPS32 cam running (without pan/tilt and all the neat stuff) is it time to move to ESP32 ??

Thanks

**Comment by gysmo38** [comment]
The hack still work. I bought cameras a few weeks ago :) Maybe you can check your sdcard. Have you try with a new one or try to repair it ?

**Comment by int2018** [comment]
The camera does nothing when I connect it to power, with or without sdcard. No usual startup squence, motor turn, no led, etc.
I have not enough elctrical skills to find a dead capcitor or whatever the probem may be. But I thought maybe somebody knows where to look and what to ceck. 
It is a shame that everythings seems ok but now it turns into a peace of plastic waste. Replace & Repair seems not the opular way to go these days.
I thought I can "buy" some more time for this device...

**Comment by int2018** [comment]
Any electronic experts around? 
I thought before opening the trashcan I could at least open the camera and see if I can find anything obious...
Opening was easy and I took it apart. Then I connected it to power and still nothing happens. Just a chirping noise from somewhere. I touched the board with my fingers and found one very hot component, labeled with "4R7". I unplugged the power and made a picture.
![IMG_20200617_175414](https://user-images.githubusercontent.com/35401885/84921940-6ce1ba80-b0c5-11ea-9bed-4f020b789085.jpg)

I think it s a waste of time (and time is money...?) to try and find and solve the problem. 
But also, it is a shame that some not working tiny component turns this device into a peace of garbage. If resources would be finite, repairing stuff would be more an issue. 
What did you say, resources ARE finite??? hm...

**Comment by fundef1** [comment]
FYI, that looks link an inductor coil you are pointing at.
My best guess: you have a power supply issue somewhere. 
In any case don't leave it "whining" for too long, eventually the coil will short itself. (that's short, as in short-circuit - not good)

**Comment by int2018** [comment]
It is not the coil itself? 
Maybe it is "short" already and therefor it is getting hot?

**Comment by int2018** [comment]
Ok, since I could find the problem and since I don't know enough about electronic components I decided to take the camera apart and totally "converted" it. I bought a ESP32 Cam board for about 10 Euros (incl. Wifi etc.) with and 2 little step motor controller boards. It fits into the Dafang housing and I plan to re-use the step motors.
The ESP Cam can be programmed with Arduino IDE and a webserver is working (streaming). There are lots of projects out there for the ESP32. 
I will add functionality to use the stepper motors in the Dafang house for turning and hopefully I will have a "decent" replacement for the Dafang camera...
