### ISSUE TITLE
VoicePack EN 

### ISSUE THREAD

**Issue by myrmidondvb** [EliasKotlyar/Xiaomi-Dafang-Hacks#15]
http://www.share-online.biz/dl/W0R5TM0PS1L

./usr/share/Nokia.wav
./usr/share/baojing.wav
./usr/share/notify/CN/code_ok.wav
./usr/share/notify/CN/code_wrong.wav
./usr/share/notify/CN/connect_wifi_ok.wav
./usr/share/notify/CN/connecting.wav
./usr/share/notify/CN/copy.wav
./usr/share/notify/CN/dang.wav
./usr/share/notify/CN/get_msg.wav
./usr/share/notify/CN/init_ok.wav
./usr/share/notify/CN/speaker.wav
./usr/share/notify/CN/update_system.wav
./usr/share/notify/CN/upgrade_success.wav
./usr/share/notify/binbin.wav
./usr/share/notify/dang.wav

Source:
https://www.youtube.com/watch?v=BF8UFTz5BoQ

**Comment by marvinroger** [comment]
Reuploaded on GitHub, avoid having to wait to download!

[voice.zip](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/files/1542491/voice.zip)

**Comment by sharkoz** [comment]
Thanks but as I mentioned in #14 , the cam currently cannot play the .wav files as expected. I tried to copy them to the sd card and then `audioplay dang.wav` but it only makes a crackling sound.

**Comment by Shaktohh** [comment]
It's working now
 /system/sdcard/bin/ossplay /system/sdcard/share/notify/dang.wav

**Comment by lolouk44** [comment]
Thanks.
