### ISSUE TITLE
How do I know my Xiaofang 1S is a supported T20 or unsupported T20L version?

### ISSUE THREAD

**Issue by maichai** [EliasKotlyar/Xiaomi-Dafang-Hacks#1500]
The Sticker on the box says: 2019.09
Sticker on the cam: 
1S
iSC5
SENISC5
2016DP5557
MAC 44:23:7C:...

Is that a Xiaofang 1s with T20 oder is it a T20L?

**Comment by maichai** [comment]
I just tried it and it works well. No problems at all following this youtube video:
https://www.youtube.com/watch?v=fD0dH_FAjPY

**Comment by SilverWx** [comment]
where did you buy it ?

**Comment by maichai** [comment]
Ebay
