### ISSUE TITLE
How to add new user/pass for lighttpd authentication?

### ISSUE THREAD

**Issue by mr2c12** [EliasKotlyar/Xiaomi-Dafang-Hacks#1503]
I see in lighttp.user the line:
root:all:hash

I am wondering whether is possible to *add* a new user/psw to that file, or just replace the existing one with the new one.

Is it possible?
Is "all" at second place a fixed value?
How to compute the new hash?

Thanks!

**Comment by jmtatsch** [comment]
Just log in via ssh and use the command passwd to change your password.

**Comment by mr2c12** [comment]
Thanks. What if I want to change the user, too? Is it possible?

**Comment by jmtatsch** [comment]
Try useradd

**Comment by enrekatr** [comment]
Can toy specify the process please. I forget my password and newbie in programming
