### ISSUE TITLE
Time sync fails

### ISSUE THREAD

**Issue by markuznw** [EliasKotlyar/Xiaomi-Dafang-Hacks#1504]
Hello, with both master branch and beta I can't seem to have a working time sync feature. It is set by default to time.google.com but even if I change that to another NTP server time still stays at January 1970. Is there anything else I can do to fix that?
I also tried through ssh but there is no ntpdate command

**Comment by jmtatsch** [comment]
Likely you have dns problems or you didn’t have internet at startup.

**Comment by gadget78** [comment]
also see if you have configured the `staticip.conf`
and if you did make sure you also setup `defaultgw.conf` as well :) as i fell for this too !

**Comment by markuznw** [comment]
Hello and thanks for reply @gadget78. I've got both files configured:
# IP address and subnet mask
# The format must be [ip] netmask [netmask]
# Ex: 10.0.0.10 netmask 255.255.255.0
192.168.1.247 netmask 255.255.255.0

# default gateway IP address
192.168.1.1

which is my router ip (192.168.1.1) but it doesn't work. Don't have any idea on what's wrong.

**Comment by mr2c12** [comment]
I suffered from (probably) the same problem.
Please check: https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/1540

Long story short: check the filesystem on your sd, it may be (partially) corrupted.

**Comment by MrAndersonMD** [comment]
I have the same problem. First, my time zone is not available for selection (America, Chile, Santiago), and second every time I configure static ip and default gateway at staticip.conf and defaultgw.conf, time and date changes to 1967, even when time.google.com is configured as ntp server.

**Comment by nemiro-TECH** [comment]
@MrAndersonMD and @markuznw 

I have the same problem. 

Double checked and it is when I use **fix IP** it looses the time and goes back to the **70's**.
If I change through ssh and reboots the time and date updates back to the **20's** *(2020 🥇 )*

Also, update ~~brakes~~ too...

**Comment by MrAndersonMD** [comment]
Now time sync it's working on my Xiaomi camera. Don't know what worked from all the things I've done, but it's working.

**Comment by sar** [comment]
If you have an offline install, one workaround is the linux `date` set command, it's not persistent on reboot without a `hwclock` sync present.

```bash
$ date -s YYMMDDhhmm
```

**Comment by 555666555** [comment]
I am also having this issue. I cannot get the correct time to display. I've tried updating resolv.conf, staticip.conf, and defaultgw.conf with no success. Unsure if I am entering in the wrong info or if something else is happening.

**Comment by kiranbhakre** [comment]
> If you have an offline install, one workaround is the linux `date` set command, it's not persistent on reboot without a `hwclock` sync present.
> 
> ```shell
> $ date -s YYMMDDhhmm
> ```

Works for me
