### ISSUE TITLE
Support for Hikvision

### ISSUE THREAD

**Issue by SparkyRedcar** [EliasKotlyar/Xiaomi-Dafang-Hacks#1509]
Guys,

Please first of all accept my apologies if this isn’t the correct place to be posting this. I am new here and trying to learn the protocol.

I have excessively looked on here and the web in general to see if there is anything already out there to help with my request.

I have installed the hack onto my Neos Smart Cam and I have a old DVR that I would like to use as I have other cameras setup with that.

The DVR is a Hikvision Turbo  DS-7204HWI-SH, the problem it appears (I think) is that when I try and add a IP camera the only protocol available is “Hikvision” though it does have a drop down box as if options should be available.

I’ve tried adding the camera with the IP address but just won’t have it.

Any advice is much appreciated.

Thanks.

Mark

**Comment by TurfnSurf** [comment]
[manualslib.com](https://www.manualslib.com/products/Hikvision-Ds-7204hwi-Sh-3690801.html) has user manuals and guides for that DVR
