### ISSUE TITLE
Possibilities to mount a NAS

### ISSUE THREAD

**Issue by goermezer** [EliasKotlyar/Xiaomi-Dafang-Hacks#151]
Is it possible to mount a NAS with cifs, smb or nfs? Curl to FTP works. But I don`t like the overhead of the implementation in scripts.

I tried following, which works on my raspberries:

[root@dafang1~]# mount -t nfs 192.168.178.11:/volume1/Media /system/media/nas
mount: mounting 192.168.178.10:/volume1/Media on /system/media/nas failed: Permission denied

**Comment by goermezer** [comment]
Ok, solved it. This works for a Synology NAS:

mount -o nolock -t nfs 192.168.178.11:/volume1/Media /system/media/nas

**Comment by shinebar1001** [comment]
I added this to the wiki: https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/wiki/Mount-a-NFS-share
