### ISSUE TITLE
Hundreds of MQTT connections

### ISSUE THREAD

**Issue by maichai** [EliasKotlyar/Xiaomi-Dafang-Hacks#1511]
Model | Xiaomi Xiaofang 1S
Firmware date | 2020-06-21T08:01:00Z
Firmware branch | beta
Firmware commit | cbace4f ( No update available)
Kernel Version | #32 PREEMPT Wed Jan 24 02:40:56 CST 2018
Bootloader Version | U-Boot 2013.07 (Jul 05 2018 - 17:59:02)
```
console=ttyS1,115200n8 mem=41700K@0x0 ispmem=8M@0x28B9000 rmem=15644K@0x30B9000 init=/linuxrc rootfstype=squashfs root=/dev/mtdblock2 rw mtdparts=jz_sfc:256k(boot),2048k(kernel),3392k(root),640k(driver),4736k(appfs),2048k(backupk),640k(backupd),2048k(backupa),256k(config),256k(para),-(flag)
```

The camera connects to the MQTT broker over and over.
This is not only inefficient, but also floods the log file of the MQTT broker.

Normally MQTT clients would connect to the broker only once and then use that connection for all communication with the broker. They would only re-connect, if the connect breaks to external circumstances.

It would be better if the camera would also behave that way.

**Comment by Dopeyr** [comment]
See #1016 - close as duplicate?

**Comment by maichai** [comment]
Yes, it is a duplicate. The thread is quote old. Is there a particular reason why the proposed solution is not adopted, so that the alternative binaries come with the releases ad the beta?
