### ISSUE TITLE
ONVIF server not working

### ISSUE THREAD

**Issue by maichai** [EliasKotlyar/Xiaomi-Dafang-Hacks#1512]
Model | Xiaomi Xiaofang 1S
Firmware date | 2020-06-21T08:01:00Z
Firmware branch | beta
Firmware commit | cbace4f ( No update available)
Kernel Version | #32 PREEMPT Wed Jan 24 02:40:56 CST 2018
Bootloader Version | U-Boot 2013.07 (Jul 05 2018 - 17:59:02)
```
console=ttyS1,115200n8 mem=41700K@0x0 ispmem=8M@0x28B9000 rmem=15644K@0x30B9000 init=/linuxrc rootfstype=squashfs root=/dev/mtdblock2 rw mtdparts=jz_sfc:256k(boot),2048k(kernel),3392k(root),640k(driver),4736k(appfs),2048k(backupk),640k(backupd),2048k(backupa),256k(config),256k(para),-(flag)
```

The ONVIF server can be started and then runs on port 8080.
However, it does not seem to provide any information. At least Shinobi Pro is not able to get anything from the ONVIF server. Also when telling Shinobi Pro that the camera can be controlled and setting the ONVIF as interface, setting night mode throught the controls in Shinobi does not work.

Does this work for anyone else?
Does the ONVIF server need any configuration files to be changed?
Does it use any user credentials in the URL? If so, which? The Web UI admin credentials do not seem to work either.

**Comment by tERB00** [comment]
Same here - does not work

**Comment by kotjaraxx** [comment]
Тоже не рабоает. Есть решение?

**Comment by divemasterjm** [comment]
same here

**Comment by maichai** [comment]
automatically closing real issues seems not the right approach. just my 2 cents

**Comment by bas-r** [comment]
> automatically closing real issues seems not the right approach. just my 2 cents
Nope. 

It doesn't work here either. What could I supply to further investigate?
