### ISSUE TITLE
Motion Detection UI does not reflect Config file content

### ISSUE THREAD

**Issue by maichai** [EliasKotlyar/Xiaomi-Dafang-Hacks#1516]
Model | Xiaomi Xiaofang 1S
Firmware date | 2020-06-21T08:01:00Z
Firmware branch | beta
Firmware commit | cbace4f ( No update available)
Kernel Version | #32 PREEMPT Wed Jan 24 02:40:56 CST 2018
Bootloader Version | U-Boot 2013.07 (Jul 05 2018 - 17:59:02)

Even if I enable motion detection under UI Configuration > Motion Detection, the UI will will still show it not to be enabled there, but I can see that it is enabled in the config file!

**Comment by ahmadnazirafiq** [comment]
Yeah, same issue here with my Xiaofang as well. When I enabled and save Motion Detection, it doesn't actually check the box once the page refreshes.

![91039779-c3c4bc80-e63f-11ea-93b4-58c0fc09f573](https://user-images.githubusercontent.com/66505845/91185274-3016ed00-e720-11ea-9b94-f657a9a5ecbc.png)
![Screenshot 2020-08-25 at 10 00 07 PM](https://user-images.githubusercontent.com/66505845/91185282-33aa7400-e720-11ea-9edd-a955bcf936dc.png)

**Comment by maichai** [comment]
automatically closing real issues does not seem to be a valid approach.

**Comment by jmtatsch** [comment]
I totally agree. Nevertheless there are so many low quality issues its hard to manage all of this in my spare time and most are outdated after a while.

Concerning the issue, I could not reproduce it on the current master.  It likely concerns only the old UI.
