### ISSUE TITLE
LED off on startup

### ISSUE THREAD

**Issue by o0Scope0o** [EliasKotlyar/Xiaomi-Dafang-Hacks#1520]
Morning all,

Small issue that I am having with a Xiaofang: I have looked in the config files for an option to keep the blue/yellow LED permanently off, (The config dir where I have gone to set a static ip) but unable to find an option. I can turn it off in the menu of the camera but when the camera restarts the LED comes back on. 

We are using this as a baby monitor and our little one has now decided that looking at the blue LED is the best thing to do instead of sleeping! - Doh!

Any tips pointers on keeping this off via config would be great!

Thanks all!

**Comment by fanaticsurf** [comment]
On my dafang, I just greated a script "blueLED-off" in autostart with:

```
#!/bin/sh

. /system/sdcard/scripts/common_functions.sh

blue_led off
```

Make sure it is executable, and add other LEDs from common_functions.sh as you like.

**Comment by o0Scope0o** [comment]
Thanks so much, worked a treat!! - Easy when you know how!!
