### ISSUE TITLE
Autoupdate not working

### ISSUE THREAD

**Issue by markuznw** [EliasKotlyar/Xiaomi-Dafang-Hacks#1521]
Hello there!
I've got issues with autoupdate since it was changed to "commit version" and such.
I've tried with both master and beta branch clean cloned from the repo and uploaded to sd-card.
In both cases in the update page it keeps saying (actually trying with beta branch)
``
Version: commit from the beta branch
``
then on the page it says I am on the latest commit from the branch (not true)
and even pressing "Force full update" command it just triggers a (fake) reboot and stays the same. Any advice on making it work? Thanks

**Comment by Combie81** [comment]
Is the sdcard marked as read only?  It'll tell you in info panel i top left of live view screen,

**Comment by markuznw** [comment]
@Combie81 Being on beta it doesn't say anything on the UI but I guess that's the problem yeah because I moved the sdcard to computer and it said there were errors that it fixed.
But bringing it again to xiaofang the same stays, so I guess it becomes corrupted at every power cycle / after a while it is in use like reported in other opened issues here.
Is there a way to finally fix this? or need a port to ext3/4? Thanks

**Comment by Dopeyr** [comment]
@markuznw Hi, just wondering if there's something else going on, since you have issues with ntp too #1504. Does your camera have internet access, or maybe there's a DNS issue? e.g. can you `ping github.com` from the camera?
