### ISSUE TITLE
Bitrate not respected

### ISSUE THREAD

**Issue by sshaikh** [EliasKotlyar/Xiaomi-Dafang-Hacks#1529]
* exact camera hardware: Wyze V2
* Version: commit 535065f from the beta branch

### Description

Bitrate of RTSP stream to be set to value in config - has no effect.

### What did you do to debug the issue

Setconf reports its set:
```
[root@camera5:~]# /system/sdcard/bin/setconf -g d
7,1
[root@camera5:~]# /system/sdcard/bin/setconf -g b
3072
```
Tried with 1080p VBR and SMART, no effect.

### Evidence

However VLC and ffprobe report a much lower bitrate:
```
  Duration: 00:14:56.00, start: 0.001995, bitrate: 843 kb/s
```
RTSP Command in top:
```
/system/sdcard/bin/v4l2rtspserver-master -fH264 -W1920 -H1080 -E MP3:16000:44100 -r 2 -F 7 -P 554
```

### Contribute Back

If your issue was resolved, please consider contributing back to the project by creating a pull request to improve the code or documentation in order to avoid that this issue arises again for other people.

**Comment by droidmahn** [comment]
Do you have the open source uboot installed? From my understanding that's whats required to get 1080p back on the v2 as you need to set boot variables. Thats the part im bricking cameras left and right trying to do

**Comment by sshaikh** [comment]
I don't think that I have. Do you have a reference?

That said I am able to change the resolution, and 1080p does work. I think I did flash something a while back to adjust a memory config however

**Comment by droidmahn** [comment]
> 
> 
> I don't think that I have. Do you have a reference?
> 
> That said I am able to change the resolution, and 1080p does work. I think I did flash something a while back to adjust a memory config however

Ah sounds like you've already done it then
https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/hacks/flashinguboot.md

**Comment by sshaikh** [comment]
OK. Confirmed that I have that uboot (found the files and memory config checks out).

To be clear my issue isn't the resolution but the bitrate. It doesn't seem to change.

(Let me know if you need any help with the flashing, although I have to say it was pretty painless when I did it using those instructions)

**Comment by droidmahn** [comment]
> 
> 
> OK. Confirmed that I have that uboot (found the files and memory config checks out).
> 
> To be clear my issue isn't the resolution but the bitrate. It doesn't seem to change.
> 
> (Let me know if you need any help with the flashing, although I have to say it was pretty painless when I did it using those instructions)

Ah ok, thought you were having issues with both. Yeah, flashing the BL seems painless, I followed the instructions to a T (not my first rodeo with this kind of thing) but still ended up with 2 completely bricked wyze v2 cameras after reboot(no lights or clicks) . Any suggestions would be great, but I think the issue lies within the uboot itself and maybe the firmware these came with (pure speculation though)
