### ISSUE TITLE
SSH Port

### ISSUE THREAD

**Issue by nobet78** [EliasKotlyar/Xiaomi-Dafang-Hacks#153]
How can you change the SSH port?

**Comment by wojtulab** [comment]
add port number
/system/sdcard/bin/dropbearmulti dropbear -p XXXX
inside file
vi system/sdcard/run.sh

**Comment by nobet78** [comment]
@wojtulab  Dzięki :) Thanks

**Comment by rsamboceu** [comment]
Not sure if I could ask here. But I am not able to SSH into my xiaomi dafang camera. I have already hacked it and it is working but I cannot ssh. I am using putty on windows. and i tried to connect to ip address and getting doesnt exist error. Was wondering how do I ssh into the camera? Any help will do. Thank you.

**Comment by deten** [comment]
> Not sure if I could ask here. But I am not able to SSH into my xiaomi dafang camera. I have already hacked it and it is working but I cannot ssh. I am using putty on windows. and i tried to connect to ip address and getting doesnt exist error. Was wondering how do I ssh into the camera? Any help will do. Thank you.

Did you figure this out.  Trying myself with Putty using the IP address of the camera port 22 (ssh).  Doesnt work.
