### ISSUE TITLE
Increase /tmp size

### ISSUE THREAD

**Issue by Anonym-tsk** [EliasKotlyar/Xiaomi-Dafang-Hacks#1535]
I have 17Mb size of /tmp partition. And autoupdate not working.
I think, it's good idea to remount /tmp with increased tmpfs size before update in autoupdate.sh

```
mount -o remount,size=50M /tmp
```

**Comment by mjrider** [comment]
or maybe, use a temp folder on the sdcard for the update
tmpfs takes memory and there isn't enough already

**Comment by xoniq** [comment]
Came across this issue, since /tmp wasn't big enough to run `autoupdate.sh`. So this stays an issue.
