### ISSUE TITLE
Update freezes

### ISSUE THREAD

**Issue by martinschm** [EliasKotlyar/Xiaomi-Dafang-Hacks#1536]
Hi,

I have a Xiaofang Cam running the version Version: 2019-05-21T19:52:43Z of the hack. If I click the update button for the firmware upgrade the red bar progresses approximately until 25% and then freezes. Not progress for at least 10 minutes.

Is there a known issue for upgrading from this old version to the current branch?

**Comment by asecor** [comment]
Have you tried auto-updating via SSH? Example: 

ssh root@CAMERAIP 
#  cd /system/sdcard/
# ./autoupdate.sh --verbose
Starting AutoUpdate
Getting list of remote files.
autoupdate.sh needs to be updated. Overwrite?
[Y]es or [N]o or [A]ll?

**Comment by pserranoa** [comment]
I have same problem, and when I look inside the camera and execute de update I found this error

**Received zero byte file https://raw.githubusercontent.com/EliasKotlyar/Xiaomi-Dafang-Hacks/master/firmware_mod/lib/libgroupsock.so, exiting.**

Searching for the problem, I found that the volume /tmp has no space. **You can access to this folder /tmp/Update remove content**, and execute again:

```
#  cd /system/sdcard/
# ./autoupdate.sh --verbose
```

**Comment by mapa0402** [comment]
Have the same problem, come to this result:

`./autoupdate.sh: line 359: can't create 1: Read-only file system
./autoupdate.sh: line 171: can't create /system/sdcard/VERSION: Read-only file system
No files to update.`

**Comment by nemiro-TECH** [comment]
Your sdcard may be corrupted and/or file system without the correct permitions.
You can copy your important config files, format and make a fresh copy of the hack.
(If it don't fix, try another sdcard and/or try to scan the card to find corrupted sections.)
