### ISSUE TITLE
Increase OutPacketBuffer::maxSize to avoid dropped data?

### ISSUE THREAD

**Issue by Damme** [EliasKotlyar/Xiaomi-Dafang-Hacks#154]
As it sais, increase OutPacketBuffer::maxSize to avoid dropping data, I'm getting drops in the lower half of the image.

[INFO] /home/eko/Dokumente/projects/Xiaomi-Dafang-Software/v4l2rtspserver-master/src/DeviceSource.cpp:29
	MultiFramedRTPSink::afterGettingFrame1(): The input frame data was too large for our buffer size (301380).  75156 bytes of trailing data was dropped!  Correct this by increasing "OutPacketBuffer::maxSize" to at least 375156, *before* creating this 'RTPSink'.  (Current value is 300000.)

I was unable to compile your Xiaomi-Dafang-Software and make it work with the toolchain. I am probably missing something.

**Comment by Damme** [comment]
Link to what happens with too small buffer size: [https://imgur.com/a/gwZRx](url)

**Comment by boy1dr** [comment]
I'm having the same issue

**Comment by goermezer** [comment]
Same for me with bitrates above ~1000.

**Comment by jmtatsch** [comment]
Closing this as its probably outdated.

**Comment by Damme** [comment]
But has it been changed in code?

**Comment by nik0** [comment]
yes some buffer have been increased

**Comment by ParcelRot** [comment]
I am having the same problem - running the latest firmware, and it doesn't seem like the buffers were increased. Can someone point me to the code where the change was made? Thanks.

"MultiFramedRTPSink::afterGettingFrame1(): The input frame data was too large for our buffer size (301380)"
