### ISSUE TITLE
Reverting back to NEOS original firmware doesnt appear to work

### ISSUE THREAD

**Issue by asantaga** [EliasKotlyar/Xiaomi-Dafang-Hacks#1542]
This is an issue tracking system only.
If you have general questions or are a newbie, please ask for help in our [chat channel](https://gitter.im/Xiaomi-Dafang-Hacks).

To make sure your issue can be resolved as quickly as possible please state your

* NEOS cam
* the Xiaomi-Dafang-Hacks commitid (from `git log`) you are experiencing the issue with: 2c2990bad1714d44d817ac5ef6270662da84199b

### Description

Ive installed DAFANG and all works, but I wanted to go back to the original NEOS firmware. I thought I could just pull out the SD card but to no avail.. The camera just sits there (led goes yellow->blue->then yellow and stops

### What did you do to debug the issue
Tried holding the reset button on boot of the neos camera. to no avail.

I tried to redeploy the neos boot loader, by downloading the ubootin.bin file, putting on my uSD card , renaming as demo.bin and following the flash procedure. Alas nothing happened and the DAFANG hack is still working... very weird

it might be me, but I thought Id check with the community
### Evidence

N/A
### Contribute Back

If your issue was resolved, please consider contributing back to the project by creating a pull request to improve the code or documentation in order to avoid that this issue arises again for other people.

**Comment by asantaga** [comment]
just reading around. When i tried to flash the original neos firmware I couldnt find a demo.bin file so I renamed the ubootin.bin file to demo.bin..

I dont think this was right, what are the right steps?

**Comment by jamess5** [comment]
Hi all, did anyone manage to sort this? Looking to revert back to original firmware, but can't seem to do it!
