### ISSUE TITLE
Anybody kind enough build me openvpn client binary please?

### ISSUE THREAD

**Issue by trogalko** [EliasKotlyar/Xiaomi-Dafang-Hacks#1547]
This is simply a low priority request, if there is anyone that has successfully build openvpn client binary/executable for xiaofang 1S (T20 CPU), could You please kindly share it with me?
I had build it myself, following the tutorial, up until the executable were generated. Unfortunatelly, it doesn't working when executed on the camera, error message indicated that the build is not working,
Thank You so much

**Comment by tachang** [comment]
What error message did you get?

**Comment by trogalko** [comment]
Initially it complained about string not found, but after i recreate lighttpd.pem (because its not working for first time), now openvpn run but with different error message : openvpn: can't load library 'libcrypto.so.46'   . This file is exist in system/sdcard/lib, but somehow not loaded into readonly system folder : /lib or /system/lib or thirdlib. So the question now, how do i load libcrypto.so.46 to make openvpn work? Thank You
