### ISSUE TITLE
Bought a new Dafang DF3 and a Xiaofang 1S and it works!

### ISSUE THREAD

**Issue by int2018** [EliasKotlyar/Xiaomi-Dafang-Hacks#1548]
Hi everybody

this is not an "issue" but rather a hint. 
Since my "old" Dafang DF3 died, I tried to buy a new one but it is not easy to get in Germany.  Finally I ordered in China a DF3 and a little Xiaofang. It took 5 weeks but everything rrived safe.

Surprisingly the DF3 had the same label as my old one, so I am not sure if it was "new old stock" or if Xiaomi is not developing this product any further?

Anyway, I just did the 10-minute-hack-install and BOTH cameras work like a charme with the hack!
I can confirm that the Xiaofang with label 2016DP5557 works out of the box (I guess S1 with T20, Ingenic Xburst V0.1)
I can confirm taht the DF3 with the label 2017DP3894 works out of the box

Ok, the processor has limits and the device can't do wonders. The sound is poor and sometimes the video stream stops after some time (via VLC), but hey, it works!
I have one DF3 installed at my mom's house with a reduced web interface (no configuration options, just stream + pan&tilt) so friends can have a look how she is doing.

Motion detection, no chinese cloud involved, easy access. I am happy...

Once again: Thanks Elias and all contributers for all the effort for this project! Really a nice example what is possible if interested people come together and "free" the hardware :-)

Have fun and stay healthy!

**Comment by SilverWx** [comment]
I'm interested to get old Xiaofang with T20 (not t20s), can you send me the link ?

**Comment by int2018** [comment]
Hallo,
I bought on Aliexpress, about 20€ but it did not say which processor it was. It was jut luck to get the old one.
https://de.aliexpress.com/item/32884030076.html
But now it says the item is not available anymore.

So I guess you have to try some other vendor on Aliexpress.
https://de.aliexpress.com/wholesale?SearchText=+Xiaofang

Maybe you can contact the seller and ask about the sticker, as I said the one with label 2016DP5557 works...

Good luck!

**Comment by SilverWx** [comment]
I will try that, but I've asked 2-3 seller for T20 Xiaofang (not t20L) without success one month ago.

**Comment by ahmadnazirafiq** [comment]
I managed to install CFW on XiaoFang 1S and can be streamed thru its IP on the browser. However, I want to integrate it to HomeKit via Homebridge. Any working guide I could follow?

**Comment by SilverWx** [comment]
Find a tutorial to integrate rtsp flux if it is possible to do it.Le 15 août 2020 12:17, ahmadnazirafiq <notifications@github.com> a écrit :
I managed to install CFW on XiaoFang 1S and can be streamed thru its IP on the browser. However, I want to integrate it to HomeKit via Homebridge. Any working guide I could follow?
