### ISSUE TITLE
Feature idea: low power mode option

### ISSUE THREAD

**Issue by jlg89** [EliasKotlyar/Xiaomi-Dafang-Hacks#1549]
Feature idea, not an issue.

What about a "minimize power consumption" option that would disable everything but the PIR and basic network stack, unless network data is being requested or PIR detects motion and needs to record and/or send notifications? This would dramatically reduce power consumption, especially at night, which would be a nice feature for solar-powered setups. It would be a greener camera for sure.

**Comment by SilverWx** [comment]
I don't now if it's possible to enable PIR without enable RSTP server which produce the image I Think.

**Comment by int2018** [comment]
Hallo,
I think the Dafang and Xiaofang are not inteded for low power setup but if you activate Wifi (and other processes) only after motion detection, that might save some battey. But the hardware is not deisgned for "deep-sleep".

If you can live with lower image qualitiy it may be an option to check out the ESP32 "board" +camera and PIR and some coding... The hardware is available for about 10-15€.
Ok, that is a different terrain and it needs some effort with jumper wires and Arduino IDE but I got it working with this tutorial (there are more around): 
https://randomnerdtutorials.com/esp32-cam-pir-motion-detector-photo-capture

Yes, go green(er) and Have fun!

**Comment by jlg89** [comment]
The thing that prompted this idea was my experience with a Reolink Argus Eco video cam. It's a very well-executed battery-powered camera, gives good video & audio, uses very little power...basically, the only thing not to like about it is that it won't connect to anything but Reolink's app. No RTSP, no nothing. Even thirtythreeforty/neolink won't connect to it.

**Comment by jlg89** [comment]
What about adding a "Motion IR LED" switch (like the "Motion LED" switch) so it works along with the "Auto Night Detection" feature to only turn on the IR LED when it's dark and motion is detected? This alone would save significant power.

**Comment by int2018** [comment]
As far as I know the motion detection works on the amount changed pixels in the images. And if you don't have IR lights at night the image maybe to dark to detect motion. I don't know how much power individual processes need. Maybe you can disable all unnecessary processes in order reduce power consumption. I heard that even displaying the OSD date and time in the image needs some processing power. Maybe there is a list of processes which could safely be disabled of run with reduced priority?
Cheers!

**Comment by jlg89** [comment]
You're right...apparently the new Wyze Outdoor has a PIR sensor, but the others use pixel changes to detect motion.
