### ISSUE TITLE
Solution Rtsp Stream

### ISSUE THREAD

**Issue by DerMilchShake** [EliasKotlyar/Xiaomi-Dafang-Hacks#155]

**Comment by DerMilchShake** [comment]
Is it possible to change the solution of the camera?
If it is possible, where can I find this and how it works?

**Comment by shinebar1001** [comment]
You can change the resolution for v4lrtspserver like this:
`/system/sdcard/bin/v4l2rtspserver-master -W 640 -H 360`
Depending on which way you start the rtsp Server you can add the paramters in run.sh or in /system/sdcard/controlscripts/rtsp-h264 or /system/sdcard/controlscripts/rtsp-mjpeg
