### ISSUE TITLE
can't connect it with Octoprint

### ISSUE THREAD

**Issue by ragde22** [EliasKotlyar/Xiaomi-Dafang-Hacks#1550]
Hi

I try to use the Camera with octoprint

I try to use the https://ip
I try to use rtsp://ip
I try to use https://usr:pwd@ip

I try multiple ways to use it, and can't make it work
Works fine in the browser, but not with octoprint

Besides that, I configured the timezone and still showing something like "Wed Dec 31 16:37:53 PST 1969 - PST8PDT,M3.2.0,M11.1.0" 
and today is Aug 4 2020 @ 1:00AM

So, I do not know what else to do!!!

Thanks!!!!

**Comment by bakman2** [comment]
You cannot use it with octoprint. Octoprint requires a http videostream.
I have created some instructions to [make it work](https://gist.github.com/bakman2/521fd7333b4fad6602b9f9955c4fbc2c) with a workaround.

**Comment by ragde22** [comment]
Cool, I follow all the instructions and works, but same as 
"JeedHome44 commented on Feb 13
but stop work chen i close putty"
I went to your response and follow the instructions, even I had to assign password to a user call root (I do not why, because normally ask me for pi), so I just enter same password as pi user.

run "sudo restart"

and don't work, until I run it and while still in PuTTY, is working, get out and stops!! 

Thanks!!!

**Comment by bakman2** [comment]
You need to run it in the background.
