### ISSUE TITLE
Anyone got their original wyze cam pan bootloader that can share with me?

### ISSUE THREAD

**Issue by prawnz** [EliasKotlyar/Xiaomi-Dafang-Hacks#1553]
Anyone got their original wyze cam pan bootloader that can share with me?

**Comment by cameronkelley28** [comment]
Here's mine. I don't know if there's any revisions of the Pan that could have a different bootloader, but this is from a camera purchased in February.

[Wyze-Cam-Pan-original-bootloader.zip](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/files/5074939/Wyze-Cam-Pan-original-bootloader.zip)

**Comment by prawnz** [comment]
Thanks @cameronkelley28
