### ISSUE TITLE
Motion detection with Synology

### ISSUE THREAD

**Issue by DerMilchShake** [EliasKotlyar/Xiaomi-Dafang-Hacks#156]
Hello,

i connected the camera to my synology  surveillance, the live stream works, but i have problem with the motion detection.
Every time, the cam/synology detects motion, the cameria is going to be deactivated on the synology for some seconds and the recording is stopped after 1 second.
How it is possible to use the camera with motion detection and recordings on the synology?
Is there someone who has the same problem or did i a mistake on the configuration of camera?

**Comment by goermezer** [comment]
On Synology I even could not view the rtsp-h264 live stream. Recordings were created, but when viewing them in the internal viewer, it says that the stream was already deleted ?! For me there is something wrong with the stream itself or while capturing the stream to Synology.

So I decided to record the rtsp-h264 live stream with ffmpeg and external motion detection from a PIR sensor, which is connected to OpenHAB. I used this command, when motion was detected:

ffmpeg -i rtsp://@192.168.178.100:8554/unicast -acodec copy -vcodec copy /media/nas/Kameras/camera6/`date +%d-%m-%Y_%H.%M.%S`.mp4

This works not good enough for me. Fffmpeg quickly starts recording the stream to NAS. But the resulting mp4 file always shows the video after the first 6-8 seconds in VLC. So the most important part of the recording is not visible.

I`m still searching for a better solution to record as instantly as possible. For me only "getimage" is quick enough. But that`s only a static image...

**Comment by goermezer** [comment]
Avconv instead of ffmpeg seems to react much faster on my Raspberry. The 6-8 seconds gap and a bit of scrambling starting the video seems gone with this:

> avconv -rtsp_transport tcp -y -i rtsp://192.168.178.100:8554/unicast -vcodec copy -c:a aac -strict experimental /media/nas/Kameras/camera6/`date +%d-%m-%Y_%H.%M.%S`.mp4

**Comment by helio58** [comment]
One question @goermezer @DerMilchShake how long do you have your cameras running?
Mine stop stream same time, and cannot be reach via ssh or http have to manually restart.
Sorry I know is not the topic.

**Comment by goermezer** [comment]
@helio58 good power supply is important. I use the original from Raspberry foundation. RPI3s seem more stable than RPI2 regarding WIFI. And the cams don`t have to be too far away from the access point. Then they run quite stable for a long time. Nevertheless I have a cron job on each of them, which reboot them every evening, in case that they want not connect to the access point.

Since two weeks I placed an additional  access point (more professional one from Ubiquity) into my house. Since then I noticed, that the cams often connects to it, even though it is round about 5m plus a wall away than the old one. That speaks for bad german routers (FritzBox 7490 in my case)...

One more thing: The FritzBox 7490 has 5G and 2,4G Wifi. If I switch off 5G, I have much more range with 2,4G Wifi - in case you need a little bit better reception at your cams.

**Comment by helio58** [comment]
@goermezer thanks ,
I see I m using the power supply that was in the camera box + one adapter.
I m using a Asus router with very good range.
I ran the original software for one week, without any problem with the stream.
One off the reason to use this mod is to be able to see/download the notifications.
Plus at the system is at my place.
I have used ContaCam for motion detection works well the beta version.
Its windows but there is a possibility to use in wine. I haven't test.

**Comment by lamiskin** [comment]
@DerMilchShake I am experiencing the same issues, can add the camera in surveillance station, but recordings are 1 second and the camera constantly disconnects. I've been able to use many cameras with surveillance station over the years, but it seems something in particular with this stream does not work well with the synology.

**Comment by Adriien-M** [comment]
I had the same issue : synology recorded multiple videos of several seconds each.
After many tries, I finally found a solution. The trick is to switch the `Transport Protocp` from `Auto` to `TCP` in the advanced settings of the camera (in RTSP configuration section).

Here is a screenshot (sorry it is in French) :
![capture](https://user-images.githubusercontent.com/927834/37605071-b6c0659e-2b92-11e8-9be4-a674801761a3.JPG)

Hope it helps...

**Comment by helio58** [comment]
@Adriien-M 
THANKS works very well.

**Comment by shinebar1001** [comment]
Thanks, @Adriien-M  - I added it to the wiki

**Comment by lamiskin** [comment]
It is still not working for me after changing the transport to TCP.

**Comment by helio58** [comment]
I have it running since 4 days , works great

**Comment by Adriien-M** [comment]
@lamiskin Try to disable audio it might work...

**Comment by lamiskin** [comment]
Thanks @Adriien-M, on first test disabling the audo seems to be working 👍

**Comment by DerMilchShake** [comment]
I have to change the transport protocol to **UDP**, now it works for me too.

**Comment by jmtatsch** [comment]
Closing this because the knowledge is in the wiki.
