### ISSUE TITLE
theme cookie lifespan

### ISSUE THREAD

**Issue by mikeage** [EliasKotlyar/Xiaomi-Dafang-Hacks#1561]
### Description

The theme cookie is currently set with an expiration of "session" https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/firmware_mod/www/scripts/index.html.js#L175

Any objection to making this a more-or-less-forever cookie that expires in 2038?

### What did you do to debug the issue

https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/firmware_mod/www/scripts/index.html.js#L175

### Evidence

https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/firmware_mod/www/scripts/index.html.js#L175

### Contribute Back

will do soon, if approved

**Comment by jmtatsch** [comment]
Makes sense imho, please whip up a pull request.
