### ISSUE TITLE
Auto Reboot the rtsp or device when rtsp goes out?

### ISSUE THREAD

**Issue by KaneHart** [EliasKotlyar/Xiaomi-Dafang-Hacks#1569]
Sadly since I started using Beta or Normal version I always have rtsp seem to crash after several hours. I'm wondering if anyone made a script that can auto reboot the entire device when it happens or even on a timer so I can have it more stable.

Thanks.

**Comment by MrAndersonMD** [comment]
Please fix this, it' s the only actual problem with the firmware. Thanks in advance.

**Comment by KaneHart** [comment]
This issue is as stale as waiting for it to be fixed :(

**Comment by jmtatsch** [comment]
There were some posts about cron jobs to restart the rtspserver frequently. Maybe you can find them?

**Comment by jmtatsch** [comment]
https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/1100
