### ISSUE TITLE
Bug with MQTT Autodiscovery when using Ethernet

### ISSUE THREAD

**Issue by stoickish** [EliasKotlyar/Xiaomi-Dafang-Hacks#1570]
When using USB-over-Ethernet, the script [here](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/firmware_mod/scripts/mqtt-autodiscovery.sh) seems to silently fail at populating the MAC & MAC_SIMPLE variables, which has the effect of making the "identifiers" set to a blank value.  This seems to break some things "down stream" such as Home Assistant once you have more than one of these cameras running on Ethernet.

The problem seems to be just that when you're using USB-over-Ethernet, the MAC address is not found in this file:
/sys/class/net/**wlan0**/address

but rather, it is found here:
/sys/class/net/**eth0**/address

A solution to this seems to be just doing something like this:

```
if [ -f /sys/class/net/wlan0/address ]; then
MAC=$(cat /sys/class/net/wlan0/address)
MAC_SIMPLE=$(cat /sys/class/net/wlan0/address | tr -d :)
elif [ -f /sys/class/net/eth0/address ]; then
MAC=$(cat /sys/class/net/eth0/address)
MAC_SIMPLE=$(cat /sys/class/net/eth0/address | tr -d :)
else
MAC="Unknown"
MAC_SIMPLE="Unknown"
fi
```

**Comment by jmtatsch** [comment]
Can you whip up a pull request for this?
