### ISSUE TITLE
Night mode working bad, ir leds issues... (Xiaomi Dafang)

### ISSUE THREAD

**Issue by Ayo91** [EliasKotlyar/Xiaomi-Dafang-Hacks#1571]
I have the firmware installed in two Xiaomi Dafang cameras since some months, I usually update the firmware and I have the latest one.

Since the begining I have issues with the night mode, its not working fine:

1. Sometimes the camera is in day mode during the night and when I access throught the UI to the SW auto night setting view, then the switch to night mode is done.
2. I think when IR Filter is enabled, the night mode doesnt work. Is it the same for you?
3. After enable the night mode and verify with the mobile phone that the leds are working, I have really bad results, the rooms are very dark. It seems the leds are not working with **the same power** as with the original firmware. 

I have the defaults values set...
![image](https://user-images.githubusercontent.com/2479896/92995473-f0138080-f4fb-11ea-8be5-46343aa9926b.png)

Any advice?

**Comment by TheRealWaldo** [comment]
Having exactly the same issues here.  Did you ever find a resolution?
