### ISSUE TITLE
Dafang cameras is not change video format

### ISSUE THREAD

**Issue by SAOPP** [EliasKotlyar/Xiaomi-Dafang-Hacks#1574]
Hi!

I have an three Dafang cameras at latest at current moment beta branch with commit 1169b21. Not one of the cameras can't change the video format, after clicking to save button, next window with parameters is opened, but nothing is changed.

Before this commit the issue is present too also. 

Any suggestion? Thanks.

**Comment by SAOPP** [comment]
Guys any suggestions?

**Comment by drkdoesgit** [comment]
Just to confirm, whenever you change the Video Size under **Camera Configuration** > **Format** it always defaults to 640x360?

If so, the issue lies on the file \Xiaomi-Dafang-Hacks\firmware_mod\www\cgi-bin\ui_camera.cgi at line 25. The system loads the saved value onto the **RTSPH264OPTS** variable whereas we save the new value to **RTSPOPTS** at line 62. Going to the configuration file \Xiaomi-Dafang-Hacks\firmware_mod\config\rtspserver.conf(.dist) at line 36, the actual value is saved to  **RTSPOPTS**.

Just change line 25 of ui_camera.cgi to the one below and you should be fine.

`echo "videoSize#:#${RTSPOPTS}"`

I don't have write access to the repo so I am unable to push my change. Sorry.

**Comment by jmtatsch** [comment]
Please test if that fixes the issue.

**Comment by Markie1306** [comment]
> Please test if that fixes the issue.

It seems that it fix the issue. Thanks.

**Comment by SAOPP** [comment]
Sorry guys, I missed the answer... I have the last beta and no changes, the only the resolution is now saved correctly, I set the resolution and it remains, but the picture doesn't change.

**Comment by SAOPP** [comment]
![Uploading Kazam_screencast_00004.gif…]()

**Comment by Markie1306** [comment]
I'm using the latest beta for my Xiaomi Xiaofang 1S and i'm able to set a different resolution.

**Comment by SAOPP** [comment]
Yes, but I'm talking 'bout Dafang.

**Comment by SAOPP** [comment]
@jmtatsch the issue is not gone, the result of the save the same, digits is changed and video resolution is not, 640x360.

**Comment by SAOPP** [comment]
![image](https://user-images.githubusercontent.com/5647009/98444717-e2edc900-211b-11eb-849a-5519bc9b9653.png)

**Comment by SAOPP** [comment]
So guys, it's beta branch bug ot what?

**Comment by jmtatsch** [comment]
Master and beta are almost the same right now. Can you please verify that stuff is actually written into the config file. Then look if it's that config file that is actually load it went running the rtsp service.￼￼

**Comment by SAOPP** [comment]
@jmtatsch Could u please explain again exactly where and what to check?

**Comment by jmtatsch** [comment]
Okay, so the changed video format is written properly to the config file and picked up on a reboot of the camera.
It seems like the rtspservice is not properly restarted after applying the settings.

**Comment by jmtatsch** [comment]
Actually, it seems to be working as expected for me.
Maybe you have a read only file system on the camera.
Is there a red notification on upper right corner of your ui?

**Comment by SAOPP** [comment]
> Okay, so the changed video format is written properly to the config file and picked up on a reboot of the camera.
> It seems like the rtspservice is not properly restarted after applying the settings.

Is this a statement of a problem or what?



> Actually, it seems to be working as expected for me.
> Maybe you have a read only file system on the camera.
> Is there a red notification on upper right corner of your ui?

On three cameras, read-only? And what could have led to this?

![image](https://user-images.githubusercontent.com/5647009/99147148-3cf40e80-2687-11eb-844b-f66f5e54ec48.png)

Where should I see the red notification?

**Comment by SAOPP** [comment]
I will add again, I have 3 cameras, and I cannot set the resolution on all three cameras.

**Comment by SAOPP** [comment]
```
rootfs on / type rootfs (rw)
/dev/root on / type squashfs (ro,relatime)
tmpfs on /dev type tmpfs (rw,relatime)
proc on /proc type proc (rw,relatime)
devpts on /dev/pts type devpts (rw,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /tmp type tmpfs (rw,relatime)
tmpfs on /run type tmpfs (rw,nosuid,nodev,relatime,mode=755)
sysfs on /sys type sysfs (rw,relatime)
media on /media type tmpfs (rw,relatime)
/dev/mtdblock3 on /driver type squashfs (ro,relatime)
/dev/mtdblock4 on /system type jffs2 (rw,relatime)
/dev/mtdblock7 on /backupa type jffs2 (rw,relatime)
/dev/mtdblock8 on /configs type jffs2 (rw,relatime)
/dev/mtdblock9 on /params type jffs2 (rw,relatime)
/dev/mmcblk0p1 on /system/sdcard type vfat (rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro)
/dev/mmcblk0p1 on /bin/busybox type vfat (rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro)
/dev/mmcblk0p1 on /root type vfat (rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro)
/dev/mmcblk0p1 on /etc type vfat (rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro)
```

**Comment by jmtatsch** [comment]
You can find a read only file system warning at the bell icon of the upper right corner of your ui.
According to you screenshot your filesystem seems fine.

To debug, connect to your camera via ssh
and 
`cat  /system/sdcard/config/rtspserver.conf`
to display the contents of your configuration.

Watch if it changes when you change and save something in the ui.

Something might have gone foul with a software update. I would recommend wiping you sdcard and start with a fresh checkout of the hack.

**Comment by SAOPP** [comment]
![image](https://user-images.githubusercontent.com/5647009/99147463-c99fcc00-2689-11eb-9dc5-7c6ea8f0e28d.png)
![image](https://user-images.githubusercontent.com/5647009/99147474-dcb29c00-2689-11eb-925d-dd769ff5fa61.png)
![image](https://user-images.githubusercontent.com/5647009/99147478-e6d49a80-2689-11eb-9009-d7cf49851707.png)

As u can see, 640x360 has changed to 768x432, but nothing effect at the rtsp stream. :(

**Comment by SAOPP** [comment]
Here is my working services:

![image](https://user-images.githubusercontent.com/5647009/99147515-4fbc1280-268a-11eb-8e0a-3e48e0d2f413.png)

**Comment by jmtatsch** [comment]
Can you start the rtsp service pls? are the changes picked up then?
You are on the latest commit from this morning?

**Comment by SAOPP** [comment]
Yes, this camera updated to 4 latest commits... one seconds, I changed config manually and rebooting the camera...

**Comment by SAOPP** [comment]
I also trying rtsp switch, nothing happens... I will try again.

**Comment by SAOPP** [comment]
Changed this manually, one reboot, after this second and reboot, nothing :( 640...

![image](https://user-images.githubusercontent.com/5647009/99147672-77f84100-268b-11eb-8059-a7ba91d371ef.png)

**Comment by SAOPP** [comment]
Turn on rtsp service, rebooting camera, nothing. :| What I can do else buddy? Another sd card or what? ..and of course I tried to re pull full branch. :(

**Comment by jmtatsch** [comment]
That parameter is now called RTSPOPTS, should be further down your config file.
You could also try deleting that config file, then it should reinitialize from the current .dist file.

**Comment by SAOPP** [comment]
ok, it looks like I've the ability to set 940x... strange but 768x is nothing the effect.

well, I'll play some more, on one camera I deleted the rtsp configuration file, on others I just turned on the rtsp service (now I can see that it restarts after applying a new resolution in the log in the last line), and also updated all 3 cameras to the last commit.
