### ISSUE TITLE
Unable to Enable Motion Detection for Dafang/XiaoFang

### ISSUE THREAD

**Issue by ahmadnazirafiq** [EliasKotlyar/Xiaomi-Dafang-Hacks#1575]
I've tried this hack for both my XiaoFang and Dafang camera. Everything works well except for the Motion Detection that refused to enable despite me checking the box, saved, rebooted... it always goes back Unchecked.

Anyone having the same issue? I have no idea what's wrong as both cameras exhibit the same issue with the custom firmware.

![Screenshot 2020-09-14 at 10 37 26 AM](https://user-images.githubusercontent.com/66505845/93038097-a8653400-f676-11ea-89a6-90654e189742.png)

**Comment by icebrian** [comment]
I also noticed that same behaviour, but it seems that motion detection is being activated, it's just the webinterface that is not reflecting the activation when you reload the page.

You can check in this file: /system/sdcard/config/motion.config

If even after making sure it is activated you still can't get motion detection it might be due to lack of RAM. Check here for more info: https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/1567

**Comment by ahmadnazirafiq** [comment]
> I also noticed that same behaviour, but it seems that motion detection is being activated, it's just the webinterface that is not reflecting the activation when you reload the page.
> 
> You can check in this file: /system/sdcard/config/motion.config
> 
> If even after making sure it is activated you still can't get motion detection it might be due to lack of RAM. Check here for more info: #1567

Hi, thanks for your suggestions. I have enabled Swap to True but I'm still not getting motion detection notification. FYI, since you are getting notification via email however I'm trying to integrate this with HomeKit using Homebridge, so I'd expect it to work considering the camera itself recognized the motion (denoted with red dot).

Unfortunately it still doesn't :(

Btw, did you set up MQTT broker yourself by connecting to existing one or host MQTT using MongoDB? According to this (https://github.com/sahilchaddha/homebridge-dafang/blob/master/Setup_MQTT.md) I'm stuck here on finding mongoURL.

**Comment by icebrian** [comment]
Glad it works!

Not using homebridge so can't help with that.

**Comment by ahmadnazirafiq** [comment]
Haha no worries! Appreciate your help 👍
