### ISSUE TITLE
Telegram bot video alerts are broken on my wyze camera v2.

### ISSUE THREAD

**Issue by codaine420** [EliasKotlyar/Xiaomi-Dafang-Hacks#1576]
So I got the telegram bot all set up and working on my wyze camera v2 and I can get the image alerts to work just fine, I get a nice clear picture when motion is detected. But with video alerts, half of the videos it records are glitchy. Some record just fine, and other start being fine after a few seconds. What can I do to fix this? It seems like if there isn't like, enough motion, or a big enough object moving, then it doesn't record right.. but idk.. any help would be appreciated! I have sample clips to help explain.

**Comment by codaine420** [comment]
https://drive.google.com/file/d/1MIoUEcis80jpNrRVzuTt3Du3JuD42nOh/view?usp=drivesdk

https://drive.google.com/file/d/1MIkJmfh6cVCsjvWw-cK7-TPTEQ8hU6Me/view?usp=drivesdk

Also there is no audio....

**Comment by dvybornov** [comment]
Hello. I have the same problem on Xiaofang T20 and Dafang cameras. All image alerts works fine but all videos are broken (white screen or too small bitrate). Also there are no any sounds in video. 
Here are examples of video:
https://yadi.sk/d/XmDP_2Fllv882Q
https://yadi.sk/i/eqcZwLhyW-REBA

**Comment by codaine420** [comment]
I made a little bit of progress... i got audio to work now kind of, its distorted sometimes.. but its there. and the video seems to have gotten a little bit better, itll start all green and weird but then get clear a few seconds in. it also seems like the video is in slow motion cause objects move slowly and the audio doesnt last through the whole video. ive been playing with the config/script files, camera settings, doing all i can think of but i dont know what else to try now. im posting my settings so maybe @dvybornov can get your audio working too. [Audio Settings](https://imgur.com/zEgd0X4),   [Video Settings](https://imgur.com/mQY7qnj)
