### ISSUE TITLE
PTZ control not working over MQTT or web interface when Onvif service is enabled

### ISSUE THREAD

**Issue by radinsky** [EliasKotlyar/Xiaomi-Dafang-Hacks#1580]
Reopening #1318 
Once the Onvif service enabled, PTZ control stops working, both from MQTT and Web (even calibrate is not responding).
Anybody found the way to use both Onvif and PTZ? 
Thanks!

**Comment by sedony23** [comment]
I also didn't manage to get both working. Would be great if somebody could look into that...
