### ISSUE TITLE
What is the best way to record live stream?

### ISSUE THREAD

**Issue by nemonein** [EliasKotlyar/Xiaomi-Dafang-Hacks#1585]
This is an issue tracking system only.
If you have general questions or are a newbie, please ask for help in our [chat channel](https://gitter.im/Xiaomi-Dafang-Hacks).

To make sure your issue can be resolved as quickly as possible please state your

* exact camera hardware:
* the Xiaomi-Dafang-Hacks commitid (from `git log`) you are experiencing the issue with:

### Description

Describe what you were trying to achieve.
Tell us what happened and what you expected to happen.

### What did you do to debug the issue

Tell us what you did to remedy/debug the issue yourself and what you think causes the issue.

### Evidence

Please add snippets from the logfiles in:
* /system/sdcard/log/startup.log
* /var/log/*
* dmesg
* logcat
and/or screenshots you deem relevant.

### Contribute Back

If your issue was resolved, please consider contributing back to the project by creating a pull request to improve the code or documentation in order to avoid that this issue arises again for other people.

---------------------------

Sorry, it's not actually an issue. If it's not appropriate, this message can be deleted.
Hello. I'm using Xiomi Dafang, and it works fine.
Here are my settings.

```
RTSP h264 server ON
Video : 1920x1080 / CBR / 24 fr / 1500kbps
Audio : PCMU 8000 / 8000 / No filter at all
```

On TinyCam, though it stops sometimes, but most of the time works fine.

I'd like to record the stream, I made a script on my SBC(Cubietruck) using ffmpeg.

```
#!/usr/bin/bash

ffmpeg -rtsp_transport tcp \
 -fflags nobuffer \
 -an \
 -i rtsp://ip:port/unicast \
 -map 0:v \
 -c copy \
 -metadata title="" \
 -f segment \
 -segment_time 60 \
 -segment_wrap 100 \
 -strftime 1 \
 "/file-%Y%m%d-%H%M.mp4"
```

However, ffmpeg stops working without any possible reasons. It just freezes.
I roughly guess when the stream signal is lost(or something like that), ffmpeg keeps waiting for it, but could not connect to the rtsp server, then freezes. There is usually no special error messages.

So, can you suggest a good solution for recording the stream file?
I want to record the video on the other machine, not from the Dafang itself.

**Comment by nemonein** [comment]
No one cares about this...

**Comment by ryaske** [comment]
Pretty sure this is because of the quality of the camera and limited processing capabilities. It just cant handle what we are asking of it, and the symptoms are why/how its possible to fit the price point. Just wish there was a way to prove it.

It's like the wifi chip cant handle some type of broadcast or something, and loses its mind for the 20 seconds or so it takes to gather itself back again. I can see this clearly when viewing the RTSP feed in VLC. I found it got a little better if I use FixedQP instead of the VBR I was using prior

**Comment by nemonein** [comment]
Thanks @ryaske .
It's sure there's no way to fix this, I close this issue.

**Comment by int2018** [comment]
Hi,
I just read your post and tried your ffmpeg command. What can I say, it works and keeps creating mp4 files.
(but mwith this command there is no audio recording)

I have ffmpeg running on a Raspberry 3+ (not the high-end recording machine) and the camera is in some other place, access via intrernet and some dyndns service.

Here is the output:

**pi@raspberrypi:~ $ ./record.sh**
ffmpeg version 3.2.14-1~deb9u1+rpt1 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 6.3.0 (Raspbian 6.3.0-18+rpi1+deb9u1) 20170516
  configuration: --prefix=/usr --extra-version='1~deb9u1+rpt1' --toolchain=hardened --libdir=/usr/lib/arm-linux-gnueabihf --incdir=/usr/include/arm-linux-gnueabihf --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libebur128 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-omx-rpi --enable-mmal --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libiec61883 --arch=armhf --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 34.101 / 55. 34.101
  libavcodec     57. 64.101 / 57. 64.101
  libavformat    57. 56.101 / 57. 56.101
  libavdevice    57.  1.100 / 57.  1.100
  libavfilter     6. 65.100 /  6. 65.100
  libavresample   3.  1.  0 /  3.  1.  0
  libswscale      4.  2.100 /  4.  2.100
  libswresample   2.  3.100 /  2.  3.100
  libpostproc    54.  1.100 / 54.  1.100
[mp3 @ 0xb9c600] Header missing
Input #0, rtsp, from 'rtsp://**xxx.xx:port**/unicast':
  Metadata:
    title           : LIVE555 Streaming Media v2020.05.15
    comment         : LIVE555 Streaming Media v2020.05.15
  Duration: N/A, start: 0.349211, bitrate: N/A
    Stream #0:0: Video: h264 (Main), yuv420p(progressive), 1600x900, 25 fps, 48 tbr, 90k tbn, 50 tbc
    Stream #0:1: Audio: mp3, 16000 Hz, mono, s16p, 24 kb/s
[segment @ 0xbb6490] Opening '/home/pi/videos/xxx-20210221-1708.mp4' for writing
Output #0, segment, to '/home/pi/videos/xxx-%Y%m%d-%H%M.mp4':
  Metadata:
    comment         : LIVE555 Streaming Media v2020.05.15
    encoder         : Lavf57.56.101
    Stream #0:0: Video: h264 (Main), yuv420p(progressive), 1600x900, q=2-31, 25 fps, 48 tbr, 12800 tbn, 25 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
Press [q] to stop, [?] for help
[segment @ 0xbb6490] Opening '/home/pi/videos/xxx-20210221-1709.mp4' for writing
[segment @ 0xbb6490] Opening '/home/pi/videos/xxx-20210221-1710.mp4' for writing
[segment @ 0xbb6490] Opening '/home/pi/videos/xxx-20210221-1711.mp4' for writing
[segment @ 0xbb6490] Opening '/home/pi/videos/xxx-20210221-1712.mp4' for writing
[segment @ 0xbb6490] Opening '/home/pi/videos/xxx-20210221-1713.mp4' for writing
[segment @ 0xbb6490] Opening '/home/pi/videos/xxx-20210221-1714.mp4' for writing
frame= 4757 fps= 12 q=-1.0 Lsize=N/A time=00:06:39.89 bitrate=N/A speed=1.01x
video:25550kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown

Stopped with 'q' key... 

The video settings of the DAFANG camera are:
VideoSize: 1600x900
Bitrate: 512 kbps
Format: VBR
Framerate: 12 fps

I think the by reducing the video stream quality you might get it working.

Good luck!
