### ISSUE TITLE
compatibility with IP Camera Adapter 3.1

### ISSUE THREAD

**Issue by Psudonico** [EliasKotlyar/Xiaomi-Dafang-Hacks#159]
Hi all,
I'd like to use Dafang with Skype.
Do you know if is compatible with IP Camera Adapter 3.1?
http://ip-webcam.appspot.com/

Do you know alternatives?

Thanks

**Comment by shinebar1001** [comment]
As this application is able to use a mjpeg stream it should work with Dafang Hacks

**Comment by Psudonico** [comment]
I've tried but it crashes.
I've used  http://192.168.84.106:8554/unicast.m3u8 and  http://192.168.84.106:8554/unicast.mpd links but not works

**Comment by shinebar1001** [comment]
You have to enable the mjpeg-stream and use this URL: rtsp://192.168.84.106:8554/unicast

**Comment by Psudonico** [comment]
I've tried but when I click on "autodetect" the result is "no data received".
Seems that you can use only http addresses.
Do you know alternatives?

**Comment by shinebar1001** [comment]
How  about manycam? https://manycam.com/features/ (just googled it, got no experience)

**Comment by Psudonico** [comment]
Thank you

**Comment by shinebar1001** [comment]
so, I'll like to Close the issue - feel free to reopen it :)
