### ISSUE TITLE
Viewer not working

### ISSUE THREAD

**Issue by josephdouce** [EliasKotlyar/Xiaomi-Dafang-Hacks#1591]
This is an issue tracking system only.
If you have general questions or are a newbie, please ask for help in our [chat channel](https://gitter.im/Xiaomi-Dafang-Hacks).

To make sure your issue can be resolved as quickly as possible please state your

* exact camera hardware: 
Neos
* the Xiaomi-Dafang-Hacks commitid (from `git log`) you are experiencing the issue with:
Dafang Hacks Version: commit 406cf52 from branch master Issues?

### Description

The viewer download links do not work as they are pointing to a file that is not exposed by the the http server, DCIM is in the parent directory of the www folder. I tried ln -s /system/sdcard/DCIM /system/sdcard/www/viewer but i was unable to create the link. 

### What did you do to debug the issue

Tell us what you did to remedy/debug the issue yourself and what you think causes the issue.

### Evidence

Please add snippets from the logfiles in:
* /system/sdcard/log/startup.log
* /var/log/*
* dmesg
* logcat
and/or screenshots you deem relevant.

### Contribute Back

If your issue was resolved, please consider contributing back to the project by creating a pull request to improve the code or documentation in order to avoid that this issue arises again for other people.

**Comment by klutchell** [comment]
This still looks broken to me, the viewer paths in the Web UI all return 404.

**Comment by jmtatsch** [comment]
Hmm, cannot reproduce. Just downloaded a motion movie and a jpg file from time lapse. Even the viewer showed the jpeg file. Try to start fresh also with fresh config.

**Comment by klutchell** [comment]
Cool, with a new config it works fine. Thanks!
