### ISSUE TITLE
ISSUE  with JPEGOPTIM

### ISSUE THREAD

**Issue by alexloza1965** [EliasKotlyar/Xiaomi-Dafang-Hacks#1596]
* exact camera hardware:   Xiaomi Small Square Smart Camera

* the Xiaomi-Dafang-Hacks commitid (from `git log`) you are experiencing the issue with:   currentpic.cgi  with jpegoptim

### Description

I want to optimize size of image received by /cgi-bin/currentpic.cgi.

For this I tried to use additional jpegoptim command in /cgi-bin/currentpic.cgi like this:

/system/sdcard/bin/getimage | /system/sdcard/bin/jpegoptim -m70 --stdin --stdout

That i see:
1st received image is OK, but 2nd, 3d and all others are the copies of 1st image.
So jpegoptim optimize image only ones and then use old image as output for all other attempts to receive new one.

It seems to me the problem is in jpegoptim. May be it makes sense to reassemble its new version?

### What did you do to debug the issue

I tried to use another camera. The same model.
I tried to use different options with jpegopt and they combinations, among them:
-s (--strip-all) - Strip all markers from output file
-o (Overwrite target file even if it exists)
-p (Preserve file modification times)
-P (Preserve file permissions)
--all-progressive

### Evidence

https://s.mail.ru/vVwt/4eNhcPhcY

**Comment by nik0** [comment]
Getimage is updated only every seconds. Did you add a “sleep” between the calls ?

**Comment by alexloza1965** [comment]
I receive image 1 time per min. Not faster.
