### ISSUE TITLE
Any way to get a sub stream or lower quality stream?

### ISSUE THREAD

**Issue by maxiedaniels** [EliasKotlyar/Xiaomi-Dafang-Hacks#160]
Is there any way to lower the quality and/or resolution of a stream? Specifically the RTSP stream?

**Comment by shinebar1001** [comment]
Change resolution:
https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/wiki/change-the-resolution-of-the-Video
Change Bitrate:
https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/wiki/Parameters-for-setconf

**Comment by saipsa** [comment]
@shinebar1001 Where to pass that parameter, it is not clear to me from the wiki.
