### ISSUE TITLE
Client mosqpub|1403-Voortuin disconnected.

### ISSUE THREAD

**Issue by Sloth-on-meth** [EliasKotlyar/Xiaomi-Dafang-Hacks#1608]
MQTT does not work. it just spams the shit out of my broker with xxx-devicename where xxx starts as 0 and increments by 1 with every connection attempt. this crashes my mqtt broker.

hostname | Voortuin
-- | --
Model | Xiaomi Xiaofang 1S
Firmware Version | 2020-04-21T11:36:25Z
Kernel Version | #32 PREEMPT Wed Jan 24 02:40:56 CST 2018
Bootloader Version | U-Boot 2013.07 (Jul 05 2018 - 17:59:02)

Local Time | Wed Oct 28 16:44:38 CET 2020
Uptime | 2m
Load Average | 2.34, 0.77, 0.27

i tried updating from the interface but this is seemingly the newwest version

**Comment by hugalafutro** [comment]
I'm using beta branch on 2 neos smartcams and mqtt works on both. Yes, they spam the broker, but they don't crash it. My broker is eclipse-mqtt running in a docker on RPi 3B+. So maybe try beta if you're on master (or vice versa)

Btw, the xxx goes way up to xxxxx :) `1603921074: New client connected from 192.168.1.170 as mosqpub|29934-dafang-in (p1, c1, k60, u'mosquitto').`  

MQTT broker uptime is 6days atm.
Camera:

Firmware date: | 2020-10-01T07:01:36Z
-- | --
Firmware Branch: | beta
Firmware Commit: | 74480c8 ( No update available)
Kernel Version: | #21 PREEMPT Thu Oct 19 11:38:16 CST 2017
Bootloader Version: | U-Boot 2013.07 (Jul 05 2018 - 13:33:27)

Local Time: | Wed Oct 28 21:42:12 GMT 2020
System Uptime: | 13d, 8h, 29m
Load Average: | 1.80, 1.83, 1.77

**Comment by Sloth-on-meth** [comment]
Still broken
