### ISSUE TITLE
Recording don't work

### ISSUE THREAD

**Issue by adicrescenzo** [EliasKotlyar/Xiaomi-Dafang-Hacks#1609]
Camera Hardware: **Xiaomi Dafang**
Commit **2948300** from branch **master**

Problem description:

If I start the recording script it will be stopped immediatly and nothing will get record. The live streaming works properly.
I tried to launch the script from the web ui and also via ssh but the result is the same.
I noticed that the file /run/recording.pid is created but the process get killed immediately.
Anyone knows how to solve this issue?
 
Thanks in advance

**Comment by Sloth-on-meth** [comment]
not working here either, it's missing from the UI too

**Comment by jmtatsch** [comment]
There is a little camera button for recording on the lower right corner of the image.
Its only visible on mouse over though.
I just verified, for me recording still works on a recently freshly configurated camera.
The files end up here /system/sdcard/DCIM/Recording/2020-11-24/22/REC_22-00-29.h264 and are non-zero.

**Comment by jmtatsch** [comment]
@adicrescenzo  you should update to a more recent commit, there were a lot of changes to master recently.

**Comment by ryaske** [comment]
I find recording and timelapse are both not working in 50a937c. I entered my own issue for it, inclusive of both functions
