### ISSUE TITLE
Dual-booting to original fw is slow and unusable

### ISSUE THREAD

**Issue by kokossoppa** [EliasKotlyar/Xiaomi-Dafang-Hacks#161]
After patching the bootloader with CFW 1.3 or 1.2 I am able to run custom firmware, however when rebooting the camera without SD-card the original firmware seems to be factory-reset and I need to add the camera again in the app. This should be fine, however the camera seems to be running really slow when on CFW1.3/1.2 and running a new setup is virtually impossible. The setup is painfully slow, sometimes the chinese voice crackles during the setup and it seems that the cpu or some other resources are running at 100%. The QR-code is not recognized at all and adding device fails every time. Switching to SD-card with custom firmware works fine, but "dual-booting" to original FW has these problems. When re-flashing an original FW everything works perfect again, the camera is fast, recognizes QR-code straight away, but then I can't run your hacks anymore. Is this a known problem? It seems that the custom bootloader makes my orig fw slow to the point where it is unusable. For reference my camera is about one week old.

By the way, awesome work! I am really enjoying it but sometimes I want to be able to switch between custom/orig fw.

**Comment by helio58** [comment]
Hi,
I have 2 cameras ,One I bought for 2 month ago and other last week.
The first one no problem with using this hack and back to original.Have just to remove sd card or rename run.sh file.
The new one is exactly as you said: QR-code is not recognized at all
Xiaomi may have change something .

**Comment by hubmon** [comment]
What version Firmware is on your Camera?
Currently  have 243 installed, see that 287 is available. 
Holding off on the update.

**Comment by kokossoppa** [comment]
I’m on 243 but with a very new camera. As helio58 said something might have changed recently from xiaomi.

**Comment by helio58** [comment]
Hi, I m on 243 too. Received  yesterday one more camera same problem. It seems they change, i don't know what.
The first camera i bought from Ebay for 2 month ago.
The most recents are from Gearbest.
