### ISSUE TITLE
Outdated Samba version

### ISSUE THREAD

**Issue by dewi-ny-je** [EliasKotlyar/Xiaomi-Dafang-Hacks#1613]
Samba (smbclient) provided is 2.2.x, released in 2002.
Besides the countless security issues, it also supports only SMBv1 ("CIFS"), therefore cannot connect to several SMB servers which have SMBv1 disabled by default.

SMB2 is supported starting from Samba 3.6 (released in 2011) and it should be provided for better compatibility.

I have no idea how to compile and include it, so either you give me instructions, or someone with a working dev enviroment for the firmware does it.

**Comment by daniel-bavrin** [comment]
Suse site says we need Samba 4, not 3.6:
Samba 3.6 which ships with SLES 11 does not support SMBv2. (Because of problems with durable handles.)
Samba 4.x which ships with SLES 12 does support SMBv2. (Durable handles support was added in 4.0.0)

**Comment by raidenii** [comment]
I have compiled a 3.6.25 version of smbclient (it's not stripped, having whopping size of ~7MB), but it runs on my Wyze Cam 2 with Dafang firmware, and can connect to my SMB2 share + transfer files back and forth.

I have little to no experience in cross-compiling, and this build is surely VERY problematic. Any suggestions to optimize/stripping the size of binary would be highly appreciated.

[smbclient.zip](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/files/5698691/smbclient.zip)

**Comment by raidenii** [comment]
Tried stripping and adding -Os to CFLAGS but the size is still ~6M.

**Comment by nik0** [comment]
With the compiler you should have a « strip » something exe 
While compiling the video server the following is done:
  ${CROSS_COMPILE}strip -s _install/bin/*

**Comment by raidenii** [comment]
@nik0 Used `mips-linux-gnu-strip -s` and it reduced like ~700k along with -Os.

**Comment by nik0** [comment]
Does the binary running ? If yes I don’t see any problem 
Maybe all the libs are statically linked

**Comment by raidenii** [comment]
The standalone works fine for browsing/uploading/downloading/deleting files, but somehow motion detection doesn't work, don't know why yet.

The binary is dynamically linked.
```
samba-3.6.25/source3/bin/smbclient: ELF 32-bit LSB executable, MIPS, MIPS32 rel2 version 1 (SYSV), dynamically linked, interpreter /lib/ld-uClibc.so.0, stripped
```

**Comment by raidenii** [comment]
Motion is working - somehow when the firmware copies new smbclient binary to `/system/bin` it truncated the binary and made it segfault when triggered. Change `detectionOn.sh` pointing to the binary on `/system/sdcard/bin` and everything worked.

**Comment by bklane2** [comment]
I took the zip file from raidenii transferred to camera via ftpget, unzipped, rename smbclient in /system/bin to smbclient.orig and then created a symbolic link from unzipped smbclient to /system/bin/smbclient
motion detection, still and video now working. A huge thank you to raidenii for the smbclient.zip
NB: I could not copy the new smbclient file to /system/bin as ran out of storage on device and I dont now how or if even possible to grow that storage.

**Comment by raidenii** [comment]
Glad it works - maybe @EliasKotlyar has better idea about how to integrate this binary to the rootfs image

**Comment by greskii** [comment]
After following the steps provided by @bklane2, I was able to get this to work by setting `server min protocol = NT1` in `/etc/samba/smb.conf` on the server hosting the samba share.  Host is Ubuntu 20.10.
It would be awesome to see this project get an updated version of smbclient.

**Comment by dewi-ny-je** [comment]
NT1 is the old protocol, the change makes sense if SMB 2 works too

**Comment by greskii** [comment]
> 
> 
> NT1 is the old protocol, the change makes sense if SMB 2 works too

I realize its _very_ old, but it it was the only way that I could find to get around smbclient returning `protocol negotiation failed: NT_STATUS_INVALID_NETWORK_RESPONSE` when trying to connect.

**Comment by dewi-ny-je** [comment]
@raidenii have you tested smb2?

**Comment by raidenii** [comment]
@dewi-ny-je Yes. Works fine for me and @bklane2.

**Comment by raidenii** [comment]
It's weird since last time I tested it works but not now. Let me take a double look

**Comment by greskii** [comment]
> 
> 
> @raidenii have you tested smb2?

Yea, smb2 did not work for me.  The only protocols I could get to work are `LANMAN1`, `LANMAN2`, and `NT1`.  I went with `NT1` as it is the newest (but still very old) of the three.

**Comment by raidenii** [comment]
I managed to compile a smbclient 4.7.12 that supports SMB2/SMB3. Still trying to figure out why motion detection isn't working yet.
[smbclient_4.7.12.tar.gz](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/files/6137722/smbclient_4.7.12.tar.gz)

**Comment by jmtatsch** [comment]
@raidenii would you be so kind to open a pull request with a compile script at da fang hacks main repository?

**Comment by raidenii** [comment]
I'll write a blog post to take note of what I did, then check later to see if I can do this in a single script.

**Comment by AndroX55** [comment]
try to connect to freenas, i got the following error "Can't load /system/sdcard/etc/smb.conf - run testparm to debug it"
@greskii how to create /etc/samba/smb.conf and what is inside of this file, would you mind to show me some direction.
sorry for this noob question

**Comment by raidenii** [comment]
Just create a `smb.conf` in `/system/sdcard/etc` with content

```
[global]
max protocol = SMB3
```

**Comment by greskii** [comment]
> 
> 
> I managed to compile a smbclient 4.7.12 that supports SMB2/SMB3.
> 
> Updated with single static binary.
> 
> [smbclient.zip](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/files/6137836/smbclient.zip)

I just confirmed that I can now use `SMB3` with the latest version of smbclient compiled by @raidenii .  Thank you very much for doing this!

**Comment by AndroX55** [comment]
thanks @raidenii @greskii, but i've got the following message "BUS ERROR", try to wipe all in sd card and restart. hopefully it can work well

**Comment by photocyte** [comment]
Just adding that @radenii 's blog post about cross compiling the smbclient binary can be found here:
http://raidenii.github.io/2021/03/1536

The dafang hacks main repository w/ the scripts for compiled modules is here:
https://github.com/Dafang-Hacks/Main

Here is a recent compile script that might be a useful model to base the updated smbclient after:
https://github.com/Dafang-Hacks/Main/pull/84/files

**Comment by reenberg** [comment]
@EliasKotlyar, please either add some docs about this issue, or possible add a script that bind mounts a newer version of the smbclient from /system/sdcard/bin/smbclient to /system/bin/smbclient on each boot.  I don't assume that its feasible to mess with the limited space of the /system partition, that is stored on /dev/mtdblock4, especially as the above 4.7.12 version of the smbclient binary is about 15M in size, and the /system partition has about 1.1M of free space.

No one should be forced to downgrade their SMB servers to run v1.  That is just a security nightmare.

**Comment by reenberg** [comment]
Looking a bit at the output of the rtsp server, I noticed that it tries to create a folder structure for both the stills and the videos it uploads to the various supported services.  In the case of samba, it however fails, as the `$groupname` it uses in the command argument for `mkdir` is a date pattern gotten from the [config/motion.config#30](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/firmware_mod/config/motion.conf.dist#L30) file, which contains a forward slash (/), resulting in malformed argument to windows mkdir (it doesn't do recursive directory creation). 

This "groupname feature" seems only to be used on the local and samba storage paths.  The code thats saves the files locally correctly use `mkdir -p`.  So i would guess you either need to split this up and build a dynamic list of mkdirs, for each '/' that is present in the groupname, or just replace it with a valid windows filename like an underscore.

**Comment by raidenii** [comment]
@reenberg Or change `/system/bin/smbclient` to a symlink to `/system/sdcard/bin/smbclient`, and in the main fw update deploy this updated binary to `/system/sdcard/bin`.

**Comment by EliasKotlyar** [comment]
@reenberg Unfortunately, i havent compiled this smbclient - I suppose it was someone else.
 I would suggest removing it if its a security concern and its enabled by default.

**Comment by numericOverflow** [comment]
I have the smbclient binary that @raidenii compiled, and it works for me to connect to my smb share (see below), however the motion scripts don't actually save anything to the network folder(s).

Any thoughts on why motion won't save to samba share, but saves locally to SDCARD just fine?

_Smbclient (v4.7.12) works to manually connect/browse network share_
![image](https://user-images.githubusercontent.com/3429424/180513226-e86927d0-05e7-4b5a-aa6c-492d6480271f.png)

_Motion Save Screen_
![image](https://user-images.githubusercontent.com/3429424/180513526-74c9e68f-ce9e-4a04-b8a0-faec7c814056.png)

SMB settings in /system/sdcard/config/motion.conf
![image](https://user-images.githubusercontent.com/3429424/180513554-b1a463d8-f5b4-40a9-be62-9f94949e6717.png)

**Comment by raidenii** [comment]
Permissions? Try to see if you can copy a file / mkdir on the samba share you specified.

**Comment by numericOverflow** [comment]
> Permissions? Try to see if you can copy a file / mkdir on the samba share you specified.

Permissions on the network share seem OK - I can put, mkdir, and del as expected with these credentials.
 (Plus this user/pass is working elsewhere on another machine (non-wyze cam)

``` 
[root@webcam04:~]# /system/sdcard/bin/smbclient -m SMB3 "//192.168.******************" -U
************ -D "motion/images/webcam04/stills"
Enter ************************'s password:
Try "help" to get a list of possible commands.
smb: \motion\images\webcam04\stills\> put ./.profile
putting file ./.profile as \motion\images\webcam04\stills\.profile (4.8 kb/s) (average 4.8 kb/s)
smb: \motion\images\webcam04\stills\> dir
  .                                   D        0  Fri Jul 22 16:54:34 2022
  ..                                  D        0  Fri Jul 22 16:54:34 2022
  .profile                            A      437  Fri Jul 22 16:54:34 2022

                211323762 blocks of size 65536. 91922022 blocks available
smb: \motion\images\webcam04\stills\> exit
smb: \motion\images\webcam04\stills\> mkdir test
smb: \motion\images\webcam04\stills\> dir
  .                                   D        0  Fri Jul 22 16:55:14 2022
  ..                                  D        0  Fri Jul 22 16:55:14 2022
  .profile                            A      437  Fri Jul 22 16:54:34 2022
  test                                D        0  Fri Jul 22 16:55:14 2022

                211323762 blocks of size 65536. 91922022 blocks available
smb: \motion\images\webcam04\stills\> del .profile
smb: \motion\images\webcam04\stills\> dir
  .                                   D        0  Fri Jul 22 16:59:38 2022
  ..                                  D        0  Fri Jul 22 16:59:38 2022
  test                                D        0  Fri Jul 22 16:55:14 2022

                211323762 blocks of size 65536. 91922022 blocks available
smb: \motion\images\webcam04\stills\>
