### ISSUE TITLE
Script to mount NFS

### ISSUE THREAD

**Issue by dewi-ny-je** [EliasKotlyar/Xiaomi-Dafang-Hacks#1614]
I wrote a script to mount an NFS share in the /system/sdcard/DCIM directory, so that recordings and Motion capture go to NFS directly.
You can also set crontab to run it every 5 minutes, in case the network connection is lost and some files are recorded locally.

Where should I place it?

Here the script (I haven't tested the "if [ ! -d ${TEMP} ]; then mkdir ${TEMP}; fi" because I created it manually, but it should be ok).

```
#!/bin/sh

WORKING=/system/sdcard/DCIM
TEMP=/system/sdcard/DCIM-temp
# customise the following variable:
NFSREMOTE=/tank/media/security

if [ ! -d ${TEMP} ]; then mkdir ${TEMP}; fi

if [ "$(mount | grep '/system/sdcard/DCIM' -c)" -ne 0 ]; then
#  echo mountpoint found
  exit 0
fi

if [ "$(ls -A ${WORKING})" ]; then
  echo WORKING not empty
  mv $WORKING/* $TEMP/
fi

mount -o nolock -t nfs 192.168.3.5:${NFSREMOTE} /system/sdcard/DCIM

if [ "$(ls -A ${TEMP})" ]; then
  echo TEMP not empty
  cd ${TEMP}
  find . -type d -exec mkdir -p ${WORKING}/{} \;
  find . -type f -exec mv \{} ${WORKING}/{} \;
  find . -type d -empty -delete
fi

```

**Comment by numberdotone** [comment]
Does anybody tried the script?
Regarding to the directory structure it could be placed in /system/sdcard/config/userscripts/ or better in /system/sdcard/config/userscripts/startup ?
How is it then executed? Automatically?

**Comment by sborovik** [comment]
scrip works fine for me 
from /system/sdcard/config/userscripts/startup/nfs.sh
