### ISSUE TITLE
Wyze Cam Pan not moving / very weak motors.

### ISSUE THREAD

**Issue by kquinsland** [EliasKotlyar/Xiaomi-Dafang-Hacks#1615]
### exact camera hardware:

I have a Wyze Cam Pan/Tilt. The `System/Overview` details:
```
Model | Xiaomi Dafang
Firmware date | 2020-10-02T13:19:41Z
Firmware branch | master
Firmware commit | 2948300 ( No update available)
Kernel Version | #21 PREEMPT Thu Oct 19 11:38:16 CST 2017
Bootloader Version | U-Boot 2013.07-gba03eeb (Dec 04 2018 - 21:41:16)

Uptime | 2h, 01m
Load Average | 2.95, 2.73, 2.66

```

I have successfully flashed a custom boot loader and have the cam working well w/ my MQTT broker...etc.

### Description

The pan/tilt function does not work. I fi listen _very_ carefully, i can hear the motors being driven when i adjust the position (both via the web UI and via the `motor` bin that's on the device's SD card. The room must be _SILENT_ to hear the motors, you can 'feel' them being driven if you touch the camera while issuing the motor commands.

I opened up the camera and was able to confirm that motor commands _are_ triggering the motors... they're just **incredibly** under-powered. If i give the device some "assistance" then it usually moves as expected. E.G.: if i issue the `tilt down` command with my thumb gentle pulling the camera part down, then the entire camera assembly moves down a short distance before encountering resistance. As soon as I  issue  another `tilt down`  command, the 'pre-load' from my thumb  quickly moves down a short bit before the resistance increases... again.

Mechanically, the motors are connected to the physical camera body and assembly with well greased gears and the  electrical path between whatever GPIO is on the SoC and the motor driver and the servos appears to be working.

The motors are just incredibly weak. 

I see the `GET /cgi-bin/action.cgi?cmd=motor_down` requests in the log when I click the down arrow on the 'live preview' overlay and when I click on the dedicated arrow buttons on the `Confiiguretion > pan/tilt` page. When I inspect the requets, i see a reply that looks like this:

```
x: 1524 y: 193 speed: 900 
```

Clicking the Calibrate button does nothing to fix this (but i do hear the servos...trying to move)

I checked for existing issues and found two:

https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/1318.  However, the `onvif-srvd.sh` service is  off/disabled (yellow dot) on my camera.  I was having the issue before I configured MQTT / any other service. MQTT is the only service that I turned on;  every other service has been left as the defaults.

https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/1563

I do have one of the 'new' cameras, apparently. The QR code on the back of my camera has this info in it:

```
MA:AC:AD:DR:ES|F00A0000|WYZECP1_JEF
```

But i don't have any  issues w/ bootloader as I was able to get custom loader flashed w/o issues/

Thoughts?

**Comment by kquinsland** [comment]
I saw some new changes related to motors: https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/commit/11270522ab357dd58dee69e1c8fe0414a2127509

and decided to update to master:

```
Firmware Branch: | master
Firmware Commit: | ede5abe ( No update available)
```

After updating to the latest build, motors still dont work, but i see this in `system logs`


```
# A few of these 
[ 87.073455] motor_ops_reset468

# MANY of these
[ 651.004415] tcu_chn2 tcu_chn2.2: Motor driver busy now!
```

I can trigger many, many, many messages in the logs by sending the move or calibrate commands.


Possibly related: https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/1625

**Comment by jmtatsch** [comment]
Do you have onvif running? It takes over the motors. Also motors can get stuck or the cable can wind up.

**Comment by kquinsland** [comment]
> Do you have onvif running? 

No.  `But I do not have onvif activated :(` Also, see attached.

```
[root@cam01:~]# ps aux | grep onvi
 6319 root      0:00 busybox grep onvi
```

> Also motors can get stuck or the cable can wind up.

I can easily move the camera 'ball' up and down and rotate the base. I don't feel any mechanical hindrance and i didn't see any other mechanical issues when i opened the camera up.


When i run commands like this:
```
[root@cam01:bin]# ./motor -d r -s 1000
x: 1000
y: 700
speed: 900
```

I can hear/feel the motor _trying_ to spin, but it feels under volted / like it has no power.


![cam01](https://user-images.githubusercontent.com/1808375/99835695-d012c580-2b19-11eb-8b38-1cd474ad3021.png)

**Comment by jmtatsch** [comment]
Do you have a decent power supply?

**Comment by jmtatsch** [comment]
My camera still moves with current fw.

**Comment by kquinsland** [comment]
I am using the cable and power supply that came with the camera. I can reproduce it with other USB power supplies and cables that I know can source 10W @ 5V (2A max)

> My camera still moves with current fw.

Do you have either of these strings showing up in your `dmesg`:

```
motor_ops_reset468
tcu_chn2 tcu_chn2.2: Motor driver busy now!
```

**Comment by wtgee** [comment]
I'm having this same issue. It's possible I have weak power supply but unfortunately the system is remote and I don't have access to it right now.  

Any more information about this?

**Comment by wtgee** [comment]
> I'm having this same issue. It's possible I have weak power supply but unfortunately the system is remote and I don't have access to it right now.

Quick follow up that I check on and replaced the power supply so that it's 2amps, but still no movement.

**Comment by arfletcher** [comment]
I have the same issue with the latest production firmware. Everything else works great :-)

The motors worked perfectly with the Wyze firmware this morning immediately before installing the dafang firmware.
