### ISSUE TITLE
Wyze V2 slow flashing yellow light

### ISSUE THREAD

**Issue by Rooster519** [EliasKotlyar/Xiaomi-Dafang-Hacks#1616]
Trying to load the firmware onto a Wyze v2.   16 gb sd card with partitioned 512mb root drive.   Get the blue light then it begins slow blink and I can hear it clicking.   Put in the sd card with the firmware_mod folder and it continues to slow blink and click.  Tried it without an sd card and same thing.  I've tried resetting to factory by holding the setup button for 20 seconds and the light just flashes.  Any ideas?

**Comment by mrjohnjones** [comment]
Same problem. Just got two new Wyze v2's and intended to put Wyze RTSP firmware on, but I had this problem, so I tried this firmware and same exact thing. Happens on both the new cameras. It's also being discussed in the wyzecam subreddit. You can download the latest default firmware from Wyze and flash that and it will be back to normal but useless to me without RTSP.

**Comment by Conradical07** [comment]
I have run into the same issue.  Can confirm mrjohnjones on all counts.  Can't flash Wyze RTSP.  Can't flash custom firmware.  Can get back to stock firmware by flashing the most recent available from Wyze.

**Comment by Rooster519** [comment]
I reached out to Wyze about my issue of not being able to flash any different firmware, including RTSP.  They are sending me a replacement.  Hopefully it will fix it and allow custom firmware or RTSP at a minimum.  I'm wondering if flashing to an older firmware first would help?

**Comment by michaelShriver** [comment]
I experienced this issue on a new Wyzecam V2 that I received this week. It appears that Wyzecam V2 has perhaps undergone a hardware revision that renders newer units incompatible with this firmware:

https://forums.wyzecam.com/t/rtsp-4-28-4-41-on-new-v2-cams/136439

**Comment by RohitJones** [comment]
I am facing the same issue as well.

**Comment by RohitJones** [comment]
I can confirm that [Openmiko](https://github.com/openmiko/openmiko) does support the new hardware revision, however there are other issues that need to be addressed with the prebuilt binary. It might be possible to fix the issues by self compiling.

**Comment by xmlguy74** [comment]
Is there any effort to fix this within the dafang hack? Openmiko doesn't seem ready for mass consumption yet.

**Comment by darrylhadfield** [comment]
> Is there any effort to fix this within the dafang hack? ~Openmiko doesn't seem ready for mass consumption yet.~
> 
> Was able to get openmiko working. Documentation is a bit rough, but manageable.

A brief peek at the docs didn't show a clean path forward; where'd you get the initial demo.bin file, there?

**Comment by TheDarthFather** [comment]
I have the same issue with a Wyze Pan. Followed the guide here: https://www.youtube.com/watch?v=-jVMKWoePvo 
After updating the config files and rebooted the cam, the same "slow yelow" blink.
 
PS: SSD formated at 512MB
