### ISSUE TITLE
disable audio and fixed ip

### ISSUE THREAD

**Issue by xxameht** [EliasKotlyar/Xiaomi-Dafang-Hacks#162]
brilliant work, mod works flawlessly

i do want to set a fixed IP address tho, and cant figure that one out

and id like to just disable audio all together

thanks

**Comment by hubmon** [comment]
Miracle of search
https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/122

**Comment by xxameht** [comment]
gawd, i didnt spot that one at all, thanks man

**Comment by hubmon** [comment]
Next one will cost you a beer. :)

**Comment by shinebar1001** [comment]
Please see the wiki - it just got updated, because if there is a dhcpd running in your network, you will have to kill the dhcp-client.
https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/wiki/static-IP
