### ISSUE TITLE
Update Wiki Request - Misc Section - How to Manually Force Firmware Update

### ISSUE THREAD

**Issue by Jonathan-Garber** [EliasKotlyar/Xiaomi-Dafang-Hacks#1621]
Sorry this isn't an issue per-se and I would have posted this suggestion to the chat but it's late and I don't really want to sign up for an account there just to post this suggestion.

I ran into a failed firmware update tonight on a Wyze Cam v2 that is not in a user friendly place to get the SD card out. The UI was incomplete and it seemed to be missing several css and js files. So nothing really worked in the UI. I picked apart the latest code and I could see the calls to action.cgi that trigger the firmware update. It may be good to put this in the Wiki for a last resort users can try before pulling the SD card and redoing things. Sort of a Break Glass in Case of Emergency method.

Force Update to Stable Release
```
https://yourcamip/cgi-bin/action.cgi?cmd=update&release=master&mode=full
```
Note: This page will just show the command issued to start the update script. This is totally normal. Once you see this command on screen then go to the Show Update Progress Page to keep tabs on the progress.

Show Update Progress
```
https://yourcamip/cgi-bin/action.cgi?cmd=show_updateProgress
```
Note: The progress page is simply a number displayed on page indicating percentage complete. Just keep refreshing the page every min or so and you will see the progress going up. If it halts for a bit, just wait longer and refresh again. It can take a bit to update the firmware. Be patient.

Now I kept refreshing the update progress page and upon completion the camera fell offline and never came back. I waited about 10 minutes then unplugged and re-plugged the camera. It successfully booted into the latest firmware with full interface. I had to adjust a few things but it saved me from having to get to the camera and pull the SD card. This solution worked for me and saved me a lot of hassle. Your mileage may vary but I hope others find this helpful if they are in a similar situation.

**Comment by ryaske** [comment]
GREAT INFO!  Wish I read this before what I went through last night with 50a937c :-(    

I had to go pull the SDcard. And then the camera. And then the sd card in the replacement camera. And then that replacement camera too.   I ended up reverting to a version 8/21/2020 and putting the camera back in the precarious, cold, wet, and not-fun location with the same SD card I started with.

Can any one of us just stick that info into the readme or wiki?  Not sure how this works. But I'd be happy to immortalize it if that's how it should be done.  Maybe I would have found this remote-recovery backup plan if it was in the readme....
