### ISSUE TITLE
New GitHub authentication for autoupdate.sh?

### ISSUE THREAD

**Issue by jlg89** [EliasKotlyar/Xiaomi-Dafang-Hacks#1622]
Apparently the "-u" flag that autoupdate.sh uses to authenticate to GitHub is no longer going to work:

https://developer.github.com/changes/2020-02-14-deprecating-password-auth/

They're switching from "curl -u my_username:my_password ..." to "curl -H 'Authorization: token my_access_token' ..."

Shouldn't be too much trouble to update the script, since you've nothing else to do. 🙄

**Comment by jlg89** [comment]
Perhaps the script could look for an auth token in a specific file, and automatically use it if found, go anonymous otherwise. That would allow the GUI update to use it as well.

**Comment by hb9eue** [comment]
Thank you. I just went trough disabling 2FA and trying to debug this issue, as I was always hitting the ratelimit while attempting to update.
Is there any other way to circumvent rate limiting to allow autoupdate.sh to work again?
