### ISSUE TITLE
Doesn't go to stock firmware when sd card is removed (Wyze Cam v2)

### ISSUE THREAD

**Issue by netcheung** [EliasKotlyar/Xiaomi-Dafang-Hacks#1624]
Wyze Cam V2
with open source U-boot

### Description

After flashing CFW1.1, my WyzeCam v2 works fine with custom firmware booting from sd card. However, when I try to go back stock firmware by removing sd card.

I did try to put stock firmware as demo.bin, push setup button for 3 to 6 sec. and try to flash back to stock firmware but no luck at all. I believe it is due to my 'new version' of wyze cam v2 with 'old' firmware 'cfw1.1' which caused a semi-bricked device (only work with booting from SD card).

Any suggestion or chance that I can flash back stock firmware? Very very appreciated for any suggestion and help.

**Comment by vinniet** [comment]
I also have not found way to revert the firmware back to stock.  The instructions says to remove the run.sh which did nothing besides the device not coming online.

**Comment by jsj0318** [comment]
Even if I remove the SD card, it won't go back to the original version.
Maybe it's because I worked on a patch for 1080p.
I also want to know how to go back to the original.

**Comment by vinniet** [comment]
I read somewhere if you use the Wyze RTSP firmware that was in beta you could get back.   I tried to look up the bookmarked URL and its gone.  Did anyone try this?

**Comment by NorthernMan54** [comment]
This is unlikely to help as it was a bit involved and may not resolve your issue.  I'm doing this more to help anyone else in the same situation and save them a similar amount of googling I did over the last few days.

I had changed the boot loader on my Wyze Cam 2 as part of trying to get 1080p working and wanted to go to the Webcam firmware by putting demo.bin on the SD card and holding setup when starting.  

1 - Install serial pins on [board](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/hacks/serial.md) and connect to your laptop.  Please note that the pins are in a slightly different location on the wyze V2 cam, but the order is the same.  RX - TX - GND, with RX in the corner.

2 - Put a copy of the original uboot.bin and the firmware you want to upgrade to on the SD Card.  If your like me and lost the original uboot.bin for the V2, the latest Wyze V2 boot loader firmware is available [here](https://github.com/agent86ix/wyze-cam-pan-sd-flash-fix/tree/master/Upgrade).

3 - Connect the serial cable, boot the camera and press any key immediately

4 - Install the original boot loader firmware using these [commands](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/hacks/install_various.md). to install new version using the boot loader.

5 - After complete, enter the command `reset`

6 - Normal firmware updates from the SD card should now work.

**Comment by vinniet** [comment]
Thanks for the solution but this is incredibly involved.   It would of been nice to note that this is NOT reversible on the web site.

**Comment by vinniet** [comment]
I have confirmed that if you install Wyze beta RTSP beta it will put it back on Wyze cloud.   I assume I can flash the hack again if I want it.  No sure how to get it out of general codebase of Wyze. 

https://wyzelabs.zendesk.com/hc/en-us/articles/360026245231-Wyze-Cam-RTSP
