### ISSUE TITLE
Do you have onvif activated? That blocks the motor for itself.

### ISSUE THREAD

**Issue by bbc581** [EliasKotlyar/Xiaomi-Dafang-Hacks#1629]
I have never messed with the new onvif functionality.  However, I did notice as of late that despite all updates since this introduction I have not had any directional control over the motors in quite a while.  It took having to cross-reference the "tcu_chn2 tcu_chn2.2: Motor driver busy now!" log entry to the comment to the issue below to determine my root cause.

Resolution was to enable/disable the service/config rocker switches in the settings from OFF > ON > and then back OFF again to get it to work.  Note that the onvif was supposedly not running and I still had problems.  Wishing now that I had checked before trying to remedy the situation.  Could this have been potentially due to a poor initialization of some kind?

The motor control works fine since I toggled ONVIF back and forth...  Hope this helps those who haven't messed with it yet.

----- Original Message -----
Do you have onvif activated? That blocks the motor for itself.

_Originally posted by @jmtatsch in https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/1229#issuecomment-650377826_

**Comment by blooesky** [comment]
Same issue....onvif not starting and crash moving controls...with message tcu_chn2 tcu_chn2.2: Motor driver busy now!

**Comment by schumi2004** [comment]
Same issue here.
But not be able to move it via browser was not such a big deal if I could move it using Onvif  but even that is not possible.
Or i'm doing things wrong but onvif-srvd control constatly crashes.

**Comment by magidel** [comment]
Same issue!
When I activate the ONVIF server in systme control, the directional control (PTZ control) from the camera web page do not work.
As soon as I turn off the ONVIF server, everything goes back to working.
I would like to be able to activate the ONVIF server to use it under Home Assistant, so as to command the PTZ controls both from HA and from the web page.
We await news on this
Thanks for your work and best regards

**Comment by nebakanezzer** [comment]
issue is still present. verified with 2 separate pan devices brand new in box. toggling onvif fixes the issue. this makes these essentially useless as IP cameras.

**Comment by shado80** [comment]
Issue is still present in latest and greatest fw
