### ISSUE TITLE
Unable to flash firmware device not booting

### ISSUE THREAD

**Issue by geekmoto13** [EliasKotlyar/Xiaomi-Dafang-Hacks#1630]
I have the wyze pan/tilt and the firmware that allows the boot loader to function installs fine but when I swap to an Sd card with the boot loader it just sits there doing nothing except turning the yellow led on/off every 5to 10 seconds. The instructions are not very clear when you do the firmware card swap

**Comment by fleshTH** [comment]
I have a Wyze V2 that won't take the firmware. I think they blocked it now.

**Comment by nzubair** [comment]
> 
> 
> I have a Wyze V2 that won't take the firmware. I think they blocked it now.

Finding the same thing.

**Comment by jonpurdy** [comment]
Same thing with recently v2 purchased last week. Initial purchase from early December had no problem.

**Comment by darrylhadfield** [comment]
:( same.  Wyze v2; I've heard suggestions elsewhere that upgraded firmware may be the culprit. Unfortunately, even when I downgrade to 4.9.4.28, still no luck - seems like something was flipped permanently with the newer firmware.

**Comment by McNutnut** [comment]
@fleshTH @nzubair @jonpurdy @darrylhadfield [Hopefully this helps](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/1667#issuecomment-770461311)

**Comment by nzubair** [comment]
@McNutnut  I was able to get my hands on a version with FCC ID 2ANJHWYZEC2 (without the 02 at the end) and was able to flash it.  Will check out your fw file for the newer one.

**Comment by darrylhadfield** [comment]
> @fleshTH @nzubair @jonpurdy @darrylhadfield [Hopefully this helps](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/1667#issuecomment-770461311)

So, I have the v2 cames with an FCC id ending in '02' and I was able to flash this.

Unfortunately, while it still boots up to the default Wyze firmware, I can't put an SD card into it with the Xiaomi-Dafang OS on it...  I've been wiating 10 mins, going to power it off and pull the SD card to review the log file now.

**Comment by darrylhadfield** [comment]
Yeah, it appears to have booted properly, but either the wifi or the network config didn't seem to work - I'm going to guess, at this point, that it may be the wifi..

... and yep, turns out I mistyped the SSID.I appear to be online - Thank you very much!

**Comment by fleshTH** [comment]
@McNutnut Work's perfectly. Thanks!
