### ISSUE TITLE
Can't stop rtsp server

### ISSUE THREAD

**Issue by Subteblu** [EliasKotlyar/Xiaomi-Dafang-Hacks#1631]
Hello, yesterday I updated to the latest version master branch ede5abe and with the new interface, much better, the button to stop the rtsp server does not work. Before I could stop the server, now there is no way to do it. Keep broadcasting even when the switch is off. Any solution? Thanks.

**Comment by benru** [comment]
I believe that #1636 will fix this issue.

**Comment by Subteblu** [comment]
Thank you! I will try to delete the files from the autostart folder.

**Comment by Subteblu** [comment]
> I believe that #1636 will fix this issue.

Deleting the rtsp files from the autostart folder worked for me, thanks a lot!
