### ISSUE TITLE
problem with (Windows 10's built-in) NTP server, resulting date is 1969 instead of now

### ISSUE THREAD

**Issue by jromero2k** [EliasKotlyar/Xiaomi-Dafang-Hacks#1644]
This is an issue tracking system only.
If you have general questions or are a newbie, please ask for help in our [chat channel](https://gitter.im/Xiaomi-Dafang-Hacks).

To make sure your issue can be resolved as quickly as possible please state your

* exact camera hardware:

XIAOMI DAFANG Pan 1080p Wireless Camera

* the Xiaomi-Dafang-Hacks commitid (from `git log`) you are experiencing the issue with:

50a937cfb7bea25c553569919608df1a375ed2c8

### Description

I have the built-in Windows 10 Professional NTP server enabled, and all IoT (incl. my Dafang camera) is barred from accessing the Internet. My other Linux devices work properly this way, but in this case the date is set to 1969:

```
(root @ DAFANG)-> ntpd -q -p main.local

(root @ DAFANG)-> date
Wed Dec 31 19:08:20 EST 1969

(root @ DAFANG)-> ntpd -w -p main.local
ntpd: reply from 192.168.0.101: offset:+1608080763.148691 delay:0.002470 status:0x1c strat:1 refid:0x4c434f4c rootdelay:0.000000 reach:0x01
ntpd: reply from 192.168.0.101: offset:+1608080763.148449 delay:0.002767 status:0x1c strat:1 refid:0x4c434f4c rootdelay:0.000000 reach:0x03
ntpd: reply from 192.168.0.101: offset:+1608080763.148359 delay:0.002597 status:0x1c strat:1 refid:0x4c434f4c rootdelay:0.000000 reach:0x07
^C
```

I have no idea why it's not working or how to interpret that output, to be honest :)

### What did you do to debug the issue

See above

### Evidence

See above

### Contribute Back

If your issue was resolved, please consider contributing back to the project by creating a pull request to improve the code or documentation in order to avoid that this issue arises again for other people.

**Comment by ryaske** [comment]
I am having the same problem. On every reboot the time gets set back. I have resorted to resetting the time/date myself with date -s command.  I have verified the NTP servers I was using are definitely working fine, by using the w32tm command and receiving correct results from each NTP server.

**Comment by ryaske** [comment]
Same issue reported already here: https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/1644

It could be related to specifying a static IP, which I have done. How about you @jromero2k  ?   I will be switching to DHCP reservation via my router if you are also specifying a static in the camera...  maybe that will nip this until it's properly fixed

**Comment by jromero2k** [comment]
> Same issue reported already here: #1504
> 
> It could be related to specifying a static IP, which I have done. How about you @jromero2k ? I will be switching to DHCP reservation via my router if you are also specifying a static in the camera... maybe that will nip this until it's properly fixed

`main.local` is registered with DHCP in my router and working properly, `ping main.local` works as expected. Notice that `ntpd -w -p main.local` is resolving and querying properly. I suspect my problem might be related to the format of the returned response, but I'm not familiar with the NTP RFC

**Comment by rklassen** [comment]
Having same issue. Tried setting NTP server in the web interface to `time.nist.gov` and `time.google.com` but the date says 1969 or 1970.
