### ISSUE TITLE
Get to XiaoFang Hacks page but no menu options

### ISSUE THREAD

**Issue by radyeab** [EliasKotlyar/Xiaomi-Dafang-Hacks#165]
Using version 1.3 firmware.   I login to the ip for the camera and on all my different browsers, I get the blue XiaoFang Hacks (Ascii) page Version 0.0.1 and that is it.   There are no menu options to select.   The rest of the blue page is blank.   Checked to make sure no ad blocker, etc running.

**Comment by hubmon** [comment]
Was that a Typing Error or you are lost?
This is DAFANG Hack not XIAOfang hack section.

**Comment by shinebar1001** [comment]
But there is still the xiaofang ASCII Art at the top of the Page
Can you please ssh into the camera and try to execute status.cgi? It seems that some command cannot be executed.

**Comment by radyeab** [comment]
I get this....
<span><pre style="display:inline">                                              Version 0.0.1</pre></span>
<br/>
./status.cgi: line 108: syntax error: EOF in backquote substitution

So I am going to assume I have a corrupt install for the moment and re-download from scratch.

Will followup.

**Comment by radyeab** [comment]
Confirmed corrupt files.   All is well now.
