### ISSUE TITLE
No boot after upgrade

### ISSUE THREAD

**Issue by nickrout** [EliasKotlyar/Xiaomi-Dafang-Hacks#1657]
This is an issue tracking system only.
If you have general questions or are a newbie, please ask for help in our [chat channel](https://gitter.im/Xiaomi-Dafang-Hacks).

To make sure your issue can be resolved as quickly as possible please state your

* exact camera hardware:
The Dafang camera (the first one pictured on your front github page). The MAC is 78:11:DC:70:D2:8D
* the Xiaomi-Dafang-Hacks commitid (from `git log`) you are experiencing the issue with:
Can't say as the damn thing will not boot.

### Description

I have been running the hack for maybe a couple of years. I have updated several times (via the web interface) in the past with no problem.

Tell us what happened and what you expected to happen.

I started the update in the UI as usual and went to bed, thinking it'd sort itself out overnight as usual. Since then the camera does not seem to boot. If I unplug and replug the power usb cable the led goes yellow for about 5 secs, then a short blue flash, back to yellow for about 2 or 3 secs  then the led goes off. At about 4 seconds there is a faint click somewhere inside the device. The is no other sign of life, and it doesn't join my wifi lan. 

I am afraid I have no idea what firmware version I was on before, nor what git it was trying to update to.

### What did you do to debug the issue

Tell us what you did to remedy/debug the issue yourself and what you think causes the issue.

### Evidence

Please add snippets from the logfiles in:

At this point there are no log files :(

### Contribute Back

If your issue was resolved, please consider contributing back to the project by creating a pull request to improve the code or documentation in order to avoid that this issue arises again for other people.

**Comment by nickrout** [comment]
Having removed the SD card and mounted it in a linux machine, I note that the card is full. What is it safe to remove. I see a log file v4l2rtspserver-master.log that is 49M and last modified in Feb 2019. Is it safe to delete?

Also I notice that most of the space is taken up by /DCIM and subdirs. This seems to be .h264 video files. Can they go? I'll assume so.

**Comment by nickrout** [comment]
Well it seems likely that the full sd card made the update fail. I managed to update by mounting the card to my linux box and transferring a complete set of firmware files from a git clone. 

Although this seems fixed and this issue is solved, I want to take the opportunity to say thanks for this repo and the work that has gone into it. Cheers.

**Comment by jmtatsch** [comment]
These h264 files are movie files your camera recorded for each motion detection.
If you don't use/want that, you can delete the videos folder and deactivate that function here:

<img width="1133" alt="Bildschirmfoto 2020-12-27 um 10 03 15" src="https://user-images.githubusercontent.com/3080674/103167357-d0923080-482a-11eb-9e8d-3580038d3a13.png">
