### ISSUE TITLE
Any Plans to Support WyzeCam V3?

### ISSUE THREAD

**Issue by SomebodySysop** [EliasKotlyar/Xiaomi-Dafang-Hacks#1661]
Are there any plans to support WyzeCam V3, or is it supported by the current binary for V2?

**Comment by jmtatsch** [comment]
Not really supported. No idea what changed. Apparently you got to change the name of demo.bin to something else (described in the howto) to make it load the fw.

**Comment by jmtatsch** [comment]
No plans to support it from my side as I don't have one and they are not sold/cheap in Germany.
Community contributions are always welcome.

**Comment by SomebodySysop** [comment]
What about if I send you one?

> No plans to support it from my side as I don't have one and they are not sold/cheap in Germany.
> Community contributions are always welcome.

**Comment by sveip** [comment]
I'm having some trouble finding a reliable information on where to get a compatible camera. @jmtatsch, could you point me to the best model/place to get a compatible camera in EU?  :smiley:

**Comment by maccaches** [comment]
If anyone needs the Ingenic T31 SDK, you can find it at https://dl.openipc.org/SDK/Ingenic/T31 . You have to make a small financial contribution to download it ($5). I have no affiliation with OpenIPC, but they seem to be the only ones with the SDK. I couldn't find it on any of the Chinese IP cam forums.

**Comment by maccaches** [comment]
Teardown info on WyzeCam V3: https://fccid.io/document.php?id=5001016

**Comment by gtxaspec** [comment]
https://github.com/HclX/WyzeHacks is now compatible with the V3.   some good info there regarding the V3's inner workings.  FYI.

**Comment by SomebodySysop** [comment]
> https://github.com/HclX/WyzeHacks is now compatible with the V3. some good info there regarding the V3's inner workings. FYI.

Thank you for info.  I did look into it.  WyzeHacks does not support RTSP.

**Comment by gtxaspec** [comment]
what about using https://github.com/umlaeute/v4l2loopback/ to create the loopback device and feeding it to the rtsp server manually? anyone try this?

**Comment by bradley-madaris** [comment]
@jmtatsch It looks like you updated install_cfw.md with the information that CFW-Binary for the Wyze Cam V3 should be labeled as demo_wcv3.bin instead of demo.bin, though there is no CFW-Binary for the V3 listed. Am I missing something there, or are we able to use the V2 CFW-Binary for the V3?

**Comment by EMishra186** [comment]
> 
> 
> @jmtatsch It looks like you updated install_cfw.md with the information that CFW-Binary for the Wyze Cam V3 should be labeled as demo_wcv3.bin instead of demo.bin, though there is no CFW-Binary for the V3 listed. Am I missing something there, or are we able to use the V2 CFW-Binary for the V3?

were you able to use the v2 cfw-binary on the v3?

**Comment by mshrem** [comment]
Would like to know this also .... just aquired a V3 to use as a baby monitor.

**Comment by BiatuAutMiahn** [comment]
Found a few leads:
`https://github.com/rockchip-toybrick/kernel/blob/stable/drivers/media/i2c/gc2053.c`
`https://github.com/jmichault/ipcam-100`

**Comment by OutputCoupler** [comment]
@jmtatsch I can mail you a v3 if that will help get this supported. Send me a PM and we'll get this rolling.

**Comment by BiatuAutMiahn** [comment]
Got some progress!

```
[root@wcv3-c:bin]# ./rtsp_server -h
[  195.878920] set sensor gpio as PA-low-10bit
[  195.956435] gc2053 chip found @ 0x37 (i2c0)
T21-hacks RTSP Server
Play streams from this server using the URL
        rtsp://10.26.1.123/stream1
        rtsp://10.26.1.123/stream2
(We use port 80 for optional RTSP-over-HTTP tunneling, or for HTTP live streaming (for indexed Transport Stream files only).)
```

**Comment by BiatuAutMiahn** [comment]
Got a uboot working that we can work with:
[https://github.com/BiatuAutMiahn/wcv3-uboot](https://github.com/BiatuAutMiahn/wcv3-uboot)

**Comment by quixoticmind** [comment]
Has anyone had any luck with the v3 yet? I've been attempting to install the custom firmware by changing the name to demo_wcv3.bin, but no luck so far.

**Comment by jmtatsch** [comment]
@OutputCoupler I don't have the time to look into supporting v3.
you might want to get in touch with @anmaped https://github.com/anmaped/openfang/issues/65 to get it supported on openfang

**Comment by SomebodySysop** [comment]
> @jmtatsch I can mail you a v3 if that will help get this supported. Send me a PM and we'll get this rolling.
> 
> Edit: Apparently github doesn't have PMs anymore. So just let me know how you'd like to get in touch and I'll send you the camera.
@OutputCoupler
Looks like this guy will do it: https://github.com/anmaped/openfang/issues/65

**Comment by OutputCoupler** [comment]
I just reached out to @anmaped on his gitter channel with an offer to send the v3.

**Comment by BiatuAutMiahn** [comment]
> Has anyone had any luck with the v3 yet? I've been attempting to install the custom firmware by changing the name to demo_wcv3.bin, but no luck so far.

Like @gtxaspec said, WyzeHacks works, in fact I've been using it on 4 cams for a few weeks now. I've managed to get a bootloader on it that has a delay in the boot so that we can load alternate firmware for testing via sdcard and the serial interface.

**Comment by SomebodySysop** [comment]
> > Has anyone had any luck with the v3 yet? I've been attempting to install the custom firmware by changing the name to demo_wcv3.bin, but no luck so far.
> 
> Like @gtxaspec said, WyzeHacks works, in fact I've been using it on 4 cams for a few weeks now. I've managed to get a bootloader on it that has a delay in the boot so that we can load alternate firmware for testing via sdcard and the serial interface.

With RTSP supported?

**Comment by pdefoy** [comment]
Any progress on this?
Just got my v3.

**Comment by aechelon** [comment]
I have a v3 with root access and would be happy to help.

**Comment by pdefoy** [comment]
How did you get root access?

**Comment by aechelon** [comment]
https://github.com/HclX/WyzeHacks

**Comment by pdefoy** [comment]
OK, will try this and I am also happy to help with this project.

**Comment by pdefoy** [comment]
What's the root password for the v3?
wellknown does not work

**Comment by romedtino** [comment]
> What's the root password for the v3?
> wellknown does not work

WYom2020

**Comment by pdefoy** [comment]
Success!! Thanks buddy

**Comment by jdesai61** [comment]
I have a v3 with WyzeHacks installed - I would be willing to try out any builds for RTSP support. Thanks

**Comment by dudududodododedede** [comment]
someone got RTSP working on v3, I tested it and it works pretty well however audio is not supported yet :(
https://github.com/FiveLeavesLeft/WyzeCameraLiveStream

**Comment by dsarel10** [comment]
> someone got RTSP working on v3, I tested it and it works pretty well however audio is not supported yet :(
> https://github.com/FiveLeavesLeft/WyzeCameraLiveStream

It's not an RTSP stream unfortunately.

**Comment by k-rock** [comment]
What bin file should I download and use for the Wyzecam v3? Assuming the 'cfw-1.2.bin' file but want to confirm before flashing.

instructions:
> `Copy the CFW-Binary from step 1 to the formatted microSD card and rename it to "demo.bin". For Wyzecam v3 the filename must be demo_wcv3.bin. There must not be other files on the microSD! This is really important and it won't work if there are any other files on there.`

**Comment by juneauwallace** [comment]
How long does a typical remote update take? Mine has been running for several hours.

**Comment by SomebodySysop** [comment]
Instead of waiting to hack the Wyze v3 firmware, I opted to go with the docker-wyze-bridge:

https://forums.wyzecam.com/t/rtsp-for-new-v3-camera/146016/222
https://github.com/mrlt8/docker-wyze-bridge

You will need to run this on a networked computer -- it does not run on the camera.  What it does is log into the v3 camera and redirect it's output to an rtsp stream that can then be read by most ip cam nvrs.   If, like me, you have multiple cameras and a computer to dedicate to the task (I pulled out a 12 year old laptop and loaded Linux on it), it works beautifully.  It gives you all the benefits of the Wyze firmware plus rtsp support.  It also works with both Wyze v3 and v2 cameras.

**Comment by diamondavocado** [comment]
@SomebodySysop Can you re-open this issue, please? Your workaround might work but it's still just a workaround; it would be much more beneficial if Dafang Hacks could be made to work with the Wyze Cam 3. Thanks.

@jmtatsch Did anyone ever send you a v3?

**Comment by SomebodySysop** [comment]
I don't mind re-opening issue, but what for?  @jmtatsch has made it clear he isn't interested in supporting Wyze V3 cams: https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/1661#issuecomment-818020167

I've been using the docker-wyze-bridge since July and it's been working well: https://github.com/mrlt8/docker-wyze-bridge

**Comment by diamondavocado** [comment]
> I don't mind re-opening issue, but what for?
Understandable if the developer isn't interested. However maybe someone else might see and adopt the issue, and develop a solution?

I'd try the docker solution but don't have a spare machine. Also I guess it would just be nice to have a self-contained solution like Dafang Hacks on the camera itself.

**Comment by boboche** [comment]
This is unfortunate.  Having this exact solution running on a V3, no hacks, would be awesome.  Too bad the world is going on subscription models, I'd pay the hardware much more to not have this cloud junkware.  Too bad there aren't cheap starlight cameras for diy'ers yet...

**Comment by SomebodySysop** [comment]
FYI, Wyze has released the beta RTSP firmware for it's V3 cameras: https://forums.wyzecam.com/t/beta-testing-for-wyze-cam-v3-rtsp-firmware-now-available/196922
