### ISSUE TITLE
Night mode - IR led issue

### ISSUE THREAD

**Issue by jokerigno** [EliasKotlyar/Xiaomi-Dafang-Hacks#1662]
Hi,

Don't know if it is hw or sw related but every time I switch on night mode the image is "damaged". Please look at screenshot below![image](https://user-images.githubusercontent.com/23552762/103478096-bc1edc80-4dc4-11eb-9201-ab175bbb935a.png)

Can someone please support me?

**Comment by jokerigno** [comment]
UPDATE: It definitely depends on night mode. If it is off image is PERFECT. Every time is on it is "damaged"

**Comment by pooshok** [comment]
this can be hw issue as night mode has more power consumption. At least you can simple try to reproduce it with other (good) power supply

**Comment by jokerigno** [comment]
following your suggestion I tested it with 2 different usb cable and 2 different usb power supply. The issue is still there, even (it seems at the moment) less intense.

**Comment by jokerigno** [comment]
Another thing I noticed is that this defections is visible only in RTSP streaming. No trace when looking at the image in dafang ui.
