### ISSUE TITLE
Remove password requirement of Still image /cgi-bin/currentpic.cgi

### ISSUE THREAD

**Issue by Prutsium** [EliasKotlyar/Xiaomi-Dafang-Hacks#1666]
Not a bug more a question / feature request.

I use the cams in some systems that wont work with https://root:ismart12@xxx.xxx.xxx.xxx (actually even in a browser i get still a popup window for password)

Is there a way to remove the password requirement?

**Comment by jmtatsch** [comment]
Sure, you need to remove the auth. in the Webserver config file.

**Comment by Prutsium** [comment]
> 
> 
> Sure, you need to remove the auth. in the Webserver config file.

This part you mean:
auth.backend				= "htdigest"
		auth.backend.htdigest.userfile = "/system/sdcard/config/lighttpd.user"
		auth.require = ( "/" => ("method" => "basic", "realm" => "all", "require" => "user=root"))

**Comment by jmtatsch** [comment]
Exactly

**Comment by BiatuAutMiahn** [comment]
It would be nice to make this a configurable option in the webui, and would it be possible to make the still capture faster?

**Comment by zgadgeter** [comment]
> Sure, you need to remove the auth. in the Webserver config file.

Hello, where is the webserver config file? thanks
