### ISSUE TITLE
New Wyze V2 cannot load CFW

### ISSUE THREAD

**Issue by pbruen** [EliasKotlyar/Xiaomi-Dafang-Hacks#1667]
Looks like WYZE V2 cameras that have had newer firmware loaded on them do not allow CFW to install properly.  Doing so returns:
solid orange light for ~3s. a click, light blinks out briefly after another 3s, and repeat.  
Loading an older official firmware prior to CFW  does not improve things

If there is a method around this, I'd love to hear it, as these devices are worthless to me with firmware that requires external connectivity (all the official firmware).  I've seen a few other people describe this in a few different places, but no one seems to respond and (at least in git) the issue gets closed as stale.  :(

**Comment by ardlc0** [comment]
Can confirm that this issue is also happening on my end. I have a Wyze cam V2 purchased from Amazon in December. I have the exact same issues as @pbruen described. Once I write the cfw-1.1.1bin file onto the micro sd card, the flashing process looks like it begins because the light turns from orange to blue, but then it goes back to orange for about 3-6 seconds then turns off, turns back on for another 3 seconds, makes a clicking noise and then turns back off. This repeats until I unplug the device from USB.

Steps in order to replicate issue:
1. **Mount micro sd to filesystem and erase all contents on micro sd.**
     
     Note: I have tried multiple types of micro sd cards and formatted them completely to erase all contents and old partitions. First was a 256mb Kingmax, the second was a 4gb Sandisk, and the third was a 32gb Sandisk ImageMate. For the 4 gb and 32 gb micro sd cards I created the recommended 512mb primary partition with boot flag on both. I also tried using the full sd card capacity for 4gb and 32gb and still no luck. I used the fat32 format for all sd cards tested. I also tried with gpt and ms-dos partition tables. No luck with those either.

2. **Download cfw bin file for the Wyzecam V2 file**. Located here -> https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/raw/master/hacks/cfw/wyzecam_v2/cfw-1.1.bin
     
     Note: I tried also the T2 and Xia0mi dafang cfw bin files. Not able to flash using these either. 

3. **Copy bin file to the micro sd card root. Rename cfw-1.1.bin to "demo.bin"**
4.  **Safely unmount the micro sd and insert into Wyzecam V2 while camera is off and not connected to USB.**
5. **Press the setup button and insert the usb cable to supply power to camera.**
6. **Wait ~20 seconds until orange light turns blue. Release the setup button after light has turned blue.**
7. **After about 2-3 minutes the light will return to orange.**
8. **After another 10 seconds, a "clicking" sound will come from the camera and after 3 seconds the light will turn off**
9. **The camera reboots and will begin flickering orange light, make clicking sounds and turn off again.**
10. **This will repeat until the USB is disconnected.**

The Wyzecam V2 was never able to connect to a router I had setup using simple ssid and password. Also tried with no password.

I retried all of the steps above using a different base firmware located from the manufacturer here for V2 -> https://wyzelabs.zendesk.com/hc/en-us/articles/360024852172-Release-Notes-Firmware

I tried installing dafang hacks with base firmwares:
 4.9.5.115
4.9.6.156
4.9.6.199
4.9.6.218

Info about camera:
Model: WYZEC2
FCCID: 2ANJHWYZEC02
IC: 24984-WYZEC02

Micro sd setups were tested on both macOS and Linux

I look forward to any help on this since this is the only opensource firmware there is for these kinds of cameras. Thanks!

**Comment by rklassen** [comment]
Hi guys - the cfw-1.1.bin does work on the newest WyzeCam v2. Purchased one this month (early January 2021) and got it to work. Biggest issue I had was in the `wpa_supplicant.conf`file. Make sure you only have the following three keys set, the latest dafang hacks repository has more that create problems.

`network={
	ssid="wifiname"
	psk="password"
	key_mgmt=WPA-PSK
}`

**Comment by rklassen** [comment]
> Can confirm that this issue is also happening on my end. I have a Wyze cam V2 purchased from Amazon in December. I have the exact same issues as @pbruen described. Once I write the cfw-1.1.1bin file onto the micro sd card, the flashing process looks like it begins because the light turns from orange to blue, but then it goes back to orange for about 3-6 seconds then turns off, turns back on for another 3 seconds, makes a clicking noise and then turns back off. This repeats until I unplug the device from USB.
> 
> Steps in order to replicate issue:
> 
> 1. **Mount micro sd to filesystem and erase all contents on micro sd.**
>    Note: I have tried multiple types of micro sd cards and formatted them completely to erase all contents and old partitions. First was a 256mb Kingmax, the second was a 4gb Sandisk, and the third was a 32gb Sandisk ImageMate. For the 4 gb and 32 gb micro sd cards I created the recommended 512mb primary partition with boot flag on both. I also tried using the full sd card capacity for 4gb and 32gb and still no luck. I used the fat32 format for all sd cards tested. I also tried with gpt and ms-dos partition tables. No luck with those either.
> 2. **Download cfw bin file for the Wyzecam V2 file**. Located here -> https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/raw/master/hacks/cfw/wyzecam_v2/cfw-1.1.bin
>    Note: I tried also the T2 and Xia0mi dafang cfw bin files. Not able to flash using these either.
> 3. **Copy bin file to the micro sd card root. Rename cfw-1.1.bin to "demo.bin"**
> 4. **Safely unmount the micro sd and insert into Wyzecam V2 while camera is off and not connected to USB.**
> 5. **Press the setup button and insert the usb cable to supply power to camera.**
> 6. **Wait ~20 seconds until orange light turns blue. Release the setup button after light has turned blue.**
> 7. **After about 2-3 minutes the light will return to orange.**
> 8. **After another 10 seconds, a "clicking" sound will come from the camera and after 3 seconds the light will turn off**
> 9. **The camera reboots and will begin flickering orange light, make clicking sounds and turn off again.**
> 10. **This will repeat until the USB is disconnected.**
> 
> The Wyzecam V2 was never able to connect to a router I had setup using simple ssid and password. Also tried with no password.
> 
> I retried all of the steps above using a different base firmware located from the manufacturer here for V2 -> https://wyzelabs.zendesk.com/hc/en-us/articles/360024852172-Release-Notes-Firmware
> 
> I tried installing dafang hacks with base firmwares:
> 4.9.5.115
> 4.9.6.156
> 4.9.6.199
> 4.9.6.218
> 
> Info about camera:
> Model: WYZEC2
> FCCID: 2ANJHWYZEC02
> IC: 24984-WYZEC02
> 
> Micro sd setups were tested on both macOS and Linux
> 
> I look forward to any help on this since this is the only opensource firmware there is for these kinds of cameras. Thanks!

If you experience step 9, this is normal. Unplug the camera, wipe the sdcard, add the config files.

One more thing to note (assuming you're connecting to homebridge) and after you can see the camera in the browser: be sure to set a static ip:

1. delete the ".dist" extension to "staticip.conf"
2. Empty the staticip.conf file and add one line: `XXX.XXX.X.XXX netmask 255.255.255.0` where you set the XXX values.
2. Then login to your router and reserve the IP address so the router doesn't give it to a different device.

This last step is necessary to get snapshots into your app and for the rtsp stream to work for video feeds.

**Comment by Jorloja** [comment]
No joy here either. Same as Ardlc0, just yellow light and clicks no matter what I do, different firmwares (including beta RTSP) including the modified wpa_supplicant.

**Comment by seetheviz** [comment]
It's possible this is related to a hardware revision on newer V2s vs newer firmware. 
I purchased two V2s recently and both have the changes noted at the below link, and I am unable to flash- I get the repeating click/reset/whatever it's doing. 

https://www.reddit.com/r/wyzecam/comments/jyc9jo/does_the_new_version_of_the_wyze_cam_v2_hardware/gde2k7c?utm_source=share&utm_medium=web2x&context=3

**Comment by rklassen** [comment]
> It's possible this is related to a hardware revision on newer V2s vs newer firmware.
> I purchased two V2s recently and both have the changes noted at the below link, and I am unable to flash- I get the repeating click/reset/whatever it's doing.
> 
> https://www.reddit.com/r/wyzecam/comments/jyc9jo/does_the_new_version_of_the_wyze_cam_v2_hardware/gde2k7c?utm_source=share&utm_medium=web2x&context=3

What are your V2 specs (SN, factory firmware version, etc)? I purchased two more units this week from amazon, will try flashing this weekend and will post results

What kind of machine (pc, Mac, raspberry pi) are you using to format the SD? When flashing make sure the total partition size is less than 512 MB

**Comment by Jorloja** [comment]
Tried it and still no joy.. click.. click.. click. I'll contact the person and see if they can suggest anything.

**Comment by bshirgur** [comment]
I am having a same clicking problem with two V2s that were purchased recently. @rklassen , can you post the link to the Reddit thread about the fix? Thanks.

**Comment by bshirgur** [comment]
I am having a same clicking problem with two V2s that were purchased recently. @rklassen , can you post the link to the Reddit thread about the fix? Thanks.

**Comment by jay3702** [comment]
I have precisely same issue. I tried the solution posted on Reddit: https://www.reddit.com/r/wyzecam/comments/jyc9jo/does_the_new_version_of_the_wyze_cam_v2_hardware/ 

But, it doesn't work form me. The author of that post told me that he is now having the same issue with a new camera.

**Comment by McNutnut** [comment]
Currently I have 3x Wyzev2 2ANJHWYZE**C2** which all work fine with cfw-1.1.bin.   I purchased 4x Wyzev2 last week that were 2ANJHWYZE**C02** and they all experienced the bootloop with cfw-1.1.bin.

I found [users on the Wyze Forums reporting](https://forums.wyzecam.com/t/rtsp-4-28-4-41-on-new-v2-cams/136439) a similar bootloop a few months back when attempting to use the latest RTSP firmware on newer purchased cameras.  Subsequently [an update to the RTSP firmware](https://forums.wyzecam.com/t/new-rtsp-binaries-for-beta-testing/145275) was released to fix the issue.

At your own risk, [here is an updated demo.bin](https://mcnutnut.com/dafang/cfw-1.2.bin) that has been based on the [latest RTSP firmware](https://download.wyzecam.com/firmware/rtsp/demo_v2_rtsp_4.28.4.49.bin.zip) with [SD card mounting fixes](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/986) thanks to @mbevand 

So far I've flashed this on 2 of the new purchased cameras with 2ANJHWYZE**C02** and have successfully booted into the latest `firmware_mod`.  It also boots into the stock (RTSP) firmware as well without an SD-card/mod installed (though I haven't gone through the 'scan qr code' setup, but setup button triggers setup voice)

**Comment by jay3702** [comment]
@McNutnut, @mbevand Thanks, that did the trick!

**Comment by pbruen** [comment]
I'm going to mark this as closed, though I have not personaly tested the fix (I ended up returning my cameras, and went with something that allows RTSP natively - eufy)

**Comment by bshirgur** [comment]
Thanks so much. My primary reason to choose Wyze was prevent them from communicating with cloud servers outside of US.



I suppose that Eufy mods don't have that capability, do they as far as you know?



Badri

On February 1, 2021 at 11:23 AM, Patrick Bruen <notifications@github.com> wrote:






I'm going to mark this as closed, though I have not personaly tested the fix (I ended up returning my cameras, and went with something that allows RTSP natively - eufy)

**Comment by rklassen** [comment]
> Currently I have 3x Wyzev2 2ANJHWYZE**C2** which all work fine with cfw-1.1.bin. I purchased 4x Wyzev2 last week that were 2ANJHWYZE**C02** and they all experienced the bootloop with cfw-1.1.bin.
> 
> I found [users on the Wyze Forums reporting](https://forums.wyzecam.com/t/rtsp-4-28-4-41-on-new-v2-cams/136439) a similar bootloop a few months back when attempting to use the latest RTSP firmware on newer purchased cameras. Subsequently [an update to the RTSP firmware](https://forums.wyzecam.com/t/new-rtsp-binaries-for-beta-testing/145275) was released to fix the issue.
> 
> At your own risk, [here is an updated demo.bin](https://github.com/McNutnut/Xiaomi-Dafang-Hacks/blob/208ab7d971be2c5558cd0179683847e06ec8cea9/hacks/cfw/wyzecam_v2/cfw-1.2.bin) that has been based on the [latest RTSP firmware](https://download.wyzecam.com/firmware/rtsp/demo_v2_rtsp_4.28.4.49.bin.zip) with [SD card mounting fixes](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/986) thanks to @mbevand
> 
> So far I've flashed this on 2 of the new purchased cameras with 2ANJHWYZE**C02** and have successfully booted into the latest `firmware_mod`. It also boots into the stock (RTSP) firmware as well without an SD-card/mod installed (though I haven't gone through the 'scan qr code' setup, but setup button triggers setup voice)

Thanks @McNutnut !!! The new cfw-1.2.bin saved my two new WCV2's! It works!

**Comment by pbruen** [comment]
@bshirgur - My experience with Eufy so far is that they survive reboots with no external access (some configs changes seem to need external access to take effect) - and RTSP works out of the box - so it is close enough to meet my needs and I haven't even looked into modding it.

**Comment by ZuluWhiskey** [comment]
> Currently I have 3x Wyzev2 2ANJHWYZE**C2** which all work fine with cfw-1.1.bin.   I purchased 4x Wyzev2 last week that were 2ANJHWYZE**C02** and they all experienced the bootloop with cfw-1.1.bin.
> 
> 
> 
> I found [users on the Wyze Forums reporting](https://forums.wyzecam.com/t/rtsp-4-28-4-41-on-new-v2-cams/136439) a similar bootloop a few months back when attempting to use the latest RTSP firmware on newer purchased cameras.  Subsequently [an update to the RTSP firmware](https://forums.wyzecam.com/t/new-rtsp-binaries-for-beta-testing/145275) was released to fix the issue.
> 
> 
> 
> At your own risk, [here is an updated demo.bin](https://github.com/McNutnut/Xiaomi-Dafang-Hacks/blob/208ab7d971be2c5558cd0179683847e06ec8cea9/hacks/cfw/wyzecam_v2/cfw-1.2.bin) that has been based on the [latest RTSP firmware](https://download.wyzecam.com/firmware/rtsp/demo_v2_rtsp_4.28.4.49.bin.zip) with [SD card mounting fixes](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/986) thanks to @mbevand 
> 
> 
> 
> So far I've flashed this on 2 of the new purchased cameras with 2ANJHWYZE**C02** and have successfully booted into the latest `firmware_mod`.  It also boots into the stock (RTSP) firmware as well without an SD-card/mod installed (though I haven't gone through the 'scan qr code' setup, but setup button triggers setup voice)

I have a Neos camera that I'm trying to flash unsuccessfully at the moment. I've just tried to follow the link to 1.2 but I'm getting an error, has this been removed now? 😩

**Comment by ashjas** [comment]
> Currently I have 3x Wyzev2 2ANJHWYZE**C2** which all work fine with cfw-1.1.bin. I purchased 4x Wyzev2 last week that were 2ANJHWYZE**C02** and they all experienced the bootloop with cfw-1.1.bin.
> 
> I found [users on the Wyze Forums reporting](https://forums.wyzecam.com/t/rtsp-4-28-4-41-on-new-v2-cams/136439) a similar bootloop a few months back when attempting to use the latest RTSP firmware on newer purchased cameras. Subsequently [an update to the RTSP firmware](https://forums.wyzecam.com/t/new-rtsp-binaries-for-beta-testing/145275) was released to fix the issue.
> 
> At your own risk, [here is an updated demo.bin](https://github.com/McNutnut/Xiaomi-Dafang-Hacks/blob/208ab7d971be2c5558cd0179683847e06ec8cea9/hacks/cfw/wyzecam_v2/cfw-1.2.bin) that has been based on the [latest RTSP firmware](https://download.wyzecam.com/firmware/rtsp/demo_v2_rtsp_4.28.4.49.bin.zip) with [SD card mounting fixes](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/986) thanks to @mbevand
> 
> So far I've flashed this on 2 of the new purchased cameras with 2ANJHWYZE**C02** and have successfully booted into the latest `firmware_mod`. It also boots into the stock (RTSP) firmware as well without an SD-card/mod installed (though I haven't gone through the 'scan qr code' setup, but setup button triggers setup voice)

Hello, thanks for these firmwares, i can run successfully dafang hack.
But there is no audio of any kind in whatever videos are produced.
Is this same for you or is this a known issue on dafang hack and we will have to live with it ?

Thanks for your help.

**Comment by 87435** [comment]
Sorry for digging out an old thread here - I have 2 v2 that I am trying to "unbrick". They were on the latest firmware at some point, does that mean there is no way to downgrade now and use Dafang Hacks? I've been unable to flash using CFW 1.1 or 1.2
