### ISSUE TITLE
Send Mail Problem

### ISSUE THREAD

**Issue by bfoss2** [EliasKotlyar/Xiaomi-Dafang-Hacks#1670]
Hi Guys,

I've had problems with the "sendPictureMail.sh" file.
The Mail is never send out. But I've solved it.

At the end of the sendPictureMail.sh was this, but is doesn't worked.

 } | /system/sdcard/bin/busybox sendmail \
 -H"exec /system/sdcard/bin/openssl s_client -CAfile /system/sdcard/config/ssl/cacert/cacert.pem -quiet -connect $SERVER:$PORT -**starttls** smtp" \
 -f"$FROM" -au"$AUTH" -ap"$PASS" $TO 2>/dev/null

I've changed it to:

} |  /system/sdcard/bin/busybox sendmail \
-H"exec /system/sdcard/bin/openssl s_client -quiet -connect $SERVER:$PORT -**tls1_2**" \
-f"$FROM" -au"$AUTH" -ap"$PASS" $TO 2>/dev/console

and this worked, please change it in the future updates.
Thanx

**Comment by empierre** [comment]
trying it too

**Comment by empierre** [comment]
useless, went back to #1362 till less secure apps works on gmail
