### ISSUE TITLE
 iCamera KEEP Pro support?

### ISSUE THREAD

**Issue by fotiDim** [EliasKotlyar/Xiaomi-Dafang-Hacks#1677]
I have a couple of "iCamera KEEP Pro"s from iSmartAlarm. Since they are shutting down operations and their cloud does not work anymore I wonder if this custom firmware is compatible with them. On the outside they look exactly like the dafang except that they are black: https://www.amazon.com/iSmartAlarm-Security-Tracking-Compatible-iSC3S/dp/B06XWQQN3T

**Comment by DJbanek** [comment]
Hey, I'm interessting to try this hack on IsmartAlarm Icamera Keep Products too. Works for anyone with this hardware? I try to copy these files on USB Stick but it won't work. Failed.
Maybe someone can try it too? I used a 4GB USB Stick and a Icamera Keep...

**Comment by fotiDim** [comment]
I took the camera apart and took some pictures of the boards. Hope they give us a clue if the camera can be supported or not.

![IMG_3163](https://user-images.githubusercontent.com/2326415/114420923-70e34980-9bbd-11eb-8f8e-855e5eda81ed.jpeg)
![IMG_3156](https://user-images.githubusercontent.com/2326415/114420884-6923a500-9bbd-11eb-8406-4a54c5c96deb.jpeg)
![IMG_3157](https://user-images.githubusercontent.com/2326415/114420907-6de85900-9bbd-11eb-9c6a-7e4d8bb235b7.jpeg)
![IMG_3155](https://user-images.githubusercontent.com/2326415/114420910-6f198600-9bbd-11eb-853d-c235919152e8.jpeg)
![IMG_3161](https://user-images.githubusercontent.com/2326415/114420915-6fb21c80-9bbd-11eb-904f-d1eb2b0f046c.jpeg)
![IMG_3162](https://user-images.githubusercontent.com/2326415/114420921-704ab300-9bbd-11eb-9c30-0705fb8cd5c8.jpeg)
![IMG_3158](https://user-images.githubusercontent.com/2326415/114420926-717be000-9bbd-11eb-80f5-120943b8c769.jpeg)

**Comment by steventran87** [comment]
any update?
