### ISSUE TITLE
ROM alerting firewall: ET MALWARE Beizhu/Womble/Vipdataend Controller Keepalive

### ISSUE THREAD

**Issue by bachmannn** [EliasKotlyar/Xiaomi-Dafang-Hacks#1678]
**Informations**
* exact camera hardware: WyzeCam
* the Xiaomi-Dafang-Hacks commitid (from `git log`) you are experiencing the issue with: `master`

### Description

I flashed the Dafang Hacks ROM bins but my network firewall is detecting `network trojan` alert from the device. This does not happen with stock rom.

```
ET MALWARE Beizhu/Womble/Vipdataend Controller Keepalive
A Network Trojan was detected
```

Please explain which part of the source code would cause this alert to go off from Dafang-Hacks ROM to confirm its false positive or if prebuilt ROM contains mallicous code.

**Has anyone done PCAP on the rom to see if its connecting externally or acting suspiciously?**

**Comment by jmtatsch** [comment]
Try if you still get the alert with all services in services tab deactivated.
