### ISSUE TITLE
sannce_i141cb_v2.bin + bg0806 + kernel Linux version 3.10.14 (eko@eko-GE62VR-6RF) (gcc version 4.7.2 (Ingenic r2.3.3 2016.12) )

### ISSUE THREAD

**Issue by markonym** [EliasKotlyar/Xiaomi-Dafang-Hacks#1688]
Hi
I want to ask questions about an old problem that is already closed.
I have sannce clone

![1613981599272](https://user-images.githubusercontent.com/62997132/108681303-ae015880-74f7-11eb-8f1b-29c4c4d69fb8.jpg)
![1613981599264](https://user-images.githubusercontent.com/62997132/108681340-b6f22a00-74f7-11eb-9362-5635e1ca33f4.jpg)

  and I did reflashing uboot sannce_i141cb_v2.bin, put in ext3 sdcard rootfs as described in sannce.md.

[dmesg.txt](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/files/6020577/dmesg.txt)

[rcS.txt](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/files/6020590/rcS.txt)

[v4l2rtspserver-master.txt](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/files/6020603/v4l2rtspserver-master.txt)

[v4l2rtspserver-master.txt](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/files/6020633/v4l2rtspserver-master.txt)
sensor datasheet --> http://www.brigates.com/product/3.html   bg0806应用指南_v2.0.pdf

I can boot and reach camera site but I can't see any picture and can't move PT.
I saw in original rootfs that it use different image sensor BG0806.
I used kernel-t20.bin on uEnv.txt. on rcS I used mt7601Usta.ko , disable dafang sensor and added sensor_bg0806.ko and module bg0806.bin that I extracted from original flash dump.

Whatever I tried, there is no video ... how can I do it?

**Comment by markonym** [comment]
[CMOS Image Sensor Knowledge Base](https://www.goprawn.com/forum/lens-and-sensor-talks/8762-cmos-image-sensor-knowledge-base)

**Comment by markonym** [comment]
[CMOS Image Sensor Knowledge Base](https://www.goprawn.com/forum/lens-and-sensor-talks/8762-cmos-image-sensor-knowledge-base)

**Comment by yeyeto2788** [comment]
Hey @markonym, 

What voltage did you use to gather serial data? Do mind sharing a picture of the board? I have a Sannce camera that I want to dump the info also.

**Comment by markonym** [comment]
Hello colleague, my camera is a Chinese clone of Sannce with a cpu Ingenic T20. For serial communication use 3.3 volts.

**Comment by yeyeto2788** [comment]
> Hello colleague, my camera is a Chinese clone of Sannce with a cpu Ingenic T20. For serial communication use 3.3 volts.

Hey! Thanks for the reply. I have a camera called Ankee but looks similar to the Sannce one. ![20211124_153532.jpg](https://user-images.githubusercontent.com/6363686/143278156-ea68f419-6f18-44bc-9d30-0fbb663f65b7.jpg) and wanted to know the normal voltage used for serial communication on the CPU.

**Comment by markonym** [comment]
Make it look the same as my camer
![RxTxpng](https://user-images.githubusercontent.com/62997132/143282212-e9579abe-3030-41ed-baf1-4402fbb3e471.png)
a!

**Comment by yeyeto2788** [comment]
Awesome! Thank you very much @markonym .Did your camera finally worked? 

@EliasKotlyar is there anything to be done in regards making it work?

**Comment by markonym** [comment]
Before you start doing various experiments with the camera, be sure to make a dump on the flash !!!

**Comment by markonym** [comment]
To work as a device but no picture from the sensor

**Comment by yeyeto2788** [comment]
@markonym I'll keep it in mind. The weird part is that using 115200 baud rate I do not get any console output

**Comment by markonym** [comment]
What usb to uart converter are you using?

**Comment by yeyeto2788** [comment]
FTDI USB to serial converter

![image](https://i.ebayimg.com/images/g/SSEAAOSwYHxWNmcn/s-l400.jpg)

**Comment by markonym** [comment]
Wonderful!

**Comment by yeyeto2788** [comment]
Seems like I'm now able to log into the camera as root and do some things on it. @markonym did you get it work with the hacks? Is there an option to open up this issue again? My camera is based on a T10 but I guess most of the hacks should work.

@EliasKotlyar any way I can help on this?

**Comment by markonym** [comment]
Yes Elias hacks work for me. Download and flash this bootloader - sannce_i21ag_v2.bin ( for Ingenic T10).

**Comment by markonym** [comment]
Which who terminal program are you working ?
I use Tera Term !

**Comment by yeyeto2788** [comment]
> Yes Elias hacks work for me. Download and flash this bootloader - sannce_i21ag_v2.bin ( for Ingenic T10).

I thought your camera was a T20 one. Ok  I'll try that then.

I'm using picocom and now I can get full access to the terminal via serial or telnet.

**Comment by markonym** [comment]
Yes my camera is with T20.
But your bootloader is sannce_i21ag_v2.bin mine is different.

**Comment by markonym** [comment]
Do you see U-Boot already ?

**Comment by yeyeto2788** [comment]
Yes I was able to see u-boot and even set some bootargs. I'll try that firmware after I dump everything from the camera as a safety measure.
