### ISSUE TITLE
trouble with password-protected streams

### ISSUE THREAD

**Issue by herrxyz** [EliasKotlyar/Xiaomi-Dafang-Hacks#169]
Hello,
I want to protect my streams with username and password

~~in folder firmware_mod / config, file "rtsp-h264" and "rtsp-mjpeg", I can add parameter "-U user1:password1" to get an encrypted rtsp-stream (in line with /system/sdcard/bin/busybox nohup /system/sdcard/bin/v4l2rtspserver-master -U user1:password1 &>/dev/null & )
unfortunately, if I do the same in run.sh, it don't asks for a password after reboot~~

suggestion: add config-file for stream-users & passwords and use them instead of hardcoding in ech config file? unfortunately, at the moment I don't know how to do it

Version 5.5.1.243

edit: info about parameters found [here](https://github.com/mpromonet/v4l2rtspserver/issues/29)
edit2: it works, I just forgot to copy it to SD-card

**Comment by helio58** [comment]
@herrxyz 
I don't know way but if you add this in the run.sh it works
-fH264 -U user1:password1

**Comment by shinebar1001** [comment]
Actually, I second the config-file for the v4l2rtspserver. Unfortunately I'm quite short of time at the moment.

**Comment by herrxyz** [comment]
shame on me, I didn't copy the file to sd-card, changed it only on my computer ;-(
it works without additional "-fH264" parameter, but thanks for your try :-)

anyway, config file would be great, I'll try it and if it works I'll commit it
