### ISSUE TITLE
mqtt cover for left/right & up/down not valid in the latest Home Assistant (2021.3.1)

### ISSUE THREAD

**Issue by realthk** [EliasKotlyar/Xiaomi-Dafang-Hacks#1695]
mqtt-autodiscovery.sh creates MQTT covers for horizontal and vertical movement [with "value_template"](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/972ba9d5cfcc48c1f8863f9c6f8001bdc99284be/firmware_mod/scripts/mqtt-autodiscovery.sh#L71), which is deprecated now, according to the log message:
`
2021-03-05 16:02:44 WARNING (MainThread) [homeassistant.components.mqtt.cover] using 'value_template' for 'position_topic' is deprecated and will be removed from Home Assistant in version 2021.6, please replace it with 'position_template'
`

**Comment by Fietspomp86** [comment]
Just made a very simple PR, replaced value_template for position_template in mqtt-autodiscovery.sh

**Comment by SAOPP** [comment]
Guys, it's not clear over here, how to back this functionality again?
