### ISSUE TITLE
Software Auto Night Settings - Some Text. Some Text

### ISSUE THREAD

**Issue by rechena** [EliasKotlyar/Xiaomi-Dafang-Hacks#1697]
This is an issue tracking system only.
If you have general questions or are a newbie, please ask for help in our [chat channel](https://gitter.im/Xiaomi-Dafang-Hacks).

To make sure your issue can be resolved as quickly as possible please state your

* Neos Smartcam
* Latest release cloned yesterday

### Description

When I hit Save on the Software Auto Night Settings the following message shows up. 

### What did you do to debug the issue

Just tried on several other cameras and the same happens. 

### Evidence

![image](https://user-images.githubusercontent.com/3226822/110201979-ceb5a080-7e5d-11eb-9391-05ca1cba9a6a.png)

and/or screenshots you deem relevant.

### Contribute Back

If your issue was resolved, please consider contributing back to the project by creating a pull request to improve the code or documentation in order to avoid that this issue arises again for other people.

**Comment by fhl206** [comment]
This is an issue in [softnight.html](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/972ba9d5cfcc48c1f8863f9c6f8001bdc99284be/firmware_mod/www/softnight.html#L21) from line 21:

`<tr><td colspan="2">`
`<input style="display: block; text-align: center; margin: auto;" class='button is-primary' id="sw_night_submit" type="submit" value="Save">`
`<button onclick="document.getElementById('id01').style.display='block'" class="w3-button w3-black">Save</button>`
`</td></tr>`

The first button in grey beneath the commandline text will save the parameters. The second button in black was introduced with the new UI whose only action at the moment is to show the text. I'm not confident enough to fix the issue myself though.
