### ISSUE TITLE
mjpegStreamer segfaults instantly

### ISSUE THREAD

**Issue by jmtatsch** [EliasKotlyar/Xiaomi-Dafang-Hacks#17]
```
[root@DAFANGHACKS:~]# /system/sdcard/bin/mjpegStreamer 10
Play this stream using the URL "rtsp://192.168.180.30:7070/"
Beginning streaming...
Polling stream timeout
Segmentation fault
```

Unfortunately I cannot get a proper core dump, the following is logged in dmesg:

```
[ 1264.019955] do_page_fault() #2: sending SIGSEGV to mjpegStreamer for invalid read access from
[ 1264.019955] 00000000 (epc == 00402a50, ra == 00402990)
```

**Comment by EliasKotlyar** [comment]
Many thanks for this report. I will try to fix this soon

**Comment by jbeck22** [comment]
I'm experiencing this as well -- any testing please let me know.

**Comment by EliasKotlyar** [comment]
I have fixxed this. Now it should work as expected.

**Comment by jbeck22** [comment]
Updated and this does work.  Question -- how is this different than the other RTSP Server on the page status page?

**Comment by dmolner** [comment]
Hello,
Great work!!!

When rtsp is on my mouse work slow.

Best regards,
David.

**Comment by ril3y** [comment]
Not the same issue as the segfault.  But yes there is something wonky going
on the RTSP streaming shuts down my dd-wrt network.  I have not looked at
it in wireshark but there is something crazy going on.

**Comment by EliasKotlyar** [comment]
@jbeck22 : The MJPEG RTSP transfers the images in JPEG-Format and the H264 transfers them in h264.

@dmolner : Thats normal, its not supposed to be fast because of the format. The H264 Stream should be fast.

@ril3y : Its a UDP-Multicast Stream. I suppose its breaking down the network because its sending everything using multicast.

**Comment by jmtatsch** [comment]
Works perfectly now, thanks for fixing!
