### ISSUE TITLE
Disable https so that the camera is usable with Chrome again?

### ISSUE THREAD

**Issue by PaulAntonDeen** [EliasKotlyar/Xiaomi-Dafang-Hacks#1706]
This is an issue tracking system only.
If you have general questions or are a newbie, please ask for help in our [chat channel](https://gitter.im/Xiaomi-Dafang-Hacks).

To make sure your issue can be resolved as quickly as possible please state your

* exact camera hardware:
* the Xiaomi-Dafang-Hacks commitid (from `git log`) you are experiencing the issue with:

### Description
Upon loading the web interface with Chrome 89 on mac I do no longer get the option to ignore the security warning so I cannot get to the web interface anymore and need to use safari instead. I would like ot disable https if possible.

### What did you do to debug the issue

Tell us what you did to remedy/debug the issue yourself and what you think causes the issue.
![image](https://user-images.githubusercontent.com/25848961/111133749-2600f280-857b-11eb-9ebd-21b1a49f8a69.png)

### Evidence

Please add snippets from the logfiles in:
* /system/sdcard/log/startup.log
* /var/log/*
* dmesg
* logcat
and/or screenshots you deem relevant.

### Contribute Back

If your issue was resolved, please consider contributing back to the project by creating a pull request to improve the code or documentation in order to avoid that this issue arises again for other people.

**Comment by redood** [comment]
One trick that still works:
When you see "Your connection is not private" message, just type on your keyboard "thisisunsafe" (basically "this is unsafe" all one word, without the quotes). You don't need to type it into any location or search box; just type those characters and Chrome will bypass this warning.
