### ISSUE TITLE
Wifi does not connect

### ISSUE THREAD

**Issue by Arkady23** [EliasKotlyar/Xiaomi-Dafang-Hacks#1707]
The 1S iSC5 camera. 
WiFi stopped connecting. 

2 times WiFi was connected. 1 time via Mi-home, 2 times via Xiaomi-Dafang-Hacks. Further connections did not occur any more. I wrote a test script run.sh:

`MAC=$(grep MAC < /params/config/.product_config | cut -c16-27 | sed 's/\(..\)/\1:/g;s/:$//')`
`insmod /driver/8189fs.ko rtw_initmac="$MAC"`
`/system/bin/wpa_supplicant -d -B -P /var/run/wpa_supplicant.pid -i wlan0 -c /system/sdcard/config/wpa_supplicant.conf > /system/sdcard/log/startup.log`

In the logs, the answer is: 

>wpa_supplicant v2.5.nova.1.02
random: Trying to read entropy from /dev/random
Successfully initialized wpa_supplicant
Initializing interface 'wlan0' conf '/system/sdcard/config/wpa_supplicant.conf' driver 'default' ctrl_interface 'N/A' bridge 'N/A'
Configuration file '/system/sdcard/config/wpa_supplicant.conf' -> '/system/sdcard/config/wpa_supplicant.conf'
Reading configuration file '/system/sdcard/config/wpa_supplicant.conf'
ctrl_interface='/var/run/wpa_supplicant'
ctrl_interface_group='0'
ap_scan=1
Priority group 0
   id=0 ssid='Dlink_41'
nl80211: Could not add multicast membership for vendor events: -2 (No such file or directory)
rfkill: Cannot open RFKILL control device
nl80211: RFKILL status not available
nl80211: Supported cipher 00-0f-ac:1
nl80211: Supported cipher 00-0f-ac:5
nl80211: Supported cipher 00-0f-ac:2
nl80211: Supported cipher 00-0f-ac:4
nl80211: Disable use_monitor with device_ap_sme since no monitor mode support detected
nl80211: interface wlan0 in phy phy0
nl80211: Set mode ifindex 2 iftype 2 (STATION)
nl80211: Subscribe to mgmt frames with non-AP handle 0x8a4218
nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x8a4218 match=06
nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x8a4218 match=0a07
nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x8a4218 match=0a11
nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x8a4218 match=1101
nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x8a4218 match=1102
nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x8a4218 match=0505
netlink: Operstate: ifindex=2 linkmode=1 (userspace-control), operstate=5 (IF_OPER_DORMANT)
nl80211: Could not re-add multicast membership for vendor events: -2 (No such file or directory)
nl80211: driver param='(null)'
Add interface wlan0 to a new radio phy0
nl80211: Regulatory information - country=00
nl80211: 2402-2472 @ 40 MHz 20 mBm
nl80211: 2457-2482 @ 40 MHz 20 mBm (no IR)
nl80211: 2474-2494 @ 20 MHz 20 mBm (no OFDM) (no IR)
nl80211: 5170-5250 @ 80 MHz 20 mBm (no IR)
nl80211: 5735-5835 @ 80 MHz 20 mBm (no IR)
nl80211: 57240-63720 @ 2160 MHz 0 mBm
nl80211: Added 802.11b mode based on 802.11g information
wlan0: Own MAC address: e4:aa:ec:23:77:fc
wpa_driver_nl80211_set_key: ifindex=2 (wlan0) alg=0 addr=(nil) key_idx=0 set_tx=0 seq_len=0 key_len=0
wpa_driver_nl80211_set_key: ifindex=2 (wlan0) alg=0 addr=(nil) key_idx=1 set_tx=0 seq_len=0 key_len=0
wpa_driver_nl80211_set_key: ifindex=2 (wlan0) alg=0 addr=(nil) key_idx=2 set_tx=0 seq_len=0 key_len=0
wpa_driver_nl80211_set_key: ifindex=2 (wlan0) alg=0 addr=(nil) key_idx=3 set_tx=0 seq_len=0 key_len=0
wlan0: RSN: flushing PMKID list in the driver
nl80211: Flush PMKIDs
wlan0: Setting scan request: 0.100000 sec
ENGINE: Loading dynamic engine
ENGINE: Loading dynamic engine
EAPOL: SUPP_PAE entering state DISCONNECTED
EAPOL: Supplicant port status: Unauthorized
nl80211: Skip set_supp_port(unauthorized) while not associated
EAPOL: KEY_RX entering state NO_KEY_RECEIVE
EAPOL: SUPP_BE entering state INITIALIZE
EAP: EAP entering state DISABLED
ctrl_interface_group=0
wlan0: Added interface wlan0
wlan0: State: DISCONNECTED -> DISCONNECTED
nl80211: Set wlan0 operstate 0->0 (DORMANT)
netlink: Operstate: ifindex=2 linkmode=-1 (no change), operstate=5 (IF_OPER_DORMANT)
Writing wpa stat file /tmp/wpastat
Daemonize..

Help, please.

**Comment by Snotmann** [comment]
Got the same ... after first boot wifi wont reconnect ... dont know whats happen :(

**Comment by Whitou** [comment]
Same here... Google a lot of shit and tried many... still no luck

**Comment by jmtatsch** [comment]
Do you have several cameras with the same MAC adress on the same network?

**Comment by Whitou** [comment]
Nope, I just went through the whole DHCP entries

**Comment by jmtatsch** [comment]
Did you read that issue https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/718

**Comment by Whitou** [comment]
Yup just went through. Many issues there 😅 will look again tomorrow. 
I just tried to download and start fresh with a new SD, got to the same point. (FIY, I'm working on a Dafang, just realised OP was on 1S).
FIY 2 : cam working with Mi App.
Cheers

**Comment by nurikk** [comment]
same here

**Comment by nurikk** [comment]
Hey guys, I had same issue. But i've noticed that I've been flashing wrong `demo.bin` file, after I flashed correct `Xiaomi XiaoFang T20` then it worked!
