### ISSUE TITLE
Running audioplay changes audio device setting and this prevents v4l2rtspserver from correctly recording audio from that point on

### ISSUE THREAD

**Issue by gz7-design** [EliasKotlyar/Xiaomi-Dafang-Hacks#1708]
The camera hardware is Wyze Cam v2. Commit ID is f7c4a0ef49d911e56da79cf29448c5dead34da8e.

### Description

I've noticed that v4l2rtspserver and audioplay have some issues working together. Basically they each work fine on their own, i.e. v4l2rtspserver captures video and audio and audioplay plays audio all without issues, but if you use audioplay just once, v4l2rtspserver can no longer capture audio correctly since that point. Other than the audio, video capture itself continues to work normally. 

My guess is that audioplay actually comes in and changes the audio device's settings without v4l2rtspserver's knowing. The workaround I've found is to restart v4l2rtspserver every time after using audioplay. 

What I am trying to achieve is that audioplay doesn't interfere with v4l2rtspserver any more, maybe by saving original device settings before playing the audio and restoring the original device settings afterwards.

### What did you do to debug the issue

I've tested many times. After a camera cold restart, it only takes one audioplay command such as "/system/sdcard/bin/audioplay /system/sdcard/media/police.wav" for this problem to happen. 

### Evidence

I haven't seen any additional error logs associated with this issue. It's just videos captured from that point on will not have correct audio, like gibberish. 

### Contribute Back

If your issue was resolved, please consider contributing back to the project by creating a pull request to improve the code or documentation in order to avoid that this issue arises again for other people.

**Comment by und3f1ned** [comment]
This is definitely a bug. But if you set camera audio format to PCM and sample rate to 8000 then rtsp audio will seems to be fine
