### ISSUE TITLE
What Does Dafang Hacks Look Like?

### ISSUE THREAD

**Issue by brianmichalk1** [EliasKotlyar/Xiaomi-Dafang-Hacks#1710]
I could not get Dafang-Hacks working on my new V2, so I installed OpenMiko, which is working.
I don't want the unknowns associated with the stock Wyze firmware, and I am curious what DH provides (since I can't evaluate it).

Perhaps a web configuration interface is too much to ask, and I'm okay with logging in SSH, or editing files on the SD card directly.  But, does DH provide motion detection in the camera?  And, does the microphone/speaker work?

**Comment by SaturnusDJ** [comment]
I have no been active here much anymore in trying the lastest versions but this probably still goes: There is a webinterface, it works well. There is motion detection, with some configuration options. I don’t use it. Mine run relatively stable now but getting there was a hell. Also see the many issues that always are open in this repo. There are other nice software things like controllable via MQTT.

Few days ago a friend bought new cheap Chinese cams. The improvement in quality over the Dafangs is huge. Not sure if that is software. I am sure my cams (FHD) will start crashing again when I change quality. Of course those new cams don’t have custom operating system so China can monitor you, I won’t buy them. Nevertheless I would not recommend Dafang anymore.

**Comment by digiltd** [comment]
Here you go

![Screen Shot 2021-03-25 at 12 59 45](https://user-images.githubusercontent.com/5680968/112478592-14ce9780-8d6c-11eb-9def-e99e44f5c3ed.jpg)
![Screen Shot 2021-03-25 at 12 59 54](https://user-images.githubusercontent.com/5680968/112478607-17c98800-8d6c-11eb-9247-aec821705112.jpg)
![Screen Shot 2021-03-25 at 13 00 10](https://user-images.githubusercontent.com/5680968/112478611-18621e80-8d6c-11eb-8ad2-764121e833ae.jpg)
![Screen Shot 2021-03-25 at 13 00 30](https://user-images.githubusercontent.com/5680968/112478613-18fab500-8d6c-11eb-982b-6a4f0b65aeda.jpg)
![Screen Shot 2021-03-25 at 13 00 50](https://user-images.githubusercontent.com/5680968/112478616-18fab500-8d6c-11eb-9723-2b97875db11f.jpg)
![Screen Shot 2021-03-25 at 13 00 54](https://user-images.githubusercontent.com/5680968/112478618-19934b80-8d6c-11eb-8c31-0e00375e1906.jpg)
![Screen Shot 2021-03-25 at 13 00 58](https://user-images.githubusercontent.com/5680968/112478619-1a2be200-8d6c-11eb-9ccc-85f47824f54f.jpg)
![Screen Shot 2021-03-25 at 13 01 00](https://user-images.githubusercontent.com/5680968/112478621-1a2be200-8d6c-11eb-8226-2a2d74a85e42.jpg)
![Screen Shot 2021-03-25 at 13 01 06](https://user-images.githubusercontent.com/5680968/112478625-1ac47880-8d6c-11eb-83a2-e3854e489a8f.jpg)
![Screen Shot 2021-03-25 at 13 01 18](https://user-images.githubusercontent.com/5680968/112478627-1ac47880-8d6c-11eb-984d-468e5a74efc9.jpg)
![Screen Shot 2021-03-25 at 13 01 22](https://user-images.githubusercontent.com/5680968/112478630-1b5d0f00-8d6c-11eb-8da7-264a19ae272d.jpg)
![Screen Shot 2021-03-25 at 13 01 25](https://user-images.githubusercontent.com/5680968/112478633-1bf5a580-8d6c-11eb-88a7-e110454f1085.jpg)
![Screen Shot 2021-03-25 at 13 01 38](https://user-images.githubusercontent.com/5680968/112478638-1bf5a580-8d6c-11eb-9507-4344b3232f7f.jpg)
![Screen Shot 2021-03-25 at 13 01 54](https://user-images.githubusercontent.com/5680968/112478640-1c8e3c00-8d6c-11eb-92dd-0904c903d60c.jpg)
![Screen Shot 2021-03-25 at 13 02 03](https://user-images.githubusercontent.com/5680968/112478642-1c8e3c00-8d6c-11eb-8d0f-dbcd2496880c.jpg)
![Screen Shot 2021-03-25 at 13 02 12](https://user-images.githubusercontent.com/5680968/112478643-1d26d280-8d6c-11eb-8b93-549c2e68d263.jpg)
![Screen Shot 2021-03-25 at 13 02 16](https://user-images.githubusercontent.com/5680968/112478645-1dbf6900-8d6c-11eb-8fa2-de3909351667.jpg)
![Screen Shot 2021-03-25 at 13 02 20](https://user-images.githubusercontent.com/5680968/112478646-1dbf6900-8d6c-11eb-87be-9e8c7fe976c4.jpg)
![Screen Shot 2021-03-25 at 13 02 45](https://user-images.githubusercontent.com/5680968/112478652-1e57ff80-8d6c-11eb-92db-53388e8116e8.jpg)
![Screen Shot 2021-03-25 at 13 03 03](https://user-images.githubusercontent.com/5680968/112478655-1e57ff80-8d6c-11eb-8ce3-b4f165ba6f1a.jpg)

**Comment by brianmichalk1** [comment]
Thanks!!  This interface addresses all of my needs.
