### ISSUE TITLE
Privacy mask?

### ISSUE THREAD

**Issue by GSVNoFixedabode** [EliasKotlyar/Xiaomi-Dafang-Hacks#1727]
Feature Request: can we get the ability to create a Privacy mask/zone on the image i.e. define an area of the image that is either blurred, pixellated, or simply blocked out by a black region?

**Comment by GSVNoFixedabode** [comment]
Anyone, anyone? Bueller?

**Comment by c---** [comment]
There is a command on the camera bin/jpegtran that has the switch:
`-wipe WxH+X+Y  Wipe (gray out) a rectangular subarea`

So you would have to look through everything in scripts/ for calls to getimage and pipe it through jpegtran with -wipe set.

This won't work for rtsp streaming though, AFAIK.

**Comment by GSVNoFixedabode** [comment]
Thanks - so jpegtran is part of the base os within the camera image?  At present I'm piping the snapshot image to a R.Pi and running a pixelated overlay via ImageMagik.  It would be nice to be able to do it all within the camera before sending via FTP

**Comment by c---** [comment]
Yes, jpegtran is part of the default install. It's at */system/sdcard/bin/jpegtran*.

I tested it by editing */system/sdcard/scripts/detectionOn.sh* around line 205 I made the change:
`/system/sdcard/bin/getimage | /system/sdcard/bin/jpegtran -wipe 500x500+100+100 > "$snapshot_tempfile"`

And that worked for uploading snapshots to my web server. You can also make similar changes for video that is uploaded because it uses getimage in *detectionOn.sh* as well.

**Comment by GSVNoFixedabode** [comment]
Thanks, sounds like a good solution!

**Comment by GSVNoFixedabode** [comment]
> I tested it by editing _/system/sdcard/scripts/detectionOn.sh_ around line 205 I made the change:
> `/system/sdcard/bin/getimage | /system/sdcard/bin/jpegtran -wipe 500x500+100+100 > "$snapshot_tempfile"`
> 
@c--- Just tried this with epic fails. If I use the syntax as above (...getimage **|** /system...) it looks like the image file is being cat'd to the screen, If I use ...getimage **>** /system...jpegtran -wipe 500x500+100+100 > /media/somefilename.jpg then the image is saved but jpegtran has done nothing at all.  Very confusing!  Any suggestions?

**Comment by c---** [comment]
The pipe character `|` sends the output of one command in to the input of another command. The redirect character `>` sends the output of a command to a file. If you did `getimage  > /system/sdcard/bin/jpegtran` then that would erase your jpegtran program (you'll need to copy it back on to your camera from firmware_mod).

To simplify the logic in my original post:
`getimage | jpegtran > tempfile`
getimage runs and sends its output in to the input of jpegtran which sends its output to a file called tempfile. Without the redirection jpegtran would send its output to the screen.

**Comment by GSVNoFixedabode** [comment]
[FACEPALM] Of course it does that - feeling a little stupid now using redirect instead of pipe!! Thanks.
