### ISSUE TITLE
FORCE to connect to 2.4GHZ on same SSID for(2.4GHZ and 5GHZ)

### ISSUE THREAD

**Issue by meduar** [EliasKotlyar/Xiaomi-Dafang-Hacks#1730]
Hi, 

I have a Dafang camera and everything has been working without issue until a week ago when I changed the router, the camera wasn't connecting to WIFI, everything was the same I only changed the ssid and the password it didn't work then after trying different things I realized the **SSID IS THE SAME for **2.4 ghz and 5ghz.****, the camera doesn't work on 5hgz I think for any reason always try to connect to the 5ghz, sometimes it connects and works and I is when randomly connects to 2.4ghz.

I am using the latest version.

How could I force the camera to only connect to 2.4 ghz frequency.

I already tried to change freq_lis in the wpa_supplicant like this:

network={
    ssid="SSID"
    psk="fakepassphrase"
    ....... other configs.....
    freq_list=2412 2417 2422 2427 2432 2437 2442 2447 2452 2457 2462
}

It didn't work either

Someone suggested in a forum to use, bssid=34:81:C4:XX:XX:XY, yeah that solution is not goo as well.

Any other suggestion, could it be done through different method like modifying the scripts to scan and only get the 2.4 frequencies?

**Comment by c---** [comment]
Take a look at the `freq_list` option in config/wpa_supplicant.conf
```
freq_list: Array of allowed frequencies
Space-separated list of frequencies in MHz to allow for selecting the BSS. If
set, scan results that do not match any of the specified frequencies are not
considered when selecting a BSS.
```
So you end up with something like
```
network={
   ...normal settings...
   freq_list=2412 2437 2462
}
```
You will need to figure out which frequencies are valid for your country. Those three I listed are channel 1, 6, and 11.

I should mention that it's quite normal to configure different SSID's for 2.4GHz and 5GHz. That way you force the frequency by simply selecting the correct SSID.
