### ISSUE TITLE
ffprobe shows 25fps while camera is set to 5fps

### ISSUE THREAD

**Issue by Sloth-on-meth** [EliasKotlyar/Xiaomi-Dafang-Hacks#1731]
This is an issue tracking system only.
If you have general questions or are a newbie, please ask for help in our [chat channel](https://gitter.im/Xiaomi-Dafang-Hacks).

To make sure your issue can be resolved as quickly as possible please state your

* exact camera hardware: dafang
* the Xiaomi-Dafang-Hacks 

### Description

changing the fps in the settings works, as it's reflected in the file, but FFPROBE still shows 25fps

### What did you do to debug the issue
checked cat /system/sdcard/config/rtspserver.conf

**Comment by jonathanchin** [comment]
I'm seeing this too. Maybe a regression? IIRC a couple months ago I was able to update it via the UI or via the config and it worked as expected.
