### ISSUE TITLE
Options for Downgrade to NON-"NEW-GUI"?

### ISSUE THREAD

**Issue by olvier** [EliasKotlyar/Xiaomi-Dafang-Hacks#1733]
Hey, because of telegram-picture-notification isn't working and isn't fixed for weeks, with the new software, which options do I have to downgrade?

Is there any from web-gui?
Is there any from ssh'ing into it?
Do I have to change files from SD?

Greeeeetz :)

**Comment by timstanley1985** [comment]
Have you tried to debug your problem?  Telegram images works fine for me.
If you SSH into the camera and manually invoke detectionOn.sh you might be
able to work out why you aren't receiving pictures

**Comment by olvier** [comment]
Tried all I found from here, some weeks ago. Didn't help.

Telegram itself is working, I'm able to get motion alert with text and video, but not with images. But I am not the only one, as I had read those weeks ago.
Images manually invoked with `/shot,` works too.

Manually invoking the detectionOn.sh outputs the following
`chmod: /tmp/snapshot-XRK9FsF: No such file or directory
cp: can't stat '/tmp/snapshot-XRK9FsF': No such file or directory`

**Comment by timstanley1985** [comment]
Next thing I would suggest is to add the command set -x to the top of the
script and execute detectionon.sh again.  This will print out each command
from the script one at a time and help you track down what is going wrong.

Post the output here if like.

**Comment by olvier** [comment]
[root@Flur:~]# cd /system/sdcard/scripts/
[root@Flur:scripts]# ./detectionOn.sh
+ . /system/sdcard/config/motion.conf
+ debug_msg_enable=false
+ region_of_interest=0,0,1280,720
+ motion_sensitivity=4
+ motion_indicator_color=2
+ motion_timeout=-1
+ motion_detection=off
+ motion_tracking=off
+ motion_trigger_led=true
+ publish_mqtt_message=false
+ publish_mqtt_snapshot=false
+ publish_mqtt_video=false
+ send_email=false
+ send_telegram=true
+ telegram_alert_type=image
+ send_matrix=false
+ night_mode_event_delay=30
+ group_date_pattern='+%Y-%m-%d/%H'
+ file_date_pattern='+%Y-%m-%d_%H-%M-%S'
+ video_duration=10
+ save_files_attr=0644
+ save_dirs_attr=0755
+ video_use_rtsp=true
+ video_rtsp_w=1280
+ video_rtsp_h=720
+ video_rtsp_f=15
+ save_snapshot=true
+ save_snapshot_dir=/system/sdcard/DCIM/Motion/Stills
+ max_snapshot_days=20
+ save_video=false
+ save_video_dir=/system/sdcard/DCIM/Motion/Videos
+ max_video_days=10
+ ftp_snapshot=false
+ ftp_video=false
+ ftp_host=ftp.myserver.net
+ ftp_port=21
+ ftp_username=user1
+ ftp_password=password2
+ ftp_stills_dir=motion/stills
+ ftp_videos_dir=motion/videos
+ dropbox_snapshot=false
+ dropbox_video=false
+ dropbox_token=token
+ dropbox_stills_dir=/motion/stills
+ dropbox_videos_dir=/motion/videos
+ smb_snapshot=false
+ smb_video=false
+ smb_share=//DEVICE/SHARE
+ smb_username=admin
+ smb_password=admin
+ smb_stills_path=dafang_camera/stills
+ smb_videos_path=dafang_camera/videos
+ . /system/sdcard/scripts/common_functions.sh
+ MAX_X=2600
+ MAX_Y=700
+ MIN_X=0
+ MIN_Y=0
+ STEP=100
+ . /system/sdcard/config/rtspserver.conf
+ PORT=8554
+ RTSPH264OPTS='-W1280 -H720'
+ RTSPMJPEGOPTS='-W1280 -H720'
+ BITRATE=5000
+ FRAMERATE_DEN=1
+ FRAMERATE_NUM=25
+ VIDEOFORMAT=2
+ AUDIOFORMAT=PCMU
+ AUDIOOUTBR=8000:8000
+ RTSPH264OPTS='-W1280 -H720'
+ AUDIOINBR=16000
+ HWVOLUME=70
+ SWVOLUME=-1
+ FILTER=4
+ HIGHPASSFILTER=ON
+ AECFILTER=ON
+ FLIP=OFF
+ USERNAME=
+ USERPASSWORD=
+ '[' -f /tmp/last-night -a -n 30 -a 30 -gt 0 ]
+ date '+%s'
+ now_ts=1621204902
+ /system/sdcard/bin/busybox stat -c '%Y' /tmp/last-night
+ night_ts=1621160227
+ dt=44675
+ '[' 44675 -lt 30 ]
+ '[' true '=' true ]
+ debug_msg 'Trigger LED'
+ '[' false '=' true ]
+ yellow_led on
+ setgpio 38 0
+ GPIOPIN=38
+ echo 0
+ mktemp /tmp/snapshot-XXXXXXX
+ snapshot_tempfile=/tmp/snapshot-XVdB9el
+ mktemp /tmp/video-XXXXXXX
+ video_tempfile=/tmp/video-X07PnV8
+ group_pattern='+%Y-%m-%d/%H'
+ date '+%Y-%m-%d/%H'
+ groupname=2021-05-17/00
+ filename_pattern='+%Y-%m-%d_%H-%M-%S'
+ date '+%Y-%m-%d_%H-%M-%S'
+ filename=2021-05-17_00-41-43
+ /system/sdcard/bin/getimage
+ debug_msg 'Got snapshot_tempfile=/tmp/snapshot-XVdB9el'
+ '[' false '=' true ]
+ '[' false '=' true -o false '=' true -o image '=' video+image -o image '=' video -o false '=' true ]
+ '[' false '=' true ]
+ '[' false '=' true ]
+ '[' false '=' true ]
+ '[' false '=' true ]
+ '[' false '=' true ]
+ send_snapshot
+ '[' false '=' true -o false '=' true ]
+ '[' true '='+ '[' false '=' true ]
+ '[' true true ]
+ '[' false '=' true ]
+  '=' true ]
'[' false '=' true ]
+ '[' false '=' true ]
+ '[' true '=' true ]
+ '[' false '=' true ]
+ include /system/sdcard/config/telegram.conf
+ '[[' -f /system/sdcard/config/telegram.conf ]]
+ '[' -x '/system/sdcard/config/userscripts/motiondetection/*' ]
+ debug_msg 'Waiting for background jobs to end:'
+ '[' false '=' true ]
+ include /system/sdcard/config/telegram.conf
+ '[[' -f /system/sdcard/config/telegram.conf ]]
+ source /system/sdcard/config/telegram.conf
+ apiToken=xxxxxxxxxx:xxxxxxxxx_xxxxxxxxxxxxxxxxxxxx
+ userChatId=-100000012345
+ '['+ debug_msg 'Save snapshot to /system/sdcard/DCIM/Motion/Stills/2021-05-17/00/2021-05-17_00-41-43.jpg'
+ '[' false '=' true ]
+ '[' '!' -d /system/sdcard/DCIM/Motion/Stills/2021-05-17/00 ]
+ mkdir -p /system/sdcard/DCIM/Motion/Stills/2021-05-17/00
+ source /system/sdcard/config/telegram.conf
+ apiToken=xxxxxxxxx:xxxxxx_xxxxxxxxxxxxxxxx
+ userChatId=-100000005678
+ '[' image '=' text ]
+ '[' image '=' image -o image '=' video+image ]+ jobs -p
 image '=' video -o image '=' video+image ]

+ debug_msg 'Send telegram image'
+ '[' false '=' true ]
+ + wait 22994
+ debug_msg ' Job 22994 ended'
+ '[' false '=' true ]
+ wait 22992
+ debug_msg ' Job 22992 ended'
+ '[' false '=' true ]
+ debug_msg 'Cleanup tempfiles'
+ '[' false '=' true ]
+ rm /tmp/snapshot-XVdB9el
/system/sdcard/bin/telegram p /tmp/snapshot-XVdB9el
+ chmod 0755 /system/sdcard/DCIM/Motion/Stills/2021-05-17/00
+ rm /tmp/video-X07PnV8
+ + lswc -l+ debug_msg DONE
+ '[' false '=' true ]
[root@Flur:scripts]#
 /system/sdcard/DCIM/Motion/Stills
+ '[' 20 -ge 20 ]
+ awk 'NR==2{print $9}'
+ ls -ltr /system/sdcard/DCIM/Motion/Stills
+ rm -rf /system/sdcard/DCIM/Motion/Stills/2021-04-03
+ chmod 0644 /tmp/snapshot-XVdB9el
chmod: /tmp/snapshot-XVdB9el: No such file or directory
+ cp /tmp/snapshot-XVdB9el /system/sdcard/DCIM/Motion/Stills/2021-05-17/00/2021-05-17_00-41-43.jpg
cp: can't stat '/tmp/snapshot-XVdB9el': No such file or directory
[root@Flur:scripts]#

**Comment by timstanley1985** [comment]
If you type the following command does it successfully send a test message?

telegram m test

**Comment by olvier** [comment]
Of course

**Comment by olvier** [comment]
"... which options do I have to downgrade?

Is there any from web-gui?
Is there any from ssh'ing into it?
Do I have to change files from SD?"
