### ISSUE TITLE
T20L support

### ISSUE THREAD

**Issue by tekgamerpt** [EliasKotlyar/Xiaomi-Dafang-Hacks#1736]
Hello
Maybe this is not the best way to post it, but, is this firmware working on the Xiaofang T20L? Can't find answer for this question anywhere...

Cheers

**Comment by R31N4LD0** [comment]
Did You read this [section](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/hacks/install_cwf_t20l.md) ?
