### ISSUE TITLE
OSD-Display disable doesn't work

### ISSUE THREAD

**Issue by QcVictor** [EliasKotlyar/Xiaomi-Dafang-Hacks#174]
Hi Guys
Tks for your great jobs, with latest revision 20/03/208 I'm unable to disable the OSD-Display, when I untick the box set, got "OSD removed Invalid Argument ? Invalid Argument ?"

**Comment by pax0707** [comment]
For me, it does that but it also removes the OSD so it ... works?

**Comment by QcVictor** [comment]
OK finally it's working, after a couple try osd is gone....
