### ISSUE TITLE
Unable to connect to admin interface (HTTP) with PTZ camera

### ISSUE THREAD

**Issue by htjunkie007** [EliasKotlyar/Xiaomi-Dafang-Hacks#1742]
Camera is Wyze PTZ 1080p with firmware: 4.10.0.222

We had a brief power outage and since then I'm not able to connect to the camera admin interface through Chrome or any browser!  Keep getting connection refused. 

I ended up factory resetting it, used Wyze app to connect and get it on WiFi.  All was good then I tried the hacked firmware again, no go!  Even with Wyze app, I can see the camera through app only, still it wouldn't let me go through http access.

I'm at a lost, anything else I can try?  Much appreciate your response.

**Comment by MapGuy11** [comment]
Me too, with my Wyze V2 wanted to try the firmware again and it just refuses to open the Web UI on every browser known.

**Comment by c---** [comment]
How are you setting up the wifi on the camera during the initial install?

Have you checked on your router to make sure the camera is really connected and has an IP address? Can you successfully ping the camera? Can you ssh in to it?
