### ISSUE TITLE
NTP host customizable

### ISSUE THREAD

**Issue by omega4h** [EliasKotlyar/Xiaomi-Dafang-Hacks#175]
MY cam isn't allowed to connect to internet. So date/time is always wrong.
It would be nice to be able to customize my own NTP-Server (192.168.0.1).

**Comment by Karkas66** [comment]
I redirected them via DNS. They try to reach time.google.com and I gave this host my Internal NTP Address

**Comment by herrxyz** [comment]
edit ruh.sh and change 
`/system/sdcard/bin/busybox ntpd -q -n -p time.google.com`
to
`/system/sdcard/bin/busybox ntpd -q -n -p fritz.box` (as example with fritzbox, IP should also work)

**Comment by omega4h** [comment]
Both suggestions didn't work for me.
1st one: I logged in with root and tried to change /etc/hosts. The file is read only and I wasn't allowed to change to read write.
2nd. one: I changed run.sh (/system/sdcard/bin/busybox ntpd -q -n -p 192.168.0.1) but Time didn't change.

**Comment by herrxyz** [comment]
did you reboot afterwards?
you can also just run this line using ssh to see if it works (or get an error message)
`/system/sdcard/bin/busybox ntpd -q -n -p 192.168.0.1`

**Comment by jmtatsch** [comment]
customizable via ntp_srv.conf now
