### ISSUE TITLE
ONVIF Server 

### ISSUE THREAD

**Issue by chross** [EliasKotlyar/Xiaomi-Dafang-Hacks#1752]
Xiaomi Dafang
Bootloader Version: U-Boot 2013.07 (Jul 28 2017 - 17:10:01)

Hi!
I'm trying to activate the ONVIF server, however it gets always switched off.
What could be the reason?

![grafik](https://user-images.githubusercontent.com/7794409/124037078-44daa600-d9ff-11eb-85af-0a0e990bcf49.png)

**Comment by timstanley1985** [comment]
Have you checked logs??

**Comment by chross** [comment]
It seems as if it has been loaded
```
332 root 0:00 /system/sdcard/bin/mDNSResponder -b -P /run/mdns-responder.pid -n DafangCamera -t _rtsp._tcp -p 8554
350 root 0:00 /system/sdcard/bin/onvif_srvd --pid_file /var/run/onvif_srvd.pid --ifs wlan0
363 root 0:15 /system/sdcard/bin/v4l2rtspserver-master -fH264 -W1280 -H720 -E PCM:16000:44100 -r 3 -F 17 -U admin:REDACTED -P 8554
366 root 0:00 /system/sdcard/bin/dropbearmulti dropbear -R -p 22
369 root 0:00 /system/sdcard/bin/lighttpd.bin -f /system/sdcard/config/lighttpd.conf
```

**Comment by jhelbig** [comment]
I just noticed that it's hardcoded to use the wlan0 interface on the control script.

https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/firmware_mod/controlscripts/onvif-srvd#L8

Even after changing that to eth0 it's still pulling from wlan0, it's still attempting to use wlan0.  I'm pretty sure that the binary was compiled with the same interface hard coded in there.  I would compile a new one to test further, but I'm not sure where the source is in the repo.

I might be able to create a symlink from eth0 to wlan0 though, so I'll give it a shot and report back if that helped get further.

**Comment by timstanley1985** [comment]
Source code should be here: https://github.com/Dafang-Hacks/Main

**Comment by jhelbig** [comment]
@timstanley1985 Thanks!

Looks like this _may_ be the culprit

https://github.com/Dafang-Hacks/Main/blob/950bff3a9361e0e33a2f37cb947e4b400839ef7a/onvif/src/system_utils.cpp#L157

I'll see if I can get a new copy compiled and test it out

**Comment by jhelbig** [comment]
So I was able to compile a version with the fix from above, (changing wlan0 to eth0 since I am using an POE adapter).

```diff
 string system_get_mac()
 {
-       return system_exec("cat /sys/class/net/wlan0/address");
+       if (system_file_exists("/sys/class/net/wlan0/address"))^M
+               return system_exec("cat /sys/class/net/wlan0/address");^M
+       else if(system_file_exists("/sys/class/net/eth0/address"))^M
+               return system_exec("cat /sys/class/net/eth0/address");^M
+       return "";^M
 }
```

This doesn't do much to make the process seem "on" from the dashboard.  Also the error I was seeing was not really related to this open issue, but I hope I can shed some light on what may be causing the service to show as "off".

If you are interested in trying out the debug binary along with the changes above you can get the full source and compile your own or download and use the binary from a [public gist](https://gist.github.com/jhelbig/b7414c326b078aff296d48b980b53ed5).

---

Now for the really interesting part.  Before I wasn't able to get onvif to even remain operational or even connect to it.  Upon pulling up the help details about it, I can see that there are more options on configuration when using the binary.

```
[root@FOYERCAM:controlscripts]# /system/sdcard/bin/onvif_srvd --help
 ===============  Help  ===============
 Daemon name:  onvif_srvd
 Daemon  ver:  1.1.0
 Build  mode:  debug
 Build  date:  Jul  5 2021
 Build  time:  04:25:45

Options:                      description:

       --no_chdir             Don't change the directory to '/'
       --no_fork              Don't do fork
       --no_close             Don't close standart IO files
       --pid_file     [value] Set pid file name
       --log_file     [value] Set log file name

       --port         [value] Set socket port for Services   (default = 8080)
       --user         [value] Set user name for Services     (default = root)
       --password     [value] Set user password for Services (default = password)
       --model        [value] Set model device for Services  (default = (Auto detected))
       --ifs          [value] Set Net interfaces for work    (default = wlan0)
       --hardware_id  [value] Set Hardware ID of device      (default = (Auto detected))
       --serial_num   [value] Set Serial number of device    (default = (Auto detected))
       --firmware_ver [value] Set firmware version of device (default = (Auto detected))
       --manufacturer [value] Set manufacturer for Services  (default = (Auto detected))

  -v,  --version              Display daemon version
  -h,  --help                 Display this help

```

The controlscript only provides the [pid and interface](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/firmware_mod/controlscripts/onvif-srvd#L8) by default.

By manually running with added arguments I was actually able to get my Amcrest NVR to see and "connect" to the onvif server.
`/system/sdcard/bin/onvif_srvd --pid_file /var/run/onvif_srvd.pid --ifs eth0 --port 832 --log_file /system/sdcard/log/onvif.log`

![image](https://user-images.githubusercontent.com/11377461/124423699-512a7000-dd2b-11eb-8014-8b7c53d5f50b.png)

It didn't work unfortunately though, but it did spit out some new errors in the logs since I compiled the binary in debug mode.

```
Error -1 fault: SOAP-ENV:Client[no subcode]
"End of file or no input: Operation interrupted or timed out (3 s recv delay) (3 s send delay)"
Detail: [no detail]
Device: GetSystemDateAndTime
Error -1 fault: SOAP-ENV:Client[no subcode]
"End of file or no input: Operation interrupted or timed out (3 s recv delay) (3 s send delay)"
Detail: [no detail]
Device: GetSystemDateAndTime
Error -1 fault: SOAP-ENV:Client[no subcode]
"End of file or no input: Operation interrupted or timed out (3 s recv delay) (3 s send delay)"
Detail: [no detail]
Device: GetServices
Device: GetSystemDateAndTime
Device: GetServices
Device: GetSystemDateAndTime
Device: GetServices
Device: GetSystemDateAndTime
Device: GetSystemDateAndTime
Device: GetSystemDateAndTime
Device: GetSystemDateAndTime
Device: GetCapabilities
Device: GetSystemDateAndTime
Device: GetCapabilities
Media: GetProfiles
sh: rtsp_mjpeg_server: not found
sh: rtsp_mjpeg_server: not found
Device: GetCapabilities
Media: GetProfiles
sh: rtsp_mjpeg_server: not found
sh: rtsp_mjpeg_server: not found
Media: GetCompatibleVideoAnalyticsConfigurations
Media: GetProfiles
sh: rtsp_mjpeg_server: not found
sh: rtsp_mjpeg_server: not found
Media: GetCompatibleVideoAnalyticsConfigurations
Media: GetProfiles
sh: rtsp_mjpeg_server: not found
sh: rtsp_mjpeg_server: not found
Media: GetCompatibleVideoAnalyticsConfigurations
Media: GetProfiles
sh: rtsp_mjpeg_server: not found
sh: rtsp_mjpeg_server: not found
Device: GetSystemDateAndTime
Media: GetProfiles
sh: rtsp_mjpeg_server: not found
sh: rtsp_mjpeg_server: not found
Error -1 fault: SOAP-ENV:Client[no subcode]
"End of file or no input: Operation interrupted or timed out (3 s recv delay) (3 s send delay)"
Detail: [no detail]
Device: GetSystemDateAndTime
Device: GetSystemDateAndTime
Device: GetSystemDateAndTime
Device: GetServices
Device: GetServices
Device: GetServices
Device: GetSystemDateAndTime
Device: GetSystemDateAndTime
Device: GetSystemDateAndTime
Device: GetSystemDateAndTime
Device: GetSystemDateAndTime
Device: GetSystemDateAndTime
Device: GetCapabilities
Device: GetCapabilities
Device: GetCapabilities
Media: GetProfiles
sh: rtsp_mjpeg_server: not found
sh: rtsp_mjpeg_server: not found
Device: SetSystemDateAndTime
Device: GetSystemDateAndTime
Media: GetCompatibleVideoAnalyticsConfigurations
Device: GetSystemDateAndTime
Device: SetSystemDateAndTime
Media: GetProfiles
sh: rtsp_mjpeg_server: not found
sh: rtsp_mjpeg_server: not found
Error -1 fault: SOAP-ENV:Client[no subcode]
"End of file or no input: Operation interrupted or timed out (3 s recv delay) (3 s send delay)"
Detail: [no detail]
Device: GetScopes
Device: GetSystemDateAndTime
Error -1 fault: SOAP-ENV:Client[no subcode]
"End of file or no input: Operation interrupted or timed out (3 s recv delay) (3 s send delay)"
Detail: [no detail]
Device: GetDeviceInformation
Media: GetSnapshotUri
Media: Snapshot Uri: http://192.168.30.34:80/cgi-bin/currentpic.cgi
Error -1 fault: SOAP-ENV:Client[no subcode]
"End of file or no input: Operation interrupted or timed out (3 s recv delay) (3 s send delay)"
Detail: [no detail]
Error -1 fault: SOAP-ENV:Client[no subcode]
"End of file or no input: Operation interrupted or timed out (3 s recv delay) (3 s send delay)"
Detail: [no detail]
Error -1 fault: SOAP-ENV:Client[no subcode]
"End of file or no input: Operation interrupted or timed out (3 s recv delay) (3 s send delay)"
Detail: [no detail]
Error -1 fault: SOAP-ENV:Client[no subcode]
"End of file or no input: Operation interrupted or timed out (3 s recv delay) (3 s send delay)"
Detail: [no detail]
Error -1 fault: SOAP-ENV:Client[no subcode]
"End of file or no input: Operation interrupted or timed out (3 s recv delay) (3 s send delay)"
Detail: [no detail]
Device: GetScopes
Error 15 fault: SOAP-ENV:Client[no subcode]
"HTTP GET method not implemented"
Detail: [no detail]
Error -1 fault: SOAP-ENV:Client[no subcode]
"End of file or no input: Operation interrupted or timed out (3 s recv delay) (3 s send delay)"
Detail: [no detail]
Error -1 fault: SOAP-ENV:Client[no subcode]
"End of file or no input: Operation interrupted or timed out (3 s recv delay) (3 s send delay)"
Detail: [no detail]
Error -1 fault: SOAP-ENV:Client[no subcode]
"End of file or no input: Operation interrupted or timed out (3 s recv delay) (3 s send delay)"
Detail: [no detail]
Error 15 fault: SOAP-ENV:Client[no subcode]
"HTTP GET method not implemented"
Detail: [no detail]
Error -1 fault: SOAP-ENV:Client[no subcode]
"End of file or no input: Operation interrupted or timed out (3 s recv delay) (3 s send delay)"
Detail: [no detail]
Media: GetStreamUri   for profile:main-profile
Media: Stream Uri: rtsp://192.168.30.34:8554/unicast
Error -1 fault: SOAP-ENV:Client[no subcode]
"End of file or no input: Operation interrupted or timed out (3 s recv delay) (3 s send delay)"
Detail: [no detail]
Error -1 fault: SOAP-ENV:Client[no subcode]
"End of file or no input: Operation interrupted or timed out (3 s recv delay) (3 s send delay)"
Detail: [no detail]
Event: Subscribe
Error -1 fault: SOAP-ENV:Client[no subcode]
"End of file or no input: Operation interrupted or timed out (3 s recv delay) (3 s send delay)"
Detail: [no detail]
Media: SetSynchronizationPoint
Error -1 fault: SOAP-ENV:Client[no subcode]
"End of file or no input: Operation interrupted or timed out (3 s recv delay) (3 s send delay)"
Detail: [no detail]
Error -1 fault: SOAP-ENV:Client[no subcode]
"End of file or no input: Operation interrupted or timed out (3 s recv delay) (3 s send delay)"
Detail: [no detail]
Error -1 fault: SOAP-ENV:Client[no subcode]
"End of file or no input: Operation interrupted or timed out (3 s recv delay) (3 s send delay)"
Detail: [no detail]
Error -1 fault: SOAP-ENV:Client[no subcode]
"End of file or no input: Operation interrupted or timed out (3 s recv delay) (3 s send delay)"
Detail: [no detail]
Error -1 fault: SOAP-ENV:Client[no subcode]
"End of file or no input: Operation interrupted or timed out (3 s recv delay) (3 s send delay)"
Detail: [no detail]
Error -1 fault: SOAP-ENV:Client[no subcode]
"End of file or no input: Operation interrupted or timed out (3 s recv delay) (3 s send delay)"
Detail: [no detail]
Error -1 fault: SOAP-ENV:Client[no subcode]
"End of file or no input: Operation interrupted or timed out (3 s recv delay) (3 s send delay)"
Detail: [no detail]
Error -1 fault: SOAP-ENV:Client[no subcode]
"End of file or no input: Operation interrupted or timed out (3 s recv delay) (3 s send delay)"
Detail: [no detail]
Error -1 fault: SOAP-ENV:Client[no subcode]
"End of file or no input: Operation interrupted or timed out (3 s recv delay) (3 s send delay)"
Detail: [no detail]
Error -1 fault: SOAP-ENV:Client[no subcode]
"End of file or no input: Operation interrupted or timed out (3 s recv delay) (3 s send delay)"
Detail: [no detail]
Error -1 fault: SOAP-ENV:Client[no subcode]
"End of file or no input: Operation interrupted or timed out (3 s recv delay) (3 s send delay)"
Detail: [no detail]
Error -1 fault: SOAP-ENV:Client[no subcode]
"End of file or no input: Operation interrupted or timed out (3 s recv delay) (3 s send delay)"
Detail: [no detail]
Error -1 fault: SOAP-ENV:Client[no subcode]
"End of file or no input: Operation interrupted or timed out (3 s recv delay) (3 s send delay)"
Detail: [no detail]
Error -1 fault: SOAP-ENV:Client[no subcode]
"End of file or no input: Operation interrupted or timed out (3 s recv delay) (3 s send delay)"
Detail: [no detail]
Error -1 fault: SOAP-ENV:Client[no subcode]
"End of file or no input: Operation interrupted or timed out (3 s recv delay) (3 s send delay)"
Detail: [no detail]
Error -1 fault: SOAP-ENV:Client[no subcode]
"End of file or no input: Operation interrupted or timed out (3 s recv delay) (3 s send delay)"
Detail: [no detail]
Error -1 fault: SOAP-ENV:Client[no subcode]
"End of file or no input: Operation interrupted or timed out (3 s recv delay) (3 s send delay)"
Detail: [no detail]
Media: GetOSDOptions
Media: GetOSDs
Error -1 fault: SOAP-ENV:Client[no subcode]
"End of file or no input: Operation interrupted or timed out (3 s recv delay) (3 s send delay)"
Detail: [no detail]
Error -1 fault: SOAP-ENV:Client[no subcode]
"End of file or no input: Operation interrupted or timed out (3 s recv delay) (3 s send delay)"
Detail: [no detail]
Media: GetOSDs
Error -1 fault: SOAP-ENV:Client[no subcode]
"End of file or no input: Operation interrupted or timed out (3 s recv delay) (3 s send delay)"
Detail: [no detail]
Media: GetCompatibleVideoAnalyticsConfigurations
Error 15 fault: SOAP-ENV:Client[no subcode]
"HTTP GET method not implemented"
Detail: [no detail]
Error -1 fault: SOAP-ENV:Client[no subcode]
"End of file or no input: Operation interrupted or timed out (3 s recv delay) (3 s send delay)"
Detail: [no detail]
Error -1 fault: SOAP-ENV:Client[no subcode]
"End of file or no input: Operation interrupted or timed out (3 s recv delay) (3 s send delay)"
Detail: [no detail]
Error -1 fault: SOAP-ENV:Client[no subcode]
"End of file or no input: Operation interrupted or timed out (3 s recv delay) (3 s send delay)"
Detail: [no detail]
Imaging: GetImagingSettings
Imaging: GetOptions
Error -1 fault: SOAP-ENV:Client[no subcode]
"End of file or no input: Operation interrupted or timed out (3 s recv delay) (3 s send delay)"
Detail: [no detail]
Media: GetOSDs
Error -1 fault: SOAP-ENV:Client[no subcode]
"End of file or no input: Operation interrupted or timed out (3 s recv delay) (3 s send delay)"
Detail: [no detail]
Media: GetOSDs
Error -1 fault: SOAP-ENV:Client[no subcode]
"End of file or no input: Operation interrupted or timed out (3 s recv delay) (3 s send delay)"
Detail: [no detail]
Error -1 fault: SOAP-ENV:Client[no subcode]
"End of file or no input: Operation interrupted or timed out (3 s recv delay) (3 s send delay)"
Detail: [no detail]
Device: GetSystemDateAndTime
Device: SetSystemDateAndTime
Device: GetSystemDateAndTime
Error -1 fault: SOAP-ENV:Client[no subcode]
"End of file or no input: Operation interrupted or timed out (3 s recv delay) (3 s send delay)"
Detail: [no detail]
Media: SetSynchronizationPoint
Error -1 fault: SOAP-ENV:Client[no subcode]
"End of file or no input: Operation interrupted or timed out (3 s recv delay) (3 s send delay)"
Detail: [no detail]
Error -1 fault: SOAP-ENV:Client[no subcode]
"End of file or no input: Operation interrupted or timed out (3 s recv delay) (3 s send delay)"
Detail: [no detail]
Error -1 fault: SOAP-ENV:Client[no subcode]
"End of file or no input: Operation interrupted or timed out (3 s recv delay) (3 s send delay)"
Detail: [no detail]
Imaging: GetImagingSettings
Error -1 fault: SOAP-ENV:Client[no subcode]
"End of file or no input: Operation interrupted or timed out (3 s recv delay) (3 s send delay)"
Detail: [no detail]
Imaging: GetImagingSettings
Error 15 fault: SOAP-ENV:Client[no subcode]
"HTTP GET method not implemented"
Detail: [no detail]
Error 15 fault: SOAP-ENV:Client[no subcode]
"HTTP GET method not implemented"
Detail: [no detail]
Error 15 fault: SOAP-ENV:Client[no subcode]
"HTTP GET method not implemented"
Detail: [no detail]
```

Hopefully this provides some more details to someone who's a bit more well versed with the onvif service than I am.

**Comment by luizbossoi** [comment]
Hello

I was able to make it work.
Followed your steps and figure out that onvif server watches for a stream on port 554, not 8554 as it is set by default.

I cannot tell you exactly what I did to solve, but all steps:

> Edited staticip.conf and set a static ip
> Edited rtspserver.conf and changed default por PORT=8554 to PORT=554 . Also, take a look if USERNAME and PASSWORD is set, if yes, leave it blank


Now I can use ONVIF protocol on my NVD without issues.

Your progress made me find the path.
Thanks

**Comment by MyCodeRocks** [comment]
I have the same issue, question here is:

1. Do you have to use eth0 can you not leave it to the WLAN interface? Asking because in my case I only use wifi and wouldn’t be able to specify eth0.
2. I see you changed the port to 554 which is the default most RTSP servers use however why would you need to change it could it not be left to the default or is it required to use 554?

**Comment by luizbossoi** [comment]
> I have the same issue, question here is:
> 
> 1. Do you have to use eth0 can you not leave it to the WLAN interface? Asking because in my case I only use wifi and wouldn’t be able to specify eth0.
> 2. I see you changed the port to 554 which is the default most RTSP servers use however why would you need to change it could it not be left to the default or is it required to use 554?


1. Only WLAN, because my camera is the "Mijia Xiaofang 1s" .... so it only has Wifi, doesn't have ETH ports

2. I changed the default port which was "8554" to use the default RTSP 554.. I really don't know why the firmware was configured to 8554. You can see it here at line 14. 
https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/firmware_mod/config/rtspserver.conf.dist#L14

`....

PORT=8554

...`

**Comment by bdruth** [comment]
Note, per @mikazp's notes - I did _not_ need a username/password, presumably because I didn't have it set for the camera configuration? Not sure ... I do have a username/password set for the camera, in general.

**Comment by nnmalex** [comment]
This still doesn't work for me unfortunately.

**Comment by Sungtroll** [comment]
According to milestonesys Onvif uses port 580 for controlling the rtsp server stream. The dafang custom firmware is a fantastic development for the dafang cameras but the onvif server is not very fantstic because  most people are able to get it to work. How hard can it be to integrate the onvif service so it will work as intended withoud novice users having to work hard to find a way to "hack" the dafang custom firmwire to get i to work? Please make this issue high priority to fix.

**Comment by Sungtroll** [comment]
This is the ports open showed på advansed ip scanner
port 80 seems to be responsing to both http with gSoap that is the protocol used by onvif and to httpd for the web server. How advanced ip scanner figure out that port 80 is used by two services is something of a mystery to me. Dafang service closes the onvif service every time i try to start it, when i exit the control panel and return it is always showing it is not running.

![image](https://user-images.githubusercontent.com/37970110/189464142-8625b064-e7fa-4641-b426-cb3a6a87d905.png)

**Comment by kirsch33** [comment]
for anyone interested in this, i figured out the root cause of this issue was that the ONVIF server included within the firmware was responding with an xaddr of 127.0.0.1. then when the client receives this value and attempts to connect it all falls apart. im not an ONVIF expert but to me it seemed fairly straightforward to hard-code the actual server IP into xaddr to solve my problems. obviously not the best method but serves my purpose well

i cloned the repo listed below and modified the highlighed line to omit `getServerIpFromClientIp(htonl(soap->ip))` with `192.168.62.100` which in my case is the static IP of my wyzecam. 

https://github.com/Dafang-Hacks/Main/blob/950bff3a9361e0e33a2f37cb947e4b400839ef7a/onvif/src/services/ServiceContext.h#L122

please note you still will need to modify RTSP server to 554 rather than the default of 8554.

i still need to do more testing to confirm this works 100% but initial testing at least allow camera to connect without issue, versus before it ALWAYS resulted in connection refused

**Comment by domoticz-italia** [comment]
> for anyone interested in this, i figured out the root cause of this issue was that the ONVIF server included within the firmware was responding with an xaddr of 127.0.0.1. then when the client receives this value and attempts to connect it all falls apart. im not an ONVIF expert but to me it seemed fairly straightforward to hard-code the actual server IP into xaddr to solve my problems. obviously not the best method but serves my purpose well
> 
> i cloned the repo listed below and modified the highlighed line to omit `getServerIpFromClientIp(htonl(soap->ip))` with `192.168.62.100` which in my case is the static IP of my wyzecam.
> 
> https://github.com/Dafang-Hacks/Main/blob/950bff3a9361e0e33a2f37cb947e4b400839ef7a/onvif/src/services/ServiceContext.h#L122
> 
> please note you still will need to modify RTSP server to 554 rather than the default of 8554.
> 
> i still need to do more testing to confirm this works 100% but initial testing at least allow camera to connect without issue, versus before it ALWAYS resulted in connection refused

I there.
I wanna try your method to let the server Onvif works but I didn't understand wher i have to modify this line:
> i cloned the repo listed below and modified the highlighed line to omit `getServerIpFromClientIp(htonl(soap->ip))` with `192.168.62.100` which in my case is the static IP of my wyzecam.
>
can You please explain me? thanks so much

**Comment by adrianmihalko** [comment]
Anyone was able to add ONVIF to Scrypted?

<img width="610" alt="Screenshot 2023-06-10 at 21 57 54" src="https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/assets/733361/28f7d09f-8620-4c67-993d-e4adda06678c">

**Comment by allekss90** [comment]
This works for Home Assistant without changing any ports:

Add integration ONVIF with params:
    name: name
    host: your-ip
    port: 8080
    user: root
    password: password

**Comment by fx-k** [comment]
> > for anyone interested in this, i figured out the root cause of this issue was that the ONVIF server included within the firmware was responding with an xaddr of 127.0.0.1. then when the client receives this value and attempts to connect it all falls apart. im not an ONVIF expert but to me it seemed fairly straightforward to hard-code the actual server IP into xaddr to solve my problems. obviously not the best method but serves my purpose well
> > i cloned the repo listed below and modified the highlighed line to omit `getServerIpFromClientIp(htonl(soap->ip))` with `192.168.62.100` which in my case is the static IP of my wyzecam.
> > https://github.com/Dafang-Hacks/Main/blob/950bff3a9361e0e33a2f37cb947e4b400839ef7a/onvif/src/services/ServiceContext.h#L122
> > please note you still will need to modify RTSP server to 554 rather than the default of 8554.
> > i still need to do more testing to confirm this works 100% but initial testing at least allow camera to connect without issue, versus before it ALWAYS resulted in connection refused
> 
> I there. I wanna try your method to let the server Onvif works but I didn't understand wher i have to modify this line:
> 
> > i cloned the repo listed below and modified the highlighed line to omit `getServerIpFromClientIp(htonl(soap->ip))` with `192.168.62.100` which in my case is the static IP of my wyzecam.
> 
> can You please explain me? thanks so much

Same here, ONVIF doesn't seem to work on my Hikvision NVR either. When I use an ONVIF scanning tool, it detects that ONVIF is listening on the 127.0.0.1 port, which might be the source of the problem.

Could you help to tell more details? thanks a lot :-)

Additionally, my Hikvision NVR doesn't seem to support audio streaming (either PCM, MP3...) with this hack firmware. Unfortunately, it only seems to support aac! Could anyone here solve it, would be grateful!

**Comment by presslab-us** [comment]
> Same here, ONVIF doesn't seem to work on my Hikvision NVR either. When I use an ONVIF scanning tool, it detects that ONVIF is listening on the 127.0.0.1 port, which might be the source of the problem.
> 
> Could you help to tell more details? thanks a lot :-)

I just figured this out..  it's a bug in `onvif_srvd`.  It tries to give the local address that matches the subnet of the client.  But if the client is not on one of the local adapter subnets it just replies with the localhost.  I guess instead of doing that it should give the address of whatever IP is associated with the route back to the client...

Anyway the fix for me was to put my NVR on the same subnet as the camera.  I have VLANs so this lightens the load on the router anyway as the switch can do the work.
