### ISSUE TITLE
Handle github rate limit in update script

### ISSUE THREAD

**Issue by marciogranzotto** [EliasKotlyar/Xiaomi-Dafang-Hacks#1755]
As already debugged on #1652, sometimes the update fails due to github rate limit.
The problem is that it saves "null" on the VERSION file:
```json
{"date":"null","branch":"master","commit":"null"}
```

and when running the script, even using an account with token, it fails until you delete the VERSION file:
```bash
[root@LivingRoomCam:sdcard]# ./autoupdate.sh -u RETRACTED:RETRACTED
Need to upgrade from null to b6a93e9
jq: error (at <stdin>:4): Cannot iterate over null (null)
No files to update.
```

The update script/UI should clearly state that was an error with github's rate limit, don't save a new VERSION file with null values, and offer an option to fix the issue, like adding your github account via the web UI.

**Comment by jmtatsch** [comment]
Can you Make a pull request please?

**Comment by chrisdaloa** [comment]
> 
> 
> As already debugged on #1652, sometimes the update fails due to github rate limit.
> The problem is that it saves "null" on the VERSION file:
> 
> ```json
> {"date":"null","branch":"master","commit":"null"}
> ```
> 
> and when running the script, even using an account with token, it fails until you delete the VERSION file:
> 
> ```shell
> [root@LivingRoomCam:sdcard]# ./autoupdate.sh -u RETRACTED:RETRACTED
> Need to upgrade from null to b6a93e9
> jq: error (at <stdin>:4): Cannot iterate over null (null)
> No files to update.
> ```
> 
> The update script/UI should clearly state that was an error with github's rate limit, don't save a new VERSION file with null values, and offer an option to fix the issue, like adding your github account via the web UI.

what's the path of the version file, please?

**Comment by nemonein** [comment]
This could possible work around the issue.
First, ssh to the camera, then delete VERSION file, and force update with autoupdate.sh

$ rm /system/sdcard/VERSION
$ /system/sdcard/autoupdate.sh -f -d /system/sdcard -u github_username -t github_token

OR,
$ /system/sdcard/autoupdate.sh -f -d /system/sdcard -u github_username:github_password
