### ISSUE TITLE
Matrix Message fails on white space

### ISSUE THREAD

**Issue by PalasX** [EliasKotlyar/Xiaomi-Dafang-Hacks#1756]
Expected:
/system/sdcard/bin/matrix m "Motion Detected"
would send the message "Motion Detected" to the configured matrix server.

Actual:
[root@WyzeDafangBlack1:bin]# matrix m "a b"
Sending message: a b
curl: (3) [globbing] unmatched close brace/bracket in column 3
{"errcode":"M_BAD_JSON","error":"The request body could not be decoded into valid JSON. unexpected end of JSON input"}[root@WyzeDafangBlack1:bin]#

The space does not send, and causes errors. Doing the message without any spaces work as expected:

[root@WyzeDafangBlack1:bin]# matrix m "ab"
Sending message: ab
{"event_id":"$xYRmx-ncWZ4aMdMBiLoHl6ilc-ikNH8XVWGOSIfnC7I"}[root@WyzeDafangBlack1:bin]#

so i guess the /system/sdcard/bin/matrix file is not scripted correctly?
Also, there are three options for this script, m p and f, for message, picture, and file, but only message is ever used on detectionOn.sh
Has anyone scripted a way to send a picture on motion detection to a Matrix server?

**Comment by c---** [comment]
Try my patched version of the matrix command and see if that fixes your issue.

**Comment by c---** [comment]
I made another set of changes to better handle embedded double quotes and escape characters like newline/tab/etc. Seems to work well enough. I can't get it perfect without a proper json encoder. I couldn't get `jq` to work.

**Comment by PalasX** [comment]
confirmed that your "matrix" bin works as intended with spaces on my cameras. I didn't need any other special characters.

thanks for the fix! I hope you have time to implement picture eventually :)

**Comment by c---** [comment]
I have added image and video support.

**Comment by PalasX** [comment]
sending images work.
Cannot use the web interface to set Matrix Alert type back to Text, though.

**Comment by c---** [comment]
Weird. I can't recreate that issue. I have it working on 3 cameras. Maybe your `www/cgi-bin/ui_motion.cgi` is not updated?

**Comment by PalasX** [comment]
that was 100% the fix. I missed it while updating the other files somehow. Thanks!
