### ISSUE TITLE
USB to Ethernet - One Cable

### ISSUE THREAD

**Issue by SomebodySysop** [EliasKotlyar/Xiaomi-Dafang-Hacks#1758]
This is an issue tracking system only.
If you have general questions or are a newbie, please ask for help in our [chat channel](https://gitter.im/Xiaomi-Dafang-Hacks).

To make sure your issue can be resolved as quickly as possible please state your

* exact camera hardware:
Xiaomi Xiaofang 1S

* the Xiaomi-Dafang-Hacks commitid (from `git log`) you are experiencing the issue with:
Don't know how to get the version number.  Latest version as of my writing this.

### Description

I enabled USB to Ethernet connection plugging this device https://www.amazon.com/dp/B00MYT481C?psc=1&smid=AKXVBT49GGF3B&ref_=chk_typ_imgToDp into the 2nd USB port and checking "Enable USB Ethernet (Disables Wifi)".  Very nice work.

I was wondering if it is possible to run this with just one cable instead of two (POE)?  The camera will be located outside and running one wire to it would be preferable if possible. 

### What did you do to debug the issue

I have not tried to do this myself.  I ordered a female to female usb coupler  and my plan is to connect power cable from camera to usb-to-ethernet adapter and connect the ethernet cable to a POE hub.  But, I thought I would ask just the same to see if anyone has tried it.

### Evidence

Kind of pieced together the process from these posts:

https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/1176
https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/1378

![20210711_013308](https://user-images.githubusercontent.com/41084665/125188772-e3c68580-e1e9-11eb-9f4c-1919bea75676.jpg)
![20210711_013314](https://user-images.githubusercontent.com/41084665/125188773-e45f1c00-e1e9-11eb-88cc-f5ef4477fe5c.jpg)

### Contribute Back

If your issue was resolved, please consider contributing back to the project by creating a pull request to improve the code or documentation in order to avoid that this issue arises again for other people.

**Comment by rgon** [comment]
Just get a 5v POE PD extractor (POE -> Ethernet & Micro USB), they cost about 4 dollars in AliExpress IIRC. Search for "Micro USB POE" and you'll find a ton. You might want a short (10cm+) MicroUSB extension cable to tidy the cables up. On the dafang, you can just tape the USB-Eth converter to the back.

![dafang_xiaofang_poe](https://user-images.githubusercontent.com/25673263/127502815-02d37dd4-4900-4218-adb0-a8391731d8ae.jpg)
