### ISSUE TITLE
Include 'nsupdate' to facilitate dns challenges for Let's Encrypt certificates?

### ISSUE THREAD

**Issue by EmnaX** [EliasKotlyar/Xiaomi-Dafang-Hacks#1760]
Hello,

I am trying to use the included scripts to obtain a Let's Encrypt certificate for my Xiaomi Dafang camera. I would like to use the dns route, specifically, the `dns_nsupdate` option for the acme.sh client. My current config is as follows:

/system/sdcard/config/letsencrypt.conf:
``` 
LETSENCRYPT_DOMAIN=cam01.example.com
LETSENCRYPT_METHOD=dns
LETSENCRYPT_DNS_PROVIDER=dns_nsupdate

# acme.sh config variables:
export NSUPDATE_SERVER="ns1.example.com"
export NSUPDATE_KEY="/system/sdcard/config/ssl/_acme-challenge.cam01.example.com.private"
export NSUPDATE_ZONE="example.com"
```

When I run the script (/system/sdcard/config/ssl/letsencrypt_setup.sh), I get an error that 'nsupdate' is not found. I did search for the file and it was not found. Not surprising since BusyBox is pretty bare bones. The following is an excerpt of the script output:
```
...
[Sat Jul 10 20:03:35 EDT 2021] adding _acme-challenge.cam01.example.com. 60 in txt "oWWC4DuxsHBcrqMQVKnHKZ5Dj0XwvpWZmpzqD1kjFlg"
./acme.sh/acme.sh: line 35: nsupdate: not found
[Sat Jul 10 20:03:35 EDT 2021] error updating domain
[Sat Jul 10 20:03:35 EDT 2021] Error add txt for domain:_acme-challenge.cam01.example.com
...
```

I was wondering if it would be possible to include the nsupdate tool in future builds to enable the dns_nsupdate option from the acme.sh script? I have taken a look at cross compiling the tool but this is well beyond my ability! The tool is included as part of the [Bind9 project](https://gitlab.isc.org/isc-projects/bind9) and I did find a website discussing [cross compiling for the Ingenic T20](https://znanev.github.io/Cross-compile-tools-for-Ingenic-T20/). The steps shown on how to cross-compile `htop` and a couple other binaries did work but I couldn't figure out how to apply that to create an`nsupdate` binary.

Anyway, if it isn't too much effort, it would be a great addition and enable people running their own DNS servers to update the appropriate records using the nsupdate tool.

btw, thanks for all the hard work on the development of the Xiaomi-Dafang-Hacks firmware 👍

**Comment by c---** [comment]
The "nsupdate" utility would have to be specific for your own setup. I don't think it could be distributed generically. There is different DNS server software, different services, etc all with their own API. You're actually running your own DNS server(s) or using a service? I ask because it's relatively rare to run your own servers.

**Comment by EmnaX** [comment]
> The "nsupdate" utility would have to be specific for your own setup. I don't think it could be distributed generically. There is different DNS server software, different services, etc all with their own API.
> 
> You're actually running your own DNS server(s) or using a service? I ask because it's relatively rare to run your own servers.

Hi @c--- !
The nsupdate tool is a generic utility used to update zone records. It can work with any RFC 2136 compliant name servers. In my case, I am using Bind9 but there could be others. The [Debian Man Pages](https://manpages.debian.org/buster/dnsutils/nsupdate.1.en.html) have some more info about the tool. The following is an example that I could use to update a random resource record using nsupdate:

``` bash
nsupdate -v -L 3 -k mykey.private
> server ns1.example.ca
> zone example.ca
> update add _acme-challenge.host.example.ca 60 IN TXT "add stuff here"
> send
```

So none of that info would need to be hard coded during compile time. The values would need to be added to the lets_encrypt script and the key would need to be copied over to the camera but that is all easy stuff.

There is a description from acme.sh on using nsupdate with the script:
https://github.com/acmesh-official/acme.sh/wiki/dnsapi#7-use-nsupdate-to-automatically-issue-cert

It is super handy! I use it on some of my Ubuntu servers and it makes life super easy.

**Comment by c---** [comment]
Ah, I see. Personally I generate my keys/certificates on another machine then deploy to the cameras. You have to consider that embedded type devices like these cameras have poor random number generation and can generate low quality keys.

That's just my thought anyway.
