### ISSUE TITLE
Using MQTT to trigger mqtt-autodiscovery not working

### ISSUE THREAD

**Issue by derekoharrow** [EliasKotlyar/Xiaomi-Dafang-Hacks#1761]
For some reason, my Wyzecam v2 sometimes seems to lose connection to Home Assistant - not entirely sure why.

I first resolved this by rebooting the camera, which kicked things back into life. I then found that I could get it working again by executing the script **/system/sdcard/scripts/mqtt-autodiscovery.sh**, which was great. What I want is a way to automate this when Home Assistant notices that the camera is unavailable.

Looking through mqtt-control.sh it would appear that this should be possible by publishing an MQTT message to **LOCATION/TOPIC/set announce**. 

I've tried this, but nothing happens. I get the following output from MQTT:

```
cabin/cam1/set announce
cabin/cam1/announce OK (this means: action.cgi invoke with parameter announce, nothing more, nothing less)
cabin/cam1 {"uptime":" 13:32:31 up 3 days,  1:35,  0 users,  load average: 2.42, 2.51, 2.50",  "ssid":"5cce", "bitrate":"72.2 Mb/s", "signal_level":"100%", "link_quality":"88%", "noise_level":"0%" }
```

My mqtt.conf is setup like this:

```
LOCATION="cabin"
DEVICE_NAME="cam1"
```

If I publish a message like "cabin/cam1/set help" then that works and I get the help text displayed, but trying to use the "set announce" doesn't. It appears that while the mqtt-control script looks correct it isn't running the mqtt-autodiscovery.sh script when asked to.

* exact camera hardware: **Wyzecam V2**
* the Xiaomi-Dafang-Hacks commitid (from `git log`) you are experiencing the issue with: **b6a93e9** 

Any ideas?

**Comment by raidenii** [comment]
Looks like changing
https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/b6a93e9cf5130251f596e66aabfe0d34c43a0828/firmware_mod/scripts/mqtt-control.sh#L30
to
```
"${TOPIC}/set announce")
```
fixed the issue. (Verified by sending a `set announce` via mosquitto_pub).

If that works for you, I'll submit a PR.
