### ISSUE TITLE
Restart RTSP Server

### ISSUE THREAD

**Issue by SomebodySysop** [EliasKotlyar/Xiaomi-Dafang-Hacks#1762]
This is an issue tracking system only.
If you have general questions or are a newbie, please ask for help in our [chat channel](https://gitter.im/Xiaomi-Dafang-Hacks).

To make sure your issue can be resolved as quickly as possible please state your

* exact camera hardware:
Xiaomi Xiaofang 1S

* the Xiaomi-Dafang-Hacks commitid (from `git log`) you are experiencing the issue with:
Most recent

### Description

I would like an easy way to automate restarting the RTSP server.  For some reason, after several hours, it stops.  Camera is still connected via ssh, but video just stops.  I could reboot the camera itself each day, but would rather just restart the rtsp server for now.

### What did you do to debug the issue

I used to be able to resolve this problem (in earlier commits of this project years ago) with this script:

```
#!/bin/sh
/system/sdcard/controlscripts/rtsp-h264 stop
sleep 3
/system/sdcard/controlscripts/rtsp-h264 start

```
But rtsp-h264 no longer exists.  So, looking for the new way to do it.

### Evidence

My nvr says "cannot reach camera" and vlc does not see stream.  But, I can log into camera and see the camera view on home screen (although it appears frozen).  I can also ssh in.  I am able to reboot from camera web server, which is still running.

### Contribute Back

If your issue was resolved, please consider contributing back to the project by creating a pull request to improve the code or documentation in order to avoid that this issue arises again for other people.

**Comment by unrelentingtech** [comment]
> But rtsp-h264 no longer exists. So, looking for the new way to do it.

Try just `rtsp`

**Comment by SomebodySysop** [comment]
> > But rtsp-h264 no longer exists. So, looking for the new way to do it.
> 
> Try just `rtsp`

That does it.  Thanks.
