### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by manutenfruits** [EliasKotlyar/Xiaomi-Dafang-Hacks#1763]
Hi, I just wanted to point out that the project does not have a License! This might seem trivial but some employers restrict collaborating (even on a personal level) to certain repos that don't have licenses.

Do you mind adding one? And please note some lax licenses like WTFPL are not considered valid by many companies.

**Comment by jmtatsch** [comment]
Would love to add one but some things are based on the ingenic sdk. And everything is a Patchwork of a gazillion contributors who have not been asked. Is it still possible then?

**Comment by manutenfruits** [comment]
Absence of a license means [the code is copyrighted and nobody can use it](https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license). IANAL but I don't think you need to ask people that have contributed already, because they didn't have the legal right to fork it to begin with. With small projects like these usually nobody tries to enforce their rights, but it's not guaranteed.

About the Ingenic SDK, I'm not exactly sure what you mean by some things being based off of it, what "parts"? What license does the SDK have? Depending on their license it tells you how you can use it.

**Comment by manutenfruits** [comment]
Some info I found helpful: https://choosealicense.com
Includes what happens if you don't have a license: https://choosealicense.com/no-permission/

**Comment by jmtatsch** [comment]
Some stuff was compiled with a ingenic toolchain I don't know how official it is and who agreed to what terms for that.

**Comment by manutenfruits** [comment]
If you're not sure you should find out, but if it's not essential to the project (like a piece of firmware outside of firmware_mod which is what most people use), maybe you could move it to a separate repo, so you can license the important bits of the code (web UI, etc)
