### ISSUE TITLE
Telegram video alerts are no longer sent

### ISSUE THREAD

**Issue by nanoamp** [EliasKotlyar/Xiaomi-Dafang-Hacks#1767]
Neos SmartCam running latest beta commit (21f00d7).

### Description

Since I updated to a version after #1709 was merged, I've not had any video alerts via Telegram.

### What did you do to debug the issue

I replicated the new behaviour of _detectionOn.sh_ by creating a test video:
`openRTSP -4 -w 1920 -h 1080 -f 20 -d 10 -b 1500000 rtsp://REDACTED:REDACTED@127.0.0.1:8554/unicast > /tmp/test.mp4`

and then trying to strip the audio:
`avconv -i /tmp/test.mp4 -c:v copy -c:a copy /tmp/test-telegram.mp4`

This fails with the following error:
```
avconv version v13_dev0-1541-ge368b0cbf, Copyright (c) 2000-2018 the Libav developers
  built on May 17 2018 20:39:55 with gcc 4.7.2 (Ingenic r2.3.3 2016.12)
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1776040] invalid size 8 in stsd
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1776040] error reading header: -1052488119
test.mp4: Invalid data found when processing input
```

This is code which appears to have worked for @timstanley1985 in #1658, so I'm not sure why my instance would create an MP4 which isn't handled by avconv.

**Comment by nanoamp** [comment]
Output from openRTSP:
```
Created new TCP socket 3 for connection
Connecting to 127.0.0.1, port 8554 on socket 3...
...remote connection opened
Sending request: OPTIONS rtsp://REDACTED:REDACTED@127.0.0.1:8554/unicast RTSP/1.0
CSeq: 2
User-Agent: openRTSP (LIVE555 Streaming Media v2020.05.15)


Received 152 new bytes of response data.
Received a complete OPTIONS response:
RTSP/1.0 200 OK
CSeq: 2
Date: Fri, Jul 30 2021 21:29:43 GMT
Public: OPTIONS, DESCRIBE, SETUP, TEARDOWN, PLAY, PAUSE, GET_PARAMETER, SET_PARAMETER

Sending request: DESCRIBE rtsp://REDACTED:REDACTED@127.0.0.1:8554/unicast RTSP/1.0
CSeq: 3
User-Agent: openRTSP (LIVE555 Streaming Media v2020.05.15)
Accept: application/sdp

Received 175 new bytes of response data.
Received a complete DESCRIBE response:
RTSP/1.0 401 Unauthorized
CSeq: 3
Date: Fri, Jul 30 2021 21:29:43 GMT
WWW-Authenticate: Digest realm="LIVE555 Streaming Media", nonce="REDACTED"

Resending...
Sending request: DESCRIBE rtsp://REDACTED:REDACTED@127.0.0.1:8554/unicast RTSP/1.0
CSeq: 4
Authorization: Digest username="REDACTED", realm="LIVE555 Streaming Media", nonce="REDACTED", uri="rtsp://REDACTED:REDACTED@127.0.0.1:8554/unicast", response="REDACTED"
User-Agent: openRTSP (LIVE555 Streaming Media v2020.05.15)
Accept: application/sdp


Received 814 new bytes of response data.
Received a complete DESCRIBE response:
RTSP/1.0 200 OK
CSeq: 4
Date: Fri, Jul 30 2021 21:29:43 GMT
Content-Base: rtsp://127.0.0.1:8554/unicast/
Content-Type: application/sdp
Content-Length: 651

v=0
o=- 1627676274703749 1 IN IP4 192.168.1.106
s=LIVE555 Streaming Media v2020.05.15
i=LIVE555 Streaming Media v2020.05.15
t=0 0
a=tool:LIVE555 Streaming Media v2020.05.15
a=type:broadcast
a=control:*
a=range:npt=0-
a=x-qt-text-nam:LIVE555 Streaming Media v2020.05.15
a=x-qt-text-inf:LIVE555 Streaming Media v2020.05.15
m=video 0 RTP/AVP 96
c=IN IP4 0.0.0.0
b=AS:168
a=rtpmap:96 H264/90000
a=fmtp:96 profile-level-id=4d4028;sprop-parameter-sets=Z01AKJ2oHgCJ+WEAAAMAAQAAAwAyhA==,aO48gA==
a=x-dimensions:1920,1080
a=control:track1
m=audio 0 RTP/AVP 97
c=IN IP4 0.0.0.0
b=AS:168
a=rtpmap:97 L16/16000
a=fmtp:97
a=control:track2

Opened URL "rtsp://REDACTED:REDACTED@127.0.0.1:8554/unicast", returning a SDP description:
v=0
o=- 1627676274703749 1 IN IP4 192.168.1.106
s=LIVE555 Streaming Media v2020.05.15
i=LIVE555 Streaming Media v2020.05.15
t=0 0
a=tool:LIVE555 Streaming Media v2020.05.15
a=type:broadcast
a=control:*
a=range:npt=0-
a=x-qt-text-nam:LIVE555 Streaming Media v2020.05.15
a=x-qt-text-inf:LIVE555 Streaming Media v2020.05.15
m=video 0 RTP/AVP 96
c=IN IP4 0.0.0.0
b=AS:168
a=rtpmap:96 H264/90000
a=fmtp:96 profile-level-id=4d4028;sprop-parameter-sets=Z01AKJ2oHgCJ+WEAAAMAAQAAAwAyhA==,aO48gA==
a=x-dimensions:1920,1080
a=control:track1
m=audio 0 RTP/AVP 97
c=IN IP4 0.0.0.0
b=AS:168
a=rtpmap:97 L16/16000
a=fmtp:97
a=control:track2

Created receiver for "video/H264" subsession (client ports 42448-42449)
Created receiver for "audio/L16" subsession (client ports 32854-32855)
Sending request: SETUP rtsp://127.0.0.1:8554/unicast/track1 RTSP/1.0
CSeq: 5
Authorization: Digest username="REDACTED", realm="LIVE555 Streaming Media", nonce="REDACTED", uri="rtsp://127.0.0.1:8554/unicast/", response="REDACTED"
User-Agent: openRTSP (LIVE555 Streaming Media v2020.05.15)
Transport: RTP/AVP;unicast;client_port=42448-42449


Received 208 new bytes of response data.
Received a complete SETUP response:
RTSP/1.0 200 OK
CSeq: 5
Date: Fri, Jul 30 2021 21:29:43 GMT
Transport: RTP/AVP;unicast;destination=127.0.0.1;source=127.0.0.1;client_port=42448-42449;server_port=6970-6971
Session: 8B5D9F47;timeout=65

Setup "video/H264" subsession (client ports 42448-42449)
Sending request: SETUP rtsp://127.0.0.1:8554/unicast/track2 RTSP/1.0
CSeq: 6
Authorization: Digest username="REDACTED", realm="LIVE555 Streaming Media", nonce="REDACTED", uri="rtsp://127.0.0.1:8554/unicast/", response="REDACTED"
User-Agent: openRTSP (LIVE555 Streaming Media v2020.05.15)
Transport: RTP/AVP;unicast;client_port=32854-32855
Session: 8B5D9F47


Received 208 new bytes of response data.
Received a complete SETUP response:
RTSP/1.0 200 OK
CSeq: 6
Date: Fri, Jul 30 2021 21:29:43 GMT
Transport: RTP/AVP;unicast;destination=127.0.0.1;source=127.0.0.1;client_port=32854-32855;server_port=6972-6973
Session: 8B5D9F47;timeout=65

Setup "audio/L16" subsession (client ports 32854-32855)
Warning: We don't implement a QuickTime Audio Media Data Type for the "L16" track, so we'll insert a dummy "????" Media Data Atom instead.  A separate, codec-specific editing pass will be needed before this track can be played.
Outputting to the file: "stdout"
Sending request: PLAY rtsp://127.0.0.1:8554/unicast/ RTSP/1.0
CSeq: 7
Authorization: Digest username="REDACTED", realm="LIVE555 Streaming Media", nonce="REDACTED", uri="rtsp://127.0.0.1:8554/unicast/", response="REDACTED"
User-Agent: openRTSP (LIVE555 Streaming Media v2020.05.15)
Session: 8B5D9F47
Range: npt=0.000-10.000


Received 253 new bytes of response data.
Received a complete PLAY response:
RTSP/1.0 200 OK
CSeq: 7
Date: Fri, Jul 30 2021 21:29:43 GMT
Range: npt=0.000-
Session: 8B5D9F47
RTP-Info: url=rtsp://127.0.0.1:8554/unicast/track1;seq=10133;rtptime=101112125,url=rtsp://127.0.0.1:8554/unicast/track2;seq=49443;rtptime=2813138319

Started playing session
Receiving streamed data (for up to 10.000000 seconds)...
Sending request: TEARDOWN rtsp://127.0.0.1:8554/unicast/ RTSP/1.0
CSeq: 8
Authorization: Digest username="REDACTED", realm="LIVE555 Streaming Media", nonce="REDACTED", uri="rtsp://127.0.0.1:8554/unicast/", response="REDACTED"
User-Agent: openRTSP (LIVE555 Streaming Media v2020.05.15)
Session: 8B5D9F47

Received 65 new bytes of response data.
Received a complete TEARDOWN response:
RTSP/1.0 200 OK
CSeq: 8
Date: Fri, Jul 30 2021 21:29:53 GMT```

**Comment by c---** [comment]
The command to strip audio would be:
`avconv -i /tmp/test.mp4 -c:v copy -an /tmp/test-telegram.mp4`

What do you have set under Settings->Camera->Audio->Audio format?  avconv can only handle `OFF` or `PCMU`, no other audio formats.

If you want a more modern version of avconf I have compiled the [latest ffmpeg](https://github.com/c---/Xiaomi-Dafang-Tools/tree/master/bin) with support for H.264 and VP9 encoding. This is a nearly drop-in replacement for avconv. It also handles decoding of the other audio formats like OPUS and MP3. PCMU is also supported but not plain PCM because I can't figure out what format that actually is, nothing will play it.

**Comment by nanoamp** [comment]
> The command to strip audio would be:
> `avconv -i /tmp/test.mp4 -c:v copy -an /tmp/test-telegram.mp4`

Sorry, my bad in prepping the issue description. I was trying different params to see if I could provoke a difference, and pasted the wrong one. Same error with this version that doesn't transcode (copy) the audio.

> What do you have set under Settings->Camera->Audio->Audio format? avconv can only handle `OFF` or `PCMU`, no other audio formats.

I had PCM. I've tried with PCMU and with OFF and, after restarting the RTSP server each time, still get the same error from avconv. Shame that didn't fix it straight off, as then we could have guarded whether to do the avconv based on what's set in the config.

> If you want a more modern version of avconv I have compiled the [latest ffmpeg](https://github.com/c---/Xiaomi-Dafang-Tools/tree/master/bin) with support for H.264 and VP9 encoding. This is a nearly drop-in replacement for avconv. It also handles decoding of the other audio formats like OPUS, MP3, PCMU, and stripping PCM (decoding/copying the audio track with PCM is tricky but I'm working on it). Encoding OPUS, AAC, PCMU should work. Maybe other stuff I'm forgetting. I can easily compile new versions of ffmpeg to handle whatever it supports.

I might give that a try when I'm back in front of a computer. I assume it copes with throughput better than the older ffmpeg version mentioned in #1658? That was reported to transcode at 1/9x realtime 🤮

**Comment by c---** [comment]
Weird, that `invalid size 8 in stsd...-1052488119` error is almost always because of an unrecognized input audio format.

Transcoding speed depends on which format and resolution you're using. Just copying the video and stripping the audio is pretty fast. Use `-preset ultrafast` when encoding H.264 (mp4) or `-cpu-used 8` for encoding VP9 (webm). Or try the mjpeg or mpeg4 encoders (less compatible with apps though). 1920x1080 formats are of course going to be the slowest and use the most memory.

Keep in mind that memory usage is also an issue when encoding. Again, dependent on the resolution and formats you're encoding from/to. It's possible to run out of memory when and the process will get killed. Personally I scale my video down using something like `-vf scale=640:360` for Matrix because I don't need super high-res in a messaging app and the smaller file size is a huge benefit.

**Comment by c---** [comment]
Just a heads up. I have been playing with this and frankly there is no combination of codecs that is fast enough when re-encoding a RTSP file. avconv and ffmpeg are the same slow speed. Stripping audio and just copying the video stream is very fast but actual transcoding is quite slow. The processor is just not very powerful without hardware acceleration. Also memory constraints are a big problem.

Converting the MJPEG streams to H.264 or VP9 is pretty fast though.

**Comment by nanoamp** [comment]
I've had a bit more time to experiment, and it seems that when I stopped and restarted the RTSP server, it wasn't enough to pick up the requested change in audio codec. After a reboot, having set PCMU, it worked. So, I think the best fix here is to make running the avconv for telegram conditional on the configured format being PCMU/OFF. I'll PR that in a bit.
