### ISSUE TITLE
Web browsers can't open video files created by Dafang Hacks

### ISSUE THREAD

**Issue by towerofpower256** [EliasKotlyar/Xiaomi-Dafang-Hacks#1770]
### Description
I have a Wyze Cam v2, using Dafang Hacks downloaded on 15th of July 2021.

I'm not able to open any video files created by Dafang Hacks motion events or recordings in any sort of browser that I have on hand. This includes:
* manually opening the files.
* viewing the files using the Home Assistant Media Browser Player.

Attached is a sample recording video, made by the camera when it detected motion.
https://user-images.githubusercontent.com/8175242/129187441-010022d3-24f8-4f1d-85b8-48350bbbfab7.mp4

When I attempt to do so, the media player is visible, spins for a moment, and then stops. It appears that it refused to open the file, with no play button, and video length details.

![image](https://user-images.githubusercontent.com/8175242/128269080-5e282a38-e868-42a6-9973-9bff6ba19f4d.png)

And in Firefox.

![image](https://user-images.githubusercontent.com/8175242/128269345-73a9661d-146d-4a8c-adfe-3c795c5fc89d.png)

However, when I open the file in VLC, it opens fine. Here's the Codec information that shows.
![image](https://user-images.githubusercontent.com/8175242/128269436-9b23c160-3227-4e68-a645-9d9c0a2af508.png)

### What did you do to debug the issue

Browsers that I tested:
* Chrome (desktop) Version 92.0.4515.107 (Official Build) (64-bit)
* Edge (desktop) Version 92.0.902.62 (Official build) (64-bit)
* Firefox (desktop) Version 90.0.2 (64-bit)
* Home Assistant app (mobile, uses Chrome)
* Samsung Internet (mobile) Version 12.2.3.14

I confirmed that it wasn't an issue with Home Assistant by copying over a different MP4 file into the media browser, which played normally.

**Comment by c---** [comment]
How are you acquiring the video? Is that via FTP upload? Just wondering because I believe that's the only thing that creates mjpeg AVI files which I see in your picture. But I also see H.264 mp4 so I'm confused as to which format you're trying to play.

I thought the raw native RTSP H.264 recordings can be played in a browser but I need to check that again. The mjpeg format videos definitely can not be played by a browser.

For the mjpeg format in browsers the best solution I have found is to re-encode them using [my version of ffmpeg](https://github.com/c---/Xiaomi-Dafang-Tools/tree/master/bin) which can encode H.264 or VP9, both of which work great in the browser. Re-encoding the 1FPS mjpeg video is relatively quick (use `-preset ultrafast` with H .264 or `-cpu-usage 8` with VP9).

I have been thinking/working on a way to incorporate my build of ffmpeg to replace avconv in the default firmware so we can get proper H.264/VP9 encoding but haven't had a lot of time to spend on it (also not sure if it will be easily accepted since it's a major change).

**Comment by towerofpower256** [comment]
> How are you acquiring the video? Is that via FTP upload? Just wondering because I believe that's the only thing that creates mjpeg AVI files which I see in your picture. But I also see H.264 mp4 so I'm confused as to which format you're trying to play.

I've tried both the videos dumped by the openrtsp tool, and the videos made by stitching together still shots at 1-second intervals, my browsers can't seem to open either of them.

**Comment by okto2005** [comment]
have you tried update the codec? like k-lite mega codec etc??

**Comment by MyCodeRocks** [comment]
In the documentation says one needs to start the RSTP server with -S to get this to work. I am in the same situation as you as I need this for a home assistant.

Have you started the RTSP service with the -S flag - if you did I couldnt find out where to do this how did you do it?

One thing I think would be simple is if there could be a way to have a simple way to get video for systems like http://IP-address-of-your-webcam/path/to/stream?usr=User&pwd=Password

**Comment by towerofpower256** [comment]
> In the documentation says one needs to start the RSTP server with -S to get this to work. I am in the same situation as you as I need this for a home assistant.

Good to know, I might give this a try. I wonder what that `-S` flag does?

> One thing I think would be simple is if there could be a way to have a simple way to get video for systems like http://IP-address-of-your-webcam/path/to/stream?usr=User&pwd=Password

I did consider that, but I'd like to avoid that if I could. The series of events would be:
1. Motion detected.
2. Motion alert sent from camera to MQTT broker
3. MQTT broker forwards the motion alert to Home Assistant (or whatever solution you're using).
4. Home Assistant digests that alert. Eventually, an automation is fired which says to fetch a recording from the camera because motion was detected.
5. Home Assistant initiates and negotiates an RTSP connection with the camera, then saves the output to a file.

Lets say that introduces a 2-5 second delay. In 2-5 seconds, an intruder could've moved around the corner and you can't see their face anymore.

I'd prefer to have the recording done by the camera right as motion is detected.

**Comment by MyCodeRocks** [comment]
Well to enable the HLS stream which you trying to access, the rstp server has to be started with the -S flag otherwise you get no stream (which is what you experiencing now) so first we all have to figure out how to start the rstp service with -S at boot. I have looked but can't figure it out

**Comment by c---** [comment]
Look at `/system/sdcard/config/rtspserver.conf` there is a variable `RTSOPTS`, add the -S flag there and see if that works.

**Comment by MyCodeRocks** [comment]
That's a greàt pointer thank will try that today

**Comment by towerofpower256** [comment]
I'm not sure if we're talking about the same thing.
The issue I'm experiencing is with the video files, the recordings that are being created. They can't be opened by most web browsers (Chrome, Firefox, Edge, etc).

But it sounds like HLS has to do with streaming video over HTTP. Does that factor in with how the video recording files are created on the camera's storage?

**Comment by MyCodeRocks** [comment]
Let me understand can you open the HLS feed with VLC? If not then no matter what you use to view the feed it won't work unless you add the -S switch. I just added as per above to the config file and all working on all browsers now

**Comment by c---** [comment]
@towerofpower256 That video can't be played because it has an invalid audio codec. If I strip off the audio then it plays in Firefox. Set the audio codec to "OFF" or "PCMU". Those are the only ones that set the audio codec correctly. Browser should be able to play it then.

**Comment by towerofpower256** [comment]
> Set the audio codec to "OFF" or "PCMU". Those are the only ones that set the audio codec correctly. Browser should be able to play it then.

No joy, I'm afraid. In VLC I can see that the audio part of the files has indeed changed, but they still won't open in Chrome or Home Assistant.

Audio PCMU

https://user-images.githubusercontent.com/8175242/129190738-068b5b84-ed40-47b4-8913-64aa5c0898aa.mp4

Audio OFF

https://user-images.githubusercontent.com/8175242/129190389-6962f3ce-38f8-44a2-94c5-e6ad3a98de42.mp4

**Comment by towerofpower256** [comment]
In `/system/sdcard/scripts/detectionOn.sh`, the `record_video` function has caught my eye. It records the video by opening up `../openRTSP` and dumps that output to a file.

```
/system/sdcard/bin/openRTSP -4 -w "$video_rtsp_w" -h "$video_rtsp_h" -f "$video_rtsp_f" -d "$video_duration" -b "$output_buffer_size" rtsp://127.0.0.1:$PORT/unicast > "$video_tempfile"
```

`openRTSP` appears to be a 3rd party tool from Live555
http://www.live555.com/openRTSP/

The `-4` option in theory should be outputting an MPEG-4 file. The files being outputted are specifically MPEG-4 Part 10 which is AVC / H.264, which it turns out that Chrome dropped support for.

Damn.

**Comment by c---** [comment]
Yes, I see. Both play fine in Firefox but will not play in Chromium. Hmmm

**Comment by towerofpower256** [comment]
I did try changing the openRTSP command line arguments from `-4` (MPEG-4) to `-a` (AVI) and `-q` (Quicktime) but that didn't seem to change the video format itself, which remained MPEG-4 part 10 H.264.

**Comment by c---** [comment]
The video format is limited because the accelerated hardware encoder only encodes in that specific H.264 format.

**Comment by towerofpower256** [comment]
@c--- I'd be interesting in having a crack at getting `ffmpeg` to dump the video from the RTSP stream locally on the camera, and use that to save the recording.

Having a quick look at the FFMPEG guide, it looks like I can do that with the below, does that sound about right?
```
ffmpeg -i "rtsp://127.0.0.1/unicast" -c copy -map 0 -f segment -segment_time 300 -segment_format mp4 "capture.mp4"
```

That link that you've got at the top there, how would I go about getting that onto the camera?
