### ISSUE TITLE
Unable to flash iSmartAlarm Spot+ (iSC5P)

### ISSUE THREAD

**Issue by ghost** [EliasKotlyar/Xiaomi-Dafang-Hacks#1775]
THello,
I tried a lot of times to flash Xiomi-Dafang-Hacks on iSmartAlarm Spot+ (iSC5P).
I tried different ways/firmware and steps, different sd card (with different partitions), pushing on "setup" while plugin power for 1/2/5/10/15/20/30... seconds.

I still have no blue led, only an orange one blinking fast.
And if I stay more than 30s on setup, I have a voice telling me "Ready to connect".

Anybody managed to flash an iSmartAlarm Spot+ or can I just throw them to the bin?

Thank you for your help.

**Comment by magarma** [comment]
Same here, did you manage to do something with it?

**Comment by jdherdt** [comment]
same here ... no light change :/
