### ISSUE TITLE
What next after flashing u-boot bootloader? Just a blue LED, no connection

### ISSUE THREAD

**Issue by DrNicT61** [EliasKotlyar/Xiaomi-Dafang-Hacks#1776]
* exact camera hardware: Wyze Cam v2 FCC 2ANJHWYZEC02
* the Xiaomi-Dafang-Hacks commitid (from `git log`) you are experiencing the issue with: Current 

### Description

Successfully flashed dafang cfw onto my camera and was able to access the web ui! 

Then I wanted FullHD, so I followed the "Flashing an open source U-Boot bootloader" guide. The md5 matched my downloaded file, it flashed fine, then I renamed the uEnv.bootfromnand file to uEnv. After rebooting the camera, I now only have a solid blue LED. The camera isn't connecting to my network anymore. I don't know if there are any additional steps to get this working or if it's now bricked? If there are additional steps, it's not clear from the documentation :S 

### What did you do to debug the issue

-if I rename the uEnv file back to uEnv.bootfromnand and reset power to the camera, the LED will turn on and stay on solid yellow / orange
-if I rename the uEnv.bootfromnand file again back to just uEnv, then reset the power, the LED will turn on and stay on solid blue again
-tried reformatting the sdcard and booting with just demo.bin anbd holding the setup button, just getting a solid orange LED when powered on
-copying the modded firmware files back onto the sdcard and renaming the uEnv.bootfromnand back to uEnv again still shows a blue LED after powering on, so it seems there is some hope?

### Evidence

There are no logs being generated on the sdcard and I have no access to the camera to get any

**Comment by klack** [comment]
Getting the same error.  @DrNicT61 did you find the answer?

**Comment by DrNicT61** [comment]
> Getting the same error. @DrNicT61 did you find the answer?

Sadly I have not. I got my hands on another Wyze camera and had no issues setting it up!
