### ISSUE TITLE
Why are my 3 exact cameras getting different kernel versions?

### ISSUE THREAD

**Issue by surfrock66** [EliasKotlyar/Xiaomi-Dafang-Hacks#1778]
To make sure your issue can be resolved as quickly as possible please state your

I have 3 exact Wyzecam v2 cameras
All 3 are on "master" branch as of 2021.09.06

### Description

I had 2 cameras working fine with the Xiaomi Dafang Hacks firmware.  I bought 2 more, and even though all are up to date with the master branch, I'm getting differences in the UI.  The CSS is slightly different and in the info page, I'm getting a different Kernel version.  The problem is, I cannot enable SSH on the older cameras to do additional troubleshooting; the option isn't even there in the services list.

### What did you do to debug the issue

I have done full forced updates on all 3 devices, and have switched to beta and stable branches of all cameras and back.  The versions show the same on all, except for the kernel version.  I don't see what configuration or update I can do to get all the cameras fully in sync up to date.

### Evidence

![sr66-wyze-01 info](https://user-images.githubusercontent.com/1345467/132263706-a8df3022-8022-4d4e-a63e-4bd56597511d.png)
![sr66-wyze-01 services](https://user-images.githubusercontent.com/1345467/132263708-1fa8f702-95ee-492c-a618-bfe7b4966bfa.png)
![sr66-wyze-02 info](https://user-images.githubusercontent.com/1345467/132263710-b56656d9-219c-49f1-96b4-c1d0efb32fd9.png)
![sr66-wyze-02 services](https://user-images.githubusercontent.com/1345467/132263711-fa8da742-89db-404c-87cb-77e78cecf24e.png)
![sr66-wyze-03 info](https://user-images.githubusercontent.com/1345467/132263713-fbd649ae-30a9-4625-bfa9-54881af26c74.png)
![sr66-wyze-03 services](https://user-images.githubusercontent.com/1345467/132263714-f18380a5-3fbc-4c95-ae2b-28cc4e640288.png)

### Contribute Back

If your issue was resolved, please consider contributing back to the project by creating a pull request to improve the code or documentation in order to avoid that this issue arises again for other people.

**Comment by jmtatsch** [comment]
Kernel versions can only change with flashing the initial demo.bin custom firmware flash. All updates just affect your overlay file system. Maybe you hacked these cameras at different times?

Regarding the different services available, that is likely a config file migration issue so either start with a fresh checkout on your sd without the botched old config files or copy the sd of a "working" camera.

**Comment by surfrock66** [comment]
For sure they were done at different times.  I'll try to do that; the chicken-and-egg of not being able to access the cards over ssh is a pain as they're mounted in a physically difficult place to get, but that's just life.

**Comment by jmtatsch** [comment]
Can you maybe use the FTP server to replace those configs? Or how about telnet access?

**Comment by c---** [comment]
If you have SSH access I use rsync to synchronize the SD card configs. I have a build for the cameras [here](https://github.com/c---/Xiaomi-Dafang-Tools/tree/master/bin).

**Comment by surfrock66** [comment]
Sorry if it wasn't clear...that's the problem, SSH appears to have disappeared on the older cameras?  The SSH slider for the service is gone.  Is there a way you can think of to re-enable it remotely?  I've tried full firmware update.

**Comment by c---** [comment]
Oh, my fault for not reading. I'm not sure why the SSH service wouldn't show up. I've had my config on the SD card corrupted by the camera before. They don't seem terribly stable.

**Comment by jmtatsch** [comment]
Did you try telnet? FTP?
