### ISSUE TITLE
Bootloader step is done, but 1S is booting straight into official firmware

### ISSUE THREAD

**Issue by Kaan88** [EliasKotlyar/Xiaomi-Dafang-Hacks#1779]
I have a Xiaomi Xiaofang 1S, not sure if it's T20L but I already tried instructions for it every single time. The device just boots into official firmware and there are absolutely no logs.

My evidence for successful CFW flash comes from Mi Home firmware update screen, it shows 5.6.2.43 instead of a newer version it was before. I could flash firmwares old and new or CFW with no issue. Also blue light stays on for 5 seconds.

### What did you do to debug the issue

I tried 3 different SD cards as I thought it was the CFW step that wasn't working, but that doesn't seem to be the case. I even did every step from Linux to prevent Windows from creating unnecessary folders and such.

### Evidence

http://IP is a blank page and Mi Home works like before.

Searched for issues all day but all I could find was people failing to flash CFW, not booting firmware_mod. I'm out of ideas, I'm thinking of getting FTDI adapter to get logs.

**Comment by anzo** [comment]
It was the same problem. I took out an old Samsung SD card and managed to fix it.
The Maxell class 10 did not work.
