### ISSUE TITLE
Motion detection works, but doesn`t execute the script

### ISSUE THREAD

**Issue by goermezer** [EliasKotlyar/Xiaomi-Dafang-Hacks#178]
Impressive! Only 12 days to implement motion detection, which looks very promising.

I understood that the intention of #176 was to call the script /system/sdcard/scripts/detectionOn.sh whenever motion was detected. That seems not to work at the moment. I created the script with following content:

#!/bin/sh
/system/sdcard/bin/curl --header "Content-Type: text/plain" --request PUT --data "ON" http://openhab/rest/items/motion/state

It is executable. Should it work like that?

**Comment by nik0** [comment]
yes, there is something that doesn't work ?
do you have the little circle when the detection is on ?
do you have the output of the v4l2rtspserver-master?

**Comment by nik0** [comment]
Try to put "&" at the end of the curl command:

`#/bin/sh
/system/sdcard/bin/curl --header "Content-Type: text/plain" --request PUT --data "ON" http://openhab/rest/items/motion/state&
`
and you can try to add a command like that, and then  check if the file exists
`date >> /tmp/detect.txt`

**Comment by goermezer** [comment]
& doesn`t work
date >> /tmp/detect.txt doesn`t work
touch /system/sdcard/test.txt doesn`t work

I started the server from the shell. The detection is being logged fine.  I also had a look into ImpEncoder.cpp (home it`s the right program. And it seems that this line is not executed:

LOG(NOTICE) << "Will execute command " << command << "\n";

Here is my output of the server:
...
[NOTICE] /home/osboxes/SRC/Xiaomi-Dafang-Software/v4l2rtspserver-master/src/ServerMediaSubsession.cpp:41
        Creating normal Source...
[NOTICE] /home/osboxes/SRC/Xiaomi-Dafang-Software/v4l2rtspserver-master/src/ServerMediaSubsession.cpp:50
        RTCPInstance::RTCPInstance error: totSessionBW parameter should not be zero!
RTCPInstance::RTCPInstance error: totSessionBW parameter should not be zero!
Creating Sink for format : audio/MPEG
[NOTICE] /home/osboxes/SRC/Xiaomi-Dafang-Software/v4l2rtspserver-master/src/ImpEncoder.cpp:646
        Detect !!

[NOTICE] /home/osboxes/SRC/Xiaomi-Dafang-Software/v4l2rtspserver-master/src/ImpEncoder.cpp:656
        Detect finished!!
...

**Comment by nik0** [comment]
What do you mean by "doesn't work"? You have an error when executing `date >> /tmp/detect.txt `  ?
According to the trace it seems that your script exists and may be executed
can you try:
`chmod +x /system/sdcard/scripts/detectionOn.sh`
and post the output of
`ls -l /system/sdcard/scripts/detectionOn.sh`

**Comment by helio58** [comment]
Hi,  its it possible to make a script to record on motion to the sdcard ?

**Comment by nik0** [comment]
Yes, but I didn't succeeded have avconv working
You can try having this kind of stuff in the script: https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/wiki/Take-a-video-and-upload-it-to-an-FTP-Server
With only `FILE=`date +%Y-%m-%d_%H.%M.mov` && ./avconv -rtsp_transport tcp -y -i rtsp://0.0.0.0:8554/unicast -vcodec copy -c:a aac -strict experimental -t 10 /system/sdcard/DCIM/VideoRecorder/$FILE`
theoretically it should work.

But for me it is not working ;-(
 https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/106

**Comment by goermezer** [comment]
@nik0 there is no error and the file was not created.
The script was already executable. So chmod +x didn`t help.
Here is the requested output:

[root@DAFANG1:~]# ls -l /system/sdcard/scripts/detectionOn.sh
-rwxr-xr-x    1 root     root           170 Mar 23 23:53 /system/sdcard/scripts/detectionOn.sh
[root@DAFANG1:~]#

**Comment by nik0** [comment]
If you just execute your script it is working as expected?
It is strange anyway that you cannot create a file in /tmp

**Comment by goermezer** [comment]
The script is always working as expected when I call it from the shell. It doens`t matter, if it writes a file, send a command to Openhab or whatever. The problem is, that it is not executed from v4l2rtspserver-master.

**Comment by nik0** [comment]
Can you try this binary and check the logs

[v4l2rtspserver-master.zip](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/files/1844547/v4l2rtspserver-master.zip)

**Comment by goermezer** [comment]
Can not see any difference. I`m 100% sure, that I replaced the binary.

[NOTICE] /home/osboxes/SRC/Xiaomi-Dafang-Software/v4l2rtspserver-master/src/main.cpp:151
        Play this stream using the URL "rtsp://192.168.178.100:8554/unicast"
[NOTICE] /home/osboxes/SRC/Xiaomi-Dafang-Software/v4l2rtspserver-master/src/DeviceSource.cpp:87
        begin thread
[NOTICE] /home/osboxes/SRC/Xiaomi-Dafang-Software/v4l2rtspserver-master/src/ImpEncoder.cpp:655
        Detect !!
[NOTICE] /home/osboxes/SRC/Xiaomi-Dafang-Software/v4l2rtspserver-master/src/ImpEncoder.cpp:665
        Detect finished!!
[NOTICE] /home/osboxes/SRC/Xiaomi-Dafang-Software/v4l2rtspserver-master/src/ImpEncoder.cpp:655
        Detect !!
[NOTICE] /home/osboxes/SRC/Xiaomi-Dafang-Software/v4l2rtspserver-master/src/ImpEncoder.cpp:665
        Detect finished!!

**Comment by nik0** [comment]
Can you please double check you replaced the binary (re-download it, I changed it)
The line for the detect message should be 664 instead of 655

**Comment by goermezer** [comment]
Can you double check the timestamp of the file? It seems that the line number doesn`t change. I downloaded the file multiple times and also cleared the browser cache:

[NOTICE] /home/osboxes/SRC/Xiaomi-Dafang-Software/v4l2rtspserver-master/src/ImpEncoder.cpp:655
        Detect !!
[NOTICE] /home/osboxes/SRC/Xiaomi-Dafang-Software/v4l2rtspserver-master/src/ImpEncoder.cpp:665
        Detect finished!!

**Comment by nik0** [comment]
And with this one:
[v4l2rtspserver-master.zip](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/files/1844685/v4l2rtspserver-master.zip)

**Comment by goermezer** [comment]
Ok, that did it. Seems to be a memory error. I drive the cam with 1664x936. Will try to reduce the resulotion...

[NOTICE] /home/osboxes/SRC/Xiaomi-Dafang-Software/v4l2rtspserver-master/src/ImpEncoder.cpp:662
        Detect !!
540
543
555
[NOTICE] /home/osboxes/SRC/Xiaomi-Dafang-Software/v4l2rtspserver-master/src/ImpEncoder.cpp:556
        Fork error !!Cannot allocate memory
573
672
[NOTICE] /home/osboxes/SRC/Xiaomi-Dafang-Software/v4l2rtspserver-master/src/ImpEncoder.cpp:673
        Detect finished!!
540
543
555
[NOTICE] /home/osboxes/SRC/Xiaomi-Dafang-Software/v4l2rtspserver-master/src/ImpEncoder.cpp:556
        Fork error !!Cannot allocate memory
573

**Comment by goermezer** [comment]
Even with default resolution I get the memory error.

**Comment by goermezer** [comment]
With lower resolution (v4l2rtspserver-master -W 896 -H 504) the script finally gets executed. Seems that we have to save some memory :-)

**Comment by goermezer** [comment]
I don`t know if this it is a good idea. But I created a 256MB swap file on sdcard, which solved the memory issue above:

dd if=/dev/zero of=/system/sdcard/swapfile bs=1M count=256
mkswap /system/sdcard/swapfile
swapon /system/sdcard/swapfile

After reboot it isn`t mounted. So I added this to run.sh:

swapon /system/sdcard/swapfile

**Comment by nik0** [comment]
Does it help ?
I did this at the beginning (maybe it is related, or not): https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/30

**Comment by nik0** [comment]
By curiosity can you post the result of the commands:
`free -m`
`ps -l`

**Comment by herrxyz** [comment]
would you mind to sum up all necessary files and changes to get it to work?

**Comment by goermezer** [comment]
@nik0:
[root@Camera2:~]# free -m
             total         used         free       shared      buffers
Mem:         35404        33956         1448            0         1120
-/+ buffers:              32836         2568
Swap:       262136            0       262136

[root@Camera2:~]# ps -l
S   UID   PID  PPID   VSZ   RSS TTY   STIME TIME     CMD
S     0     1     0  1600   456 0:0   12:51 00:00:02 {linuxrc} init
S     0     2     0     0     0 0:0   12:51 00:00:00 [kthreadd]
S     0     3     2     0     0 0:0   12:51 00:00:00 [ksoftirqd/0]
S     0     4     2     0     0 0:0   12:51 00:00:00 [kworker/0:0]
S     0     5     2     0     0 0:0   12:51 00:00:00 [kworker/0:0H]
S     0     6     2     0     0 0:0   12:51 00:00:00 [kworker/u2:0]
S     0     7     2     0     0 0:0   12:51 00:00:00 [rcu_preempt]
S     0     8     2     0     0 0:0   12:51 00:00:00 [rcu_bh]
S     0     9     2     0     0 0:0   12:51 00:00:00 [rcu_sched]
S     0    10     2     0     0 0:0   12:51 00:00:00 [watchdog/0]
S     0    11     2     0     0 0:0   12:51 00:00:00 [khelper]
S     0    12     2     0     0 0:0   12:51 00:00:00 [writeback]
S     0    13     2     0     0 0:0   12:51 00:00:00 [bioset]
S     0    14     2     0     0 0:0   12:51 00:00:00 [kblockd]
S     0    15     2     0     0 0:0   12:51 00:00:00 [khubd]
S     0    16     2     0     0 0:0   12:51 00:00:00 [kworker/0:1]
S     0    17     2     0     0 0:0   12:51 00:00:00 [cfg80211]
S     0    18     2     0     0 0:0   12:51 00:00:00 [rpciod]
S     0    19     2     0     0 0:0   12:51 00:00:00 [kworker/0:2]
S     0    20     2     0     0 0:0   12:51 00:00:00 [kswapd0]
S     0    21     2     0     0 0:0   12:51 00:00:00 [fsnotify_mark]
S     0    22     2     0     0 0:0   12:51 00:00:00 [nfsiod]
S     0    23     2     0     0 0:0   12:51 00:00:00 [crypto]
S     0    37     2     0     0 0:0   12:51 00:00:00 [kworker/u2:1]
S     0    38     2     0     0 0:0   12:51 00:00:00 [deferwq]
S     0    39     2     0     0 0:0   12:51 00:00:00 [kworker/0:1H]
S     0    52     1  1588   216 0:0   12:51 00:00:00 telnetd
S     0    54     2     0     0 0:0   12:51 00:00:00 [kworker/u2:2]
S     0    56     2     0     0 0:0   12:51 00:00:00 [mmcqd/0]
S     0    60     2     0     0 0:0   12:51 00:00:00 [jffs2_gcd_mtd4]
S     0    62     2     0     0 0:0   12:51 00:00:00 [jffs2_gcd_mtd7]
S     0    64     2     0     0 0:0   12:51 00:00:00 [jffs2_gcd_mtd8]
S     0    66     2     0     0 0:0   12:51 00:00:00 [jffs2_gcd_mtd9]
S     0    73     1  1600   444 ttyS1 12:51 00:00:00 /sbin/getty -L console 11
S     0    91     2     0     0 0:0   12:51 00:00:00 [ksdioirqd/mmc1]
S     0    94     2     0     0 0:0   12:51 00:00:00 [RTW_XMIT_THREAD]
S     0    95     2     0     0 0:0   12:51 00:00:00 [RTW_CMD_THREAD]
S     0    96     2     0     0 0:0   12:51 00:00:00 [RTWHALXT]
S     0   105     1  4696  1336 0:0   12:51 00:00:00 wpa_supplicant -B -i wlan
S     0   142     1  1604   212 0:0   12:52 00:00:00 udhcpc -i wlan0 -p /var/r
S     0   145     2     0     0 0:0   12:52 00:00:00 [i2s_work_1]
S     0   146     2     0     0 0:0   12:52 00:00:00 [i2s_codec_irq_w]
D     0   158     2     0     0 0:0   12:52 00:00:00 [motor_thread]
S     0   164     2     0     0 0:0   12:52 00:00:00 [irq/37-isp]
S     0   177     1  1448   344 0:0   12:52 00:00:00 {dropbearmulti} /system/s
S     0   181     1  1236   356 0:0   12:52 00:00:00 /system/sdcard/bin/bftpd
S     0   182     1  1280   404 0:0   12:52 00:00:00 /system/sdcard/bin/boa -c
S     0   195     1  1596   444 0:0   12:52 00:00:00 {ldr.sh} /bin/sh /system/
S     0   214     1  173m 11340 0:0   12:52 00:00:37 {v4l2rtspserver-} /system
D     0   219     2     0     0 0:0   12:52 00:00:02 [apical_isp_fw_p]
S     0   245   177  1516   664 0:0   12:52 00:00:01 {dropbearmulti} /system/s
S     0   256   245  1600   516 pts0  12:52 00:00:00 -sh
S     0   298   195  1584   296 0:0   12:53 00:00:00 sleep 10
R     0   299   256  1588   412 pts0  12:53 00:00:00 ps -l

**Comment by goermezer** [comment]
@herrxyz: Currently I`m testing it. If it works stable, I hope to get created a wiki item.

**Comment by hubmon** [comment]
Every time run configMotion I get
Invalid Argument r
Invalid Argument m
Invalid Argument z

What am I missing?

**Comment by nik0** [comment]
I think you didn't copy the binary setconf

**Comment by msj33** [comment]
This is SO cool! Thanks a lot:-)

The sensitivity is working very well for motion detection.

Can anyone please share an example of how to integrate this with Home Assistant? Or give an example on how I can send a trigger/event to Home Assistant for grabbing pictures/recording.

**Comment by hubmon** [comment]
@nik0 Thanks, that was it. FTP dropped out.

**Comment by shiznat** [comment]
@msj33 I would also love to know this!

**Comment by goermezer** [comment]
Anybody here, who has got motion detection working without memory issues? For me it only works, when I enable a swap file or drastically reduce the resolution. Even when I kill bftp and telnetd, memory seems not to be enough?! Does this thing really has ~35MB RAM?

```
[root@DAFANG2:~]# ps
  PID USER       VSZ STAT COMMAND
    1 root      1600 S    {linuxrc} init
    2 root         0 SW   [kthreadd]
    3 root         0 SW   [ksoftirqd/0]
    4 root         0 SW   [kworker/0:0]
    5 root         0 SW<  [kworker/0:0H]
    6 root         0 SW   [kworker/u2:0]
    7 root         0 SW   [rcu_preempt]
    8 root         0 SW   [rcu_bh]
    9 root         0 SW   [rcu_sched]
   10 root         0 SW   [watchdog/0]
   11 root         0 SW<  [khelper]
   12 root         0 SW<  [writeback]
   13 root         0 SW<  [bioset]
   14 root         0 SW<  [kblockd]
   15 root         0 SW   [khubd]
   16 root         0 SW   [kworker/0:1]
   17 root         0 SW<  [cfg80211]
   18 root         0 SW<  [rpciod]
   19 root         0 SW   [kworker/0:2]
   20 root         0 SW   [kswapd0]
   21 root         0 SW   [fsnotify_mark]
   22 root         0 SW<  [nfsiod]
   23 root         0 SW<  [crypto]
   37 root         0 SW   [kworker/u2:1]
   38 root         0 SW<  [deferwq]
   39 root         0 SW<  [kworker/0:1H]
   54 root         0 SW   [kworker/u2:2]
   56 root         0 SW   [mmcqd/0]
   60 root         0 SWN  [jffs2_gcd_mtd4]
   62 root         0 SWN  [jffs2_gcd_mtd7]
   64 root         0 SWN  [jffs2_gcd_mtd8]
   66 root         0 SWN  [jffs2_gcd_mtd9]
   73 root      1600 S    /sbin/getty -L console 115200 vt100
   91 root         0 SW   [ksdioirqd/mmc1]
   94 root         0 SW   [RTW_XMIT_THREAD]
   95 root         0 SW   [RTW_CMD_THREAD]
   96 root         0 SW   [RTWHALXT]
  105 root      4700 S    wpa_supplicant -B -i wlan0 -c /system/sdcard/config/wpa_supplicant.conf -P
  142 root      1604 S    udhcpc -i wlan0 -p /var/run/udhcpc.pid -b -x hostname DAFANG2
  145 root         0 SW<  [i2s_work_1]
  146 root         0 SW<  [i2s_codec_irq_w]
  158 root         0 DW   [motor_thread]
  164 root         0 SW   [irq/37-isp]
  177 root      1452 S    /system/sdcard/bin/dropbearmulti dropbear -R
  182 root      1296 S    /system/sdcard/bin/boa -c /system/sdcard/config/
  287 root      1592 S    {mqtt-status-int} /bin/sh /system/sdcard/scripts/mqtt-status-interval.sh
  419 root      1520 S    /system/sdcard/bin/dropbearmulti dropbear -R
  420 root      1612 S    -sh
  537 root      163m S    /system/sdcard/bin/v4l2rtspserver-master
  541 root         0 DW   [apical_isp_fw_p]
  558 root      1520 R    /system/sdcard/bin/dropbearmulti dropbear -R
  559 root      1600 S    -sh
  604 root      1584 S    sleep 30
  605 root      1592 R    ps
[root@DAFANG2:~]# free
             total         used         free       shared      buffers
Mem:         35404        33836         1568            0         1696
-/+ buffers:              32140         3264
Swap:            0            0            0
```

**Comment by jmtatsch** [comment]
@goermezer running here stable with no issues on 3 cameras. One of my cameras has a flashed bootloader for a different memory partitioning because full hd streaming needs more ram also. But i don't remember which one :) Maybe you dig up the old FHD bootloader flashing thread ... its not without risks but may be worth your while.

**Comment by goermezer** [comment]
@jmtatsch would you post the output of `free` for one of your cams with normal partitioning? I installed the bootloader according to the instructions in README.md. Perhaps something went wrong for me.

**Comment by jmtatsch** [comment]
```
[root@DAFANGHACKS:~]# free
             total         used         free       shared      buffers
Mem:         99640        95432         4208            0          176
-/+ buffers:              95256         4384
Swap:            0            0            0
```

**Comment by jmtatsch** [comment]
```
[root@DAFANGHACKS:~]# free
             total         used         free       shared      buffers
Mem:         82232        74676         7556            0         3072
-/+ buffers:              71604        10628
Swap:            0            0            0
```

**Comment by goermezer** [comment]
Very interesting. You have ~100MB Memory. Nearly three times more than mine with 35MB ?!

**Comment by jmtatsch** [comment]
```
[root@DAFANGHACKS:~]# free
             total         used         free       shared      buffers
Mem:         99640        96924         2716            0         1400
-/+ buffers:              95524         4116
Swap:            0            0            0
```

**Comment by jmtatsch** [comment]
seems more like i modded two of them

**Comment by goermezer** [comment]
Thanks jmtatsch. I have already read the post with FHD bootloader. But until today I was not keen enough. Now I did it and I have 82MB, which changes everything :-).  Motion detection even works in FHD now. That`s quite impressive!

**Comment by shinebar1001** [comment]
Hm. My camera is definitely unmodded:
![image](https://user-images.githubusercontent.com/33186930/38389252-24651a66-391e-11e8-9972-2269edcba24b.png)
Maybe there are different versions in the wild?

**Comment by lolouk44** [comment]
Same here. Unmodded and I have just under 100mb. Based on @goermezer I think I might take the plunge and try FHD too...

**Comment by goermezer** [comment]
@jmtatsch : One last question, please can you provide me your normal bootloader.bin from your last unmodded cams? I have some stability issues with the fullhd-bootloader and want to go to default.

**Comment by jmtatsch** [comment]
Actually I think all 99640 K memory cams are unmodded. 
I dumped the bootloader from one of them for you like this:
```
dd if=/dev/mtdblock0 of=uboot.bin
512+0 records in
512+0 records out
262144 bytes (256.0KB) copied, 0.072591 seconds, 3.4MB/s
```
Use at you own risk!
https://www.dropbox.com/s/7x5zb2587sntpyh/uboot.bin?dl=0

**Comment by goermezer** [comment]
Thank you very much. Exactly, what I needed :-)

**Comment by tradziej** [comment]
@goermezer how did you solve this issue? I've also only 35MB memory.

**Comment by goermezer** [comment]
@tradziej you have to replace your bootloader. jmtatsch provided it 2 posts above via dropbox: https://www.dropbox.com/s/7x5zb2587sntpyh/uboot.bin?dl=0

First download it and copy it to your SDCard. Don`t do it via FTP. Your FTP client could transfer it as text and you would brick your cam. Do it in Windows or select another reliable method. I copied  it through a NFS mount directly from my NAS and and did then following:

```
flash_eraseall /dev/mtd0
dd if=/system/sdcard/uboot.bin of=/dev/mtd0
```
That`s it. Reboot your cam.

**Comment by tradziej** [comment]
@goermezer thanks!

**Comment by shinebar1001** [comment]
We should add that to the wiki, don't we?

**Comment by robbinjanssen** [comment]
Does this work for the Xiaofang 1S as well?

**Comment by robbinjanssen** [comment]
@goermezer so what exactly does the bootloader do, extend the memory somehow? I read the thread but don't really get it yet.

Would applying a different bootloader (enabling more memory) be better?

**Comment by goermezer** [comment]
@robbinjanssen You don`t need the bootloader for a swap file. What I posted in comment #178 is a standard way in Linux to create a swap file, which caches a max of 64 MB of memory to SDCard. With a little more available memory, the motion detection and script execution works for me reliable on a Xiaofang 1S.

**Comment by goermezer** [comment]
@rfenouil I can not explain it in detail. But the bootloader posted in this post could be old. Please read this post: #573

**Comment by dmolner** [comment]
> Hola @goermezer i gràcies per les teves publicacions. 
> Gràcies, em vaig alliberar del problema de la memòria mitjançant un fitxer d'intercanvi i podria habilitar la detecció de moviment al meu Xiaofang 1S amb 35 MB de memòria.
> 
> Si això ajuda, això és el que va afegir un run.sh (després de la configuració del nom del servidor), de manera que es crea un nou swap si canvia la targeta SD o elimineu el fitxer. 
> Després d'afegir, només cal reiniciar la càmera (el primer reboot serà més llarg ja que necessita crear un fitxer d'intercanvi).
> 
> ```
> ## Create swap file on SD if does not exist and use it
> SWAP=true
> SWAPPATH="/system/sdcard/swapfile"
> SWAPSIZE=256
> if [ "$SWAP" = true ]; then
>   if [ ! -f $SWAPPATH ]; then
>     echo "Creating ${SWAPSIZE}MB swap file on SD card"  >> $LOGPATH
>     dd if=/dev/zero of=$SWAPPATH bs=1M count=$SWAPSIZE
>     mkswap $SWAPPATH
>     echo "Swap file created in $SWAPPATH" >> $LOGPATH
>   fi
>   echo "Configuring swap file" >> $LOGPATH
>   swapon $SWAPPATH
>   echo "Swap set on file $SWAPPATH" >> $LOGPATH
> fi
> ```
> Tanmateix, realment no entenc què parpellejar el gestor d'arrencada ajuda per dispositius de 35 MB. La càmera té més d'això però una part d'ella queda reservada per a altres coses pel gestor d'arrencada original?
> 
> El 'uboot.bin' s'adjunta a aquest fil idèntic al d'instruccions de FHD?
> 
> Què es diu un mod? Parpellejant el booloader?
> 
> Ho sento per les preguntes ingenioses, la teva ajuda és molt apreciada.
> 
> Edita: Disculpeu una mica de duplicat amb les preguntes @robbinjanssen ;)

Could you indicate the apropiate line for insert these?

**Comment by Jpsy** [comment]
Just for completeness:
Creating a swap file meanwhile is part of Dafang Hacks. 
You just have to activate it.  Read the FAQ: 
https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/hacks/faq.md
> **What if my scripts in config/userscripts/motiondetection are not executed or mqtt/telegram messages/emails are not sent on motion?**
Your camera probably runs out of memory when processing the motion event. This is likely in cameras with 64MB e.g. the Xiaofang 1s. Try to enable some swap memory by copying swap.conf.dist to swap.conf and setting SWAP=true.
