### ISSUE TITLE
Home Assistant Media Browser Support

### ISSUE THREAD

**Issue by broyuken** [EliasKotlyar/Xiaomi-Dafang-Hacks#1780]
Not an issue but a feature request. Would it be possible to pull the motion videos from the cameras into Home Assistant's Media Browser? This would be similar to how MotionEye and Frigate do it.

**Comment by nemiro-TECH** [comment]
Include in your config file in home assistant:

`camera:
   - platform: generic
     name: Camera
     still_image_url: https://192.168.0.40/cgi-bin/currentpic.cgi
     username: !secret cam_user
     password: !secret cam_pass
     authentication: basic
     verify_ssl: false
     scan_interval: 5`

Edit your camera IP, user and pswd.

Works like a charm

**Comment by broyuken** [comment]
That just is the most recent static image, not historical motion events via the media browser.

**Comment by nemiro-TECH** [comment]
Ok. Understood.

Is there a way to pull the files on the HA side?

On the camera side you can open an smb or ftp access.
