### ISSUE TITLE
What is the latest "safe" version of the original Wyzecam V2 firmware?

### ISSUE THREAD

**Issue by nospam2k** [EliasKotlyar/Xiaomi-Dafang-Hacks#1787]
Sorry to put this as an issue but not able to find info elsewhere. I just want to know how far I can upgrade my Wyzecam V2 without effecting the ability to load XDH or flashing boot loader. It would be nice to have this info in the readme.

**Comment by seganku** [comment]
It would be really nice to have a working demo.bin in under firmware_original/!

I'm having trouble with dd over serial :(
