### ISSUE TITLE
Is my cam bricked? Very odd behavior.

### ISSUE THREAD

**Issue by kram12085** [EliasKotlyar/Xiaomi-Dafang-Hacks#1794]
Wyzecam V2 running modified firmware. Was working fine for a few months then stopped working. When I connect to it, the admin panel appears malformed and none of the links work. I've tried re-partitioning the SD card, using a different SD card, and reflashing the bootloader. Every time I get the same resulting admin panel, which leads me to believe the issue is with the camera and not the firmware or SD card. Any thoughts?

![dafang](https://user-images.githubusercontent.com/1285519/146660830-26924e5a-1928-42cc-afcc-b9aefaa45ede.jpg)
[startup.log](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/files/7740212/startup.log)
[wifi.log](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/files/7740213/wifi.log)

**Comment by kram12085** [comment]
> Is your camera daisy-chained, using an extra-long power lead or a power supply of less than 1A? Sometimes issues displaying the web interface and accessing the device via ssh can be due to low power.

Nope, plugged in directly to an outlet with the OEM cable and adapter. The only options I can think of is maybe corrupted SD card or firmware, even though nothing stands out (to me at least) in the logs.

**Comment by vswee** [comment]
In case you haven't tried it; ssh-ing into the device and running `/system/sdcard/autoupdate.sh` can often sort out a myriad of firmware issues.

**Comment by kram12085** [comment]
> In case you haven't tried it; ssh-ing into the device and running `/system/sdcard/autoupdate.sh` can often sort out a myriad of firmware issues.

What fixed it was reformatting a different SD card and adding the mod firmware. What's odd is it took a couple of tries with two different cards, would get the same result making a 512 MB partition. I finally gave up and reformatted the card as 16 GB and that's what fixed it. I'm not sure if it's a faulty SD card or touchy system.
