### ISSUE TITLE
Power consumption increases after installing CFW 

### ISSUE THREAD

**Issue by whuang1965** [EliasKotlyar/Xiaomi-Dafang-Hacks#18]
When running on the latest official firmware 5.5.1.200, the power consumption, when its idle, i.e., no viewing nor tracking movement, is around 1.7 - 1.8 watts.

After installing the latest CFW firmware, cfw-1.1.bin, the power consumption is around 2.2 - 2.3 watts.  From the top command, the idle time is almost 0.  This measurement was taken 15 minutes after power on.

That's more than a quarter power consumption increased.

**Comment by EliasKotlyar** [comment]
Hello @whuang1965,

Thanks for your report. I suspect that there is some process/driver which is taking so much power. Also the CFW-1.1 is based on the firmware 5.5.1.177 which may include an older kernel. I have released a CFW-1.2 which is based on the 5.5.200 Firmware. I hope that it will consume lesser power. Can you please update and measure again?

Many thanks
Greating
Elias

**Comment by whuang1965** [comment]
@EliasKotlyar 

Thanks for the new firmware, really appreciate your effort and time to make this thing working. 

Just had a chance to install the latest CFW, cfw-1.2.bin, and did the measurement with the same condition in my previous post.  The power consumption is around 2.0 - 2.1 watts.  There is a noticeable improvement.  From the top command, the idle is still almost 0% and nice uses up all the CPU time.

Mem: 30688K used, 68952K free, 0K shrd, 2944K buff, 10492K cached
CPU:  0.0% usr  1.6% sys  0.0% nic 98.3% idle  0.0% io  0.0% irq  0.0% sirq
Load average: 2.30 2.31 2.40 1/55 219

BTW, [Kill A Watt model P4482] is used for the power measurement.

Regards,
Wade

**Comment by sharkoz** [comment]
@whuang1965 I beleive you are reading it wrong, here is how you should read the top result : .

>  CPU: 
> 0.0% usr
> 1.6% sys
> 0.0% nic 
> 98.3% idle
> 0.0% io 
> 0.0% irq 
> 0.0% sirq

So your CPU is 98.3% idle which is very reasonable :smile: 
nic represents the low priority processes, and is at 0%
Only the system is using 1.6% which is normal

**Comment by guteSeite** [comment]
If you use the motor the power consumption increases from 200mAh up to more than 1000mAh and it doesn't drop until reboot :-(

**Comment by EliasKotlyar** [comment]
There is some driver option to "reset" the motor:
https://github.com/EliasKotlyar/Xiaomi-Dafang-Software/blob/master/drivers/misc/sample_motor/motor.c

I suppose that it may decrease the power consuption.

**Comment by EliasKotlyar** [comment]
Hey,

I have intregrated a option to "stop" the motors:

Run it with following command(after you are done rotating)
```
/system/sdcard/bin/motor -d s
```

@guteSeite : Could you please have a test if this helps to decrease power consumption?

**Comment by dmolner** [comment]
@EliasKotlyar : I test the instruction but no change.
I have a 0.6A if move to right and 0.8A move to left, after move the consumption not decrease.
If I type the command 
`/system/sdcard/bin/motor -d s`
 the consumption is the same.
In the terminal I have the message
`Invalid Direction Argument`

**Comment by EliasKotlyar** [comment]
Hello dmolner,

You need to update to the latest firmware(only sdcard). This error means that you are using a old binary.

Greating

**Comment by guteSeite** [comment]
Hi Elias, it's great! With the command "motor -d s" after camera moving the amperage is back to 130 mAh. The lowest value I ever had!

**Comment by EliasKotlyar** [comment]
So yeah, its the motors which are causing the high demand on power. I hope it could resolve your issue.
