### ISSUE TITLE
Does is work with all hardware revisions?

### ISSUE THREAD

**Issue by kmplngj** [EliasKotlyar/Xiaomi-Dafang-Hacks#181]
Hello,

I just want to know if the hacks work with every hardware revision?

Thanks
Jan

**Comment by TheOncomingStorm** [comment]
Yeah, I'm interested in knowing this as well. Mine doesn't seem to be allowing flashing.

**Comment by jmtatsch** [comment]
There seems to be a new hardware revision where we have trouble with the motor endstops #287.
Please continue discussion there if you have an issue with that new hardware revision.

**Comment by jmtatsch** [comment]
Oh and there seem to be some issues with the newer original firmwares also #161

**Comment by Ridawis** [comment]
I have same problem, but don't know what i have todo :((
