### ISSUE TITLE
mqtt not responding

### ISSUE THREAD

**Issue by jongdesteven** [EliasKotlyar/Xiaomi-Dafang-Hacks#183]
I have configured the mqtt.dist file according to my information:
```
Options for mosquitto_sub & mosquitto_pub

USER=
PASS=
HOST=raspi
PORT=1883

TOPIC=home/dafang2/
```
But whatever i try, i dont get a message from the Dafang.
I have manually started a mosquitto_sub with the same topic on the dafang and that is receiving messages, but the mqtt-control or mqtt-status processes are silent.
`mosquitto_pub -h raspi -t home/dafang2/set -m status`
results in (on the dafang)
```
[root@Dafang2:config]# /system/sdcard/bin/mosquitto_sub -v -h raspi -t home/dafang2/#
home/dafang2/set status`
```
Because i'm not using the login on the mosquitto server. i even tried modifying the mqtt-control to remove the -u and -P

**Comment by jongdesteven** [comment]
found the issue: #172 removed the '#'

**Comment by wojtulab** [comment]
I've another issue:
```
/system/sdcard/bin/mosquitto_sub.bin -v -h 192.168.1.2
/system/sdcard/bin/mosquitto_sub.bin: can't load library 'libmosquitto.so.1'
```

**Comment by jongdesteven** [comment]
The mqtt-control.sh file is currently not working. roll it back to the previous version and it is working again.

**Comment by wojtulab** [comment]
oh i see... there is no listening on all subtopics topic/# but only one topic/

ok. thx

**Comment by msj33** [comment]
Anyone that can fix this?

I have tried to set up Mosquitto and Home Assistant:
1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890
1522192017: New connection from 192.168.1.151 on port 1883.                                                                                              
1522192017: Client mosqsub|208-StueCam already connected, closing old connection.                                                                        
1522192017: Client mosqsub|208-StueCam disconnected.                                                                                                     
1522192017: New client connected from 192.168.1.151 as mosqsub|208-StueCam (c1, k60, u'home').                                                           
1522192017: Sending CONNACK to mosqsub|208-StueCam (0, 0)                                                                                                
1522192017: Received SUBSCRIBE from mosqsub|208-StueCam                                                                                                  
1522192017:     LivingRoom/DaFang/ (QoS 0)                                                                                                               
1522192017: mosqsub|208-StueCam 0 LivingRoom/DaFang/                                                                                                     
1522192017: Sending SUBACK to mosqsub|208-StueCam  

I see the PINGREQ/PINGRESP nicely:
1522192078: Received PINGREQ from mosqsub|208-StueCam                                                                                                    
1522192078: Sending PINGRESP to mosqsub|208-StueCam   

but whatever I try to parse commands down to Dafang, they are never responded to in Mosquitto.

Example:
Mosquitto log:
1522191665: Received PUBLISH from 773ae23f-4978-4e69-8114-22995f555688 (d0, q0, r0, m0, 'LivingRoom/DaFang/set', ... (11 bytes)) 

Nothing happens more in the Mosquitto log.

Have the following config in my mqtt file(x=masked):
USER: xxx
PASS: xxx
HOST x.x.x.x
Port: xxx

Topic=LivingRoom/Dafang

**Comment by staudtm** [comment]
I have found something strange:
when calling "mqtt-status-interval.sh", I am getting the following error:

./mqtt-status-interval.sh
Error: Unknown option ''.
Use 'mosquitto_pub --help' to see usage.

Maybe someone is able to find the issue...

**Comment by tthk** [comment]
staudtm commented 2 days ago
> I have found something strange:
> when calling "mqtt-status-interval.sh", I am getting the following error:
>
> ./mqtt-status-interval.sh
> Error: Unknown option ''.
> Use 'mosquitto_pub --help' to see usage.

I got the same error, causing mqtt unable to report status.  Tracked it down to this line in mqtt-status-interval.sh:
```
 /system/sdcard/bin/mosquitto_pub.bin -h "$HOST" -u "$USER" -P "$PASS" -t "${TOPIC}"status "${MOSQUITTOOPTS}" "${MOSQUITTOPUBOPTS}" -m "$(/system/sdcard/scripts/mqtt-status.sh)"
```
Should be:
```
 /system/sdcard/bin/mosquitto_pub.bin -h "$HOST" -u "$USER" -P "$PASS" -t "${TOPIC}"status ${MOSQUITTOOPTS} ${MOSQUITTOPUBOPTS} -m "$(/system/sdcard/scripts/mqtt-status.sh)"
```
Once the double quotes around ${MOSQUITTOOPTS} and ${MOSQUITTOPUBOPTS} are removed, mqtt started reporting status.

**Comment by tthk** [comment]
Had to fix a bunch of errors in scripts/mqtt-control.sh to get mqtt subscription to work and be controlled by commands from mqtt publishers:
```
#!/bin/sh

source /system/sdcard/config/mqtt

# We're not using named pipes (FIFO), but rather pipe directly to while loop
#/bin/mknod "$FIFO" p 2>/dev/null

# next two lines are a little bit cruel
killall mosquitto_sub 2> /dev/null
killall mosquitto_sub.bin 2> /dev/null

export LD_LIBRARY_PATH='/thirdlib:/system/lib:/system/sdcard/lib'

/system/sdcard/bin/mosquitto_sub.bin -v -h "$HOST" -u "$USER" -P "$PASS" -t "${TOPIC}"# | while read -r line ; do
  case $line in
    "${TOPIC}set help")
      /system/sdcard/bin/mosquitto_pub.bin -h "$HOST" -u "$USER" -P "$PASS" -t "${TOPIC}"help ${MOSQUITTOOPTS} -m "possible commands: configured topic + Yellow_LED/set on/off, configured topic + Blue_LED/set on/off, configured topic + set with the following commands: status, $(grep \)$ /system/sdcard/www/cgi-bin/action.cgi | grep -v '[=*]' | sed -e "s/ //g" | grep -v -E '(osd|setldr|settz|showlog)' | sed -e "s/)//g")"
    ;;

    "${TOPIC}set status")
      # Publish updated states
      /system/sdcard/bin/mosquitto_pub.bin -h "$HOST" -u "$USER" -P "$PASS" -t "${TOPIC}"status ${MOSQUITTOPUBOPTS} ${MOSQUITTOOPTS} -m "$(/system/sdcard/scripts/mqtt-status.sh)"
    ;;

    "${TOPIC}Blue_LED/set on")
      /system/sdcard/bin/curl -m 2 ${CURLOPTS} -s http://127.0.0.1/cgi-bin/action.cgi\?cmd=blue_led_on -o /dev/null 2>/dev/null
      # Publish updated states
      /system/sdcard/bin/mosquitto_pub.bin -h "$HOST" -u "$USER" -P "$PASS" -t "${TOPIC}"status ${MOSQUITTOPUBOPTS} ${MOSQUITTOOPTS} -m "$(/system/sdcard/scripts/mqtt-status.sh)"
    ;;

    "${TOPIC}Blue_LED/set off")
      /system/sdcard/bin/curl -m 2 ${CURLOPTS} -s http://127.0.0.1/cgi-bin/action.cgi\?cmd=blue_led_off -o /dev/null 2>/dev/null
      # Publish updated states
      /system/sdcard/bin/mosquitto_pub.bin -h "$HOST" -u "$USER" -P "$PASS" -t "${TOPIC}"status ${MOSQUITTOPUBOPTS} ${MOSQUITTOOPTS} -m "$(/system/sdcard/scripts/mqtt-status.sh)"
    ;;

    "${TOPIC}Yellow_LED/set on")
      /system/sdcard/bin/curl -m 2 ${CURLOPTS} -s http://127.0.0.1/cgi-bin/action.cgi\?cmd=yellow_led_on -o /dev/null 2>/dev/null
      # Publish updated states
      /system/sdcard/bin/mosquitto_pub.bin -h "$HOST" -u "$USER" -P "$PASS" -t "${TOPIC}"status ${MOSQUITTOPUBOPTS} ${MOSQUITTOOPTS} -m "$(/system/sdcard/scripts/mqtt-status.sh)"
    ;;

    "${TOPIC}Yellow_LED/set off")
      /system/sdcard/bin/curl -m 2 ${CURLOPTS} -s http://127.0.0.1/cgi-bin/action.cgi\?cmd=yellow_led_off -o /dev/null 2>/dev/null
      # Publish updated states
      /system/sdcard/bin/mosquitto_pub.bin -h "$HOST" -u "$USER" -P "$PASS" -t "${TOPIC}"status ${MOSQUITTOPUBOPTS} ${MOSQUITTOOPTS} -m "$(/system/sdcard/scripts/mqtt-status.sh)"
    ;;

    "${TOPIC}set "*)
      COMMAND=$(echo "$line" | awk '{print $2}')
      #echo "$COMMAND"
      /system/sdcard/bin/curl -m 2 ${CURLOPTS} -s http://127.0.0.1/cgi-bin/action.cgi\?cmd="${COMMAND}" -o /dev/null 2>/dev/null
      if [ $? -eq 0 ]; then
        /system/sdcard/bin/mosquitto_pub.bin -h "$HOST" -u "$USER" -P "$PASS" -t "${TOPIC}${COMMAND}" ${MOSQUITTOOPTS} -m "OK (this means: action.cgi invoke with parameter ${COMMAND}, nothing more, nothing less)"
      else
        /system/sdcard/bin/mosquitto_pub.bin -h "$HOST" -u "$USER" -P "$PASS" -t "${TOPIC}error" ${MOSQUITTOOPTS} -m "An error occured when executing ${line}"
      fi
      # Publish updated states
      /system/sdcard/bin/mosquitto_pub.bin -h "$HOST" -u "$USER" -P "$PASS" -t "${TOPIC}"status ${MOSQUITTOPUBOPTS} ${MOSQUITTOOPTS} -m "$(/system/sdcard/scripts/mqtt-status.sh)"
    ;;
  esac
done
```

**Comment by jmtatsch** [comment]
@tthk could you please be a little bit more specific on what needed fixing and maybe even consider whipping up a pull request?

**Comment by msj33** [comment]
I'm verfying the fix on my end with Mosquitto broker as we speak:-)

**Comment by msj33** [comment]
Yep, this does actually make MQTT work/respond :-)

1522406120: New connection from 192.168.1.x on port x.                                                                                                                                     
1522406120: New client connected from 192.168.1.x as mosqpub|1031-StueCam (c1, k60, u'home').                                                                                                 
1522406120: Sending CONNACK to mosqpub|1031-StueCam (0, 0)                                                                                                                                      
1522406120: Received PUBLISH from mosqpub|1031-StueCam (d0, q0, r0, m0, 'LivingRoom/DaFang/motor_down', ... (88 bytes))                                                                         
1522406120: Sending PUBLISH to mosqsub|206-StueCam (d0, q0, r0, m0, 'LivingRoom/DaFang/motor_down', ... (88 bytes))                                                                             
1522406120: Received DISCONNECT from mosqpub|1031-StueCam                                                                                                                                       
1522406120: Client mosqpub|1031-StueCam disconnected.                                                                                                                                           
1522406120: New connection from 192.168.1.x on port x.                                                                                                                                     
1522406120: New client connected from 192.168.1.x as mosqpub|1072-StueCam (c1, k60, u'home').                                                                                                 
1522406120: Sending CONNACK to mosqpub|1072-StueCam (0, 0)                                                                                                                                      
1522406120: Received PUBLISH from mosqpub|1072-StueCam (d0, q0, r0, m0, 'LivingRoom/DaFang/status', ... (290 bytes))                                                                            
1522406120: Sending PUBLISH to mosqsub|206-StueCam (d0, q0, r0, m0, 'LivingRoom/DaFang/status', ... (290 bytes))                                                                                
1522406120: Sending PUBLISH to 7cdc5d3d-60e9-458c-836c-8c50d2722092 (d0, q0, r0, m0, 'LivingRoom/DaFang/status', ... (290 bytes))                                                               
1522406120: Received DISCONNECT from mosqpub|1072-StueCam                                                                                                                                       
1522406120: Client mosqpub|1072-StueCam disconnected.                        

Only concerning thing is, that I no see constant connections spawning for status

1522406297: New client connected from 192.168.1.x as mosqpub|1476-StueCam (c1, k60, u'home').                                                                                                 
1522406297: Sending CONNACK to mosqpub|1476-StueCam (0, 0)                                                                                                                                      
1522406297: Received PUBLISH from mosqpub|1476-StueCam (d0, q0, r0, m0, 'LivingRoom/DaFang/status', ... (291 bytes))                                                                            
1522406297: Sending PUBLISH to mosqsub|206-StueCam (d0, q0, r0, m0, 'LivingRoom/DaFang/status', ... (291 bytes))                                                                                
1522406297: Sending PUBLISH to c91db634-1264-4c5a-8d96-10ca94ced470 (d0, q0, r0, m0, 'LivingRoom/DaFang/status', ... (291 bytes))                                                               
1522406297: Received DISCONNECT from mosqpub|1476-StueCam                                                                                                                                       
1522406297: Client mosqpub|1476-StueCam disconnected.                                                                                                                                           

And again 30 seconds later
1522406327: New connection from 192.168.1.x on port x.                                                                                                                                     
1522406327: New client connected from 192.168.1.x as mosqpub|1545-StueCam (c1, k60, u'home').                                                                                                 
1522406327: Sending CONNACK to mosqpub|1545-StueCam (0, 0)                                                                                                                                      
1522406327: Received PUBLISH from mosqpub|1545-StueCam (d0, q0, r0, m0, 'LivingRoom/DaFang/status', ... (291 bytes))                                                                            
1522406327: Sending PUBLISH to mosqsub|206-StueCam (d0, q0, r0, m0, 'LivingRoom/DaFang/status', ... (291 bytes))                                                                                
1522406327: Sending PUBLISH to c91db634-1264-4c5a-8d96-10ca94ced470 (d0, q0, r0, m0, 'LivingRoom/DaFang/status', ... (291 bytes))                                                               
1522406327: Received DISCONNECT from mosqpub|1545-StueCam                                                                                                                                       
1522406327: Client mosqpub|1545-StueCam disconnected.            

Is this right behaviour? Why not just use PINGREQ/PINGRESP for status?
1522406628: Received PINGREQ from mosqsub|206-StueCam                                                                                                                                           
1522406628: Sending PINGRESP to mosqsub|206-StueCam

This can in my opinion be committed to Master, hence it is an improvement over existing functionality of MQTT.

/Morten

**Comment by tthk** [comment]
msj33 commented 14 hours ago
> Is this right behaviour? Why not just use PINGREQ/PINGRESP for status?
> 1522406628: Received PINGREQ from mosqsub|206-StueCam
> 1522406628: Sending PINGRESP to mosqsub|206-StueCam

I'm just getting into mqtt, but it looks like the way mqtt publishings are done in this instance is via the short running /system/sdcard/bin/mosquitto_pub.bin script, which can't keep a connection alive unless some daemon was implemented.

**Comment by tthk** [comment]
@jmtatsch commented 15 hours ago
> @tthk could you please be a little bit more specific on what needed fixing and maybe even consider whipping up a pull request?

I'm also just getting into contributing to github.  I'll do a pull request, but feel free to apply the fixes if I'm too slow getting it done.
