### ISSUE TITLE
Minor source flaws found

### ISSUE THREAD

**Issue by centralware** [EliasKotlyar/Xiaomi-Dafang-Hacks#1833]
I've been having an issue with Wyz**e** v2 and PAN running with ONVIF and for unknown reasons (lack of research on my part - which is what I'm doing right now) the ONVIF service stops running, usually days of uninterrupted service, so I was going to write a watch-dog script for boot time to keep an eye on things and properly terminate and restart vital services should they crash, reboot the device if resources are unrecoverable, etc. and I came across little quirks thus far which likely should be remedied within the repo when time permits:

**/system/sdcard/controlscripts/common_functions.sh**
* refers to **onvif-srvd.sh** whereas the filename in ./scripts does not contain a file extension **(.sh)**
(There's likely a reference to this in the web interface as the start/stop switch never _detects_ onvif running, but DOES start/stop the service when it's clicked on.)
* refers to **mqtt_control** whereas the filename in ./scripts is **mqtt-control** (dash)
* There have been numerous "issues" over the years regarding PAN motor control being "lost" (ONVIF running)
A quick and cheesy fix to have both UI control AND ONVIF control of the motors could be: 
```
motor(){
  ov=$(onvif_srvd status)
  [ "${ov}" == "ON" ] && onvif_srvd off
```
...and at the end of the function, turn ONVIF back on:
```
  esac
  [ "${ov}" == "ON" ] && onvif_srvd on
}
```
This way, if the UI is clicked on it "takes control" of the motor functions for a moment, does what it needs to and returns control to ONVIF afterward, which takes so little time it's unlikely to interfere with normal operations.  It hasn't been thoroughly tested with calibration, etc. so no guarantee this method is fool-proof for **every** scenario, but it works for what I've tested with thus far.

### Added Suggestions: ###
DAFANG is an awesome CFW/FW replacement and tiny glitches like those above are well worth the tiny efforts required to put things where they belong; the only real vulnerability I've noticed over the years would be the SD CARD itself and how easily it can become glitched due to its R/W state.  A possible fix for this would be to remount SD as Read Only for normal operations and if set up the way we do, the OS is dedicated with the first 256MB to 512MB of the SD card and mmcblk0p2 (vfat) is mounted at DCIM for the remainder of the card where a copy of sdcard/config is double-backed-up, where updates are performed, etc.  If blk0p1 were R.O. from the start, this should reduce the risk of **OS** corruption (config remains vulnerable, but fix-able via backups whereas if partition 1 becomes corrupt, the card needs to be removed and re-flashed.)  Even if the entire second partition was un-readable the operating system is still likely to survive and can be recovered.  REMOTELY, without a ladder! :^)

Out of 283 v2/PAN cameras we installed/tested in 2022, more than half (156) had to be re-flashed already (at least once) due to power glitches/outages causing card corruption (yellow LED remains lit during boot and hangs.)

**It may also be worthwhile to add kernel and tool support for EXT(2) and SYNC.**
* Being able to format mmcblk0p2 as EXT (without journaling due to flash memory) would open the door to linux permissions ON the card making it (potentially) more useful for the core.
* Being able to flush the file system (sync) could come in handy and help maintain FS cleanliness.

Again, many kudos and Happy Holidays!

**Comment by jmtatsch** [comment]
Thanks for tracking those issues down. Could you please do a pull request?

**Comment by centralware** [comment]
I'll be doing a bit more than a pull; likely after the holidays I should be done as I need some of these changes "live" on my end by year's end.  I'll send a link (dafang repo _clone_) with a list of before/after changes and notes and the DAFANG members can pick and choose what should be implemented globally.  (For example, we updated the web interface to include smaller video resolutions (320x180 to name one) to allow a large number of cameras to stream to a single DVR/NVR without hogging up bandwidth...  something DAFANG may have no need or interest in if it doesn't affect the global scale of things.)  Things we have notes on but HAVE NOT yet implemented...  who knows, maybe the DAFANG team may take interest and join in; we'll see!
