### ISSUE TITLE
Unable to discover through Zigbee2MQTT in Home Assistant

### ISSUE THREAD

**Issue by timothe** [EliasKotlyar/Xiaomi-Dafang-Hacks#1837]
### Description
I flashed my Neos Smartcam with success. I can confirm I have access to the Web UI, SSH, and I can see the camera with its stream in Home Assistant, using the Generic IP Camera integration.

I want to be able to get all the sensors and actions in HA, as illustrated in the HA guide:
![image](https://user-images.githubusercontent.com/6997555/213923003-0bb2fd13-32a9-4c3b-9580-668972a3bf97.png)

I have other Zigbee devices (switches) detected through the MQTT moquitto broker and Zigbee2MQTT. This is 100% working.

There's no discovery / pairing for the camera. My switches were detected after I permitted devices in Zigbee2MQTT.
I can't find the camera and all its sensors. I would like to use it to create automation on motion detection, etc.

Debugging this issue could help improving the documentation. 

### What did you do to debug the issue

* I modified the dafang config to connect to my local HA server, homeassistant.local. I also tried core-mosquitto, as it's used by Zigbee2MQTT
* I restarted the dafang camera, got it off and on again, restarted services
* I restarted HA, checked the config, user access

### Evidence

<img width="287" alt="Screenshot 2023-01-22 at 15 21 08" src="https://user-images.githubusercontent.com/6997555/213923736-c6995445-8d58-434c-9a67-b29effe6e9fe.png">

<img width="1014" alt="Screenshot 2023-01-22 at 15 21 32" src="https://user-images.githubusercontent.com/6997555/213923750-4abf8d40-e69d-4e1d-8db1-901ffe1f7d84.png">

<img width="482" alt="Screenshot 2023-01-22 at 15 22 09" src="https://user-images.githubusercontent.com/6997555/213923786-f745468f-258c-401b-b586-ab66e4b343a7.png">

<img width="595" alt="Screenshot 2023-01-22 at 15 33 02" src="https://user-images.githubusercontent.com/6997555/213924355-87af05f5-9a55-4880-a8b7-1971b1eabe76.png">

There's no trace of connection, successful or not, in the logs.

**Comment by olegskod** [comment]
Same problem/ Can't connect to MQTT

**Comment by timothe** [comment]
I solved that issue by doing the below (not sure which one was missing tbh):
* put the user credentials directly in the yaml of the mosquitto broker
* added `listener: 1883`
* added `allow_anonymous: true`
* changed the host for the IP address of the VM

Hope that will help someone!
