### ISSUE TITLE
Is the source for setconf available?

### ISSUE THREAD

**Issue by dbuezas** [EliasKotlyar/Xiaomi-Dafang-Hacks#1849]
My camera's microphone has such a bad signal to noise ratio that I wanted to take a look at any other hidden tricks available.

Thank you for this project, very fun to explore.

**Comment by jmtatsch** [comment]
https://github.com/EliasKotlyar/Xiaomi-Dafang-Software/blob/master/v4l2rtspserver-tools/setconf.cpp

**Comment by dbuezas** [comment]
Oh, wow, the rabbit hole deepens :)
