### ISSUE TITLE
HLS stream not working properly

### ISSUE THREAD

**Issue by gysmo38** [EliasKotlyar/Xiaomi-Dafang-Hacks#185]
Hello,

I try to enhance the liveview UI. I would like to integrate hls stream in html5 page.

I made some test, it is not working now. I am able to get it work if I add -S 30 (or 25) to v4l2rtspserver-master command.

It work but my live view have a lot of delay. If I move, it take more than 10 secondes to show on stream. If I move the camera it take 10 secondes to move on the video.

If someone have a clue of what happen...

**Comment by jmtatsch** [comment]
@gysmo38 I would also be very interested in this.
Can you please post a code snippet of your html5 page?
In which browsers did you get it to run?
I didn't have any luck to get mine running in safari, firefox & chrome :(

**Comment by gysmo38** [comment]
Hello,
For Chrome you can use a plugin: Native HLS Playback.
I also try with an embeded player, it work for Firefox with this code:

`<script src="https://cdn.jsdelivr.net/npm/hls.js@latest"></script>
<video id="video" width="640" height="400" ></video>
<script>
  if(Hls.isSupported()) {
    var video = document.getElementById('video');
    var hls = new Hls();
    hls.loadSource('http://CHANGE_WITH_YOUR_HOST_OR_IP:8554/unicast.m3u8');
    hls.attachMedia(video);
    hls.on(Hls.Events.MANIFEST_PARSED,function() {
      video.play();
  });
 }
</script>`

It not work directly, you need to stop v4l2rtspserver-master and start it with option -S 30 but there is a lot of delay. If someone have an idea to get it work...

**Comment by jmtatsch** [comment]
I seem to get a lot of same origin issues:

[Error] Origin http://dafanghacks is not allowed by Access-Control-Allow-Origin.
[Error] Failed to load resource: Origin http://dafanghacks is not allowed by Access-Control-Allow-Origin. (unicast.m3u8, line 0)
[Error] XMLHttpRequest cannot load http://dafanghacks:8554/unicast.m3u8 due to access control checks.

Also i am not even able to just curl the playlist.

**Comment by gysmo38** [comment]
Have you try to start the server like this: /system/sdcard/bin/v4l2rtspserver-master -S 30 ?

**Comment by jmtatsch** [comment]
Closed via 668558f, need to set -S flag manually though.
