### ISSUE TITLE
rtsp-h264 NOK autostart

### ISSUE THREAD

**Issue by wojtulab** [EliasKotlyar/Xiaomi-Dafang-Hacks#186]
Hello,
I noticed that rtsp-h264 can't start in autostart.
After manual STOP&START it's wokring normally.

After boot:
![image](https://user-images.githubusercontent.com/14801148/37912784-879bfc2a-3113-11e8-8e77-fe78fc3a6a51.png)
![image](https://user-images.githubusercontent.com/14801148/37912796-912028b6-3113-11e8-86fa-858e4afed048.png)

After Start & Stop:
![image](https://user-images.githubusercontent.com/14801148/37912876-c1ef1dda-3113-11e8-9fe7-5ef77c67ef53.png)
![image](https://user-images.githubusercontent.com/14801148/37912887-c8350b6e-3113-11e8-9dbd-a33ff68feb8a.png)

as you can see in both examples the process are running but the status is wrong

**Comment by tthk** [comment]
The v4l2rtspserver-master is started in run.sh:
```
#Start
/system/sdcard/bin/busybox nohup /system/sdcard/bin/v4l2rtspserver-master -S &>/dev/null &
```
If these lines are changed to:
```
#Start
/system/sdcard/controlscripts/rtsp-h264 start
```
then this problem will go away.  Additionally, any customizations to the rtsp-h264 command can be localized in one place: controlscripts/rtsp-h264 

I'll open a pull request for this fix.  Let me know if this is the proper way to contribute fixes.

**Comment by tthk** [comment]
Took some tries but I think I created the pull request for just this fix properly.

**Comment by jmtatsch** [comment]
should be fixed thanks to @tthk, please re-open if not
