### ISSUE TITLE
Feature request: Google Drive autoupload

### ISSUE THREAD

**Issue by markwain** [EliasKotlyar/Xiaomi-Dafang-Hacks#188]
Hi there!
First of all thanks for the good work you guys are doing here :)

I would be very good to have the possibility to auto upload recording from the cam to google drive. Can we do that?
I can even write the code myself, if you will be able to provide me proper guidance

**Comment by shinebar1001** [comment]
It should be possible to upload the files with cURL and the GoogleDrive API: https://developers.google.com/drive/v3/web/simple-upload

**Comment by markwain** [comment]
Can you provide more information on this ...?

**Comment by markwain** [comment]
How can I do curl available in the OS of Dafang?

**Comment by leonidas2522** [comment]
Interesting.
