### ISSUE TITLE
HTTP MJPEG Support

### ISSUE THREAD

**Issue by jbeck22** [EliasKotlyar/Xiaomi-Dafang-Hacks#19]
Is there any way to get http mjpeg support working?

**Comment by EliasKotlyar** [comment]
Yeah, i am trying to make it work trough compiling the 
https://github.com/mpromonet/v4l2rtspserver

For now its breaking down every time i am starting it.

**Comment by sharkoz** [comment]
MJPEG stream is kinda working for me, but unfortunately today it is set to run at 640*480 px, and so it crops the picture to only show the top left corner of the image.

I tried launching : 
`/system/sdcard/bin/v4l2rtspserver-master -fMJPG -W 1920 -H 1080`

But then I have cropped frames and the following error message : 

```
Frame1(): The input frame data was too large for our buffer size (61000).  117315 bytes of trailing data was dropped!  Correct this by increasing "OutPacketBuffer::maxSize" to at least 177315, *before* creating this 'RTPSink'.  (Current value is 60000.)
MultiFramedRTPSink::afterGettingFrame1(): The input frame data was too large for our buffer size (61000).  117053 bytes of trailing data 
```

Any way around this ?

**Comment by EliasKotlyar** [comment]
Hello sharkoz,

I increased the buffersize. Now it should work.

Greatings
Elias

**Comment by MasterPIC** [comment]
Still not able to get 1920x1080 resolution working.

**Comment by EliasKotlyar** [comment]
@MasterPIC Could you please describe what exactly is not working?

**Comment by MasterPIC** [comment]
Occasionally the frame is at 1920x1080 (and reported codec, resolution , and decoded format are right); generally the frame is not complete (typically the first rows are right) and VLC doesn't report any codec detail.
In any case I can see just one frame (by VLC).

**Comment by EliasKotlyar** [comment]
Okey, i increased some Buffers. Can you please try again? @MasterPIC

**Comment by hubmon** [comment]
@MasterPIC  is this issue resolved?
Am still having issues with MJEG streaming.

**Comment by khseal** [comment]
v4l2rtspserver can mjeg routed in http?
There is a flag -p port: RTSP over HTTP port (default 0)
But it does not seem to work?

**Comment by EliasKotlyar** [comment]
I suppose that this topic is already obsolete, due to the fact that its now possible to get a JPEG-Picture and a H264 Stream on the same time. If not - feel free to open it up again.

**Comment by xPRozAcx** [comment]
Please open up this topic again, because most home automation systems can not use h264.
Fibaro as example only support mjpeg over http.
Can you please help out with this limitation?

**Comment by shinebar1001** [comment]
you can change the stream to mjpeg - would that help you?

**Comment by xPRozAcx** [comment]
I tried with v4l2rtspserver-master -p 8080 -fMJPG -W 640 -H 480 but can not connect through the http stream via vlc

**Comment by xPRozAcx** [comment]
I still can connect with rtsp instead of http on port 8080

**Comment by Seraf** [comment]
Hello @xPRozAcx, I also have a Fibaro, did you success to make it working ?
Right now, I'm using the cgi-bin/currentpicoptim.cgi endpoint to get a snapshot but it's not really nice ...

**Comment by DifferentComputers** [comment]
"its now possible to get a JPEG-Picture " Could someone point to the docs on how to do this? RTSP will not work for me. I need a snapshot. I don't see any documentation on what url to access for a snapshot, or what needs to be enabled for the camera to take snapshots.

Nor do I see anything about how to authenticate when grabbing an image.

**Comment by crackers8199** [comment]
can someone re-open this? h264 is extremely unreliable across a VPN, the only way i've been able to get my cameras viewable via tinycam across vpn is by re-streaming to MJPEG.
