### ISSUE TITLE
Boot time till RTSP?

### ISSUE THREAD

**Issue by naitsimp** [EliasKotlyar/Xiaomi-Dafang-Hacks#190]
Hi,

What is the boot time till RTSP is available?
My plan is to use a MCU to detect Motion, if one is detected the Dafang gets powered on and Home Assistant sends me the first picture to my phone. 
Thanks

**Comment by jmtatsch** [comment]
@naitsimp That will take around 30 seconds and your motion will be long gone. Why don't you use the internal motion recognition of the dafang?
