### ISSUE TITLE
New Motion service with Xiaomi Motion Tracking

### ISSUE THREAD

**Issue by bizzul** [EliasKotlyar/Xiaomi-Dafang-Hacks#195]
Hi,

It's possibile to integrate the cool features "motion tracking" that is in the stock xiaomi version, in the new motion implemented?

Obviously it will not work with a selected zone, but it could be possibile if all the area is selected, when there is motion send a motor signal to follow the motion (pixel changing).

**Comment by nik0** [comment]
Can you explain a bit more what the original app do?
In the motion API you can have 4 regions that detect motion. And the API return only true if a motion is detected ...

**Comment by jmtatsch** [comment]
Do we get something like x and y velocity of the detected motion?
The original app uses this information to move the camera so that the moving object stays in the cameras view. This would be a really cool feature for the modded fw 👍

**Comment by nik0** [comment]
We get just motion on/off
I think twice of this stuff, what we can do is to define the 4 detections regions to the corner of the image.
If all area detect motion: no movement
if the top left detect motion: move top and left 
if the top left and bottom right detect motion: move left 
etc ...
It is easily feasible, I won't have much time this weekend but I'll try it ...

**Comment by bizzul** [comment]
Yes I think its the easiest solution, for the motion output its not so usefull, but  for recording when there is motion to follow: motion sensor + move camera its cool.

Thanks!

**Comment by nik0** [comment]
I did an experimental version (that seems to work)
See the MotionTracking branch on my fork: https://github.com/nik0/Xiaomi-Dafang-Hacks.git
You need the v4l2master binary + the new script: script/detectionTracking.sh

The source are also on my fork repo  (branch MotionTracking): https://github.com/nik0/Xiaomi-Dafang-Software.git

**Comment by bizzul** [comment]
Hi! Thanks for the work!

I have the two files in the sd card. But it does not work.

I had to draw the 4 zones in the config motion??

Thanks again!

**Comment by nik0** [comment]
The zones is not anymore active. They are automatically configured to split the screen in 4
Start the server manually and show me the traces

**Comment by bizzul** [comment]
Sorry for the dump question,
I need in the terminal start the service v4l2rtspserver-master?

**Comment by nik0** [comment]
Yes ! On a terminal you need first to kill the previous instance of the server:
`pkill v4l2rtspserver-master`
then restart v4l2rtspserver-master with the parameter you use.
You can also try 
`chmod +x /system/sdcard/scripts/detectionTracking.sh`

**Comment by bizzul** [comment]
Here is the trace: 

```
[root@DAFANGBEDROOM:bin]# pkill v4l2rtspserver-master
[root@DAFANGBEDROOM:bin]# chmod +x /system/sdcard/scripts/detectionTracking.sh
[root@DAFANGBEDROOM:bin]# ./v4l2rtspserver-master
i264e[info]: profile Constrained Baseline, level 3.1

[NOTICE] /home/osboxes/SRC/Xiaomi-Dafang-Software/v4l2rtspserver-master/src/ImpEncoder.cpp:146
        OSD pos 0,0,1279,36

[NOTICE] /home/osboxes/SRC/Xiaomi-Dafang-Software/v4l2rtspserver-master/src/ImpEncoder.cpp:146
        OSD pos 1240,0,1279,39
Changed OSD
Display motion OSD color=2

[NOTICE] /home/osboxes/SRC/Xiaomi-Dafang-Software/v4l2rtspserver-master/src/main.cpp:646
        Create ALSA Source.../dev/dsp
[NOTICE] /home/osboxes/SRC/Xiaomi-Dafang-Software/v4l2rtspserver-master/src/ALSACapture.cpp:51
        Open ALSA device: "/dev/dsp"
[NOTICE] /home/osboxes/SRC/Xiaomi-Dafang-Software/v4l2rtspserver-master/src/DeviceSource.cpp:87
        begin thread
[NOTICE] /home/osboxes/SRC/Xiaomi-Dafang-Software/v4l2rtspserver-master/src/ALSACapture.cpp:68
        LAME 3.100 32bits (http://lame.sf.net)
Using polyphase lowpass filter, transition band: 16538 Hz - 17071 Hz
Channel Count:1
[NOTICE] /home/osboxes/SRC/Xiaomi-Dafang-Software/v4l2rtspserver-master/src/main.cpp:151
        Play this stream using the URL "rtsp://192.168.2.244:8554/unicast"

[NOTICE] /home/osboxes/SRC/Xiaomi-Dafang-Software/v4l2rtspserver-master/src/DeviceSource.cpp:87
```

**Comment by nik0** [comment]
correct
and if you wait a couple of minute ? I guess the first frames are dropped

**Comment by bizzul** [comment]
Yes Im moving, but no tracking.

I had try to copy all your source hack mod, but still not start the Tracking in the log.

**Comment by nik0** [comment]
And with the old version of the server it is working ? What are the traces ?

**Comment by bizzul** [comment]
With the original v4l2rtspserver-master by Elias not work, this is the trace:

` pkill v4l2rtspserver-master
[root@DAFANGBEDROOM:bin]# ./v4l2rtspserver-master
i264e[info]: profile Constrained Baseline, level 3.1

[NOTICE] /home/osboxes/SRC/Xiaomi-Dafang-Software/v4l2rtspserver-master/src/ImpEncoder.cpp:145
        OSD pos 0,0,1279,36

[NOTICE] /home/osboxes/SRC/Xiaomi-Dafang-Software/v4l2rtspserver-master/src/ImpEncoder.cpp:145
        OSD pos 1240,0,1279,39
Changed OSD

[NOTICE] /home/osboxes/SRC/Xiaomi-Dafang-Software/v4l2rtspserver-master/src/ImpEncoder.cpp:588
        Detection region= ((0,0)-(1279,719))
Changed motion region
Display motion OSD color=2

[NOTICE] /home/osboxes/SRC/Xiaomi-Dafang-Software/v4l2rtspserver-master/src/main.cpp:646
        Create ALSA Source.../dev/dsp
[NOTICE] /home/osboxes/SRC/Xiaomi-Dafang-Software/v4l2rtspserver-master/src/ALSACapture.cpp:51
        Open ALSA device: "/dev/dsp"
[NOTICE] /home/osboxes/SRC/Xiaomi-Dafang-Software/v4l2rtspserver-master/src/DeviceSource.cpp:87
        begin thread
[ERROR] /home/osboxes/SRC/Xiaomi-Dafang-Software/v4l2rtspserver-master/src/ALSACapture.cpp:68
        LAME 3.100 32bits (http://lame.sf.net)
Using polyphase lowpass filter, transition band: 16538 Hz - 17071 Hz
Channel Count:1
[NOTICE] /home/osboxes/SRC/Xiaomi-Dafang-Software/v4l2rtspserver-master/src/main.cpp:151
        Play this stream using the URL "rtsp://192.168.2.244:8554/unicast"

[NOTICE] /home/osboxes/SRC/Xiaomi-Dafang-Software/v4l2rtspserver-master/src/DeviceSource.cpp:87
        begin thread
[NOTICE] /home/osboxes/SRC/Xiaomi-Dafang-Software/v4l2rtspserver-master/src/ImpEncoder.cpp:646
        Detect !!

[NOTICE] /home/osboxes/SRC/Xiaomi-Dafang-Software/v4l2rtspserver-master/src/ImpEncoder.cpp:656
        Detect finished!!

[NOTICE] /home/osboxes/SRC/Xiaomi-Dafang-Software/v4l2rtspserver-master/src/ImpEncoder.cpp:646
        Detect !!

[NOTICE] /home/osboxes/SRC/Xiaomi-Dafang-Software/v4l2rtspserver-master/src/ImpEncoder.cpp:656
        Detect finished!!

[NOTICE] /home/osboxes/SRC/Xiaomi-Dafang-Software/v4l2rtspserver-master/src/ImpEncoder.cpp:646
        Detect !!

[NOTICE] /home/osboxes/SRC/Xiaomi-Dafang-Software/v4l2rtspserver-master/src/ImpEncoder.cpp:656
        Detect finished!!

[NOTICE] /home/osboxes/SRC/Xiaomi-Dafang-Software/v4l2rtspserver-master/src/ImpEncoder.cpp:646
        Detect !!

[NOTICE] /home/osboxes/SRC/Xiaomi-Dafang-Software/v4l2rtspserver-master/src/ImpEncoder.cpp:656
        Detect finished!!

[NOTICE] /home/osboxes/SRC/Xiaomi-Dafang-Software/v4l2rtspserver-master/src/ImpEncoder.cpp:646
        Detect !!

[NOTICE] /home/osboxes/SRC/Xiaomi-Dafang-Software/v4l2rtspserver-master/src/ImpEncoder.cpp:656
        Detect finished!!
^CSIGINT

[NOTICE] /home/osboxes/SRC/Xiaomi-Dafang-Software/v4l2rtspserver-master/src/main.cpp:732
        Exiting....[root@DAFANGBEDROOM:bin]#
`

**Comment by nik0** [comment]
I added some logs, can you try this binary 
[v4l2rtspserver-master.zip](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/files/1886337/v4l2rtspserver-master.zip)

**Comment by bizzul** [comment]
Now I see this:


```
[root@DAFANGBEDROOM:bin]# pkill v4l2rtspserver-master
[root@DAFANGBEDROOM:bin]# ./v4l2rtspserver-master
i264e[info]: profile Constrained Baseline, level 3.1
ImpEncoder::ImpEncoder(impParams):910

[NOTICE] /home/osboxes/SRC/Xiaomi-Dafang-Software/v4l2rtspserver-master/src/ImpEncoder.cpp:146
        OSD pos 0,0,1279,36
ImpEncoder::ImpEncoder(impParams):939
ImpEncoder::ImpEncoder(impParams):949
ImpEncoder::ImpEncoder(impParams):955

[NOTICE] /home/osboxes/SRC/Xiaomi-Dafang-Software/v4l2rtspserver-master/src/ImpEncoder.cpp:146
        OSD pos 1240,0,1279,39
ImpEncoder::ImpEncoder(impParams):962
ImpEncoder::ImpEncoder(impParams):968
ImpEncoder::ImpEncoder(impParams):977
ImpEncoder::ImpEncoder(impParams):984
Changed OSD
Display motion OSD color=2

[NOTICE] /home/osboxes/SRC/Xiaomi-Dafang-Software/v4l2rtspserver-master/src/main.cpp:646
        Create ALSA Source.../dev/dsp
[NOTICE] /home/osboxes/SRC/Xiaomi-Dafang-Software/v4l2rtspserver-master/src/ALSACapture.cpp:51
        Open ALSA device: "/dev/dsp"
[NOTICE] /home/osboxes/SRC/Xiaomi-Dafang-Software/v4l2rtspserver-master/src/DeviceSource.cpp:87
        begin thread
[NOTICE] /home/osboxes/SRC/Xiaomi-Dafang-Software/v4l2rtspserver-master/src/ALSACapture.cpp:68
        LAME 3.100 32bits (http://lame.sf.net)
Using polyphase lowpass filter, transition band: 16538 Hz - 17071 Hz
Channel Count:1
[NOTICE] /home/osboxes/SRC/Xiaomi-Dafang-Software/v4l2rtspserver-master/src/main.cpp:151
        Play this stream using the URL "rtsp://192.168.2.244:8554/unicast"

[NOTICE] /home/osboxes/SRC/Xiaomi-Dafang-Software/v4l2rtspserver-master/src/DeviceSource.cpp:87

```

What do you think? It seems that dont start the script.

**Comment by nik0** [comment]
I think I understood the bug !
Try to change the sensitivity and restart the server
use the command `/system/sdcard/bin/setconf -k m -v 3`

for some reason when the sensitivity is kept as default (4) the init is not done
hope it will solve this ...

**Comment by bizzul** [comment]
You are the best!

It works!  The only problem now is that if I stop the service and start mjpeg or h264 in the webpage it does not work again.  I think I have to change the sensitivity to 3 permanently?

**Comment by nik0** [comment]
yes for now ... I am working on the configuration and this problem will be corrected (I hope :-))
Just tell me if the motion seems to be correct.

**Comment by bizzul** [comment]
Yes. If no motion for I think 20 30 seconds.

**Comment by nik0** [comment]
OK ... my next task then ...

**Comment by bizzul** [comment]
If you wish.

I think its a great update for the main fork this, with the addiction of a button in the webpage to choose between motion with zones or motion tracking in the scripts panel

**Comment by nik0** [comment]
I am doing the configuration in the webpage (I am not an html exper so it takes some time ...)

**Comment by bizzul** [comment]
Maybe there is someone who can help...

Im not very expert unfortunately..

**Comment by nik0** [comment]
Thanks, I will succeed !! It will take longer that's it ... But I am learning ...

**Comment by jmtatsch** [comment]
initial motion support working thanks to @nik0

**Comment by jmtatsch** [comment]
Yes long time ago. Doesn’t work so good for the new cameras without endstops.
