### ISSUE TITLE
no audio v4l2rtspserver-master

### ISSUE THREAD

**Issue by ceif** [EliasKotlyar/Xiaomi-Dafang-Hacks#196]
i installed last version of v4l2rtspserver-master (with motion detection) and have no audio-
here is the log: 

[root@DAFANGHACKS:bin]# ./v4l2rtspserver-master 
i264e[info]: profile Constrained Baseline, level 3.1
[NOTICE] /home/osboxes/SRC/Xiaomi-Dafang-Software/v4l2rtspserver-master/src/ImpEncoder.cpp:145
	OSD pos 0,0,1279,36
[NOTICE] /home/osboxes/SRC/Xiaomi-Dafang-Software/v4l2rtspserver-master/src/ImpEncoder.cpp:145
	OSD pos 1240,0,1279,39
Changed OSD color
IMP_IVS_GetParam(0) failed
Changed motion sensitivity 3
[NOTICE] /home/osboxes/SRC/Xiaomi-Dafang-Software/v4l2rtspserver-maste/src/ImpEncoder.cpp:588
Detection region= ((0,0)-(1279,719))
Changed motion region
Display motion OSD color=6
[NOTICE] /home/osboxes/SRC/Xiaomi-Dafang-Software/v4l2rtspserver-master/src/main.cpp:646
Create ALSA Source.../dev/dsp
[NOTICE] /home/osboxes/SRC/Xiaomi-Dafang-Software/v4l2rtspserver-maste/src/ALSACapture.cpp:51
Open ALSA device: "/dev/dsp"
[NOTICE] /home/osboxes/SRC/Xiaomi-Dafang-Software/v4l2rtspserver-maste/src/DeviceSource.cpp:87
begin thread
[ERROR] /home/osboxes/SRC/Xiaomi-Dafang-Software/v4l2rtspserver-maste/src/ALSACapture.cpp:68
LAME 3.100 32bits (http://lame.sf.net)
Using polyphase lowpass filter, transition band: 16538 Hz - 17071 Hz
Channel Count:1
[NOTICE] /home/osboxes/SRC/Xiaomi-Dafang-Software/v4l2rtspserver-master/src/main.cpp:151
Play this stream using the URL "rtsp://192.168.10.103:8554/unicast"
[NOTICE] /home/osboxes/SRC/Xiaomi-Dafang-Software/v4l2rtspserver-maste/src/DeviceSource.cpp:87

**Comment by nik0** [comment]
The “error” message that you get is not a real error (the log is misnamed and you be only a notice). To me there is nothing strange.
Did you test with an old version of the sever ?
With a lower resolution ?
Nik0

**Comment by ceif** [comment]
I tried and old version of v4l2rtspserver-master and the audio is fine. so the last version has some bug

**Comment by ceif** [comment]
anyone can give me some tips about how to compile v4l2rtspserver-master to dafang and change compile options, like default W, H, fps, etc

**Comment by tthk** [comment]
You don't need to recompile `v4l2rtspserver-master` to set options, just enter them on the command line.  Here are the options:
```
[root@dafangcam1:controlscripts]# /system/sdcard/bin/v4l2rtspserver-master -h
/system/sdcard/bin/v4l2rtspserver-master [-v[v]] [-Q queueSize] [-O file]
                  [-I interface] [-P RTSP port] [-p RTSP/HTTP port] [-m multicast url] [-u unicast url] [-M multicast addr] [-c] [-t timeout] [-T] [-S[duration]]
                  [-r] [-w] [-s] [-f[format] [-W width] [-H height] [-F fps] [device] [device]
         -v        : verbose
         -vv       : very verbose
         -Q length : Number of frame queue  (default 10)
         -O output : Copy captured frame to stdout
         RTSP/RTP options :
         -I addr   : RTSP interface (default autodetect)
         -P port   : RTSP port (default 8554)
         -p port   : RTSP over HTTP port (default 0)
         -U user:password : RTSP user and password
         -R realm  : use md5 password 'md5(<username>:<realm>:<password>')
         -u url    : unicast url (default unicast)
         -m url    : multicast url (default multicast)
         -M addr   : multicast group:port (default is random_address:20000)
         -c        : don't repeat config (default repeat config before IDR frame)
         -t timeout: RTCP expiration timeout in seconds (default 65)
         -T        : send Transport Stream instead of elementary Stream
         -S[duration]: enable HLS & MPEG-DASH with segment duration  in seconds (default 5)
         -fformat  : V4L2 capture using format (-W,-H,-F are used)
         -W width  : V4L2 capture width (default 1280)
         -H height : V4L2 capture height (default 720)
         -F fps    : V4L2 capture framerate (default 25)
         Sound options :
         -A freq    : Disable Sound
```

Currently, you will need to pass any custom options in the call to `v4l2rtspserver-master` in the files `controlscripts/rtsp-h264` or `controlscripts/rtsp-mjpeg` (depending which rtsp server you use).

Once the Pull Request #203 gets merged, you can add these options in the `config/rtspserver.conf` file.

**Comment by nik0** [comment]
Can it be memory issue like here: https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/178#event-1559702675 ?

**Comment by gabcac** [comment]
I have the same issue.
I edit to have rtsp h254 in 1080p, working great, but no audio. Same in 720p.
Anyone has an idea?
Thanks.

**Comment by jmtatsch** [comment]
Close in favour of #234. Please continue the discussion there.
