### ISSUE TITLE
How to view/edit filesystem

### ISSUE THREAD

**Issue by Ferrisbane** [EliasKotlyar/Xiaomi-Dafang-Hacks#2]
I am trying to view **Boa/0.94.13** webserver files, however using the method to unpack the firmware and then mount only works on the **appfs.bin**,

Is there a way to find what bin file contains the webserver files and then extract them?

Thanks.

**Comment by EliasKotlyar** [comment]
Hello Ferrisbane,

I have added some informations regarding this topic.
https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/hacks/howto_modfirmware.md

Greatings
Elias

**Comment by Ferrisbane** [comment]
Great thanks, very easy to follow.
