### ISSUE TITLE
Webserver not work.

### ISSUE THREAD

**Issue by dmolner** [EliasKotlyar/Xiaomi-Dafang-Hacks#20]
Hellom

I can't acces to Webserver, I only see a blue page.
If I write
http://IPDAFANG/cgi-bin/currentpic.cgi?width=1920&height=1080&nightvision=1
I can see photo and move motor too, but not work page.

**Comment by sharkoz** [comment]
This address _IS_ (part of) the webserver :)
Can you say which URL is not working ?

**Comment by dmolner** [comment]
This address.
http://192.168.1.144/cgi-bin/status.cgi
I only see a blue page without buttons or text.

**Comment by sharkoz** [comment]
Can you post the content of the source of what you get ?

**Comment by dmolner** [comment]
Now this is the message`

<HTML><HEAD><TITLE>502 Bad Gateway</TITLE></HEAD>
--
  | <BODY><H1>502 Bad Gateway</H1>
  | The CGI was not CGI/1.1 compliant.
  | </BODY></HTML>

`

**Comment by sharkoz** [comment]
This is weird, have you altered the status.cgi file in any way ? 
Try to set its rights to 777 : `chmod 777 /system/sdcard/www/cgi-bin/status.cgi`
  
Or have you tried rebooting maybe ?

**Comment by dmolner** [comment]
I write SD now finaly work, I made this 4 times with no solution.

Thankyou

**Comment by dmolner** [comment]
One more question.
Is possible instruciton for center the camera?
I see in these photo a possible sensor for center possition.
When the camera up move left and right and finaly stops in center.

[https://photos.google.com/share/AF1QipPPF2LQt3cq0qns9IRV_CBheMfjMohG43D7xfpVK2BA0ivfWr3Sgp2Kgt7nqwMutQ/photo/AF1QipN4FOG7LkyUC7cSoPOwWjYs3JpBBTWohxlijSib?key=T1k3SDFXRjlQSWxpWDJoTms5YU5qY21mbC1yOGhB](url)

**Comment by EliasKotlyar** [comment]
I think this issue was resolved. If not, feel free to open it up.
