### ISSUE TITLE
After DST changed to Summer, timezone does not seem to work properly

### ISSUE THREAD

**Issue by pplucky** [EliasKotlyar/Xiaomi-Dafang-Hacks#200]
Before Europe changing DST to Summer, Portugal timezone was UTC.

After the change, time started appearing wrong, so I tried changing it to UTC+1 (our current timezone).

Still then, time was 2h ahead of what it should be, so I had to set it to UTC-1 to get the right time.

I think somehow the camera is not interpreting the timezones correctly.

Does anyone else have this issue?

**Comment by tthk** [comment]
Just a data point: I am in California, and TZ set to PST8PDT gives the correct time for the cameras.

**Comment by pplucky** [comment]
Actually I hadn’t. Thanks for pointing it out to me
