### ISSUE TITLE
Confirmed works with Milestone Xprotect Essentials+ 2018 R1

### ISSUE THREAD

**Issue by Sungtroll** [EliasKotlyar/Xiaomi-Dafang-Hacks#201]
Video streaming works with both h264 and Mjpeg settings.
Not possible to change resolution, framerate or streaming rate.
The settings for the microphone i dont know. I get only noise but havent tried all the options yet.

![image](https://user-images.githubusercontent.com/37970110/38169777-a6e6ea16-359d-11e8-9e24-89975907aa5a.png)

**Comment by Sungtroll** [comment]
Information from VLC tells that audio codec is mpga 64 Kb/s but Milestone Xprotect does not support this audio format
![image](https://user-images.githubusercontent.com/37970110/38169986-81e64332-35a3-11e8-843e-40001656d093.png)

![image](https://user-images.githubusercontent.com/37970110/38169988-8e6ee492-35a3-11e8-9ec8-394bf8d6b937.png)

**Comment by jmtatsch** [comment]
It is possible to change resolution and bitrate now. New audio support in a pull request. Please reopen if your issue still exists.

**Comment by k1ng440** [comment]
what audio should i use with xprotect?
