### ISSUE TITLE
No audio on stream

### ISSUE THREAD

**Issue by markwain** [EliasKotlyar/Xiaomi-Dafang-Hacks#204]
Hey guys, need a little help here.
... So I was trying to connect my hacked camera to Angelcam network.
Did it successfully, but there was no audio on their side.

Here is reply from Angelcam's support team:
 ![](https://i.imgur.com/cy8yLao.png) 

For the record - I was running standard v4l2rtspserver-master

**Comment by ceif** [comment]
I already reported that last version of v4l2rtspserver-master is not streaming audio. Try with an old version.

**Comment by markwain** [comment]
Okey, how can I do this?

**Comment by markwain** [comment]
Hi guys!
Can anyone help me? @ceif? 
What is the best way to get audio aac up & running?

**Comment by anup-d** [comment]
@ceif Do you have the link to the old version? Audio is not working for me here either.

**Comment by jmtatsch** [comment]
close in favour of #234
