### ISSUE TITLE
wpa_sup help please

### ISSUE THREAD

**Issue by jonto20** [EliasKotlyar/Xiaomi-Dafang-Hacks#205]
so I had this working perfectly on normal mi-home app and decided to try and edit.

boot loader working fine just can't get it to show on my network, using sky in the uk.

below is my wpa edit I suspect this is the problem, could anyone take a look and tell me if this is wrong?

also now I can't even connected back to the mi home app, connection times out all the time.

ctrl_interface=/var/run/wpa_supplicant
ctrl_interface_group=0
ap_scan=1

network={
        ssid="SKYC9***"
        #scan_ssid=1 
        key_mgmt=WPA-PSK
        pairwise=CCMP TKIP
        group=CCMP TKIP WEP104 WEP40
        psk="XPPU***B"
        priority=2
}

**Comment by tthk** [comment]
Here is my working one:
```
network={
        ssid="MySSID"
        # Uncomment to connect to Hidden SSIDs
        #scan_ssid=1 
        key_mgmt=WPA-PSK
        pairwise=CCMP TKIP
        group=CCMP TKIP
        psk="MYsecretwifiKEY"
        priority=2
}
```
I spend an hour trying to get my camera to connect, when it turned out that I used all caps (MYSSID) for my SSID whereas my SSID was "MySSID".

Plus, I don't think the system will connect to the Mi Home app running in hacked mode (with SDCard installed).  In hacked mode with SDCard, you can go to http://camIPAddress/ to access/control the camera.

**Comment by jonto20** [comment]
I’ve been trying from Saturday to get it working. I’ll change mine so it’s like yours and see does that help so fingers crossed.

I’ll have to try and install original firmware if I can’t get this working. Also my security says WPA2-PSK should I change that??

**Comment by jmtatsch** [comment]
Did you copy wpa_suplicant.dist into wpa_supplicant.conf and make your adjustments? That is necessary for the latest versions...

**Comment by jonto20** [comment]
No I wasn’t aware that I needed to as it just said edit the file with your WiFi settings

**Comment by jmtatsch** [comment]
So is it working now? If yes can you please correct that in the wiki and close the issue?

**Comment by jonto20** [comment]
I've just checked an I only have wpa_suplicant.dist in the config folder???

**Comment by jmtatsch** [comment]
You have to make a copy of wpa_supplicant.dist and name it wpa_supplicant.conf.
Then in wpa_supplicant.conf add your personal SSID and WPA key.

**Comment by jonto20** [comment]
ok so I copied wpa_supplicant.dist and renamed it wpa_supplicant.conf and entered all my details in there. so in the folder I have both files but only the .conf has my details and iam still getting nothing.

orange light is solid on the front, but nothing showing in router attached devices. anything else you can suggest that can help please

**Comment by jonto20** [comment]
so got it working finally heres what I did for anyone who isn't a pro at this sort of thing

open the file wpa_supplicant.dist and copied all the txt in there
open a new notepad page and past all the txt in there.
enter wifi details
save using name wpa_supplicant.conf
in the drop down below the name select all files
save into the config folder

job done thanks for all the help
