### ISSUE TITLE
CFW

### ISSUE THREAD

**Issue by wimpi13** [EliasKotlyar/Xiaomi-Dafang-Hacks#208]
Hello, everybody.
I'm new on GitHub.
I just want to know : when installing CFW on SD card with Xiaomi Dafang, must I leave demo.bin on DSCard 
when copying CFW-Files ?
(I try to install it, because Dafang can't connect to Mi Home (Timed out error)
Thanks in advance for any help .
(Sorry for my english writing, I'm french)

**Comment by jmtatsch** [comment]
You don’t have to leave it there, it will not hurt either.

**Comment by wimpi13** [comment]
OK, thank you.
