### ISSUE TITLE
question

### ISSUE THREAD

**Issue by wimpi13** [EliasKotlyar/Xiaomi-Dafang-Hacks#209]
Hi, everybody.
I finally can connect my Dafang to Mi Home.
I want to know if I hack it after that (by installing CFW then CFW-Files on SDCard), will I be able to still use Mi Home or not ?

And anybody can tell me the meaning of the ligth : blinking yellow and blue, solid yellow and blue ?

Thanks in advances
BR
Gilles (Marseille - France)

**Comment by marvinroger** [comment]
Hi Gilles,

No, you won’t. The CFW files disable access to the Mi Home servers. See https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/hacks/faq.md

About the LEDs, I am not sure, so I’ll let someone else answer!

Regards from Paris

**Comment by wimpi13** [comment]
OK, c'est noté. Merci pour ta réponse.
Cordialement,

**Comment by thawizard** [comment]
@marvinroger Why has it been disabled? 
Is there a way to allow server access? I find it quite convenient when I can choose between CFW and Mi Home any time.  My old Yi Ants 720p still can do both.

**Comment by jmtatsch** [comment]
There is a button: Start original Xiaomi Software in the main menu,
which will load some original kernel modules and the original applications
In theory that should work. Please reopen if it doesn't work.
