### ISSUE TITLE
Remote Access to Multiple Cameras. Need Help

### ISSUE THREAD

**Issue by edenrock** [EliasKotlyar/Xiaomi-Dafang-Hacks#210]
I would like to access multiple Hacked Cameras remotely.  I can access one using TinyCam. Each Camera need a different port. I can access one camera on port 80.

I tried changing the port in rtspserver.conf.
RTSPMJPEGOPTS="-p 8123"

Doesn't work. What am I doing wrong?

**Comment by edenrock** [comment]
It would appear that multiple access is NOT possible with this mod. Or maybe no one want to share. I will continue with 'mainland' servers as I need remote access from more than one camera. 
Great effort. Thanks.

**Comment by nik0** [comment]
@edenrock 
I don't see your issue here, 
multiple camera-> multiple IP so you can control separatly each of them. 
You want to have access to the streaming, the status page, both of them?
Do you have a router ? Maybe there is something you need to configure here, nothing with the camera
You may need to change the streaming and web ports (I need to do that because my internet provider router is crappy and I can't redirect to the same port and different IP from outside)
Nik0

**Comment by edenrock** [comment]
The issue is, How do I set the port. For example to 8080.
Tried starting the stream with the switch "-p 8080" also "-p:8080". 
Still can only access the camera on port 80.

Thanks for responding.

**Comment by nik0** [comment]
Which port are you talking about ? The status page with all the camera information or the video stream ?
Anyway you don't need to change the port as the IP of the camera shall be different

**Comment by edenrock** [comment]
Yes IP is different, and is not an issue within the network.
HTTP port. See list of switches here, near the bottom. https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/196

**Comment by nik0** [comment]
I understand that TinyCam can not setup different camera with the same ports
I guess you are using RTSP, so add the following `-P 8555` in the file `config/v4l2rtspserver.conf`
8555 is the new port

**Comment by edenrock** [comment]
Will try that when I get back to the camera.

**Comment by edenrock** [comment]
Didn't solve the issue.
With TinyCam I only get a stream with Snapshot(JPEG) protocol and the RTSP option is 'greyed out'
Changing the RTSP port to anything in other protocol and return to Snapshot protocol, the stream continues. Seems RTSP is ignored.
Questions.
1. What is the correct way to set HTTP port, and is it a working option?
2. Is there a a command to see/verify enabled option?
Also I read that http port should be used with mjepg stream. If accurate, what is the best way to execute this?

**Comment by jmtatsch** [comment]
Simply set another port in lighttpd.conf for each camera e.g.
server.port = 81
..
server.port = 85

**Comment by edenrock** [comment]
Did this work for you? It doesn't work for me.
After changing the port to 81. I can no longer access the camera remotely. (Yes also forward port 81)
Thanks. Closed with a Non-Working Solution. How enlightening?

**Comment by jmtatsch** [comment]
Obviously not every corner case requirement can be supported. You were given some hints how to alleviate your issue anyway but you could not make it work nor did you investigate thoroughly why it doesnt work. Now you expect us recreate your usecase? This is not the way free community support works.

**Comment by edenrock** [comment]
ATTIDUDE!
