### ISSUE TITLE
work with ip cam viewer

### ISSUE THREAD

**Issue by jaimepcol** [EliasKotlyar/Xiaomi-Dafang-Hacks#211]
Hi, I Add in run.sh this command:
"/system/sdcard/bin/busybox nohup /system/sdcard/bin/v4l2rtspserver-master -fMJPG -P: 80 &>/dev/null &"
and work in ip cam viewer with wifi inside of house, but when I try outside with data network doesn't work.

Please help me

**Comment by c0defire** [comment]
If you want access to view the live feed outside your network. You have to port forward the cam's IP/port in your router settings.

PS. Make sure you change your password, or attackers will scan your cam and try the default creds.

**Comment by logannc** [comment]
> PS. Make sure you change your password, or attackers will scan your cam and try the default creds.

Which password? Different from https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/245?

**Comment by jmtatsch** [comment]
the rtsp password, settable in rtspserver.conf

**Comment by jmtatsch** [comment]
Closing this as it is not a real issue. For support please use the gitter chat in future.
