### ISSUE TITLE
Dafang + Ds Cam Synology

### ISSUE THREAD

**Issue by sango74** [EliasKotlyar/Xiaomi-Dafang-Hacks#213]
I put the Fang Hacks firmware on my Dafang.
I managed to integrate the Synology Surveillance Station, and I manage to have the live without any problem.
By cons when I want to watch the camera on the phone with the application "DS CAM" I have no picture with a message: Network Error.
Is it possible to operate this camera with the mobile application "DS CAM"?
PS: I am French translation via Google.
thank you in advance

**Comment by helio58** [comment]
I m using it for 2 weeks ,works.

**Comment by mitchoklemen** [comment]
Mine works too, except PTZ.

**Comment by sango74** [comment]
Hello,
Do you want to tell me what is your configuration? (in the synology station)
Phone type? Android version and DS CAM
I do not understand why the video does not start.
:(
Thank you

**Comment by mitchoklemen** [comment]
DS214play, DSM 6.2 beta, DS cam 
SS:
port: 8554
brand: user defined
path: /unicast
username:    "none"
password:     "none"

Probably something gone wrong with flash from SD.
Try reset it and make it from scratch.

**Comment by snjoetw** [comment]
I noticed the same thing with my DS216+II

I couldn't view the stream using DS Cam app also noticed that in Surveillance Station, it keeps saying connection lost :(

**Comment by helio58** [comment]
Please take a look at the wiki

**Comment by snjoetw** [comment]
I've tried switch protocol to TCP but that didn't help. Turns out I had to disable audio as well. Might be related to https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/196

**Comment by mitchoklemen** [comment]
In DScam app try to switch "play video stream over HTTP" and set the Http port in Settings.

**Comment by RaymondSchnyder** [comment]
The PTZ also doesnt works on my cams, not too bad in my case, as they will be watching not movable objects and i can move them via the webinterface of the cam :)

**Comment by hondaj** [comment]
I have a little diferent problem but woudn't add a new topic. 
Two Dfang's in the LAN that have been work fairly stable for today (from 01.2018) with RSTP MJPEG with my Synology SS 8.1
Because due to SS licensing I decided to rollback SS software to version 8.0.1, it turned out that there is some error in this version and I can not connect the MJPEG stream but it works with H264.
However, one of the cameras has ~11fps and second ~25fps, both have exactly the same mod (sd card cloned). 
What could be the reason for this?

**Comment by Adrimau** [comment]
Hi! Someone can show me his settings in the hack UI and Surveillance Station ? Because my integration in SS works half, see [here](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/755).

**Comment by hondaj** [comment]
![1](https://user-images.githubusercontent.com/36073063/47616099-6188e800-dab8-11e8-8c08-5be72ce188e9.jpg)
![2](https://user-images.githubusercontent.com/36073063/47616101-68175f80-dab8-11e8-8ce4-a1c57199eadc.jpg)
![3](https://user-images.githubusercontent.com/36073063/47616102-6a79b980-dab8-11e8-9b87-33830121a5fc.jpg)

**Comment by hondaj** [comment]
![4](https://user-images.githubusercontent.com/36073063/47616159-57b3b480-dab9-11e8-82fa-9b695e5d7c82.jpg)

**Comment by hondaj** [comment]
![5](https://user-images.githubusercontent.com/36073063/47616239-7bc3c580-daba-11e8-9b6d-3cfb6767a6e7.jpg)

**Comment by hondaj** [comment]
Mobile view (iOS):
![6](https://user-images.githubusercontent.com/36073063/47616318-761aaf80-dabb-11e8-962b-02baf6d672c2.jpg)

**Comment by Adrimau** [comment]
Thanks @hondaj for your screen. I tried exactly the same settings and the real live view doesn't work (juste the thumbnail). I noticed that I haven't exactly the same UI as your first screen, what is your Surveillance Station version? It could be the problem..

<img width="762" alt="image" src="https://user-images.githubusercontent.com/31062488/47621236-38d31380-daf5-11e8-822c-65f740f94d15.png">

**Comment by hondaj** [comment]
But tell me what is the problem? you can't save camera configuration or you only can't see initial preview of the image (this is not a big problem)?

Try to use Surveillance Station Client for configure : https://archive.synology.com/download/Tools/SurveillanceStationClient/ 

My SS is 8.0.1-5128 you can try to uninstall you SS and manually install exact the same as mine (from Synology server: https://archive.synology.com/download/Package/spk/SurveillanceStation/).

Surveillance Station is great stuff but initial config unsupported cameras it is a torture :-)

**Comment by tesnic** [comment]
I have the same problem than Adrimau, It works on Surveillance Station Client, but not into the SS on DSM. I try to unistall the app and install again manually but it diddn't work....

**Comment by cmol1** [comment]
Hi All,

I managed to run the camera in 1600x900 with audio, no issues so far. In order to get the audio working you have to change the format to PCM, that's all, once done, live view and recording should be working like a charm, before changing this, if audio was enabled, video feed will disconnect and reconnect, also recording did not work.

![image](https://user-images.githubusercontent.com/46232015/50531576-63c2fd80-0b60-11e9-8050-970e99db9e63.png)
![image](https://user-images.githubusercontent.com/46232015/50531579-71788300-0b60-11e9-8e09-f7a96052a10c.png)

Cheers

**Comment by stucki** [comment]
@cmol1 Thanks for your info! This works for me.

**Comment by urkl** [comment]
@cmol1 Thanks. It was audio issue. Great.

**Comment by bartaspoz** [comment]
Do you thing PTZ can be achieved? Maybe we should ask for that feature to be able to use in Synology

**Comment by jghaanstra** [comment]
@cmol1 I have a Xiaomi Xiaofang camera added to SS. I have changed the audio profiel to PCM and when I record video or watch a live video I have audio. But for some reason I am unable to use sound detection within SS. Is this working for you and if so, did you do something specific to get this to work?
