### ISSUE TITLE
New UI

### ISSUE THREAD

**Issue by gysmo38** [EliasKotlyar/Xiaomi-Dafang-Hacks#217]
Hello,
I start to write a new html5 ui. I give you, if soemone want to try and tell me what to improve.

It is not finish, I hope to finish it in few days.

Just create a directory ui under www directory and unzip the file.

[ui.zip](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/files/1891753/ui.zip)

**Comment by fcastroruiz** [comment]
its good option , work fine! some links dont work fine (normal in beta version) but i think is great job

**Comment by Psudonico** [comment]
good work,
I'am colorblind and do not distinguish the active buttons from the non-active ones

**Comment by jmtatsch** [comment]
This color schema is very hard to read
<img width="417" alt="screen shot 2018-04-13 at 08 00 52" src="https://user-images.githubusercontent.com/3080674/38720953-8643a2fe-3ef8-11e8-870a-c037ad2ccecf.png">

**Comment by ping** [comment]
My apologies if this is bad form, but I am also working on a new UI.
Latest changes are on my fork at https://github.com/ping/Xiaomi-Dafang-Hacks/tree/new-ui where you can download and replace your copy of the ``www/`` folder.

The new UI is responsive and should work mostly fine on both mobile and desktops. Comments/feedback are welcomed.

### Screenshots

![newui-1](https://user-images.githubusercontent.com/104607/38770054-71d78978-403f-11e8-88e2-fd26efbb8d3b.png)

![newui-2](https://user-images.githubusercontent.com/104607/38770056-8019f82c-403f-11e8-9547-08848b270a91.png)

![newui-3](https://user-images.githubusercontent.com/104607/38770058-891e3a32-403f-11e8-87d7-5c919a59e9ca.png)

**Comment by remb0** [comment]
Nice,  i hope or wilill be the default.

**Comment by desq42** [comment]
+1

**Comment by jmtatsch** [comment]
@ping Love your work, would you maybe open up a pull request, so we can continue discussing things there?

**Comment by ping** [comment]
@jmtatsch PR submitted

**Comment by jmtatsch** [comment]
pr #239 was recently merged, please continue bringing in your great ideas
