### ISSUE TITLE
Default password not working

### ISSUE THREAD

**Issue by c0defire** [EliasKotlyar/Xiaomi-Dafang-Hacks#219]
I uncommented the line Auth / Basic:/system/sdcard/config/htpasswd.conf in boa.conf
Scanned the network for the IP cam and used the default creds. After hitting enter, I was prompt again to enter a username and password.

Is there something I'm missing?

Thanks

**Comment by c0defire** [comment]
I feel like such a noob, I fixed my problem I didn't read all the documentation in the config files.
Thanks for a great hack.

**Comment by wojtulab** [comment]
/scripts/common_functions.sh
run simply with your password:
```
user="root" # fill it with user, default is root
  realm="all" # realm is defined in the lightppd.conf
  pass="myPasswordhere" # fill it with password, default is root
  hash=$(echo -n "$user:$realm:$pass" | md5sum | cut -b -32)
  echo "$user:$realm:$hash" > /system/sdcard/config/lighttpd.user
echo "my user and new password are: "${user}" , "${pass}"
```

**Comment by piero78** [comment]
Thanks
