### ISSUE TITLE
Dafang in EU and other questions

### ISSUE THREAD

**Issue by rkrisi** [EliasKotlyar/Xiaomi-Dafang-Hacks#222]
Dear Everyone!

Do someone use this cam in the EU? Is it working? Because the XiaoFang camera had some issues that it can only be used in China.

How this custom-firmware different from fang-hacks? After installing does this provide rtsp stream or other video stream? Does it support changing the IR and other things via scripts?

Thanks

**Comment by goermezer** [comment]
I use two of them in Germany. No issues related to the region. I can not explain the differences. But I am sure, that it has at least to do with different hardware.

Everything else, what you ask for is supported. But only one RTSP or MJPEG stream at the moment. Capturing a JPEG while streaming works.

**Comment by rkrisi** [comment]
Thank you very much for your help! I think I will try one!
If you have a little spare time, just a few other questions:

- What about the video quality? I have seen some videos on YouTube but it is more likely an SD video stream rather than a HD one.
- I'm a little bit lost in the hack installation. So you need to connect it to your wifi with it's original software and then insert the SD containing the modded firmware?

Really thanks for your help!

**Comment by goermezer** [comment]
The video quality for me is much better than a Raspberry Pi Camera, even it’s horsepower is much stronger and the camera has a much higher resolution. I replaced two of the against hacked Dafangs. I usually have 25fps@1280p. You can bump the resolution a bit in cost of FPS.

No, you don’t need to boot into Xiaomi firmware. You simply flash an addional small Linux and then run everything else from SD card. The WiFi credentials are placed in wpa_config file. It automatically connects then with you router. Follow the installation instruction... But: a FAT32 formatted SD card could be a problem. To be sure, or if your camera doesn’t boot, I would format as FAT, even somebody has luck with FAT32. I think the FAT format (or usually known as FAT16) is not possible in Windows. So find a partitioning tool which supports it. I used the FAT partition which was already there on my Raspberries from their Raspbian installation.

**Comment by rkrisi** [comment]
Thanks for your help! I'll close this thread and buy one and try it out!

**Comment by saipsa** [comment]
@goermezer 

>  I usually have 25fps@1280p

I have 20 fps@960p and 750 bitrate. If I increase the bitrate or the resolution, the stream starts to hang as in the moving object will remain in its old position and also in new position with pixelated stuff in between.

I tried streaming on mobile and laptop.

My router is 300Mbps. 

Any help/pointer is appreciated.

Thanks.
