### ISSUE TITLE
MQTT Not Working (Fix Found -- Please Update)

### ISSUE THREAD

**Issue by Small6oy** [EliasKotlyar/Xiaomi-Dafang-Hacks#224]
I was trying to set MQTT to work and it failed because you are pointing to 
`/system/sdcard/bin/mosquitto_pub.bin`
instead of
`/system/sdcard/bin/mosquitto_pub`
in your scripts.

**Comment by jmtatsch** [comment]
Using mosquitto_pub.bin directly isn't a problem as long as its libs are exported on the library path LD_LIBRARY_PATH='/thirdlib:/system/lib:/system/sdcard/lib'.
This usually happens in source /system/sdcard/scripts/common_functions.sh. I did not find a mosquitto_pub.bin without sourcing common_functions.sh first.

Did your issue occur using the latest code? In which files exactly?

**Comment by Small6oy** [comment]
@jmtatsch Thanks. I see that I had copied my old `mqtt.conf` file across and I can see that in the new `mqtt.dist` the `LD_LIBRARY_PATH` is referenced.
