### ISSUE TITLE
OSD date and time format

### ISSUE THREAD

**Issue by rolfz** [EliasKotlyar/Xiaomi-Dafang-Hacks#225]
The use of proportional font makes date and time to be too close to each other when the seconds end with 1 and the date starts with 1. 
Example:
12:10:00  13.04.2018
12:10:0113.04.2018 (looks like this when seconds end with 1)
Maybe an additional space in such a case would help.

**Comment by nik0** [comment]
Did you try "fixed width" ? Or add 2 spaces between hours and day ..

**Comment by rolfz** [comment]
Thank you that works ! did not see the options before sorry !
