### ISSUE TITLE
Not a issue, but Camera speaks english with original firmwarr

### ISSUE THREAD

**Issue by mtunberg** [EliasKotlyar/Xiaomi-Dafang-Hacks#227]
I followed this guys hack and now my camera speaks english, even after update. If someone will make a great UI for dafang hack it would be awsome! Until then I’ll go for the original fw. I can’t get this hack to work reliable, it hangs and rtsp server stops intermittent. Check the link below, I had trouble connect in Mi app woth original fw, after hack that problem is gone!

https://youtu.be/BF8UFTz5BoQ

**Comment by mtunberg** [comment]
Great! I think I give it a couple of weeks and then try it again, great work by the way!

**Comment by jmtatsch** [comment]
we have a new interface now, please re-evaluate
