### ISSUE TITLE
MQTT commands which relay to action.cgi not functioning

### ISSUE THREAD

**Issue by wild9** [EliasKotlyar/Xiaomi-Dafang-Hacks#228]
They generate a 401 Error in the boa log:

>  "GET /cgi-bin/action.cgi?cmd=motor_hcalibrate HTTP/1.1" 401 0 "-" "curl/7.59.0-DEV"

running the command directly in the shell gives : 

> <.HTML><.HEAD><.TITLE>401 Unauthorized<./TITLE><./HEAD>
> <.BODY><.H1>401 Unauthorized<./H1>
> Your client does not have permission to get URL /cgi-bin/action.cgi from this server.
> <./BODY><./HTML>

This happens even with a user and password defined in mqtt.conf - CURLOPTS or directly in the curl command using the shell

It's possible I'm doing something wrong here but I'm out of ideas.

edit:
Not sure how to post html tags in this comment without them marking up the text so added .'s to the <> tags

**Comment by jmtatsch** [comment]
Still works for me on the latest version.
Are you on the latest version?
There was a switch from boa to light http a few commits ago...

**Comment by wild9** [comment]
Downloaded from master last night, is there a different branch I should use?

**Comment by jmtatsch** [comment]
Master is ok. The switch from boa to lighthttp has not happened so far, it is only prepared.
Nevertheless I have also noticed that the web interface has been requesting credentials irregularly as of lately. Which is in principle a good thing 😄, we should just make it more regularly.

For me
CURLOPTS="–user root:ismart12"
works.

**Comment by jmtatsch** [comment]
No feedback, closing this for now.
