### ISSUE TITLE
SMTP not working

### ISSUE THREAD

**Issue by codewizer** [EliasKotlyar/Xiaomi-Dafang-Hacks#230]
nothing is send to my gmail using the configurations below:

# motion.conf
# Configure how to deal with motion events
sendemail=true

# sendmail.conf
# Email and name of the sender (maybe it doesn't work as mailer override it from authentication info)
FROM="XXsenderXX@gmail.com"
FROMNAME="`Dafang Motion`"

# Login and pasword to access snmtp server
AUTH="XXsenderXX@gmail.com"
PASS="XXsenderpwdXX"

# Destination email
TO="XXrecipientXX@@gmail.com"
# SMTP information
SERVER=smtp.gmail.com
PORT=587

# Subject of the email
SUBJECT="Alert !!"
# Body of the email
BODY="This is an alert from `dafang`"

# Number of capture to join the email
NUMBEROFPICTURES=5
# Time in seconds between captures
TIMEBETWEENSNAPSHOT=5

**Comment by codewizer** [comment]
i get an error message when using shell

```
[root@DAFANG:~]# /system/sdcard/bin/busybox sendmail \-H"exec /system/sdcard/bin/openssl s_client -quiet -connect smtp.gmail.com:587 -tls1 -starttls smtp" \-f"XXsenderXX@gmail.com" -au"XXsenderXX@gmail.com" -ap"XXsenderpwdXX"
 XXrecipientXX@gmail.com
WARNING: can't open config file: /home/osboxes/SRC/Xiaomi-Dafang-Software/libressl/_install/etc/ssl/openssl.cnf
depth=1 C = US, O = Google Trust Services, CN = Google Internet Authority G3
verify error:num=20:unable to get local issuer certificate
verify return:0
250 SMTPUTF8
```

**Comment by codewizer** [comment]
Thanks. It worked perfectly!
> I think your AUTH name is not correct, you don't need to add "@gmail.com"

**Comment by nik0** [comment]
I did a change request that compress the jpg image. I don’t know if it related to size of the images but while my tests I get a temporary ban from google 😭

**Comment by mr2c12** [comment]
Sorry to jump in this thread :)

I don't receive any email, so I tried the shell command above. Username and password are hidden here.

> # /system/sdcard/bin/busybox sendmail \-H"exec /system/sdcard/b
> in/openssl s_client -quiet -connect smtp.gmail.com:587 -tls1 -starttls smtp" \-f
> "myaccount@gmail.com" -au"myaccount" -ap"mypasswd"
> WARNING: can't open config file: /home/osboxes/SRC/Xiaomi-Dafang-Software/libressl/_install/etc/ssl/openssl.cnf
> depth=1 C = US, O = Google Trust Services, CN = Google Internet Authority G3
> verify error:num=20:unable to get local issuer certificate
> verify return:0
> 250 SMTPUTF8
> sendmail:  failed

For what I see, it tries to get the openssl.cnf from a non-existing path.
What can I do?

**Comment by nik0** [comment]
openssl.cnf is not an issue. Anyway If you want to add one: 
`/system/sdcard/bin/curl http://web.mit.edu/crypto/openssl.cnf -o /system/sdcard/config/openssl.cnf
export OPENSSL_CONF=/system/sdcard/config/openssl.cnf
`
Anyway you will still get the error (I also have your error with you commandline)
How about starting 
`/system/sdcard/bin/sendmail` it does work for me
I don't have time to see the differences ....

**Comment by mr2c12** [comment]
I don't have sendmail in /system/sdcard/bin/
Maybe you meant to sendPictureMail.sh in scripts folder?
This is the output of this script:

> # sh /system/sdcard/scripts/sendPictureMail.sh 
> stdin 1280x720 24bit N WARNING: can't open config file: /home/osboxes/SRC/Xiaomi-Dafang-Software/libressl/_install/etc/ssl/openssl.cnf
>  [OK] 0 --> 85889 bytes (-inf%), optimized.

Anyway, I haven't received an email :(

**Comment by nik0** [comment]
Yes: Sendmail is a personal test
sendPictureMail.sh is also working
I think there is something wrong in your configuration
Be sure that sendmail.conf is well configured, the AUTH variable is your login. If your email is john.doe@gmail.com; AUTH should be "john.doe" only

You can also try the following:
https://support.google.com/accounts/answer/6010255?hl=en

**Comment by mr2c12** [comment]
I found the problem: gmail was set to block any attempt to send email coming from an "unsecure" app.
After enabling that, I can send&receive email.

Thanks for you support, hope this can help someone else!

**Comment by camera20038** [comment]
for email motion detection alert, i tried on Xiaomi Xiaofang 1S, with all default parameters, it doesn't work, workaround to reduce memory/cpu usage and found that, it's only work if resize video to 640x360, any suggestion to get 1080p mode?

**Comment by shaggness** [comment]
Same here.  Only work if resize video to 640x360. Anyone got it working with higer resolution than that?

**Comment by wiredolphin** [comment]
For the email notification to work at a higher resolution than 640x360, enabling swap on my Xiaofang S1 worked!
Just edit `/system/sdcard/run.sh` at line 59 changing it to `swap=true`, then reboot
That also made Telegram notify to work at a wider resolution.
