### ISSUE TITLE
How to set control url in dafangcam Android app

### ISSUE THREAD

**Issue by tyronevdm** [EliasKotlyar/Xiaomi-Dafang-Hacks#235]
![screenshot_20180416-055443](https://user-images.githubusercontent.com/16231769/38782724-1400957c-413b-11e8-883b-902324dcbac2.png)
Hi , I've not read nearly all the help files and forum posts and can not find any information on how to set the control server url in dafang, probably not the best place to ask this but the app is referenced on the home page readme , below is a screenshot of what I'm talking about

**Comment by jcrombez** [comment]
Look at the app screenshots on its store page, there is an exemple.

**Comment by jmtatsch** [comment]
Look at the integration instructions on the front page

**Comment by mslr75** [comment]
Could you give me the lik because on the front page of the playstore when i enter the information for the control, https://192.168.1.20/cgi-bin/status.cgi

the stram work but not the control

**Comment by mslr75** [comment]
Could you give me the URL please ?

**Comment by jmtatsch** [comment]
https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/integration/tinycam/tinycam.md
