### ISSUE TITLE
Schedule a motion detection

### ISSUE THREAD

**Issue by wojtulab** [EliasKotlyar/Xiaomi-Dafang-Hacks#240]
Is it possible to schedule a motion detection?
I tried with MQTT and send via:
`$TOPIC/motion/detection/set OFF`
and then enable it again with:
`$TOPIC/motion/detection/set ON`
but this scenarios is not working properly.
I noticed that motion is still running...

**Comment by nik0** [comment]
To deactivate the motion: `/system/sdcard/bin/setconf -k m -v -1`
To re-activate the motion: `/system/sdcard/bin/setconf` -k m -v SENSITIVITY`
With SENSITIVITY from 0 to 4, you can get the current 
`/system/sdcard/bin/setconf -g m`

Nik0

**Comment by jmtatsch** [comment]
Do you get a reply OFF on  topic/motion/detection?

Why do you think it is still on?

**Comment by wojtulab** [comment]
Yes, got it on topic/motion/detection.
I am sure because of mqtt events, amber led and finally pictures saved in sd card.

**Comment by wojtulab** [comment]
ok, finally the answer is:
`motion_detection_off -> $topic/set`

**Comment by jmtatsch** [comment]
I don't understand what you mean by this:
motion_detection_off -> $topic/set

**Comment by wojtulab** [comment]
sth like that
`mosquitto_pub.bin  -h $HOST -u $USER -P $PASS -t ${TOPIC}/set -m "motion_detection_off"`
