### ISSUE TITLE
Unsupported command 'setvideosize'

### ISSUE THREAD

**Issue by Maxmudjon** [EliasKotlyar/Xiaomi-Dafang-Hacks#242]
![image](https://user-images.githubusercontent.com/23142922/38889102-0d259fa6-4297-11e8-9b0c-75b6b00b47f5.png)

**Comment by mitchoklemen** [comment]
dito

**Comment by phineasthecat** [comment]
![unsupported_command](https://user-images.githubusercontent.com/14878852/38903912-46cbb8d4-4275-11e8-99c3-0158f5f98039.PNG)

Same here.

**Comment by jmtatsch** [comment]
Should be fixed via #247, if not reopen
