### ISSUE TITLE
external access via tinycam no tilt or pan or sound

### ISSUE THREAD

**Issue by maxhammond** [EliasKotlyar/Xiaomi-Dafang-Hacks#243]
Hi, 

so I have the camera hacked and working well on my home network. i have uploaded custom_vendors.xml and the camera moves as commanded within tinycam from my phone. however I have no sound , i get an error message about a timeout due to  incorrect host name and port number.

if i use VLC media player on my PC or my phone I have picture & sound so audio is working , just not via tinycam. is that expected behaviour? .

If i port forward through my router so to access camera away from home,  i can still use tinycam on my phone, no sound as before but now the movement controls dont work. they are not greyed out, just dont work. is that to be expected? Internal Yes working  , external No not working?

If I use VLC on my phone away from home, I  get sound and picture so no issue with router. 

Is it possible to use movement control with tinycam &  custom_vendors.xml with external IP ? Do i need to port forward port 8554 and port 80?

<vendor name="Xiaomi3">
        <model name="Dafang (max Software)" defaultPort="80" defaultRtspPort="8554">

Is sound  working with tinycam either using internal IP or external IP or it a straight no to both?

any help would be great as this is driving me nuts

**Comment by jmtatsch** [comment]
You will need to expose both ports to the internet to get video stream and controls.

**Comment by jmtatsch** [comment]
Closed due to inactivity.

**Comment by maxhammond** [comment]
Hi, so whats the other port ? I have port forward on 8554 and video is fine , what port is the controls?

**Comment by jmtatsch** [comment]
443

**Comment by maxhammond** [comment]
thanks will try that.

**Comment by maxhammond** [comment]
Thanks , but thats not done it , still no sound or controls with tiny cam via web, controls work with tinycam on home WIFI / but no sound, getting a timeout due to incorrect host name and port number message.
I'm port forwarding 8554 and 443 now, I haven't set any user authentication / login on the HTTP just the RTSP ,i read a thread that perhaps they should both be set as the same user and PW , should I have authentication on for HTTP as well?

**Comment by jmtatsch** [comment]
Yes same users and password s for http & rtsp. Does calling the control services as defined in custom vendor xml from a browser work?

**Comment by maxhammond** [comment]
OK, rebuilt camera with latest firmware and set passwords the same on RTSP and HTTP the same. If i access the web server external i can control the camera in browser, Ive reloaded the custom _vendors in to tinycam , the video works, but no movement.

**Comment by maxhammond** [comment]
Ah Ha! fixed it!!! thanks for you help. !!

**Comment by Dopeyr** [comment]
@maxhammond Great news! What was the fix, just in case someone else has the same issue?

**Comment by maxhammond** [comment]
me being thick more than anything. Make sure you have the same ID and PW for both HTTP and RTSP. I changed the HTTP password via the web server. Port forward both ports , the rtsp 8554 and port  443.   configure Tiny Cam to use the custom vendors file. then set up Tiny Cam  with correct external IP address for camera, the web port as 443, rtsp as 8554 and enable HTTPS in the app. reboot everything and remote control works both internally and externally via Tiny Cam. Sounds not working yet, but one thing at a time ....

**Comment by anemes** [comment]
To get sound, you want to set
```
AUDIOFORMAT=PCMU
AUDIOOUTBR=8000:8000
```
 in `/system/sdcard/config/rtspserver.conf`, this should pass to v4l2rtspserver-master `-E PCMU:8000:8000`.

Then tinycam works great. 

If you still have trouble with outside access or don't want to pass the password in clear text, I suggest using openvpn on android VPN to your camera's network - a raspberry pi zero for $5 will do the trick as the openvpn server.

**Comment by maxhammond** [comment]
ok, so are you saying I should add AUDIOFORMAT=PCMU & AUDIOOUTBR=8000:8000 to the rtspserver.conf file , and then add -E PCMU:8000:8000 to the RTSPH264OPTS option line as below? sorry not come across or set those variables before

#######################################################################
# Edit this file and move it to /system/sdcard/config/rtspserver.conf #
# if you need to add options, otherwise defaults will be used         #
#######################################################################

# Configure RTSP Servers
# Use /system/sdcard/bin/v4l2rtspserver-master -h to see available options

# H264 RTSP server options
# Examples:
# RTSPH264OPTS="-W960 -H540"
# To enable authentication:
# RTSPH264OPTS="-U user:password"
AUDIOFORMAT=PCMU
AUDIOOUTBR=8000:8000
RTSPH264OPTS="-W1280 -H720 -U xxxxx:yyyyyyy -E PCMU:8000:8000"

# MJPEG RTSP server options
# Examples:
# RTSPMJPEGOPTS="-W960 -H540"
# To enable authentication:
# RTSPMJPEGOPTS="-U user:password"
RTSPMJPEGOPTS=""

**Comment by anemes** [comment]
No. If you have the latest config, you can just have
```
AUDIOFORMAT=PCMU
AUDIOOUTBR=8000:8000
RTSPH264OPTS="-W1280 -H720 -U xxxxx:yyyyyyy"
```

**Comment by maxhammond** [comment]
ok added the two lines and rebooted camera , i started up tiny cam and tap the audio button when the video starts up , it spins for a while then returns the same timeout  error like before

**Comment by maxhammond** [comment]
i rebuilt the camera 5 days ago so assume i have the latest config ??

**Comment by anemes** [comment]
Try it first on your internal network. These are the settings I use:

Tinycam camera settings (with custom_vendor.xml loaded)

Web port number: 443
Protocol: RTSP over TCP (MPEG/H264/H265)
RTSP port number: 8554
Use HTTPS: ticked

**Comment by maxhammond** [comment]
Fantastic! All working now I've uploaded the latest config. Sound and Controls all working. With the new custom_vendor file the home button works as well!

Volume is a bit quiet but I have ago with the /system/sdcard/bin/setconf -k h -v 100  


thanks Anemes  for helping.

**Comment by maxhammond** [comment]
so i take it if i reboot the camera have to re run the /system/sdcard/bin/setconf -k h -v 100 command again, can i load it somewhere so it runs every time?

**Comment by jmtatsch** [comment]
You can put it in run.sh

**Comment by nik0** [comment]
On the GUI page you can set the volume (there is a slider) and it should remains across reboots

**Comment by tripchoc** [comment]
Thank you for referencing me to this #
Below are some of the things I have done but I am unsure if there is any misconfigurations that caused me not to view from WAN. 

I did a password change for HTTP (through index.html) and RSTP (rtspserver.conf) and both username and password are the same. 
Did a change on server.port = 80 to server.port=’1234’ (lighttpd.conf) and maintain the RSTP port to default (8554). Configured the port forwarding on the router for ‘1234’ only. 
When I tried to access from the WAN (http://dyndns:1234), I noticed there was a TLS handshake message on the browser and eventually a timeout. 
I did not change the SSL port (443) below. Is there any scripting for re-direction from port no:’1234’ to port.no:443? 

$SERVER["socket"] == ":443" {
  ssl.engine = "enable"
  ssl.pemfile = "/system/sdcard/config/lighttpd.pem"
}

Do I need to set another port forwarding rule for port 443 and for RSTP 8554?
I have 5 units of Xiaomi Dafang camera that I would like to view from the WAN through IP Cam Viewer (iOS app) as I do not own an Android to run TinyCam. 

Is there a need to change every 443 (SSL) and 8554 (RSTP) to identify the cameras? What about the standard port 80? 
1.	444, 8555
2.	445, 8556
3.	.
4.	.
5.	448, 8558

**Comment by jmtatsch** [comment]
If you have not disabled https redirection you must forward 443.

**Comment by tripchoc** [comment]
Apologies. How do I disable https redirection? I tried to comment # a few lines but it hanged.

**Comment by rafalefighter** [comment]
Hi is it possible to deploy OpenVPN client inside camera?. Is this hardware capable of running it?

**Comment by xgusto** [comment]
That would interest me as well
