### ISSUE TITLE
Jffs2 Mount Empty

### ISSUE THREAD

**Issue by openipcamera** [EliasKotlyar/Xiaomi-Dafang-Hacks#246]
Hello.

Attempting to mount the appfs bin with included script folder is empty:

 ./jffs2_mount_loop.sh dafang-demo_hack_telnet.bin-extracted/appfs.bin test 00008000
Successfully mounted dafang-demo_hack_telnet.bin-extracted/appfs.bin on test
du -sh test
0       test

Using jefferson I can unpack the jffs2 appfs.bin but there does not seem to be a repacking method - thus the mount is required to make edits.

**Comment by jmtatsch** [comment]
@EliasKotlyar maybe you can help here?
