### ISSUE TITLE
PORT parameter in mqtt.conf is useless.

### ISSUE THREAD

**Issue by Knurlnheim** [EliasKotlyar/Xiaomi-Dafang-Hacks#250]
As far as I figured, the PORT parameter in mqtt.conf is not used.
If you want to use anything other than the default "1883", you have to add it in the MOSQUITTOOPTS along with the others options you need, eg. :
MOSQUITTOOPTS="-p 8883 --cafile /system/sdcard/config/Root_CA.pem".

**Comment by jmtatsch** [comment]
Thank you. Should be fixed now, if not please reopen.
