### ISSUE TITLE
Status page doesn't correctly read ldr_average setting

### ISSUE THREAD

**Issue by Knurlnheim** [EliasKotlyar/Xiaomi-Dafang-Hacks#251]
When a user sets a value for "Number of measurements" in the Auto_night_mode on the status page, it is correctly written in the ldr-average.conf file.
But subsequent display of the status page does not show the value that was set, it stays at the default "1".
PR to follow.

**Comment by jmtatsch** [comment]
Thank you. Issue should be fixed, if not reopen
