### ISSUE TITLE
Camera short circuited itself

### ISSUE THREAD

**Issue by Jhyrachy** [EliasKotlyar/Xiaomi-Dafang-Hacks#256]
Not directly related to this project, but my dafang stopped working without apparent reason and when powered by a pc it say that is draining too much current and the usb port is being shut down to prevent damage. Have anyone had any similar problem?

**Comment by jmtatsch** [comment]
Are the motors at the motors stuck at the endstops? Can you start without the sd card in normal xiaomi mode? Can you run it on a stupid wall charger? Since 5225088 the camera writes a startup.log to the log directory of your sdcard. This can probably help you to figure out your issues.

**Comment by SamHead** [comment]
Jhyrachy your situation is not as serious as that.

What you are seeing is normal (for now )

The camera will startup and operate with 350mA current draw.

This may increase to 1.3 Amperes after motor operations. Use the Xiaomi USB supply  rated at 2 Amps

See https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/249

Sam

**Comment by hubmon** [comment]
@Jhyrachy 
PC USB port comply with USB spec. for that device, 500mA(.5A) MAX.
Why would anyone attempt to power this camera with that Power Source?

**Comment by jmtatsch** [comment]
This is getting a little bit off topic. Closing this for now.
