### ISSUE TITLE
Integration with motion

### ISSUE THREAD

**Issue by lolouk44** [EliasKotlyar/Xiaomi-Dafang-Hacks#26]
Not really an issue, more of a question of whether it is possible to integrate with motion (https://github.com/Motion-Project/motion)
Motion supports PTZ and I was wondering whether there's a way to modify your code to make it work with motion:
https://htmlpreview.github.io/?https://github.com/Motion-Project/motion/blob/master/motion_config.html#Options_Tracking

Thanks

**Comment by EliasKotlyar** [comment]
I assume that you want to run motion not on the dafang itself (what could also be possible). 

If the motion code provide some sort of "http-trigger", than it should be possible to make it work with the Dafang by simple configuration. If not, you need to implement some code in the motion-project, which will provide this triggers.

**Comment by edvm** [comment]
@EliasKotlyar i'm still waiting to get my dafang camera to start playing with it. Do you know if with its implemented on camera firmware to send photos to a REST API endpoint when motion is detected by the camera ? (to further process the image).  Thanks in advance,

**Comment by EliasKotlyar** [comment]
No its currently not implemented. But it can be implemented. The Source Code of the SDK provides a example for this.

**Comment by edvm** [comment]
@EliasKotlyar thanks! If you dont mind, could you please point me to that SDK ?

**Comment by EliasKotlyar** [comment]
Hello edvm,
The SDK is located here:
https://github.com/dim08/Ingenic-T10_20

You can use my toolchain to build this example code(libimp-samples):
https://github.com/EliasKotlyar/Xiaomi-Dafang-Software
