### ISSUE TITLE
Integration in Domoticz

### ISSUE THREAD

**Issue by remb0** [EliasKotlyar/Xiaomi-Dafang-Hacks#264]
I reviewed the cam and used this repo to change firmware. (thanks for it)
after that, it's working great in Domoticz
https://gadget-freakz.com/2018/04/xiaomi-dafang-1080p-smart-monitor-camera-review/

can this placed in the readme besides home-assistant?

**Comment by jmtatsch** [comment]
@remb0 sure, create a domoticz.md with the necessary info and make a pull request.

**Comment by jmtatsch** [comment]
Added to the integrations with 580df7795c25f3c72b143594b2d8cb74595e564a. Please make pull requests and help to improve it.
