### ISSUE TITLE
How to know what Xiaofang had t20 processor

### ISSUE THREAD

**Issue by pax0707** [EliasKotlyar/Xiaomi-Dafang-Hacks#265]
I was planing to get Xiaofang for porch.
How can I know the camera I order will have T20?

**Comment by qheuestc** [comment]
There are two ways to know it:
1.  Just tear down your device, and you will get the information on the main board.
2.  And also you can follow [installation guide](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/hacks/install_cfw.md), using cfw-1.0.bin under directory cfw_xiaofang.  If the cfw-1.0.bin flashed into xiaofang successfully, you can also observe that the blue light shining up for 5 seconds. Next, copy all the stuffs under firmware_mod to your root of sdcard, insert it to xiaofang, and it will boot from the sdcard, and you can connect to it through ssh using root/ismart12.  You can type _cat /proc/cpuinfo_ in the command line, and you will get following output:

> [root@xiaofang:bin]# cat /proc/cpuinfo 
system type		: bull
machine			: Unknown
processor		: 0
cpu model		: Ingenic Xburst V0.1  FPU V0.0
BogoMIPS		: 709.42
wait instruction	: yes
microsecond timers	: no
tlb_entries		: 32
extra interrupt vector	: yes
hardware watchpoint	: yes, count: 1, address/irw mask: [0x0fff]
isa			: mips32r1
ASEs implemented	:
shadow register sets	: 1
kscratch registers	: 7
core			: 0
VCED exceptions		: not available
VCEI exceptions		: not available
Hardware		: isvp
Serial			: 00000000 00000000 00000000 00000000

It also has some problems to migrate software for Dafang to Xiaofang now, I'm still trying to fix it.

**Comment by EliasKotlyar** [comment]
Hello everyone,

Here is the same output from the Dafang:
```
[root@DAFANGHACKS:~]# cat /proc/cpuinfo
system type		: bull
machine			: Unknown
processor		: 0
cpu model		: Ingenic Xburst V0.1  FPU V0.0
BogoMIPS		: 858.52
wait instruction	: yes
microsecond timers	: no
tlb_entries		: 32
extra interrupt vector	: yes
hardware watchpoint	: yes, count: 1, address/irw mask: [0x0fff]
isa			: mips32r1
ASEs implemented	:
shadow register sets	: 1
kscratch registers	: 7
core			: 0
VCED exceptions		: not available
VCEI exceptions		: not available

Hardware		: isvp
Serial			: 00000000 00000000 00000000 00000000
```
It seems that the Xiaofang has a slightly slower clock rate(709.42 vs 858.52)

Is there any difference in the serial Number? For example, i can imagine, that T20 Xiaofangs has a different starting char than the ARM-Xiaofang. If someony owns both: Can you please have a look and tell if there is any other difference?

**Comment by pax0707** [comment]
Guess I got the old one.

```
~ # cat /proc/cpuinfo
Processor       : ARM926EJ-S rev 5 (v5l)
BogoMIPS        : 200.29
Features        : swp half fastmult edsp java 
CPU implementer : 0x41
CPU architecture: 5TEJ
CPU variant     : 0x0
CPU part        : 0x926
CPU revision    : 5

Hardware        : SONiX SN98600 Development Platform
Revision        : 9302014
Serial          : 000014900827b000
~ # 
```

**Comment by jmtatsch** [comment]
It seems to be sold as XiaoFang S1.

**Comment by 4rianton** [comment]
[pax0707](https://github.com/pax0707)

were you able to flash your xiaofang camera with sonix chip?
