### ISSUE TITLE
Secure the RTSP stream with a password

### ISSUE THREAD

**Issue by rcheung81** [EliasKotlyar/Xiaomi-Dafang-Hacks#27]
Hello, I am able to log into RTSP without a user name and password. I am also able to SSH into the camera  but do not know how to set a password for RTSP. Can you give me instructions on how to do that?

**Comment by EliasKotlyar** [comment]
Hello @rcheung81 ,

You need to edit the action.cgi and add some parameters to the v4l2rtspserver strings:
```
-U foo:bar -U admin:admin
```

Refer to:
https://github.com/mpromonet/v4l2rtspserver

**Comment by swieprecht** [comment]
Hi Elias,
Can you treat me like a complete idiot, as it seems thats what I am...
Trying to setup a password but having no luck at all.
I've got it setup to the point I can see the rtsp on VLC and on Chrome, but not password is needed.
I can SSH in, but it isnt like standard linux so can't Sudo or Nano any changes. How do I do the above?
I tried to also do the password to get in to the web interface by changing the two files in config, but once done it just gave me connection refused messages when accessing the IP.
Scott

**Comment by EliasKotlyar** [comment]
Hello @swieprecht ,

You need to change the "action.cgi" and add some parameters to the "v4l2rtspserver"-calls. Like:

```
v4l2rtspserver -U admin:admin
```
Also, its not a normal linux, cause the camera is lacking resources. However you can install some programs using the crosscompile-environment.

**Comment by swieprecht** [comment]
If I run that on Putty I get: -sh: v4l2rtspserver: not found

**Comment by kszere** [comment]
Please try:
`/system/sdcard/bin/busybox nohup /system/sdcard/bin/v4l2rtspserver-master -fMJPG -U admin:pass &>/dev/null &
`

**Comment by link47** [comment]
Like @swieprecht I'm also looking to password protect the RTSP stream from outside access. 

Just reporting @kszere's solution worked for me, thanks!

**Comment by helio58** [comment]
Hi, I see this is closed.
I have try  @kszere's solution, but is not working anymore.
Is there another way ?
Thanks

**Comment by wojtulab** [comment]
You can also use a md5 password :)
Password schema is: 'md5(<username>:<realm>:<password>')

it will be sth like that:
`/system/sdcard/bin/v4l2rtspserver-master -A -R rbpi -U wb:f58a07f32ff7648ds8731f16a1acsdx1`

**Comment by helio58** [comment]
Sorry it was my misstake . It works well 👍

**Comment by Merwenus** [comment]
What was the mistake exactly? Because using this does exactly nothing, I still can see the stream without username and password.

`/system/sdcard/bin/busybox nohup /system/sdcard/bin/v4l2rtspserver-master -fMJPG -U myusername:randompassword>/dev/null &`

**Comment by mixpc** [comment]
Simple question. Is @kszere solution permament? If not, how could it be made permanent? Because I tried editing rtspserver.conf but after updating resolution via webinterface, my RTSPH264OPTS="-U user:password" vanished. Thank you!

**Comment by jmtatsch** [comment]
RTSPH264OPTS is overwritten once you change the resolution. Of course you could split the OPTS and set them individually. I would gladly accept a pull request.

**Comment by nik0** [comment]
@jmtatsch my last commit add the login/password/port configuration

**Comment by jmtatsch** [comment]
Awesome, thank you @nik0

**Comment by lloydwatkin** [comment]
For anyone else who tries to find this out, this is now configurable via 'video' option in the UI.

**Comment by S-P-J** [comment]
Is there any way or anywhere I can find simple instructions for a moron with one brain cell on how to hack my da fang camera as every site and instruction that I have looked at and read leaves me completely in the dark with vague instructions and words/instructions that I don't understand from the very begining?

**Comment by broros** [comment]
Is the stream connection secure?  ( Https) ??

**Comment by jmtatsch** [comment]
You can set a password to access it but I don't think it is encrypted.

**Comment by broros** [comment]
can it be brute-forced?

**Comment by jmtatsch** [comment]
Sure

**Comment by S-P-J** [comment]
I'm just trying to to get someone to indicate what setups are available to use with our Mi Walkie Talkies to make operating a boat easier. Voice activated transmit might be helpful.

Regards,
Shaun.

Sent from Yahoo Mail on Android 
 
  On Tue, 17 Sep 2019 at 3:12, jmtatsch<notifications@github.com> wrote:   
Sure
