### ISSUE TITLE
Restart bug and other small bug.

### ISSUE THREAD

**Issue by khseal** [EliasKotlyar/Xiaomi-Dafang-Hacks#272]
After rebooting from the menu, the camera does not work. When you turn off the power all okay.
Calibration repaired =)
The auto-update script does not work.
The sound is completely broken.
Do not remember the flipping of the image after reboot.
How to change the default password for web access?

**Comment by khseal** [comment]
It seems after correcting the calibration, all the reboot began to work fine.

**Comment by nik0** [comment]
What do mean by "not working" for the autoupdate ? How did you start it?

**Comment by khseal** [comment]
[root@DAFANG:sdcard]# ./autoupdate.sh -s
/system/sdcard/bin/curl.bin: '/system/sdcard/lib/libcrypto.so.42' is not an ELF file
/system/sdcard/bin/curl.bin: can't load library 'libcrypto.so.42'
New commit is available, some files may need to be updated

**Comment by khseal** [comment]
[root@DAFANG:sdcard]# ./autoupdate.sh 
./run.sh is excluded due to filter
Failed to get ./bin/bftpd
Failed to get ./bin/boa
Failed to get ./bin/curl.bin
Failed to get ./bin/dropbearmulti
Failed to get ./bin/getimage
Failed to get ./bin/v4l2rtspserver-master
./config/bftpd.conf is excluded due to filter
./config/boa.conf is excluded due to filter
./config/hostname.conf is excluded due to filter
./config/htpasswd.conf is excluded due to filter
./config/ldr-average.conf is excluded due to filter
./config/lighttpd.conf is excluded due to filter
./config/lighttpd.user is excluded due to filter
./config/ntp_srv.conf is excluded due to filter
./config/timelapse.conf is excluded due to filter
./config/v4l2rtspserver.conf is excluded due to filter
./config/video_size.conf is excluded due to filter
Bus error
Failed to get ./lib/libcrypto.so.42
/system/sdcard/bin/curl.bin: '/system/sdcard/lib/libcrypto.so.42' is not an ELF file
/system/sdcard/bin/curl.bin: can't load library 'libcrypto.so.42'
Failed to get ./lib/libmosquitto.so.1
/system/sdcard/bin/curl.bin: '/system/sdcard/lib/libcrypto.so.42' is not an ELF file
/system/sdcard/bin/curl.bin: can't load library 'libcrypto.so.42'
Failed to get ./lib/libmosquittopp.so.1
/system/sdcard/bin/curl.bin: '/system/sdcard/lib/libcrypto.so.42' is not an ELF file
/system/sdcard/bin/curl.bin: can't load library 'libcrypto.so.42'
Failed to get ./lib/libssl.so.44
/system/sdcard/bin/curl.bin: '/system/sdcard/lib/libcrypto.so.42' is not an ELF file
/system/sdcard/bin/curl.bin: can't load library 'libcrypto.so.42'
Failed to get ./lib/libusb-0.1.so.4
/system/sdcard/bin/curl.bin: '/system/sdcard/lib/libcrypto.so.42' is not an ELF file
/system/sdcard/bin/curl.bin: can't load library 'libcrypto.so.42'
Failed to get ./lib/libusb-1.0.so.0
/system/sdcard/bin/curl.bin: '/system/sdcard/lib/libcrypto.so.42' is not an ELF file
/system/sdcard/bin/curl.bin: can't load library 'libcrypto.so.42'
Failed to get ./lib/libz.so.1
/system/sdcard/bin/curl.bin: '/system/sdcard/lib/libcrypto.so.42' is not an ELF file
/system/sdcard/bin/curl.bin: can't load library 'libcrypto.so.42'
Failed to get ./scripts/common_functions.sh
/system/sdcard/bin/curl.bin: '/system/sdcard/lib/libcrypto.so.42' is not an ELF file
/system/sdcard/bin/curl.bin: can't load library 'libcrypto.so.42'
Failed to get ./scripts/debugInOsd.sh
/system/sdcard/bin/curl.bin: '/system/sdcard/lib/libcrypto.so.42' is not an ELF file
/system/sdcard/bin/curl.bin: can't load library 'libcrypto.so.42'
Failed to get ./scripts/detectionOff.sh
/system/sdcard/bin/curl.bin: '/system/sdcard/lib/libcrypto.so.42' is not an ELF file
/system/sdcard/bin/curl.bin: can't load library 'libcrypto.so.42'
Failed to get ./scripts/detectionOn.sh
/system/sdcard/bin/curl.bin: '/system/sdcard/lib/libcrypto.so.42' is not an ELF file
/system/sdcard/bin/curl.bin: can't load library 'libcrypto.so.42'
Failed to get ./scripts/detectionTracking.sh
/system/sdcard/bin/curl.bin: '/system/sdcard/lib/libcrypto.so.42' is not an ELF file
/system/sdcard/bin/curl.bin: can't load library 'libcrypto.so.42'
Failed to get ./scripts/iwlist.awk
/system/sdcard/bin/curl.bin: '/system/sdcard/lib/libcrypto.so.42' is not an ELF file
/system/sdcard/bin/curl.bin: can't load library 'libcrypto.so.42'
Failed to get ./scripts/ldr.sh
/system/sdcard/bin/curl.bin: '/system/sdcard/lib/libcrypto.so.42' is not an ELF file
/system/sdcard/bin/curl.bin: can't load library 'libcrypto.so.42'
Failed to get ./scripts/mqtt-autodiscovery.sh
/system/sdcard/bin/curl.bin: '/system/sdcard/lib/libcrypto.so.42' is not an ELF file
/system/sdcard/bin/curl.bin: can't load library 'libcrypto.so.42'
Failed to get ./scripts/mqtt-control.sh
/system/sdcard/bin/curl.bin: '/system/sdcard/lib/libcrypto.so.42' is not an ELF file
/system/sdcard/bin/curl.bin: can't load library 'libcrypto.so.42'
Failed to get ./scripts/mqtt-status-interval.sh
/system/sdcard/bin/curl.bin: '/system/sdcard/lib/libcrypto.so.42' is not an ELF file
/system/sdcard/bin/curl.bin: can't load library 'libcrypto.so.42'
Failed to get ./scripts/mqtt-status.sh
/system/sdcard/bin/curl.bin: '/system/sdcard/lib/libcrypto.so.42' is not an ELF file
/system/sdcard/bin/curl.bin: can't load library 'libcrypto.so.42'
Failed to get ./scripts/sendPictureMail.sh
/system/sdcard/bin/curl.bin: '/system/sdcard/lib/libcrypto.so.42' is not an ELF file
/system/sdcard/bin/curl.bin: can't load library 'libcrypto.so.42'
Failed to get ./scripts/timelapse.sh
/system/sdcard/bin/curl.bin: '/system/sdcard/lib/libcrypto.so.42' is not an ELF file
/system/sdcard/bin/curl.bin: can't load library 'libcrypto.so.42'
Failed to get ./www/configmotion.html
/system/sdcard/bin/curl.bin: '/system/sdcard/lib/libcrypto.so.42' is not an ELF file
/system/sdcard/bin/curl.bin: can't load library 'libcrypto.so.42'
Failed to get ./www/favicon.ico
/system/sdcard/bin/curl.bin: '/system/sdcard/lib/libcrypto.so.42' is not an ELF file
/system/sdcard/bin/curl.bin: can't load library 'libcrypto.so.42'
Failed to get ./www/index.html
/system/sdcard/bin/curl.bin: '/system/sdcard/lib/libcrypto.so.42' is not an ELF file
/system/sdcard/bin/curl.bin: can't load library 'libcrypto.so.42'
Failed to get ./www/logs.html
/system/sdcard/bin/curl.bin: '/system/sdcard/lib/libcrypto.so.42' is not an ELF file
/system/sdcard/bin/curl.bin: can't load library 'libcrypto.so.42'
Failed to get ./www/css/border-anim-h.gif
/system/sdcard/bin/curl.bin: '/system/sdcard/lib/libcrypto.so.42' is not an ELF file
/system/sdcard/bin/curl.bin: can't load library 'libcrypto.so.42'
Failed to get ./www/css/border-anim-v.gif
/system/sdcard/bin/curl.bin: '/system/sdcard/lib/libcrypto.so.42' is not an ELF file
/system/sdcard/bin/curl.bin: can't load library 'libcrypto.so.42'
Failed to get ./www/css/border-h.gif
/system/sdcard/bin/curl.bin: '/system/sdcard/lib/libcrypto.so.42' is not an ELF file
/system/sdcard/bin/curl.bin: can't load library 'libcrypto.so.42'
Failed to get ./www/css/border-v.gif
/system/sdcard/bin/curl.bin: '/system/sdcard/lib/libcrypto.so.42' is not an ELF file
/system/sdcard/bin/curl.bin: can't load library 'libcrypto.so.42'
Failed to get ./www/css/bulma-badge.1.0.1.min.css
/system/sdcard/bin/curl.bin: '/system/sdcard/lib/libcrypto.so.42' is not an ELF file
/system/sdcard/bin/curl.bin: can't load library 'libcrypto.so.42'
Failed to get ./www/css/bulma-quickview.1.0.1.min.css
/system/sdcard/bin/curl.bin: '/system/sdcard/lib/libcrypto.so.42' is not an ELF file
/system/sdcard/bin/curl.bin: can't load library 'libcrypto.so.42'
Failed to get ./www/css/bulma-switch.1.0.1.min.css
/system/sdcard/bin/curl.bin: '/system/sdcard/lib/libcrypto.so.42' is not an ELF file
/system/sdcard/bin/curl.bin: can't load library 'libcrypto.so.42'
Failed to get ./www/css/bulma.0.6.2.min.css
/system/sdcard/bin/curl.bin: '/system/sdcard/lib/libcrypto.so.42' is not an ELF file
/system/sdcard/bin/curl.bin: can't load library 'libcrypto.so.42'
Failed to get ./www/css/imgareaselect-animated.css
/system/sdcard/bin/curl.bin: '/system/sdcard/lib/libcrypto.so.42' is not an ELF file
/system/sdcard/bin/curl.bin: can't load library 'libcrypto.so.42'
Failed to get ./www/css/imgareaselect-default.css
/system/sdcard/bin/curl.bin: '/system/sdcard/lib/libcrypto.so.42' is not an ELF file
/system/sdcard/bin/curl.bin: can't load library 'libcrypto.so.42'
Failed to get ./www/css/unable_load.png
/system/sdcard/bin/curl.bin: '/system/sdcard/lib/libcrypto.so.42' is not an ELF file
/system/sdcard/bin/curl.bin: can't load library 'libcrypto.so.42'
Failed to get ./www/scripts/index.html.js
/system/sdcard/bin/curl.bin: '/system/sdcard/lib/libcrypto.so.42' is not an ELF file
/system/sdcard/bin/curl.bin: can't load library 'libcrypto.so.42'
Failed to get ./www/scripts/jquery-3.3.1.min.js
/system/sdcard/bin/curl.bin: '/system/sdcard/lib/libcrypto.so.42' is not an ELF file
/system/sdcard/bin/curl.bin: can't load library 'libcrypto.so.42'
Failed to get ./www/scripts/jquery.imgareaselect.pack.js
/system/sdcard/bin/curl.bin: '/system/sdcard/lib/libcrypto.so.42' is not an ELF file
/system/sdcard/bin/curl.bin: can't load library 'libcrypto.so.42'
Failed to get ./www/scripts/scripts.cgi.js
/system/sdcard/bin/curl.bin: '/system/sdcard/lib/libcrypto.so.42' is not an ELF file
/system/sdcard/bin/curl.bin: can't load library 'libcrypto.so.42'
Failed to get ./www/scripts/status.cgi.js

**Comment by nik0** [comment]
It seems that you have some binaries that are corrupted or not present
please check /system/sdcard/bin/curl.bin and '/system/sdcard/lib/libcrypto.so.42
Sorry but the autoupdate need some stuff to be installed first. Maybe we can work on this ...

**Comment by khseal** [comment]
[root@DAFANG:bin]# ./curl.bin
./curl.bin: can't load library 'libssl.so.44'
The library is in the folder.
File '/system/sdcard/lib/libcrypto.so.42 broken after startup  ./autoupdate.sh

**Comment by jmtatsch** [comment]
I have exactly the same error as khseal.
@khseal We should not use curl.bin directly because then the library path is not set and it cannot find 'libssl.so.44'.
`/system/sdcard/lib/libcrypto.so.42` exists in my setup but is empty.
That is likely the culprit, @nik0 can you upload a working one from your build?

**Comment by nik0** [comment]
I don't understand the script use curl (not curl.bin)
what is not working ? there is something not working when updating curl itself ?

**Comment by jmtatsch** [comment]
Sorry, in the repo there is a good libcrypto.so.42.
I really seem to have an incomplete checkout.

**Comment by nik0** [comment]
can you run curl command ?

**Comment by shinebar1001** [comment]
There is an issue if you run curl (without .bin) within a cgi... I couldn't figure it out until now.

**Comment by jmtatsch** [comment]
Very strange. I transplanted a fresh libcrypto.so.42, with which update was working for a while.
Now libcrypto.so.42 is 0 byte again.

**Comment by nik0** [comment]
I reproduced the issue.
The script get all the files from repo, and curl doesn't like when a dependant lib is overwritten
Sorry about that. I will add a filter no to override this libs
- To recover copy back the lib from the repo
- use the options "-x -b" of the scripts that seems to be safer

**Comment by nik0** [comment]
Did the update of the filter
as said I would recommend to use options "-x -b"

**Comment by khseal** [comment]
I checked. The script works. Nice!

**Comment by khseal** [comment]
The problem with rebooting the device has not disappeared. The problem appears periodically.

**Comment by aferraz** [comment]
@jmtatsch I just try and same problem on the same cam. The solution is refresh demo.bin

**Comment by jmtatsch** [comment]
@aferraz you mean you flashed the cfw again?

**Comment by aferraz** [comment]
@jmtatsch yes

**Comment by jmtatsch** [comment]
We are getting a bit off-topic here.
@khseal there is now support for setting a password via webui #330, can you please test that?
If with the current commit the other issues continue to bug you please open separated issues for them.

**Comment by khseal** [comment]
Change password work. Ok, i'm open other commit.
