### ISSUE TITLE
Master(21 April) = Multiple functions not working

### ISSUE THREAD

**Issue by msj33** [EliasKotlyar/Xiaomi-Dafang-Hacks#273]
Updated today as I have done multiple times before - Only to figure out that current Master seems to be in a "Beta" phase:-)

Note: Only my WPA config file was copied into new firmware update.

1: No autostart of video stream by default(Why!? - Enable at least one of them - So the end-user gets a product)
2: Old CGI Webinterface is broken (Layout seem gone- White page with function all aligned to the left)
3: New Layout - Looks promising, but has still multiple flaws(but maybe thats why its version 0.0.1:-))
4: Motion detection is not working properly - Dropdown is empty be default and area is 0,0,0,0!? - Nothing changes when trying to save the motion config - Just crashes the video streaming.
5: MQTT status gets NOK status, although MQTT control is set to Autostart.
6: Debug OSD - You can start it in Scripts - but stop button does nothing.
7: Very often Night-vision is enabled although light conditions are fine - Flicks back in 5-15 seconds.

All-in-all I have decided to rollback for now...

Kudos to all the great work being done here! - The new webiterface looks great and i'm eager to get both motion tracking and MQTT going here at some point - But looks like current Master needs some bugfix attention :-)

/Morten

**Comment by jmtatsch** [comment]
1. Good point - fixed in https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/commit/4f5dfd6a25565d1b66459119812f31b80cad77a7.
2. Its not broken, its the separation between content & style.
3. Tell us which, or even better - whip up some pull requests for them
4. Did you try with the fixes from today noon?
5. Is your mqtt.conf correct?
6. Possible bug
7. Set your LDR averaging to 15

**Comment by khseal** [comment]
LDR does not work on my camera. = (

**Comment by luisbarreto** [comment]
Hi,

I am also facing some issues with the new layout.
The previous one - downloaded in the begining of te week, was working great...

**Screenshot of the "homescreen"**

![screenshot 2018-04-22 23 31 44](https://user-images.githubusercontent.com/1310589/39100691-ae19e52e-4685-11e8-8e6a-171354d33890.png)

**Screenshot of the "scripts" screen**

![screenshot 2018-04-22 23 32 14](https://user-images.githubusercontent.com/1310589/39100692-b1ea3e74-4685-11e8-9786-fa6d43a096c5.png)

**Comment by gysmo38** [comment]
@luisbarreto
I think this is a problem with your browser cache. It cache index.html that redirect to /cgi-bin/status.cgi.bin
Try to open with full URL http://CAM-NAME/index.html
It should work.

**Comment by jmtatsch** [comment]
@luisbarreto and/or clean your caches

**Comment by luisbarreto** [comment]
My issue was solved deleting all cache related with the camera address.
Even before posting, I tried to forcefully reload the page with Ctrl + R || Shift + R without success (using chrome).
Thanks @jmtatsch

**Comment by msj33** [comment]
1) OK - Verified
2) OK
3) OK - Work in progress + Remove history cache = Just use the IP-adress(remove /cgi-bin/status.cgi)
4) Works if you configure and rename the motion.dist file - I forgot that:-)
But GUI confuses here, hence it from a user perspecitve looks like it can be configured here) 
Suggestion: If the mqtt.conf file is not found the GUI should refer to defining/creating the config file.
5) Works if you create the file - But same issue as above - Service can be enabled, although mqtt.conf file does not exist.
6) Yep - Stop button does nothing to OSD debug(although it looks reactive in GUI)
7) OK - Verified

Will split this into 3 new specific issues
1: Motion Detection webpage should check for valid motion.conf and/or be disabled for invalid/missing conf file.
2: MQTT services status should not possible to enable without a valid mqtt.conf
3: OSD Debug "Stop"-button have no effect on OSD.
