### ISSUE TITLE
Integration problems with HA

### ISSUE THREAD

**Issue by Pharizna** [EliasKotlyar/Xiaomi-Dafang-Hacks#275]
Thank you for this help https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/integration/homeassistant/homeassistant.md

But I have a question because I don't know if it is correct or have I a problem with my HA installation in my RPi3.

I tried streaming RTSP in VLC (in a PC) and it's working nice but in my HA (in a RPi3) I can only watch a frame every 4 seconds... and clicking over the component... I can see a "static" picture (full screen resolution) but after 30-40 seconds at least :(

![image](https://user-images.githubusercontent.com/3939655/39097282-95bbae20-465a-11e8-8ffd-c1eb9a5883f3.png)

Also, I can't any problem watching the video (slow motion?) in the DafangHacks main page... but with a lot timeout warnings from HA :(

![image](https://user-images.githubusercontent.com/3939655/39097423-32d75adc-465c-11e8-8c1e-69023a193f20.png)

**Comment by jmtatsch** [comment]
Cozy living room you have there 😄 
My stream is also very slow and buggy.
You could experiment with different resolutions and bitrates and tell us what you find..

**Comment by Pharizna** [comment]
Where can I change resolution and bitrate?

**Comment by jmtatsch** [comment]
Change resolution:
https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/wiki/change-the-resolution-of-the-Video
Change Bitrate:
https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/wiki/Parameters-for-setconf

**Comment by jmtatsch** [comment]
Resolution also via web interface since https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/commit/bd6939bb68518276842dc9aa65270b56b4fa6e02

**Comment by Pharizna** [comment]
Thanks, I saw the new option

![image](https://user-images.githubusercontent.com/3939655/39398524-508d633e-4b0f-11e8-9206-250f599da2f2.png)

but when I tried to set it 

![image](https://user-images.githubusercontent.com/3939655/39398526-65cc2398-4b0f-11e8-8a72-cd8d8de5a962.png)


... and ther RSTP server not start ... until a reboot (with not any change in resolution, of course ) :(

**Comment by jmtatsch** [comment]
What is in your rtspserver conf?

**Comment by jmtatsch** [comment]
For now you will manually have to copy that file. We should soon initialize the conf from the dist file.

**Comment by Pharizna** [comment]
What file I have to copy?

**Comment by Pharizna** [comment]
Thank you ... but using lower resolution the "new image" can't see in HA.

Now, I have a HA in a RPi3+ and also as a container in a QNAP NAS with the same problems :(

**Comment by Pharizna** [comment]
I've just saw a small change in your rtspserver.conf.dist   ( now RTSPH264OPTS="-W960 -H540") ... but the problem remains: The resolution has decreased in the Dafang Hacks page ... but now it dissapears from HA :(

Using not any resolution changes at least it appears in HA page

**Comment by jmtatsch** [comment]
> the video in HA-QNAP is now about 1 fps... against 0.2 fps in the RPi3
this means rpi3 is simply not fast enough to decode the h264 stream
I would recommend you to get an intel nuc or similar.
