### ISSUE TITLE
Automatic Discovery Publishing

### ISSUE THREAD

**Issue by maddox** [EliasKotlyar/Xiaomi-Dafang-Hacks#280]
It would be super helpful if discovery happened routinely. 

The discovery support for Home Assistant is SUPER helpful, but it is lost every time Home Assistant is restarted, which ends up being frequent for those that work on their system a lot.

It could even be nice if there was an endpoint to hit to trigger discovery, then maybe we could hit it when Home Assistant finishes booting.

**Comment by jmtatsch** [comment]
I agree, but I don't know what the right frequency would be.
A trigger from HomeAssistant would be even better, but I don't know if there exists one.
You are the expert, how would you realize this?

**Comment by maddox** [comment]
I tried this out and it works. I opened #281 to add it in.
