### ISSUE TITLE
Motion Detection webpage should check for valid motion.conf

### ISSUE THREAD

**Issue by msj33** [EliasKotlyar/Xiaomi-Dafang-Hacks#282]
**Issue:**
If a user does not create a motion.conf when setting up firmware first time, the Motion Detection webpage does not function correctly. This may lead to confusion about functionality for the end user.

**How to replicate:**
Start DAFANG without a motion.conf file.

**Suggestion:**
Motion Detection webpage should be either
-Disabled with web page notification about missing/invalid motion.conf
or
-Possible to enable/configure directly in the webpage.

**Comment by jmtatsch** [comment]
Should be fixed with 16b5c93431fe266a6c073493ba8ed6b18afe2d42. Please reopen if still an issue.
