### ISSUE TITLE
MQTT services(control+status) cannot be started without a valid mqtt.conf

### ISSUE THREAD

**Issue by msj33** [EliasKotlyar/Xiaomi-Dafang-Hacks#283]
**Issue:**
MQTT services(MQTT control + MQTT status) cannot be started or autorun without a valid mqtt.conf
This can be misleading to new DAFANG users.

**Steps to replicate:**
Use MQTT Services buttons/autorun toogle without a mqtt.conf file present.

**Suggestion:**
-Check for mqtt.conf file before buttons/toogle can be enabled + present a notification about missing/invalid.
or
- Check for a mqtt.conf file - If not present, give option to set up MQTT variables directly in Webinterface

**Comment by jmtatsch** [comment]
At least MQTT control should show an error message if you try to run it without mqtt.conf. 
https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/bd6939bb68518276842dc9aa65270b56b4fa6e02/firmware_mod/controlscripts/mqtt-control#L17
Does it not show for you?

**Comment by jmtatsch** [comment]
Warning should be visible now with
eb43daab6929fb4209cb5695e0ede624ba015580
before even starting the service.

**Comment by jmtatsch** [comment]
pre-initializing mqtt.conf doesn't really make sense as we cannot guess the users mqtt broker address.
