### ISSUE TITLE
Services: Debug-On-OSD - "Stop"-button have no effect on OSD-text.

### ISSUE THREAD

**Issue by msj33** [EliasKotlyar/Xiaomi-Dafang-Hacks#284]
**Issue:**
In Services: Debug-On-OSD the "Stop"-button have no effect on OSD-debug text.

**Steps to replicate**
1) Press Start on "Debug-On-OSD" service.
2) See OSD screen change to OSD Debug mode
3) Press Stop on "Debug-On-OSD" service.
4) The OSD-Debug does not revert back to normal OSD.

**Suggestion:**
The Stop-button should work:-)

**Comment by jmtatsch** [comment]
@ping would you please have a look at this?
The debug-on-osd in services seems to go up and down properly.
Could be the interface not passing the stop along properly...

**Comment by ping** [comment]
I just synced with master, wiped my camera's SD and reloaded everything except for ``config/``.
I ran the control script ``debug-on-osd stop`` from shell, and it did not work for me.

I had to resort to ``/system/sdcard/bin/setconf -k o -v "%Y-%m-%d  %H:%M:%S"``. This looks to be something with the controlscript.

**Comment by nik0** [comment]
It is OK (go on and off) also for me
For me the status page is confusing as the button seems to have no action. Maybe it would be better to have toggles?

**Comment by jmtatsch** [comment]
The service properly shuts down from the service pane. But the osd debug params are still set in the rtspserver until it is rebooted . I don’t really get why we need another  running loop for this. Seems as if a simple setconf and counter setconf would’ve been enough.

**Comment by nik0** [comment]
See https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/pull/296

**Comment by jmtatsch** [comment]
Should be fixed via #296. If not reopen.
