### ISSUE TITLE
Home Assistant: MQTT Auto discovery: Invalid connection: [MQTT-3.1.2-1] Incorrect protocol name: "MQIsdp"

### ISSUE THREAD

**Issue by msj33** [EliasKotlyar/Xiaomi-Dafang-Hacks#285]
**Issue:**
Trying to set up Home Assistant and DAFANG with MQTT discovery:
Invalid connection from (client @=192.168.x.x:x) : [MQTT-3.1.2-1] Incorrect protocol name: "MQIsdp"

**Steps to replicate**
1) Setup Home Assistant(0.67.1):
2) Enable MQTT discovery in configuration.yaml
mqtt:
  discovery: true
  discovery_prefix: homeassistant

3) Enable mqtt.conf
DAFANG mqtt.conf
renamed .dist withdefinition of:
-username
-password
-host
-auto discovery enabled (homeassistant)

**Result:**
Invalid connection from (client @=192.168.x.x:x) : [MQTT-3.1.2-1] Incorrect protocol name: "MQIsdp"

**Comment by jmtatsch** [comment]
Are you running mosquitto Broker or HA builtin?  You have to run mosquitto for now ...

**Comment by jmtatsch** [comment]
No feedback

**Comment by youqingkui** [comment]
me too

**Comment by youqingkui** [comment]
How to running mosquitto Broker?

**Comment by nbarrientos** [comment]
Thanks @OverFlow636! Definitely it'd be nice to add that to [homeassistant.md](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/integration/homeassistant/homeassistant.md) :)

**Comment by Chiunownow** [comment]
> to have the camera work with home-assistant's builtin mqtt server add this to the mqtt.conf
> `MOSQUITTOOPTS="-V mqttv311"`

I try it and the new error coming. 
> BrokerProtocolHandler Unhandled exception in reader coro: IncompleteReadError('0 bytes read on a total of 1 expected bytes',)
