### ISSUE TITLE
Support new DaFang revision without motor endstops

### ISSUE THREAD

**Issue by joshstrange** [EliasKotlyar/Xiaomi-Dafang-Hacks#287]
I could't figure out why the web UI wasn't coming up (also ssh/ftp) so I telnet'd into in and was running the run.sh commands one by one. I got to the `motor hcalibrate` one and the device spun around till the power cable was at the front and then made a noise like it was trying to go further but couldn't. That command never would complete. I tried turning it off and adjusting the base of the unit to a number of different orientations but none worked. I commented out that line and now the device will start up without issue. Has anyone else had this issue?

**Comment by jmtatsch** [comment]
I had almost the same issue once, the vertical motor was stuck to far up. While the camera was turned off, I moved it down a little. After that `motor vcalibrate` would run again and everything was fine.

**Comment by jmtatsch** [comment]
I just set up another fresh dafang. There seems to be a new revision and the calibration doesn't seem to work anymore because the endstops are not found anymore (maybe different sensor supplier or rationalised away). The camera turns like 2 times, winds up the cable and is stuck. We should not use hcalibrate and vcalibrate for now as it could really damage our units.

**Comment by jmtatsch** [comment]
Old Serial: DF3-00115712
New Serial: DF3-00344746

**Comment by eekdood** [comment]
Just received my first Dafang and I'm seeing the same thing. My serial is within 10k of your "New Serial" and the calibration is broken. Also experiencing the same issues as #291 with regards to connecting to WiFi, even after commenting out the calibration steps. I can confirm that the camera works with the native app and is also booting to the SD.

**Comment by EliasKotlyar** [comment]
Hello everyone,

I suppose that they have cheaped out at least one of the sensors per axis. The "old" Version of the Dafang used two sensors for detecting the limits, they were mounted on following pins:
#define MOTOR0_MIN_GPIO		77		
#define MOTOR0_MAX_GPIO		78	
#define MOTOR1_MIN_GPIO		41
#define MOTOR1_MAX_GPIO		60

Motor 0 = horizontal axis,
Motor 1 = vertical axis.

Can someone check how the GPIOs behave on the new Camera? I can then try to fix this issue by a different motor-driver. Remember to "uncomment" the motor-driver first, because you cannot use them while the motor-driver is loaded. You can rotate the camera "manually" to the end position and then check the pins.

**Comment by QcVictor** [comment]
Same behavior for me with latest release, nothing work led orange led blink after motor start calibration even with motor hcalibrate and motor vcalibrate commented. 
Luckily have saved previous setup and can go back online with this version.

**Comment by jmtatsch** [comment]
@EliasKotlyar  I tried to read the gpio values, nothing changes at the endstops.
I set up the gpios as follows:
```
  echo "41" > /sys/class/gpio/export
  echo "60" > /sys/class/gpio/export
  echo "77" > /sys/class/gpio/export
  echo "78" > /sys/class/gpio/export
  echo in > "/sys/class/gpio/gpio41/direction"
  echo in > "/sys/class/gpio/gpio60/direction"
  echo in > "/sys/class/gpio/gpio77/direction"
  echo in > "/sys/class/gpio/gpio78/direction"
  echo 1 > "/sys/class/gpio/gpio41/active_low"
  echo 1 > "/sys/class/gpio/gpio60/active_low"
  echo 1 > "/sys/class/gpio/gpio77/active_low"
  echo 1 > "/sys/class/gpio/gpio78/active_low"
```
I enabled active low because before all signals were always active before.

Fun facts: gpio 77 fails to export, it probably exists already. also launching there rtsp fails:

```
/system/sdcard/bin/v4l2rtspserver-master
failed to open ISP
IMP_System_Init() failed
Segmentation fault
```

**Comment by leetrungip** [comment]
Help==================================================
Starting the Dafang Hacks Custom Application Layer
==================================================
loaded common functions
Created etc directory on sdcard
Bind mounted /system/sdcard/root to /root
Bind mounted /system/sdcard/etc to /etc
Created cron directory
wpa_supplicant: Successfully initialized wpa_supplicant
Failed to open config file '/system/sdcard/config/wpa_supplicant.conf', error: No such file or directory
Failed to read or parse configuration '/system/sdcard/config/wpa_supplicant.conf'.
udhcpc: udhcpc (v1.22.1) started
Sending discover...
Sending discover...
Sending discover...
No lease, forking to background
initialized gpios
dropbear: 
bftpd: 
lighttpd: 
Startup finished!

**Comment by jmtatsch** [comment]
@leetrungip you have not set up wpa_supplicant.conf as requested in the instructions. Any your issue does not belong here.

**Comment by neroxps** [comment]
@EliasKotlyar  My device is different from the GPIO you set in [motor.h](https://github.com/EliasKotlyar/Xiaomi-Dafang-Software/blob/23d399f3a5fbd646552a16537b79093f07b3d045/drivers/misc/sample_motor/motor.h).

May I ask if is ok to adapt to the new version of DAFANG?
Is any informations should I provide？

### Device Information
- Model: DF3
- Serial number: DF3-00356***

### ALL GPIO

```
[root@DAFANG:gpio]# ls -al
total 0
drwxr-xr-x    2 root     root             0 Jan  1  1970 .
drwxr-xr-x   28 root     root             0 Jan  1  1970 ..
--w-------    1 root     root          4096 May 19 09:29 export
lrwxrwxrwx    1 root     root             0 Jan  1  1970 gpio25 -> ../../devices/virtual/gpio/gpio25
lrwxrwxrwx    1 root     root             0 Jan  1  1970 gpio26 -> ../../devices/virtual/gpio/gpio26
lrwxrwxrwx    1 root     root             0 Jan  1  1970 gpio38 -> ../../devices/virtual/gpio/gpio38
lrwxrwxrwx    1 root     root             0 Jan  1  1970 gpio39 -> ../../devices/virtual/gpio/gpio39
lrwxrwxrwx    1 root     root             0 May 19 09:33 gpio40 -> ../../devices/virtual/gpio/gpio40
lrwxrwxrwx    1 root     root             0 May 19 09:33 gpio43 -> ../../devices/virtual/gpio/gpio43
lrwxrwxrwx    1 root     root             0 May 19 09:33 gpio46 -> ../../devices/virtual/gpio/gpio46
lrwxrwxrwx    1 root     root             0 May 19 09:33 gpio47 -> ../../devices/virtual/gpio/gpio47
lrwxrwxrwx    1 root     root             0 May 19 09:33 gpio48 -> ../../devices/virtual/gpio/gpio48
lrwxrwxrwx    1 root     root             0 Jan  1  1970 gpio49 -> ../../devices/virtual/gpio/gpio49
lrwxrwxrwx    1 root     root             0 Jan  1  1970 gpio77 -> ../../devices/virtual/gpio/gpio77
lrwxrwxrwx    1 root     root             0 Jan  1  1970 gpiochip0 -> ../../devices/virtual/gpio/gpiochip0
lrwxrwxrwx    1 root     root             0 Jan  1  1970 gpiochip128 -> ../../devices/virtual/gpio/gpiochip128
lrwxrwxrwx    1 root     root             0 Jan  1  1970 gpiochip160 -> ../../devices/virtual/gpio/gpiochip160
lrwxrwxrwx    1 root     root             0 Jan  1  1970 gpiochip32 -> ../../devices/virtual/gpio/gpiochip32
lrwxrwxrwx    1 root     root             0 Jan  1  1970 gpiochip64 -> ../../devices/virtual/gpio/gpiochip64
lrwxrwxrwx    1 root     root             0 Jan  1  1970 gpiochip96 -> ../../devices/virtual/gpio/gpiochip96
--w-------    1 root     root          4096 Jan  1  1970 unexport
```

**Comment by neroxps** [comment]
Hi @EliasKotlyar ,

I am very happy that you have updated.

I tested the calibration and it worked well.

But there is a problem with the move. All moves take only one small step, and the specified number of steps cannot be performed.

```
[root@DAFANG:bin]# ./motor -d v
x: 1300
y: 350
speed: 900
[root@DAFANG:bin]# ./motor -d u 100
x: 1300
y: 356
speed: 900
[root@DAFANG:bin]# ./motor -d u 10
x: 1300
y: 362
speed: 900
[root@DAFANG:bin]# ./motor -d l -s 100
x: 1271
y: 362
speed: 900
```

**Comment by EliasKotlyar** [comment]
Ok, i have updated that motor-application again. Now the parameter should work. I have made a loop, cause it makes no difference if you send "1" or "1000" as parameter to the driver.

**Comment by neroxps** [comment]
@EliasKotlyar 

Now the motor command can move to the specified target, but it is very slow.

It's like walking step by step, very slow.

**Comment by MasterPIC** [comment]
What about restoring endstops for older Dafang? #445 
An user settings to enable endstops mode could be added too...
