### ISSUE TITLE
Invalid payload for MQTT cover in HA

### ISSUE THREAD

**Issue by callelj** [EliasKotlyar/Xiaomi-Dafang-Hacks#288]
After upgrading I now get this issue with MQTT autodiscovery in HA:

> 2018-04-23 23:54:18 WARNING (MainThread) [homeassistant.components.cover.mqtt] Payload is not True, False, or integer (0-100): -86
> 2018-04-23 23:54:18 WARNING (MainThread) [homeassistant.components.cover.mqtt] Payload is not True, False, or integer (0-100): 172

Seems like the values for position needs to be between 0 and 100.

**Comment by akinomeroglu** [comment]
I can repeat this too. I am at 0.68b in HA and updated FW with autoupdate.sh

**Comment by jmtatsch** [comment]
Yes, someone will have to implement a mapping between Dafangs absolute ticks and 0-100

**Comment by jezzamine** [comment]
I have the same error with 0.70.1 but with no value after ... (0-100):

**Comment by jmtatsch** [comment]
Fixed via #537
