### ISSUE TITLE
Motor calibration not working properly 

### ISSUE THREAD

**Issue by tie82** [EliasKotlyar/Xiaomi-Dafang-Hacks#289]
Hi,

when I bootup the Dafang and the horizontal and vertical calibration is executed, the lens stops most times in a slightly different position.
This makes motion tracking for a defined region impossible.

Is it possible to bring the lens every time in the same defined starting position?

Thanks

**Comment by jmtatsch** [comment]
I think that is exactly what the calibration is made for.
Have a look at https://github.com/EliasKotlyar/Xiaomi-Dafang-Software/blob/034ded14cc8e90cbab94bdf65075c9a08cee9461/motor/motor.c#L90 maybe you can improve upon it.
