### ISSUE TITLE
Motion Detection Sensitivity

### ISSUE THREAD

**Issue by gysmo38** [EliasKotlyar/Xiaomi-Dafang-Hacks#290]
Hello,

I use Domoticz script to start and stop Motion Detection.
I use http://CAM/cgi-bin/action.cgi?

I notice that enable motion detection put sensitivity to 4.

In action.cgi:
    motion_detection_on)
      /system/sdcard/bin/setconf -k m -v 4
    ;;
Could be replace 
    motion_detection_on_s1)
      /system/sdcard/bin/setconf -k m -v 1
    ;;
    motion_detection_on_s2)
      /system/sdcard/bin/setconf -k m -v 2
    ;;
    motion_detection_on_s3)
      /system/sdcard/bin/setconf -k m -v 3
    ;;
    motion_detection_on_s4)
      /system/sdcard/bin/setconf -k m -v 4
    ;;

Or have a way to  configure a prefered sensitivity.

**Comment by nik0** [comment]
Shoud be corrected with this https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/pull/295
