### ISSUE TITLE
Reboot not working consistently

### ISSUE THREAD

**Issue by MarkSanders54** [EliasKotlyar/Xiaomi-Dafang-Hacks#293]
If I try to reboot via Telnet or schedule a reboot via a script, the camera boots into the original firmware instead of the mod firmware. The mod firmware seems to freeze after operating for ~one week. So I was trying to deal with that by having the camera periodically reboot. What is strange is that if I reboot via the web interface, it seems to load back into the mod firmware as expected. I seem to be using the same binary via Telnet. So I don't understand why the behavior is different. Can any body else replicate this issue?

**Comment by joshstrange** [comment]
Have you also tried calling via the "api" `/cgi-bin/action.cgi?cmd=reboot` it uses the exact same reboot command `/sbin/reboot` but that's how the webui reboots.

**Comment by MarkSanders54** [comment]
Since I posted, I updated to the latest version of the mod. The last time I had updated was sometime in March. This is a clean install with only the wifi configuration being the only file that is changed. With the latest mod, all methods of rebooting (telnet "reboot", web ui, and wget the web api) result in the camera not loading into the mod firmware. I have to cycle the power to get back into the mod firmware. Does reboot work for anyone else?

**Comment by jmtatsch** [comment]
reboot just works fine for me via ssh & webui.
Telnet is deprecated and will be deactivated soon.
reboot currently does a soft reboot.  
maybe you can try a hard reset: https://www.shellhacks.com/remote-hard-reset-linux-server-reboot-not-work/

**Comment by MarkSanders54** [comment]
Thanks, but I tried the hard reset via ssh with the same results as before. The camera just reboots into the original firmware. 

I think this might be an issue with the sdcard. If the card can't be read after a reboot, this is the expected behavior. I think physically power cycling must cause the card to behave differently than with the reset. I'd try out a different card if the camera wasn't currently being used to monitor an active bird nest up close. I'll have to wait until the birds leave to investigate the card.

**Comment by CDKnightNASA** [comment]
I'm seeing this behavior in the latest mod firmware. When I was using a previous firmware (~1 month ago, I can probably find the version) I was able to reboot using the URL, but not the reboot command.

**Comment by jmtatsch** [comment]
Can you please try again with a current version? My 4 Dafangs just work fine.

**Comment by MarkSanders54** [comment]
I updated via the webUI. Then I did a hard reset. Once it booted, I tried to reboot via the webUI and it did not boot back into the Mod firmware. I'm assuming it booted into the original firmware based on the camera scanning back and forth. This was a few days ago. I have not tried updating since. 

Also to note, the camera image is no longer appearing. I get "Unable to load image".

**Comment by MarkSanders54** [comment]
I completely wiped the card and reloaded the files. The image is back, but reboot via any method still results in the original firmware starting up. I tried a few other micro sd cards, but those cards resulted in the camera booting straight into the original firmware. 

Anyone getting the ""Unable to load image" message should try manually updating all the files instead of using the WebUI update.

**Comment by reikred** [comment]
I have the same problem: Any form of reboot, whether GUI/WEB command, or powercycle, or ssh followed by "reboot" command leads to a camera that appears to have booted the original firmware. A press of the reset button leads to "ready to connect", and the android app can then add the camera , etc. I just added the camera again (I had to re0-add it, old config not working), and I also got an upgrade from 4.9.1.60 to 4.9.2.18 while at it. Camera now up with factory firmware.

So the question remains, why will Wyze V2 not do an unattended reboot, whether initiated from webgui, from ssh, or powercycle?

hardware: Wyze V2
software: openipc for Wyze V2 as of 2018-08-03 on micro-sdcard

**Comment by marcusramberg** [comment]
My Dafang seems to have the same problem.

**Comment by corvy** [comment]
I also experience the exact same problem. Hard boot with "echo b > /proc/sysrq-trigger" does not work either. I have to powercycle to get it online on the hack again. Anyone have any suggestions?

**Comment by sanjeewasam** [comment]
My RTSP stream stop every couple of days. I tried playing with Temp file settings etc and it improve but still every 2-3 days it has no signal to blue iris. I could view it via url

in cron job what should I add to reboot. I want to include a daily reboot task in daily cron folder
in putty as root when I type reboot the camera reboot. so is it just adding reboot as cron job or do I have to add something different?

Thanks

**Comment by jmtatsch** [comment]
yeah just reboot as cron job
