### ISSUE TITLE
MQTT during boot executes cmds

### ISSUE THREAD

**Issue by wojtulab** [EliasKotlyar/Xiaomi-Dafang-Hacks#294]
Hello,
is it normal that MQTT reads last executed command/s and execute its again?
For example evry reboot my cam sends status. 

How to disable it (retain)?

I noticed, that during mosquitto_sub.bin start it catches:
`[root@dzieci:sdcard]# /system/sdcard/bin/mosquitto_sub.bin -v -h "$HOST" -p "$PORT" -u "$USER" -P "$PASS" -t "${TOPIC}"/#
pokoj/dzieci/set motion_detection_off

^C
`

after killing by it with ctrl+c and re-run mosquitto_sub.bin ...there is the same situation evry time.

After another re-run and a few seconds waiting I saw sth more:
```
`[root@dzieci:sdcard]# /system/sdcard/bin/mosquitto_sub.bin -v -h "$HOST" -p "$PORT" -u "$USER" -P "$PASS" -t "${TOPIC}"/#
pokoj/dzieci/set motion_detection_off


                            öł´˙çë@   $
z@ ÎÍÁXĆ÷ĚYNn=iňş"˛3ĄI\`z)&7
Ň§ĚŔ°Z#1¤mzcßóŞŇě-Ád$p3ďÇĹeËlé°ŠdRyČůA=Nyz÷ŤŔ76ć#%G~ž*ibTCçŤ ĂQĎ^\zţ]*ÍX  "¸e
'˙˝˙Ö  "ŇyjA1°+šr3Âť/
GoĚgčy   ň/­Yá;÷| ÓżJlörAţś)6rŔÁ8č+řesŠßNm~ĘÎÉL
`ônzwWĽjöŇ
c- Ł#˙­@´]] a
šŮŔ\ţşľ`ęH ÷ÁÉkĺ2îR?TYPuTTYPuTTYPuTTYuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTY1;0xPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPu
TTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTT
YPuTTYPuTTYPuTTYPuTTYPuTTY
`
```

**Comment by jmtatsch** [comment]
Hmm, that must have been introduced by https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/commit/b546a196042069705527a211fda37a40f6537248

For absolute commands like `motion_detection_off` it kind of makes some sense that after a reboot it is reapplied.
But for relative e.g. motor commands it doesn't make sense at all.
To disable the retain you can remove the `-r` flags in mqtt-status-interval.sh and probably restart your mqtt server.

**Comment by wojtulab** [comment]
No. The problem was:
Retained messages coming from broker mqtt.
I cleaned it and the problem gone.
