### ISSUE TITLE
MQTT save snapshot with image optimization

### ISSUE THREAD

**Issue by wojtulab** [EliasKotlyar/Xiaomi-Dafang-Hacks#297]
If you want to get quality optimization at save snapshot on, use followin code:

#add to config/motion.conf
#configure snapshot quality/optimization
```
opt=1           #set optimization on on/off
scl=0          #set scale on/off
sclv="1/2"      #set scale eg 1/4 is 25% of file resolution
cln=1			#set cleanup on/off 
clnd=2			#set cleanup after N days
```

#add to scripts/detectionOn.sh
#after line '/system/sdcard/bin/getimage > $save_dir/$filename #&'
```
if [ "$opt" -eq 1 ]; then o="-optimize"; else o=""; fi
if [ "$scl" -eq 1 ]; then s="-scale $sclv"; else s=""; fi
if [[ "$opt" -eq 1 || "$scl" -eq 1 ]]; then
/system/sdcard/bin/jpegtran ${s} ${o} "$save_dir/$filename" > "$save_dir/$filename.jpg"
rm "$save_dir/$filename"
if [ "$cln" -eq 1 ]; then
/system/sdcard/bin/busybox find $save_dir/ -type f -mtime $clnd | xargs rm -f
fi
fi
```

**Comment by keesschollaart81** [comment]
Love the idea. Are you planning to pop a PR? Please note that the instruction misses this remark 

> add a # before the & on in '/system/sdcard/bin/getimage > $save_dir/$filename &' line

This script also copies the original snapshop to a second file, ending with and extra '.jpg'. I updated it like this:
```  /system/sdcard/bin/jpegtran ${s} ${o} -outfile $save_dir/$filename $save_dir/$filename ```
And now I only store (and publish via MQTT) the optimized file.

**Comment by wojtulab** [comment]
Yes, I could create a PR.

> add a # before the & on in '/system/sdcard/bin/getimage > $save_dir/$filename &' line

this is ok because with a '&' character script is not working properly. I know this character sends command to the background but in my tests script was down. So I recommend to add a '#' before '&'.

**Comment by ortegafernando** [comment]
@wojtulab Hi, did you have time to create the PR? It will be perfect to save and send (MQTT) reduced images.
Thanks

**Comment by ortegafernando** [comment]
Anyone?

**Comment by wojtulab** [comment]
sorry, I forgot about this small idea.
Tomorrow should be available to download.

**Comment by wojtulab** [comment]
PR created.
