### ISSUE TITLE
Schedule timelapses

### ISSUE THREAD

**Issue by remb0** [EliasKotlyar/Xiaomi-Dafang-Hacks#298]
I have a question:
is it possible to schedule timelapse?  I want to make a timelapse every day from 8 am to 8 pm.
How can I script or schedule this?

**Comment by MrPasty** [comment]
This would be a great feature, the jpg images are great but if it could automatically create a timelapse movie of the day it would be awesome!

**Comment by jmtatsch** [comment]
cron could be used to start or stop the time-lapse service

**Comment by DonEugraf** [comment]
> cron could be used to start or stop the time-lapse service

not trying to be a pain but would you share an example for newbies please?
I've managed to start the service but don't know how to stop it.
Thank you!
