### ISSUE TITLE
Currentpic resolution

### ISSUE THREAD

**Issue by crazikPL** [EliasKotlyar/Xiaomi-Dafang-Hacks#299]
Is there a possibility to change default resolution for snapshot taken from currentpic.cgi?
I have also XiaoFang cameras, and snapshots there are in a full HD instead of 1280x720

**Comment by joshstrange** [comment]
Looks like that endpoint just calls "getimage" but some initial googling doesn't point me towards documentation for this binary file. It was first committed here https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/commit/dde79a09491ef969d30a6baeaef31c1e61ef7b2b#diff-2334125236c6c2d67568d4bece977939 so maybe @EliasKotlyar can shed some more light. I also tried to call `-h` and `--help` on the file but it doesn't appear to take parameters

**Comment by jmtatsch** [comment]
Its the beauty of open source. Everyone can have a look https://github.com/EliasKotlyar/Xiaomi-Dafang-Software/blob/15d586ca4ff60d3794d4872a084eaaafe1c72299/v4l2rtspserver-tools/getimage.cpp .

**Comment by crazikPL** [comment]
Still don't get it. My C++ skills are... well. there is no such thing like my C++ skills :)

Now serious: for me it looks like there is no switch for resolution.

**Comment by jmtatsch** [comment]
Exactly, this is not supported yet.

**Comment by crazikPL** [comment]
Still hope it will be supported some day :)
