### ISSUE TITLE
H264 RTSP

### ISSUE THREAD

**Issue by EliasKotlyar** [EliasKotlyar/Xiaomi-Dafang-Hacks#3]
Current State of the development:
I can get a h264-stream of the camera. Unfortunately, this stream cannot be used to stream trough the LIVE555-RTSP Server. Here is a dump of mediafile:

```
General
Complete name                            : test.h264
Format                                   : AVC
Format/Info                              : Advanced Video Codec
File size                                : 132 KiB

Video
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : Baseline@L1.3
Format settings, CABAC                   : Yes
Format settings, RefFrames               : 2 frames
Width                                    : 320 pixels
Height                                   : 240 pixels
Display aspect ratio                     : 4:3
Frame rate                               : 25.000 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
```

I have no idea why this stream cannot be streamed trough the LIVE555. It seems that there is something missing. Maybe someone give it a try ?

**Comment by samtap** [comment]
If you have the code to retrieve h264 frames from the hardware, it's quite easy to integrate with i.e. v4l2rtspserver. I'm working on a v4l2rtspserver derived codebase for my XiaoFang rtsp server. It's a bit of a mess now, but I'll eventually put the xf-specific hardware stuff in a seperate module so it could support other cams as well. 
Have you looked at other formats most notably WebRTC for real-time streaming? RTSP doesn't work for embedding streams in a webpage :(.

**Comment by EliasKotlyar** [comment]
Okey i try to explain my current Problem:
1. I have succesfully compiled the live555 testStreamer and modified it to work from stdin. So you can provide a File and it will stream it trough h264. You can call it like this:
```
cat videofile.264 > h264streamer
```
It is streaming really fine without any problems when any of the testfiles(http://www.live555.com/liveMedia/faq.html#264-file) http://www.live555.com/liveMedia/public/264/

I have also created some Application, which will provide this bytestream from the camera and output it to its stdout. My Idea was to call it this way:
```
h264Snap >  h264streamer
```

Unfortunately, this works but i cannot get any result on the client side. Next Step was to create a file from the bytestream and to stream it over rtsp. Unfortunately, i am getting the same result. Streamer is working, but no picture.

I suppose there are some differences between the both files. Here are the both files for comparison:

https://gist.github.com/EliasKotlyar/36b8ac333765e96052c7aff3854d9b8c

**Comment by samtap** [comment]
RTSP while being a standard, doesn't mean all servers work with all clients. The reason VLC works well with my live555-based server is that it uses liblive555 for it's RTSP client implementation ;-). The example files you mention are very likely also created by live555.

I guess your end-goal is to have a standalone rtsp streamer. So messing with stuff that passes loads of data over a pipe is probably only useful for getting to know the video APIs of the camera SoC. H264 isn't anything like MJPEG that you would use for snapshots. So it seems there's a problem with the bytestream that doesn't provide frames in the proper format? I would focus on configuring the hardware to provide h264 frames (not a stream, it should be able to get you a complete frame on each read). Then you'll have to add some bits to make some frames into keyframes. Then feed each frame to live555 which will take care of all the RTSP stuff. 

I would love to help out but really lack time and loads of stuff to do for XiaoFang :(. I can only say v4l2rtspserver, for me, provided an ideal basis to work on, the code is clean and easily changed. I added some stuff to reconfigure the camera hw on the fly, so when I want to take a snapshot I reconfigure for MJPEG, grab a frame (which is literally just a jpeg file) and reconfigure for H264. I loose a couple of H264 frames but it's barely noticeable when viewing the stream. It's *much* faster compared to transcoding h264 frames to jpg on the cpu.

**Comment by EliasKotlyar** [comment]
Hey,

I managed to get this code working. Many thanks for the hint with the keyframes. I have found out that the real problem was, that you have to request them from the hardware. If you havent request them, it wouldnt send them at all. For now its working, but its not that "good". It has several issues , like hanging pictures etc etc.

Here is the code:
https://github.com/EliasKotlyar/Xiaomi-Dafang-Software/blob/master/videostreamer/ImpH264VideoDeviceSource.cpp

How often do you take a keyframe? For now i am taking it every frame, but it seems really bad to leave it that way. Maybe every second? 

Greatings
Elias

**Comment by tseel** [comment]
Hey,
Great to hear you've got it runnning. Every second is too much, the keyframes work as anchors in the video stream and should not occur too often.
This page has a good chapter on keyframes: http://www.lighterra.com/papers/videoencodingh264/
In short, for x264's default is 250 frames (8.3 seconds at 30fps) and the general recommendation for streaming videos seems to be one every 10 seconds.

Greatings

Thomas

**Comment by mvgrizzle** [comment]
How’s it going?

**Comment by EliasKotlyar** [comment]
I havent progressed yet. Anyone wants to help?

**Comment by EliasKotlyar** [comment]
Okey, i was able to compile 
https://github.com/mpromonet/v4l2rtspserver
and modify it to use the camera input. Now its streaming mjpeg/h264 very well. I still need to request IDRs every 2 seconds, but now its working. Thanks everyone!
