### ISSUE TITLE
Any Logs?

### ISSUE THREAD

**Issue by Simon0Harms** [EliasKotlyar/Xiaomi-Dafang-Hacks#302]
Hi, i tried to hack a xiofang and a dafang.
Will the hack produce any log outputs, if it works?

The cam isn't connecting  to the network and only record audio/video  files to the sd card.

**Comment by jmtatsch** [comment]
I don’t think there is a log on the sd card. Which would actually a good idea :)
your custom fw probably wasn’t flashed properly. Or your wpa_supplicant.conf is non existent. Or your motor is stuck. Try commenting the motor calibration in run.sh

**Comment by Simon0Harms** [comment]
I got the dafang working now, but i can't get the xiofang working.
I suppose the firmware hack don't work. I don't know if the xiofang have a blue led, i never seen one shining...

**Comment by Simon0Harms** [comment]
to  be honest, i have no clue...

**Comment by jmtatsch** [comment]
The h264/mjpeg server produces now log files on the sdcard
