### ISSUE TITLE
Too many requests to MQTT Server

### ISSUE THREAD

**Issue by akinomeroglu** [EliasKotlyar/Xiaomi-Dafang-Hacks#303]
Hello, 

I am using camera and integrated it to Home Assistant last night. I am using default mqtt config with discovery option and I just pointed a crt file for creating SSL connection between server and camera. I checked my pihole logs today and it seems that camera sent ~88.000 requests to my MQTT (which is in DigitalOcean) server in 15 hour.

Is this a normal behavior of MQTT communication or is there any mistake in configuration? 

Thanks & regards

**Comment by wojtulab** [comment]
Do you use / configure motion events via mqtt?

**Comment by akinomeroglu** [comment]
@wojtulab Yes but as far as I see this problem occur after #288

**Comment by wojtulab** [comment]
so simply disable autodiscovery

**Comment by akinomeroglu** [comment]
@wojtulab thanks for workaround will try it later but I think that this is a bug which can occur in some corner cases. So I don't close it for now.

**Comment by ioldfish** [comment]
@akinomeroglu Is this problem finally settled ？I met the same problem

**Comment by akinomeroglu** [comment]
this problem finally settled after fixing auto discovery for HA
