### ISSUE TITLE
Zoneminder Support

### ISSUE THREAD

**Issue by joshstrange** [EliasKotlyar/Xiaomi-Dafang-Hacks#308]
This is less of an issue/bug and more of wanting to document this for others. I have the Xiaomi Defang working in Zoneminder and I can give more information if desired. Most of the setup is quite simple and the zmNinja app (Android/iOS) is really neat for viewing your camera over the internet. The last missing piece that I was able to do today was to get the control scripts working so you can move your camera from within ZM or the app. Here is the control script https://gist.github.com/joshstrange/73a2f24dfaf5cd5b470024096ce2680f and if you need help just post here.

I'm not sure if anyone is even interested or I would have done a larger writeup, let me know if you are.

**Comment by aarora11** [comment]
Hi @joshstrange 

I've recently bought a dafang and I'm planning to use Zoneminder as well. Could you tell me if you ever got the night mode working? Also can you provide some detailed instructions on how to get the setup going. 

Thanks

**Comment by joshstrange** [comment]
Sure!

Night mode: I just turned this on in dafang web ui and it appears to work just fine not sure if you need to do anything other than that.

ZM Setup:

- Click "Add a Monitor"

## General Tab
- Name your camera
- Select Source Type of "Ffmpeg"
- Function (this depends on you, I picked modect)
- Left all other settings as-is on this tab (https://www.dropbox.com/s/j7j6andnl8s62jz/Screenshot%202018-04-30%2011.50.15.png?dl=0)

## Source Tab
- Source Path: rtsp://XX.XX.XX.XX:8554/unicast (Where XX.XX.XX.XX is the IP of your camera)
- Remote Method: UDP (This was the first I tired and it worked, not saying it's the only way.
- Target colorspace: 32 bit colour
- Capture Width: 1920
- Capture Height: 1080
- The rest as-is (https://www.dropbox.com/s/4ds8vfb1xohzpd1/Screenshot%202018-04-30%2011.52.42.png?dl=0)

## BEFORE you can configure the Control tab
- If you don't see this make sure you enabled OPT_CONTROL in the ZM options
- Copy the gist into a file named `Xiaomi.pm` in /usr/share/perl5/ZoneMinder/Control/ (May be different for your distro, make sure it has the same permissions as the other controls)
- Navigate to the control tab for your camera
- Click on the "Edit" next to "Control Type"
- Click "Add New Control" at the bottom of the popup
- Name: "Xiaomi Defang"
- Type: "Fffmpeg"
- Protocol: "Xiaomi"  (it has to match the .pm file from above)
- Can Reset: Yes
- Pic: https://www.dropbox.com/s/mm0aquc8s9zpul4/Screenshot%202018-04-30%2011.58.31.png?dl=0

### Move Tab
- Can move: yes
- Can move relative: yes
- Pic: https://www.dropbox.com/s/br17kax291ld2vk/Screenshot%202018-04-30%2011.59.42.png?dl=0

### Pan Tab
- Can pan: yes
- Pic: https://www.dropbox.com/s/912cznq42khwkkp/Screenshot%202018-04-30%2012.00.13.png?dl=0

### Tilt Tab
- Can tilt: yes
- Pic: https://www.dropbox.com/s/dafhvnsbv2v6bvr/Screenshot%202018-04-30%2012.00.44.png?dl=0

That's it, now save your new control type and head back to the control tab

## Control Tab
- Select "Controllable"
- Control Type "Xiaomi Dafang"
- Control Device: leave this empty
- Control Address: root:ismart12@XX.XX.XX.XX  (Where XX.XX.XX.XX is the IP of your camera)
- Pic: https://www.dropbox.com/s/gd2vrd8cj7d1cbj/Screenshot%202018-04-30%2012.02.19.png?dl=0

## Rest of the tabs I left as-is
- 100% up to you

That's about it, as far as events and movement go I haven't gotten those working 100%. It detects events but doesn't seem to persist them but that might be due to my docker setup for ZM. The basics (moving the camera around from the zmNinja app or the web ui) all work and I'm happy with it.

**Comment by aarora11** [comment]
Thanks! 😄 

I'll try this tonight!

**Comment by aarora11** [comment]
Tried this last night, can't get the Night mode running at all. Can you please guide me through how to get that running first. 

Thanks

**Comment by jmtatsch** [comment]
@joshstrange I took the liberty to copy your findings into the integrations part with 580df7795c25f3c72b143594b2d8cb74595e564a. I hope that is okay with you?

**Comment by joshstrange** [comment]
@jmtatsch Of course, I'm glad it might be able to help someone else! Thank you for doing that.

**Comment by boy1dr** [comment]
What is "The gist" that i need to copy in to file "Xiaomi.pm" ?
thanks

**Comment by helio58** [comment]
@joshstrange is it possible to use the "control part"  with Shinobi ?
Thanks

**Comment by joshstrange** [comment]
@boy1dr The gist is here: https://gist.github.com/joshstrange/73a2f24dfaf5cd5b470024096ce2680f

@helio58 Not sure about Shinobi, it looks like an alternative to ZoneMinder? You can look at the gist to see the endpoints I hit to move the camera. Should be possible

@swieprecht What isn't working? Is it not showing up as a type?

**Comment by swieprecht** [comment]
It all shows up, it's just it doesn't actually move it at all

**Comment by Daylights** [comment]
I have followed the @joshstrange guide with my hacked Xiaofang, in Zoneminder I get a ? icon as a view. The rtsp stream works in VLC though, any ideas?

**Comment by kawalis** [comment]
hi ,
I need some help with viewing my defang camera when im outside home using internet connection , I dont have static ip and I cant get one , so I cant do port forwarding or something like that , I have a windows VPS which has static ip , so please tell me how I can setup remote view.
thanks in advance

**Comment by Daylights** [comment]
> hi ,
> I need some help with viewing my defang camera when im outside home using internet connection , I dont have static ip and I cant get one , so I cant do port forwarding or something like that , I have a windows VPS which has static ip , so please tell me how I can setup remote view.
> thanks in advance

You can always make a port forward on your router, although the internet IP address you have to connect to may differ from time to time. You can use a Dynamic DNS provider (I use FreeDNS) for that, combined with a local client that updates the IP address to what the Dynamic address points to. So externally you connect to something like 'mycamera.dyndns.org' which always points towards your current internet IP.  When you have a decent router/firewall, it has something built in for Dynamic DNS, but you could run ddclient as a simple app for it on a linux server as well:

https://help.ubuntu.com/community/DynamicDNS

Note: you need to run the ddclient from your home, not from the VPS (obviously).

**Comment by Daylights** [comment]
I have been testing some settings, as the 'Ffmpeg' setup wasn't stable for me with the Xiaofang S1. Every now and then, the signal goes blue or ?

Right now I am using the following settings:

General
- Source type: Remote

Source
- Protocol: RTSP
- Method: RTP/Unicast
- Host name: <IP adress>
- Port: 8554
- Path: /unicast
- Color: 32 bit
- Width: 1280
- Height: 720
- RTSP Response Media URL: Enabled

In the S1 config I set the width/height to 1280/720 and 10 fps, VBR. Every now and then I see some 'Discarding partial/incomplete frame' in the ZM logs, which is seen in the recorded events (moving elements acting back/forward/back/forward), but at least the stream is stable.

What settings are you guys using for Zoneminder?
