### ISSUE TITLE
Donations

### ISSUE THREAD

**Issue by Dopeyr** [EliasKotlyar/Xiaomi-Dafang-Hacks#31]
Hi Elias,

You've obviously put a lot of work into this which benefits a lot of people! Do you accepts donations, however small?

Keep up the good work.

Thanks,
Andy.

**Comment by andybites** [comment]
I second this. The RTSP abilities that seem to be (mostly) working now have turned this camera from a brick into a really useful device, certainly worth a donation from my end.

Cheers

Andrew

**Comment by hubmon** [comment]
Willing to show my appreciation by donating also.

**Comment by everteam** [comment]
Good idea !!! I woulk like to offer a coffee or a beer :-)
