### ISSUE TITLE
Light doesn't stop flashing blue/orange

### ISSUE THREAD

**Issue by nniillaa** [EliasKotlyar/Xiaomi-Dafang-Hacks#313]
Hi,
I've been trying to do this to hack it and didn't know exactly what I was/am doing. 
I have cleared an SD card and formatted to Fat32, copied cfw-1.0.bin to the card and renamed it to demo.bin.
Pulled the power from the Xioami Xiaofang camera and put in the SD card. 
I held in the setup little white push button, plugged it in and then let go after 5s
The light was orange then started flashing blue/orange.

Unfortunately this is all that I can get to, it never changes and just keeps flashing. Not sure what I am meant to do next?

**Comment by jmtatsch** [comment]
Since 5225088 the camera writes a startup.log to the log directory of your sdcard. This can probably help you to figure out your issues. Closing this for now.
