### ISSUE TITLE
Flashing XiaoFang not working

### ISSUE THREAD

**Issue by nniillaa** [EliasKotlyar/Xiaomi-Dafang-Hacks#314]
Hi,
I have the Xioami Xiaofang camera. I am looking for the instructions of how I actually flash this firmware onto this device:

1. Format your microSD to FAT. NTFS, EXFAT etc. won't work.
**The above should say 'FAT32' as it's not FAT.**

2. Copy the CFW-Binary from step 1 to the formated microSD and rename it to "demo.bin". There should be no other files on the microSD! This is really important and it won't work if there are any other files on there.
**Done**

3. Shutdown the Dafang camera, remove the power cable and plug the microSD into the Dafang
**Done**

4. Hold the setup button on the Dafang camera
**Done**

5. Plug in the USB power cable
**Done - after how long do I release the setup button?**

6. Wait until the firmware has finished flashing (like 2 minutes). Disconnect the power as soon as the base starts moving.
**When I plug in the USB cable, it starts flashing orange, but then what? When do I disconnect the power?**

7. Remove the microSD and try to start the Dafang camera
**Done - After I had left the orange light flashing for like 5 minutes**

8. You should see the blue led shining up for 5 seconds (not blinking) before the base starts moving. 
**I have no base on this camera and no blue light starts flashing**

**Comment by jmtatsch** [comment]
We really need different HowTo's for the different cameras.

**Comment by jmtatsch** [comment]
Worked for me with a Samsung EVO Plus Micro SDHC 32GB

**Comment by jmtatsch** [comment]
Improved via d8284a1. Is it working for you now

**Comment by jmtatsch** [comment]
Since 5225088 the camera writes a startup.log to the log directory of your sdcard. This can probably help you to figure out your issues.

**Comment by alexymik** [comment]
Hi all,

I'm also having issues flashing the Dafang camera (tall motorized one). I have two of them, one flashed successfully and the other one won't work.

Here's what's happening:

- I put the SD card with `demo.bin` into the OFF camera. 
- I hold down the `SETUP` button on the base of the camera and connect the micro USB power.
- The orange LED comes on for three seconds, then then blue LED comes on.
- 10 seconds after power, I release the `SETUP` button
- LED stays blue for approx. 60 seconds after power.
- LED turns orange, relays(?) start clicking and camera starts calibrating.
- On the successful flash, the LED turned off for an additional minute at the 60 second mark.

I then disconnect the power, put the SD card back into my computer and delete the `time_lapse` folder and continue to try flashing the camera with no change.

Any ideas?

**Comment by jmtatsch** [comment]
Try with demo.bin on the known good sd card and/ or hold the button longer.

**Comment by alexymik** [comment]
Thanks for the tips.

I used the same SD card on both cameras, so I was able to flash successfully once with it.

I've also tried releasing the button at various times. I also found out that if you keep the button pressed, the camera starts speaking Chinese which startled me a bit 🤣

**Comment by jmtatsch** [comment]
So the second one works now?

**Comment by alexymik** [comment]
No, I have two cameras and two identical SanDisk 16gb microSD cards. I put the `demo.bin` on one of them and was able to flash one camera with it. I then put the modified firmware files on the second microSD card on the flashed camera and it successfully connected to wifi.

Now I am having trouble flashing the second camera with the same microSD card that worked in the first camera.

**Comment by jmtatsch** [comment]
Very strange, did you buy them at the same time?

**Comment by alexymik** [comment]
Yes, I bought both cameras from GearBest on Apr. 6th.

Also after some more attempts at flashing, it finally worked 🎉

Thanks for the tips!

**Comment by youqingkui** [comment]
Is xiaofang 1s hack sucess?

**Comment by jmtatsch** [comment]
Startup should work. Video seems to have issues. Op is not responding so I am closing this issue.
