### ISSUE TITLE
Another WiFi issue

### ISSUE THREAD

**Issue by wojtulab** [EliasKotlyar/Xiaomi-Dafang-Hacks#316]
Hello,
I found that some of us have problem with WiFi connection.
I was really surprised that is possible because it is very simple configuration inside wpa_supplicant

Last weekend I format my SD card and update it from this git with new files.
After that I have problem like you with WiFi.... Its strange.

My checklist is:

> 1. After format and move all files from git->sd card I restore config files for example my previous wpa_supplicant.conf file. The proper path is : /system/sdcard/config/wpa_supplicant.conf
> 2. Power adapter is ok. Voltage is ok.
> 3. LED flashes with orange color, so cam and hack are working.
> 4. I trace my router log for new dhck req and ping - no results.
> (_should be sth like that:
> Mon Apr 30 12:09:57 2018 daemon.info dnsmasq-dhcp[30053]: DHCPDISCOVER(br-lan) 18:fe:34:df:08:52
> Mon Apr 30 12:09:57 2018 daemon.info dnsmasq-dhcp[30053]: DHCPOFFER(br-lan) 192.168.1.41 18:fe:34:df:08:52
> Mon Apr 30 12:09:57 2018 daemon.info dnsmasq-dhcp[30053]: DHCPREQUEST(br-lan) 192.168.1.41 18:fe:34:df:08:52
> Mon Apr 30 12:09:57 2018 daemon.info dnsmasq-dhcp[30053]: DHCPACK(br-lan) 192.168.1.41 18:fe:34:df:08:52 DAFANG_)

Do you have any news in this case? I tried with many config without success.
For now my setting file:
cat wpa_supplicant.conf
```
ctrl_interface=/var/run/wpa_supplicant
ctrl_interface_group=0
ap_scan=1

network={
        ssid="$MYSIID"
        # Uncomment to connect to Hidden SSIDs
        #scan_ssid=1 
        key_mgmt=WPA-PSK
        pairwise=CCMP TKIP
        group=CCMP TKIP
        psk="$mypass"
        priority=2
}
```
In my opinion we should create workaround beacse I noticed that is popular issue.

**Comment by jmtatsch** [comment]
Since 5225088 the camera writes a startup.log to the log directory of your sdcard. This can probably help you to figure out your issues. Closing this for now.
