### ISSUE TITLE
Blank on load?

### ISSUE THREAD

**Issue by darkgeej** [EliasKotlyar/Xiaomi-Dafang-Hacks#317]
just uploaded the new mod files, and when i go to the ip i only get a blank page
no errors or anything

**Comment by jmtatsch** [comment]
Empty your caches

**Comment by darkgeej** [comment]
same, triede from my phone to, it hasn't visits the site before, still blank

**Comment by darkgeej** [comment]
and triede from chrome and safari

**Comment by darkgeej** [comment]
i dont think i reads the sd card files

**Comment by darkgeej** [comment]
got further but now it wants user(pass

**Comment by Dopeyr** [comment]
@darkgeej The default is root/ismart12

**Comment by jmtatsch** [comment]
How did you solve your issue?

**Comment by darkgeej** [comment]
yes :) finally, follow the guide step by step and then Bingo :D

**Comment by ronnyandre** [comment]
Same issue here. Cache not a problem, followed every step of the guide. How did you fix this?

**Comment by nik0** [comment]
Can you ssh the box ?
What is the URL you are trying to access ?
