### ISSUE TITLE
No Led or movement - bricked?

### ISSUE THREAD

**Issue by alexanderbecher** [EliasKotlyar/Xiaomi-Dafang-Hacks#318]
Hi, 

I've followed the instructions and got the hack running for about an hour constantly (Web access and RTSP tested). The camera then stopped working at all. Tried another power supply (and cable) but the led remains off and the camera doesn't move.  I've tried pushing the setup button but nothing.
Is it bricked? Is there anything I can do?

**Comment by alexanderbecher** [comment]
Already tried without sd card. Same result.

**Comment by peturdainn** [comment]
then I guess it is broken

**Comment by jmtatsch** [comment]
Try reflashing the custom fw.
If that doesn't help, try to establish a serial connection to see the bootlog.

**Comment by jmtatsch** [comment]
Since 522508869f219868095cfed4f1d967e2e2f70dff the camera writes a startup.log to the log directory of your sdcard. This can probably help you to figure out your issues. Closing this for now. Reopen when you have tried all suggestions.
