### ISSUE TITLE
How to use and change parameters via commands?

### ISSUE THREAD

**Issue by NatanAz** [EliasKotlyar/Xiaomi-Dafang-Hacks#321]
sorry for the noob question ,
I see people post how to change parameters like:
Playing Audio:
/system/sdcard/bin/ossplay /usr/share/notify/CN/init_ok.wav

where do i past this path? where is /system/sdcard ?
do i need to take out the sd card and do something? or directly to the camera some how?

Thanks!

**Comment by jmtatsch** [comment]
you need to ssh into your camera like 
`ssh root@myfangip`
default password is ismart12.
Please use the chat for such questions.
