### ISSUE TITLE
Restore original FW

### ISSUE THREAD

**Issue by Quentinvarquet** [EliasKotlyar/Xiaomi-Dafang-Hacks#322]
Hello i m using you firmware since two weeks (mostly to send the record to a ftp server, working well)

I would like to know if its possible to restore / Reset / install the original xiaomi firmware ?

**Comment by jmtatsch** [comment]
That should not be necessary, the only thing that is changed in the custom firmware is another bootloader path for booting from sdcard.
If you still want to do it, just flash an original fw as demo.bin
