### ISSUE TITLE
two way voice chat

### ISSUE THREAD

**Issue by silentbil** [EliasKotlyar/Xiaomi-Dafang-Hacks#323]
Hi,

I managed to run on vlc the rstp with audio , so i can hear 
but what if i want to send the camera an audio i recorded so it to play at runtime.
is this feature exist at all? any other way for two way communication? 

Thanks

**Comment by sanderdh** [comment]
If I may ask, how did you manage to get the audio working?

**Comment by jmtatsch** [comment]
Two way chat is not possible right now.
You can however record and play back correctly formatted wav files.

```
Playing Audio:
/system/sdcard/bin/ossplay /usr/share/notify/CN/init_ok.wav

Recording Audio:
/system/sdcard/bin/ossrecord /system/sdcard/test.wav 
```

It should work to have some text to wave cloud service, download the generated files and play them back. Would someone implement that?

**Comment by nik0** [comment]
I have a plan to do it (live talking) with something like WebRTC https://webrtc.org/
It should not be to complicated, but for now I don't have time (I am trying to improve the recorded audio first)
There is a way on github to make a "wish" list of features that people would like (someone else talked about onvif compatibility) ?

**Comment by jmtatsch** [comment]
We can label it as an enhancement and make it part of a milestone

**Comment by nik0** [comment]
Can you please test: https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/pull/354

**Comment by netRunner0** [comment]
https://github.com/KhaosT/homebridge-camera-ffmpeg/issues/174

**Comment by netRunner0** [comment]
Are there any advances in this issue?

**Comment by vevsvevs** [comment]
Guy, please keep working on it, it would be an incredible enhancement! 👍

**Comment by timdonovanuk** [comment]
Any luck? I wouldn't even know where to start!

**Comment by eschava** [comment]
> Any luck? I wouldn't even know where to start!

As a workaround, I use node-red with telegram plugin installed
So any voice message to the telegram is converted to the file having correct format and put to the camera using FTP. But it has some delay and is far from "two voice chat"

**Comment by gadget78** [comment]
just wanted to add would like to implement this some way... 
even a simple MQTT activity to play the onboard .wav files... (like we could on the older GUI)

**Comment by nik0** [comment]
audioplay binary is still able to play wav files
I had made an old PR to play audio from Webbrowser (using  https://webrtc.org/) but it is a nightmare to configure security bewteen the browser and the camera
I am open to ideas to send audio ...

**Comment by gadget78** [comment]
looking into the MQTT script `mqtt-control.sh` i can actually achieve what i was hoping already,
this so needs to be written somewhere were people can see this feature already exists !! 

by publishing a MQTT  (depending on your MQTT settings of course ! will quote default here)

`myhome/defang/play police.wav `

the device plays the police.wav file thats by default in the /media/ folder location on sdcard...
therefore i/we can record/put .wav's files of choice in the `media` folder, and have them activated by many means via MQTT...
for example this police.wav could be setoff/played when motion is triggered when its deemed armed, via homeassistant ...
or a doorbell chime could be placed here, and played when thats triggered etc etc .... 

sure theres a way that a recorded files can be sent easily, 
be it ftp/shh, or better yet via http on the same page area as pictures/videos are downloaded maybe?
then triggered here, or just left for MQTT
would work as a very rudimentary 2 way comm's ? slow yes, but would work on the few occasions its needed.... 

But for me the above prerecorded files and MQTT utilisation works EXACTLY as hoped !! 
and i hope this post can help others too :) 
im now going to incorporate this into a homeassistant `call for tea` `someone at door` buttons :)

**Comment by nik0** [comment]
This https://github.com/njh/petey need to be tried ...

**Comment by sblfc** [comment]
Is there a solution to this yet by any chance?

**Comment by nik0** [comment]
> Is there a solution to this yet by any chance?

Check this PR: https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/pull/1539

**Comment by sblfc** [comment]
> > Is there a solution to this yet by any chance?
> 
> Check this PR: #1539

Thank you so much! Days of googling and I couldn't find that.

**Comment by StevenJonSmith** [comment]
This functionality should now be available in the beta stream, after pull request [#1743](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/pull/1743).

Feel free to test it and let me know. I'd personally like to make it better if I can find some detail on audio playback on the camera and potential to create and play a stream rather than create a file and send it to be played.
