### ISSUE TITLE
Add configuration information to config/wpa_supplicant.conf.dist

### ISSUE THREAD

**Issue by tomers** [EliasKotlyar/Xiaomi-Dafang-Hacks#324]
In the file `hacks/install_cfw.md` there are the following instructions:
> - Copy config/wpa_supplicant.conf.dist to config/wpa_supplicant.conf
> - Modify the file config/wpa_supplicant.conf on the microSD to match your wifi-settings

The thing is that this file is minimal, and it is missing all the documentation regarding the various configuration options available.

Reference for similar file with all relevant information:
https://w1.fi/cgit/hostap/plain/wpa_supplicant/wpa_supplicant.conf

I suggest either add the above link to these lines at `hacks/install_cfw.md`, or replace the `config/wpa_supplicant.conf.dist` file with the above linked file, which is much bigger, as it contains many commented lines.

**Comment by jmtatsch** [comment]
Fixed via  c21c5b4
