### ISSUE TITLE
Home assistant integration error

### ISSUE THREAD

**Issue by mr-orange** [EliasKotlyar/Xiaomi-Dafang-Hacks#326]
Hi I have a lot of warning in home assistant about the dafang camera:

Payload is not True, False, or integer (0-100): down_endstop
11:15 components/cover/mqtt.py (WARNING)

This led the cover button for camera movement not working at all.

I'm running on the latest version and my dafang is positioned on an high shelf so I set my camera to point the lens all down.

**Comment by akinomeroglu** [comment]
Hello,

This is a known bug #288 

Is other commands like turn off led etc works for you?

**Comment by jmtatsch** [comment]
closing this in favour of #288
