### ISSUE TITLE
Change resolution error

### ISSUE THREAD

**Issue by khseal** [EliasKotlyar/Xiaomi-Dafang-Hacks#331]
Video resolution set to -W1280 -H720
Restarting H264 RSTP server
Starting v4l2rtspserver-master Invalid Argument ? Invalid Argument ? Invalid Argument ? Invalid Argument ?
No corret load web, after press back button.

**Comment by khseal** [comment]
![web](https://user-images.githubusercontent.com/11374629/39687482-4a384cdc-51d7-11e8-83ab-19e7b44a2198.png)

**Comment by mr-orange** [comment]
Also I have the same problem and yes I have correctly configured the  rtspserver.conf file.

**Comment by khseal** [comment]
> Starting v4l2rtspserver-master Invalid Argument ? Invalid Argument ? Invalid Argument ? Invalid Argument ?
This error occurs when there is no file rtspserver.conf.dist, but if it is rtspserver.conf is created empty.

**Comment by jmtatsch** [comment]
The non-existent rtspserver.conf should be fixed with 55fde785d75bb4ff4d3647224ca726a0df296b85
@ping could you please have a look why the web interface is disfigured after changing the resolution?
I have no idea why that is happening.

**Comment by jmtatsch** [comment]
Thank you @ping , this issue should be fixed with 0a58b14425a74062b86e63c17cc393a9fe11726a. If not please reopen.
