### ISSUE TITLE
Sync captured motion images to Dropbox

### ISSUE THREAD

**Issue by CDKnightNASA** [EliasKotlyar/Xiaomi-Dafang-Hacks#333]
I use Dropbox as my cloud solution and I have been able to get the Motion generated images to go to the cloud (almost) immediately.

Here's how I do it:

I have a Linux system with Dropbox running and I've NFS-shared a folder from within that. My username in Linux is "cdknight", I've added the following to `/etc/exports`:

```
/home/cdknight/Dropbox/cam 192.168.100.0/255.255.255.0(rw,sync,no_subtree_check,
all_squash,anonuid=1000,anongid=1000)

```
I then created a script "`/system/sdcard/config/autostart/nfs`" that contains:

```
mount -o nolock -t nfs 192.168.100.5:/home/cdknight/Dropbox/cam /system/sdcard/motion/stills
```

And, of course, enabled save_snapshot in `/system/sdcard/config/motion.conf`.

Works like a champ! I'm tempted to try recording videos on motion detection...

Love this project, I bought a bunch of cams for security around the house!

**Comment by Dennisd80** [comment]
Thank you, finally is was able to adept this to use it with my domoticz!
