### ISSUE TITLE
Connection problems

### ISSUE THREAD

**Issue by dmolner** [EliasKotlyar/Xiaomi-Dafang-Hacks#336]
Hello,

I have two cams.
First work well for timw with hack cfw 1.1 and initial hack
Now I change for last version and only work for few minutes, later not work. I can't connect by http, ssh or telnet after reboot.
The second cam hacked with cfw1.3 work with new hack but not with older.

Is possible these problem?
Need I hack with new firmware for new version?
Best Regards,
David.

**Comment by darookee** [comment]
I have a similar problem. I can't connect reliably from only one computer in my network, all the others don't seem to have a problem. I can open the WebUI without a problem, use `ssh` or connect with VLC from my 'work PC', but not from my 'server' (which is running HomeAssistant).  From that one I can't get `ssh` to connect at all, using `telnet` on port 80 or `curl` works sometimes. I already tried to rule out any networking issues. The cam can connect to MQTT running on the same machine without problems.
I already tried updating to cfw1.3 (from cfw1.2) but that did not change anything.
[This](https://gist.github.com/darookee/6f4c0a26a9f28a521ff60be0ef73e145) is my `startup.log`. The IP it get's as it's DNS is the 'server' which cannot connect to it.

**Comment by dmolner** [comment]
Where I can found startup.log @jmtatsch

**Comment by jmtatsch** [comment]
sdcard/log/startup.log

**Comment by dmolner** [comment]
I can't found

**Comment by jmtatsch** [comment]
are you sure you running an up to date version of the repo?

**Comment by jmtatsch** [comment]
Closing this for now. Reopen if still an issue.
