### ISSUE TITLE
v4l2rtspserver problem

### ISSUE THREAD

**Issue by khseal** [EliasKotlyar/Xiaomi-Dafang-Hacks#337]
It runs without problems, but there is no picture on the ip address.
When you click the start button in the services. The button is spinning endlessly.
When starting from the console, everything works
/system/sdcard/bin/v4l2rtspserver-master -S -W1600 -H900

**Comment by khseal** [comment]
Logs after stratup and try connect vlc
LAME 3.100 32bits (http://lame.sf.net)
Using polyphase lowpass filter, transition band: 16538 Hz - 17071 Hz

[NOTICE] /home/osboxes/SRC/Xiaomi-Dafang-Software/v4l2rtspserver-master/src/main.cpp:646
	Create ALSA Source.../dev/dsp
[NOTICE] /home/osboxes/SRC/Xiaomi-Dafang-Software/v4l2rtspserver-master/src/ALSACapture.cpp:51
	Open ALSA device: "/dev/dsp"Changed OSD

[NOTICE] /home/osboxes/SRC/Xiaomi-Dafang-Software/v4l2rtspserver-master/src/DeviceSource.cpp:87
	begin thread
[NOTICE] /home/osboxes/SRC/Xiaomi-Dafang-Software/v4l2rtspserver-master/src/ALSACapture.cpp:68
	Channel Count:1
[NOTICE] /home/osboxes/SRC/Xiaomi-Dafang-Software/v4l2rtspserver-master/src/DeviceSource.cpp:87
	begin thread
[NOTICE] /home/osboxes/SRC/Xiaomi-Dafang-Software/v4l2rtspserver-master/src/main.cpp:151
	Play this stream using the URL "rtsp://192.168.5.39:8554/unicast"

[NOTICE] /home/osboxes/SRC/Xiaomi-Dafang-Software/v4l2rtspserver-master/src/ServerMediaSubsession.cpp:24
	Creating Source...

[NOTICE] /home/osboxes/SRC/Xiaomi-Dafang-Software/v4l2rtspserver-master/src/ServerMediaSubsession.cpp:50
	Creating Sink for format : video/MP2T
[NOTICE] /home/osboxes/SRC/Xiaomi-Dafang-Software/v4l2rtspserver-master/src/ServerMediaSubsession.cpp:24
	Creating Source...

[NOTICE] /home/osboxes/SRC/Xiaomi-Dafang-Software/v4l2rtspserver-master/src/ServerMediaSubsession.cpp:41
	Creating normal Source...
[NOTICE] /home/osboxes/SRC/Xiaomi-Dafang-Software/v4l2rtspserver-master/src/ServerMediaSubsession.cpp:50
	Creating Sink for format : audio/MPEG
[NOTICE] /home/osboxes/SRC/Xiaomi-Dafang-Software/v4l2rtspserver-master/src/ServerMediaSubsession.cpp:24
	Creating Source...

[NOTICE] /home/osboxes/SRC/Xiaomi-Dafang-Software/v4l2rtspserver-master/src/ServerMediaSubsession.cpp:50
	Creating Sink for format : video/MP2T
[NOTICE] /home/osboxes/SRC/Xiaomi-Dafang-Software/v4l2rtspserver-master/src/ServerMediaSubsession.cpp:24
	Creating Source...
RTCPInstance::RTCPInstance error: totSessionBW parameter should not be zero!
RTCPInstance::RTCPInstance error: totSessionBW parameter should not be zero!

**Comment by khseal** [comment]
Formatted the memory card, loaded a new cfw. Everything worked, but after the change the resolution all broke down.
The problem is related to changing the resolution.

**Comment by sbrandsborg** [comment]
I get the same problem. it happens when i change resolution.

I have tried reformatting the SD card and getting the newest fw.

**Comment by Majon-Thanaton** [comment]
I've been having the same trouble, as soon as I alter the resolution via the web interface, I just can't get the camera to display a picture.
A format and copying across the firmware got it working again.

I've also tried altering the rtspserver.conf file to specify "-W1920 -H1080", but it seems to only follow the first dimension; I either get a stream that is 1280x1080, or 1920x720, depending on if I put the height or the width at the start of the argument.

**Comment by wojtulab** [comment]
In my scenario I removed all config from conf file so my CMD is simple: 
/system/sdcard/bin/v4l2rtspserver-master -U userpass 
this setting is also good.

**Comment by moooff** [comment]
i have my dafang since today and i encountered the same problem.

I already edited my rtspserver.conf to specify different resolutions manually however it does not work as stated by @Majon-Thanaton. I also could not switch to 1920x1080 (full HD) mode at all. 

For example if i set my resolution to 1600 x 900 in the config file and reboot the camera i only get a
1600 x 720 video stream. But i see the following active program in the output of  `ps`

` 210 root      167m S    /system/sdcard/bin/v4l2rtspserver-master -W 1600 -H 900`

Therefore the server is started with the correct settings. 
But it clearly ignore the height setting however if i restart the server manually (!!!) with the following commands i get a 1600x900 steam.
```
kill 210
 /system/sdcard/bin/v4l2rtspserver-master -W 1600 -H 900
```
Very Strange ....

**Comment by shinebar1001** [comment]
I remember this behaviour from my tests with setconf - it seems to have something to do with the processing of blanks from the config files. Unfortunately I never found the cause. Probably it's something similar here?

**Comment by moooff** [comment]
ok got it... you need to fix 
`/system/sdcard/controlscripts/rtsp-h264`
you need to change the line 
`/system/sdcard/bin/busybox nohup /system/sdcard/bin/v4l2rtspserver-master "$RTSPH264OPTS" >> "$LOGPATH" &`
to (remove the two double quotes around the variable)
`/system/sdcard/bin/busybox nohup /system/sdcard/bin/v4l2rtspserver-master $RTSPH264OPTS >> "$LOGPATH" &`
This fixes the problem with the width and height ... however it is still not possible to set the camera to 1920x1080

**Comment by Dopeyr** [comment]
I was just about to log this also. `$RTSPH264OPTS` needs " removing or it does not start.

**Comment by jmtatsch** [comment]
@Dopeyr Thank you for fixing this.
