### ISSUE TITLE
Compiling new software for webrtc

### ISSUE THREAD

**Issue by iashwinprasada** [EliasKotlyar/Xiaomi-Dafang-Hacks#34]
I wanted to know if it's possible to compile Janus or similar webrtc gateway for this linux? Can anybody point in the right direction

**Comment by EliasKotlyar** [comment]
Hello @iashwinprasada ,

That should be possible, but its a huge job. According to https://janus.conf.meetecho.com/docs/DEPS.html, there are at least 5 dependencys which need to be compiled before you can compile it.

**Comment by iashwinprasada** [comment]
Yes! Seems like it, I have already compiled a couple of them and looking forward to the remaining. Hopefully it goes well. 

It'll be really interesting to make it work over webrtc.

**Comment by iashwinprasada** [comment]
im stuck at compiling gnutls for the camera, any ideas?

/mips-linux-gnu/bin/ld: cannot find -lp11-kit
collect2: error: ld returned 1 exit status
Makefile:1733: recipe for target 'libgnutls.la' failed
make[3]: *** [libgnutls.la] Error 1
