### ISSUE TITLE
Image flip parameter is not persisted 

### ISSUE THREAD

**Issue by jmtatsch** [EliasKotlyar/Xiaomi-Dafang-Hacks#341]
After each reboot, rtsp flip has to be set again which is annoying.

**Comment by anup-d** [comment]
Just paste this line in your run.sh file and save:
/system/sdcard/bin/setconf -k f -v 1

Don't forget to reboot after making the change.

**Comment by freddujour** [comment]
it works! Thanks

**Comment by nik0** [comment]
I close as it seems to be working

**Comment by andrempo** [comment]
Not working for me. After reboot the image is not fliped.
