### ISSUE TITLE
Cron

### ISSUE THREAD

**Issue by dmolner** [EliasKotlyar/Xiaomi-Dafang-Hacks#343]
Hello,
I need help for edit crontab.
I have older Yi ant and I can modify for take pictures but in Dafang I need help.
[https://github.com/fritz-smh/yi-hack](url)
Thakyou

Is possible apply this code for these cam?

**Comment by dmolner** [comment]
Read txt file over Internet for turn the camera to the value I put in this file.

**Comment by jmtatsch** [comment]
With the latest version you should be able to:

Create a new crontabs directory (because the default /var/spool/cron/crontabs is a link to /tmp and will not survive a reboot):
```
mkdir -p /system/sdcard/cron/crontabs
```
Edit your crontabs:
```
crontab -c /system/sdcard/cron/crontabs -e
```
List your crontabs:
```
crontab -c /system/sdcard/cron/crontabs -l
```
Start your crond, this would need to be added to the run.sh:
```
crond -L /system/sdcard/log/crond.log -c /system/sdcard/cron/crontabs
```

**Comment by jmtatsch** [comment]
Should work with 11e110d00056e3abe0ba2d9121f087ef68d2d171. If not reopen.

**Comment by dmolner** [comment]
Hello,
I have this line in cron
`*/2 * * * * root system/sdcard/scripts/radar.sh`
I change radar.sh with chmod +x
But not work
If I write sh radar.sh works fine.

**Comment by nik0** [comment]
Missing leading / ? Should be /system....

**Comment by dmolner** [comment]
@nik0 
I test but not work.
If in console write 
` env -i sh /system/sdcard/scripts/radar.sh
This is the answer
`/system/sdcard/scripts/radar.sh: line 11: curl: not found`

**Comment by nik0** [comment]
in line 11 or radar.sh you should write: `/system/sdcard/bin/curl ...`

**Comment by dmolner** [comment]
@nik0 
Now I have this error.
`/system/sdcard/bin/curl.bin: can't load library 'libssl.so.44'`

**Comment by nik0** [comment]
What does the "env" command says ?
You should have the variable: LD_LIBRARY_PATH set to '/system/sdcard/lib/:/thirdlib:/system/lib'
For that you need to add at beginning of your script:
`export LD_LIBRARY_PATH='/system/sdcard/lib/:/thirdlib:/system/lib'`

**Comment by dmolner** [comment]
@nik0 
Work very well.
Thanyou
