### ISSUE TITLE
Ftp connection

### ISSUE THREAD

**Issue by helio58** [EliasKotlyar/Xiaomi-Dafang-Hacks#347]
Hi again and big thanks with the color fix #344.

When connecting with ftp I log in as root and can only access to this directory.
How can I change to access the sdcard  when I log in?
Thanks

**Comment by nik0** [comment]
Edit` /system/sdcard/config/bftpd.conf`
and change the line 
` ROOTDIR="/" ` and restart bftpd or reboot

**Comment by helio58** [comment]
Thanks nik0
