### ISSUE TITLE
Delete images older than X days

### ISSUE THREAD

**Issue by anup-d** [EliasKotlyar/Xiaomi-Dafang-Hacks#348]
This command would usually work in a linux environment:
find /path/* -mtime +X -exec rm {} \;

But the find command on Dafang's busybox edition is very limited and does not support -mtime and -exec.

Is there an alternate way to achieve this as my SD card keeps getting full and I am having to manually delete images every couple of days now?

**Comment by nik0** [comment]
mtime and exec should exist in the last version of installed busybox,
try `/system/sdcard/bin/busybox find `
