### ISSUE TITLE
installing packages on the camera

### ISSUE THREAD

**Issue by lolouk44** [EliasKotlyar/Xiaomi-Dafang-Hacks#35]
Hi Elias,

I would like to install packages on the camera, how might one go about doing this?
I want to install probably mosquitto (and maybe python) to control the LEDs via MQTT and send a few other states to my home automation software (home-assistant), I'm also thinking of potentially installing motion to handle motion detection.
I know where to get the software but I'm not sure where to start from and where to install the files to.

Thanks

**Comment by EliasKotlyar** [comment]
Hello @lolouk44,

You can use the following Toolchain for building software:
https://github.com/EliasKotlyar/Xiaomi-Dafang-Software

There are certain examples for scripts which will compile some applications.

**Comment by lolouk44** [comment]
Thanks I did notice but I'm a bit of a newbie with embedded linux (or the equivalent installed on the dafang)
Are you able to share a few pointers/guidelines to get me started?
For example, I can make a copy of one of the compile scripts and probably edit for my needs, but do I need to run this on the dafang or on a separate linux and then copy the compiled file to the SD card?

Sorry if I sound too much like a noob ;)

**Comment by lolouk44** [comment]
By the way, in case it helps anyone, for MQTT, I'm looking to use [bish-bosh](https://github.com/raphaelcohn/bish-bosh) since it requires no install and works with busybox.
For those interested I'm looking to use MQTT to control the camera from home-assistant, namely Blue & Yellow LED, RTSP Server start/stop, and the motor (until I figure a way to get motion to control the PTZ, though per their [guide](http://htmlpreview.github.io/?https://github.com/Motion-Project/motion/blob/master/motion_config.html#OptDetail_Tracking), it's "_permanently at the experimental stage_"
So that should be one package installation issue solved quickly I hope. Will post back here any updates and advancements.

**Comment by EliasKotlyar** [comment]
You need to crosscompile it, using your pc. You also can try to create a Buildchain, which will be suitable for compiling on the dafang itself. It would be just really really slow due to the lack of the resources on the camera.

I have seen a little bit into the motion project, and i think that the PTZ Support is pretty basic. It should be possible to port it to the camera, but i wouldnt recommend it due to the high amount of work involved.

**Comment by lolouk44** [comment]
Thanks Elias,

I'll give it a try compiling some simple app to test.
For motion, I would not run it directly off the camera, I think it'll be too resource intensive, but maybe we can update the camera in such a way that it would be compatible with motion running off a different machine?

**Comment by lolouk44** [comment]
Hi @EliasKotlyar 

I tried to create a new script from one of your examples to cross compile nano and curl, but I get an error:
```
cctv@HP-N54L:~/Dafang/Xiaomi-Dafang-Software-master$ sudo ./compile_nano.sh 
make: *** No rule to make target 'clean'.  Stop.
checking build system type... x86_64-pc-linux-gnu
checking host system type... mips-unknown-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for mips-linux-strip... no
checking for strip... strip
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for style of include used by make... GNU
checking for mips-linux-gcc... /home/cctv/Dafang/Xiaomi-Dafang-Software-master/mips-gcc472-glibc216-64bit/bin/mips-linux-gnu-gcc
checking whether the C compiler works... no
configure: error: in `/home/cctv/Dafang/Xiaomi-Dafang-Software-master/nano':
configure: error: C compiler cannot create executables
See `config.log' for more details
make: *** No targets specified and no makefile found.  Stop.
```

Any idea?

**Comment by EliasKotlyar** [comment]
There is some error with the C-Compiler. Try if you can run
```
/home/cctv/Dafang/Xiaomi-Dafang-Software-master/mips-gcc472-glibc216-64bit/bin/mips-linux-gnu-gcc
```
Without errors. There may be an error here...

**Comment by shinebar1001** [comment]
Adding mqtt sounds like a great idea. I managed to compile mosquitto without ssl - if that will help you, I can upload the files. (mosquitto_pub, mosquitto_sub and the library) 

For adding SSL I need some help - anything compiles fine until:

`/home/shine/Xiaomi-Dafang-Software/mips-gcc472-glibc216-64bit/bin/mips-linux-gnu-gcc pub_client.o client_shared.o -o mosquitto_pub -muclibc -O2 -L/home/shine/Xiaomi-Dafang-Software/libressl/_install/lib/ -L../lib ../lib/libmosquitto.so.1

/home/shine/Xiaomi-Dafang-Software/mips-gcc472-glibc216-64bit/bin/../lib/gcc/mips-linux-gnu/4.7.2/../../../../mips-linux-gnu/bin/**ld: warning: libssl.so.44, needed by ../lib/libmosquitto.so.1, not found (try using -rpath or -rpath-link)**

/home/shine/Xiaomi-Dafang-Software/mips-gcc472-glibc216-64bit/bin/../lib/gcc/mips-linux-gnu/4.7.2/../../../../mips-linux-gnu/bin **/ld: warning: libcrypto.so.42, needed by ../lib/libmosquitto.so.1, not found (try using -rpath or -rpath-link)**
`

Obviously the -L includes these libraries - Is there another directive I can tell the linker to use the right files? I didn't crosscompile things for more than 15 years, so I'm stuck here....
