### ISSUE TITLE
No WebUI?

### ISSUE THREAD

**Issue by rogerjak** [EliasKotlyar/Xiaomi-Dafang-Hacks#353]
Had a working camera with firmware from a month ago.
Updated the repo, deleted all files on SD, replaced with repo, edited wpa.
Now I can't connect to the Web UI anymore?!
I know it's running because the rtsp stream is live in XProtect.

**Comment by jmtatsch** [comment]
Can you post your startup.log please?

**Comment by rogerjak** [comment]
Here's the startup log.
[startup.log](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/files/1998414/startup.log)

Also, when I log in I get this:
> : not found
> 'sh: .: line 5: can't open '/root/.busybox_aliases

**Comment by jmtatsch** [comment]
Sure you checked out the latest version? I would expect it to generate a ssl key on first start now... look if there is a lighthttpd.pem in config directory...

**Comment by rogerjak** [comment]
No such file there. I pulled the repo yesterday, so I don't have the two latest commits ("enable cron" and the one before).

**Comment by jmtatsch** [comment]
Ah ok, i am already further in my mind. Have a look at the /var/log/lighthttpd* if you have ssh access...

**Comment by rogerjak** [comment]
No lighttpd* files in /var/log/

**Comment by jmtatsch** [comment]
Then try to launch lighthttpd as in run.sh from your ssh console.

**Comment by rogerjak** [comment]
That worked, but can't login with default user/pass.

**Comment by jmtatsch** [comment]
You tried to log in with root/ismart12?
any messages when lighthttpd comes up?
What do the access logs say when you try to login?

**Comment by rogerjak** [comment]
No message when I manually started lighttpd (as in run.sh).
access-log says:
2018-05-13 12:42:50: (server.c.1423) server started (lighttpd/1.4.50-devel-lighttpd-1.4.49-7-g26fb8d3e)
2018-05-13 12:44:07: (mod_auth.c.525) password doesn't match for / username: root, IP: 192.168.0.105

Strange thing: after a reboot lighttpd is started automatically (which it didn't before) but still can't login.

**Comment by jmtatsch** [comment]
Nothing with respect to the webserver has changed the last 8 days and for many people it seems to work. I would recommend to format your sdcard and also do a fresh git clone.

**Comment by rogerjak** [comment]
Ok, will try that. But has any breaking changes been made the last month?
Dependencies to the stock firmware perhaps?
Because it all worked with the repo from April 11th.

**Comment by jmtatsch** [comment]
You are on custom firmware 1.3, right?

**Comment by rogerjak** [comment]
Yes I am

**Comment by jmtatsch** [comment]
The you should be fine. Did you use the autoupdate script?

**Comment by rogerjak** [comment]
No I didn't, deleted all files and copied the new ones from cloned repo.

**Comment by rogerjak** [comment]
Ok, formatted sdcard, copied from fresh clone, same thing: lighttpd wont start, but rtsp stream works.

**Comment by jmtatsch** [comment]
I’ll try a fresh checkout when I get home tomorrow.

**Comment by rogerjak** [comment]
Solved it! Stupid me :(
Downloaded the repo as zip and now all is ok. Git (on Win) messes with line endings...
Used the zip last month (cause it says so in the docs) but then totally forgot about it.
Didn't want to download everything all the time, that's why I used Git today.
Maybe the docs should emphasize this more (and perhaps explain why too).
Anyway, thanks for your help!

**Comment by tssva** [comment]
The repo has a .gitattributes file which lists files which need to have linefeed as the line ending so git won't change them, but it looks like it hasn't kept up with recent changes and some files are missing from it.

**Comment by vkhurana** [comment]
I'm seeing the same thing. I can ssh in, i can even see an rtsp stream in vlc, but there's no webui.
a netstat -l shows that nothing in port 80 or 443.

when i execute run.sh (as root) i see that a pem file is generated, and the webui comes up, but it seems incomplete (as some resources are not loaded - it doesnt look like the screenshot in the repo) and none of the buttons work.

@rogerjak i tried download the zip on github, editted the wpa supplicant file. is there anything else you did?

**Comment by jmtatsch** [comment]
@vkhurana  seems this is now caused by #369

**Comment by vkhurana** [comment]
You're right. I reverted the changes and everything worked perfectly.
Thanks for getting back to me.
