### ISSUE TITLE
Need to go back to Original firmware- methods mentioned not working- Help please

### ISSUE THREAD

**Issue by sanjeewasam** [EliasKotlyar/Xiaomi-Dafang-Hacks#356]
I followed the instructions and installed the hack on my Defang. It worked but very slow and then after few hours get stuck and need rebooting. This is the case for many times. So I want to go back to original firmware.

Instructions given is just remove the SD card. Nope that does not work as it has permanently written something to boot loader I guess.

Could someone please provide instructions. Lately I also do not get the video feed but only the controls are available, I could even move the camera but no feed. I reinstalled the hack (step 2) again still having these issues

Also please let me know where I could get the original firmware if I need to load via SD card because boot loader is messed up

would appreciate if someone could update the problems in the installation page and a warning so some people who are half brave will not attempt it. Definitely not ready for lot of people

Thanks

**Comment by hubmon** [comment]
Unless am mistaken, 
You rename the original firmware(most recent in repository is .243) as demo.bin and load the same as Hack Bootloader.

**Comment by jmtatsch** [comment]
hubmon is correct, I extended the faq a bit for you 8acd8f4012e9d346075a774de92851abed9e1da7

**Comment by joeio** [comment]
There's multiple BIN files in these folders. Which one should be renamed to demo.bin?

**Comment by taylornelson** [comment]
^ seriously, what's up?

**Comment by jmtatsch** [comment]
You can also use the packer script to pack your own firmware from a dump.

**Comment by taylornelson** [comment]
For anyone else who get's stuck just go to the wyze website, unlike this
thread/repo they clearly explain where the firmware is located.  Download
the latest, name it demo.bin indicated and you're good to go.

Side note the bins in the repo for wyzecamv2 are unclear/didn't work for me
(3 bins when only 1 is the firmware).
