### ISSUE TITLE
RTSP-h264 server does not start if log directory not exist

### ISSUE THREAD

**Issue by akinomeroglu** [EliasKotlyar/Xiaomi-Dafang-Hacks#357]
Hello,

I just updated my camera with update script (with -f -v flags) RTSP-h264 service did not start after update. I tried to check control script and run it manually and it gave an error that you find below. It works after I created a log folder in my sdcard.

`[root@DAFANG:controlscripts]# ./rtsp-h264 start
Starting v4l2rtspserver-master
[root@DAFANG:controlscripts]# ./rtsp-h264: line 17: can't create /system/sdcard/log/v4l2rtspserver-master.log: nonexistent directory
`

Maybe we could add an empty log folder to firmware or maybe we can add a check to script for folder and create it if it does not exist.

**Comment by jmtatsch** [comment]
The problem is that those folders are created in run.sh which is not autoupdated.

**Comment by nik0** [comment]
Of needed we can remove this restriction

**Comment by akinomeroglu** [comment]
@jmtatsch thanks for clarification. I checked my run.sh and saw that I am still using boa instead of lighttpd because I only can update my cfw with update script. 

So @nik0 maybe we can add an option to update script for updating run.sh or we can remove this restriction. I don't know why there is a restriction but this run.sh script have an important role and must updated regularly.

**Comment by jmtatsch** [comment]
We can try. 
I thought you had good reasons to exclude it in the first place 😄 
We could also download all files to be updated in a different folder, then shutdown all services and  copy the files and restart. That could solve the problems with curl libs replaced in the middle of an update.

**Comment by nik0** [comment]
yep good idea, I add it to the stack of things to do :-)

**Comment by jmtatsch** [comment]
Since 6d1b50fdee6c139cd4198f24e8b43a4577037015 we have nik0's new autoupdate. That definitely fixes the issue.
