### ISSUE TITLE
PAYLOAD IS NOT VALID JSON DATA when looking at MQTT payloads

### ISSUE THREAD

**Issue by lolouk44** [EliasKotlyar/Xiaomi-Dafang-Hacks#358]
For some topics/payloads I get this:
```
*** PAYLOAD IS NOT VALID JSON DATA *** 

Unexpected character ('O' (code 79)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: java.io.StringReader@37cb3f65; line: 1, column: 2]
```
Base topic, motors/vertical, motors/horizontal, brightness are fine. All other topics display the above error message.
Any idea?

**Comment by jmtatsch** [comment]
I don't understand.
There is only one status topic which has json output which is created here in mqtt-status.sh
The rest isn't supposed to be valid json.

**Comment by lolouk44** [comment]
I'm using MQTT.fx to track my MQTT traffic.
Just checked and MQTT had its settings set to JSON decrypt. Thanks and sorry
