### ISSUE TITLE
Delete files older than x days locally and on ftp servers

### ISSUE THREAD

**Issue by Psudonico** [EliasKotlyar/Xiaomi-Dafang-Hacks#359]
Hi all.
I'd like to delete local video files older than 3 days but this command:
`find /system/sdcard/DCIM/VideoRecorder/*.* -mtime +3  -exec rm {} \;`
not work.
The error is -mtime not recognized

I have the same problem with local FTP.
I found this script but don't work:
```
#!/bin/bash
# get a list of files and dates from ftp and remove files older than ndays
ftpsite="192.168.1.1"
ftpuser="user"
ftppass="pass"
putdir="/Archivio_Esterno(sda1)/cam"

ndays=3


# work out our cutoff date
MM=`date --date="$ndays days ago" +%b`
DD=`date --date="$ndays days ago" +%d`


echo removing files older than $MM $DD

# get directory listing from remote source
listing=`ftp -i -n $ftpsite <<EOMYF 
user $ftpuser $ftppass
binary
cd $putdir
ls
quit
EOMYF
`
lista=( $listing )

# loop over our files
for ((FNO=0; FNO<${#lista[@]}; FNO+=9));do
  # month (element 5), day (element 6) and filename (element 8)
  #echo Date ${lista[`expr $FNO+5`]} ${lista[`expr $FNO+6`]}          File: ${lista[`expr $FNO+8`]}

  # check the date stamp
  if [ ${lista[`expr $FNO+5`]}=$MM ];
  then
    if [[ ${lista[`expr $FNO+6`]} -lt $DD ]];
    then
      # Remove this file
      echo "Removing ${lista[`expr $FNO+8`]}"
      ftp -i -n $ftpsite <<EOMYF2 
      user $ftpuser $ftppass
      binary
      cd $putdir
      delete ${lista[`expr $FNO+8`]}
      quit
EOMYF2


    fi
  fi
done
```

**Comment by nik0** [comment]
Try` /system/sdcard/bin/busybox find /system/sdcard/DCIM/VideoRecorder/*.* -mtime +3 -exec rm {} \;`

**Comment by Psudonico** [comment]
Thank you nik0 bug not work.
[root@CASA:~]# /system/sdcard/bin/busybox find /system/sdcard/DCIM/VideoRecorder/*.* -mtime +3 -exec rm {} \;
rm: remove '/system/sdcard/DCIM/VideoRecorder/2018-04-27_02.53.avi'? y
rm: can't remove '/system/sdcard/DCIM/VideoRecorder/2018-04-27_02.53.avi': Read-only file system

Ask confirm and can't delete

**Comment by nik0** [comment]
This is not related to find command
To avoid having to press Y to rm command use « rm -f »
Said that it is strange to have read only file system. Can you type « mount «  command and see what is going wrong with the file system.

**Comment by Psudonico** [comment]
@nik0 
Thanks, now it works for locally files.
Can you help me find a similar command for the FTP server?
Thanks

**Comment by Psudonico** [comment]
```
[root@CAM:scripts]# ./deloldfile.sh
date: invalid date '3 days ago'
date: invalid date '3 days ago'
removing files older than
./deloldfile.sh: line 26: ftp: not found
./deloldfile.sh: line 27: syntax error: unexpected "("
```

**Comment by nik0** [comment]
You need to rewrite your script ... it is bash based and sh is a bit different
some ideas:
- you can replace the date commands by theses:
```
MM=`date -d "@$(( $(busybox date +%s) - 86400 * $ndays ))" +%b`
DD=`date -d "@$(( $(busybox date +%s) - 86400 * $ndays ))" +%d`
```

- you can replace ftp command by curl:
`listing=$(curl -s -u $ftpuser:$ftppass ftp://$ftpsite/$putdir/)`

-To delete file with curl:
`curl -v -u username:pwd ftp://host/FileTodelete.xml -Q "DELE FileTodelete.xml"`

You need to rewrite the parsing of the ftp output to match curl one (a bit of work)
