### ISSUE TITLE
Error in web site URL for Dark Theme

### ISSUE THREAD

**Issue by Leemonoid** [EliasKotlyar/Xiaomi-Dafang-Hacks#360]
The dark theme setting in the interface doesn't work because it is attempting to load:
https://cdn.jsdeliver.net/npm/bulmaswatch@0.6.2/slate/bulmaswatch.min.css

The URL should be:
https://cdn.jsdelivr.net/npm/bulmaswatch@0.6.2/slate/bulmaswatch.min.css

Note that jsdelivr is spelled incorrectly.

**Comment by Dekonass** [comment]
Hi, 

How do I correct this ?! Where is the file to edit ?

"jquery-3.3.1.min.js:2 GET https://cdn.jsdeliver.net/npm/bulmaswatch@0.6.2/slate/bulmaswatch.min.css 0 ()"

**Comment by Dekonass** [comment]
Hi,

I found it, need to edit 

Xiaomi-Dafang-Hacks-master\firmware_mod\www

File **index.htm**l, line 314

<a id="theme_.htmlchoice_1" href="javascript: setTheme('1')" class="theme_choice dropdown-item" data-css="https://cdn.jsdelivr.net/npm/bulmaswatch@0.6.2/slate/bulmaswatch.min.css">

**Comment by jmtatsch** [comment]
Can someone please make a pullrequest out of this?
