### ISSUE TITLE
[Xiaomi DAFANG] Synology and surveillance station

### ISSUE THREAD

**Issue by ninjax95** [EliasKotlyar/Xiaomi-Dafang-Hacks#366]
Hi,

It's possible to connect the dafang camera with Synology and surveillance station, if yes, 
how can one proceed to the configuration?

I have cfw-1.3 with the last firmware mod.
xiaomi firmware 5.5.1.306 without sdcard

**Comment by snics** [comment]
Does the hack also support the PTZ at the Synology surveillance station?

**Comment by jmtatsch** [comment]
I don't think so.  Please continue discussion in the Synology issue #213.
