### ISSUE TITLE
web config page can not open

### ISSUE THREAD

**Issue by qiqiji** [EliasKotlyar/Xiaomi-Dafang-Hacks#374]
try http://dafang/ or http://10.0.1.55/ with no luck
however rtsp is working

**Comment by jmtatsch** [comment]
Startup log please.

**Comment by DerMilchShake** [comment]
I cant open config page because i'm asked to put name and password.
what is the name and password for config page?

**Comment by xhizorsz** [comment]
Hey I'm also unable to open the web config page. SSH is working.

Here is my log:

`==================================================
Starting the Dafang Hacks Custom Application Layer
==================================================
Loaded common functions
Bind mounted /system/sdcard/root to /root
Bind mounted /system/sdcard/etc to /etc
wpa_supplicant: Successfully initialized wpa_supplicant
rfkill: Cannot open RFKILL control device
nl80211: Could not re-add multicast membership for vendor events: -2 (No such file or directory)
udhcpc: udhcpc (v1.22.1) started
Sending discover...
Sending discover...
Sending select for 192.168.111.87...
Lease of 192.168.111.87 obtained, lease time 86400
deleting routers
adding dns 192.168.111.1
Initialized gpios
dropbear:
bftpd:
lighttpd:
Startup finished!`

**Comment by xhizorsz** [comment]
I switched to a older version. https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/tree/8efe0431f89c72de0598d7d55fc4ba9d910a028e

Now it's working!

**Comment by jmtatsch** [comment]
Closing this due to no reaction from op.
