### ISSUE TITLE
Lighthttpd http->https not working because not compiled with PCRE

### ISSUE THREAD

**Issue by jmtatsch** [EliasKotlyar/Xiaomi-Dafang-Hacks#377]
I would like to [redirect http to https](https://redmine.lighttpd.net/projects/1/wiki/HowToRedirectHttpToHttps) for better security. 

When adding the redirect in lighttpd.conf
```
$HTTP["scheme"] == "http" {
    # capture vhost name with regex conditiona -> %0 in redirect pattern
    # must be the most inner block to the redirect rule
    $HTTP["host"] =~ ".*" {
        url.redirect = (".*" => "https://%0$0")
    }
}
```
it fails to start with:

`can't handle '$HTTP[host] =~ ...' as you compiled without pcre support.
(perhaps just a missing pcre-devel package ?) `

@nik0 could you compile lighttpd with pcre support please?

**Comment by nik0** [comment]
I will have a look, but it seems I need to compile another lib. It may takes some time

**Comment by nik0** [comment]
Please check https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/pull/378

**Comment by jmtatsch** [comment]
The binary in the PR doesn't seem to have PCRE support:

```
/system/sdcard/bin/lighttpd -V
lighttpd/1.4.50-devel-lighttpd-1.4.49-7-g26fb8d3e (ssl) - a light and fast webserver

Event Handlers:

	+ select (generic)
	+ poll (Unix)
	+ epoll (Linux)
	- /dev/poll (Solaris)
	- eventports (Solaris)
	- kqueue (FreeBSD)
	- libev (generic)

Network handler:

	+ linux-sendfile
	- freebsd-sendfile
	- darwin-sendfile
	- solaris-sendfilev
	+ writev
	+ write
	- mmap support

Features:

	- IPv6 support
	- zlib support
	- bzip2 support
	+ crypt support
	+ SSL support
	- PCRE support
	- MySQL support
	- PgSQL support
	- DBI support
	- Kerberos support
	- LDAP support
	- memcached support
	- FAM support
	- LUA support
	- xml support
	- SQLite support
	- GDBM support
```
Did you commit the right binary?

**Comment by nik0** [comment]
I didn't' check with -V option but I changed the conf file as you described and lighthttpd starts without error. 
Can you check if it works anyway, I will check why it doesn't appear to be activated

**Comment by jmtatsch** [comment]
Sorry, i must have downloaded the wrong binary somehow. Yours has PCRE support and the redirect works.

**Comment by jmtatsch** [comment]
Thank you very much.

**Comment by nik0** [comment]
cool !
