### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Pixiio** [EliasKotlyar/Xiaomi-Dafang-Hacks#38]
Hi! I'm trying to block all outgoing connecting to the servers of Xiaomi. I don't really like the idea that my camera is streaming things to China/to the internet. 

But I don't really understand how to do this.. I think I'll be able to install the firmware, but what then? I read something about setting up RTSP. How do I do this? And how do I disable the outgoing connecting?

Thank you so much!

**Comment by lolouk44** [comment]
My understanding is that if you use the Xiaomi app, the video will stream via China.
If you don't want to stream via China, then use @EliasKotlyar 's firmware and use the RTSP to stream the video to wherever you want.
You will need to look for another app on your phone or application on your PC/laptop to view the stream.
I personally use [motion ](https://github.com/Motion-Project/motion) but that requires a Linux server to run 24/7. Not sure what you have and what you're looking for to replace the Xiaomi app...
