### ISSUE TITLE
Unable to load image

### ISSUE THREAD

**Issue by shadi1989** [EliasKotlyar/Xiaomi-Dafang-Hacks#381]
I've did all the installation steps mentioned in the Installation Guide. 
Dafang 1080p booted correct, webinterface and video showed
After enabling/disabling some settings i'm getting the "Unable to load image" in the video part.

What did i do wrong?
I can still connect to the web interface and edit all settings.

**Comment by jmtatsch** [comment]
did you try rebooting?

**Comment by shadi1989** [comment]
@jmtatsch yes i did, multiple times.
Did also tried "Update" but nothing happend as the firmware was already the latest

**Comment by shadi1989** [comment]
Reflashed the sd-card and re-created this issue:
1. changes root password
2. set time to UTC-2
3. set "Auto Night Mode" to ON, choose "5" and press "Set"
4. set Video Size to "1920x1080" and press "Set"
After this the image shows "Unable to load image"

**Comment by jmtatsch** [comment]
Try smaller resolutions

**Comment by heyggu** [comment]
The same situation

**Comment by shadi1989** [comment]
@jmtatsch already did that. see the results above.

Looks like its the 1920x1080 resolution who causes this.
@heyggu can you confirm the same issue? so fresh install and edit only the resolution?

**Comment by jmtatsch** [comment]
For full hd you would have to change the memory partioning in the bootloader.
See #30 for details.

**Comment by christallire** [comment]
commit https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/commit/62851318a38aaba22ab47c5353f7c180f451c211
broke functionality for me

**Comment by jmtatsch** [comment]
Should be fixed now. If not please reopen.
