### ISSUE TITLE
Access for 3rd party apps like tinyCam Monitor for motion data.

### ISSUE THREAD

**Issue by saipsa** [EliasKotlyar/Xiaomi-Dafang-Hacks#383]
Would it be possible to provide access to motion data to say tinyCam

Here is what https://tinycammonitor.com/manual/camera_motion_detection.html says

> On-camera motion detection
> 
> On-camera motion detection is done solely on camera. All settings like motion detection area or motion sensitivity should be changed via camera web interface.
> 
> It does not use Android device CPU for detecting motion (no battery consumption), but it may consume additional traffic.
> 
> If on-camera motion detection is disabled in Camera Settings, then your camera does not support motion detection or it does not provide access for 3d party apps like tinyCam Monitor for motion data.

Thanks

**Comment by sanjeewasam** [comment]
Interest in this. I looked at the following https://kszere.gitbooks.io/custom-software-for-xiaomi-dafang-manual/content/en/integrations/tinycam-on-android.html

the download for configuration file custom_vendors.xml come empty and not accepted by the app. As per the instruction it is meant for defang camera

**Comment by theslackjaw** [comment]
>the download for configuration file custom_vendors.xml come empty and not accepted by the app

If you are getting a 'file not found' type error when trying to load custom_vendors.xml it may be to do with the way your device file manager gives tinycam the link to the file. Ensure you just have a file path and not 'document:_path_'.

**Comment by jmtatsch** [comment]
Can you ask via what API tinyCam would require motion data.

**Comment by saipsa** [comment]
@jmtatsch I mailed them the same day, but haven't heard from them.

Since Foscam is on their recommended camera list, Foscam's API would be of help.

Here is how openhab handles it.

https://github.com/openhab/openhab1-addons/wiki/Foscam-IP-Cameras#motion-alarms
