### ISSUE TITLE
First installation question

### ISSUE THREAD

**Issue by sfanicola** [EliasKotlyar/Xiaomi-Dafang-Hacks#39]
Sorry guys, I've got a question about the installation.

On the installation guide it first says:
_" The custom firmware (CFW) bootloader will boot from microSD only if a microSD is plugged in and has a "run.sh" file on it. "_
and then at point 3:
_" Put it to microSD and rename it to "demo.bin". There should be no other files on the microSD! This is really important and it won't work if there are any other files on there. "_

So I get a little confused, cause I tried many times without success.

**Comment by lolouk44** [comment]
These are 2 separate steps:
First you update the firmware with demo.bin only.
Once you have flashed the firmware you remove demo.bin and copy the other files  (incl run.sh)

Hope that makes sense

**Comment by crinop** [comment]
Thanks for the above clarification. I was have the same confusion.  

I'm new to all this, so I appreciate you all being willing to answer some basic questions.  I think I've done everything correctly. However, after I remove the demo.bin and reboot with the new bootfiles, the camera LED is yellow, the blue for a second or two, and the (after rotating the camera) it blinks yellow. Is this correct?

**Comment by zgadgeter** [comment]
Thanks for the clarification. However i'm stil not able to flash my device. I have tried 3 different SD cards, so do not think it is a problem with the SD card.
What I do is as follows:
I format my SD card with FAT32
I copy the demo.bin onto the car. There are no other files on the card.
I put the card into the camera.
I hold the setup button on the camera
I then plug in the camera to power.
I have tried holding the setup button for a long time, and also have let it go after powering the camera up, same result.
The camer powers up, and with about 10 seconds begins to turn it's base as though it's starting up normally.
So, does anyone have any further suggestions?

thanks.

**Comment by kszere** [comment]
Sometime, upload new firmware less than 10 sec.

# Next step: Installation of the new Firmware on MicroSD

1. Clone or download the [EliasKotlyar/Xiaomi-Dafang-Hacks](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks) repository as an archive file from GitHub.

2. Copy every file and directory from "**firmware_mod**" directory into the root of the MicroSD.
It should look like this:
```
MicroSD:/
├── bin
├── config
├── run.sh
├── scripts
├── www
└── run.sh
```
3. Modify the file `/config/wpa_supplicant.conf` on the MicroSD to match your WiFi settings.
4. Insert the MicroSD and start the camera.

### If really not upload new firmware, I not solution.
