### ISSUE TITLE
v4l2rtspserver-master can't load library

### ISSUE THREAD

**Issue by nbourre** [EliasKotlyar/Xiaomi-Dafang-Hacks#391]
Hey guys,

I'm unable to start any rtsp services on the camera.

I always get the error "can't load library 'libliveMedia.so'"

I've googled this and found nothing.

What's am I doing wrong?

BTW, I'm pretty noob with this camera.

Can you do a step by step manual?

Thank you

**UPDATE**
FYI, I get this message in the logfile for the video server
`/system/sdcard/bin/v4l2rtspserver-master: /home/ptkang/work/platform/isvp_20160504_e/proj/sdk-lv3/src/imp/ivs/ivs_move/src/filter.c: 156: Start: Assertion filter->roi.x >= 0 && filter->roi.y >= 0 && filter->roi.width >= 0 && filter->roi.height >= 0 && filter->roi.x + filter->roi.width <= filter->wholeSize.width &&filter->roi.y + filter->roi.height <= filter->wholeSize.height' failed.`

**Comment by EliasKotlyar** [comment]
It should be fixxed with the latest commit. If not, please report back!
