### ISSUE TITLE
Unable to change bitrate (new binary)

### ISSUE THREAD

**Issue by Dopeyr** [EliasKotlyar/Xiaomi-Dafang-Hacks#393]
Hi,

I'm struggling to change the bitrate using e.g. `/system/sdcard/bin/setconf -k b -v 1000`. I am using commit ff24120d6e8e6da350f06be0814cf81c85884042

I believe the issue is the CBR -> VBR change (I was very excited by this change btw @EliasKotlyar).

I see 

```
2018-05-30 22:24:21.312 (  32.002s) [update_thread   ]         ImpEncoder.cpp:413      0| Changed Bitrate
```

...in the log, but the bitrate does not change.

I think it's down to this bit of code:

```
if (currentConfig.bitrate != newConfig->bitrate) {
            LOG_S(INFO) << "Changed Bitrate";
            IMPEncoderAttrRcMode attr;
            IMP_Encoder_GetChnAttrRcMode(0, &attr);
            attr.attrH264Cbr.outBitRate = (uint)newConfig->bitrate;
            IMP_Encoder_SetChnAttrRcMode(0, &attr);
        }
```

Which is changing the CBR rate still. Unfortunately I don't know C++, so I'm unable to help with/test a patch :(

**Comment by nik0** [comment]
I did the change of CBR to VBR (my bad)
You think that in VBR the bitrate can not be changed?
What is in the "logcat" command when changing it ?

If it have some issue, we may have the VBR/CBR in command line ...

**Comment by Dopeyr** [comment]
Hi @nik0 

Great work, still excited by the change for this reason: I was hoping the CBR->VBR change would reduce the bitrate for video that isn't changing much. I watch the feed on mobile data, so was hoping the VBR change would reduce my mobile usage.

I've seen so far that the bitrate is around 400-500KB/s, and was using the `setconf -k b -v X` to play around with reducing the bitrate. That's when I noticed it wasn't changing. In the 'old' binary it would change right away.

It looks like the bitrate for VBR is now called `rc_attr->attrRcMode.attrH264Vbr.maxBitRate = currentParams.bitrate;` (https://github.com/Dafang-Hacks/Main/blob/5396ed5bc912672d08b6e40b38d820ac96ec830b/v4l2rtspserver-master/src/ImpEncoder.cpp#L1441)

but the `setconf` code above calls `attr.attrH264Cbr.outBitRate = (uint)newConfig->bitrate;` (https://github.com/Dafang-Hacks/Main/blob/5396ed5bc912672d08b6e40b38d820ac96ec830b/v4l2rtspserver-master/src/ImpEncoder.cpp#L416), which refers to CBR.

I was hoping I could set a maximum VBR for high motion video, but when the video was mainly static, by bandwidth usage would be low.

I'll get my `logcat` output as I change the setting.

Thanks

**Comment by nik0** [comment]
The currentParams.bitrate is the bitrate set at the beginning (hardcoded)
and newConfig->bitrate comes from setconf.
I added some logs (I didn't see any errors logcat or API calls). I didn't have time to see if the bite rate is really changing, if not we will need to revert VBR

**Comment by nik0** [comment]
Good catch !!! It was so obvious that I didn’t see it !
I will test it tonight....

**Comment by Dopeyr** [comment]
Thanks @nik0 Yes, this works fine for me, thanks. The actual delivered bitrate doesn't seem to directly related to the value entered, e.g. 

entering 1200 gives me a bitrate of ~2100 kb/s,
entering 600 gives be a bitrate of ~1520 kb/s
entering 2000 gives be a bitrate of ~3200 kb/s

I have audio disabled. I am running at 1600x900 25fps. I wondered if it had something to do with this line that has been commented out

```
rc_attr->attrRcMode.attrH264Vbr.maxBitRate = currentParams.bitrate; //(double)2000.0 * (imp_chn_attr_tmp->picWidth * imp_chn_attr_tmp->picHeight) / (1280 * 720);
```

Anyway, I'm able to reduce the bitrate as needed by playing around with the values. Thanks!

**Comment by Dopeyr** [comment]
For ref @nik0, I've added https://github.com/Dafang-Hacks/Main/pull/4 which hopefully allows for playing around with the different encoding options at runtime rather than compile time.

**Comment by nik0** [comment]
I close this now, shall be ok
