### ISSUE TITLE
XiaoFang wlan0: Failed to initialize driver interface

### ISSUE THREAD

**Issue by drcobra** [EliasKotlyar/Xiaomi-Dafang-Hacks#394]
Hi,
I have a XiaoFang that has been produced in 2018.04 so I assume it is a Xiaomi Xiaofang T20.
The wlan driver is missing.
I used the following commands to fix it with no success.
```
if [ -f /driver/8189es.ko ]; then
  insmod /driver/8189es.ko rtw_initmac="$MAC"
else
  insmod /driver/rtl8189ftv.ko rtw_initmac="$MAC"
fi
```
and
`insmod /driver/8189es.ko rtw_initmac="$MAC"`
and
`insmod /driver/rtl8189ftv.ko rtw_initmac="$MAC"`

Am I missing something?

The startup.log is

> ==================================================
> Starting the Dafang Hacks Custom Application Layer
> ==================================================
> Loaded common functions
> Created etc directory on sdcard
> Bind mounted /system/sdcard/root to /root
> Bind mounted /system/sdcard/etc to /etc
> Created cron directory
> wpa_supplicant: Successfully initialized wpa_supplicant
> rfkill: Cannot open RFKILL control device
> Could not read interface wlan0 flags: No such device
> nl80211: Driver does not support authentication/association or connect commands
> nl80211: deinit ifname=wlan0 disabled_11b_rates=0
> Could not read interface wlan0 flags: No such device
> wlan0: Failed to initialize driver interface
> udhcpc: 
> Initialized gpios
> dropbear: 
> bftpd: 
> Created new certificate for webserver
> lighttpd: 
> Startup finished!

**Comment by jmtatsch** [comment]
Which cfw did you flash exactly? Can you list your driver dir to startup.log?

**Comment by drcobra** [comment]
Stupid of me, now I understood what you ment.
These are the files:
```
8189fs.ko
audio.ko
exfat.ko
sample_motor.ko
sample_pwm_core.ko
sample_pwm_hal.ko
sample_speakerctl.ko
sensor_jxf22.ko
sensor_jxf23.ko
sinfo.ko
tx-isp.ko
```
By using the following I managed to connect to WiFi
`insmod /driver/8189fs.ko rtw_initmac="$MAC"`

Is that a new WiFi chipset/driver?
How come after flashing the cfw-1.0.bin (demo.bin), the factory drivers remained?

Thanks for the suggestion!

**Comment by jmtatsch** [comment]
Hope a5bb3597f19502f23837d3ea6bc1912534d81658 fixes it for you.
The really only changes the bootloader and leaves everything else in tact. Thus the factory drivers remain there and are used for many things.
