### ISSUE TITLE
Problem with autoupdate.sh , read only file system?

### ISSUE THREAD

**Issue by olskar** [EliasKotlyar/Xiaomi-Dafang-Hacks#396]
Trying to run autoupdate.sh and get this:

`./autoupdate.sh: line 312: can't create 1: Read-only file system
`

**Comment by nik0** [comment]
Do you have the latest version of the script. There was commit of the file was corrupted.
Line 312 is the last line of the script ...

**Comment by jmtatsch** [comment]
probably your sdcard is in a bad state.
Can your reformat your sd and checkout a fresh copy of the repo?

**Comment by olskar** [comment]
Dont know why, but worked after reboot, closing :)
