### ISSUE TITLE
How to implement DVR videos recording 

### ISSUE THREAD

**Issue by iashwinprasada** [EliasKotlyar/Xiaomi-Dafang-Hacks#40]
Stock firmware can do DVR by storing sequential videos, what is the best tool to work with to achieve such functionality? Also how will it handle DVR and livestream together? Any ideas on how to implement this?

**Comment by ineedit91** [comment]
I'm not very technical so sorry if I misunderstood your question. But I use an Android app that streams the video from the camera and also records it to act as a DVR. The app is on a cheap dedicated Android TV box with a hdd attached. This way the cameras dvr ability is not necessary and the Android box/ app picks up that responsibility.

**Comment by iashwinprasada** [comment]
that's one way to do it. but because the camera already has an SD card, it also makes sense to replicate the stock DVR feature which records the videos directly on the box.

**Comment by ineedit91** [comment]
Agreed that it would be a good feature to have, especially if you only have a couple of the cameras. My approach was a method to save money considering I have 7 of the dafangs being used as home security cams, and buying a good size sd card for each would break the bank.

**Comment by lolouk44** [comment]
You'd need to find a very lightweight app with little dependencies that can run on the camera.
I'm not sure whether there are restrictions on how many feeds can be seen at the same time. @EliasKotlyar any idea?
I personally use [motion](https://github.com/Motion-Project/motion) to pull the feeds and do all the recording on a server thus not putting pressure on the camera...

**Comment by Chris-Nbg** [comment]
@iashwinprasada Did you try https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/hacks/install_cfw.md (bottom section)?

**Comment by iashwinprasada** [comment]
@Chris-Nbg sure, it works independently but not when the stream is active. but what I'm trying to achieve is to record without disturbing the main live stream. Ingenic documentation allows for this implementation, I have got a little direction now, please check this issue from the other repo : [Issue](https://github.com/EliasKotlyar/Xiaomi-Dafang-Software/issues/5)

**Comment by EliasKotlyar** [comment]
Hello @iashwinprasada ,

There is an option in the rtsp_server, to stream it to a "file". I have uncommented it, to allow the usage of the JPG-Snap Function. You can restore it by inspecting the "-O" parameter. For now it streams to the stdout, and use only 1 Frame. It should be easy to restore it to "stream" to a file.

**Comment by jmtatsch** [comment]
Close in favour of #106
