### ISSUE TITLE
http request error in openhab

### ISSUE THREAD

**Issue by sladaar** [EliasKotlyar/Xiaomi-Dafang-Hacks#400]
Hey there, just a simple question:
with the latest firmware the usual http request ( http://user:pwd@ip/cgi-bin/currentpic.cgi) i used to control the camera doesn't seem to work anymore, Eclipse certificate or SSL engine error. 
I know about turning off the authorization request in lighttpd.conf but actually i wasn't able to properly eliminate it. I've got to go back to previous versions of this hack to get it to work.

Is there another way to control the camera? I mean, also getting an image (i guess with mqtt you can't).
Or, can anyone kindly help me turning off the need of the pwd (but i think that won't be the perfect solution, i would like some security as well).
Thanks in advance

**Comment by jmtatsch** [comment]
Why don’t you try https? Http is redirected to https now. Maybe openhab doesn’t like the redirect...

**Comment by sladaar** [comment]
Thanks for the reply! I tried, indeed!
Maybe it's just my bad, but as far as i know Openhab doesn't like https. But i admit not to be too far deep into it, lack of knowledge here and there

**Comment by jmtatsch** [comment]
You need to run openhab allowing  self signed certificates. If it doesn’t allow that, get a better home automation framework.

**Comment by amagnolo** [comment]
To solve this problem, that I experienced with Home Assistant, I had to remove the https redirection.
i.e. remove these lines from /system/sdcard/config/lighttpd.conf :
```
$HTTP["scheme"] == "http" {
    # capture vhost name with regex conditiona -> %0 in redirect pattern
    # must be the most inner block to the redirect rule
    $HTTP["host"] =~ ".*" {
        url.redirect = (".*" => "https://%0$0")
    }
}
```

**Comment by sladaar** [comment]
@jmtatsch thanks anyway. And openHab can allow ssl for sure, it's just my bad atm, i'm learning!

@amagnolo many thanks for the solution, i will try it! (grazie!)

Btw the best solution i found, by now, it's to control the camera through mqtt and to use a third party software to embed the preview in openHab.
