### ISSUE TITLE
Upgrade instructions?

### ISSUE THREAD

**Issue by DifferentComputers** [EliasKotlyar/Xiaomi-Dafang-Hacks#403]
Maybe this is my newness on GitHub, but I can't find any documentation here for what the upgrade process is if I have a working hacked camera.

Currently running "v.0.0.1" according to the camera's web page.

Do I just replace the files on the SD card with the new ones? What do I need to do to be assured my configuration won't be broken?

**Comment by saipsa** [comment]
from the web UI, you can update the firmware.

**Comment by DifferentComputers** [comment]
Apparently not with the version I'm on, which is more than a month old. I see no options for updating in the UI.

**Comment by jmtatsch** [comment]
You can just copy over the fresh git checkout to sd and replace the existing files. Your configuration stays in files git doesn’t have so they shouldn’t be harmed.
