### ISSUE TITLE
how to control the base?

### ISSUE THREAD

**Issue by rex5652** [EliasKotlyar/Xiaomi-Dafang-Hacks#406]
It's ok to control on the web, but how to contron the base in Home Assistant?
Thanks

**Comment by rex5652** [comment]
Got it
curl -u root:ismart12 "https://IPADDRSS/cgi-bin/action.cgi?cmd=motor_right" -k

http://[ip_of_camera]/cgi-bin/action.cgi?cmd=motor_right
http://[ip_of_camera]/cgi-bin/action.cgi?cmd=motor_left
http://[ip_of_camera]/cgi-bin/action.cgi?cmd=motor_top
http://[ip_of_camera]/cgi-bin/action.cgi?cmd=motor_bottom

**Comment by sifus** [comment]
Hello, it doens't work in jeedom...
