### ISSUE TITLE
Disable Motion Detection at startup

### ISSUE THREAD

**Issue by LiloBzH** [EliasKotlyar/Xiaomi-Dafang-Hacks#407]
Hi !

How to disable Motion Detection, Blue led at startup please ?

Same question for bitrate. How to fix the value ?

Each startup, i change via SSH with "/system/sdcard/bin/setconf -k b -v 2500"

Can we add a startup script ? Thank's !

**Comment by LiloBzH** [comment]
Go idea the Run.sh file

I have edited like this

```
# force IP
ifconfig wlan0 192.168.0.155 netmask 255.255.255.0
# Force BitRate
/system/sdcard/bin/setconf -k b -v 2500
# disable blue light
setgpio 39 1
#disable motion detection
/system/sdcard/bin/setconf -k m -v -1
```

**Comment by rjpgt** [comment]
This may not be relevant now after all this time. But it appears the problem was that in the `configureMotion` script the parameter `motion_detection` is being compared with `false` instead of with `off` since that is how it is set in `motion.conf` for disabled motion detection.
