### ISSUE TITLE
 Read-only file system

### ISSUE THREAD

**Issue by olskar** [EliasKotlyar/Xiaomi-Dafang-Hacks#409]
I sometimes get message when for example running autoupdate or trying to edit files: "Read-only file system"

I do not think it is my sd-card that is faulty as I can solve the problem bu running 
`mount -o remount,rw /system/sdcard
`
or rebooting.

For some reason the filesystem is made read-only sometimes?

**Comment by nik0** [comment]
I 've got this when the sdcard was "corrupted" it mounts the flesystem in read only.
I had to check fisk on my windows machine.

**Comment by goermezer** [comment]
I had this issue too with the previous changes. With the last changes I have not recognized it.

**Comment by helto4real** [comment]
Getting this alot. Know I have a ok SD card

**Comment by youqingkui** [comment]
I have also had this error recently.

**Comment by jmtatsch** [comment]
@youqingkui can you please test #527?

**Comment by eridesktop** [comment]
1. update your firmware so there is FSCK tools #527 
2. on your ssh console type _mount_ to see your sdcard mount location. mine _/dev/mmcblkop1_ . Dont use /system/sdcard path
3. type dosfsck [flag] [sdcard path] eg:
`dosfsck -a /dev/mmcblkop1`

**Comment by nik0** [comment]
There is a way to add this command in run.sh ? I don't know if we can check the status before ...

**Comment by olskar** [comment]
Use fsck on a mounted file system? Thought that was a big NO-NO?

**Comment by dmolner** [comment]
After last update I have this error
I type `dosfsck -a /dev/mmcblkop1`
the answer is `-sh: dosfsck: not found`

**Comment by jmtatsch** [comment]
Dosfsck is probably not on your path. Either add /system/sdcard/bin to your path or cd there and run it from there.

**Comment by dmolner** [comment]
Hello,
I write
`/system/sdcard/bin/dosfsck -a /dev/mmcblkop1` with the same result.
`cd /system/sdcard/bin/
dosfsck -a /dev/mmcblkop1` with the same result.

**Comment by Dopeyr** [comment]
@dmolner Should be `/dev/mmcblk0p1` instead of `/dev/mmcblkop1` (Zero instead of the letter o)

**Comment by dmolner** [comment]
@Dopeyr 
In my /bin i not have dosfsck
I'm sorry , I need help

**Comment by Dopeyr** [comment]
@dmolner 

Hmm, if the sdcard was read only when you did the update, you might not have dosfsck as it could not write it  (I guess?).

It's  probably best to take the card out, check it on a different machine, format it and then install everything from scratch. You might want to keep a copy of your `wpa_supplicant.conf` (the wifi settings).

**Comment by reikred** [comment]
This issue should be reopened. I still have the same problem with ro mount today. Was able to fix via  ssh login to shell and running the command

mount -o remount,rw /system/sdcard

So it is presumably not the sdcard that is broken nor a corrupted filesystem. But is does occur when cycling the power to the cameras. Not good for a standalone and remote security camera to behave like this -- one might not have ssh access and one might not notice the problem.

Hardware:  Wyzecam V2

**Comment by ioanbsu** [comment]
+1 @reikred . I have this issue on regular basis.
running ```mount -o remount,rw /system/sdcard``` solves it, but temporary only.

**Comment by k1ng440** [comment]
same issue but i cant access ssh.

**Comment by sevenofnine-jni** [comment]
Also having the same issue. But when this happens ssh is not working so the only solution is to remove the sd card from the camera wich is a pain beacuse all my cameras are mounted on the wall near the cealing.

**Comment by stainlessray** [comment]
Same issue

**Comment by ortegafernando** [comment]
Same issue. Sometimes sdcard is read only (Dafang)

**Comment by FrankLeith** [comment]
Same issue...

**Comment by LouiS22** [comment]
Have the same issue

**Comment by stainlessray** [comment]
I resolved my issue by formatting the SD and re flashing from scratch. Windows line endings were inserted in several of the config files and rather than trying to find and fix them all I took that route and made sure any file I edited had the LF line endings before saving the file.

**Comment by k1ng440** [comment]
can we have an option in the UI to remount the sdcard? 

mount -o remount,rw /system/sdcard

**Comment by CeccoCQ** [comment]
Same issue here

**Comment by jamman9000** [comment]
Now finally getting my wyzecam v2 jx23 connected to my wifi, I'm having this issue too. Unable to SSH to it either.

**Comment by jmtatsch** [comment]
Just start from scratch then

**Comment by jgwinner** [comment]
I had the same error today; power out. Was about to write it up as the auto-link didn't find the bug, so this is pretty formal :) 

* exact camera hardware:

Wyze Cam, v2 (WYZEC2)

* the Xiaomi-Dafang-Hacks commitid (from `git log`) you are experiencing the issue with:
Downloaded today

### Description

I got everything working, changed some settings (Camera name, disabled arrows)

I then pulled the plug to reboot. (I know … probably dumb, but consumers are like that)

Now, despite running fsck from a root terminal session, it still says settings can't be changed, read only file system. 

I checked dmesg, and this doesn't look good:

```
[   20.670239] FAT-fs (mmcblk0p1): error, clusters badly computed (17 != 16)
[   20.677686] FAT-fs (mmcblk0p1): Filesystem has been set read-only

``` 

### What did you do to debug the issue

Ran fsck:

```
[root@CARECAM_1:~]# fsck -A -V
fsck (busybox 1.29.0.git)
Checking all filesystems
[root@CARECAM_1:~]#

```

No joy. No error messages, even with -v, but it didn't fix it either.

### Evidence

dmesg given above.

### Contribute Back  

The fix for me was to move the sdcard back to my PC, and run chkdsk /f. Oddly, it reported no errors:

```
[C:\]chkdsk e: /f
The type of the file system is FAT.
Volume NEW VOLUME created 1/6/2019 8:28 AM
Volume Serial Number is BCCE-6382
Windows is verifying files and folders...
File and folder verification is complete.

  536,584,192 bytes total disk space.
       16,384 bytes in 2 hidden files.
      253,952 bytes in 31 folders.
   39,690,240 bytes in 211 files.
  496,623,616 bytes available on disk.

        8,192 bytes in each allocation unit.
       65,501 total allocation units on disk.
       60,623 allocation units available on disk.

```
I'm not sure if the linux distro can handle power outs, but maybe we should convert to ext file system? I'll report back if I figure it out.

**Comment by jamman9000** [comment]
> ### What did you do to debug the issue
> Ran fsck:
> 
> ```
> [root@CARECAM_1:~]# fsck -A -V
> fsck (busybox 1.29.0.git)
> Checking all filesystems
> [root@CARECAM_1:~]#
> ```
> No joy. No error messages, even with -v, but it didn't fix it either.
> 
> ### Evidence
> dmesg given above.
> 
> ### Contribute Back
> The fix for me was to move the sdcard back to my PC, and run chkdsk /f.

Did you try the command mentioned above? `mount -o remount,rw /system/sdcard`

**Comment by jgwinner** [comment]
> Did you try the command mentioned above? mount -o remount,rw /system/sdcard

No, honestly I had already fixed it via chkdsk before I saw this thread. 

I realize this would help with debugging, but I don't see shell access as a permanent fix. At the most, there could be a UI for doing this in the web pages under setup, but that could generate a DOS attack too.

**Comment by devnull404-pi** [comment]
I hope it helps: 

Once I had this problem with a Dafang with motion detection activated and capturing snapshots in local storage (I didn't notice I ever activated that option). I was missing that I had only 512MB, and the read only flag in notifications appeared because the storage was already full. Yet, after deleting all media, the error remained. I just had to delete all from de SD card and copy the modified firmware, easy as c/p. Not need to reflash.

**Comment by Bazowsky** [comment]
Have same issue every power cycle on camera with ALWAYS ON TIME LAPSE RECORDING to sdcard.

Found dirty solution to put script in `/system/sdcard/config/userscripts/startup/chkRO.sh`

```
#!/bin/sh
PATH=/system/sdcard/bin:/system/bin:/bin:/sbin:/usr/bin:/usr/sbin

mkdir /system/sdcard/ReadOnlyTest/
if [ $? -ne 0 ] ; then
        /system/sdcard/bin/audioplay /usr/share/notify/CN/speaker.wav 100
        dosfsck -a /dev/mmcblk0p1
        mount -o remount,rw /system/sdcard
        rm -rf /system/sdcard/ReadOnlyTest/
        reboot
else
        rm -rf /system/sdcard/ReadOnlyTest/
fi
```

Dont forget to `chmod +x /system/sdcard/config/userscripts/startup/chkRO.sh`
This run on every startup and if mkdir fails, then run dosfsck, then remount, and reboot.

Typical error on dosfsck run is:
```
0x25: Dirty bit is set. Fs was not properly unmounted and some data may be corrupt.
Automatically removing dirty bit.
*** Filesystem was changed ***
Writing changes.
/dev/mmcblk0p1: 1582 files, 11615/60924 clusters
```

In my case doing just dosfsck and remount, without proper reboot will always cause some problems and kernel crush in next 5-10 minutes.
With proper reboot, all going fine until next power cycle.

` /system/sdcard/bin/audioplay /usr/share/notify/CN/speaker.wav 100` 
command just for fun, you can drop it in you script.

Another approach to do same check, is in placing script in
`/system/sdcard/config/cron/periodic/15min/chkRO.sh`
But, CRON trying to write log on sdcard, and drop errors like this, 
```
crond: USER root pid 23646 cmd busybox run-parts /system/sdcard/config/cron/periodic/15min
crond: crond (busybox 1.32.0.git) started, log level 8
crond: can't open '/system/sdcard/log/crond.log': Read-only file system
```
And some times fails to execute script, some times run it, have no idea about this.
