### ISSUE TITLE
Website not working properly

### ISSUE THREAD

**Issue by stve-a** [EliasKotlyar/Xiaomi-Dafang-Hacks#410]
Hi guys, 

(Update: issue on both DAFANG and XIAOFANG S1)

Hacked my dafang and RTSP, ping, SSH, etc ... everything works, except the website.

When I go to https://(ipaddr)/cgi-bin/status.cgi I get a white page with all options and buttons under eachother, see screenshot below.

When I try and change something like timezone or hostname, it does not work and receive a "404 - Not Found" for the URL -> https://(ipaddr)/cgi-bin/cgi-bin/action.cgi?cmd=settz

Notice de double /cgi-bin/cgi-bin
When I remove one /cgi-bin and a press enter on that url, the changes are applied.

This goes for everything.
Problem is that I cannot manipulate it for bottons that control the pan and tilt and so on, which makes me unable to control the camera.

Am I doing something wrong ?
I using the master build from https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks.git

Anyone who can point me in the right direct to further troubleshoot or solve this ?

Kind regards
S
![cgi-bin_status cgi](https://user-images.githubusercontent.com/11457252/40931044-d4ee4300-6829-11e8-8abd-f103518ca642.png)

**Comment by nik0** [comment]
Try just  https://(ipaddr)
You don't go through index.html which loads css and everything ...

**Comment by stve-a** [comment]
@nik0  wow, that just works straight away. I followed the wiki. So always thought I had to go to the status.cgi one.

Now I can control the camera, thanks alot !
Works for the FANG S1 aswell !

Do you get the website like my screenshot above as well when you go to the the status.cgi ?
specially the double /cgi-bin url entries are weird.

I tried it in chrome, firefox and IE8, all have it.

**Comment by nik0** [comment]
I don't get the double /cgi but I have the same layout ...
I was not aware of that in the wiki ...

**Comment by stve-a** [comment]
Well now that I search for it, I cannot find it but I know where my assumption came from.
Initially I didn't know I had a new S1, so I was reading and trying ... https://github.com/samtap/fang-hacks

And there you are pointed to the status page, so I assumed I had to go to status.cgi here aswell.
Anyways all is good.

Appreciated !
