### ISSUE TITLE
HTML GUI broken on latest commit

### ISSUE THREAD

**Issue by mr-orange** [EliasKotlyar/Xiaomi-Dafang-Hacks#413]
I've just updated to last commit and seem something is broken on the html page.
All buttons are not working and firefox debug console raise a lot of XML error.

**Comment by hcgonzalezpr** [comment]
None of the camara controls seems to work for me.

For example executing : https://balconycam.mylocal.network/cgi-bin/action.cgi?cmd=ir_cut_off

Returns a blank response, and no action is performed on the camara.

**Comment by iashwinprasada** [comment]
yes, i also have the same issue

**Comment by Dopeyr** [comment]
Looks like a syntax error in action.cgi. 


```
       /system/sdcard/bin/setconf -k q -v "$F_audioinFilter" 2>/dev/null
       /system/sdcard/bin/setconf -k l -v "$F_HFEnabled" 2>/dev/null
       /system/sdcard/bin/setconf -k h -v "$F_audioinVol" 2>/dev/null
       return
   *)
    echo "Unsupported command '$F_cmd'"
```

Should be:

```
       /system/sdcard/bin/setconf -k q -v "$F_audioinFilter" 2>/dev/null
       /system/sdcard/bin/setconf -k l -v "$F_HFEnabled" 2>/dev/null
       /system/sdcard/bin/setconf -k h -v "$F_audioinVol" 2>/dev/null
       return
   ;;
   *)
    echo "Unsupported command '$F_cmd'"
```

Added `;;` below `return`

I can't try it until I'm home, but I think that will resolve it.

**Comment by nik0** [comment]
I thing you’re right 
Can not do the modifications from my phone 😢

**Comment by mr-orange** [comment]
@Dopeyr you are right. Just modded the file manually as per your instruction and rebooted.
Now the cam is working.
Thank you.

**Comment by saipsa** [comment]
@nik0 I am not sure, if I should open a new issue for this, so I am asking here. What are SMART and FixedQp encoding? I could find CBR and VBR using google.

Thanks

**Comment by nik0** [comment]
I don't know really, this is encoding proposed by the SDK :-)
You need to check how it renders for you ...
You can find some info on fixedQp on internet ... but I am not a video encoding expert ...

**Comment by iashwinprasada** [comment]
that fixed it, but anybody having OSD not showing up even after configuring in services? i was able to get time OSD by turning on and off the debug OSD. must be some startup issue?

**Comment by nik0** [comment]
I saw the problem. The problem is on the server I have a correction but I don't understand why so far ...

**Comment by mr-orange** [comment]
I'm closing this issue because is resolved.

**Comment by mr-orange** [comment]
@nik0 I'm reopening the issue because the ';;' added to fix the issues are not indended well.
So the fix is not working.

**Comment by nik0** [comment]
What is wrong ? It seems to work for me ...

**Comment by mr-orange** [comment]
Settings preferenze is not working... the position of the added ;; is not right

________________________________

**Comment by Dopeyr** [comment]
I don't see any syntax errors now after @nik0's fix. Might be a different issue? Shell scripts don't care about indentation as far as I know.

**Comment by mr-orange** [comment]
I just updated again and I can confirm I was wrong.... all is working I think it was a browser cache issue.
Sorry
