### ISSUE TITLE
Can't start mqtt-control

### ISSUE THREAD

**Issue by sergiofslopes** [EliasKotlyar/Xiaomi-Dafang-Hacks#414]
Can’t star the mqtt-control. Changed the mqtt.conf but mqtt-control allways shows “nok”.
Is there anyone that could help?
Thanks.

**Comment by jmtatsch** [comment]
What mqtt broker do you run?

**Comment by sergiofslopes** [comment]
Hi, I'm using the native Home Assistant mqtt broker and I set my mqtt.conf like this

```
USER=XXX
PASS=XXX
HOST=localhost
PORT=1883
```
on Home Assistant configuration.yaml like this:

`mqtt:
  broker: localhost
  port: 1883
  username: XXXX
  password: XXXX
  keepalive: 60
  discovery: true
  discovery_prefix: homeassistant` 

![sem titulo](https://user-images.githubusercontent.com/39806421/40993230-e9bb3b72-68f0-11e8-96b8-50b0854ff45b.jpg)

**Comment by jmtatsch** [comment]
nah for some reason that doesn't work. use mosquitto like mentioned in the guide.

**Comment by sergiofslopes** [comment]
Can you help me? I'm quit noob with this. 
what should I change?

**Comment by jmtatsch** [comment]
https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/integration/homeassistant/homeassistant.md

**Comment by hcgonzalezpr** [comment]
I have the same issue:

If i try to run mqtt-autodiscovery.sh from the command line I get the following:

[root@balconycam:scripts]# ./mqtt-autodiscovery.sh
: not founddiscovery.sh: /system/sdcard/config/mqtt.conf: line 4:
: not founddiscovery.sh: /system/sdcard/config/mqtt.conf: line 6:
: not founddiscovery.sh: /system/sdcard/config/mqtt.conf: line 12:
: not founddiscovery.sh: /system/sdcard/config/mqtt.conf: line 15:
: not founddiscovery.sh: /system/sdcard/config/mqtt.conf: line 18:
: not founddiscovery.sh: /system/sdcard/config/mqtt.conf: line 23:
: not founddiscovery.sh: /system/sdcard/config/mqtt.conf: line 26:
: not founddiscovery.sh: /system/sdcard/config/mqtt.conf: line 31:
: not founddiscovery.sh: /system/sdcard/config/mqtt.conf: line 34:
: not founddiscovery.sh: /system/sdcard/config/mqtt.conf: line 37:
/system/sdcard/bin/mosquitto_pub.bin: can't load library 'libmosquitto.so.1'
/system/sdcard/bin/mosquitto_pub.bin: can't load library 'libmosquitto.so.1'
/system/sdcard/bin/mosquitto_pub.bin: can't load library 'libmosquitto.so.1'
/system/sdcard/bin/mosquitto_pub.bin: can't load library 'libmosquitto.so.1'
/system/sdcard/bin/mosquitto_pub.bin: can't load library 'libmosquitto.so.1'
/system/sdcard/bin/mosquitto_pub.bin: can't load library 'libmosquitto.so.1'
/system/sdcard/bin/mosquitto_pub.bin: can't load library 'libmosquitto.so.1'
/system/sdcard/bin/mosquitto_pub.bin: can't load library 'libmosquitto.so.1'
/system/sdcard/bin/mosquitto_pub.bin: can't load library 'libmosquitto.so.1'
/system/sdcard/bin/mosquitto_pub.bin: can't load library 'libmosquitto.so.1'
/system/sdcard/bin/mosquitto_pub.bin: can't load library 'libmosquitto.so.1'
/system/sdcard/bin/mosquitto_pub.bin: can't load library 'libmosquitto.so.1'
/system/sdcard/bin/mosquitto_pub.bin: can't load library 'libmosquitto.so.1'
/system/sdcard/bin/mosquitto_pub.bin: can't load library 'libmosquitto.so.1'
/system/sdcard/bin/mosquitto_pub.bin: can't load library 'libmosquitto.so.1'

**Comment by sergiofslopes** [comment]
Just solve my issue. There was a little problem with my mqtt host.
Thanks

**Comment by myusuf3** [comment]
@sergiofslopes what was it?

**Comment by marrobHD** [comment]
I have the same problem. What was the problem

**Comment by jokerigno** [comment]
Can you show us your solution?

**Comment by indiocochino** [comment]
Same problem here...tried to use "" with user and password, but nothing happens.
Please help!

**Comment by brendanmullan** [comment]
To anyone who's got this issue, it's likely formatting in the config file. I too was frustrated with this as it's not overly clear in the documentation on how to do it if you're not very familar with this sort of thing.  I'll try submit a pull request with some extra clarification if I get some time soon, the author of Dafang Hacks has done so much excellent work and we should help where we can.

Here's my config (**mqtt.conf** - placed into system/sdcard/config/) for connecting to Mosquitto Broker in Hass.io - You should have the username, password, host and port between single quotation marks. The host should be the IP of your Raspberry PI. You should also get your router to assign a static IP to the PI if you haven't done so already or this will break once you reboot the PI.

```
# Options for mosquitto_sub & mosquitto_pub
USER='xxxxxx'
PASS='xxxxxx'
HOST='192.168.xxx.xxx'
PORT='1883'


# Define a location
LOCATION="myhome"

# Define device name
DEVICE_NAME="Dafang"

# Define the base topic used by the camera
# send a message to myhome/dafang/set with the payload help for help.
# Results will be placed in myhome/dafang/${command} or topic/dafang/error - so please subscribe topic/dafang/# for testing purposes
TOPIC="$LOCATION/$DEVICE_NAME"

# Define an autodiscovery prefix, if autodiscovery is desired:
AUTODISCOVERY_PREFIX="homeassistant"

# Define additional options for Mosquitto here.
# For example --cafile /system/sdcard/config/DST_Root_CA_X3.pem --tls-version tlsv1
# or use a special id to connect to brokers like azure
MOSQUITTOOPTS=""

# Add options for mosquitto_pub like -r for retaining messages
MOSQUITTOPUBOPTS=""

# Send a mqtt statusupdate every n seconds
STATUSINTERVAL=30

# Define whether you would like to have light level exposed (by hardware sensor og virtual calcuations).
# If the device doesn't come with a hardware sensor, your only option is to use 'virtual'.
# 
#  Options:
#     hw = Use 'hw' if the device has build in hardware light sensor. For more details, see . See issue eg. #1120 for more details...
#     virtual = Use 'virtual' calculations, based on the lightlevel on the image, also known as ISP exposure (from /proc/jz/isp/isp_info)
#     false = Use 'false' (default) to DISABLE the topic (It will not publishing details about light level)
LIGHT_SENSOR="false"
```

**Comment by jokerigno** [comment]
Hi all,

in my case the issue happens when I try to start mqtt status and mqtt control simultaneusly.

If I tick mqtt status, wait few seconds, and then tick mqtt control it starts without issue.

Maybe it's not related to config but it's a bug.

**Comment by tjharman** [comment]
For anyone else that encounters this problem, it can be caused by a stale process ID file (.pid file)
SSH onto the camera and run

`rm /run/mqtt-control.pid`

This will remove the stale file and allow the process to start (assuming that was the problem and not some other config issue)

You can know this is the cause of your problem by running

`/system/sdcard/controlscripts/mqtt-control start` and if it returns
`MQTT Control already running` then it thinks there's already a control process running.
