### ISSUE TITLE
flip is not working from the Webinterrface

### ISSUE THREAD

**Issue by staudtm** [EliasKotlyar/Xiaomi-Dafang-Hacks#417]
Hello,

I am running the camera with the latest version (05-JUN-2018).

I have difficulties to use the FLIP option. It is not working from the Webinterface, but when I run it from the command line (/system/sdcard/bin/setconf -k f -v 1), it works!

The strange thing is that it is NOT working when I paste "/system/sdcard/bin/setconf -k f -v 1" in run,sh?!

Can someone confirm this behaviour?

Just to mention it: permanent FLIP was working already in previous versions by inserting the setconf command in run.sh

Regards
Markus

**Comment by nickyhuyskens** [comment]
I hope I'm not too late, but I was having the same problem today!
what "fixed" it for me was adding the following line to the run.sh
`sleep 30 && /system/sdcard/bin/setconf -k f -v 1 &`
it just delays the command with 30 seconds

**Comment by codedmind** [comment]
When will be possible set this persistent way? After every upgrade that line goes away

**Comment by nik0** [comment]
Please check https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/pull/569

**Comment by jmtatsch** [comment]
Verified as fixed in #569
