### ISSUE TITLE
Is this hacks only for three models you have on front page?

### ISSUE THREAD

**Issue by lpt2007** [EliasKotlyar/Xiaomi-Dafang-Hacks#418]
How to know if my camera is compatible?

uname -a
[root@Ingenic-g1_1:www]# uname -a
Linux Ingenic-g1_1 3.10.14 #36 PREEMPT Mon Jul 31 18:07:54 CST 2017 mips GNU/Linux

**Comment by lpt2007** [comment]
system type           : mango
machine                       : Unknown
processor             : 0
cpu model             : Ingenic Xburst V0.0  FPU V0.0
BogoMIPS              : 858.52
wait instruction      : yes
microsecond timers    : no
tlb_entries           : 32
extra interrupt vector        : yes
hardware watchpoint   : yes, count: 1, address/irw mask: [0x0fff]
isa                   : mips32r1
ASEs implemented      :
shadow register sets  : 1
kscratch registers    : 7
core                  : 0
VCED exceptions               : not available
VCEI exceptions               : not available

Hardware              : isvp
Serial                        : 00000000 00000000 00000000 00000000

**Comment by jmtatsch** [comment]
Yes, only those models are supported right now. What camera do you want to see supported?

**Comment by jmtatsch** [comment]
Looks like you have a mango i.e. T10 based camera. https://github.com/dim08/Ingenic-T10_20/blob/master/dev_board/Mango/Mango_v11_开发板说明.pdf
Unfortunately this is not (yet) supported.

**Comment by EliasKotlyar** [comment]
Hello lpt2007,

I can try to make this camera compatible. Can you please dump the firmware and provide it as a pull request? I suppose that it should be really similar to the T20 Model. Most features should also work out of the box.

Greatings
Elias

**Comment by lpt2007** [comment]
Can you tell me how to dump firmware and I will do it.

thx in advance

**Comment by EliasKotlyar** [comment]
Just use following commands from this page:
https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/hacks/firmware-dump.md
Post the results here.

**Comment by lpt2007** [comment]
Here is my camera dump:
[https://mega.nz/#!x8sjgCoZ!cgyTbAGtGXC-QuRlMPgEEzSTusMHjnvMt0PwSCg9zQs](url)

**Comment by lpt2007** [comment]
`[root@Ingenic-g1_1:~]# cat /proc/mtd
dev:    size   erasesize  name
mtd0: 00040000 00008000 "boot"
mtd1: 00280000 00008000 "kernel"
mtd2: 00200000 00008000 "root"
mtd3: 00340000 00008000 "appfs"
`

**Comment by lpt2007** [comment]
What do you think about this?
[](https://github.com/samtap/fang-hacks/issues/363#issuecomment-399753599)

**Comment by lpt2007** [comment]
Hi can you explain me bit more?

 You send me rootfs.bin file in the instruction I need to get u-boot.imx. Where I can get that file?

ver and fatls command not working:
[root@Ingenic-g1_1:~]# ver
-sh: ver: not found

[root@Ingenic-g1_1:~]# fatls mmc 0:1 /
-sh: fatls: not found

**Comment by lpt2007** [comment]
Blue light is lit and red light is flashing slow after camera flash? Any idea why?

[https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/671](url)
