### ISSUE TITLE
Wifi Signal Quality

### ISSUE THREAD

**Issue by zhajar** [EliasKotlyar/Xiaomi-Dafang-Hacks#42]
This is not really an issue with this project but I was just wondering if anyone applied any mods to increase the wifi performance of this camera.

I have a good router but I'm finding that the camera can't keep a stable connection if there is more than 1 wall separating it from the router.

**Comment by Shaktohh** [comment]
I have 2 bearing wall (stone) and another wall and no problem.

**Comment by EliasKotlyar** [comment]
You can add some antennas using a normal pigtail connector to increase the range. Refer to the teardown to find out the connector type.

**Comment by zhajar** [comment]
Thank you for your help on this. I appreciate it. I took it apart and found that the internal antenna was disconnected from the board. Reconnecting it fixed the range issue.
