### ISSUE TITLE
Saving to USB

### ISSUE THREAD

**Issue by asecor** [EliasKotlyar/Xiaomi-Dafang-Hacks#420]
With the original Xiaomi Software, (Android) app & USB stick connected, you could have motion detected footage (or continuous recording) saved directly to the USB stick for later viewing. 

Is it possible to achieve the same thing on this custom firmware? I have seen there is a way to save to SD card, can the same be for USB? I am able to mount and access the USB (it is NTFS), but I get the following:

```
[root@DAFANG:dev]# mount /dev/sda1 /media/usb
[root@DAFANG:dev]# /system/sdcard/bin/h264Snap > /media/usb/video.h264
Segmentation fault
[root@DAFANG:usb]# cd /system/sdcard/bin/
[root@DAFANG:bin]# h264Snap
failed to AddSensor
IMP_System_Init() failed
Segmentation fault
```

**Comment by jmtatsch** [comment]
Good idea. Did you try create a file on that volume by hand?

**Comment by asecor** [comment]
That works:

```
[root@DAFANG:usb]# pwd
/media/usb
[root@DAFANG:usb]# mkdir test
[root@DAFANG:usb]# ls
test
[root@DAFANG:usb]# touch testingdefang.file
[root@DAFANG:usb]# ls
testingdefang.file
```

**Comment by tetreum** [comment]
@asecor did you succeed?

**Comment by coolVariable** [comment]
How do you save to the SD card?
And is there a way to use the full size of the SD card? I have 32GB cards but had to format them to less than 1GB in order for the hack to load properly.

**Comment by jmtatsch** [comment]
The small partition loading shenanigans is only valid when applying the cfw via the demo bin route.
