### ISSUE TITLE
Calibration always horizontal

### ISSUE THREAD

**Issue by staudtm** [EliasKotlyar/Xiaomi-Dafang-Hacks#421]
Hello,
when I start the calibration it is doing horizontal calibration always, that means also when I click the "vertical" button.

**Comment by jmtatsch** [comment]
That behaviour was introduced by the new motor driver. I will adjust the buttons accordingly.

**Comment by franciz16** [comment]
I suggest you put calibration routine command in run.sh, so it would start on power-on.
