### ISSUE TITLE
Time Zone Issue

### ISSUE THREAD

**Issue by asecor** [EliasKotlyar/Xiaomi-Dafang-Hacks#423]
Setting the time zone to GMT-2 corrects the time being displayed, though strangely I am in GMT+1 (Netherlands) so it anything it could either be GMT+1 or GMT+2 (daylight saving), but for sure not GMT-2:

![image](https://user-images.githubusercontent.com/13489208/41066220-76292ef2-69e1-11e8-95c9-515d163f1345.png)

For sanity check I tried different NTP severs (0.europe.pool.ntp.org).

**Comment by mixpc** [comment]
Same here. I thought I was going crazy. TZ set to +2 via webinterface:

```
Setting TZ to 'UTC+2:00'...

Syncing time...

Success
```

It should show 20.45h when it actually shows Thu Jun 7 16:45:12 UTC 2018 and 16:45 UTC +2 is still 18:45. Minor bug, though. This Dafang Hack simply rules!

**Comment by nik0** [comment]
Not sure it makes difference I have "UTC-2:00" in TZ field ...

**Comment by asecor** [comment]
@nik0 - I can confirm, setting UTC-2 also works. 

![image](https://user-images.githubusercontent.com/13489208/41123724-ea1092ba-6a9f-11e8-8166-5670fc7cb72e.png)

I guess this can be closed now?
