### ISSUE TITLE
Unable to connect to my Network (Wyze Cam V2)

### ISSUE THREAD

**Issue by astronaut701** [EliasKotlyar/Xiaomi-Dafang-Hacks#425]
I have repeatedly done the instructions (besides the mircoSD bootloader, that's a one time thing) and I have gotten the solid blue light (which is supposed to indicate it has connected and is working), but it never connects to my WiFi network. I have configured the file necessary to make the camera connect. (aka wpa_supplicant.conf) Is there anything I could try make it connect and be able to stream video from the camera?

**Comment by jmtatsch** [comment]
Startup log please

**Comment by astronaut701** [comment]
Question, I do I get the startup log, from the micro sd card or connecting the camera?

**Comment by astronaut701** [comment]
Completely ignore the question above, found it, I will upload it

**Comment by astronaut701** [comment]
Read the Log, seems it can't read the wifi config file for some reason, send me upload both files instead of just the log.

**Comment by astronaut701** [comment]
https://jpst.it/1gi7D (Startup Log file)

**Comment by astronaut701** [comment]
Never mind on the wifi config file, that contains my wifi info!

**Comment by astronaut701** [comment]
I wonder what I did wrong, should I be renaming the file extension from .conf.dist to .conf, or should I make a completely new file?

**Comment by jmtatsch** [comment]
rename the file extension from .conf.dist to .conf

**Comment by astronaut701** [comment]
Ah, gotcha, that is probably my problem.

**Comment by astronaut701** [comment]
It also fails to parse the network name and password.

**Comment by jmtatsch** [comment]
Did the startup log change? maybe you have windows line endings in the .conf file now?

**Comment by astronaut701** [comment]
hmm, let me check, i'll upload the file to you.

**Comment by astronaut701** [comment]
Here you go, https://jpst.it/1gizJ, the removed text is just removing my network name + password, I do note the before the network name, there is a ' then the " like this, ' "example" ' (no spaces)

**Comment by astronaut701** [comment]
My network also has a space in it, do I just add a space or add _ to it?

**Comment by jmtatsch** [comment]
seems like you have doubled up your quotes somehow. Don't use an underscore. only double quotes.

**Comment by astronaut701** [comment]
ok, so like that? "example"

**Comment by jmtatsch** [comment]
yes

**Comment by astronaut701** [comment]
will do

**Comment by astronaut701** [comment]
it says invalid PSK in the log, will upload the rest

**Comment by astronaut701** [comment]
(just decided to just post it here)
==================================================
Starting the Dafang Hacks Custom Application Layer
==================================================
Loaded common functions
Bind mounted /system/sdcard/root to /root
Bind mounted /system/sdcard/etc to /etc
wpa_supplicant: Successfully initialized wpa_supplicant
Line 9: failed to parse ssid '“removed”'.
Line 9: failed to parse ssid '“removed”'.
Line 15: Invalid PSK '“removed”'.
Line 15: failed to parse psk '“removed”'.
Line 17: failed to parse network block.
Failed to read or parse configuration '/system/sdcard/config/wpa_supplicant.conf'.

**Comment by jmtatsch** [comment]
You quotes are still wrong. Use " instead of “. There is a difference if you look closely.

**Comment by openipcamera** [comment]
The kernel of the wyzev2 is different than the Xiamo Dafang kernel. the wifi module does not work. Check the openipc repo for a proper .bin with the right kernel modules.

**Comment by astronaut701** [comment]
Solved, I just copy and pasted the text from the original file, then just changed the ssid and password sections only to get it to work, which corrected any issues my quotation marks.
