### ISSUE TITLE
Noob question about the mainpage preview video many lagging

### ISSUE THREAD

**Issue by kevinshane** [EliasKotlyar/Xiaomi-Dafang-Hacks#427]
Hi sir first of all congrates the awesome job for the cam, I've successfully hacked the dafang cam and get it working.
However when I go to the front page `https://192.168.0.xx/` it shows the video preview with so many lagging, and it barely can move the camera via the red handle(like pressing the button and wait around 10 sec, then can see the view change). Then I try rtsp in potplayer, it still laggy but much much better(3-4sec to see the view change)
I am sure my wifi connection is good enough(tested in xiaomi app with no lag and smooth moving view), I use a C4 class 4g sd card(very old one, not sure if this is the reason causing this lag)
Could some gurus please help me solve this problem, am I the only one facing this laggy problem? Many Thanks!

**Comment by Dopeyr** [comment]
Hi, the image on the frontage isn't a video, but an image that reloads every 5 seconds, so it's normal to see a delay.

The lag in RTSP video is *roughly* consistent with what I see, I wouldn't say 3-4 seconds, more like 1-2 s for me. I don't know of a solution, but you might want to play around with the video modes and bitrate in the settings.

**Comment by kevinshane** [comment]
@Dopeyr Thank you sir, I took your advise and play around the video format, currently I have set the format to 2000 bitrate and VBR, I get a better video quality with 720P, for the lag, I tested couple of times and found that if I restart/shutdown the device and turn it back on, the very laggy appears(3-4sec moving), and after a while(not sure how long but I would say a few minutes later), the lag becomes much less(1-2sec) and everything seems stable currently.
Anyway thank you so much for your comments, have a nice day

**Comment by jmtatsch** [comment]
Closing this as your question was answered.
