### ISSUE TITLE
Recording video segments

### ISSUE THREAD

**Issue by nbourre** [EliasKotlyar/Xiaomi-Dafang-Hacks#429]
Hey guys,

I've been trying to record continuous segments, but without success.

This is the command I try to launch to record 60 seconds segments.

/system/sdcard/bin/avconv -rtsp_transport tcp -y -i rtsp://0.0.0.0:8554/unicast -vcodec copy -c:a aac -strict experimental -f segment -segment_time 60 -segment_format mp4 /system/sdcard/DCIM/VideoRecorder/`date +%Y-%m-%d_%H.%M`.mp4

Unfortunately, I always get "Output file #0 does not contain any stream".

What is wring with my command?

**Comment by jmtatsch** [comment]
is the mjpg or h264 server running?

**Comment by nbourre** [comment]
The H264, I've read about the mjpg, but I get a "NOK" error.

**Comment by nbourre** [comment]
Ok, I've figured out options that works

FILE=`date +%Y-%m-%d_%H.%M_%04d.mp4` && /system/sdcard/bin/avconv -rtsp_transport tcp -y -i rtsp://0.0.0.0:8554/unicast -vcodec copy -c:a aac -map 0:0 -f segment -segment_time 60 -segment_format mp4 /system/sdcard/DCIM/VideoRecorder/$FILE

Now my problem is I don't have any audio. I've check different answers in the issue sections, but no success.

**Comment by molo1134** [comment]
To get the audio, I had success using a different container format instead of mp4.  I used mkv filenames and `-acodec copy`.  I have h264 video and mp3 audio at 16 kHz configured.

```
avconv -v quiet -rtsp_transport tcp -y -i \
rtsp://127.0.0.1:8554/unicast -vcodec copy -acodec copy \
-strict experimental file.mkv
```

**Comment by goermezer** [comment]
Thanks a lot @molo1134. I spent too much time to get a successful recording with avconv. I wouldn`t expect, that a mkv container makes a so much difference. Unfortunately I still have this error with -rtsp_transport tcp:

[rtsp @ 0x198e100] CSeq 5 expected, 0 received.

When I use -rtsp_transport udp, the recording is quite good with avconv as well as ffmpeg. So I mounted my NAS via NFS and record directly to NAS. It seems to work quite good so far. This is my recording script in /system/sdcard/config/userscripts/motiondetection/

#!/bin/sh

PIDFILE=/root/avconv.pid

if [ "$1" == "on" ]; then
    filename=`date +%d.%m.%Y-%H%M%S`
    if [ -f $PIDFILE ]; then
        echo "Recording process is already running, PID: $(< $PIDFILE)"
        exit 1
    else
        /system/sdcard/bin/avconv -v quiet -t 30 -rtsp_transport udp -buffer_size 512k -max_delay 0 -analyzeduration 0 -probesize 32 -y -i rtsp://127.0.0.1:8554/unicast -c copy -strict experimental -pix_fmt yuv420p /system/sdcard/nas/Kameras/dafang1/media/`date +%d.%m.%Y-%H%M%S`.mkv && rm $PIDFILE &
        PID=$!
        echo $PID > $PIDFILE
    fi
fi

Does anybody have an idea, how to modify it for a timer?  I would like to check, whether avconv is already recording whenever motion is detected. The timer then should be extended. After no motion detection for a defined period, avconv should be stopped. Unfortunately my skills about shell scripting are not enough to implement it.

**Comment by goermezer** [comment]
Ok, I tried it. Here are two scripts. First one runs in background and watches the file /root/motion.dat which is updated with the motion events on/off from the seconds script. It works like a timer with 2 seconds interval and stops avconv after 30 seconds recording and when no more motion happens. Simply put it into /system/sdcard/config/userscripts/startup:

```
#!/bin/sh 

#date=`busybox stat -c %Y /root/motion.dat`
count=2
PIDFILE_AVCONV=/root/avconv.pid

while sleep 1; do
    date=`busybox stat -c %Y /root/motion.dat`
    sleep 1
    date2=`busybox stat -c %Y /root/motion.dat`
    if [[ $date2 -eq $date ]]; then 
        echo "File not changed since $count seconds!"
        let "count+=2"
        if [[ $count -ge 30 ]]; then
            if [ -f $PIDFILE_AVCONV ]; then
                echo "Recording STOP"
                cat $PIDFILE_AVCONV > $PIDFILE_AVCONV
                rm $PIDFILE_AVCONV
            fi
            pkill -f "/system/sdcard/bin/avconv" # sometimes needed
        fi
    else
        echo "Changed"
        count=2
    fi
done
```
This one is an update of the previous post. It simply writes the motion events on/off to /root/motion.dat and starts avconv. Put it into /system/sdcard/config/userscripts/motiondetection/

```
#!/bin/sh

PIDFILE_AVCONV=/root/avconv.pid
DETECTION=/root/motion.dat

if [ "$1" == "on" ]; then
    echo "on" > $DETECTION
    if [ -f $PIDFILE_AVCONV ]; then
        echo "Recording already running, PID: $(< $PIDFILE_AVCONV)"
        cat $PIDFILE_AVCONV > $PIDFILE_AVCONV
        exit 1
    else
        filename=`date +%d.%m.%Y-%H%M%S`
        /system/sdcard/bin/avconv -t 300 -rtsp_transport udp -buffer_size 512k -max_delay 0 -analyzeduration 300k -probesize 1M -y -i rtsp://127.0.0.1:8554/unicast -c copy -strict experimental -pix_fmt yuv420p /system/sdcard/nas/Kameras/dafang1/media/$filename.mkv &
        PID_AVCONV=$!
        echo $PID_AVCONV > $PIDFILE_AVCONV
        echo "Recording START [$PID_AVCONV]"
    fi
fi
if [ "$1" == "off" ]; then
     echo "off" > $DETECTION
fi
```

My tests were more or less successful. But Recording with ffmpeg from another computer makes better results for me than direct recording - especially when the scene is more complex like lots of light.
