### ISSUE TITLE
Blocked Cam after moving with  stream running

### ISSUE THREAD

**Issue by mmohamed** [EliasKotlyar/Xiaomi-Dafang-Hacks#43]
Hi,

Cam is totaly blocked, HTTP do not answer, lose SSH connection and RTSP stream, if i move it (with calibrate or step moving) many times.

I don't found log file when i restart it (manualy) and i dont have any idea why it's happened.

NOTE: I use last version from Repository.

**Comment by dmolner** [comment]
I haver similar poblem when torn to right not to left.
But I can reboot.

**Comment by EliasKotlyar** [comment]
@mmohamed : Can you try to use another power plug? Sounds like a lack of power.

**Comment by mmohamed** [comment]
hi @EliasKotlyar, this problem is just appeared with motor action and stream on.
When i try to use motor.bin directly, it is run normaly for first time, then it don't respond (no output and not finished) with motor sound but it's dont turn.

Maybe i can help with motor.bin code source or with debug mode.

**Comment by CliffordClavin** [comment]
The source for the motor.bin should be in Elias other repository: https://github.com/EliasKotlyar/Xiaomi-Dafang-Software

Did you try Elias' suggestion to use another power supply? Total hangup sounds like a problem in this area. I couldn't replicate the described hangup, by streaming and moving the camera.

**Comment by MasterPIC** [comment]
Maybe some noise coming from the motor? Maybe moving/shielding the motor cable can fix it?

**Comment by EliasKotlyar** [comment]
Hello @mmohamed ,

Could you please give a update on this topic? 

Many thanks,
Elias

**Comment by mmohamed** [comment]
Hi @EliasKotlyar , 
After investigation on ioctl function in motor.c, the problem is due to the power of the Cam, it was rather using a dedicated power supply. When the motor blocks, ioctl does not return the hand and the motor does process not stop (with many motor process on, Cam blocked).

Thank you, I close the issue
