### ISSUE TITLE
Audio playback via ossplay is broken

### ISSUE THREAD

**Issue by jmtatsch** [EliasKotlyar/Xiaomi-Dafang-Hacks#434]
```
ossplay /usr/share/notify/CN/init_ok.wav -v
Playing WAVE file init_ok.wav, 16 bits/mono/8000 Hz
Time: 00:04.47 of 00:04.47 VU 0
```
looks okay, but there is nothing to hear.

**Comment by nik0** [comment]
As now we are back to the original audio module we need to use the SDK API.
audioplay is working. I didn't put it back as I didn't migrate the sources on the new repo.
I guessed no one use it as the audio is in Chinese.

**Comment by jmtatsch** [comment]
It is cool for sending notifications to the camera. Eventually we could have a mqtt text to wav bridge.

**Comment by gadget78** [comment]
is there any way to implement this .wav play? .. 
as sending notifications is the reason i would want this 
for door bell,call kids in for tea, after motion detection acting as a deterrent  etc etc...

just a way to trigger the .wav files already on camera, like we could on the older GUI theres around 5-10 to choose from... activating via MQTT would be magic .. 
leave adding ability to 'send' audio to play for later... just triggering whats on there will be good :)
or is there pointers in the direction i could try implement this myself ?
