### ISSUE TITLE
Autoupdate does not work

### ISSUE THREAD

**Issue by olskar** [EliasKotlyar/Xiaomi-Dafang-Hacks#441]
Autoupdate does not work for some reason. I have tried both running it via GUI and running the script directly, the script finds files that needs to be updated and then reboots, after reboot nothing has changed.

**Comment by nik0** [comment]
Any logs ? Try verbose option 
The update process is running in several steps:
- compare and get files in /tmp/update folder
- copy all the new files from tmp to sdcard
- stop services and reboot
From your description I would say the step 2 failed. Can you check there is something in the tmp folder while the update. 
May be your file system is mounted in read only ?

**Comment by olskar** [comment]
@nik0 

The files gets downloaded to /tmp/update during the script running, it looks like step 2 is failing since the new files does not get moved to sdcard..

This is result from mount, looks fine to me. I can also create files and folders manually on sdcard from terminal so it seems to be mounted in read/write

`rootfs on / type rootfs (rw)
/dev/root on / type squashfs (ro,relatime)
tmpfs on /dev type tmpfs (rw,relatime)
proc on /proc type proc (rw,relatime)
devpts on /dev/pts type devpts (rw,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /tmp type tmpfs (rw,relatime)
tmpfs on /run type tmpfs (rw,nosuid,nodev,relatime,mode=755)
sysfs on /sys type sysfs (rw,relatime)
media on /media type tmpfs (rw,relatime)
/dev/mtdblock3 on /driver type squashfs (ro,relatime)
/dev/mtdblock4 on /system type jffs2 (rw,relatime)
/dev/mtdblock7 on /backupa type jffs2 (rw,relatime)
/dev/mtdblock8 on /configs type jffs2 (rw,relatime)
/dev/mtdblock9 on /params type jffs2 (rw,relatime)
/dev/mmcblk0p1 on /system/sdcard type vfat (rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro)
/dev/mmcblk0p1 on /root type vfat (rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro)
/dev/mmcblk0p1 on /etc type vfat (rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro)`

**Comment by nik0** [comment]
Can you post  the logs with the -v -p options ?

**Comment by nik0** [comment]
I observe the same issue now
It seems that the update is done on /system/sdcard/system/sdcard
I don't know why for now ...

**Comment by nik0** [comment]
Found why !
no one noticed it ... In my last PR (I will merge it)
