### ISSUE TITLE
Tinycam untrusted connection

### ISSUE THREAD

**Issue by MasterPIC** [EliasKotlyar/Xiaomi-Dafang-Hacks#444]
Hi,

I'm no more able to move the camera by Tinycam.
Maybe the authentication is causing the issue together with a wrong configuration.
Are SSL and 443 port required to make remote controls working from Tinycam?

**Comment by jmtatsch** [comment]
Yes ssl is required now. Did you follow the guide in integrations?

**Comment by MasterPIC** [comment]
Ok,
I just executed
openssl req -new -x509 -keyout lighttpd.pem -out lighttpd.pem -days 365 -nodes
to generate the required pem file.
Then I forwarded 443 port (opened on my dafang) to a public port and I used it as the remote web port.
It seems working but by TinyCam I still read connection is not secure. Maybe it's just because of the certification...
I'm now able to move the cam also remotely.
I'm just not sure about the SSL. So is it working as expected?

Thanks again
Armando

**Comment by jmtatsch** [comment]
You need to trust your self-signed certificate. Not using SSL would be crazy these days.

**Comment by MasterPIC** [comment]
How to make TinyCam trust the certificate?

**Comment by jmtatsch** [comment]
I have no idea. Ask the developer.

**Comment by MasterPIC** [comment]
As with Chrome I think it doesn't trust the certificate but it uses an encrypted connection, that is what matters...

**Comment by jmtatsch** [comment]
https://stackoverflow.com/questions/37281958/how-to-trust-self-signed-certificate-on-android

**Comment by jmtatsch** [comment]
@MasterPIC Did installing the certificate work? Can we close this now?

**Comment by MasterPIC** [comment]
I installed it but both Chrome and TinyCam still report the root.
I think something more is required while generating the pem file but I didn't make other attempts.

**Comment by Daviey** [comment]
@MasterPIC Maybe consider trying the new letsencrypt support?  That will give you a real SSL cert, and you shouldn't need to import it into the client.

**Comment by MasterPIC** [comment]
@Daviey I just executed the script to obtain a real SSL cert. But should I remove lighttpd.pem??
Are they related?
In a few words with a fresh Dafang SD card what should I do to have SSL and tinycam controls working?
Thanks again!

**Comment by seiyria** [comment]
@Daviey I can't find anything in the documentation about _how_ to do this. My best guess is to run the script, but it keeps saying a directory (`config/ssl/acme`) exists so it must have already been done. When I delete the directory, it goes away. When I rerun the script, suddenly it's back.
