### ISSUE TITLE
How to control the motor right/left together with one command?

### ISSUE THREAD

**Issue by kevinshane** [EliasKotlyar/Xiaomi-Dafang-Hacks#449]
Hi all
Sorry maybe it's a stupid question, but how to controlling the motor x(left and right together)?
I try this command and it worked, it goes the the very left:
`http://192.168.0.120/cgi-bin/action.cgi?cmd=motor_left&val=2600`

and then I put the val to 0, nothing happen(obviously it already goes to the very left and won't continue):
`http://192.168.0.120/cgi-bin/action.cgi?cmd=motor_left&val=0`

When I need to go back to center(1300) I need to put this cmdt:
`http://192.168.0.120/cgi-bin/action.cgi?cmd=motor_right&val=1300`

My question is, does it possible to control the motor left and right together with one command? So that I can maybe put a slider(0-100 mapped to 0-2600 in node red) to rotate the cam in full range without seperate them into 2 cmd? or maybe a x value?
Sorry for the noob english, I hope I make myself clear, thanks all!

**Comment by jmtatsch** [comment]
not possible right now
