### ISSUE TITLE
Secure the Webpage with a Password ?

### ISSUE THREAD

**Issue by bestgrafix** [EliasKotlyar/Xiaomi-Dafang-Hacks#45]
Hi thanks for the hack, now i can use the cam after few months :)

Is it possible to get a login window to the control page , is any authentification possible ? Sorry iam only a user not an developer :)

greetings
Ben

**Comment by wert2all** [comment]
As I see You can modify a code from https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/tree/master/firmware_mod/www/cgi-bin

But I have another question - where need to store a default login and password?

**Comment by EliasKotlyar** [comment]
Hello @bestgrafix ,

This topic was already discussed here:
https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/24
