### ISSUE TITLE
How to install the Wyzecam Pan firmware onto Xiaomi Dafang?

### ISSUE THREAD

**Issue by bradc87** [EliasKotlyar/Xiaomi-Dafang-Hacks#450]
I am a huge fan and have been using dafang-hacks for quite a while now with my xaiomi dafang. I would like to try out the defauly wyzecam pan firmware to see what its like, can you provide instructions on how to install that firmware, what ive read online about renaming demo.bin does not seem to apply, as there are multiple bin files in your package.

**Comment by tssva** [comment]
It is installed in the same manner as for the other cameras. Follow the installation instructions linked to on the main page.

**Comment by mr350** [comment]
Hello tssva,

Could you elaborate a little more on flashing the OEM Wyzecam Pan firmware onto the Dafang? Using the same manner… part 1, copy cfw-1x.bin to micro-SD and rename it "demo.bin" and continue following the steps until I see the blue led shining up for 5 seconds (not blinking), that part all works fine! But what do I do now? In part 2 you’re supposed to Clone the repository and then copy everything from "firmware_mod" folder into the root of the micro-SD… how do I do this using the OEM Wyzecam Pan firmware bin file?

Thank you!

**Comment by xerexa** [comment]
I would also like to know how you can install the stock Wizecam Pan firmware on the Dafang camera.

**Comment by tssva** [comment]
It seems like I misunderstood the original question. I thought they were asking how to install the custom Wyzecam Pan firmware on the actual Wyzecam Pan. You can grab the original Wyzecam Pan firmware files at the Wyzecam site. https://www.wyzecam.com/forums/topic/flashing-your-wyzecam-pan-firmware/

If you are thinking you can install the firmware and then use the dafang with the Wyzecam app and cloud service, you are out of luck. The firmware will install, the Wyzecam setup process will successfully connect the camera to your wifi and that is where your success will end. During the process to associate your camera to the Wyzecam cloud service it sends a combination of information which the service can use to identify if the camera is a device produced for Wyzecam. Since it isn't your camera will not be associated to your Wyzecam account.

**Comment by bradc87** [comment]
And I suppose there is no way so far to spoof a device ID or anything like
that..
- Brad

**Comment by SamHead** [comment]
Has anyone found anything interesting in analyzing the Wyzecam Pan firmware ?

**Comment by hubmon** [comment]
Will the Wyzecam Pan RTSP beta work on the Dafang?

**Comment by wesbos** [comment]
It doesn't work - I just tried it. Best to go with another dafang RTSP firmware

**Comment by none815** [comment]
I got my Dafang working with the Wyze app.
It is "para.bin" that includes all necessary information, including MAC address.

- Download Wyzecam [para.bin](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/firmware_original/wyzecam_v2/4.9.1.60/para.bin) and flash it:
> flash_eraseall /dev/mtd9
> dd if=/system/sdcard/para.bin of=/dev/mtd9

- Then install the current Wyzecam [RTSP firmware](https://support.wyzecam.com/hc/en-us/articles/360026245231-Wyze-Cam-RTSP).

**Comment by hubmon** [comment]
Can't find #none815 comment posted yesterday, Dec 28. Deleted?

**Comment by wesbos** [comment]
Comment was as below. Would love to know more about how to do this:  

> I got my Dafang working with the Wyze app.
It is "para.bin" that includes all necessary information, including MAC address.

Download Wyzecam para.bin and flash it:
flash_eraseall /dev/mtd9
dd if=/system/sdcard/para.bin of=/dev/mtd9

Then install the current Wyzecam RTSP firmware.

**Comment by hubmon** [comment]
Me too. Need the 'for dummies' version.

**Comment by wesbos** [comment]
I think it is related to this: https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/hacks/flashinguboot.md

**Comment by hubmon** [comment]
Was in that comment. Link 
https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/firmware_original/wyzecam_v2/4.9.1.60/para.bin

**Comment by wesbos** [comment]
I got it to work! 

So assuming you already have dafang loaded onto your cam:

Download the wyze para.bin linked above and put it on your SD card.

SSH into the dafang cam: `ssh root@camera-ip`

Enter password (default is `ismart12`) 

Backup the original, just in case

`dd if=/dev/mtd9 of=/system/sdcard/original-para.bin`

Clear the original: `flash_eraseall /dev/mtd9`

Load the wyze para.bin: `dd if=/system/sdcard/para.bin of=/dev/mtd9`

Then remove that SD and load the regular Wyze firmware via their website instructions. I used the regular Wyze firmware as I'm not using RTSP

Once it's loaded, set it up like a regular wyze cam

**Comment by wesbos** [comment]
What isn't working right now is the Panning - there are not control for that - I think beause I used the `para.bin` from the regular wyze cam. Does anyone have the para.bin from the pan cam?

**Comment by none815** [comment]
> Can't find #none815 comment posted yesterday, Dec 28. Deleted?

Comment was actually deleted on purpose, i noticed the Wyze app still detects the camera as Wyze Cam V2 activated on 06/2019, so it's effectively just hardware id spoofing of an existing device.
If they decide to block the mac address, the original device will be rendered unusable as well.

**Comment by hubmon** [comment]
As I understand this, any camera using this **para.bin** will have the same mac address. 
Will there be a conflict for multiple cameras using same mac?
Is there a solution?

**Comment by hubmon** [comment]
Inspected para.bin. mac there is different than what shows up in the router.
