### ISSUE TITLE
Video stream very slow. Best presets?

### ISSUE THREAD

**Issue by egidoval** [EliasKotlyar/Xiaomi-Dafang-Hacks#456]
First thanks for your software, it´s great.
I got my dafang working. Problem is i don´t know what are the bests bitrate/video format and quality combinations. My video is very slow on the browser. If i open rtsp with vlc it´s a bit faster but it´s still slow. My wifi is very fast and i don´t have any problem with other adapters.
Thanks again for this great utility.

**Comment by saipsa** [comment]
960 resolution, 500 bitrate. 

If I increase anymore, the moving objects start to pixelate. 

There is no way to change fps it seems.

According to one issue, Memory partition needs to be changed for better performance.

**Comment by egidoval** [comment]
thanks for your fast reply @saipsa , what do you mean by Memory partition? how can i access that option? thank you

**Comment by saipsa** [comment]
It needs to be changed in the firmware. You will have to change the code.

**Comment by T3rm1** [comment]
500kb/s? Are you sure? The default value is 5000kb/s.

**Comment by chaseadam** [comment]
The default 5000 is problematic for me. I was able to set to 1000kbps at 720/21fps and with consistent quality.
