### ISSUE TITLE
Settings changed with UI are not saving

### ISSUE THREAD

**Issue by sth313** [EliasKotlyar/Xiaomi-Dafang-Hacks#457]
When i change any setting with the UI these changes are not saving and jumps back to it's original state. What am i doing wrong?

**Comment by nik0** [comment]
Whatever the settings ?

**Comment by sth313** [comment]
Every setting, like the TZ, NTP Server, Bitrate, video size. I changed it, press the SET button and after a few seconds it's changing back to original value

**Comment by nik0** [comment]
That’s strange. 
What does the mount logs say ? Do you have read only partition ?

**Comment by sth313** [comment]
I guess you mean this log: 

rootfs on / type rootfs (rw)
/dev/root on / type squashfs (ro,relatime)
tmpfs on /dev type tmpfs (rw,relatime)
proc on /proc type proc (rw,relatime)
devpts on /dev/pts type devpts (rw,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /tmp type tmpfs (rw,relatime)
tmpfs on /run type tmpfs (rw,nosuid,nodev,relatime,mode=755)
sysfs on /sys type sysfs (rw,relatime)
media on /media type tmpfs (rw,relatime)
/dev/mtdblock3 on /driver type squashfs (ro,relatime)
/dev/mtdblock4 on /system type jffs2 (rw,relatime)
/dev/mtdblock7 on /backupa type jffs2 (rw,relatime)
/dev/mtdblock8 on /configs type jffs2 (rw,relatime)
/dev/mtdblock9 on /params type jffs2 (rw,relatime)
/dev/mmcblk0p1 on /system/sdcard type vfat (ro,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro)
/dev/mmcblk0p1 on /root type vfat (ro,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro)
/dev/mmcblk0p1 on /etc type vfat (ro,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro)

**Comment by nik0** [comment]
That’s it ! 
 This it not normal:
/dev/mmcblk0p1 on /system/sdcard type vfat (ro,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro)

Unplug your sdcard and check it with Windows check disk or something similar

**Comment by nik0** [comment]
Super !!

**Comment by reikred** [comment]
I have a similar problem that settings will not save, specifically NTP server is blank and I cannot  set it. It used to be time.google.com.

My mounts are normal, I think:

# mount
rootfs on / type rootfs (rw)
/dev/root on / type squashfs (ro,relatime)
tmpfs on /dev type tmpfs (rw,relatime)
proc on /proc type proc (rw,relatime)
devpts on /dev/pts type devpts (rw,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /tmp type tmpfs (rw,relatime)
tmpfs on /run type tmpfs (rw,nosuid,nodev,relatime,mode=755)
sysfs on /sys type sysfs (rw,relatime)
media on /media type tmpfs (rw,relatime)
/dev/mtdblock3 on /driver type squashfs (ro,relatime)
/dev/mtdblock4 on /system type jffs2 (rw,relatime)
/dev/mtdblock7 on /backupa type jffs2 (rw,relatime)
/dev/mtdblock8 on /configs type jffs2 (rw,relatime)
/dev/mtdblock9 on /params type jffs2 (rw,relatime)
/dev/mmcblk0p1 on /system/sdcard type vfat (rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro)
