### ISSUE TITLE
tinyCam rtsp audio

### ISSUE THREAD

**Issue by stantheboss** [EliasKotlyar/Xiaomi-Dafang-Hacks#461]
Cannot find anything about getting audio steam from the inbuild mic to passthrough within rtsp video stream, is it possible? Followed [manual ](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/integration/tinycam/tinycam.md)but still no sound.

**Comment by jmtatsch** [comment]
Do you hear sound when you watch with vlc?

**Comment by stantheboss** [comment]
Yep, I do hear sound through vlc, tinyCam seems not to detect camera as sound enabled though...

**Comment by saipsa** [comment]
tincyCam has audio muted by default.

**Comment by stantheboss** [comment]
OK, where do I unmute? It tells me that the camera does not support audio.

**Comment by stantheboss** [comment]
Anyone can confirm working audio stream in tynycam?

**Comment by Dopeyr** [comment]
@stantheboss Yes, it works for me. My command line arguments look like this:

`/system/sdcard/bin/v4l2rtspserver-master -W1600 -H900 -E PCMU:8000 -r 3 -U root:mypassword -P 8554`

When I click the 'unmute' button in tinycam it then shows a level meter to the right of the icon. I'm running 10.1 Beta 6 of tinycam.

**Comment by Dopeyr** [comment]
Hi @stantheboss,

Just to avoid any confusion, this is the icon I see when the audio is muted.

![screenshot_20180618-223319](https://user-images.githubusercontent.com/5502915/41588977-2e21a408-73ab-11e8-9aab-2fbd52d7565e.png)

My only thought is perhaps if you have multiple cams, you have to be viewing only one camera in tinycam before the sound icon appears.

**Comment by stantheboss** [comment]
Hi @Dopeyr 
I do have multiple cams, but non of the Dafang cams have the sound button. Has it been introduced with the specific firmware version? Maybe I need to update fw first or my rtspserver service needs some additional audio specific flags to be set...

**Comment by Dopeyr** [comment]
Yeah, if you can get it in VLC it seems v4l2rtspserver-master is working OK. I think I remember someone saying it only worked in tinycam with PCM, but I could be wrong. I haven't tried anything else e.g. MP3.

Might be worth running v4l2rtspserver-master manually and trying some different audio options until you find a combination that works? It would be good to see the output too which might have some clues as to why it's not working.

**Comment by maxhammond** [comment]
Hi @stantheboss , how many cameras do you have working with TinyCam? I have 3 and The TinyCam app can’t really cope. It starts them ok but they all start to decay FPS wise and soon drop. It’s not an issue with my network as running 3 VLC sessions on my PC is fine. Might be my phone , it a Samsung S6. What are you running TinyCam on and how many cameras have you run at the same time successfully? thanks Max

**Comment by stantheboss** [comment]
Hi @maxhammond, I've got 2 cameras hooked up in tinycam, both dafang, and both cope to stream with 25fps simultaneously in LAN and in WAN through openvpn, my phone is lg v30.

**Comment by dengrgry** [comment]
I'm facing the same issue. tinyCam says the camera doesn't support audio. Any solution already? I'm also getting sound in VLC.

**Comment by Antimus** [comment]
@dengrgry I'm using tinycam free, also tried pro, only see Xiaomi as an option for the vendor which has dafang under it.
I have the same issue as you did, no audio through the RTSP stream. force stop doesn't change anything, still only Xiaomi
