### ISSUE TITLE
Axis on OSD - Question

### ISSUE THREAD

**Issue by staudtm** [EliasKotlyar/Xiaomi-Dafang-Hacks#463]
Now that the "Axis on OSD" issue is solved (fixes #454), I have a simple question:
How will it look like?

I can see no "axis" on my screen.

And: will the axis be usefull to define PTZ points?

**Comment by neroxps** [comment]
Sorry, I can't speak English. The following text comes from Google Translate.

> I can see no "axis" on my screen.

Please confirm that the DISPLAY_AXIS=true parameter is in the osd.conf file.

> And: will the axis be usefull to define PTZ points?

Yes, you can set PTZ with reference to the axis.

like this`http://root:ismart12@192.168.1.108/cgi-bin/api.cgi?action=motor_PTZ&x_axis=1070&y_axis=400`

**Comment by staudtm** [comment]
Der Parameter ist auf "true" gesetzt. Wie stellt sich denn die Achse auf dem Bild dar?

**Comment by staudtm** [comment]
Kann es sein, dass die Achse nicht angezeigt wird, weil ich das Bild "geflippt" habe?

**Comment by neroxps** [comment]
Sorry, the last PR fix was not completed. There is a bug left.

You can try to modify the file here or wait for the merge. [(PR #474)](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/pull/474)
