### ISSUE TITLE
wyze cam pan original boot loader?

### ISSUE THREAD

**Issue by dony71** [EliasKotlyar/Xiaomi-Dafang-Hacks#464]
I check repository under  ../firmware_original/wyzecam_pan/4.10.0.222,
can only find appfs.bin, driver.bin, kernel.bin, rootfs.bin
Can somebody share uboot.bin ?

**Comment by tssva** [comment]
The firmware bin file from Wyzecam doesn't include the boot loader and the custom firmware bin doesn't change the boot loader. Unless you have changed it yourself your Wyzecam Pan still has the original boot loader on it. You can use the instructions at https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/hacks/firmware-dump.md to dump it to a file.

**Comment by dony71** [comment]
My understanding from https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/hacks/install_cfw.md, need to install boot loader, which means will overwrite original uboot. This is needed since original uboot won't allow boot from micro sdcard. Am I understanding wrongly?

**Comment by tssva** [comment]
It does not modify the boot loader. The boot loader still boots the camera by calling th elinux kernel stored on the camera. This in turn launches the boot process stored on the root filesystem on the camera. The custom firmware installs a modified copy of this root file system with the only change being to the startup script. The startup script is modified to attempt to mount the sd card. If it can and there is a file named run.sh on the sd card than the startup script turns control over to this script. If it can't mount the sd card or the sd card doesn't contain a file named run.sh it continues the boot process as if nothing has been changed.
