### ISSUE TITLE
Update not working

### ISSUE THREAD

**Issue by saipsa** [EliasKotlyar/Xiaomi-Dafang-Hacks#466]
On running `autoupdate.sh` it confirms files that need to be updated, reboots.

Expected result: Files should be updated and missing files should be created.

Actual result: Files are neither updated nor created.

Updating from web GUI doesn't help either.

**Comment by nik0** [comment]
There was a bug in previous audotupdate script (it gets the files in /system/sdcard/system/sdcard)
Make sure you got the last version (you can edit it there is only online change)
