### ISSUE TITLE
ftp client

### ISSUE THREAD

**Issue by dmolner** [EliasKotlyar/Xiaomi-Dafang-Hacks#470]
Hello,

Can put by ftp files from camera to a server?
Or need download files from camera and later upload to server?

**Comment by wube1** [comment]
Hi @jmtatsch, in which file you think this command would be the best to nest so it could check for new files and transfer them to qnap for example? Is there a possibility to actually record rtsp feed directly on qnap but without using qvr pro nor surveillance station?

**Comment by jmtatsch** [comment]
@wube1 I would write a little script to do the ftp sync and run that via cron job. No idea about qnaps.

**Comment by jmtatsch** [comment]
Question answered.
