### ISSUE TITLE
ER: Support for multiple RTSP streams

### ISSUE THREAD

**Issue by chriscrowe** [EliasKotlyar/Xiaomi-Dafang-Hacks#475]
This one's an enhancement request.

I've got my Wyze cam hooked into my Synology RAID-- it would be great if the cam was broadcasting multiple streams (eg, low, medium, and high quality) so that I setup recording rules like:

- 24/7 continuous recording on low quality stream
- Live view on medium quality
- Motion detection recording on high quality

**Comment by aartrost** [comment]
This would also be very useful for my setup where I offload motion detection to my NAS. If I could detect motion on a low res stream and only use the high res stream to store videos I could save a ton of CPU cycles.

**Comment by manianac** [comment]
I've offloaded motion detection to my server using motioneyeos.  It runs motiond reading the rtsp stream, works great.  But the RTSP server alone on the camera is >75% cpu usage.  Not sure if we could run multiple.
