### ISSUE TITLE
/usr/bin/basename doesn't work

### ISSUE THREAD

**Issue by Daviey** [EliasKotlyar/Xiaomi-Dafang-Hacks#477]
basename normaly works because there is an alias in ~root/.busybox_aliases which means that the busybox in the PATH is used.

However, /usr/bin/basename is used (which is a symlink to /bin/busybox), it uses the older busybox which doesn't have the basename applet builtin.

```
[root@DAFANG:~]# /usr/bin/basename 
basename: applet not found
[root@DAFANG:~]# 
```

I've tried to think of some ways this can be solved, without touching the squashfs.. but we can't use symlinks, as this is a vfat filesystem.

The best i've been able to do so far is a bind mount:

```
mount -o bind /system/sdcard/bin/busybox /bin/busybox
```

**Comment by nik0** [comment]
did you try `/system/sdcard/bin/busybox basename` ?

**Comment by Daviey** [comment]
yeah, that works as expected.. but the issue is I want to use scripts which haven't been customised for this platform.
