### ISSUE TITLE
Start MJPEG RTSP no Get Image

### ISSUE THREAD

**Issue by khseal** [EliasKotlyar/Xiaomi-Dafang-Hacks#48]
Problem get image after start mjpeg
![bad](https://user-images.githubusercontent.com/11374629/35095567-f25e5196-fc59-11e7-8b35-e2586a3b4647.jpg)

**Comment by pplucky** [comment]
I don't think it is currently possible to have RTSP server running and doing image capture.

**Comment by khseal** [comment]
This is bad =( I understand that  are using one and the same program in both cases.

**Comment by EliasKotlyar** [comment]
Yes, but the camera device is blocked after you start the stream. The device can be used only by one application at a time.

**Comment by kszere** [comment]
I propose this solution. Works when v4l2rtspserver-master running and when not running.
[https://kszere.gitbooks.io/xiaomi-dafang-api/content/en/action/getsnaphot.html](https://kszere.gitbooks.io/xiaomi-dafang-api/content/en/action/getsnaphot.html)

## Use v4l2rtspserver-master (nightvision enabled)
![v4l2rtspserver-master](https://user-images.githubusercontent.com/7155051/35710931-721c3b1c-07ba-11e8-8045-1e50362b813d.jpg)

## Use avconv (nightvision enabled)
![avconv](https://user-images.githubusercontent.com/7155051/35710934-75a9199e-07ba-11e8-9034-0010adaf597f.jpg)

**Comment by shinebar1001** [comment]
Can you please submit your Version of avconv to the public? :) In my opinion the best way would be to merge your changes with the original repo, so we don't have too many steps to get a fully working dafang - the Things you did are fantastic, so why don't integrate them in the main hack?

**Comment by kszere** [comment]
I not compiled avconv, this make by @Jhyrachy
[Please see here (download)](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/49#issuecomment-359628479)

**Comment by shinebar1001** [comment]
Ah, sorry. I must have been blind. So I'll update my plans for the Weekend :)
Thanks! :)

**Comment by shinebar1001** [comment]
Okay. I think we first have to make the http-segmentation configurable. 
I managed to get a proper picture from the mjpeg. But when trying to fetch a single frame from the h264-stream I get only garbage. When I disable segementation, everything is fine. 
For my personal use-case I'm fine with mjpeg and the segmented h264-stream breaks even my vlc - but I want to have a nice solution enabling people to use the feature without accessing the console (hmkay, let's say "working" - i definitely can't design anything in html and my code is sometimes working, but not really nice :)

At this moment I think  about:
- making the "-S" for v4l2rtspserver-master configurable (uuh, another line on the status-page)
- checking if v4l2rtspserver-master is running in mjpeg-mode -> output the live picture
- checking if v4l2rtspserver-master is running in h264-mode with -S > output a static picture (sorry, you have to use v4l2rtspserver-master without segmentation)
- checking if v4l2rtspserver-master is running in h264-mode without -S -> output the live picture
Any better suggestions?

**Comment by shinebar1001** [comment]
Okay, included all these in my newest commit.

**Comment by EliasKotlyar** [comment]
Hey everyone, 

I released a new Version, which is capable of creating a JPEG-Snap when running in MJPG-Mode. It doesnt stop the stream, its just using IPC to transfer the binary image.

I assume that creating a JPEG-Snap when running on H264 is also possible, but it needs some tweaking. 

About your commit @shinebar1001:
Many thanks, but i need to refactor the code before merging it. There are some issues with the changed structure.

**Comment by EliasKotlyar** [comment]
Okey, i managed to create "both" streams at the same time. Now you can stream with H264 and get a Image. Still need some solution for the nightvision mode.

**Comment by khseal** [comment]
Excellent, everything works. Need to automatically switch to black and white mode ...

**Comment by shinebar1001** [comment]
Great news here!

@EliasKotlyar 
> About your commit @shinebar1001:
Many thanks, but i need to refactor the code before merging it. There are some issues with the changed structure.

No worry! If it helps you I can try to do that as well. Otherwise I would start to make the OSD configurable.

**Comment by kszere** [comment]
@EliasKotlyar, new binary v4l2rtspserver-master not works with `-W` and `-H` param
![capture](https://user-images.githubusercontent.com/7155051/35777573-6b07edce-09b0-11e8-86aa-ad0e94339a44.PNG)

**Comment by EliasKotlyar** [comment]
Hello @kszere,

Thanks for poiting out. There was a bug when chaging the resolution. Now it should work fine, i uploaded a new Version which resolve this issue. 

Greatings
Elias

**Comment by pplucky** [comment]
@EliasKotlyar Thanks for the quick resolution. Quick related question: will running it with the above settings be enough to have 1920x1080?

**Comment by EliasKotlyar** [comment]
@pplucky : Yeah, it should work. I tested it few minutes ago. Its required that you have a custom bootloader for running in FULLHD.

**Comment by pplucky** [comment]
@EliasKotlyar Is this custom bootloader available to download or what needs to be done to have it? Thanks in advance for all your help.

**Comment by shinebar1001** [comment]
@EliasKotlyar 

> Okey, i managed to create "both" streams at the same time. Now you can stream with H264 and get a Image. Still need some solution for the nightvision mode.

Great release! I just did some testing, the quality of the h264-Stream is now 100% like the mjpeg-stream,  with 10% of the bandwith. So in most environments there is no need for the MJPEG Stream anymore. Thank you very much!

**Comment by kszere** [comment]
@EliasKotlyar can you commit new version suport `-W` and `-H` param?

**Comment by EliasKotlyar** [comment]
Hello @kszere ,

Sorry, i forgot to commit it to the right branch. Now it should be fine.

Greating
Elias

**Comment by khseal** [comment]
Sometimes the image contains artifacts below.
![bug](https://user-images.githubusercontent.com/11374629/35907695-bbfbc0ce-0bff-11e8-8be2-5a9125b7a7b5.jpg)

**Comment by jmtatsch** [comment]
Closing this as it should be solved in principle. Open a new issue if the artefacts persist.
