### ISSUE TITLE
wyzecam pan SSH and FTP access denied

### ISSUE THREAD

**Issue by dony71** [EliasKotlyar/Xiaomi-Dafang-Hacks#480]
According to this FAQ (https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/hacks/faq.md) default login/password should be root/ismart12
But I get "Access Denied".
HTTP login is working with root/ismart12 but problem with SSH and FTP
Anything I'm missing?

**Comment by jmtatsch** [comment]
Should be fixed now thanks to @tssva

**Comment by naitsimp** [comment]
I am also trying to access the camera with FTP.
I am using FileZilla.
Server: [IP-Address of camera]
username: root
password: ismart12
Port: is empty, ??

But I am always getting an error that the connection to the server has failed.
Do I have to activate the FTP Function on the camera before I can use it?

**Comment by jmtatsch** [comment]
Try port 21

**Comment by naitsimp** [comment]
Thank you very much. I am now able to access it.
