### ISSUE TITLE
possible to change http port?

### ISSUE THREAD

**Issue by dony71** [EliasKotlyar/Xiaomi-Dafang-Hacks#481]
is it possible to change http port ?

**Comment by jmtatsch** [comment]
sure, just alter your lighthttpd.conf accordingly. Don't forget the automatic https redirection.

**Comment by dony71** [comment]
i change server.port = 80 to server.port = 9097 in lighthttpd.conf, but no response when trying http://my-wyzecam-ip:9097
what is automatic https redirection?

**Comment by nik0** [comment]
Also change this line: `$SERVER["socket"] == ":443" ` 
It means that when you connect to  http://my-wyzecam-ip:9097 you will be redirected to  http://my-wyzecam-ip:443

**Comment by tripchoc** [comment]
does this mean when changes are made on server.port = 80 to server.port = 9097 in lighthttpd.conf, we need to change this line to $SERVER["socket"] == ":9097" ?
