### ISSUE TITLE
After update to 2018-06-17T09:24:27Z

### ISSUE THREAD

**Issue by DyArt** [EliasKotlyar/Xiaomi-Dafang-Hacks#487]
I have updates from 2018-06-13 to 2018-06-17 and now cgi-bin doesn't work anymore in the browser Chrome:

`jquery-3.3.1.min.js:2 GET https://192.168.192.46/cgi-bin/state.cgi?cmd=yellow_led 500 (Internal Server Error)
jquery-3.3.1.min.js:2 GET https://192.168.192.46/cgi-bin/state.cgi?cmd=blue_led 500 (Internal Server Error)
jquery-3.3.1.min.js:2 GET https://192.168.192.46/cgi-bin/state.cgi?cmd=ir_led 500 (Internal Server Error)
jquery-3.3.1.min.js:2 GET https://192.168.192.46/cgi-bin/state.cgi?cmd=ir_cut 500 (Internal Server Error)
jquery-3.3.1.min.js:2 GET https://192.168.192.46/cgi-bin/state.cgi?cmd=rtsp_h264 500 (Internal Server Error)
jquery-3.3.1.min.js:2 GET https://192.168.192.46/cgi-bin/state.cgi?cmd=rtsp_mjpeg 500 (Internal Server Error)
jquery-3.3.1.min.js:2 GET https://192.168.192.46/cgi-bin/state.cgi?cmd=auto_night_detection 500 (Internal Server Error)
jquery-3.3.1.min.js:2 GET https://192.168.192.46/cgi-bin/state.cgi?cmd=mqtt_status 500 (Internal Server Error)
jquery-3.3.1.min.js:2 GET https://192.168.192.46/cgi-bin/state.cgi?cmd=motion_detection 500 (Internal Server Error)
jquery-3.3.1.min.js:2 GET https://192.168.192.46/cgi-bin/state.cgi?cmd=sound_on_startup 500 (Internal Server Error)
jquery-3.3.1.min.js:2 GET https://192.168.192.46/cgi-bin/state.cgi?cmd=mqtt_control 500 (Internal Server Error)`

So the menu services and the log in the browser doen't work as also the button to control the cam

**Comment by jmtatsch** [comment]
But the index.html works? Did you restart? Can you try a fresh repo clone?

**Comment by DyArt** [comment]
Yes index.html works all the calls to cgi-bin aren't working. Already booted from an power off. Not tried yet to make an new refresh from the repo

**Comment by nik0** [comment]
Same problem for me.
Investigating, no luck for now

**Comment by nik0** [comment]
Still don't know why but PR: https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/pull/478 introduce the regression ...

**Comment by jmtatsch** [comment]
Fixed via #492
