### ISSUE TITLE
dafang udhcpc: deleting routers

### ISSUE THREAD

**Issue by ruprechtcua** [EliasKotlyar/Xiaomi-Dafang-Hacks#488]
Hi guys,

first time doing this. I am not entirely sure what is the issue here but I can't access the cgi-bin/status page.

here is my startup log
==================================================
Starting the Dafang Hacks Custom Application Layer
==================================================
Loaded common functions
Created etc directory on sdcard
Bind mounted /system/sdcard/bin/busybox to /bin/busybox
Bind mounted /system/sdcard/root to /root
Bind mounted /system/sdcard/etc to /etc
Created cron directories and standard interval jobs
wpa_supplicant: Successfully initialized wpa_supplicant
rfkill: Cannot open RFKILL control device
nl80211: Could not re-add multicast membership for vendor events: -2 (No such file or directory)
udhcpc: deleting routers
adding dns 192.168.1.1
adding dns 0.0.0.0
Initialized gpios
dropbear: 
bftpd: 
Created new certificate for webserver
lighttpd: 
Startup finished!

it seems like the issue is udhcpc? 

this is my wpa_supplicant.conf
# For more configuration option please see:
# https://w1.fi/cgit/hostap/plain/wpa_supplicant/wpa_supplicant.conf

ctrl_interface=/var/run/wpa_supplicant
ctrl_interface_group=0
ap_scan=1

network={
        ssid="MySSID"
        # Uncomment to connect to Hidden SSIDs
        scan_ssid=1 
        key_mgmt=WPA-PSK
        pairwise=CCMP TKIP
        group=TKIP CCMP
        psk="xxxxxx"
        priority=1
}

I believe i have used this commit: caf1cb37891255ad69ff7b6988555fee5b9a45bd

**Comment by jmtatsch** [comment]
That looks mostly normal. Are you sure your device doesn’t get an ip? Look at your router dhcp server... try to Ping it, ssh to it etc. What model is that exactly?

**Comment by ruprechtcua** [comment]
dhcp

DAFANG | F8:FB:AD:FF:FF:FF | *.*.*.116

tried to go to ip/cgi-bin/status asking for user/password? seems like there is an auth header?

last night i have both DAFANG and the mac address on the device showing up as 2 different IPs. the mac address - IP doesn't ping or anything.

when i open da fang now i can see a yellow light when there is movement

**Comment by ruprechtcua** [comment]
oh it means it is running then. where do I get the default user/pass? 

thanks

**Comment by ruprechtcua** [comment]
found it! dumb dumb me.
https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/firmware_mod/config/lighttpd.user

apologies for the bother. good work!
