### ISSUE TITLE
Suggestion for updating

### ISSUE THREAD

**Issue by timbuchwaldt** [EliasKotlyar/Xiaomi-Dafang-Hacks#489]
I think polling Github for all files is not a preferable way of updating firmware - I would suggest building a .tar releasefile that contains all relevant files as a normal GitHub release that then can be downloaded by the camera. A second (maybe .zip) could be created that only contains the files to put on the sdcard (like the update, but including configurations) so one doesn't have to download all the original FW blobs.

**Comment by mixpc** [comment]
I select Update from the web interface menu but always receive... No files to update. See [log](https://pastebin.com/Bv9SB04x) when in fact files in github have been updated.

So if you describe the method you use, that might be of help to some of us of go into the FAQ, for the matter.

Thank you and regards,

**Comment by nik0** [comment]
what happen if you just run autoupdate.sh script (without -d option)
do you have the latest version ?
