### ISSUE TITLE
Streaming to YouTube

### ISSUE THREAD

**Issue by Jhyrachy** [EliasKotlyar/Xiaomi-Dafang-Hacks#49]
How hard is to make the webcam stream directly to youtube?

You need an RTMP data stream, if we could encode it directly on the webcam, it should be feasible

**Comment by Jhyrachy** [comment]
Adding detail, I found that it should be really easy using cvlc (http://xmodulo.com/live-stream-video-webcam-linux.html )

Anyone know if the camera cpu is strong enough?

**Comment by EliasKotlyar** [comment]
@Jhyrachy :
I suppose that you cannot run the avconf with the /dev/video0 device. This device has a "crippled" driver, which has some unusual functions. I had to use the "libimp", a propriatary library to make the rtsp work.

**Comment by kszere** [comment]
`/dev/video1` and `/dev/video1` is alias to `/dev/video0`?

**Comment by kszere** [comment]
Thanks.
Works with snaphot when v4l2rtspserver-master running.
I will add new function to my [Xiaomi DaFang API Repo](https://github.com/kszere/Xiaomi-Dafang-API).

**Comment by Jhyrachy** [comment]
Wait, you managed to stream to youtube?

**Comment by kszere** [comment]
@Jhyrachy no, I get only one frame as snaphot. Please see [here](https://kszere.gitbooks.io/xiaomi-dafang-api/content/en/action/getsnaphot.html). It is not put on GitHub. I will add when make documentation.

I not know avconv, ale please try:
### YouTube
`./avconv -rtsp_transport tcp -y -i rtsp://0.0.0.0:8554/unicast -f flv "rtmp://a.rtmp.youtube.com/live2/[KEY]/[NAME_STREAM]"`

### Facebook  
`./avconv -rtsp_transport tcp -y -i rtsp://0.0.0.0:8554/unicast -f flv "rtmp://live-api.facebook.com:80/rtmp/[KEY]"`

### vKontakte
`./avconv -rtsp_transport tcp -y -i rtsp://0.0.0.0:8554/unicast -f flv "rtmp://stream.vkuserlive.com:443/live?srv=[ID]&s=[BASE64_DATA]/[KEY]"`

In vKontakte, receive more than one frame and set as thumb video stream, but when Camera return in console `[rtsp @ 0x1d978a0] CSeq 5 expected, 0 received.`, stream drop.


## Another problem
`Failed to resolve hostname stream.vkuserlive.com: Name or service not known`
I fix change domain to ip.

**Comment by kszere** [comment]
# Works!
I've successfully made a YouTube broadcast!
Watch on YouTube: [Streaming to YouTube from Xiaomi Dafang IP Camera](https://youtu.be/CeiHsPI4AtY)
Watch on YouTube: [Streaming to YouTube from Xiaomi Dafang IP Camera view from the back office](https://youtu.be/PzWruPKXZIM)

![vlcsnap-error061](https://user-images.githubusercontent.com/7155051/35708818-24aa4072-07b0-11e8-9c6d-8ee6fe267de5.png)

# I think that use avconv is good idea for all operations of video and audio for recordings, stream local and outsite ex. YouTube. I propose making good compile version for Dafang.
example: can solved the Start MJPEG RTSP no Get Image #48 issue

## How to (my best settings)
`/system/sdcard/bin/v4l2rtspserver-master -W 640 - H 360 -F 30 -Q 30`

`./avconv -rtsp_transport tcp -y -i rtsp://0.0.0.0:8554/unicast -c:v copy -profile:v high -coder 1 -pix_fmt yuv420p -g 30 -bf 2 -c:a aac -b:a128k -profile:a aac_low -strict experimental -aspect 16:9 -f flv "rtmp://173.194.150.107/live2/[KEY]/[NAME_STREAM]"`

## Helper materials
```bash
#/bin/sh
ffmpeg -i input -c:v libx264 -preset slow -profile:v high -crf 18 -coder 1 -pix_fmt yuv420p -movflags +faststart -g 30 -bf 2 -c:a aac -b:a 384k -profile:a aac_low output
```


### Container: MP4 (current compile version I can't run with mp4, so I use flv)

| Parameter | YouTube recommends setting |
|---------------------|-------------------------------------------------|
| -movflags faststart | moov atom at the front of the file (Fast Start) |

### Video codec: H.264

| Parameter | YouTube recommends setting |
|---------------------|----------------------------|
| -profile:v high | High Profile |
| -bf 2 | 2 consecutive B frames |
| -g 30 | Closed GOP. GOP of **half the frame rate**. |
| -coder 1 | CABAC |
| -crf 18 | Variable bitrate. |
| -pix_fmt yuv420p | Chroma subsampling: 4:2:0 |

### Audio codec: AAC-LC

| Parameter                   | YouTube recommends setting                              |
|-----------------------------|---------------------------------------------------------|
| -c:a aac -profile:a aac_low | AAC-LC                                                  |
| -b:a 384k                   | Recommended audio bitrates for uploads: Stereo 384 kbps |

# /dev/video0 /dev/video1 /dev/video2
I think that not support with current binary

`illegal short term buffer state detected`

`Non-monotonous DTS in output stream 0:1; previous: 3434, current: -106303; changing to 3435. This may result in incorrect timestamps in the output file.`

`[rtsp @ 0x1be58a0] CSeq 5 expected, 0 received.`

`[flv @ 0x1adc8a0] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly`

**Comment by Jhyrachy** [comment]
Fantastic!

I'll give a try as soon as I can!

**Comment by kszere** [comment]
@Jhyrachy  I tried with different parameters, but with /dev/video0,1,2 not running.
I think that in the moment you can use only source from RTSP local stream or try recompile with other version or other functions avconv.

**Comment by Jhyrachy** [comment]
With your exact same commands, i got errors :/

No idea why

Avconv: 
![immagine](https://user-images.githubusercontent.com/5394678/35768066-b90cba00-08f6-11e8-80a2-00fca8f129f1.png)

V4l2: 
![immagine](https://user-images.githubusercontent.com/5394678/35768071-c62b0fc0-08f6-11e8-9830-033e63c60ca6.png)

**Comment by kszere** [comment]
It not will works.
You have resolution set to 640x720, so will not working, bacause not supports (conflict).
Please try with 640x360.

**Comment by mixpc** [comment]
Please, kindly advice on error "Expected number for b:a128k but found: -profile:a".

This is the closest I  have been:

```
[root@DAFANG:~]# kill pid #pid is process under which v4l2rtspserver-master automatically runs after boot
[root@DAFANG:~]# export LD_LIBRARY_PATH='/system/sdcard/lib/:/thirdlib:/system/lib'
[root@DAFANG:~]# /system/sdcard/bin/v4l2rtspserver-master -W 640 - H 360 -F 30 -Q 30
```

And then...

```
[root@DAFANG:~]# /system/sdcard/bin/avconv -rtsp_transport tcp -y -i rtsp://0.0.0.0:8554/unicast -c:v copy -profile:v high -coder 1 -pix_fmt yuv420p -g 30 -bf 2 -c:a aa
c -b:a128k -profile:a aac_low -strict experimental -aspect 16:9 -f flv "rtmp://a.rtmp.youtube.com/live2/IDCODE"
avconv version v13_dev0-1541-ge368b0cbf, Copyright (c) 2000-2018 the Libav developers
  built on May 17 2018 20:39:55 with gcc 4.7.2 (Ingenic r2.3.3 2016.12)
[rtsp @ 0x156cce0] Non-increasing DTS in stream 1: packet 14 with DTS 50214, packet 15 with DTS 36108
[rtsp @ 0x156cce0] Non-increasing DTS in stream 1: packet 22 with DTS 68546, packet 23 with DTS 54440
[rtsp @ 0x156cce0] Non-increasing DTS in stream 1: packet 37 with DTS 103881, packet 38 with DTS 89775
[rtsp @ 0x156cce0] Non-increasing DTS in stream 1: packet 45 with DTS 122424, packet 46 with DTS 108318
[rtsp @ 0x156cce0] Non-increasing DTS in stream 1: packet 60 with DTS 158614, packet 61 with DTS 144508
[rtsp @ 0x156cce0] Non-increasing DTS in stream 1: packet 68 with DTS 176662, packet 69 with DTS 162556
[rtsp @ 0x156cce0] Estimating duration from bitrate, this may be inaccurate
Guessed Channel Layout for Input Stream #0.1 : mono
Input #0, rtsp, from 'rtsp://0.0.0.0:8554/unicast':
  Metadata:
    title           : LIVE555 Streaming Media v2017.10.28
    comment         : LIVE555 Streaming Media v2017.10.28
  Duration: N/A, start: 0.080567, bitrate: 64 kb/s
    Stream #0:0: Video: h264 (Constrained Baseline)
      yuv420p, 1280x720
      25 fps, 90k tbn
    Stream #0:1: Audio: mp3
      44100 Hz, 1 channels, s16p, 64 kb/s
Expected number for b:a128k but found: -profile:a

```

Any idea on that error in the last line? I have copied it straight from @kszere code except the last piece about rtmp.


And a modification in the -b parameter results in a different error, rtmp error:

```
[root@DAFANG:~]# /system/sdcard/bin/avconv -rtsp_transport tcp -y -i rtsp://0.0.0.0:8554/unicast -c:v copy -profile:v high -coder 1 -pix_fmt yuv420p -g 30 -bf 2 -c:a aa
c -b:a 128k -profile:a aac_low -strict experimental -aspect 16:9 -f flv "rtmp://a.rtmp.youtube.com/live2/IDCODE"
avconv version v13_dev0-1541-ge368b0cbf, Copyright (c) 2000-2018 the Libav developers
  built on May 17 2018 20:39:55 with gcc 4.7.2 (Ingenic r2.3.3 2016.12)
[rtsp @ 0x1c5b2a0] Non-increasing DTS in stream 1: packet 14 with DTS 49903, packet 15 with DTS 35797
[rtsp @ 0x1c5b2a0] Non-increasing DTS in stream 1: packet 22 with DTS 68237, packet 23 with DTS 54131
[rtsp @ 0x1c5b2a0] Non-increasing DTS in stream 1: packet 37 with DTS 103904, packet 38 with DTS 89798
[rtsp @ 0x1c5b2a0] Non-increasing DTS in stream 1: packet 45 with DTS 122385, packet 46 with DTS 108279
[rtsp @ 0x1c5b2a0] Non-increasing DTS in stream 1: packet 60 with DTS 158041, packet 61 with DTS 143935
[rtsp @ 0x1c5b2a0] Non-increasing DTS in stream 1: packet 68 with DTS 176244, packet 69 with DTS 162138
[rtsp @ 0x1c5b2a0] Estimating duration from bitrate, this may be inaccurate
Guessed Channel Layout for Input Stream #0.1 : mono
Input #0, rtsp, from 'rtsp://0.0.0.0:8554/unicast':
  Metadata:
    title           : LIVE555 Streaming Media v2017.10.28
    comment         : LIVE555 Streaming Media v2017.10.28
  Duration: N/A, start: 0.057256, bitrate: 64 kb/s
    Stream #0:0: Video: h264 (Constrained Baseline)
      yuv420p, 1280x720
      25.67 fps, 90k tbn
    Stream #0:1: Audio: mp3
      44100 Hz, 1 channels, s16p, 64 kb/s
rtmp://a.rtmp.youtube.com/live2/IDCODE: Input/output error
```

My rtspserver.conf is default:

```
#######################################################################
# Edit this file and move it to /system/sdcard/config/rtspserver.conf #
# if you need to add options, otherwise defaults will be used         #
#######################################################################

# Configure RTSP Servers
# Use /system/sdcard/bin/v4l2rtspserver-master -h to see available options

# H264 RTSP server options
# Examples:
# RTSPH264OPTS="-W960 -H540"
# To enable authentication:
# RTSPH264OPTS="-U user:password"
RTSPH264OPTS=""

# MJPEG RTSP server options
# Examples:
# RTSPMJPEGOPTS="-W960 -H540"
# To enable authentication:
# RTSPMJPEGOPTS="-U user:password"
RTSPMJPEGOPTS=""

# Video
BITERATE=5000
#
# AudioFormat
# Can be: OPUS | MP3 | PCM | PCMU
AUDIOFORMAT=MP3
AUDIOOUTBR=44100
HWVOLUME=70
SWVOLUME=-1
FILTER=4
HIGHPASSFILTER=ON
```

I can see resolution is set to 1280x720 in avconv. However, I have set it to 640x360 before:

`[root@DAFANG:~]# /system/sdcard/bin/v4l2rtspserver-master -W 640 - H 360 -F 30 -Q 30`

And avconv outputs mp3 when it should be aac as per parameters...

Thank you in advance,

**Comment by lloydwatkin** [comment]
Would love to get this working on camera. I can use ffmpeg on an ubuntu server to the reencoding and push, but every option I try on the camera either crashes out or seems to get stuck.

**Comment by fotiDim** [comment]
Any success from anyone on this? It would be nice to have that as a feature within the firmware.

**Comment by lloydwatkin** [comment]
> Any success from anyone on this? It would be nice to have that as a feature within the firmware.

From my experiments the camera hardware isn't powerful enough, so you need a second device to do the transcoding and pushing to Youtube :)
