### ISSUE TITLE
curl: not found

### ISSUE THREAD

**Issue by dmolner** [EliasKotlyar/Xiaomi-Dafang-Hacks#490]
Hello,
My Dafang send these messatge.
I have two camera but new newest send these message. 
Can I install?

**Comment by Daviey** [comment]
Where are you seeing this error?

Can you give the output of:
```
$ which curl

$ ls -alh /system/sdcard/bin/curl*
```

Thanks

**Comment by dmolner** [comment]
`[root@DAFANG:~]# which curl
-sh: which: not found
[root@DAFANG:~]# ls -alh /system/sdcard/bin/curl*
-rwxr-xr-x    1 root     root         102 Apr 28 08:31 /system/sdcard/bin/curl
-rwxr-xr-x    1 root     root      613.3K Apr 28 08:31 /system/sdcard/bin/curl.bin`

**Comment by jmtatsch** [comment]
@dmolner You seem to run an outdated version.
Please checkout the latest version from the repo manually as there have been issues with web update.

**Comment by jmtatsch** [comment]
Is it working now? If not please reopen.
