### ISSUE TITLE
Not able to change setting and to open "services" 

### ISSUE THREAD

**Issue by TheCrey** [EliasKotlyar/Xiaomi-Dafang-Hacks#491]
Hello, 

Dafang

i do have an issue where i am not sure what exactly is the issue. 
I think a kind of full reset would solve it, bu I am not quite sure how to achieve this. 

I did have had all running and it was very fine, then I decided to run the cam with the originAl firmware, to see how it would behave with the ap etc. 
So, before all this happened, I was able to get into services to update the hack etc. 
So i removed just the sd and added it into the app.
Now I wanted to go back to the hacked version, but it was not working, so I repeated the install stell and this wen well. 

Now, I have access again, I also can see the view and a picture on the main page, but everything else it not working fine. 
As Example, If I want to change the name Dafang, I can save, but nothing happens, the name stays the same, also the movement does not work. 
The Stream does work to, even the settings say its turned off.
The Update area shows "update in progress" but nothing happens. 

The Logs are completely empty. Any of them. 

Network Information does not load also. 
SSH is working fine, but does not help me right now. 

While the Cam was connected to the APP, it installed an Update, to 5.5.1.327

Anyone can help?
Do you need any more information? 

Cheers

**Comment by Damme** [comment]
I have same problem

**Comment by hcgonzalezpr** [comment]
Same here. Status.CGI returns error 500.

**Comment by nik0** [comment]
I guess PR https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/pull/478 introduce the problem
Don't know why ...

**Comment by hcgonzalezpr** [comment]
@nik0 if I enable logs on lighttpd does it give us the error?

One other thing that #478 might be affecting is root password, after last update, the root password returned to the default password.

**Comment by nik0** [comment]
No,  no error
even strace does not give obvious error
I never change my root password

**Comment by hcgonzalezpr** [comment]
@nik0  I manually reverted the changes made in #478 and can confirm that the gui works.

It seems the new busyxbox does not want to play nice.

**Comment by Damme** [comment]
confirm solution works

**Comment by tomusher** [comment]
My solution for this was to update all 

`source func.cgi`

to

`source /system/sdcard/www/cgi-bin/func.cgi`

in any relevant files under `/system/sdcard/www/cgi-bin`.

I've not figured out why the relative path stopped working with the mentioned change though.

**Comment by Damme** [comment]
confirmed, solution works too :)

**Comment by Daviey** [comment]
Sorry chaps, this was my fault.  It seems the busybox we are using doesn't have "." as part of the default $PATH, which means that "source func.cgi" doesn't work.

In all the cgi scripts, adding a leading "./" to func.cgi makes it work for me (so source func.cgi).

I'm adding a pull request for this now.

**Comment by Acrilia** [comment]
Hi I have the same problem but I'm not as experienced as you, what I have to do exactly, replace file, or add text in a file ? If you can help me. Thanks ;).

**Comment by Daviey** [comment]
@Acrilia Latest install resolves this issue.. Just run `/system/sdcard/autoupdate.sh` or reinstall the sdcard from git master.
