### ISSUE TITLE
create_inode: failed to create symlink ... , because Operation not supported

### ISSUE THREAD

**Issue by dony71** [EliasKotlyar/Xiaomi-Dafang-Hacks#495]
I try to generate hack firmware with create_hacked_firmware_wyzecam_pan.sh
but got lots of error
create_inode: failed to create symlink ... , because Operation not supported
I think this happens when executing unsquashfs -d $TMPDIR $FIRMWARE_ROOT/rootfs.bin in script
Any idea?

**Comment by dony71** [comment]
I try to make hack wyze cam pan version 4.10.0.223 
Can successfully pack firmware bin, but wyze cam cannot boot
I suspect this error is the root cause ??

**Comment by jmtatsch** [comment]
Are you maybe on a file system like fat32 that does not support symlinking?
