### ISSUE TITLE
flash_eraseall: applet not found

### ISSUE THREAD

**Issue by patrik72** [EliasKotlyar/Xiaomi-Dafang-Hacks#496]
tried to flash boot.bin with the actual release. no luck.
when i tried to erase mtd0 with this command: flash_eraseall /dev/mtd0, i received the message "applet not found". 
So how can i update the firmware, because i ran out of mem.

**Comment by jmtatsch** [comment]
This is possibly caused by using the new busy box binaries in #478. flash_eraseall might be a custom applet of the old busybox.

**Comment by jmtatsch** [comment]
Fixed in https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/commit/75eee98412c560efbbad041d0abff0c37e2c73e4. Thanks @Daviey

**Comment by timdonovanuk** [comment]
I just tried this and also got `flash_eraseall: applet not found `.  I'm currently using cfw-1.1.bin.
