### ISSUE TITLE
Problems with old and new camera

### ISSUE THREAD

**Issue by dmolner** [EliasKotlyar/Xiaomi-Dafang-Hacks#498]
Hello,
I have two cameras.
The old camera not work fine with the new hack because when I move the camera this move very slow and not stop when arribe to end.
When I make calibrate Vertical the cam move left-right and up-down, when calibrate horizontal the same.
The new camera not work cron and curl.

**Comment by jmtatsch** [comment]
The new motor driver does not separate between vertical and horizontal calibration.
