### ISSUE TITLE
App for Ios

### ISSUE THREAD

**Issue by darkslayert** [EliasKotlyar/Xiaomi-Dafang-Hacks#499]
Hi there People. Is there an app to control the camera for Ios like there is for Android? Thank you

**Comment by nik0** [comment]
I am using LiveCams Pro, but there is no pan control (only for RTSP and/or image viewer)

**Comment by darkslayert** [comment]
Does it has motion detector and send notifications?

**Comment by nik0** [comment]
No, but I don't know why you want this on your app. 
I configured the cam to send me emails

**Comment by nik0** [comment]
No I didn't. What kind of functions ?

**Comment by darkslayert** [comment]
IP Cam Viewer Lite de: NibblesnBits

**Comment by darkslayert** [comment]
Check it out

**Comment by nik0** [comment]
What type of cam did you setup ? I tried RTSP, I get the image.
I don't know how the motion is triggered ... And there is no control (nothing to configure it)

**Comment by darkslayert** [comment]
I didn’t tried it. I was hoping that you could do it and see if it works well

**Comment by nik0** [comment]
:-) My feelings is that LiveCams Pro is "nicer" than IP Cam Viewer. And I didn't find that IP Cam Viewer brings more functions

**Comment by darkslayert** [comment]
How did you configured the app to send you emails on detection?

**Comment by nik0** [comment]
I didn't through the app, but through the settings page of the camera

**Comment by darkslayert** [comment]
Where is the settings page of the camera? On the Mi Home app?

**Comment by nik0** [comment]
https:://IP-OF-YOUR-CAM you will have a image preview and some configuration menu
Did you apply the hack ?

**Comment by darkslayert** [comment]
No i haven’t yet applied the hack because I want to find an app that can do what the Mi Home app does, principally the motion detection with video saves and the ability to send msg when motion is detected. Do you know any app that can do that?

**Comment by nik0** [comment]
Without the hack, I don't think so. You are stuck with the MiHome ...

**Comment by darkslayert** [comment]
And with the hack is there any app that does all that an can be viewed trought lte on an iPhone?

**Comment by jmtatsch** [comment]
Question answered.

**Comment by JManuMartinez** [comment]
You can use "ip cam viewer pro" or "ip cam viewer lite" from Apple Store, you can select as a camera for https or rtsp dafang hacks selecting first, Xiaomi and after that "dafang hacks", from camera models.

**Comment by JManuMartinez** [comment]
> Question answered.

You can use "ip cam viewer pro" or "ip cam viewer lite" from Apple Store, you can select as a camera for https or rtsp dafang hacks selecting first, Xiaomi and after that "dafang hacks", from camera models. It give you some controls over the camera, not all as web interface but probably enough for a minimal control..
