### ISSUE TITLE
Error 404 

### ISSUE THREAD

**Issue by slimen59** [EliasKotlyar/Xiaomi-Dafang-Hacks#502]
Hello,

I have a problem to validate values in configuration Dafang : https://device-ip/cgi-bin/status.cgi
I see the menu,  but the background is blank (white), and the menu is not clean.

When i set a value, i have a "404 - Not Found" page. I can't configure my Dafang Camera.

I did the re-install at many times, but it's always the same.

I don't find the same problem in this page.

Can you help me please ?

cfw-1.3.bin, 
fmw 5.5.1.327

CMIIT ID : 2017DP3894

(Sorry for my English, i'm french).

**Comment by Dopeyr** [comment]
Hi, what do you see when you go to https://device-ip (without cgi-bin part)?

**Comment by slimen59** [comment]
Hi,

It's that !
I see configuration Dafang hacks page now
Thank you very much...
