### ISSUE TITLE
How do you get the values for PTZ?

### ISSUE THREAD

**Issue by staudtm** [EliasKotlyar/Xiaomi-Dafang-Hacks#505]
Hello,

maybe that is is stupid question, but I couldn't find the information yet: How do you get the values for PTZ config when you have moved the camera in a certain position?

**Comment by too-ugly-for-tv** [comment]
There's probably a better way, but moving any axis by zero dumps the current position:

`/system/sdcard/bin/motor -d r -s 0`

```
x: 1300
y: 350
speed: 900
```

**Comment by jmtatsch** [comment]
Question answered.

**Comment by staudtm** [comment]
I thought it would be a good idea to display the X,Y values in OSD.
