### ISSUE TITLE
MQTT - Need to add option for Client_ID for MQTT broker compatibility

### ISSUE THREAD

**Issue by gdgeist** [EliasKotlyar/Xiaomi-Dafang-Hacks#506]
Need to add support for the mosquitto_pub/mosquitto_sub "-i client_id" or  "-I client id prefix" .  I manually edited the scripts to get MQTT sub/pub to work but havent had time to fork and add this to the collected config options etc.

**Comment by shinebar1001** [comment]
You can define the Client ID in mqtt.conf with "MOSQUITTOOPTS":

> # Define additional options for Mosquitto here.
> # For example --cafile /system/sdcard/config/DST_Root_CA_X3.pem --tls-version tlsv1
> # or use a special id to connect to brokers like azure
> MOSQUITTOOPTS=""
