### ISSUE TITLE
busybox fsck.vfat missing

### ISSUE THREAD

**Issue by Damme** [EliasKotlyar/Xiaomi-Dafang-Hacks#507]
I must remove sd card to scan in computer to repair, fsck.vfat missing on sdcard.

**Comment by nik0** [comment]
Is it a busybox feature ?
I have compiled https://github.com/dosfstools/dosfstools to have fsck.vfat
I didn't submit it because I did a check but my card was still have an issue. I don't if the binary is not working or if i mis-use it.
I will do a PR if you want to test it ...

**Comment by jmtatsch** [comment]
Imho it’s not a busybox feature but a dosfstools feature as you said. I tried to compile it to but had trouble to include libudev headers... so I would be grateful also for the compile recipe :)

**Comment by nik0** [comment]
OK I will do it tonight at home ...

**Comment by nik0** [comment]
Created the PR.
I added all the binaries, not sure everyone will be used ...

**Comment by jmtatsch** [comment]
@Damme Can you please try #527 and report back?

**Comment by eridesktop** [comment]
1. update your firmware so there is FSCK tools #527 
2. on your ssh console type _mount_ to see your sdcard mount location. mine _/dev/mmcblkop1_ . Dont use /system/sdcard path
3. type dosfsck [flag] [sdcard path] eg:
`dosfsck -a /dev/mmcblkop1`

**Comment by Damme** [comment]
[root@Dafang1:~]# dosfsck -a /dev/mmcblk0p1 
CP850//TRANSLIT: Invalid argument
CP850: Invalid argument
fsck.fat 4.1+git (2017-01-24)
0x41: Dirty bit is set. Fs was not properly unmounted and some data may be corrupt.
 Automatically removing dirty bit.
malloc:Cannot allocate memory
[root@Dafang1:~]#

**Comment by eridesktop** [comment]
try
`dosfsck -v -a -w /dev/mmcblkop1`

**Comment by Damme** [comment]
[root@Dafang1:~]# dosfsck -v -a -w /dev/mmcblkop1
CP850//TRANSLIT: Invalid argument
CP850: Invalid argument
fsck.fat 4.1+git (2017-01-24)
open: No such file or directory

**Comment by eridesktop** [comment]
then try to manually fix yor sdcard :
`dosfsck /dev/mmcb1kop1`
fix the error on your sdcard one by one, then dont forget to reboot your cam after it finished.
