### ISSUE TITLE
No IP assignment when setting up new Dafang

### ISSUE THREAD

**Issue by bloodybeet** [EliasKotlyar/Xiaomi-Dafang-Hacks#508]
I'm having troubles setting up a brand new Dafang. It looks like some of its setup steps are failing, but it's not very clear where and why. This output is shown for both a correct, incorrect wifi password, and with both the original and minimal versions of wpa_supplicant.conf. Moreover, the device isn't showing up in the DHCP overview of my router. LED stays a solid blue on the Dafang.

`==================================================
Starting the Dafang Hacks Custom Application Layer
==================================================
Loaded common functions
Created etc directory on sdcard
Bind mounted /system/sdcard/bin/busybox to /bin/busybox
Bind mounted /system/sdcard/root to /root
Bind mounted /system/sdcard/etc to /etc
wpa_supplicant: Successfully initialized wpa_supplicant
rfkill: Cannot open RFKILL control device
nl80211: Could not re-add multicast membership for vendor events: -2 (No such file or directory)
udhcpc: 
Initialized gpios
dropbear: 
bftpd: 
lighttpd: 
Startup finished!`

**Comment by bloodybeet** [comment]
Hi - I tried getting next to the router with exactly the same outcome. Could someone post his succesful connection logs here? Maybe that way I can try to pinpoint the issue.

**Comment by nickyhuyskens** [comment]
I'm having the exact same issue after updating the files on the sd card today! 
The hack was working fine before, after upgrading and putting back the wpa_supplicant.conf file, I'm not getting any connection from the device and my logs are exactly the same!
