### ISSUE TITLE
which firmware version to stay on?

### ISSUE THREAD

**Issue by chicco83** [EliasKotlyar/Xiaomi-Dafang-Hacks#51]
hi. i received mi dafang.
the firmware installed is 5.5.1.161
there is available an update to version 5.5.1.197

to use the hack, is it better to stay with the old firmware or to update to the newest one?

**Comment by jmtatsch** [comment]
If you use the most current hack, you will be updated to 5.5.1.200 anyway.

**Comment by chicco83** [comment]
ok so can i instally directly the hack without doing the update trought mi home?
and if i want to use mi home again i have only to remove the sd card, right?

**Comment by chicco83** [comment]
i noticed now that the latest firmware il 243.
will be the hack updated to latest firmware version?

**Comment by EliasKotlyar** [comment]
Hello @chicco83,

There is no need to update to the latest firmware version if you are using the hack. The hack is running a different startup-function and dont depend on the firmware version too much
