### ISSUE TITLE
Calibration via Webinterface only horizontal

### ISSUE THREAD

**Issue by staudtm** [EliasKotlyar/Xiaomi-Dafang-Hacks#512]
The camera "Calibration" via Webinterface is still doing "horizontal" also when choosing "vertical"

**Comment by jmtatsch** [comment]
7e04fa931aa91074b7fff50f6cfe6cbef8b165b9

**Comment by hyteoo** [comment]
Can be merged into [525](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/525)
