### ISSUE TITLE
Motion detection scripts not being executed

### ISSUE THREAD

**Issue by Damme** [EliasKotlyar/Xiaomi-Dafang-Hacks#515]
I added extra logging into detectionOn and Off but the scripts dont seam to be executed.

2018-06-23 19:38:40.271 (17466.327s) [ivsMoveDetection]         ImpEncoder.cpp:558      0| Will execute command /system/sdcard/scripts/detectionOn.sh
2018-06-23 19:38:40.274 (17466.329s) [ivsMoveDetection]         ImpEncoder.cpp:560      0| Execute /system/sdcard/scripts/detectionOn.sh returned:-1
2018-06-23 19:38:40.274 (17466.329s) [ivsMoveDetection]         ImpEncoder.cpp:752      0| Detect !!
2018-06-23 19:38:42.573 (17468.628s) [ivsMoveDetection]         ImpEncoder.cpp:558      0| Will execute command /system/sdcard/scripts/detectionOff.sh
2018-06-23 19:38:42.574 (17468.629s) [ivsMoveDetection]         ImpEncoder.cpp:560      0| Execute /system/sdcard/scripts/detectionOff.sh returned:-1

**Comment by nik0** [comment]
-1 means that either the scripts are not executed or the status of execution can't be retrieved.
is it always the case ? I got this once and after a reboot everything was alright.
What kind of camera do you have ? Try to lower the resolution, may be it is a memory issue.

**Comment by Damme** [comment]
I lowered resolution, and even tried modifying the script:
[root@Dafang1:scripts]# cat detectionOn.sh
echo "." >> /tmp/detect

same error, -1

**Comment by nik0** [comment]
What kind of camera?

**Comment by Damme** [comment]
Dafang df3

**Comment by nik0** [comment]
Maybe a memory issue
If you start the script manually?

**Comment by Damme** [comment]
Tried a whipe, new install and same issue, regardless och resolution.. :(

**Comment by belch85** [comment]
@Damme - did you have any luck?  I think I may be having a [similar issue](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/552).

**Comment by hjalves** [comment]
I'm having the same problem

**Comment by hjalves** [comment]
My problem is that the detection script doesn't even execute:

```
2018-07-08 10:45:02.660 ( 108.566s) [ivsMoveDetection]         ImpEncoder.cpp:571      0| Will execute command /system/sdcard/scripts/detectionOn.sh
2018-07-08 10:45:02.663 ( 108.570s) [ivsMoveDetection]         ImpEncoder.cpp:573      0| Execute /system/sdcard/scripts/detectionOn.sh returned:-1
2018-07-08 10:45:02.664 ( 108.570s) [ivsMoveDetection]         ImpEncoder.cpp:765      0| Detect !!
2018-07-08 10:45:04.699 ( 110.606s) [ivsMoveDetection]         ImpEncoder.cpp:571      0| Will execute command /system/sdcard/scripts/detectionOff.sh
2018-07-08 10:45:04.703 ( 110.609s) [ivsMoveDetection]         ImpEncoder.cpp:573      0| Execute /system/sdcard/scripts/detectionOff.sh returned:-1
```

**Comment by Damme** [comment]
running script manually works, but the automatic execution does not.
I tried making a small test script just echo "test" >> /tmp/testfile but no execution
manually works as I said.

**Comment by hjalves** [comment]
Exactly. Same problem as @Damme

**Comment by naitsimp** [comment]
I have the exact same problem. 
No yellow LED, no MQTT message, no Telegram message, no saved Image when motion is detected. 
Does someone found a solution to this yet?

I always read I should try to run the script manually, how do I do this?

**Comment by jmtatsch** [comment]
Are you on the latest version? Is motion enabled at all? Did you restart since enabling?

**Comment by naitsimp** [comment]
Yes. I downloaded the version from today and set the camera up.
Then I rebooted the camera.
The yellow LED and telegram message worked once, after that it didn't work again. I got the same message in the logs as hjalves.

On the GUI under Camera Controll:
- Motion Detection: ON
- Motion - LED: ON
- Motion - MQTT Message: ON

In the motion.conf file I have the following:
```
# edit this file and move it to /system/sdcard/config/motion.conf #
############################################################

# Configure the motion core parameters:

region_of_interest=0,0,1280,720
motion_sensitivity=4
motion_indicator_color=2
motion_timeout=-1
motion_tracking=off

# Configure how to deal with motion events:

motion_trigger_led=true
save_snapshot=false
max_snapshots=20
publish_mqtt_message=true
sendemail=false
send_telegram=true
save_dir=/system/sdcard/motion/stills
```

Still no luck of getting this to work.

**Comment by jmtatsch** [comment]
Is your telegram configured alright?

**Comment by czacha338** [comment]
I think I am facing the same problem with my Xiaofang 1S.

1. In script detectionOn.sh I have placed small test script:
> #!/bin/sh
> 
> date >> /system/sdcard/log/motion.log

2. When I run it manually it adds date to /system/sdcard/log/motion.log file
3. The logs on v4l2rtspserver-master.log looks so:
> 2018-09-30 20:41:35.106 ( 619.172s) [ivsMoveDetection]         ImpEncoder.cpp:599      0| Detect !!
> 2018-09-30 20:41:37.183 ( 621.249s) [ivsMoveDetection]         ImpEncoder.cpp:405      0| Will execute command /system/sdcard/scripts/detectionOff.sh
> 2018-09-30 20:41:37.189 ( 621.255s) [ivsMoveDetection]         ImpEncoder.cpp:407      0| Execute /system/sdcard/scripts/detectionOff.sh returned:-1
> 2018-09-30 20:41:41.318 ( 625.384s) [ivsMoveDetection]         ImpEncoder.cpp:405      0| Will execute command /system/sdcard/scripts/detectionOn.sh
> 2018-09-30 20:41:41.321 ( 625.387s) [ivsMoveDetection]         ImpEncoder.cpp:407      0| Execute /system/sdcard/scripts/detectionOn.sh returned:-1
> 2018-09-30 20:41:41.321 ( 625.387s) [ivsMoveDetection]         ImpEncoder.cpp:599      0| Detect !!
> 2018-09-30 20:41:43.364 ( 627.430s) [ivsMoveDetection]         ImpEncoder.cpp:405      0| Will execute command /system/sdcard/scripts/detectionOff.sh
> 2018-09-30 20:41:43.370 ( 627.447s) [ivsMoveDetection]         ImpEncoder.cpp:407      0| Execute /system/sdcard/scripts/detectionOff.sh returned:-1

4. The red circle in upper right corner is working, also in logs I can se that it detects something but the script is not executed by server itself...
5. I have tried to change resolution, sensivity etc. but without any success
6. Have anyone the same problem and could help me?

**Comment by jmtatsch** [comment]
Check if the detection scripts are really executable.

**Comment by necod** [comment]
Same problem with my Xiaofang 1S.
Permission are good:

[root@camara1:~]# ls -ld /system/sdcard/scripts/detectionOff.sh
-rwxr-xr-x    1 root     root           652 Sep 12 00:27 /system/sdcard/scripts/detectionOff.sh

[root@camara1:~]# ls -ld /system/sdcard/scripts/detectionOn.sh
-rwxr-xr-x    1 root     root          1692 Oct  6 12:35 /system/sdcard/scripts/detectionOn.sh

Does not return error where running from ssh.

**Comment by czacha338** [comment]
So scripts also on my camera are executable. without problem I can run them by hand and they give expected result. 

> -rwxr-xr-x    1 root     root            50 Sep 30 20:29 detectionOn.sh

Does anyone faced with this problem?

**Comment by necod** [comment]
It's a memory problem, adding swap solve the problem:
[](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/178#issuecomment-375931538)

**Comment by czacha338** [comment]
I have just made added to run.sh this swap, as it is written here:
https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/178#issuecomment-375931538

```
## Create swap file on SD if does not exist and use it
SWAP=true
SWAPPATH="/system/sdcard/swapfile"
SWAPSIZE=256
if [ "$SWAP" = true ]; then
  if [ ! -f $SWAPPATH ]; then
    echo "Creating ${SWAPSIZE}MB swap file on SD card"  >> $LOGPATH
    dd if=/dev/zero of=$SWAPPATH bs=1M count=$SWAPSIZE
    mkswap $SWAPPATH
    echo "Swap file created in $SWAPPATH" >> $LOGPATH
  fi
  echo "Configuring swap file" >> $LOGPATH
  swapon $SWAPPATH
  echo "Swap set on file $SWAPPATH" >> $LOGPATH
fi
```
And...

Finally I got motion detection running! Thanks a lot. It was a memory problem. 

```
[root@DAFANG:sdcard]# tail -f /system/sdcard/log/motion.log
Sun Sep 30 20:41:48 UTC 2018
Sat Oct  6 18:06:52 UTC 2018
Sat Oct  6 18:06:56 UTC 2018
Sat Oct  6 18:07:08 UTC 2018
Sat Oct  6 18:07:14 UTC 2018
Sat Oct  6 18:07:18 UTC 2018
Sat Oct  6 18:07:23 UTC 2018
Sat Oct  6 18:07:33 UTC 2018
Sat Oct  6 18:07:37 UTC 2018
Sat Oct  6 18:07:52 UTC 2018
Sat Oct  6 18:08:49 UTC 2018
Sat Oct  6 18:08:53 UTC 2018
Sat Oct  6 18:09:12 UTC 2018
Sat Oct  6 18:09:33 UTC 2018
```

**Comment by hooksoft** [comment]
Same thing was happening with me. Wish this tip was on display :)

**Comment by devernay** [comment]
The official recipe is in the FAQ: https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/hacks/faq.md#what-if-my-scripts-in-configuserscriptsmotiondetection-are-not-executed-or-mqtttelegram-messagesemails-are-not-sent-on-motion

### What if my scripts in config/userscripts/motiondetection are not executed or mqtt/telegram messages/emails are not sent on motion?

Your camera probably runs out of memory when processing the motion event. This is likely in cameras with 64MB e.g. the Xiaofang 1s. Try to enable some swap memory by copying swap.conf.dist to swap.conf and setting SWAP=true.
