### ISSUE TITLE
Calibration after reboot.

### ISSUE THREAD

**Issue by bgga** [EliasKotlyar/Xiaomi-Dafang-Hacks#517]
After rebooting camera i cant rotate camera to left vertical positon, i must activate calibration in settings menu and after that everything works fine.

**Comment by too-ugly-for-tv** [comment]
Same here, and possibly related is that doing a vertical calibration does both vertical and horizontal, but doing horizontal calibration does only horizontal. Either one fixes the problem with being able to move the base through the web interface.

**Comment by too-ugly-for-tv** [comment]
Related to: #512

**Comment by fotiDim** [comment]
How about an auto-calibration after each reboot?

**Comment by hyteoo** [comment]
Can be merged into [525](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/525)
