### ISSUE TITLE
Motion highlighting on image

### ISSUE THREAD

**Issue by too-ugly-for-tv** [EliasKotlyar/Xiaomi-Dafang-Hacks#519]
Wondering if there's potential to provide some kind of indication of where the motion was detected directly on the image as an option. Would be good for troubleshooting false-positives.

**Comment by nik0** [comment]
For now it is not possible.
The Ingenic SDK allow to define a detection area and returns true or false when detection happens.
In the last version of SDK they increased the number of areas (from 4 to 52). So we need to "cut" the image though these 52 areas to determine a region.

**Comment by Elxarus** [comment]
> 
> 
> For now it is not possible.
> The Ingenic SDK allow to define a detection area and returns true or false when detection happens.
> In the last version of SDK they increased the number of areas (from 4 to 52). So we need to "cut" the image though these 52 areas to determine a region.

Where did you find the SDK?

**Comment by nik0** [comment]
On Internet. Some people leack it on github
You have to purchase some evaluation device to get it "officially"
