### ISSUE TITLE
Compile "screen" package for Dafang

### ISSUE THREAD

**Issue by kszere** [EliasKotlyar/Xiaomi-Dafang-Hacks#52]
"screen" package will good for running any command and easy close, check running. This package can create new virtual terminal with any command.
Could anyone compile the screen package on Dafang?

Can use ex:
`/system/sdcard/bin/v4l2rtspserver-master -fMJPG
`
without `/system/sdcard/bin/busybox nohup` and ` &>/dev/null &`

**Comment by tseel** [comment]
I've started with

```bash
TOOLCHAIN=$(pwd)/mips-gcc472-glibc216-64bit/bin
CROSS_COMPILE=$TOOLCHAIN/mips-linux-gnu-
export CC=${CROSS_COMPILE}gcc
export LD=${CROSS_COMPILE}ld
export CFLAGS=""
export CPPFLAGS="-muclibc -O2"
export LDFLAGS="-muclibc -O2"

git clone https://git.savannah.gnu.org/git/screen.git

cd screen/src
sudo apt install ncurses-dev libtinfo-dev 
sudo ./autogen.sh
sudo ./configure --host=mips-linux-gnu-gcc
  
make
```
after cloning the dev environment and it compiles, but throws errors on execution. If I don't run the configure as with sudo, it wasn't able to pickup ncurses lib.
There are posts from 2011 about cross compiling and patches needed for not running some tests but they seem to be merged as compiling worked without patching.

**Comment by EliasKotlyar** [comment]
Hello @tseel ,

I tried to compile ncurses, but failed. There are a lot of dependencies, and i cannot make it work....
