### ISSUE TITLE
Could not connect to camera

### ISSUE THREAD

**Issue by smcallis77** [EliasKotlyar/Xiaomi-Dafang-Hacks#521]
Updated to the latest version (as at 24/06/2018 approx 01:00UTC) by writing contents of firmware_mod to a formatted memory card and reboot. RTSP was functioning (could access camera via VLC), but, could not access URL https://<IP Address> and could not login via ssh, ftp. I could enter root/ismart12 but got access denied.

Reverted back to previous version and then updated via the web page. All working. RTSP server, webpage, ftp and ssh.

You should be able to reproduce by the same process.

**Comment by jmtatsch** [comment]
What camera exactly?

**Comment by smcallis77** [comment]
Dafang. Sorry I should have said.

**Comment by manianac** [comment]
Different camera, but this is the same as #518

**Comment by smcallis77** [comment]
Yes, I agree, it seems to be the same issue, the symptoms and the logs are the same. Reverting back to a version from the 16/06 and then doing on online update resolved it.

**Comment by tsvi** [comment]
Confirming this issue.
Reverting to 394780d053679174141abaf8aa1a0d5f1097b778 solved it for me.

**Comment by manianac** [comment]
> Confirming this issue.
Reverting to 394780d solved it for me.

Cause unknown, but confirmed this worked for me

**Comment by jmtatsch** [comment]
Could not reproduce. Perform a fresh checkout of the git repo and you should be fine.
