### ISSUE TITLE
Add fw_setenv and fw_printenv tools for modifying U-Boot variables from Linux

### ISSUE THREAD

**Issue by mali1** [EliasKotlyar/Xiaomi-Dafang-Hacks#524]
fw_setenv and fw_printenv allow the modification of the U-Boot enviroment variables from a booted system. The addition of this tools would allow us to easily modify the buffers to allow Full-HD streaming (https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/30)
See also https://elinux.org/U-boot_environment_variables_in_linux

**Comment by EliasKotlyar** [comment]
Hello mali1,

Yes, that would be theoretically possible. Unfortunately, the stock u-boot is broken, and it cannot write the environment vars even when in u-boot. I have tried to compile a new uboot, but i am not brave enough to flash it, because it can brick the camera. If anyone have the proper devices to recover from a broken u-boot and want to try - contact me here.

**Comment by Damme** [comment]
I might give it a try, I have a smashed camera that still works. is there an dump of the original uboot in case I have to de-solder the flash to restore?

**Comment by EliasKotlyar** [comment]
Hell damme,

Thanks for your support. In a different issue, there are some hints how to flash the uboot:
https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/476

I ordered a Ch341 adapter and a clip for trying it out. It should arrive in a few weeks.

Please try to out the recovery first - before flashing a new bootloader which may break the system. In my experience it wont run on the first attempt.


PS: What kind of "smash" did your camera have?

Greatings
Elias

**Comment by Damme** [comment]
Cool, I already have all things to recover from dead firmware then :) I'll try to recover a healthy Uboot first.

Off topic; I had burglaries in my house just two days after I took down all my surveillance for maintenance and upgrades, I did not have time to put them back up immediately. They found some of my cameras and smashed them to pieces, I suppose they were afraid that they were online still... I later found them laying outdoors in bits. Might sound incredible but its sadly true, Murphy's law... :)

**Comment by EliasKotlyar** [comment]
@everyone:
I have created a new bootloader for all kind of T20 based Devices. If someone is brave enough, try it out:
https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/hacks/flashinguboot.md
It has support for changing the bootline and also support for a custom boot from microsd(uEnv.txt)
