### ISSUE TITLE
PTZ presets in web interface

### ISSUE THREAD

**Issue by satanasinc** [EliasKotlyar/Xiaomi-Dafang-Hacks#525]
Hi!

First of all excuse my bad english.
Your firmware is awesome! Thanx dude.

I have 2 bash scripts to move the camara to 2 preset positions but it can only run from a ssh session.
Is there any way to add buttons to the web gui for preset the cammera position or to call bash scripts?
My idea is move the camera from the domoticz events and take a pic.

Thank you in advance for your help.

Regard

**Comment by jmtatsch** [comment]
Can you show your script? Best thing would probably to send a mqtt message from domcotiz to Xiaomi camera...

**Comment by satanasinc** [comment]
Hi!
Thanks for your answer

**Comment by jmtatsch** [comment]
That command is relative to the current position, not absolute.
Recently @neroxps has done some extensions to enable going to absolute positions.

**Comment by RaymondSchnyder** [comment]
@jmtatsch is there documentation on how to control the cam with mqtt? i try it but it ignores my commands

**Comment by jmtatsch** [comment]
@RaymondSchnyder you probably suffer from #538

**Comment by staudtm** [comment]
May I share my thoughts about the PTZ preset?
I am wondering whether the following would be possible:
1. Do a calibration during startup and position the camera in the middle, vertically and horizontically (X=0,Y=0)
2. Whenever the position of the camera changes, log the new position.
3. Offer to save the current position as a preset via Webinterface (10 presets available)
4. Offer to move the camera to preset position via Webinterface; if preset not set, just don't move the camera)
5. Offer to move the camera to preset position via API (URL/MQTT)

Please tell me your opinions :-)

Regards
Markus

**Comment by hyteoo** [comment]
@staudtm this is actually the default behavior of most stock PTZ cameras that - like the Dafang - don't have an absolute positioning system.

But I think we can improve on that:

1. keep a structure of settings for PTZ that could include:
- calibration status (bool)
- X
- Y

2. On boot check calibrationStatus:
- if false: Do a calibration and position the camera in the middle, vertically and horizontically (X=0,Y=0). Set calibrationStatus = true
- if true: don't move the head and restore the X and Y positions

3. Whenever the position of the camera changes, save X and Y
4. Offer to save the current position as a preset via Webinterface (10 presets available)
5. Offer to move the camera to preset position via Webinterface; if preset not set, just don't move the camera)
6. Offer to move the camera to preset position via API (URL/MQTT)

This would be a more robust way of having both PTZ presets and absolute movements

@satanasinc can you share your scripts?
@neroxps can you share your experience on this subject?

**Comment by neroxps** [comment]
Hello everyone , I have been paying attention to this project, due to my poor English, I am sorry that I did not write detailed documentation for PTZperset.sh. (Another reason for not writing the documentation is that the New DAFANG motor driver is still not perfect, I still use the old motor driver)

How to use PTZperset.sh:

1. Set `motor hcalibrate` or `motor hcalibrate` in run.sh to make the motor calibrated.
2. Apply PTZ perset using the URL. As follows

```
wget --output-document=/dev/null http://[dafang_user]:[dafang_passwd]@192.168.1.108/cgi-bin/action.cgi?cmd=motor_PTZ&x_axis=100&y_axis=2500
```

Currently motor calibration is also available in new DAFANG (using the new motor driver), but the old motor drive moves very slowly, just like step by step. @EliasKotlyar Can fix the problem of slow moving speed for new DAFANG motors?

**Comment by S474N** [comment]
Is there app to iOS for PTZ control of Dafang?

**Comment by valkjsaaa** [comment]
It seems that @neroxps 's solution no longer works.

I've have tested it a bit and I found this command works for the latest firmware. The Dafang will recalibrate ever time it restarts once this line is added to into `run.sh`.

```
/system/sdcard/bin/motor.bin -d h -s 100
```

**Comment by fotiDim** [comment]
Can we make that an option in the UI?
