### ISSUE TITLE
Implementation "motion" package for Dafang

### ISSUE THREAD

**Issue by kszere** [EliasKotlyar/Xiaomi-Dafang-Hacks#53]
I think that this is good idea.
Motion can stream video, save snaphot and record video clip, check move and ver more...

I know that MicroSD is not good idea for saving most data. We can use USB Flash disk or SSD drive for save data.

**Comment by EliasKotlyar** [comment]
Hello @kszere ,

Compiling motion is a big task. You need to compile a lot of packages like ffmpeg, which wont run good on the dafang. It can be done, but i assume the performance would not be great.

Here is a tutorial for the motion project:
https://raw.githubusercontent.com/Motion-Project/motion/master/INSTALL

**Comment by nik0** [comment]
I agree with EliasKotlyar, 
motion is quite easy to compile.
I also succeded to cross compile FFMPEG, unfortunatly it crashes for some unknown reasons. I give up this way and I use motion on a Raspberry ...

**Comment by msj33** [comment]
Motion detection works somewhat in Home assistant through the ffmpeg_motion implementation(uses scheme change detection). 

Only bug I have currently is the distance to trigger the scene change(forest diction is 2 meters)........ But will try to tweak some extra parameters in ffmpeg tomorrow.

**Comment by msj33** [comment]
@EliasKotlyar : This have been implemented - Will you close it, thx

**Comment by kszere** [comment]
No this not implementation. Motion not available for Dafang, but implementation support with Home Assistant.

Good idea for close it.

**Comment by jmtatsch** [comment]
Alternative motion detection support available since #176, let's close this.
