### ISSUE TITLE
Pre-Event Motion Capture

### ISSUE THREAD

**Issue by bengalaviz** [EliasKotlyar/Xiaomi-Dafang-Hacks#530]
It would be good if the video was buffered in memory for a few seconds. Then when motion is detected, it would include the video up to the motion when writing out the file. Is this possible?

**Comment by saipsa** [comment]
but that will be limited by RAM. Another way would be to buffer it on disk, that way buffer can be several minute long.

**Comment by jmtatsch** [comment]
buffering on sdcard would write it through in a matter of weeks...

**Comment by saipsa** [comment]
@jmtatsch if with write it through you mean, decrease the life of sd-card, then we can buffer on usb hard disk.

**Comment by goermezer** [comment]
I think this feature is only possible by using the limited RAM. In this case I suggest stealing code from raspimjpeg: https://elinux.org/RPi-Cam-Web-Interface#Pre-Event_Motion_Capture_Buffer.

Another strategy could be a small additional buffer added to the front of the RTSP stream. The motion stop command then would have to be fired after the additional buffer time to be complete.

I do the recording with FFMPEG and Nodered on a Raspberry Pi after receiving the motion commands from Dafang through MQTT. There is always a lag of 2-6 seconds when motion is detected and recording starts.  In my case I could eliminate this lag with it.

**Comment by claud9999** [comment]
I'm familiar with the open source "Motion" security camera system, and it has the capability to capture N images before and M images after a motion detection event. (Where N and M are configurable.) Given the performance of SD storage, and the fact that it doesn't last forever, this really needs to be done in RAM. But it should only take N * {avg size of JPEG stills} memory.

**Comment by dmolner** [comment]
Hello,
I have a hack for a first Yi camera and make a video with images before movement.
[https://github.com/fritz-smh/yi-hack](url)

**Comment by dmolner** [comment]
My new Xiaomi Xiaofang 1S not have Motion folder and not work motion.
I create the folder but not work.
Not is possible capture few secons before motion?
https://github.com/fritz-smh/yi-hack
