### ISSUE TITLE
status.cgi broken

### ISSUE THREAD

**Issue by gabest11** [EliasKotlyar/Xiaomi-Dafang-Hacks#535]
It's under /cgi-bin and all calls are directed to /cgi-bin/cgi-bin/status.cgi

Interestingly, it won't fix the DafangCam on Android.

192.168.0.152 192.168.0.161 root [28/Jun/2018:12:57:19 -0200] "GET /cgi-bin/action.cgi?cmd=motor_up HTTP/1.1" 301 0 "-" "dafang-app-v0.1"
192.168.0.3 192.168.0.161 root [28/Jun/2018:12:57:37 -0200] "GET /cgi-bin/action.cgi?cmd=motor_up HTTP/1.1" 200 125 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36"

Any idea why it returns status code 301 when the app calls it? 

Edit: redirects to https, but that does not work for the app.

**Comment by gabest11** [comment]
A few more things. 

getMotionInfo.cgi: ps -wl, no 'w' switch for ps
action.cgi: rtsp-h264-with-segmentation stop, -with-segmentation does not exists

**Comment by jmtatsch** [comment]
Would you be so kind to whip up some PRs?

**Comment by gabest11** [comment]
PRs?

**Comment by gabest11** [comment]
Added a https redirection exception to lighttpd.conf for the user-agent "dafang-app". This fixes everything, but breaks the video stream, because now the mjpeg activation also goes through. 

As Mr. S Chen writes in the app store review.

"The app needs some fixes: it won't work with self signed certificates on the cam side, and it incorrectly starts the mjpeg service prior to opening video stream. The about page provides a link to the app's source but it's not there. Where's the source code, please?"

Too bad, because it looked like a semi-usable software.

**Comment by jmtatsch** [comment]
Regarding DafangCam please also see #399
