### ISSUE TITLE
HTTP MPEG Stream

### ISSUE THREAD

**Issue by AustinSaintAubin** [EliasKotlyar/Xiaomi-Dafang-Hacks#539]
Any chance that MPEG streams could be implemented?
https://github.com/jacksonliam/mjpg-streamer

**Comment by jmtatsch** [comment]
We already have functionality for streaming mjpg in https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/firmware_mod/bin/mJpegStreamer . What are you missing?

**Comment by AustinSaintAubin** [comment]
Tried, after killing the other streaming processes.....
Every time I would start `mJpegStreamer 10`, the Wyzecam V2 would lockup.

**Comment by AustinSaintAubin** [comment]
['mJpegStreamer'](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/firmware_mod/bin/mJpegStreamer) provides an mpeg streams over RTSP.

I need an MPEG stream over HTTP, like what [mjpg-streamer](https://github.com/jacksonliam/mjpg-streamer) is able to do. Its similar to what is done with `https://CAMERA-IP/cgi-bin/currentpic.cgi` but constantly refreshes based on settings.
Similar to how [these streams](http://www.ispyconnect.com/man.aspx?n=vivotek) behave.
Stream needs the option to be over HTTP, not HTTPS. 
Here are [some sample steams](http://en.ipcams.ch/WebCam.aspx?nr=1729).

**Comment by mcheah** [comment]
Seconding this feature request.  
Looking to use this camera as a cheap wifi cam for [Octoprint](https://github.com/foosel/OctoPrint/issues/937).  Octoprint currently only supports http mjpg streams, directly embedded in their web interface, explicitly not RTSP.
I may look into this myself.  Is the video interface accessible as a normal video4linux device?  Is there a method for compiling directly on the device?  Or is cross-compilation the only method for creating code?

**Comment by AustinSaintAubin** [comment]
@SomebodySysop I am looking for something more native... that does not require another application just to get an mpeg stream. But thanks for the info.

**Comment by AustinSaintAubin** [comment]
Trying a work around to [Restream RTSP to M-JPEG](https://github.com/cncjs/cncjs/wiki/FAQ#restream-rtsp-to-m-jpeg).
But I cannot get it to work with the camera... tested H264 RTSP, and MJPEG RTSP streams.

**Comment by kalazzerx** [comment]
I am also interested in this feature - in order to connect to https://www.actiontiles.com/ as a tile on my smartthings interface.

**Comment by jneilliii** [comment]
I'd like this thread to be revisited.  Native mjpg over http IMO would be efficient and a welcome addition to the project.  Like @mcheah mentioned, being able to use this CFW on a Wyze 2 Cam with OctoPrint would be a huge benefit.

**Comment by jokesters** [comment]
I've been trying to get this to work with octoprint for a while now.

**Comment by redpizza69** [comment]
Just flashed a Neos camera to use with Octoprint... and then read this after I couldn't get it to work.

+1 for mjpg over http.

Anybody found a solution yet?

**Comment by jneilliii** [comment]
There are some posts on the octoprint community forum that are basically reencoding the stream using VLC or ffmpeg, but in that situation you still introduce lag.

**Comment by crackers8199** [comment]
add me as a +1 for adding this, if possible. i have been unable to get rtsp to work reliably on my phone over openvpn. 

right now, i have this running on a server at home re-encoding the RTSP stream...

https://github.com/eroji/rtsp2mjpg

doesn't seem to be much (if any) lag, and stream seems solid so far on my phone (while the H264 RTSP stream viewed in tinycam pro crashes often when i'm connected via VPN). the downside (to me) is that in addition to needing an always on machine to do the re-encode, i can't move the camera from the active stream, since there's no setting for it using a generic camera.  having this available natively from the camera would be a huge improvement and a great addition to the firmware.

**Comment by jmtatsch** [comment]
Why dont you just stop the H264 RTSP and start the MJPEG RTSP?

**Comment by crackers8199** [comment]
I haven't been able to get the mjpeg streamer to work. Even when trying to connect on my home network i have no picture...

**Comment by jmtatsch** [comment]
You need to shut down the h264 server first. Also check your autostarts.

**Comment by crackers8199** [comment]
> You need to shut down the h264 server first. Also check your autostarts.

I have done that. I've tried it multiple times, each time shutting down the h264 first. Mjpeg doesn't work. There was an issue that seemed to indicate it is known it doesn't work, but isn't important to fix because h264 works...I'll try to find it but I'm on my phone so it might be tough.

**Comment by crackers8199** [comment]
can someone re-open this issue? either that or explain how to get MJPG RTSP streaming to work? if it's supposed to work i'm doing something wrong, because i've been trying for weeks and have never been able to get a video feed when using the MJPG RTSP server...

**Comment by mathewgreen** [comment]
Yes, this would be awesome!  This would be the prefect solution if we could get native HTTP MJPG.

**Comment by JamesSimpson** [comment]
I too am interested in this if it could be added.

**Comment by drug123** [comment]
For all OctoPrint users (@crackers8199 @AustinSaintAubin @redpizza69 etc.) - you can have a nice workaround for getting it to work with your printer which does not require any transcodings. You basically need to do two things to make it work:

1. Remove login requirement from /cgi-bin/currentpic.cgi You can do it by modifying /config/lighthttpd.conf on SD card:
```
# Support letsencrypt SSL cert paths
# (we don't want to upgrade to SSL nor auth' this path)
$HTTP["url"] !~ "^/.well-known/(.*)|^/cgi-bin/currentpic.cgi" {

	$HTTP["scheme"] == "https" {
		auth.backend				= "htdigest"
		auth.backend.htdigest.userfile = "/system/sdcard/config/lighttpd.user"
		auth.require = ( "/" => ("method" => "basic", "realm" => "all", "require" => "user=root"))
		alias.url = ( "/viewer" => "/system/sdcard/DCIM/" )
		$HTTP["url"] =~ "^/viewer($|/)" { server.dir-listing = "enable" }
	}
```
I've added `|^/cgi-bin/currentpic.cgi` over there to disable password request for getting snapshots.
2. Use `https://micam.local/cgi-bin/currentpic.cgi` in your Webcam snapshots section (use whatever hostname/IP you have instead `micam.local`), and also install SnapStream plugin and point it to `https://micam.local/cgi-bin/currentpic.cgi`
