### ISSUE TITLE
Pan and Tilt / Similar camera to use in apps

### ISSUE THREAD

**Issue by pgruetter** [EliasKotlyar/Xiaomi-Dafang-Hacks#54]
Thanks for your great work, installing the hacks worked flawlessly. 

I'm using tinyCam pro on Android and the only way I got the camera working there is by using the XiaoFang as camera model. Since the XiaoFang doesn't support pan and tilt, the controls are greyed out. 
I know this question should probably be directed to tinyCam to support the camera, but do you know of a similar camera that I could try ? I was under the impression that I could chose any camera "model" that would support RTSP over TCP.
Strangely, I tried many other camera that also support RTSP over TCP but none of these worked.

Thanks

**Comment by EliasKotlyar** [comment]
Hello @pgruetter ,

There is a similar issue here:
https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/41

There is a solution for tinycam, to use pan/tilt.

Greatings 
Elias

**Comment by pgruetter** [comment]
Wow, thanks a lot for the quick answer. Looks like I missed that lengthy discussion. Will go through it and add my comments there.

**Comment by daihung1** [comment]
Hi...I'm a noob here so please bear with me.  This is so technical for me so I have a few questions.  I just recently got a Dafang...and I followed the installation instruction to install bootloader, put the firmware mod in the sdcard and modified the file to connect to my wifi.  I don't know what to do next. I can't tell if it is connected to my wifi. It has a steady yellow light.  what do I need to do next to connect it to my Tinycam pro app or view it on the computer?  I'm totally lost.  Any advice is very much appreciated.

Thanks all for all the great work here.
