### ISSUE TITLE
access videos/pictures in web ui

### ISSUE THREAD

**Issue by ceif** [EliasKotlyar/Xiaomi-Dafang-Hacks#543]
Is it possible to create a menu in web ui where we can see thumbnail and download video/pictures recorded?

And add a record button in right menu...where easily we control the record action.

**Comment by mitchoklemen** [comment]
Great idea! ... and button to delete picture or video.

**Comment by jmtatsch** [comment]
That would be great. We would certainly appreciate a pull request.
