### ISSUE TITLE
Default password denied by SSHd

### ISSUE THREAD

**Issue by mcknly** [EliasKotlyar/Xiaomi-Dafang-Hacks#544]
Attempting to connect via SSH, username:root password:ismart12

` $ ssh root@192.168.1.112`
`The authenticity of host '192.168.1.112 (192.168.1.112)' can't be established.`
`ECDSA key fingerprint is 5a:e8:ff:5f:1d:d2:47:99:9d:4f:5f:08:3f:ae:ca:0f.`
`Are you sure you want to continue connecting (yes/no)? yes`
`Warning: Permanently added '192.168.1.112' (ECDSA) to the list of known hosts.`
`root@192.168.1.112's password:`
`Permission denied, please try again.`
`root@192.168.1.112's password:`
`Permission denied, please try again.`
`root@192.168.1.112's password:`
`Permission denied (publickey,password).`

Can SSH access/default password of 'ismart12' be verified in the latest release?

**Comment by jmtatsch** [comment]
Which camera exactly? There were issues with the wyzecams using different passwords...

**Comment by mcknly** [comment]
Sorry, should have specified, it is Wyzecam v2. Any others I should try?

**Comment by jmtatsch** [comment]
No idea. Can you post your first startup.log?

**Comment by jmtatsch** [comment]
@tssva do you have an idea why people still have problems to use the bind mounted shadow file?

**Comment by mcknly** [comment]
I think I have found the issue. For some reason my /etc/passwd and /etc/shadow had a .txt appended to the filenames. Before writing to the SD I had the directory up on Google Drive, and pulled it down on another machine. It seems that maybe GDrive added the file extension.

I can't test at the moment but I will verify later and close.

**Comment by mcknly** [comment]
Verified it was a problem with extraneous file extension. Closing issue. Word of caution for using Google Drive!
