### ISSUE TITLE
DaFang 2017DP3894 5.5.1.327 Can't Initiate Firmware Update

### ISSUE THREAD

**Issue by belch85** [EliasKotlyar/Xiaomi-Dafang-Hacks#545]
Hi Guys,

I'm having [this issue](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/64).

Back of my DaFang "2017DP3894".  Can't figure out if I should be using [fang-hacks](https://github.com/samtap/fang-hacks) or [Xiaomi-Dafang-Hacks](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks).  Have tried both for hours in frustration, no success.

When trying to install the Xiaomi-Dafang-Hacks booloader [here](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/hacks/install_cfw.md) I get to step 7 - the camera doesn't seem to initiate firmware update, instead the base moves/calibrates and it starts up normally.  I've tried holding setup button for slightly shorter periods and for longest possible (until base moves).  I've tried two different microSD cards, both formatted fat32, no other files, following all instructions.  Can't get it to trigger the update.

When getting to fang-hacks Step 5 [here](https://github.com/samtap/fang-hacks) I was presented with 404 not found while on Xiaomi firmware 5.5.1.287, but since updating to 5.5.1.327 I now receive 404 connection refused.  Have tried:
- http://device-ip/cgi-bin/status
- http://device-ip/cgi-bin/hello.cgi
- https://device-ip

All give same results (404).  I do hear the "tap-tap" sound in all attempts.  The log file it creates is bloated & not legible.

Have tried [downgrading firmware](https://github.com/samtap/fang-hacks/wiki/HowTo:-Flash-original-Xiaomi-firmware-from-sdcard-(factory-reset)) using SD Card method - can't get it to trigger firmware update, camera boots as per normal.  Have tried connecting via SSH COM1/COM2/COM3 - nothing works.

No matter what method & files I put on SD card, it doesn't seem to initiate the firmware update sequence.  What am I doing wrong?

**Comment by Darkblade48** [comment]
You should be using this repository (Elias Kotlyar's). Fang-hacks only works with the older version of the Xiaofang.

For installing the microSD bootloader, make sure of the following:

1) Ensure microSD is formatted to FAT32
2) Do not right click --> download the .bin file from the install_cfw.md page! It actually saves the page that links you to the [i]actual[/i] .bin file! Instead, click the link (or go to https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/hacks/cfw/dafang/cfw-1.3.bin), and hit the "Download" button. Ensure that the .bin file is ~11 mb in size!

I had the same problem of being unable to flash, but it turned out to be due to (2)!

**Comment by belch85** [comment]
Thanks for that suggestion.  I'll triple check tonight, however I'm already certain I was using the correct file, I recall it's file size and using the download button itself.

Do you remember the exact sequence to force firmware update once microSD is in the DaFang?  Did you release the setup button after a certain point (IE a noise or light)?

**Comment by belch85** [comment]
****SOLUTION*****

I'm certain my camera was paired prior to trying this process multiple times, but with microSD card A.  I'm now on my third microSD card and by this stage it was no longer paired with the MiHome app.

After finding @luisbarreto comment, I completed the setup process and paired with MiHome, and now finally progressed through the bootloader stage!

See [here](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/64#issuecomment-403021863) for more details.

**Comment by Darkblade48** [comment]
How odd! The camera has to be setup in Mi Home app first now?

I do recall playing around with the camera in the app for a bit, but thought nothing of it (let alone that it would be required to flash the microSD bootloader onto it)

**Comment by Alejandro-pucci** [comment]
Using the app isn't necessary.

**Comment by belch85** [comment]
@shiznat The issue you're describing seems exactly the same as mine.  I guess I have no way of knowing that configuring the camera in Mi Home app is actually what caused it to work.  At that point I'd also tried about 20+ times with different microSD cards - it just happened to work that time, and has worked every time since.  I had initially tried with it configured in the app and also without (I think holding down the button causes it to reset - so you have to get it right the first time, if you don't, it needs to be added to MiHome all over again.

I guess something else may have caused it to begin working - but I can't put my finger on it.  For me all arrows pointed towards pairing it with the app as the solution.

By the way - I'm finding the camera frustrating in Home Assistant (the image on front-tile is updated once every 10 seconds roughly, and when I click to view the live-stream, it can also sometimes be very low frame rate).  I have a strong UniFi network and the connectivity is excellent.  Would you mind sharing your config.yaml so I can compare notes on how you have yours configured?

**Comment by shiznat** [comment]
@belch85 To add to that you could try modifying the video feed resolution and bitrate from within the DaFang Hacks WebUI but again depending on the device you run Home Assistant on it may not help much.

**Comment by shiznat** [comment]
@belch85 Yea I am using rtsp.

```
camera:
  - platform: ffmpeg
    input: -rtsp_transport tcp -i rtsp://root:pass@10.1.4.10:8554/unicast
    name: Kitty Cam
    extra_arguments: -q:v 2 
```

The extra arguments was from when I was trying to lower the quality for use on my Pi. TBH I'm not sure I need it still or if it should be there.  

I'd recommend SSH'ing in to the QNAP while you load the live stream and check 'top' to see how much CPU ffmpeg is using.

**Comment by jmtatsch** [comment]
Closing this as belch85 was successful.

**Comment by dgonneau** [comment]
Old thread, closed but there was no real answer.
For what it's worth, make sure the partition on the sd card is primary. I was creating 512 mb partitions as advised by the hack installation instructions, but the partition was logical. Once I changed it to primary I got the blue light right away after 5/6 seconds of pressing the button after plugging in the power.

**Comment by jmtatsch** [comment]
I added a hint to partition as a primary partition into the installation instructions. Thanks.
