### ISSUE TITLE
WyzeCam Pan - No web interface, can't log into SSH

### ISSUE THREAD

**Issue by jcoutch** [EliasKotlyar/Xiaomi-Dafang-Hacks#546]
I spent the better part of a day trying to get the custom firmware loaded on my WyzeCam Pan (model `WYZECP1`)...and while I can tell it's booting (I see updated files in /log on my SD card), I cannot access the web UI.

I attempted connecting via SSH and FTP using `root/ismart12`, but get `access denied` for both services.

Here's the steps I performed:

1. Downloaded and flashed cfw-1.0.bin:
Instructions used: https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/hacks/install_cfw.md
Firmware downloaded: https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/hacks/cfw/wyzecam_pan/cfw-1.0.bin

2. Cloned this repo, and copied all files from `/firmware_mod` to the root of the SD card (the master branch's head was at `301dadc` at the time of me cloning it.)

3. Edited my wpa_supplicant.conf file with my AP's info.

4. Followed instructions in #522 and extracted `8189es.ko` from `driver.bin` located here:
https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/tree/master/firmware_original/wyzecam_pan/4.10.0.222

5. Started up the WyzeCam Pan with the SD card installed, and after booting, the light stays a slowly flashing amber color.

Here is my startup.log:
```
==================================================
Starting the Dafang Hacks Custom Application Layer
==================================================
Loaded common functions
Created etc directory on sdcard
Bind mounted /system/sdcard/bin/busybox to /bin/busybox
Bind mounted /system/sdcard/root to /root
Bind mounted /system/sdcard/etc to /etc
wpa_supplicant: Successfully initialized wpa_supplicant
rfkill: Cannot open RFKILL control device
nl80211: Could not re-add multicast membership for vendor events: -2 (No such file or directory)
udhcpc: deleting routers
adding dns 8.8.8.8
adding dns 8.8.4.4
Initialized gpios
dropbear: 
bftpd: 
lighttpd: 
Startup finished!
```

I can verify that the WyzeCam Pan is connecting to my Wi-Fi (I see a host named `DAFANG` with an IP address assigned), and dropbear/bftpd are both running and responding to requests, yet nothing else works, and I can't log in to do any sort of diagnostics.  What am I doing wrong?

**Comment by max-cooliotto** [comment]
I'm having the same issue except with the XIAOMI DAFANG camera.  

My startup log:

```
==================================================
Starting the Dafang Hacks Custom Application Layer
==================================================
Loaded common functions
Created etc directory on sdcard
Bind mounted /system/sdcard/bin/busybox to /bin/busybox
Bind mounted /system/sdcard/root to /root
Bind mounted /system/sdcard/etc to /etc
wpa_supplicant: Successfully initialized wpa_supplicant
rfkill: Cannot open RFKILL control device
nl80211: Could not re-add multicast membership for vendor events: -2 (No such file or directory)
udhcpc: deleting routers
adding dns 192.168.1.1
Initialized gpios
dropbear: 
bftpd: 
lighttpd: 
Startup finished!
```
I am able to see my dafang on my WIFI network as well, and i can connect to it via SSH but cannot login using the root/ismart12 creds supplied in the FAQ.  Same with FTP (login denied).

**Comment by tssva** [comment]
Are you cloning and copying the files on a Windows, Mac or Linux system?

**Comment by jcoutch** [comment]
Windows

**Comment by tookus123** [comment]
Check the line endings on /system/sdcard/passwd and /system/sdcard/shadow. Windows git will sometimes change the line ending from lf to crlf. It will cause login to fail.

**Comment by max-cooliotto** [comment]
@tookus123 Looks like that helped (a bit) as well as I'm on Windows also -- I have changed the line endings on the `shadow` and `passwd` files to UNIX (LF).  I can now SSH and FTP into the camera no problem.  Now the only thing is that the CFW webserver is still not accepting connections.  Are there any other files that we need to ensure have the right line endings?

**Comment by tssva** [comment]
Check config/lighttpd.user

**Comment by jcoutch** [comment]
@tssva - Good thing I installed WSL (Windows Subsystem for Linux) yesterday.  :-)  I re-cloned the repo under Ubuntu 18.04, copied the files to the SD card (along with the 8189es.ko module), and everything works!  I'm going to submit a pull request to update the documentation.

**Comment by tssva** [comment]
PR #551 adds an eol setting to .gitattributes for the files in firmware_mod/etc and updates the entry for lighttpd.user to firmware_mod/config/lighttpd.user. This should prevent the Windows git client from modifying the line endings.

Copying the 8189es.ko module should not be necessary. If you just copy it to the drivers directory on the sdcard it isn't getting loaded anyways. The `run.sh` script specifically loads `/drivers/8819es.ko` and not `/system/sdcard/drivers/8819es.ko`. `/drivers/8819es.ko` is the driver from the original firmware. You have in effect extracted and copied over the identical driver file to a location where it will not be loaded by the startup script.
