### ISSUE TITLE
Config entries in rtspserver.conf may be wrong

### ISSUE THREAD

**Issue by goermezer** [EliasKotlyar/Xiaomi-Dafang-Hacks#548]
In rtspserver.conf.dist there are some entries which are set differently via the web interface. For example 

rtspserver.conf.dist:

HIGHPASSFILTER=ON

When I set the high pass filter to on in web interface I get true in rtspserver.conf:

HIGHPASSFILTER=true

Same for OFF -> false

**Comment by nik0** [comment]
And something is not working ? Setconf is able to read true/false or on/off as input
maybe on the gui itself ?

**Comment by goermezer** [comment]
No everything is fine. It was only a remark...
