### ISSUE TITLE
original firmware broken

### ISSUE THREAD

**Issue by sucht3371** [EliasKotlyar/Xiaomi-Dafang-Hacks#549]
the firmware update was a power failure now the original firmware is broken.
Is there a way to flash the original firmware via serial.

**Comment by EliasKotlyar** [comment]
Just apply the microsd-hack. It should repair your camera.

**Comment by Alejandro-pucci** [comment]
Hi,
I may have a similar problem. My second Dafang flashed the demo.bin on the first try and loaded the firmware_mod contents on the next boot from a different card. So the cards are proven to work. 

Now, the first Dafang (2017DP3894 firmware 5.5.1.285) does not initiate the flashing. When connecting the usb and holding the setup button, it flashes the orange LED for a few seconds, the the blue LED for <10 seconds, and starts turning the base.

It is possible that with the first Dafang I didn't know what I was doing so I might have interrupted the flashing process. Is it even theoretically possible that I may have corrupted the specific part of the firmware that does the flashing? 

If so, how to re-flash the firmware? The app offers an upgrade to 5.5.1.327. Would this help and should I try it? (Can anyone confirm 5.5.1.327 doesn't cause anything irreversible?) 

The last hope would then be to use the serial connection, but I would like try everything possible before opening it up. I do have an FTDI lying around.

Thanks in advance for any advice.

**Comment by jmtatsch** [comment]
@Alejandro-pucci I think updating to 5.5.1.327 should be save. You can also try downgrading to one of those firmwares 
https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/tree/master/firmware_original/dafang with the demo.bin game. If nothing works wire up your serial interface and look what really is going on.
