### ISSUE TITLE
Trouble flashing the custom firmware

### ISSUE THREAD

**Issue by Repolho88** [EliasKotlyar/Xiaomi-Dafang-Hacks#550]
Hi, I just bought my Dafang, connected the cable and the light stays solid orange, tried to flash with all the instructions you have here and everytime I use the SDcard holding the setup button while plugging the cable, it stays orange for about 10 sec. then it turns the blue light and stays blue and orange solid light...tried more than 24h and it is still the same. Anyone had this type of problem?

**Comment by tookus123** [comment]
Make sure  you have rename the .bin file to demo.bin. Also check the filesize of the .bin file. If the file isn't more than 10mb then you don't have the correct file. This can happen if you right click on the .bin file and try to "Save Link As" or use something like curl or wget. You have to click on the link in your browser and then click Download. Not sure if that's  your problem but i and a bunch of others have run into this.

**Comment by Repolho88** [comment]
@tookus123 everything by the book, it's been a mont of trial and error, reading all information on the web about it (slim to non), but never found anyone talking about the 2 colored leds on when entering the "flash mode". To make it even clearer, I've opened the cam and disconnected all the plugs and put them back. Considering it a brick now, I'm from Europe and bought from China, it's stupid to send it back. If I detect the source of the problem whatever the process to fix it i'm able to, is there a TOTAL reset from factory via USB or Serial that solves any software problem that may be causing this?

**Comment by jmtatsch** [comment]
Did you camera work with the stock firmware?

**Comment by Repolho88** [comment]
@jmtatsch I connected the first time it moved and talked and but never again felt her pulse =(

**Comment by jmtatsch** [comment]
And now, without the sdcard in it should still load stock application layer?

**Comment by Repolho88** [comment]
Same results, without the card it stays orange and does 2 clicks, no movement and no speech. With card without pressing buttons same thing. With card pressing the button about 8-10 seconds it turns the blue light on but the orange stays lit to, and does nothing. Tried 2 sd cards, formated from FAT to FAT32 with a 512mb partition, a 4gb partition and the whole card in every format possible. Can't think of any solution, they don't have any type of light codes to identify what's wrong.

**Comment by tookus123** [comment]
@Repolho88 - Not sure if this will work but have you tried to revert to the original firmware? Directions are in the faq. See if you can do that and if you get movement and voice again like when you first connected it. You say you've tried two different sd cards. Are they the same brand. Maybe try a different brand. Very frustrating.

**Comment by Repolho88** [comment]
Tried that also... Hanging myself with the usb cord in 3...2...1...

**Comment by shiznat** [comment]
I bought a DaFang 1080P camera a few months ago and flashed it no problem, have been using it with Home Assistant integration, no problems. I decided to buy another one as the first was working so well but frustratingly I CANNOT get the bootloader to flash - I am fairly certain I am doing it correctly as I managed to flash the first camera I bought.

I have tried 3 different SD cards and confirmed 100% that I am using the correct .bin file and have downloaded it correctly (~10.5MB in size) but the camera blue light comes on for a few seconds after turning on while holding the setup button and then goes back to yellow and within ~10 seconds the base starts moving and it boots in to the normal firmware. 

It doesn't matter what combination of SD cards or button pressing I use it just refuses to flash. I had also read in a few other threads that hooking it up in the MiHome app is also required which I have done a handful of times as well but this hasn't made any difference.

**Comment by sn33ky** [comment]
i have the same problem. I tried it +-20 times on my dafang, but i don't get it to work.  please help.

The first step is going well. after removing the SD card and booting without it is orange for 5+ seconds, then blue for 5+ second, then orange for 5+ and then it starts moving. 

But when performing step 2 the orange led is on for 10+ seconds, then  1 second blue, then 20 seconds orange, 15 second blue and then it continues blinking 3 seconds orange.

**Comment by bloodybeet** [comment]
Same as above, but it after the 20 seconds orange, it will stay deep blue indefinitely, and still won't show up in my router as having joined the network :'(
It will even go to indefinitely blue when I enter incorrect WPA credentials, so I'm not sure what else is wrong :/

**Comment by Tramsrepus** [comment]
I also have the same problem. At step 10 at the instrictions, It lights up blue for about 5-6 sec and then yellow for 8 seconds then it starts moving... Then i cant get the firmware working. I will try to revert the org firmware and then try again. I had this problems with my XiaoFang cameras with a too new firmware.

**Comment by Tramsrepus** [comment]
@jmtatsch The latest. 5.5.1.197 but i successfully ran the demo_5.5.1.194.bin and also confirmed it in MI Home. But it did not change anything. A also tried the demo_5.5.1.177 but the foot motor got stuck at the end-stop and never turned off. So im back on demo_5.5.1.194.

**Comment by Tramsrepus** [comment]
@ i just did a new update and it now shows 5.5.1.344... It may work better. I will test it anyway

**Comment by Tramsrepus** [comment]
@jmtatsch It did not change anything either. After custom firmware is started the LEDD goes fast yellow blinking. I have spent the whole day trying to get this work but to no avail. I have had no problem with my 3 XiaoFang after downgraded the original firmware. But Dafang is more stubborn... Any ideas?

**Comment by Tramsrepus** [comment]
@jmtatsch Okay. It seems that the size 32GB of my SD-card did matter. Partitioned at 8GB and all worked out well.... But it was asking for a password, found one but I got a lot warnings. Well in, there is no graphics, just plain text. How to fix?

**Comment by Tramsrepus** [comment]
I can see the video stream but no buttons work in the https://xxxxxxxxxx/cgi-bin/status.cgi. Why is it an S at http? "Secure"?? I dont have that on me XiaoFangs.

**Comment by Tramsrepus** [comment]
@jmtatsch  I already do that. But how to get the /cgi-bin/status.cgi page for my Dafang to be shown correctly and with working settings?

**Comment by jmtatsch** [comment]
You are not supposed to use that page directly.
The CGI renders only the content without the skin.
You should call https://yourDafangHostnameOrIP instead.

**Comment by jmtatsch** [comment]
@Tramsrepus Nice video, but also pretty outdated. A lot has happened since then.
Was your XiaoFang purchased recently or is an older model? The older models are not supported by this repo.

**Comment by Tramsrepus** [comment]
XiaoFang are brand new 1080P cameras, bought a few weeks ago.

**Comment by shiznat** [comment]
I'm still having this same issue with the second DaFang camera I purchased. I've come back to it after a month and am unable to flash the demo.bin to it. Is this an isolated issue or what?
