### ISSUE TITLE
Night mode not working in Blue Iris

### ISSUE THREAD

**Issue by Bboy486** [EliasKotlyar/Xiaomi-Dafang-Hacks#553]
Picture is black but the LED lights are red on the camera.

**Comment by SnOOpeRa** [comment]
same here , xiaofang 1s , latest commit

**Comment by jjlawren** [comment]
Same on a Dafang after a recent update.

**Comment by jjlawren** [comment]
Perhaps it's from the pull requests related to this case: https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/79

If I run the old script (`/system/sdcard/scripts/ldr.sh`) then night mode will toggle on/off. Perhaps the light threshold defaults for the new binary are too conservative?

**Comment by jjlawren** [comment]
Or maybe that was a random coincidence as my Dafang doesn't even seem to have a light sensor: https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/332 :(

**Comment by FuzzyMistborn** [comment]
I think we can mark this closed based on the recent addition of autonight mode with #699
