### ISSUE TITLE
Loop n times on audio file and API to stop playing sound

### ISSUE THREAD

**Issue by didaskein** [EliasKotlyar/Xiaomi-Dafang-Hacks#555]
Good morning,

Thanks for all the work you've already done and it's working great! :)

In the context of an alarm scenario, I would like to be able to launch a sound (police.wav) several times in loop as long as I do not call an audio playback stop command. I don't know if it's complicated to add...

Thank you in advance,

**Comment by nik0** [comment]
It is not complicated as long as you know a bit of scripting
you can create custom scripts while detection in `/system/sdcard/config/userscripts/motiondetection/`
see `/system/sdcard/detectionOn.sh
`

**Comment by didaskein** [comment]
I'm not very good at scripting ;) I would like to call the Dafang API from Jeedom home automation solution... ;)

**Comment by nik0** [comment]
The script could be like this (I didn't test it to no wake up the house)
Put this script in /system/sdcard/config/userscripts/motiondetection/audio.sh
```
FILE=/tmp/audioOn
OnExecution()
{
        while [ -f $FILE ]
        do
          /system/sdcard/bin/audioplay /system/sdcard/Media/police.wav 50
        done                                                             
}                        
            
if [ $1 == "on" ]
then             
        echo ON  
        touch $FILE
        OnExecution &
else                 
        rm -rf $FILE 
        echo OFF    
fi      
```
You will find logs in "video server" section
enjoy !

Nik0

**Comment by Morphy99** [comment]
I'm looking at doing this for a doorbell via mqtt. Having some trouble with the script though, I get this when doing ./doorbell.sh

`ash: on: unknown operand
OFF
`
My script in /system/sdcard/config/userscripts/ looks like this:
`LE=/tmp/audioOn
OnExecution()
{
        while [ -f $FILE ]
        do
          /system/sdcard/bin/audioplay /system/sdcard/Media/doorbell.wav 50
        done
}

if [ $1 == "on" ]
then
        echo ON
        touch $FILE
        OnExecution &
else
        rm -rf $FILE
        echo OFF
fi
`

**Comment by Morphy99** [comment]
Ok so I hacked the script to work but how can I trigger this from HA?

**Comment by corvy** [comment]
I enable / disable motion detection from MQTT from HA @Morphy99 . If this is not an option I think you have to use an automation that runs the command from SSH. Node-RED exec node is what I use for this purpose.

**Comment by Morphy99** [comment]
Yea I can switch motion via mqtt. I will try running it via ssh.

**Comment by Morphy99** [comment]
Ok so I have set up a SSH key from my HA box and would like to run a script to trigger the doorbell. 
The above script didnt work for me so I simplified it to:
```
#!/bin/sh

PATH=/system/sdcard/bin:/system/bin:/bin:/sbin:/usr/bin:/usr/sbin:/sbin:/bin

/system/sdcard/bin/audioplay /system/sdcard/Media/doorbell.wav 50
```
works fine if I run it logged in via SSH but as soon as I put it after the ssh command it errors with this: /system/sdcard/bin/audioplay: can't load library 'libimp.so'

**Comment by nik0** [comment]
@Morphy99 
You need to set the variable LD_LIBRARY_PATH (you should have example somewhere else) but you should have something like that in your script:
`export LD_LIBRARY_PATH=/system/sdcard/lib:$LD_LIBRARY_PATH`

**Comment by Morphy99** [comment]
Thanks I already tried that as I saw it mentioned somewhere else but I thought I was going down the wrong path:
```
ssh root@192.168.0.25 '/system/sdcard/config/userscripts/doorbell.sh'
Volume is 50
Usage:please check file:libaudioProcess.so is in path of /lib or /usr/lib
If you put file:libaudioProcess.so in your defined path:
  you need to set the enviroment variable LD_LIBRARY_PATH
enable audio hpf error.
```

**Comment by nik0** [comment]
Is it working when logged on the camera ?
What the full script looks like ?

**Comment by Morphy99** [comment]
Yep works when logged in.

#!/bin/sh

```
PATH=/system/sdcard/bin:/system/bin:/bin:/sbin:/usr/bin:/usr/sbin:/sbin:/bin

export LD_LIBRARY_PATH=/system/sdcard/lib:$LD_LIBRARY_PATH

/system/sdcard/bin/audioplay /system/sdcard/Media/doorbell.wav 50
```

**Comment by nik0** [comment]
Tried at home, it is working.
But I think you should do this on your camera
` chmod +x /system/sdcard/config/userscripts/doorbell.sh`

**Comment by Morphy99** [comment]
Thanks got it working now, thought I replied yday. I had to change this path for it to work:
`LD_LIBRARY_PATH=/system/lib`
