### ISSUE TITLE
Local Recorded Videos

### ISSUE THREAD

**Issue by allan37825** [EliasKotlyar/Xiaomi-Dafang-Hacks#560]
Hi,

I am very new to this and need some help with recording videos (motion if possible) locally to SD card.
I have looked through previous issues trying to find a solution, but I am still confused.
- How do I execute avconv? I tried opening in Notepad++, but comes up as ASCII.
- What does Auto Night Mode enable? Is it just IR LED or and IR CUT? What does the measurements mean? 
- Is it possible to remotely take photos?

Thank you.

**Comment by tookus123** [comment]
@allan37825 

Firstly, you should know Dafang Hacks is work in progress and undergoing development every day. Not everything works perfectly yet and recording videos locally is one. It is possible though and it does work. You should familiarize yourself with ssh. This way you can login to the camera directly and run commands like avconv and getimage that will allow you to record video and take image snapshots. 

Here's an example of taking an image snapshot.

`getimage > /system/sdcard/mytestimage.jpg`

And here's a way to record a 10 second video clip

`avconv -rtsp_transport tcp -y -i rtsp://0.0.0.0:8554/unicast -vcodec copy -c:a copy -strict experimental -t 10 /system/sdcard/mytestvideo.mov`

There can still be issues trying to record especially if you're on a Xiaofang 1S. Before trying to record with avconv, disable autorun for recording under Settings and then restart the camera. This post has some tips on video size, audio settings, and username/passwords if you can't get it to record the first time. https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/452

Once you've learned about ssh, you can login from a remote location and  use the getimage command to take an image snapshot.
