### ISSUE TITLE
Power saving by stopping only Camera

### ISSUE THREAD

**Issue by binomie** [EliasKotlyar/Xiaomi-Dafang-Hacks#561]
Hi,

Thanks for all the work. I really like the camera firmware.

Do you have an option to shut down camera mode to save energy. So  camera shall only listen to mqtt until I tell to wake up. But camera and image processing should be stopped.

My use case are multiple surveillance cameras which do not have to run 24/7.

So something like a global switch.

Thanks binomie

**Comment by jmtatsch** [comment]
I don't think you will save so many watts doing that but you can use mqtt to start and stop the rtsp server like "myhome/dafang3/rtsp_h264_server/set ON"

**Comment by binomie** [comment]
Ok, then i will do it like this. Thank you!
