### ISSUE TITLE
Installation of the microSD bootloader not working on Wyze V2

### ISSUE THREAD

**Issue by briodan** [EliasKotlyar/Xiaomi-Dafang-Hacks#564]
Just received my Wyze V2 camera and i'm having issues installing the bootloader.
I'm guessing its because my process might not be correct but i'm not sure where one to follow.

I tried the steps outlined in the main instructions, but they don't seem to work, the camera goes from solid yellow led for 10-12 sec to blinking yellow led and never changes. Waiting 3 minutes unplugging, removing sd card and powering back on does not result in a blue LED, it goes back to solid yellow moving to blinking yellow.

I tried the steps outlined [here](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/292) by ark-git, but the led does not turn blue.

The SD card only has one file named demo.bin which is the 1.1 cfw from the wyze V2 folder.

 Questions i need to figure out:
- do i need to expect a blue LED before releasing the setup button
- is there any indication on Wyze V2 when to remove power? like the clicks?
- how long must one wait after removing power and the SD card to see a blue LED, does this step apply to Wyze

**Comment by pkohut** [comment]
I just went through the process last night for the first time and had similar issues with the lights not acting as mentioned. 

Went ahead and continued with the process here (https://github.com/Dafang-Hacks/Xiaomi-Dafang-Hacks/blob/master/hacks/install_cfw.md#installation-of-the-new-firmware), and deleted demo.bin from the root of the sd card.  Also, edit wpa_supplicant.conf with your SSID and PSK values (case matters on the SSID).  Put sdcard back into camera and powered it on.

The device showed up on my network client list as "IEEE Registration Authority".

After about 30 seconds you can point your web browse to the IP of the camera and interact with it.  The RTSP address can be found in the settings part, copy that address to open a network stream inside VLC (runs very smooth).

**Comment by briodan** [comment]
when you went to delete demo.bin and load the other files did you have a record and time_lapse folder also show up on the SD card?

**Comment by pkohut** [comment]
I deleted those from the sd card as well.

**Comment by pkohut** [comment]
Just reinstalled from scratch and the camera's web server did not appear to be running.  The fix was to ssh into the camera and run ./system/sdcard/autoupdate.sh
Answer yes or all for updating files, then yes for reboot at the end.

**Comment by briodan** [comment]
i went ahead an tried a brand new out of the box SD and it finally worked, the lights doing what they should.
turn blue after ~6 sec while holding the setup button.
then go from yellow to blue with the firmware loaded.
