### ISSUE TITLE
Jpeg images returned by currentpic.cgi unnecessarily big

### ISSUE THREAD

**Issue by hyteoo** [EliasKotlyar/Xiaomi-Dafang-Hacks#565]
Preview image generated in the web UI by currentpic.cgi is 1.4MB with a set resolution of 1600x900
That is very big for a jpeg image, especially for preview purposes.

A jpeg compression of 75% would output a frame of about 200kb without noticeable loss of quality.

A better option would to add a section in the webUI for:
- compression
- webUI preview fps (currently 1/4)

**Comment by nik0** [comment]
I provided a cgi that compress the image:
Try currentpicoptim.cgi instead of currentpic.cgi to get the image. You will use a bit more of CPU

**Comment by DifferentComputers** [comment]
Thanks for this currentpicoptim.cgi, but on my camera the optimized version was 370 Kb, vs the currentpic.cgi which is 395 Kb. It is smaller, but not very small. Even a light optimization with ffmpeg lowers it to about  165 Kb without really harming image quality.

Is there a way to tune the output of currentpicoptim.cgi? Some of us have awful WAN connections with terrible upload speeds.

**Comment by nik0** [comment]
Indeed the currentpic was optimized and the optimized version is obsolete.
You can anyway change this on currentpicoptim.cgi

`/system/sdcard/bin/getimage |  /system/sdcard/bin/jpegtran -progressive -optimize`

in 
`/system/sdcard/bin/getimage |  /system/sdcard/bin/jpegoptim -m50 --stdin --stdout`
And you can change the 50 value (this is a %age)
