### ISSUE TITLE
Motion track not really working

### ISSUE THREAD

**Issue by pixeldublu** [EliasKotlyar/Xiaomi-Dafang-Hacks#567]
Hello,
New here and got a fresh installed dafang camera.
Wanted to activate the motion track but as soon as it senses some motion it rotates backwards and points camera down. 
Fresh and latest install few hours ago.
Is this a known issue ? missing some config ? 

Thanks in advance.

**Comment by nik0** [comment]
What does the log of the video server says ?

**Comment by staudtm** [comment]
Same with my camera. I have mounted my camera top down and thought this is the issue...

**Comment by SiliconAvatar** [comment]
I resubmitted this as [issue #802](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/802) with some new information.

To fix this, temporarily, First you have to change "detectionTracking.sh". You can do this from reading the SDCard externally, or use VI inside SSH; comment out or delete lines 103,104, and 105. This will stop the camer from overwriting the home position. next, SSH into the camera, go to the /tmp/ directory, and run "touch cameraposition" this will create the file that holds the "home" position. Then edit it in VI and type in X: xxxx" and "Y: xxxx: where the 'xxxx' sections hold the coordinates you want the camera to return to. Add a line break between them so the file is 2 lines long, one has the X position and the other the Y. You can find the position you want it to return to by first running the calibration, then centering the camera where you want and either looking at the position on the OSD, or running "/system/sdcard/bin/motor -d s" in the camera SSD command prompt. 

Once you have "detectionTracking.sh" no longer overwriting the position, and have the position file created and entered in the home position, it should work fine. Until it's rebooted, then the tmp directory is deleted. If you want to make this persistent, change line 16 of "detectionTracking.sh" to somewhere inside "/system/sdcard" and create the file there which will hold the home position of the camera.

Hopefully this issue get's resolved the proper way though, so this isnt needed.
