### ISSUE TITLE
Bug in the Video settings web interface

### ISSUE THREAD

**Issue by pulsar123** [EliasKotlyar/Xiaomi-Dafang-Hacks#568]
There seems to be a bug in the software. I downloaded it 2 days ago, and installed it on WyzeCam v2. Any time I try to change some video settings from the web interface (frame rate, quality, resolution), the rtps video quality drops significantly: bandwidth goes down to 0.3 Mps (from 5-10 Mps). I discovered that this creates three new lines at the end of /config/rtspserver.conf :
VIDEOFORMAT=0
USERNAME=
USERPASSWORD=

Once I delete these lines and restart the rtsp server, the quality is restored.

Because of this bug I can't really use web interface to play with video parameters - I have to use ssh and edit them directly in the config files.

**Comment by tookus123** [comment]
Try setting video size to 1280x720, bitrate 5000, video format vbr, and framerate 25 per second, and then click Set. After doing that, the video should be the same quality. Those are actual video settings being used when you first install and run dafang hacks. The video settings displayed on the Settings page aren't actually being used until you click the "Set" button for the first time. I imagine this confusion can be fixed by setting default video size settings in rtspserver.conf to the same values v4l2rtspserver-master uses by default.

**Comment by nik0** [comment]
I don't understand when you get VIDEOFORMAT=0 ?
I added the default value in rtspserver.conf.dist (and it is 2 for CBR)

**Comment by pulsar123** [comment]
The files I got on July 11 didn't have VIDEOFORMAT parameter in the rtspserver.conf file. But any time I try to "Set" video parameters from the browser, I get the three new lines at the bottom of that file, including "VIDEOFORMAT=0". Some web scripts  must be doing something wrong here.

**Comment by tookus123** [comment]
Hello @nik0 , what do you think about setting these two options as the default size in rtspserver.conf.dist? That's the default width and height used by v4l2rtspserver-master during the initial run. When you go to the Settings page for the first time, it's set at 640x360 even though v4l2rtspserver-master is running at 1280x720. 

RTSPH264OPTS="-W1280 -H720" 
RTSPMJPEGOPTS="-W1280 -H720"

**Comment by nik0** [comment]
The default is  indeed 1280x720.
Check the last update of the PR

**Comment by pulsar123** [comment]
Is 1600x900 resolution supposed to work? At 1280x720 my video stream is stable, but at 1600x900 I get lots of artifacts (every second). When I run v4l2rtspserver-master manually,

/system/sdcard/bin/v4l2rtspserver-master -W1600 -H900 -E PCMU:8000:8000 -r 2 -P 8554

I get these errors every second:

MultiFramedRTPSink::afterGettingFrame1(): The input frame data was too large for our buffer size (301380).  48775 bytes of trailing data was dropped!  Correct this by increasing "OutPacketBuffer::maxSize" to at least 348775, *before* creating this 'RTPSink'.  (Current value is 300000.)

Is it possible to recompile the binary with an increased buffer size? In terms of CPU utilization (30% at 1280x720x 25fps) the camera should be able to handle the 1600x900 resolution.

**Comment by nik0** [comment]
Sure this can be easyly fixed.
I will provide you a test version tonight

**Comment by pulsar123** [comment]
I am still getting mpeg artifacts in the video (but no more error messages), so these two were probably unrelated. Things looks better at 128-x720, but still not perfect. It could be the mpeg decoder I am using (iSpy's - likely ffmpeg).

To sort this out, I am playing with different video parameters. FixedQp mode (0) seems to be interesting, but I cannot find a way to change the Qp parameter, and the default one results in a very poor video quality (and very small bandwidth - 0.3 Mbs). Is there a way to change the Qp parameter, without recompiling the code?

I also tried -fMJPG, but I get no video stream - under iSpy, VLC, IPcam PRO, and web interface for the camera. But I do not see anything wrong when running 

/v4l2rtspserver-master -fMJPG -r 2 -P 8554

I get normal audio, but blank video stream. Am I doing something wrong?

Finally, apparently WyzeCam v2 doesn't have a light sensor, so auto night mode doesn't work. The vendor's firmware apparently uses the video stream to measure the illumination level. I wonder if a workaround can be implemented for this camera? If measuring light from the video stream is not possible, then perhaps a sunset/sunrize calculator? I am using the latter in my own smart switch code (Arduino/C++). One could also use mosquitto and get this info from an external computer, but I don't like to rely on other devices for the camera operation.

**Comment by nik0** [comment]
For the Qp parameter, yes I guess you need to recompile the server, no 
I don't know about mjpeg (I don't use it).
For the light detection, I started to implement this (I closed the PR for now, I need to work on the algorithm)
It is based on this: https://stackoverflow.com/questions/7935814/how-to-determine-if-image-is-dark-high-contrast-low-brightness
I compiled imagemagick, and it is working but need to find how to deal with night/day threshold ...

**Comment by pulsar123** [comment]
I did try VLC, both standalone and inside iSpy. In both cases I still get artifacts, but they are different =- instead of random ones I get with ffmpeg, I get strong motion artifacts when something moves. With standalone VLC I get a huge lag (3-4s; with other options it's ~0.5s). Finally, the VLC option under iSpy produces wrong (negative) colors for some reason. So I'm kind of stuck with ffmpeg. With 1280x720 resolution the ffmpeg artifacts are quire rare, so perhaps I can live with this.

Regarding auto night detection with WyzeCam v2 (which has no light sensor): I found a workaround, but it will not work for many I'm afraid. I am already running a MQTT (mosquitto) server on my windows desktop (for my smart home setup), and I programmed [my own smart switches](https://github.com/pulsar123/Smart-light-switch) (for backyard and front porch) which have a sunset calculator, and which turn on at sunset and off at sunrise. Every time they turn on/off, they publish 1 or 0 to the topic lightX/light_state. I just wrote a couple of scripts for my WyzeCam which seem to do the proper job: when my backyard light goes on, the night mode is enabled, when off, it is disabled.

Here are the two scripts:
 -- /system/sdcard/config/autostart/mqtt-run :
#!/bin/sh
/system/sdcard/bin/busybox nohup /system/sdcard/controlscripts/mqtt-nightmode &>/dev/null &

 -- /system/sdcard/controlscripts/mqtt-nightmode
#!/bin/sh
# Should be launched at boot. Monitors mqtt for light2/light_state topic, turns the night mode on/off for the values 1/0
export LD_LIBRARY_PATH='/system/sdcard/lib/:/thirdlib:/system/lib'
export PATH='/system/sdcard/bin:/system/bin:/bin:/sbin:/usr/bin:/usr/sbin'
. /system/sdcard/scripts/common_functions.sh
mosquitto_sub -R -h My_MQTT_host_ip -t light2/light_state | while read RAW_DATA
do
  if test $RAW_DATA -eq 0
    then
    night_mode off
    else
    night_mode on
    fi
done

**Comment by jmtatsch** [comment]
Original Issue seems solved. Please open new issues or participate in ongoing discussions for the other issues.
