### ISSUE TITLE
CO sensors in Camera

### ISSUE THREAD

**Issue by kszere** [EliasKotlyar/Xiaomi-Dafang-Hacks#57]
![capture](https://user-images.githubusercontent.com/7155051/35506028-49562a46-04e8-11e8-9ec6-19d564882595.PNG)
This camera really have CO sensor?
[https://www.gearbest.com/blog/buying-guide/xiaomi-dafang-vs.-xiaomi-xiaofang-what-s-the-differences-2180](https://www.gearbest.com/blog/buying-guide/xiaomi-dafang-vs.-xiaomi-xiaofang-what-s-the-differences-2180)

Edit:
Official site not say's have this camera, but XiaoFang have official.

**Comment by ykaminoh** [comment]
My understanding it's not smoke and CO detection but smoke and CO alarm detection; ie it can be triggered by the sound of your alarms going off but doesn't have any sensors built in and don't do any detection themselves.

**Comment by EliasKotlyar** [comment]
I agree with @ykaminoh. There is no dedicated sensor for CO-Detection
