### ISSUE TITLE
Streaming radio

### ISSUE THREAD

**Issue by s1ngl3player** [EliasKotlyar/Xiaomi-Dafang-Hacks#572]
Is it possible to stream Internetradio to the internal speakers?

**Comment by nik0** [comment]
Theoretically yes ...
But the quality is very poor ... What do you want to do ?

**Comment by s1ngl3player** [comment]
Hi thank you for the fast reply :-)
i know that the quality would be very pour cause the speaker from the
camera is not High End,but as a small Radio it would be very nice.
Is there a binary already compiled, that is be able to decode mp3?
All the best and thank you for your help

nik0 <notifications@github.com> schrieb am So., 15. Juli 2018, 17:59:

**Comment by nik0** [comment]
For now only PCM supported to be played.
I guess it is not a big deal to add MP3 as the MP3 lib is already compiled

**Comment by s1ngl3player** [comment]
Thank you for your fast reply, 
can you give me a little hint how i will be able to play mp3?
Will i have to compile Lame or another decoder?
Thank you for your help

**Comment by nik0** [comment]
Lame lib is already compiled see https://github.com/Dafang-Hacks/Main
You can add MP3 support to this executable: https://github.com/Dafang-Hacks/Audio/tree/392ca0a1c6066b9f0c74ac830e32f9d70e4cdd97/AudioPlay

You will see what are the SDK audio API
