### ISSUE TITLE
Tinycam no audio

### ISSUE THREAD

**Issue by stayingarmed** [EliasKotlyar/Xiaomi-Dafang-Hacks#58]
When clicking the audio button in tinycam, I get an error as pictured below. Is there any fix to allow for use of "push to talk" on this camera?

![screenshot_2018-01-29-19-47-00-1](https://user-images.githubusercontent.com/35941829/35542330-719646d6-052d-11e8-9a8d-e1a1eb71bb9d.png)

**Comment by kszere** [comment]
@EliasKotlyar Can you recompile package with compatible audio format?

**Comment by EliasKotlyar** [comment]
Currently its not possible due to technical reasons - i have no clue how the transfer of audio should work(TinyCam -> Dafang) . Do someone have any idea which transfer-protocol they are using for push-to-talk?

**Comment by msj33** [comment]
On RTSP MJPEG the sound is really bad quality(distorted) from the Dafang microphone when streaming in VLC -  maybe others can confirm this? 

So by fixing that audio/codec/driver bug, 
 it might even fix audio on Tiny cam. (Can confirm here as well, that audio is dead)

**Comment by fia5000** [comment]
@msj33 Sound is bad for me when streaming on VLC on both MJPEG and H264 streams. Not sure why.

**Comment by Psudonico** [comment]
@EliasKotlyar 
What application should I use for push-to-talk ?

**Comment by markwain** [comment]
Any progress on this topic ... having the same problems with audio(no environment audio in TinyCam)?

**Comment by jmtatsch** [comment]
Bad audio is a more general issue. Please try the suggestions in #234.
Closing this for now.
