### ISSUE TITLE
Xiaofang 1S new Bootloader - Issue from @paumove

### ISSUE THREAD

**Issue by EliasKotlyar** [EliasKotlyar/Xiaomi-Dafang-Hacks#581]

**Comment by EliasKotlyar** [comment]
Hello @paumove,

Your microsd is not being recognized. I had a similar issue on the dafang. I also see that you have a serial header attached, and it should be easy to recover. Just do following:
1. Boot into u-boot and stop the booting by pressing a button
2. Run "mmc rescan". It should return a error.
3. Check your bootlog - there were some pins set on / off during the boot. After that your microsd was recognized again.
4. Set this pins on/off with following command:
gpio set <pinvalue>
gpio clear <pinvalue>
5. Try the command "mmc rescan" again. If it returns no error, you can boot info dafanghacks. 
6. Please try to find out, which pins are responsible for the mmc card. As soon as you know it, i can make a new version which will enable them by default.

**Comment by paumove** [comment]
Sorry, I don't know how to do steps 3 & 4. This is what I do:

U-Boot 2013.07 DafangHacksV1.3-g96a42d5-dirty (Jul 16 2018 - 22:15:12)

Board: ISVP (Ingenic XBurst T20 SoC)
DRAM:  64 MiB
Top of RAM usable for U-Boot at: 84000000
Reserving 419k for U-Boot at: 83f94000
Reserving 32784k for malloc() at: 81f90000
Reserving 32 Bytes for Board Info at: 81f8ffe0
Reserving 124 Bytes for Global Data at: 81f8ff64
Reserving 128k for boot params() at: 81f6ff64
Stack Pointer at: 81f6ff48
Now running in RAM - U-Boot at: 83f94000
MMC:   msc: 0
the manufacturer c8
SF: Detected GD25Q128

*** Warning - bad CRC, using default environment

In:    serial
Out:   serial
Err:   serial
Setting yellow_gpio to off:
gpio_request lable = cmd_gpio gpio = 38
gpio: pin 38 (gpio 38) value is 1
Setting blue_gpio to off:
gpio_request lable = cmd_gpio gpio = 39
gpio: pin 39 (gpio 39) value is 1
Setting night_gpios:
gpio_request lable = cmd_gpio gpio = 81
gpio: pin 81 (gpio 81) value is 0
gpio_request lable = cmd_gpio gpio = 49
gpio: pin 49 (gpio 49) value is 0
gpio_request lable = cmd_gpio gpio = 25
gpio: pin 25 (gpio 25) value is 0
Setting USB enable:
gpio_request lable = cmd_gpio gpio = 47
gpio: pin 47 (gpio 47) value is 1
Setting Speaker enable:
gpio_request lable = cmd_gpio gpio = 63
gpio: pin 63 (gpio 63) value is 1
Setting Enable SDCARD:
gpio_request lable = cmd_gpio gpio = 43
gpio: pin 43 (gpio 43) value is 1
gpio_request lable = cmd_gpio gpio = 48
gpio: pin 48 (gpio 48) value is 0
Running SDupdate....
Interface:  MMC
  Device 0: Vendor: Man 000002 Snr 0926af00 Rev: 0.0 Prod: SB08G
            Type: Removable Hard Disk
            Capacity: 7384.0 MB = 7.2 GB (15122432 x 512)
Filesystem: FAT16 "NO NAME    "
the manufacturer c8
SF: Detected GD25Q128

reading flash-uboot.bin
reading flash-kernel.bin
reading flash-rootfs.bin
reading flash-full.bin
Hit any key to stop autoboot:  0
U-Boot> mmc rescan
U-Boot>

**Comment by paumove** [comment]
U-Boot> fatload mmc 0:1 0x80600000 uEnv.txt
reading uEnv.txt
** Unable to read file uEnv.txt **

**Comment by EliasKotlyar** [comment]
Hm ok. That seems very strange. You SDcard is being recognized, but it cannot read your filesystem. Can you try to reformat it to FAT16? I had a similar issue before. 
Another hint: You can try to reformat your whole partition to EXT3. The bootloader is capable of reading an uEnv.txt from an EXT3 partition.

**Comment by paumove** [comment]
So here is the result with only one EXT3 partition and using the current rootfs content.

> Running SDupdate....
> sdupdate - auto upgrade file from mmc to flash
> 
> Usage:
> sdupdate LOAD_ID ADDR_START ADDR_END
> LOAD_ID: 0-->u-boot
>          1-->kernel
>          2-->rootfs
>          3-->demo.bin
> ex:
>         sdupdate   (update all)
> or
>         sdupdate 0 0x0 0x40000
> Hit any key to stop autoboot:  0
> ** Unrecognized filesystem type **
> 576 bytes read in 26 ms (21.5 KiB/s)
> Booting from microsd ...
> gpio_request lable = cmd_gpio gpio = 39
> gpio: pin 39 (gpio 39) value is 0
> 1709592 bytes read in 119 ms (13.7 MiB/s)
> ## Booting kernel from Legacy Image at 80600000 ...
>    Image Name:   Linux-3.10.14
>    Image Type:   MIPS Linux Kernel Image (lzma compressed)
>    Data Size:    1709528 Bytes = 1.6 MiB
>    Load Address: 80010000
>    Entry Point:  803b3f00
>    Verifying Checksum ... OK
>    Uncompressing Kernel Image ... OK

Maybe it don't like some command refering ext3 or ext4 filesystem type on the uEnv file.

Finally I get an error:

> [    1.441244] Waiting for root device /dev/mmcblk0p2...
> [    1.790117] dwc2 dwc2:  ++OTG Interrupt: A-Device Timeout Change++

**Comment by EliasKotlyar** [comment]
If you have only one partition with EXT3:
Can you change "root=/dev/mmcblk0p2" to "root=/dev/mmcblk0p1" in your uEnv.txt? There may be an error here.

**Comment by paumove** [comment]
I have tested it with no success.

Now I have an sdcard with FAT32+EXT4. In the FAT32 I have the uEnv & kernel.bin and in EXT4 the rootfs. 
Boots kernel but finally gets "Waiting for root device /dev/mmcblk0p2..."

**Comment by EliasKotlyar** [comment]
The U-Boot and/or Kernel have some issues with EXT4. Dont try to use EXT4 - use EXT3 instead. I suppose that there are some errors related to the GPIOs. The kernel does not recognize the SDCard and dont want to boot it. A similar issue appears on the original kernel - it recognizes the SDCard, but at a really late stage.

**Comment by paumove** [comment]
Log using only one EXT3 partition and current rootfs (with today's last commit). Same result.

[boot.log](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/files/2209748/boot.log)

**Comment by EliasKotlyar** [comment]
@paumove : Yes, i will try to fix it. But i will need your help, because i cannot fix this without having this piece of hardware here.

**Comment by paumove** [comment]
@EliasKotlyar No problem. I will tests asap what you need.

**Comment by EliasKotlyar** [comment]
Ok i have an idea, try this:
1. Format Card to EXT3. 
2. Put the rootfs to EXT3. (ensure that you are using latest commit with new uEnv.txt)
3. Boot into "u-boot". Press any key to stop the boot process
4. Run in uboot:
```
gpio clear 46
gpio clear 25
gpio clear 26
gpio clear 38
gpio clear 39
gpio clear 49
gpio clear 47
gpio clear 48
gpio clear 43
gpio clear 30
boot
```
5. It should start booting. Post the boot-logs here.

**Comment by paumove** [comment]
Boot result. [boot.log](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/files/2209906/boot.log)

(In case of doubts, I have only one EXT3 partition on sdcard)

**Comment by EliasKotlyar** [comment]
This is looking really really good- with this pins set, its recognizing the microsd again.  Can you try to find out which Pin is responsible for this good boot result? You should just start with:
1. Boot into u-boot
2. Run 
```
gpio clear <pin> (from the list above)
boot
```
3. Look if its stuck at "Waiting for root device /dev/mmcblk0p1...". If so, try another pin. As soon as you have found out which pin is responsible, report it here. I will make a new bootloader which will enable that for you,so you don`t have to do it manually.

Next Steps:
I have changed the uEnv to boot from EXT3. Please checkout the latest commit from rootfs. Its already booting into the new rootfs.

**Comment by paumove** [comment]
Uboot says:

> Setting Enable SDCARD:
> gpio_request lable = cmd_gpio gpio = 43
> gpio: pin 43 (gpio 43) value is 1

So I have tested first to clear the gpio 43 and voila! Passing the "waiting" message! 👍 

I have changed the rootfstype to ext3 but I still get the same error like last posted boot.log...

> [  140.580481] EXT4-fs error (device mmcblk0p1): ext4_lookup:1437: inode #2: comm linuxrc: deleted inode referenced: 8161
> [  140.594014] EXT4-fs error (device mmcblk0p1): ext4_lookup:1437: inode #2: comm linuxrc: deleted inode referenced: 8161
> can't open /dev/console: Input/output error
> [  141.608085] EXT4-fs error (device mmcblk0p1): ext4_lookup:1437: inode #2: comm linuxrc: deleted inode referenced: 8161

**Comment by EliasKotlyar** [comment]
Okey, the Dafang needs the Pin to be set, but XioaFang 1S needs to have it cleared. Will create different bootloaders for the different devices...

Can you check your SDCard for errors? I have googled this error up, and it seems that the partition is somehow broken. Look here:
https://unix.stackexchange.com/questions/191370/ext4-lookup-deleted-inode-referenced-error-in-var-log-messages

**Comment by paumove** [comment]
@EliasKotlyar, you were right, it was due to problems with the card. I have started again from zero and I have added the "gpio clear 43" command temporarily to the "bootcmd" line of uEnv.txt so I do not have to do it every time. It seems that there are other problems. There is the log.
[boot.log](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/files/2211863/boot.log)

**Comment by GSzabados** [comment]
Gents,
Please excuse me for hijacking this thread, but I managed to brick my 1S (with the jxf23 and 64 MB ram) by flashing an original Dafang uboot. It doesn't boot since that, not even to the original (no amber nor blue LED at all). Which way should I try to recover? Straight the chip off and reprogram or with an FTDI? Does any of you have the original firmware for the 1S what I can try to restore, or any other solution still in progress?
(The main issue, where I've got side tracked, that the motion detection is not triggering correctly the script and does nothing, but the red circle on the video. So, I wanted to increase the available memory from the original 32 MB, and misread the content of another issue. Bummer... I ended up flashin the wrong uboot.)
I am about to order a CH341A programmer, but if it would work with the FTDI, then I will proceed with that. The issue is fresh, I managed to do it a few hours ago.
Thanks for any feedback and suggestion!

**Comment by jmtatsch** [comment]
@paumove your camera needs a different wifi driver and camera sensor driver which aren’t in the rootfs yet.

**Comment by EliasKotlyar** [comment]
@GSzabados : You can try to solder the FTDI first, but i suppose that you have hardbricked it and it wont help much. Buy an CH341 and solder the chip out. You can find the original firmware for a Xiaofang 1S here:
https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/tree/master/firmware_original/xiaofang/5.6.2.43

@jmtatsch  You are right. I suppose that the Xiaofang 1S needs a jxf23 sensor driver. Which Wifi driver is needed? 8189fs or 8189ftv? Maybe we can try to include the binarys from the flash?

@paumove : Do you have a USB-Wifi Adapter? Preferably a RaLink or RTL8187? It would be easier to connect the camera to WIFI via USB  first, and then try to make the internal WIFI work.

**Comment by jmtatsch** [comment]
@EliasKotlyar  
8189es.ko for dafang
8189fs.ko for xiaofang
rtl8189ftv.ko for wyzecam v2
can't we enable them in the kernel build configuration and transfer to the rootfs? the sensor_jxf23.ko we could extract from a xiaofang firmware file?

**Comment by paumove** [comment]
I was previously using the camera through RTSP and WiFi with the method demo.bin + firmware_mod folder. They are related?

As you mention, this camera uses the jxf23 sensor driver as I saw in the logs.

I think I have an USB WiFi, I can try what you need.

**Comment by jmtatsch** [comment]
@paumove can you try my pullrequest https://github.com/Dafang-Hacks/rootfs/pull/1 and in the rcfile comment the Dafang driver and uncomment the xiaofang driver...

**Comment by paumove** [comment]
@jmtatsch Ok, I will try your pull asap and I tell you the result. Thanks!

**Comment by EliasKotlyar** [comment]
@paumove : I have added a new kernel driver for the wifi module which was compiled from scratch. I hope it will work for you.

You can also try to flash a new bootloader which was compiled specially for the 1s, which will disable the GPIO43 before booting:
https://github.com/Dafang-Hacks/uboot/tree/master/compiled_bootloader

**Comment by paumove** [comment]
@EliasKotlyar  worked! And video working through VLC. Finally I have obtained a kernel panic and the camera has been restarted. You can see it at the end of the log.
[boot.log](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/files/2218783/boot.log)

Another thing... In website, there is no image ("Unable to load image"), all camera controls are OFF and services section throws "No scripts.cgi found in /system/sdcard/controlscripts/"

**Comment by EliasKotlyar** [comment]
Thats very good - i will compile a new version of the bootloader which will have this code inside it.

About your kernel panic: Can you please deactivate the motor driver? I suppose that its causing this problem. Its not supposed to be there anyway, because your camera has no motors inside.

About the webcontrol-panel: It needs some refactoring - many things are not working as expected. I suppose that it will happen as soon as we get everyone to the new firmware variant.

**Comment by paumove** [comment]
> Thats very good - i will compile a new version of the bootloader which will have this code inside it.

Ok. When you can have it, I test it.

> About your kernel panic: Can you please deactivate the motor driver? I suppose that its causing this problem. Its not supposed to be there anyway, because your camera has no motors inside.

I do it by commenting on the following line on /etc/init.d/rcS?
`insmod /lib/modules/$KERNEL_VERSION/sample_motor.ko`

> About the webcontrol-panel: It needs some refactoring - many things are not working as expected. I suppose that it will happen as soon as we get everyone to the new firmware variant.

No problem ;)

Thanks so much

**Comment by EliasKotlyar** [comment]
>I do it by commenting on the following line on /etc/init.d/rcS?
>insmod /lib/modules/$KERNEL_VERSION/sample_motor.ko
Yes

**Comment by GSzabados** [comment]
@EliasKotlyar : Thanks! I've just had a little time time and did the solder for the FTDI, and as you said, it doesn't really help. The U-Boot starts, but stops at this point, and I cannot do anything there, I need to wait to get the SPI programmer.

```
U-Boot SPL 2013.07 (Jul 28 2017 - 17:10:01)
pll_init:365
l2cache_clk = 375000000
pll_cfg.pdiv = 8, pll_cfg.h2div = 4, pll_cfg.h0div = 4, pll_cfg.cdiv = 1, pll_cfg.l2div = 3
nf=36 nr = 1 od0 = 1 od1 = 1
cppcr is 02404900
CPM_CPAPCR 0470890d
nf=42 nr = 1 od0 = 1 od1 = 1
cppcr is 02a04900
CPM_CPMPCR 07d0c90d
nf=50 nr = 1 od0 = 1 od1 = 1
cppcr is 03204900
CPM_CPVPCR 0320490d
cppcr 0x9a794410
apll_freq 860160000
mpll_freq 1000000000
vpll_freq = 1200000000
ddr sel mpll, cpu sel apll
ddrfreq 500000000
cclk  860160000
l2clk 286720000
h0clk 250000000
h2clk 250000000
pclk  125000000
DDRC_DLP:0000f003

```  

Have you tried this, before you have de-soldered the chip for re-flashing? What was the reason, you needed to de-solder?

> How-to: Asserting HOLD# on the flash chip caused the bootloader to crash, so the flash-reader had the SPI bus all to itself after that. Powered via the USB connector, not the flash programmer. (Of course making sure the programmer’s 3v3 wasn’t connected to the chip.)

I've found it on the Digoo BB M2 camera hacking site: https://nm-projects.de/2017/01/hacking-ip-camera-digoo-bb-m2-part-3-getting-root-access/

**Comment by EliasKotlyar** [comment]
@GSzabados : I have tried to flash it using a clip-adapter first. It was not working at all, the chip was sometimes recognized, but was not flashed correctly. Then i have soldered some connections to the chip, and still was unable to flash it. So i decided to desolder it, because i was thinking that i had destroyed the chip with my various attemps. After desoldering, i have soldered it to the pcb-adapter which was delivered with my CH341. And then everything started working again, i was able to recover it very fast. Afterwards i was really lazy and has soldered back only the cables which were necessery for flashing. I left the nand flash on this pcb adapter to flash it again in emergency :)

See pictures here : https://github.com/Dafang-Hacks/spiflasher

**Comment by EliasKotlyar** [comment]
@paumove : I have uploaded a new bootloader for your cam. It can be found here:
https://github.com/Dafang-Hacks/uboot/tree/master/compiled_bootloader

I hope it will finally get a stable boot.

**Comment by paumove** [comment]
Boot working correctly!! 👍 

Thanks!
