### ISSUE TITLE
Sound detection

### ISSUE THREAD

**Issue by gostaj** [EliasKotlyar/Xiaomi-Dafang-Hacks#583]
Would it be possible to detect sound with the microphone just like the camera can detect motion?
Saving audio files in a directory when something was "heard" based on thresholds and max recording time?

Has anyone tried this?

Perhaps it could be achieved with something like the *sox* audio utility using the *rec* and *silence* commands?
http://sox.sourceforge.net/sox.html

An example is shown there:
```rec −r 44100 −b 16 −e signed-integer −p \  
     silence 1 0.50 0.1% 1 10:00 0.1% | \
     sox −p song.ogg silence 1 0.50 0.1% 1 2.0 0.1% : \
     newfile : restart
```

> records a stream of audio such as LP/cassette and splits in to multiple audio files at points with 2 seconds of silence. Also, it does not start recording until it detects audio is playing and stops after it sees 10 minutes of silence.

**Comment by vashbreak** [comment]
Like baby crying detection at official mi app?

**Comment by gostaj** [comment]
I haven't used the official MI app but yes, that sounds correct.

**Comment by ravensteijn** [comment]
I would like that. I tried to use the ffmpeg audio noise sensor from home assistant. But it wouldn't work. https://www.home-assistant.io/components/binary_sensor.ffmpeg_noise/

**Comment by PasteurPT** [comment]
Do you have news about this feature? I just want to detect sound and make an action.

**Comment by thepuncake** [comment]
Any follow up on this?
