### ISSUE TITLE
Motion sensitivity documentation

### ISSUE THREAD

**Issue by gostaj** [EliasKotlyar/Xiaomi-Dafang-Hacks#584]
I've been trying to reverse engineer where the motion sensitivity integer (-1 - 4 in the GUI) is actually used. I saw that it ended up in some *sense* array in `Xiaomi-Dafang-Software/v4l2rtspserver-master/src/ImpEncoder.cpp` but I have no clue where that value is used.

Is the value passed along to `minimum_motion_frames`in the *Motion* project?
https://motion-project.github.io/motion_config.html#minimum_motion_frames

I think it would be good to know what the number actually stands for and if a higher value means higher sensitivity (which would be logical) or if it's the other way around.
Experimenting with the values did not give any answer to the question for me (motion was sensed often using both 1 and 4).

Thanks a lot for the project and thanks for any help!

**Comment by nik0** [comment]
Hi,
The value are not related at all to motion project.
This is the camera SDK value, and unfortunately it is not well documented. But 4 is the highest sensitivity and -1 is to deactivate the detection
regards,
Nik0

**Comment by jmtatsch** [comment]
Question answered and interface improved.
