### ISSUE TITLE
timezone settings

### ISSUE THREAD

**Issue by mo8Zomo0** [EliasKotlyar/Xiaomi-Dafang-Hacks#586]
Hi!

It looks to me that there is something wrong with the timezone setting.

First of all it seems to be adding / subtracting in the wrong direction.

Like here for Norway it should be currently UTC+2 but to get the correct time shown UTC-2:00 needs to be entered.

![timezone setting screen shot 2018-07-20 at 12 33 17](https://user-images.githubusercontent.com/2004752/42998084-409e9de4-8c19-11e8-85f1-c3e3f07f830c.png)

further
* auto daylight savings should be present 
* support for other named time zones, like CET or Europe/Oslo should be available

**Comment by nik0** [comment]
Did you check this: https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/95 or this https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/423 ?

**Comment by mo8Zomo0** [comment]
Hi @nik0,

yes, both look related, when I searched for timezone I did not find them, thank you.

That said, both are closed and the bug is still present.

**Comment by mo8Zomo0** [comment]
Ah, yes, that makes sense, maybe it would be handy to have a wiki with the hints to the parameters and their meaning, an online help on the dafang page itself or as written above a menu based version so people do not have to interact with the TZ syntax.

Btw, for CE(S)T it seems to be (/ it works for me): CET-1CEST,M3.5.0,M10.5.0/3
