### ISSUE TITLE
bootloader installation problem

### ISSUE THREAD

**Issue by Nijisakai** [EliasKotlyar/Xiaomi-Dafang-Hacks#587]
I use a DaFang Camera 
I keep holding down the setup button after the sd care into camera ,
the i plug the power while holding down the setup button.
At Step 7，Keep setup button down for another 10 seconds
**After 10 seconds , the base start moving itself.**
And after 3-10 minutes, the camera keeps yellow blink quickly and i go on step but no blue light.
Where did i went wrong?

**Comment by Nijisakai** [comment]
switch from a 16g to 8g sd card, and all went well

**Comment by Tramsrepus** [comment]
I have the same problems. I think... But i get a blue light for about 5 seconds and then it blink yellow for a few seconds before it moves? Is that how it should be?

**Comment by reikred** [comment]
Follow up: I managed to scrunge up a **2**GB micro-sdcard, made one big **2**GB (2GB) partition and created a FAT filesystem on it. THEN installation of the boot loader worked.
