### ISSUE TITLE
how to add night_mode in crontab

### ISSUE THREAD

**Issue by LuminousPickle** [EliasKotlyar/Xiaomi-Dafang-Hacks#588]
Hi All,

Thanks all for your hard work on these hacks. I have 3 Xiaofang 1S's up and running with Dafang-Hacks. Also have 3 of the older Xiaofangs running samtap's hacks. As it seems the daylight sensor doesn't seem to work, I was wanting to add /system/sdcard/scripts/nightmode.sh to crontab to turn on at 18:00 and off at 06:00 but cannot figure out how to add it correctly.

I am typing "crontab -c /system/sdcard/config/cron/crontabs -e" but not quite sure how to format the command string for on and off. Every thing i have tried doesn't seem to do anything.

Thanks!

**Comment by saipsa** [comment]
add this at the end of the file. 
```
0      18      *       *       *       /system/sdcard/scripts/nightmode.sh on
0       6       *       *       *       /system/sdcard/scripts/nightmode.sh off

```

**Comment by LuminousPickle** [comment]
Thanks @saipsa i will give that a try over the weekend.

**Comment by ortegafernando** [comment]
PLease, check this:
[https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/pull/739](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/pull/739)

It works perfect !!! 

@jmtatsch  could close this.
