### ISSUE TITLE
Won't boot after Bootloader flash.

### ISSUE THREAD

**Issue by buliwyf42** [EliasKotlyar/Xiaomi-Dafang-Hacks#589]
Hello,

today i tried to flash the bootloader, which seemed to have worked.
But now the camera won't boot

`
root@192.168.203.129's password:
[root@cam:~]# cat /proc/cmdline
console=ttyS1,115200n8 mem=41700K@0x0 ispmem=8M@0x28B9000 rmem=15644K@0x30B9000 init=/linuxrc rootfstype=squashfs root=/dev/mtdblock2 rw mtdparts=jz_sfc:256k(boot),2048k(kernel),3392k(root),640k(driver),4736k(appfs),2048k(backupk),640k(backupd),2048k(backupa),256k(config),256k(para),-(flag)
[root@cam-ebel-hedy:~]# wget https://github.com/Dafang-Hacks/kernel_release/blob/master/uboot/opensource-T20-V1.3-64MB.bin
Connecting to github.com (192.30.253.112:443)
opensource-T20-V1.3- 100% |**********************************************************************************************************************************************************************************************************************************************************************************************************************| 41064  0:00:00 ETA
[root@cam:~]# flash_eraseall /dev/mtd0
Erasing 32 Kibyte @ 40000 - 100% complete.
[root@cam:~]# dd if=opensource-T20-V1.3-64MB.bin of=/dev/mtd0
80+1 records in
80+1 records out
41064 bytes (40.1KB) copied, 0.271973 seconds, 147.4KB/s`

I think i have chosen the correct bootloader.
I think i did nothing wrong, but it seems i have bricked the device.

**Comment by jmtatsch** [comment]
I don’t think you can wget it like that, you will get a html file. You need to wget the raw binary.

**Comment by buliwyf42** [comment]
You are probably right. Stupid me. :( so now i have a a fancy paperweight.

Time to heat the soldering iron.
