### ISSUE TITLE
Please post a normal output log

### ISSUE THREAD

**Issue by bloodybeet** [EliasKotlyar/Xiaomi-Dafang-Hacks#591]
Hi there! I'm deep into trying to set up my DaFang which still isn't connecting to my wifi network. I'm currently trying to set static IP's, but I'm actually not even sure if that's where the issue is. 2 questions:

- should we only strictly copy/paste the 4 folders and 1 file described in the tutorial, or is this tutorial outdated and should be simply copy everything inside the source control's firmware_mod folder?
- can someone post a proper, working output log, so I can do some more troubleshooting myself? Here is my log, and it shows some errors, but I'm unsure if they're expected or not. Perhaps it's a good idea to add a "correct working output log" to the tutorial page 😄 

Loaded common functions
Created root user home directory
Created etc directory on sdcard
Bind mounted /system/sdcard/bin/busybox to /bin/busybox
Bind mounted /system/sdcard/root to /root
Bind mounted /system/sdcard/etc to /etc
Created cron directories and standard interval jobs
wpa_supplicant: Successfully initialized wpa_supplicant
rfkill: Cannot open RFKILL control device
nl80211: Could not re-add multicast membership for vendor events: -2 (No such file or directory)
udhcpc:
Initialized gpios
Determined image sensor model as
dropbear:
bftpd:
Created new certificate for webserver
lighttpd:
Startup finished!

**Comment by jmtatsch** [comment]
Tutorial is probably outdated. Copy everything inside firmware_mod to your sd card root.

**Comment by jmtatsch** [comment]
A successful startup could look like that:

```
==================================================
Starting the Dafang Hacks Custom Application Layer
==================================================
Loaded common functions
Created etc directory on sdcard
Bind mounted /system/sdcard/root to /root
Bind mounted /system/sdcard/etc to /etc
Created cron directory
wpa_supplicant: Successfully initialized wpa_supplicant
rfkill: Cannot open RFKILL control device
nl80211: Could not re-add multicast membership for vendor events: -2 (No such file or directory)
udhcpc: udhcpc (v1.22.1) started
Sending discover...
Sending discover...
Sending select for 192.168.181.45...
Lease of 192.168.181.45 obtained, lease time 2592000
deleting routers
adding dns 192.168.181.22
Initialized gpios
Determined image sensor model as jxf22
dropbear: 
bftpd: 
lighttpd: 
Startup finished!
```

**Comment by bloodybeet** [comment]
So I still wonder why my udhcpc step isn't outputting anything at all. Right now, I'm trying to bypass that step by setting a static IP using:

killall udhcpc
ifconfig wlan0 192.168.1.100 netmask 255.255.255.0
route add default gw 192.168.1.1
echo "nameserver 192.168.1.1" > /tmp/resolv.conf

Printing ifconfig in between shows me:

IFCONFIG START
lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

wlan0     Link encap:Ethernet  HWaddr 78:11:DC:44:CA:42  
          inet addr:192.168.1.100  Bcast:192.168.1.255  Mask:255.255.255.0
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)


IFCONFIG END

But still, nothing shows up on my router and it looks like the device still isn't joining my network. As if the network credentials would be wrong (checked 500 times and dos2unix'd the file 100 times). I tried the more simplified version:

ctrl_interface=/var/run/wpa_supplicant
ctrl_interface_group=0
ap_scan=1

network={
	ssid="plaintext"
	psk="plaintext"
  key_mgmt=WPA-PSK
}

But there must be some reason why it still can't join. Could it be that I have a new/special kind of device? How do I figure out? The CMIIT ID on the back says 2017DP3894

**Comment by bloodybeet** [comment]
The documentation for udhcpc says:

`-b, --background                Fork to background if lease cannot be immediately negotiated.`

Removing this -b parameter from the cmd, makes my Dafang stay in orange state forever and it will hang indefinitely on the udhcpc command. So where do I go from here?

**Comment by bloodybeet** [comment]
Sorry for spamming my own thread, I think i'm getting somewhere. So I tried a version from 05/05/2018 and now got the following output:

```
udhcpc: udhcpc (v1.22.1) started
Sending discover...
Sending discover...
Sending discover...
No lease, forking to background
initialized gpios
dropbear: 
bftpd: 
lighttpd: 
Startup finished!
```

So what could be the reason that my router isn't properly responding to the IP request. Does this mean the wpa_applicant still isn't correct, or does it mean my router has some weird setting (it's just a standard AC68U).

**Comment by jmtatsch** [comment]
For me that still looks like messed up line endings in wps supplicant conf. Can’t you edit the file on a Mac or Linux? Do you have unusual characters in your ssid/ password? Try to log more information from wpa supplicant, maybe it has a verbose mode?

**Comment by Dopeyr** [comment]
@bloodybeet Just one thought, is the SSID on your router hidden?

**Comment by bloodybeet** [comment]
Thanks to be involved guys - keeps me going and not give up :-)
So I am now carefully editing files through a Docker volume mount on ubuntu. Never open/edit/save on Windows, only copy/paste.
- The SSID is not hidden, but I did already try to toggle the scan parameter
- The password is just a normal word, no special characters
- When adding more debug traces to wpa_supplication, I get the following output:

Loaded common functions
Created etc directory on sdcard
Bind mounted /system/sdcard/bin/busybox to /bin/busybox
Bind mounted /system/sdcard/root to /root
Bind mounted /system/sdcard/etc to /etc
wpa_supplicant: wpa_supplicant v2.5
random: Trying to read entropy from /dev/random
Successfully initialized wpa_supplicant
Initializing interface 'wlan0' conf '/system/sdcard/config/wpa_supplicant.conf' driver 'default' ctrl_interface 'N/A' bridge 'N/A'
Configuration file '/system/sdcard/config/wpa_supplicant.conf' -> '/system/sdcard/config/wpa_supplicant.conf'
Reading configuration file '/system/sdcard/config/wpa_supplicant.conf'
ctrl_interface='/var/run/wpa_supplicant'
ctrl_interface_group='0'
ap_scan=1
Line: 8 - start of a new network block
ssid - hexdump_ascii(len=7):
     42 61 4b 61 42 6f 78                              BaKaBox         
key_mgmt: 0x2
pairwise: 0x18
group: 0x18
PSK (ASCII passphrase) - hexdump_ascii(len=12):
     [redacted]               [redacted]
priority=1 (0x1)
PSK (from passphrase) - hexdump(len=32): [redacted]
Priority group 1
   id=0 ssid='BaKaBox'
nl80211: Could not add multicast membership for vendor events: -2 (No such file or directory)
rfkill: Cannot open RFKILL control device
nl80211: RFKILL status not available
nl80211: Supported cipher 00-0f-ac:1
nl80211: Supported cipher 00-0f-ac:5
nl80211: Supported cipher 00-0f-ac:2
nl80211: Supported cipher 00-0f-ac:4
nl80211: Using driver-based off-channel TX
nl80211: Disable use_monitor with device_ap_sme since no monitor mode support detected
nl80211: interface wlan0 in phy phy0
nl80211: Set mode ifindex 2 iftype 2 (STATION)
nl80211: Subscribe to mgmt frames with non-AP handle 0x55c248
nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x55c248 match=06
nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x55c248 match=0a07
nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x55c248 match=0a11
nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x55c248 match=1101
nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x55c248 match=1102
nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x55c248 match=0505
netlink: Operstate: ifindex=2 linkmode=1 (userspace-control), operstate=5 (IF_OPER_DORMANT)
nl80211: Could not re-add multicast membership for vendor events: -2 (No such file or directory)
nl80211: driver param='(null)'
Add interface wlan0 to a new radio phy0
nl80211: Regulatory information - country=00
nl80211: 2402-2472 @ 40 MHz 20 mBm
nl80211: 2457-2482 @ 40 MHz 20 mBm (no IR)
nl80211: 2474-2494 @ 20 MHz 20 mBm (no OFDM) (no IR)
nl80211: 5170-5250 @ 80 MHz 20 mBm (no IR)
nl80211: 5735-5835 @ 80 MHz 20 mBm (no IR)
nl80211: 57240-63720 @ 2160 MHz 0 mBm
nl80211: Added 802.11b mode based on 802.11g information
wlan0: Own MAC address: 78:11:dc:44:ca:42
wpa_driver_nl80211_set_key: ifindex=2 (wlan0) alg=0 addr=(nil) key_idx=0 set_tx=0 seq_len=0 key_len=0
wpa_driver_nl80211_set_key: ifindex=2 (wlan0) alg=0 addr=(nil) key_idx=1 set_tx=0 seq_len=0 key_len=0
wpa_driver_nl80211_set_key: ifindex=2 (wlan0) alg=0 addr=(nil) key_idx=2 set_tx=0 seq_len=0 key_len=0
wpa_driver_nl80211_set_key: ifindex=2 (wlan0) alg=0 addr=(nil) key_idx=3 set_tx=0 seq_len=0 key_len=0
wlan0: RSN: flushing PMKID list in the driver
nl80211: Flush PMKIDs
wlan0: Setting scan request: 0.100000 sec
ENGINE: Loading dynamic engine
ENGINE: Loading dynamic engine
EAPOL: SUPP_PAE entering state DISCONNECTED
EAPOL: Supplicant port status: Unauthorized
nl80211: Skip set_supp_port(unauthorized) while not associated
EAPOL: KEY_RX entering state NO_KEY_RECEIVE
EAPOL: SUPP_BE entering state INITIALIZE
EAP: EAP entering state DISABLED
ctrl_interface_group=0
wlan0: Added interface wlan0
wlan0: State: DISCONNECTED -> DISCONNECTED
nl80211: Set wlan0 operstate 0->0 (DORMANT)
netlink: Operstate: ifindex=2 linkmode=-1 (no change), operstate=5 (IF_OPER_DORMANT)
Daemonize..

**Comment by jmtatsch** [comment]
Seems like your router could be the problem. Do you have a raspi that connects just fine? Try different wpa modes and ciphers on your access point.

**Comment by ineedit91** [comment]
@bloodybeet Your problem seems very similar to mine, as @jmtatsch has already pointed out. Maybe my solution will work for you aswell. Take a look at #642

**Comment by PedroSilv4** [comment]
So, I have the same problem after, I set up a bridge on a VM on my raspberry pi
