### ISSUE TITLE
Will FullHD only work with the new bootloader?

### ISSUE THREAD

**Issue by Tramsrepus** [EliasKotlyar/Xiaomi-Dafang-Hacks#594]
Hi,

Maybe a dumb questin, But will this hack only work at FHD resolution with the new (beta?) bootloader? I read something about it in the FAQ. What is the default resolution otherwise? My cams are all 1080P

New Bootloader - Testers needed #573

**Comment by hcgonzalezpr** [comment]
Depends on device model, at the moment only devices with 128mb of ram can do 1080p with the bootloader. 

Witch device model do you own?

**Comment by Tramsrepus** [comment]
@hcgonzalezpr  Hi and thanks for a quick response. 

How can i tell? The back on the Dafang says DF3 and 1080P

How to tell if, on my XiaoFang 1080P?

**Comment by jmtatsch** [comment]
You will need to install the hack and have a look at your cmdline

```
cat /proc/cmdline 
console=ttyS1,115200n8 mem=104M@0x0 ispmem=8M@0x6800000 rmem=16M@0x7000000 init=/linuxrc root=/dev/mmcblk0p2 rootwait rootfstype=ext4 rw mtdparts=jz_sfc:256k(boot),2048k(kernel),3392k(root),640k(driver),4736k(appfs),2048k(backupk),640k(backupd),2048k(backupa),256k(config),256k(para),-(flag)
```

Then just count all the mem variables together. mem + ispmem + rmem = Its 128Mb

**Comment by Tramsrepus** [comment]
It is installed already. Where do i find this "CMDLINE"

**Comment by jmtatsch** [comment]
Ssh to the camera then cat /proc/cmdline

**Comment by Tramsrepus** [comment]
Yes, it is 128, so no need to change the bootholder?

[root@DAFANG:~]# cat /proc/cmdline
console=ttyS1,115200n8 mem=104M@0x0 ispmem=8M@0x6800000 rmem=16M@0x7000000 init=                                              /linuxrc rootfstype=squashfs root=/dev/mtdblock2 rw mtdparts=jz_sfc:256k(boot),2                                              048k(kernel),3392k(root),640k(driver),4736k(appfs),2048k(backupk),640k(backupd),                                              2048k(backupa),256k(config),256k(para),-(flag)
[root@DAFANG:~]#

**Comment by Tramsrepus** [comment]
Oh i got it, the new boot loader requires 128 minimum. Yea as it is not i get 720 at 4-5 FPS at best..
