### ISSUE TITLE
5.6.2.65 - unable to install

### ISSUE THREAD

**Issue by tb205gti** [EliasKotlyar/Xiaomi-Dafang-Hacks#596]
Unable to install on 5.6.2.65 on an Xiaomi 1S.

No logs whatsoever after demo.bin, not starting files from SD (as I suspect the demo.bin is never flashed properly).

Are there issues with this firmware version?

**Comment by EliasKotlyar** [comment]
I dont think that the bootloader was patched against this upgrade procedure. Can you try to use another microsd card? Also ensure that you have formatted it as FAT16

**Comment by tb205gti** [comment]
Ahh that might be the culprit then. I have made a 4GB partition on a 16GB SDcard - formatted in FAT32.
..I'll try FAT16

How will I know when the small Xiaomi camera have finalized the update process from the demo.bin? It does not turn like the bigger ones.

**Comment by tb205gti** [comment]
It did not work with the 16GB SDcard with a smaller 1GB FAT partition - but it worked with a 2GB SD card..
