### ISSUE TITLE
Integration in home assistant

### ISSUE THREAD

**Issue by Pharizna** [EliasKotlyar/Xiaomi-Dafang-Hacks#60]
Hi and thank you for your hack!

Now, I'm trying to include this camera in my HA but I don't know how. I only can see a "still image" but not any video :)

I'm using this code in my configuration.yaml
 
camera
  - platform: mjpeg
    name: Dafang
    mjpeg_url: http://192.168.1.73:8554
    still_image_url: http://192.168.1.73/cgi-bin/currentpic.cgi?width=1920&height=1080

Also, I tried with ffmepg camera, installing ffmepg in my RPi3, etc... but it doesn't work :(

Anyone has this camera working in HA?  Thank you in advance

**Comment by msj33** [comment]
Use the ffmpeg platform(and maybe combine it with ffmpeg_motion) in home assistant. 

I have it up and running here with RTSP(mjepg) STREAM.....but not 100% stable yet.

**Comment by lolouk44** [comment]
in case that helps, try this:
https://community.home-assistant.io/t/hacking-the-xiaomifang-wifi-camera/18579/42

**Comment by pplucky** [comment]
And this, following @lolouk44's idea:
https://community.home-assistant.io/t/hacking-the-xiaomifang-wifi-camera/18579/58

**Comment by jmtatsch** [comment]
also have a look at https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/integration/homeassistant/homeassistant.md
