### ISSUE TITLE
Not responding to mqtt commands

### ISSUE THREAD

**Issue by tb205gti** [EliasKotlyar/Xiaomi-Dafang-Hacks#600]
eg. home/dafang/set flip-off
I do get a response back: 
"OK (this means: action.cgi invoke with parameter flip-on, nothing more, nothing less)"

..But nothing happens. If I pass the parameter to the action.cgi manually - then it works just fine. :/

..The same goes for audio_test, motion_detection all all the others that pass a parameter to action.cgi. 
setting the leds via /home/dafang/leds/blue/set on is working.

**Comment by tb205gti** [comment]
..Naah it has the -k parameter, but it does not pass username:password correctly.

**Comment by nathanchantrell** [comment]
You can put the -u user:password in CURLOPTS in config/mqtt.conf that way you don't lose the changes across updates.
