### ISSUE TITLE
can this Xiaomi hack be used witht his hot new camera ??  see comment

### ISSUE THREAD

**Issue by Nortrop** [EliasKotlyar/Xiaomi-Dafang-Hacks#603]
https://www.aliexpress.com/store/product/INQMEGA-1080P-Cloud-IP-Camera-Intelligent-Auto-Tracking-Of-Human-WiFi-cam-Home-Security-Surveillance-CCTV/1972053_32884327613.html?spm=2114.12010608.0.0.31f9757aK15WKf

INQ MEGA

**Comment by jmtatsch** [comment]
You would have to research which chipset it is based on. Probably not.

**Comment by Nortrop** [comment]
Hello jmtatsch I don't know the chipset you have to buy it good PTZ camera with auto tracking functionality but i cant let it work with my DVR box. Can't connect to the video stream

**Comment by saipsa** [comment]
@Nortrop you can open the camera, and post pics of the chipset.

**Comment by mr350** [comment]
@Nortrop - I don't think that's a hot new camera as you've been lead to believe, It looks like it's just a copy of a camera that's been around for a few years! Maybe stick with the Dafang... lots of progress being made!

**Comment by jmtatsch** [comment]
Possibly spam.

**Comment by Nortrop** [comment]
OK I will make some pictures of the chipset.

**Comment by nermso** [comment]
I have a couple of these. For $20 they are pretty fun. This camera appears identical to the Sannse I’ve been seeing. I got them to talk to my pets when I’m at work....

**Comment by Alimentator** [comment]
I know this thread is closed - but I just bought such a camera and found the solution:
Stream without sound: rtsp://admin:@[IP-ADRESS]:8001
Log: http://[IP-ADRESS]/
Open Ports: 843,3201,5050,6670,8001
