### ISSUE TITLE
Motion not starting

### ISSUE THREAD

**Issue by jstride** [EliasKotlyar/Xiaomi-Dafang-Hacks#604]
I have both dafang and xaiofang cameras none seem.to be able to get motion running. The config is updated, web says the service is running but no snapshots saved.

Where/which logs should I be checking?

**Comment by saipsa** [comment]
motion snapshot and motion detection both need to be on

also see if motion region is selected properly

**Comment by tookus123** [comment]
What saipsa says. And i also have to reboot my Xiaofang 1S before it will start taking snapshots and storing them in /system/sdcard/motion/stills.

**Comment by jstride** [comment]
Thanks, seems to be intermittently working now - get some images sent but not all. Will further investigate.
