### ISSUE TITLE
Only RTSP stream seems to work

### ISSUE THREAD

**Issue by Antimus** [EliasKotlyar/Xiaomi-Dafang-Hacks#606]
So I've got 2 Dafangs that I've had for a while, I put the hack on months ago then gave up, it had full access back then, could move the camera, all worked. I've put the latest version on and nothing works, I can get an RTSP stream through MPC-HC but moving the camera fails, turning leds on and off fails, changing any setting fails, whenever I try to change anything on the website I get 404 not found.

using the android app I get video, no audio and when I try to make any changes I get an error message "Oups!"

One Dafang has the latest Xiaomi firmware, one has an older version, different SDCards, both formatted Fat32

**Comment by jmtatsch** [comment]
You can always go back to any version you feel comfortable with ...

**Comment by Antimus** [comment]
I want the new features, without knowing when the issue started what is a working version date?

Also surely if it's an issue it should be logged, just telling me to downgrade doesn't help really

**Comment by jmtatsch** [comment]
@Antimus Read your original post carefully again. Your description is far to imprecise to pinpoint any issue. E.g. latest version, which commit id? how are you attempting to control the camera? via Manage->Settings in the web interface? Via tiny cam? Via mqtt? Which url exactly is not found (404 error)?

Leaving this guesswork to the developers is just wasting everyones time.

**Comment by Antimus** [comment]
I've been using the Android app suggested in the readme, as soon as I installed tiny cam it is all working. I can only assume that the android app hasn't been updated at the same speed as the hack, probably needs to be removed from the readme to be honest as that'll catch out a lot of new users.

As for the 404, I was using http://ipaddress/cgi-bin/status.cgi because that's what I used to use to modify the camera, I didn't know it was all now available on a web viewer. Again, readme needs updating.

**Comment by nik0** [comment]
Use http://ipaddress/ only don't specify the status.cgi

**Comment by LeonCame** [comment]
I agree with #Antimus 
"http://ipaddress/ only" work with PC navigator but do not work with the android app.
There is an auto redirection http to https maybe the problem ?
In addition, the application is rather heavy.
I had seen this hack with enthusiasm, but it seems that it is not enough to be nice.

**Comment by nik0** [comment]
Which android app you are talking about? this is a web link, I guess you can open it on chrome
Which application is heavy ?

What is missing to be nice ? I don't see any commit from you, this is something done by people on their personal time, and they don't get don't get any money from it.
I suggest you to by an Arlo camera, and I am sure you will have all the features you need ...

**Comment by LeonCame** [comment]
https://play.google.com/store/apps/details?id=io.ext.medinvention.dafangcam
