### ISSUE TITLE
Horizontal movement not possible

### ISSUE THREAD

**Issue by NicoSomerwil** [EliasKotlyar/Xiaomi-Dafang-Hacks#608]
Thanks a lot for your great hacks!

I use your hacks within home-assistant. There is an issue right now to move the Dafang camera horizontal, it is not working anymore! Don't know (yet) what caused it, could be the hack or something within HA?
The vertical movement still works. The MQTT messages for horizontal movement are there but not executed. 

Does anyone have the same issues and/or a solution/workaround?
I use the latest version of your hacks and HA 0.74.2.  

Any help/suggestions are appreciated.

**Comment by davidbb** [comment]
What does the MQTT topic $yourtopic/motors/horizontal show? In my case when the camera reboots, it thinks its position is x=0. This prevents the motor from accepting rotation commands to the left, as it would go negative values. Try hitting the "calibrate" button in the settings. This causes the camera motor to find its start and end points, and set an x value that allows movement to the right and to the left.  

If that works, you could run the calibration script when the camera boots up, or submit  PR that allows calibration via an MQTT message.

**Comment by NicoSomerwil** [comment]
@davidbb  You are the best!!! You solved it, thank your very very much.  I indeed had to 'calibrate' the camera. Happy me :-)
