### ISSUE TITLE
How do i get dafang to record video to sd card

### ISSUE THREAD

**Issue by nodashipl** [EliasKotlyar/Xiaomi-Dafang-Hacks#609]
I got the custom firmware to install and work, but I dont know how to make it work as a simple camera that records everything to its sd card. Maybe im missing something simple.

**Comment by SomebodySysop** [comment]
I have searched for an answer to this as well.  I don't know that it can be done from ui.

However, if you wish to record video locally, one way I have done it is by using iSpy software.  I stream live video to iSpy using rtsp, and then use iSpy to record (also record on motion detection).  There are several other applications, like Blue Iris or TinyCam, etc...

**Comment by mpataki** [comment]
I'm only just poking with this now, but that should be what [this script](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/firmware_mod/controlscripts/recording) is for, which is available from the UI under Services, listed as "recording".
