### ISSUE TITLE
motion detection delay

### ISSUE THREAD

**Issue by esunarto** [EliasKotlyar/Xiaomi-Dafang-Hacks#610]
i have the wyze v2 camera running dafang hack.
my problem is, when i configure motion capture (and send email) it:
1. wait 1-2 sec before the first snapshot
2. delay between snap was set to 1 or 0.5, the timestamp shows 3-7 seconds delay between each snapshot. is this because of the sheer power required to ssl encode the pictures?
3. the rtsp server takes 90+% of cpu power, is there no other way?

the original wyze firmware actually record a video 2 sec before motion and 8 sec after motion.
is this do-able in dafang hack?
i'm pretty decent with *nix and busybox scripting, any pointer is appreciated.

Thanks!

**Comment by Dopeyr** [comment]
Hi @esunarto 

I've made a pull request here https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/pull/613 that allows you to not specify the -m quality level to jpegoptim. I've found this approx. 4 times as fast when compressing the image, with a similar quality level and file size. This means there's less wait between image captures.

Are you able to try it? Ultimately it's just changing `/system/sdcard/bin/jpegoptim -m${QUALITY} --stdin --stdout` to `/system/sdcard/bin/jpegoptim --stdin --stdout` in `scripts/sendPictureMail.sh`

Hopefully you'll see similar results.

I've looked into another option that writes the images to memory or sdcard first, then compresses, but that comes at the expense of RAM (in short supply) or sdcard wear.

**Comment by Dopeyr** [comment]
Hi @esunarto 

@nik0 has told be about the latest code which compresses the jpeg now. 

So to speed up sending emails with the latest release, if you set `QUALITY=-1` in `config/sendmail.conf` that won't try and compress the image further which causes a delay.
