### ISSUE TITLE
Save files in windows folder

### ISSUE THREAD

**Issue by dmolner** [EliasKotlyar/Xiaomi-Dafang-Hacks#612]
Due to problem only read I need save files in windows folder.
Could explain how made this?
Thank You

**Comment by jmtatsch** [comment]
I can not understand what you are are trying to say. Please rephrase carefully.

**Comment by dmolner** [comment]
I'm sorry that my English is very bad.
I have a new problem after upgrading my SD.
Continually, my SD is only for reading.
I need to restart the camera's continous.

I need save the images captured by the camera on a Windows PC that I have in my house.
I try some instructions i found inInternet to mount a shared folder from the windows but it does not work.
I need your help to save files to the Windows \ \ My-computer \ dafang shared folder.

Best regards.

**Comment by gabest11** [comment]
In my experience, running avconv together with the rtsp streamer is very hard on the cpu and crashes very often. I would open and save the rtsp stream on the Windows machine. Then you don't even have to mount a share. Get ffmpeg for windows and try this command:
`ffmpeg -rtsp_transport udp -y -i rtsp://root:ismart12@INSERT_DAFANG_IP_HERE:8554/unicast -vcodec copy -c:a copy -map 0 -f segment -strftime 1 -segment_time 300 -segment_atclocktime 1 -segment_format mp4 %Y%m%d-%H%M.mp4`

**Comment by dmolner** [comment]
@gabest11 
I use Ispy now but I have more interruptions on video.
Because this I think use de camera for take de imatges and upload to Internet, but now with the problem with the SD and only read message i need other option for save the images.
I use the camera only for weather.

**Comment by jmtatsch** [comment]
Then format your sdcard and start from scratch.
