### ISSUE TITLE
WiFi Interference from Camera

### ISSUE THREAD

**Issue by jeffc** [EliasKotlyar/Xiaomi-Dafang-Hacks#616]
I'm running the firmware on a Wyzecam v2. The camera connects just fine, but it interferes with other nearby WiFi devices, slowing their connections or kicking them off the network entirely, even ones on different AP/SSIDs. The stock firmware doesn't seem to have this issue, so I don't think it's (only) a hardware problem.

**Comment by jmtatsch** [comment]
This is all commodity chipsets and software running in millions of linux systems. 
I very much doubt there is any inference due to poor driver configuration.

**Comment by jeffc** [comment]
On further investigation, it looks like there was some network congestion, and turning on the camera was the straw that broke the camel's back. The stock firmware didn't exhibit the issue because it wasn't configured yet, so it wasn't on the network.

Sorry to waste everyone's time!
