### ISSUE TITLE
Can't get audio working through tinycam pro

### ISSUE THREAD

**Issue by Antimus** [EliasKotlyar/Xiaomi-Dafang-Hacks#617]
Works through VLC, I've tried PCM and PCMA, the app just says audio is not supported on this device.
Previous issue logged about this but the fix they found doesn't work for me.
Got a standard setup, nothing changed except login credentials

**Comment by jmtatsch** [comment]
But the video stream is running fine in tinycam?

**Comment by Antimus** [comment]
Yep video stream is fine, camera controls are also fine

**Comment by jmtatsch** [comment]
Then get in touch with the tinyCam author. Maybe he can support more formats.

**Comment by Antimus** [comment]
Other users have got it working

**Comment by jmtatsch** [comment]
Close in favour of #461
