### ISSUE TITLE
Activate and deactivate motion

### ISSUE THREAD

**Issue by dmolner** [EliasKotlyar/Xiaomi-Dafang-Hacks#619]
I write `/system/sdcard/scripts/detectionOff.sh` for motion off and `/system/sdcard/scripts/detectionOn.sh` but motion not stops.

**Comment by jmtatsch** [comment]
Cannot understand what is your problem.

**Comment by dmolner** [comment]
Very fast!
I need stop motion and later star motion

**Comment by jmtatsch** [comment]
You can call 
https://yourcameraip/cgi-bin/action.cgi?cmd=motion_detection_on
https://yourcameraip/cgi-bin/action.cgi?cmd=motion_detection_off
to start/stop motion.

In future please do not open new issues in the tracking system for all your questions.
Ask them in the chat.
