### ISSUE TITLE
dropbearmulti scp (secure copy) problem missing dbclient

### ISSUE THREAD

**Issue by tookus123** [EliasKotlyar/Xiaomi-Dafang-Hacks#620]
I'm running into a problem trying to use the dropbear scp client to upload image files to a ssh server.  It fails with /usr/bin/dbclient: No such file or directory. The dropbear docs say you can make a symbolic link from dropbearmulti to dbclient to fix this. The problem is the read only filesystem of /usr/bin won't allow me to make the symbolic link. Does anyone know how i can add a symbolic link or any workarounds?

`ln -s /system/sdcard/bin/dropbearmulti /usr/bin/dbclient`

```
[root@DAFANG:system]# dropbearmulti scp -P22 test.jpg test@192.168.1.155:/home/test/test.img
/usr/bin/dbclient: No such file or directory
lost connection
```

**Comment by jmtatsch** [comment]
Maybe try the new rootfs way?

**Comment by reikred** [comment]
To elaborate, the problem is that fat32 does not allow creation of softlinks (or hardlinks).  That is why the rootfs system based on ext3 is suggested as a possible fix.

rootfs reference
https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/hacks/install_sdcard.md

**Comment by tookus123** [comment]
Thanks guys. Gonna use rootfs.

**Comment by robertcedwards** [comment]
@tookus123 How were you able to resolve this using rootfs? I'm trying to accomplish the same goal, but got stuck on this step as well.

**Comment by X-Ryl669** [comment]
Did this to fix that:
```
   opkg install openssh-sftpserver
   cd /opt
   mkdir oldusr
   cp -a /usr olduser
   mkdir oldusr/usr/libexec
   mount -o bind /opt/oldusr/usr /usr
   ln -sf /opt/lib/sftp-server /usr/libexec/sftp-server
   ln -sf /system/sdcard/bin/dropbearmulti /usr/bin/dbclient
```
After that, you need to add a script to the `mount -o bind /opt/oldusr/usr /usr` is run on boot.

**Comment by timotheecour** [comment]
@X-Ryl669 how were you able to install opkg?

**Comment by X-Ryl669** [comment]
@timotheecour  See #542

**Comment by inode-** [comment]
A temporary workaround for FAT32 too is:

```ln -s /system/sdcard/bin/dropbearmulti /system/bin/dbclient```

To make the fix persistent edit the file /system/sdcard/controlscripts/dropbear and add:

```
if [ ! -f /system/bin/dbclient ]; then
  ln -s /system/sdcard/bin/dropbearmulti /system/bin/dbclient
fi
```

then reboot the camera.
