### ISSUE TITLE
Does Dafang emulates any other "well-known" camera?

### ISSUE THREAD

**Issue by Tramsrepus** [EliasKotlyar/Xiaomi-Dafang-Hacks#621]
Does Dafang emulates any other "well-known" camera? Asking as I cant find it in Blue Iris settings. XiaoFang is in the list and i'm running it as such for now. But I get no control over the camera, just the picture stream.

**Comment by jmtatsch** [comment]
Not that I know of. Does the Blue Iris have configuration files for mapping their commands to camera api?

**Comment by Tramsrepus** [comment]
I have no idea. I ggogled on it but I could not find anything about it. I will ask the support about it

**Comment by Tramsrepus** [comment]
Cool, I have now gotten Blue Iris to look into it. But they need to access the camera via HTTP and not HTTPS as it is now. How to change it?

**Comment by Tramsrepus** [comment]
@jmtatsch   I have now gotten Blue Iris to look into it. But they need to access the camera via HTTP and not HTTPS as it is now. How to change it?

**Comment by jmtatsch** [comment]
Look at the history of /system/sdcard/config/lighttpd.conf. There you can find how to configure it without https.

**Comment by darkstardxm** [comment]
I realize you may have solved this already, but it is as easy as enabling H264 RTSP in the camera settings and then adding it in Blue Iris as a Generic H264 RTSP camera, using its IP and RTSP port number shown in the configuration page of the camera
