### ISSUE TITLE
no motion snapshot is send

### ISSUE THREAD

**Issue by BernhardBuckel** [EliasKotlyar/Xiaomi-Dafang-Hacks#622]
Hi guys, 

mqtt is set correctly (both status and control) and reporting. 
What is missing is the snapshot message to decode it in home assistant
Having the xiaomi 1s model.

any suggestions what to try?

**Comment by jmtatsch** [comment]
Is motion detection enabled? Is mqtt message enabled? 
<img width="297" alt="screen shot 2018-08-05 at 18 32 00" src="https://user-images.githubusercontent.com/3080674/43687879-fbb3f69e-98dd-11e8-88ac-5beb27c37415.png">

Please use gitter for questions and the issue tracker for bugs.

**Comment by BernhardBuckel** [comment]
yes and yes.
will close issue and move to gitter. sorry
