### ISSUE TITLE
Settings changed with UI are not saving -- again

### ISSUE THREAD

**Issue by reikred** [EliasKotlyar/Xiaomi-Dafang-Hacks#626]
I have a similar problem to number 457, that settings will not save, specifically NTP server is blank and I cannot set it. It used to be time.google.com. Creating a new issue because 457 was solved, but problem seems different.

My mounts are normal, I think:

# mount
rootfs on / type rootfs (rw)
/dev/root on / type squashfs (ro,relatime)
tmpfs on /dev type tmpfs (rw,relatime)
proc on /proc type proc (rw,relatime)
devpts on /dev/pts type devpts (rw,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /tmp type tmpfs (rw,relatime)
tmpfs on /run type tmpfs (rw,nosuid,nodev,relatime,mode=755)
sysfs on /sys type sysfs (rw,relatime)
media on /media type tmpfs (rw,relatime)
/dev/mtdblock3 on /driver type squashfs (ro,relatime)
/dev/mtdblock4 on /system type jffs2 (rw,relatime)
/dev/mtdblock7 on /backupa type jffs2 (rw,relatime)
/dev/mtdblock8 on /configs type jffs2 (rw,relatime)
/dev/mtdblock9 on /params type jffs2 (rw,relatime)
/dev/mmcblk0p1 on /system/sdcard type vfat (rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro)

**Comment by jmtatsch** [comment]
Log in to your camera via ssh an create a file in the sdcard/config directory or alter the ntp config file there directly.

**Comment by reikred** [comment]
I have  looking for a workaround such as setting the NTP-server value in a file. Could not find ntp.conf, where is it??

**Comment by jmtatsch** [comment]
In the config directory ntp_srv.conf.

**Comment by reikred** [comment]
# vi /system/sdcard/config/ntp_srv.conf
# cat /system/sdcard/config/ntp_srv.conf
time.google.com

Then did a reboot from web interface. That does not work. For a reboot, must hold the reset button and follow the full recipe of the initial install. 

However, the ntp server setting does stick, at least for the time being. So what is still bad is that unattended reboot does not work, and that the timezone setting does not have the expected result. I'll start looking for reports on these other issues. No idea how the ntp server value got lost in the first place.

**Comment by reikred** [comment]
The bug of no being able to save appears to exists only in the by now quite outdated 

https://github.com/openipcamera/openipc-firmware

After switching to 

https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks

I can save the NTP server value. The time still is not correct, but that's another issue.

**Comment by reikred** [comment]
I'm sorry. Although openipc was derived from Xiaomi-Dafang-Hacks, it is by now lagging 2-3 months behind. I was not aware that XDH was the one I should be using, and that it was newer and better. Rookie mistake.

**Comment by Gamer106** [comment]
Same issue for me. I use a smart-switch to turn the camera off when I’m home and on when I leave. I can’t remove the SD card every time this happens due to the install locations, so it’s a pain in the neck to resolve by having windows scan/fix the disk.
