### ISSUE TITLE
RTSP autostart

### ISSUE THREAD

**Issue by hondaj** [EliasKotlyar/Xiaomi-Dafang-Hacks#63]
Thank you for your hard work! I have a question is it possible to „autostart” RTSP or any other setting when reboot device?

**Comment by kszere** [comment]
You can it make adding last line to `run.sh` file. 
```
MicroSD
├── bin
├── config
├── run.sh
├── scripts
├── www
└── run.sh
```
## I use this
#### For play welcome sound after start camera.
`/system/sdcard/bin/ossplay -g 100 /system/sdcard/sounds/startup.wav &`
`-g` param is for volume settings, 100 is 100%, but you can set 500 (500%)

#### For autostart stream RTSP
`/system/sdcard/bin/busybox nohup /system/sdcard/bin/v4l2rtspserver-master -fMJPG -F 10 &>/dev/null &`

**Comment by shinebar1001** [comment]
Just added a small pull-request to make this configurable

**Comment by hondaj** [comment]
Thanks for the hint, it works perfectly! 
After many hours of testing and work around with Synology, I'm also able now to connect the Dafang to Surveillance 8.1, streaming/record well, no audio in MJPEG, no cam controll but it's another topic. Thank you once again!
