### ISSUE TITLE
Correct timezone (TZ) settings -- submit your settings here

### ISSUE THREAD

**Issue by reikred** [EliasKotlyar/Xiaomi-Dafang-Hacks#630]
Hopefully this is the thread to end all timezone setting threads: Here is what I know so far about correct TZ values for the webUI TZ setting (which btw.  reads from and and saves to the file  /system/sdcard/etc/TZ ):

#US eastern standard time, with daylight savings changeover programmed
EST+5EDT,M3.2.0/2,M11.1.0/2
#US pacific standard time, with daylight savings changeover programmed
PST+8PDT,M3.2.0/2,M11.1.0/2
#Central European Time, with summer time changeover programmed
CET-1CEST,M3.5.0/2,M10.5.0/3

Why these complicated expressions, you may ask?  Well, part of the complexity is the programming of daylight saving time changeover dates. Also, people may find the signs of the numerical offsets counterintuitive. For example, EST+5 (plus) when EST is more typically thought of as GMT-5 or UTC-5 (minus). Likewise, CET is often thought of as UTC+1. Why the opposite sign in the TZ spec? Well, this is because the POSIX definition of TZ uses the opposite definition of offset than what most humans do: The POSIX offset is to be *subtracted* from GMT or UTC to get the local time.

Obviously, I did not invent this particular wheel. Other people have hinted/stated various bits and pieces of this, but it took a long time for me to understand what was going on. Hence I wanted to contribute a be-all-and-end-all thread where the correct settings can be explained and collected up front.

Ideally, the webui would at least contain some quick examples/information about the offset definition in POSIX being the opposite sign of the "human" definition, and a link to the POSIX TZ reference material, as included below here. Maybe even a link to this thread, in the webui, would be useful as well!!??

Reference:
https://www.gnu.org/software/libc/manual/html_node/TZ-Variable.html

**Comment by plasticrake** [comment]
Thank you!

**Comment by jonwaland** [comment]
AEST (Sydney, Melbourne, Hobart, Canberra etc) - AEST-10AEDT,M10.1.0/02:00,M4.1.0/03:00

(date changes will of course be wrong in future years...)

a bunch of not quite accurate examples at 
https://knowledgebase.progress.com/articles/Article/P129473

**Comment by Dopeyr** [comment]
Some further examples on the openwrt project: https://openwrt.org/docs/guide-user/base-system/system_configuration#time_zones

**Comment by swxxii** [comment]
> AEST-10AEDT,M10.1.0/02:00,M4.1.0/03:00

Thanks @jonwaland for this. it works if i manually edit the TZ file but resets on reboot
