### ISSUE TITLE
Wifi not connecting after web reboot

### ISSUE THREAD

**Issue by kimonm** [EliasKotlyar/Xiaomi-Dafang-Hacks#632]
If I reboot with web interface (or use the web to upgrade), the wifi doesn't reconnect (or the reboot totally fails, I can't tell). If I unplug and re-plug the camera in, everything is fine.

**Comment by jmtatsch** [comment]
model?

**Comment by tookus123** [comment]
It's the sdcard. Try a different brand or model. I had the exact same thing and others have as well. Once i changed to a different card, it would reboot like it's supposed to. I'm not sure why this happens but i suppose some cards aren't initialized fast enough at boot so the original firware is loaded instead.

**Comment by kimonm** [comment]
Duh, sorry: It's a Xiaomi Dafang. Thanks for the tip on the SD card. I'll try another brand.

-Kimon
