### ISSUE TITLE
Timelapse/getimage returns only 1 unique frame per second

### ISSUE THREAD

**Issue by Thndr** [EliasKotlyar/Xiaomi-Dafang-Hacks#636]
I am using a Wyze Cam V2 to test out the firmware and it seems setting the timestamp interval to lower than a second just makes the device repeat the same image twice per second.

When using the OpenIPC it shows a unique image per image captured.

Is there an option to adjust how many times getimage can retrieve the image from the camera? If not can that option be added?

**Comment by SevenXOR6** [comment]
Hate to bump, but same problem here. It's really a pain since OpenIPC doesn't work anymore....
