### ISSUE TITLE
How does "Auto Night Mode" work?

### ISSUE THREAD

**Issue by talormanda** [EliasKotlyar/Xiaomi-Dafang-Hacks#639]
I have the camera in a room, I turn the lights off, and nothing happens.....I can edit the settings and manually turn on night vision and the IR LED / IR Cut, but how do you make this work automatically when it gets to a certain darkness level?

**Comment by FuzzyMistborn** [comment]
What camera do you have?  Wyze v2?  It's a known issue. There's no light sensing chip in most of those cameras and the auto night mode is handled via software on the stock firmware.  No solution yet exists on this firmware.

**Comment by talormanda** [comment]
@FuzzyMistborn Yes, I have v2. If its possible to SSH to the device, I can always auto turn it on/off by my raspberry pi. Thanks for the insight.

**Comment by tb205gti** [comment]
..You do not need ssh to do that - you can use the cgi-bin "API" for that. (I have added a functionality to turn on IR, IR_cut_off and nightmode to the action.cgi script.) The I control it form my Openhab - so when the sun sets, I enable IR led, turn off the IR cut off and set it to grayscale (nightvision)

You can use curl or similar to call the functions in action.cgi

**Comment by bachya** [comment]
If you enable MQTT control, you can also use MQTT to toggle on/off night mode, the IR filter, etc.

**Comment by talormanda** [comment]
@bachya what is MQTT and how would I control it using that?

**Comment by tjharman** [comment]
Just curious why Night Mode isn't a toggle in the Web GUI?
Auto-night mode is, but plain old night mode isn't.
I just discovered night mode because I've started using MQTT :)

**Comment by ioanbsu** [comment]
Can someone please give me a hint on how people discover available mqtt commands?
I was able to get text output only like ${DESTINATION}/# and I see some metadata for my camera that looks like `{"uptime":" 15:28:46 up 42 min, 0 users, load average: 2.13, 2.27, 2.25", "ssid":"Artigile", "bitrate":"72.2 Mb/s", "signal_level":"100%", "link_quality":"78%", "noise_level":"0%" }15:29:26` but I can't see what mqtt commands are available and how to use it?

**Comment by sahilchaddha** [comment]
@ioanbsu You should check out 
https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/firmware_mod/controlscripts/mqtt-control

This will show what all commands it accepts after subscribing to MQTT.

For E.g.
To turn on night mode, publish a MQTT message to topic `$topic/night_mode/set` with payload `ON`

`/myhome/dafang/night_mode/set ON`

If you are planning to integrate with HomeKit. You should check out

https://github.com/sahilchaddha/homebridge-dafang

It supports hosting/connecting to MQTT automatically and have preconfigured switches for all controls.

**Comment by sahilchaddha** [comment]
@ioanbsu Yes, i am sorry for the incorrect link. I was travelling when i posted it. 
I am glad it solved your issue.
