### ISSUE TITLE
 WiFi wont Connect, Flashing Yellow light

### ISSUE THREAD

**Issue by ineedit91** [EliasKotlyar/Xiaomi-Dafang-Hacks#642]
Hello, I have the bootloader correctly flashed as I can see the solid blue light for 5 seconds. I even had the camera working before, but after trying out the new firmware I can't seem to get the camera to connect to my wifi, i only keep getting the flashing yellow light. My router is using WPA2-PSK and AES. I have altered the wpa_supplicant.conf file many times trying  things such as adding proto=RSN but to no avail. I have attached my startup.log and wpa_supplicant.conf . I changed the files so they don't have my real details on them. Please let me know if you have any ideas.
[startup.log](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/files/2293219/startup.log)
[wpa_supplicant.txt](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/files/2293223/wpa_supplicant.txt)

**Comment by jmtatsch** [comment]
looks like #591

**Comment by jmtatsch** [comment]
looks like #591

**Comment by jmtatsch** [comment]
everything looks as expected. Can you move the camera close to the router? Do you have a raspi?

**Comment by ineedit91** [comment]
I use Linux to format and copy files over from the extracted firmware mod zip to SD card (2gb transcend). Are you thinking it could be line endings?

**Comment by jmtatsch** [comment]
Unlikely then.

**Comment by ineedit91** [comment]
After some experimenting, I think I made some progress. I set a static IP by manually adding 
`ifconfig wlan0 192.168.0.###` into line 114 of run.sh. After doing this and putting the sd card into my camera and powering it up i promptly checked my routers DHCP page to see if the camera had been listed. But the router did not show the cameras host name nor its MAC address. So I went into my browser and typed http://192.168.0.###  anyways, and I was prompted with a login screen, i used the default username: root and password: ismart12 and it showed the entire Dafang web UI along with the live video feed but the camera was STILL  not showing up in my routers DHCP list, even though the static ip address i assigned was working. While the camera was connected and streaming a live video feed it was still flashing a yellow light. So it is still seeing something as wrong.  I then tried to see if i could view the stream through the android app tinycam (phone), and whilst trying to set it up, the connection to the camera on my browser died and i couldnt get it back up. I then checked the SD card and the log looked the same as the one in my first post. But when i checked the run.sh file i noticed that the log was also writing to the run.sh file. The only way i could recreate the connection was to delete the entire contents of the SD card and recopy/paste the firmware_mod folder contents to it, modify wpa_supplicant.conf, and again add the static ip into the run.sh.
I dont know much about this stuff, but i am hoping this can atleast give someone more knowledgeable a better idea of what is going on and a possible solution, as i am not the only one having this problem.

**Comment by ineedit91** [comment]
SOLVED by changing `wpa_supplicant.conf`

- Using DAFANG DF3 camera, back of device reads CMIIT ID: 2017DP3894
- Using `cfw-1.3.bin`  and commit 86ff275 from August 18th, 2018
- Router is set to WPA2-PSK AES 2.4ghz 802.11g/n

My wpa_supplicant.conf file reads as follows

`
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=0
update_config=1
country=US

network={
	ssid="MYSSID"
	psk="MYPASSWORD"
}
`

After this change the Camera finally shows up on my routers DHCP page including its MAC, IP, and Hostname.
The yellow light continues to flash BUT this is actually just the "Motion - LED" feature (which flashes the yellow LED every time the camera detects motion) this feature is on by default and can be turned off from the Web UI, this took embarrassingly too long to figure out.

SSH is now possible, as it was not with my previous attempt at setting a static IP
RTSP is incredibly bad with high dropped frames, but that will be another issue

wpa_supplicant.conf is attached as [wpa_supplicant.txt](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/files/2300237/wpa_supplicant.txt)

Here is the [startup.log](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/files/2300241/startup.log) of the successful startup.

**Comment by SomebodySysop** [comment]
Thank you very much for posting your resolution.  I had same exact problem, and the steps above helped me resolve.
