### ISSUE TITLE
DaFang 1080p DF3 Delay in video

### ISSUE THREAD

**Issue by Stalksy** [EliasKotlyar/Xiaomi-Dafang-Hacks#643]
I bought the following DaFang 1080p Camera Model DF3

https://www.zapalstyle.com/xiaomi-dafang-1080p-night-version-wifi-ip-camera.html

I have been able to get the custom firmware running and integrate it into homeassistant, while the picture is ok there is a significant delay in the picture, sometimes 10 seconds or more.

Is there a known way to improve this?

**Comment by jmtatsch** [comment]
Is the lag there when you watch the stream via VLC? The homeassistant likely is the culprit...
