### ISSUE TITLE
general feedback - delay and motor, etc.

### ISSUE THREAD

**Issue by TungstenE2** [EliasKotlyar/Xiaomi-Dafang-Hacks#648]
Hi all,

first of all I was very impressed about the hack of the Dafang cam.
In general about the option and the active project on this.
But after several days of testing and playing around I am a bit disappointed,
but I am not sure if it is about the hardware or the software of the hack.
Tested with GUI, VLC and Tinycam Pro.

Here comes a list of my findings:

- live video has a strong delay and only about 5fps instead of 25fps as defined in settings
- error message on read-only sd-card
- auto-night modus does not turn on ir-leds
- motor does not turn correct, returns back instead of following orders and is stuttering
- several settings are not implemented in GUI. while this is a lot of effort for sure, a note in the 
  GUI would be helpfull to check the config files for all settings.
- only one-way audio from camera is supported

So my main issues are the delay/5fps and the not correct working motor.
How to fix this or am I doing something wrong?

thx

**Comment by eridesktop** [comment]
Playing with Video Size, Video Format and Bit Rate in Video Settings Option maybe can help you solve the FPS problem
My settings was Video Size 1600 x 900 , Video Format SMART and Bit Rate 2000, of course you can try another option, just trial and error and find which option suites you the best.

**Comment by tsvi** [comment]
To all those with this problem.
Could you please check if you stop the RTSP server and then run:

```
dosfsck -a /dev/mmcblk0p1
mount -o remount,rw /system/sdcard
/system/sdcard/autoupdate.sh
```
If the problem stops occuring?

**Comment by TungstenE2** [comment]
good to see someone is working on the issues. but I can not test this as I sold my dafang, as it was not reliable working. but I will watch  the progress and may be buy one again if issues are fixed. thx
