### ISSUE TITLE
Disable http redirection to https

### ISSUE THREAD

**Issue by krettek** [EliasKotlyar/Xiaomi-Dafang-Hacks#649]
Hi,

as I have several Problems with iobroker to request urls like:
`https://192.168.178.161/cgi-bin/action.cgi?cmd=ir_led_off`

I tried to disable http redirection to https with deleting the following:
`$HTTP["scheme"] == "http" {
    # capture vhost name with regex conditiona -> %0 in redirect pattern
    # must be the most inner block to the redirect rule
    $HTTP["host"] =~ ".*" {
        url.redirect = (".*" => "https://%0$0")
    }
}`

Unfortunately the redirection for the actio.cgi urls is still enabled.
Anyone got an idea what to do else?

**Comment by jmtatsch** [comment]
Did you restart lighttpd or the camera?
