### ISSUE TITLE
Looking to replace flexible flat cable inside Dafang

### ISSUE THREAD

**Issue by thawizard** [EliasKotlyar/Xiaomi-Dafang-Hacks#653]
My camera doesn't show the image anymore, but everything works fine (had this before #504 ). 
I assume it has something to do with a burned part of the cable (black part of the blue end).

![20180823_164735 2](https://user-images.githubusercontent.com/36935247/44533151-2acbd580-a6f5-11e8-84dc-6127d760360a.jpg)

I wonder if anyone knows exactly how many pins this flexible flat cable has? It seems to have 34 (36? 40?) pins. And I cannot find it anywhere to buy that cable.

Any help is greatly appreciated.

**Comment by gabest11** [comment]
Search for 34p cable on ebay or aliexpress. There are 0.5mm and 1mm wide versions.
