### ISSUE TITLE
Web Client Live Stream

### ISSUE THREAD

**Issue by SomebodySysop** [EliasKotlyar/Xiaomi-Dafang-Hacks#654]
I have installed firmware into wayzecam v2.  It appears to be working.  I can stream rtsp to iSpy server and ssh in.  I noticed that while the OSD display updates in rtsp stream, it does not update on web client camera display unless I refresh image.  

Is this normal?

**Comment by Dopeyr** [comment]
Do you mean the image at https://<ip of camera> ? If so, that should refresh every 5 seconds by default.

**Comment by SomebodySysop** [comment]
Yes.   The image from my camera never refreshes unless I refresh the page manually.  What can I do about this?

Also, I do not get https://.  Only http://.

**Comment by Dopeyr** [comment]
What version are you running, as https has been default for quite a while. There should be a redirect from http -> https whenever you access via http. Have you altered any config at all?

Re: the image, looking at the code it's all JS in the browser and will refresh the image every 1 second. My version is older, and it's reloading every 4 seconds, so whether the reduction in timeout has caused an issue I'm not sure. 

Do you see any errors in the browser developer tools, on the console or network tab?

**Comment by SomebodySysop** [comment]
I do not know how to find the version number, but I have the latest commit as of August 22nd.  

The first error I get is when trying to get to https://<ip of camera>.  I get page is not secure error, then when i go to advanced, I can continue to page.  

![not secure 2018-08-24_6-40-05](https://user-images.githubusercontent.com/41084665/44588370-6359c680-a76a-11e8-8c6c-da130bb6a984.jpg)

Second error I see is: This page is trying to load scripts from unauthenticated sources.

![trying to load scripts from unauthorized sources 2018-08-24 2](https://user-images.githubusercontent.com/41084665/44588448-956b2880-a76a-11e8-885a-53502f8d3310.png)

I am using the latest Chrome browser.

**Comment by Dopeyr** [comment]
Ok, that may be the issue. I see the certification error too as it's a self signed cert, but I don't see the "insecure content blocked" message. I'm using Chrome Version 68.0.3440.106 (Official Build) (64-bit) FWIW. Not sure under what circumstances that message appears.

**Comment by Dopeyr** [comment]
Just used autoupdate for the latest code and I still don't see the same error :( The image refreshes (roughly) every 1 second. 

Can you open chrome developer tools and see if it gives you any warnings about "mixed mode content" in the console tab?

**Comment by SomebodySysop** [comment]
Yes, there is a mixed mode content warning in developer tool: Mixed Content: "The page at 'https://192.168.1.188/' was loaded over HTTPS, but requested an insecure font 'http://fonts.gstatic.com/s/roboto/v18/KFOkCnqEu92Fr1MmgVxFIzIFKw.woff2'. This request has been blocked; the content must be served over HTTPS."

And another couple of images.  Is it safe to load them?

![mixed content - insecure font 2018-08-24_10-57-55](https://user-images.githubusercontent.com/41084665/44600099-19360c80-a78d-11e8-8706-4aea79c67da0.jpg)

**Comment by Dopeyr** [comment]
Sorry, I'm struggling to reproduce this in Chrome on Mac + Windows. I also tried Edge on Windows. I also can't find any reference to the google fonts in the code, except for `api.cgi`, but that script isn't called/used as far as I can tell.

Also, I'm not really sure if the inability to load fonts would prevent the image from refreshing, it doesn't sound connected, but it's difficult to tell without being able to reproduce it :(

It would be useful to know if you see the issue in other browsers, in case it's something like a Chrome extension that's causing the issue.

**Comment by SomebodySysop** [comment]
The only other browser I have is Microsoft Edge.  MS Explorer is way too large and buggy.  

My workaround is to simply press one of the arrow keys, the the stream is normal until I close the window.  That will work for me.  I just need the rtsp stream -- I can do the monitoring, motion detection, recording, etc... from iSpy.

Thanks for help and looking into this!
