### ISSUE TITLE
RTSP Streaming Latency

### ISSUE THREAD

**Issue by SomebodySysop** [EliasKotlyar/Xiaomi-Dafang-Hacks#655]
I have wyzecam v2 camera h.264 rtsp streaming to ispy server.  Using ispy for motion detection and recording.  It's working fairly well with an average actual FPS of 25.  My problem is that every minute or so, there is a 5-7 second delay in stream.  I would like to eliminate or significantly reduce this lapse.

I have reviewed these posts in trying to understand how to approach this: 

- https://support.video.ibm.com/hc/en-us/articles/207852117-Internet-connection-and-recommended-encoding-settings
- https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/98

Based upon my video settings below, could someone please suggest settings which would help me reduce these delays?  Thanks!

![video settings 2018-08-24_16-25-42](https://user-images.githubusercontent.com/41084665/44615156-6d6dda80-a7e7-11e8-91f8-add7db6e8f82.jpg)

**Comment by Antimus** [comment]
I've found that SMART seems to give the best frame rates but also the worst motion, walk in front of it and the rate drops, move the camera and sometimes the stream completely stops. So a high reported frame rate doesn't mean much when it comes to how it handles it when the image actually changes.

I'm using FixedQp and the motion is a lot better, quality isn't as good though

**Comment by akutruff** [comment]
I turned off MP3 audio encoding as a test - the cpu usage dropped significantly and I could actually stream.

**Comment by SomebodySysop** [comment]
As a follow up:  I am using latest build, which seems to have improved things.

Also, I finally tried FixedQp today (fps=15, bitrate=5000, videosize=1600x900).  Audio and motion detection turned off.  This is giving me the best overall performance I have seen so far.  Fewer disconnects, less pixelation and just more consistent video streaming in general.

This is during the day.  Still need to test it at night, but so far I am very pleased with results.

**Comment by grigio** [comment]
I also turned off audio and motion detection but there is always a 1sec of lag (at least) 1280x720 VBR 10 FPS

**Comment by grigio** [comment]
Did somebody test if flashing the open source bootloader improve this situation?

**Comment by akutruff** [comment]
> Did somebody test if flashing the open source bootloader improve this situation?

Of what bootloader do you speak?

**Comment by grigio** [comment]
> > Did somebody test if flashing the open source bootloader improve this situation?
> 
> Of what bootloader do you speak?

I mean this https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/hacks/flashinguboot.md
Because with the original Xiaomi firmware and a direct connection via ad-hoc wifi I don't have this problem

**Comment by akutruff** [comment]
Was about to follow those instructions and I think there may be bug there - 

## Flashing the U-Boot bootloader:

1. Login via SSH
2. Get the correct [bootloader](https://github.com/Dafang-Hacks/uboot/tree/master/compiled_bootloader) for your device and RAM size.
3. Put the bootloader file in the root of your microsd card. It will get mounted to /system/sdcard on your camera.
4. **Verify the MD5 hash of the file!! Do not skip this step or you may brick your camera!**
3. Run the following commands

```bash
flash_eraseall /dev/mtd0
```
```bash
dd if=/system/sdcard/NAME_OF_YOUR_BOOTLOADER_FILE.bin of=/dev/mtd0
```
For example, if you're flashing dafang_128mb_v2.bin, your command should look like this:

```bash
dd if=/system/sdcard/dafang_128mb_v2.bin of=/dev/mtd0
```

It says to put the bin in the **root** folder of your SD card.  First, when you ssh into the camera you're sent to /root.  This is confusing.  I'm *assuming* that the instructions mean to copy the file to / and not /root.   Second, and most scary, the dd command says if=/system/sdcard/NAME_OF_YOUR_BOOTLOADER_FILE.bin which is not where I was just told to copy the file.  I'm hesitant to follow the instructions as they are as I see other issues bricking the camera.  Please let me know if I'm wrong here.  Either way, the instructions are not clear as I am sitting here unable to follow them as written.

**Comment by jmtatsch** [comment]
The root of your sd card will be mounted to /system/sdcard.
This is where you should go for flashing.
You will also find your boot loader files there.

**Comment by akutruff** [comment]
I appreciate your comment, but your response did not clarify any of the specific ambiguities and questions I put above.  Could you please precisely address the specific ambiguities I pointed out?  Sorry to be annoying, I do not want to brick this device.  Note: I'm completely comfortable in command line environments. 

First, are you saying the instructions are fine as is?

> The root of your sd card will be mounted to /system/sdcard. 

Should the bin file be in / or /root.  Are you saying to put the bin file in / ?  if=/system/sdcard/THE.bin Nothing in the instructions say to copy the file /system/sdcard.

**Comment by jmtatsch** [comment]
The tutorial assumes you take the sdcard out of your camera and into your computer to put the validated bootloader files on the sdcard.

If you know your way with a shell, it really doesn't matter from where you flash. 
Just make sure you didn't download any html files instead of the bins.

**Comment by akutruff** [comment]
Still didn't answer any of the exact questions I asked, man. : (  Just looking for precise answers to the above questions.

**Comment by akutruff** [comment]
`
[root@DAFANG:]# wget https://github.com/Dafang-Hacks/uboot/raw/master/compiled_bootloader/dafang_128mb_v2.bin

Connecting to github.com (192.30.253.112:443)
Connecting to raw.githubusercontent.com (151.101.0.133:443)
wget: can't open 'dafang_128mb_v2.bin': Read-only file system
`
The above command works fine when downloading file to /root.  (I'm using the url to the raw bin and verified with md5sum.)

**Comment by Dopeyr** [comment]
Hi @akutruff 

I think the confusion lies in that the "root of the microsd card" is not the same as "root of the filesystem" i.e. `/`, nor is it the same as "the home directory of the root account" i.e. `/root`

The tutorial expects you to take the sd card out of the camera (I agree this isn't clear), put it in another machine, mount it there, download the correct .bin and put it in the "root of the sd card" i.e. don't put it in a sub directory.

Then put the sd card back in the camera. The camera will then mount the root of the sd card to `/system/sdcard`, hence the instructions telling you to use `/system/sdcard`

However, you don't have to do that if you don't want. If you're downloading the file directly to the camera, you can put it anywhere you can write to. As far as I know, /root would be fine, as long as a) the md5sum still matches and b) you then use the correct path in the dd command

(As an aside, `/root` is in fact on your sdcard; it's bind mounted from `/system/sdcard/root` - but I didn't want to confuse things further!)

**Comment by akutruff** [comment]
@Dopeyr Yep.  Spot on and thanks so much for clarifying.  This is what I was looking for.  Kicking myself in retrospect as it is "simple" now that I get what was being referred to.

The following is all that needs to be done:  
```
cd /system/sdcard/

wget https://github.com/Dafang-Hacks/uboot/raw/master/compiled_bootloader/NAME_OF_YOUR_BOOTLOADER_FILE.bin 

md5sum NAME_OF_YOUR_BOOTLOADER_FILE.bin 

dd if=/system/sdcard/NAME_OF_YOUR_BOOTLOADER_FILE.bin of=/dev/mtd0

mv uEnv.bootfromnand.txt uEnv.txt
```

With permission, I'd like to update the wiki to the above with all the necessary provisos about verifying MD5 and including the warnings.  I feel like since all of this requires ssh access anyway, the extra step of ejecting the microsd card for the copy on another machine is unnecessary and may avoid errors.  For windows users, accidentally double clicking the env file and it ending up in notepad even changed line endings on me.  (Thankfully I double checked before booting with Notepad++)

**Comment by akutruff** [comment]
*Returning to the original performance issue:** 

So still having lots of performance and stability problems even after flashing.  Testing on both VLC and Synology Surveillance Station

I have tried various combinations of video formats simply at 720p.  I disabled audio completely as it was eating 50% of the CPU according to top.  Synology doesn't like the SMART format at all.  The quality of FixedQP is too low and also unstable.  I tried bitrates between 2500 and 5000 for all formats.  I disabled motion detection entirely as well?

Am I just super unlucky?   My home network is beefy - Unifi ACPRO HD's, pfSense router running baremetal.  Everything at the moment is on the same subnet.

Who is able to run 24 hours a day at good quality?

```
Your Bootloader Version is:
U-Boot 2013.07-gba03eeb (Dec 04 2018 - 21:41:16)

Your CMDline is:

console=ttyS1,115200n8 mem=87M@0x0 ispmem=9M@0x5700000 rmem=32M@0x6000000 init=/linuxrc rootfstype=squashfs root=/dev/mtdblock2 rw mtdparts=jz_sfc:256k(boot),2048
```

**Comment by jmtatsch** [comment]
@akutruff Its a good idea document the wget approach and checksum checking. Please make a pull request towards the relevant documentation file.

**Comment by jmtatsch** [comment]
@akutruff concerning the original performance issue, if you can live without audio & motion processing consider building a fresh vanilla v4l2rtspserver https://github.com/mpromonet/v4l2rtspserver

**Comment by akutruff** [comment]
@jmtatsch Hmm... what's the baseline expected experience for this project?  If the camera doesn't work with the default rtsp setup on this firmware, then all of this is self-defeating.  

To me, the base feature list is to reach video performance parity with the closed source firmware with an RTSP stream / autonight.  At the heart of that is clear and stable video stream at least 720p.  If any other feature takes that away, then it doesn't make sense to have the feature on by default in the baseline build.  Don't get me wrong, I see why people want motion detection and MQTT, but even with those turned off the camera is essentially useless.  

I tried to get openfang working as it seems like he's doing exactly what you're suggesting and settting the camera up to be a minimal rtsp server.  Unfortunately instructions there are spotty and I can't get that installed.

Do you have guidance on how I can start cleanly with the most minimal form of Xiaomi-Dafang-Hacks and get v4l2rtspserver going to test your suggestion? I'll of course report back.

**Comment by jmtatsch** [comment]
This is hacked firmware maintained by some people in their free time. So don’t expect, rather help yourself fix the stuff that is important to you.

**Comment by akutruff** [comment]
I'm trying to...  That's why I asked for how to start cleanly to follow your suggestion.  

If you're reacting to the top commentary - I was trying to gently point out that the firmware presently isn't working for it's base purpose (unless I'm using it wrong.)  There's been obviously a lot of appreciated work put into this project and it's much appreciated.  Unfortunately, I've seen a lot of mention of this work on reddit but it's been sadly discussed in a negative light due to stability and performance.  That's why I'm also investing time in trying to help the situation.  These little cameras running rtsp can change the world, and it's almost there.

**Comment by jmtatsch** [comment]
Openfang  should have more stable fundamentals but less features. These projects need more people actually fixing things instead of just whining around.

**Comment by akutruff** [comment]
Wow, man.  Just wow.

**Comment by jmtatsch** [comment]
Not talking about you, you already started to help out. Some people seem to think we are doing this for a living.
