### ISSUE TITLE
Path to feed RTSP Address missing port 8554

### ISSUE THREAD

**Issue by nphil** [EliasKotlyar/Xiaomi-Dafang-Hacks#659]
The section where it shows the RTSP address is wrong, it no longer shows the port. https://imgur.com/trfMFpR

This needs to be ipaddress:8554/unicast.

**Comment by nik0** [comment]
Do you have the field "PORT" in /system/sdcard/config/rtspserver.conf ?

**Comment by nik0** [comment]
You can add this to the file: 
PORT=8554

**Comment by nphil** [comment]
Just added that under '# Video', however the webui still doesn't show the port number as part of the address properly. Still looks like this https://imgur.com/trfMFpR

Problem with webui code? This only started happening after the latest updates - not sure which one exactly. Anyone else?

**Comment by nik0** [comment]
It is working for me, the code looks like: 
$(source /system/sdcard/config/rtspserver.conf; echo $PORT)

**Comment by Dustie** [comment]
I just installed from Git and i don't have PORT either.

**Comment by nik0** [comment]
Did you copy all the .dist files ?

**Comment by jmtatsch** [comment]
PORT=8554 is in /system/sdcard/config/rtspserver.conf.dist
Please replace the contents of your rtspserver.conf with the contents of  rtspserver.conf.dist

**Comment by bachoo786** [comment]
what is the port of audio?

**Comment by nik0** [comment]
Same as video
