### ISSUE TITLE
Sound with tinyCam Monitor PRO

### ISSUE THREAD

**Issue by LeonCame** [EliasKotlyar/Xiaomi-Dafang-Hacks#660]
Not an issue, just for information :

I have contacted Alexey Vasilyev the dev of tinyCam Monitor about no sound in the app.

I let him connect to my (Dafang hacks) to test it. It made a fix in a beta version (that I installed) and now, the sound works normally without having to go through a special xml (which has never worked for me).
I think in the next version it will be integrated in the normal release.

**Comment by bachoo786** [comment]
Is the no sound in the app on a different network from the camera or the same network?

**Comment by LeonCame** [comment]
Most likely the same network.

For info, on this page: https://plus.google.com/communities/115794095184548411935 (left column)
you can get beta versions of Tinycam to enjoy audio.

**Comment by TungstenE2** [comment]
where do I find the link to the beta on Google+?

**Comment by willymarlian** [comment]
@LeonCame do you still have the beta version? I cannot find how to get beta version of Tinycam. 
I have downloaded the latest TinyCam Pro, but still have no sound for the Dafang Hacks. Please advise.

**Comment by LeonCame** [comment]
Hello,
I dont use beta version anymore, only official version, because sound was since integrated in official version.
I think if you use the good settings you should have sound.
I dont use dafang actually but if you still have problem I can upgrade to last version this WE and tell back to you.

**Comment by LeonCame** [comment]
Ok I have seen your edit
