### ISSUE TITLE
Wizecam Pan Frame Rate only like 1 FPS

### ISSUE THREAD

**Issue by Ocelotsden** [EliasKotlyar/Xiaomi-Dafang-Hacks#661]
Hi, I was able to install the custom firmware without issue and I am able to view the video stream from both the web interface and my IP Cam Pro app. The problem is that I'm only getting about 1 frame per second in the stream either in the web interface (tried different browsers, all the same) or the IP Cam Viewer Pro app.

I've tried changing the video settings to just about every combination including FPS, resolution, bitrate, VBR, Smart, etc  and it doesn't help. 

The video is sharp and bright, it's just that it's only about one frame per second. Stock firmware with the Wyze app is fast and so is my internet and other cameras. 

I don't know how to find the version, but it was the latest from this page:
https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/hacks/install_cfw.md

Any suggestions?

**Comment by Ocelotsden** [comment]
I just tried viewing the stream in VLC using rtsp://192.168.1.110:8554/unicast and other than a 2 or 3 second delay, the frame rate is where it should be, so that's great, so it must be a different stream than the web interface uses. Now I need to figure out how to view that unicast stream in IP Cam Viewer pro. It just uses an IP address and port number which I can forward in my router

**Comment by Ocelotsden** [comment]
I think I need to change the question. 
I can view the stream fine and with good frame rate with VLC using rtsp://192.168.1.110:8554/unicast
The new question is how can I view that same stream remotely outside my network? I have port forwarded Port# 8554 in my router to the cameras fixed IP address. However, If I try to view in an app by replacing the internal IP address with my external IP address, I get nothing. 

Either I'm missing something or the stream is not being broadcast outside my home network.

**Comment by Ocelotsden** [comment]
I'm using a good Linksys Gigabit router. On other cameras I have I can just forward the port for the cameras IP address and all works fine, but the other cameras are ONVIF type cameras. I tried doing the same with this one, port 8554 and it doesn't seem to work. I also tried changing the port number of the stream to something more common for cameras like port 554 and I still couldn't view the stream outside the home network.

**Comment by zacharymikel** [comment]
I would try using a utility on a different network or a service like http://www.canyouseeme.org/ to check that you get a response from that port from your public IP address. If you don't, then you know the problem is somewhere between your Dafang camera and the router.

**Comment by hubmon** [comment]
@zacharymikel 
re: setting up a home VPN server
Hope you get some time soon to blog aboutthat VPN setup. Where will you be hosting it?
