### ISSUE TITLE
How do I fix the video glitch (black and white or pink screen)? For the Xiaomi Dafang

### ISSUE THREAD

**Issue by Pmoymar** [EliasKotlyar/Xiaomi-Dafang-Hacks#664]
![xiaomi danfang](https://user-images.githubusercontent.com/42880139/44942439-bb9e5300-ad7e-11e8-8716-d27283218fc5.jpg)

**Comment by jmtatsch** [comment]
Restart your rtsp-server? Deactivate night mode? What do the logs say?
