### ISSUE TITLE
JPG file

### ISSUE THREAD

**Issue by Pharizna** [EliasKotlyar/Xiaomi-Dafang-Hacks#67]
Hi!

It would very interesting (and not very difficult, I hope) to save currentpic in a jpg file. Wouldn't?

I saw in cgi-bin/currentpic.cgi that in your https://github.com/EliasKotlyar/Xiaomi-Dafang-Software/tree/master/v4l2rtspserver-master there is an option to save this file... but it doesn't work for me :(

/system/sdcard/bin/v4l2rtspserver-master  -fMJPG **-O /tmp/dafang.jpg** 

I would like to integrate my Dafang camera in HomeAssistant in order to send (through Telegram, for example) this picture with an automatization action.

**Comment by shinebar1001** [comment]
currentpic.cgi only works, when the rtsp-server isn't running. With the help of a precompiled avconv from the forum you can save a file when working with mjpeg.
Further information about the progress in this topic: https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/48

**Comment by Pharizna** [comment]
In fact, I are not running the rtsp-server yet... but I can't take jpg files using currentpic.cgi. Anyway, it seems a very good idea to wait and to use with avconv, etc.

**Comment by kszere** [comment]
Try in terminal what not working. Param  `-O filename.jpg` save to file. `-O /stdout` print in stdout (ex. terminal)

**Comment by Pharizna** [comment]
It's works on screen (stdout) but  the filename.jpg doesn't appear :(

**Comment by kszere** [comment]
This must works `/v4l2rtspserver-master -fMJPG -O /stdout > /run/snaphot.jpg`

**Comment by Pharizna** [comment]
It works!

THANK YOU 👍

**Comment by Pharizna** [comment]
But... how can I access to this file from another site?  :(

I'm newbie, as you can see

**Comment by kszere** [comment]
You can use my edition API for Xiaomi Dafang. Please see [here](https://kszere.gitbooks.io/xiaomi-dafang-api/content/en/action/getsnaphot.html) and [manual](https://kszere.gitbooks.io/manual-for-xiaomi-dafang-api/content/en/).

**Comment by Pharizna** [comment]
Thank you for your offer :)

Aren’t you going to write a fully example about the use of your API?
