### ISSUE TITLE
red light flashing after camera flash

### ISSUE THREAD

**Issue by lpt2007** [EliasKotlyar/Xiaomi-Dafang-Hacks#671]
Hi,

Blue light is lit and red light is flashing slow. I don't have access to camera? Camera not connects to wifi?

**Comment by jmtatsch** [comment]
What camera? The xiaomi clones don't  have a red leds.

**Comment by lpt2007** [comment]
I don't konw if is xiaomi clone. Can you tell me? Here is pictures:
![front](https://user-images.githubusercontent.com/38924279/45088808-707f9980-b10a-11e8-8c6b-59c09d59bf06.jpg)
![back](https://user-images.githubusercontent.com/38924279/45088813-74abb700-b10a-11e8-9c90-31a146d4ea5d.jpg)

Error video:
http://www.youtube.com/watch?v=NA90xc9puxs

**Comment by jmtatsch** [comment]
Looks like your spy cam. Why don't you state that in your title?  Why don't you continue in your old issue?

**Comment by lpt2007** [comment]
Sorry. I will cantinue in my old issue.
