### ISSUE TITLE
Feature Request: Add easier night vision mode toggle to action.cgi

### ISSUE THREAD

**Issue by davidvermillion** [EliasKotlyar/Xiaomi-Dafang-Hacks#673]
Right now, it is possible to issue commands via HTTP call to action.cgi to enable and disable night vision functions, but in order to do a full switch, 3 commands must be issued

https://user:pass@[ip-address]/cgi-bin/action.cgi?cmd=ir_led_on
https://user:pass@[ip-address]/cgi-bin/action.cgi?cmd=ir_cut_off
https://user:pass@[ip-address]/cgi-bin/action.cgi?cmd=toggle-rtsp-nightvision-on

This is problematic for BlueIris, as only one command can be issued (I tried chaining commands with &, which wasn't accepted) for each action (IR leds on, etc)

Would it be possible for action.cgi to either accept multiple commands, or to have a command that performs all 3 functions with one command?

**Comment by nik0** [comment]
This is quite easy, look at the file action.cgi you will see what to do
