### ISSUE TITLE
Stream freezes after few seconds

### ISSUE THREAD

**Issue by sagittarius-vn** [EliasKotlyar/Xiaomi-Dafang-Hacks#674]
I'm using Xiaomi Dafang with Xiaomi-Dafang-Hacks. Stream freezes after few seconds.

_
ffplay version 4.0.2 Copyright (c) 2003-2018 the FFmpeg developers
built with gcc 7.3.1 (GCC) 20180722
configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-bzlib --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth
libavutil 56. 14.100 / 56. 14.100
libavcodec 58. 18.100 / 58. 18.100
libavformat 58. 12.100 / 58. 12.100
libavdevice 58. 3.100 / 58. 3.100
libavfilter 7. 16.100 / 7. 16.100
libswscale 5. 1.100 / 5. 1.100
libswresample 3. 1.100 / 3. 1.100
libpostproc 55. 1.100 / 55. 1.100
[mp3float @ 0000015af8744340] Header missing 0KB sq= 0B f=0/0
[h264 @ 0000015af8742e40] missing picture in access unit with size 4656
[h264 @ 0000015af8742e40] No start code is found.
[h264 @ 0000015af8742e40] Error splitting the input into NAL units.
[rtsp @ 0000015af873e540] CSeq 6 expected, 0 received. 0B f=0/0
Last message repeated 3 times
[rtsp @ 0000015af873e540] CSeq 6 expected, 0 received. 0B f=0/0
[rtsp @ 0000015af873e540] CSeq 6 expected, 0 received. 0B f=0/0
Input #0, rtsp, from 'rtsp://********:8554/unicast':
Metadata:
title : LIVE555 Streaming Media v2017.10.28
comment : LIVE555 Streaming Media v2017.10.28
Duration: N/A, start: 0.199200, bitrate: N/A
Stream #0:0: Video: h264 (Constrained Baseline), yuv420p(progressive), 1280x720, 25 fps, 25.08 tbr, 90k tbn, 50 tbc
Stream #0:1: Audio: mp3, 44100 Hz, mono, fltp, 64 kb/s
[mp3float @ 0000015af87db780] Header missing
[h264 @ 0000015afd4de680] No start code is found.
[h264 @ 0000015afd4de680] Error splitting the input into NAL units.
[rtsp @ 0000015af873e540] CSeq 6 expected, 0 received.
[mp3float @ 0000015af87db780] Header missing
[rtsp @ 0000015af873e540] CSeq 6 expected, 0 received.
Last message repeated 2 times
[h264 @ 0000015afd4de680] error while decoding MB 32 16, bytestream -21
[h264 @ 0000015afd4de680] concealing 2337 DC, 2337 AC, 2337 MV errors in I frame
[h264 @ 0000015afd4deb00] Increasing reorder buffer to 1
[rtsp @ 0000015af873e540] CSeq 6 expected, 0 received. 0B f=0/1
Last message repeated 2 times
[rtsp @ 0000015af873e540] CSeq 6 expected, 0 received. 0B f=0/1
[h264 @ 0000015afd4deb00] Increasing reorder buffer to 110B f=0/1
[h264 @ 0000015af879aa80] error while decoding MB 59 16, bytestream -13
[h264 @ 0000015af879aa80] concealing 2310 DC, 2310 AC, 2310 MV errors in P frame
[h264 @ 0000015afd4deb00] error while decoding MB 22 36, bytestream -17
[h264 @ 0000015afd4deb00] concealing 747 DC, 747 AC, 747 MV errors in I frame
[mp3float @ 0000015af87db780] Header missing 0KB sq= 0B f=0/1
[rtsp @ 0000015af873e540] CSeq 6 expected, 0 received. 0B f=0/1
[h264 @ 0000015af8799d80] error while decoding MB 75 29, bytestream -53
[h264 @ 0000015af8799d80] concealing 1254 DC, 1254 AC, 1254 MV errors in I frame
[mp3float @ 0000015af87db780] Header missing 0KB sq= 0B f=0/1
[mp3float @ 0000015af87db780] Header missing 76KB sq= 0B f=0/2
[mp3float @ 0000015af87db780] Header missing 83KB sq= 0B f=0/2
[mp3float @ 0000015af87db780] Header missing160KB sq= 0B f=0/5
[h264 @ 0000015af8799d80] left block unavailable for requested intra4x4 mode -1
[h264 @ 0000015af8799d80] error while decoding MB 0 34, bytestream 13790
[h264 @ 0000015af8799d80] concealing 929 DC, 929 AC, 929 MV errors in I frame
[h264 @ 0000015af8799d80] error while decoding MB 21 32, bytestream -14
[h264 @ 0000015af8799d80] concealing 1068 DC, 1068 AC, 1068 MV errors in I frame
[rtsp @ 0000015af873e540] CSeq 6 expected, 0 received. 0B f=0/5
Last message repeated 1 times
[mp3float @ 0000015af87db780] Header missing 0KB sq= 0B f=0/5
[h264 @ 0000015af879a200] error while decoding MB 55 15, bytestream -13
[h264 @ 0000015af879a200] concealing 2394 DC, 2394 AC, 2394 MV errors in P frame
[rtsp @ 0000015af873e540] CSeq 6 expected, 0 received. 0B f=0/5
[mp3float @ 0000015af87db780] Header missing 0KB sq= 0B f=0/5
[h264 @ 0000015afd4deb00] error while decoding MB 63 20, bytestream -19
[h264 @ 0000015afd4deb00] concealing 1986 DC, 1986 AC, 1986 MV errors in I frame
[rtsp @ 0000015af873e540] CSeq 6 expected, 0 received. 0B f=0/5
Last message repeated 1 times
[mp3float @ 0000015af87db780] Header missing
[rtsp @ 0000015af873e540] CSeq 6 expected, 0 received.
Last message repeated 1 times
[h264 @ 0000015afd4deb00] error while decoding MB 60 22, bytestream -35
[h264 @ 0000015afd4deb00] concealing 1829 DC, 1829 AC, 1829 MV errors in I frame
[mp3float @ 0000015af87db780] Header missing 0KB sq= 0B f=0/7
[rtsp @ 0000015af873e540] CSeq 6 expected, 0 received. 0B f=0/7
Last message repeated 1 times
[h264 @ 0000015af879a200] error while decoding MB 49 18, bytestream -57
[h264 @ 0000015af879a200] concealing 2160 DC, 2160 AC, 2160 MV errors in I frame
[h264 @ 0000015afd4deb00] error while decoding MB 51 11, bytestream -7
[h264 @ 0000015afd4deb00] concealing 2718 DC, 2718 AC, 2718 MV errors in P frame
[mp3float @ 0000015af87db780] Header missing 4KB sq= 0B f=0/8
[rtsp @ 0000015af873e540] CSeq 6 expected, 0 received. 0B f=0/8
[h264 @ 0000015af8799d80] error while decoding MB 7 25, bytestream -31
[h264 @ 0000015af8799d80] concealing 1642 DC, 1642 AC, 1642 MV errors in P frame
[h264 @ 0000015afd4deb00] error while decoding MB 67 21, bytestream -41
[h264 @ 0000015afd4deb00] concealing 1902 DC, 1902 AC, 1902 MV errors in I frame
[rtsp @ 0000015af873e540] CSeq 6 expected, 0 received. 0B f=0/9
Last message repeated 1 times
14.44 A-V: -5.575 fd= 60 aq= 0KB vq= 0KB sq= 0B f=0/9
_

**Comment by ppetru** [comment]
I'm also seeing regular stream freezes. Mostly using tinyCAM as a player but when trying mplayer I get similar debug output as above. Switching to FixedQp encoding seems to be a workaround, but then the video quality is much lower.

#667 seems related.

**Comment by SomebodySysop** [comment]
I have WyzeCam V2 which I believe is pretty much the same camera.  I'm having a similar problem.  My iSpy Agent reports that it's reconnecting to camera every 40 seconds or so.  Have you looked at the Video Server logs?  I see the following in mines, repeated constantly.  Does anyone know what this means, and how it might be resolved?

2018-09-08 06:14:28.568 (410696.406s) [main thread     ]       DeviceSource.cpp:110      0|V4L2DeviceSource::doStopGettingFrames
2018-09-08 06:14:28.568 (410696.406s) [main thread     ]       DeviceSource.cpp:110      0|V4L2DeviceSource::doStopGettingFrames
2018-09-08 06:14:31.268 (410699.106s) [main thread     ]ServerMediaSubsession.c:25       0|Creating Source...
2018-09-08 06:14:31.269 (410699.107s) [main thread     ]ServerMediaSubsession.c:29       0|Creating H264 Source...
2018-09-08 06:14:31.269 (410699.107s) [main thread     ]ServerMediaSubsession.c:51       0|Creating Sink for format : video/H264
2018-09-08 06:14:52.178 (410720.016s) [main thread     ]       DeviceSource.cpp:110      0|V4L2DeviceSource::doStopGettingFrames
2018-09-08 06:14:52.178 (410720.016s) [main thread     ]       DeviceSource.cpp:110      0|V4L2DeviceSource::doStopGettingFrames
2018-09-08 06:14:54.365 (410722.203s) [main thread     ]ServerMediaSubsession.c:25       0|Creating Source...
2018-09-08 06:14:54.365 (410722.203s) [main thread     ]ServerMediaSubsession.c:29       0|Creating H264 Source...
2018-09-08 06:14:54.366 (410722.203s) [main thread     ]ServerMediaSubsession.c:51       0|Creating Sink for format : video/H264
2018-09-08 06:15:13.638 (410741.476s) [main thread     ]       DeviceSource.cpp:110      0|V4L2DeviceSource::doStopGettingFrames
2018-09-08 06:15:13.638 (410741.476s) [main thread     ]       DeviceSource.cpp:110      0|V4L2DeviceSource::doStopGettingFrames
2018-09-08 06:15:16.247 (410744.085s) [main thread     ]ServerMediaSubsession.c:25       0|Creating Source...
2018-09-08 06:15:16.247 (410744.085s) [main thread     ]ServerMediaSubsession.c:29       0|Creating H264 Source...
2018-09-08 06:15:16.248 (410744.085s) [main thread     ]ServerMediaSubsession.c:51       0|Creating Sink for format : video/H264
2018-09-08 06:15:35.693 (410763.531s) [main thread     ]       DeviceSource.cpp:110      0|V4L2DeviceSource::doStopGettingFrames
2018-09-08 06:15:35.693 (410763.531s) [main thread     ]       DeviceSource.cpp:110      0|V4L2DeviceSource::doStopGettingFrames
2018-09-08 06:15:37.984 (410765.822s) [main thread     ]ServerMediaSubsession.c:25       0|Creating Source...
2018-09-08 06:15:37.985 (410765.823s) [main thread     ]ServerMediaSubsession.c:29       0|Creating H264 Source.

**Comment by badabing2005** [comment]
I have Wyze Pan and suffer from the same issue using TinyCam Pro.

Thanks

**Comment by xnaron** [comment]
@badabing2005 with the stock firmware or the hack?

**Comment by SomebodySysop** [comment]
I am running the hack on a WyzeCam V2 as well as Xiaofang 1S T20s.  I managed to resolve my issues by upgrading to the latest hack firmware and fiddling around with the settings: https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/351#issuecomment-432738939

My solution was FixedQP also.

I am using both iSpy Agent and ContaCam.  I can't say that I have eliminated my rtsp drops, but the video streams are far more stable and reliable than they were when I posted here 3 months ago.

**Comment by nonyhaha** [comment]
I am using with very very very few issues:
1280x720
400kbps
15 fps
CBR
No user/pass
No audio
No motion detection
Xiaomi dafang camera.
Motioneye software. Please check that fps in camera and fps in surveillance software is the same. Otherwise it will nor record/play correctly. 
For video recording check that the cpu on software machine is not maxed out(especially when using raspberry).

**Comment by badabing2005** [comment]
> 
> 
> @badabing2005 with the stock firmware or the hack?

With the hack firmware.

It is worth nothing that I haven't been using the RTSP for a while now because of the issues noted above.
I just tried it again today and it's working great.
My settings are:
RTSPH264OPTS="-W1280 -H720"
RTSPMJPEGOPTS="-W1280 -H720"
BITRATE=2000
FRAMERATE_DEN=1
FRAMERATE_NUM=25
VIDEOFORMAT=2

Since my last try, I believe two things has changed.
1- updated to the latest code
2- changed WAP to unifi

not sure which fixed the issue.

**Comment by SomebodySysop** [comment]
> 2- changed WAP to unifi

Can you explain how you did this?

**Comment by badabing2005** [comment]
> 
> 
> > 2- changed WAP to unifi
> 
> Can you explain how you did this?

Not exactly sure what you want me to explain.

- Bought [Unifi AC Pro](https://store.ui.com/products/unifi-ac-pro)
- Disabled my routers's WAP (wifi)
- Setup the Unifi

**Comment by Snotmann** [comment]
Same here ... stream breaks together with tinycam everytime i look more than a few seconds ...

**Comment by mikemanpl** [comment]
Same here. It freezes every few seconds after some time in tinycam pro on Android phone.
