### ISSUE TITLE
Dafang Auto Night mode doesn't work

### ISSUE THREAD

**Issue by pedrojvaz** [EliasKotlyar/Xiaomi-Dafang-Hacks#676]
**Version: 2018-08-18T18:47:32Z Issues**
 
Auto mode is on, but the image is still black. 

![image](https://user-images.githubusercontent.com/4522620/45054489-74210b00-b08d-11e8-820f-135e81a9ecf8.png)

If I manually turn IR-CUT off, I then get a purple screen

![image](https://user-images.githubusercontent.com/4522620/45054567-a894c700-b08d-11e8-8120-d9f382c91f84.png)

**Comment by jdbeitz** [comment]
+1

**Comment by huntz** [comment]
+1

**Comment by TungstenE2** [comment]
I think Dafang does not have light sensor. So Auto-mode does not work with Dafang.

**Comment by jmtatsch** [comment]
The older Generation cameras have light sensors, the newer don’t. You can use a cronjob to set night mode by time. Just search the issues.

**Comment by TungstenE2** [comment]
would be good to have trigger only to show options which are available for a model by default.

**Comment by chrismyan** [comment]
this would have been good to know before I bought the camera

**Comment by chrismyan** [comment]
> The older Generation cameras have light sensors, the newer don’t. You can use a cronjob to set night mode by time. Just search the issues.

What file would we have to edit and what would the command be?
