### ISSUE TITLE
PTZ in iSpy

### ISSUE THREAD

**Issue by sladaar** [EliasKotlyar/Xiaomi-Dafang-Hacks#679]
Thank you all in advance for reading!

In iSpy, using the preset for the dafang hack (and obviously URLs are correct) PTZ won't work, and the camera log says:
/var/log/lighttpd-error.log
(mod_auth.c.525) password doesn't match

..even if it should be the correct one (i changed it from ismart12, which doesn't work either) in the "http password" field.

Any advice?

**Comment by sladaar** [comment]
many thanks for the reply!
Sniffing with Wireshark i found that the request was:
http://192.168.1.134/cgi-bin/action.cgi?cmd=motor_right&val=100
And i guess that is the problem, without any username and password given the camera won't move.

I will tweak the config in iSpy then, the problem must be there (i tried entering the credentials everywhere or simply using http://username:pwd@ip/ but doesn't work anyway, the video always works but the ptz never seems.).

Thanks anyway !

**Comment by TungstenE2** [comment]
can you post the full correct URL syntax?

**Comment by sladaar** [comment]
Sure!

URL: https://192.168.1.134/
port: 443
channel: 0
username: root
password: yourpassword

**Comment by ortegafernando** [comment]
thanks a lot, your solution works. I think that @jmtatsch could close this.
