### ISSUE TITLE
Very, very few fps in Home Assistant (HA) 

### ISSUE THREAD

**Issue by Pharizna** [EliasKotlyar/Xiaomi-Dafang-Hacks#68]
Hi

I'm trying to use this camera in HA and rtsp streaming is not very bad in VLC (in my PC) but integrated in HA es very, very slow: 1 frame per 5-10 seconds. Is this normal?

- platform: ffmpeg
  name: Dafang2
  input: -rtsp_transport tcp -i rtsp://192.168.1.73:8554/unicast

The behaviour si simillar to this one:

  - platform: mjpeg
    name: Dafang
    mjpeg_url: http://192.168.1.73:8554/unicast.mpd
    still_image_url: http://192.168.1.73/cgi-bin/currentpic.cgi?width=1280&height=720

but, at least, I can take pictures because the rtsp service is not running :)

Any idea to improve it?

**Comment by lolouk44** [comment]
Silly question but do you click on the feed in HA to make it full screen? If not it only refreshes once every 10 sec

**Comment by Pharizna** [comment]
I can't understand your qestion :(

I tried to explain in my previous email that I tried including two different platforms:

ffmpeg: Streamed video with 1frame per 5-10 s

mjpeg: ¿Streamed video? with same freqency more or less... but I can (from the PC, for example, accessing to the dafang URL take snapshots in full screen) because I haven't to start video streaming for the camera.


![image](https://user-images.githubusercontent.com/3939655/35777340-89bad5c8-09ac-11e8-88cb-a1e1970acaf1.png)

**Comment by lolouk44** [comment]
Yes that picture will only refresh about one every 10 sec. Click on the picture and it will open in full screen with correct refresh rate

**Comment by Pharizna** [comment]
In theory yes... but I can't see anything clicking on the picture :(

![image](https://user-images.githubusercontent.com/3939655/35778631-459948ce-09c1-11e8-9b57-26caed15ca80.png)

**Comment by lolouk44** [comment]
You may have to wait for 1-2 sec for the picture to show... That's the only way you'll get full frame rate

**Comment by Pharizna** [comment]
10 minutes later after click on the picture... not any image al full frame rate :(



![image](https://user-images.githubusercontent.com/3939655/35779286-d27f4528-09ca-11e8-86cb-e1c77b9dcf29.png)

I've just installed the last mod with time stamp... but it appears a problem in the last area of the picture :(

![image](https://user-images.githubusercontent.com/3939655/35779317-5477735c-09cb-11e8-9008-2065b4ecd72c.png)

**Comment by Pharizna** [comment]
Now, timestamp has dissapeared :( Why?

**Comment by kevincaradant** [comment]
Problem is it still present ? , I have the same problem of low fps even in full screen :/
Did you have still the problem @Pharizna? Thank you

**Comment by Pharizna** [comment]
Just one frame every 10 seconds. Is it ok?

**Comment by kevincaradant** [comment]
What do you mean by is it OK. Yes I have only one frame every 10 seconds but I want at least  15/20 fps every second if possible :)

**Comment by jmtatsch** [comment]
As discussed in your other issue https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/275 your rpi3 is simply to slow to deal with h264 faster. Also HomeAssistants max frame rate for now is 2 FPS with may change soon https://github.com/home-assistant/home-assistant/pull/14079
