### ISSUE TITLE
Image-Snap documentation?

### ISSUE THREAD

**Issue by DifferentComputers** [EliasKotlyar/Xiaomi-Dafang-Hacks#680]
in the [FAQ](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/28f0e9bca07108bab66191f8e8bbb99023a6b683/hacks/faq.md), it mentions Image-Snap to get images, but this is not the same as imagesnap and there's no documentation I can find.

Does this allow the camera to capture and save an image to a remote host, or just to the SD card? And what are the commands to use? Again, nothing is documented as far as I can find. Searching for "Image-Snap" returns only the one mention of it in the FAQ.

**Comment by saipsa** [comment]
are you familiar with other commands? You should create a documentation for them, for those who don't know.

To learn more about image-snap, grep it in code.
