### ISSUE TITLE
Xiaomi Xiaofang 1S (iSC5) RS232 header pinout

### ISSUE THREAD

**Issue by piotrmalara** [EliasKotlyar/Xiaomi-Dafang-Hacks#681]
Hi everyone,
I've just bought Xiaomi Xiaofang 1S camera here: https://www.aliexpress.com/item/Original-Xiaomi-CCTV-Mijia-Xiaofang-110-Degree-F2-0-8X-1080P-Digital-Zoom-Smart-Camera-IP/32884030076.html

Below is the photo of the camera mainboard. I based on photos from here https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/hacks/serial.md and here https://nm-projects.de/wp-content/uploads/2016/12/signals.jpg. Have I marked the correct signal order?

![isc5 headers](https://user-images.githubusercontent.com/40602830/45184574-9babdb00-b227-11e8-8eed-40953669d3f6.png)

After the confirmation (or correction, if needed) the photo can be uploaded to wiki for others.

Regards!

**Comment by piotrmalara** [comment]
Luckily, the pin order was CORRECT and I managed to connect the camera to the FT232RL module:

![camera connected_scaled](https://user-images.githubusercontent.com/40602830/45267380-95a63c00-b46b-11e8-9617-46152c8382aa.png)

Now I can go on.

**Comment by yenleidong** [comment]
![image](https://user-images.githubusercontent.com/9006040/82985978-31505500-a01f-11ea-80d7-3b4e75dbd60f.png)
work like a charm,
Thanks :)
