### ISSUE TITLE
Timezone calculation inverted

### ISSUE THREAD

**Issue by marciogranzotto** [EliasKotlyar/Xiaomi-Dafang-Hacks#683]
UTC gives me 20:00:00
if I change my timezone to UTC-3 it gives me 23:00:00
but if I change my timezone to UTC+3 it gives me 17:00:00

**Comment by Dopeyr** [comment]
See https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/630 for info on how to set the TZ variable.

**Comment by Shaker1978** [comment]
I've read the #630, but I do not agree with the POSIX logic. I would like a more intuitive way of defining timezones, like it is used everywhere else. I have never come across this way of tinking: UTC (00:00:00) -2 = 02:00:00. What a crap, sorry.

**Comment by tominco** [comment]
I concur with shaker1978... The logic on the timezone is backwards. I'm in the Mountain TZ and should be using UTC-7:00, but alas, UTC+7:00 is what is required by the firmware.

**Comment by jmtatsch** [comment]
We would gladly accept a pullrequest.
