### ISSUE TITLE
Mosquitto Client Disconnected Homeassistant

### ISSUE THREAD

**Issue by moskyow** [EliasKotlyar/Xiaomi-Dafang-Hacks#688]
Hi all,
i have Hass.io on Raspberry 3 b+
I have installed the hack on a dafang. Mqqt and stream with vlc are ok.
I see disconnection on the log the mosquitto mqqt broker and the discover are not done.

1536776562: Client mosqpub|12944-Cam-Soggi disconnected.
1536776562: New connection from 192.168.2.21 on port 1883.
1536776562: New client connected from 192.168.2.21 as mosqpub|12954-Cam-Soggi (c1, k60, u'MYUSER').
1536776562: Client mosqpub|12954-Cam-Soggi disconnected.
1536776562: New connection from 192.168.2.21 on port 1883.
1536776562: New client connected from 192.168.2.21 as mosqpub|12956-Cam-Soggi (c1, k60, u'MYUSER').
etc...

Wich can be the problem ?

**Comment by moskyow** [comment]
I have resolved. The problem was in a space in the name of the camera

**Comment by naitsimp** [comment]
I think I have the same problem as you:
How did you sove it exactly?

I get:
```
1542295187: New client connected from 192.168.1.249 as mosqpub|1136-xiaomi_daf (c1, k60, u'username').
1542295187: Client mosqpub|1136-xiaomi_daf disconnected.
1542295187: New connection from 192.168.1.249 on port 1883.
[INFO] found username on local database
1542295188: New client connected from 192.168.1.249 as mosqpub|1140-xiaomi_daf (c1, k60, u'username').
1542295188: Client mosqpub|1140-xiaomi_daf disconnected.
1542295188: New connection from 192.168.1.249 on port 1883.
[INFO] found username on local database
```
etc.

My camera is called:
```
# Define device name
DEVICE_NAME="dafang_1"
```

**Comment by moskyow** [comment]
My problem was the space on camera name.
Now I use openhab, but you can try to remove the underscore.

**Comment by naitsimp** [comment]
Thanks. but still the same messsages in the Mosquitto Broker Log.
mqtt.config:
```
# Define device name
DEVICE_NAME="dafang1"
```

I also set the Hostname on the GUI to: xiaomidafang1
