### ISSUE TITLE
Not connecting to Wifi

### ISSUE THREAD

**Issue by chrismyan** [EliasKotlyar/Xiaomi-Dafang-Hacks#689]
I have two wifi networks at my house. One is 2.4 ghz and the other is 5ghz. I was able to connect to the 2.4 ghz network and verify that the hack works but when i try to connect to the 5ghz network it doesn't seem to work. I use the Fing app to look for the IP of the camera by looking for new connections on the 5ghz network but it doesn't show up. The SSID for my 5ghz is NightHawkX6-5G-2. Does the dashes mess anything up in the config file? I also noticed that when I look at the network name of the network it shows an additional 2 at the end of "NightHawkX6-5G-2" so it looks like this "NightHawkX6-5G-2 2". Please help

**Comment by jmtatsch** [comment]
The WiFi chipsets don’t support 5ghz.
