### ISSUE TITLE
Set RTSP FPS

### ISSUE THREAD

**Issue by hondaj** [EliasKotlyar/Xiaomi-Dafang-Hacks#69]
I have very nice stream at almost 25fps@1280x720p, but it's generate tons of gigabytes when connect 4-6 cams to NAS. How to reduce FPS to, for example to 15fps? I try `/system/sdcard/bin/busybox nohup /system/sdcard/bin/v4l2rtspserver-master -fMJPG -U **-F 15** admin:pass &>/dev/null &` in run.sh but no results, still have 23,8-25fps. 

Second question it's possible to force full HD res (RTSP) on v4l2rtspserver-master?

**Comment by kszere** [comment]
Try: `/system/sdcard/bin/busybox nohup /system/sdcard/bin/v4l2rtspserver-master -fMJPG -F 15 -U admin:pass &>/dev/null &`

**Comment by hondaj** [comment]
Exactly this command I used and unfortunately doesn't work, 
I still have a stream at the level of 25fps.

**Comment by saipsa** [comment]
+1

**Comment by jmtatsch** [comment]
Please test #523, reopen if necessary.
