### ISSUE TITLE
Cant load library liblivemedia.so

### ISSUE THREAD

**Issue by bachoo786** [EliasKotlyar/Xiaomi-Dafang-Hacks#691]
Hey guys I have the latest version of hacks on my dafang. And the stream is working perfectly well I am trying to use the audio on tinycam pro and I have set up everything correctly including the .xml file. 

However I don't hear anything on tinycam there is a unmute  speaker button which I have pressed but it keeps circulating to no avail and says audio failed check the port number etc. I decided to execute the following line in ssh: /system/sdcard/bin/v4l2rtspserver-master -W 1600 -H 900 &

And I get a message can't load library liblivemedia.so 

Can anyone help me please thank you.

**Comment by nik0** [comment]
What does `env` command says, you need to see the following:
`LD_LIBRARY_PATH=/system/sdcard/lib:/thirdlib/:/system/lib`
Then you need to kill the previous running server before starting a new one

**Comment by bachoo786** [comment]
I tried the env command and it gives the LD_LIBRARY_PATH as: 

LD_LIBRARY_PATH=/thirdlib:/system/lib 

Is the above ok?

How do I kill the previous server?

**Comment by nik0** [comment]
No it is not OK.
You have to type: `export LD_LIBRARY_PATH=/system/sdcard/lib:$LD_LIBRARY_PATH`
To stop the running server: ` /system/sdcard/controlscripts/rtsp-h264 stop`

**Comment by bachoo786** [comment]
Ok that's sorted. Thanks
