### ISSUE TITLE
Cannot Authenticate Via Web Login

### ISSUE THREAD

**Issue by infosectester** [EliasKotlyar/Xiaomi-Dafang-Hacks#692]
Hello,

I am unable to authenticate via the web gui / portal located at http://cam-ip . SSH is currently working.. .
Is there anyway I can reset the web pass? Thanks!

**Comment by jmtatsch** [comment]
https only

**Comment by infosectester** [comment]
I get connection refused when attempting https:..

**Comment by infosectester** [comment]
I ended up wiping the SD card and installing the newest version. I am able to connect.
