### ISSUE TITLE
Unable to install CFW on new Xiaofang 

### ISSUE THREAD

**Issue by corvy** [EliasKotlyar/Xiaomi-Dafang-Hacks#693]
Hello, just bought a new Xiaofang but I am not able to flash the CFW. The stock firmware boots all the time. A few days ago I made the same install on Dafang with no issues. I have formatted the SDcard multiple times but the camera consistently boots stock firmware. I try to be exact on the 10 seconds, and I have tried more but no success. I also tried multiple CFW files but I think the one I am supposed to use is the Xiaomi XiaoFang T20 but to be honest I am not sure. 

This is my camera: https://www.ebay.com/itm/IP-Camera-Xiaomi-xiaofang-1080P-Smart-Wireless-WiFi-Night-Vision-Webcam/292588301112?ssPageName=STRK%3AMEBIDX%3AIT&_trksid=p2057872.m2749.l2649

How do I verify what CFW to use and are there any tricks? I have reformatted to FAT32, cleaned out all dirs and files after every boot, changed to a 512Mb partition but nothing works.... Looking for some tips! :dancer:

**Comment by M203** [comment]
Something seems to have changed for the latest sw (353) for dafang. Not possbile to flash. 
One seems to be able to log it.
https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/669#issuecomment-420662499

**Comment by corvy** [comment]
I understand! :) Thanks! 

If there is anything I can do to capture logs or similar please tell me.

**Comment by moritzj29** [comment]
I'm afraid I'm facing the same issue. Tried to flash the CFW 1.0 to my new Xiaofang 1S (according to seller) but without success. The device boots to the stock firmware and creates record/time lapse folders on the SD. So the card is recognized by the system.
Thanks for sharing the link to Issue #669 as possible workaround. If I have time I will dig in to that...

**Comment by sanjeewasam** [comment]
had the same issue with xiofang. 

Go to original firmware/dafang folder and copy the demo_5.5.1.194.bin to SD card and rename to demo.bin and flash that first. This will downgrade the firmware (do not worry- same processor so Dafanf work in xiofang). Then you could install the downloaded .bin file to SD card and rename as demo.bin and flash. After that you could load the files in firmware_mod

**Comment by M203** [comment]
Can one update the dafang in mi app after this or will that mess things up?

**Comment by jmtatsch** [comment]
Wouldn’t recommend to apply Xiaomi firmware updates if you want to keep your device hackable. The latest fw seems to make hacking more difficult.

**Comment by moritzj29** [comment]
As discussed, the problem appears to be related to the newest software version 353, which appears to be not flashable via microSD at the moment. @corvy if you found a solution, please share! :D

**Comment by mahbubzone** [comment]
I have xiaofang 1s. I searched a lot but didn't find any proper instruction to flash cfw in this. can anyone help?
