### ISSUE TITLE
Dafang more power xml for tinycam

### ISSUE THREAD

**Issue by AndriiIevdoshenko** [EliasKotlyar/Xiaomi-Dafang-Hacks#694]
<?xml version="1.0" encoding="UTF-8"?>
 <vendor name="Xiaomi">
        <model name="XiaoFang">
            <comments>Use hacked firmware from https://github.com/samtap/fang-hacks for RTSP and web server.</comments>
            <request name="RTSP">/unicast</request>
            <request confirmation="true" custom="Reboot">/cgi-bin/action?cmd=reboot</request>
        </model>
        <model name="Dafang">
            <comments>Use custom firmware from https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks for RTSP and web server.</comments>
            <request name="Snap">/cgi-bin/currentpic.cgi</request>
            <request name="RTSP">/unicast</request>
            <request name="LedOn">/cgi-bin/action.cgi?cmd=ir_led_on</request>
            <request name="LedOff">/cgi-bin/action.cgi?cmd=ir_led_off</request>
            <request name="PtzMoveRelLeft">/cgi-bin/action.cgi?cmd=motor_left&amp;val=100</request>
            <request name="PtzMoveRelRight">/cgi-bin/action.cgi?cmd=motor_right&amp;val=100</request>
            <request name="PtzMoveRelUp">/cgi-bin/action.cgi?cmd=motor_up&amp;val=100</request>
            <request name="PtzMoveRelDown">/cgi-bin/action.cgi?cmd=motor_down&amp;val=100</request>
            <request name="PtzMoveHome">/cgi-bin/action.cgi?cmd=motor_hcalibrate /cgi-bin/action.cgi?cmd=motor_vcalibrate</request>
            <request custom="Blue Led On">/cgi-bin/action.cgi?cmd=blue_led_on</request>
            <request custom="Blue Led Off">/cgi-bin/action.cgi?cmd=blue_led_off</request>
            <request custom="Yellow Led On">/cgi-bin/action.cgi?cmd=yellow_led_on</request>
            <request custom="Yellow Led Off">/cgi-bin/action.cgi?cmd=yellow_led_off</request>
            <request custom="IR Cut On">/cgi-bin/action.cgi?cmd=ir_cut_on</request>
            <request custom="IR Cut Off">/cgi-bin/action.cgi?cmd=ir_cut_off</request>
            <request custom="RTSP Nightvision On">/cgi-bin/action.cgi?cmd=toggle-rtsp-nightvision-on</request>
            <request custom="RTSP Nightvision Off">/cgi-bin/action.cgi?cmd=toggle-rtsp-nightvision-off</request>
            <request custom="RTSP Flip On">/cgi-bin/action.cgi?cmd=cmd=flip-on</request>
            <request custom="RTSP Flip Off">/cgi-bin/action.cgi?cmd=cmd=flip-off</request>
            <request custom="OSD Debug On">/cgi-bin/action.cgi?cmd=onDebug</request>
            <request custom="OSD Debug Off">/cgi-bin/action.cgi?cmd=offDebug</request>
            <request custom="Auto Night Mode On">/cgi-bin/action.cgi?cmd=auto_night_mode_start</request>
            <request custom="Auto Night Mode Off">/cgi-bin/action.cgi?cmd=auto_night_mode_stop</request>
            <request custom="Test Audio">/cgi-bin/action.cgi?cmd=audio_test</request>
            <request confirmation="true" custom="Start Original Xiaomi Software">/cgi-bin/action.cgi?cmd=xiaomi_start</request>
            <request confirmation="true" custom="Reboot">/cgi-bin/action?cmd=reboot</request>
        </model>
        <model name="Ants Xiaoyi Smart Camera">
            <comments>Downgrade camera firmware to 1.8.5.1B to get RTSP support. Download it from http://xiaoyi.querex.be/</comments>
            <request name="RTSP">/ch0_0.h264</request>
            <request name="RTSP2">/ch0_1.h264</request>
        </model>
        <mac oui="B0-D5-9D" />
        <mac oui="5C-FF-FF" />
    </vendor>

**Comment by jmtatsch** [comment]
This is not an issue
