### ISSUE TITLE
Improve email notification

### ISSUE THREAD

**Issue by codedmind** [EliasKotlyar/Xiaomi-Dafang-Hacks#695]
IDEA:
Have an option to make a gif/mp4 a small file to send via email after motion detection.

**Comment by ferrolho** [comment]
In order to achieve this, I have modified `/system/sdcard/scripts/sendPictureMail.sh` to include the following code segment:

```bash
# Also include a short video
VIDEO_TIMESTAMP=$(date +%Y-%m-%d_%H-%M-%S)

printf '%s\n' "--${boundary}
Content-Type: video/mp4
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename=\"${VIDEO_TIMESTAMP}.mp4\"
"

VIDEO_DURATION=120  # in seconds
VIDEO_FILENAME=/system/sdcard/DCIM/$VIDEO_TIMESTAMP.mp4
avconv -rtsp_transport tcp -y -i rtsp://your.camera.ip.address:8554/unicast -vcodec copy -c:a copy -t $VIDEO_DURATION $VIDEO_FILENAME
openssl enc -base64 -in $VIDEO_FILENAME
echo
```

For my purpose, I have inserted it just before the block:
```bash
# print last boundary with closing --
printf '%s\n' "--${boundary}--"
printf '%s\n' "-- End --"
```

**Comment by ferrolho** [comment]
Hmmm, for some reason the snippet above makes it so that the `sendPictureMail.sh` script is only able to run successfully on the first motion detection... After sending the first email, it no longer sends any more emails.

I should check if the script is called at all. Any insight, @jmtatsch ?

**Comment by jmtatsch** [comment]
I would guess you need some kind of semaphore to make your script run only once. Right now there is probably many instances avconv spawning and then killed due to low memory. Look a dmesg, there you should see OOMs.
