### ISSUE TITLE
motion snapshots

### ISSUE THREAD

**Issue by kapiorr** [EliasKotlyar/Xiaomi-Dafang-Hacks#696]
In home assistant not showing:
 - camera.dafang3_motion_snapshot

Probably dafang not send mqtt message.
in mqtt-control.sh is not defined this topic

**Comment by jmtatsch** [comment]
did you set
publish_mqtt_message=true
in motion.conf?

**Comment by kapiorr** [comment]
Yes

**Comment by jmtatsch** [comment]
Is the yellow motion sensed led triggered? And you receive motion detection messages on the mqtt broker?

**Comment by kapiorr** [comment]
yes, i receive motion detection messages
but no camera.dafang3_motion_snapshot or similar in HA entities

**Comment by jmtatsch** [comment]
weird, 
this line should set it up

https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/c6ee7032188f383de8e019e5936de4ffd78790da/firmware_mod/scripts/mqtt-autodiscovery.sh#L18

maybe mqtt.camera can't deal with the recently added uuid ?

**Comment by kapiorr** [comment]
on the broker: 
`18.09.2018-18:51:53 home/dafang {"uptime":" 18:51:40 up  6:57,  0 users,  load average: 4.31, 4.24, 3.88",  "ssid":"LEDE", "bitrate":"72.2 Mb/s", "signal_level":"100%", "link_quality":"87%", "noise_level":"0%" }
18.09.2018-18:51:53 home/dafang/leds/blue OFF
18.09.2018-18:51:53 home/dafang/leds/yellow OFF
18.09.2018-18:51:53 home/dafang/leds/ir OFF
18.09.2018-18:51:53 home/dafang/ir_cut ON
18.09.2018-18:51:53 home/dafang/brightness 40
18.09.2018-18:51:53 home/dafang/rtsp_h264_server ON
18.09.2018-18:51:53 home/dafang/rtsp_mjpeg_server OFF
18.09.2018-18:51:53 home/dafang/night_mode OFF
18.09.2018-18:51:53 home/dafang/night_mode/auto OFF
18.09.2018-18:51:53 home/dafang/motion/detection OFF
18.09.2018-18:51:53 home/dafang/motion/tracking OFF
18.09.2018-18:51:53 home/dafang/motion/send_mail OFF
18.09.2018-18:51:53 home/dafang/motors/vertical 0
18.09.2018-18:51:53 home/dafang/motors/horizontal 0
18.09.2018-18:51:53 homeassistant/binary_sensor/dafang/motion/config {"name": "dafang motion sensor",  "icon": "mdi:run", "state_topic": "home/dafang/motion", "device_class": "motion"}
18.09.2018-18:51:53 homeassistant/switch/dafang/motion_detection/config {"name": "dafang motion detection",  "icon": "mdi:run", "state_topic": "home/dafang/motion/detection", "command_topic": "home/dafang/motion/detection/set"}
18.09.2018-18:51:53 homeassistant/switch/dafang/motion_tracking/config {"name": "dafang motion tracking",  "icon": "mdi:run", "state_topic": "home/dafang/motion/tracking", "command_topic": "home/dafang/motion/tracking/set"}
18.09.2018-18:51:53 homeassistant/switch/dafang/blue_led/config {"name": "dafang blue led", "icon": "mdi:led-on", "state_topic": "home/dafang/leds/blue", "command_topic": "home/dafang/leds/blue/set"}
18.09.2018-18:51:53 homeassistant/switch/dafang/yellow_led/config {"name": "dafang yellow led", "icon": "mdi:led-on", "state_topic": "home/dafang/leds/yellow", "command_topic": "home/dafang/leds/yellow/set"}
18.09.2018-18:51:53 homeassistant/switch/dafang/ir_led/config {"name": "dafang ir led",  "icon": "mdi:led-on", "state_topic": "home/dafang/leds/ir", "command_topic": "home/dafang/leds/ir/set"}
18.09.2018-18:51:53 homeassistant/switch/dafang/ir_cut/config {"name": "dafang ir filter", "icon": "mdi:image-filter-black-white", "state_topic": "home/dafang/ir_cut", "command_topic": "home/dafang/ir_cut/set"}
18.09.2018-18:51:53 homeassistant/switch/dafang/night_mode/config {"name": "dafang night mode", "icon": "mdi:weather-night", "state_topic": "home/dafang/night_mode", "command_topic": "home/dafang/night_mode/set"}
18.09.2018-18:51:53 homeassistant/switch/dafang/auto_night_mode/config {"name": "dafang night mode auto", "icon": "mdi:weather-night", "state_topic": "home/dafang/night_mode/auto", "command_topic": "home/dafang/night_mode/auto/set"}
18.09.2018-18:51:53 homeassistant/switch/dafang/rtsp_h264_server/config {"name": "dafang h264 rtsp server", "icon": "mdi:cctv", "state_topic": "home/dafang/rtsp_h264_server", "command_topic": "home/dafang/rtsp_h264_server/set"}
18.09.2018-18:51:53 homeassistant/switch/dafang/rtsp_mjpeg_server/config {"name": "dafang mjpeg rtsp server", "icon": "mdi:cctv", "state_topic": "home/dafang/rtsp_mjpeg_server", "command_topic": "home/dafang/rtsp_mjpeg_server/set"}
18.09.2018-18:51:53 homeassistant/switch/dafang/motion_send_mail/config {"name": "dafang motion send mail",  "icon": "mdi:run", "state_topic": "home/dafang/motion/send_mail", "command_topic": "home/dafang/motion/send_mail/set"}
18.09.2018-18:51:53 homeassistant/sensor/dafang/ldr/config {"name": "dafang light sensor", "icon": "mdi:brightness-5", "unit_of_measurement": "%", "state_topic": "home/dafang/brightness"}
18.09.2018-18:51:53 homeassistant/cover/dafang/motor_up_down/config {"name": "dafang move up/down", "state_topic": "home/dafang/motors/vertical", "command_topic": "home/dafang/motors/vertical/set", "payload_close": "down", "payload_open": "up", "optimistic": "false", "value_template": "{{ ((value|int)/7.3)|round }}"}
18.09.2018-18:51:53 homeassistant/cover/dafang/motor_left_right/config {"name": "dafang move left/right", "state_topic": "home/dafang/motors/horizontal", "command_topic": "home/dafang/motors/horizontal/set", "payload_close": "right", "payload_open": "left", "optimistic": "false", "value_template": "{{ ((value|int)/27)|round }}"}
18.09.2018-18:52:11 home/dafang/leds/blue OFF
18.09.2018-18:52:11 home/dafang/leds/yellow OFF
18.09.2018-18:52:11 home/dafang/leds/ir OFF
18.09.2018-18:52:12 home/dafang/ir_cut ON
18.09.2018-18:52:12 home/dafang/brightness 40
18.09.2018-18:52:12 home/dafang/rtsp_h264_server ON
18.09.2018-18:52:13 home/dafang/rtsp_mjpeg_server OFF
18.09.2018-18:52:13 home/dafang/night_mode OFF
18.09.2018-18:52:13 home/dafang/night_mode/auto OFF
18.09.2018-18:52:13 home/dafang/motion/detection OFF
18.09.2018-18:52:13 home/dafang/motion/send_mail OFF
18.09.2018-18:52:14 home/dafang/motion/tracking OFF
18.09.2018-18:52:14 home/dafang/motors/vertical 0
18.09.2018-18:52:14 home/dafang/motors/horizontal 0
18.09.2018-18:52:15 home/dafang {"uptime":" 18:52:14 up  6:58,  0 users,  load average: 3.95, 4.17, 3.86",  "ssid":"LEDE", "bitrate":"72.2 Mb/s", "signal_level":"100%", "link_quality":"87%", "noise_level":"0%" }`

and long message when motion detect

**Comment by jmtatsch** [comment]
if you run said line something like 
`/camera/dafang2/motion_snapshot/config {"name": "dafang2 motion snapshot",  "unique_id": "34ce00b159dd-motion-snapshot",  "topic": "home/dafang2/motion/snapshot"}`
should be published.

**Comment by kapiorr** [comment]
I found problem.
In mqtt-autodiscovery.sh line
`/system/sdcard/bin/mosquitto_pub.bin -h "$HOST" -p "$PORT" -u "$USER" -P "$PASS" -t "$AUTODISCOVERY_PREFIX/camera/$DEVICE_NAME/motion_snapshot/config" ${MOSQUITTOPUBOPTS} ${MOSQUITTOOPTS} -r -m "{\"name\": \"$DEVICE_NAME motion snapshot\",  \"unique_id\": \"$DEVICE_MAC-motion-snapshot\",  \"topic\": \"$TOPIC/motion/snapshot\"}" `

i have missing -p "$PORT"

now works. Thank you

**Comment by bachoo786** [comment]
hey @kapiorr how do you use the motion snapshots? Do you have to subscribe to a topic and enter a payload to capture a snap or does the camera automatically capture when it detects motion?

**Comment by kapiorr** [comment]
I followed the instructions: https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/integration/homeassistant/homeassistant.md

**Comment by bachoo786** [comment]
@kapiorr sorry what instructions? they only talk about motion topic and not the camera taking a snap shot of any motion ?

**Comment by bachoo786** [comment]
right I see. how do you access the saved snaps remotely?

**Comment by kapiorr** [comment]
Its send via mqtt. In the same file : publish_mqtt_message=true
On home assistant i added camera.dafang3_motion_snapshot.
Now it show snapshot in ha

**Comment by bachoo786** [comment]
right so this "camera.dafang3_motion_snapshot" is a mqtt topic?

**Comment by kapiorr** [comment]
No, it is entity in HA. I dont subscribe any topic. Its doing  automagicly when enabled mqtt discovery in Home Assistant

**Comment by bachoo786** [comment]
right I dont see it as I am running mosquitto. @jmtatsch is there any specific I need to subscribe to so I could get the motion snap shots?

thanks

**Comment by kapiorr** [comment]
Evething is in instructions:
Topic
myhome/mycamera/motion/snapshot

**Comment by bachoo786** [comment]
@kapiorr I know everything is in the instructions but I am a complete noob on this and I am trying to learn my way. I have mosquitto and I am trying to extract or get the snaps on my Home Assistant. Its easy when you have mqtt auto discovery which I dont have due to mosquitto. 

I need some help on this please.

**Comment by kapiorr** [comment]
I have mosquitto too. It works with mosquitto.

**Comment by bachoo786** [comment]
right so how do I turn on mqtt auto discovery buddy?

**Comment by kapiorr** [comment]
Read manual:


To enable mqtt discovery in Home Assistant please add/adjust in your
.homeassistant/configuration.yaml:

mqtt:
  broker: localhost
  discovery: true
  discovery_prefix: homeassistant

and restart your Home Assistant instance. Apparently this does not work
with Home Assistant's internal mqtt broker, so better run your own
<https://www.home-assistant.io/docs/mqtt/broker/#run-your-own>.

**Comment by bachoo786** [comment]
right thanks for that. I get the camera.dafang_motion_snapshot entity in Home Assistant. However no image is shown. It says image not available

**Comment by kapiorr** [comment]
In system/sdcard/config/motion.conf
publish_mqtt_message=true

In camera web interface enable motion detection

**Comment by exetico** [comment]
Hi all

I'm sorry for bringing this up again - i can see that a lot of people are asking about the same.

My motion.conf is like this (and it's present in the right `config` folder):
```
# Configure the motion core parameters:

region_of_interest=187,0,1018,720
motion_sensitivity=3
motion_indicator_color=2
motion_timeout=-1
motion_tracking=off

# Configure how to deal with motion events:

motion_trigger_led=true
save_snapshot=true
max_snapshots=20
publish_mqtt_message=true
sendemail=false
send_telegram=false
save_dir=/system/sdcard/motion/stills
save_file_date_pattern="+%d-%m-%Y_%H.%M.%S"
```

And if i move within the zone, the red spot shows up in the camera feed, so the motion is regonized, but no messages is sent to my mosq broker.

With MQTT.fx is subscripted to all topics, and "only" the following topics about motion shows up:
gang/dafang/motion/detection
gang/dafang/motion/send_mail
gang/dafang/motion/tracking

I'm also able to see that the auto-discovery on `homeassistant/camera/dafang/motion_snapshot/config` is sending out this:
```
{"name": "dafang motion snapshot",  "unique_id": "78***cd***db-motion-snapshot",  "topic": "gang/dafang/motion/snapshot"}
```
But the `gang/dafang/motion/snapshot` is not showing up...

"Motion Detection" is also enabled in "Camera Controls" in the webgui, and i restarted the camera twice.

Within Manage > Services i have a file called `configureMotion `

My MOSQ-server is just based on the standard `eclipse-mosquitto`-docker container. Could that be the problem?
