### ISSUE TITLE
human voice

### ISSUE THREAD

**Issue by bachoo786** [EliasKotlyar/Xiaomi-Dafang-Hacks#697]
Hi all

I was wondering if we could change the audio settings to monitor only human voice with the following settings? 

`highpass filter with 300 Hz and a lowpass filter with 2500 Hz`

If its already possible then how can I achieve it? thanks.

**Comment by nik0** [comment]
Did you play with the filters in audio settings ?

**Comment by bachoo786** [comment]
I did but which is the highpass and low pass filter they have a minimum of 8000 only
