### ISSUE TITLE
mqtt auto discovery not working

### ISSUE THREAD

**Issue by badabing2005** [EliasKotlyar/Xiaomi-Dafang-Hacks#698]
Hi,

I followed [this](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/integration/homeassistant/homeassistant.md) guide: to setup mqtt and integrate with Homeassistant.
I have Wyze Pan camera.

my mqtt.conf looks like this (minus the user / pass host port section)
```
# Define a location
LOCATION="camera"

# Define device name
DEVICE_NAME="wyze"

# Define the base topic used by the camera
# send a message to myhome/dafang/set with the payload help for help.
# Results will be placed in myhome/dafang/${command} or topic/dafang/error - so please subscribe topic/dafang/# for testing purposes
TOPIC="$LOCATION/$DEVICE_NAME"

# Define an autodiscovery prefix, if autodiscovery is desired:
AUTODISCOVERY_PREFIX="homeassistant"

# Define additional options for Mosquitto here.
# For example --cafile /system/sdcard/config/DST_Root_CA_X3.pem --tls-version tlsv1
# or use a special id to connect to brokers like azure
MOSQUITTOOPTS=""

# Add options for mosquitto_pub like -r for retaining messages
MOSQUITTOPUBOPTS=""

# Send a mqtt statusupdate every n seconds
STATUSINTERVAL=30

```
Monitoring MQTT topics I can see camera/wyze/* messages/topics
However I do not see homeassitant/* messages being published for mqtt discovery.

Home Assitant has   
discovery: true
discovery_prefix: homeassistant
under mqtt:

Is this  a bug or misconfiguration on my part?
Thanks

BB

**Comment by jmtatsch** [comment]
Have you tried turning it off and on again?

**Comment by badabing2005** [comment]
Thanks @jmtatsch for a quick response.
By turning it off and on again, if you mean re-starting Home Assistant, and mqtt-control and mqtt-status, then yes, multiple times.
If anything else, please kindly specify.

Thanks
BB

**Comment by jmtatsch** [comment]
Maybe some pidfile is stuck. Reboot the whole camera. The autodiscovery info is only sent once when mqtt-control service is starting up.

**Comment by jmtatsch** [comment]
can you manually run firmware_mod/scripts/mqtt-autodiscovery.sh and see if you get error or mqtt output?

**Comment by badabing2005** [comment]
Thank you very much for pointing me in the right direction,
First I ran it, and nothing happened.
Then I added -d to the first mosquitto_pub and quickly realized the problem.
Silly me, I had acl setup and never thought of allowing the user access to homeassistant/# 
I can't believe I fell for that.
Thanks for all your assistance in getting this resolved.

Have a good day.
BB
