### ISSUE TITLE
Motion tracking with Escam G02 (and siblings)

### ISSUE THREAD

**Issue by rradar** [EliasKotlyar/Xiaomi-Dafang-Hacks#700]
I wonder if **motion tracking is also available** with this cameras and the custom firmware from this repo **?**

Escam G02, Sannce I21AG, MixSight HX-I2110T2, WanScam HW0036, Digoo BB-M2, etc.

![image](https://user-images.githubusercontent.com/34582688/45750500-92e7db80-bc0f-11e8-913f-626a9f30f20b.png)

I just know that the stock software doesn't support it.

**Comment by codedmind** [comment]
The hack go escam g02 isn't possible...

**Comment by EliasKotlyar** [comment]
@rradar : We are now working on the general Escam Support. If you are still interessted on hacking it, please go to the following issue:
https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/795
