### ISSUE TITLE
XiaoFang 1S - Blue led, no connection possible

### ISSUE THREAD

**Issue by FrankReymenants** [EliasKotlyar/Xiaomi-Dafang-Hacks#701]
Hi, 

I'm stuck. after installing the demo.bin when I reboot without SD the blue led lights up for 5 sec then go orange. Then when I put the files from the firmware_mod folder and modify the wifi settings the camera boots and I get a steady blue led after a few minutes. 

However, I don't see the camera on my wifi and when I go to https://dafang  I get the error "This site can’t be reached" 

Any idea whats going wrong?

**Comment by masgar** [comment]
If you've already configured your camera with MiHome, it means that you're running original firmware and the camera is registered on the server. Try to flash it again maybe something went wrong. Check here [Issue #669](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/669)

**Comment by johnywar** [comment]
Hi @FrankReymenants 
you have solved the problem? I have the same problem and I don`t know what to do with it.

Thanks for any answer.
