### ISSUE TITLE
Accessing foreign servers????

### ISSUE THREAD

**Issue by calvo2** [EliasKotlyar/Xiaomi-Dafang-Hacks#706]
When looking at the config files what is the purpose of these:

gatewayip=193.169.4.1
ipaddr=193.169.4.81
loads_echo=1
netmask=255.255.255.0
serverip=193.169.4.2

This is from file uEnv.bootfromnand.txt and would appear to be routing traffic to a Russian ".ru" domain.

**Comment by badabing2005** [comment]
This is very discouraging, the main reason that I use this is to avoid practices like the above.
Would commenting out those lines be enough?
Or are there other parts of the code that is written to call home.

:(
