### ISSUE TITLE
how to manually start recording on Dafang cam?

### ISSUE THREAD

**Issue by TungstenE2** [EliasKotlyar/Xiaomi-Dafang-Hacks#707]
how to manually start recording on Dafang cam?

**Comment by sanjeewasam** [comment]
Could not find in the menu's but it could be triggered via motion detection.

If you use BlueIris or any software to control the camera you could easily do it

**Comment by TungstenE2** [comment]
thx, I know about motion detection but there is no record button to start it manually.
with software like tinycam you can record localy on the mobil, but this will go via the stream and this is very slow, only couple of fps.

**Comment by rsamboceu** [comment]
how do you setup the dafang to record to a network share?

**Comment by time2kite** [comment]
I have the same question. Is there any way to record to SD card:
a) by manual command
b) by motion detection alarm

Then, is there a way to access the SD card:
a) through browser
b) trough apps like Tinycam

**Comment by derekoharrow** [comment]
Recording is an option under the Services menu - you can start and stop it there.

**Comment by Zennixle** [comment]
Hi,
I have a Wyze V2 running. But activating the record button in Service menue creates only the directory in /system/sdcard/DCIM but no file will be created.
I tried to start the command
avconv -rtsp_transport tcp -y -i rtsp://0.0.0.0:8554/unicast -vcodec copy -c:a aac -strict experimental "/system/sdcard/DCIM/test.mov"
results in the same.
Any idea to get recording working?
Thanks / Zennix

**Comment by derekoharrow** [comment]
I have the same issue on a Neos Smartcam (Wyze v2 clone).

**Comment by Migz93** [comment]
Also have the same issue with Neos Smartcam.
Tried various different commands but they either don't work or just make a small file that never grows.
Would love to be able to have recording to local storage so that each camera can be self contained and isn't reliant on any other applications.

**Comment by Combie81** [comment]
Same issue on Neos here - recording creates the dir but after a reboot "NOK" is shown next to it and the service cant be started again.  Recording to network/local storage would be really helpful.

**Comment by chaoranxie** [comment]
Just setup my Wyze v2, recording seems to break for 2 reasons, but i sort of found the workaround, hope this helps.

1. if you get NOK, the issue might be because you are starting the recording before "rtsp-h264" is running, so double, that should be fixed via https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/commit/c388c86330c162ca7757d73a76528a3dfe30f47e 
2. if you set a username and password under the video section, this is different from `ssh` and the `HTTP Password` you will need to update the `0.0.0.0:8554/unicast` inside the `controlscripts/recording`
```
/system/sdcard/bin/busybox nohup /system/sdcard/bin/avconv -flags low_delay -fflags nobuffer -probesize 32 -i rtsp://0.0.0.0:8554/unicast -strict experimental -y -vcodec copy -an $RECORDING_PATH &>/dev/null &
```
to 

```
/system/sdcard/bin/busybox nohup /system/sdcard/bin/avconv -flags low_delay -fflags nobuffer -probesize 32 -i rtsp://USERNAME:PASSWORD@0.0.0.0:8554/unicast -strict experimental -y -vcodec copy -an $RECORDING_PATH &>/dev/null &
```
