### ISSUE TITLE
how to start timelapse on Dafang cam?

### ISSUE THREAD

**Issue by TungstenE2** [EliasKotlyar/Xiaomi-Dafang-Hacks#708]
how to start timelapse on Dafang cam?
![grafik](https://user-images.githubusercontent.com/39955685/45878801-aecfb680-bda2-11e8-8e60-d66db721e90a.png)

**Comment by jmtatsch** [comment]
Probably by starting the timelapse service

**Comment by TungstenE2** [comment]
damn, you are right. was searching in the right control menu, but there was no setting for this...

![grafik](https://user-images.githubusercontent.com/39955685/45880271-b80f5200-bda7-11e8-9e51-599c717582de.png)

**Comment by TungstenE2** [comment]
I find this hard sometime to find the right place for settings. 
Some are just in the control files, some are in the top menu and some are in the right control menu.
Some are in right and top menu, but not all.

**Comment by jmtatsch** [comment]
You are always welcome to improve things...

**Comment by TungstenE2** [comment]
would like to, but have limited programming skills... :-(

**Comment by jmtatsch** [comment]
To improve documentation, structure etc you don't need programming skills.
