### ISSUE TITLE
timelapse only single jpgs and corrupted files

### ISSUE THREAD

**Issue by TungstenE2** [EliasKotlyar/Xiaomi-Dafang-Hacks#709]
is this correct, that timelapse is only creating single jpg files?
if yes, this feature should be renamed to interval snapshots or similar.

I also found some 0kb files and files with errors in timelapse folder.
Is this know issue?
![grafik](https://user-images.githubusercontent.com/39955685/45885649-43dcaa80-bdb7-11e8-9361-ab71f86230bd.png)
![grafik](https://user-images.githubusercontent.com/39955685/45886051-5d322680-bdb8-11e8-9fbc-2de89180b2fd.png)

**Comment by jmtatsch** [comment]
Some broken images can happen from time to time. I guess that could come from motion trying to get the image at the same time.
