### ISSUE TITLE
Xiaofang Camera - No RTSP Server

### ISSUE THREAD

**Issue by nimdy2017** [EliasKotlyar/Xiaomi-Dafang-Hacks#710]
I bought a couple of Xiaofang cameras a couple of years ago and used the guide here https://github.com/samtap/fang-hacks to flash custom firmware to them. I thought I would buy two more cameras from New Frog, but I believe these are a newer model that isn't compatible with fang-hacks but should be compatible with Dafang-Hacks. I have followed the install guide, installed the cfw-1.1.bin bootloader and then flashed copied the contents of firmware_mod to the SD card. I am able to navigate the web interface but cannot get the RTSP service to run - it always shows a red 'NOK' mark against the service. 

I have looked around through the issues trying to find a fix - the themes seem to be low RAM (which my camera seems to have plenty of), incorrect sensor driver (not sure which my camera should have, but the SD card has sensor_jxf22.ko) or a new hardware variant which is not compatible with this modification (I really hope it isn't this one). 

Please could someone point me in the right direction for setting these two cameras up?

Thanks.

**Comment by sanjeewasam** [comment]
Had the same issue. What you need to do is go to config folder and rename rtspserver.conf.dist file rename to rtspserver.conf and start the camera. You should be now be able to have  RTSP

i have 3 cameras and none of them work perfectly (drop outs frequent). i checked with Synology surveillance station, blueiris server and zonminder and same result. This is not a good camera for RTSP but it could be used ignoring drop out issue. i have redeced the resolution to 640x368 and get 25fps  but still drop outs- but bit better. you could change the resolution in rtspserver.conf file

I may sell my camera's on ebay. i found p2P RTSP cameras supported out of the box cheaper on ebay. I have 6 panaromic camera bulbs and with no hacks RTSP work perfectly with no dropouts. These cost almost 50% of the Dafang cost. No SDcards or hacks make them much more better

**Comment by nimdy2017** [comment]
That doesn't seem to make a difference for me unfortunately.

**Comment by jmtatsch** [comment]
Maybe you have a jxf23 sensor.
I have extracted the driver for it from a newer firmware and added it to the main branch.
Please give it another shot.
