### ISSUE TITLE
Why buy these Xiomi Dafang and Xioafang and waste time. There are cheaper working out of the box

### ISSUE THREAD

**Issue by sanjeewasam** [EliasKotlyar/Xiaomi-Dafang-Hacks#711]
I know that this many be fault of the hack but should be of interest to new buyers. Do not get these cameras and waste time. They drop out. I am reducing resolution to 640x 368 not running full HD still the frames drop and video steram not available every 2-3 minutes. There are cheaper cameras coming out with P2P, RTSP and Blueiris supported out of the box.

This camera sucks with the hack too. I have 2 Dafang and1 xiaofang. All hacked but the RTSP stream drops every few minutes. This is discussed in many places so if you plan to use with something like BlueIris do not get them. I have spent countless hours to get this fix. I will be selling these on ebay (installing original firmware again) and getting cheaper Xmeye cameras that are compatible with BI and RTSP out of the box so no hacks nor SD cards required. 

I have 6 ICsee app compatible bulb cameras (almost 1/2 price of Dafang) and a forscam camera and they work great and no drop outs. Do not waste time with Dafangs

**Comment by jmtatsch** [comment]
Not an issue
