### ISSUE TITLE
IDEA: Have image snapshots delivered via MQTT

### ISSUE THREAD

**Issue by DanielMarcato** [EliasKotlyar/Xiaomi-Dafang-Hacks#716]
Does anybody know of a way to implement a periodic image snapshot stream via MQTT payloads? This would allow for easy remote access of the camera images without routing the rtsp stream over the internet.
All we would then need is an MQTT broker on the internet and an app to decode the payload into an image again.

Edit: For example I am already able to do this via the Internet by using the free online MQTT broker shiftr.io
![image](https://user-images.githubusercontent.com/11770874/45972192-63840500-c03b-11e8-8a9e-a5a6e6b798b0.png)
All that is missing is some image payload that can be triggered via an MQTT command similar to the LEDs.
(shiftr's free tier allows for payloads up to 100KB)

@keesschollaart81 @wojtulab do you guys already have a solution for this that can be used by beginners?

**Comment by jmtatsch** [comment]
We already support sending snapshots over mqtt on motion. Look at the OnMotion.sh to see how. You could use a cronjob to call that functionality in defined intervals.

**Comment by DanielMarcato** [comment]
@jmtatsch but isn't the onmotion snapshot only triggered "on motion" as the name suggests? Wouldn't a snapshot feature (=send one when triggered by an MQTT signal) be the general and thus "better" solution?
Personally I do not want to rely on the motion detection but rather have the camera send me a picture when I ask it to.

**Comment by jmtatsch** [comment]
I gave you a hint how to implement the desired functionality. Personally i do not think that this makes much sense so I won't implement or support it.

**Comment by DanielMarcato** [comment]
Well thanks for the hint - I'll try to come up with something. For what it's worth I think this functionality would help a lot of people out there and make this mod the go-to solution for easy to setup home surveillance. People could easily view images on demand even outside of their home network and would not need any additional hardware.

**Comment by DanielMarcato** [comment]
@jmtatsch ok I edited the timelapse.sh to have an MQTT send command just like the detectionON.sh
However I was wondering what would happen if the SD card becomes filled with the timelapse images. Is there a way to do a cyclical overwrite of the previous images? If I keep writing to my 16GB SD card I could do 7 days of timelapse before the card would be full.

**Comment by jmtatsch** [comment]
There is already functionality for that in detectionOn.sh if you look hard enough.

**Comment by DanielMarcato** [comment]
@jmtatsch sure there is - but right now it's limited to a single folder and not the structure the timelapse images are stored in. I could change it to suit my individual needs but feel like this should become part of the main branch with a "proper" implementation - not a hacky way that I as a non-linux developer will come up with. This is why i am bringing this to your attention.
