### ISSUE TITLE
What bitrate should I use for cam v2?

### ISSUE THREAD

**Issue by sergeymaysak** [EliasKotlyar/Xiaomi-Dafang-Hacks#717]
Hi,

I'd appreciate if anybody could share insights what is effective range of values for bitrate setting in web server (connected to resolution/video format/fps)? 
Default value 5000 kbps in 1280x720, 25 fps does not work for homebridge ffmpeg with enabled rtsp h.264 server at all. 
By trial (my cam is  Wyzecam v2.), I identified that 128kbps bitrate for 1600x900 still produces decent quality. I use SMART video format. I dont see difference if try 15 or 25 fps. Is it optimal setting (quality vs traffic)? what is better option?

Thanks )

**Comment by ortegafernando** [comment]
I hope the answer too.

**Comment by zagosch** [comment]
I am using 256kbps, 1600x900 and SMART format with 25 fps. For me it is giving me good quality images. 

My camera is the Xiaomi Xiaofang v2 (same as the wyzecam v2).
