### ISSUE TITLE
Which version of Xiaomi Xiaofang or Xiaofang 1S i have?

### ISSUE THREAD

**Issue by Cruiser79** [EliasKotlyar/Xiaomi-Dafang-Hacks#718]
Hello,

is it possible, without disassembling my camera, to find out, if i have a 1S with the needed T20 cpu?
I have two Xiaofang cameras. The first one i was unable to flash with this hack, so i used the https://github.com/samtap/fang-hacks When i connecting now to it via telnet it shows me the reason, i couldn't use this hack: It has a ARM cpu.

~ # cat /proc/cpuinfo 
Processor       : ARM926EJ-S rev 5 (v5l)
BogoMIPS        : 200.29
Features        : swp half fastmult edsp java 
CPU implementer : 0x41
CPU architecture: 5TEJ
CPU variant     : 0x0
CPU part        : 0x926
CPU revision    : 5

On buying my second cam, i explicitly order a 1S, but i will be sure, if it really is a 1S.
The information on the back are nearly the same.
The old ARM cam:
iSC5
FCC ID: SENISC5
CMITT ID: 2016DP5557
MAC: 34:CE:00...

The new 1S cam:
FCC ID: SENISC5
CMIIT ID: 2016DP5557
MAC: 78:11:DC...

Are there any optical differences to see the different version?
I remember that i read something with MAC adresses: 34: is ARM, 78: is T20. Is this an approved fact?

Thanks for your help.

**Comment by SomebodySysop** [comment]
These are T20 Xiaomi 1S cameras I ordered from AliExpress:

https://www.aliexpress.com/item/Xiaomi-Mijia-Xiaofang-Dafang-Smart-Camera-1S-1080P-New-Version-T20L-Chip-WiFi-Digital-Zoom-APP/1000005724812.html

They appear to be the same as yours.  They have the night sensor and work great (with iSpy Agent).

![20181021_124100](https://user-images.githubusercontent.com/41084665/47633098-f23be400-db09-11e8-82b4-64d31ec1b982.jpg)

**Comment by deadmaus3221** [comment]
How do you get rtsp working? I've been struggling for ages to get it working... I can see the video feed on chrome, but it's really choppy, like 1-2 fps, it's really bad. I tried rtsp://192.168.1.2:8554 on VLC, and I can't get anything... Any ideas?

**Comment by SomebodySysop** [comment]
rtsp://192.168.1.194:8554/unicast

Again, I am using iSpy.  I've connected 1 wyzecam and 2 xiaofangs.  Should work with VLC even better.  You might want to browse this issue to determine what settings will work best for you: https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/351

**Comment by kunikos** [comment]
> These are T20 Xiaomi 1S cameras I ordered from AliExpress:
> 
> https://www.aliexpress.com/item/Xiaomi-Mijia-Xiaofang-Dafang-Smart-Camera-1S-1080P-New-Version-T20L-Chip-WiFi-Digital-Zoom-APP/1000005724812.html
> 
> They appear to be the same as yours. They have the night sensor and work great (with iSpy Agent).
> 
> ![20181021_124100](https://user-images.githubusercontent.com/41084665/47633098-f23be400-db09-11e8-82b4-64d31ec1b982.jpg)

Hi SomebodySysop, I recently bought a couple T20 Xiaofang 1S as you have pictured. Would you be willing to share with me how you were able to downgrade the firmware and install a custom one? I'm assuming you're using the EliasKotlyar Xiaomi-Dafang-Hacks. 

I've been trying for several days (different sdcards, etc), but I can't seem to get the first demo.bin flashed. The Mihome App has upgraded the firmware of the cameras to 5.6.2.138. 

Every time I try to flash the cfm, after I restart the camera I never get the 'solid blue light', it still goes through the solid yellow then blinking yellow sequence.

Sorry if this is off-topic, but any assistance would be much appreciated. 

Also, I disassembled the camera to confirm it is a telegenic t20 chip.

**Comment by SomebodySysop** [comment]
Honestly, I followed the published instructions, step by step: https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/hacks/install_cfw.md

I used the Xiaomi XiaoFang T20 binary: https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/raw/master/hacks/cfw/xiaofang/cfw-1.0.bin

**Installation of the microSD bootloader** - Step 8:  I set timer and wait for at least 3 minutes before continuing to Step 9.  The base doesn't move on these cameras.

For 2nd camera, I actually just skipped Steps 9 and 10 and went on to installation of firmware.

**Installation of the new Firmware:** I copy the contents of firmware_mod to sd card, and I leave demo.bin on the card as well.  

I get blue light for a couple of seconds, then flashing yellow also.  Don't worry about it.  Look for camera on your network.  Mines always shows up as DAFANG. 

I seem to recall that I had a similar problem as you when trying to flash the wyzecam.  Kept getting that flashing light.  Turns out the bootloader was working, but camera wasn't connecting to router.  This issue helped me to resolve that: https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/642

Hope this helps.

**Comment by Amitcgartist** [comment]
How to get the original firmware of the xiaofang 1s?

**Comment by jmtatsch** [comment]
@Amitcgartist WtF, how many more issues do you want to spam about this instead of reading up on this?

**Comment by Amitcgartist** [comment]
sorry for the post. my device is not working. can you help me flashing to
the original firmware?

**Comment by Amitcgartist** [comment]
i am new to github.

**Comment by MrRonfo** [comment]
> Honestly, I followed the published instructions, step by step: https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/hacks/install_cfw.md
> 
> I used the Xiaomi XiaoFang T20 binary: https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/raw/master/hacks/cfw/xiaofang/cfw-1.0.bin
> 
> **Installation of the microSD bootloader** - Step 8: I set timer and wait for at least 3 minutes before continuing to Step 9. The base doesn't move on these cameras.
> 
> For 2nd camera, I actually just skipped Steps 9 and 10 and went on to installation of firmware.
> 
> **Installation of the new Firmware:** I copy the contents of firmware_mod to sd card, and I leave demo.bin on the card as well.
> 
> I get blue light for a couple of seconds, then flashing yellow also. Don't worry about it. Look for camera on your network. Mines always shows up as DAFANG.
> 
> I seem to recall that I had a similar problem as you when trying to flash the wyzecam. Kept getting that flashing light. Turns out the bootloader was working, but camera wasn't connecting to wifi This issue helped me to resolve that: #642
> 
> Hope this helps.
> 
> Update: Oh yeah, and make sure your sd card doesn't get corrupted. I bought 3 512 sd cards and they were all bad.

Hi there, I have a T20 Xiaomi 1S (iSC5). Followed the steps - it worked like a charm for me as well.
I've copied the mod firmware from Windows on an old 32GB SD Card, had no issue related to the card size.
Thanks @SomebodySysop!
Cheers,

**Comment by servant74** [comment]
NOOB question here:  Can I use the same firmware on my Xiaomi 1S ARM processor as the other processor camera?  My MAC address starts with 34:CE:00:... like somone elses I saw in a thread that seemed to indicate haing an ARM processor.  

Given that, I don't know wheter to go with the Xiaofang or Defang ?

**Comment by kittenarmy** [comment]
@servant74 for ARM version https://github.com/samtap/fang-hacks

**Comment by pvklink** [comment]
Hi ,

I also just bought the Xiaomi XiaoFan. At the back it says chine signs ending with1S and isc5 and seniscs. So i think i have the Xiaomi XiaoFang T20. 
firmware is 5.6.2.77

I formatted a 128kb disk with fat32 and 
copied cfw-1.0.bin to the sd and 
renamed it to demo.bin.

put in the sd card
Pluged in the power whie clicking on the setup for 10 seconds.
I waited for 3minutes. 
power off, sd card out and rebooted... after that is is blinking orange continous

I did this for 8 times, still the same!
anyone an idea?
Like to use this device in domoticz

**Comment by mckebabs** [comment]
> These are T20 Xiaomi 1S cameras I ordered from AliExpress:
> 
> https://www.aliexpress.com/item/Xiaomi-Mijia-Xiaofang-Dafang-Smart-Camera-1S-1080P-New-Version-T20L-Chip-WiFi-Digital-Zoom-APP/1000005724812.html
> 
> They appear to be the same as yours. They have the night sensor and work great (with iSpy Agent).
> 
> ![20181021_124100](https://user-images.githubusercontent.com/41084665/47633098-f23be400-db09-11e8-82b4-64d31ec1b982.jpg)



> > These are T20 Xiaomi 1S cameras I ordered from AliExpress:
> > https://www.aliexpress.com/item/Xiaomi-Mijia-Xiaofang-Dafang-Smart-Camera-1S-1080P-New-Version-T20L-Chip-WiFi-Digital-Zoom-APP/1000005724812.html
> > They appear to be the same as yours. They have the night sensor and work great (with iSpy Agent).
> > ![20181021_124100](https://user-images.githubusercontent.com/41084665/47633098-f23be400-db09-11e8-82b4-64d31ec1b982.jpg)
> 
> Hi SomebodySysop, I recently bought a couple T20 Xiaofang 1S as you have pictured. Would you be willing to share with me how you were able to downgrade the firmware and install a custom one? I'm assuming you're using the EliasKotlyar Xiaomi-Dafang-Hacks.
> 
> I've been trying for several days (different sdcards, etc), but I can't seem to get the first demo.bin flashed. The Mihome App has upgraded the firmware of the cameras to 5.6.2.138.
> 
> Every time I try to flash the cfm, after I restart the camera I never get the 'solid blue light', it still goes through the solid yellow then blinking yellow sequence.
> 
> Sorry if this is off-topic, but any assistance would be much appreciated.
> 
> Also, I disassembled the camera to confirm it is a telegenic t20 chip.

I would like to buy a Xiaofang camera which can be hacked and I see you even provided a link to Aliexpress. Under your link they state it is the new version with T20**L** processor. 
Could you please confirm that this is the one you got and it was possible to hack the new model?

Thanks

**Comment by SomebodySysop** [comment]
> > These are T20 Xiaomi 1S cameras I ordered from AliExpress:
> > https://www.aliexpress.com/item/Xiaomi-Mijia-Xiaofang-Dafang-Smart-Camera-1S-1080P-New-Version-T20L-Chip-WiFi-Digital-Zoom-APP/1000005724812.html
> > They appear to be the same as yours. They have the night sensor and work great (with iSpy Agent).
> > ![20181021_124100](https://user-images.githubusercontent.com/41084665/47633098-f23be400-db09-11e8-82b4-64d31ec1b982.jpg)
> 
> @SomebodySysop I would like to buy a Xiaofang camera which can be hacked and I see you even provided a link to Aliexpress. Under your link they state it is the new version with T20**L** processor.
> Could you please confirm that this is the one you got and it was possible to hack the new model?
> 
> Thanks

Yes, this is the camera I purchased:
https://www.aliexpress.com/item/Xiaomi-Mijia-Xiaofang-Dafang-Smart-Camera-1S-1080P-New-Version-T20L-Chip-WiFi-Digital-Zoom-APP/1000005724812.html

And yes, I did install Xiaomi-Dafang-Hack:   https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/718#issuecomment-434193796

**Comment by SomebodySysop** [comment]
> Hi ,
> 
> I also just bought the Xiaomi Xiao Fang. At the back it says chine signs ending with1S and isc5 and seniscs. So i think i have the Xiaomi XiaoFang T20.
> firmware is 5.6.2.77
> 
> I formatted a 128kb sd with fat32 and
> copied cfw-1.0.bin to the sd and
> renamed it to demo.bin.
> 
> put in the sd card
> Pluged in the power whie clicking on the setupbutton for 10 seconds.
> I waited for 3minutes.
> power off, sd card out and rebooted... after that is is blinking orange continous
> 
> I did this for 8 times, still the same!
> anyone an idea?
> Like to use this device in domoticz

It could be working.  Before you give up, look for the camera on your network -- even though the orange light is blinking.  I had the very same issue, but the camera was actually connected and working: https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/718#issuecomment-434193796

**Comment by kittenarmy** [comment]
> I waited for 3minutes.
> power off, sd card out and rebooted... after that is is blinking orange continous

The next step after waiting 3 mins whilst demo.bin flashing, and powering off, is to download the firmware image and put it on the first partition, then boot the camera.
https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/hacks/install_cfw.md#installation-of-the-new-firmware

**Comment by kittenarmy** [comment]
@SomebodySysop I am wondering what is different about T20L to T20. I cannot find any documentation about revisions. Perhaps we could learn something from the boot log, via serial port?

**Comment by SomebodySysop** [comment]
> > I waited for 3minutes.
> > power off, sd card out and rebooted... after that is is blinking orange continous
> 
> The next step after waiting 3 mins whilst demo.bin flashing, and powering off, is to download the firmware mod and put it on the first partition, edit wpa_supplicant.conf then boot the camera.
> https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/hacks/install_cfw.md#installation-of-the-new-firmware

I put the firmware on the sd card at the same time I put demo.bin on it.  This isn't in the official instructions, but after my first install, this is how I have always done it.  And, it always works.

**Comment by pvklink** [comment]
i solved my problems by buying a new modern sd-card 32gb class10 kingston.
lats things to solve:
- change the default root password of the cam
- let the cam sends a email when motion is detected..

somebody an idea how to solves these?

**Comment by pvklink** [comment]
problem solved, installed motion on raspberry

**Comment by SomebodySysop** [comment]
> problem solved, installed motion on raspberry

It would be good if you would describe what problem(s) you solved, and  how you solved it -- for the benefit of others who might have the exact same problem(s).

**Comment by pvklink** [comment]
Ok, i would like that my Xiaomi Xiao Fang 1S recognizes motions and gives alert. I did not get this working. So i searched for an solution outside of my cam. I installed motion software (i already use domoticz). With this software i can manage motions from different lan cams and record these motions on my nas and send notifications by triggering a device within domoticz! It works like a charm and i can use the rstp stream for this

**Comment by Klagio** [comment]
> These are T20 Xiaomi 1S cameras I ordered from AliExpress:
> 
> https://www.aliexpress.com/item/Xiaomi-Mijia-Xiaofang-Dafang-Smart-Camera-1S-1080P-New-Version-T20L-Chip-WiFi-Digital-Zoom-APP/1000005724812.html
> 
> They appear to be the same as yours. They have the night sensor and work great (with iSpy Agent).
> 
> ![20181021_124100](https://user-images.githubusercontent.com/41084665/47633098-f23be400-db09-11e8-82b4-64d31ec1b982.jpg)

Hi, mine is the same execpt in the first line (chinese characters= does not end with 1S

MAC address starts with 28: 6C:07

is mine ARM or T20??

Tried to install the hack, but at point 10, it never gets a solid blue.

Also I do not understand the phrase
"Format your microSD to FAT32. NTFS, EXFAT etc. won't work."

so if all the format do not work, how the hell I am supposed to format the SD card?

Very confusing to me

**Comment by voloszad** [comment]
@Klagio Only FAT32 works, none of the other (exFAT, NTFS, etc.)

**Comment by Klagio** [comment]
> @Klagio Only FAT32 works, none of the other (exFAT, NTFS, etc.)

Ok thanks.

Nothing I arrive at point 110 of installation, no blue led blinking (just yellow)

**Comment by stephandererste** [comment]
My Xiaofang has a MAC starting with 44 : 23 :7C
Does anybody know whether this will work here?
Or with samtap/fang-hacks?
Thanks :-)

**Comment by shanscendent** [comment]
> My Xiaofang has a MAC starting with 44 : 23 :7C
> Does anybody know whether this will work here?
> Or with samtap/fang-hacks?
> Thanks :-)

Hello Stephan, I just received a 1S too and I have the same starting MAC address as yours. Cracked it open just now and it says it's a T20 chip. Have not tried installing the hack yet though, will report back in a bit.

**Comment by Fromble** [comment]
I've just reveiced my xiaofang camera. It's a 1S with a mac adress starting with 44.23, i guess it's a normal T20

It came with firmware 5.6.2.77 (latest now = 5.6.2.138).
I've tried to install th micro-sf bootloader, format sdcard as fat32, copy .bin file, renamed to demo.bin. Restart with setup button pressed. 
Flashing doesn't work. No blue led's .  I have tried both 1.0 and 1.3 version's

It does work with the mi home app, so the camera itself seems ok.
Do i have the wrong version camera, what version bootloader can i install?

**Comment by raulrd2019** [comment]
> I've just reveiced my xiaofang camera. It's a 1S with a mac adress starting with 44.23, i guess it's a normal T20
> 
> It came with firmware 5.6.2.77 (latest now = 5.6.2.138).
> I've tried to install the micro-sd bootloader, format sdcard as fat32, copy .bin file, renamed to demo.bin. Restart with setup button pressed.
> Flashing doesn't work. No blue led's . I have tried both 1.0 and 1.3 version's
> 
> It does work with the mi home app, so the camera itself seems ok.
> Do i have the wrong version camera, what version bootloader can i install?

Ey. I recently installed in 1S (the same as you have, with same starting MAC ) the 1.1 demo version. I know it is for wyze versi6, but it works. 

Regards

**Comment by Fromble** [comment]
@raulrd2019 
Thanks, i will try version 1.1!

**Comment by raulrd2019** [comment]
> @raulrd2019
> Thanks, i will try version 1.1!

You welcome!

Say how it went when you do it.

Regards.

**Comment by Fromble** [comment]
@raulrd2019  
Still no luck. It looks like its not even trying to  flash demo.bin.   

The led flashes are exactly the sames as when i boot it up without a sd-card.  Maybe the xiaomi firmware is preventing the flash?
With which version firmware was your camera shipped?

**Comment by raulrd2019** [comment]
5.6.2.138.

Try to do all again.

**Comment by Fromble** [comment]
> 5.6.2.138.
> 
> Try to do all again.

That's the latest version. Maybe if i upgrade through the mi home app first.
Only, i've read that other people couldn't flash after the upgrade....
I'm not sure what to do. Do you know if a downgrade is possible afterwards?

**Comment by raulrd2019** [comment]
Yes. I used this one to restore stock firm.

https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/988

After that, you can update to the last version. (I do not tryed yet)

**Comment by zajaaczki** [comment]
Hi I bought Xiaofang 1S from here: [http://pl.aliexpress.com/item/32884030076.html?spm=a2g0o.productlist.0.0.5bb02e29GjuWco&algo_pvid=dcd281cd-1d61-42f3-843a-a264b8eea2d0&algo_expid=dcd281cd-1d61-42f3-843a-a264b8eea2d0-0&btsid=cd5cc173-872f-417c-b687-a2378bfad9cf&ws_ab_test=searchweb0_0,searchweb201602_7,searchweb201603_55](url)

And I have no idea what is the chip?

iSC5
5V 1A
FCC ID: SENISC5
CMIIT ID: 2016DP5557
MAC: 44:23:
??

**Comment by ferrexevi** [comment]
I have a xiaofang with T20 processor, I follow all the steps to the letter, and it doesn't work, it shows this "bug" https://www.youtube.com/watch?v=hKOdKisvz6Y

I have tried it with all possible combinations, without success.

**Comment by ferrexevi** [comment]
solved, the secret is to apply the hack with version 5.6.2.45 (original firm, without updates). Working great with synology surveillance station, very smooth 1920x1080 image, I activated swap in swap.config file, but I really don't know if it works just by doing that.

**Comment by kirilnedev** [comment]
Has anyone used a sniffer on the traffic of their cameras after installing the EliasKotlyar fang hack?
I saw in the configuration some hardcoded IP Addresses, behind which there are working servers in Russia. Was just curious whether this camera is sending some stuff to those servers? 
I am mostly using the samtap fang hacks which work fine for 2 of my cameras and was curious whether it's safe to go to EliasKotlyar version...

**Comment by DavidFFerreira** [comment]
@stephandererste did you get it working?

**Comment by DavidFFerreira** [comment]
after put all firmware_mod in sdcard, i have this issue in log

Initializing interface 'wlan0' conf '/system/sdcard/config/wpa_supplicant.conf' driver 'default' ctrl_interface 'N/A' bridge 'N/A'
Configuration file '/system/sdcard/config/wpa_supplicant.conf' -> '/system/sdcard/config/wpa_supplicant.conf'
Reading configuration file '/system/sdcard/config/wpa_supplicant.conf'
Failed to open config file '/system/sdcard/config/wpa_supplicant.conf', error: No such file or directory
Failed to read or parse configuration '/system/sdcard/config/wpa_supplicant.conf'.
Failed to add interface wlan0
: Cancelling scan request
: Cancelling authentication timeout

**Comment by DavidFFerreira** [comment]
Now I found what happens, but I got a page blank when I try to access to IP webpage

**Comment by barrymossel** [comment]
> solved, the secret is to apply the hack with version 5.6.2.45 (original firm, without updates). Working great with synology surveillance station, very smooth 1920x1080 image, I activated swap in swap.config file, but I really don't know if it works just by doing that.
> 
> A picture is worth 1000 words: https://ibb.co/f936VzV

Where did you buy that one?

**Comment by ferrexevi** [comment]
> > solved, the secret is to apply the hack with version 5.6.2.45 (original firm, without updates). Working great with synology surveillance station, very smooth 1920x1080 image, I activated swap in swap.config file, but I really don't know if it works just by doing that.
> > A picture is worth 1000 words: https://ibb.co/f936VzV
> 
> Where did you buy that one?

Aliexpress 👍

**Comment by Daniil145** [comment]
It worked. Applied firmware and demo.bin at the same time.

**Comment by HcNguyen111** [comment]
> It worked. Applied firmware and demo.bin at the same time.
> MAC:34:CE
> iSC5
> 2016DP5557

I have the same device. Can you detail the steps you took?

**Comment by Arkady23** [comment]
> It worked. Applied firmware and demo.bin at the same time.
> MAC:34:CE
> iSC5
> 2016DP5557

I did it, too. But once you pull out the sd card and work without it, you'll have to repeat everything from the beginning. I removed the sd card, turned on the camera without the card, worked, then put it back on and now the camera does not connect with WiFi. We need to load demo. bin again. You can't pull out the SD card. :-( I want to put the camera in the yard, and it writes without interrupting one file in a row for several hours. Such a file becomes unaffordable. The Chinese made it very convenient. One record — 1 minute. One torment with this firmware. 
Apparently, the Chinese have time to load something into the camera.
Elias @EliasKotlyar, how do I opt out of the suggested recording method? I want to make minute recordings and view them through a web server, like I did on Yi-home. Why is it so cool to break everything?
