### ISSUE TITLE
Script that records video on motion detection.

### ISSUE THREAD

**Issue by adamryczkowski** [EliasKotlyar/Xiaomi-Dafang-Hacks#719]
Please put the following script to the Wiki, or instruct me, how to do that.

--------------

Put the following script under `/system/sdcard/config/userscripts/motiondetection/triggered_recording.sh`. Turn on rtsp server (on by default) and also make sure, that the motion detection is also turned on (by default it is as well). 

When the camera detects motion, the script starts recording the file in the format like `DCIM/2018-09/2018-09-27_19.34.mjpeg`. When motion ceases, the recording is stopped. 

```
#!/bin/sh

if [ "$1" == "on" ]; then
    mkdir -p /system/sdcard/DCIM/`date +%Y-%m`
    busybox nohup /system/sdcard/bin/avconv -v quiet -rtsp_transport tcp -y -i rtsp://0.0.0.0:8554/unicast  -vcodec copy -c:a aac -strict experimental /system/sdcard/DCIM/`date +%Y-%m`/`date +%Y-%m-%d_%H.%M`.mjpeg & 
    pid=$!
    echo $pid>/root/avconv.pid
fi

if [ "$1" == "off" ]; then
    if [ -f /root/avconv.pid ]; then
        pid=$(cat /root/avconv.pid)
        kill $pid
        rm /root/avconv.pid
    fi
fi
```

**Comment by dmolner** [comment]
Hello,
Not work in my cam.
Is possible record video before motion?

**Comment by adamryczkowski** [comment]
Indeed the recording misses the first few seconds, and I do not know what to do about it. The reason is that the `avconv` needs time to load and "warmup".

**Comment by goermezer** [comment]
You can speed up the warm up sequence in ffmpeg with -probesize and -analyzeduration. Perhaps this could also work for avconv:

-probesize 2M and -analyzeduration 2M

**Comment by reichley** [comment]
I've tried the script and it doesn't end up saving a file (but creates a folder and looks as if it ran the script when I run the `top` command). What resolution do you run your camera at?

**Comment by adamryczkowski** [comment]
My resolution is much smaller than the fullHD. Perhaps that is the problem. Compressing full HD frames may by too expensive.

**Comment by pax0707** [comment]
For me it created DCIM/1105FANG/MOV_1922.mov and that's it.

**Comment by netRunner0** [comment]
Any idea why it doesn't work? Dafang 2S Camera

**Comment by Ch1zh** [comment]
Ping

**Comment by ex725** [comment]
Recording starts but doesn't stop.
How can I stop the recording after the motion is received?

#!/bin/sh

if [ "$1" == "on" ]; then
    mkdir -p /system/sdcard/DCIM/`date +%Y-%m`
    busybox nohup /system/sdcard/bin/avconv -v quiet -fflags +discardcorrupt -i rtsp://192.168.1.112:8554/unicast  -vcodec copy -c:a aac -strict experimental /system/sdcard/DCIM/`date +%Y-%m`/`date +%Y-%m-%d_%H.%M`.h264 & 
    pid=$!
    echo $pid>/root/avconv.pid
fi

if [ "$1" == "off" ]; then
    if [ -f /root/avconv.pid ]; then
        pid=$(cat /root/avconv.pid)
        kill $pid
        rm /root/avconv.pid
    fi
fi

**Comment by ex725** [comment]
Recording starts but doesn't stop
how can I stop recording after the action is over?


#!/bin/sh

if [ "$1" == "on" ]; then
    mkdir -p /system/sdcard/DCIM/`date +%Y-%m`
    busybox nohup /system/sdcard/bin/avconv -v quiet -fflags +discardcorrupt -i rtsp://192.168.1.112:8554/unicast  -vcodec copy -c:a aac -strict experimental /system/sdcard/DCIM/`date +%Y-%m`/`date +%Y-%m-%d_%H.%M`.h264 & 
    pid=$!
    echo $pid>/root/avconv.pid
fi

if [ "$1" == "off" ]; then
    if [ -f /root/avconv.pid ]; then
        pid=$(cat /root/avconv.pid)
        kill $pid
        rm /root/avconv.pid
    fi
fi
