### ISSUE TITLE
camera became unresponsive after a week of normal performance

### ISSUE THREAD

**Issue by sergeymaysak** [EliasKotlyar/Xiaomi-Dafang-Hacks#721]
Hi All,

I've installed latest custom fw on my wyze v2 cam a week ago. The start was very promising. i've got 1600x900 rtsp h264, integration with synology, camera in home assistant and mqtt switches and snapshot camera on motion and ffmpeg cam for homebridge. Great! and really working.

However, device became very unresponsive after 6 days. it looks like cpu is under heavy load constantly. web ui is mostly unaccessible, video streams as well (i'm not able to open rtsp stream in vlc - vlc hangs). I've tried to inspect contents of sdcard - its mostly empty. i.e there is nothing that close to fill up the card. I use 64Gb sd card.
Reboot does not help. So far I try to detect what makes cpu busy but w/o no luck so far. Any advice where to look are welcome.

Also tried to:
- disable motion detection completely
- disable audio
- change video resolution to lower with less fps
- disable video recording

Nothing helps. (

If anybody knows how to fix this, please share.

Best, Sergiy

**Comment by goermezer** [comment]
I recognized similar behaviors. But not that bad. In my case sometimes the stream hangs. And so does ffmpeg, which records the stream from another machine. I even switched off logging, which does happen from /system/sdcard/controlscripts/rtsp-h264 to the sdcard.

When I have updated the cam through web update, it gets better for me. But after a couple of days I get the same issues again.

**Comment by saipsa** [comment]
restarting the cam, in some cases, the router, usually fixes it for me.

**Comment by sergeymaysak** [comment]
I've extracted sdcard and run First Aid for it on mac at disk utility. It found a lot of issues in file systems. Well, I've just reformatted sdcard again and copied contents of `firmware_mode` on it again.

It looks like helped to web UI. 
But video stream is lost just after minute of so of work after restart.
My logcat shows the following after restart:

Content of logcat

D/IMP-ISP (  332): ~~~~~~ IMP_ISP_Open[267] ~~~~~~~
I/NCU     (  332): NCU Debug mode:0
E/NCU     (  332): open /etc/sensor/jxf22_nd.bin failed: No such file or directory
D/System  (  332): IMP_System_Init SDK Version:3.12.0-6f2a7d4 built: Mar 20 2018 18:53:49
D/System  (  332): system_init()
D/System  (  332): Calling DSystem
D/System  (  332): Calling FrameSource
D/System  (  332): [ignored]read /proc/cpuinfo ret is NULL
D/System  (  332): Calling IVS
D/System  (  332): Calling OSD
I/Alloc Manager(  332): MEM Alloc Method is kmalloc
D/KMEM Method(  332): CMD Line Rmem Size:16777216, Addr:0x07000000
D/KMEM Method(  332): alloc->mem_alloc.method = kmalloc
D/KMEM Method(  332):  			alloc->mem_alloc.vaddr = 0x756dc000
D/KMEM Method(  332):  			alloc->mem_alloc.paddr = 0x07000000
D/KMEM Method(  332):  			alloc->mem_alloc.length = 16777216
I/Alloc Manager(  332): MEM Manager Method is continuous
D/System  (  332): Calling Encoder
I/Encoder (  332): IMP Alloc BS Buf size:2073600
D/Encoder (  332): ispmem Size:8388608, Addr:0x06800000
I/Encoder (  332): bank-0 paddr=06800000 vaddr=74edc000 size=7172608
I/Encoder (  332): bank-1 paddr=06ed7200 vaddr=755b3200 size=1216000
D/System  (  332): Calling Decoder
D/System  (  332): Calling FB
D/Encoder (  332): channel-1 buffer malloc size=2164224 addr=0x724b0008
D/Encoder (  332): channel-0 buffer malloc size=6492672 addr=0x71c67008
I/Encoder (  332): chn-0 NCU Info vaddr=74edc000 paddr=06800000 size=729600 backv=74f8e200 backp=068b2200 outv=750f2600 outp=06a16600 total_size=3648000
D/System  (  332): system_bind(): bind DST-OSD-0(4.0.0) to SRC-Framesource-0(0.0.0)
D/System  (  332): system_bind(): bind DST-Encoder-0(1.0.0) to SRC-OSD-0(4.0.0)
D/System  (  332): system_bind(): bind DST-IVS-0(3.0.0) to SRC-Framesource-0(0.0.0)
I/Framesource(  332): [chn0]: width = 1600 height = 900
E/VBM     (  332): VBMCreatePool()-0: w=1600 h=900 f=842094158
E/VBM     (  332): VBMCreatePool()-0: pool->config.fmt.fmt.pix.sizeimage=2160000 sizeimage=2188800
E/VBM     (  332): VBMCreatePool()-0: sizeimage=2188800
I/VBM     (  332): PoolId:0, frame=0xd7f3a0, frame->priv=0xd7f3c8, frame[0].virAddr=75e5f000, frame[0].phyAddr=7783000
I/VBM     (  332): PoolId:0, frame=0xd7f3d0, frame->priv=0xd7f3f8, frame[1].virAddr=76075600, frame[1].phyAddr=7999600
I/VBM     (  332): PoolId:0, frame=0xd7f400, frame->priv=0xd7f428, frame[2].virAddr=7628bc00, frame[2].phyAddr=7bafc00
I/ai      (  332): AI Enable: 1
I/Encoder (  332): framePriv->i_fps_num=25, framePriv->i_fps_den=1
I/ai      (  332): AI Enable Chn: 1-0
I/ai      (  332): EXIT AI Enable Chn: 1-0
I/ai      (  332): AI Set Vol: 70
I/ai      (  332): AI Get Vol: 70
I/ai      (  332): AI HPF Enable
I/ai      (  332): HPF version is: Ingenic High Pass Filter 1.1.0
I/ai      (  332): AI_EnableAec:AiDevId = 1,aiChn = 0,AoDevId = 0,aoChn = 0
I/ai      (  332): AI AEC ENABLE
I/ai      (  332): AI NS ENABLE: mode = 1
I/ai      (  332): AI HPF Enable
I/ai      (  332): HPF version is: Ingenic High Pass Filter 1.1.0
I/ai      (  332): AI_EnableAec:AiDevId = 1,aiChn = 0,AoDevId = 0,aoChn = 0
I/ai      (  332): AI AEC ENABLE
I/ai      (  332): AI NS ENABLE: mode = 1
E/ai      (  332): AI NS already enable

I've found it was already discussed here: https://github.com/EliasKotlyar/Xiaomi-Dafang-Software/issues/21

Not sure what's next...

**Comment by sergeymaysak** [comment]
closing this as resolved by repairing and reformatting sdcard.
