### ISSUE TITLE
Assistance with adding login/password to RTSP 

### ISSUE THREAD

**Issue by greavette** [EliasKotlyar/Xiaomi-Dafang-Hacks#722]
Hello,

I've successfully installed dafang-hacks firmware on my wyze cam pan.  Thank you for making this firmware available for our use.

I'm still finding my way around using dafang-hacks.  I can see from the wepbage my RTSP serves up that I initially was asked to login but since that first login I've not been asked again. I'd like to make sure my RTSP webpage always asks for a login when someone tries to access that page (we host it only locally with access blocked at our firewall but I still want to make the webpage password protected).  How do I add a login/password? 

I've read the following from Issues:
https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/27

This page suggests I issue the following command on my wyze cam terminal:

/system/sdcard/bin/busybox nohup /system/sdcard/bin/v4l2rtspserver-master -fMJPG -U admin:pass &>/dev/null &

I'm assuming I change admin;pass to what ID and password I want to use.  

When I issued this command nothing happened in that my feed was still opened and no password was issued after I re-opened my webpage.  I then rebooted the wzye cam pan device but again my webpage did not ask for a user and password to see the feed.

Could someone point me in the right direction here on how to put this in place.

Thank you.

**Comment by jmtatsch** [comment]
>I can see from the wepbage my RTSP serves up that I initially was asked to login but since that first login I've not been asked again.
I cannot decipher what you mean by that.

The http server is always password protected. You probably just saved the credentials to your keychain.
The rtsp server is not password protected by default.
You can set a password via Manage->Settings->Video Settings.

**Comment by ortegafernando** [comment]
Hi, does ssh and ftp server let to change root's password as RTSP does ?

**Comment by jmtatsch** [comment]
@ortegafernando No understand questione.

**Comment by ortegafernando** [comment]
> @ortegafernando No understand questione.

Hi, is there any config file to change SSH and FTP server's root user's passwords? 

Thanks

**Comment by Shaker1978** [comment]
Use the standard Linux command "passwd" in a SSH shell to change root's password independently from the webUI's password.
