### ISSUE TITLE
Compile fanghacks

### ISSUE THREAD

**Issue by LeVuHoang** [EliasKotlyar/Xiaomi-Dafang-Hacks#726]
Hi all,
Could you please tell me steps to compile v4l2rtspserver?
I tested with a simple program but it doesn't work
`arm-linux-gnueabi-gcc -mcpu=arm926ej-s test.c
`
If I use -static flag, camera says "kernel too old", if I use dynamic library, there is a missing library.

v4l2rtspserver is more stable than snx_rtsp_server.

Xiaofang old version:

> Processor       : ARM926EJ-S rev 5 (v5l)
> BogoMIPS        : 200.29
> Features        : swp half fastmult edsp java
> CPU implementer : 0x41
> CPU architecture: 5TEJ
> CPU variant     : 0x0
> CPU part        : 0x926
> CPU revision    : 5
> 
> Hardware        : SONiX SN98600 Development Platform
> Revision        : 9302014
> Serial          : 000014900827b000

**Comment by nik0** [comment]
Not sure what you want to do, but this is not the correct processor type. Yours is ARM, Dafang is T20 (MIPS)

**Comment by LeVuHoang** [comment]
Yes I know, but there is no where to show me how to compile ARM 32bit processors.

I fixed it btw by using snx_snapshot.

Thanks
