### ISSUE TITLE
detectionOn.sh - externalize filename to motion.conf

### ISSUE THREAD

**Issue by claud9999** [EliasKotlyar/Xiaomi-Dafang-Hacks#727]
As I have multiple cameras, I prefer to have the files generated by motion detection to have the hostname in the filename. Also I don't need year or month. Every time I do an update, I have to hand-edit detectionOn.sh--I suggest the "filename" definition be externalized to motion.conf so updates don't change this behavior.

**Comment by Dopeyr** [comment]
Hi, I think the PR attached should cover this request.
