### ISSUE TITLE
My RSP services are never working fine. Why?

### ISSUE THREAD

**Issue by Pharizna** [EliasKotlyar/Xiaomi-Dafang-Hacks#73]
I've just installled the last mod firmware and I don't know why I can't start any RSP service :(

![image](https://user-images.githubusercontent.com/3939655/35875694-5ceacf2e-0b70-11e8-9b4e-4ef37ebb3177.png)
![image](https://user-images.githubusercontent.com/3939655/35875597-1583a750-0b70-11e8-9734-233d689b4aaf.png)
![image](https://user-images.githubusercontent.com/3939655/35875651-38a5d898-0b70-11e8-98ca-a8ce8fc3b9f2.png)

**Comment by shinebar1001** [comment]
The Problem is, that there is one rtsp-server in the run.sh - you have to enable autostart and reboot. 
or just remove this leine from run.sh

```
#Start
/system/sdcard/bin/busybox nohup /system/sdcard/bin/v4l2rtspserver-master -D "DafangHacks %I:%M:%S %d.%m.%Y" -d UP &>/dev/null &

```

I'll submit updated scripts on the weekend.

**Comment by shinebar1001** [comment]
Here is a quick fix for that problem.  I'll submit a clean version with configurable OSD on the weekend.

**Comment by Pharizna** [comment]
Thank you.

It works... at least the tsp-server is running. But I can't see any "movement" in the HA screen using this code. 

  - platform: ffmpeg
    name: Dafang
    input: -rtsp_transport tcp -i rtsp://192.168.1.73:8554/unicast

**Comment by Pharizna** [comment]
Using rtsp-h264 (without-segmentation) sometimes appears a static image... but never with movement :(
![image](https://user-images.githubusercontent.com/3939655/35879299-1d0e79ea-0b7b-11e8-8583-34f5ef4702b7.png)

**Comment by Pharizna** [comment]
VERY STRANGE the contents of all log files:
==> /var/log/boa.log <==
192.168.1.88 - - [06/Feb/2018:19:19:44 +0000] "GET /cgi-bin/all.cgi HTTP/1.1" 200 11 "-" "curl/7.52.1"
192.168.1.1 - - [06/Feb/2018:19:19:54 +0000] request "(null)" ("(null)"): connection timed out
192.168.1.1 - - [06/Feb/2018:19:19:54 +0000] request "(null)" ("(null)"): connection timed out
192.168.1.1 - - [06/Feb/2018:19:19:54 +0000] request "(null)" ("(null)"): connection timed out
192.168.1.1 - - [06/Feb/2018:19:19:54 +0000] "-" 408 0 "-" "-"
192.168.1.1 - - [06/Feb/2018:19:19:54 +0000] "-" 408 0 "-" "-"
192.168.1.1 - - [06/Feb/2018:19:19:54 +0000] "-" 408 0 "-" "-"

192.168.1.88 is my RPi3 and 192.168.1.1 my PC

**Comment by shinebar1001** [comment]
As you mentioned problems with HA in another thread as well there might be a problem with the ffmpeg of HA? rtsp-h264 is exactly the one that ist started in the run.sh (the OSD-one). What happens, when you switch to mjpeg?

Concerning the Logfiles: indeed, these are strange requests. The /cgi/bin/all.cgi has a response code 200, which means "OK" - in the original dafang-hacks there is no all.cgi, so how did that one got on the cam?

And what is you PC doing? These 6 lines are all timeouts. The logfiles on the dafang only show what is happening, and everything is alright (when you uploaded the all.cgi...)

**Comment by Pharizna** [comment]
Switching to mjpeg (service): Same problem and image not available

![image](https://user-images.githubusercontent.com/3939655/35883152-a21854ac-0b86-11e8-85d7-26fab4c441d1.png)

The best way is to use:

  - platform: mjpeg
    name: Dafang
    mjpeg_url: http://192.168.1.73:8554/unicast.mpd
    still_image_url: http://192.168.1.73/cgi-bin/currentpic.cgi?width=1280&height=720 

because at least I have a picture (but not any video)

 /cgi/bin/all.cgi is a script to send to HA the camera status 

sensor.dafang_blue_led_status	1
sensor.dafang_ir_cut_status	1
sensor.dafang_ir_led_status	1
sensor.dafang_rtsp_status	1
sensor.dafang_status	1,0,1,1,1
sensor.dafang_yellow_led_status	0

In the PC, I'm trying (with F5) to refresh the screen to have a new picture/video ... but withoutany  sucess

**Comment by shinebar1001** [comment]
Please change the mjpeg_url to http://192.168.1.73:8554/unicast and try again. 

Okay, all.cgi is clear. The timeouts need to be investigated further: can you determine the image source in the HA page?

**Comment by Pharizna** [comment]
More errors in the LOG:

./scripts.cgi: line 66: can't create /system/sdcard/config/autostart/rtsp-mjpeg: nonexistent directory
./scripts.cgi: line 66: can't create /system/sdcard/config/autostart/rtsp-mjpeg: nonexistent directory

**Comment by Pharizna** [comment]
Changed the mjpeg:url from unicast.mpd to unicast ... Same problem :(

I can't understand: "determine the image source in the HA page" 

Are you looking for the image URL?  http://my.domain.net/api/camera_proxy/camera.dafang?token=34a1823b73e389519c1a86befa08302908aca075955599d5670bb7e2ffd81cf5&time=1517951889280

**Comment by shinebar1001** [comment]
> ./scripts.cgi: line 66: can't create /system/sdcard/config/autostart/rtsp-mjpeg: nonexistent directory
./scripts.cgi: line 66: can't create /system/sdcard/config/autostart/rtsp-mjpeg: nonexistent directory

fixed that one #75 

Hm. When HA doesn't show the MJPEG-Stream as well - can you please check with VLC (videolan.org?) the URL should be right.

Concerning the timeouts: I found them in my log too. So, no problem with HA.

**Comment by Pharizna** [comment]
Working fine in VLC  using rtsp://192.168.1.73:8554/unicast and rtsp-h264 service running.

**Comment by shinebar1001** [comment]
So, this means everything is okay with the camera (I assume that the Snapshot is working as well).  So we need to know what HA expects as input - the mjpeg stream is totally fine (you did switch the camera back to mjpg?)

**Comment by Pharizna** [comment]
Pictures are not perfect neither :(

![e794c164-8a90-4c4e-88be-114739fdd51f](https://user-images.githubusercontent.com/3939655/35901267-169ac5cc-0bd6-11e8-831b-7e0a074517a3.jpeg)

**Comment by jmtatsch** [comment]
Let's continue figuring this out in your newer thread.
