### ISSUE TITLE
Bricked Xiaofang camera

### ISSUE THREAD

**Issue by calania** [EliasKotlyar/Xiaomi-Dafang-Hacks#730]
Hello, I just tried installing this hack on my xiaomi Xiaofang camera. I followed the instructions and flashed the micro sd card bootloader. My led is now blinking yellow and nothing happens when I insert the sd card with the hack on. Mi home can see the camera but not connect to it. I have tried pressing the setup button which previously said something in Chinese but now nothing happens. It there any way to fix this?

**Comment by kakarot84** [comment]
Did you checked the log file (startup.log), does it write anything it in? If not, then the bootloader might not be installed properly.
