### ISSUE TITLE
MQTT Scripts

### ISSUE THREAD

**Issue by DooDip** [EliasKotlyar/Xiaomi-Dafang-Hacks#732]
I just purchased a Wyze V2 and uploaded the Dafang-Firmware. I couldn't get the MQTT scripts to work from the firmware_mod/scripts folder. When I run them from the webpage (clicking services-->start) nothing would happen.

I remoted into the camera with SSH and tried running the scripts from there and I kept getting an error from using the firmware_mod/bin/mosquitto_pub.bin file. I tried adjusting permissions etc and it still gave me an error.

The error is 
`/system/sdcard/bin/mosquitto_sub.bin: can't load library 'libmosquitto.so.1'`

From there I turned off the camera, unplugged the SDcard and plugged it into my computer and manually edited each MQTT script under firmware_mod/scripts.

I replaced the lines that read

`/system/sdcard/bin/mosquitto_sub.bin -v -h "$HOST" -p "$PORT" -u "$USER" -P "$PASS" -t "${TOPIC}"`

with

`mosquitto_pub -h 192.168.X.X -p 1883 -t "${TOPIC}"`

and MQTT is working flawlessly now. Is this expected behavior? Would this happen if the mqtt.conf file was wrong or corrupted? What is the mosquitto_pub.bin file used for?

**Comment by jmtatsch** [comment]
Mosquitto_sub without the bin is just a little script making sure the necessary library’s are in the environment before running the actual bin to mitigate your error #1
