### ISSUE TITLE
Website not starting

### ISSUE THREAD

**Issue by gossamer2** [EliasKotlyar/Xiaomi-Dafang-Hacks#734]
I Just installed this firmware for the first time and the website is not starting up. It's a Xiaomi Dafang Pan camera.

At the end of the startup.log file, it shows:

```
Initialized gpios
Determined image sensor model as jxf22
dropbear:
bftpd:
lighttpd:
Startup finished!
```
I took a look through the run.sh, and found the command to start lighttpd:
```
[root@CAMPTZ1:sdcard]# sh /system/sdcard/bin/lighttpd -f /system/sdcard/config/lighttpd.conf
/system/sdcard/bin/lighttpd.bin: can't load library 'libssl.so.45'
```
So it looks like it's not finding the library file, although it does exist in /system/sdcard/lib but I'm assuming because it doesn't exist in /lib, it won't load?

Anyone have any ideas?

**Comment by gossamer2** [comment]
Got it fixed. It looks like the "/system/sdcard/bin/lighthttp" file has CR's at the end of each line which was messing things up. Removed them and now it's working.

**Comment by jmtatsch** [comment]
Did you touch it with windows?

**Comment by gossamer2** [comment]
Nope. Didn't touch it. The last modified file date was the same as the rest of the files and git is not detecting any pending changes. Re-cloned on Linux machine and there were no ^M's so I'm not sure how they got in there, and just on that one file. The rest of the files appeared to be ok. Just a weird mystery.
