### ISSUE TITLE
documentation change

### ISSUE THREAD

**Issue by adamf663** [EliasKotlyar/Xiaomi-Dafang-Hacks#736]
Twice when flashing  wyze v2s, I couldn't use a 64gb fat32 card partitioned as a single partition.
First time around, I found an 8gb card and was successful. 
This time I didn't have any small cards handy, so I tried partitioning the card with a single 2gb fat32 partition, the rest unused space.  That was also successful.

Document this?

**Comment by jmtatsch** [comment]
Should be already documented a couple of times. If it is missing somewhere where you'd expect it or it is not understandable a PR towards the documentation would be appreciated.

**Comment by RolfKoenders** [comment]
There is a [community tip](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/hacks/install_cfw.md#community-tips) which points to use smaller cards. This tip helped me at least and seems to be the reason for most problems. Maybe documenting this at the start of the page as the first step of the installation process is more clear?
