### ISSUE TITLE
New auto night mode not working

### ISSUE THREAD

**Issue by ortegafernando** [EliasKotlyar/Xiaomi-Dafang-Hacks#740]
Hi, I have just update autonight mode and tit works only when I navigate to [https://IP/sw_night_configure.html](https://IP/sw_night_configure.html)

Otherwise, my dafang camera stays into day mode. 

auto-night-detection service is running ok in my "services" web page.

I dont know where to check any log to paste here.
(I made the update yesterday throught webpage update process)

**Comment by columbusgeek** [comment]
I had the same issue. I thought it was just me.

**Comment by jmtatsch** [comment]
Can you manually run the binary?

**Comment by ortegafernando** [comment]
Hi, I have logged in trought putty SSH session.
After that, go to \system\sdcard\bin and execute:

"autonight -v" outputs (with light):
```
[root@DAFANG:bin]# autonight -v
Current value: 829.88
Current value: 828.32
Current value: 823.16
Current value: 817.16
Current value: 818.84
Window (5) Avg: 823.47
Current value: 811.76
Window (5) Avg: 819.85
Current value: 812.12
Window (5) Avg: 816.61
Current value: 832.52
Window (5) Avg: 818.48
Current value: 814.52
Window (5) Avg: 817.95
Current value: 811.52
Window (5) Avg: 816.49
```

"autonight -v" outputs (without light but with tv and laptop):
```
[root@DAFANG:bin]# autonight -v
Current value: 844.88
Current value: 857.12
Current value: 854.84
Current value: 851.12
Current value: 817.76
Window (5) Avg: 845.14
Current value: 823.52
Window (5) Avg: 840.87
Current value: 858.44
Window (5) Avg: 841.14
```
"autonight -v -S" outputs (without light but with tv and laptop):
[root@DAFANG:bin]# autonight -v -S
Starting software method using
jitter_percent = 3
eq1_user_exposure = 1200000
eq2_user_exposure = 930000
eq2_user_iridix = 14
eq2_count = 10
eq3_user_wb = 3000
eq3_user_iridix = 17
eq3_count = 8
sec_wait = 3
Night Mode Disabled
jitter active
mode switch wait active
mode switch wait active
mode switch wait active
Switching to night new exp=1277001
Night Mode Enabled
jitter active
mode switch wait active
mode switch wait active
mode switch wait active
Eq2 wait_count active exp=904159 iridix=13
Eq2 wait_count active exp=901129 iridix=13
Eq2 wait_count active exp=901730 iridix=13
Eq2 wait_count active exp=901733 iridix=13
```

And it works perfectly, I have heard the "click" when I just see "Night Mode Enabled"

After a little time, I have switched on the light again and .... works perfect.

NOTE: It is true that with TV and Laptop, binary keeps on enabling and disabling night mode, may be because of I am just in the limit. I don't know.

But .... suddenly the putty output windows stop. 
CTRL+C and running again "autonight -v -S" but same problem. This is the output:
```
[root@DAFANG:bin]# autonight -v -S
Starting software method using
jitter_percent = 3
eq1_user_exposure = 1200000
eq2_user_exposure = 930000
eq2_user_iridix = 14
eq2_count = 10
eq3_user_wb = 3000
eq3_user_iridix = 17
eq3_count = 8
sec_wait = 3
Night Mode Disabled
jitter active
mode switch wait active
mode switch wait active
mode switch wait active
```

I am not an expert, but tell me what you want with the binary. 
Web page doesnt say anything about read only usual problem. 

After I have check swtich off again the light WITHOUT running the binary and... no luck, no autonight mode.

With "top" command, I can see this process: /system/sdcard/bin/autonight

Thanks a lot  for your help

**Comment by FuzzyMistborn** [comment]
Yes i'm having the same issue as @ortegafernando .  When the window is open at https://IP/sw_night_configure.html everything works.  Or when I run autonight -v -S it also works.  but if my SSH connection is closed/web page is closed, i don't get switching

**Comment by ortegafernando** [comment]
Hi, I am now in travel so I can't check it until next week. Please @FuzzyMistborn try to check it. Thanks.
And thanks a lot @jmtatsch

**Comment by jdbeitz** [comment]
Same issue here for me - although i don't know how to ssh to my wyzecam - root@ipaddress:22 refuses

**Comment by FuzzyMistborn** [comment]
I unfortunately bricked my test/extra Wyzecam last night trying to load the custom u-boot.  And I don't have time ATM to try this on my in-use cameras and then flash the original software back.  Will try when the replacement arrives in a few days

**Comment by ortegafernando** [comment]
Ok, i will try next wednesday

**Comment by zagosch** [comment]
> Try renaming autonight.conf.sw to autonight.conf and reboot your camera.

That resolved the issue for me, the camera is now auto switching between night and day.

**Comment by chowxueh** [comment]
It does work now but the IR Led remains on even when switched to Daymode. Does anyone know how to fix that? When go Daymode the IR led should go off as well.

**Comment by neozen21** [comment]
One of my four WyzeCam V2s had the IR LED stuck  on too last night ..
Had to reset it.. will check tonight to see if it happens again..
All of them have the autonight.conf enabled already..
They never had issues with the "beta" version of autonight..

**Comment by neozen21** [comment]
So, after playing with the setting a bit, I got it to work fairly well. No issues so far.
My settings are: -S -j 75 -w 3 -1 930000 -2 930000,9999,1 -3 0,0,1
Just using exposure only decide whether to switch to day/night more.

Hope this helps others..

**Comment by LeVuHoang** [comment]
Mine doesn't work neither

> jitter_percent = 3
> eq1_user_exposure = 1200000
> eq2_user_exposure = 930000
> eq2_user_iridix = 14
> eq2_count = 10
> eq3_user_wb = 3000
> eq3_user_iridix = 17
> eq3_count = 8
> sec_wait = 3
> Night Mode Disabled
> (1283981, 7, 4400)
> jitter active
> (1283981, 12, 4400)
> mode switch wait active
> (1283981, 12, 4500)
> mode switch wait active
> (1283981, 12, 4500)
> mode switch wait active
> (1283981, 13, 4500)
> Switching to night new exp=1283981
> Night Mode Enabled
> (1273492, 9, 4500)
> mode switch wait active
> (1273492, 5, 4500)
> mode switch wait active
> (1273492, 5, 4500)
> mode switch wait active
> (1273492, 5, 4500)
> (1273492, 5, 4500)
> (1273492, 5, 4500)
> (1273492, 5, 4500)
> (1273492, 5, 4500)
> (1273492, 5, 4500)
> (1273492, 5, 4500)

I tried parameters provided by sw_night_configure.html

> -S -j 3 -w 3 -1 1200000 -2 930000,14,10 -3 3000,17,8

It also doesn't work

**Comment by chisht** [comment]
@neozen21 
> So, after playing with the setting a bit, I got it to work fairly well. No issues so far.
> My settings are: -S -j 75 -w 3 -1 930000 -2 930000,9999,1 -3 0,0,1
> Just using exposure only decide whether to switch to day/night more.
> 
> Hope this helps others..

Good. Just for curiosity, Wasn't Iridix or Whitebalance temp helpful in identifying day/night mode?
 

@LeVuHoang 
> I tried parameters provided by sw_night_configure.html
> 
> > -S -j 3 -w 3 -1 1200000 -2 930000,14,10 -3 3000,17,8
> 
> It also doesn't work

These are default parameters. Try sw_night_configure.html and and change some of the settings.

OR provide more information about what is not working.
When you ran the binary, you got,
> > Night Mode Disabled
> > (1283981, 7, 4400)
> > jitter active
> > (1283981, 12, 4400)
> > mode switch wait active
> > (1283981, 12, 4500)
> > mode switch wait active
> > (1283981, 12, 4500)
> > mode switch wait active
> > (1283981, 13, 4500)
> > Switching to night new exp=1283981
> > Night Mode Enabled

And then what? Did it get stuck in night mode? Were the lights on? Share the output of the binary  around the time when autonight didn't switch the mode.

**Comment by LeVuHoang** [comment]
I checked IR lights and they're on but images are black.
Exposure when light is off is **1273492**, light on is **1018020**.

**Comment by chisht** [comment]
> I checked IR lights and they're on but images are black.
> Exposure when light is off is **1273492**, light on is **1018020**.

@LeVuHoang Sorry I don't quite understand what you mean.
Are you saying IR LED is on and image is still black? That doesn't make any sense.
And the exposure values you pointed out, which mode camera was in?

You should disable autonight from GUI. Run the sw_night_configure.html and take shots when it does not switch the mode the way it is supposed to.

**Comment by LeVuHoang** [comment]
![dafang2](https://user-images.githubusercontent.com/8195564/47269055-55b69680-d58b-11e8-9e8d-8bb54d09adf1.png)
![dafang3](https://user-images.githubusercontent.com/8195564/47269056-55b69680-d58b-11e8-99c2-9f9069b16676.png)
![dafang1](https://user-images.githubusercontent.com/8195564/47269057-564f2d00-d58b-11e8-80ad-4137edf3cc7e.png)

Please find screenshot for sw_night_configure.html, it shows night mode.
I checked autonight from GUI and it shows ON also.
But I can't see anything.

**Comment by LeVuHoang** [comment]
![dafang4](https://user-images.githubusercontent.com/8195564/47269075-a9c17b00-d58b-11e8-8983-1d1a3cf76a28.png)

**Comment by chisht** [comment]
@LeVuHoang Sorry I don't know what's wrong with your setup.
With IR LED on, it should never produce a pitch black image, regardless of autonight working or not.

**Comment by LeVuHoang** [comment]
> @LeVuHoang Sorry I don't know what's wrong with your setup.
> With IR LED on, it should never produce a pitch black image, regardless of autonight working or not.

@chisht Thanks for your help.

**Comment by neozen21** [comment]
@LeVuHoang Try this and see if it helps: -S -j 75 -w 3 -1 930000 -2 930000,9999,1 -3 0,0,1
This setting uses only exposure ..

@chisht  I've found that the 3% in the"If exposure changes by more than X%, ignore" is too little in situations like going from all dark to bright (like when you turn on the lights in a room), so setting it much higher helps.

Also, the WB and Iridix doesn't help much and just makes the whole logic too complicated and trickier to get it right. The "if count > X,  " part is also not useful, since I noticed that it the count rarely goes up by 8 (most of the time it was 2 or 3), so I disabled that as well...

I think the logic doesn't need to be that complicated.. exposure alone is good enough in most cases. Granted, I've only tested by turning the lights on and off in my kitchen & family room and by checking the camera during the night and day. I haven't checked every minute during sunrise/sunset to see how it behaves..

**Comment by chisht** [comment]
@neozen21 , Thanks for the comments.
BTW the "Wait	3 sec after changing mode" is to avoid tripping when things are settling down during the mode change.

By changing 3% to 75%, you actually are making it even more sensitive. What you are saying is only ignore if exposure changes by more than 75%, instead whenever it changes by more than 3%.

And as for the count and WB and Iriidx, trust me they all do help a lot. In your case if count doesn't even go higher than 2 or 3 then it probably means that your lighting condition is changing every 2-3 seconds. That count logic is especially to prevent tripping over those short changes. Before switching to day mode, all the parameters should be in day mode range for at-least "range" number of seconds.

But whatever works for you. I gave up on making a universal solution. As long as there is a way to make it work for almost every case.

**Comment by LeVuHoang** [comment]
> @LeVuHoang Try this and see if it helps: -S -j 75 -w 3 -1 930000 -2 930000,9999,1 -3 0,0,1
> This setting uses only exposure ..

I used that command but it is still showing black.
![dafang2](https://user-images.githubusercontent.com/8195564/47298793-426b0000-d64b-11e8-8a89-3e9e87ad17e0.png)
![dafang1](https://user-images.githubusercontent.com/8195564/47298795-43039680-d64b-11e8-91f4-0e460a434e31.png)

**Comment by neozen21** [comment]
Hmm... according to your screen cap.. it switched to night mode already.
Has it ever worked in CFW? What about using original FW?
It could be an hardware issue...

**Comment by FuzzyMistborn** [comment]
Ok, it works going to night mode (IR) but doesn't work going back after renaming autonight.conf.sw to autonight.conf.  Unless I have the config page open.

**Comment by chisht** [comment]
Could you stop autonight service.
Open sw_night_configure.html. Keep it open and see if it works in both day and night mode.

If you want, you can also try the PR #752 . Which just makes saving the configuration a bit easier.

**Comment by LeVuHoang** [comment]
I just checked that camera with original firmware and I can see photo in dark mode.
So, it should be something with our firmware_mod
![001](https://user-images.githubusercontent.com/8195564/47354033-3e44ee00-d6f0-11e8-8705-24ed5ec0ca8e.jpg)

**Comment by chisht** [comment]
@FuzzyMistborn , you are right 752 won't help, it only makes it easier to save the new settings.

Please make sure autonight service is running from GUI and share the output of the following to confirm the commandline,
`ps aux | grep autonight`

And if you see '-S' in the output above, then please stop the service from GUI then run it from commandline as following. And share the output around when it does not switch the mode. Run as ,
`autonight -S -vv`

**Comment by FuzzyMistborn** [comment]
Here's the output:

```
[root@DAFANG:~]# ps aux | grep autonight
  223 root      0:21 /system/sdcard/bin/autonight -S -j 3 -w 3 -1 1200000 -2 930000,14,10 -3 3000,17,8
 1904 root      0:00 busybox grep autonight
```

I'm not home atm so I can't test the second part, will try tonight.

**Comment by chisht** [comment]
At least this part confirms that what you are running is the default setting for sw version of autonight. And is the default for the web version as well. I don't know why web version works but not the binary one. 
When you share the other output, hopefully it'd shed some light on it.

**Comment by paus56** [comment]
For my camera, the optimal settings for Auto Night are:
-S -j 3 -w 3 -1 1260000 -2 960000,14,10 -3 3400,14,8

The algorithm for switching on the night mode is not implemented correctly.
request in the autonight file to change the night mode enable algorithm
in this form:
- Night Vision ON
- IR LED ON
- IR Cut OFF

for the test, my keys work correctly in the action.cgi file:
    night_on)
      /system/sdcard/bin/setconf -k n -v 1
      sleep 2
      setgpio 49 0
      sleep 1
      setgpio 26 0
      setgpio 25 1
      sleep 1
      setgpio 25 0
      echo "0" > /var/run/ircut
    ;;

    night_off)
      setgpio 49 1
      sleep 1
      setgpio 25 0
      setgpio 26 1
      sleep 1
      setgpio 26 0
      echo "1" > /var/run/ircut
      /system/sdcard/bin/setconf -k n -v 0
    ;;
 
sorry for google translator...

**Comment by chisht** [comment]
@FuzzyMistborn, seems like your lighting in just on the edge of default day mode parameters. Not sure why it works with the GUI version, maybe because the phone or laptop that you are using added extra lighting and that little difference was enough.

Anyways try,
`-S -j 3 -w 3 -1 1200000 -2 945000,14,10 -3 3000,10,8`

That should switch to day mode correctly. I'd also try getting in front of the camera in night mode with lights off, and make sure it does not switch back to day mode.

**Comment by chisht** [comment]
> The algorithm for switching on the night mode is not implemented correctly.
> request in the autonight file to change the night mode enable algorithm
> in this form:
> 
> * Night Vision ON
> * IR LED ON
> * IR Cut OFF

You are right, it is wrong. Just haven't had the chance to revisit it. Feel free to change it and do the PR, I'm sure everyone is welcome to contribute.
 
> for the test, my keys work correctly in the action.cgi file:

This would only fix it for GUI version. For binary to use it, you'd need to either modify the source code or modify /system/sdcard/scripts/common_functions.sh

**Comment by FuzzyMistborn** [comment]
@chisht that seems to do the trick, thanks!

**Comment by paus56** [comment]
> You are right, it is wrong. 
> This would only fix it for GUI version. For binary to use it, you'd need to either modify the source code or modify /system/sdcard/scripts/common_functions.sh

Thank you, everything worked very well after modifying the /system/sdcard/scripts/common_functions.sh file
modified as follows:
```
#Control the night mode
night_mode () {
   case "$ 1" in
   on)
     / system / sdcard / bin / setconf -k n -v 1
     sleep 2
     ir_led on
     ir_cut off
     ;;
```

**Comment by chisht** [comment]
Thanks @FuzzyMistborn , #756 should fix that.

**Comment by paus56** [comment]
@jmtatsch  i moved the grey mode before retracting the ir_cut as you wanted but it don't see why the sleep for 2 seconds would be necessary.

in XiaoFang 1S, if there is no sleep 2 when the night mode is turned on, a purple flash appears on the screen

**Comment by jdbeitz** [comment]
Seems to be working so far for me as well

**Comment by arock093** [comment]
I finally got auto night working on my Wyze Cam v2. I had to play around with the numbers a lot! Everyones lighting situation will be different. It might be nice to have a feature to take a base sample of the normal lighting conditions of where a camera is placed.

**Comment by ortegafernando** [comment]
Sorry, yesterday I said that it was working perfect. But this morning I have check it and no auto night mode has started this night. I have to check again my configuration and confirm again that everythink is ok. I have to "rewind" this conversation again and read from the begining, thanks. I will try to check this night.

**Comment by ortegafernando** [comment]
Hi, I think that I didn't activate autonight service. I think it is necessary to configure autonight service as SW and autorun the service. I have checked this nigth. Tomorrow morning I will confirm this, thanks a lot for this great job !!!

**Comment by ortegafernando** [comment]
Good work. It seems to work perfect. I think that this could be closed.

**Comment by clrmsc** [comment]
My work settings: 
<img width="968" alt="Снимок экрана 2020-09-09 в 22 33 39" src="https://user-images.githubusercontent.com/16281451/92644868-a7d24380-f2ec-11ea-98da-09f6a7637b00.png">
