### ISSUE TITLE
Audio cuts off before completion using audioplay of the included wav files

### ISSUE THREAD

**Issue by richard512** [EliasKotlyar/Xiaomi-Dafang-Hacks#741]
Audio does work!! But it cuts off before the complete wav file has played.

**Comment by junnikokuki** [comment]
You can fix this by compile the audioplay yourself. Just add these lines:

ret = IMP_AO_FlushChnBuf(devID, chnID);
	if (ret != 0) {
		IMP_LOG_ERR(TAG, "IMP_AO_FlushChnBuf error\n");
		return NULL;
	}
	
before:

/* Step 6: disable the audio channel. */
	ret = IMP_AO_DisableChn(devID, chnID);
	if (ret != 0) {
		IMP_LOG_ERR(TAG, "Audio channel disable error\n");
		return NULL;
	}
