### ISSUE TITLE
very low fps

### ISSUE THREAD

**Issue by dmolner** [EliasKotlyar/Xiaomi-Dafang-Hacks#749]
Hello,

I reading about some issues about this and I test the solutions that no results.
I only have 1 fps
Now I have:
1600x900 (I test 640x360)
SMART
250kbps

**Comment by Dopeyr** [comment]
What are you using to view the video stream? Tinycam, VLC, etc. ?

**Comment by jmtatsch** [comment]
@dmolner can you try FixedQp 128 kbps?

**Comment by dmolner** [comment]
> What are you using to view the video stream? Tinycam, VLC, etc. ?

I test with Chrome, ISPY.
With VLC I think is correct.
If change to 128 the result is the same.

**Comment by jmtatsch** [comment]
FixedQp

**Comment by nonyhaha** [comment]
I am having issues too. 
Until now I have tried almost every resolution/bitrate/video format possible. 
in VLC or tinycam, it is fluent, everything is A-OK. 

BUT, while transmitting to surveillance software like iSpy (opensource) running on a windows 10 machine it is sending veeery choppy video, very very low fps... 
This is also happening while sending video to Motioneyeos running on a raspberry pi 3b.
