### ISSUE TITLE
Script to execute scheduled tasks

### ISSUE THREAD

**Issue by SomebodySysop** [EliasKotlyar/Xiaomi-Dafang-Hacks#753]
I would like to create a script that will:

1. Launch rtsp night vision at a specific time each day.
2. Reboot os / camera at a specific time each day.

Under Linux, I would normally do this using "crontab -e", but that command under the XDH os returns this: "crontab: can't change directory to '/var/spool/cron/crontabs': No such file or directory"

Any suggestions?

**Comment by SomebodySysop** [comment]
OK, I solved the crontab issue by simply creating the directory.  Duh!

However, what are the commands to:

1. Reboot camera (there is no shutdown command)?
2. Turn rtsp night vision on/off?

**Comment by Dopeyr** [comment]
1. /sbin/reboot
2. Not 100% sure, but https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/firmware_mod/scripts/common_functions.sh#L340 is a good starting point - see how that does it.
