### ISSUE TITLE
Can't see "big" preview in Synology Surveillance Station

### ISSUE THREAD

**Issue by Adrimau** [EliasKotlyar/Xiaomi-Dafang-Hacks#755]
Hi!

I hacked my Xiaomi Dafang to add it to Synology Surveillance Station. It works perfectly but there's a problem in Surveillance Station.

<img width="1055" alt="image" src="https://user-images.githubusercontent.com/31062488/47415760-86a5ef80-d774-11e8-9789-900788446d25.png">

As you can see, the little preview works but not the big one, it's the same for the "live view" app (where you can watch multiples camera). I tried the H264 and MJEPG RTSP Server, auto/UDP/TCP, turn off audio, nothing works. The test connection is ok. All features about detection seems works.

Thanks in advance for your help!

**Comment by sergeymaysak** [comment]
Sounds as connection to camera is dropped or not established by SS. Can you see stream using VLC? I have made it working by using the following setup:
- video settings: H264  RTSP, 1600x900, CBR 100 kb bitrate
- audio settings: does not matter - to make stream with SS working I disabled audio for camera in SS

Again - make sure you can see stream in VLC. If you cannot see stream in VLC - change video settings (say lower resolution).

**Comment by Adrimau** [comment]
Absolutely no problem to stream with VLC. I tried with your settings (and lower video size to try) but it's the same, grey screen.

**Comment by Karunamon** [comment]
I ran into this recently - in your Synology settings, make sure that your security settings are set to "Intermediate". (DSM -> Control Panel -> Security -> Advanced).

**Comment by Adrimau** [comment]
It is.

**Comment by jdbeitz** [comment]
I have had troubles with Synology when audio is enabled...

**Comment by Adrimau** [comment]
It was the first thing I disabled. Could you show me your settings if it's working for you? In the hack UI and in Surveillance Station, thanks.

**Comment by tesnic** [comment]
I have the same problem @Adrimau , can you finally fix it? thanks

**Comment by Adrimau** [comment]
Nop @tesnic, I gave up the idea. I manage my camera in Mi Home, too bad.

**Comment by cmol1** [comment]
> Sounds as connection to camera is dropped or not established by SS. Can you see stream using VLC? I have made it working by using the following setup:
> 
> * video settings: H264  RTSP, 1600x900, CBR 100 kb bitrate
> * audio settings: does not matter - to make stream with SS working I disabled audio for camera in SS
> 
> Again - make sure you can see stream in VLC. If you cannot see stream in VLC - change video settings (say lower resolution).

Hi,

To fix the audio, please change the format to PCM, then it should work. According to Synology, "Surveillance Station supports G.711, G.726, AAC, AMR and PCM audio formats. The actual supported audio formats depends on the camera specification."

I'm using PCM and all my issues went away :).

Cheers
