### ISSUE TITLE
Bricked Dafang Cam

### ISSUE THREAD

**Issue by MrUkleja** [EliasKotlyar/Xiaomi-Dafang-Hacks#760]
Hi,

My Dafang camera was working flawlessly.
Few days ago I went to web UI and did ptz movement calibration.
After that process, camera is dead. When plugging power, it does nothing. No led, no movement ... Nothing.
Did anyone experienced something like that?
Any ideas how to unbrick it if even possible?

**Comment by jmtatsch** [comment]
Open it up. Probably the power connector disconnected itself because the cable is wound up.

**Comment by columbusgeek** [comment]
Did you pull the sdcard out and see if it fired up that way?

**Comment by MrUkleja** [comment]
Guys, thank you for tips but my camera is a brick.
Pulled out sd card, checked power cable inside ... I even used pins to provide power directly, taking out cable as a source of issue.
Maybe just a bad unit. My second Dafang is working flawlessly.

**Comment by jmtatsch** [comment]
Attach serial connection

**Comment by ronnyandre** [comment]
Any luck on unbricking this?
