### ISSUE TITLE
Cannot flash Wyze V2 or Wyze PAN

### ISSUE THREAD

**Issue by williamrussellajb** [EliasKotlyar/Xiaomi-Dafang-Hacks#761]
I have 4 Wyze Cameras that I recently bought. Two Wyze-V2 and Two Wyze-Pan.

I am following the install directions, as well as this video:
https://www.youtube.com/watch?v=_Iug4n2GvcA

1. I formatted the SD Card to FAT32, partition of 512MB. 
2. Copied only the demo.bin to the SD Card
3. Unplugged the Wyze Cam
4. Inserted the SD Card
5. Held down the settings button
6. Inserted the power
7. Continued holding the settings button, tried 100's of variations of 4-15 seconds. 
Problem:
The annoying sound of "Ready to connect", it doesnt seem to flash or do anything.

I continued trying, copying the firmware_mod directory, updated the config SSID/PW and inserted the card, and powered on.

I'm not even getting a startup.log file anywhere?

**Comment by jmtatsch** [comment]
See https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/718#issuecomment-434193796
Also maybe we need to put the CFW on a diet or you need to get a serial interface and flash directly.

**Comment by williamrussellajb** [comment]
Okay, will do. thanks @jmtatsch

**Comment by williamrussellajb** [comment]
I tried 4 different SD Cards, partitioned on both a MAC and Windows 10. 

I inserted a SD card into an old Android device, and it prompted me to format it for me. 

Then it all worked..... an old ass android fixed the formatting problem.

**Comment by hansaya** [comment]
@williamrussellajb can you comment your solution to https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/669 it might help someone
