### ISSUE TITLE
Motion Snapshot not saved + Not showing up in MQTT broker

### ISSUE THREAD

**Issue by exetico** [EliasKotlyar/Xiaomi-Dafang-Hacks#762]
Hi all

I'm sorry for bringing this up again - i can see that a lot of people are asking about the same.

My devices is the `1S` cam, and it's running the latest version of Dafang, grapped a few days ago.

My motion.conf is like this (and it's present in the right `config` folder):
```
# Configure the motion core parameters:

region_of_interest=187,0,1018,720
motion_sensitivity=3
motion_indicator_color=2
motion_timeout=-1
motion_tracking=off

# Configure how to deal with motion events:

motion_trigger_led=true
save_snapshot=true
max_snapshots=20
publish_mqtt_message=true
sendemail=false
send_telegram=false
save_dir=/system/sdcard/motion/stills
save_file_date_pattern="+%d-%m-%Y_%H.%M.%S"
```

The folder called `/system/sdcard/motion/stills` was not created - and did not show up, after a few motion triggers, too. I manually tried to create the folder, with no luck.

The red spot shows up on the picture within the Web-interface, so the motion sensor is triggered, but no messages shows up about this, if i can with MQTT.fx.

With MQTT.fx i subscripted to all topics (`#`), and "only" the following topics about `motion` shows up:
```
gang/dafang/motion/detection
gang/dafang/motion/send_mail
gang/dafang/motion/tracking
```

Btw. the `gang/dafang/motion/detection` is `ON` in the broker-messages, so that should be OK, too.

I'm also able to see the auto-discovery on `homeassistant/camera/dafang/motion_snapshot/config` is working as exptected. Here is the data:
```
{"name": "dafang motion snapshot",  "unique_id": "78***cd***db-motion-snapshot",  "topic": "gang/dafang/motion/snapshot"}
```
But the `gang/dafang/motion/snapshot` is not showing up, if motion is triggered.

**Web-GUI**
`Motion Detection` is enabled in `Camera Controls`, and the camera is restarted a couple of times.

Within `Manage` > `Services` i have a option called `configureMotion`, and i tried that too - just to be sure, but it doesn't fix anything (_The script is also very basic, so it's fully understandable  _+1 )

**Mosq-server**
My mosq-server is  based on the standard `eclipse-mosquitto`-docker container, and this is used for many other things, with no problems what so ever. Could that be a problem? The container has access to both port `1883` and `9001` (_No specific message size limit is defined - it's stock settings_)

**Comment by exetico** [comment]
Also on a fresh install @jmtatsch ?

But well.. I can see that `/dev/root` & `/driver` is pretty maxed out, but everything else looks fine:
```
Filesystem                Size      Used Available Use% Mounted on
/dev/root                 4.0M      4.0M         0 100% /
tmpfs                    17.3M      8.0K     17.3M   0% /dev
tmpfs                    17.3M    428.0K     16.9M   2% /tmp
tmpfs                    17.3M     44.0K     17.2M   0% /run
media                    17.3M         0     17.3M   0% /media
/dev/mtdblock3          640.0K    640.0K         0 100% /driver
/dev/mtdblock4            4.6M      3.9M    756.0K  84% /system
/dev/mtdblock7            2.0M    132.0K      1.9M   6% /backupa
/dev/mtdblock8          256.0K    104.0K    152.0K  41% /configs
/dev/mtdblock9          256.0K    104.0K    152.0K  41% /params
/dev/mmcblk0p1           29.8G     40.6M     29.8G   0% /system/sdcard
/dev/mmcblk0p1           29.8G     40.6M     29.8G   0% /bin/busybox
/dev/mmcblk0p1           29.8G     40.6M     29.8G   0% /root
/dev/mmcblk0p1           29.8G     40.6M     29.8G   0% /etc
```

Are you still consider this as a swap issue? If so, guess i need to get the SD-card and try to reformat it, after shrinking it a bit (Or?)

**Comment by jmtatsch** [comment]
Search for swapon

**Comment by exetico** [comment]
Thanks! 
```
dd if=/dev/zero of=/system/sdcard/swapfile bs=1024 count=65536
mkswap /system/sdcard/swapfile 
swapon /system/sdcard/swapfile 
vi /etc/fstab 
```
Hereafter i added `/system/sdcard/swapfile swap swap defaults 0 0` to the end of the file.

But after reboot i can't find the swapped area. Do you have any inputs here?

**Comment by exetico** [comment]
Brilliant - Thanks! Works as expected, and motion snapshots is now working as expected. An idea could be doing this on devices with a small amount of ram, or just inform the user about the option, if they are trying to enable motion defection.

But - I'm happy :-)
