### ISSUE TITLE
CPU is low but NIC seems quite high

### ISSUE THREAD

**Issue by columbusgeek** [EliasKotlyar/Xiaomi-Dafang-Hacks#763]
What's everybody's nic usage when you look at it in "top"?

Mines never lower than 80% which leads me to believe that's the issue with my camera cutting in and out every so often.
If I just straight up ping the camera I don't drop packets.

I'm thinking the wifi is getting saturated?

**Comment by Dopeyr** [comment]
AFAIK 'nic' doesn't refer to wifi / network, but cpu 'nice' time.

**Comment by columbusgeek** [comment]
Ack, good point,

After additional testing, it's not the issue anyhow.  When I bring the camera inside it works fine.  It's definitely having issues keeping connected to my network through the doors.  bleh.
