### ISSUE TITLE
Audio lag

### ISSUE THREAD

**Issue by pedrorubster** [EliasKotlyar/Xiaomi-Dafang-Hacks#764]
Hi! I have a Xiaomi Xiaofang 1S that's currently running the Hack perfectly. However, I have a issue. On vlc, the audio has like a 2 second delay, or there's just no sound. I find that very odd, but I think it's a vlc issue. Any ideias on how to fix that? Thanks!

**Comment by deadmaus3221** [comment]
Fixed!

Just add this to your rtsp conf:

AUDIOFORMAT=PCMU

AUDIOOUTBR=8000:8000

RTSPH264OPTS="-W1280 -H720 -U root:your_password"

**Comment by netRunner0** [comment]
Not works me. Dafang 3S
