### ISSUE TITLE
Make “demo.bin” from firmware_original

### ISSUE THREAD

**Issue by osvaldoasn** [EliasKotlyar/Xiaomi-Dafang-Hacks#768]
Hi, how can I make “demo.bin” from 5.6.2.106 (firmware_original/dafang) folder?

**Comment by jmtatsch** [comment]
Have a look at 
https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/hacks/firmware/packer.py

**Comment by osvaldoasn** [comment]
Hi,
I have tried, but if fails without appfs.bin file that is missing on latest firmware folder. I’ve tried with other FW appfs.bin and with backupa.bin but it fails when I upload to camera.
Thanks for your help.

**Comment by jmtatsch** [comment]
Attach a serial interface to it and figure out why it doesn’t work.

**Comment by osvaldoasn** [comment]
> Have a look at
> https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/hacks/firmware/packer.py

5.6.2.106/appfs.bin file is missing where can I get it?

Thanks.

**Comment by jmtatsch** [comment]
you tried to rename backupa.bin to appfs.bin and it didn't boot right?
@20silencer04 dumped that firmware right at https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/705#issuecomment-428046272. @20silencer04 are you sure there was no appfs.bin file lost somewhere?

**Comment by osvaldoasn** [comment]
> you tried to rename backupa.bin to appfs.bin and it didn't boot right?
> @20silencer04 dumped that firmware right at [#705 (comment)](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/705#issuecomment-428046272). @20silencer04 are you sure there was no appfs.bin file lost somewhere?

Yes, I've tried it. (backupa.bin to appfs.bin)

**Comment by osvaldoasn** [comment]
@20silencer04 can you help with FW dump?
