### ISSUE TITLE
Wifi doesn't reconnect after drop

### ISSUE THREAD

**Issue by marcocsharp** [EliasKotlyar/Xiaomi-Dafang-Hacks#77]
Hi, thanks for your great work!
I noticed that if my home wifi connection drops, the cam doesn't reconnect automatically to the router when the wifi goes on.
I think it's caused because wpa_supplicant is called only once at start; can you suggest a script I can use? Thanks.

**Comment by markus0m** [comment]
I can confirm this problem.

**Comment by shinebar1001** [comment]
I tried this several times today and had no problems. Can you check if wpa_supplicant is running? It is called as daemon, so there should be a process.

**Comment by Shaktohh** [comment]
I have the same problem too. (i can't see if wpa_supplicant is running since i can't connect to the camera on ssh)

**Comment by jmtatsch** [comment]
Cannot reproduce that either on any of my 4 cameras.
Maybe your signal is just to weak for reconnection in that moment? Can try closer to your access point and reopen if still an issue?
