### ISSUE TITLE
ERR_SSL_VERSION_OR_CIPHER_MISMATCH

### ISSUE THREAD

**Issue by majorthorn** [EliasKotlyar/Xiaomi-Dafang-Hacks#773]
I cannot connect to the Web interface from any browser on windows 10. I am able to connect to it on my  pixel 2 xl. When trying to access the interface i get the following error 
ERR_SSL_VERSION_OR_CIPHER_MISMATCH

**Comment by jmtatsch** [comment]
Hmm possibly they blacklisted RC4 now. Can you get more log output?

**Comment by majorthorn** [comment]
> Hmm possibly they blacklisted RC4 now. Can you get more log output?

Sure! Can you point me in the direction to get the logs that you need?

**Comment by majorthorn** [comment]
I'm flexible, I can provide logs from your browser of choice. Are you needing Network Logs from the browser or different logs?

**Comment by jantje88** [comment]
I do have the same problem. How can we provide the necessary input to investigate this?

**Comment by jmtatsch** [comment]
For chrome look at View->Developer Tools->Security

**Comment by jmtatsch** [comment]
For me it works with the current chrome version.

**Comment by jantje88** [comment]
Just updated Chrome to 70.0.3538.102 (On Windows 10), but still get the same error unfortunately.

**Comment by jantje88** [comment]
Just tried it on a few other systems with Windows 10 and latest Chrome. All gave me the SSL error..

**Comment by sharkyP** [comment]
i'm also having this issue

**Comment by reaperharvest** [comment]
I can confirm this is a more widespread issue than a couple of people. I think it is the version of TLS these browsers support now. I could not get edge, chrome or firefox to work. Using my phones chrome browser did work as I suspect the mobile version isn't quite up to date as the desktop version is. Any ideas on how we get this fixed/updated in the repo?

**Comment by majorthorn** [comment]
I just connected to my camera with chrome on windows today and it seems like this issue is no longer occurring. Can anyone else confirm this to help determine if this issue has been resolve?

**Comment by reaperharvest** [comment]
@majorthorn yes I can confirm this is still happening for me

**Comment by sharkyP** [comment]
Yes still happening here - I have updated as well to test and the issue persists except on Mac with Safari where it is working fine. It seems RC4 is blocked by browsers and most AV suites these days, I think you just need to update the protocol on the httpd

________________________________

**Comment by jantje88** [comment]
Yes, still lERR_SSL_VERSION_OR_CIPHER_MISMATCH in Chrome 71.0.3578.98

**Comment by rednose66** [comment]
Any updates or ideas on this one?

**Comment by jmtatsch** [comment]
You could compile a new lighthttpd and ssl toolchain, that would fix it presumably.

**Comment by JBS5** [comment]
Thanks for your suggestion @jmtatsch
Any instructions how to do this?

**Comment by jmtatsch** [comment]
Not really, look at our software/main repo. There are some examples and scripts for building the components.

**Comment by kbehren** [comment]
I also have this problem. Checked with Chrome/Edge/Firefox on Windows 10 and Firefox on Android.

**Comment by JBS5** [comment]
Problem seems to be solved? I am able to open the interace with Chrome now, using Chrome 72.0.3626.121
