### ISSUE TITLE
 Xiaofang 1S new sensor - original firmware restore 

### ISSUE THREAD

**Issue by adamast0r** [EliasKotlyar/Xiaomi-Dafang-Hacks#774]
First of all just wanted to say @jmtatsch  thanks for creating the https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/tree/dafang_jfx23 

After weeks of frustration I managed to have my camera working after I saw the following post where someone was having the same problems with the new sensor: https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/705

I downgraded a few firmware images (including the firmware_660R.bin) and now my original firmware is not working , I can now only boot via Sdcard, is there any way of fixing this? @20silencer04  can you please provide your original xiaomi firmware ?

**Comment by jmtatsch** [comment]
Please change to a meaningful issue title and state clearly about what camera model this is.

**Comment by mahbubzone** [comment]
I have xiaofang 1s. I searched a lot but didnt find any proper instruction to flash cfw in this. can anyone help?
