### ISSUE TITLE
Implement ONVIF support

### ISSUE THREAD

**Issue by Cr4z33** [EliasKotlyar/Xiaomi-Dafang-Hacks#78]
Hi,

@EliasKotlyar before I am going to buy this camera can you please tell me if your hack supports ONVIF too?

I am already using some hacked Xiaomi XiaoFang cameras with Synology Surveillance System and I would like to use the Dafang too. :)

**Comment by shinebar1001** [comment]
Albeit ONVIF support would be very cool it isn't implemented. But you don't need ONVIF to use the camera with Surveillance Station. Just select the user defined camera with h264, Port 8554 and use /unicast as path:

![image](https://user-images.githubusercontent.com/33186930/36000679-fc39625c-0d23-11e8-9bd8-e944d44af01c.png)

**Comment by Cr4z33** [comment]
Sweet thanks @shinebar1001 ! 👍

**Comment by benjR** [comment]
Very useful, should be in the documentation ;-)
Is there a way to enable PTZ as well ?

**Comment by LiloBzH** [comment]
+1 No PTZ with S Station. Maybe it's impossible ? @EliasKotlyar ?

Thanks :)

**Comment by shinebar1001** [comment]
I added the configuration to the wiki (trying to copy & paste some ideas from the issues there)
Concerning PTZ for Synology Surveillance Station: it seems that you can edit the configuration file for cameras in the Synology. Unfortunately I don't see how to define different ports for commands and the port for the tcp-stream.

**Comment by LiloBzH** [comment]
yep

PTZ work with ONVIF, not with stream so why ONVIF don't work ? ^^

**Comment by heyggu** [comment]
I tried this way on my DSM ,but stream is very slow to use, any solution?

**Comment by rzepa10** [comment]
@shinebar1001 
Hi, did you try xiaomi defang with Surveillance Station. 
For me RTSP stream is laggy and veeeery slow like @heyggu 
In VLC everything is ok.
Any solution ?

**Comment by shinebar1001** [comment]
Actually Surveillance Station is always extremely slow at my place, because I own a DS115J which has only Little RAM + CPU - fine as NAS, no more no less. So I never had any camera connected in real use cases. My solution for that is switching to MotionEye on a local HyperV, which runs smoothly (doesn't help you, I know...)

**Comment by rzepa10** [comment]
@shinebar1001 
I have DS918+ so cpu power should not be a problem :) 
For that moment I use mihome app but surveillance station would be much safer in term that my records don't "fly" to china for free :)

**Comment by mitchoklemen** [comment]
Is there something "new" about PTZ in synology?

**Comment by JonyBCN** [comment]
+1 No PTZ and NO SOUND with S Station.

**Comment by gabcac** [comment]
+1, ONVIF support would hqve been greqt for this device.
Can this be considered as new request?

For those who doesn't have audio, I suggest them to upgrade to the latest version, and test [](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/234#issuecomment-382837689)

**Comment by snjoetw** [comment]
+1 for ONVIF support

fwiw, I finally got audio to work on my hikvision NVR, I had to change encoding to PCM

**Comment by EliasKotlyar** [comment]
Hello everyone,

As far as i see, ONVIF Protocol is just a bunch of SOAP-APIs, which are used to transmit informations about the camera and to trigger some scripts like moving etc. It seems that its definetely possible, but it needs a lot of effort to port it.

There are some implementation which may work:

1. 
https://github.com/KoynovStas/onvif_srvd
This seems to be incomplete, and i dont see any code for adding new functions. But it may provide a simple solution for adding this support.

2.
https://github.com/kristian/rpos-gateway
This probably wont work on the Dafang due to the lack of ram for running nodejs. But it seems that the guys know how to implement the protocol. 

If anyone have another reference impementation, please add it here.

**Comment by nik0** [comment]
@EliasKotlyar 
Do you plan to add onvif?

**Comment by EliasKotlyar** [comment]
Not in the near future. Working on a different, more interessting topic now, which will make things little bit easier.

**Comment by hyteoo** [comment]
+1 on this, ONVIF is now so ubiquitous that all NVR software support it.
Would be a great addition.

**Comment by hyteoo** [comment]
Another active repo that looks interesting:
https://github.com/Tereius/libONVIF
seems to cover more of the onvif spec.

**Comment by nik0** [comment]
@hyteoo,
We need to check but it seems there is some QT code. First we need QT ...

**Comment by S474N** [comment]
+1 for ONVIF support!

Is now support for main/sub streams?

**Comment by k1ng440** [comment]
+1 for ONVIF support!

**Comment by Benouzao** [comment]
+1 for ONVIF Support!

**Comment by EliasKotlyar** [comment]
It doesnt help if everyone is writing "+1" in this issue. As i said in june: there are some options available but it will cost a lot of time to implement them. Unfortunately, nobody has the time yet to implement them

**Comment by Benouzao** [comment]
Thanks Elias for this amazing hack.
The idea of the +1 is also for the community to share interest on what features are most wanted/needed.
Keep up the great work!

**Comment by jamman9000** [comment]
Hope this gets revived in the future. My NVR can't find the RTSP stream from my flashed Wyze cam but might if ONVIF was integrated. Going to try the rpos-gateway until then.

**Comment by kurabii** [comment]
> +1 for ONVIF support
> 
> fwiw, I finally got audio to work on my hikvision NVR, I had to change encoding to PCM

@snjoetw - I picked up a laview NVR recently and plan on flashing it to the hikvision firmware, were you able to get the wyze cams to record to your hikvision? Did you have to set them up in any special way?  

I ask not because I am lazy, but because I cant find it online and my nvr is still shipping. TIA

**Comment by jmtatsch** [comment]
Onvif has been added in a05a6e7 thanks to sian in #1296.

**Comment by SparkyRedcar** [comment]
> > +1 for ONVIF support
> > fwiw, I finally got audio to work on my hikvision NVR, I had to change encoding to PCM
> 
> @snjoetw - I picked up a laview NVR recently and plan on flashing it to the hikvision firmware, were you able to get the wyze cams to record to your hikvision? Did you have to set them up in any special way?
> 
> I ask not because I am lazy, but because I cant find it online and my nvr is still shipping. TIA

Hi there, did you ever manage to get this working with a Hikvision NVR, I've tried and failed.  It seems the only protocol my Hikvision NVR is offering is Nikvisions

**Comment by fx-k** [comment]
> +1 for ONVIF support
> 
> fwiw, I finally got audio to work on my hikvision NVR, I had to change encoding to PCM

Hi sorry to bother u.
Same here, I also use Hikvision's NVR and have applied the hacked firmware to my Dafang camera. 
Unfortunately, regardless of whether I change the audio stream encoding to PCM or any other format, the NVR fails to correctly read the camera's audio. (I have another camera that uses AAC-encoded RTSP, and it works fine.) 

So, I would like to ask how you configured yours.

Additionally, ONVIF doesn't seem to work on my Hikvision NVR either. When I use an ONVIF scanning tool, it detects that ONVIF is listening on the 127.0.0.1 port, which might be the source of the problem.
