### ISSUE TITLE
OSD (Axis position) not updated on mqtt PTZ

### ISSUE THREAD

**Issue by mikeage** [EliasKotlyar/Xiaomi-Dafang-Hacks#784]
Xiaomi Dafang Camera, running 9a664c9

### Description

After sending motion commands via mqtt, the camera moves, but the OSD is not updated.

Moving the camera using the default web UI does update the OSD

### What did you do to debug the issue

Comparing the code in mqtt-control.sh, it seems like it should call
```bash
      update_axis
      /system/sdcard/bin/setconf -k o -v "$OSD"
```
possibly after a sleep, after each motion.

Perhaps a better place would be in `common_function.sh`. What do you think? I'm happy to submit a PR, but I'd like to first understand if there's a reason this was done in the web UI, not in common_functions, and if there's any reason not to do it for mqtt (blocking, perhaps?)

**Comment by jmtatsch** [comment]
I agree with you that common_functions.sh would be a better place to call setconf. I will gladly merge your pull request.
WebUI uses the old action.cgi api which is kind of a big mess.
Imho action.cgi should be rewritten using the common_functions wherever possible.
