### ISSUE TITLE
Calibration doesn't work on Xiaomi Dafang (only horizontal and vertical, not regular)

### ISSUE THREAD

**Issue by mikeage** [EliasKotlyar/Xiaomi-Dafang-Hacks#785]
Xiaomi Dafang Camera, running 9a664c9

### Description

The following work:

```bash
    /system/sdcard/bin/motor -d v -s 100
    /system/sdcard/bin/motor -d h -s 100
```

This does not

```bash
    /system/sdcard/bin/motor -d f -s 100
```
it returns
```
Invalid Direction Argument f
```

Is this correct and known? I saw a bunch of threads discussing calibration, but it wasn't clear to me what the conclusion was. I'm looking at doing an automatic calibration on reboot, and I want to make sure I'm doing the right type (also, it seems like both `v` and `h` do the same thing)

**Comment by jmtatsch** [comment]
The former two commands need the dafang with endstop sensors, the latter attempts to do it in software.

**Comment by jmtatsch** [comment]
https://github.com/EliasKotlyar/Xiaomi-Dafang-Software/commit/de4e4dfd3303f1f407a7d86a9252306bffadc05c

**Comment by mikeage** [comment]
Is this the code used? Or does it take from https://github.com/Dafang-Hacks/Main/blob/master/motor_app/motor.c, which doesn't seem to have this option?

**Comment by jmtatsch** [comment]
You are right, likely the newer motor app from the Dafang-Hacks repo is checked in.

**Comment by jmtatsch** [comment]
The immediate error yes, but there is so much more broken deeper. Reset() in the motor app seems to calibrate for the old hardware but not for the new one without endstops.
