### ISSUE TITLE
Dafang FPS questions

### ISSUE THREAD

**Issue by TungstenE2** [EliasKotlyar/Xiaomi-Dafang-Hacks#788]
Hi all,

my video settings are:

![grafik](https://user-images.githubusercontent.com/39955685/48313155-974dc680-e5b8-11e8-88bb-e1f17f3911ec.png)

When I view the video by browser, tinycam andoid app or in VLC I have 3 different kinds of FPS and delays.

How come?

VLC is the best quality with small delay but good FPS rate, but why is tinycam and browser version so different?

thx

**Comment by Merwenus** [comment]
Have something similar. Using Synology and it is slow FPS no matter what I set in the options. :(
Like 1 frame per 10 seconds.

**Comment by ortegafernando** [comment]
try to reduce bitrate

**Comment by TungstenE2** [comment]
found the answer my self.

tinycam reason: energy saving option was enabled. so only very low FPS

browser: there is no live stream in browser version. according to sourcecode only currentpic.cgi is called with refresh

`<img id="liveview" src="cgi-bin/currentpic.cgi?1542740314388" onerror="this.src='css/unable_load.png';" onload="scheduleRefreshLiveImage(1000);">`

**Comment by fcastroruiz** [comment]
I use SMART and low bitrate to 256 and work best for me
