### ISSUE TITLE
Sending motion snapshots via MQTT requires saving snapshots (also saving to tmpfs vs sdcard)

### ISSUE THREAD

**Issue by mikeage** [EliasKotlyar/Xiaomi-Dafang-Hacks#789]
General question -- I'd like to have motion snapshots delivered via MQTT to my homeassistant, and so I've enabled both:
```ini
save_snapshot=true
publish_mqtt_message=true
```
[if I just had `publish_mqtt_message=true`, it kept reporting "Image Not Available". ]

However, I don't really want to keep the images on my local SD card; is there any reason not to set `max_snapshots=1` and just save it on a tmpfs, to avoid excessive writes to my card?

**Comment by jmtatsch** [comment]
`publish_mqtt_message=true` ought to be enough. Will write to sd temporarily though, temps would of course be better. What reported "Image Not Available"? Home Assistant? If you listen on the MQTT server, do you get the big binary blob?

**Comment by mikeage** [comment]
Correct, Home Assistant. When I added the saving it started displaying (and caching) images. I will check the mqtt topic when I'm actually home. Just to confirm, it's `myhome/dafang/motion/snapshot`, right?

**Comment by mikeage** [comment]
Indeed, the click doesn't work. But even the snapshot is only updated when I have `save_snapshot=true`

**Comment by jmtatsch** [comment]
You were right save_snapshot is required, which is easily misunderstood. But also I don’t want to write out every image, not even to tmpfs. Do we want yet another switch, maybe aquire_image?

**Comment by mikeage** [comment]
Just so I understand: `publish_mqtt_message` means to publish that there *was* motion, and `save_snapshot` means to both (a) save the image and (b) publish the details of that image? And you're asking about a new field in case someone only wants (b) and not (a)?

If so, what about the following names:
`publish_mqtt_message` -- send notification that there was motion
`publish_mqtt_snapshot` -- send notification containing the motion. Possibly, this implies / requires `publish_mqtt_message` = true
`save_snapshot` -- saves to disk, doesn't necessarily notify

This uses the word "publish_mqtt" for notifications, "message" for the detection, and "snapshot" for the image itself.

**Comment by jmtatsch** [comment]
Correct.
I like your proposal. Would you be willing to provide a PR for it?

**Comment by mikeage** [comment]
I will try. I need to find where the `save_snapshot` is being overloaded. If I can, I'll do it -- if not, I might come back and ask for your help :-)

**Comment by mikeage** [comment]
BTW, one thing while working on this; you save the image in the background, and then immediately try to send that file. This could be a race condition

https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/firmware_mod/scripts/detectionOn.sh#L25

**Comment by mikeage** [comment]
Ready. It works.
