### ISSUE TITLE
Light sensor problem

### ISSUE THREAD

**Issue by hondaj** [EliasKotlyar/Xiaomi-Dafang-Hacks#79]
when the light in the room is on the switching threshold, the camera constantly switches between the day / night modes. Is it possible to set the "hysteresis" somewhere in the configuration files? Is switching support embedded in the firmware?

This is a serious problem when you have motion detection enabled by the NAS software. And in addition, it can be a potential cause of damage to the filter switching system, which is implemented mechanically.

**Comment by shinebar1001** [comment]
A Hysteresis is not implemented now. One could create an average for 2 to x cycles to do this. That would fit to situations were the light smoothly dims, but not to situations where you Switch of a light in a cellar, so this would be another Option for the light sensor.

The switching support is quite unsophisticated: it takes 20 Bytes from the sensor and Counts the dots, as I didn't manage to fiddle out how the sensor data is formatted. So you could try to set the threshold higher in line 11 of scripts/ldr.sh just Change the 50 to 55 up to 60. But highly possible that won't fix your Problem.

**Comment by shinebar1001** [comment]
See #85 for a fix - this implements a configurable averaging for the light-measurement, so the constant switching should disappear, when you set the value > 1

**Comment by hondaj** [comment]
Thanks for add averaging and simple managing over web. I played with sleep time in previous of ldr.sh setted to 2m, 5m. I has a good result when light smoothly dimms, but has a one drawback. At night, when you turn off the light in the room, you have to wait a few minutes to switch to night mode :-( I think it should be added second mechanism whitch check "extreme" light change (if it's overall possible) and switch immediately when "detects" peak of light or dark. Today I updated my files from your latest work (thank you once again), seting AVG=3 and test it now for a 1-2 days. I give you an answer how it works in my conditions.

**Comment by shinebar1001** [comment]
The easiest way would be to reduce the delay between the measurements. (last but one line in /scripts/ldr.sh) - change sleep 30 to let's say sleep 10

Considering the detection of extreme light changes: I've got to think about that, but it's not really easy. Probably you got an Idea.

Let's say we go with 5 data points:
0,0,0,0,0 now the light is switched of, so we get 0,0,0,0,60 
my first idea was to compare the old average to the newest measurement:

if average of old measurement < 21 and new measurement = 60 => disable IR
This would mean:
0,0,0,0,0 new 60 -> 0 < 21 & new = 60 -> disable IR
0,0,0,0,60 new 60 -> 12 < 21 & new = 60 -> disable IR
0,0,0,60,60 new 60 -> 24 > 21 & new = 60 -> enable IR -> **meep**

if average of old measurement * 0,5 < 21 and new measurement = 60 => disable IR
This would mean:
0,0,0,0,0 new 60 -> 0 < 21 & new = 60 -> disable IR
0,0,0,0,60 new 60 -> 6 < 21 & new = 60 -> disable IR
0,0,0,60,60 new 60 -> 12 > 21 & new = 60 -> disable IR 
0,0,60,60,60 new 60 -> 18 > 21 & new = 60 -> disable IR 
0,60,60,60,60 new 60 -> 24 **>** 21 & new = 60 -> **meep**

And so on - any hints for a formula that works with 1 to 15 measurements? Probably use a weighted average? (That would break the AVG=2 thing)

**Comment by hondaj** [comment]
Ok, so because we don't have full data from light sensor (as i understand) it will be very hard to implement elastic, good working algorithm of light detection. 

So maybe do alternative as a second option based on eg https://sunrise-sunset.org/api?

**Comment by shinebar1001** [comment]
Yes, exactly. But even if we have full data, there is the Need to Change something in the algorithm. But I already have an idea (detecting the Change vom 0 -> 60 and storing this in a  variable to disable averaging until the average is above the threshold and the remove the variable. I'll try this when I've got some time and the camera is available (in the Moment it monitors our Baby, so Baby asleep -> I cannot try those Things). I already ordered another cam to Speed up processes :)

**Comment by hondaj** [comment]
> Considering the external day / night - data: this is possible, but what behaviour do you expect?

> 
this is an alternative idea, maybe rather as a separate option to choose.
The webcam already downloads the current date and time from the google server
Algorithm could work as follows:
- at 00:00:01 the camera takes the time of sunrise and sunset from the API server (you can enter your own coordinates with the link).
- downloaded data is used to enable and disable the night mode.

**Comment by jmtatsch** [comment]
@jthwho Thank you for figuring that out. 
Can you please make a pull request for the c & makefile at https://github.com/EliasKotlyar/Xiaomi-Dafang-Software. And a pull request here for the scripts + config.

**Comment by jthwho** [comment]
I hope I've done that all correctly.  This is my first time submitting on github, so please let me know if I've done something wrong.

**Comment by jmtatsch** [comment]
All is merged now. Thank you for your contribution.
