### ISSUE TITLE
Bad color balance - Xiaofang -

### ISSUE THREAD

**Issue by disco-v8** [EliasKotlyar/Xiaomi-Dafang-Hacks#790]
Hello, I got and hack Xiaofang 1s, and Dafang. 
Dafang is very good color balance by default.
But, Xiaofang is no good color balance by default.
I feel so, it is filterd by green glass. (greenish picture)
I want to get normal color... please tell me about how to set option?
Can I clear this problem?

CMD:
/system/sdcard/bin/getimage |  /system/sdcard/bin/jpegtran -copy none -optimize > /system/sdcard/www/xxx.jpg

WWW:
http://.../cgi-bin/currentpic.cgi

![currentpic](https://user-images.githubusercontent.com/5652445/48401306-30710e80-e76c-11e8-82ba-e398e632dc7d.jpg)

**Comment by jmtatsch** [comment]
Is it still a problem after 
* enabling/disabling the night mode.
* restarting the camera
* not using `jpegtran -copy none -optimize`

**Comment by disco-v8** [comment]
Hello, jmtatsch.
Thanks for your reply.

YES, I have already tried.
It was improved somewhat, when I changed "IR Cut" to OFF.
But...please see this.

Original Xiaomi App's picture, view is very good.
I want to take a same good picture... 
Please tell me.

![currentpic2](https://user-images.githubusercontent.com/5652445/48458272-f9046f80-e808-11e8-9d54-2e49a07b3a82.jpg)

**Comment by disco-v8** [comment]
Sorry!!!!!!!!!!!!!!!!!!!!!!
I was trying, Dafang's microSD into Xiaofang.
God say to me.
"You must start from STEP1" 
Oh!!!!!! It's beautiful!!!!!

Thanks all.

**Comment by disco-v8** [comment]
PS.

It is simple ...

rm -rf /system/sdcard/etc/sensor/
reboot

Bye! :-)
