### ISSUE TITLE
Escam G02 - General Support

### ISSUE THREAD

**Issue by EliasKotlyar** [EliasKotlyar/Xiaomi-Dafang-Hacks#795]
### Description

This is a general support issue for the Escam G02 Camera

**Comment by EliasKotlyar** [comment]
@codedmind: 
You can kind of "install" the dd commands by using the following small tutorial:
```
1. Download following binary and put it onto your sdcard: https://github.com/Dafang-Hacks/rootfs/blob/master/bin/busybox
2. Login via SSH and go into the SDcard folder(usually something under /mnt/)
3. Run "dd" commands using "./busybox dd" 
4. Dump the firmware using the normal dump tutorial : https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/hacks/firmware-dump.md
5. If there is any issue, just report here. I can try to help you.
```

**Comment by codedmind** [comment]
@EliasKotlyar i'm only able to connect via telnet.
I cannot run ./busybox when i try i get permission denied.
I moved the downloaded busybox and put int /tmp their i can run it but i get 

> # ./busybox dd 
>./busybox: line 1: syntax error: unexpected "("

The existent busybox in the camera don't have the dd applet
`# busybox 
BusyBox v1.18.1 (2017-08-11 16:47:04 CST) multi-call binary.
Copyright (C) 1998-2009 Erik Andersen, Rob Landley, Denys Vlasenko
and others. Licensed under GPLv2.
See source distribution for full notice.

Usage: busybox [function] [arguments]...
   or: busybox --list[-full]
   or: function [arguments]...

        BusyBox is a multi-call binary that combines many common Unix
        utilities into a single executable.  Most people will create a
        link to busybox for each function they wish to use and BusyBox
        will act like whatever it was invoked as.

Currently defined functions:
        arping, ash, awk, basename, bash, cat, chmod, cp, cttyhack, date, df, dhcprelay, dmesg, dnsdomainname, du, dumpleases, echo, egrep, false, fdisk, fgrep, free, getty, grep,
        gunzip, gzip, halt, hostname, id, ifconfig, init, insmod, kill, killall, linuxrc, ln, login, ls, lsmod, lsusb, mdev, mesg, mkdir, mknod, mount, mv, netstat, ping, poweroff,
        printenv, printf, ps, pwd, reboot, rm, rmmod, route, sed, seq, sh, sleep, stat, su, sulogin, sync, tar, telnetd, tftp, top, touch, true, udhcpc, udhcpd, umount, unzip, usleep,
        vi, wc, zcat`

**Comment by EliasKotlyar** [comment]
Hello codedminded,

Thanks you for your report. Can you please provide the files from another location? I cannot download them.

Greatings
Elias

**Comment by EliasKotlyar** [comment]
@codedmind :
It seems that the camera is using a completely different SoC. Its not a Ingenic T10/T20 based, but based on an ARM Processor. Unfortunately, we cannot make this hack work on an ARM, because the whole toolset is MIPS.

**Comment by TimelessNL** [comment]
@EliasKotlyar Are there Escam G02 units that do have a T10/T20 bases SoC? Since the unit is listed as supported in the README.md file: 98d46d5ece8557e445efbdf24b06809d10f9eeba

**Comment by CaptainHook8** [comment]
@EliasKotlyar I am also interested in making this GK7102 ARM camera working. Is there any chance to put a new firmware on?

Thank you.
