### ISSUE TITLE
After motion detects and yellow goes on, blue led goes off.

### ISSUE THREAD

**Issue by ortegafernando** [EliasKotlyar/Xiaomi-Dafang-Hacks#797]
I dont know if it is ok 
I usually see my camera blue led to know that "it is working".
I have begun to use autodetect motion option and MQTT snapshots. 
After motion is detected, yellow led is ON, and then goes off.
After yellow led is ON, blue led goes OFF, and after yellow led goes off, blue led doesnt recover its first state (led On).

May be it is a real way of doing it, but just in case, I open this "little" isue.

Thanks again.

**Comment by jmtatsch** [comment]
Fixed in ef89075
