### ISSUE TITLE
MQTT motion message or snapshot not working after last update

### ISSUE THREAD

**Issue by ortegafernando** [EliasKotlyar/Xiaomi-Dafang-Hacks#798]
Hi, I have just updated with webgui 20 minutes ago. I have no change any setting, but now MQTT motion message and snapshot don't work. Yesterday it work perfect.

What (log, command) do you need to check this?

Regards,

**Comment by jmtatsch** [comment]
You should probably start with a fresh mqtt.conf

**Comment by ortegafernando** [comment]
Probably because of [https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/804](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/804)
