### ISSUE TITLE
Open source loader - Dafang 64 MB

### ISSUE THREAD

**Issue by Schaagi** [EliasKotlyar/Xiaomi-Dafang-Hacks#805]
I have installed the open source bootloader for my 64 MB Dafang camera (dafang_64mb_v1.bin),
checked with the cat /proc/cmdline command.

To change the memory in uEnv.txt I'm looking for an example, because I only can find the version with 128 MB.

For example, is the bootcmd command the same (addresses) as the 128 MB version ?

I prefer to ask first, otherwise I have an unusable camera. 

Many thanks for your help.

Best regards

**Comment by Schaagi** [comment]
Hi Elias

As I understand, the open source bootloader is not only for the open source firmware, also for the Dafang Hacks. 
I also have tested to install the open source firmware, by formatting a sdcard with ext3 and copy the rootfs files, permissions as root, but I cannot start it. Maybe a permission problem ? It seems, the camera starts with the orig FW, instead of the OS FW.
Is the uEnv.txt necessary, to first start the OS FW ?

**Comment by EliasKotlyar** [comment]
Hello Schaagi,

I have updated the repository. You can find a updated version for your camera here:
https://github.com/Dafang-Hacks/rootfs/blob/master/uEnv_dafang64.txt

You will need to rename it to uEnv.txt and then try to launch it. It will help you a lot, if you have serial-headers attached to your camera. The open source firmware is still under development, there are a lot of issues.

**Comment by Schaagi** [comment]
Hi Elias
Thank you for your help. After installing the rootfs files including the 64mb uEnv.txt, the camera starts with blue led first, then switch to yellow and blue simultaneous. Then nothing happens anymore - no connection, only the leds glow.
Do you have any idea ?

**Comment by EliasKotlyar** [comment]
Check if the correct password is inserted into /etc/wpa_supplicant.conf 
Check if /etc/init.d/rcS has the right settings(especially under "# Start Network:"). Your camera could have a different wifi module installed, which requires a different setting there

**Comment by Schaagi** [comment]
Additionally this is the result of DMESG

[  215.964371]  sensor_read: addr=0x0 value = 0x0
[  215.968973] err sensor read addr = 0x0, value = 0x0
[  216.034350] i2c i2c-0: i2c_jz_irq 441, I2C transfer error, ABORT interrupt
[  216.041502] i2c i2c-0: --I2C txabrt:
[  216.045211] i2c i2c-0: --I2C TXABRT[0]=I2C_TXABRT_ABRT_7B_ADDR_NOACK
[  216.051824] error: sensor_read,172 ret = -5
[  216.056160]  sensor_read: addr=0x300a value = 0x0
[  216.061046] err sensor read addr = 0x300a, value = 0x0
[  216.126922]  sensor_read: addr=0xa value = 0xf
[  216.131968]  sensor_read: addr=0xb value = 0x22
[  216.136672] info: success sensor find : jxf22
[  216.141327] misc sinfo_release
[  216.271359] i2c i2c-0: Failed to register i2c client jxf22 at 0x40 (-16)
[  216.278316] tx_isp: Failed to acquire subdev jxf22, deferring probe
[  412.033825] RTL871X: send eapol packet
[  412.037839] RTL871X: set group key to hw: alg:4(WEP40-1 WEP104-5 TKIP-2 AES-4) keyid:1

**Comment by EliasKotlyar** [comment]
Hello Schaagi,

I have uploaded a new sensor driver. I hope it helps. There was an issue with that before. Just update via git pull to the latest version

Greatings
Elias

**Comment by Schaagi** [comment]
Hello Elias
It works !! :-)) Thank you very much for your support. Resolution with 1280x720 is working very smooth.
I will test now the motion detection and the night mode. 
I will get back as soon as possible and report back to you. 

Best regards and greetings from Switzerland
Schaagi

**Comment by Schaagi** [comment]
Hello Elias
I've tested the camera with rootfs. Works pretty stable already. 2 minor problems I have discovered.
- All files written in the media folder, will be deleted after booting the camera. 
- The LED control is reset at each reboot, i.e. the yellow and blue LEDs light up.

Best regards
Schaagi

**Comment by EliasKotlyar** [comment]
Hello Schaagi,

1. The media folder is mounted as a TMPFS. Refer to /etc/fstab . I dont know if this is really needed. You can try to remove it, and check if still everything is working. If yes, just provide it as a pull request.
2. Various LED States are not saved: I suppose that there are some issues with the saving due to changed paths. Do other setting save correctly?

Greatings
Elias
