### ISSUE TITLE
about HLS and MPEG-DASH not work

### ISSUE THREAD

**Issue by thylive** [EliasKotlyar/Xiaomi-Dafang-Hacks#806]
Path to feed : rtsp://192.168.22.217:8554/unicast works well 
but ：
HLS : http://192.168.1.217:8554/unicast.m3u8
MPEG-DASH : http://192.168.1.217:8554/unicast.mpd
not working ,i am using HLS to put camera stream to the google home hub ,but even use the "Native HLS Playback" in chrome ,i still can not play the "m3u8"
If someone have a clue that how to get it work.....
(i am using the Xiaomi-Dafang-Hacks latest version )

**Comment by hcgonzalezpr** [comment]
I  have the same issue.

**Comment by Swiftnesses** [comment]
I can't get it to play either, perhaps it's because of the HTTPS redirect?

**Comment by jmtatsch** [comment]
Never worked for me, also in pre-https times.

**Comment by contagon** [comment]
I'm trying to get the HLS stream going for the same reason (google home hub) and it doesn't work for me either, even in a browser.

**Comment by jmtatsch** [comment]
You need to start rtspserver with the -S flag. That may reduce the compatibility with various other ipcamviewers however.

**Comment by mpromonet** [comment]
Hi jmtatsch,

Fixing issue https://github.com/mpromonet/v4l2rtspserver/issues/117 it is now possible to enable HLS adding `-S` without transport stream muxing of unicast RTP.

Best Regards,
Michel.

**Comment by jmtatsch** [comment]
@mpromonet That is definitely good news. 
@nik0 Do you think you could rebase our custumized rtspserver on that current master?

**Comment by goermezer** [comment]
The -S flag works for me too. But then there is no audio audio stream in the feed. Should audio work with -S ?

**Comment by mpromonet** [comment]
Hi goermzer,
The audio is not in the HLS stream, but should be the same in rtsp stream with or without -S.
Best regards,
Michel.

**Comment by goermezer** [comment]
@mpromonet, no there is also no audio in the rtsp stream when using -S. The flag switches off audio in general for me.

**Comment by mpromonet** [comment]
@goermezer : if you are using release older than v0.1.1 the stream is muxed to TS and have no audio, starting with v0.1.1 the rtsp stream is not muxed into TS and should have audio.

**Comment by goermezer** [comment]
@mpromonet: Do you mean the release of v4l2rtspserver-master? This doesn`t print a version. According to the last online update the web page shows me Version: 2019-02-05T20:00:37Z.

**Comment by mpromonet** [comment]
@goermezer it depend how it was built, but normally the option -V should print the release

**Comment by goermezer** [comment]
@mpromonet: no, there is no version. It prints the usage without version. Even when running with -vv, there is no version visible. Github shows, that v4l2rtspserver-master was uploaded 7 month before.

I think, @jmtatsch has made some modifications. Perhaps this version doesn`t support audio with -S flag ?! Or does anybody else has audio in rtsp stream, when v4l2rtspserver-master is started with -S flag?

**Comment by jmtatsch** [comment]
@goermezer No, I never modified the rtspserver.

**Comment by mpromonet** [comment]
@goermezer the master from 7 month mux in TS the rtp stream and has no audio, you should use a newer version to allow streaming HLS using TS (without audio) and RTP using ES (wth audio). 
If there is no version I suppose that the build was done from an arvhive and not cloning git, as the version is computed from git information, it may be empty.

**Comment by goermezer** [comment]
@mpromonet: Thanks for clarifying it. I`m an end user and thought, it was a configuration issue on my side. 

I would be very happy, if someone could implement audio into HLS. A simple web page with live video is much better to integrate into smart home scenarios than a RTSP stream. And in parallel one can record the RTSP stream with ffmpeg.
