### ISSUE TITLE
RTSP stream problems when outside

### ISSUE THREAD

**Issue by mr2c12** [EliasKotlyar/Xiaomi-Dafang-Hacks#81]
Dear all,
my internet connection is a ADSL with an average upload speed of 97 kbps according to https://testmy.net

When using a Dafang with original fw, I can get a decent video stream when connecting from outside. I usually set it to "LOW" profile to get a stable stream.

When it comes to the hacked fw, the stream is very good when inside my local network, but it gets completely unusable when outside.
It does not seems an upload speed related problem given that:
1) the fps never get to more than 10fps
2) the speed is similar to the one I get with mi home and xiaomi fw

I run all my tests with vlc or tinycam.
The results is:
- difficult connection (it can takes up to a minute to get the first frame)
- when the stream starts, I get a good fps but it usually drops in a minute or so

Also try to set resolution to 1280x800 but nothing's changed.
Other attemps are:
- to put on the sd a clean hack
- add/remove http authentication
- add/remove rtsp authentication
- change http port
- change rtsp port

Is it possible that this is some problem related to v4l2rtspserver-master ?
What else can I do to identify the culprit?

If it is of any help, when outside it seems I am not able to get a complete screenshot from the web page, the image is corrupted in the bottom part, while I get it OK when inside my network.

**Comment by jmtatsch** [comment]
You can play around with resolution and bitrate a bit but i guess we really need someone to implement more efficient video/audio encoding  see #115. Please continue discussion there.
Closing this for now.
