### ISSUE TITLE
Missing uboot-flash in firmware_mod folder

### ISSUE THREAD

**Issue by kyutums** [EliasKotlyar/Xiaomi-Dafang-Hacks#811]
I have a Dafang with firmware version 5.5.1.243 (as per Mi Home). I have already tried it with the Mi Home and it works fine. I have tried flashing it with the CFW (1.3 and 1.0 versions) and am not sure if I did it correctly (but those are issues for another time).

I THINK I may have already flashed it correctly so I placed the contents of firmware_mod into the root folder of the SD card (a 2GB card, but partitioned the first 512MB of it to FAT32 [W95 FAT as per Ubuntu]). However, as I was checking the contents of the folder vs. the ones in the instructions at https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/hacks/install_cfw.md, I noticed that the firmware_mod did not have a uboot-flash (not sure whether file or folder) as per the instructions (https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/hacks/install_cfw.md#installation-of-the-new-firmware). **Where do I get uboot-flash**? I think this missing file or folder may finally get me to connect my camera to the network and make it work.

**Comment by EliasKotlyar** [comment]
You dont need a u-boot flash. You flash a different firmware(microsd bootloader), which will allow you to boot into a different firmware on your microsd.
