### ISSUE TITLE
OSD Timezone

### ISSUE THREAD

**Issue by droopanu** [EliasKotlyar/Xiaomi-Dafang-Hacks#814]
Currently looks like the OSD only shows the time in UTC. Can not find a way to change it to the local TZ:

![tz config](https://user-images.githubusercontent.com/7566514/48986634-753d7200-f17c-11e8-80e8-b36ce977e472.JPG)
![tz osd](https://user-images.githubusercontent.com/7566514/48986635-78386280-f17c-11e8-9931-c48fa4ccaa05.JPG)

**Comment by jmtatsch** [comment]
I seem to get exactly the ntp time on the OSD. However I live in UTC+1 and need UTC-1 to get my correct local time.
The OSD is applied there https://github.com/Dafang-Hacks/Main/blob/937ba5ddd5612de33a8451e740b5fa5e7b44679f/v4l2rtspserver-master/src/OSD.cpp#L215

**Comment by lenr9** [comment]
I agree. Normally I would set -8 but have to do +8 to get the correct time.

**Comment by JelmerT** [comment]
can confirm, seems to be inverted?
