### ISSUE TITLE
Security matters

### ISSUE THREAD

**Issue by kawett** [EliasKotlyar/Xiaomi-Dafang-Hacks#815]
Hi all,

First of all, thanks for the amazing work everyone has produced.
I just want to ask a few questions :
- Is it secure to connect remotely the the RTSP server throught VLC using credentials ? Are the frames streamed on the network encrypted ?
- Searching an answer to this question on the net, I found this report TALOS-2018-0684 (https://www.talosintelligence.com/reports/TALOS-2018-0684). I was wondering if this breach was somehow impacting this hack ?

Thanks for the help.
K.

**Comment by jmtatsch** [comment]
a) I don't think the frames are encrypted.
b) We likely are vulnerable to that.

**Comment by kawett** [comment]
Thanks for the answer.
I came to the conclusion that using a VPN is the safiest way to manage security cams (genius uh ?).
