### ISSUE TITLE
SW Night Configuration not populating

### ISSUE THREAD

**Issue by mdbrewer** [EliasKotlyar/Xiaomi-Dafang-Hacks#816]
Running two Wyzecam V2 camera both not populating the SW Night configuration.

Autonight is working, but I am unable to see the exposure rates as before. 
I executed an autoupdate on both and still the graphs are not reading.

I have rebooted and executed multiple Autonight via SSH.

I have accessed both cameras with chrome, Mozilla and IE. Same result.

![image](https://user-images.githubusercontent.com/13334531/49244330-63e6a680-f3c4-11e8-8c1d-af55a6f9b435.png)

**Comment by chisht** [comment]
@mdbrewer  Sounds like you are missing the file in cgi-bin. Try opening,
https://x.x.x.x/cgi-bin/getIspInfo.cgi

**Comment by mdbrewer** [comment]
The file exists and opens. 
****************** ISP INFO **********************
Software Version : H201709151519
Firmware Version : H01-380
SENSOR NAME : jxf22
SENSOR OUTPUT WIDTH : 1920
SENSOR OUTPUT HEIGHT : 1080
SENSOR OUTPUT RAW PATTERN : BGGR
SENSOR Integration Time : 1012 lines
ISP Top Value : 0x117c2193
ISP Runing Mode : Night
ISP OUTPUT FPS : 25 / 1
SENSOR analog gain : 46
MAX SENSOR analog gain : 128
SENSOR digital gain : 0
MAX SENSOR digital gain : 0
ISP digital gain : 1
MAX ISP digital gain : 45
ISP gain log2 id : 2
ISP total gain : 708
ISP exposure log2 id: 753041
ISP AE strategy: AE_SPLIT_BALANCED
ISP Antiflicker : 0[0 means disable]
Evtolux Probability Enable  : 0
ISP WB Gain00 : 280
ISP WB Gain01 : 256
ISP WB Gain10 : 256
ISP WB Gain11 : 603
ISP WB rg : 215
ISP WB bg : 138
ISP WB Temperature : 2700
ISP Black level 00 : 10
ISP Black level 01 : 10
ISP Black level 10 : 10
ISP Black level 11 : 10
ISP LSC mesh module : enable
ISP LSC mesh blend mode : 2
ISP LSC mesh R table : 0
ISP LSC mesh G table : 0
ISP LSC mesh B table : 0
ISP LSC mesh R blend : 0
ISP LSC mesh G blend : 0
ISP LSC mesh B blend : 0
ISP LSC mesh shading strength : 4096
ISP Sinter thresh1h : 8
ISP Sinter thresh4h : 5
ISP Sinter thresh1v : 8
ISP Sinter thresh4v : 5
ISP Sinter thresh short : 13
ISP Sinter thresh long : 13
ISP Sinter strength1 : 255
ISP Sinter strength4 : 255
ISP Temper thresh module :enable
ISP Temper thresh short : 100
ISP Temper thresh long : 100
ISP Iridix strength : 27
ISP Defect pixel threshold : 94
ISP Defect pixel slope : 650
ISP sharpening directional : 104
ISP sharpening undirectional : 122
ISP FR sharpen strength : 10
ISP DS1 sharpen strength : 50
ISP DS2 sharpen strength : 70
ISP CCM R_R : 67
ISP CCM R_G : 150
ISP CCM R_B : 29
ISP CCM G_R : 67
ISP CCM G_B : 29
ISP CCM G_G : 150
ISP CCM B_R : 67
ISP CCM B_G : 150
ISP CCM B_B : 29
Saturation Target : 0
Saturation : 128
Sharpness : 128
Contrast : 156
Brightness : 140

**Comment by chisht** [comment]
Is this still a problem? It could be because of the using the network versions of the scripts. Which have been moved to local in #860

**Comment by chaoranxie** [comment]
@mdbrewer did you ever figure it out the issue? i am having the same issue with the newest code from master
