### ISSUE TITLE
Dafang with two Mac adress

### ISSUE THREAD

**Issue by rusudanion** [EliasKotlyar/Xiaomi-Dafang-Hacks#82]
Hello to allora, i have a dafang with different mac adress.the Mac adress show in mihome is not the same as i see behindthe the camera case. I can connect to xiaomi server to see the streaming intorno mihome app. The cam connect to mi home and i see his, can i update the firmware and see status network, but i can streaming or do something because se give me connection error. When i used as Direct wifi streaming alla function. Maybe i can change the mac adress with your hack? Can you help me? Thankyou

**Comment by rusudanion** [comment]
Any help please .

**Comment by jmtatsch** [comment]
Yes, you can change the mac address in run.sh when loading the driver with 
`insmod /driver/8189es.ko rtw_initmac="YOUR_MAC_ADDRESS"`
