### ISSUE TITLE
fisheye dewarping funcation?

### ISSUE THREAD

**Issue by u0x01** [EliasKotlyar/Xiaomi-Dafang-Hacks#820]
* exact camera hardware: dafang

### Description

MiHome App is supported fisheye dewarping(distortion correction), is cfw supported?

![img_3961](https://user-images.githubusercontent.com/9703404/49419661-bc51e580-f7c2-11e8-8a18-8b5f11bfff96.PNG)

**Comment by kngharv** [comment]
ffmpeg has "lenscorrection" function.  I am wondering can someone simply find out the correct k1 k2 and other values so some degree of de-fish can be achieved.
