### ISSUE TITLE
Wireless Password Restrictions

### ISSUE THREAD

**Issue by netgeek1** [EliasKotlyar/Xiaomi-Dafang-Hacks#822]
Does any one know about the password restrictions for wireless?

I have 2 linux based IP cameras connected to my SSID "IoT_Untrusted".
  The password for the network is "^SFc4g6vzz1j^GMuIo1@" (not actual password)
I bought a Wyze v2 and installed OpenIPC on it and it connected to without an issue to "IoT_Untrusted". 
I heard better things about Xiaomi-Dafang-Hacks to I decided to install it. 
With Xiaomi-Dafang-Hacks booted up, it would not connect to "IoT_Untrusted". I checked the startup logs and didn't see anything jump out except:

=========== Not Working ===========
wlan0: Added interface wlan0
wlan0: State: DISCONNECTED -> DISCONNECTED
nl80211: Set wlan0 operstate 0->0 (DORMANT)
netlink: Operstate: ifindex=2 linkmode=-1 (no change), operstate=5 (IF_OPER_DORMANT)
Writing wpa stat file /tmp/wpastat
Daemonize..
udhcpc: 
Initialized gpios

I modified my wpa_supplicant.conf to SSID "Homenet". 
  The password for the network is "hQz97hdVKh" (again, not actual password).
This time it connected without issue. Thinking I may have had a lines issue I connected via SSH, modified the SSID and PW to "IoT_Untrusted" and rebooted. Again it did not connect. 
Quick pull of the sdcard, change SSID and PW back and it reconnected without issue. 

The startup.log doesn't show anything really different for the working one, just that it actually connected and added the dns.

wlan0: Added interface wlan0
wlan0: State: DISCONNECTED -> DISCONNECTED
nl80211: Set wlan0 operstate 0->0 (DORMANT)
netlink: Operstate: ifindex=2 linkmode=-1 (no change), operstate=5 (IF_OPER_DORMANT)
Writing wpa stat file /tmp/wpastat
Daemonize..
udhcpc: deleting routers
adding dns 192.168.0.250
adding dns 192.168.0.251

Let me know if you need anything else. 
Thanks,
netgeek1

**Comment by sorvani** [comment]
Try not using special characters. Just make the password long.
