### ISSUE TITLE
firmware version is: 5.6.2.43

### ISSUE THREAD

**Issue by donblack01** [EliasKotlyar/Xiaomi-Dafang-Hacks#825]
The xiaofang1s firmware version is: 5.6.2.43 Is it impossible to hack?

**Comment by peterhoeg** [comment]
I just received a Xiaofang 1S last week and managed to install the bootloader without any problems. I admittedly do not know which firmware version it came with.

**Comment by EsEnZeT** [comment]
It's working with this FW

**Comment by lay55** [comment]
I have the 5.6.2.43 installed...cant seem to get it to work
