### ISSUE TITLE
Javascript still refers to external site (making it unable to work when no internet)

### ISSUE THREAD

**Issue by arkhub** [EliasKotlyar/Xiaomi-Dafang-Hacks#827]
During internet outage, I noticed that tha dafang camera take longer times to connect via http and some function like SW night configuration and changing thame unable to work. After I viewed the source I found that there are script that still dependant to outside connection like : 
`<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/smoothie/1.34.0/smoothie.js"></script>`
and `<a id="theme_choice_1" href="javascript: setTheme('1')" class="theme_choice dropdown-item" data-css="https://cdn.jsdelivr.net/npm/bulmaswatch@0.6.2/slate/bulmaswatch.min.css">`

Can both script moved to internal so the camera still works in no internet connection?

**Comment by jmtatsch** [comment]
Sure please open a PR

**Comment by arkhub** [comment]
sorry for late reply... I think I have to learn how to use `Pull Requests` first since I'm not too familar with Git.
