### ISSUE TITLE
Xiaomi Dafang for 22.59 Euro !!

### ISSUE THREAD

**Issue by int2018** [EliasKotlyar/Xiaomi-Dafang-Hacks#828]
Dear all,
I bought the Xiaomi Dafang early this year thanks to Elias (+ supporters) it is a truely nice device.
One problem remains: It is hard to find for a good price.
Since I wanted another one I checked the web now and then and 2 days ago I found a deal with a good price.
If you are interested in the device you can check out this offer*:
https://www.lightinthebox.com/en/p/xiaomi-dafang-1080p-smart-ip-camera-wifi-ptz-full-hd-motion-detection_p6222038.html?prm=1.5.1.1

I ordered it but I could not find any information about the firmware version it is running. So I hope I get get it to work with this beautiful "hack" - which I'd rather call "jailbreak".

**Have a nice xmas everybody!**

* I am not related to this company in any way and I don't get any fees :-(

**Comment by purposelycryptic** [comment]
Here on the other side of the pond, the rebranded version from Wyze (with their own firmware, of course) can be had for $30 + S/H from their website, or $20 + S/H for the non-turreting cube model (called the Wyze Cam Pan and Wyze Cam v2 by then, respectively), or for $25/$40 on Amazon with free shipping over $35.

Wyze had a great deal up until just recently on the little cubes @ $51 for a 3-pack, but sadly, I waited too long, and when I ordered today (1 turret, 5 cubes), the offer was gone. Still, $150 for 6 cameras after shipping and taxes is a great deal when that's the price of a single Nest cam.

**Comment by S474N** [comment]
But there is +6.01$ for shippment, +3.33$ for tax insurence and +0.99$ for insurence. It's better to buy normal on eBay/Ali with same price.

**Comment by int2018** [comment]
I am sorry, I should have checked the offer in more detail. I have more confidence in a shop like lightinthebox.com than in a no-name seller. But yes, there a offers on ebay like this, for 15$:
https://www.ebay.com/itm/Indoor-Xiaomi-Dafang-1080P-120-Smart-IP-Camera-Wi-Fi-Full-HD-Motion-Detection-US/192753703325?epid=0

Straight from China, I am not sure if such deals really work...

Anyway, the combination of this cam + the hack is really a good deal.

Have a nice time!

**Comment by S474N** [comment]
Seller with score 10? It will be fake.

**Comment by jmtatsch** [comment]
I don’t think the original poster is affiliated with lightinthebox. His github account seems legit. I very much welcome someone scraping together good deals on the camera. We could make this an official Dafang sourcing thread.

**Comment by int2018** [comment]
Dear all, 
Plase take my apology if my initial note is misunderstood as spam for lightinthebox. 
As I said; I am not affiliated by any means with this company and I am not a bot. I don't get any fees, discounts or refunds - not even a warm handshake. This is totally a private matter to share a good deal for anybody who is interested in byuing such device (and "good"is also only my personal opinion). And I guess you wouldn't be here if you are not interested in this device?

After reading ohter comments I think it is still a fair deal for a device which can be customzied to such extend. If the device from Wyze can also be used for this "hack" that it is a reasonable option too.

The reduced price will end on saturdy anyway, so I close the thread and I wisch you all a merry xmas!

**Comment by int2018** [comment]
Wait a minute... Initallly this "project" was created closely for this device but now it can be used with other devices that have similar hardware. 
Lets look at it this way: Thanks to Elias (& contributors) this is a cool software package with many nice features which enhances the value of the hardware. (And in addition it removes the china-phone-home crap). 
If you want to use the software package you need one of the following devices: (as mentioned on the prject page)

Now there is only a small addition (or in a separate thread), a link to a "good" deal. 
Maybe "look on Amazon" is enough but maybe there are some other deals out there and maybe "we" can create an "omnibus order" (sounds strange).

Or is this already too much commercial thinking which is not wanted on github?

For me it is like this: I don't buy china ip cams if I cannot jailbreak them - even if they are cheap. And yes, I would buy any of the cams mentioned here only **because** I can jailbreak/hack them.

**Comment by int2018** [comment]
A Happy New Year everyone!

I just wanted to let you know that I received the Dafang camera via regular postal package without any issues (tax, toll or missing CE certificates etc.).  
I prepared a SD card with the "hack", wpa_supplicant.conf etc. and started the virgin cam without any "china setup" in advance. 
It works like a charme and I just wanted to thank Elias & all the support for the effort to make this a very nice product!

The camera is still available under the link above but slightly higher price but it is still a very good for this device. But this is my personal opinion anyway... 

Have a great 2019!!!

![grafik](https://user-images.githubusercontent.com/35401885/50594528-dd2a5b00-0e94-11e9-947e-f8551afc16a4.png)
