### ISSUE TITLE
Reverse screen from camera

### ISSUE THREAD

**Issue by shahzadgodil** [EliasKotlyar/Xiaomi-Dafang-Hacks#830]
Hello,

I am getting a reverse camera screen. See attached screenshot

https://www.awesomescreenshot.com/image/3781113/d6646ca84279f6435c3519458a66c7d7

Camera: 
Da Fang Camera

Please suggest

Thanks

**Comment by EliasKotlyar** [comment]
Go to "Settings"-> Image Flip. Then it should be flipped right.
