### ISSUE TITLE
Not connected to network

### ISSUE THREAD

**Issue by bchiu2000** [EliasKotlyar/Xiaomi-Dafang-Hacks#831]
After i connected power to my dafang, a yellow light was on then it turned blue.  I assume the mod is working.  However, it is not on my network.

i am using WPA2-Personal,  I wonder if my wpa_supplicant is correct?

network={
        ssid="home"
        scan_ssid=1
        key_mgmt=WPA-PSK
        psk="K8L83jK9he"
}

Any way to check what's wrong with it?

Thanks,

**Comment by bchiu2000** [comment]
I looked at the log/start.log

Here it is..

==================================================
Starting the Dafang Hacks Custom Application Layer
==================================================
Loaded common functions
Created etc directory on sdcard
Bind mounted /system/sdcard/bin/busybox to /bin/busybox
Bind mounted /system/sdcard/root to /root
Bind mounted /system/sdcard/etc to /etc
Created cron directories and standard interval jobs
wpa_supplicant: wpa_supplicant v2.5
random: Trying to read entropy from /dev/random
Successfully initialized wpa_supplicant
Initializing interface 'wlan0' conf '/system/sdcard/config/wpa_supplicant.conf' driver 'default' ctrl_interface 'N/A' bridge 'N/A'
Configuration file '/system/sdcard/config/wpa_supplicant.conf' -> '/system/sdcard/config/wpa_supplicant.conf'
Reading configuration file '/system/sdcard/config/wpa_supplicant.conf'
Failed to open config file '/system/sdcard/config/wpa_supplicant.conf', error: No such file or directory
Failed to read or parse configuration '/system/sdcard/config/wpa_supplicant.conf'.
Failed to add interface wlan0
: Cancelling scan request
: Cancelling authentication timeout
udhcpc: 
Initialized gpios
Determined image sensor model as jxf22
dropbear: 
bftpd: 
Created new certificate for webserver
lighttpd: 
Startup finished!

**Comment by bchiu2000** [comment]
So I looked at the config directory. I see that there's a file called " config/wpa_supplicant.conf.dist" but no "config/wpa_supplicant.conf"  so I am going to rename and see what happen.

**Comment by SomebodySysop** [comment]
I'm sure you've probably figured it out by now, but if you look at installation instructions: https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/hacks/install_cfw.md

It appears you missed steps 3 and 4 of Installation of New Firmware: https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/hacks/install_cfw.md#installation-of-the-new-firmware

Beyond that, here is an issue which might help further with wifi connect problem: https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/642
