### ISSUE TITLE
IPv6 Support

### ISSUE THREAD

**Issue by thedevleon** [EliasKotlyar/Xiaomi-Dafang-Hacks#832]
I just received a XiaoFang S1 and flashed the custom firmware. All working, so far so good.

I want to access my camera via the internet (going to be used for octoprint), but my ISP provider uses DS-Lite and thus I don't have a dedicated IPv4 address.

So my only option is to use IPv6, but no IPv6 address is listed in `ifconfig` or  `ip -6 addr show`.

Searching the repo and the filesystem for ipv6 yields nothing, so I guess there is no support yet.
Is there any way I could add ipv6 support?

**Comment by andrejkmet7** [comment]
I am also interested in ipv6, I tried to configure it on my own, but I failed... Would be very thankfull for any kind of information that would lead us to working ipv6...

**Comment by Emilv2** [comment]
Same thing here, I'm trying to build the ipv6 module using https://github.com/Dafang-Hacks/kernel/ ,  but trying to build the kernel with ipv6 module fails with this error:
```
net/built-in.o: In function `tcp_nuke_addr':
(.text+0x4c0a0): undefined reference to `in6addr_any'
net/built-in.o: In function `tcp_nuke_addr':
(.text+0x4c0a4): undefined reference to `in6addr_any'
net/built-in.o: In function `tcp_nuke_addr':
(.text+0x4c1e8): undefined reference to `in6addr_any'
net/built-in.o: In function `tcp_nuke_addr':
(.text+0x4c230): undefined reference to `rt6_lookup'
make: *** [Makefile:781: vmlinux] Error 1
````

Just building the modules with 'make modeles' works, but loading the module fails:
```
[root@DAFANG:~]# insmod /system/sdcard/driver/ipv6.ko
insmod: can't insert '/system/sdcard/driver/ipv6.ko': unknown symbol in module or invalid parameter
```
dmesg:
```
[18957.121820] ipv6: Unknown symbol inet6_register_icmp_sender (err 0)
[18957.137393] ipv6: Unknown symbol inet6_lookup (err 0)
[18957.153294] ipv6: Unknown symbol inet6_del_protocol (err 0)
[18957.166233] ipv6: Unknown symbol secure_tcpv6_sequence_number (err 0)
[18957.191810] ipv6: Unknown symbol tcp_nuke_addr (err 0)
[18957.210838] ipv6: Unknown symbol inet6_hash_connect (err 0)
[18957.216757] ipv6: Unknown symbol inet6_unregister_icmp_sender (err 0)
[18957.236324] ipv6: Unknown symbol inet6_protos (err 0)
[18957.243804] ipv6: Unknown symbol __inet6_lookup_established (err 0)
[18957.250505] ipv6: Unknown symbol __inet6_hash (err 0)
[18957.256035] ipv6: Unknown symbol inet6_lookup_listener (err 0)
[18957.281664] ipv6: Unknown symbol inet6_add_protocol (err 0)
[18957.287802] ipv6: Unknown symbol icmpv6_send (err 0)
```

No idea what's going wrong here.

Building the kernel with ipv6 (not as module) works, but I'd rather not risk the possibility to brick my camera.

**Comment by timsamart** [comment]
I am also interested in this because of the same reasons as @thedevleon any progress yet?

**Comment by thedevleon** [comment]
No progress yet. Hope someone figures this out! I have no way of accessing my camera outside my local network now.

**Comment by fleminra** [comment]
AFAIK, for getting video delivered over RTSP over IPv6, getting an IPv6 address assigned to the network device is only half the battle. Dafang-Hacks uses [v4l2rtspserver](https://github.com/mpromonet/v4l2rtspserver), which in turn uses live555, and to my knowledge, live555 does not yet support IPv6.

**Comment by timsamart** [comment]
it is currently propably easier to create a vpn and just connect to the local network and stream the data (it is a crappy solution though!)
