### ISSUE TITLE
Where else is there a chat for this project?

### ISSUE THREAD

**Issue by rsamboceu** [EliasKotlyar/Xiaomi-Dafang-Hacks#835]
Sorry. For posting here. I am a newbie. But doesn't seem like anyone is active on the chats. Or is there a chat that I don't know about?

I have issue with logging on with SSH and recording to a network share like a NAS. 

Please let me know where I can go to like another chat or another place for newbies?

Sorry for posting here but i am lost and cannot find help.

THank you.

**Comment by jmtatsch** [comment]
There is the one chat that you know. It can only work if the people that have already some experiences help the newbies once in a while. But people are tired of helping newbies because the don’t do their research before asking for help.

**Comment by rsamboceu** [comment]
Hi jmtatsch. I've done my research and have tried many things that i have found online. But just wanted some help in something that i am having trouble with. I am not trying to be rude or anything but I just don't know why i cannot log in through ssh. I have flashed the cfw and have the firmware mod on my sd. everything is working. but unable to ssh. but it is ok since this is not a place for questions i understand. I'll just have to wait to see if anyone will help me in the chat.
