### ISSUE TITLE
Original 128MB Xiaofang 1S Bootloader?

### ISSUE THREAD

**Issue by Swiftnesses** [EliasKotlyar/Xiaomi-Dafang-Hacks#837]
Hi guys,

I eventually got the hacks loaded on my new camera (came with the firmware from December that prevented it starting from the SD Card). I'd like to locate a copy of the original bootloader if anyone has it? My model has 128MB Ram (as per the original startup log).

For now I've flashed the one from the original firmware folder, but it currently only shows 64MB during startup, is this the reason I cannot get 1080P streaming to work? Is there a way to revert it back to 128MB?

**Comment by jmtatsch** [comment]
Ask @EliasKotlyar to create a boot loader for your memory config if it doesn’t exist already. Yes that is the reason why 1080p runs out of memory and dies.

**Comment by EsEnZeT** [comment]
Same issue here; is it possible we need to generate new hacked firmware with different config?

Latest FW for Xiaofang 1S = 5.6.2.138

**Comment by jmtatsch** [comment]
Boot with a serial interface attached or look at your untouched bootline. Cfw Installation doesn’t touch the boot loader or bootline automatically (yet). You would have needed to do that explicitly, chances are you are stock.

**Comment by EsEnZeT** [comment]
@jmtatsch  unfortunately I'm not able to connect via serial :(

**Comment by jmtatsch** [comment]
Get them or go the other way.

**Comment by Amitcgartist** [comment]
> I have updated the Repo with the Xiaofang 128MB Version. Please have a look

how can i flash the original firmware? please help

**Comment by jmtatsch** [comment]
Fw or bootloader? Elias wrote about bootloader.

**Comment by Amitcgartist** [comment]
> Fw or bootloader? Elias wrote about bootloader.

firmware. i think bootloader is ok. actually i mistakenly flashed wyze firmware. can you help please?

**Comment by Amitcgartist** [comment]
![p_20181226_172004](https://user-images.githubusercontent.com/46184069/50473827-829c8500-09e4-11e9-8216-2c7b49a74d7d.jpg)
i have this model

**Comment by jmtatsch** [comment]
All originals fw dumps we have collected are right here on github. Just flash the correct one this time.

**Comment by Amitcgartist** [comment]
@jmtatsch i could not find :( . i know how to flash (demo.bin ) via sd card.
If you can send me the link to the original demo.bin file for this model, that would be great help for me.
thank you.

**Comment by Amitcgartist** [comment]
@jmtatsch i am not a programmer. :( i cant use my camera. plz help

**Comment by jmtatsch** [comment]
Read first, ask questions later. Good luck.
