### ISSUE TITLE
[CFW] [XiaoFang 1s] on ext3/ext4/exFAT

### ISSUE THREAD

**Issue by EsEnZeT** [EliasKotlyar/Xiaomi-Dafang-Hacks#838]
Hi,

after completing point '1 Installation of the microSD bootloader'

I s it somehow possible to load custom_cfw from ext3/ext4 or exFAT?
Or the only option is to stick fo FAT32 card to load cfw?

Thanks

**Comment by jmtatsch** [comment]
Install our boot loader and then use rootfs path.

**Comment by EsEnZeT** [comment]
@jmtatsch I don't want to brick the device, so I'm not sure it's safe.

What I did:
- formatted card to FAT32
- Install microSD bootloader (https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/hacks/install_cfw.md)
- Installed new firmware (https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/hacks/install_cfw.md#installation-of-the-new-firmware)

What I see in logs:
`[    0.000000] Kernel command line: console=ttyS1,115200n8 mem=41700K@0x0 ispmem=8M@0x28B9000 rmem=15644K@0x30B9000 init=/linuxrc rootfstype=squashfs root=/dev/mtdblock2 rw mtdparts=jz_sfc:256k(boot),2048k(kernel),3392k(root),640k(driver),4736k(appfs),2048k(backupk),640k(backupd),2048k(backupa),256k(config),256k(para),-(flag)
`

Not sure if this correct, and how exactly I should flash u-boot if it's 128MB?

Device is only booting if card is formatted to FAT32

**Comment by EliasKotlyar** [comment]
You should flash u-boot to make the device boot from EXT3. The stock u-boot is not capable of booting EXT3. Where exactly are you stuck? As far as i can see, you will need to flash the u-boot for your device and then install the Ext3-System.
