### ISSUE TITLE
Problem accessing NOT through cloud but as wireless client

### ISSUE THREAD

**Issue by Pharizna** [EliasKotlyar/Xiaomi-Dafang-Hacks#84]
I'd like to use my Dafang as an IP standard camera and not to use the Xiaomi servers... but I can't find any Access Point and I have two routers, etc very close to the camera :(

![image](https://user-images.githubusercontent.com/3939655/36044314-84327e1a-0dd2-11e8-990a-129474dc5b05.png)

I don't know but there some "interesting" messages in LOG... related with?

![image](https://user-images.githubusercontent.com/3939655/36045104-f290d936-0dd4-11e8-83d3-d452393afdf6.png)

**Comment by shinebar1001** [comment]
Just edit config/wpa_supplicant.conf on the sdcard as the installation instruction says. The network settings still need some attention and are not working 100%

**Comment by shinebar1001** [comment]
Actually these functions were for Xiaofang-Hacks. You are always connected als "wireless client" as the cloud-functions are not enabled with this hack. I removed the options in #75
