### ISSUE TITLE
Remove SSL and change port

### ISSUE THREAD

**Issue by shahzadgodil2** [EliasKotlyar/Xiaomi-Dafang-Hacks#842]
Hello,

I am trying to disable SSL  and change web port to 909. But it is not working. I want to remove SSL to avoid SSL warning on Camera first page
This is a warning I want to remove
https://www.awesomescreenshot.com/image/3790986/b40d8565d2a2f361bc3e23173c4fb759

Also changing of the port is also not working

Here is my lighttpd.conf.dist. But it is not working 
http://s3.amazonaws.com/LivetecsFiles/Personal/lighttpd.conf.dist

**Comment by shahzadgodil2** [comment]
Here is the content of port-related configuration


### server.port = 9097
# #
# uncomment to allow more exotic hostnames e.g. with underscores
#server.http-parseopt-host-strict = "disable"

mimetype.assign = (
  ".html" => "text/html",
  ".txt" => "text/plain",
  ".jpg" => "image/jpeg",
  ".png" => "image/png",
  ".css" => "text/css",
  ".js" => "text/javascript"
)
index-file.names = ( "index.html" )
server.modules = ("mod_auth",
                  "mod_authn_file",
                  "mod_redirect",
                  "mod_rewrite",
                  "mod_cgi",
                  "mod_fastcgi",
                  "mod_dirlisting",
                  "mod_staticfile",
                  "mod_accesslog",
                  "mod_openssl")

cgi.assign = ( ".cgi" => "/bin/sh" )



$SERVER["socket"] == ":9097" {
  ssl.engine = "disable"
  ssl.pemfile = "/system/sdcard/config/lighttpd.pem"
}

**Comment by jmtatsch** [comment]
Did you reboot?

**Comment by shahzadgodil2** [comment]
Yes

**Comment by darookee** [comment]
You need to rename the file to `lighttpd.conf`.

**Comment by Heracles44** [comment]
if i want reove ssl i only have to rename lighttpd.conf ? it's right?

**Comment by Heracles44** [comment]
i have change enable to disable and my xiaofang don't work now...

**Comment by Combie81** [comment]
I am also having the same issue - simply changing ssl.engine = "enable" to ssl.engine = "disable" just prevents access to the web interface.
Has anyone sucessfully changed their settings to allow plain http access?  If so would you be kind enough to share the steps taken?
I've tried disable/disabled and reboots after each change with no success.  I've also tried with/without commenting out the mod_redirect and mod_openssl modules so I'm not sure what I'm missing :/ ?

**Comment by jmtatsch** [comment]
Try something like this

```
server.document-root = "/system/sdcard/www"

server.port = 80

mimetype.assign = (
  ".html" => "text/html",
  ".txt" => "text/plain",
  ".jpg" => "image/jpeg",
  ".png" => "image/png",
  ".css" => "text/css",
  ".js" => "text/javascript"
)
index-file.names = ( "index.html" )
server.modules = ("mod_auth",
                  "mod_authn_file",
                  "mod_redirect",
                  "mod_rewrite",
                  "mod_cgi",
                  "mod_fastcgi",
                  "mod_dirlisting",
                  "mod_staticfile",
                  "mod_accesslog",
                  "mod_openssl")

cgi.assign = ( ".cgi" => "/bin/sh" )

# Support letsencrypt SSL cert paths
# (we don't want to upgrade to SSL nor auth' this path)
$HTTP["url"] !~ "^/.well-known/(.*)" {

    auth.backend                = "htdigest"
    auth.backend.htdigest.userfile = "/system/sdcard/config/lighttpd.user"
    auth.require = ( "/" => ("method" => "basic", "realm" => "all", "require" => "user=root"))
}

## where to send error-messages to
server.errorlog             = "/tmp/lighttpd-error.log"

## CGI (etc) stderr log
server.breakagelog = "/tmp/lighttpd-cgi-stderr.log"

## accesslog module
accesslog.filename          = "/tmp/lighttpd-access.log"
```

**Comment by Combie81** [comment]
Thanks - but sadly UI is still redirecting to https :(
Can lighttpd also be updated from 1.4.50(current in f/w) to 1.4.55(latest version)?  Don't know if this will fix anything but just an idea

**Comment by jmtatsch** [comment]
You need to restart your camera to make it read the file anew.

**Comment by Combie81** [comment]
I feel so daft!!  Turns out after testing in IE this worked no problem.  After testing in chrome problem persisted.  Cleared all cache/history/etc for all time and boom http works.  Guessing the site cookie was causing the issue.
