### ISSUE TITLE
HLS Stream doesn't work?

### ISSUE THREAD

**Issue by Swiftnesses** [EliasKotlyar/Xiaomi-Dafang-Hacks#843]
Running the Opensource firmware and the latest RoofFS, it seems the HLS stream doesn't work?

I see people have had issues with the standard hack, has anyone actually got it working?

Thanks... :)

**Comment by contagon** [comment]
+1. It's also not working for me and I'd like to know if there's a way to get it working, it could help me out a ton.

**Comment by matthew-humphrey** [comment]
Same here. I am running the new "open source bootloader", though.

**Comment by saipsa** [comment]
> Project seems mostly dead, not sure they'll be a fix anytime soon, sadly :(

Why don't you create a PR? Or pay to the people who create the PRs?

**Comment by contagon** [comment]
I noticed in the video server log, it shows the start command as 

"/system/sdcard/bin/v4l2rtspserver-master -fMJPG -W640 -H360  -E MP3:16000:44100 -r 2  -P 8554"

However at https://github.com/mpromonet/v4l2rtspserver, it shows that to uses the HLS server it needs the -S parameter to start, could it just be missing this? Where this need to be inserted to?

**Comment by jmtatsch** [comment]
@matthew-humphrey that could very well be the culprit.
Can you implant index.html and hls.light.min.js files and test out your suspicion?

**Comment by matthew-humphrey** [comment]
I discovered that the "-S" option causes issues with stability of the video server, as well as breaking interoperability with some webcam software like ipcamviewer on iOS.

**Comment by jmtatsch** [comment]
@matthew-humphrey found a way to make it work with safari also in 668558f, can you test?

**Comment by contagon** [comment]
Just updated and would love to test it. Maybe a noob question, but could someone tell me how/where to add in the "-S" parameter?

**Comment by jmtatsch** [comment]
rtspserver.conf

**Comment by matthew-humphrey** [comment]
Just tried it on my iPad pro. Sorry, still doesn't work.

**Comment by jmtatsch** [comment]
@matthew-humphrey I only tested with safari on mac and assumed it would work on safari for iOS as well. Unfortunately not even their demo seems to work on iOS so maybe you can dig there further.

**Comment by jneilliii** [comment]
Is this still possible to use in the latest master or beta version of dafang here? My understanding is I just update `RTSPH264OPTS` to include `-S` it should just work and then I can access the stream from the URL `http://dafang:8554/unicast.m3u8`?
