### ISSUE TITLE
Constant buzz from audio channel, with no actual audio picked up from microphone

### ISSUE THREAD

**Issue by masterpotatohead** [EliasKotlyar/Xiaomi-Dafang-Hacks#846]
* Xiaomi Dafang 3:
* the Xiaomi-Dafang-Hacks commitid (caff4f7)

Audio pass through on RSTP appears to be broken. Getting a constant buzzing sound, with no actual environmental audio, regardless of settings:

- Connecting to camera through Blueiris
- Video path is set as /unicast
- No path set for audio
- Format set as RSTP
- Setup RSTP back-channel for talk support (PCM-U format) is unchecked
- Audio set to enable audio channel
- From IP camera stream

Tried various settings in Dafang Hacks menu, but reverted to standard:
- Audio format - MP3
- Sample in rate - 16,000
- Sample out rate - 44,100
- Filter (low filter) - NS Filter Moderate
- Volume - 80
- High pass filter checked
- AEC filter checked

Have tried changing the format to OPUS, PCM, PCMU to no avail. Tried various Hz settings on both input and output as well as toggling filters on/off and all filter presets.

Any thoughts from anyone as to if this is an error, or user error?

**Comment by bkcberry** [comment]
Did you figure anything out? I have a Wyze v2 and am having the same problem with blue Iris. VLC plays the audio no problem

**Comment by bkcberry** [comment]
i changed audio to PCM on the camera, and set it up in blue iris according to [this image](https://ipcamtalk.com/attachments/upload_2018-7-30_19-38-53-png.31924/) (requires signing in) and it is working now
