### ISSUE TITLE
SW auto night setting...no control of IR LED...always on.

### ISSUE THREAD

**Issue by youbecha** [EliasKotlyar/Xiaomi-Dafang-Hacks#847]
I really like the new SW night mode, works great, but always turns IR LED on, and tends to wash out image due to near camera items...in my application IR LED off works better.

But I cannot find any setting to control that...if I turn if off manually, it turns back on the next night cycle...

...sure I could cut the wires, but why not toggle in software?

**Comment by jmtatsch** [comment]
Do you have another source of infrared light?
Otherwise maybe you don't need a night mode at all.

**Comment by SomebodySysop** [comment]
I am running Xiaofang 1S T20 indoors facing my front porch balcony.  It's been there for several months with no IR reflection in window.  Below are my camera control settings.

![wyzecam02 camera control 2018-12-24_20-58-17](https://user-images.githubusercontent.com/41084665/50412849-7e435280-07bf-11e9-8152-312b4456a08d.jpg)

**Comment by youbecha** [comment]
Night mode puts it into B&W for increased detail in the dark, if it isn't in night mode it is still in color but the image is nearly completely black.  For SomebodySysop...we are talking about the SW auto night mode.  Is there any documentation on what the command line settings are?   Right now it goes in to night mode, I manually turn off the IR LED and get a fantastic picture...but if I don't turn off the IR LED the image is completely washed out...I guess an option is to physically disable the LEDs.

**Comment by chisht** [comment]
There is no such command-line option in the tool at the present, but sure it can be added if needed.
Just for clarification, in night mode you want just the grey-scale without touching IR Cut or IR LED, right?

Well, if nobody is looking at it, I sure can add that option to the tool.

**Comment by youbecha** [comment]
I need the IR led off because it is mounted behind glass, and the IR led reflects off the glass and blocks the image.   In auto SW night mode it always turns on the IR led and I have to log into the camera to manually turn it off.   Once it is off the rest of the SW auto night mode works perfectly.   So I would like an option in the SW auto night mode to deselect the IR led.   Thanks

**Comment by chisht** [comment]
Please check https://github.com/Dafang-Hacks/Main/pull/29
More details in that PR.

You can either check that code out and compile yourself. Or use the precompiled autonight binary attached.

[autonight.zip](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/files/2753231/autonight.zip)

**Comment by chisht** [comment]
Or you can simply remove https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/firmware_mod/scripts/common_functions.sh#L381 line

**Comment by youbecha** [comment]
commenting out that LED On line should solve my problem, thanks!

**Comment by chisht** [comment]
Well, using the new autonight and adding `-g 'setconf -k n -v 1'` to commandline would achieve that as well. But I agree, commenting the line in the script is better solution.

I'd leave it upto @jmtatsch , if he wants the new commandline option in that PR or not.

**Comment by jmtatsch** [comment]
@chisht thank you for helping out. I will hopefully get around to commit new auto night binaries these days.

**Comment by jmtatsch** [comment]
A solution for this issue has been committed with https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/commit/d4bfab99e3f64f3159774382f41c1989629a2af6 . Please test.

**Comment by MrUkleja** [comment]
Works as expected for me.
This is great, until this point I used automation in my smart home system (Home Assistant) for this ;)
Thank you
