### ISSUE TITLE
Dafang MQTT Denied Publish

### ISSUE THREAD

**Issue by cristimi** [EliasKotlyar/Xiaomi-Dafang-Hacks#849]
I have a bought a new **Xiaomi Dafang** camera for a week ago and I am trying to integrate it into Home Assistant. While applying the hack (**2018-12-22T13:53:10Z** ) worked out very well thanks to a very well written How-To, I am having real issues in setting up MQTT. 

I have been trying all I could think of but I didn't succeed to have the MQTT setup to publish or update the sensors to HomeAssistant. I was trying to use the embedded broker / mosquito / cloudMqtt and I am receiving the same sort of message repeating forever from all brokers when I am starting both MQTT Status / Control Servers on the camera.

Below is an extract from the log from cloudMqtt: 

```
- 2018-12-23 17:55:47: New connection from IPADRESS on port 19338.
- 2018-12-23 17:55:47: New client connected from IPADRESS  as mosqpub|19065-DAFANG (c1, k60, u'dafang').
- 2018-12-23 17:55:47: Sending CONNACK to mosqpub|19065-DAFANG (0, 0)
- 2018-12-23 17:55:48: Denied PUBLISH from mosqpub|19065-DAFANG (d0, q0, r1, m0, 'myhome/dafang', ... (193 bytes))
- 2018-12-23 17:55:48: Received DISCONNECT from mosqpub|19065-DAFANG
- 2018-12-23 17:55:48: Client mosqpub|19065-DAFANG disconnected.`
```

and the mqtt.conf

```
############################################################
# edit this file and move it to /system/sdcard/config/mqtt.conf #
############################################################
export LD_LIBRARY_PATH='/thirdlib:/system/lib:/system/sdcard/lib'

# Options for mosquitto_sub & mosquitto_pub
USER=dafang
PASS=dafangpass
HOST=m20.cloudmqtt.com
PORT=19338

# Define a location
LOCATION="myhome"

# Define device name
DEVICE_NAME="dafang"

# Define the base topic used by the camera
# send a message to myhome/dafang/set with the payload help for help.
# Results will be placed in myhome/dafang/${command} or topic/dafang/error - so please subscribe topic/dafang/# for testing purposes
TOPIC="$LOCATION/$DEVICE_NAME"

# Define an autodiscovery prefix, if autodiscovery is desired:
AUTODISCOVERY_PREFIX="homeassistant"

# Define additional options for Mosquitto here.
# For example --cafile /system/sdcard/config/DST_Root_CA_X3.pem --tls-version tlsv1
# or use a special id to connect to brokers like azure
MOSQUITTOOPTS=""

# Add options for mosquitto_pub like -r for retaining messages
MOSQUITTOPUBOPTS=""

# Send a mqtt statusupdate every n seconds
STATUSINTERVAL=30
```

I would really appreciate some help as I am really stuck and don't have any clue on how to move forward.

**Comment by jmtatsch** [comment]
Embedded broker  needs a workaround someone discovered here in the issues but I don’t really remember where exactly. Mosquito should work out of the box. Any cloud service should require encryption.

**Comment by cristimi** [comment]
My original intention was to use mosquito, but I was trying with the embedded and cloudmqtt to identify the issue. 

If mosquito should work out of the box, probably I am doing something wrong, but I really need help to identify the issue.
