### ISSUE TITLE
Which bootloader to flash? 

### ISSUE THREAD

**Issue by bkcberry** [EliasKotlyar/Xiaomi-Dafang-Hacks#850]
I apologise if this has been answered somewhere, I've searched around but am unsure if myself here.. 

I have the original wyze cam, which bootloader do I use? Is there a copy of the stock bootloader anywhere? I've tried to flash a couple different ones and think I may have messed something up.. although maybe not, it still boots up and connects to the Wyze app. Please and thanks

**Comment by EliasKotlyar** [comment]
You can find the stock firmware here:
https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/tree/master/firmware_original

**Comment by bkcberry** [comment]
Thanks, but I also need to know which CFW to flash for the Wyze cam v1?

**Comment by EliasKotlyar** [comment]
Wyzecam V1 is not based on a MIPS Processor. Please refer to https://github.com/samtap/fang-hacks

**Comment by bkcberry** [comment]
Thank you!
