### ISSUE TITLE
Default NV on ?!

### ISSUE THREAD

**Issue by Snotmann** [EliasKotlyar/Xiaomi-Dafang-Hacks#851]
Hey guys,

as the automatic night vision detection went crazy for my i want to put the night vision default on.
Could someone told my how to do that ?

I searched for the settings in config but didnt find it ... only the service config and i dont want to start the service on boot up.

Regards,
Snot

And Merry Chrismas you all !!!

**Comment by Snotmann** [comment]
Ok got it myself. Its provided in the run.sh

**Comment by SomebodySysop** [comment]
That is great.  Do you mind sharing how you did it, for the benefit of others who might have the same issue?

**Comment by Snotmann** [comment]
under search for /system/sdcard/run.sh
## Set leds to default startup states:
ir_led on
ir_cut off
yellow_led off
blue_led on
