### ISSUE TITLE
RTSP server wont start with changed Motion detection region

### ISSUE THREAD

**Issue by klingon888** [EliasKotlyar/Xiaomi-Dafang-Hacks#852]
Wyze Cam v2.  Successfully installed modded FW and works fine.  But when I change the Motion Detection Region Boundaries, the RTSP H264 server tries to start but crashes.  Manually restarting it doesn't work either.

Settings:
- Video resolution 1600x900, VBR, 25fps, 2000kbps
- Motion Detection Region Boundaries - [ (0, 150 - or any non-zero nbr will make it crash), (1600, 900) ]

I notice it works if the video resolution is set to 1280x720. Is this a limitation of the FW?  Thanks.

**Comment by klingon888** [comment]
> let there be some gap between motion detection boundaries and the boundaries of the viewport.

Not sure I understand. Where do I set the boundaries of the viewport?  Can you pls elaborate more or provide some example settings? Thanks.

**Comment by stephenjamieson** [comment]
I was about to post the same thing, happens on the xiaomi 1s too

**Comment by klingon888** [comment]
Now I understand what saipsa meant - no crash as long as the second coordinate is less than 900, i.e. (1600, 890). Feels like a bug to me.
