### ISSUE TITLE
does not work, the LED only turns yellow

### ISSUE THREAD

**Issue by Amibarbara** [EliasKotlyar/Xiaomi-Dafang-Hacks#856]
I have Xioafang S1 with firmware 5.6.2.138

I have followed the installation procedure

I have Xioafang S1 with firmware 5.6.2.138

I have followed the installation procedure

Download the CFW-Binary for your Camera

Xiaomi XiaoFang T20 333053c3e98af24e0e90746d95e310a3c65b61f697288f974b702a5bcbba48a9

Copy the CFW-Binary from step 1 to the formatted microSD card and rename it to "demo.bin". There must be no other files on the microSD! This is really important and it won't work if there are any other files on there.

Remove the power cable from the camera and plug the microSD card into the camera

Hold down the setup button on the camera while

Plugging in the USB power cable

Keep the setup button pressed for another 10 seconds

Wait until the firmware has finished flashing (like 3 minutes). You can disconnect the power as soon as the base starts move (DaFang / Wyzecam Pan).

Remove the microSD card and power up the camera

You should see the blue led shining for 5 seconds (not blinking) before the base starts moving (DaFang / Wyzecam Pan).

until here I have succeeded ... but when I try to turn it on again the led light is only yellow and there is no sound. 

then I try to the next stage

Installation of the new Firmware
Clone the repository from github. If you are on Windows download the repository as zip file. Make sure nothing gets windows line endings.
Copy everything from "firmware_mod" folder into the root of the microSD

but Xiaofang doesn't react anything?

what should I do, at least the xiaofang camera works as before even if it runs without a hack

**Comment by jmtatsch** [comment]
are there logs on the sd card?

**Comment by Amibarbara** [comment]
it looks like a file appears when running demo.bin 
but now it's deleted.

**Comment by Amibarbara** [comment]
I have tried repeating it and now it works ... but after this hack does the device still synchronize with mi home?

**Comment by jmtatsch** [comment]
No.
