### ISSUE TITLE
how to auto upload to the host server or accessed from public ip??

### ISSUE THREAD

**Issue by Amibarbara** [EliasKotlyar/Xiaomi-Dafang-Hacks#857]
where is the location of the motion detected recording file and how to automatically upload the file to the host server? and how do you make the camera accessible from outside the ip router or public ip?

**Comment by shado80** [comment]
Files are stored in Media folder on sdcard. For watching stream I use phone app tinyCam and I also have problems with accessing cam from external ip (although I did port forwarding on my router).
