### ISSUE TITLE
How Proses Restore Firmware Original Xiaofang 1S ?

### ISSUE THREAD

**Issue by Amibarbara** [EliasKotlyar/Xiaomi-Dafang-Hacks#858]
after being curious about the xiaofang hack feature and a long try and finally succeeded. but it turns out that there are many features that I can't get such as the motion detection region not avaible, not automatic recording and the hassle of opening the microsd lid just to configure the file. I finally wanted to make it like before

how is the process of returning the original firmware? Is it the same as the CFW install stage by entering all the .bin files in the Xiaomi-Dafang-Hacks / firmware_original / xiaofang / 5.6.2.43 / to micro sd folder?

**Comment by JakobM999** [comment]
take out the sdcard, and let it boot up, wait for about 20 sec, push and hold the rest button for 3 sec, it will say something, do all the Mi Home app thing, and do the firmware upgrade if you wish.
It took me 10-20 try to get it to work.

**Comment by mckebabs** [comment]
@JakobM999 Any tips on how to run the original firmware beside what you wrote? I tried at least 20x and still not able to start the wifi pairing.

**Comment by jshplayer** [comment]
After many attempts i finally managed to get an original firmware image back on there and link it back with Mi app. The light status didn't even show the correct value but i got there in the dark...

**Comment by mckebabs** [comment]
@jshplayer could you please share a step-by-step how you managed to do that?

**Comment by jshplayer** [comment]
First download: https://www102.zippyshare.com/v/OhOnBJg6/file.html

Trust me i already tried this firmware and initially had issues still but it's the only one that finally worked.

Save it as demo.bin on the root as normal AFTER a fresh wipe of the SD card using SD Card Formatter.

Hold the setup button as normal and power it up with the SD card inserted, let go after the light turns blue. Now at this point the usual status disappears and you have to go by sound and time. Wait for it to go orange for a sec and it may make a brief clicking noise again - 1 second after this point hold the setup button again for a couple of seconds (even if the status light is blank) it should make the little chinese voice sound, if not let go and hold it down again for a couple of seconds, at this point start again if you don't hear it.

After the chinese voice, point it at the Mi app QR code as normal and although the lights may not show any status, it may flash blue or go solid blue but let the app setup continue and it should link up. This took me a few attempts but now i can get it every time, after it's linked you can re-enable the status light and update the official firmware. Things go back to normal from there.

I used an 8GB and 32GB sd card formatted in fat32 without issues, but formatting it after each attempt helped as the process stuffed up sometimes after just deleting the files. Remember even if the light is out it's still technically working just keep trying.

**Comment by elfive** [comment]
> First download: https://www102.zippyshare.com/v/OhOnBJg6/file.html
> 
> Trust me i already tried this firmware and initially had issues still but it's the only one that finally worked.
> 
> Save it as demo.bin on the root as normal AFTER a fresh wipe of the SD card using SD Card Formatter.
> 
> Hold the setup button as normal and power it up with the SD card inserted, let go after the light turns blue. Now at this point the usual status disappears and you have to go by sound and time. Wait for it to go orange for a sec and it may make a brief clicking noise again - 1 second after this point hold the setup button again for a couple of seconds (even if the status light is blank) it should make the little chinese voice sound, if not let go and hold it down again for a couple of seconds, at this point start again if you don't hear it.
> 
> After the chinese voice, point it at the Mi app QR code as normal and although the lights may not show any status, it may flash blue or go solid blue but let the app setup continue and it should link up. This took me a few attempts but now i can get it every time, after it's linked you can re-enable the status light and update the official firmware. Things go back to normal from there.
> 
> I used an 8GB and 32GB sd card formatted in fat32 without issues, but formatting it after each attempt helped as the process stuffed up sometimes after just deleting the files. Remember even if the light is out it's still technically working just keep trying.

Tested myself, it works very well (20210115).
After connected to mi-home app, I have to upgrade camera firmware twice(once to 5.6.2_138 and once to 5.6.2_197).
**BECAREFUL DO NOT UPGRADE TO 5.6.2_1019, THIS VERSION DISABLED VIDEO SAVING FUNCTION!!!! INSTEAD THEY PROVIDE CLOUD STORAGE SERVICE!!!**
