### ISSUE TITLE
Synology + RTSP using Wyzecam V2 - Connection Lost + Restored over and over again

### ISSUE THREAD

**Issue by deten** [EliasKotlyar/Xiaomi-Dafang-Hacks#859]
Wyzecam V2

Camera Settings:
Video Format: "VBR"
Audio Format: "MP3"
Sample Bitrate: 16000
Out sample Rate: 44100
Filter: NS Filter Moderate
High Pass Filter is Checked
AEC Filter is Checked

So I am trying to figure out what the best Audio and Video format are, I found on the Synology page the following information: https://www.synology.com/en-us/knowledgebase/Surveillance/help/SurveillanceStation/ip_camera

User Define supports MJPEG (HTTP, RTSP), H.264 (RTSP), H.265 (RTSP), and MPEG4 (RTSP) video formats, only AAC audio format is supported

In MPEG4/H.264/H.265/MXPEG format, Surveillance Station supports audio streaming in both Live View and video recording. The audio support is only available when the IP camera is equipped with audio function. (MXPEG is a video codec implemented by Mobotix.)

Surveillance Station supports G.711, G.726, AAC, AMR and PCM audio formats. The actual supported audio formats depend on the camera capability.

The frame rate should be set appropriately for the best recording performance.

So according to this, using "User Defined" camera which is what I did only supports those formats listed above. Currently the camera supports H264 RTSP & MJPEG RTSP Streams. Which is how I setup the camera. However, under the video settings it has other video formats:

VBR
FixedQp
CBR
SMART
I am not sure which is best but by default it uses VBR.

**Comment by deten** [comment]
Is there a solution to this?

**Comment by Dreded** [comment]
i have the same issue with zoneminder, the fix seems to be to disable motion detection on the camera.

**Comment by deten** [comment]
@Dreded Do you notice an unusually large amount of data being used on local network with the wyzecam?

**Comment by deten** [comment]
> I also have a WyzeCam v2(actually 3 of them) and all have the same issue with zoneminder, the fix seems to be to disable motion detection on the camera.

I have done this but still getting the error.  Not a fix for me.  Could you elaborate exactly what you disabled, there are many settings...
