### ISSUE TITLE
New Xiaofang 1S on 5.6.2.138

### ISSUE THREAD

**Issue by danmed** [EliasKotlyar/Xiaomi-Dafang-Hacks#862]
I cannot get this thing to flash..

I've tried several SD cards, currently one with a 512mb partition..

I figure i need to downgrade the firmware, but i can't find any instructions for the 1S.. (i know i'm probably blind)... can anyone point me in the right direction or am i stuck on this firmware for now?

**Comment by JakobM999** [comment]
wait for a working hack for the Xiaofang 1S, no need to try to downgrade

**Comment by danmed** [comment]
ok, will do thanks..

**Comment by danmed** [comment]
I Know i was advised to wait for a hack, but is there actually a way to downgrade these things?

**Comment by quantum8** [comment]
Adding another device to the waiting list. I haven't updated to 138 just in case. Mine's currently on 5.6.2.77.

**Comment by brownpride3282** [comment]
https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks

does anybody here tried this?

**Comment by danmed** [comment]
Dude.. th

> https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks
> 
> does anybody here tried this?

Do you realise that's actually where we are writing these issues?

**Comment by brownpride3282** [comment]
up

**Comment by EliasKotlyar** [comment]
Please stop spamming. Many thanks!

**Comment by pvklink** [comment]
somebody got the 1s working from 5.6.2.77.

**Comment by keitetran** [comment]
Same me, :( 5.6.2.138 not lucky
