### ISSUE TITLE
Record video/audio to network share

### ISSUE THREAD

**Issue by netRunner0** [EliasKotlyar/Xiaomi-Dafang-Hacks#869]
Please add the ability to record audio / video in a network folder

**Comment by stobiaskoch** [comment]
Put a script in /system/sdcard/config/autostart, my script
mount-ntfs:
#!/bin/sh
mount -o nolock -t nfs [SERVER-IP]:/[FOLDER] /system/media/nas

Store the Videos & Picture in /system/media/nas

**Comment by netRunner0** [comment]
Isn't the video stored on raspberries?
