### ISSUE TITLE
RTSP problem, XF1S with Synology Video Station

### ISSUE THREAD

**Issue by ShentaTsai** [EliasKotlyar/Xiaomi-Dafang-Hacks#870]
First of all, I would like to say a big Thank you for all your hard work on moding the XiaoFang,
great job... and if any of the developer come to Bangkok by any chance, please let me know,
I buy you guys a beer.

OK, here's the problem I am looking at: VLC stream looks great, even at high bit rate with high frame rate.  And VLC can record the video like a charm.  But, when I try to use my Synology to record the RTSP videos, something very strange happened, seems all video recorded are corrupt and not able to be play back.   Here's video explanation of my trouble:

https://youtu.be/oDvMmtP3vP4

If anyone has found what I did wrong or have any suggestion, please let me know.  And, yes,
I did gave low resolution and bit rate a few try also, same problem.

Thanks in advance for your help.
Cheers
Shenta

**Comment by deten** [comment]
I too have issues with Synology.  It also constantly says connection is lost and restored.
