### ISSUE TITLE
HTTPS Certificate Browser-Problem 

### ISSUE THREAD

**Issue by Giraffenaffe** [EliasKotlyar/Xiaomi-Dafang-Hacks#871]
When I try to open the https://dafang website in my local network I'll always get a certificate warning. 
Same when using the internal IP.
After commitment to open the unsecure site the web access works as it should, but with this issue all the streams are not working because the access to the server ca not be established. Date of the certificate runs out 01.06.1970.

**Comment by Dopeyr** [comment]
The certificate is self-signed so this is expected. However, the streaming should be unaffected as it is not streamed over HTTPS, but over RTSP (port 8554 by default).

**Comment by jmtatsch** [comment]
The date of the certificate is probably caused because your internet/ntp server did not work the first time the camera was booted up. Just start fresh.

**Comment by Giraffenaffe** [comment]
I tried the reboot sometimes before, but today it seems to work.

Thanks for your help
