### ISSUE TITLE
Crash after last update

### ISSUE THREAD

**Issue by dmolner** [EliasKotlyar/Xiaomi-Dafang-Hacks#872]
After last update.
The camera stop after some time.

**Comment by jmtatsch** [comment]
Tracking enabled?

**Comment by dmolner** [comment]
Hello,
I can confirm that error.
Two cams with new firmware crash at 5:15 and 5:30.
Other with older version works fine

**Comment by Snotmann** [comment]
Did you got Xiaofang or Dafang ?
I got two Xiaofang and it seems that the logs are massive too big so maybe the cam crashes on logrotate ?!

**Comment by dmolner** [comment]
Hello,
I have two Dafang and one Xiao.
I need restart the camera for good work some time.
I not sure time before crash.
I reboot now and test.

**Comment by tungmeister** [comment]
I'm also seeing this. I'll be lucky if the camera stays on for an hour before locking up.

**Comment by jmtatsch** [comment]
Can someone please try out which commit exactly caused this ?

**Comment by dmolner** [comment]
20 hours aprox. work.
Yesterday reboot cameras at 17.45 and today at 13.30 all stops.

**Comment by nimbus39** [comment]
what is the firmware version of dafang that caused the error?

**Comment by dmolner** [comment]
I have this problem one month a go

**Comment by dmolner** [comment]
@jmtatsch @nimbus39 
I have problem with
Version: 2018-12-30T04:56:09Z

After this version I have problem.
I not change every version, i'm not sure my previus version probably 8/4/18 m/d/y

**Comment by jmtatsch** [comment]
if you cannot pinpoint the exact commit i cannot help

**Comment by dmolner** [comment]
@jmtatsch 
Is possible download olders versions?
I test and say when fail

**Comment by jmtatsch** [comment]
Sure it’s all git. Just check out any commit you like. Also read up on git bisect.

**Comment by MarkSanders54** [comment]
I'm running into the same issue, but I updated after 6+ months of not updating. So I'm not sure what exactly is causing it. I've been installing progressively older versions to find the cause. It takes ~20 hrs before it crashes. So it has been a slow process.  I load only the firmware_mod folder and my wifi config and let the camera do its thing until it crashes. I'm at Oct 14 right now. I'll let you know when I get to a point where it no longer crashes. 

To switch versions, I ftp in, copy firmware_mod to the /tmp folder. Then I ssh in and RM -r /system/sdcard and then mv /tmp/firmware_mod/* /system/sdcard and then power cycle. 

That should be fine, correct? The camera is somewhat inaccessible.

**Comment by dmolner** [comment]
I can't found update have this problem.
I hope you can found.

**Comment by jejedelbarro** [comment]
Same problem here. I uploaded from a very old version and then camera need to be rebooted every day.

**Comment by subhanzg** [comment]
It crashes whenever i use pan movement on wyze cam pan. it crashes and camer stops working after 2-3 steps

**Comment by subhanzg** [comment]
how can i help to pinpoint the issue?

**Comment by jmtatsch** [comment]
Try a decent power supply.

**Comment by subhanzg** [comment]
Already did. Doesn't work. I'm thinking to fetch old version of dafang and use that again.
