### ISSUE TITLE
No CPUID

### ISSUE THREAD

**Issue by jgwinner** [EliasKotlyar/Xiaomi-Dafang-Hacks#875]
* exact camera hardware:

Wyze Cam, v2 (WYZEC2)

* the Xiaomi-Dafang-Hacks commitid (from `git log`) you are experiencing the issue with:
Downloaded today

### Description

I got everything working, changed some settings (Camera name, disabled arrows)

I can't get the CPU ID from the system. 

### What did you do to debug the issue

Ran cat/proc/cpuinfo:

```
[root@CARECAM_1:~]# cat /proc/cpuinfo
system type             : bull
machine                 : Unknown
processor               : 0
cpu model               : Ingenic Xburst V0.1  FPU V0.0
BogoMIPS                : 858.52
wait instruction        : yes
microsecond timers      : no
tlb_entries             : 32
extra interrupt vector  : yes
hardware watchpoint     : yes, count: 1, address/irw mask: [0x0fff]
isa                     : mips32r1
ASEs implemented        :
shadow register sets    : 1
kscratch registers      : 7
core                    : 0
VCED exceptions         : not available
VCEI exceptions         : not available

Hardware                : isvp
Serial                  : 00000000 00000000 00000000 00000000
[root@CARECAM_1:~]#


```

No joy

### Evidence

output above

### Contribute Back  

Not sure what the CPU is, but it would help if there was a unique identifier. I'm trying to keep track of the cameras in a cloud database. Makes it hard :)

**Comment by jgwinner** [comment]
No one?

**Comment by jmtatsch** [comment]
Look at how the wifi mac is being set:  
`MAC=$(grep MAC < /params/config/.product_config | cut -c16-27 | sed 's/\(..\)/\1:/g;s/:$//')
`
