### ISSUE TITLE
h264 NOK Auto restart?

### ISSUE THREAD

**Issue by tungmeister** [EliasKotlyar/Xiaomi-Dafang-Hacks#878]
I'm getting issues with the RTSP-H264 sever crashing quite frequently.  The log is spammed with:
`2019-01-07 18:42:33.027 (1562.213s) [update_thread   ]         ImpEncoder.cpp:380      0| Failed to read the JPEG stream: Polling stream timeout`
It's state can be seen as NOK and to fix it I have to stop and start. Would it not be possible for the server to auto restart in the event of failure?

**Comment by kaymach** [comment]
I get that error when I run out of memory (like going to 1080P). Could be a leak issue.

**Comment by tungmeister** [comment]
it seems to happen within 20 minutes or so. I've already got 64MB swap file so I don't think it's memory?

**Comment by Snotmann** [comment]
I got the same here ... seems the server crashes ... maybe because cpu time -.-

**Comment by MMilesMM** [comment]
I got the same problem but it crashes for me after 20 seconds. Any Ideas how to fix that?

**Comment by prankousky** [comment]
My RTSP Server also crashes after a few seconds (restart or manual activation of server). Even the preview image in the web GUI freezes after a few seconds. I just installed and configured my first dafang and now don't know what to do. Any ideas?

**Comment by itMax86** [comment]
Some problem with xiaofang s1

**Comment by x23piracy** [comment]
Hi,

here the same the rtsp server likes to crash.

**Comment by rtenklooster** [comment]
Same problem here, it stops working after 20 minutes.

**Comment by tungmeister** [comment]
still happening for me, it's making the camera useless. Is there no way to monitor the service and restart it in the event of failure? sureley that would be easy to implement rather than fixing whatever the issue is.

**Comment by prankousky** [comment]
@tungmeister I only have one camera, which runs fine at the moment, so I don't want to temper with it... but it should be possible to write a script that checks on the service by running `pgrep <servicename>` and run it if it is not running. I am sure there is a way to test for failure (even though the process is still running) as well, which might make things easier. This script could run each x minutes via `cron`.
(just my 2 cents, I am currently in the process or learning bash scripting and this would be my first attempt)

**Comment by rtenklooster** [comment]
Ok, yesterday I made two changes and so far it's running stable.
As suggested here: https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/955 i have created a gap between the edges.
I have also lowerd the resolution, so will give it some time, then try the higher resolution.

**Comment by sepodele** [comment]
Anyone created a script like this? Can't use the webcam when it crashes all the time. Weird thing is that I have an identical camera without issues. Perhaps poor quality control from Xiaomi.
