### ISSUE TITLE
2 CAM in one Network dont work

### ISSUE THREAD

**Issue by 20silencer04** [EliasKotlyar/Xiaomi-Dafang-Hacks#879]
I have 2 Wyze Cam V2 and try to get the both working in one network.
If i just power on one everything work, but if they are both powered on nothing work. The both got a different Static ip, but seams that my Router thought they are one. Got someone any idea what is going wrong. Thanks

**Comment by Snotmann** [comment]
I use the subnet 192.168.2.x /24 at home with two cam's and they work fine ... must be a config problem on wifi

**Comment by 20silencer04** [comment]
I usw a Fritzbox with the subnet 192.168.10.x / 255. Cam 1. is x.x.x.60 & 2. is x.x.x.62. or ist ist possible they got the same Mac adress?!

**Comment by 20silencer04** [comment]
Now ich checked it. They got the Same Mac adress. How can i Change the Mac adress?!

**Comment by jmtatsch** [comment]
https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/806e500cdabac48fdaa4ac9810aa9c31fea023fc/firmware_mod/run.sh#L115

**Comment by 20silencer04** [comment]
THX WORKED. Close pleas
