### ISSUE TITLE
Not conecting to the WiFi

### ISSUE THREAD

**Issue by Pharizna** [EliasKotlyar/Xiaomi-Dafang-Hacks#88]
Hi

With the latest 83efb58  commit it is not possible to connect to WiFi... using the same wpa_supplicant.conf as previously. 

I've just downlgraded to the previous version and now it's working again

**Comment by shinebar1001** [comment]
The commit didn't change anything in the way the camera connects to WiFi - is the camera getting an IP-Address? Are you still able to ping it?

**Comment by Pharizna** [comment]
Not, now the camera has lost the IP and my router can't see its MAC address for example and it don't give an IP

**Comment by richardvertigan** [comment]
I appear to have the same problem.

**Comment by shinebar1001** [comment]
My fault. I had some files in DOS-Mode, so run.sh wasn't executed (and many others as well) Fixed that in #87

**Comment by shinebar1001** [comment]
Until @EliasKotlyar accepts the PR you can use this one: https://github.com/shinebar1001/Xiaomi-Dafang-Hacks

**Comment by Pharizna** [comment]
Thank you. Just installed the new mod from your site and not problem with the connection but...

1.-

**Comment by shinebar1001** [comment]
Arghs... All fixed. Please redownload. Thank you & a big sorry

**Comment by Pharizna** [comment]
OK. Typo problems solved but...the auto-nigth service-detection enable problem... remains :(

**Comment by shinebar1001** [comment]
The auto-night-detection is fixed in my repo and submitted as a pull request. Sorry for the hassle.

Concerning the size OSD - the OSD was implemented by @nik0 and @EliasKotlyar

**Comment by Pharizna** [comment]
I'm using your repo ... and the auto-right-detection enable appears to be wrong :(
