### ISSUE TITLE
SD card turns to Read-Only everytime power is cycled

### ISSUE THREAD

**Issue by kaymach** [EliasKotlyar/Xiaomi-Dafang-Hacks#880]
Hello. This is pretty consistent and 100% reproduce-able. Anytime I lose power to the camera or disconnect the power cable, the SD card will turn to read-only and I must plug it back into my PC to let windows fix the drive. Once I re-seat it back into the camera, it works fine again until the next power cycle down the line.

Installing it outdoors was a nightmare as I had to constantly take apart the outdoor enclosure and climb up a ladder to fix the SD card as I was not able to SSH in to remount it. It refused the connection.

The last time this issue was posted, it closed as the user just basically did what I did. To avoid future users and myself the headache of having to run around in case of power cycle, it would be useful to know how to permanently fix this issue going forward.

Any ideas?

**Comment by MiguelAngelLV** [comment]
I have the same problem. I thought my card was broken but I see that it happens to more people.

**Comment by humpedli** [comment]
I just ordered 8 piece of Sandisk SD (16 GB) card for my 8 cameras. Sometimes I experience the same issue, but only on the same camera and not always, other SD cards / cameras are working well. Anyway it's an interesting issue.

**Comment by ravensteijn** [comment]
I got the same issue. It helped me connecting the sd card back to my computer. i then got a message that the disk needs repair. When i hit repair disk it was solved. maybe this helps?

**Comment by pascal1n** [comment]
same issue here ! 
 a special linux configuration is nedded ?? (like no log on SD or something like that ?
Thanks for help

**Comment by Gamer106** [comment]
Same issue for me. I use a smart-switch to turn the camera off when I’m home and on when I leave. I can’t remove the SD card every time this happens due to the install locations, so it’s a pain in the neck to resolve by having windows scan/fix the disk.

`[   20.999410] FAT-fs (mmcblk0p1): error, clusters badly computed (12 != 11)`
`[   21.006556] FAT-fs (mmcblk0p1): Filesystem has been set read-only`

I guess it’s writing to the disk constantly and pulling power is a no-no.

**Comment by jmtatsch** [comment]
Why not just toggling motion detection via mqtt?

**Comment by Gamer106** [comment]
I may just leave them powered on now that they’re local only. I was told the cameras on factory firmware sometimes remain “on” while you tell them to turn off so I used a switch.

**Comment by jmtatsch** [comment]
That is very true. I don't trust (especially chinese) cloud services at all.

**Comment by jvence** [comment]
Any help on manually solving this issue using Mac OS? Do we use the Disk Utility to repair permissions?

**Comment by lenr9** [comment]
mount -o remount,rw /system/sdcard is working for me.

**Comment by jbogatay** [comment]
Happening to me as well.   In prior versions dosfsck would fix things up.   Since upgrading to latest git version (2019-01-05),   dosfsck is broken.   It either segfaults or invalid argument and craps out.

Force remounting RW allows changes for now.

**Comment by tsvi** [comment]
To all those with this problem.
Could you please check if you run:

```
dosfsck -a /dev/mmcblk0p1
mount -o remount,rw /system/sdcard
/system/sdcard/autoupdate.sh
```

If the problem stops occuring?

**Comment by hajoland** [comment]
Hi tsvi,
thanks for your post. It seems to be the right solution. 
I get the following replay:

_[root@cam-2:]# dosfsck -a /dev/mmcblk0p1
CP850//TRANSLIT: Invalid argument
CP850: Invalid argument
fsck.fat 4.1+git (2017-01-24)
0x41: Dirty bit is set. Fs was not properly unmounted and some data may be corrupt.
 Automatically removing dirty bit.
/log/v4l2rtspserver-master.log
  File size is 145714259 bytes, cluster chain length is > 145719296 bytes.
  Truncating file to 145714259 bytes.
Free cluster summary wrong (1887712 vs. really 1886121)
  Auto-correcting.

*** Filesystem was changed ***
Writing changes.
/dev/mmcblk0p1: 250 files, 11382/1897503 clusters
[root@cam-2:]# mount -o remount,rw /system/sdcard
[root@cam-2:]# /system/sdcard/autoupdate.sh
No files to update._


The message about read-only does not apear again.
Thangs

**Comment by lenr9** [comment]
Solved the problem for me also.  Thanks!

**Comment by SamHead** [comment]
Can this solution be incorporated in normal power on bootup?
A file system check followed by a conditional repair is desired in this type of system

**Comment by misanthrophy** [comment]
> To all those with this problem.
> Could you please check if you stop the RTSP server and then run:
> 
> ```
> dosfsck -a /dev/mmcblk0p1
> mount -o remount,rw /system/sdcard
> /system/sdcard/autoupdate.sh
> ```
> If the problem stops occuring?

How do I run these commands from terminal on my iPad/MacBook Pro?

**Comment by camerling** [comment]
Hi,
@misanthrophy 
You need a ssh client terminal 
There is one in MacOs but you can download PuTTy 
Default credentials should be user:root, psw:ismart12
Have a good day.

**Comment by hyteoo** [comment]
I also have this issue more often than not.
This is a robustness feature that should be ran at boot time.

@EliasKotlyar Shouldn't this be integrated into the run script?
Do you see any issues in that?

**Comment by pillemats** [comment]
Hey guys 

I have trouble with my 1S and homebridge

I updatet to the newest fw and bootloader but the cam will freeze after few seconds in Homekit in live Mode

I Tryed this 

dosfsck -a /dev/mmcblk0p1
mount -o remount,rw /system/sdcard
/system/sdcard/autoupdate.sh

But Same as before and i dont know why!
 

Please help

**Comment by mmmmlab** [comment]
I'm having same error, too...
I control my camera via Sonoff and every time I switch it off (without a clean shutdown...) I found the filesystem corrupted (clearly!).

So very simply, I've added at the very beginning of run.sh the following:
/system/sdcard/bin/dosfsck -a /dev/mmcblk0p1 >> $LOGPATH

**Comment by mr2c12** [comment]
@mmmmlab it may be not elegant but works.

In my setup I have two dafang with a very similar configuration. One camera is affected by this problem, the other one seems not affected.
Maybe it's related to its sdcard?

**Comment by jlg89** [comment]
Save the following script to /system/sdcard/config/userscripts/startup/fixdisk.sh

`
#!/bin/sh
/system/sdcard/bin/dosfsck -a /dev/mmcblk0p1
/bin/mount -o remount,rw /system/sdcard
/system/sdcard/autoupdate.sh
`

If you don't want the firmware automatically updated to the latest release, leave out the last line.

**Comment by int2018** [comment]
Hi all,
one of my Dafang cameras is in my moms house (another place) and from time to time she unplugs the camera and moves it into another room.
And yes, after power cycle the filesystem is read-only ( I am not sure if this happens every time but at least the problem exists).
I used another solution to "fix" this and hence I did not read this post before:

When the camera is up again after powercycle and the file system is read-only I use the "Reboot" option from the web GUI and usually after the reboot everything is back to normal.

This is a more manual  solution to the problem but it seems to work too ...

Have fun and stay healthy!

**Comment by devnull404-pi** [comment]
Once I had this problem with a Dafang with motion detection activated and capturing snapshots in local storage (I didn't notice I ever activated that option). I was missing that I had only 512MB, and the read only flag in notifications appeared because the storage was already full. Yet, after deleting all media, the error remained. I just had to delete all from de SD card and copy the modified firmware, easy as c/p. Not need to reflash.
