### ISSUE TITLE
Xiaomi DaFang HomeKit Edit config.json 

### ISSUE THREAD

**Issue by 1043717432** [EliasKotlyar/Xiaomi-Dafang-Hacks#884]
{
	"bridge": {
		"name": "Homebridge_dafang",
		"username": "CC:22:32:E1:D2:AE",
		"port": 51824,
		"pin": "341-61-919"
	},
	"platforms": [{
			"platform": "Dafang",
			"mqtt": {
				"hostBroker": false,
				"port": 1883,
				"host": "192.168.120.2",
				"debug": true
			},
			"cameras": [{
				"cameraName": "My Dafang",
				"cameraRTSPStreamUrl": "rtsp://192.168.120.85:8554/unicast",
				"disableStream": false,
				"folder": "/home/dafang/",
				"segmentLength": 60,
				"maxDirSize": 2048,
				"checkStorageSizeInterval": 300,
				"accessories": [{
						"name": "aw",
						"type": "motionSensor",
						"threshold": 300000
					},
					{
						"name": "e",
						"type": "autoMotionTrackingSwitch"
					},
					{
						"name": "c",
						"type": "nightVisionSensor",
						"threshold": 0
					},
					{
						"name": "a",
						"type": "nightVisionSwitch"
					},
					{
						"name": "l",
						"type": "autoNightVisionSwitch"
					},
					{
						"name": "Horizontal Left",
						"type": "moveCamera",
						"axis": "horizontal",
						"direction": "left"
					},
					{
						"name": "Horizontal Right",
						"type": "moveCamera",
						"axis": "horizontal",
						"direction": "right"
					},
					{
						"name": "Vertical Up",
						"type": "moveCamera",
						"axis": "vertical",
						"direction": "up"
					},
					{
						"name": "Vertical Down",
						"type": "moveCamera",
						"axis": "vertical",
						"direction": "down"
					},
					{
						"name": "Record Video",
						"type": "recordVideo"
					},
					{
						"name": "Record Audio",
						"type": "recordAudio"
					},
					{
						"name": "Capture Image",
						"type": "captureImage"
					},
					{
						"name": "RPi Storage Sensor",
						"type": "storageSensor"
					},
					{
						"name": "Clear Storage Switch",
						"type": "clearStorage"
					},
					{
						"name": "Reset Streaming",
						"type": "resetFFMPEG"
					},
					{
						"name": "Camera Brightness",
						"type": "brightness"
					}
				]
			}]
		},
		{
			"platform": "Camera-ffmpeg",
			"cameras": [{
				"name": "Camera_abc",
				"videoConfig": {
					"source": "-rtsp_transport tcp -re -i rtsp://root:isdd2sd12@192.168.120.85:8554/unicast",
					"maxStreams": 5,
					"maxWidth": 1280,
					"maxHeight": 720,
					"maxFPS": 25,
					"vcodec": "h264_omx",
					"debug": true
				}
			}]
		}
	]
}
These are my configuration files.

Dafang homebridge runs on docker.

Home /home/dafang has created folders and permissions. But there are still errors.

[Dafang] Checking Recordings Folder Size : /home/dafang/

[1/14/2019, 3:53:54 AM] [Dafang] Error Occured

[1/14/2019, 3:53:54 AM] [Dafang] { [Error: ENOENT: no such file or directory, lstat '/home/dafang']
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: '/home/dafang' }

**Comment by jmtatsch** [comment]
Seems like  /home/dafang isn't there or isn't accessible. Try to find the guy who contributedHomeKit support.
