### ISSUE TITLE
Lighttp question, file path mod_alias

### ISSUE THREAD

**Issue by int2018** [EliasKotlyar/Xiaomi-Dafang-Hacks#885]
Hallo 

I want to access an additional folder e.g. "/system/sdcard/motion" via the lighttp webserver on my Dafang besides the standard webserver rootpath. My SD card is formatted under windows and I learned from here that it is not possible to have symbolic links with such format. 
So I thought maybe I can use the lighttp feature "alias.url" in the config file. In order to do this the module "mod_alias" seems required. 
https://redmine.lighttpd.net/projects/lighttpd/wiki/Docs_ModAlias

Unfortunately when I add that module and reboot the camrea the webserver doesn't start anymore. Am I missing something?

So my question is: How can I access a special path "outside" the webserver root path?
Reformat the SD card and use symbolic links?
Or any easier solution?

Thanks for a hint...

**Comment by lenisko** [comment]
bump
