### ISSUE TITLE
Cannot view 720p with CFW after flashing u-boot open source bootloader

### ISSUE THREAD

**Issue by sbajek** [EliasKotlyar/Xiaomi-Dafang-Hacks#886]
Camera: Xiaofang 1S 64MB
Commit:  806e500

I'm unable to view 720p rtsp stream with CFW after flashing open source u-boot bootloader.

Steps I did:
1. Installed CFW-Binary on brand new Xiaofang S1
2. Installed CFW-Firmware, camera boot just fine
3. I did some tests, 720p worked fine with VLC on desktop, but only 1 to 5 tries with quite powerful smartphone and tablet (streaming not even started), so I decided to flash open source bootloader to try ext3 version as well
4. I flashed xiaofang1s_64mb_v2.bin and used rootfs repo (btw: I think instructions needs to be updated with uEnv and rcS steps)
5. Camera started fine, video was not working, discovered that issue was reported already [https://github.com/Dafang-Hacks/rootfs/issues/11](url)
6. I restored fat32 version from step 2
7. Video stream doesn't work, works when I reduce to 360p

```
v4l2rtspserver-master.log:
2019-01-14 21:48:31.457 (   3.375s) [main thread     ]         ImpEncoder.cpp:1278     0| Set initial bitrate (from sharedmem) to 1000
i264e[error]: [func:i264e_threadpool_init,line:223]create pthread[0] failed
i264e[error]: [func:i264e_init,line:78]threadpool init failed
2019-01-14 21:48:31.470 (   3.389s) [main thread     ]         ImpEncoder.cpp:1357   ERR| IMP_Encoder_CreateChn(0) error:-1

dmesg:
[  279.064144] jxf23 stream on
[  279.155948] ###### image_tuning_v4l2_open 4219 #######
[  279.190698] &&& chan1  scaler.max_width = 1920 max_height = 1080  min_width = 128 min_height = 128 &&&
[  279.228393] do_page_fault() #2: sending SIGSEGV to v4l2rtspserver- for invalid read access from
[  279.228393] 00090f80 (epc == 76f45f74, ra == 76cb3d8c)
[  279.246095] jxf23 stream off
[  279.253677] do not support ctrl->cmd ====0

[root@Xiaofang:log]# cat /proc/cmdline
console=ttyS1,115200n8 mem=32M@0x0 ispmem=8M@0x2000000 rmem=24M@0x2800000 init=/linuxrc rootfstype=squashfs root=/dev/mtdblock2 rw mtdparts=jz_sfc:256k(boot),2048k(kernel),3392k(root),640k(driver),4736k(appfs),2048k(backupk),640k(backupd),2048k(backupa),256k(config),256k(para),-(flag)
[root@Xiaofang:log]# cat /proc/meminfo 
MemTotal:          26496 kB
MemFree:            1292 kB
Buffers:              44 kB
Cached:             7888 kB
```
I'm not sure why I have less than 26MB of memory, shouldn't it be 32MB? So there is a chance v4l2 runs out of memory.

**Comment by sbajek** [comment]
Answering my question: of course it shouldn't because it excludes kernel and other system structures, which can be easily checked by running:

`dmesg | grep Memory`

However it's still not clear why I cannot get 720p under CFW, so instead I used @fabi280's [rootfs](https://github.com/fabi280/rootfs) with updated driver dependencies and it works just fine. Hopefully it will be merged soon to the main repo.

**Comment by unrelentingtech** [comment]
zram (`config/swap.conf`) really helps with running out of memory
