### ISSUE TITLE
Someone tried full "stand-alone" "offline" mode?

### ISSUE THREAD

**Issue by int2018** [EliasKotlyar/Xiaomi-Dafang-Hacks#888]
Hi all,

I am thinking to use the Dafang camera with the hack in a stand-alone-offline-mode for wildlife monitoring. Anybody tried this before?

Questions:
- what would be a battery-friendly minimum setup for motion detection mode?
- anybody checked the max. size of a sdcard which could be used?

Anything else?

**Comment by saipsa** [comment]
> anybody checked the max. size of a sdcard which could be used?

I have tried 64gb card, and it worked.

**Comment by jmtatsch** [comment]
I would get a decent wildlife cam if I were you. They have low power pir sensor that wakes the camera only In case of warm movements.
