### ISSUE TITLE
AAC audio

### ISSUE THREAD

**Issue by hyteoo** [EliasKotlyar/Xiaomi-Dafang-Hacks#890]
Would it be possible to also add aac as audio format?
Some VMS systems only support that.
Ex.: I use orchid core VMS

**Comment by bromptonista** [comment]
+1 to this request - I realise editing and building v4l2rtspserver from source is required to do this (the latest version supports aac however the one included here is modified), but I have no idea how to go about it myself.

**Comment by fx-k** [comment]
hi all, i met this issue too, my nvr only support aac audio stream...
Any update to solve it :-) ? thanks

**Comment by jmtatsch** [comment]
As a last resort you can recode using go2rtc
