### ISSUE TITLE
mqtt-control not working (subtopics, commands)

### ISSUE THREAD

**Issue by prankousky** [EliasKotlyar/Xiaomi-Dafang-Hacks#894]
Hi,

I am using the current version of Xiaomi-Dafang-Hacks on a Xiaomi .
Bootloader Version `U-Boot 2013.07 (Dec 21 2017 - 18:44:33)`
CMDline `console=ttyS1,115200n8 mem=104M@0x0 ispmem=8M@0x6800000 rmem=16M@0x7000000 init=/linuxrc rootfstype=squashfs root=/dev/mtdblock2 rw mtdparts=jz_sfc:256k(boot),2048k(kernel),3392k(root),640k(driver),4736k(appfs),2048k(backupk),640k(backupd),2048k(backupa),256k(config),256k(para),-(flag)`

I edited the `mqtt.conf.dist` and saved it as `mqtt.conf`. Both mqtt-control and mqtt-status can be started and get a PID; they threw `NOK` error flag at first because until I changed `mqtt.local` as server to its actual ip address.

In mqtt.conf, I set 

```
#Define a location
LOCATION="home/dafang"
#Define a device name
DEVICE_NAME="dafang-livingroom"
```

At first I assumed that the extra dash in LOCATION might cause the problem, but I can subscribe to  `home/dafang/dafang-livingroom/#` and will receive all status updates.

I did some google search but could not find any information on how to actually control the camera via mqtt. Some information available (not on this github, some home automation softwares wiki) listed commands like `motor_left`,`motor_right`,`motor_up`, and `motor_down` which should be submitted via (in this case) `home/dafang/dafang-livingroom/set`, **set** being the topic to submit those commands to. I tried them all, but none of them worked. Another external wiki suggested to use `/control` instead of `/set`, which also did not work.

What commands are actually available and how (exact topic) can I control the camera with them? I assume set and control are outdated, or the commands I've found are incorrect - or both.

Sorry if I missed this in the wiki, but I have looked multiple times. There seems to be nothing on this wiki on how to control the camera via mqtt. Especially arming/disarming motion detection and/or enabling/disabling telegram notifications via mqtt would be very helpful. 

Tell us what you did to remedy/debug the issue yourself and what you think causes the issue.

There are only `isp_tuning_func` and three lighttpd logfiles in `/var/log`, but nothing mqtt related. Cannot find anything relevant in the webGUI logs, either. Both mqtt services are running.

Again, sorry if this has already been solved, but I could not find anything relevant in the wiki. Also, as I mentioned before, it did not work first because of incorrect mqtt-host in my conf file, but now I have fixed it (and rebooted the device), *and* mqtt-status is now publishing stats, so all I can think of is that either the mqtt topic and/or payloads are incorrect. 

Thanks in advance for your help :+1:

**Comment by jmtatsch** [comment]
Look at https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/ec816859749e9ff49d6500f97fa8f3187145d535/firmware_mod/scripts/mqtt-control.sh for inspiration

**Comment by prankousky** [comment]
Sorry... I had figured that out in the meantime (before @jmtatsch replied to this) and forgot to close it. That solution works fine :)
