### ISSUE TITLE
Dafang with latest hacks won't trigger "alarms"

### ISSUE THREAD

**Issue by fangme** [EliasKotlyar/Xiaomi-Dafang-Hacks#897]
Took a couple tries - but have hacked my Dafang PTZ camera.  RTSP works, etc.

However, I can't seem to get it to "trigger alarms" or recording during detected movement.  I can turn movement tracking on - that works fine.  But nothing happens.

I have the homebridge setup complete, and connected to the camera.  Couple items not working there, but for the most part - seems to work.

I'd expect to see a message come back, or something from the camera - but don't see anything when movement occurs.

**Comment by fangme** [comment]
Ok - may have had an issue on the camera with the mqtt.conf.

Made a slight correction, and homebridge is now sending messages to my iPhone.  Still not sure I've got this quite correct - I'll post what I think are the relevant portions of my ~.homebridge/config.json and the mqtt.conf - please comment appropriately.

-----  ~/.homebridge/config.json -----------
{
    "bridge": {
        "name": "Homebridge",
        "username": "<hex values>",
        "port": 51826,
        "pin": "<pin>"
    },
    "mqtt": {
                "hostBroker": true,
                "debug": true,
                "mongoUrl": "mongodb://localhost:27017/mqtt"
            },

    "description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",

    "platforms": [
        {
            "platform": "Dafang",
            "mqtt": {
                "port": 1883,
                "host": "localhost"
            },
            "cameras": [{
                "cameraName": "DAFANG1",
                "cameraRTSPStreamUrl": "rtsp://192.168.1.90:8554/unicast",
                "mqttTopic": "myhome/dafang/#",
                "disableStream": false,
                "folder": "/root/Recordings/",
                "segmentLength": 60,
                "maxDirSize": 2048,
                "checkStorageSizeInterval": 300,
      "videoConfig": {
        "source": "-re -i rtsp://192.168.1.90:8554/unicast",
        "stillImageSource": "-i http://faster_still_image_grab_url/this_is_optional.jpg",
        "maxStreams": 1,
        "maxWidth": 1280,
        "maxHeight": 720,
        "maxFPS": 30
      },
<etc>,<etc>
---------   end of file -----------

---------- mqtt.conf -------------
############################################################
# edit this file and move it to /system/sdcard/config/mqtt.conf #
############################################################

export LD_LIBRARY_PATH='/thirdlib:/system/lib:/system/sdcard/lib'

# Options for mosquitto_sub & mosquitto_pub
USER=mqtt-user
PASS=mqtt-password
HOST=192.168.1.70
PORT=1883

# Define a location
LOCATION="myhome"

# Define device name
DEVICE_NAME="dafang1"

# Define the base topic used by the camera
# send a message to myhome/dafang/set with the payload help for help.
# Results will be placed in myhome/dafang/${command} or topic/dafang/error - so
TOPIC="myhome/dafang"
                                                              
# Define an autodiscovery prefix, if autodiscovery is desired:
# AUTODISCOVERY_PREFIX="homeassistant"                           
                                                                                
# Define additional options for Mosquitto here.                                 
# For example --cafile /system/sdcard/config/DST_Root_CA_X3.pem --tls-version tl
# or use a special id to connect to brokers like azure
MOSQUITTOOPTS=""                                              
                                                              
# Add options for mosquitto_pub like -r for retaining messages
MOSQUITTOPUBOPTS=""                       
                                          
# Send a mqtt statusupdate every n seconds
STATUSINTERVAL=30   
---------  end of file ------------

As you can see - the topic between config.json and mqtt.conf is slightly different - config.json has a trailing "/#" - but I felt that was essentially a variable that gets replaced in homebridge (?) .

**Comment by enz1ey** [comment]
I’m currently having an issue with notifications as well. So you’re saying you needed to add the “/#” in the config.json to get them to work?

**Comment by fangme** [comment]
Sorry for the very delayed reply - I've been very busy with family matters.

No - slight misspelling.  I'm still not sure about the trailing /#...
