### ISSUE TITLE
Reflash Xiaofang using CH431 

### ISSUE THREAD

**Issue by Papadoma** [EliasKotlyar/Xiaomi-Dafang-Hacks#900]
I have bricked my xiaofang camera by trying to flash the uboot of EliasKotlyar. I tried the serial access method, but didn't work.
My only choice is to remove the flash memory, hook it up to a CH431 and program it. The flash memory is a GD25Q127.

I have the CH431 and the programmer working. As a binary file I used the one provided in the description of this video https://www.youtube.com/watch?v=DgIP_ey_138
However, the CH431A programmer fails to verify the contents. It says they do not match, yet it looks like it detects and erases the flash successfully. There is no option however for a GD25Q127 chip, so I selected the GD25Q128 instead. Not sure if that is the issue or if the binary file I used cannot be used in such a way.

Any ideas?

**Comment by hansaya** [comment]
you need to put only the boot loader into the chip. You would extract that from the .bin file
https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/hacks/unbrick.md

**Comment by Papadoma** [comment]
Ok I see. Have in mind though that it is the xiaofang one, the small cube. Its not even the Xiaofang 1S, it is the 1st version xiaofang, with the ARM chip.

**Comment by Papadoma** [comment]
> you need to put only the boot loader into the chip. You would extract that from the .bin file
> https://github.com/Dafang-Hacks/spiflasher

Nope, didn't work
Plus, it is NOT the xiaofang S1, it is the Xiaomi Xiaofang, they are different. That's how it broke in the first place.
Nevertheless, I tried flashing the whole rom found here https://github.com/samtap/fang-hacks/wiki/HowTo:-Flash-original-Xiaomi-firmware-from-sdcard-(factory-reset) but nothing happened. Solid yellow light. 

running out of ideas
