### ISSUE TITLE
Ability to run CFW without sdcard

### ISSUE THREAD

**Issue by iashwinprasada** [EliasKotlyar/Xiaomi-Dafang-Hacks#906]
### Description

Can the CFW have a light version that can be flashed on to the camera storage itself and not rely on the sd card to boot? This will be useful when trying to use a lot of devices.

**Comment by imacks** [comment]
i am also relunctant to flash uboot into nand due to the brief documentation. is the current firmware mod working with uboot? how do we replace the firmware on nand?

**Comment by jmtatsch** [comment]
Yes you can boot the current cfw via uboot. Flashing a bootloader is always a little bit dangerous like a heart surgery :)

Once you have uboot running and booted from sd you should be able to flash our experimental rootfs into Nand the same way you would do on sd. But Dont do that unless you know what you are doing.

**Comment by imacks** [comment]
can you elaborate on how to flash the experimental rootfs to nand? i did not find anything about that

**Comment by danergo** [comment]
One more thing needs to be cleared though:
If I want to put everything to NAND shall I use the mtd2 (root) or mtd4 (appfs) for this purpose?
