### ISSUE TITLE
Size of "pictures"

### ISSUE THREAD

**Issue by Pharizna** [EliasKotlyar/Xiaomi-Dafang-Hacks#91]
I'm trying to have "small" pictures but it seems  they are always 1280*720.

I tried with this cgi-bin/currentpic.cgi?width=640&height=360 and (at least in Chrome, IE) the size is 1280*720 pixels, etc

**Comment by EliasKotlyar** [comment]
Hello Pharizna,

I have removed the scaling option for enabling both JPG and H264 to run. Just start the H264 with the right parameters to have a smaller Picture.

**Comment by bosscrew** [comment]
I got a problem running rtsp stream with -f or -fformat option:
[FATAL] /home/eko/Dokumente/projects/Xiaomi-Dafang-Software/v4l2rtspserver-master/src/main.cpp:638

**Comment by DrumSergio** [comment]
How can it be solved? I have a problem of bandwidth, 6Mbps is too much. I would like to reduce it to 200Kbps or so.

**Comment by shinebar1001** [comment]
you can change the bitrate like this:

> /system/sdcard/bin/setconf -k b -v 500

for 500kbps

Alternatively you can change the the resolution for v4lrtspserver like this:
`/system/sdcard/bin/v4l2rtspserver-master -W 640 -H 360`
Depending on which way you start the rtsp Server you can add the paramters in run.sh or in /system/sdcard/controlscripts/rtsp-h264 or /system/sdcard/controlscripts/rtsp-mjpeg
