### ISSUE TITLE
Sannce I21AG - Stuck when flash_eraseall

### ISSUE THREAD

**Issue by MathiasVandePol** [EliasKotlyar/Xiaomi-Dafang-Hacks#921]
Sannce I21AG

### Description

Connecting via telnet is successful but when running flash_eraseall I either get:

```
flash_eraseall: /dev/mtd0: MEMERASE: Operation not permitted
```

or it is stuck when executing the command.

![stuck](https://user-images.githubusercontent.com/606681/52184400-fe26f880-2812-11e9-8294-b51559f9e278.png)

I've tried rebooting the camera a few times but that does not help.
Anyone got an idea?

Thanks!

**Comment by wschleifer** [comment]
Hello,

I have the same problem...

Anyone an idea?

Thanks,
W. Schleifer
ps

**Comment by wschleifer** [comment]
Hello,

is it probably a readonly of the mtd0?

What can I do to solve this?
I can support with the dump binary files of the mtd's if its neccessary.

Thanks,
W. Schleifer

**Comment by wschleifer** [comment]
Hello,

it is probably a readonly of the mtd0?

What can I do to solve this?
I can support with the dump binary files of the mtd's if it is neccessary.

Thanks,
W. Schleifer

**Comment by freman** [comment]
Same issue here, if you skip that and try to dd it gets just as stuck

**Comment by iddq** [comment]
So, did you manage to overwrite the boot after all? I would have tried dd with /dev/mtdblock0
