### ISSUE TITLE
Change username

### ISSUE THREAD

**Issue by silentbil** [EliasKotlyar/Xiaomi-Dafang-Hacks#935]
Hi ,  I managed to changed the password (via admnistration page) ,
but i couldnt changed the "root" to be "myUser".
I tried to change it in the lighttp , but it doesnt work (cant login with the user i changed).
whats the trick?

thanks!

**Comment by jmtatsch** [comment]
Changing the user name is not really recommended. Look at https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/2e018ee0dd09fec2d94dc4a0b3d8d669ea195695/firmware_mod/scripts/common_functions.sh#L253 how to still do it.
