### ISSUE TITLE
Changing password does not change SSH password

### ISSUE THREAD

**Issue by ThomasBlt** [EliasKotlyar/Xiaomi-Dafang-Hacks#938]
### Description

After changing the root password in the web app, the root password for SSH is not changed ==> security risk.
(commit id 2e018ee)

### What did you do to debug the issue

connect with the stock password ismart12 and changed it myself using `passwd`

**Comment by jmtatsch** [comment]
It says "Set HTTP Password" in the web ui. Gladly accept a pull request for also invoking passwd.

**Comment by x23piracy** [comment]
Hi,

no these are two different services! If you hack a camera you should know what you are doing. So the pitty is you need to do something twice and this is good do not tie the http and the ssh passwd being the same, that's bullshit.

I would not suggest to merge something like that into the project.


Regards X23

**Comment by lgigil** [comment]
> ### Description
> After changing the root password in the web app, the root password for SSH is not changed ==> security risk.
> (commit id [2e018ee](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/commit/2e018ee0dd09fec2d94dc4a0b3d8d669ea195695))
> 
> ### What did you do to debug the issue
> connect with the stock password ismart12 and changed it myself using `passwd`

Hi, how did you change the web app password?
