### ISSUE TITLE
Motion Detection -  MQTT Motion Detection "ON" calls function with static motion sensitivity of "4" instead of what is in the motion config or last value

### ISSUE THREAD

**Issue by vivekmreddy** [EliasKotlyar/Xiaomi-Dafang-Hacks#940]
Hi all,

This is my first post on github (long time lurker), and I noticed an issue that I've dealt with in a poor manner on my own setup (just changed the value from 4 to 1) but I'm not confident enough to add a change to the code where it dynamically reads the value from the configuration.

Long story short, I use MQTT with Home Assistant to enable/disable motion detection on my camera. After enabling again, it always reverted back to the highest sensitivity which threw all sorts of false positives. It looks like that mqtt-control.sh is calling the motion_detection function in common_functions.sh. The line in the function, that pertains to enabling/disabling motion:

`/system/sdcard/bin/setconf -k m -v 4`

located in: Xiaomi-Dafang-Hacks/firmware_mod/scripts/common_functions.sh at line 305

I'm pretty confident it's possible to pull the value from the the motion.conf, but since I'm a bit new, and I didn't see anything out there on this issue so I figured I'd at least mention it so someone more capable than I, who could make the change quicker.

Please let me know if you have any more questions.

**Comment by jmtatsch** [comment]
Should work now. Please report back if not fixed.

**Comment by vivekmreddy** [comment]
Thanks for updating! But it seems the enable component doesn't work. I can disable the motion detection, but MQTT cannot re-enable it.

**Comment by vivekmreddy** [comment]
Just to confirm, I removed that line from my file, and it works as expected. Thank you!

I will read up on how to submit fixes for the next time. If there is any good documentation, besides the official, that is worth reading, I'm all ears. Thanks again!
