### ISSUE TITLE
Dafang CFW installation interrupted

### ISSUE THREAD

**Issue by Wind-Storm** [EliasKotlyar/Xiaomi-Dafang-Hacks#942]
Hello!

The owner of the camera interrupted the installation of the demo.bin file, so the camera now seems like bricked.
I thought, the bootloader erased or corrupted, so I desoldered the SPI flash and read its content. The u-boot seems ok, compared to the uboot-fullhd.bin
What I need to restore in this case?
UART connection would enough in this case, not need external reprogramming? I just ask, because I did the desoldering already.
Sorry, I'm not too experienced in the Dafang world.

**Comment by jmtatsch** [comment]
Consider trying our rootfs or openfang

**Comment by Wind-Storm** [comment]
Sorry, exactly what I need to do?
I want to restore the original firmware.

**Comment by jmtatsch** [comment]
If you have the open source bootloader you could boot from sdcard and write the nand from there. But I wouldn’t bother restoring the nand. Just keep running one of the rootfses.

**Comment by Wind-Storm** [comment]
I reprogrammed the flash from 000400000 to 00acffff with the "demo.bin" after I cut out the first 40 bytes.
Unfortunately not working. Whats wrong? No serial output, Is it possible the full brick?

**Comment by jmtatsch** [comment]
You said your boot loader is fine, then you should have some serial output i guess?
@EliasKotlyar maybe you can help with this one.

**Comment by Wind-Storm** [comment]
Fine, the only difference is this: "mem=104M@0x0 ispmem=8M@0x6800000 rmem=16M@0x7000000"
Here it is:
[read_uboot.zip](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/files/2872427/read_uboot.zip)

**Comment by Wind-Storm** [comment]
@jmtatsch How can I write to him?

**Comment by jmtatsch** [comment]
We already put him on notify, maybe he is just too busy to answer you now.
