### ISSUE TITLE
Xiaofang 1S hangs, not connecting to Wifi

### ISSUE THREAD

**Issue by kittenarmy** [EliasKotlyar/Xiaomi-Dafang-Hacks#943]
I have a newer version Xiaofang 1S with T20 processor which came with firmware 5.6.2.77 which I did not update. I flashed demo.bin (CFW Xiaomi XiaoFang T20), and now loading custom firmware from SD card but the camera hangs with blue LED on and I can only log in via serial (root/ismart12). There is no IP from router or https://dafang. 

I wondered if it is the bootloader issue like in #834 since serial shows `U-Boot 2013.07 (Jul 05 2018 - 17:59:02)` but it starts run.sh from SD card, then I see uphcpc:

Ingenic-uc1_1 login: [    4.939113] RTL871X: module init start
[    4.945483] RTL871X: rtl8189ftv v4.3.24.7_21113.20170208.nova.1.01
[    4.951996] RTL871X: build time: Nov 22 2017 16:25:23
[    4.957205] wlan power on
[    4.971377] RTL871X: module init ret=0
[    5.016717] mmc1: card claims to support voltages below the defined range. These will be ignored.
[    5.037413] mmc1: new SDIO card at address 0001
[    5.046707] RTL871X: ++++++++rtw_drv_init: vendor=0x024c device=0xf179 class=0x07
[    5.114703] RTL871X: HW EFUSE
[    5.117794] RTL871X: hal_com_config_channel_plan chplan:0x20
[    5.334330] RTL871X: rtw_regsty_chk_target_tx_power_valid return _FALSE for band:0, path:0, rs:0, t:-1
[    5.371273] RTL871X: rtw_ndev_init(wlan0) if1 mac_addr=78:11:dc:75:80:3f
udhcpc: started, v1.29.0.git
udhcpc: sending discover
udhcpc: sending discover
udhcpc: sending discover
udhcpc: no lease, forking to background
Terminated.

**Comment by jmtatsch** [comment]
Does your router pick up the mac address?
Maybe wpa_conf is misconfigured or your DHCP is down.
Or they changed the wifi chipset again so it is using an outdated driver for new hardware now.

**Comment by kittenarmy** [comment]
I've only had it successfully connect to my router with original firmware, same credentials. I've checked wpa_supplicant.conf, even using really basic version too. Not sure about DHCP; other devices can connect at same time I try powering the camera.

ctrl_interface=/var/run/wpa_supplicant
ctrl_interface_group=0
ap_scan=1

network={
	ssid="myssid"
	psk="mypassword"
  key_mgmt=WPA-PSK
}

**Comment by kittenarmy** [comment]
I tried it again with firmware commit 647b694 and it's connecting to router now. I can log in via browser at http://192.168.0.27 but not http://dafang and neither with https. RTSP is working, however in tinycam with default Defang setting.
