### ISSUE TITLE
Increase motor steps 

### ISSUE THREAD

**Issue by SSkull995** [EliasKotlyar/Xiaomi-Dafang-Hacks#944]
Hi all!
I have an issue I hope you can try to solve with me. I changed the stepper motor of my Dafang with a new one, but I am afraid that its steps are a bit shorter that the original one. What happens is that, even after calibration, the camera never turns fully 360 degrees, it runs out of steps just at 1/3 of the ring. I would like to know if there is the possibility to increase the steps in the horizontal motor, in order to make it fully move. 
Do you know if it is possible? Thanks

**Comment by SSkull995** [comment]
I just realize that the changed motor moves as the original one, but it never reaches the endstop, it just moves randomly. When I perform 2 motor calibrations, the camera just stops in a Different position every time.

**Comment by MasterPIC** [comment]
If your Dafang is equipped with endstops you can try an older motor driver/bin.
Please refer to #937

**Comment by SSkull995** [comment]
Hi! Thanks! I read the issue you referred to, but I don’t understand how to change the motor.bin file, mainly which is its location in my microSD and when I can find a older version on github. Thanks for the help!

**Comment by MasterPIC** [comment]
Hi @SSkull995 ,

from the page related to pull request #937 you can click on "files changed" to get the (4) files to use in place of current ones.
You can also refer to my fork ( https://github.com/MasterPIC/Xiaomi-Dafang-Hacks ) and copy firmware_mod content to the SD (as you already made with the sources from @EliasKotlyar ).
Anyway just 4 files are to be changed/overwritten...

**Comment by SSkull995** [comment]
Ah, perfect! I actually managed to change the last two files, manually. The first two are not displayed, the is why I couldn't understand what to change. Thanks @MasterPIC !
