### ISSUE TITLE
How do i disable Blue LEd and Motion Sensor on boot?

### ISSUE THREAD

**Issue by danmed** [EliasKotlyar/Xiaomi-Dafang-Hacks#945]
I need neither the Blue Light or the Motion Detection to be active after the system is rebooted.. How can i acheive this?

(Xiaofang 1S)

**Comment by saipsa** [comment]
out the code in startup user-script folder

**Comment by hubmon** [comment]
What does this mean in everyday language?
Some of us are not coders/scripters

**Comment by danmed** [comment]
> put the code in startup user-script folder

What code?

**Comment by danmed** [comment]
So.. the cmdline commands are

blue_led off
motion_detection off

but putting them in a script file in /system/sdcard/config/userscripts/startup does not execute them.. is there a format to the script file?

**Comment by danmed** [comment]
Right.. Figured it out : 

Update to the latest version.

create a file called off.sh in /system/sdcard/config/userscripts/startup

put in the following : 

```
#!/bin/sh

. /system/sdcard/scripts/common_functions.sh

blue_led off
motion_detection off
```

**Comment by stucki** [comment]
@danmed Works, many thanks!
@jmtatsch Would be great if this could be changed via web interface. Can you reopen the issue for that, or should I create a new one instead?

**Comment by jmtatsch** [comment]
You can create a pull request for a stealth mode if you want.

**Comment by andrepetinga** [comment]
> Right.. Figured it out :
> 
> Update to the latest version.
> 
> create a file called off.sh in /system/sdcard/config/userscripts/startup
> 
> put in the following :
> 
> ```
> #!/bin/sh
> 
> . /system/sdcard/scripts/common_functions.sh
> 
> blue_led off
> motion_detection off
> ```

Hello.
I tried this (just removed "motion_detection off") and blue led is still on, at startup :( 
I have the "off.sh" at config/userscripts/startup
and the file is like this:

#!/bin/sh

. /system/sdcard/scripts/common_functions.sh

blue_led off

Looking at the code I think that first common_functions.sh file is called and then "blue_led off" is called.
But is it just like this??
