### ISSUE TITLE
NTP Server can't setup

### ISSUE THREAD

**Issue by ddima75** [EliasKotlyar/Xiaomi-Dafang-Hacks#949]
Hi!
After update, now i have version: 2019-02-21T13:07:30Z can't setup an NTP Server.

BR,
ddima75

**Comment by nickrout** [comment]
IIRC you should set the timezone under the System|System menu, pretty sure it used to only include timezones like +1100 etc, not it accepts proper timezones like Pacific/Auckland.

**Comment by ddima75** [comment]
All Ok, thank you!
