### ISSUE TITLE
Feature Request - Send Matrix message

### ISSUE THREAD

**Issue by xMateMCPE** [EliasKotlyar/Xiaomi-Dafang-Hacks#950]
Matrix is a decentralized messaging platform. Could we get an option to automatically send photos to Matrix?

The Swagger docs is at https://matrix.org/docs/api/client-server/

**Comment by jmtatsch** [comment]
Would be interested in that as well but couldnt find an api which would work just with a simple http post request. Did you find one?

**Comment by xMateMCPE** [comment]
You can get the token with `curl -XPOST -d '{"type":"m.login.password", "user":"example", "password":"password"}' "https://HOMESERVER/_matrix/client/r0/login"` and then use the token to send a message using `curl -XPOST -d '{"msgtype":"m.text", "body":"message"}' "https://HOMESERVER/_matrix/client/r0/rooms/ROOM_ID/send/m.room.message?access_token=YOUR_ACCESS_TOKEN"`


There is more information about the HTTP api in https://matrix.org/docs/guides/client-server.html

**Comment by jmtatsch** [comment]
61ca503757f9cf6d8319bc0419cdf3353835c859

**Comment by jmtatsch** [comment]
I should have been more specific. I couldn't find a way to send a picture without a web server hosting that picture and serving it to the matrix homeserver.

**Comment by xMateMCPE** [comment]
Thanks for the help! Gonna try to make the image work without needing to host it.
