### ISSUE TITLE
Home Assistant warning

### ISSUE THREAD

**Issue by dgomes** [EliasKotlyar/Xiaomi-Dafang-Hacks#952]
https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/d0af19a495a0af295f296528f1fa521c28ebfeae/firmware_mod/scripts/mqtt-autodiscovery.sh#L25

Camera component has no "device" attribute, as of HA 0.88 you will get a Warning that will become an Error in the next version.

**Comment by jmtatsch** [comment]
So should we just remove the device part?

**Comment by dgomes** [comment]
For now, yes! 

In near future it's likely that HA might add it, and then it can be added back.
