### ISSUE TITLE
I need full flash dump for Dafang!

### ISSUE THREAD

**Issue by Wind-Storm** [EliasKotlyar/Xiaomi-Dafang-Hacks#953]
Hello,
I have a mysterious brick, unfortunately no serial output.
Where can I download all the mtdblocks?
One 16MB file would be great from a working camera.
Thanks!

**Comment by fabi280** [comment]
Just take a look at the original firmware directories here, for example
https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/tree/master/firmware_original/dafang/5.6.2.106

**Comment by Wind-Storm** [comment]
Hello!
Thanks.
"appfs" is missing. What does this block contain?

**Comment by fabi280** [comment]
Sorry, just noticed it. The easiest solution would be to take another
firmware version, it's included at least in the 5.5.1.391. As far as I know
it's quite important, I think it contained a lot of binaries, even the
software that connects it to the Xiaomi cloud (miiio or something like
that)

Wind-Storm <notifications@github.com> schrieb am Mo., 25. Feb. 2019, 01:30:

**Comment by nimbus39** [comment]
i just need help how to dowgrade the dafang firmware from 5.5.1.419 to maybe 5.5.1.391. But there are so  many .bin files like appfs, backupa, backupd, config, driver, etc. So which one to choose from?

**Comment by fabi280** [comment]
You need like every image - combined into one package. Take a look into the hack/firmware/ folder, there are some scripts

**Comment by nimbus39** [comment]
Wow, i just check the scrip and instructions, it so complicated for me. I just wonder where i can request the file demo_5.5.1.391.bin. Demo_5.5 1.177.bin and demo_5.5.1.194 not really work for me (i flash them, but still buggy).

**Comment by fabi280** [comment]
I'll look into it and see if I can find some time to create it for you. But
don't expect it in the next few hours, probably in the late evening/night
(CET/UTC+1)

nimbus39 <notifications@github.com> schrieb am Mo., 4. März 2019, 18:14:

**Comment by nimbus39** [comment]
Wow, greatly appreciated fabi280.. Thanks..

**Comment by fabi280** [comment]
Here are the generated firmware files. I take NO responsibility for those files. The hash of demo_5.5.1.177.bin and 5.5.1.177.bin are different to each other. So they are not the same files
https://www.jottacloud.com/s/161032c43d4b0c4480bb40e546771e4fdf2

The tool which I used is packer.py - its also used to generate those hacked firmwares.

**Comment by nimbus39** [comment]
Ok. Thanks for the work, appreciated it. I will test it later and let all u know the result. Good job fabi280

**Comment by Bogdis** [comment]
can anyone pack the xiaonfang original firmware for me plz? I have tried myself but with no luck :(
