### ISSUE TITLE
NEOS Smartcam

### ISSUE THREAD

**Issue by michaelsage** [EliasKotlyar/Xiaomi-Dafang-Hacks#954]
Got the NEOS Smartcam which is a T20 device, it appears to be a complete clone of the 1S / Wyzecam. I have managed to load the BIN file (both the latest wyze one and the dafang). I have copied the hack across to the SD card and altered the wpa file. 

It appears to totally ignore the run.sh script. I haven't soldered a header on yet, but that is likely to be my next step. 

Any tips to try before this? I guess it could be using a different wifi chipset (realtek 8189ftv). It is definitely a T20 device as I have removed the case and it's printed on the board.

**Comment by jf19742016** [comment]
I followed the instructions for the Wyze V2.  When doing the setup with demo.bin however, it did give me the impression it wasn't working as it kept creating a folder and copying images across.  But saying that it did all work without the need for any soldering....  I used an older 512mb mini SD card, not sure it that helps or not.

**Comment by michaelsage** [comment]
That's interesting. The writing of the BIN file definitely works as my camera is now fluent in Chinese! I guess it might be an issue with my WPA supplicant file. I'll give it another go. Thanks

**Comment by michaelsage** [comment]
Awesome. I had flashed it with the wrong BIN file, I'd used the Xiaomi Xiaofang 1S rather than the Wyze V2. Thanks for pointing me in the right direction.

**Comment by jf19742016** [comment]
Great, to be honest I debated to do it for a number of days as I thought I may brick the camera.  I couldn't see anyone else trying it so gave it a go.  Happy I did as I wouldn't have bothered if i needed to solder etc.

**Comment by michaelsage** [comment]
I have asked NEOS for the original firmware too. If I get a response I'll message you.

**Comment by aqueiroz** [comment]
Any luck with getting the Neos original firmware... updated a couple of days ago with the latest version of xiaomi hacks wyze V2 firmware and the Neos didn't like it. Stream is very laggy even at low res. Tried to remove and and boot into original firmware, but the neos won't connect to the neos app. There must be something written to the memory ... so now I have a camera I cant use. Need to original firmware to attempt to fix it. Thanks

**Comment by michaelsage** [comment]
No luck. They basically said they won't ever offer it up. Which is a shame, as their latest firmware has left the camera constantly disconnecting and reconnecting to WiFi ??

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by aqueiroz** [comment]
Shame... well maybe someone in the forum can get a dump of the neos camera software??? Or best case dafang fixes issues with current firmware. Thanks for the reply 😎👍

**Comment by michaelsage** [comment]
My understanding (and this is from reading similar threads) is that the firmware dump would only be good for the camera it was dumped for. Which is a real shame.

I hope dafang gets sorted as it is a better firmware

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by aqueiroz** [comment]
Hmmm could be coz there's a serial number or mac address specific???? Shame... yeah dafang is great... just needs a cloud upload feature... like googledrive or something. But yeah they need to fix the laggy resource hungry stream.

**Comment by HectoSpark** [comment]
I'll take a look at dumping it anyway. I've got 3 of them coming on tuesday. I'll hook up the USB to TTL if I can find it.

**Comment by aqueiroz** [comment]
@HectoSpark hi any luck getting the firmware?

**Comment by aqueiroz** [comment]
any one manager to get the original Neos Firmware yet?

**Comment by aqueiroz** [comment]
managed to fix my camera :-) check my post!

https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/pull/964#issuecomment-515421690
