### ISSUE TITLE
RTSP H264 fails with Motion Detection

### ISSUE THREAD

**Issue by Wibias** [EliasKotlyar/Xiaomi-Dafang-Hacks#955]
Hey!

So when I have the RTSP H264 Server enabled I cant get to enable Motion Detection. But when I disable the RTSP H264 Server,then I can enable Motion Detection. But after enabling Motion Dection I cant start the RTSP H264 Server and I get a "NOK".

Can anyone help me with this? Its a big problem because I really need motion detection.

**Comment by saipsa** [comment]
The motion detection boundaries should have some gap from the edges of the view port.

**Comment by Wibias** [comment]
> The motion detection boundaries should have some gap from the edges of the view port.

Yup, that worked! Thanks a lot!
