### ISSUE TITLE
Xiaofang 1S no RTSP H264, only JPEG

### ISSUE THREAD

**Issue by kittenarmy** [EliasKotlyar/Xiaomi-Dafang-Hacks#958]
Using latest firmware commit 647b694. Xiaofang 1S with T20 processor.

RTSP is not working for me at all in tinycam or VLC. Only JPEG snapshot protocol with default Defang setting is working for me in tinycam, no audio. 

I have the default Defang settings. I tried disabling motion detection, and I'm not using MQTT at all. In serial it appears the rtsp server is started but I don't get anything in logs about status of RTSP stream. I've also tried stopping and restarting rtsp-h264 without rebooting the camera.

- sh: jxf22: unknown operand
- Starting Auto Night Detection
- Starting v4l2rtspserver-master
- /system/sdcard/run.sh: line 245: /system/sdcard/config/userscripts/startup/*: not found
- [   16.450591] name : i2c-gpio1 nr : 1
- [   16.454498] name : i2c0 nr : 0

**Comment by kittenarmy** [comment]
Got it working. problem was rtspserver.conf.dist specifies 8554 and I was expecting default port 554.

**Comment by wnleo** [comment]
Sama persis dengan apa yang saya alami, adakah yang bisa membantu mengatasinya
