### ISSUE TITLE
Hack still available for new cam ?

### ISSUE THREAD

**Issue by pimoon** [EliasKotlyar/Xiaomi-Dafang-Hacks#959]
Hello,

I want to buy a cam Xiaomi Xiaofang which will come with T20L chip and obviously the latest Xiaomi firmware.
Link here : https://www.aliexpress.com/item/Xiaomi-Mijia-Xiaofang-Dafang-Smart-Camera-1S-1080P-New-Version-T20L-Chip-WiFi-Digital-Zoom-APP/1000005724812.html?spm=2114.search0604.3.16.3e07277eaTwaoR&ws_ab_test=searchweb0_0,searchweb201602_6_10065_10068_319_10892_317_10696_10084_453_454_10083_10618_10304_10307_10820_10821_537_10302_536_10902_10843_10059_10884_10887_321_322_10103,searchweb201603_16,ppcSwitch_0&algo_expid=fa22361c-a323-4ca6-a828-1565543937f2-2&algo_pvid=fa22361c-a323-4ca6-a828-1565543937f2

I want to know if the hack is still working with the latest firmware ?

**Comment by dsbaars** [comment]
I bought the exact same one, from the same seller who shipped it on December 9th.
The hack is working, but it is very unstable. Even with lower resolutions, the camera freezes after watching 10 seconds of the H.264 RTSP stream, which makes it unusable.

I also tried installation of the [open source camera firmware and ext3 filesystem](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/hacks/install_sdcard.md). The ext3 filesystem seems to be behind the squashfs based one though. I did get it to boot, but couldn't get the image sensor to work.

My guess is that this is because it has only 64MB RAM. 

Because of these problems I bought the Dafang as well, which works great with this firmware: https://www.aliexpress.com/item/Xiaomi-Mijia-Xiaofang-Dafang-Smart-IP-Camera-1080-p-FHD-110-Graden-Intelligente-Beveiliging-WIFI-netwerk/32960335681.html?

**Comment by pimoon** [comment]
when did you buy it ?
will the latest firmware works with this Dafang ? (your last link)

thanks

**Comment by dsbaars** [comment]
The Xiaofang 1s was bought on December 8th 2018 (so does work, but unstable), the Dafang was bought on December 17th 2018 and does work with the latest firmware and is stable.

**Comment by pimoon** [comment]
can you tell me what is the firmware version on your xiaofang ?

**Comment by dsbaars** [comment]
Right now it's the CFW xiaofang1s_64mb_v2.bin from https://github.com/Dafang-Hacks/uboot/tree/master/compiled_bootloader with md5 1b3fcafab119afd36bf4270c1d3c4da1

I don't know what the originally installed firmware version was since I flashed CFW right away.

**Comment by x23piracy** [comment]
@dsbaars interesting i also bought a S1 and i am playing around with the settings but i cannot get a smooth stream working, the rtsp server crashes when i try to long. i extra started with the cheaper S1 one for playing around with it.

**Comment by cmlosncz** [comment]
Damnit...  I just received this model   https://www.aliexpress.com/item/Original-Xiaomi-CCTV-Mijia-Xiaofang-110-Degree-F2-0-8X-1080P-Digital-Zoom-Smart-Camera-IP/32884030076.html?spm=a2g0s.9042311.0.0.62754c4dBw2HtO 
Has FW 5.6.2.77 and MAC 34:xx:... any feedback on this ..?? I suppose it is like the S1 model then...

**Comment by kittenarmy** [comment]
I have two 1S and both came with 5.6.2.77, T20 processor, 64 MB memory. Production date are 2018.09 and 2019.01. I couldn't find any information regarding T20L over regular T20.

@cmlosncz try https://github.com/samtap/fang-hacks

**Comment by x23piracy** [comment]
@kittenarmy i am confused how much forks are existing from dafang hacks and which one is the best? i've read about a watchdog in the other project that is restarting the rtsp when it's broken, afai can see this project doesn't use the watchdog, is there a reason?


Regards X23

**Comment by kittenarmy** [comment]
The older Xiaofang camera has ARM processor, the newer 1S has a specialised T20 processor. They are not compatible, and the older Xiaofang is not truly 1080p as sometimes advertised (also I find mine runs quite warm even with added heatsink).

**Comment by cmlosncz** [comment]
Turn out this camera from the link given before is the S1 model too it is it is written below at the bottom 
I have the opportunity to sold it and maybe to buy the Dafang  
@dsbaars any advice..??

**Comment by pimoon** [comment]
I just bought another camera for $15 which should work with a hack : https://github.com/miicam/MiiCam

**Comment by DavidFFerreira** [comment]
it still not avaliable tor xiaofang t20l :(
