### ISSUE TITLE
OSD in webfrontend

### ISSUE THREAD

**Issue by Tschipel** [EliasKotlyar/Xiaomi-Dafang-Hacks#96]
When changing the OSD text it will be shown in the stream correctly, but in the web fronend there will be displayed 'DafangHacks_%H:%M:%S_%d.%m.%Y' after the successful set instead the changed format.

**Comment by shinebar1001** [comment]
Confirmed. The OSD has to be adapted to the new setconf - probably on friday

**Comment by Pharizna** [comment]
Now OSD doesn't run properly as previously :(

I'd like to have it DOWN but it always appears up and... it didn't remember my selection: I'd like to delete DafanHacks... but it always apperar the default format :(

**Comment by shinebar1001** [comment]
The OSD can be configured through web front end again: 2c68304be7a4ddec6f42eaa17f1007543b89c0cd
at the moment setconf doesn't pass the direction to v4l2rtspserver, so the Up / Down thing is commented out for now.
