### ISSUE TITLE
Update v4l2rtspserver-master to allow for better RTSP compatibility when enabling HLS with -S

### ISSUE THREAD

**Issue by aartrost** [EliasKotlyar/Xiaomi-Dafang-Hacks#962]
Hi all.

I'm trying to get the HLS stream working whilst not breaking RTSP compatibility with Motion. It looks like a few months ago v4l2rtspserver received an update that should fix this (if I understand correctly). See https://github.com/mpromonet/v4l2rtspserver/commit/df5215a75fa502001cb48b212a44ea75da230bbe & https://github.com/mpromonet/v4l2rtspserver/issues/117 for more details. 

It looks like https://github.com/EliasKotlyar/Xiaomi-Dafang-Software/tree/master/v4l2rtspserver-master is quite old and does not have this patch. Is it possible to get the latest build of v4l2rtspserver so we can use both HLS & RTSP? I would do this myself but I remember reluctance to accept binary pull requests from non-verified contributors.

Thanks in advance!

**Comment by jmtatsch** [comment]
Our fork is quite modified. If you’re willing to rebase those that would be great.

**Comment by aartrost** [comment]
> Our fork is quite modified. If you’re willing to rebase those that would be great.

Gotcha, I'll make an attempt!

**Comment by aartrost** [comment]
Hey @jmtatsch,

I've been able to successfully integrate the changes from https://github.com/mpromonet/v4l2rtspserver/commit/df5215a75fa502001cb48b212a44ea75da230bbe into the https://github.com/Dafang-Hacks/Main repo on my local machine. RTSP and HLS both seem to work concurrently and have been running stable for an hour or 12 on one of my cameras. 

However a bunch of configuration stuff has been changed see (https://github.com/Dafang-Hacks/Main/commit/8c13703fb15d30c9a0a7944bf54762eefa76c0ab#diff-0093f7fa952cafad76f41c6c9a56aa48L342) and most of the v4l2rtsp config seems to have moved to an .ini file which the web dashboard settings panel doesn't read/write to. Not sure how to proceed from here. Should I just create a pull request with the changes to v4l2rtspserver-master while you guys work on the settings?

**Comment by jmtatsch** [comment]
So you mean v4l2rtspserver-master wouldn't take any more command line parameters? Do the motion detection parameters still work?

**Comment by aartrost** [comment]
Yeah correct, config for that is now contained in this ini file https://github.com/Dafang-Hacks/Main/blob/master/v4l2rtspserver-master/v4l2rtspserver-master.ini. 

I'm not sure if the motion detection still works, it looks disabled in that .ini file. I've never used motion in-camera as I just use the cameras as an RTSP device for a central NAS that runs Motion in a docker.

**Comment by jmtatsch** [comment]
That is strange because there is still documentation for the command line parameters on the original mprotonet repository. Did they readd these parameters?
The motion detection was always enabled/disabled via shared memory setconf -k m -v your_sensitivity, would you be so kind and see if it still works?

**Comment by aartrost** [comment]
Yeah, the removal of the command line params seems to be an effort to standardize configuration by @EliasKotlyar but looks like it's still a WIP. No more activity on that matter after Dec 4, 2018, so not sure if this is still something that's happening or not. 

Running `setconf -k m -v 3` runs fine and updates the web UI, but I'm not sure if the settings actually work, how would I verify that? Is the camera supposed to track motion by panning using its motors? If so I can test that out tonight when I'm back home. 

Also, the `/cgi-bin/currentpic.cgi` endpoint is broken, but I'm guessing this is just because I haven't compiled the imagemagick and jpegturbo libs properly or something.

**Comment by puddly** [comment]
@aartrost The SoC itself generates JPEGs so there's no need for those two libraries (IIRC, `jpegturbo` was included only because of a buffer issue with the original JPEG code that generated 2MB JPEGs instead of 100kb JPEGs). I haven't tried in a while but I think you need to properly set every config option (they're not documented):

```ini
[Hardware]
SensorName = jx22  ; your sensor might be a jx23
SensorAddr = 0x40

[Video]
Width = 1280
Height = 720
Fps = 25
Bitrate = 1000
EncoderMode = 2  ; 0 = FIXQP, 1 = CBR, 2 = VBR, 3 = SMART
                 ; actual encoder options are pulled from shared memory, I think

[Audio]
Enabled = false

[RTSP]
Port = 8554
Url = /unicast  ; might just be unicast, without the slash
Mode = 1  ; unused
```

As far as I can tell the code in the `master` branch is incomplete. The last usable commit seems to be [`a0cb97b720f309fa6a8fe941b85ad1a631d111e6` from from September 1](https://github.com/Dafang-Hacks/Main/commit/a0cb97b720f309fa6a8fe941b85ad1a631d111e6), which might be a better starting point if you actually want to test this stuff out.

**Comment by aartrost** [comment]
Hey, sorry for the late reply.

Yeah, I've been able to get things running by adding more options to the supplied .ini file. However the whole repo just seems to be in an unusable state. I can commit my changes that integrate this commit https://github.com/mpromonet/v4l2rtspserver/commit/df5215a75fa502001cb48b212a44ea75da230bbe to the master branch, and then hopefully that'll just get picked up whenever the repository is clean again. I'm no longer needing HLS so I'm in no rush whatsoever.

**Comment by jonwaland** [comment]
just a flag that those using Home assistant and a hacked camera will probably be pushing for HLS support from today...  https://rc--home-assistant-docs.netlify.com/components/stream/

**Comment by hanross2323** [comment]
So! Any success so far? I may be one of those hacked  Dafang owners using HA... ;)

**Comment by jonwaland** [comment]
TBH, I forgot about this - streaming works mostly fine - I have issues with the way HA does it, that currently causes a crash...

**Comment by hanross2323** [comment]
What I experience is some kind of delay in streaming. All working fine after a reboot, after a few hours stream shows old footage - that can be hours old and always the same images after some more hours.

**Comment by jonwaland** [comment]
I dont think Ive left a stream long enough to see that.

**Comment by aartrost** [comment]
Hey everybody. 

I do have a modified binary of the streaming server that can stream both HLS & H264 RTSP. It's been running stable on one of my cameras for a few weeks now, but it does break various web UI functionality, so use at your own risk. Here's a download link:
[v4l2rtspserver-master.zip](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/files/3233797/v4l2rtspserver-master.zip) to a zip file containing my custom built binary + a configuration ini file that'll let you configure your stream. Note that these settings cannot be managed through the UI anymore after using this binary.

**Comment by hanross2323** [comment]
Great job! It’s working flawlessly in my setup except for OSD that I still couldn’t make it show in footage... but it’s totally ok

Alex

**Comment by peterbarlow2000** [comment]
I'm using your binary (thank you for that :)) but still seeing a 1s+ lag. Has anyone managed to pin point the cause of this lag? I don't care about any other functionality. I just want RTSP streaming with no perceptible lag. As this is achieved in the native app I assume it can be done with RTSP. Has anyone achieved this yet?

**Comment by rafalefighter** [comment]
I started to use this modified binary and stream seems very smooth since then. I can stream to my zoneminder without any issues and quality is so far very good. Most of the web interface configuration broken though. can anyone post how we can make this modified binary work with motion detection + scripts?. I don't mind web configurator at all. Just only need to use the telegram when motion detection

**Comment by puddly** [comment]
@aartrost could you upload your modified source code somewhere?

**Comment by aartrost** [comment]
Hey @puddly, I committed my changes here: https://github.com/aartrost/Main/commit/6b00cddd51bdad7f4af5ae1849a29ea2e2e200ba

This is as far as I can take this binary. Currently https://github.com/Dafang-Hacks/Main is in a broken in-between state and that repo either needs to be reverted to a working version or the work in progress needs to be finalized.

**Comment by aartrost** [comment]
> I started to use this modified binary and stream seems very smooth since then. I can stream to my zoneminder without any issues and quality is so far very good. Most of the web interface configuration broken though. can anyone post how we can make this modified binary work with motion detection + scripts?. I don't mind web configurator at all. Just only need to use the telegram when motion detection

This binary should not offer any performance improvements over the original binary. You are probably seeing a performance improvement because I spent lots of time testing out what the best settings for the RTSP server are. I'd suggest reverting to the original binary so you have your web controls again, then use these video settings:

![Screen Shot 2019-06-26 at 10 26 42 AM](https://user-images.githubusercontent.com/1044015/60201427-1c5eb680-97fd-11e9-9151-cc4baa0eb9b5.png)
settings:

**Comment by Garulf** [comment]
Great work! Seeing a big improvement in video quality too. There seems to be less encoding artifacts.

Any way to get PCM audio working? or any audio for that matter...

**Comment by aartrost** [comment]
> Great work! Any way to get PCM audio working? or any audio for that matter...
> 
> I have tried enabling audio in the INI config

No Idea! I'm personally not using the audio stream so I've not looked into that.
