### ISSUE TITLE
Any update for readme or wiki about Telegram and motion detection on options?

### ISSUE THREAD

**Issue by ortegafernando** [EliasKotlyar/Xiaomi-Dafang-Hacks#965]
Hi, I have read script and config files.

I have found information about MQTT topic to control and to get status information, but I am not sure about:
1. telegram
2. options about motion detection. Image? Video (I read sometime ago about that video recording is not very stable, but may be with newer versions there is not problem with video). Send video to ftp? to mqtt? to email?

Hope your help, thanks a lot.

**Comment by x23piracy** [comment]
https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/968
