### ISSUE TITLE
Picture problems

### ISSUE THREAD

**Issue by Verxuls** [EliasKotlyar/Xiaomi-Dafang-Hacks#967]
Hi.
I have several problems with image quality:
https://youtu.be/ZrpiWEv9QTc
https://youtu.be/FUumPYX9igg

This happens both for rtsp, as in the mp4 saved in the microSD.
I tried several firmware versions.

Any idea what could be the cause?
Regards.

**Comment by kittenarmy** [comment]
I'd try reconnecting the flat camera ribbon cable, maybe clean it with IPA.

**Comment by x23piracy** [comment]
Hi,

it more looks like a mix from normal picture and ir-cut, try to disable ir-cut problem still there?


Regards X23
