### ISSUE TITLE
Telegram bot chatid i don't get it

### ISSUE THREAD

**Issue by x23piracy** [EliasKotlyar/Xiaomi-Dafang-Hacks#968]
Hi,

i created a new telegram bot and i have the token but i don't get it, how do i gain the chatid and what exact steps needs to be done to make it right, can someone help me please?

Regards X23

**Comment by asharijuang** [comment]
Chat id you can get from telegram api, from telegram app you can create group with your bot then call this api to get chat id(base on group/single chat)
```
https://api.telegram.org/bot[token]/getUpdates
```

expectation for telegram integration is:
<img width="494" alt="Screen Shot 2019-03-10 at 06 17 43" src="https://user-images.githubusercontent.com/3271668/54078576-edc7d900-42fc-11e9-9e23-2d6d36d3d6d9.png">

**Comment by x23piracy** [comment]
Hi,

thanks i found out how it's working.


Regards X23

**Comment by jmtatsch** [comment]
@x23piracy maybe you could contribute a short howto setup the telegram integration?

**Comment by x23piracy** [comment]
Hi,

sure:

- Search for @botfather in telegram
- Write /help to him, to see what he can offer
- Create a new bot with /newbot
- Botfather will present you the api key 
- Create a new Group and put the created bot inside
- Now writes something to the Group
- Open https://api.telegram.org/bot[token]/getUpdates in your browser and look for the chat id.

This started only working for me (Xiaofang 1S, afaik 32MB of RAM (less, less and less)) after i enabled SWAP in run.ssh, i currently only use a 64MB SWAP instead of the default of 256MB.

After that the camera started to send picture by telegram.


Regards X23

**Comment by jmtatsch** [comment]
Would you be so kind and make a PR towards the documentation?

**Comment by x23piracy** [comment]
@jmtatsch do you mean me? Sorry but whats a PR? :)

**Comment by jmtatsch** [comment]
Yes, PR means a pull request :)

**Comment by asharijuang** [comment]
in my case motion detect not triger sendphoto to telegram, don't know why.

@x23piracy just modify on /script/telegram-bot-daemon.sh
we can play sound, just for fun 😅

<img width="788" alt="Screen Shot 2019-03-11 at 19 52 53" src="https://user-images.githubusercontent.com/3271668/54125407-78acee80-4437-11e9-8156-e0f92b3c2ca6.png">

**Comment by grzegorz189** [comment]
![Zrzut ekranu (3)](https://user-images.githubusercontent.com/17804684/57062822-b274d580-6cc1-11e9-8f4c-433883f996f6.png)

I added some functions, I also added reboot this function works when I start restarting the cameras again and again, my question is how to remove / reboot functions from the memory of the camera to perform only once

**Comment by kszere** [comment]
I update to last git version files project.
I put auth api data to file.
Change SWAP size from 256 to 64.
From url api get id chat. Enable in panel slide motion telegram.
In chat i write /start, /mem and not work.

Can you wrote step to step how make this to work?

**Comment by wiredolphin** [comment]
Just for future reference and for user that could not get the ChatID with the mothods explained before, I was able to get it right with the following instructions:

Search for  **Botfather** user in Telegram
Write `/help` to him, to see what he can offer
Create a new bot with the `/newbot` command and provide the requested info
**@Botfather** will answer with the api key and some other helpful infos
Create a new Group and call it as you want (i.e.: **ipcamalarms**) and add the created bot
Now add also the **@getidsbo** user, he will anser with the chat object containing the userChatId

IMPORTANT: if any, also the minus "-" sign must be included at the `userChatId` field when setting up the `telegram.conf` file, for example:
`userChatId="-436522340"`

**Comment by meidyjordan** [comment]
Hi,
I have successfully flashed my Xiaofang S1 (64mb) camera. I have been able to use the telegram feature, but for the /videoalert feature it doesn't seem to work as it should. For features / textalerts and /imagealerts to function properly. Is there something I'm missing?
I have also activated Memory Swap.

**Comment by nemiro-TECH** [comment]
> in my case motion detect not triger sendphoto to telegram, don't know why.
> 
> @x23piracy just modify on /script/telegram-bot-daemon.sh
> we can play sound, just for fun 😅
> 
> <img alt="Screen Shot 2019-03-11 at 19 52 53" width="788" src="https://user-images.githubusercontent.com/3271668/54125407-78acee80-4437-11e9-8156-e0f92b3c2ca6.png">

This way worked for me.

But I am not been able to get response from camera with /mem /shot etc
