### ISSUE TITLE
GPIO for usage as doorbell (S1)?

### ISSUE THREAD

**Issue by x23piracy** [EliasKotlyar/Xiaomi-Dafang-Hacks#969]
Hi,

has the camera internally some gpio pins? I may would like to use it as doorbell (combined with telegram).

Regards X23

**Comment by jmtatsch** [comment]
What model? Try the light sensor or end stop sensors for newer dafangs which don't have these sensors anymore. Solder points should be available for them.

**Comment by x23piracy** [comment]
Hi,

the question is for the 1S camera.
Ok lets say i will find a free gpio how can i find out with a script that the gpio was connected to gnd for example? is there a need to poll it or can it simply trigger another script when the action accours?


Regards X23

**Comment by EliasKotlyar** [comment]
I havent seen any free pins when i opened up the xiaomi-devices. However there are a lot of them in the SannCe Devices. However i cannot tell you, if they can be used...

PS: Maybe you just buy a doorbell set from xiaomi? There is one available...

**Comment by x23piracy** [comment]
Hi,

thank you for the response, good to know i don't need to open mine ;)
Hm, i don't like the idea of the xiaomi door bell cloud stuff, i have a lot from xiaomi but 99% percent is offline.


Regards X23

**Comment by EliasKotlyar** [comment]
Here is a teardown of the Dafang, so you can see that there are no pins on the board(except the 3 pins which are for the serial connection:)
https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/information/teardown.md

>i don't like the idea of the xiaomi door bell cloud stuff
Me neither. I have ordered one anyway, just for having some fun with hacking it. Its a really nice device as far as i see. Hopefully it features a Ingenic Chipset :)

**Comment by x23piracy** [comment]
Hi,

is there a chat u are sticking around? I have the feeling you are the man to ask ;P


Regards X23

**Comment by EliasKotlyar** [comment]
Hello @x23piracy ,

I am available at https://gitter.im/Xiaomi-Dafang-Hacks/Lobby, if you want to talk...


Unfortunately, not. However you can find it here: 
https://www.youtube.com/watch?v=OOghPawyIms
