### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by nbourre** [EliasKotlyar/Xiaomi-Dafang-Hacks#97]
Hi,
I have just received my camera. I'm unable to see any rstp feed. I always get segmentation fault when trying the h264Snap.

I tried going to the script section, but I only get NOK. I rebooted after setting the auto start, nothing I can do.

![Screenshot](https://i.imgur.com/SihzR7G.png)

But So far so good.

**Comment by shinebar1001** [comment]
The scripts should be fixed in  72e5bb8290f12dfc42aaf551ce75a2eaabd25b09 
Please try to use /system/sdcard/bin/getimage as h264snaps only works when there is no rtsp-server running.
