### ISSUE TITLE
Will it also work with these cameras (pictures)?

### ISSUE THREAD

**Issue by x23piracy** [EliasKotlyar/Xiaomi-Dafang-Hacks#972]
![grafik](https://user-images.githubusercontent.com/772243/54088990-28b12780-4364-11e9-9907-c86992e41177.png)
xiaomi 180° 1080p hub camera

and or?

![grafik](https://user-images.githubusercontent.com/772243/54088998-3b2b6100-4364-11e9-91e5-92accf710b30.png)
xiaomi 360° 1080p camera

Is one of them T10/20?

Regards X23

**Comment by dashcamguy** [comment]
Very possible. Get it and let us know if it's got a T10/20.
