### ISSUE TITLE
2 Xiaofang 1S - Both crashing daily with no SSH available

### ISSUE THREAD

**Issue by danmed** [EliasKotlyar/Xiaomi-Dafang-Hacks#973]
I have 2 Xiaofang 1S runnnig the latest Dafang Hacks.. and to be honest, they are very unstable.

I'm having to reboot them daily.. what do i need to do to provide useful logs that might help diagnose this?

**Comment by x23piracy** [comment]
Hi,

are u using different sdcards in both?
is it just the rtsp server thats crashed but still running? try to just restart the rtsp if so.

I also have a 1S but mine only has the problem that the rtsp server is randomly stopping to work while the process still runs, afai can say that doesn't happen with fixedqp when using the stream over the home app, i was testing if i could get better stream quality but the rtsp is crashing always after some seconds.


Regards X23

**Comment by zeroflow** [comment]
I see a simmilar issue.

Sometimes just the rtsp server stops and can be restarted, but other times it simply stops responding over all known ports

Only for me, it happens in <1h timeframes

**Comment by x23piracy** [comment]
Hi,

i had the feeling this works better for me with enabled swap drive (run.ssh) and with fixedqp the stream with homekit doesnt break (i cannot say it never crashes but i have the feeling with fixedqp it works better) i mean fixedqp in the cameras webif video settings.

But i don't really like it the quality is bad with fixedqp but with vbr or such the rtsp crashes easily after watching the stream for only some seconds.


Regards X23

**Comment by danmed** [comment]
> Hi,
> 
> are u using different sdcards in both?
> is it just the rtsp server thats crashed but still running? try to just restart the rtsp if so.
> 
> I also have a 1S but mine only has the problem that the rtsp server is randomly stopping to work while the process still runs, afai can say that doesn't happen with fixedqp when using the stream over the home app, i was testing if i could get better stream quality but the rtsp is crashing always after some seconds.
> 
> Regards X23

They re both running on SD cards yeah

They are both crapping our completely.. no ping results.. i'm running MQTT on them both so i'm going to disable that and see if it improves..

I'm having to use the RTSP H264 Server as the MJPEG one i can't get a picture out of.

**Comment by kittenarmy** [comment]
Try changing the audio setting if you haven't already. Unfortunately the default mp3 16K in/44.1 out is too much I think for the 1S camera, to do good video and audio at once. I have set it to PCMU 8K in/8K out and the feed is more stable.

**Comment by danmed** [comment]
> Try changing the audio setting if you haven't already. Unfortunately the default mp3 16K in/44.1 out is too much I think for the 1S camera, to do good video and audio at once. I have set it to PCMU 8K in/8K out and the feed is more stable.

Thanks for the tip, i've done this now.. i also switched ti fixedqp but the quality really suffered especially in night mode.. So i've gone back to VBR, but with the MQTT stuff turned off and the audio changes, things seem pretty stable for now.

**Comment by giuarb** [comment]
I have a dafang and a xiofang, both bought in December 2018 from Aliexpress, both with the hack, Dafang works beside the crappy quality I get in zoneminder on RTSP regardless of settings.....
The xiaofang works for a random number of hours then stops! and needs a rebood

**Comment by duncanleo** [comment]
I'm also running 2 Xiaofang cameras, and one of them constantly exhibited weird behaviour (e.g. going unresponsive, RTSP crashing, etc). My setup has one camera plugged into the USB port of another for power. Whenever I connected the problematic camera to another USB power source, some of the weird behaviour would go away. I discovered that the USB power supply powering both was insufficient. I replaced the 5V 1A adapter I was using with one that supports up to 2.4A and it's running much better now. Not sure if you share the same power setup as me but hopefully this helps.

**Comment by danmed** [comment]
I have plugged in to a USB wart now, and it seems to be working better, though not 100%.. my biggest issue is that it doesn't reboot.. If i tell it to, it never comes back and needs a hard power reset.

**Comment by kittenarmy** [comment]
I find the 1S to consume about 280-310mA during RTSP stream (classic Xiaofang is more like 450-510mA). The stock Xiaomi power supply should be more than enough for two cameras.

**Comment by danmed** [comment]
I've ended up sticking mine on a smart plug and having nodered repower the switch when it doesn't respond to a ping anymore.. can't be bothered faffing with it any more

**Comment by LouiS22** [comment]
Had this issue before, make sure you never fiddle with timelapse settings! I've found it the hard way when inspected the sd card and had around 250 000(!) stills. Also, the above mentioned audio setting might do the trick (I don't need it at all, so disabled it).

**Comment by marciogranzotto** [comment]
I'm having exactly the same problem. Both my cameras became completely unresponsive on a daily basis. I keep upgrading the firmware but it never solves the issue.

**Comment by welcometopwn** [comment]
Same here, 1S keeps crashing and doesn't come back online. I don't use MQTT and Audio is set to off.

**Comment by rafalefighter** [comment]
same here. I set video 15fps, vbr, 2500kbps, turned off audio completely and kill the lighttpd process also. still crashing every 1 hour and become unresponsive, not usable at all. with my videos settings CPU not go more than 60% any time.

**Comment by aaamoeder** [comment]
same for me, hope someone finds a fix soon.. driving me nuts...

**Comment by Anonym-tsk** [comment]
+1

**Comment by marciogranzotto** [comment]
After I changed my Home Assistant instance from a RPi 3 to an Intel NUC, my cameras started working fine.
No idea what Home Assistant was doing with the RTSP streams, but that's what fixes it for me 🤷‍♂ 
It also may be a coincidence, but I'm using that setup for 2 months now.
