### ISSUE TITLE
Change permissions for saved snapshots and video files.

### ISSUE THREAD

**Issue by ddima75** [EliasKotlyar/Xiaomi-Dafang-Hacks#975]
Hi, 
I use automount to nfs, so like this...

mount -o nolock -t nfs 192.168.1.10:/nfs/cams /system/media/nas

But i can't read snapshots from my NAS, it have permissions 0600 with "nobody" user.

ls -l /system/media/nas
-rw-------    1 501      1000        162528 Mar 13 13:52 13-03-2019_13.52.49.jpg
-rw-------    1 501      1000        162790 Mar 13 13:53 13-03-2019_13.53.30.jpg
-rw-------    1 501      1000        161054 Mar 13 13:53 13-03-2019_13.53.52.jpg

My propose - make a litle change in /system/sdcard/scripts/detectionOn.sh

change from
	cp "$snapshot_tempfile" "$save_dir/${snapshot_filename}.jpg"
to
	chmod 0666 "$snapshot_tempfile"
        cp -p "$snapshot_tempfile" "$save_dir/${snapshot_filename}.jpg"

In result i have:
-rw-------    1 501      1000        162528 Mar 13 13:52 13-03-2019_13.52.49.jpg
-rw-------    1 501      1000        162790 Mar 13 13:53 13-03-2019_13.53.30.jpg
-rw-------    1 501      1000        161054 Mar 13 13:53 13-03-2019_13.53.52.jpg
-rw-rw-rw-    1 501      1000        162964 Mar 13 13:54 13-03-2019_13.54.29.jpg
-rw-rw-rw-    1 501      1000        160783 Mar 13 13:54 13-03-2019_13.54.39.jpg

In same case, make change from
	cp "$video_tempfile" "$save_video_dir/${snapshot_filename}.mp4"
to
	chmod 0666 "$video_tempfile"
        cp -p "$video_tempfile" "$save_video_dir/${snapshot_filename}.mp4"

BR
ddima75

**Comment by ddima75** [comment]
... or add new varable in motion.conf
save_snapshot_attr="0666"
save_video_attr="0666"

and use in /system/sdcard/scripts/detectionOn.sh:
...
chmod "$save_snapshot_attr" "$snapshot_tempfile"
cp -p "$video_tempfile" "$save_video_dir/${snapshot_filename}.mp4"
...
chmod "$save_video_attr" "$video_tempfile"
cp -p "$video_tempfile" "$save_video_dir/${snapshot_filename}.mp4"
...
BR
ddima75

**Comment by jmtatsch** [comment]
Isn’t there options on the nfs client side to deal with this?

**Comment by ddima75** [comment]
> 
> 
> Isn’t there options on the nfs client side to deal with this?

Upgrade server side to NFSv4 or later and use mapping nobody user in /etc/idmap.conf
in client side use
mount -o vers=4 -t nfs 192.168.1.10:/nfs/cams /system/media/nas
but...
mount: mounting 192.168.16.11:/nfs/cams on /system/media/nas failed: Protocol not supported

**Comment by jmtatsch** [comment]
Hmm, I would go with your first proposal. Please create a pull request for it.

**Comment by jmtatsch** [comment]
Thanks for helping out.

**Comment by ddima75** [comment]
Thanks for all!
