### ISSUE TITLE
configuring motion to take more pictures

### ISSUE THREAD

**Issue by fanaticsurf** [EliasKotlyar/Xiaomi-Dafang-Hacks#978]
As in #610 I also recognize 3-7 seconds delay in telegram pictures while motions are detected.
Is it possible to get more pictures taken and send to telegram?
For example every 1 oder 2 seconds?
When somebody walks fast through the surveillance area I sometimes only got on picture.

**Comment by dashcamguy** [comment]
Take a look at this:

https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/e656f061388513eee0c927815e4fe1e3f49750b7/firmware_mod/config/motion.conf.dist

And this:

https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/c7451624acb4bddbff2aaa7dfcb6238064bfef7c/firmware_mod/scripts/detectionOn.sh
