### ISSUE TITLE
Don't working Xiaofang 1S after change SD

### ISSUE THREAD

**Issue by Picnic89** [EliasKotlyar/Xiaomi-Dafang-Hacks#979]
People, who knows as anew burn SD card for 1S. The camera is stitched, everything worked, pulled out a flash drive for other purposes for a while, formatted, returned everything that was there, but the camera to wifi does not conect. Heard that the camera such as SD card parts special. How do I restore my card?

**Comment by dashcamguy** [comment]
My bet:
The wifi config file is probably incorrect in some way. Take a look at it.
