### ISSUE TITLE
List known Ingenic T10/T20 devices

### ISSUE THREAD

**Issue by stucki** [EliasKotlyar/Xiaomi-Dafang-Hacks#980]
This is a request for feedback.

### Description

The README mentions a list of devices that are known to be working with this project. It also mentions that "any other Ingenic T10/T20 device" is supported. Unfortuantely, I don't know how to find such devices.

It would be great if the documentation (or Wiki) can point to these known devices, as I'm looking for an outdoor camera but still haven't found one so far...

**Comment by dashcamguy** [comment]
Here's a start:

Hikvision Smart Wifi Cameras

Xiaomi Home Surveillance Cameras

Wyze Cam Home Surveillance Cameras

Siepem S6211-WR Home Surveillance Camera

ANPWOO Digoo BB-M2 Home Surveillance Camera

You can make a cheap piece of crap indoor camera waterpoof with hot glue or probably even super glue. Might not look fancy but it would work. You can muse on that idea. Anything that keeps the water outta the electronics.

**Comment by wnleo** [comment]
can anyone provide a hack link for xiaofang with ingenic TL20

**Comment by erew123** [comment]
From the looks of it, the Sannce I141HD should be possible as it has a TL20 chip. I may give it a go... Im just reading the instructions for now, but thought Id add this here, after I opened one up to take a look inside.

It also looks like it had 4 x holes for power/gnd/TX/RX programming.

![i141HDb](https://user-images.githubusercontent.com/35898566/79601983-9be9a900-80e1-11ea-9bbd-d283c6d6fd91.jpg)
![i141HDa](https://user-images.githubusercontent.com/35898566/79601987-9d1ad600-80e1-11ea-98a5-05385f1fa315.jpg)

**Comment by erew123** [comment]
Ive started work on the I141HD but Im stuck now, with a device thats booted to root access, however the filesystem is write only [link](https://github.com/Dafang-Hacks/uboot/issues/15) 

any help would be appreciated

**Comment by jmtatsch** [comment]
Did you make and install a custom fw for it?

**Comment by erew123** [comment]
@jmtatsch Hi... Ive not yet... thats where Im at now. If you look at my [post](https://github.com/Dafang-Hacks/uboot/issues/15)

Ive detailed where Ive gotten to (Photos, Backups, Boot process dump, Command line instructions, root password etc). 

Im now just at the stage of, what next.... which firmware should I try on this thing. If you have any suggestions/thoughts on this... Im happy to give it a go. If it gets bricked, it gets bricked.... but Id like to get it working if possible. 

Have you any thoughts?

**Comment by jmtatsch** [comment]
Never done the process myself.
I think the main idea is to make a custom firmware that already contains a sideloader for run.sh so when the file system is marked read only you still have something to easily sneak stuff in.

**Comment by erew123** [comment]
Thats about where I had gotten to in my head too!! :)

I was just a bit uncertain when it says "Download the CFW for your camera".... Best I can see, I just need to download one of these [custom bootloaders](https://github.com/Dafang-Hacks/uboot/tree/master/compiled_bootloader) and try them..... Was thinking to give the Wyzecam v2 a go as thats T20 based.

Ill give it a shot later and see what happens.

**Comment by jmtatsch** [comment]
Dont flash those bootloaders. Thats an unneccesary risk.

**Comment by jmtatsch** [comment]
With your root access, did you dump all these partitions?
Then proceed to build your cfw https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/hacks/howto_modfirmware.md

**Comment by jmtatsch** [comment]
You are following this https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/hacks/newdevices.md right?

**Comment by erew123** [comment]
@jmtatsch (thanks for your help with this)

So if I follow the [getting root access](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/hacks/getroot.md) guide and use either the 128MB or 64MB command, the device only partially boots and then reboots. 

If I modify the standard bootargs command to include **init=/bin/sh** and **rw** first, the partition it boots to does not become writable and the command prompt I get, is only available for about 60 seconds before the device automatically reboots (looks like there is some kind of watchdog timer).

However, I have the root username/password for the device, so I have dumped the standard Sannce partitions, of which there are 6 of them. Please see my dump commands [here](https://github.com/Dafang-Hacks/uboot/issues/15#issuecomment-615982801)

So I have 6 x files now, of the Sannce firmware/partitions.

From there, Im trying to follow those guides.... but I am getting lost in the process. Those links you sent are the guides I am following though (as best I can).

I guess in my mind Im stuck on a couple of questions:

1) Are the 6 x files Ive created what I should be doing something with now? and are those files ok, because I didnt use the dump commands for the 64 or the 128? 

2) Should I be dumping the files onto an SD card, putting it in the camera and running 

```
fatls mmc 0:1
fatload mmc 0:1 0x80600000 bootloader.bin
sf probe
sf update 0x80600000 0x0 0x40000
```
against the bootloader file Ive just created?

3) If I need to download a set of files on here, which ones should I try?

4) Something else?

As I say, Im a little lost with this, but kind of putting it together in my head, bit by bit.

**Comment by jmtatsch** [comment]
1) Yes, I think you will need to pack them to a custom firmware update.bin which can be flashed as an update. There shouldnt be a difference in commands for dumping 64/128mb versions. You did dump the original bootloader though?

2) Yes dump on a sdcard and then put those files somewhere save.
Use this howto https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/hacks/firmware-dump.md
Make sure you dump all that are listed with `cat /proc/mtd`
3) I dont think you need any files from here except the unpacking/packing script.

**Comment by jmtatsch** [comment]
Seems I am wrong.
Other Sannce cameras seemed to need a custom uboot and seem to only load the very outdated experimental dafang rootfs. I am sorry, you are on your own there.

**Comment by erew123** [comment]
@jmtatsch Thanks for your time and helping me with that! That at least helps me clear up a bit of confusion I had and a route to try/test. Ill maybe research a bit more and try a couple of things with bootloaders, to see if that works or bricks them. If I have any success, Ill be sure to post back

**Comment by jmtatsch** [comment]
If I were you I would flash that sannce bootloader and then boot openfang...

**Comment by BuffAzi** [comment]
360 Smart Camera or anything by this company I believe. https://www.amazon.com/360-Wireless-Security-Surveillance-Detection/dp/B0725JSSCN . I haven't installed the cfw on it yet I'm still waiting for my oscilloscope to come in the mail but it has a t20 chip. Ill update this if I can get it working

**Comment by mymeyer** [comment]
Hello, is there a hack for "AKASO P30" ? Maybe one of you knows something.

**Comment by rabikkk** [comment]
Hello, Wanscam HW0026 Can I embed a code snippet I want in it?

**Comment by mymeyer** [comment]
Hello yes you can do you need another info from me?

Cu...
MyMeyer ...

rabikkk <notifications@github.com> schrieb am Mo., 2. Nov. 2020, 15:02:

**Comment by kchatcha** [comment]
Can anyone give me an idea of this camera with chip T20? It is possible to hack with [https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks] 
I'm done with Neos Camera and Xiaomi Camera hacks. I'm not sure with this camera.
Can I used the same CFW with this one?
![14B1093D-1D90-488F-AD26-783634656916_1_105_c](https://user-images.githubusercontent.com/6255965/104128188-fefd2900-535d-11eb-9f5d-d3f86fad2adb.jpeg)
![A9A136C4-4ED1-4CE7-8EA3-CE616B8A28C1_1_105_c](https://user-images.githubusercontent.com/6255965/104128192-0290b000-535e-11eb-8e33-465c5bc5eaf9.jpeg)

**Comment by BiatuAutMiahn** [comment]
The Wyze Outdoor Camera is a T20, firmware executes sd_update/upgrade.sh before doing an actual update. I attempted to get it to connect to my router via the camera's /system/bin/wl command but I tried for hours to no avail if you guys need any information I have a full dump of the firmware

**Comment by febriyan1302** [comment]
> Here's a start:
> 
> Hikvision Smart Wifi Cameras
> 
> Xiaomi Home Surveillance Cameras
> 
> Wyze Cam Home Surveillance Cameras
> 
> Siepem S6211-WR Home Surveillance Camera
> 
> ANPWOO Digoo BB-M2 Home Surveillance Camera
> 
> You can make a cheap piece of crap indoor camera waterpoof with hot glue or probably even super glue. Might not look fancy but it would work. You can muse on that idea. Anything that keeps the water outta the electronics.

i just to make sure, this camera works ?

![PTZ-Pro-Xiaomi-Mijia-2K-3-Megapixel-360-Panorama-bluetooth4-2-Smart-IP-Camera-AI](https://user-images.githubusercontent.com/18423871/127563631-bc8b4f1c-9702-40db-ad9d-81b60833cc3f.jpeg)

https://www.mi.com/global/product/mi-360-home-security-camera-2k-pro/overview

anyone try CFW for this camera ?

**Comment by felipecrs** [comment]
Just wondering, is there any chance this could support T21 devices as well?

http://www.howellcam.com/product/38.html

**Comment by volkerm81** [comment]
> > Here's a start:
> > Hikvision Smart Wifi Cameras
> > Xiaomi Home Surveillance Cameras
> > Wyze Cam Home Surveillance Cameras
> > Siepem S6211-WR Home Surveillance Camera
> > ANPWOO Digoo BB-M2 Home Surveillance Camera
> > You can make a cheap piece of crap indoor camera waterpoof with hot glue or probably even super glue. Might not look fancy but it would work. You can muse on that idea. Anything that keeps the water outta the electronics.
> 
> i just to make sure, this camera works ?
> 
> ![PTZ-Pro-Xiaomi-Mijia-2K-3-Megapixel-360-Panorama-bluetooth4-2-Smart-IP-Camera-AI](https://user-images.githubusercontent.com/18423871/127563631-bc8b4f1c-9702-40db-ad9d-81b60833cc3f.jpeg)
> 
> https://www.mi.com/global/product/mi-360-home-security-camera-2k-pro/overview
> 
> anyone try CFW for this camera ?

Did you try this one? Does it work?

**Comment by volkerm81** [comment]
> Here's a start:
> 
> Hikvision Smart Wifi Cameras
> 
> Xiaomi Home Surveillance Cameras

It’s been a while - but did you test these camera models? Do they work with this firmware?

**Comment by brainstorm** [comment]
Another T10-based camera: https://github.com/OpenIPC/ipctool/issues/30

**Comment by 3DStreetFurniture** [comment]
Does Wyze cam v3 work?

**Comment by brainstorm** [comment]
> Does Wyze cam v3 work?

Yes: https://openipc.org/cameras/vendors/ingenic/socs/t31n

**Comment by Tectract** [comment]
Did anyone ever get the Wyze Outdoor Cam to work? Any further info on that?

**Comment by BiatuAutMiahn** [comment]
> @BiatuAutMiahn
> 
> > The Wyze Outdoor Camera is a T20, firmware executes sd_update/upgrade.sh before doing an actual update. I attempted to get it to connect to my router via the camera's /system/bin/wl command but I tried for hours to no avail if you guys need any information I have a full dump of the firmware
> 
> Hey, can you share a full dump of the firmware?

If your talking about the one that has a built in battery and needs a dedicated receiver...no. I couldn't get too far cause it doesn't have a normal wlan radio and I didnt want to take it apart. I ended up returning the unit.

**Comment by Tectract** [comment]
Yeah I was looking at putting together a little solar / battery / charge controller setup to power a couple of the regular Wyze V2 cams (not outdoor model) and it was around $80 for the system, thought I might save a little by upgrading to the "outdoor" model but I guess it's looking like I can spend the extra $20 or spend hours and hours of my life trying to get the "outdoor" cam working, lol.

**Comment by BiatuAutMiahn** [comment]
you know what they say...want something done do it yourself :P

**Comment by Tectract** [comment]
If you have to buy a base controller and also a seperate panel for each Wyze2 cam, and they have those tiny little batteries, who knows how old they are now... It's probably just as economical and you'll get a much better system that could support multiple cameras and maybe some lights, for about the same price, it seems. You can get a really good charge controller for like $16 and a 35Ah lithium phosphate battery for $20, and you can probably find some old solar panels up to get up to 30W for like, almost free.

**Comment by gitmnk** [comment]
Any chance there is support for Wyze  cam v3 Pro too ?

**Comment by BiatuAutMiahn** [comment]
> Any chance there is support for Wyze cam v3 Pro too ?

diff chip afaik
