### ISSUE TITLE
How to restore/change MAC address in original firmware (uboot.bin) Xiaofang 1S 

### ISSUE THREAD

**Issue by rah66** [EliasKotlyar/Xiaomi-Dafang-Hacks#982]
Hi all,
I restored firmware by this [method](https://github.com/Dafang-Hacks/spiflasher), using [dumps](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/tree/master/firmware_original/xiaofang).
After that, the MAC address of camera was changed, it was registered in uboot.bin
I suppose that precisely because of this, the camera periodically disappears from Mihome application, when someone registers a camera with the same address. 
Help me change the address to the original. I am not good at editors ... My original address is 78:11:DC:76:49:26. 
Now the camera has address 78:11:DC:70:43:C5
Thanks for the help.

**Comment by kielby** [comment]
Did you ever figure this out?
