### ISSUE TITLE
How it applies -s flag?

### ISSUE THREAD

**Issue by rabeliyo** [EliasKotlyar/Xiaomi-Dafang-Hacks#984]
Hi, I'm trying to play video by hls and I see that you have to execute "HLS & MPEG-DASH require the rtspserver to be started with the -S flag." but I do not know how or where to do it, can anyone help me?

Awesome hack, Thanks!!

**Comment by surenz** [comment]
Go to file /system/sdcard/controlscripts/rtsp-h264 and change like this:
/system/sdcard/bin/v4l2rtspserver-master **-S** $RTSPH264OPTS $AUDIOPARAM $VIDEOFORMAT $CREDENTIAL $PORT 2>> "$LOGPATH" >> "$LOGPATH" &


I think it will not survive an update from git.

**Comment by jakommo** [comment]
The persistent way to add this option is to edit `/system/sdcard/config/rtspserver.conf` and add it to `RTSPH264OPTS`. I.e. `RTSPH264OPTS="-S -W1280 -H720"`

**Comment by SilverWx** [comment]
> The persistent way to add this option is to edit `/system/sdcard/config/rtspserver.conf` and add it to `RTSPH264OPTS`. I.e. `RTSPH264OPTS="-S -W1280 -H720"`

doesn't work for me

**Comment by jneilliii** [comment]
I can confirm that this seems to be broken in the latest versions, including beta branch. It seems that @aartrost may have done some work to get it working earlier. Should we post a new issue/request @EliasKotlyar? After adding the above parameters mentioned by @jakommo, when attempting to access what should be the HLS stream at `http://dafang:8554/unicast.m3u8` in VLC it will not connect. Opening a test stream like https://multiplatform-f.akamaihd.net/i/multi/will/bunny/big_buck_bunny_,640x360_400,640x360_700,640x360_1000,950x540_1500,.f4v.csmil/master.m3u8 in VLC works fine.
