### ISSUE TITLE
Wifi Drivers

### ISSUE THREAD

**Issue by dashcamguy** [EliasKotlyar/Xiaomi-Dafang-Hacks#985]
I've got a brand new Wyzecam Pan and the wifi chip isn't being detected.

Haven't opened it up yet but I'm guessing there's a different wifi chip in there.

Having the most likely driver binaries readily available would be useful:

```
8189es.ko
8189fs.ko
mt7601Usta.ko
rtl8189ftv.ko
```

For awareness, these chips have their drivers installed like this:

```
MAC=$(grep MAC < /params/config/.product_config | cut -c16-27 | sed 's/\(..\)/\1:/g;s/:$//')
# dafang uses:
insmod /driver/8189es.ko rtw_initmac="$MAC"
# XiaoFang T20 uses:
insmod /driver/8189fs.ko rtw_initmac="$MAC"
# wyzecam v2 uses:
insmod /driver/rtl8189ftv.ko rtw_initmac="$MAC"
```

**Comment by jmtatsch** [comment]
I would guess so too. Either take it apart and identify the chip or buy another one and dump the fw before flashing a custom firmware.

**Comment by todrobbins** [comment]
@dashcamguy did you open it up or find another workaround?
