### ISSUE TITLE
Update cfw-1.1.bin for Wyve V2

### ISSUE THREAD

**Issue by mbevand** [EliasKotlyar/Xiaomi-Dafang-Hacks#986]
I've rebuilt wyvecam_v2/cfw-1.1.bin based on the latest official firmware (4.9.4.28) here:
https://github.com/mbevand/Xiaomi-Dafang-Hacks/commit/957b7ccfda5471e6770863fb071c7c3043e91e63

This provides a number of enhancements:

- First of all Xiaomi-Dafang-Hacks is in theory designed so that if the SD card containing firmware_mod is removed, the camera is supposed to boot the original firmware and be fully working with the Wyze app. Currently this is broken for the latest Wyve V2 cameras based on the jxf23 sensors. The current cfw-1.1.bin is built on a very old firmware (4.9.1.60) that doesn't
support jxf23. So users are left with a broken firmware.

- In 4.9.4.28 they removed the "/system/bin/singleBoadTest" binary which used to enable the SD card interface. I found by trial and error that the SD card interface can be enabled by writing 0 to GPIO43. This simplifies rcfile.sh somewhat.

- Finally, my changes also properly unmount /system/sdcard when the camera doesn't find run.sh when booting, so that it proceeds with booting the official 4.9.4.28 firmware without the SD card being mounted in two different locations.

I have also extracted the individual 4.9.4.28 binary blobs in https://github.com/mbevand/Xiaomi-Dafang-Hacks/commit/fb78faeb8da4fc264c4fa74aaa18ff908a97faac

Please let me know how you'd like to submit my changes to this repo.

**Comment by jmtatsch** [comment]
Great work, open two pull requests for the changes please.

**Comment by mttyptty** [comment]
Looking forward to flashing the rebuilt CFW! Thanks @mbevand and anyone else for figuring this out.

**Comment by mrlindstrom** [comment]
So I have one the old cfw flashed to two of my wyze cams and they indeed have the issue where if the sdcard is removed, they do not boot.  I'm trying to flash them with anything, the new cfw you provided, the latest official, the test rtsp firmware, and none of them want to flash.  The camera just sits idle until I put the sdcard with the dafang files back in it.  Do you know if the broken cfw would cause this?

**Comment by Tectron** [comment]
Id be interested to know as well, I'm in the same boat. Without the Dafang sd card inserted i essentially have a brick.

**Comment by FuzzyMistborn** [comment]
My cam boots without an SD card but it reverts to the latest firmware (4.9.4.37) no matter what i do in terms of trying to flash a different demo.bin file.

**Comment by mbevand** [comment]
Don't know how to create 2 independent pull requests are the changes are inter-dependent, but I broke down my work into multiple commits:
https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/pull/1041

**Comment by mbevand** [comment]
> Do you know if the broken cfw would cause this?

Flashing your Wyze camera once with a broken firmware (whether cfw or original) should not cause you camera to fail to flash, because the flashing mechanism is called very early, by the u-boot firmware, and neither the original fw nor cfw change the u-boot firmware, so they can't break it.

**Comment by jthomasdewald** [comment]
Thank you for this. Is there any reason this hasn't been pulled into master yet? Spent way too many hours trying various cfw's before finding this.

**Comment by jmtatsch** [comment]
No. Just too little time. Merged now. Still need to build the cfw though.

**Comment by NorthernMan54** [comment]
@jmtatsch 

I have been using the version linked here for a while now, and it works great.  Can we get this officially published?

**Comment by stephenjamieson** [comment]
I'm having the same issue as others here... Can't flash a new demo.bin.  Not sure what I need to do to get to this version?

**Comment by stephenjamieson** [comment]
Ok, so the uboot that I flashed that's in the original firmware directory in this github didn't allow for the demo.bin to be loaded, but I flashed with a newer bootloader from a camera I had telnet access to.  The new bootloader seems to have done the trick.
