### ISSUE TITLE
Working example of Wyze Cam Pan running dafang cfw-1.3 functioning as a wifi access point using hostapd

### ISSUE THREAD

**Issue by dashcamguy** [EliasKotlyar/Xiaomi-Dafang-Hacks#987]
Anybody else want their cam to be able to function as a wifi access point?

[This](https://github.com/dashcamguy/Xiaomi-Dafang-as-Wifi-Access-Point) does that.

I'm totally cool with this functionality to be added to this repo.

Can possibly add an option for switching between "wifi client" and "wifi access point" mode.

I can do that myself, but it's Sunday and right now feels like time to do absolutely nothing for a while.

**Comment by chaveiro** [comment]
Very nice, why dont you submit a pull request yourself to Xiaomi-Dafang-Hacks?
