### ISSUE TITLE
Xiaofang 1S latest firmware March 2019

### ISSUE THREAD

**Issue by alinelena** [EliasKotlyar/Xiaomi-Dafang-Hacks#988]
* exact camera hardware:
Xiaofang 1s 64MB  latest firmware March 2019
### Description
I have applied the method to install the cfw and all was fine. One thing i noticed sd card needs to have a dos partition table. 
I have managed to run the latest stack of hacks.

Issues:
- video is very choppy even at low and very low resolutions
- relatively high load by the streaming sensor 25% on mine.
- camera still works with the original firmware, after sd card is removed but pairing is a pain.
- no clear way of restoring the original, firmware. this will be useful 

I am more than happy to contribute any log, serial logs if needed. just ask.

**Comment by kittenarmy** [comment]
What is the firmware version you have? I have 5.6.2.77 on my 1S cameras. Serial log should show it.

**Comment by chaveiro** [comment]
I confirm there is an issue with the CFW for xiaofang latest firmwares.
Updated to 5.6.2.138 then applied xiaofang cfw loader. 
After that the original app (sd card removed) gets many disconnects or moments of 'connecting 1/3' frezzing just there many time on a day.
When this happens camera responds to ping but i cant use camera settings from the original app, it says not connected, but the general settings option gives the correct wifi information from the camera.
I reverted to stock firmware using an old image and after updating to 5.6.2.138 from the app and everything is stable, so it's not an hardware issue.
Something seems to be messing up stock app usage just by installing the only available xiafang CFW to a 5.6.2.138 firmware.
Should the CFW need to be updated for xiaofang firmwares after Q1 2019?

**Comment by welcometopwn** [comment]
I've noticed that as well.. 
Would love to know how to restore the original firmware, i can't pair my Camera if i remove the SD Card.

**Comment by brownpride3282** [comment]
i have xiaofang in the philippines.i cannot view camera here in macau..what can be the problem?help pls

**Comment by andyjusuf** [comment]
Hi @chaveiro, my issue looks very similar to the one you described above. I have a Xiaomi Xiaofang 1S camera, which has the CFW flashed. Last week I removed the SD card and set up my camera using Mi Home app and I updated the firmware to v 5.6.2.138. I wasn't aware that it is not compatible with the CFW. Since then the camera randomly disconnected as you experienced. The only way to get it back is to power cycle the camera . It's getting a bit much to reboot the camera many times in a day. I was thinking to restore the camera using the older firmware version, but I haven't found a way to do it yet. 

You said in your post that you reverted to stock firmware using an old image. Do you mind sharing with me where I could download the firmware image you used and the procedure to revert the existing firmware? Thanks.

**Comment by andyjusuf** [comment]
Hi again, I managed to pack the firmware version 5.6.2.182, found in the firmware_original folder and flashed it on to my Xiaofang camera.

**Comment by chaveiro** [comment]
I downgrate to 5.6.2.45 and then updated trough the app.
Found firmware at this link: https://en.miui.com/thread-5096189-1-1.html

**Comment by farrokh19** [comment]
> Hi again, I managed to pack the firmware version 5.6.2.182, found in the firmware_original folder and flashed it on to my Xiaofang camera.

Hi, could you send me the packed 5.6.2.182 please. My Xiaofang 1s with MAC starting with 34 was working well before I stupidly did the update to 5.6.2.197. Thanks a lot

**Comment by andyjusuf** [comment]
My Xiaofang 1S MAC address starts with 78. I don't know what the differences are between devices with MAC address starting 34 and 78. If you want to take a risk and flash the firmware version 5.6.2.182, let me know where to send the firmware. No guarantee that the firmware will work with you Xiaofang camera.

**Comment by farrokh19** [comment]
> My Xiaofang 1S MAC address starts with 78. I don't know what the differences are between devices with MAC address starting 34 and 78. If you want to take a risk and flash the firmware version 5.6.2.182, let me know where to send the firmware. No guarantee that the firmware will work with you Xiaofang camera.

I'll try to find more info about it. I remember someone saying that 34 is arm while 78 is t20, but actually I can't find any distinction on github regarding that. Could please send it to me anyway? Just drug it here, thanks

**Comment by farrokh19** [comment]
Ok I've done it. I flashed the firmware 5.6.2.45 that I found already packed online. Then I updated to .138 and now it's working well. It's still suggesting me the .197 update obviously...

**Comment by chaveiro** [comment]
I'm on 5.6.2.182 stock now and working well. 
What problem did you guys get with .197 and were you stock or had previous installed CFW?

**Comment by farrokh19** [comment]
I was on stock and updated to .197 and got the screen with the regional restriction (only Mainland China bla bla...) even if I always set China as server.

**Comment by chaveiro** [comment]
Thanks, how did you update to 5.6.2.138, can you share the image?

**Comment by farrokh19** [comment]
> Thanks, how did you update to 5.6.2.138, can you share the image?

I got the same screen reported in the OP of this discussion https://c.mi.com/thread-2174105-1-1.html
I just updated from the settings of the camera in the mi home app. It doesn't go directly to .197, because the app offers you the update to .138 first

**Comment by alinelena** [comment]
would be nice and probably useful is someone published the workflow for restoring the firmware

1. how the firmware was extracted or where from downloaded, with the caveats.

2. how was flashed?
sd card, header?, link pictures.

**Comment by farrokh19** [comment]
This is what I did for a xiaofang 1s with mac starting with 34, but should work with mac 78 too:
- I canceled the camera from the mi home app.
- Downloaded the file from here https://en.miui.com/thread-5096189-1-1.html in the OP (it's the 5.6.2.45 and has to be named demo.bin) without extracting or anything
- Copied in a new 32 gb micro sd card (smaller should work, bigger require creating a small partition sometimes). If not new, it has to be formatted in FAT32
- Inserted the card in the camera while it is off, 
- Pushed and held the setup button while plugging the camera
- After about 10-15 seconds holding, the light turned blue
- I stopped pressing the setup button and waited for a flashing yellow light
- The firmware is now flashed; you can press for a few seconds the setup button to start the coupling process as usual
- After that I updated the firmware to the .138 from the mi home app, which is still now suggesting me to update to .197
Sorry but I don't have pictures right now

**Comment by a20691** [comment]
It worked for me now. it was necessary to do some resets on the camera before being able to update to .138 but after a few tries it works perfectly.

**Comment by alinelena** [comment]
I do not seem able to download the firmware, link is giving a 403. I will need to see how one can make the demo.bin from dumps


---Dr Alin Marin Elenahttp://alin.elena.space

 ---- On Mon, 03 Jun 2019 21:53:01 +0000 a20691 <notifications@github.com> wrote ----

**Comment by a20691** [comment]
Try from here

https://mega.nz/#!ZyAAmK4B!PI94xgaRWEtVGHvHbgBcC4rDcS0sbAPd991WlQnbMuY

I'm new to this forum I hope I'm not breaking any rules.


________________________________
De: Alin Marin Elena <notifications@github.com>
Enviado: Monday, June 3, 2019 10:55:09 PM
Para: EliasKotlyar/Xiaomi-Dafang-Hacks
Cc: a20691; Comment
Assunto: Re: [EliasKotlyar/Xiaomi-Dafang-Hacks] Xiaofang 1S latest firmware March 2019 (#988)

I do not seem able to download the firmware, link is giving a 403. I will need to see how one can make the demo.bin from dumps


---Dr Alin Marin Elenahttp://alin.elena.space

---- On Mon, 03 Jun 2019 21:53:01 +0000 a20691 <notifications@github.com> wrote ----

**Comment by alinelena** [comment]
ok... if the link does not work or you do not want to download the firmware from the link you can generate the demo.bin by yourself.

on a linux system, clone the repo

go into original firmware

cp ../../../hacks/firmware/packer.py .
cd firmware_original/xiaofang/5.6.2.182/

edit packer.py outfile to match the firmware version
run it

./packer.py

all good you shall have a demo_5.6.2.182.bin
rename it on a sd card to demo.bin as described above. 
things seem to work. this was on a 78:



---Dr Alin Marin Elenahttp://alin.elena.space

 ---- On Mon, 03 Jun 2019 21:53:01 +0000 a20691 <notifications@github.com> wrote ----

**Comment by alinelena** [comment]
Thanks @a20691. just built my own, instructions posted. let us hope one will consolidate everything and help others too.

Alin


---Dr Alin Marin Elenahttp://alin.elena.space

 ---- On Mon, 03 Jun 2019 22:10:28 +0000 a20691 <notifications@github.com> wrote ----

**Comment by johnnyt83** [comment]
I just downgraded my camera, but unfortunately it automatically updates to the blocked china version. how to prevent this?

**Comment by a20691** [comment]
Here it continues in the same version and does not update automatically. And none of the products I have in the application do firmware update automatically.

**Comment by jmtatsch** [comment]
Close in favour of #1128
