### ISSUE TITLE
Enhancement: MQTT LWT topic

### ISSUE THREAD

**Issue by pplucky** [EliasKotlyar/Xiaomi-Dafang-Hacks#99]
@shinebar1001 Would it be feasible to add an MQTT [LWT](https://www.hivemq.com/blog/mqtt-essentials-part-9-last-will-and-testament) topic to the camera?

This would be useful to quickly know if the camera is available on the network or not.

Thanks in advance.

**Comment by shinebar1001** [comment]
No problem, as mosquitto_sub is used that is quite easy. I'll commit an updated version which makes use of the config file (apparently only the mqtt.dist ist updated)
