### ISSUE TITLE
Command doesn`t exist when motion is detected with Xiaofang 1s

### ISSUE THREAD

**Issue by goermezer** [EliasKotlyar/Xiaomi-Dafang-Hacks#990]
I got a new Xiaofang 1s, which I ordered here: https://de.aliexpress.com/item/Xiaomi-Mijia-Xiaofang-Dafang-Smart-Kamera-1-S-1080-P-Neue-Version-T20L-Chip-WiFi-Digital/1000005724812.html?spm=a2g0s.9042311.0.0.3da24c4dwyGoDp
After flashing it with V2 of the 64 MB uboot, everything seem to work like expected, except the motion detection:

```
2019-03-26 11:39:10.972 (   3.439s) [DeviceSource    ]       DeviceSource.cpp:91       0| begin thread
2019-03-26 11:39:16.763 (   9.230s) [ivsMoveDetection]         ImpEncoder.cpp:419      0| command  does not exist

2019-03-26 11:39:16.764 (   9.230s) [ivsMoveDetection]         ImpEncoder.cpp:599      0| Detect !!
2019-03-26 11:39:18.805 (  11.271s) [ivsMoveDetection]         ImpEncoder.cpp:419      0| command  does not exist
```

I have no customizations so far. Even with a swap file the motion detection scripts are not executed. There is no more output than "Command doesn`t exist".

Bytheway Aliexpress advertises this camera as a new version with faster processor (1GHz). But the label on the bottom of the cam is nearly identical to my other Xiaofang. I assume this is the same 1S-model right?

![IMG_0250](https://user-images.githubusercontent.com/19188171/54992872-bb86ce80-4fc0-11e9-9142-bb7a2ceb7c16.jpg)

**Comment by jmtatsch** [comment]
It should try to run DetectionOn.sh there. Can you try to run that script manually?

**Comment by goermezer** [comment]
Yes, executing detectionOn.sh in the shell wors and sends the MQTT message out.

**Comment by janvotava** [comment]
Hi, I'm getting an error:

```
2019-03-27 11:52:08.675 (   5.496s) [ivsMoveDetection]         ImpEncoder.cpp:407      0| Execute /system/sdcard/scripts/detectionOn.sh returned:-1
2019-03-27 11:52:08.675 (   5.496s) [ivsMoveDetection]         ImpEncoder.cpp:599      0| Detect !!
```

When trying to run it manually, it works as expected.

**Comment by goermezer** [comment]
@jmtatsch  It seems, that this camera has a jxf23 sensor. I copied the file sensor_jxf23.ko from the newest original firmware into /system/sdcard/driver. That didn`t help with motion detection. But it seems, that this driver is a bit better regarding the cseq5 expected-error, which I always have when I record with ffmpeg in tcp transport mode. Will take the new driver into a long term test now...

**Comment by pvklink** [comment]
Hi i also bought a new 1s.
i enabled motiondetection and 
added a bashscript to system/sdcard/config/userscripts/motiondetection

#!/bin/sh

if [ "$1" == "on" ]; then

    source /system/sdcard/config/motion.conf
    source /system/sdcard/scripts/common_functions.sh

    curl 'http://192.168.20.32:82/json.htm?type=command&param=switchlight&idx=1226&switchcmd=On'

    # Check external service to see it anyone present.
    # presence=$(/system/sdcard/bin/curl http://openhab/rest/items/PresenceAtHome/state 2>/dev/null)
    #if [ "$presence" == "OFF" ] ; then
        # No-one is meant to be here, but motion detected. Send email.
        # /system/sdcard/scripts/sendPictureMail.sh &
    #fi

elif [ "$1" == "off" ]; then

    curl 'http://192.168.20.32:82/json.htm?type=command&param=switchlight&idx=1226&switchcmd=Off'

fi

but nothing works!

Anybody an idea?

**Comment by goermezer** [comment]
I made a fresh reinstall today and now the error "command doesn`t exist" doesn`t occur anymore. Something may be fixed it...

**Comment by chrisdaloa** [comment]
Same issue on the same camera. Motion detection works (I see the colored indicator on the video) but no mqtt topic is published.
